### PR TITLE
crypto: Use secure_allocator for `AES256_ctx`

### LINKED ISSUE #31744: crypto: secure erase memory
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

In `AES256Encrypt::~AES256Encrypt()`: 
https://github.com/bitcoin/bitcoin/blob/master/src/crypto/aes.cpp#L20
and `AES256Decrypt::~AES256Decrypt()`:
https://github.com/bitcoin/bitcoin/blob/master/src/crypto/aes.cpp#L35

`memset` is used to reset the `ctx` and `key`, this is not secure and can be optimized out by the compiler: 

https://www.cryptologie.net/article/419/zeroing-memory-compiler-optimizations-and-memset_s/

Instead use secure erase primitives such as  `OPENSSL_cleanse`:
https://github.com/openssl/openssl/blob/master/crypto/mem_clr.c

### Expected behaviour

`memset` should be avoided  to reset the `ctx` and `key`,

### Steps to reproduce

NA

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master

### Operating system and version

Linux

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by davidgumberg**
Fixes #31744 

Reuse `secure_allocator` for `AES256_ctx` in the aes 256 encrypters and decrypters and the `iv` of `AES256CBC` encrypters and decrypters. These classes are relevant to `CCrypter`, used for encrypting wallets, and my understanding is that if an attacker knows some or all of the contents of these data structures (`AES256_ctx` & `iv`) they might be able to decrypt a user's wallet.

 Presently the `secure_allocator` tries to protect sensitive data with `mlock()` on POSIX systems and `VirtualLock()` on Windows to prevent memory being paged to disk, and by zero'ing out memory contents on deallocation with `memory_cleanse()` which is similar to `OPENSSL_cleanse()` by scaring compilers away from optimizing `memset` calls on non-Windows systems, and using `SecureZeroMemory()` on Windows.

### CODE REVIEW

**Comment by davidgumberg** [comment]
> I'm wondering if a minimum-diff fix which simply replaces the `memset` calls in the dtors with `memory_cleanse` would be largely sufficient here? In [#31166 (comment)](https://github.com/bitcoin/bitcoin/pull/31166#issuecomment-2446055905) one argument for not needing secure allocators was the short-lived nature of the secrets. 

It seems right to me that this structure is always short lived, but I also felt in #31166 `secure_allocator` should have been used over just `memory_cleanse()`. I feel that the alloc/dealloc strategy for secrets in memory should be reused and applied universally unless there is a good reason not to.

----

> I think the approach here might have an unacceptable performance impact, as it is allocating and deallocating a secure area for every individual key being encrypted/decrypted.

I added a benchmark for `WalletEncrypt()` which I ran a few times and it appears that the performance impact is neglible on my machine (Ryzen 7900x, Fedora 40),  if the benchmark I wrote is actually representative:

| wallet type | branch                                                                                         | EncryptWallet() (ns/key) | benchmark overhead (ns/key)  | normalized value (total - overhead) |                                                                         flamegraph |
|-------------|------------------------------------------------------------------------------------------------|--------------------------|------------------------------|-------------------------------------|-----------------------------------------------------------------------------------:|
| Descriptor  | https://github.com/bitcoin/bitcoin/pull/31774/commits/15d8500f99012422be495b8e85e4e25e6a4419d8 | 42,106.55                | 36,235.03                    | 5,871.53                            | [link](https://davidgumberg.github.io/fg/aes-secure-alloc/branch-descriptors.html) |
| Descriptor  | master                                                                                         | 42,050.82                | 36,362.40                    | 5,688.42                            | [link](https://davidgumberg.github.io/fg/aes-secure-alloc/master-descriptors.html) |
| Legacy      | https://github.com/bitcoin/bitcoin/pull/31774/commits/15d8500f99012422be495b8e85e4e25e6a4419d8 |  17,067.82               | 2,779.16                     | 14,288.6                            | [link](https://davidgumberg.github.io/fg/aes-secure-alloc/branch-legacy.html)      |
| Legacy      | master                                                                                         | 16,812.63                | 2,757.26                     | 14,055.57                           | [link](https://davidgumberg.github.io/fg/aes-secure-alloc/master-legacy.html)      |

---


But if the short-lived nature of the key material makes just using `memory_cleanse()` a good-enough solution over having to reason about whether or not the benchmark is sufficiently correct, and whether or not the larger diff required in order to reuse `secure_allocator` is worth the risk, I'm happy to change it.

**Comment by laanwj** [comment]
> I think the approach here might have an unacceptable performance impact, as it is allocating and deallocating a secure area for every individual key being encrypted/decrypted.

This may still be true, though FWIW the idea behind the `LockedPool` is that it reduces the amount of locking/unlocking operations by mapping and locking memory in blocks, not every time it's requested.

**Comment by davidgumberg** [comment]
Rebased to address merge conflict.

**Comment by davidgumberg** [comment]
Rebased to address merge conflict, dropped legacy wallet encryption benchmark, and reduced number of keys since the benchmark was taking an unreasonably long time.

**Review by sipa — COMMENTED** [review]
utACK 591764f6170d6f74d7eebb5fec1cbf5b912098a4, just coding style nits

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -578,21 +578,26 @@ void CWallet::UpgradeDescriptorCache()
...
     constexpr MillisecondsDouble target{100};
     auto start{SteadyClock::now()};
     CCrypter crypter;
 
-    crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
-    master_key.nDeriveIterations = static_cast<unsigned int>(master_key.nDeriveIterations * target / (SteadyClock::now() - start));
+    if (force_iterations.has_value()) {
+        master_key.nDeriveIterations = force_iterations.value();
+    }
+    else {
```
[the remark this answers is not in the document]
Comment (davidgumberg) [reply src/wallet/wallet.cpp]: Thanks, fixed.

File: src/bench/wallet_encrypt.cpp [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    bench.batch(key_count).unit("key").run([&] {
+        wallet = TestLoadWallet(std::move(database), context, create_flags);
+        wallet->m_testonly_encrypt_iterations = 25'000;
+
+        // Save a copy of the db before encrypting
+        database = DuplicateMockDatabase(wallet->GetDatabase());
+
+        // Skip actually encrypting wallet on the overhead measuring run, so we
+        // can subtract the overhead from the results.
+        if(!measure_overhead) {
```
[the remark this answers is not in the document]
Comment (davidgumberg) [reply src/bench/wallet_encrypt.cpp]: Thanks, fixed.

**Comment by davidgumberg** [comment]
Rebase to address style feedback.

**Review by theStack — APPROVED** [review]
Code-review ACK 3d7d2c37f7fe10e77d50c8b8fa4d6c74ad52a3c6

**Review by furszy — COMMENTED** [review]
I don't see why the first commit is necessary. Couldn't you just mock the time so that it's fixed and the number of derivation rounds always stays at the default value?

**Comment by davidgumberg** [comment]
> I don't see why the first commit is necessary. Couldn't you just mock the time so that it's fixed and the number of derivation rounds always stays at the default value?

Maybe I'm not thinking creatively enough, but I think because the timing takes place entirely inside of `EncryptWallet()->EncryptMasterKey`, from the `wallet_encrypt.cpp` benchmark, I could only mock the clock so that it's static during the derivation "benchmark"[^1] runs, so the difference between the end time and the start time of a run will be `0` which will result in dividing by `0`:
https://github.com/bitcoin/bitcoin/blob/68ac9f116c0228a277f18f60ba2278b56356e6ac/src/wallet/wallet.cpp#L581-L589

[^1]: The ones that [decide](https://github.com/bitcoin/bitcoin/blob/68ac9f116c0228a277f18f60ba2278b56356e6ac/src/wallet/wallet.cpp#L587-L597) how many derivations to perform based on hardware speed.

**Comment by furszy** [comment]
> so the difference between the end time and the start time of a run will be 0 which will result in dividing by 0:

Yes, it seems much more straightforward to address that inside the encryption function (which could arguably be considered a 'fix', since we shouldn’t be dividing by zero regardless of whether the clock time is messed up) than to add a test-only field to the wallet and another function arg just just for this.

**Comment by davidgumberg** [comment]
>  since we shouldn’t be dividing by zero regardless of whether the clock time is messed up

AFAIK, `std::chrono::steady_clock`, unlike the system clock, cannot fail to move forward, and this will never happen.

> than to add a test-only field to the wallet and another function arg just just for this.

I agree that adding a test-only field and arg is very bad, and would like to avoid it, but it seems to me worse to imbue secret meaning into the benchmark by handling a time difference of 0 in this special way which appears on the surface to be error-handling, but is really a "side-channel" for test code to sneak an extra parameter into `EncryptWallet`, but I don't feel strongly enough about which of those is worse, so I'll implement your approach.

**Comment by davidgumberg** [comment]
Refactored to address @furszy feedback to avoid adding a test-only parameter to `CWallet`, and added a somewhat opinionated refactor (https://github.com/bitcoin/bitcoin/pull/31774/commits/7176b26cde7cbaffdd92af9c25f85f8e5233e78a) of `CWallet::EncryptMasterKey()` since I was touching the iteration measuring stuff anyways. I don't like the idea of using a `for` loop that iterates once with `0` and once with `1`, but it's nearly 50% the LOC, I believe it is easier to understand how the weighted average calculation is working, and this version generalizes to any number of measurement runs.

**Review by sipa — COMMENTED** [review]
utACK 8bdcd12d3bcbeaf922fa10dc2a261848e3900cfd

**Review by theStack — APPROVED** [review]
Code-review ACK 8bdcd12d3bcbeaf922fa10dc2a261848e3900cfd

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -580,16 +580,20 @@ void CWallet::UpgradeDescriptorCache()
...
+    // Get the weighted average of iterations we can do in 100ms over 2 runs.
+    for (int i = 0; i <= 1; i++){
+        auto start_time{SteadyClock::now()};
+        crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
+        auto elapsed_time{SteadyClock::now() - start_time};
 
-    start = SteadyClock::now();
-    crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
-    master_key.nDeriveIterations = (master_key.nDeriveIterations + static_cast<unsigned int>(master_key.nDeriveIterations * target / (SteadyClock::now() - start))) / 2;
+        // target_iterations : elapsed_iterations :: target_time : elapsed_time
```
Comment (furszy) [inline src/wallet/wallet.cpp:597]: In 7176b26cde7cbaffdd92af9c25f85f8e5233e78a:
nano nit:  I'm not sure how helpful this comment is.

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -580,16 +580,20 @@ void CWallet::UpgradeDescriptorCache()
...
 static bool EncryptMasterKey(const SecureString& wallet_passphrase, const CKeyingMaterial& plain_master_key, CMasterKey& master_key)
 {
-    constexpr MillisecondsDouble target{100};
-    auto start{SteadyClock::now()};
+    constexpr MillisecondsDouble target_time{100};
     CCrypter crypter;
 
-    crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
-    master_key.nDeriveIterations = static_cast<unsigned int>(master_key.nDeriveIterations * target / (SteadyClock::now() - start));
+    // Get the weighted average of iterations we can do in 100ms over 2 runs.
```
Comment (furszy) [inline src/wallet/wallet.cpp:585]: In https://github.com/bitcoin/bitcoin/commit/7176b26cde7cbaffdd92af9c25f85f8e5233e78a:
Pedantic ultra-nano nit:
We finish comments with a dot only if they span more than one line.

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -580,16 +580,20 @@ void CWallet::UpgradeDescriptorCache()
...
+        auto start_time{SteadyClock::now()};
+        crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
+        auto elapsed_time{SteadyClock::now() - start_time};
 
-    start = SteadyClock::now();
-    crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
-    master_key.nDeriveIterations = (master_key.nDeriveIterations + static_cast<unsigned int>(master_key.nDeriveIterations * target / (SteadyClock::now() - start))) / 2;
+        // target_iterations : elapsed_iterations :: target_time : elapsed_time
+        unsigned int target_iterations = master_key.nDeriveIterations * target_time / elapsed_time;
+        // Get the weighted average with previous runs.
```
Comment (furszy) [inline src/wallet/wallet.cpp:599]: In https://github.com/bitcoin/bitcoin/commit/7176b26cde7cbaffdd92af9c25f85f8e5233e78a:
nano nit: you are already mentioning this above the for-loop line.

**Review by furszy — COMMENTED** [review]
ACK 8bdcd12d3bcbeaf922fa10dc2a261848e3900cfd

No need to tackle the nano nits I left.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (achow101) [inline src/wallet/wallet.cpp:597]: In 7176b26cde7cbaffdd92af9c25f85f8e5233e78a "refactor: Generalize derivation target calculation"

This comment does not seem helpful, I'm not sure what information it is trying to convey.

File: src/bench/wallet_encrypt.cpp [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+    // Add destinations
+    for (auto type : OUTPUT_TYPES) {
+        for (int i = 0; i < 5'000; i++) {
+            CMutableTransaction mtx;
+            mtx.vout.emplace_back(COIN, GetScriptForDestination(*Assert(wallet->GetNewDestination(type, ""))));
+            mtx.vin.emplace_back();
+            wallet->AddToWallet(MakeTransactionRef(mtx), TxStateInactive{});
+            key_count++;
+        }
+    }
```
Comment (achow101) [inline src/bench/wallet_encrypt.cpp]: In 26442fec572da263765c576c080186c84cee1615 "bench: Add wallet encryption benchmark"

This part of setup is unnecessary. Encryption does not encrypt destinations or transactions. Generating new destinations does not result in more things to be encrypted.

If the idea was to have a bunch of keys to be encrypted for the benchmark, then several independent descriptors would need to be imported.

File: src/bench/wallet_encrypt.cpp [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+    bench.batch(key_count).unit("key").run([&] {
+        wallet = TestLoadWallet(std::move(database), context, create_flags);
+
+        // Save a copy of the db before encrypting
+        database = DuplicateMockDatabase(wallet->GetDatabase());
+
+        // Skip actually encrypting wallet on the overhead measuring run, so we
+        // can subtract the overhead from the full benchmark results to get
+        // encryption performance.
+        if (!measure_overhead) {
```
Comment (achow101) [inline src/bench/wallet_encrypt.cpp]: In 26442fec572da263765c576c080186c84cee1615 "bench: Add wallet encryption benchmark"

We've generally not had "measure overhead" in the benchmarks. If this is because encryption is actually a very small amount of time, I would suggest generating significantly more keys that need to actually be encrypted.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (davidgumberg) [reply src/wallet/wallet.cpp:597]: https://en.wikipedia.org/wiki/Ratio#Notation_and_terminology ([archive link](https://web.archive.org/web/20250918113648/https://en.wikipedia.org/wiki/Ratio#Notation_and_terminology))

This comment explains why the assignment below is correct. This can be read as "target_iterations is to elapsed_iterations as target_time is to elapsed_time", this is mostly equivalent to: $\frac{\text{targetiterations}}{\text{elapsediterations}} = \frac{\text{targettime}}{\text{elapsedtime}}$

File: src/wallet/wallet.cpp (hunk 5 above)
Comment (davidgumberg) [reply src/wallet/wallet.cpp:599]: Fair enough, I think this is adding a little more information than the comment above the for loop, but I'll remove when/if retouching.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (davidgumberg) [reply src/wallet/wallet.cpp:597]: I responded here: https://github.com/bitcoin/bitcoin/pull/31774#discussion_r2511344463

I'll mark this resolved and we can discuss there.

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (davidgumberg) [reply src/wallet/wallet.cpp:585]: Really? I couldn't find this in `doc/` and I find a lot of counter-examples when doing:

```
git grep -n -C 2 "// .*\." '*.cpp' '*.h'
```

**Comment by glozow** [comment]
IIRC we're waiting on @davidgumberg to address the comments from @achow101 's reviews https://github.com/bitcoin/bitcoin/pull/31774#discussion_r2511273130 here?

**Comment by davidgumberg** [comment]
```
git range-diff 68ac9f1..8bdcd12 9890058..e54690a
```

Rebased against master to fix a silent merge conflict with `lockedpool.cpp` being moved from util -> kernel in aed38ea, and addressed @achow101's comment about the previous benchmark only measuring encryption of a single key, I've updated the benchmarks to test encryption of 2000 keys, the performance impact is still negligible:

| branch |  EncryptWallet (total - overhead) | total ns/key | overhead ns/key
|-------:|----------------------------------:|-------------:|:---------------
| master + benchmarks (8abee2b) | 192,652.62 ns | 293,553.20 ns | 104,682.68 ns
| branch (e54690a)                | 192,772.32 ns | 294,794.46 ns | 104,329.09 ns

<details>

<summary>

### Benchmark details

</summary>
To set up, I cleaned my build dir and used pyperf.
```bash
rm -rf ./build 
pip install pyperf && sudo pyperf system tune
```

#### Master + benchmarks (8abee2b)
```bash
git checkout 8abee2b
cmake -B build -DBUILD_BENCH=ON && cmake --build build -j $(nproc)
./build/bin/bench_bitcoin --filter="WalletEncrypt.*" -min-time=12000
```

|              ns/key |               key/s |    err% |         ins/key |         cyc/key |    IPC |        bra/key |   miss% |     total | benchmark
|--------------------:|--------------------:|--------:|----------------:|----------------:|-------:|---------------:|--------:|----------:|:----------
|          293,553.20 |            3,406.54 |    0.1% |    6,848,134.51 |    1,258,326.47 |  5.442 |     151,429.70 |    0.9% |     12.91 | `WalletEncryptDescriptors`
|          104,682.68 |            9,552.68 |    0.1% |    2,329,994.28 |      448,813.08 |  5.191 |      74,084.65 |    0.9% |     13.02 | `WalletEncryptDescriptorsBenchOverhead`


-----

Branch (e54690a)
```bash
git checkout e54690a
cmake -B build -DBUILD_BENCH=ON && cmake --build build -j $(nproc)
./build/bin/bench_bitcoin --filter="WalletEncrypt.*" -min-time=12000
```

|              ns/key |               key/s |    err% |         ins/key |         cyc/key |    IPC |        bra/key |   miss% |     total | benchmark
|--------------------:|--------------------:|--------:|----------------:|----------------:|-------:|---------------:|--------:|----------:|:----------
|          294,794.46 |            3,392.19 |    0.3% |    6,855,246.26 |    1,264,321.32 |  5.422 |     153,125.52 |    0.9% |     12.97 | `WalletEncryptDescriptors`
|          104,329.09 |            9,585.05 |    0.1% |    2,330,778.18 |      447,414.99 |  5.209 |      74,203.06 |    0.8% |     12.94 | `WalletEncryptDescriptorsBenchOverhead`

</details>

File: src/bench/wallet_encrypt.cpp (hunk 6 above)
Comment (davidgumberg) [reply src/bench/wallet_encrypt.cpp]: Thanks for catching this, I've fixed this with importing multiple descriptors as you suggest in https://github.com/bitcoin/bitcoin/pull/31774/commits/8abee2b4bb1ac463a9ec200aa32b9c5276f0dcac

File: src/bench/wallet_encrypt.cpp (hunk 7 above)
Comment (davidgumberg) [reply src/bench/wallet_encrypt.cpp]: Unfortunately, even after generating more keys, there is still significant overhead, and this overhead is not fixed, it scales with the number of keys...

 Even though `total - overhead` isn't something we've measured in any existing benchmarks, it's probably a good idea for some benchmarks. It won't make a difference for catching extreme regressions, but for smaller performance regressions / improvements, the setup overhead in each run adds noise that makes changes harder to measure. Ideally there would be some way to achieve this with nanobench, but for now this hasn't been implemented and the maintainer of nanobench has suggested this approach: https://github.com/martinus/nanobench/issues/86#issuecomment-1423165976

File: src/bench/wallet_encrypt.cpp [hunk 8]
```diff
@@ -0,0 +1,87 @@
...
+    uint64_t create_flags{WALLET_FLAG_DESCRIPTORS};
+
+    auto database{CreateMockableWalletDatabase()};
+    auto wallet{TestLoadWallet(std::move(database), context, create_flags)};
+
+    {
+        LOCK(wallet->cs_wallet);
+        for (unsigned int i = 0; i < key_count; i++) {
+            CKey key;
+            key.MakeNewKey(/*fCompressed=*/true);
```
Comment (theStack) [inline src/bench/wallet_encrypt.cpp]: nit:
```suggestion
            CKey key = GenerateRandomKey();
```

**Review by theStack — APPROVED** [review]
re-ACK e54690ab9b53996d7ec893671e10b6d582cd6a1d

File: src/wallet/wallet.cpp [hunk 9]
```diff
@@ -533,16 +533,20 @@ void CWallet::UpgradeDescriptorCache()
...
 {
-    constexpr MillisecondsDouble target{100};
-    auto start{SteadyClock::now()};
+    constexpr MillisecondsDouble target_time{100};
     CCrypter crypter;
 
-    crypter.SetKeyFromPassphrase(wallet_passphrase, master_key.vchSalt, master_key.nDeriveIterations, master_key.nDerivationMethod);
-    master_key.nDeriveIterations = static_cast<unsigned int>(master_key.nDeriveIterations * target / (SteadyClock::now() - start));
+    // Get the weighted average of iterations we can do in 100ms over 2 runs.
+    for (int i = 0; i <= 1; i++){
```
Comment (furszy) [inline src/wallet/wallet.cpp]: nano nit: you are the first person I know that writes `i <= 1` instead of `i < 2`.

File: src/bench/wallet_encrypt.cpp [hunk 10]
```diff
@@ -0,0 +1,87 @@
...
+    });
+}
+
+constexpr unsigned int KEY_COUNT = 2000;
+
+static void WalletEncryptDescriptors(benchmark::Bench& bench) { WalletEncrypt(bench, /*key_count=*/KEY_COUNT, /*measure_overhead=*/false); }
+BENCHMARK(WalletEncryptDescriptors, benchmark::PriorityLevel::HIGH);
+
+static void WalletEncryptDescriptorsBenchOverhead(benchmark::Bench& bench) { WalletEncrypt(bench, /*key_count=*/KEY_COUNT, /*measure_overhead=*/true); }
+BENCHMARK(WalletEncryptDescriptorsBenchOverhead, benchmark::PriorityLevel::LOW);
```
Comment (furszy) [inline src/bench/wallet_encrypt.cpp]: I would remove this one, and focus on improving the benchmark code (or/and the benchmark framework) to be able to benchmark what we want and nothing else. Having an extra benchmark only to measure the overhead of another benchmark's setup and teardown smells quite bad.

We can do the improvements in a follow-up. But I wouldn't leave this overhead bench here, most likely no one will ever run it again.

Comment (davidgumberg) [reply src/bench/wallet_encrypt.cpp]: OK, I've removed it and added a comment explaining in the benchmark.

File: src/wallet/wallet.cpp (hunk 9 above)
Comment (davidgumberg) [reply src/wallet/wallet.cpp]: Okay, I'll take this as I don't feel very strong, but my intention was to make it obvious to a reader that this loop was only run twice.

File: src/bench/wallet_encrypt.cpp (hunk 8 above)
Comment (davidgumberg) [reply src/bench/wallet_encrypt.cpp]: Thanks, I've taken this.

**Comment by davidgumberg** [comment]
Pushed an update to address feedback from @theStack, @furszy @achow101 

- Simplified `CKey` creation in benchmark (https://github.com/bitcoin/bitcoin/pull/31774#discussion_r2897007308)
- Dropped measure overhead benchmark (https://github.com/bitcoin/bitcoin/pull/31774#discussion_r2897740216, @achow101)
- `i <= 1` -> `i < 2` (@furszy)

**Comment by davidgumberg** [comment]
Rebased to fix two silent merge conflicts:

- Create and load wallet split (https://github.com/bitcoin/bitcoin/commit/e12ff8aca049ec7b054cb3047a167c7ce8dbd421)
- Removal of benchmark priority (https://github.com/bitcoin/bitcoin/commit/fa51a28a948dbab7109f660bf11dbfd389c839ed from https://github.com/bitcoin/bitcoin/pull/34210)

**Review by furszy — COMMENTED** [review]
utACK af0da2fce2146a005f54b900a1fd545a6278173a

Thanks.

**Review by theStack — APPROVED** [review]
re-ACK af0da2fce2146a005f54b900a1fd545a6278173a

(as per `$ git range-diff e54690ab...af0da2fc`)

**Comment by achow101** [comment]
ACK af0da2fce2146a005f54b900a1fd545a6278173a

**Comment by fanquake** [comment]
Note that this had a side-effect for changes like #31425.
