### PR TITLE
fuzz: txgraph: fix `real_is_optimal` flag propagation in `CommitStaging`

### LINKED ISSUE #33097: fuzz: `txgraph`: Assertion `cmp == 0' failed
```
$ echo "oK+goKCgArv/GMG0oAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOTkAr6AAAgIC/wICAgICAgICCAAAAAAAAAAAAAgAAP8A/wACAAAAAAAAAAAAAAAAAAAAAAAAAAAAABACAgICf/8AoKAAAAAAAAAAAAgAAP8AAgAAAAAAABACAgICf/8AAAAAIAAAAAAAAAAAAAAACAAA/wACgIAAAAAAgIAAAAAAAAAAAAAACAAA/wACAAAAAAAAAAAAAAAAAAAAAAAAAAAAABACAgICf/8AoF4AFgAAAAAAAAAIAAD/AAIAAICAAAA=" | base64 --decode > txgraph.crash
$ FUZZ=txgraph ./fuzz txgraph.crash 
fuzz: test/fuzz/txgraph.cpp:1057: void txgraph_fuzz_target(FuzzBufferType): Assertion `cmp == 0' failed.
==6038== ERROR: libFuzzer: deadly signal
/usr/bin/llvm-symbolizer: error: 'linux-vdso.so.1': No such file or directory
   #0 0xaaaae4109fc4 in __sanitizer_print_stack_trace /llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
   #1 0xaaaae4005890 in fuzzer::PrintStackTrace() /llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
   #2 0xaaaae3feae50 in fuzzer::Fuzzer::CrashCallback() /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:231:3
   #3 0xffff856b57b8  (linux-vdso.so.1+0x7b8) (BuildId: d721ef96679f76202b9d0a21a3db1069daa73c69)
   #4 0xffff851b7dbc  (/lib/aarch64-linux-gnu/libc.so.6+0x87dbc) (BuildId: 817c172ae01de5c5673c0e5a5d33e8fa0d4c6bd5)
   #5 0xffff8516697c in raise (/lib/aarch64-linux-gnu/libc.so.6+0x3697c) (BuildId: 817c172ae01de5c5673c0e5a5d33e8fa0d4c6bd5)
   #6 0xffff85151ac0 in abort (/lib/aarch64-linux-gnu/libc.so.6+0x21ac0) (BuildId: 817c172ae01de5c5673c0e5a5d33e8fa0d4c6bd5)
   #7 0xffff8515f9b8  (/lib/aarch64-linux-gnu/libc.so.6+0x2f9b8) (BuildId: 817c172ae01de5c5673c0e5a5d33e8fa0d4c6bd5)
   #8 0xaaaae461b4b0 in txgraph_fuzz_target(std::span<unsigned char const, 18446744073709551615ul>) txgraph.cpp
   #9 0xaaaae4791604 in LLVMFuzzerTestOneInput fuzz.cpp
   #10 0xaaaae3fec344 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
   #11 0xaaaae3fd7ff8 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:328:6
   #12 0xaaaae3fdd4ac in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:863:9
   #13 0xaaaae4006070 in main /llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
   #14 0xffff85152298  (/lib/aarch64-linux-gnu/libc.so.6+0x22298) (BuildId: 817c172ae01de5c5673c0e5a5d33e8fa0d4c6bd5)
   #15 0xffff85152378 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x22378) (BuildId: 817c172ae01de5c5673c0e5a5d33e8fa0d4c6bd5)
   #16 0xaaaae3fd19ac in _start (/workdir/out/libfuzzer_asan/fuzz+0x14819ac)
```

### PR DESCRIPTION
**Pull request by theStack**
In the `txgraph` fuzz test, the `CommitStaging` step updates the `SimTxGraph` levels simply by erasing the front (=main) one in the `sims` vector, i.e. the staging level instance takes the place of the main level instance:

https://github.com/bitcoin/bitcoin/blob/83a2216f5278c1123ba740f1c8a055652e033ddd/src/test/fuzz/txgraph.cpp#L668-L672

This also includes the `real_is_optimal` flag (reflecting whether the corresponding real graph is known to be optimally linearized), without taking into account that this flag should only be set if _both_ levels before the commiting are optimal.

E.g. in case of #33097, at this point the main level is not optimally linearized, while the staging level is, and due to the incorrect propagation of the latter the simulation incorrectly assumes that the main level is optimal after, leading to the assertion fail in the additional checks that are ran in this case[1]. Fix this by setting the flag in the resulting main level explicitly. This is done in a generic way, in case there will ever be more than two levels (not sure what is planned in this direction), a simpler alternative would be e.g. `main_optimal = sim[0].real_is_optimal && sim[1].real_is_optimal`.

Fixes #33097.

[1] see https://github.com/theStack/bitcoin/commit/0aedf09ccc0ad4fff5956bdc012778534612c017 for the printf-debug-session-clutter, if that is useful/interesting for anyone (most of the output turned out to be irrelevant to the actual cause of #33097, but it was an entertaining way to discover the interface and get a first glimpse of `TxGraph` internals as a cluster-mempool newbie).

### CODE REVIEW

**Review by glozow — COMMENTED** [review]
ACK 444dcb2f9944ad5208bf00c9f197da7b2c98063c

The fix works and makes sense to me. I suppose a concrete scenario (edited for more clarity):
1. we have main and staging, neither optimally linearized. there are some non-optimal clusters that haven't been pulled from main to staging (this is the case in the real TxGraph, though the sim has a full copy)
2. we create an observer for the main level (alternatively, it could be oversized)
3. we call DoWork() which returns true after optimally linearizing the staging level and skipping the main level
4. we delete the main level observer
5. we call CommitStaging. sims staging gets copied over.
6. in the real `TxGraph`, while some clusters are optimal (the ones that changed in staging), others aren't

File: src/test/fuzz/txgraph.cpp [hunk 1]
```diff
@@ -668,7 +668,10 @@ FUZZ_TARGET(txgraph)
             } else if (block_builders.empty() && sims.size() > 1 && command-- == 0) {
                 // CommitStaging.
                 real->CommitStaging();
+                // Resulting main level is only guaranteed to be optimal if all levels are
+                const bool main_optimal = std::all_of(sims.cbegin(), sims.cend(), [](const auto &sim) { return sim.real_is_optimal; });
                 sims.erase(sims.begin());
+                sims.front().real_is_optimal = main_optimal;
```
Comment (sipa) [inline src/test/fuzz/txgraph.cpp:674]: Nit: if this is actually aiming to be forward compatible with a future more-than-two-levels extension (which we may in fact need at some point), I think this should be `sims.back(). ... = ...`. Doesn't matter now of course as it's all equivalent to level 0.

**Comment by sipa** [comment]
ACK 444dcb2f9944ad5208bf00c9f197da7b2c98063c
