### PR TITLE
wallet, bugfix: fix ComputeTimeSmart function during rescanning process.

### LINKED ISSUE #20181: Wrong `time` when importing transactions with `rescanblockchain ` RPC command
When using the `rescanblockchain` wallet RPC command, it seems like sometimes (though not always, and I couldn't find a specific pattern for when this does and doesn't happen) the `time` field of all transactions found is being set to the time of the most recent transaction detected. Besides that field, all data (including block and blocktime) return correctly. What's more, even in a node with `txindex=1` this happens, despite that when calling the (non-wallet-specific) `getrawtransaction` command, it returns the correct time.

Here's an example of a testnet transaction where I experienced this behaviour, and the output of Core where the same `txid` has. 2 different `time`s - a correct one using `getrawtransaction` and an incorrect one using `gettransaction`:
```
bitcoin-cli --testnet -rpcwallet=wallet getrawtransaction 8bacfc9c63d181e9d303f57f550fe72870afd640c961466829c6212bb23a72fe 1
{
  "txid": "8bacfc9c63d181e9d303f57f550fe72870afd640c961466829c6212bb23a72fe",
  "hash": "3de22064b8fec52fb183a8ad46fd011e6c6cab9906a008afa3d649d11bd250f1",
  "version": 2,
  "size": 222,
  "vsize": 141,
  "weight": 561,
  "locktime": 0,
  "vin": [
    {
      "txid": "685571776adce2ac3332faf6ed125235366cc3cb464604c9234bf371f1ab4e02",
      "vout": 0,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "txinwitness": [
        "30440220516d0b313aae44f639a111dac8f27bc1fac446345aaad51852a784620ac62c690220433cb7fdeb78cd84574ec0ddd08789a248fe19b71759e1b3b448ff9c3f980be401",
        "03eca8ceb44c4d930ab89fb5d721d02a745e4aeb0f75993fa535e98fb6c7f6e16e"
      ],
      "sequence": 4294967294
    }
  ],
  "vout": [
    {
      "value": 0.53891045,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 f3020d45a9ccf870ddf4176fde4420931ffd9af6",
        "hex": "0014f3020d45a9ccf870ddf4176fde4420931ffd9af6",
        "reqSigs": 1,
        "type": "witness_v0_keyhash",
        "addresses": [
          "tb1q7vpq63dfenu8ph05zahau3pqjv0lmxhk73dsjm"
        ]
      }
    },
    {
      "value": 0.10000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "0 bf702bf755da860153e7b1043fea160c6dcd9f1a",
        "hex": "0014bf702bf755da860153e7b1043fea160c6dcd9f1a",
        "reqSigs": 1,
        "type": "witness_v0_keyhash",
        "addresses": [
          "tb1qhaczha64m2rqz5l8kyzrl6skp3kum8c6m0c2h4"
        ]
      }
    }
  ],
  "hex": "02000000000101024eabf171f34b23c9044646cbc36c36355212edf6fa3233ace2dc6a777155680000000000feffffff02e54f360300000000160014f3020d45a9ccf870ddf4176fde4420931ffd9af68096980000000000160014bf702bf755da860153e7b1043fea160c6dcd9f1a024730440220516d0b313aae44f639a111dac8f27bc1fac446345aaad51852a784620ac62c690220433cb7fdeb78cd84574ec0ddd08789a248fe19b71759e1b3b448ff9c3f980be4012103eca8ceb44c4d930ab89fb5d721d02a745e4aeb0f75993fa535e98fb6c7f6e16e00000000",
  "blockhash": "00000000000000bc3b97cbe323c4695f39a65cc1d73060dca8ad084fb0ce61b5",
  "confirmations": 27528,
  "time": 1600623861,
  "blocktime": 1600623861
}
```
```
bitcoin-cli --testnet -rpcwallet=wallet gettransaction 8bacfc9c63d181e9d303f57f550fe72870afd640c961466829c6212bb23a72fe
{
  "amount": -0.10000000,
  "fee": -0.00000142,
  "confirmations": 27528,
  "blockhash": "00000000000000bc3b97cbe323c4695f39a65cc1d73060dca8ad084fb0ce61b5",
  "blockheight": 1835261,
  "blockindex": 24,
  "blocktime": 1600623861,
  "txid": "8bacfc9c63d181e9d303f57f550fe72870afd640c961466829c6212bb23a72fe",
  "walletconflicts": [
  ],
  "time": 1601486746,
  "timereceived": 1602570577,
  "bip125-replaceable": "no",
  "details": [
    {
      "involvesWatchonly": true,
      "address": "tb1q7vpq63dfenu8ph05zahau3pqjv0lmxhk73dsjm",
      "category": "send",
      "amount": -0.53891045,
      "label": "Change #5",
      "vout": 0,
      "fee": -0.00000142,
      "abandoned": false
    },
    {
      "involvesWatchonly": true,
      "address": "tb1qhaczha64m2rqz5l8kyzrl6skp3kum8c6m0c2h4",
      "category": "send",
      "amount": -0.10000000,
      "vout": 1,
      "fee": -0.00000142,
      "abandoned": false
    },
    {
      "involvesWatchonly": true,
      "address": "tb1q7vpq63dfenu8ph05zahau3pqjv0lmxhk73dsjm",
      "category": "receive",
      "amount": 0.53891045,
      "label": "Change #5",
      "vout": 0
    }
  ],
  "hex": "02000000000101024eabf171f34b23c9044646cbc36c36355212edf6fa3233ace2dc6a777155680000000000feffffff02e54f360300000000160014f3020d45a9ccf870ddf4176fde4420931ffd9af68096980000000000160014bf702bf755da860153e7b1043fea160c6dcd9f1a024730440220516d0b313aae44f639a111dac8f27bc1fac446345aaad51852a784620ac62c690220433cb7fdeb78cd84574ec0ddd08789a248fe19b71759e1b3b448ff9c3f980be4012103eca8ceb44c4d930ab89fb5d721d02a745e4aeb0f75993fa535e98fb6c7f6e16e00000000"
}
```

### PR DESCRIPTION
**Pull request by BitcoinTsunami**
The function ComputeTimeSmart in wallet.cpp assume that transaction are discovered in the right order.
Moreover the 'smarttime' determination algorithm is coded with realtime scenario in mind and not rescanning of old block.

The functional test demonstrate that if the user import a wallet, then rescan only recent history, and then rescan the entire history, the older transaction discovered would have an incorrect time determination.
In the context of rescanning old block, the only time value that as a meaning is the blocktime.

That's why I've fixed the problem with a simple separation between rescanning of old block and realtime time determination. The fix is written to have no impact on every realtime scenario and only impact the behaviour during a rescanning process.
This PR Fixes #20181.

To be fair, I don't think that this bug could be triggered with the wallet GUI, because it always proceed with a proper rescan.
But RPC API provide the possibility to trigger it. I've discovered it, because Specter desktop v0.10.0 was impacted. (https://github.com/cryptoadvance/specter-desktop/issues/680).

### CODE REVIEW

**Comment by jonatack** [comment]
If this PR is intended to address issue #20181, can you add "Closes #20181" or "Fixes #20181" to the PR description?

**Comment by BitcoinTsunami** [comment]
Is it right this way ?

**Comment by jonatack** [comment]
Yes, thank you.

**Comment by sipa** [comment]
Concept ACK.

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -3679,38 +3679,42 @@ void CWallet::GetKeyBirthTimes(std::map<CKeyID, int64_t>& mapKeyBirth) const {
...
-                int64_t nSmartTime;
-                nSmartTime = pwtx->nTimeSmart;
-                if (!nSmartTime) {
-                    nSmartTime = pwtx->nTimeReceived;
-                }
-                if (nSmartTime <= latestTolerated) {
-                    latestEntry = nSmartTime;
-                    if (nSmartTime > latestNow) {
-                        latestNow = nSmartTime;
+            if(!rescanning_old_block) {
```
Comment (jonatack) [inline src/wallet/wallet.cpp:3688]: commit 4997a2ea5f2 "wallet: fix ComputeTimeSmart algorithm to use blocktime during old block rescanning fixes #20181"

- does the documentation need to be updated?

- missing space
```suggestion
            if (!rescanning_old_block) {
```

- maybe start with the truthy case first, e.g. `if (rescanning_old_block) {`...

- can drop the "fixes #20181" from the commit message; in the PR description is fine (it will be copied by the merge commit)

- suggestion to reviewers: review this commit diff with `-w`

File: test/functional/wallet_transactiontime_rescan.py [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+
+    def skip_test_if_missing_module(self):
+        self.skip_if_no_wallet()
+
+    def run_test(self):
+        self.log.info('Prepare nodes and wallet')
+
+        minernode = self.nodes[0] # node used to mine BTC and create transactions
+        usernode = self.nodes[1] # user node with correct time
+        restorenode = self.nodes[2] # node used to restore user wallet and check time determination in ComputeSmartTime (wallet.cpp)
```
Comment (jonatack) [inline test/functional/wallet_transactiontime_rescan.py:27]: nit: 2 spaces before each comment per PEP8
```suggestion
        restorenode = self.nodes[2]  # node used to restore user wallet and check time determination in ComputeSmartTime (wallet.cpp)
```

File: test/functional/wallet_transactiontime_rescan.py [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+        assert_equal(restorewo_wallet.getbalance(), 16)
+        assert_equal(len(restorewo_wallet.listtransactions()), 3)
+
+        # check transactions time
+        self.log.info('Check transactions time after restoration')
+        for tx in restorewo_wallet.listtransactions():
+            if tx['address'] == 'bcrt1qqvs4h9g5kemwu8zdffv3c9tm3dm2qp9uzlxwzx':
+                assert_equal(tx['blocktime'], 1525971225)
+                assert_equal(tx['time'], 1525971225)
+            elif tx['address'] == 'bcrt1qnw7peeq89hwrg674zjf4phzzluld798p667q7q':
```
Comment (jonatack) [inline test/functional/wallet_transactiontime_rescan.py:152]: The test does indeed fail here without the change.
```
2020-12-07T22:04:28.394000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/jon/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "test/functional/wallet_transactiontime_rescan.py", line 152, in run_test
    assert_equal(tx['time'], 1525971225)
  File "/home/jon/projects/bitcoin/bitcoin/test/functional/test_framework/util.py", line 50, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(1527699225 == 1525971225)
```
But the test commit needs to be after the commit that makes the change, not before, otherwise the test fails. The tests and CI should pass for each commit. Also, you can squash the linter fixup commit into the test commit.

File: test/functional/wallet_transactiontime_rescan.py [hunk 4]
```diff
@@ -0,0 +1,160 @@
...
+
+    def run_test(self):
+        self.log.info('Prepare nodes and wallet')
+
+        minernode = self.nodes[0] # node used to mine BTC and create transactions
+        usernode = self.nodes[1] # user node with correct time
+        restorenode = self.nodes[2] # node used to restore user wallet and check time determination in ComputeSmartTime (wallet.cpp)
+
+        # time constant
+        mocktime = 1525107225
```
Comment (jonatack) [inline test/functional/wallet_transactiontime_rescan.py:30]: could use current time, grep in the functional tests for `int(time.time()`

File: test/functional/wallet_transactiontime_rescan.py [hunk 5]
```diff
@@ -0,0 +1,160 @@
...
+        wo1 = 'bcrt1qqvs4h9g5kemwu8zdffv3c9tm3dm2qp9uzlxwzx'
+        wo2 = 'bcrt1qnw7peeq89hwrg674zjf4phzzluld798p667q7q'
+        wo3 = 'bcrt1qdr36v724uddf50jhnju3amzap2gmmt9tf4aac5'
+
+        usernode.createwallet(wallet_name='wo', disable_private_keys=True)
+        wo_wallet = usernode.get_wallet_rpc('wo')
+
+        wo_wallet.importpubkey(pubkey='02f8802962c2ca756d8961c719f75bdfff2b6dbb775788ed54a68bcb182c0ea1ef')
+        wo_wallet.importpubkey(pubkey='0330f4a96800a38fa0a49cde4b5f802e95a0c1044e5954389a8d00cecde01b842b')
+        wo_wallet.importpubkey(pubkey='02f5ccbee49546e0b5bf2e76422ed959e983dafaa94c8abafc9c8f8b99ef23d16a')
```
Comment (jonatack) [inline test/functional/wallet_transactiontime_rescan.py:54]: The addresses and pubkeys don't need to be hardcoded. Have a look in other tests how this can be done (grep for "importpubkey", "deterministic", "pub_key", "priv_key", etc.)

**Review by jonatack — COMMENTED** [review]
Concept ACK

File: src/wallet/wallet.h [hunk 6]
```diff
@@ -664,7 +664,7 @@ class CWallet final : public WalletStorage, public interfaces::Chain::Notificati
      * Abandoned state should probably be more carefully tracked via different
      * posInBlock signals or by checking mempool presence when necessary.
      */
-    bool AddToWalletIfInvolvingMe(const CTransactionRef& tx, CWalletTx::Confirmation confirm, bool fUpdate) EXCLUSIVE_LOCKS_REQUIRED(cs_wallet);
+    bool AddToWalletIfInvolvingMe(const CTransactionRef& tx, CWalletTx::Confirmation confirm, bool fUpdate, bool rescanning_old_block) EXCLUSIVE_LOCKS_REQUIRED(cs_wallet);
```
Comment (jonatack) [inline src/wallet/wallet.h:667]: It would probaby be good to update the Doxygen documentation here.

File: src/wallet/wallet.cpp [hunk 7]
```diff
@@ -1788,7 +1788,7 @@ CWallet::ScanResult CWallet::ScanForWalletTransactions(const uint256& start_bloc
                 break;
             }
             for (size_t posInBlock = 0; posInBlock < block.vtx.size(); ++posInBlock) {
-                SyncTransaction(block.vtx[posInBlock], {CWalletTx::Status::CONFIRMED, block_height, block_hash, (int)posInBlock}, fUpdate);
+                SyncTransaction(block.vtx[posInBlock], {CWalletTx::Status::CONFIRMED, block_height, block_hash, (int)posInBlock}, fUpdate, true /* rescanning_old_block */);
```
Comment (jonatack) [inline src/wallet/wallet.cpp:1791]: nit
```suggestion
                SyncTransaction(block.vtx[posInBlock], {CWalletTx::Status::CONFIRMED, block_height, block_hash, (int)posInBlock}, fUpdate, /* rescanning_old_block */ true);
```

**Comment by BitcoinTsunami** [comment]
Thanks for all the feedback. I'll correct everything and ask question if needed.

**Comment by decryp2kanon** [comment]
Concept ACK. Thanks!

File: src/wallet/wallet.cpp (hunk 7 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.cpp:1791]: done locally, not pushed yet

File: src/wallet/wallet.h (hunk 6 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.h:667]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 2 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:27]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 3 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:152]: done locally, not pushed yet

File: src/wallet/wallet.cpp (hunk 1 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.cpp:3688]: done locally, except doxygen documentation update, not pushed yet

**Comment by jonasschnelli** [comment]
Concept ACK - code looks good (haven't looked at the tests). Code is relatively simple, basically just an `if` to bypass the smart-time calculation.

File: test/functional/wallet_transactiontime_rescan.py (hunk 4 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:30]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 5 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:54]: I've a question about this one. My first local version didn't use any hardcoded key and I use getaddressinfo and the pubkey field. I found my test a little bit hard to read, because I needed 4 wallets to realise it (and one, just to get a couple of address/pubkey). I find that by hardcoding address and pubkey, I could remove one wallet, and let the reader of the test be more focus on the 3 really important wallets.

Can you confirm me that I need to create a wallet to avoid hardcoded pubkey ? Or is there something I'm missing here.

If another wallet is required, I'll try to isolate it better from the 3 others than in my first attempt.

File: src/wallet/wallet.cpp (hunk 1 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.cpp:3688]: I'm not sure about how to update the doxygen documentation, because I don't understand the way the logic is explained. The documentation split sending and receiving transaction treatment explanation, but there's no distinction in ComputeTimeSmart in the code (or I don't see it).

That's why I'm not sure between which lines I should insert the new beahaviour description.
Maybe something like "- If receiving a transaction during a rescanning process, assign all its (not already known) transactions' timestamps to the block time." between the second and the third one :

```
/**
 * Compute smart timestamp for a transaction being added to the wallet.
 *
 * Logic:
 * - If sending a transaction, assign its timestamp to the current time.
 * - If receiving a transaction outside a block, assign its timestamp to the
 *   current time.
 * - If receiving a transaction during a rescanning process, assign all its
 *   (not already known) transactions' timestamps to the block time.
 * - If receiving a block with a future timestamp, assign all its (not already
 *   known) transactions' timestamps to the current time.
 * - If receiving a block with a past timestamp, before the most recent known
 *   transaction (that we care about), assign all its (not already known)
 *   transactions' timestamps to the same timestamp as that most-recent-known
 *   transaction.
 * - If receiving a block with a past timestamp, but after the most recent known
 *   transaction, assign all its (not already known) transactions' timestamps to
 *   the block time.
 *
 * For more information see CWalletTx::nTimeSmart,
 * https://bitcointalk.org/?topic=54527, or
 * https://github.com/bitcoin/bitcoin/pull/1393.
 */
```

File: src/wallet/wallet.h (hunk 6 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.h:667]: I need some feedback here too.

I want to add this at the end of the existing comment : 
"Should be called with rescanning_old_block set to true, if the transaction is not discovered in realtime, but during a rescan of old blocks." 

```
 /**
     * Add a transaction to the wallet, or update it.  pIndex and posInBlock should
     * be set when the transaction was known to be included in a block.  When
     * pIndex == nullptr, then wallet state is not updated in AddToWallet, but
     * notifications happen and cached balances are marked dirty.
     *
     * If fUpdate is true, existing transactions will be updated.
     * TODO: One exception to this is that the abandoned state is cleared under the
     * assumption that any further notification of a transaction that was considered
     * abandoned is an indication that it is not safe to be considered abandoned.
     * Abandoned state should probably be more carefully tracked via different
     * posInBlock signals or by checking mempool presence when necessary.
     *
     * Should be called with rescanning_old_block set to true, if the transaction is
     * not discovered in realtime, but during a rescan of old blocks.
     */
```

**Comment by BitcoinTsunami** [comment]
I've push a new version with the rework marked as resolved done.
What is not done yet:
- remove hardcoded pubkey in the functionnal test : wait for feedback on the way to do it to limit useless code.
- update ComputeTimeSmart doxygen documentation : wait for feedback on my proposal in comment.
- update AddToWalletIfInvolvingMe doxygen documentation : wait for feedback on my proposal in comment.

File: test/functional/wallet_transactiontime_rescan.py (hunk 5 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:56]: I've find a way with getnewaddress() on the node. The test is rewrited with importaddress() instead of importpubkey(). It's simplier and demonstrated the same thing.
Done locally, not pushed yet.

File: src/wallet/wallet.cpp (hunk 1 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.cpp]: I've push the proposition in a dedicated commit and will revise it if needed.

File: src/wallet/wallet.h (hunk 6 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.h:670]: I've push the proposition in a dedicated commit and will revise it if needed.

**Comment by BitcoinTsunami** [comment]
I've push the full rework and add documentation update proposal in a separated commit.

**Comment by luke-jr** [comment]
Weak NACK. Seems like a hacky "fix" for what is pretty much a user error...?

**Comment by BitcoinTsunami** [comment]
Thanks for your feedback.

I'll try to give a broader view of the problem and of my fix, from my perspective.

First of all, the current behaviour seems to be present for years, and no recent modification has changed this.It's rare that users encounter this one and there's clearly no emergency here.

The issue that triggered my investigation is this one : https://github.com/bitcoin/bitcoin/issues/20181But by looking at open issue, I've now found two more open issue on Github that should be related to the same behaviour :
https://github.com/bitcoin/bitcoin/issues/11703
https://github.com/bitcoin/bitcoin/issues/6662
And one pull request abandoned due to the lack of activity :
https://github.com/bitcoin/bitcoin/pull/12024
This pull request proposed in 2018 by @achow101 is more radical than the way I fix it, because it remove the SmartTime computation, but this raises an interesting point for me on which I would like to come back later.

The thing is that when someone encounters this behavior from Bitcoin Core wallet, it clearly has no clue on what's going on, because it's hard to reproduce it and the date seems so random and nonsense, that there's no easy way to request for similar problems on search engines. And when you try to investigate it, nothing points you in the right direction.

If it's considered as an error from the RPC API user to proceed first with a recent scan, and after with an older one, it must be documented in the RPC API Reference.
And maybe it's the right solution for this problem : simply inform that rescanblockchain function should be manipulated with some rules in mind.In that case, the documentation should precise that a miss handling of this method is fatal. Because if the API user proceeds to an improper rescan, there's no way to correct transaction datation later : the only way is to destroy the wallet.

Here why I think it might be a good idea to fix it : the API RPC users are mainly teams working around Bitcoin Core to enrich the ecosystem with more tools.
This part of the ecosystem is far more experimental (and less strict) than Bitcoin Core itself, and that's a good thing from my point of the view.
The specter desktop team has exploited the RPC rescanblockchain function to enable faster wallet import :
- If it's a segwit wallet, the rescanning process starts automatically on the first segwit enable block.
- During the backup process, the first transaction blockheight is saved, to enable auto optimized reimport of this wallet later.
- If the user is a power user and knows the height of his first transaction, it could restart manually from here to restore faster his wallet.
I found all these ideas interesting for a faster and better user experience and guess what, they had a bug that broke my wallet, and pushed me to look at the problem.
This type of experimentation has not his place in the Bitcoin Core wallet, but is, for me, a net positive for the ecosystem.
We could imagine others optimisation for an external wallet project to improve the user experience with this RPC rescanblockchain function, for example : start with a fast utxo rescanning process with UI blocked, then unblock the interface and rescan only the current year, then the previous one, then the previous one,...
From an user perspective, I think that the oldest transactions are way less important than the more recents one.
It's just some random thought, but my core point is that RPC API functions are not going to be used the way the internal wallet uses them, and it's a good thing because it enables leveraged creativity outside the Bitcoin Core project and high quality and reference code for the Bitcoin Core wallet.
That's why I think it might be good to enable a non restricted usage of RPC rescanblockchain function between the two points (start_height and stop_height), even if it's not used by the wallet internally.

Now let's go back to the fix itself.
I've tried to limit the impact on my fix on the existing code, but I'll try to give a broader view of the way I've thought about it to feed the conversation.
As I've said in the description of my PR : In the context of rescanning old blocks, the only time value that has a meaning is the blocktime.
That's why my first reaction was to look for a way not to call the ComputeTimeSmart function during a rescanning of old blocks, because you don't want to launch a complex time evaluation function in the first place when you already know that the blocktime is the only time that means something.
I then discovered that the ComputeTimeSmart call was a very deep call in the hierarchy of functions and that a lot of wallet logic was shared in the middle part whatever the context.
The separation of the code between block rescan processing and realtime processing would have been an incorrect approach, due to this middleware logic.
The main wrong thing here, to me, is to compute the time of a specific context (realtime processing) in a shared function called deep in the hierarchy.
A good way to fix it, is to push this responsibility outside the hierarchy (at least near the surface of the hierarchy).
But this way will require a bigger refactoring for the wallet.cpp file. If someone finds this interesting, I could try to write a proof of concept in a branch outside a pull request. But this patch would have a far bigger impact on the code.

Finally this PR approach was a way of keeping the patch simple while preserving functionality.
But If this seems too hacky, there's 3 other ways :
- Keep it as it's today, don't touch the wallet code, but update the RPC API Reference to explain restrictions on rescanblockchain function.
- Make a bigger refactoring to push ComputeTimeSmart responsibility in the right place in the functions hierarchy.
- Fix it like achow101 in his previous PR, by removing the part of ComputeTimeSmart that is only valid in a realtime context. This way, ComputeTimeSmart has not to be moved because it's not context dependent, but you've restricted a part of the current functionality. It's clearly an interesting approach too, from my point of view because it removes the root cause of the misplacement of the function in the hierarchy call.

Happy to pursue the discussion here.

**Comment by kristapsk** [comment]
> Seems like a hacky "fix" for what is pretty much a user error...?

How is rescanning blockchain a user error?

**Comment by luke-jr** [comment]
Manually scanning out of order, to be specific, is a user error because the wallet is assumed to always be scanned up to its sync-point.

**Comment by sipa** [comment]
@luke-jr I'd agree the wallet is written with that assumption, but I also don't see a downside to changing the behavior when the wallet can know it's dealing with an unusual situation. I haven't dug into the details, but I suspect this change makes things match expectations in strictly more situations.

**Comment by decryp2kanon** [comment]
Concept ACK

**Review by ryanofsky — APPROVED** [review]
Code review ACK ace3f77597a04785c2ab98708f31970934197044. This is great! A trivial fix replacing currently insane behavior (using latest transaction times to estimate times of transactions in old blocks) with the simple and obvious behavior of using the block timestamp as the transaction timestamp.

The only suggestion I would make is to maybe use block max time instead of block time for these transactions, to ensure that times within the set of rescanned transactions are monotonically increasing. (You can get the max time by chaining the `FoundBlock` expression `FoundBlock().time(blocktime).maxTime(block_max_time)`).

I will say I don't actually understand Luke's objection to this, and would be curious for an explanation. I understand (despite disagreeing with) the idea that it may be good to alert users that something is wrong by showing bad timestamps when they do something that the wallet can't support. But it's not clear what the exact user mistake is here, and if there is a better way to alert users about the bad usage, or just add code supporting the usage.

**Comment by ryanofsky** [comment]
Another thing I think could be done to improve this is to avoid adding these transactions to `wtxOrdered` when `rescanning_old_block` is true:

https://github.com/bitcoin/bitcoin/blob/ea96e17e1f2c2b0a949366260906ef02e560a425/src/wallet/wallet.cpp#L873-L874

If we want to exclude these transactions from smart time calculation, better to fully exclude instead of half-excluding them. Maybe there is a way to adjust the smart time calculations to include them, but that would require more thought and might not be worth the effort.

Another code cleanup that would be nice to see is moving `nTimeReceived`, `nOrderPos`, and `wtxOrdered` updates inside the `ComputeTimeSmart` function instead of doing them before. `ComputeTimeSmart` is only called one place and the current way time calculation is split up outside and inside this function is probably unnecessarily confusing. 

IMO, previous ACK is still ok and switching from block time to max block time, excluding these transactions from wtxOrdered, and making `ComputeTimeSmart` more self-contained are all optional improvements that could be followed up later.

**Comment by ryanofsky** [comment]
There appear to be spurious "Agent is not responding!" test failures https://cirrus-ci.com/task/5367295805489152, probably could be fixed by a new push or bulk restart

**Review by ryanofsky — APPROVED** [review]
Code review ACK 0072fc36b2e4d1a3660c46dd4d8cd9e551c17917. No changes since last review other than rebase. Suggestions from https://github.com/bitcoin/bitcoin/pull/20591#pullrequestreview-582518603 to use max block time instead of block time, and https://github.com/bitcoin/bitcoin/pull/20591#pullrequestreview-582518603 to keep rescan transactions out of wtxOrdered still apply and could be implemented here or in a followup

File: test/functional/wallet_transactiontime_rescan.py [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+        wo_wallet.importaddress(wo2)
+        wo_wallet.importaddress(wo3)
+
+        self.log.info('Start transactions')
+
+        # check blockcount
+        assert_equal(minernode.getblockcount(), 200)
+
+        # generate some btc to create transactions and check blockcount
+        minernode.generatetoaddress(300, m1)
```
Comment (jonatack) [inline test/functional/wallet_transactiontime_rescan.py:64]: I think 101 blocks would suffice here (the test functions the same but would run faster), unless I'm missing something.
 
<details><summary>working example</summary><p>

```diff
         # generate some btc to create transactions and check blockcount
-        minernode.generatetoaddress(300, m1)
-        assert_equal(minernode.getblockcount(), 500)
+        initial_mine = 101
+        minernode.generatetoaddress(initial_mine, m1)
+        assert_equal(minernode.getblockcount(), initial_mine + 200)
 
         # synchronize nodes and time
         self.sync_all()
@@ -75,7 +76,7 @@ class TransactionTimeRescanTest(BitcoinTestFramework):
 
         # generate blocks and check blockcount
         minernode.generatetoaddress(100, m1)
-        assert_equal(minernode.getblockcount(), 600)
+        assert_equal(minernode.getblockcount(), initial_mine + 300)
 
         # synchronize nodes and time
         self.sync_all()
@@ -88,7 +89,7 @@ class TransactionTimeRescanTest(BitcoinTestFramework):
 
         # generate blocks and check blockcount
         minernode.generatetoaddress(100, m1)
-        assert_equal(minernode.getblockcount(), 700)
+        assert_equal(minernode.getblockcount(), initial_mine + 400)
 
         # synchronize nodes and time
         self.sync_all()
@@ -101,7 +102,7 @@ class TransactionTimeRescanTest(BitcoinTestFramework):
 
         # generate more blocks and check blockcount
         minernode.generatetoaddress(100, m1)
-        assert_equal(minernode.getblockcount(), 800)
+        assert_equal(minernode.getblockcount(), initial_mine + 500)
 
         # check user final balance and transaction count
         self.log.info('Check user final balance')
@@ -136,7 +137,7 @@ class TransactionTimeRescanTest(BitcoinTestFramework):
 
         # proceed to rescan, first with an incomplete one, then with a full rescan
         self.log.info('Rescan last history part')
-        restorewo_wallet.rescanblockchain(650)
+        restorewo_wallet.rescanblockchain(initial_mine + 350)
         self.log.info('Rescan all history')
         restorewo_wallet.rescanblockchain()
```
</p></details>

**Review by jonatack — COMMENTED** [review]
ACK 0072fc36b2e4d1a3660c46dd4d8cd9e551c17917

Verified the test passes on this branch and fails on master.

> Suggestions from #20591 (review) to use max block time instead of block time, and #20591 (review) to keep rescan transactions out of wtxOrdered still apply.

Agree with @ryanofsky here.

One further suggestion below.

**Comment by BitcoinTsunami** [comment]
Thanks ryanofsky for your feedback and suggestions !
I confirm that my latest push was just to rebase master and I was a bit perplex about CI test failing.

I'll implement thoses two point :
> Suggestions from #20591 (review) to use max block time instead of block time, and #20591 (review) to keep rescan transactions out of wtxOrdered still apply.

I need a little time to fully understand the impact of you recommandation. I may have question about it later.

jonatack : I'll modify the functional test with your adjustment. You're not missing anything, my test just using a large number because I was to lazy to look at the minimal working number (If I remember correctly, I was not sure If I should use 100 or 101 to unlock miner coins and I increased the number).

**Comment by BitcoinTsunami** [comment]
Hey I just push a first update:
- fresh rebase
- use block_max_time instead of blocktime following ryanofsky advice
- faster functional test with jonatack recommandation.

The block_max_time advantage is clear for me now, because blocktime could sometimes  not be ordered in strict chronological order. block_max_time prevents this and Foundblock helper is very practical to get it.

Following jonatack recommandation, the test is now faster and validates the exact same thing as my previous iteration.

But this update doesn't contain any change concerning the wtxOrdered list.
I can't wrap my head around the fact that ryanofsky and jonatack sees a way to change this to obtain a better code.

At first glance, I thought I would do this first: 

> Another code cleanup that would be nice to see is moving nTimeReceived, nOrderPos, and wtxOrdered updates inside the ComputeTimeSmart function instead of doing them before

To cleanup the code first and change the behavior with rescanning_old_block after.
But I don't think it's a good idea to do that : currently, ComputeTimeSmart has no side effect on the wtx transaction. It's a good thing for me. If I do that, and you look at the resulting AddToWallet function : the fInsertedNew path will populate wtx via side effects in the ComputeTimeSmart function and the !fInsertedNew path will populate it directly in AddToWallet function. I don't like this type of asymetric + side effects behaviors in various execution path, but I'm open to understand the way things are done in Bitcoin Core and in C++ (I don't have any experience in C++).

After that, I just tried the simplest approach:
```
if (fInsertedNew) {
        wtx.m_confirm = confirm;
        wtx.nTimeReceived = chain().getAdjustedTime();
        if(!rescanning_old_block) {
            wtx.nOrderPos = IncOrderPosNext(&batch);
            wtx.m_it_wtxOrdered = wtxOrdered.insert(std::make_pair(wtx.nOrderPos, &wtx));
        }
        wtx.nTimeSmart = ComputeTimeSmart(wtx, rescanning_old_block);
        AddToSpends(hash);
    }
```

But this make me scratched my head : In the rescanning_old_block case, wtx object will be left with uninitialized field. I'm pretty sure it could produce error somewhere else... maybe not if nOrderPos != -1 is always checked before manipulating m_it_wtxOrdered, but a minima it requires more prudence to manipulate this. To be clear : I'm inconfortable because I don't visualise all consequences.

And after that , I looked at the wtxOrdered usage, and that's where my head explode : This list has two usages at the same time:
- the first is to maintain an ordered list for ComputeTimeSmart. The ordered aspect is only used here. That's why I understand why ryanofsky want to remove the transaction from here in the first place.
- the second usage is from RPC interface in the listtransactions method. And here I don't think that transaction order has impact (not sure, but highly probable), but I'm sure that absence of a wallet transaction has impact. I can't remove the wtxOrdered insertion in rescanning_old_block scenario without breaking things here.

That's why I'm stuck and don't understand the way you two see it in the first place. Could you please help me here ? I'll be happy to better understand implications here and way to move around this problem here !

The only way I could thing about refactoring it, is to separate the two list : maintain one unordered with all transactions and one ordered with transaction for ComputeTimeSmart only... but I doesn't make any sense for me to do that and I can't envision a step after this move to obtain a clearer code after that.

File: test/functional/wallet_transactiontime_rescan.py (hunk 8 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py]: done.

**Comment by BitcoinTsunami** [comment]
More thoughts :

I realise that the "two separate list" already exist with wtxOrdered (ordered) and mapWallet (unordered). It make more sens to me now. Because listtransactions() method in rpcwallet.cpp is dependant from wtxOrdered, I can't skip some transactions to be added in it.

If you still think that I should avoid adding these transactions to wtxOrdered, maybe a rewrite of listtransactions() is needed to use mapWallet instead of wtxOrdered (like the listsinceblock() method in rpcwallet.cpp).
I don't know exactly how the listtransactions RPC method is used externaly. Is wtxOrdered order really important or is the order just an easy way to ensure repetable output during pagination with moving (skip, count) couple ?

Last point, if we drop this point and keep the fix as it is right now, It should be noted that in case of and RPC API user which proceed first with a recent scan, and after with an older one, the ComputeTimeSmart function is fixed, but wtxOrdered is not sorted correctly. It may not be a big deal for listtransactions() method, but it may induce an unexpected behavior in the futur if some fresh code use this list thinking it's well sorted.

**Review by leonardojobim — COMMENTED** [review]
Tested ACK https://github.com/bitcoin/bitcoin/pull/20591/commits/6fb0173427df4b6a63131d0c338b5a2e63805561 
The test passes on this branch and fails on master.

If the approach mentioned above is applied, the test will fail with `restorewo_wallet.listtransactions()` returning 0.
```
if(!rescanning_old_block) {
    wtx.nOrderPos = IncOrderPosNext(&batch);
    wtx.m_it_wtxOrdered = wtxOrdered.insert(std::make_pair(wtx.nOrderPos, &wtx));
}
```

**Comment by charlierlee** [comment]
I tried this pull request today, and I still have the same problem. It's pulling in the wrong date after a rescan. I am now attempting to reload the entire blockchain. I need this fixed for my IRS audit.

**Comment by BitcoinTsunami** [comment]
> I tried this pull request today, and I still have the same problem. It's pulling in the wrong date after a rescan. I am now attempting to reload the entire blockchain. I need this fixed for my IRS audit.

You must encounter a similar problem as the one that make me code this PR. You can't recovered a wallet with incorrect datation. It's not possible yet, even with this PR : the only way is to destroy and recreate it. This PR only prevent the datation to be corrupted in the first place.

**Review by ryanofsky — APPROVED** [review]
Code review ACK bb6bc61bea3098d4dab895a73c2c0f7b8d293e2b. No significant changes since last review other than rebase, optimizing test, and switching to max block time instead of block time.

Thanks for looking into txordered suggestions! It'd be nice to clean up this code more but I can see how listtransaction constrains changing txordered, and I can see upsides of keeping ComputeTimeSmart functional even I might still prefer to see time logic less spread out over two method. There's space for more improvements later but I think this PR is clearly better than status quo.

One thing I don't know is what problem may cause the other reported issue https://github.com/bitcoin/bitcoin/pull/20591#issuecomment-783675403. Might be worth filing separate bug if there are known steps to reproduce.

**Review by promag — COMMENTED** [review]
How about `nTimeSmart = min(nTimeSmart, block_max_time)` and avoid `rescanning_old_block` argument?

**Comment by BitcoinTsunami** [comment]
> Code review ACK [bb6bc61](https://github.com/bitcoin/bitcoin/commit/bb6bc61bea3098d4dab895a73c2c0f7b8d293e2b). No significant changes since last review other than rebase, optimizing test, and switching to max block time instead of block time.
> 
> Thanks for looking into txordered suggestions! It'd be nice to clean up this code more but I can see how listtransaction constrains changing txordered, and I can see upsides of keeping ComputeTimeSmart functional even I might still prefer to see time logic less spread out over two method. There's space for more improvements later but I think this PR is clearly better than status quo.
> 
> One thing I don't know is what problem may cause the other reported issue [#20591 (comment)](https://github.com/bitcoin/bitcoin/pull/20591#issuecomment-783675403). Might be worth filing separate bug if there are known steps to reproduce.

Thanks ryanofsky for your feedback and your code review !

For the [#20591 (comment)], I need some confirmation from @charlierlee on my analysis :
I think that @charlierlee encountered an incorrect datation in a wallet.
After that, he searched for a solution online, found this PR and try it with a rescan of the wallet.
His incorrect datation was not corrected after that and he give his feedback here.

My point is that in that case : this PR won't save you because you can't recover an incorrect datation. It's an unrecoverable state. I mention in a previous comment "there's no way to correct transaction datation later : the only way is to destroy the wallet.". The rescan function never change a previous datation (even with a full rescan). That's why I think this PR is important, because it prevent the bad datation to occured in the first place.

**Comment by ryanofsky** [comment]
@promag did want to follow up on https://github.com/bitcoin/bitcoin/pull/20591#issuecomment-794463385?

To me this PR seems like a straightforward improvement that gets the rescan context taken into account in a simple way and adds test coverage. I'm sure there are other ways it could be improved beyond this, but I think this change should only help make future improvements and not get in the way.

**Comment by BitcoinTsunami** [comment]
Same code. I've just rebased from the latest master code to resolve conflict.

File: src/wallet/wallet.h [hunk 9]
```diff
@@ -503,7 +503,7 @@ class CWallet final : public WalletStorage, public interfaces::Chain::Notificati
     //! @return true if wtx is changed and needs to be saved to disk, otherwise false
     using UpdateWalletTxFn = std::function<bool(CWalletTx& wtx, bool new_tx)>;
 
-    CWalletTx* AddToWallet(CTransactionRef tx, const CWalletTx::Confirmation& confirm, const UpdateWalletTxFn& update_wtx=nullptr, bool fFlushOnClose=true);
+    CWalletTx* AddToWallet(CTransactionRef tx, const CWalletTx::Confirmation& confirm, const UpdateWalletTxFn& update_wtx=nullptr, bool fFlushOnClose=true, bool rescanning_old_block=false);
```
Comment (meshcollider) [inline src/wallet/wallet.h:509]: nit: spaces around `=` (we use new style guidelines even if it doesn't match with surrounding code)

File: test/functional/wallet_transactiontime_rescan.py [hunk 10]
```diff
@@ -0,0 +1,164 @@
...
+        initial_mine = 101
+        minernode.generatetoaddress(initial_mine, m1)
+        assert_equal(minernode.getblockcount(), initial_mine + 200)
+
+        # synchronize nodes and time
+        self.sync_all()
+        minernode.setmocktime(cur_time + ten_days)
+        usernode.setmocktime(cur_time + ten_days)
+        restorenode.setmocktime(cur_time + ten_days)
+        # send 10 btc to user first watch-only address
```
Comment (meshcollider) [inline test/functional/wallet_transactiontime_rescan.py:73]: nit: `user's`

File: test/functional/wallet_transactiontime_rescan.py [hunk 11]
```diff
@@ -0,0 +1,164 @@
...
+            elif tx['address'] == wo2:
+                assert_equal(tx['blocktime'], cur_time + ten_days + ten_days)
+                assert_equal(tx['time'], cur_time + ten_days + ten_days)
+            elif tx['address'] == wo3:
+                assert_equal(tx['blocktime'], cur_time + ten_days + ten_days + ten_days)
+                assert_equal(tx['time'], cur_time + ten_days + ten_days + ten_days)
+
+        # restore user wallet without rescan
+        self.log.info('Restore user wallet on another node without rescan')
+        restorenode.createwallet(wallet_name='wo', disable_private_keys=True, )
```
Comment (meshcollider) [inline test/functional/wallet_transactiontime_rescan.py:127]: nit: unnecessary `, ` after the last argument

File: test/functional/wallet_transactiontime_rescan.py [hunk 12]
```diff
@@ -0,0 +1,164 @@
...
+        restorewo_wallet = restorenode.get_wallet_rpc('wo')
+
+        restorewo_wallet.importaddress(wo1, rescan=False)
+        restorewo_wallet.importaddress(wo2, rescan=False)
+        restorewo_wallet.importaddress(wo3, rescan=False)
+
+        # check user has 0 balance and no transaction
```
Comment (meshcollider) [inline test/functional/wallet_transactiontime_rescan.py:134]: nit: `transactions`

**Review by meshcollider — COMMENTED** [review]
Code review ACK b92d5522782a8d56f71f9ed4d04dbb068b9d65e6

Verified the test fails on current master but passes with this PR. Nits inline are non-blocking. Will merge if @ryanofsky or someone else re-ACKs.

Thanks @BitcoinTsunami!

File: test/functional/wallet_transactiontime_rescan.py [hunk 13]
```diff
@@ -0,0 +1,164 @@
...
+        # send 1 btc to our third watch-only address
+        self.log.info('Send 1 btc to user')
+        miner_wallet.sendtoaddress(wo3, 1)
+
+        # generate more blocks and check blockcount
+        minernode.generatetoaddress(100, m1)
+        assert_equal(minernode.getblockcount(), initial_mine + 500)
+
+        # check user final balance and transaction count
+        self.log.info('Check user final balance')
```
Comment (jonatack) [inline test/functional/wallet_transactiontime_rescan.py:108]: c308ceba94e0d8fced7cf70ec0227f7f0d80cf8c nit, can omit the comment on line 107 and move it into line 108
```suggestion
        self.log.info('Check user's final balance and transaction count')
```

**Review by jonatack — COMMENTED** [review]
Code review re-ACK b92d5522782a8d56f71f9ed4d04dbb068b9d65e6 

Edit, also re-verified the debug build is clean and the test passes on the branch and fails on master.
```
2021-09-28T10:46:57.258000Z TestFramework (INFO): Check transactions time after restoration
2021-09-28T10:46:57.260000Z TestFramework (ERROR): Assertion failed
  File "/home/jon/projects/bitcoin/bitcoin/test/functional/wallet_transactiontime_rescan.py", line 154, in run_test
    assert_equal(tx['time'], cur_time + ten_days)
AssertionError: not(1635418013 == 1633690013)
```
Happy to re-review quickly for the suggestions.

**Review by ryanofsky — APPROVED** [review]
Code review ACK b92d5522782a8d56f71f9ed4d04dbb068b9d65e6. No changes since previous review other than rebase (conflicts on nearby lines)

File: src/wallet/wallet.h (hunk 9 above)
Comment (BitcoinTsunami) [reply src/wallet/wallet.h:509]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 10 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:73]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 11 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:127]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 12 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:134]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py [hunk 14]
```diff
@@ -0,0 +1,164 @@
...
+        self.sync_all()
+        minernode.setmocktime(cur_time + ten_days)
+        usernode.setmocktime(cur_time + ten_days)
+        restorenode.setmocktime(cur_time + ten_days)
+        # send 10 btc to user first watch-only address
+        self.log.info('Send 10 btc to user')
+        miner_wallet.sendtoaddress(wo1, 10)
+
+        # generate blocks and check blockcount
+        minernode.generatetoaddress(100, m1)
```
[the remark this answers is not in the document]
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:78]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py [hunk 15]
```diff
@@ -0,0 +1,164 @@
...
+        assert_equal(minernode.getblockcount(), initial_mine + 500)
+
+        # check user final balance and transaction count
+        self.log.info('Check user final balance')
+        assert_equal(wo_wallet.getbalance(), 16)
+        assert_equal(len(wo_wallet.listtransactions()), 3)
+
+        # check transactions time
+        self.log.info('Check transactions time')
```
[the remark this answers is not in the document]
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:113]: done locally, not pushed yet

File: test/functional/wallet_transactiontime_rescan.py (hunk 13 above)
Comment (BitcoinTsunami) [reply test/functional/wallet_transactiontime_rescan.py:108]: done locally, not pushed yet

File: src/wallet/wallet.h [hunk 16]
```diff
@@ -271,8 +271,11 @@ class CWallet final : public WalletStorage, public interfaces::Chain::Notificati
      * abandoned is an indication that it is not safe to be considered abandoned.
      * Abandoned state should probably be more carefully tracked via different
      * posInBlock signals or by checking mempool presence when necessary.
+     *
+     * Should be called with rescanning_old_block set to true, if the transaction is
+     * not discovered in realtime, but during a rescan of old blocks.
```
[the remark this answers is not in the document]
Comment (BitcoinTsunami) [reply src/wallet/wallet.h:276]: done locally, not pushed yet

**Comment by BitcoinTsunami** [comment]
Thanks meshcollider and jonatack for your feedback.
All your recommendations are included in the new code.

**Comment by jonatack** [comment]
ACK 240ea294d5e899a906f213f039b21e94c24d6018 per `git diff b92d552 240ea29`, re-verified rebase to latest master + debug build clean + new test passes on the branch and fails on master, only change since my review a few hours ago is incorporation of latest review suggestions

**Review by meshcollider — COMMENTED** [review]
re-utACK 240ea294d5e899a906f213f039b21e94c24d6018
