### PR TITLE
init: allow startup with -onlynet=onion -listenonion=1

### LINKED ISSUE #24980: -onlynet=onion plus -onlynet=ipv4/etc, without -onion=, in spite of -torcontrol= specified, incorrectly kills startup
In v22, using the options: -onlynet=onion -onlynet=ipv4 -onlynet=ipv6, combined with the options -torcontrol= (etc) functioned and bitcoind correctly pulled the onion socks address via a probe to tor. In v23, that combination of options no longer functions and -onion= is required.

** expected **

Using -onlynet=onion (and ipv4 and ipv6) if -torcontrol= is specified should still work.

**Actual behavior**

bitcoind refuses to start up due to commitid e53a8505db preventing it from doing so in init.cpp.

**To reproduce**

Run as per above.

**System information**

Sources built from fcf6c8f4eb217763545ede1766831a6b93f583bd (tag v23.0 as of this writing I .. think?)

Error message in debug.log is:

Error: Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is not provided
(no -proxy= and no -onion= given) or it is explicitly forbidden (-onion=0)
Shutdown: In progress...
scheduler thread exit
Shutdown: done

### PR DESCRIPTION
**Pull request by vasild**
It does not make sense to specify `-onlynet=onion` without providing a
Tor proxy (even if other `-onlynet=...` are given). This is checked
during startup. However, it was forgotten that a Tor proxy can also be
retrieved from "Tor control" to which we connect if `-listenonion=1`.

So, the full Tor proxy retrieval logic is:
1. get it from `-onion`
2. get it from `-proxy`
3. if `-listenonion=1`, then connect to "Tor control" and get the proxy
   from there (was forgotten before this change)

Fixes https://github.com/bitcoin/bitcoin/issues/24980

### CODE REVIEW

**Comment by vasild** [comment]
`111bec2fdc...bbbb1755da`: remove `;` from python code 🤦

`111b`, `bbbb1`, wow! today is my lucky day!

File: src/init.cpp [hunk 1]
```diff
@@ -1361,11 +1368,14 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+        // If -listenonion is set, then we will (try to) connect to the Tor control port
+        // later from the torcontrol thread and may retrieve the onion proxy from there.
+        const bool maybe_later = args.GetBoolArg("-listenonion", DEFAULT_LISTEN_ONION);
+        if (onlynet_used_with_onion && !maybe_later) {
             return InitError(
                 _("Outbound connections restricted to Tor (-onlynet=onion) but the proxy for "
-                  "reaching the Tor network is not provided (no -proxy= and no -onion= given) or "
-                  "it is explicitly forbidden (-onion=0)"));
+                  "reaching the Tor network is not provided: none of -proxy, -onion or "
+                  "-listenonion is given"));
```
Comment (jonatack) [inline src/init.cpp:1378]: Maybe consider something like this as a more helpful error message:
```diff
-                _("Outbound connections restricted to Tor (-onlynet=onion) but the proxy for "
-                  "reaching the Tor network is not provided: none of -proxy, -onion or "
-                  "-listenonion is given"));
+                _("The -onlynet=onion configuration option was passed to restrict outbound"
+                  " connections to Tor, but the proxy for reaching the Tor network was not"
+                  " provided: none of -proxy, -onion or -listenonion was given"));
```

**Review by jonatack — COMMENTED** [review]
Light Approach ACK (looked quickly, in seminar ATM)

```
₿ bitcoind -signet -onlynet=onion -listenonion=0
2022-04-26T12:11:00Z [init] Error: Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is not provided: none of -proxy, -onion or -listenonion is given
Error: Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is not provided: none of -proxy, -onion or -listenonion is given
2022-04-26T12:11:00Z [init] Shutdown: In progress...
2022-04-26T12:11:00Z [scheduler] scheduler thread exit
2022-04-26T12:11:00Z [shutoff] Shutdown: done
```

**Comment by dunxen** [comment]
Concept ACK

> `111bec2fdc...bbbb1755da`: remove `;` from python code 🤦
> 
> `111b`, `bbbb1`, wow! today is my lucky day!

Nice!

**Comment by dunxen** [comment]
tACK bbbb175

`./src/bitcoind -signet -onlynet=onion -listenonion=1` will not fail to start up. Node starts connecting to onion peers and runs normally.

`./src/bitcoind -signet -onlynet=onion -listenonion=0` will kill init with:
```
2022-04-28T07:09:12Z Error: Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is not provided: none of -proxy, -onion or -listenonion is given
Error: Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is not provided: none of -proxy, -onion or -listenonion is given
```

**Comment by laanwj** [comment]
@midnightmagic Can you confirm this solves your issue?

**Comment by vasild** [comment]
`bbbb1755da...c313568a97`: address suggestions

File: src/init.cpp [hunk 2]
```diff
@@ -1361,11 +1368,14 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
     if (onion_proxy.IsValid()) {
         SetProxy(NET_ONION, onion_proxy);
     } else {
-        if (args.IsArgSet("-onlynet") && IsReachable(NET_ONION)) {
+        // If -listenonion is set, then we will (try to) connect to the Tor control port
+        // later from the torcontrol thread and may retrieve the onion proxy from there.
+        const bool maybe_later = args.GetBoolArg("-listenonion", DEFAULT_LISTEN_ONION);
+        if (onlynet_used_with_onion && !maybe_later) {
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/init.cpp]: Done.

File: src/init.cpp (hunk 1 above)
Comment (vasild) [reply src/init.cpp]: Done.

File: test/functional/feature_proxy.py [hunk 3]
```diff
@@ -335,20 +335,29 @@ def networks_dict(d):
...
             self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
 
+        self.log.info("Test passing -onlynet=onion without -proxy, -onion or -listenonion raises expected init error")
+        self.nodes[1].extra_args = ["-onlynet=onion", "-listenonion=0"]
+        msg = (
+            "Error: Outbound connections restricted to Tor (-onlynet=onion) but "
+            "the proxy for reaching the Tor network is not provided: "
+            "none of -proxy, -onion or -listenonion is given"
+        )
+        self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
```
[the remark this answers is not in the document]
Comment (vasild) [reply test/functional/feature_proxy.py:354]: Since now the behavior depends on the `-listenonion` value, I added two tests - one with `1` and one with `0`. Leaving the test without an explicit `-listenonion` would mean relying on some parameter interaction or that the testing framework uses a specific value. This could result in a test failure if it is changed.

**Comment by schildbach** [comment]
Does this issue prevent incoming connections via Tor, if `--torcontrol` is used in combination with `--listenonion=1`? I've been running version 23.0 for days, and I've not got a single incoming connection via Tor. All are outgoing.

**Comment by vasild** [comment]
@schildbach, no, the issue itself (described in https://github.com/bitcoin/bitcoin/issues/24980) is that startup would abort with an error if `-onlynet=onion` is given without `-proxy` and without `-onion`. Those options specify the proxy for connecting to the Tor network. However there is a 3rd way to provide a Tor proxy - if `-listenonion=1` is given, then we would connect to the "Tor control center" and retrieve the IP address/port of the Tor proxy from there.

This PR aims to fix that problem by relaxing the startup check to allow startup with `-onlynet=onion` without `-proxy`, without `-onion` if `-listenonion` is given.

**Review by jonatack — COMMENTED** [review]
Diff LGTM in latest push per `git diff bbbb175 c313568`, will re-review. 

> I've been running version 23.0 for days, and I've not got a single incoming connection via Tor.

@schildbach If you like, send me your tor address over IRC (nick jonatack on #bitcoin-core-dev) and I'll try to manually connect to you.

**Comment by vasild** [comment]
`c313568a97...28ae912f50`: rebase due to conflicts

Previously invalidated ACK from @dunxen

**Comment by mzumsande** [comment]
Concept ACK, will review closely soon. I think it would be nice to get this fixed for 24.0.

File: src/init.cpp [hunk 4]
```diff
@@ -1348,13 +1348,20 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
     // -noonion (or -onion=0) disables connecting to .onion entirely
     // An empty string is used to not override the onion proxy (in which case it defaults to -proxy set above, or none)
     std::string onionArg = args.GetArg("-onion", "");
     if (onionArg != "") {
         if (onionArg == "0") { // Handle -noonion/-onion=0
             onion_proxy = Proxy{};
+            if (onlynet_used_with_onion) {
+                return InitError(
+                    _("Outbound connections restricted to Tor (-onlynet=onion) but the proxy for "
+                      "reaching the Tor network is explicitly forbidden: -onion=0"));
```
Comment (jonatack) [inline src/init.cpp:1363]: nit, use the same (more explicit) phrasing here as for the error message below, and consistent verb tense
```diff
-                    _("Outbound connections restricted to Tor (-onlynet=onion) but the proxy for "
-                      "reaching the Tor network is explicitly forbidden: -onion=0"));
+                    _("The -onlynet=onion configuration option was passed to restrict outbound"
+                      " connections to Tor, but the proxy for reaching the Tor network was explicitly forbidden: -onion=0"));
```

File: test/functional/feature_proxy.py [hunk 5]
```diff
@@ -336,20 +336,29 @@ def networks_dict(d):
...
+        msg = (
+            "Error: The -onlynet=onion configuration option was passed to restrict outbound"
+            " connections to Tor, but the proxy for reaching the Tor network was not"
+            " provided: none of -proxy, -onion or -listenonion was given"
+        )
+        self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
+
+        self.log.info("Test passing -onlynet=onion without -proxy or -onion but with -listenonion=1 is ok")
+        self.nodes[1].extra_args = ["-onlynet=onion", "-listenonion=1"]
+        self.start_node(1)
```
Comment (jonatack) [inline test/functional/feature_proxy.py:359]: - these two lines can be combined to one, i.e. `self.start_node(1, extra_args = ["-onlynet=onion", "-listenonion=1"])`
- maybe check that Tor is successfully up with assert_debug_log

```diff
         self.log.info("Test passing -onlynet=onion without -proxy or -onion but with -listenonion=1 is ok")
-        self.nodes[1].extra_args = ["-onlynet=onion", "-listenonion=1"]
-        self.start_node(1)
+        with self.nodes[1].assert_debug_log(["[tor] Authentication successful"]):
+            self.start_node(1, extra_args = ["-onlynet=onion", "-listenonion=1"])
         self.stop_node(1)
```

**Review by jonatack — COMMENTED** [review]
ACK 28ae912f501e1a09bd050dcf35ecf712374f743f

I agree that this should be tagged for the v24.0 milestone, have run across this issue myself.

File: src/init.cpp (hunk 4 above)
Comment (vasild) [reply src/init.cpp:1363]: Would be good to have consistent wording here and for I2P and CJDNS in https://github.com/bitcoin/bitcoin/pull/25989.

`master`:

> Outbound connections restricted to Tor (-onlynet=onion) but the proxy for  reaching the Tor network is not provided ...

this PR:

> Outbound connections restricted to Tor (-onlynet=onion) but the proxy for reaching the Tor network is explicitly forbidden: -onion=0

> The -onlynet=onion configuration option was passed to restrict outbound connections to Tor, but the proxy for reaching the Tor network was not provided ...

https://github.com/bitcoin/bitcoin/pull/25989

> Outbound connections restricted to CJDNS (-onlynet=cjdns) but -cjdnsreachable is not provided

> Outbound connections restricted to i2p (-onlynet=i2p) but -i2psam is not provided

**Comment by vasild** [comment]
`28ae912f50...2d0b4e4ff6`: rebase because this was old (no clear conflicts though) + pick suggestion + reword error message for consistency with the other message in this PR and with https://github.com/bitcoin/bitcoin/pull/25989.

Invalidates ACKs from @dunxen, @jonatack

File: test/functional/feature_proxy.py (hunk 5 above)
Comment (vasild) [reply test/functional/feature_proxy.py]: I combined the two lines to one, as suggested.

However, expecting "[tor] Authentication successful" in the log failed for me because it tried to talk to a Tor daemon on `127.0.0.1:9051`, not to the Python one from the testing framework at `self.conf2.addr`, because when overriding `extra_args` the setting `-onion=...` which was in `extra_args` is lost.

File: src/init.cpp [hunk 6]
```diff
@@ -1326,11 +1333,14 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
     if (onion_proxy.IsValid()) {
         SetProxy(NET_ONION, onion_proxy);
     } else {
-        if (args.IsArgSet("-onlynet") && IsReachable(NET_ONION)) {
+        // If -listenonion is set, then we will (try to) connect to the Tor control port
+        // later from the torcontrol thread and may retrieve the onion proxy from there.
+        const bool listenonion_disabled{!args.GetBoolArg("-listenonion", DEFAULT_LISTEN_ONION)};
```
Comment (mzumsande) [inline src/init.cpp:1338]: Since `DEFAULT_LISTEN_ONION=true`, this makes the InitError go away in some cases where it would be useful - i.e. in the (probably very typical) where a user just starts `./bitcoind -onlynet=onion` without providing any additional configuration and hopes everything works together out of the box. The user would have to actively set `-listenonion=0` or `listen=0` to still get this error.

I wonder if it might be more helpful to change the InitError to a info/warning (something along the lines of "Did you maybe forgot to provide a tor proxy? Disregard this you use torcontrol") that is not conditional on `-listenonion` Not a strong suggestion though, I am not sure either way.

**Comment by kristapsk** [comment]
Concept ACK

File: src/init.cpp (hunk 6 above)
Comment (vasild) [reply src/init.cpp:1338]: > this makes the InitError go away in some cases where it would be useful ... `./bitcoind -onlynet=onion`

That is exactly the case where we do not want an init error -- the problem described in https://github.com/bitcoin/bitcoin/issues/24980 which this PR aims to fix. Because it could as well work out of the box, giving an init error is too strict and is relaxed by this PR.

Now, it is true that we do not know for sure, at this stage, at startup, whether we would be able to connect to torcontrol and retrieve the proxy address from it. I think it is proper to allow startup and later, if the tor control thread fails to retrieve the proxy it will log the relevant error. That is similar (but not identical) to the case where `-proxy=` is given and at startup we do not know if it will work and actually proxy connections. Maybe later we would find out that nobody is listening on the given proxy address and will log an error then.

That is, we give init errors only if we are sure, guaranteed that it will not work.

> I wonder if it might be more helpful to change the InitError to a info/warning

I am a bit confused. Do you mean to keep the init error as it is in this PR, but in the case where we silently allow startup (the new relaxation in this PR) to log a warning? I think it would not be necessary because it could be annoying for the cases when all is ok. For the cases when it is not, then the tor control thread will log a proper message if/when the problem occurs. Also, "Disregard this if you use torcontrol" -- `-torcontrol` is irrelevant here -- even if not specified it has a reasonable default. The relevant setting is `-listenonion=1`.

Off topic rant: I find the name `listenonion` confusing, it should be something like `-auto_create_tor_listening_service_via_torcontrol` because `-listenonion` does not control whether or not we _listen_ on `127.0.0.1:8334` and the tor service could be setup in `tor.conf` (the "static" way in which we should have `-listenonion=0`, but would still be listening and accepting incoming tor connections).

Comment (mzumsande) [reply src/init.cpp:1338]: I was just thinking about the scenario where a user installs and starts tor, then `./bitcoind -onlynet=onion`, but didn't setup a Onion Service as described in `tor.md` because they didn't read the doc.
In that case they wouldn't make outbound connections and I think also get no error or warning from the torcontrol Thread unless they have `debug=tor` enabled.

**Comment by mzumsande** [comment]
Tested ACK 2d0b4e4ff66e60c85f86c526a53f8fb242ebb7d0

File: src/init.cpp (hunk 6 above)
Comment (vasild) [reply src/init.cpp:1338]: > but didn't setup a Onion Service as described in `tor.md`

There are two ways - [automatic](https://github.com/bitcoin/bitcoin/blame/2557429d2b82fe5ba308b940bcf14c3047634345/doc/tor.md#L70) and [manual](https://github.com/bitcoin/bitcoin/blame/2557429d2b82fe5ba308b940bcf14c3047634345/doc/tor.md#L162), which one do you mean?

What you describe above _could_ work with the automatic way:
1. `bitcoind` finds the tor control at `127.0.0.1:9051` (no need to specify `-torcontrol=127.0.0.1:9051` since that is the default).
2. The tor daemon tells `bitcoind` where is the tor cookie file and `bitcoind` is able to read it. Authentication is successful.
3. `bitcoind` automatically creates the onion service and starts listening and accepting incoming tor connections (locally at `127.0.0.1:8334`)
4. `bitcoind` retrieves the address of the socks5 tor proxy from tor control and sets `-onion` to it, for making outbound connections to tor peers.

If 2. fails then there will be some error in the log, either from [`TorController::auth_cb()`](https://github.com/bitcoin/bitcoin/blob/2557429d2b82fe5ba308b940bcf14c3047634345/src/torcontrol.cpp#L459) or from [`TorController::protocolinfo_cb()`](https://github.com/bitcoin/bitcoin/blob/2557429d2b82fe5ba308b940bcf14c3047634345/src/torcontrol.cpp#L562-L595).

If 4. fails, there will be an error from [`TorController::get_socks_cb()`](https://github.com/bitcoin/bitcoin/blob/2557429d2b82fe5ba308b940bcf14c3047634345/src/torcontrol.cpp#L337).

File: src/init.cpp (hunk 4 above)
Comment (jonatack) [reply src/init.cpp:1322]: I think the explicit version is clearer.

File: src/init.cpp (hunk 6 above)
Comment (mzumsande) [reply src/init.cpp:1338]: I mean the automatic way.
If step 1) is not successful, there will be  repeated messages:
```
[tor] Error connecting to Tor control socket
[tor] Not connected to Tor control port 127.0.0.1:9051, trying to reconnect
```
that are usually hidden in the `tor` debug category, because with `-listenonion=1` being the default, we probably don't even intend to use anything but clearnet and don't need to see those. These messages would become kind of relevant though if we used `-onlynet=onion` because we'd not find any peers without being able to find tor control, so it might be helpful to log something unconditionally in this case.
But these are logging nits that don't have to be discussed in this PR and certainly shouldn't hold it off, so I think you should just go ahead and resolve this.

Comment (vasild) [reply src/init.cpp:1338]: > ... a user installs and starts tor, then ./bitcoind -onlynet=onion ...

For 1. to fail, then tor is not listening on `127.0.0.1:9051` which it does by default. So, maybe the user did not install and start tor or did so, but fiddled with its config and changed the listening address.

Anyway, maybe this change makes sense:

```diff
--- i/src/torcontrol.cpp
+++ w/src/torcontrol.cpp
@@ -612,13 +612,26 @@ void TorController::disconnected_cb(TorControlConnection& _conn)
     if (service.IsValid())
         RemoveLocal(service);
     service = CService();
     if (!reconnect)
         return;

-    LogPrint(BCLog::TOR, "Not connected to Tor control port %s, trying to reconnect\n", m_tor_control_
+    const auto onlynets = gArgs.GetArgs("-onlynet");
+    if (gArgs.IsArgSet("-onlynet") &&
+        std::any_of(onlynets.begin(), onlynets.end(), [](const auto& n) {
+            return ParseNetwork(n) == NET_ONION;
+        })) {
+        LogPrintf("Not connected to Tor control port %s, trying to reconnect. "
+                  "Use -listenonion=0 to disable the tor control thread.\n",
+                  m_tor_control_center);
+    } else {
+        LogPrint(BCLog::TOR,
+                 "Not connected to Tor control port %s, trying to reconnect. "
+                 "Use -listenonion=0 to disable the tor control thread.\n",
+                 m_tor_control_center);
+    }

     // Single-shot timer for reconnect. Use exponential backoff.
```

Keep it in the debug log only if `-onlynet=onion` is not given, because for users that did not install tor and do not care about tor and just run `bitcoind` this would be just noise.

**Comment by MarcoFalke** [comment]
ACK 2d0b4e4ff66e60c85f86c526a53f8fb242ebb7d0 🕸

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 2d0b4e4ff66e60c85f86c526a53f8fb242ebb7d0 🕸
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgf6gv+JHLZSJ81Lalmx6JwgWyyjItQKB/aJMLaEK32S1zCAgLEEWK0RLm6L9XK
agQsA3ShTx7s25Lpa50vESdibiK/gGARpd2Wt8k0KsSdq4swZQiA5GnH2MIVGCY/
tS6H0bNnZUxNtq5yY9i0bT7MTPbjd0QTeQUs3KZHlmZBgigEkMXfIYyW24LtgTiE
rDo5Q70SXeQde2tbxKAvUET3TIdVCRj8sZ6+qyqP2VS9w54DfKA4w/q8jnv5RC8q
2glKU/0RMrQ7M23EH1vFH6Qp9TWV6/PQhKFB9LgyciSGGcBfG8IwF4Elhsc34pxV
TgIISzdWBhjrWG6ql78eXMT2vJAfmPCD+pThkBc9nxzbIeU/CBSQMwYCjyhDOyN0
mX0xpeDdjuCb3rIHgG2qDgrvBs9FkL2zNOAbKYyqzkIwCYfDNMDDYHDrYpqiGd7B
CKTL0X9zUB7+aIao36dM7QkcT8Q8V8eL9nEY8wZ4JwAgF+8ujZ9yp0rJ3uB7tOZx
vz9IevYu
=4zdT
-----END PGP SIGNATURE-----
```


</details>
