### PR TITLE
rpc: Fix rpcRunLater race in walletpassphrase

### LINKED ISSUE #14995: possible deadlock with walletpassphrase
When i used the encrypted wallet to test transfer parallelly,i frequently got the trouble: The rpc server is not responding.My test script is like below:
#!/bin/sh
while [ 1 ]
do
./bitcoin-cli listaddressgroupings>null
./bitcoin-cli walletpassphrase "!@#$%^&*" 2
./bitcoin sendtoaddress "mhAW6mzs5DeCbzBUHXBi4U446Fdnr1z8U7" 0.01
done

When i open the dead lock trace macro and check the debug log,i found the last print is as below:
2018-12-17 08:27:58 ThreadRPCServer method=walletpassphrase
2018-12-17 08:27:58 LOCKCONTENTION: cs_main
2018-12-17 08:27:58 Locker: wallet/rpcwallet.cpp:2642
2018-12-17 08:27:58 LOCKCONTENTION: pWallet->cs_wallet
2018-12-17 08:27:58 Locker: wallet/rpcwallet.cpp:2607

The line no 2642 is walletpassphrase and 2607 is LockWallet. I checked the code,i found there is no log printed for this line in function "walletpassphrase":
"LogPrint(BCLog::RPC, "queue run of timer %s in %i seconds (using %s)\n", name, nSeconds, timerInterface->Name());" So i guess the reason may be:
When "walletpassphrase" is running and lock the cs_wallet,the last relock timer triggered and call "LockWallet"."LockWallet" want to lock the cs_wallet but it has been locked by "walletpassphrase",so "LockWallet" is blocked.When "walletpassphrase" run to call "RPCRunLater",the function will erase the timer from the std::map "deadlineTimers",but the timer's timeout call is blocked,so the dead lock take place.
Is my guess right?
How to reslove the issue?
Any help will be appreciative！

### LINKED ISSUE #18482: RPC stuck on walletpassphrase call
Sometimes RPC API stops responding after calling walletpassphrase 
Unfortunately I can not exactly reproduce this bug. 
I have tried 20 threads with about 100 requests on each with sequential calling walletpassphrase -> listtransactions -> walletpassphrase -> getransactions, but with no luck.   

Observe it four-five times a day and only restart of node could help. 

It happens not only for bitcoin wallet on mainnet and testnet, but also for litecoin and bitcoin abc wallets, also for mainnet and testnet

I could provide additional data such as logs, etc.

**System information**

Bitcoin Core version v0.19.1
Litecoin Core Daemon version v0.17.1
Bitcoin ABC Daemon version v0.19.9.0-2f1adeefb

OS: Debian 10, Xen guest, SSD

debug.log with last call. after that RPC won't response anymore.

```
2020-03-31T10:17:47Z received: inv (37 bytes) peer=11
2020-03-31T10:17:47Z got inv: tx bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c  new peer=11
2020-03-31T10:17:47Z Requesting witness-tx bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c peer=11
2020-03-31T10:17:47Z sending getdata (37 bytes) peer=11
2020-03-31T10:17:48Z received: tx (247 bytes) peer=11
2020-03-31T10:17:48Z AcceptToMemoryPool: peer=11: accepted bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c (poolsz 10 txn, 13 kB)
2020-03-31T10:17:48Z sending inv (37 bytes) peer=5
2020-03-31T10:17:48Z received: inv (37 bytes) peer=6
2020-03-31T10:17:48Z got inv: tx bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c  have peer=6
2020-03-31T10:17:48Z sending inv (37 bytes) peer=14
2020-03-31T10:17:48Z sending inv (37 bytes) peer=13
2020-03-31T10:17:49Z received: inv (37 bytes) peer=15
2020-03-31T10:17:49Z got inv: tx bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c  have peer=15
2020-03-31T10:17:50Z received: inv (37 bytes) peer=21
2020-03-31T10:17:50Z got inv: tx bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c  have peer=21
2020-03-31T10:17:50Z received: inv (37 bytes) peer=2
2020-03-31T10:17:50Z got inv: tx bc6099be609e8a81e11b1ba53badd401a3361fe70c8a90dd92cc743ab972b32c  have peer=2
2020-03-31T10:17:50Z libevent: epoll_dispatch: epoll_wait reports 1
2020-03-31T10:17:50Z libevent: event_active: 0x561e681d9d08 (fd 9), res 2, callback 0x7fe4fc82e1b0
2020-03-31T10:17:50Z libevent: event_process_active: event: 0x561e681d9d08, EV_READ   call 0x7fe4fc82e1b0
2020-03-31T10:17:50Z libevent: evhttp_get_request_connection: new request from 10.10.1.10:22443 on 52

2020-03-31T10:17:50Z libevent: Attempting connection to 10.1.1.10:22443

2020-03-31T10:17:50Z libevent: event_add: event: 0x7fe4e0000b60 (fd -1), EV_READ    call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4e0000be0 (fd -1), callback 0x7fe4fc81fb40
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4e0000b60 (fd -1), callback 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4e0000be0 (fd -1), callback 0x7fe4fc81fb40
2020-03-31T10:17:50Z libevent: event_add: event: 0x7fe4e0000b60 (fd 52), EV_READ    call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: Epoll ADD(1) on fd 52 okay. Old events were 0; read change was 1 (add); write change was 0 (none); close change was 0 (none)
2020-03-31T10:17:50Z libevent: event_add: event: 0x7fe4e0000b60 (fd 52), EV_READ   EV_TIMEOUT call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_add: event 0x7fe4e0000b60, timeout in 30 seconds 0 useconds, call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4e0000be0 (fd 52), callback 0x7fe4fc81fb40
2020-03-31T10:17:50Z libevent: event_add: event: 0x7fe4e0000b60 (fd 52), EV_READ   EV_TIMEOUT call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_add: event 0x7fe4e0000b60, timeout in 30 seconds 0 useconds, call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: timeout_next: event: 0x7fe4bc001f90, in 0 seconds, 4053 useconds
2020-03-31T10:17:50Z libevent: epoll_dispatch: epoll_wait reports 1
2020-03-31T10:17:50Z libevent: event_active: 0x7fe4e0000b60 (fd 52), res 2, callback 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_process_active: event: 0x7fe4e0000b60, EV_READ   call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_add: event: 0x7fe4e0000b60 (fd 52), EV_READ   EV_TIMEOUT call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: event_add: event 0x7fe4e0000b60, timeout in 8206112 seconds 564133 useconds, call 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: evhttp_add_header: key: Host val: 10.1.1.5:50000
2020-03-31T10:17:50Z libevent: evhttp_add_header: key: Authorization val: Basic c210L.....dFZnMGE3YVk3MnRGcU9qTzhRVT0=

2020-03-31T10:17:50Z libevent: evhttp_add_header: key: Accept val: */*

2020-03-31T10:17:50Z libevent: evhttp_add_header: key: Content-type val: application/json

2020-03-31T10:17:50Z libevent: evhttp_add_header: key: Content-Length val: 111

2020-03-31T10:17:50Z libevent: evhttp_read_header: checking for post data on 52

2020-03-31T10:17:50Z libevent: evhttp_get_body_length: bytes to read: 111 (in buffer 111)

2020-03-31T10:17:50Z libevent: event_del: 0x7fe4e0000b60 (fd 52), callback 0x7fe4fc81ff40
2020-03-31T10:17:50Z libevent: Epoll DEL(1) on fd 52 okay. Old events were 2; read change was 2 (del); write change was 0 (none); close change was 0 (none)
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4e0000b60 (fd 52), callback 0x7fe4fc81ff40
2020-03-31T10:17:50Z Received a POST request for /wallet/test from 10.1.1.10:22443
2020-03-31T10:17:50Z libevent: timeout_next: event: 0x7fe4bc001f90, in 0 seconds, 4053 useconds
2020-03-31T10:17:50Z ThreadRPCServer method=walletpassphrase user=test
2020-03-31T10:17:50Z libevent: epoll_dispatch: epoll_wait reports 0
2020-03-31T10:17:50Z libevent: timeout_next: event: 0x7fe4bc001f90, in 0 seconds, 4053 useconds
2020-03-31T10:17:50Z libevent: epoll_dispatch: epoll_wait reports 0
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4bc001f90 (fd -1), callback 0x561e66258dd0
2020-03-31T10:17:50Z libevent: timeout_process: event: 0x7fe4bc001f90, call 0x561e66258dd0
2020-03-31T10:17:50Z libevent: event_active: 0x7fe4bc001f90 (fd -1), res 1, callback 0x561e66258dd0
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4bc001f90 (fd -1), callback 0x561e66258dd0
2020-03-31T10:17:50Z libevent: event_process_active: event: 0x7fe4bc001f90,    call 0x561e66258dd0
2020-03-31T10:17:50Z libevent: event_del: 0x7fe4bc001f90 (fd -1), callback 0x561e66258dd0
2020-03-31T10:17:58Z received: ping (8 bytes) peer=109
2020-03-31T10:17:58Z sending pong (8 bytes) peer=109
2020-03-31T10:19:13Z Making feeler connection to [2607:fea8:8460:2b4a::4]:18333
2020-03-31T10:19:13Z trying connection [2607:fea8:8460:2b4a::4]:18333 lastseen=842.8hrs
2020-03-31T10:19:18Z connection to [2607:fea8:8460:2b4a::4]:18333 timeout
2020-03-31T10:20:03Z socket closed
2020-03-31T10:20:03Z disconnecting peer=110
2020-03-31T10:21:10Z Making feeler connection to 54.162.24.231:18333
2020-03-31T10:21:10Z trying connection 54.162.24.231:18333 lastseen=556.7hrs
2020-03-31T10:21:15Z connection to 54.162.24.231:18333 timeout
2020-03-31T10:21:16Z Making feeler connection to 70.24.60.7:18333
2020-03-31T10:21:16Z trying connection 70.24.60.7:18333 lastseen=634.4hrs
2020-03-31T10:21:21Z connection to 70.24.60.7:18333 timeout
2020-03-31T10:21:35Z socket closed
2020-03-31T10:21:35Z disconnecting peer=111
```

### PR DESCRIPTION
**Pull request by promag**
Release locks before calling `rpcRunLater`.

Quick explanation: `rpcRunLater` leads to `event_free` which calls `event_del` which can wait for the event callback to finish if it's already running and that callback will try to lock wallet mutex - which is already locked in http thread.

Fixes #14995 , fixes #18482. Best reviewed with whitespace changes hidden.

### CODE REVIEW

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -1918,43 +1918,46 @@ static UniValue walletpassphrase(const JSONRPCRequest& request)
...
+        if (!pwallet->Unlock(strWalletPass)) {
+            throw JSONRPCError(RPC_WALLET_PASSPHRASE_INCORRECT, "Error: The wallet passphrase entered was incorrect.");
+        }
 
-    pwallet->TopUpKeyPool();
+        pwallet->TopUpKeyPool();
 
-    pwallet->nRelockTime = GetTime() + nSleepTime;
+        pwallet->nRelockTime = GetTime() + nSleepTime;
+    }
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp:1960]: Would be nice to add a comment why this scope is needed for `cs_wallet`

**Comment by MarcoFalke** [comment]
Can be tested with #18507

File: src/wallet/rpcwallet.cpp [hunk 2]
```diff
@@ -1918,47 +1918,52 @@ static UniValue walletpassphrase(const JSONRPCRequest& request)
...
 
     // Keep a weak pointer to the wallet so that it is possible to unload the
     // wallet before the following callback is called. If a valid shared pointer
     // is acquired in the callback then the wallet is still loaded.
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp:1964]: Should this say "locked" instead of "loaded"?

File: src/wallet/rpcwallet.cpp [hunk 3]
```diff
@@ -1918,47 +1918,52 @@ static UniValue walletpassphrase(const JSONRPCRequest& request)
...
+    // Currently this must be called without locks held otherwise a deadlock
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp:1965]: Why "currently"? Is there a plan to change this in the future?

Also, could add a `AssertLockNotHeld(cs_wallet);` to accommodate  the comment?

File: src/wallet/rpcwallet.cpp [hunk 4]
```diff
@@ -1918,47 +1918,52 @@ static UniValue walletpassphrase(const JSONRPCRequest& request)
...
+    // can occur with cs_wallet. For more details see #18487.
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp:1966]: Instead of plain hashtag and number, which is hard to quickly look up (especially without internet), what about describing the issue here briefly?

Comment (MarcoFalke) [reply src/wallet/rpcwallet.cpp:1966]: The comment from the pull request description seems suitable

**Comment by MarcoFalke** [comment]
ACK 47dd37cc83bdcaf19a3abe95950b2409baae6249 only tested that this avoids the node freezing. Didn't look at how libevent works or how the deadlock happens or if this breaks other stuff.

File: src/wallet/rpcwallet.cpp (hunk 2 above)
Comment (promag) [reply src/wallet/rpcwallet.cpp:1964]: No, loaded. This is to handle the case a wallet is unloaded before the timer is triggered.

File: src/wallet/rpcwallet.cpp (hunk 3 above)
Comment (promag) [reply src/wallet/rpcwallet.cpp:1965]: > Why "currently"? Is there a plan to change this in the future?

No plans. However I think it could be improved because after the timer stays in `deadlineTimers` after being triggered.

Comment (promag) [reply src/wallet/rpcwallet.cpp:1965]: > Also, could add a `AssertLockNotHeld(cs_wallet);` to accommodate the comment?

Done.

File: src/wallet/rpcwallet.cpp (hunk 4 above)
Comment (promag) [reply src/wallet/rpcwallet.cpp:1966]: Will improve&mix.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 0944cafe294d4ee009b615fc8d8caca77c117481. This is a nice, clean bug fix, but agree with Marco's suggestions to improve the comment. Adding the explanation of why the lock is released from the PR description would be very helpful. And it doesn't seem right to say "Currently this must be called without locks held", when I don't think it was or will be safe to safe to add a timer with locks held.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 7b8e15728d1ad058a4b7d7569fd5d5ba6806ca28. Just updated comment since last review

**Comment by MarcoFalke** [comment]
ACK 7b8e15728d, only tested that this avoids the node freezing. Did not look at how libevent works or how the deadlock happens or if this breaks other stuff. 📞

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 7b8e15728d, only tested that this avoids the node freezing. Did not look at how libevent works or how the deadlock happens or if this breaks other stuff. 📞
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjKCgwAjQesMVDRk/0HJqT63QzYXgsky/+kGB7rdd3glG/ytl06M6dgM3bgepAv
t2Jfe/uGUugB9v0ettQ5/MkXewKi/r9dllozXIf6ZYyW0tzQKN22kSO6ybRcn0bL
GJDJeK35QG5CEoRB8kJiwohGhxPBeI0HF9LkkfEb7eLsXJGH4hliuQ9xpc0KGr32
0Sj3SUttKlK4xUbyDVyC7VOGeD53ZphJFiq+HPMY3lm6FmXn5Z2wXv6/FeV2jFQb
oxCCJ52gBzijv5YImikXjeOBEElUhI2IuIKCmTvNgXFv3T/c/ToSPShFpH2j2btP
cCzsIK3pex8fJSZI1ZE+PszAeh2FejdDN144fP7Ds/9fOwXIARU/vPVCgXeDsHZe
0yl17Qtl6p1YAGK2NGDXNM8UOA9MtzqAUyDBl4jRblIux3qEwEsxskjsDUv5d3JX
Im6mmvKOk/5loNPGXNhIE150YdbYZ4PNKjy4ke6rLvMW60tX0PnhfwOKWGdVM5iw
Lxj6BnQy
=jUhE
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `72e45144d2300c2bfb37bf5663a6b1678638fd7ac770b9ac957658a6a77b4224  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e89294010872e45144d2300c2bfb37bf5663a6b1678638fd7ac770b9ac957658a6a77b4224f0109ca4b78eac0f9bc00e3fa6d9e07c621508fff0100d486fd595906b0f2e37c995bd6bdf4d08f12082668eceff96a8434888e60adc6e3bd8eaef49bf6defcfb4cf06320162a2754408f1045e86134cf0081b878fc32894389f0083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6dfff010359c91954884418e52df686749fb2ec908f1045e86134df0082c29508769168a540083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff01097250bf63f8fb92103baaad4d125418a08f02067053ad5be1fee548552b5f5eac723a10d5cafe82283a07c84f3deb924a0e34408f1045e86134cf00879fc4848f25e6ee20083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010b2184820e4d99f52920b22a7cd0fda6208f020e8e879f8d8b046c15439aed265a2f83ffbf83296fe7cb8029e4e3dfc468c066f08f1045e86134cf00895b0800664b9596c0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267)

</details>

**Comment by promag** [comment]
I didn't want to write libevent details in rpcwallet and also how RPCRunLater is implemented.

**Comment by promag** [comment]
@MarcoFalke the deadlock happens in this case: 

- (we are in one of the http thread)
- walletpassphrase
- RPCRunLater
- ~HTTPEvent()
- event_free()
- event_del()
- event_del_(, EVENT_DEL_AUTOBLOCK);

And from libevent header
```
/** Argument for event_del_nolock_. Tells event_del to block on the event
 * if it is running in another thread and it doesn't have EV_FINALIZE set.
 */
#define EVENT_DEL_AUTOBLOCK 2
```
And the event callback (triggered from the event base thread) will lock `cs_wallet` and deadlock:
https://github.com/bitcoin/bitcoin/blob/b83565625e32b22395e28c1965b2e42fc17f04d7/src/wallet/rpcwallet.cpp#L1963-L1969

**Comment by promag** [comment]
> > or if this breaks other stuff.
> 
> I can't see how that could happen. but..

@MarcoFalke but #18811 happened.
