### PR TITLE
gui: Fix issue: "default port not shown correctly in settings dialog"

### LINKED ISSUE #12623: gui: default port not shown correctly in settings dialog
screenshot 2018-03-06 at 4 11 21 pm
Using 20e3b9a485fd6b23785c5caa49d01ea49fdc8bcf. Should obviously be 9050, not %2.

### PR DESCRIPTION
**Pull request by l2a5b1**
In f05d349 the value of the `addrProxy` and `addrSeparateProxyTor` settings is set to an illegal default value, because the value of `DEFAULT_GUI_PROXY_PORT ` is passed to the `fieldWidth` parameter of the `QString QString::arg(const QString &a, int fieldWidth = 0, QChar fillChar = QLatin1Char( ' ' )) const` method:

https://github.com/bitcoin/bitcoin/blob/29fad97c320c892ab6a480c81e2078ec22ab354b/src/qt/optionsmodel.cpp#L129

https://github.com/bitcoin/bitcoin/blob/29fad97c320c892ab6a480c81e2078ec22ab354b/src/qt/optionsmodel.cpp#L139

This will create a default proxy setting that consists of 9053 characters and ends with the string `127.0.0.1:%2`.

This PR attempts to resolve #12623 by setting the correct value for the `addrProxy` and `addrSeparateProxyTor` settings (i) if the proxy setting does not exist; or (ii) if the proxy setting has an illegal value caused by to the aforementioned bug. 

The second condition is *only* relevant if we don't want Bitcoin Core 0.16.0 users to explicitly reset their settings to see the correct default proxy port value.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK, soryr for making such a stupid mistake.

> The second condition is only relevant if we don't want Bitcoin Core 0.16.0 users to explicitly reset their settings to see the correct default proxy port value.

If we add that workaround, let's at least add a comment that explains that workaround, so that future maintainers know why it's there and when it can be removed.

**Comment by 251Labs** [comment]
Thanks @laanwj! I have added a comment to both conditional statements to clarify the purpose of the second boolean condition.

**Review by randolf — APPROVED** [review]

**Comment by DavidWard1980** [comment]
The reason it is not on the original port is because the php. Server that AT&T and other companies have taken from me off my personal device, was the helloworld.php server that was benchmarked by me, David Ward email address davidwardsr@gmail.com, it was on a port called "have Patience" and ran off my IP address at the time. It was my personal APN 192.168.0.100 it took me 15 sec to test it and is the fastest server there is...... Helloworld.php/192.168.0.100  is the APN I created it was on no security and the value was ffff witch I was told would never work. If you want to be back on the original server and original port then you will have to contact Apache Inc. and Zeus technologies because they are the ones who took my IP server off my personal device. So they can direct you or sign contracts with to get back on the level 5 platform you need.

File: src/qt/optionsmodel.cpp [hunk 1]
```diff
@@ -125,8 +125,10 @@ void OptionsModel::Init(bool resetSettings)
 
     if (!settings.contains("fUseProxy"))
         settings.setValue("fUseProxy", false);
-    if (!settings.contains("addrProxy"))
-        settings.setValue("addrProxy", QString("%1:%2").arg(DEFAULT_GUI_PROXY_HOST, DEFAULT_GUI_PROXY_PORT));
+    // The second condition in the boolean expression is a workaround to overwrite the 'addrProxy' setting
+    // in case it has been set to an illegal default value by release 0.16.0 (see issue #12623; PR #12650).
```
Comment (Sjors) [inline src/qt/optionsmodel.cpp]: Move to `OptionsModel::checkAndMigrate()`?

**Review by Sjors — COMMENTED** [review]
Concept ACK

**Comment by 251labs** [comment]
He @Sjors, thanks! I took a stab at addressing your suggestion in 6bb2adb and rebased this feature branch onto master.  I committed on top of 87bd26b in case you prefer that version and want me to revert the changes.

File: src/qt/optionsmodel.cpp [hunk 2]
```diff
@@ -485,4 +493,16 @@ void OptionsModel::checkAndMigrate()
 
         settings.setValue(strSettingsVersionKey, CLIENT_VERSION);
     }
+
+    // Overwrite the 'addrProxy' setting in case it has been set to an illegal
```
Comment (MarcoFalke) [inline src/qt/optionsmodel.cpp]: Trailing whitespace in this line

**Comment by 251labs** [comment]
Thanks @MarcoFalke! 40141b7 is rebased onto the master (048ac8326) and addresses the trailing whitespace character.

**Comment by 251labs** [comment]
squashed previous work in 2f3ce02, which is based on @Sjors' suggestion:

> Move to OptionsModel::checkAndMigrate()?

**Comment by Sjors** [comment]
tACK 2f3ce02

Nit: maybe change "Addresses" to "Fix" in your commit message, if only so it fits in 72 characters.

**Review by Sjors — APPROVED** [review]
tACK 2f3ce02

Nit: maybe change "Addresses" to "Fix" in your commit message, if only so it fits in 72 characters.

**Comment by jonasschnelli** [comment]
utACK 2f3ce024eb36f93f82f4fc644d57c45639b9f3de

*Nods* for new migration/auto-fix code without EOL strategy.

**Comment by 251labs** [comment]
Thanks @jonasschnelli, @sjors! @sjors: I have addressed your feedback and changed the commit message in 40c5886 to make it fit in 72 characters.

**Comment by Sjors** [comment]
reACK 0c5886

**Comment by WorkShop-Office** [comment]
Yes, of course

**Comment by MarcoFalke** [comment]
Tagged for backport in case there is a 16.1 release

**Comment by fanquake** [comment]
Backported in #12967
