### PR TITLE
wallet: Do not iterate a directory if having an error while accessing it 

### LINKED ISSUE #20081: wallet: Can't Access System Volume Information
I have the C:\Users\username\AppData\Roaming\Bitcoin folder as a soft link to a separate internal drive. This apparently caused an issue when trying to access another wallet. NTFS has created a hidden folder called System Volume Information on the root of the drive where the data directory is. When I try to open another wallet inside of Bitcoin-QT, it freezes up. The error I get in the log is ListWalletDir: Access is denied C:\Users\Linrono\AppData\Roaming\Bitcoin\System Volume Information. This shows up in the logs over and over until I force close Bitcoin-QT. It took up my entire 10MB log file at one point. I also tested this using bitcoind.exe and the same thing happens when running bitcoin-cli.exe getwalletdir. An easy fix for me would be to just create a folder in the volume and move my soft link to point there. I just wanted to bring this to your attention.

**Expected behavior**

I thought I would get a list of wallets I have created in the directory with the createwallet command.

**Actual behavior**

This caused a freeze that required the program to be force closed.

**To reproduce**

Just store the Bitcoin Data Directory in the root of a Windows Volume, and then try to find local wallets. This has happened to me every time I go to File and then mouse over Open Wallet or use the listwalletdir bitcoin-cli command.

**System information**

I am using Bitcoin Core v.20.1 from the BitcoinCore.org website.

Windows 10, Ryzen 5, Hard Drive

I believe this issue is related to the NTFS system folder on the root of volumes.

ListWalletDir: Access is denied C:\Users\Linrono\AppData\Roaming\Bitcoin\System Volume Information

### LINKED ISSUE #21136: UI Hangs when running as std user
When accessing the Open Wallet from the File Menu, the UI hangs. Looking at the debug.log in the data directory, there are thousands of ListWalletDir: ACcess is Denied E:\$Recycle.bin\s-1-5-18 events. 

The data directory is set to be the root of a USB drive mapped to the E: letter. 

Client is started as std user. 

**Expected behavior**

Expected behaviour is for the client UI to handle the access issue and continue, possibly noting the requirement to have further permissions. Even when the client is started as administrator, the same hang occurs. It appears the client data directory should be set to a folder and not the root of a drive. 

**Actual behavior**

Any attempt to access the open wallet menu gets stuck. 

**To reproduce**

Install bitcoin core 0.21.0 x64
Set data directory to the root of a drive in Windows
Let sync or not, hover over the Open Wallet menu
Program UI hangs

**System information**

bitcoin core 0.21.0 x64

Windows 10 x64 PC, SSD drive, Core i9 9980xe

Windows 10 20H2 Build 19042.789

thousands of lines of the below. The debug.log is 370MB. 

05:32:18Z ListWalletDir: Access is denied E:\System Volume Information
2021-02-10T05:32:18Z ListWalletDir: Access is denied E:\System Volume Information
2021-02-10T05:32:18Z ListWalletDir: Access is denied E:\System Volume Information

### LINKED ISSUE #21904: Crash when opening wallet
Bitcoin Core crashes when trying to open a wallet on Windows because your application logic is nonsensical. When Bitcoin Core was installed, I chose the root level of a dedicated volume (E:) for Bitcoin to store its data on. When I go to open a new wallet, it pegs one CPU core to 100%. Looking at the debug log, it is repeatedly trying to access E:\System Volume Information, and is getting an access denied message because this user doesnt have administrative rights, so it cant access this directory. Your application shouldnt be accessing this directory just to present an open file dialog, and it should be smart enough to throw an exception with an error message to the user and not get stuck in an infinite loop if it encounters problems with file permissions.

### PR DESCRIPTION
**Pull request by hebasto**
On Windows when `ListDatabases` tries to iterate any system folder, e.g., "System Volume Information", it falls into an infinite loop.

This PR fixes this bug. Now the `debug.log` contains:
```
2021-05-12T09:07:53Z ListDatabases: Access is denied D:/System Volume Information -- skipping.
```

An easy way to reproduce the bug and test this PR is to pass the `-walletdir=D:\` command-line option, and run the `listwalletdir` RPC, or File -> Open Wallet in the GUI menu.

Fixes #20081.
Fixes #21136.
Fixes #21904.

Also https://bitcoin.stackexchange.com/questions/99243/listwalletdir-access-is-denied-d-system-volume-information

### CODE REVIEW

File: src/wallet/db.cpp [hunk 1]
```diff
@@ -19,6 +23,12 @@ std::vector<fs::path> ListDatabases(const fs::path& wallet_dir)
     for (auto it = fs::recursive_directory_iterator(wallet_dir, ec); it != fs::recursive_directory_iterator(); it.increment(ec)) {
         if (ec) {
             LogPrintf("%s: %s %s\n", __func__, ec.message(), it->path().string());
+#ifdef WIN32
+            if (ec.value() == boost::system::windows_error::access_denied) {
```
Comment (laanwj) [inline src/wallet/db.cpp:27]: Is this specific to windows? Or could this happen with directory "access denied" errors on other OSes as well?

Comment (hebasto) [reply src/wallet/db.cpp:27]: > Is this specific to windows?

The error code is specific to windows.

> Or could this happen with directory "access denied" errors on other OSes as well?

Yes, it could. But on other OSes the reason of "access denied" errors is a bad setup that a user can/should fix. On windows this situation seems common and not always fixable by a user.

**Comment by sipsorcery** [comment]
Started with:

`bitcoin-qt.exe -walletdir=c:\`

Is this error message expected? The app continues as normal once `OK` is clicked.

bitcoin-qt_walletdir

On `master` the message is a warning:

bitcoin_qt_warning

**Comment by hebasto** [comment]
> Sure I was only attempting to test the fix in this PR by getting the wallet logic to scan the root drive. I don't have a `D:\` drive.

A USB flash-drive could work, no?

**Review by ghost — COMMENTED** [review]
1. `bitcoin-qt.exe -walletdir=E:\` Not Responding when I try to open wallets

image

2. `bitcoind.exe -walletdir=E:\`

Not sure why its using forward slash which is used in Linux
```
2021-05-12T08:05:49Z Using wallet directory E:/
2021-05-12T08:05:49Z init message: Verifying wallet(s)...
2021-05-12T08:05:49Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2021-05-12T08:05:49Z Using wallet E:/wallet.dat
```
    
`bitcoin-cli.exe listwalletdir` returns nothing and cmd prompt running bitcoind starts printing error continuously until I close it.
    
image


Will compile the branch for this PR in some time and two more things that I noticed:

1. `"E:"` works when used with `datadir` but gives error for `walletdir`
2. https://bitcoin.stackexchange.com/questions/103295/unable-to-use-blocks-and-chainstate-from-external-drive

File: src/wallet/db.cpp (hunk 1 above)
Comment (promag) [reply src/wallet/db.cpp:27]: Maybe it should avoid recursion regardless of the error and platform? Is there any case where this approach is not desirable?

**Review by promag — COMMENTED** [review]
Concept ACK.

File: src/wallet/db.cpp (hunk 1 above)
Comment (hebasto) [reply src/wallet/db.cpp:27]: > Maybe it should avoid recursion regardless of the error and platform? Is there any case where this approach is not desirable?

To be sure I understand you correctly, you are suggesting do not iterate a directory if we have any error while accessing it, right?

Comment (promag) [reply src/wallet/db.cpp:27]: Yes, that was my suggestion. Is there any downside of that approach?

**Comment by hebasto** [comment]
Updated bd13ec6d834d4c5f20a5ff9ab41e2e9e86f32d93 -> 29c9e2c2d2015ade47ed4497926363dea3f9c59b ([pr21907.01](https://github.com/hebasto/bitcoin/commits/pr21907.01) -> [pr21907.02](https://github.com/hebasto/bitcoin/commits/pr21907.02), [diff](https://github.com/hebasto/bitcoin/compare/pr21907.01..pr21907.02)):

- addressed @laanwj's [comment](https://github.com/bitcoin/bitcoin/pull/21907#discussion_r630076648) and @promag's [comment](https://github.com/bitcoin/bitcoin/pull/21907#discussion_r630836556)

File: src/wallet/db.cpp (hunk 1 above)
Comment (hebasto) [reply src/wallet/db.cpp]: @laanwj @promag 

Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/21907#issuecomment-839610690).

**Comment by prayank23** [comment]
Compiled branch for this PR

1. `bitcoin-qt.exe -walletdir=E:\` I am able to see some names in File->Open Wallet
2. `bitcoind.exe -walletdir=E:\` and `bitcoin-cli.exe listwalletdir` works fine

```
2021-05-12T13:35:53Z ListDatabases: Access is denied E:/System Volume Information -- skipping.
```

I see few names returned by `listwalletdir`

ACK https://github.com/bitcoin/bitcoin/pull/21907/commits/29c9e2c2d2015ade47ed4497926363dea3f9c59b

Found some issues with weird wallet names but its not related to this PR: https://github.com/bitcoin/bitcoin/issues/21510#issuecomment-839803680

**Review by promag — COMMENTED** [review]
Code review ACK 29c9e2c2d2015ade47ed4497926363dea3f9c59b.

**Review by meshcollider — COMMENTED** [review]
Code review ACK 29c9e2c2d2015ade47ed4497926363dea3f9c59b

**Comment by fanquake** [comment]
Backported to 0.21 in #22255.
