### PR TITLE
getrawtransaction: inform about blockhash argument when lookup fails

### LINKED ISSUE #16142: `getrawtransaction` fails (0.18.0)
`getrawtransaction` fails

Return decoded raw tx

* `bitcoin-qt -prune=8192  -server -rpcuser=rpc -rpcpassword=rpc -onlynet=ipv4 -rpcbind=127.0.0.1:18332 -testnet`
  * BTC 0.18.0
  * `getrawtransaction b423b2b22d6d74376de2887c07f7c84ae890a93d541fcc6dbf3686f2923b2753 1`
image
  * BTC 0.17.1
  * `getrawtransaction b423b2b22d6d74376de2887c07f7c84ae890a93d541fcc6dbf3686f2923b2753 1`
image

Request `getrawtransaction`.

Official from site.

`Linux pentagon 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux`, u5200, 2x8Gb, SSD

QT

### PR DESCRIPTION
**Pull request by darosior**
Just 4 words added on `getrawtransaction` lookup error to fix #16142

### CODE REVIEW

File: src/rpc/rawtransaction.cpp [hunk 1]
```diff
@@ -196,7 +196,7 @@ static UniValue getrawtransaction(const JSONRPCRequest& request)
             }
             errmsg = "No such transaction found in the provided block";
         } else if (!g_txindex) {
-            errmsg = "No such mempool transaction. Use -txindex to enable blockchain transaction queries";
+            errmsg = "No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries";
```
Comment (promag) [inline src/rpc/rawtransaction.cpp]: No strong opinion, but generally I think error messages shouldn't mention arguments or configurations, for that we have the help message.

**Comment by MarcoFalke** [comment]
ACK, could you also update the help text, so that this is not only shown on error?

**Comment by darosior** [comment]
@MarcoFalke it's already in the help text : 
https://github.com/bitcoin/bitcoin/blob/c59e3a32614e627ba2834b032d4799eb69672155/src/rpc/rawtransaction.cpp#L78-L80

File: src/rpc/rawtransaction.cpp (hunk 1 above)
Comment (instagibbs) [reply src/rpc/rawtransaction.cpp]: Is that really a guideline? This seems very helpful, especially as the underlying API changes(no more UTXO lookup)

Comment (promag) [reply src/rpc/rawtransaction.cpp]: For cli usage this might be useful, but for the developer what really matters IMO is the documentation and error code in the response.

I understand the issue regarding the API change, but I'd rather see a documentation improvement than having "hints" in the errors.
