### PR TITLE
qt: Show addresses for "SendToSelf" transactions

### LINKED ISSUE #11464: Payment to yourself shows no address in Qt client
## Issue
When transacting unspent inputs to a new address in own wallet, the qt registers it as 'payment to yourself' without showing the receiving address. That can only be seen in the details or via 'listunspent' command

## Can you reliably reproduce the issue?
Yes

## If so, please list the steps to reproduce below:
1. create raw transaction to own address with multiple inputs
2. send the raw transaction with a miner fee
3. overall balance stays the same minus miner fee, in the transactions tab shows 'payment to yourself' without the receiving address

## Expected behaviour
I'd expect the payment to show up as a received payment with (my own) recipient address and 'payment to self' tag.

## Actual behaviour
Qt client only shows miner fee as 'transacted' and shows what seems to be an empty transaction without a receiving address in the transactions tab.

## Screenshots.

qtweird

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

Core 14.02

### Machine specs:
- OS: Ubuntu 14.04
- CPU: amd
- RAM: 8G
- Disk size: 360Gb
- Disk Type (HD/SDD):Sata

### LINKED ISSUE #12688: Transactions GUI list does not show a transaction from self to self+foreign
For a certain transaction structure the GUI does not show all transactions that occurred.

Perform the following transaction structure to reproduce the bug:

Input: Any owned coins
Output 1: Address not owned by the wallet
Output 2: Address owned by the wallet (generated using the receive payment feature, so it's not a change address)

So there is a payment to someone else and a payment to self. The payment to self is missing in the GUI. Normally, the GUI does list payments to self.

`listtransactions` lists 3 transactions here: The send to the foreign address and a send/receive pair for the payment to self. I don't know if this is correct. I'm mentioning this so that the devs can make sure this is intended.

See transaction `5299f198919d6bd5b9f6d7a5f256b23417cb49ea663828f51cfc1b4d7e69822d` on testnet.

### PR DESCRIPTION
**Pull request by hebasto**
Fix #11464
Fix #12688
Ref: #11471 by jonasschnelli 

Note: change addresses are not recognized (ref: https://github.com/bitcoin/bitcoin/pull/11471#discussion_r180547041)

Result:
screenshot from 2019-01-04 09-06-12

### CODE REVIEW

**Comment by promag** [comment]
I had a different approach based on #12578 which would a row for each *ismine* output.

File: src/qt/transactionrecord.cpp [hunk 1]
```diff
@@ -93,10 +93,14 @@ QList<TransactionRecord> TransactionRecord::decomposeTransaction(const interface
         if (fAllFromMe && fAllToMe)
         {
             // Payment to self
-            CAmount nChange = wtx.change;
+            std::string address = "";
```
Comment (practicalswift) [inline src/qt/transactionrecord.cpp]: Redundant string initialization here: `std::string address;` is enough :-)

**Comment by hebasto** [comment]
@practicalswift thank you for your review.
Your comment has been addressed.

**Comment by hebasto** [comment]
@promag 
> I had a different approach based on #12578 which would a row for each _ismine_ output.

Current #12578 does not help here; see: https://github.com/bitcoin/bitcoin/pull/12578#issuecomment-451733393

**Comment by hebasto** [comment]
Also this PR will fix #12688.
Description has been updated.

**Comment by meshcollider** [comment]
Concept ACK

**Comment by jonasschnelli** [comment]
Needs more review (maybe @fanquake @promag ?)
Since @meshcollider @practicalswift commented, maybe continue with the review (ack/nack/comment).

**Review by meshcollider — COMMENTED** [review]
LGTM, just did a quick code-read 11fdfcf7f940fab48625d102e825a59c16ad4fbc

**Comment by jonasschnelli** [comment]
Tested ACK 11fdfcf7f940fab48625d102e825a59c16ad4fbc

**Comment by fanquake** [comment]
ACK 11fdfcf7f940fab48625d102e825a59c16ad4fbc - did the bare minimum testing.

master ():
master

PR (11fdfcf7f940fab48625d102e825a59c16ad4fbc):
pr
