### PR TITLE
Avoid calling `getnameinfo` when formatting IPv6 addresses in `CNetAddr::ToStringIP`

### LINKED ISSUE #21466: Avoid use of "socket" syscall when formatting IP addresses in CNetAddr::ToString
When fuzzing our codebase in a restricted syscall setup I noticed that calling `CNetAddr::ToString` triggers the use of the `socket` syscall. The syscall is made indirectly via `getnameinfo`.

AFAICT `getnameinfo` is used in our code only to format IPv6 addresses in their "shortened" form. I think our formatting only use case should be possible to fully cover without involving the kernel via `socket` :)

Not a big deal of course, but it would be nice if kept the direct and indirect use of networking related syscalls such as `socket` to functions where they cannot be avoided. That would make reasoning about syscall restrictions and/or application-vs-kernel boundaries somewhat easier. 

The call chain is: `CNetAddr::ToString` > `CNetAddr::ToStringIP` > `getnameinfo` > `gni_host` > `gni_host_inet`  > `gni_host_inet_numeric` > `if_indextoname` > `__opensock` > `socket`.

Live demo:

```
$ FUZZ=netaddress src/test/fuzz/fuzz
…
ERROR: The syscall "socket" (syscall number 41) is not allowed by the syscall sandbox in thread "test". Please report. Exiting.
terminate called without an active exception
==13417== ERROR: libFuzzer: deadly signal
    #0 0x5581be296819 in __sanitizer_print_stack_trace compiler-rt/lib/ubsan/ubsan_diag_standalone.cpp:33
    #1 0x5581be22e9f8 in fuzzer::PrintStackTrace() compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210                                                                                                                                                                                        #2 0x5581be15a14a in fuzzer::Fuzzer::CrashCallback() (.part.48) compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233
    #3 0x5581be20ab47 in fuzzer::Fuzzer::CrashCallback() compiler-rt/lib/fuzzer/FuzzerLoop.cpp:205
    #4 0x5581be20ab47 in fuzzer::Fuzzer::StaticCrashSignalCallback() compiler-rt/lib/fuzzer/FuzzerLoop.cpp:204
    #5 0x7f3139b2089f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1289f)
    #6 0x7f3138526f46 in __libc_signal_restore_set /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80
    #7 0x7f3138526f46 in raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
    #8 0x7f31385288b0 in abort /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:79
    #9 0x7f3139db9956  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x8c956)
    #10 0x7f3139dbfae5  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x92ae5)
    #11 0x7f3139dbfb20 in std::terminate() (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x92b20)
    #12 0x5581bec4e6f7 in (anonymous namespace)::SyscallSandboxDebugSignalHandler(int, siginfo_t*, void*) src/util/syscall_sandbox.cpp:71:5
    #13 0x7f3139b2089f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1289f)
    #14 0x7f313860b076 in socket /build/glibc-2ORdQG/glibc-2.27/socket/../sysdeps/unix/syscall-template.S:78
    #15 0x7f313860b2b0 in __opensock /build/glibc-2ORdQG/glibc-2.27/socket/../sysdeps/unix/sysv/linux/opensock.c:100
    #16 0x7f3138626fd3 in if_indextoname /build/glibc-2ORdQG/glibc-2.27/inet/../sysdeps/unix/sysv/linux/if_index.c:226
    #17 0x7f3138626abd in gni_host_inet_numeric /build/glibc-2ORdQG/glibc-2.27/inet/getnameinfo.c:354
    #18 0x7f3138626abd in gni_host_inet /build/glibc-2ORdQG/glibc-2.27/inet/getnameinfo.c:389
    #19 0x7f3138626abd in gni_host /build/glibc-2ORdQG/glibc-2.27/inet/getnameinfo.c:422
    #20 0x7f3138626abd in getnameinfo /build/glibc-2ORdQG/glibc-2.27/inet/getnameinfo.c:539
    #21 0x5581beab72e3 in CNetAddr::ToStringIP[abi:cxx11]() const src/netaddress.cpp:580:18
…
```

### LINKED ISSUE #21967: cnetaddr_tostring_canonical_ipv6 test fails during `make check` on fresh clone of repo on macOS 10.14
**Expected behavior**
`make check` completes successfully when run on a freshly cloned [Bitcoin Core repo](https://github.com/bitcoin/bitcoin).

**Actual behavior**
`make check` fails with the following errors --

```
test/net_tests.cpp:446: error: in "net_tests/cnetaddr_tostring_canonical_ipv6": check net_addr.ToString() == expected_canonical_representation_output has failed [2001:db8::1:1:1:1:1 != 2001:db8:0:1:1:1:1:1]
test/net_tests.cpp:446: error: in "net_tests/cnetaddr_tostring_canonical_ipv6": check net_addr.ToString() == expected_canonical_representation_output has failed [2001:db8::1:1:1:1:1 != 2001:db8:0:1:1:1:1:1]
test/net_tests.cpp:446: error: in "net_tests/cnetaddr_tostring_canonical_ipv6": check net_addr.ToString() == expected_canonical_representation_output has failed [2001:db8::1:1:1:1:1 != 2001:db8:0:1:1:1:1:1]
test/net_tests.cpp:446: error: in "net_tests/cnetaddr_tostring_canonical_ipv6": check net_addr.ToString() == expected_canonical_representation_output has failed [2001:db8:aaaa:bbbb:cccc:dddd::1 != 2001:db8:aaaa:bbbb:cccc:dddd:0:1]
test/net_tests.cpp:446: error: in "net_tests/cnetaddr_tostring_canonical_ipv6": check net_addr.ToString() == expected_canonical_representation_output has failed [2001:db8:aaaa:bbbb:cccc:dddd::1 != 2001:db8:aaaa:bbbb:cccc:dddd:0:1]
...
...

Leaving test module "Bitcoin Core Test Suite"; testing time: 75790us

*** 5 failures are detected in the test module "Bitcoin Core Test Suite"
make[3]: *** [test/net_tests.cpp.test] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

**To reproduce**
1. Follow the build steps available here -- [build-osx.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md) -- on a macOS 10.14.  Install all required dependencies and the first set of optional dependencies.  Use `Wallet (only SQlite) and GUI Support` configuration.
2. Proceed until the "2. Compile" step under the "Building Bitcoin Core" section, at which point running `make check` will result in the error above.

**System information**

Not running Core yet; this is a build time issue when running `make check` on the bitcoin repo cloned from https://github.com/bitcoin/bitcoin/ master branch at commit c8571486364d6e9ca8c86bd1c81e230ca64f8904.

```
$ ./src/bitcoind -version
Bitcoin Core version v21.99.0-1ef34ee25ed3
```

System Version:	macOS 10.14.6 (18G8022)
Processor Name:	Intel Core i5
  Processor Speed:	1.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB
File System:	APFS
Physical Drive:
  Device Name:	APPLE SSD AP0128N
  Media Name:	AppleAPFSMedia
  Medium Type:	SSD
  Protocol:	PCI-Express

### PR DESCRIPTION
**Pull request by practicalswift**
Avoid calling `getnameinfo` when formatting IPv6 addresses in `CNetAddr::ToStringIP`.

Fixes #21466.
Fixes #21967.

The IPv4 case was fixed in #21564.

### CODE REVIEW

**Comment by laanwj** [comment]
Concept ACK

**Review by vasild — APPROVED** [review]
ACK 54548bae8004a8f49d73bd29aeca8b41894214c4

**Review by Subawit — APPROVED** [review]

**Comment by ssb402** [comment]
ACK c10f27fdb2d335954dd1017ce6d5800159427374

I've reviewed the code and it looks good.  Also ran unit tests and `make check` completes successfully.

**Comment by practicalswift** [comment]
@shobitb Thanks a lot for reviewing! I think you might have gotten the commit id wrong when ACK:ing. The last commit id in the sequence of commits is the one used when ACK:ing a PR assuming one ACK:s the entire PR and not just a subset of it :)

**Comment by laanwj** [comment]
Code review ACK 54548bae8004a8f49d73bd29aeca8b41894214c4
It at first surprised me that there are no tests for `IPv6ToString`. However there are for the higher-level functions. As this passes the CNetAddr ToString, I think this is covered sufficiently.

File: src/netaddress.cpp [hunk 1]
```diff
@@ -578,15 +615,6 @@ std::string CNetAddr::ToStringIP() const
     case NET_IPV4:
         return IPv4ToString(m_addr);
     case NET_IPV6: {
-        CService serv(*this, 0);
-        struct sockaddr_storage sockaddr;
-        socklen_t socklen = sizeof(sockaddr);
-        if (serv.GetSockAddr((struct sockaddr*)&sockaddr, &socklen)) {
-            char name[1025] = "";
-            if (!getnameinfo((const struct sockaddr*)&sockaddr, socklen, name,
```
Comment (jonatack) [inline src/netaddress.cpp:586]: Was removing link-local scoped id functionality an intended consequence of this PR?

Comment (practicalswift) [reply src/netaddress.cpp:586]: https://github.com/bitcoin/bitcoin/issues/21982#issuecomment-842325937

Comment (laanwj) [reply src/netaddress.cpp:586]: If we want to restore that functionality we could pass `m_scope_id` to `IPv6ToString` and append it if non-zero.

**Comment by jonatack** [comment]
According to https://github.com/bitcoin/bitcoin/issues/21982#issuecomment-842325937, no longer returning scoped ids was an intentional part of this PR. Maybe that wasn't obvious to reviewers. After test coverage was removed by #21689, no other tests signalled the change.

It would be good to be more explicit in the PR description regarding why make the change, and straightforward about what support was being dropped.

**Comment by vasild** [comment]
There seems to be two "functionalities" being discussed together, it took me some time to figure it out:

1. The functionality of IPv6 scope id, introduced in https://github.com/bitcoin/bitcoin/pull/7570. That is still working, has not been removed.
2. The printout of such IPv6 addresses - before we used the system `getnameinfo()` which included `%zoneid` (on all or most platforms). Now we roll our own which does not include `%zoneid`.

For reference, here is the FreeBSD implementation of `getnameinfo()` (which is under... eh... the BSD license):

https://github.com/freebsd/freebsd-src/blob/c232fd4b4191a722f8c3193ef1e7c6efd8385182/lib/libc/net/getnameinfo.c#L43-L46

https://github.com/freebsd/freebsd-src/blob/c232fd4b4191a722f8c3193ef1e7c6efd8385182/lib/libc/net/getnameinfo.c#L358-L375

https://github.com/freebsd/freebsd-src/blob/c232fd4b4191a722f8c3193ef1e7c6efd8385182/sys/netinet6/in6.h#L296-L297

**Comment by practicalswift** [comment]
@vasild 

Exactly. Thanks for bringing some sense to this.

What this entire discussion boils down to if the expectation is that `CNetAddr::ToStringIP()` should print the IPv6 _address_ or the IPv6 _socket address_:
* IPv6 address ([std::net::Ipv6Addr](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html)): _"IPv6 addresses are defined as 128-bit integers in IETF RFC 4291. They are usually represented as eight 16-bit segments."_
* IPv6 socket address ([std::net::SocketAddrV6](https://doc.rust-lang.org/std/net/struct.SocketAddrV6.html)): _"IPv6 socket addresses consist of an IPv6 address, a 16-bit port number, as well as fields containing the traffic class, the flow label, and a scope identifier (see IETF RFC 2553, Section 3.3 for more details)."_

**Comment by jonatack** [comment]
Indeed. What does not make sense to me is why this PR was not upfront about this, nor the reasons that were given to have the only test coverage removed willy-nilly allowing this to be changed without tests warning about it, nor why we should break user space to follow the rustlang version without discussion. If those questions do not make sense, then I apologize.

**Comment by jonatack** [comment]
The comment I referred to above in https://github.com/bitcoin/bitcoin/issues/21982#issuecomment-842325937:

> If you by "functionality" mean not appending an unwanted %zone_index string to CNetAddr::ToString(), then yes that non-appending of an unwanted string is obviously intentional. The new implementation of IPv6ToString (which is called from CNetAddr::ToString) follows Rust's std::net::Ipv6Addr which does not append %zone_index. FWIW that is how the previous implementation of CNetAddr::ToString worked under macOS.

Yes, as the removed test and as #21690 showed, macOS returns a different getnameinfo format for scoped ids, without the zone id, from all the other platforms that do provide support for it.  Why should we align with the macOS exception without discussing it?  Does it not make sense to call attention to this change?

**Comment by vasild** [comment]
It should be easy to append `%zoneid` like @laanwj [suggests](https://github.com/bitcoin/bitcoin/pull/21756#discussion_r633592556)?

**Comment by jonatack** [comment]
> It should be easy to append `%zoneid` like @laanwj [suggests](https://github.com/bitcoin/bitcoin/pull/21756#discussion_r633592556)?

#21985
