### PR TITLE
gui: Fix start timer from non QThread

### LINKED ISSUE #16296: gui: crash with loadwallet & QT_FATAL_WARNINGS
Pretty sure this should be low priority, just keeping a record because there's been some discussion around using `QT_FATAL_WARNINGS=1` during debugging.

```log
2019-06-27T07:23:13Z init message: Done loading
2019-06-27T07:23:13Z GUI: Platform customization: "macosx"
2019-06-27T07:23:17Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2019-06-27T07:23:17Z Using wallet /Users/michael/Library/Application Support/Bitcoin/testing
2019-06-27T07:23:17Z BerkeleyEnvironment::Open: LogDir=/Users/michael/Library/Application Support/Bitcoin/testing/database ErrorFile=/Users/michael/Library/Application Support/Bitcoin/testing/db.log
2019-06-27T07:23:17Z init message: Loading wallet...
2019-06-27T07:23:17Z BerkeleyEnvironment::Open: LogDir=/Users/michael/Library/Application Support/Bitcoin/testing/database ErrorFile=/Users/michael/Library/Application Support/Bitcoin/testing/db.log
2019-06-27T07:23:17Z [testing] nFileVersion = 189900
2019-06-27T07:23:17Z [testing] Keys: 0 plaintext, 2001 encrypted, 2001 w/ metadata, 2001 total. Unknown wallet records: 0
2019-06-27T07:23:17Z [testing] Wallet completed loading in             113ms
2019-06-27T07:23:17Z GUI: QObject::startTimer: Timers can only be used with threads started with QThread
```

```bash
src/bitcoin-cli loadwallet testing
```

```bash
lldb src/qt/bitcoin-qt
(lldb) target create "src/qt/bitcoin-qt"
Current executable set to 'src/qt/bitcoin-qt' (x86_64).
(lldb) env QT_FATAL_WARNINGS=1
(lldb) run
Process 19523 launched: '/Users/michael/github/bitcoin/src/qt/bitcoin-qt' (x86_64)
2019-06-27 15:23:04.327755+0800 bitcoin-qt[19523:550417] MessageTracer: Falling back to default whitelist
Process 19523 stopped
* thread #21, name = 'bitcoin-httpworker.0', stop reason = signal SIGABRT
    frame #0: 0x00007fff593ec2c6 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff593ec2c6 <+10>: jae    0x7fff593ec2d0            ; <+20>
    0x7fff593ec2c8 <+12>: movq   %rax, %rdi
    0x7fff593ec2cb <+15>: jmp    0x7fff593e6457            ; cerror_nocancel
    0x7fff593ec2d0 <+20>: retq   
Target 0: (bitcoin-qt) stopped.
```

### PR DESCRIPTION
**Pull request by promag**
Fixes #16296.

### CODE REVIEW

**Review by hebasto — COMMENTED** [review]
Concept ACK

**Comment by emilengler** [comment]
Concept ACK

File: src/qt/walletmodel.cpp [hunk 1]
```diff
@@ -57,6 +52,14 @@ WalletModel::~WalletModel()
     unsubscribeFromCoreSignals();
 }
 
+void WalletModel::init()
```
Comment (hebasto) [inline src/qt/walletmodel.cpp]: nit: Could slot name be more expressive, as it initiates regular polling?

**Review by hebasto — APPROVED** [review]
ACK af0eeba79da7b387731a41fb05c382a9e4b41a5f, tested on:
- Linux Mint 19.2, Qt 5.9.5
- macOS 10.13.6, Qt 5.11.2

There is no more `QTimer` warnings during `loadwallet` via `bitcoin-cli` RPC call.

File: src/qt/walletmodel.cpp (hunk 1 above)
Comment (promag) [reply src/qt/walletmodel.cpp]: Yeah like `startPollBalance`?

Comment (hebasto) [reply src/qt/walletmodel.cpp]: Yup ;)

**Comment by promag** [comment]
Renamed `init` to `startPollBalance` and asserted `QMetaObject::invokeMethod` result for Qt < 5.10..

**Comment by hebasto** [comment]
@promag 

> Renamed `init` to `startPollBalance` and asserted `QMetaObject::invokeMethod` result for Qt < 5.10..

Why for Qt < 5.10 only?

**Comment by promag** [comment]
@hebasto because for Qt >= 5.10 the `invokeMethod` is compiler checked.

**Comment by hebasto** [comment]
@promag 

> because for Qt >= 5.10 the `invokeMethod` is compiler checked.

To be pedantic, a compiler just checks a lambda body in your code ;)

A compiler checked overloaded `invokeMethod` function is:

```
QMetaObject::invokeMethod(wallet_model, &WalletModel::startPollBalance, Qt::QueuedConnection);
```

More details:
- [Add QMetaObject::invokeMethod() overloads for function pointers](https://codereview.qt-project.org/c/qt/qtbase/+/182339)
- https://forum.qt.io/topic/83278/qt5-invokemethod/4

As `startPollBalance()` slot does not accept parameters, the mentioned above `invokeMethod()` call without lambda seems cleaner, IMO ;)

File: src/qt/walletcontroller.cpp [hunk 2]
```diff
@@ -108,6 +108,13 @@ WalletModel* WalletController::getOrCreateWallet(std::unique_ptr<interfaces::Wal
     wallet_model->setParent(this);
     m_wallets.push_back(wallet_model);
 
+#if QT_VERSION < QT_VERSION_CHECK(5, 10, 0)
```
Comment (laanwj) [inline src/qt/walletcontroller.cpp]: There's a risk in implementing this twice. It's not strictly necessary because the pre-5.10 code will work fine on newer Qt. Might just as well remove the `#if` imo.

Comment (promag) [reply src/qt/walletcontroller.cpp]: Just wanted to make it easier for when we bump Qt. But will remove considering there are other places that would benefit the same approach.

**Comment by promag** [comment]
Dropped `Qt::QueuedConnection` as the default `Qt::AutoConnection` is enough. Also added comment.

File: src/qt/walletcontroller.cpp (hunk 2 above)
Comment (laanwj) [reply src/qt/walletcontroller.cpp]: I understand, but I think it's better to change these (if desired) when bumping the *minimum supported* Qt version. Don't introduce conditional compilation when not necessary.

Comment (promag) [reply src/qt/walletcontroller.cpp]: Done :+1:

**Comment by MarcoFalke** [comment]
How can this be tested?

**Comment by promag** [comment]
@MarcoFalke without this change:
 - `bitcoin-qt -regtest -server`
 - generate coins
 - `bitcoin-cli -regtest createwallet test`
 - `bitcoin-cli -regtest -rpcwallet=test getnewaddress`
 - `bitcoin-cli -regtest -rpcwallet="" sendtoaddress` with the above address
 - check that balance hasn't changed in the test wallet GUI

**Comment by hebasto** [comment]
Could a functional test be added to prevent regressions in the future?

File: src/qt/walletcontroller.cpp (hunk 2 above)
Comment (laanwj) [reply src/qt/walletcontroller.cpp]: Thanks!

**Comment by laanwj** [comment]
A functional test cannot help with testing this GUI functionality.

**Comment by laanwj** [comment]
code review ACK a8f5026d6d992fd8d72908c848c5028f0f9a8cd1

File: src/qt/walletcontroller.cpp [hunk 3]
```diff
@@ -108,6 +108,12 @@ WalletModel* WalletController::getOrCreateWallet(std::unique_ptr<interfaces::Wal
     wallet_model->setParent(this);
     m_wallets.push_back(wallet_model);
 
+    // WalletModel::startPollBalance needs to be called in a thread managed by
```
Comment (laanwj) [inline src/qt/walletcontroller.cpp]: Are you sure this comment is correct? Doesn't `QTimer(self)`, as the timer is intended to end up in the event loop of the GUI thread, need to be called from the GUI thread?

(the fix is correct in any case)

Comment (promag) [reply src/qt/walletcontroller.cpp]: > as the timer is intended to end up in the event loop of the GUI thread

Yes this is the case at the moment, but probably will be moved to other thread, like #17135 (same thread maybe doesn't matter now).

Either way `startTimer` can't be called from a RPC thread.
