### PR TITLE
Fix crash via division by zero assertion

### LINKED ISSUE #11501: Assertion fail when opening coin control dialog
#### If so, please list the steps to reproduce below:
1. Enable coin control features in Settings
2. Click Inputs... on Send tab

### Expected behaviour
Coin inputs dialog apears

### Actual behaviour
Crash with message

`bitcoin-qt: qt/coincontroldialog.cpp:585: static void CoinControlDialog::updateLabels(WalletModel*, QDialog*): Assertion `nBytes != 0' failed.`

### What version of bitcoin-core are you using?

master. 6ab0e4cf49549640b903bf5fce0e6035b8116397 or a865b38bf33202b66ee2e72912fe164aa2a504c7

### Any extra information that might be useful in the debugging process.

Reverting to 892809309c1bc370677241a715e57a2744f94323 fixes the problem

### PR DESCRIPTION
**Pull request by jonasschnelli**
Replaces the newly added `assert` for a devision by zero protection by a control structure. Floating point division by zero is defined by the floating point standard and results in +inf or -inf.

Introduced in #11133
Reported by @mzhou, fixes #11501

### CODE REVIEW

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/207408b0889caf3f5986bde4b122dbece1ed0dac

**Comment by practicalswift** [comment]
ACK 207408b0889caf3f5986bde4b122dbece1ed0dac :-)

File: src/qt/coincontroldialog.cpp [hunk 1]
```diff
@@ -582,8 +582,7 @@ void CoinControlDialog::updateLabels(WalletModel *model, QDialog* dialog)
     QString toolTipDust = tr("This label turns red if any recipient receives an amount smaller than the current dust threshold.");
 
     // how many satoshis the estimated fee can vary per byte we guess wrong
-    assert(nBytes != 0);
-    double dFeeVary = (double)nPayFee / nBytes;
+    double dFeeVary = (nBytes != 0) ? (double)nPayFee / nBytes : 0;
```
Comment (promag) [inline src/qt/coincontroldialog.cpp]: Nit, like above in line 567:
```cpp
double dFeeVary = nBytes > 0 ? (double)nPayFee / nBytes : 0;
```

**Review by promag — COMMENTED** [review]
utACK 207408b.

**Comment by laanwj** [comment]
> Floating point division by zero is defined by the floating point standard and results in +inf or -inf.

Indeed, floating point division by zero is well-defined in IEEE 754 which all current platforms implement.
