### PR TITLE
wallet: Avoid requesting fee rates multiple times during coin selection

### LINKED ISSUE #19229: Transaction fee and change calculation failed... using v0.21.0 binary
After upgrade of binary bitcoind from 0.19.1 to 0.20.0 could not process transactions. Did not see anything in release notes that would be breaking. Any idea what could be the issue? I cant find any documentation on this error message.

**Expected behavior**

Process transaction without error using "sendtoaddress"

**Actual behavior**

error code -4 "Transaction fee and change calculation failed"

**To reproduce**

All we did was upgrade binary bitcoind from 0.19.1 to v0.20.0. Nothing else changed.

**System information**

Using binary from https://bitcoincore.org/bin/bitcoin-core-0.20.0/bitcoin-0.20.0-x86_64-linux-gnu.tar.gz

On Linux Ubuntu 18.04.3 LTS on a SSD

No ERRORs exist in debug.log. Node syncs fine on v0.20.0... The following seems relevant but we saw same logs on v0.19.1.

**v0.19.1...**

2020-06-09T07:51:36Z [default wallet] Fee Calculation: Fee:2871 Bytes:136 Needed:2871 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99931: Estimation: (20593.8 - 21623.5) 97.20% 37504.3/(38582.5 0 mem 3.0 out) Fail: (19613.1 - 20593.8) 92.07% 24792.5/(26908.8 0 mem 19.2 out)
2020-06-09T07:54:32Z [default wallet] Fee Calculation: Fee:13110 Bytes:621 Needed:13110 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99931: Estimation: (20593.8 - 21623.5) 97.20% 37504.3/(38582.5 0 mem 3.0 out) Fail: (19613.1 - 20593.8) 92.07% 24792.5/(26908.8 0 mem 19.2 out)
2020-06-09T09:58:09Z [default wallet] Fee Calculation: Fee:7326 Bytes:347 Needed:7326 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99931: Estimation: (20593.8 - 21623.5) 97.39% 40008.9/(41076.7 0 mem 3.0 out) Fail: (19613.1 - 20593.8) 92.28% 25270.9/(27366.8 0 mem 19.0 out)
2020-06-09T13:22:31Z [default wallet] Fee Calculation: Fee:16956 Bytes:803 Needed:16956 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99931: Estimation: (20593.8 - 21623.5) 97.64% 43671.2/(44725.9 0 mem 3.0 out) Fail: (19613.1 - 20593.8) 92.48% 25689.0/(27759.1 0 mem 18.8 out)
2020-06-09T14:36:45Z [default wallet] Fee Calculation: Fee:54877 Bytes:2255 Needed:54877 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (23839.9 - 25031.9) 98.23% 3643.5/(3709.2 0 mem 0.0 out) Fail: (22704.7 - 23839.9) 81.84% 2485.0/(3036.6 0 mem 0.0 out)
2020-06-09T15:33:30Z [default wallet] Fee Calculation: Fee:5709 Bytes:258 Needed:5709 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (21623.5 - 22704.7) 88.84% 3368.3/(3791.3 0 mem 0.0 out) Fail: (20593.8 - 21623.5) 77.45% 3045.0/(3928.4 0 mem 3.2 out)
2020-06-09T16:06:13Z [default wallet] Fee Calculation: Fee:90020 Bytes:4068 Needed:90020 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (21623.5 - 22704.7) 88.87% 3127.1/(3518.6 0 mem 0.0 out) Fail: (20593.8 - 21623.5) 77.48% 2822.9/(3640.5 0 mem 2.9 out)
2020-06-09T18:16:54Z [default wallet] Fee Calculation: Fee:7683 Bytes:347 Needed:7683 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (21623.5 - 22704.7) 92.06% 3166.4/(3439.3 0 mem 0.0 out) Fail: (20593.8 - 21623.5) 82.08% 2307.7/(2809.5 0 mem 2.1 out)
2020-06-09T18:28:31Z [default wallet] Fee Calculation: Fee:11759 Bytes:531 Needed:11759 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (21623.5 - 22704.7) 92.58% 3152.3/(3404.9 0 mem 0.0 out) Fail: (20593.8 - 21623.5) 82.64% 2219.5/(2683.9 0 mem 2.0 out)
2020-06-09T18:53:50Z [default wallet] Fee Calculation: Fee:11716 Bytes:529 Needed:11716 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (21623.5 - 22704.7) 93.28% 3003.3/(3219.7 0 mem 0.0 out) Fail: (20593.8 - 21623.5) 83.47% 2016.6/(2414.3 0 mem 1.7 out)
2020-06-09T19:18:43Z [default wallet] Fee Calculation: Fee:4962 Bytes:224 Needed:4962 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (21623.5 - 22704.7) 93.59% 2925.7/(3126.0 0 mem 0.0 out) Fail: (20593.8 - 21623.5) 83.74% 1903.9/(2272.0 0 mem 1.6 out)

**v0.20.0 ...**

2020-06-09T20:18:06Z [default wallet] Fee Calculation: Fee:2829 Bytes:134 Needed:2829 Tgt:6 (requested 6) Reason:"Conservative Double Target longer horizon" Decay 0.99931: Estimation: (20593.8 - 21623.5) 97.79% 45111.8/(46130.7 0 mem 2.9 out) Fail: (19613.1 - 20593.8) 93.00% 26822.9/(28822.8 0 mem 18.2 out)

**v0.19.1...**

2020-06-09T21:44:39Z [default wallet] Fee Calculation: Fee:7372 Bytes:349 Needed:7372 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (20593.8 - 21623.5) 91.12% 2121.8/(2327.6 0 mem 0.9 out) Fail: (19613.1 - 20593.8) 83.14% 777.5/(935.0 0 mem 0.1 out)
2020-06-09T21:45:57Z [default wallet] Fee Calculation: Fee:7330 Bytes:347 Needed:7330 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (20593.8 - 21623.5) 91.12% 2121.8/(2327.6 0 mem 0.9 out) Fail: (19613.1 - 20593.8) 83.14% 777.5/(935.0 0 mem 0.1 out)
2020-06-09T21:50:48Z [default wallet] Fee Calculation: Fee:36125 Bytes:1710 Needed:36125 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (20593.8 - 21623.5) 91.12% 2121.8/(2327.6 0 mem 0.9 out) Fail: (19613.1 - 20593.8) 83.14% 777.5/(935.0 0 mem 0.1 out)
2020-06-09T22:04:02Z [default wallet] Fee Calculation: Fee:4775 Bytes:226 Needed:4775 Tgt:6 (requested 6) Reason:"Target 85% Threshold" Decay 0.96200: Estimation: (20593.8 - 21623.5) 92.53% 2369.9/(2560.4 0 mem 0.8 out) Fail: (19613.1 - 20593.8) 84.30% 783.4/(929.1 0 mem 0.1 out)

### PR DESCRIPTION
**Pull request by achow101**
During coin selection, there are various places where we need to have a feerate. We need the feerate for the transaction itself, the discard fee rate, and long term feerate. Fetching these each time we need them can lead to a race condition where two feerates that should be the same are actually different. One particular instance where this can happen is during the loop in `CreateTransactionInternal`. After inputs are chosen, the expected transaction fee is calculated using a newly fetched feerate. If `pick_new_inputs == false`, the loop will go again with the assumption that the fee for the transaction remains the same. However because the feerate is fetched again, it is possible that it actually isn't and this causes coin selection to fail.

Instead of fetching the feerate each time it is needed, we fetch them all at once at the top of `CreateTransactionInternal`, store them in `CoinSelectionParams`, and use them where needed.

While some of these fee rates probably don't need this caching, I've done it for consistency and the guarantee that they remain the same.

Fixes #19229

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK, was thinking about this as well

**Comment by meshcollider** [comment]
Concept / light-look-through ACK

File: src/wallet/wallet.h [hunk 1]
```diff
@@ -607,16 +607,18 @@ struct CoinSelectionParams
...
     size_t change_spend_size = 0;
     CFeeRate effective_fee = CFeeRate(0);
+    CFeeRate m_long_term_feerate = CFeeRate(0);
     size_t tx_noinputs_size = 0;
     //! Indicate that we are subtracting the fee from outputs
     bool m_subtract_fee_outputs = false;
     bool m_avoid_partial_spends = false;
 
-    CoinSelectionParams(bool use_bnb, size_t change_output_size, size_t change_spend_size, CFeeRate effective_fee, size_t tx_noinputs_size, bool avoid_partial) :
+    CoinSelectionParams(bool use_bnb, size_t change_output_size, size_t change_spend_size, CFeeRate effective_fee, CFeeRate long_term_feerate, size_t tx_noinputs_size, bool avoid_partial) :
```
Comment (ryanofsky) [inline src/wallet/wallet.h]: In commit "wallet: Move long term feerate setting to CreateTransaction" (d3191194a8ced53ae511551dce1321c0416d9e6d)

In this commit and next commit, usage of SelectCoins is now more error prone because caller is responsible for setting `m_long_term_feerate` and `m_discard_feerate` variables in some cases (in other cases they are apparently never used), and there's not documentation about when to set them. Also these changes add to a proliferation of CoinSelectionParams constructor arguments can get easily confused together.

A safer approach might be to make these `std::optional<CFeeRate>` members instead of `CFeeRate` members so the CoinSelectionParams constructor doesn't have to be involved with them at all. Then they can be directly set by name, and explicit errors will be triggered if they are ever accessed without being set.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 7b4b48f6aa186d878984ae14727e5fa203f0d9b6. What a fucking horror show this code is! But overall the change does make it better. I left some suggestions below, but they're not important so feel free to ignore!

File: src/wallet/wallet.h (hunk 1 above)
Comment (achow101) [reply src/wallet/wallet.h]: The constructor parameters are more to make the tests easier to implement.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -2814,6 +2814,11 @@ bool CWallet::CreateTransactionInternal(
                 error = strprintf(_("Fee rate (%s) is lower than the minimum fee rate setting (%s)"), coin_control.m_feerate->ToString(FeeEstimateMode::SAT_VB), nFeeRateNeeded.ToString(FeeEstimateMode::SAT_VB));
                 return false;
             }
+            if (feeCalc.reason == FeeReason::FALLBACK && !m_allow_fallback_fee) {
+                // eventually allow a fallback fee
+                error = _("Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -fallbackfee.");
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp:2813]: Will update the commit message if I have to retouch.

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -2807,11 +2807,11 @@ bool CWallet::CreateTransactionInternal(
             CFeeRate discard_rate = GetDiscardRate(*this);
 
             // Get the fee rate to use effective values in coin selection
-            CFeeRate nFeeRateNeeded = GetMinimumFeeRate(*this, coin_control, &feeCalc);
+            coin_selection_params.effective_fee = GetMinimumFeeRate(*this, coin_control, &feeCalc);
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp:2804]: Will update the commit message if I have to retouch.

File: src/wallet/wallet.h [hunk 4]
```diff
@@ -607,16 +607,20 @@ struct CoinSelectionParams
...
     CFeeRate effective_fee = CFeeRate(0);
+    CFeeRate m_long_term_feerate = CFeeRate(0);
+    CFeeRate m_discard_feerate = CFeeRate(0);
     size_t tx_noinputs_size = 0;
     //! Indicate that we are subtracting the fee from outputs
     bool m_subtract_fee_outputs = false;
     bool m_avoid_partial_spends = false;
 
-    CoinSelectionParams(bool use_bnb, size_t change_output_size, size_t change_spend_size, CFeeRate effective_fee, size_t tx_noinputs_size, bool avoid_partial) :
+    CoinSelectionParams(bool use_bnb, size_t change_output_size, size_t change_spend_size, CFeeRate effective_fee, CFeeRate long_term_feerate, CFeeRate discard_feerate, size_t tx_noinputs_size, bool avoid_partial) :
```
Comment (luke-jr) [inline src/wallet/wallet.h:617]: I suggest not expanding the monster constructor here. Overall code readability seems to improve just assigning the new members after construction.

Comment (achow101) [reply src/wallet/wallet.h:617]: See https://github.com/bitcoin/bitcoin/pull/21083#discussion_r579457178

**Comment by fjahr** [comment]
Code review ACK 7b4b48f6aa186d878984ae14727e5fa203f0d9b6

The code is definitely an improvement and can be merged as-is.

Looking at #19229 I was skeptical initially that this would fix it fully because, even though nobody said It explicitly, I assume some people have tried running the command multiple times. It sounded like it was a particular tx that caused these issues, rather than it just happening inconsistently on different txs which would seem more reasonable if a volatile fee market is the cause for this. But I have stared at the code for a pretty long time now (particularly the `subtractfeefromamount` scenario because that was mentioned several times in #19229) and I couldn't find another edge case that might cause this error. So I think the best path forward is to try and see if this code fixes the issue for those that have observed it. At least one user has already indicated in #19229 that they didn't see the issue again after running this PR so that's a good sign.

**Comment by chappjc** [comment]
> even though nobody said It explicitly, I assume some people have tried running the command multiple times

That's correct, @fjahr, we have observed that a retry can still be met with the error.  Bad luck maybe?

If a 0.21 backport branch were available, I might be able to try this out.

File: src/wallet/wallet.h (hunk 4 above)
Comment (achow101) [reply src/wallet/wallet.h]: I've tried to make it more readable. However I also think that setting all of these things should be set in the constructor and that the current thing where we set all the parameters ad-hoc is not a good design.

File: src/wallet/wallet.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp:2804]: Updated the commit message

File: src/wallet/wallet.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp:2813]: Updated the commit message

**Comment by achow101** [comment]
@chappjc Here is a branch of this PR backported to 0.21: https://github.com/achow101/bitcoin/tree/0.21-createtx-same-feerate

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (Xekyo) [inline src/wallet/wallet.cpp:2805]: It seems to me that `effective_fee` is a feerate, not a fee.

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -2804,17 +2798,28 @@ bool CWallet::CreateTransactionInternal(
...
+            }
+            if (feeCalc.reason == FeeReason::FALLBACK && !m_allow_fallback_fee) {
+                // eventually allow a fallback fee
+                error = _("Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -fallbackfee.");
                 return false;
             }
 
+            // Get long term estimate
+            CCoinControl cc_temp;
+            cc_temp.m_confirm_target = 1008;
```
Comment (glozow) [inline src/wallet/wallet.cpp:2820]: Since you're touching this, seems appropriate to have magic numbers like this be `static const`

**Review by murchandamus — COMMENTED** [review]
Code Review ACK (https://github.com/bitcoin/bitcoin/pull/21083/commits/cb93fbda152fe7427502b41ad897f40be13fc33b)

Great improvement! Please do rename the `effective_fee` to `effective_feerate`, though, if you have to update again.

File: src/wallet/wallet.h [hunk 6]
```diff
@@ -607,16 +607,21 @@ struct CoinSelectionParams
     size_t change_output_size = 0;
     size_t change_spend_size = 0;
     CFeeRate effective_fee = CFeeRate(0);
+    CFeeRate m_long_term_feerate = CFeeRate(0);
+    CFeeRate m_discard_feerate = CFeeRate(0);
```
Comment (glozow) [inline src/wallet/wallet.h:611]: `CFeeRate` default constructor gives it a 0, so this is not needed in the declaration
```suggestion
    CFeeRate m_long_term_feerate;
    CFeeRate m_discard_feerate;
```

**Review by glozow — COMMENTED** [review]
utACK https://github.com/bitcoin/bitcoin/commit/cb93fbda152fe7427502b41ad897f40be13fc33b

I think this is a good change but actually could go a lot further, heh. In my opinion everything in `CoinSelectionParams` should be `const` and grabbed before coin selection begins. And a second attempt (e.g. not using bnb anymore) can be a copy/move of the first set of params.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (achow101) [reply src/wallet/wallet.cpp:2805]: Renamed to `m_effective_feerate`.

File: src/wallet/wallet.cpp (hunk 5 above)
Comment (achow101) [reply src/wallet/wallet.cpp]: Changed to use the function we have to fetch the maximum confirmation target.

File: src/wallet/wallet.h (hunk 6 above)
Comment (achow101) [reply src/wallet/wallet.h]: done

File: src/wallet/test/coinselector_tests.cpp [hunk 7]
```diff
@@ -35,7 +35,10 @@ static CAmount balance = 0;
 CoinEligibilityFilter filter_standard(1, 6, 0);
 CoinEligibilityFilter filter_confirmed(1, 1, 0);
 CoinEligibilityFilter filter_standard_extra(6, 6, 0);
-CoinSelectionParams coin_selection_params(false, 0, 0, CFeeRate(0), 0, false);
+CoinSelectionParams coin_selection_params(/* use_bnb= */ false, /* change_output_size= */ 0,
+                                          /* change_spend_size= */ 0, /* effective_fee= */ CFeeRate(0),
```
Comment (glozow) [inline src/wallet/test/coinselector_tests.cpp:39]: 👀

Comment (achow101) [reply src/wallet/test/coinselector_tests.cpp:39]: Oops. Fixed.

File: src/wallet/wallet.h [hunk 8]
```diff
@@ -606,17 +606,22 @@ struct CoinSelectionParams
...
     bool m_avoid_partial_spends = false;
 
-    CoinSelectionParams(bool use_bnb, size_t change_output_size, size_t change_spend_size, CFeeRate effective_fee, size_t tx_noinputs_size, bool avoid_partial) :
+    CoinSelectionParams(bool use_bnb, size_t change_output_size, size_t change_spend_size, CFeeRate effective_feerate,
+                        CFeeRate long_term_feerate, CFeeRate discard_feerate, size_t tx_noinputs_size, bool avoid_partial) :
         use_bnb(use_bnb),
         change_output_size(change_output_size),
         change_spend_size(change_spend_size),
-        effective_fee(effective_fee),
+        m_effective_feerate(effective_feerate),
```
Comment (Xekyo) [inline src/wallet/wallet.h:622]: Should perhaps all of these now start with `m_`?

**Review by murchandamus — COMMENTED** [review]
tACK https://github.com/bitcoin/bitcoin/pull/21083/commits/f9cd2bfbccb7a2b8ff07cec5f6d2adbeca5f07c3

File: src/wallet/wallet.h (hunk 8 above)
Comment (glozow) [reply src/wallet/wallet.h:622]: 👍 Good for followup?

Comment (achow101) [reply src/wallet/wallet.h:622]: They should, but that's an unrelated change. The newly added members use `m_`.

**Comment by glozow** [comment]
reACK https://github.com/bitcoin/bitcoin/commit/f9cd2bfbccb7a2b8ff07cec5f6d2adbeca5f07c3

Changes since last review:
- Rename effective_fee to m_effective_feerate
- Remove unnecessary `CFeeRate(0)`s in declaration
- Grab long term target from `longStats` instead of hard-coding 1008

**Comment by fjahr** [comment]
Code review re-ACK f9cd2bfbccb7a2b8ff07cec5f6d2adbeca5f07c3

Checked range-diff since last review.

**Review by meshcollider — COMMENTED** [review]
Code review + test run ACK f9cd2bfbccb7a2b8ff07cec5f6d2adbeca5f07c3

**Comment by fjahr** [comment]
> > even though nobody said It explicitly, I assume some people have tried running the command multiple times
> 
> That's correct, @fjahr, we have observed that a retry can still be met with the error. Bad luck maybe?
> 
> If a 0.21 backport branch were available, I might be able to try this out.

@chappjc please let us still know how it's going. Thanks!

**Comment by chappjc** [comment]
I haven't been able to test in our use case, but incidentally the error has been rare lately even with release.  I will provide feed back when possible.

**Comment by fanquake** [comment]
> Here is a branch of this PR backported to 0.21: https://github.com/achow101/bitcoin/tree/0.21-createtx-same-feerate

@achow101 did you want to open a PR to 0.21 with this branch?

**Comment by achow101** [comment]
> @achow101 did you want to open a PR to 0.21 with this branch?

Done in #21520
