### PR TITLE
net: fix remaining net assertions

### LINKED ISSUE #9212: Assertion failed: (nSendVersion != 0), function GetSendVersion, file ./net.h, line 775.
Current master on testnet:

```
2016-11-23 13:28:25 AcceptToMemoryPool: peer=1: accepted facb01dba78b58bcd4a2edd4edecf71816075e1ae5e2e66f886e82a7798ccac5 (poolsz 55 txn, 183 kB)
2016-11-23 13:28:25 received: version (111 bytes) peer=2
2016-11-23 13:28:25 peer=2 does not offer the expected services (00000001 offered, 00000009 expected); disconnecting
2016-11-23 13:28:25 sending reject (45 bytes) peer=2
2016-11-23 13:28:25 ProcessMessages(version, 111 bytes) FAILED peer=2
2016-11-23 13:28:25 SendMessages: sending inv peer=2 hash=00000000000019d53bb75ddae964e7cec1d39ef6f01a41b90bca4de869438298
Assertion failed: (nSendVersion != 0), function GetSendVersion, file ./net.h, line 775.
Abort trap: 6
```
Can't reproduce even with the same peer.

@theuni Any idea?

### PR DESCRIPTION
**Pull request by theuni**
First change is from @TheBlueMatt.

https://github.com/bitcoin/bitcoin/pull/8708/commits/462965635e8bf9c2754c27946f8b05560b8ddd84 added assertions to ensure that we never send out any messages before version negotiation has completed, but a few issues remain.

In cases where the version message failed to deserialize fully, we can end up with only some of the vars set, leading to sending messages that shouldn't be sent.

Additionally, the ForEach* functions allow the caller to send messages to all nodes, including those that aren't yet fully connected. To prevent that, filter out nodes that definitely shouldn't be sending/processing messages.

As a follow-up, I'd like to remove the assert, as I think it's done its job, but I'll save that discussion for another PR because I think @TheBlueMatt mentioned that he'd prefer to keep it.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
(fixes #9212)

File: src/net_processing.cpp [hunk 1]
```diff
@@ -1232,18 +1239,15 @@ bool static ProcessMessage(CNode* pfrom, string strCommand, CDataStream& vRecv,
...
-            vRecv >> LIMITED_STRING(pfrom->strSubVer, MAX_SUBVERSION_LENGTH);
-            pfrom->cleanSubVer = SanitizeString(pfrom->strSubVer);
+            vRecv >> LIMITED_STRING(strSubVer, MAX_SUBVERSION_LENGTH);
         }
         if (!vRecv.empty()) {
-            vRecv >> pfrom->nStartingHeight;
+            vRecv >> nStartingHeight;
         }
         {
             LOCK(pfrom->cs_filter);
```
Comment (gmaxwell) [inline src/net_processing.cpp]: This block no longer accesses a cs_filter protected variable. The lock and braces should be removed.

File: src/net_processing.cpp [hunk 2]
```diff
@@ -1254,7 +1258,19 @@ bool static ProcessMessage(CNode* pfrom, string strCommand, CDataStream& vRecv,
             return true;
         }
 
+        pfrom->nServices = nServices;
         pfrom->addrLocal = addrMe;
+        pfrom->strSubVer = strSubVer;
+        pfrom->cleanSubVer = SanitizeString(strSubVer);
+        pfrom->nStartingHeight = nStartingHeight;
+        pfrom->fRelayTxes = fRelay;
```
Comment (gmaxwell) [inline src/net_processing.cpp]: This was protected by cs_filter above.

File: src/net_processing.cpp [hunk 3]
```diff
@@ -1254,7 +1258,19 @@ bool static ProcessMessage(CNode* pfrom, string strCommand, CDataStream& vRecv,
...
+        pfrom->fClient = !(nServices & NODE_NETWORK);
+
+        // Change version
+        pfrom->SetSendVersion(nSendVersion);
+        pfrom->nVersion = nVersion;
```
Comment (gmaxwell) [inline src/net_processing.cpp]: nVersion should be made atomic.

**Comment by theuni** [comment]
@gmaxwell ACK all of those, will fix.

File: src/net_processing.cpp [hunk 4]
```diff
@@ -1278,11 +1291,7 @@ bool static ProcessMessage(CNode* pfrom, string strCommand, CDataStream& vRecv,
         UpdatePreferredDownload(pfrom, State(pfrom->GetId()));
         }
 
-        // Change version
         connman.PushMessage(pfrom, CNetMsgMaker(INIT_PROTO_VERSION).Make(NetMsgType::VERACK));
```
Comment (gmaxwell) [inline src/net_processing.cpp]: If we set succesfully connected and nversion before sending VERACK is it possible that some other thread will send some other message to this peer before VERACK has been sent?

Comment (theuni) [inline src/net_processing.cpp]: Yes, and that's ok. It's seen on the current network.

What's not ok is that messages before VERACK could possibly end up being sent with the upgraded version. So i suppose setting the sendversion should stay as-is, after the VERACK.

Comment (theuni) [inline src/net_processing.cpp]: Er, that doesn't work, it just reintroduces the problem that we're attempting to solve.

A mutex for a group of these attributes may be unavoidable. I'll poke at it some more.

Comment (gmaxwell) [inline src/net_processing.cpp]: the setsetversion can be run on based on nversion variable. So there is no reason it can't be done early with the nversion set later, as far as I can tell.

**Comment by theuni** [comment]
Ok, I think this is solid now.

**Comment by morcos** [comment]
tenuous utACK 
Read through it and makes sense to me, but not too familiar with this code.

I'm also not very familiar with feeler connections but would it make sense to move the feeler check before the fSuccessfullyConnected, so that we set fDisconnect first, and then won't send anything to the feeler peers?   Are we meant to be sending addr and GetAddr messages to the feeler peers?

**Comment by gmaxwell** [comment]
@morcos yes we should send addr to feelers-- their purpose is to improve knowledge about the node addresses all around.  I agree we should probably set Successfully after the disconnect flag is set for them.

File: src/net.h [hunk 5]
```diff
@@ -166,7 +166,7 @@ class CConnman
     {
         LOCK(cs_vNodes);
         for (auto&& node : vNodes)
-            if(!func(node))
+            if (NodeFullyConnected(node) && !func(node))
```
Comment (TheBlueMatt) [inline src/net.h]: Can we just remove unused functions instead of fixing them?

File: src/net_processing.cpp [hunk 6]
```diff
@@ -1263,9 +1263,25 @@ bool static ProcessMessage(CNode* pfrom, string strCommand, CDataStream& vRecv,
...
+        pfrom->fClient = !(nServices & NODE_NETWORK);
+        {
+            LOCK(pfrom->cs_filter);
+            pfrom->fRelayTxes = fRelay; // set to true after we get the first filter* message
+        }
+
+        // Change version
+        pfrom->SetSendVersion(nSendVersion);
+        pfrom->nVersion = nVersion;
+        pfrom->fSuccessfullyConnected = true;
```
Comment (TheBlueMatt) [inline src/net_processing.cpp]: If we're gonna be using fSuccessfullyConnected (which I think we should), can we set it in VERACK instead and use it in SendMessages? I looked over where we check nVersion for "are we connected" and it all looks like that would leave it at just ProcessMessage, which is right.

This would mean we at least dont do anything but respond to messages if we haven't gotten the peer's verack yet.

Comment (gmaxwell) [inline src/net_processing.cpp]: what if someone sends us a VERACK without anything else having happened? :P

**Comment by TheBlueMatt** [comment]
Then we can catch it with our nVersion != 0 check :)

File: src/net_processing.cpp (hunk 6 above)
Comment (theuni) [inline src/net_processing.cpp]: @TheBlueMatt That disagrees with my intended future usage of fSuccessfullyConnected (net layer only), but I agree that it makes more sense that way for now. I'll make that change, and we can discuss further post-0.14.

**Comment by gmaxwell** [comment]
ACK a79e00b8b251ab3744bd2f1bd48f265c1a7d7912

**Comment by laanwj** [comment]
> ACK a79e00b8b251ab3744bd2f1bd48f265c1a7d7912

That commit is not part of the repository :)

**Comment by gmaxwell** [comment]
It's the head I reviewed and tested however. :P (I wondered if someone would notice.)  (it sounds like cfields intends to change this more)

**Comment by theuni** [comment]
Fixed up as requested. fSuccessfullyConnected is set last thing when processing VERACK so that we push out SENDCMPCT/SENDHEADERS first.

We will now avoid doing anything in SendMessages() until the handshake is complete.

@morcos That fixes the feeler issue as well, since after VERSION, no more messages will be processed, and nothing else will go out.

@gmaxwell VERACK can't be seen before VERSION, as we refuse to process anything before version has been set.

Also removed the unused ForEach* in CConnman as requested by @TheBlueMatt.

**Comment by gmaxwell** [comment]
Concept ACK. Will test. You should consider making a brief release note that some broken P2P implementations (that never send VERACK) may stop working.

File: src/net.h [hunk 7]
```diff
@@ -213,36 +213,43 @@ class CConnman
     void ForEachNode(Callable&& func)
     {
         LOCK(cs_vNodes);
-        for (auto&& node : vNodes)
-            func(node);
+        for (auto&& node : vNodes) {
```
Comment (TheBlueMatt) [inline src/net.h]: I know it was already there, but can we remove the auto here? It doesnt save any space, and during review I always find myself thinking "OK, gonna go grep for CNode to find every use of it in the codebase", which our ever-increasing use of auto breaks.

**Comment by TheBlueMatt** [comment]
Other than my general objection to increased use of auto in the codebase (which I'll probably go through and get upset and rip out soon enough), utACK 47134d7de2ae57fbcb0715922094eca624ccb0fb

File: src/net.h (hunk 7 above)
Comment (theuni) [inline src/net.h]: It's conducive to large type changes, though. With this one in particular, when CNode becomes a shared_ptr\<CNode\>, this code requires no changes.

For exactly that reason, I actually have local changes which switch _all_ loop operations on vNodes to ```for (auto&& node : vNodes)``` :\

**Comment by TheBlueMatt** [comment]
I'm much happier reviewing a massive pile of sed-generated diff than having auto everywhere, but maybe I'm alone... I'll bring it up at the next meeting (because we didn't /just/ have a discussion of style or anything...).

File: src/net_processing.cpp [hunk 8]
```diff
@@ -2721,8 +2721,8 @@ bool SendMessages(CNode* pto, CConnman& connman, std::atomic<bool>& interruptMsg
 {
     const Consensus::Params& consensusParams = Params().GetConsensus();
     {
-        // Don't send anything until we get its version message
-        if (pto->nVersion == 0 || pto->fDisconnect)
+        // Don't send anything until the version handshake is complete
+        if (!pto->fSuccessfullyConnected || pto->fDisconnect)
```
Comment (gmaxwell) [inline src/net_processing.cpp]: Why isn't this !NodeFullyConnected(pto) ?

Comment (TheBlueMatt) [inline src/net_processing.cpp]: I believe because Cory wanted NodeFullyConnected to be a net-specific thing, and not a net_processing thing...its all a bit intermixed at the moment but I believe @theuni wants to fix it up soon.

Comment (theuni) [inline src/net_processing.cpp]: Yep, exactly that. I have no problem with changing it for the time-being though if you think it'd be more clear.

**Comment by MarcoFalke** [comment]
Needs rebase after #9626

File: src/net.h (hunk 7 above)
Comment (gmaxwell) [inline src/net.h]: I don't care, just looked like an obvious omission.

**Comment by sdaftuar** [comment]
I'll echo the tenuous utACK (though this needs to be rebased). I spent some time trying to find ways to break this code and wasn't able to come up with anything interesting.  I do think that we should remove the asserts for the 0.14 release, but I'm indifferent to whether we keep them around in master.

**Comment by TheBlueMatt** [comment]
Yes, I'd agree with @sdaftuar and remove the assertion in the 0.14 branch, but leave it in in master.

**Comment by laanwj** [comment]
I really hate the assertions in the net code. They can and will lead to remotely-triggered DoS attacks. It's just not acceptable to do debugging in this way, sorry.

They should be replaced with logging, or maybe an option 'stop on network errors' that needs to be enabled explicitly while debugging network code.

**Comment by TheBlueMatt** [comment]
We use assertions in many places to ensure our logic is functioning - here we're asserting that the peer we're accessing has completed the handshake, a pretty important cleanup IMO. Indeed, this assertion is somewhat shit due to the half-cleaned-up state of net at the moment, but I don't think that means we should remove the assertion in 0.15. Let's remove it after the branch and open an issue to revisit before 0.15 release.

**Comment by jtimon** [comment]
I see the way we use asserts as equivalent to exceptions, but making sure
they cannot be catched. Perhas activating them optionally as wumpus
suggests is interesting.
I really don't understand the reasoning for doing this in 0.14 but not in
master. If it needs to be revisited, fine,  it can be done after this
change.  I really dislike that version branches differ from master more
than they need, specially when it's for no good reason like it seems is tje
case here. IMO it should be only version change,  release notes,  etc.  And
bug fixes that we were NOT aware of before doing the branch.

**Comment by TheBlueMatt** [comment]
@jtimon the reason for not doing it on master is that the assert, if it fires, actually is an indication of a bug. On the flip side, because of the relative youth of this code (and the fact that such bugs are long-standing issues, not regressions), its probably better to not ship something with the assert in just yet. I dont see any problem having master and 0.14 differ by one line...

**Comment by laanwj** [comment]
> We use assertions in many places to ensure our logic is functioning

In places where there is no (direct) interface with the outside world it's somewhat more acceptable. At least if there'd be crashes it is not remotely triggerable. It's assertions in net code that I have a problem with.

> Let's remove it after the branch and open an issue to revisit before 0.15 release.

What I am afraid of is that that will be forgotten and they somehow will make it into a release anyway. I think leaving master even temporarily in a "dangerous" state is very risky.

**Comment by TheBlueMatt** [comment]
@laanwj ok, fair... @sdaftuar points out that its probably time to rethink our assertion infrastructure - get more agressive with assertions when not running a production build and get weaker on a few of them when doing so (and probably dont use assert(), since it is rarely what we want).

**Comment by theuni** [comment]
(Back in town, sorry for slow response)

I agree with removing the assertion. It probably never should have been there, as it introduces the possibility of remote crashers. I must admit that I'm glad that it forced us to fully address this problem, though.

I'll rebase and turn the assertion into a log.

File: src/net_processing.cpp (hunk 8 above)
Comment (gmaxwell) [inline src/net_processing.cpp]: I don't care, just looked like an obvious omission.

**Comment by laanwj** [comment]
utACK 08bb6f4

**Comment by TheBlueMatt** [comment]
utACK 08bb6f4ed48359aedd869450b99799b9c734084b

**Comment by gmaxwell** [comment]
ACK 08bb6f4

**Comment by sipa** [comment]
utACK 08bb6f4ed48359aedd869450b99799b9c734084b, testing with `-fsanitize`s.

File: src/net_processing.cpp [hunk 9]
```diff
@@ -1199,50 +1199,51 @@ bool static ProcessMessage(CNode* pfrom, std::string strCommand, CDataStream& vR
         CAddress addrFrom;
         uint64_t nNonce = 1;
         uint64_t nServiceInt;
-        vRecv >> pfrom->nVersion >> nServiceInt >> nTime >> addrMe;
```
Comment (rebroad) [inline src/net_processing.cpp]: this has been in the code forever... is it really needing to be changed now?

Comment (laanwj) [inline src/net_processing.cpp]: Unfortunately, many of the race conditions have been in the code forever and are only now being discovered and solved.

**Comment by jtimon** [comment]
Needs rebase.
