### PR TITLE
init: ignore BIP-30 verification in DisconnectBlock for problematic blocks

### LINKED ISSUE #22596: Coin database inconsistencies found
**Describe the issue**
Core can not check past blocks correctly

**What behavior did you expect?**
Expected setting checkblocks=0, checklevel=6, and assumevalid=0 to result in verification that the chain is valid. And that it would take nigh upon forever. It doesn’t. It poops out in about 12 hours. 

**What was the actual behavior** 
Debug.log highlights:
(Note: Block height at time of message was 693086)
init message: Verifying blocks…
Verifying last 693086 blocks at level 4
[0%]… [10%]… [20%]… [30%]… [40%]…ERROR: VerifyDB(): *** coin database inconsistencies found (last 601365 blocks, 142571 good transactions before that)

Corrupted block database detected.

**How reliably can you reproduce the issue, what are the steps to do so?**
100% reproducible. To reproduce, just try rechecking the chain. I don’t know the fastest way to do this, in fact, I’m not even entirely sure how many checklevels there even are but I read 6 on stack exchange…anyhow, just add this to bitcoin.conf and restart node:

assumevalid=0
checkblocks=0
checklevel=6

**What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?**
0.21.1.0; self compiled. I got the code two different t ways: over Internet using git at the command line and from the friendly lizards working for blockstream in space via satellite using blocksat-cli.

**What type of machine are you observing the error on (OS/CPU and disk type)?**
I’ve checked two intel architecture nodes I have running. Both are little intel NUCs.
Ubuntu 20.04 Lts/2.6 ghz intel i7 underclocked at 2.4 GHz max just in case/16 and 32 GB RAM at conservative BIOS settings/NVME SSD (tried it on one node with a single Samsung 970 evo plus formatted ext4 filesystem and another with 2 Samsung 980 NVME in raid 1 configuration…also ext4)

**What is your operating system and its version? If Linux, what is your desktop environment and graphical shell?**
Whatever is default for Ubuntu 

**Any extra information that might be useful in the debugging process.**
Someone far smarter than me can reproduce this too (dflate)

Somehow relates to this…see explorers disagreeing (via dflate)

https://blockstream.info/tx/d5d27987d2a3dfc724e359870c6644b40e497bdc0589a033220fe15429d88599?expand

https://explorer.bitcoin.com/btc/tx/d5d27987d2a3dfc724e359870c6644b40e497bdc0589a033220fe15429d88599

Otherwise, not yet. I keep my node off the internet, because, you know, satellite and stuff…but I’ve typed out by hand what seems relevant above.

### PR DESCRIPTION
**Pull request by seejee**
Fixes https://github.com/bitcoin/bitcoin/issues/22596

When using checklevel=4, block verification fails because of duplicate coinbase transactions involving blocks 91812 and 91722. There was already a check in place within `ConnectBlock` to ignore the problematic blocks, but `DisconnectBlock` did not contain a similar check to ignore these blocks when called from `VerifyDB`.

By ignoring these two blocks in `DisconnectBlock`, the block verification process succeeds at checklevel=4.

(Note to reviewers: this is my first contribution to Bitcoin Core, so any feedback is most welcome. Thanks in advance for reviewing!)

## Steps to reproduce:

Use the following bitcoin.conf file and start bitcoind. I only used block data through block ~100000 so that the verification process was much faster.

```
assumevalid=0
checkblocks=0
checklevel=4
```

Without this change, you will see the following error when the blocks are verified:

```
2022-04-14T02:56:44Z init message: Verifying blocks…
2022-04-14T02:56:44Z Verifying last 101881 blocks at level 4
2022-04-14T02:56:44Z [0%]...[10%]...[20%]...[30%]...[40%]...ERROR: VerifyDB(): *** coin database inconsistencies found (last 10160 blocks, 142571 good transactions before that)

2022-04-14T02:57:01Z : Corrupted block database detected.
Please restart with -reindex or -reindex-chainstate to recover.
: Corrupted block database detected.
Please restart with -reindex or -reindex-chainstate to recover.
```

With this change, you will see this instead:

```
2022-04-14T02:32:29Z init message: Verifying blocks…
2022-04-14T02:32:29Z Verifying last 101746 blocks at level 4
2022-04-14T02:32:29Z [0%]...[10%]...[20%]...[30%]...[40%]...[50%]...[60%]...[70%]...[80%]...[90%]...[DONE].
2022-04-14T02:32:48Z No coin database inconsistencies in last 101746 blocks (226126 transactions)
```

### CODE REVIEW

File: src/validation.cpp [hunk 1]
```diff
@@ -1837,6 +1837,15 @@ DisconnectResult CChainState::DisconnectBlock(const CBlock& block, const CBlockI
         return DISCONNECT_FAILED;
     }
 
+    // Ignore blocks that contain transactions which are 'overwritten' by later transactions,
+    // unless those are already completely spent.
+    // See https://github.com/bitcoin/bitcoin/issues/22596 for additional information.
+    // Note: the blocks specified here are different than the ones used in ConnectBlock because DisconnectBlock
+    // unwinds the blocks in reverse. As a result, the inconsistency is not discovered until the earlier
+    // blocks with the duplicate coinbase transactions are disconnected.
```
Comment (seejee) [inline src/validation.cpp:1845]: I'm still pretty new to Bitcoin, so if there is a more precise way to describe this, I welcome the feedback.

File: src/validation.cpp [hunk 2]
```diff
@@ -1850,7 +1859,7 @@ DisconnectResult CChainState::DisconnectBlock(const CBlock& block, const CBlockI
                 COutPoint out(hash, o);
                 Coin coin;
                 bool is_spent = view.SpendCoin(out, &coin);
-                if (!is_spent || tx.vout[o] != coin.out || pindex->nHeight != coin.nHeight || is_coinbase != coin.fCoinBase) {
+                if (fEnforceBIP30 && (!is_spent || tx.vout[o] != coin.out || pindex->nHeight != coin.nHeight || is_coinbase != coin.fCoinBase)) {
```
Comment (seejee) [inline src/validation.cpp:1862]: At first I tried to mimic the behavior in [ConnectBlock](https://github.com/bitcoin/bitcoin/blob/b620b2d58a55a88ad21da70cb2000863ef17b651/src/validation.cpp#L1825-L1834) and the put the `fEnforceBIP30` guard around the entire loop that begins on line 1850, but that would still result in the verification failing later in the process. Moving the guard here allowed the verification process to complete successfully.

I'm assuming that we need to call `SpendCoin` in both cases because we still need to update the view's state even if we ignore the `is_spent` result.

**Review by jamesob — COMMENTED** [review]
Concept ACK

Thanks for the contribution and welcome to the project. I've tested the patch locally and it works as advertised; I also perturbed each height value to ensure that the heights listed are those necessary to fix the `VerifyDB` issue.

My one comment is that since BIP30 violations are limited to coinbase transactions, it might be nice to restrict the exceptions accordingly, e.g. with a patch like this
```diff
diff --git a/src/validation.cpp b/src/validation.cpp
index 6d87ab88b3..ffad7e8402 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -1851,6 +1851,7 @@ DisconnectResult CChainState::DisconnectBlock(const CBlock& block, const CBlockI
         const CTransaction &tx = *(block.vtx[i]);
         uint256 hash = tx.GetHash();
         bool is_coinbase = tx.IsCoinBase();
+        bool is_bip30_exception = (is_coinbase && !fEnforceBIP30);
 
         // Check that all outputs are available and match the outputs in the block itself
         // exactly.
@@ -1859,8 +1860,10 @@ DisconnectResult CChainState::DisconnectBlock(const CBlock& block, const CBlockI
                 COutPoint out(hash, o);
                 Coin coin;
                 bool is_spent = view.SpendCoin(out, &coin);
-                if (fEnforceBIP30 && (!is_spent || tx.vout[o] != coin.out || pindex->nHeight != coin.nHeight || is_coinbase != coin.fCoinBase)) {
-                    fClean = false; // transaction output mismatch
+                if (!is_spent || tx.vout[o] != coin.out || pindex->nHeight != coin.nHeight || is_coinbase != coin.fCoinBase) {
+                    if (!is_bip30_exception) {
+                        fClean = false; // transaction output mismatch
+                    }
                 }
             }
         }
```

**Comment by seejee** [comment]
@jamesob Thanks for the review and good idea to ensure that we're only allowing exceptions for coinbase transactions. I've included your suggested patch in the latest commit and retested to ensure things are working as expected. 👍 

Thanks again!

**Comment by jamesob** [comment]
@seejee great. FWIW, looks like there's a typo in your commit message ("trxs"); you can fix with `git commit --amend`. You can also add co-author credits by appending
```
Co-authored-by: James O'Beirne <james.obeirne@pm.me>
```
if you'd like.

**Comment by seejee** [comment]
@jamesob Fixed they type and I included your co-author credits. Sorry for not doing that in the first place! 🙇

**Review by jamesob — APPROVED** [review]
(Biased) ACK e899d4ca6f44785b6e5481e200a6a9a8d2448612 ([`jamesob/ackr/24851.2.seejee.init_ignore_bip_30_verif`](https://github.com/jamesob/bitcoin/tree/ackr/24851.2.seejee.init_ignore_bip_30_verif))

Well documented and symmetric with the equivalent `ConnectBlock` conditionals; 
even better in terms of specifically acting on coinbase transactions. Tested
locally per the PR description.


<details><summary>Show signature data</summary>
<p>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK e899d4ca6f44785b6e5481e200a6a9a8d2448612 ([`jamesob/ackr/24851.2.seejee.init_ignore_bip_30_verif`](https://github.com/jamesob/bitcoin/tree/ackr/24851.2.seejee.init_ignore_bip_30_verif))

Well documented and symmetric with the equivalent `ConnectBlock` conditionals; 
even better in terms of specifically acting on coinbase transactions. Tested
locally per the PR description.

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEGNRVI1NPYuZCSIrGepNdrbLETwUFAmJYSjwACgkQepNdrbLE
TwWLXg/8CvE6Lr2u2y6fuWoXCnTNyfh/sTKlxyE7VMXiCw9eV2RvmoIaGCPHNHZP
5onsUv0J8WQ+KJVdUZUJpVaW0Gg/dThjDeUEjqTaniYqy8JgUEcjy5fTayI6Cpkt
YDY1M5oAX80Tq7zaHLxMonLUmqy/moYBJw8TmmAMyVoFPJh2UcSie7P5TLVsmPLe
XQyFc0QjvBNr2ois/uLswN7rArtPPldakCnXrBeDWkDIMN7gcPmrNJXbeKl4vEYk
dwtAvuacpGimm7YVNjIY5vnamL2KAp+0d+pw8g8IWX1AJmH7noMeJ09ZmUqpeooo
vF8l6+Q5mWwKs05WRYpG3dmU+Lfhpn+q48tN0n2GFxYNtKBF1XVRUEvse3Vdo0JM
GVr4ISVLYhKLU+HzVH1iNRQ+lZ5GgOutvZfgjzxrKVI71kv6XRcu3+8nFmuSfJNx
wvDhXSNjlMCX0qbBi+UOuKYLscuzEN+dnltnF1UH/u3AyV/EDwcvbF6iwhKunuNU
uo4Qf1g8ipaGVVVs2UavruE3AyAQx8ajmmGb64NsirqMuIVxbdPNMZiUHPeIj5S+
z4z0GXpyII2p8lJlI4+lHXpH+EX/Cypo7XGqOzJItWYEfmn4BSVK8ieC5I8LcdSC
VSBup0RTpyHIWg1gu1ZCy0lQKoEpu8tl8OA0WAEP/hcXRjdQiMc=
=w1jg
-----END PGP SIGNATURE-----

```

</p></details>

<details><summary>Show platform data</summary>
<p>

```
Tested on Linux-5.10.0-11-amd64-x86_64-with-glibc2.31

Configured with ./configure LDFLAGS=-L/home/james/src/bitcoin/db4/lib/ CPPFLAGS=-I/home/james/src/bitcoin/db4/include/ CXXFLAGS=-fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare -Wsign-compare -Werror=thread-safety-analysis --enable-wallet --enable-debug --with-daemon --enable-natpmp-default

Compiled with /usr/bin/ccache /usr/local/bin/clang++ -std=c++17 -mavx -mavx2 -mpclmul -fPIE -pipe -O2 -g -Wthread-safety-analysis -Wall -Werror=sign-compare -Wsign-compare -Werror=thread-safety-analysis -O0 -g3 -ftrapv -fdebug-prefix-map=$(abs_top_srcdir)=.  -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection -msse4.1 -msse4.2 -msse4 -msha  i

Compiler version: Debian clang version 13.0.1-++20220126092033+75e33f71c2da-1~exp1~20220126212112.63
```

</p></details>

File: src/validation.cpp [hunk 3]
```diff
@@ -1837,11 +1837,21 @@ DisconnectResult CChainState::DisconnectBlock(const CBlock& block, const CBlockI
         return DISCONNECT_FAILED;
     }
 
+    // Ignore blocks that contain transactions which are 'overwritten' by later transactions,
+    // unless those are already completely spent.
+    // See https://github.com/bitcoin/bitcoin/issues/22596 for additional information.
+    // Note: the blocks specified here are different than the ones used in ConnectBlock because DisconnectBlock
+    // unwinds the blocks in reverse. As a result, the inconsistency is not discovered until the earlier
+    // blocks with the duplicate coinbase transactions are disconnected.
+    bool fEnforceBIP30 = !((pindex->nHeight==91722 && pindex->GetBlockHash() == uint256S("0x00000000000271a2dc26e7667f8419f2e15416dc6955e5a6c6cdf3f2574dd08e")) ||
```
Comment (laanwj) [inline src/validation.cpp:1846]: Maybe it'd make sense to factor out this "EnforceBIP30(pindex)" logic into a function? I know, it will never change so it doesn't hurt either to hardcode it in duplicate, but I'd like the symmetry of it better.

**Comment by laanwj** [comment]
Code review ACK e899d4ca6f44785b6e5481e200a6a9a8d2448612

It would be real nice to have a functional test for the disconnection behavior, though not necessarily in this PR.

**Comment by 0xB10C** [comment]
Successfully tested with `verifychain 4 0` on mainnet. Had to change source https://github.com/0xB10C/bitcoin/commit/eb0d5f078f03a5190d458ab4cc2d2e859e2492da to allow for a dbcache larger than 16GB. Ran it with 48GB and from what I can tell it used just under 32 GB of RAM. Took 14h.

**Comment by achow101** [comment]
ACK e899d4ca6f44785b6e5481e200a6a9a8d2448612
