### PR TITLE
qt: Ensure that ModalOverlay is resized properly

### LINKED ISSUE #17269: Qt: If you reindex a black bar shows up on the bottom of the window when the sync overlay is hidden
I was testing from commit be50469217bd775c4305938634c32e5932f47841 and noticed that the "out of sync" overlay went away correctly after mining blocks, but then after restarting with --reindex this black bar shows up after the overlay is hidden. I've only tested this in regtest mode. I'm not sure that the issue is related to the overlay but it seems to show up right when the overlay is hidden. 

Screenshot_20191026_171200

On another system:

Before reindex
Screenshot_20191026_174635

After reindex 
Screenshot_20191026_174657

### LINKED ISSUE #17967: qt: Shadow ribbon at the bottom of QFrame
A semi-opaque ribbon is observed in the main window:

DeepinScreenshot_bitcoin-qt_20200119212040

DeepinScreenshot_bitcoin-qt_20200119212253

Tab switching does not remove it. Window moving does not remove it.
It vanishes after window resizing.

**To reproduce**
Run with `-regtest`, generate some blocks (200 in my case), then quit.
Remove `rev00000.dat` file to trigger an error.
Run with `-regtest` and in the dialog "Do you want to rebuild the block database now?" click "OK".

**System information**
Linux Mint 19.3 + Cinnamon 4.4.8

Both versions affected:
- 0.19.0.1 (gitian)
- master + system Qt 5.9.7

### PR DESCRIPTION
**Pull request by hebasto**
In certain circumstances the `ModalOverlay` widget is not sized properly:
- #17269
- #17967 
- https://github.com/bitcoin/bitcoin/pull/17968#pullrequestreview-350753107

On master (f018d0c9cd7f408dac016b6bfc873670de713d27) this bug looks like this:
DeepinScreenshot_bitcoin-qt_20200120193402

With this PR the wallet frame looks ok:
DeepinScreenshot_bitcoin-qt_20200120195241

Fix #17269
Fix #17967

### CODE REVIEW

**Comment by emilengler** [comment]
utACK f3bac3a1874313796cf2d7acea2d3da74f36a2b0

**Review by promag — COMMENTED** [review]
Unrelated but while we are here you can notice that if the window height is increased while the modal is hiding then it will stay a little visible like:

Screenshot 2020-01-30 at 11 20 42

because the animation end value doesn't track the new height.

Honestly why not drop the animation and eventually make it a modal dialog instead of being embedded?

**Comment by hebasto** [comment]
@promag 
> Unrelated but while we are here you can notice that if the window height is increased while the modal is hiding then it will stay a little visible...

With this PR?

**Comment by promag** [comment]
@hebasto here and master. You can check more easily by increasing the animation duration.

**Comment by hebasto** [comment]
Reworked and rebased.

@promag 
> Unrelated but while we are here you can notice that if the window height is increased while the modal is hiding then it will stay a little visible like:
> ...
> because the animation end value doesn't track the new height.

Fixed.

File: src/qt/modaloverlay.h [hunk 1]
```diff
@@ -45,6 +46,7 @@ public Q_SLOTS:
     QVector<QPair<qint64, double> > blockProcessTime;
     bool layerIsVisible;
     bool userClosed;
+    QPropertyAnimation animation{};
```
Comment (promag) [inline src/qt/modaloverlay.h:49]: nit, m_animation, m_slide_animation or something like that. Also, could drop `{}`?

File: src/qt/modaloverlay.cpp [hunk 2]
```diff
@@ -48,6 +53,9 @@ bool ModalOverlay::eventFilter(QObject * obj, QEvent * ev) {
             if (!layerIsVisible)
                 setGeometry(0, height(), width(), height());
 
+            if (animation.state() != QAbstractAnimation::Stopped && animation.endValue().toPoint().y()) {
```
Comment (promag) [inline src/qt/modaloverlay.cpp:56]: nit, `== QPropertyAnimation::Running`? Also add `> 0` or maybe a comment giving some context.

**Review by promag — COMMENTED** [review]
Code review ACK 14f68ecdc22e96011e53b6aea5672c853e2c648b.

File: src/qt/modaloverlay.h (hunk 1 above)
Comment (hebasto) [reply src/qt/modaloverlay.h:49]: Sure! Going to fix.

File: src/qt/modaloverlay.cpp (hunk 2 above)
Comment (hebasto) [reply src/qt/modaloverlay.cpp:56]: According to the [`enum QAbstractAnimation::State`](https://doc.qt.io/qt-5/qabstractanimation.html#State-enum) docs, `state != QAbstractAnimation::Stopped` does not imply `state == QAbstractAnimation::Running` :)

Going to add `>0`.

Comment (promag) [reply src/qt/modaloverlay.cpp:56]: We don't pause right? Oh well, just drop it and always update when > 0 🙈

**Comment by hebasto** [comment]
Updated 14f68ecdc22e96011e53b6aea5672c853e2c648b -> 4fc1df41d570ab631a8b47e4427a0b84305e37d1 ([pr17968.02](https://github.com/hebasto/bitcoin/commits/pr17968.02) -> [pr17968.03](https://github.com/hebasto/bitcoin/commits/pr17968.03), [diff](https://github.com/hebasto/bitcoin/compare/pr17968.02..pr17968.03)):

- addressed @promag's comments
- added comment for clarity

File: src/qt/modaloverlay.h (hunk 1 above)
Comment (hebasto) [reply src/qt/modaloverlay.h]: [Updated](https://github.com/bitcoin/bitcoin/pull/17968#issuecomment-621398261).

File: src/qt/modaloverlay.cpp (hunk 2 above)
Comment (hebasto) [reply src/qt/modaloverlay.cpp]: [Updated](https://github.com/bitcoin/bitcoin/pull/17968#issuecomment-621398261).

**Comment by promag** [comment]
Code review ACK 4fc1df41d570ab631a8b47e4427a0b84305e37d1.

**Comment by jonasschnelli** [comment]
utACK 4fc1df41d570ab631a8b47e4427a0b84305e37d1
