### PR TITLE
 Fix signed integer overflow in prioritisetransaction RPC 

### LINKED ISSUE #19278: Three UBSan warnings when loading corrupt mempool.dat files
I noticed three UBSan warnings that are reachable when loading corrupt `mempool.dat` files.

```
$ xxd -p -r > mempool.dat-crashes-in-validation.cpp-5064 <<EOF
0100000000000000000000000004000000000000000000000000ffffffff
ffffff7f00000000000000000000000000
EOF
$ cp mempool.dat-crashes-in-validation.cpp-5064 ~/.bitcoin/regtest/mempool.dat
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" src/bitcoind -regtest
validation.cpp:5064:23: runtime error: signed integer overflow: 9223372036854775807 + 1209600 cannot be represented in type 'long'
    #0 0x5573a5a07a8b in LoadMempool(CTxMemPool&, std::function<_IO_FILE* (boost::filesystem::path const&, char const*)>) src/validation.cpp:5064:23
    #1 0x5573a52cce12 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) src/init.cpp:750:9
    #2 0x5573a52cbef7 in AppInitMain(util::Ref const&, NodeContext&)::$_9::operator()() const src/init.cpp:1845:48
```

```
$ xxd -p -r > mempool.dat-crashes-in-util-moneystr.cpp-16a <<EOF
010000000000000000050900000000000509000000000000800000000000
0000000000000000000000800000000000
EOF
$ cp mempool.dat-crashes-in-util-moneystr.cpp-16a ~/.bitcoin/regtest/mempool.dat
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" src/bitcoind -regtest
util/moneystr.cpp:16:34: runtime error: negation of -9223372036854775808 cannot be represented in type 'CAmount' (aka 'long'); cast to an unsigned type to negate this value to itself
    #0 0x5641ce3e0aec in FormatMoney[abi:cxx11](long const&) src/util/moneystr.cpp:16:34
    #1 0x5641cd98a001 in CTxMemPool::PrioritiseTransaction(uint256 const&, long const&) src/txmempool.cpp:850:77
    #2 0x5641cdb117b4 in LoadMempool(CTxMemPool&, std::function<_IO_FILE* (boost::filesystem::path const&, char const*)>) src/validation.cpp:5061:22
    #3 0x5641cd3d6e12 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) src/init.cpp:750:9
    #4 0x5641cd3d5ef7 in AppInitMain(util::Ref const&, NodeContext&)::$_9::operator()() const src/init.cpp:1845:48
```

```
$ xxd -p -r > mempool.dat-crashes-in-util-moneystr.cpp-16b <<EOF
0100000000000000000000000000000001253d8c0000000000000000006b
00000000f7000000ff00f7000000ff0000000000000000000000800000ff
0000
EOF
$ cp mempool.dat-crashes-in-util-moneystr.cpp-16b ~/.bitcoin/regtest/mempool.dat
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" src/bitcoind -regtest
util/moneystr.cpp:16:34: runtime error: negation of -9223372036854775808 cannot be represented in type 'CAmount' (aka 'long'); cast to an unsigned type to negate this value to itself
    #0 0x55987d51daec in FormatMoney[abi:cxx11](long const&) src/util/moneystr.cpp:16:34
    #1 0x55987cac7001 in CTxMemPool::PrioritiseTransaction(uint256 const&, long const&) src/txmempool.cpp:850:77
    #2 0x55987cc4ed6f in LoadMempool(CTxMemPool&, std::function<_IO_FILE* (boost::filesystem::path const&, char const*)>) src/validation.cpp:5092:18
    #3 0x55987c513e12 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) src/init.cpp:750:9
    #4 0x55987c512ef7 in AppInitMain(util::Ref const&, NodeContext&)::$_9::operator()() const src/init.cpp:1845:48
```

The signed integer overflow can probably be avoided simply by re-arranging the terms in the conditional (`nTime > nNow - nExpiryTimeout` instead of `nTime + nExpiryTimeout > nNow`), and the invalid negation can likely be avoided by simply checking that the delta amount is valid before calling `PrioritiseTransaction`.

### LINKED ISSUE #20626: Signed integer overflow in CTxMemPool::PrioritiseTransaction(…) reachable via RPC call prioritisetransaction
While fuzzing the RPC interface I stumbled upon a signed integer overflow in `CTxMemPool::PrioritiseTransaction(…)` which is reachable via the following two `prioritisetransaction` RPC calls:

```
$ ./autogen.sh
$ CC=clang CXX=clang++ ./configure --with-sanitizers=address,undefined
$ make
$ UBSAN_OPTIONS="print_stacktrace=1" src/bitcoind &
$ src/bitcoin-cli -prioritisetransaction cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe 0 -9123456789123456789
$ src/bitcoin-cli -prioritisetransaction cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe 0 -9123456789123456789
txmempool.cpp:832:15: runtime error: signed integer overflow: -9123456789123456789 + -9123456789123456789 cannot be represented in type 'long'
    #0 0x5581f3e69c3c in CTxMemPool::PrioritiseTransaction(uint256 const&, long const&) src/txmempool.cpp:832:15
    #1 0x5581f3c93852 in prioritisetransaction()::$_6::operator()(RPCHelpMan const&, JSONRPCRequest const&) const src/rpc/mining.cpp:470:36
…

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior txmempool.cpp:832:15
```

Nothing high priority of course, but still worth fixing :)

### PR DESCRIPTION
**Pull request by maflcko**
Signed integer overflow is UB in theory, but not in practice. Still,
it would be nice to avoid this UB to allow Bitcoin Core to be
compiled with sanitizers such as `-ftrapv` or ubsan.

It is impossible to predict when and if an overflow occurs, since
the overflow caused by a prioritisetransaction RPC might only be
later hit when descendant txs are added to the mempool.
Since it is impossible to predict reliably, leave it up to the user
to use the RPC endpoint responsibly, considering their mempool
limits and usage patterns.

Fixes: #20626
Fixes: #20383
Fixes: #19278
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34146 / https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47132

## Steps to reproduce

Build the code without the changes in this pull.

Make sure to pass the sanitizer flag:

```
./autogen.sh && ./configure --with-sanitizers=signed-integer-overflow && make clean && make -j $(nproc)
```

### Reproduce on RPC

```
./src/bitcoind -chain=regtest -noprinttoconsole &
./src/bitcoin-cli -chain=regtest prioritisetransaction 00000000deadbeef00000000deadbeef00000000deadbeef00000000deadbeef 0 9123456789123456789
./src/bitcoin-cli -chain=regtest prioritisetransaction 00000000deadbeef00000000deadbeef00000000deadbeef00000000deadbeef 0 9123456789123456789
|> txmempool.cpp:920:15: runtime error: signed integer overflow: 9123456789123456789 + 9123456789123456789 cannot be represented in type 'long int'

./src/bitcoin-cli -chain=regtest stop
```

### By fuzzing

```
wget https://github.com/bitcoin/bitcoin/files/8921302/clusterfuzz-testcase-minimized-validation_load_mempool-5599531390074880.bin.txt
FUZZ=validation_load_mempool ./src/test/fuzz/fuzz ./clusterfuzz-testcase-minimized-validation_load_mempool-5599531390074880.bin.txt 
|> txmempool.cpp:920:15: runtime error: signed integer overflow: 7214801925397553184 + 2314885530818453536 cannot be represented in type 'long int'
|> validation_load_mempool: succeeded against 1 files in 0s.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Currently a draft, so please only review the concept and approach. I'll rebase this after #23411 (which shares the first commit) and take it out of draft.

**Review by PastaPastaPasta — COMMENTED** [review]
See https://godbolt.org/z/aWTKcM6db, I have a couple of suggestions:

1. make TestAdd, TestAddMatrixOverflow, TestAddMatrix and AdditionOverflow constexpr b/c why not
2. Consider replacing MaybeAdd with my implementation of MaybeAddRet, which returns a value instead of mutating a mutable reference, which enables MaybeAddRet to be constexpr. (they appear virtually equally efficient, especially when we take into account we'll be using trivial types with this) (I also think this just makes more sense for a function called "MaybeAdd" as opposed to "MaybeAddEquals" or smth else)
3. Consider adding a    `static_assert(std::is_trivial<T>::value);` to ensure we only are using trivial types

(also, I see that you weren't really asking for a review, but I just saw the PR and started poking around :D )

File: src/txmempool.cpp [hunk 1]
```diff
@@ -22,6 +23,22 @@
 #include <cmath>
 #include <optional>
 
+template <typename T>
+static void MaybeAdd(T& mut, const T& apply)
```
Comment (vasild) [inline src/txmempool.cpp:27]: In this interface the function may or may not add the second argument to the first and it does not signal to the caller which one of the two it did. I find this puzzling. Surely the caller needs to take a different action depending on whether the two numbers can be summed or not? If the caller does not care and takes the same action either way, and the code is still correct, then why bother and not just skip calling `MaybeAdd()` altogether? (if not adding is also ok)

Or, if this is used in some kind of blurred logic where everything is ok, is it not better for the sum to produce `numeric_limits<T>::max()` in case of an overflow? E.g. if summing `char` `100 + 30` to produce `127` instead of `100`?

To me it would be more logical to check for an overflow and take the appropriate action if one would occur, even if that is to `abort()` the program. We have types that are wide enough to ensure that overflow "never" occurs, or if it occurs then `abort()`ing is justified. Something like:

```cpp
template <typename T>
T SumOrDie(T x, T y)
{
    assert(!AddOverflows(x, y));
    assert(!AddUnderflows(x, y));
    return x + y;
}

File: src/txmempool.cpp [hunk 2]
```diff
@@ -22,6 +23,22 @@
...
+{
+    if (AdditionOverflow(mut, apply)) {
+        // Signed integer overflow is UB in theory.
+        // It is impossible to predict when and if an overflow occurs, since
+        // the overflow caused by a prioritisetransaction RPC might only be
+        // later hit when descendant txs are added to the mempool.
+        // Since it is impossible to predict reliably, leave it up to the user
+        // to use the RPC endpoint responsibly, considering their mempool
+        // limits and usage patterns.
+        return;
```
Comment (luke-jr) [inline src/txmempool.cpp:37]: This ignores the fee delta when it would otherwise overflow, which seems like incorrect behaviour. Shouldn't we just set `mut` to the max value?

**Review by luke-jr — CHANGES_REQUESTED** [review]

**Comment by PastaPastaPasta** [comment]
> See https://godbolt.org/z/aWTKcM6db, I have a couple of suggestions:
> 
> 1. make TestAdd, TestAddMatrixOverflow, TestAddMatrix and AdditionOverflow constexpr b/c why not
> 2. Consider replacing MaybeAdd with my implementation of MaybeAddRet, which returns a value instead of mutating a mutable reference, which enables MaybeAddRet to be constexpr. (they appear virtually equally efficient, especially when we take into account we'll be using trivial types with this) (I also think this just makes more sense for a function called "MaybeAdd" as opposed to "MaybeAddEquals" or smth else)
> 3. Consider adding a    `static_assert(std::is_trivial<T>::value);` to ensure we only are using trivial types
> 
> (also, I see that you weren't really asking for a review, but I just saw the PR and started poking around :D )

@MarcoFalke do you have an opinion about these suggestions?

**Comment by MarcoFalke** [comment]
Please review https://github.com/bitcoin/bitcoin/pull/24224 first, while this stays in draft

File: src/txmempool.cpp (hunk 2 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: thanks, done

File: src/txmempool.cpp (hunk 1 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: We can't abort here. Otherwise it might be possible for remote peers to shut down your node. Even if it wasn't P2P exploitable and only RPC exploitable, an RPC call should never crash the process either (unless it triggers a bug in the consensus engine). See documentation of `CheckNonFatal`.

The caller *does* care about the result of the calculation. However, values so large that they overflow 64-bits are not supported by Bitcoin Core. Thus, we can pick any behaviour we want to deal with it.

**Comment by MarcoFalke** [comment]
Rebased and replied to all feedback

File: src/txmempool.cpp (hunk 1 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: Resolving discussion for now, but feel free to reply or reopen.

File: src/txmempool.cpp [hunk 3]
```diff
@@ -496,7 +496,7 @@ void CTxMemPool::addUnchecked(const CTxMemPoolEntry &entry, setEntries &setAnces
     CAmount delta{0};
     ApplyDelta(entry.GetTx().GetHash(), delta);
     if (delta) {
-            mapTx.modify(newit, update_fee_delta(delta));
+        mapTx.modify(newit, update_modify_fee(delta));
```
Comment (glozow) [inline src/txmempool.cpp:500]: Since you're touching anyway, might as well update this to use a lambda (now that we're not pre-C++11 anymore), and we can delete the `update_modify_fee` struct. Similar to e177fcab3831b6d259da5164cabedcc9e78f6957
```suggestion
        mapTx.modify(newit, [&delta](CTxMemPoolEntry& e) { e.UpdateModifyFee(delta); });
```

(Same suggestion to L935)

**Review by glozow — COMMENTED** [review]
concept ACK faa69b3876ac18d2ec69d6ac28468144d98ebceb

Very nice to get rid of a sanitizer suppression, and the fee delta for modified fees should be a `CAmount` anyway. I have a small suggestion which is not really within scope of this PR, so feel freee to ignore.

File: src/txmempool.cpp [hunk 4]
```diff
@@ -99,11 +100,11 @@ CTxMemPoolEntry::CTxMemPoolEntry(const CTransactionRef& tx, CAmount fee,
       nModFeesWithAncestors{nFee},
       nSigOpCostWithAncestors{sigOpCost} {}
 
-void CTxMemPoolEntry::UpdateFeeDelta(int64_t newFeeDelta)
+void CTxMemPoolEntry::UpdateModifyFee(CAmount modify_fee)
```
Comment (vasild) [inline src/txmempool.cpp:103]: I find the name `UpdateModifyFee()` confusing because both `Update` and `Modify` are verbs. What about `UpdateModifiedFee(CAmount delta)`? Or `diff` instead of `delta`? The member variable is called "modifi**ed**_fee". Or maybe even use `Increment` instead of `Update` in the name because we are doing `+=` (surely, incrementing with a negative number is actually decrementing).

(if you decide to change the name, the same change should be done to the name of `struct update_modify_fee`)

File: src/txmempool.h [hunk 5]
```diff
@@ -101,7 +101,7 @@ class CTxMemPoolEntry
     const unsigned int entryHeight; //!< Chain height when entering the mempool
     const bool spendsCoinbase;      //!< keep track of transactions that spend a coinbase
     const int64_t sigOpCost;        //!< Total sigop cost
-    int64_t feeDelta{0};            //!< Used for determining the priority of the transaction for mining in a block
+    CAmount modified_fee{nFee};     //!< Used for determining the priority of the transaction for mining in a block
```
Comment (vasild) [inline src/txmempool.h:104]: I think it is better to initialize `modified_fee` where the rest of the members are initialized:

```cpp
CTxMemPoolEntry::CTxMemPoolEntry(const CTransactionRef& tx, CAmount fee,
                                 int64_t time, unsigned int entry_height,
                                 bool spends_coinbase, int64_t sigops_cost, LockPoints lp)
    : tx{tx},
      nFee{fee},
      nTxWeight(GetTransactionWeight(*tx)),
      nUsageSize{RecursiveDynamicUsage(tx)},
      nTime{time},
      entryHeight{entry_height},
      spendsCoinbase{spends_coinbase},
      sigOpCost{sigops_cost},
      lockPoints{lp},
      nSizeWithDescendants{GetTxSize()},
      nModFeesWithDescendants{nFee},
      nSizeWithAncestors{GetTxSize()},
      nModFeesWithAncestors{nFee},
      nSigOpCostWithAncestors{sigOpCost} {}
```

File: src/txmempool.cpp [hunk 6]
```diff
@@ -496,7 +497,7 @@ void CTxMemPool::addUnchecked(const CTxMemPoolEntry &entry, setEntries &setAnces
     CAmount delta{0};
     ApplyDelta(entry.GetTx().GetHash(), delta);
     if (delta) {
-            mapTx.modify(newit, update_fee_delta(delta));
+        mapTx.modify(newit, update_modify_fee(delta));
```
Comment (vasild) [inline src/txmempool.cpp:500]: This looks wrong.

Lets say `nFee` is `100`.

Before this PR we would store `feeDelta=5` to designate a modified fee of `105`. Lets say this code wants to change that to a modified fee of `107`. Then this `delta` argument here would be `7`. In this case, inside the old `CTxMemPoolEntry::UpdateFeeDelta()` the variables `nModFeesWithDescendants` and `nModFeesWithAncestors` would be incremented with `2`, and `7` would be stored in `feeDelta` (to designate a modified fee of `107` (`nFee=100` plus `feeDelta=7`).

After this PR we would store `modified_fee=105` to designate a modified fee of `105`. Then this code gets executed with argument `delta=7`. The new `CTxMemPoolEntry::UpdateModifyFee()` would increment the variables `nModFeesWithDescendants` and `nModFeesWithAncestors` with `7` (not with `2` as before) and would store `105+7=112` in `modified_fee` to designate a modified fee of `112` (not `107`).

Either this call site, or the method `UpdateModifyFee()` has to be changed in order to keep the same behavior, or I miss something. I think the other call site of `UpdateModifyFee()` is correct.

File: src/txmempool.cpp (hunk 3 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: Thx, already fixed in master.

File: src/txmempool.cpp [hunk 7]
```diff
@@ -54,14 +55,14 @@ struct update_ancestor_state
...
 {
-    explicit update_fee_delta(int64_t _feeDelta) : feeDelta(_feeDelta) { }
+    explicit update_modify_fee(CAmount modify_fee) : modify_fee{modify_fee} {}
 
-    void operator() (CTxMemPoolEntry &e) { e.UpdateFeeDelta(feeDelta); }
+    void operator()(CTxMemPoolEntry& e) { e.UpdateModifyFee(modify_fee); }
 
 private:
-    int64_t feeDelta;
+    CAmount modify_fee;
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/txmempool.cpp]: Thx, already fixed in master.

File: src/txmempool.cpp (hunk 4 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: Thx, changed to `UpdateModifiedFee(fee_diff)` as suggested.

File: src/txmempool.h (hunk 5 above)
Comment (MarcoFalke) [reply src/txmempool.h:104]: Thx, done

File: src/txmempool.cpp (hunk 6 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: This code path is for newly added txs. Thus, `nFee` is always equal to `modified_fee` before this call to update the fee. It is not possible to execute this code for txs that have already been added, whose fee is modified repeatedly.

Luckily we have tests to catch this.

If I am missing something, it might be good if you write a test (or explain steps to reproduce).

**Comment by MarcoFalke** [comment]
Rebased and replied to all comments. Also changed the name of the update function.

File: src/txmempool.cpp (hunk 6 above)
Comment (vasild) [reply src/txmempool.cpp]: Ok, so the behavior of the code before and after this PR is the same only in the case where `feeDelta` is `0` (old code) / `nFee` is equal to `modified_fee` (new code). It is quite obscure to me whether this code is executed only for such cases (and will always be in the future). What about adding an assert to ensure that:

```diff
     if (delta) {
-        mapTx.modify(newit, [&delta](CTxMemPoolEntry& e) { e.UpdateModifiedFee(delta); });
+        mapTx.modify(newit, [&delta](CTxMemPoolEntry& e) {
+            assert(e.GetFee() == e.GetModifiedFee());
+            e.UpdateModifiedFee(delta);
+        });
     }
```

or, to preserve the behavior in all cases, not just when `feeDelta=0`:

```diff
     if (delta) {
-        mapTx.modify(newit, [&delta](CTxMemPoolEntry& e) { e.UpdateModifiedFee(delta); });
+        mapTx.modify(newit, [&delta](CTxMemPoolEntry& e) {
+            e.UpdateModifiedFee(e.GetModifiedFee() - e.GetFee() + delta);
+        });
     }
```

I would be more comfortable with the second variant as it preserves the behavior in all cases and there is no chance that a newly added assert is too strong and is triggered unintentionally by a legit code.

Comment (MarcoFalke) [reply src/txmempool.cpp]: I don't like the second variant, because it makes the code more verbose and confusing. Also, it will lead to signed integer overflow (the thing that this pull is trying to solve).

Comment (MarcoFalke) [reply src/txmempool.cpp]: I've pushed a documention update to make it clearer along with an `Assume`. I don't think an `assert` is the right thing to pick here. It seems incredibly unlikely that someone is going to modify the code while violating the assumption and at the same time have passing tests (hopefully added in the same patch that modifies the code). So I am also happy to remove the `Assume` again, if deemed useless.

Comment (vasild) [reply src/txmempool.cpp]: Ok, IMO it is better with the `Assume()` compared to without any protection.

This call site is kind of misusing the `UpdateModifiedFee()` method whose semantic is to alter the existent value with a provided delta, while this call site is actually trying to _set_ the value. It works as long as the value is `0` here, before the call.

What about introducing a new method to set the modified fee and use it here?

```cpp
void CTxMemPoolEntry::SetModifiedFee(CAmount modified_fee_)
{
    nModFeesWithDescendants = modified_fee_;
    nModFeesWithAncestors = modified_fee_;
    modified_fee = modified_fee_;
}
```

Or check that what we intended was actually done correctly afterwards:

```diff
     if (delta) {
         mapTx.modify(newit, [&delta](CTxMemPoolEntry& e) { e.UpdateModifiedFee(delta); });
+        Assume(entry.GetModifiedFee() == SaturatingAdd(entry.GetFee(), delta));
     }
```

**Review by vasild — APPROVED** [review]
ACK fac053d9d883ed87707b62f87ab107d41d9cdf50

Consider https://github.com/bitcoin/bitcoin/pull/23418#discussion_r839437631

File: src/txmempool.cpp (hunk 6 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: I think it is fine to call `UpdateModifiedFee` to set the initial fee update. Introducing a new method doesn't allow to get rid of the Assumption that the fee wasn't previously modified.

Happy to move the `Assume`/comment after the mapTx.modify call.

File: src/txmempool.h [hunk 8]
```diff
@@ -101,7 +101,7 @@ class CTxMemPoolEntry
     const unsigned int entryHeight; //!< Chain height when entering the mempool
     const bool spendsCoinbase;      //!< keep track of transactions that spend a coinbase
     const int64_t sigOpCost;        //!< Total sigop cost
-    CAmount feeDelta{0};            //!< Used for determining the priority of the transaction for mining in a block
+    CAmount modified_fee;           //!< Used for determining the priority of the transaction for mining in a block
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/txmempool.h]: thx, fixed.

**Review by vasild — APPROVED** [review]
ACK fa471a7ae273d3bf8f956e8a862d0b586dd3fe4b

File: src/txmempool.cpp (hunk 6 above)
Comment (MarcoFalke) [reply src/txmempool.cpp]: Closing thread for now. Let me know if I should reopen.

File: src/txmempool.cpp [hunk 9]
```diff
@@ -82,18 +83,19 @@ CTxMemPoolEntry::CTxMemPoolEntry(const CTransactionRef& tx, CAmount fee,
...
+      m_modified_fee{nFee},
       lockPoints{lp},
       nSizeWithDescendants{GetTxSize()},
       nModFeesWithDescendants{nFee},
       nSizeWithAncestors{GetTxSize()},
       nModFeesWithAncestors{nFee},
       nSigOpCostWithAncestors{sigOpCost} {}
 
-void CTxMemPoolEntry::UpdateFeeDelta(CAmount newFeeDelta)
+void CTxMemPoolEntry::UpdateModifiedFee(CAmount fee_diff)
```
Comment (LarryRuane) [inline src/txmempool.cpp:95]: Would a better name be `IncrementModifiedFee`? The verb "update" isn't wrong, but it could mean simply setting a variable to a value (as in a simple assignment statement). The verb "increment" makes it clear that a variable, or, in this case, 3 variables, are being incremented by the argument. It's true that the previous name used the verb "update", so maybe it would be best to preserve that. But I just thought I'd mention it for consideration.

File: src/txmempool.cpp [hunk 10]
```diff
@@ -921,7 +925,7 @@ void CTxMemPool::PrioritiseTransaction(const uint256& hash, const CAmount& nFeeD
         delta += nFeeDelta;
```
Comment (LarryRuane) [inline src/txmempool.cpp]: `delta` is now unused

**Review by LarryRuane — COMMENTED** [review]
Rebased onto latest master (7377ed778c6d832ecd291e65b2789af7bac2ae2b), was able to reproduce the bug both using RPC and fuzzing, and the bug is fixed using the PR (both ways).

You could make a couple of small fixes in the description: dot before `/autogen.sh`, and add `-chain=regtest` to the `bitcoin-cli` command lines.

In the first commit message, s/tacked/tracked/.

File: src/txmempool.cpp (hunk 9 above)
Comment (MarcoFalke) [reply src/txmempool.cpp:95]: I agree, but maybe this can be done as a follow up to also rename the `Update*State` functions, which do the same thing, but are not touched in this pull request.

**Review by vasild — APPROVED** [review]
ACK fa07f84e316171d60dd9941fb8db37e0a0de6654

**Review by dunxen — APPROVED** [review]
ACK fa07f84

**Comment by michaelfolkson** [comment]
Concept ACK, Approach ACK. 

The saturating approach (as discussed in today's [PR review club](https://bitcoincore.reviews/23418) makes sense over alternative approaches. Reviewed code changes, didn't test unfortunately.

**Review by LarryRuane — COMMENTED** [review]
ACK fa07f84e316171d60dd9941fb8db37e0a0de6654
I reproduced the bug on master both using RPC and fuzzing, and the bug is fixed using the PR (both ways)/
