### PR TITLE
Give a better error message if system clock is bad

### LINKED ISSUE #2007: (serious) bug with wrong system clock
I set my computers date to 2012-07-13 and tried to start the client (current master) and during startup it simply crashes. This is from the debug.log:

<pre>
07/13/12 13:56:32 ERROR: CheckBlock() : block timestamp too far in the future
07/13/12 13:56:32 LoadBlockIndex() : *** found bad block at 34105, hash=0000000037c57b5ff0ebedd38469b9797c89e8640cbcd52dc967d3805e487b51
07/13/12 13:56:32 ERROR: LoadBlockIndex(): chain database corrupted
</pre>

There should be a check and warning like the one in util.cpp - AddTimeData(), but this needs to be done from some core dev.

### PR DESCRIPTION
**Pull request by casey**
Fixes #2007

This checks to see if the system clock appears to be bad and gives a
helpful error message. If the user's clock is set incorrectly, hopefully
they'll abort, fix it, and then save themselves a fruitless resync.

I wasn't sure if I needed to grab cs_main before accessing chainActive.Tip(), is that correct?

### CODE REVIEW

**Comment by sipa** [comment]
You do need cs_main for that.

File: src/init.cpp [hunk 1]
```diff
@@ -1225,6 +1225,19 @@ bool AppInit2(boost::thread_group& threadGroup, CScheduler& scheduler)
                     LogPrintf("Prune: pruned datadir may not have more than %d blocks; -checkblocks=%d may fail\n",
                         MIN_BLOCKS_TO_KEEP, GetArg("-checkblocks", 288));
                 }
+
+                {
+                    LOCK(cs_main);
+                    CBlockIndex* tip = chainActive.Tip();
+                    CBlock block;
+                    if (tip && ReadBlockFromDisk(block, tip)) {
```
Comment (laanwj) [inline src/init.cpp]: Any specific reason to read the block from disk here? Reminder: `tip` itself, a `CBlockIndex`, also has `nTime`

**Comment by laanwj** [comment]
Concept ACK

File: src/init.cpp (hunk 1 above)
Comment (casey) [inline src/init.cpp]: Ahh, okay. Fixed.

**Comment by casey** [comment]
Updated the commit to use chainActive.Tip()->nTime directly

File: src/init.cpp [hunk 2]
```diff
@@ -1225,6 +1225,16 @@ bool AppInit2(boost::thread_group& threadGroup, CScheduler& scheduler)
                     LogPrintf("Prune: pruned datadir may not have more than %d blocks; -checkblocks=%d may fail\n",
                         MIN_BLOCKS_TO_KEEP, GetArg("-checkblocks", 288));
                 }
+
+                {
+                    LOCK(cs_main);
+                    CBlockIndex* tip = chainActive.Tip();
+                    if (tip && tip->nTime > GetAdjustedTime() + 2 * 60 * 60) {
+                        strLoadError = _("The block database contains a block which appears to be from the future. This may be due to your computer's date and time being set incorrectly. Only rebuild the block database if you are sure that your computer's date and time are correct");
```
Comment (bensussman) [inline src/init.cpp]: Is there no styleguide for the bitcoin codebase that says ">250 character lines are just TOO LONG @casey"?!

Comment (casey) [inline src/init.cpp]: This string is going to be translated via gettext (that's what the "_" is for) so it's better than it appear in the source as one line, as opposed to being broken up.

Comment (laanwj) [inline src/init.cpp]: @bensussman To answer your question: no, there is no such rule. See https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md 

@casey Using multiple "line" "line2" line3" does not affect translation IIRC if you specify only one `_`, eg:
```c++
strLoadError = _("The block database contains a block which appears to be from the future. "
    "This may be due to your computer's date and time being set incorrectly. "
    "Only rebuild the block database if you are sure that your computer's date and time are correct");
```

**Comment by casey** [comment]
Changed to use less ridiculously long strings.

**Comment by laanwj** [comment]
utACK

**Comment by sipa** [comment]
utACK

**Comment by fanquake** [comment]
utACK

File: src/init.cpp [hunk 3]
```diff
@@ -1225,6 +1225,18 @@ bool AppInit2(boost::thread_group& threadGroup, CScheduler& scheduler)
                     LogPrintf("Prune: pruned datadir may not have more than %d blocks; -checkblocks=%d may fail\n",
                         MIN_BLOCKS_TO_KEEP, GetArg("-checkblocks", 288));
                 }
+
+                {
+                    LOCK(cs_main);
+                    CBlockIndex* tip = chainActive.Tip();
+                    if (tip && tip->nTime > GetAdjustedTime() + 2 * 60 * 60) {
+                        strLoadError = _("The block database contains a block which appears to be from the future. "
+                                "This may be due to your computer's date and time being set incorrectly. "
```
Comment (Diapolo) [inline src/init.cpp]: ``computer's`` is some weird grammar, no?

Comment (NanoAkron) [inline src/init.cpp]: Not really. It indicates that the computer is the owner of the date & time, which in this case it is.
