### PR TITLE
fix crash on shutdown when e.g. changing -txindex and abort action

### LINKED ISSUE #3136: [Qt] Do you want to rebuild the block database now? No -> crash
I'm using -txindex in my normal environment, when using payment requests without the client running, the client is started without any parameters and detects the missing -txindex and asks me ``Do you want to rebuild the block database now?`` answering no here crashes the client.

https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L834

@sipa Can you check that part of the code, as most of it was done by you :).

Edit: Error is on Win7 x64 and it's a BEX (Buffer Overflow Exception).

### PR DESCRIPTION
**Pull request by Diapolo**
- fixes #3136
- the problem is related to Boost path and a static initialized internal
  pointer
- using a std::string in CDBEnv::EnvShutdown() prevents the problem

### CODE REVIEW

File: src/wallet/db.h [hunk 1]
```diff
@@ -28,6 +28,7 @@ class CDBEnv
     bool fDbEnvInit;
     bool fMockDb;
     boost::filesystem::path path;
```
Comment (laanwj) [inline src/wallet/db.h]: Shouldn't this field go away, then?

Comment (Diapolo) [inline src/wallet/db.h]: I didn't replace all occurances, because it's used when building paths still.

Comment (laanwj) [inline src/wallet/db.h]: Do add a comment then, on why the duplicated field was added. Otherwise people will be really confused to read this code.

**Comment by laanwj** [comment]
If `boost::path` gives any problems at static deinitialization, I still dont feel good with this.

My suggestion would be to precompute all the usages of `path` in `CDBEnv::Open`. E.g.

    std::string strPath;
    std::string strPathLogDir;

Then in the initialization

    strPath = pathIn.string();
    strPathLogDir = pathLogDir.string();

Remove the `boost::filesystem::path path` field. Replace the usages of `path` outside `CDBEnv::Open` with these precomputed strings.

**Comment by Diapolo** [comment]
@laanwj That suggestion is fine, I tried to be minimal invasive but will gladly remove the path field.

**Comment by Diapolo** [comment]
@laanwj See pull after rebase, I removed the ``path`` field, but as quite some functions require a boost::filesystem::path I couldn't eliminate all uses (e.g. ``TryCreateDirectory()`` and ``boost::filesystem::remove_all()``).

**Comment by Diapolo** [comment]
Seems the build faulire is unrelated to the pull: "No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated"

**Comment by laanwj** [comment]
Looks good to me, utACK, travis error is the misbehaving comparison tool again...

**Comment by Diapolo** [comment]
Now it passed, great!

**Comment by laanwj** [comment]
> I removed the path field, but as quite some functions require a boost::filesystem::path I couldn't eliminate all uses

Right. Eliminating the uses of boost::filesystem is not the goal here, just avoiding that a static `filesystem::path` field stays around as part of CDBEnv, which this does now.

File: src/wallet/db.h [hunk 2]
```diff
@@ -27,7 +27,7 @@ class CDBEnv
 private:
     bool fDbEnvInit;
     bool fMockDb;
-    boost::filesystem::path path;
+    std::string strPath;
```
Comment (laanwj) [inline src/wallet/db.h]: Please add a comment here why this field is a string instead of a `boost::filesystem::path`, so that a future smart-ass doesn't think "hey let's use that type directly".

Comment (Diapolo) [inline src/wallet/db.h]: Done!

**Comment by sipa** [comment]
utACK

**Comment by laanwj** [comment]
Backported to 0.11 as daf956b7b196769f8027026dd047e72412a9a039, thanks @luke-jr for the heads up
