### PR TITLE
[gui] reset addrProxy/addrSeparateProxyTor if colon char missing

### LINKED ISSUE #11209: [GUI] Proxies in QSettings storage without a colon cause crashes when options dialog is opened
If `addrProxy` or `addrSeparateProxyTor` do not have a colon in the string somewhere in the QSettings storage, then attempting to open the options dialog will cause the entire program to crash.

I'm not sure if this is really a problem since it is impossible to make those strings not have colons in them from normal operation. In order to replicate this, you must modify what QSettings stores (a conf file in Linux and Registry in Windows).

### PR DESCRIPTION
**Pull request by mess110**
If addrProxy or addrSeparateProxyTor do not have a colon in the string
somewhere in the QSettings storage, then attempting to open the options
dialog will cause the entire program to crash.

Fixes #11209

### CODE REVIEW

File: src/qt/optionsmodel.cpp [hunk 1]
```diff
@@ -126,6 +126,8 @@ void OptionsModel::Init(bool resetSettings)
         settings.setValue("fUseProxy", false);
     if (!settings.contains("addrProxy"))
         settings.setValue("addrProxy", "127.0.0.1:9050");
+    if (!settings.value("addrProxy").toString().contains(':'))
```
Comment (achow101) [inline src/qt/optionsmodel.cpp]: Can you just make this an OR with the if statement above?

Comment (mess110) [reply src/qt/optionsmodel.cpp]: Done

**Comment by MeshCollider** [comment]
Please change PR description to say 'Fixes #11209' so that GitHub auto-closes the issue if this is merged

**Comment by jonasschnelli** [comment]
Can't reproduce the #11209 crash on OSX.
Also, there are probably other situations where a corrupted or manually edited QSettings files may lead to a crash.

But this is better then noting.

Concept ACK

**Comment by jonasschnelli** [comment]
utACK ce2418fa4cef5514305cca82e74891b9d643c4c7

**Comment by mess110** [comment]
@MeshCollider To check this I just deleted the : from `addrProxy`: `127.0.0.19050`. My though process was: corrupt? ok, rewrite. My goal was to avoid the crash.

**Comment by MeshCollider** [comment]
Fair enough I guess. utACK

**Comment by laanwj** [comment]
utACK,

though I'm not sure I agree the original issue is really an issue - this can only be reached by manually tampering with the settings, which can mess up the client in a lot of ways.

**Comment by achow101** [comment]
utACK ce2418fa4cef5514305cca82e74891b9d643c4c7

**Comment by promag** [comment]
AFAIK it doesn't fix the issue when the settings is changed in runtime externally.

I think the settings value should be validated when used. In this case the `.split(":")[1]` wouldn't crash. This is also relevant when a setting can be upgraded/extended to a new format and/or have default values for the missing bits (port in this case).

In this particular case I would say the fix could be the introduction/usage of a decent address parser.

utACK ce2418f considering it's an remote use case.

**Comment by laanwj** [comment]
> AFAIK it doesn't fix the issue when the setting is changed in runtime externally.

The setting is only ever loaded from the qsettings at startup. Changing it at runtime does nothing.
