### PR TITLE
Use std::filesystem. Remove Boost Filesystem & System

### LINKED ISSUE #20460: C++17 std::fs
C++17 std::fs would be useful for a stronger rename method (#20435) and dropping boost fs in favor of the stdlib (#19245).

However, we currently use bionic to compile gitian binaries, which uses gcc-7 by default. If we are ok switching to gcc-8 on bionic for our gitian builds and everyone compiling from source on bionic, we could start using std::fs

### LINKED ISSUE #23846: No match for fs::path operator+= when compiling with Boost 1.78
With Boost 1.78 (installed on my system), I get a compiler error:

```
./fs.h: In function ‘fs::path fs::operator+(fs::path, fs::path)’:
./fs.h:91:8: error: no match for ‘operator+=’ (operand types are ‘fs::path’ and ‘std::remove_reference<fs::path&>::type’ {aka ‘fs::path’})
   91 |     p1 += std::move(p2);
      |     ~~~^~~~~~~~~~~~~~~~
```

It appears that in Boost 1.78, `operator+=` became a template function, and our `path` class which subclasses `boost::filesystem::path::path` no longer has an `operator+=` which will work with it.

I also opened an issue with boost: https://github.com/boostorg/filesystem/issues/223

### PR DESCRIPTION
**Pull request by fanquake**
This PR replaces our Boost Filesystem usage with [`std::filesystem`](https://en.cppreference.com/w/cpp/filesystem) and includes dropping Boost System as a dependency. It includes a squashed down version of the changes from #19245. 

[A macro has been added](https://github.com/bitcoin/bitcoin/commit/7002c4ade0148c3273659208ae517b79822b289d), modelling how we check for `-latomic` to facilitate linking with `-lstdc++fs` when required. This is  ~GCC < 9.1 & ~Clang < 9.0, however not always. i.e you could be using Clang 7 on top of a GCC 9 installation (i.e Ubuntu Focal) and use `<filesystem>` without passing any additional arguments. I've tested this with GCC 8 on Bionic, Clang 7 on Focal & with Apple Clang 12.0.0 on macOS.

Guix build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
c1f9b326f9be4140f00cebeae5ff8de428a2fb8ecced539fcc36c53f53bfecf4  guix-build-07269321f38e/output/aarch64-linux-gnu/SHA256SUMS.part
b44aca3bcf5ea92a3a6c48c24d6f85576f425f59b73528d4d00c20e950cf2128  guix-build-07269321f38e/output/aarch64-linux-gnu/bitcoin-07269321f38e-aarch64-linux-gnu-debug.tar.gz
27a5553f7bd14797293fc40c5fb131c91e98a61d5481a283f13a1d0497eb5ed8  guix-build-07269321f38e/output/aarch64-linux-gnu/bitcoin-07269321f38e-aarch64-linux-gnu.tar.gz
99e55a88823f6095864a09c9eaa824e24d9ec527380eb394f751c7205b930f69  guix-build-07269321f38e/output/arm-linux-gnueabihf/SHA256SUMS.part
b720b2724fa47fde584f58ed3b587f1d1183523540777fd367ab7e582605cfea  guix-build-07269321f38e/output/arm-linux-gnueabihf/bitcoin-07269321f38e-arm-linux-gnueabihf-debug.tar.gz
c19c247f4e9e0d7f888ac8ba9de1c12d382f48fa828a685d4fe02818a18abd1f  guix-build-07269321f38e/output/arm-linux-gnueabihf/bitcoin-07269321f38e-arm-linux-gnueabihf.tar.gz
55b49ccb38de03bb95101354a16fd8d2190abede5ccc0d9b00b40c0cd526a2f6  guix-build-07269321f38e/output/arm64-apple-darwin/SHA256SUMS.part
baa44752470a6be9acae1c2f8fd1b9bc37afb00971787ea11fbaeddc9ab7c4aa  guix-build-07269321f38e/output/arm64-apple-darwin/bitcoin-07269321f38e-arm64-apple-darwin.tar.gz
ad7df4d8026d5bcce1321cdccc2e1820e8a8bb7e1064ed16e20a7ea354057fd2  guix-build-07269321f38e/output/arm64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.dmg
f342066dc34a14d67c47779a2413a14633a996e8e7ddca89ae0184e23ef99efd  guix-build-07269321f38e/output/arm64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.tar.gz
f6905346a5d48f57805fb062d0247ab5007c89047070a0b3125941dd1a2b8aa6  guix-build-07269321f38e/output/dist-archive/bitcoin-07269321f38e.tar.gz
a1f6c4b2b118dbd89770801f0bcffd2218b82df408cd227e34c40493469bb7a2  guix-build-07269321f38e/output/powerpc64-linux-gnu/SHA256SUMS.part
ba8359426e523bf013d93579c1bedc57380214c8170a9743b64ec1a8a3bbccbf  guix-build-07269321f38e/output/powerpc64-linux-gnu/bitcoin-07269321f38e-powerpc64-linux-gnu-debug.tar.gz
b0bb500c274a683ea28ecbc1e8f18c618a9f8acb00045f80ae43c515288402c0  guix-build-07269321f38e/output/powerpc64-linux-gnu/bitcoin-07269321f38e-powerpc64-linux-gnu.tar.gz
38c85e9589e092cd3aa08996aa383c0ccd5c73208943389741355a6eb7f72537  guix-build-07269321f38e/output/powerpc64le-linux-gnu/SHA256SUMS.part
50fcba7942ff48d91e84c093fda0affc17e46167fe1d5137c6e14c5c41f289d1  guix-build-07269321f38e/output/powerpc64le-linux-gnu/bitcoin-07269321f38e-powerpc64le-linux-gnu-debug.tar.gz
fa08ef1ceca072e014faa95ffee945954b2976fa28f90926b87ab0e5f15f8ca5  guix-build-07269321f38e/output/powerpc64le-linux-gnu/bitcoin-07269321f38e-powerpc64le-linux-gnu.tar.gz
e52dd80a9c306d6aeb544acaa1f4ed560b6b92b5184764a05026d45451aa2e94  guix-build-07269321f38e/output/riscv64-linux-gnu/SHA256SUMS.part
864e0a16c485b4159cec3ee0a83b046f1b1c3bc821670011c5ac5cd09ddfb91f  guix-build-07269321f38e/output/riscv64-linux-gnu/bitcoin-07269321f38e-riscv64-linux-gnu-debug.tar.gz
4a061172181322e7ad0cf06405bf74f4c8683eaba3a67ecfd46158cba7627f62  guix-build-07269321f38e/output/riscv64-linux-gnu/bitcoin-07269321f38e-riscv64-linux-gnu.tar.gz
876d82251853205420dffe7237523fc6ee3d09f78bf74cc03dc71f548446f335  guix-build-07269321f38e/output/x86_64-apple-darwin/SHA256SUMS.part
3f82b2e62c60eee68e7b8fc28e4792e069e3c2cd780ee2d67290ca422cdbc47c  guix-build-07269321f38e/output/x86_64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.dmg
4ccdd4c410cac9d627e54ce83ee4816608681735da3cb93c60c5eb70ca86337a  guix-build-07269321f38e/output/x86_64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.tar.gz
2179d36b2f60e28c15262d4e51f27465b5ae077f60e550345e125683ca611066  guix-build-07269321f38e/output/x86_64-apple-darwin/bitcoin-07269321f38e-osx64.tar.gz
b377e72fe84b6a982b8d414d60c85e6319523dff50dc852a0ba907f6d850ddd0  guix-build-07269321f38e/output/x86_64-linux-gnu/SHA256SUMS.part
8547e2f582ce05ae6a6224793b64efb2eb63f2816bf0bed5d53fcc4786274597  guix-build-07269321f38e/output/x86_64-linux-gnu/bitcoin-07269321f38e-x86_64-linux-gnu-debug.tar.gz
83b64805aa39f31a6fa4c2ed41e029c3be084e6dea06b90fac1ebca5c95bce29  guix-build-07269321f38e/output/x86_64-linux-gnu/bitcoin-07269321f38e-x86_64-linux-gnu.tar.gz
```

### CODE REVIEW

File: ci/test/00_setup_env_native_nowallet.sh [hunk 1]
```diff
@@ -7,8 +7,8 @@
 export LC_ALL=C.UTF-8
 
 export CONTAINER_NAME=ci_native_nowallet
-export DOCKER_NAME_TAG=ubuntu:18.04  # Use bionic to have one config run the tests in python3.6, see doc/dependencies.md
-export PACKAGES="python3-zmq clang-5.0 llvm-5.0"  # Use clang-5 to test C++17 compatibility, see doc/dependencies.md
+export DOCKER_NAME_TAG=ubuntu:20.04
```
Comment (MarcoFalke) [inline ci/test/00_setup_env_native_nowallet.sh:10]: Would be nice to not change this. clang-7 is also in bionic: 

* https://packages.ubuntu.com/bionic-updates/clang-7

File: ci/test/00_setup_env_win64.sh [hunk 2]
```diff
@@ -7,7 +7,7 @@
 export LC_ALL=C.UTF-8
 
 export CONTAINER_NAME=ci_win64
-export DOCKER_NAME_TAG=ubuntu:18.04  # Check that bionic can cross-compile to win64 (bionic is used in the gitian build as well)
+export DOCKER_NAME_TAG=ubuntu:20.04
```
Comment (MarcoFalke) [inline ci/test/00_setup_env_win64.sh:10]: the comment should stay to say that this is the version used in gitian as well. I presume this pull is blocked (waiting on) gitian getting bumped to focal? Thus the label "waiting for other".

**Review by maflcko — COMMENTED** [review]
Concept ACK for 0.23 (earliest), given that this again requires a bunch of aggressive bumps.

**Comment by sheffine** [comment]
Hello Marco,
Good morning, this is Sheffine one of Bitcore customer .My repositories  is
sitting on githib since 2017, I have lost my private keys and recently
found them .
I have reached out to bit-pay regarding my bitcoins and was directed to
GitHub.
I believe Luke was working on my file so I sent him an email but haven't
heard from him. I just noticed that your name showed up on my dashboard so
I am not sure if you are the one who is now assigned to the project.

What I basically need is someone assistance with computing the Bitcoin to
my wallet, not sure if this the right word😄I an sure there will be a cost
to do so.
I I am very confused and don't know where to start.Your assistance will be
appreciated .

Thanks Sheffine

File: ci/test/00_setup_env_win64.sh (hunk 2 above)
Comment (MarcoFalke) [reply ci/test/00_setup_env_win64.sh:10]: Oh, and this has to be bumped in the cirrus yaml as well (Sorry, confusing, but I didn't find a way around this redundancy)

**Comment by MarcoFalke** [comment]
@sheffine Usually the issue tracker is used to track technical issues related to the Bitcoin Core code base. Keep in mind that general bitcoin questions and/or support requests are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com) or the `#bitcoin` IRC channel on freenode.

File: src/test/util_tests.cpp [hunk 3]
```diff
@@ -50,19 +50,19 @@ BOOST_AUTO_TEST_CASE(util_datadir)
     ClearDatadirCache();
     const fs::path dd_norm = GetDataDir();
 
-    gArgs.ForceSetArg("-datadir", dd_norm.string() + "/");
+    gArgs.ForceSetArg("-datadir", dd_norm.string());
```
Comment (vasild) [inline src/test/util_tests.cpp:53]: Why this change? Does it break with `+ "/"`?

File: ci/test/00_setup_env_win64.sh (hunk 2 above)
Comment (fanquake) [reply ci/test/00_setup_env_win64.sh:10]: > Oh, and this has to be bumped in the cirrus yaml as well

Thanks. Did not realise that was required.

File: src/wallet/wallettool.cpp [hunk 4]
```diff
@@ -105,7 +105,7 @@ static void WalletShowInfo(CWallet* wallet_instance)
 
 bool ExecuteWalletToolFunc(const ArgsManager& args, const std::string& command, const std::string& name)
 {
-    fs::path path = fs::absolute(name, GetWalletDir());
+    fs::path path = fs::absolute((name == "") ? GetWalletDir() : (GetWalletDir() / name));
```
Comment (vasild) [inline src/wallet/wallettool.cpp:108]: Why not just `GetWalletDir() / name` even if `name` is empty?

**Review by mjdietzx — COMMENTED** [review]
Nice‼️ Concept Ack

I didn't have any problems building and running some tests locally on my machine. Also, there's a minor TODO that kind of got lost in the mix here. I had a PR for it when we were on boost https://github.com/bitcoin/bitcoin/pull/20265

I rebased on your branch and tested it out, seems to work: https://github.com/mjdietzx/bitcoin/commit/55bafb983d9642e304beefd21017aa4099e96ec3 - not sure if you want to pull it into this PR, or once this get merged I'll re-open the PR

File: src/wallet/load.cpp [hunk 5]
```diff
@@ -62,7 +62,7 @@ bool VerifyWallets(interfaces::Chain& chain)
     std::set<fs::path> wallet_paths;
 
     for (const auto& wallet_file : gArgs.GetArgs("-wallet")) {
-        const fs::path path = fs::absolute(wallet_file, GetWalletDir());
+        const fs::path path = fs::absolute(GetWalletDir() / wallet_file);
```
Comment (ryanofsky) [inline src/wallet/load.cpp:65]: I think this isn't equivalent if wallet_file is the empty string (this will add trailing slash now, wouldn't add trailing slash previously).

**Review by ryanofsky — COMMENTED** [review]
This seems good, but it would be nice to move code changes to their own PR separate from the build changes, so they can get better review and so the final code is simpler. (It would be nice if final code wasn't checking for empty strings multiple places and wasn't calling `fs::absolute` on paths already known to be absolute.)

I think an initial PR simplifying this one would just replace `fs::system_complete(x)` with `fs::absolute(x)` and replace `fs::absolute(x, y)` with `AbsPathJoin(y, x)` everywhere. `AbsPathJoin` would be a util function defined like:

```c++
fs::path AbsPathJoin(fs::path p1, fs::path p2)
{
    assert(p1.is_absolute());
    return boost::filesystem::absolute(p2, p1);
}
```

Then I think this PR wouldn't need to touch any meaningful code except one line in AbsPathJoin:

```c++
fs::path AbsPathJoin(fs::path p1, fs::path p2)
{
    assert(p1.is_absolute());
    return p2.empty() ? p1 : p1 / p2;
}
```

**Comment by kiminuo** [comment]
@ryanofsky It is maybe worth reading "Differences between filesystem implementations that affects Bitcoin code" in https://github.com/bitcoin/bitcoin/pull/19245.

**Comment by ryanofsky** [comment]
> @ryanofsky It is maybe worth reading "Differences between filesystem implementations that affects Bitcoin code" in #19245.

Thanks, I've saw it but don't think it takes into account the "appends path::preferred_separator" behavior described https://en.cppreference.com/w/cpp/filesystem/path/append which can result in trailing slashes and is different from boost::absolute behavior https://www.boost.org/doc/libs/1_66_0/libs/filesystem/doc/reference.html#absolute.

Also I think it is clearer and better to avoid calling fs::absolute on paths that we already know are absolute. Ideally we would go further and never call fs::absolute or fs::system_complete after daemonization. Behavior of code shouldn't change depending on the process working directory, and in most cases it makes sense from a usability perspective to interpret paths relative to the data directory or wallet directory, not the process working directory.

File: src/rpc/blockchain.cpp [hunk 6]
```diff
@@ -2393,10 +2393,10 @@ static RPCHelpMan dumptxoutset()
         },
         [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
 {
-    fs::path path = fs::absolute(request.params[0].get_str(), GetDataDir());
+    fs::path path = fs::absolute(GetDataDir() / request.params[0].get_str());
     // Write to a temporary path and then move into `path` on completion
     // to avoid confusion due to an interruption.
-    fs::path temppath = fs::absolute(request.params[0].get_str() + ".incomplete", GetDataDir());
+    fs::path temppath = fs::absolute(GetDataDir() / request.params[0].get_str() / ".incomplete");
```
[the remark this answers is not in the document]
Comment (fanquake) [reply src/rpc/blockchain.cpp:2399]: Thanks, I've fixed this in the next push.

**Comment by practicalswift** [comment]
Concept ACK

File: src/wallet/load.cpp (hunk 5 above)
Comment (kiminuo) [reply src/wallet/load.cpp:65]: Yes, this simple sample confirms it:

```cpp
// Run with: g++ --std=c++17 path.cpp && ./a.out

#include <string>
#include <iostream>
#include <filesystem>
namespace fs = std::filesystem;

int main()
{
    fs::path walletDir = "/home/user";
    std::string wallet_file = "";
    fs::path path = fs::absolute(walletDir / wallet_file);

    std::cout << "walletDir = " << walletDir << "\n"; // walletDir = "/home/user"
    std::cout << "path      = " << path << "\n";      // path      = "/home/user/"
}
```

Comment (ryanofsky) [reply src/wallet/load.cpp:65]: In commit "refactor: replace boost::filesystem with std::filesystem" (f449c26f30bb8e223d4d7833c579d555a0005daa)

re: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r556553883

> Yes, this simple sample confirms it:

Issue should be resolved when this is rebased after #20932.

File: src/wallet/wallet.cpp [hunk 7]
```diff
@@ -3780,11 +3780,11 @@ std::unique_ptr<WalletDatabase> MakeWalletDatabase(const std::string& name, cons
     // 2. Path to an existing directory.
     // 3. Path to a symlink to a directory.
     // 4. For backwards compatibility, the name of a data file in -walletdir.
-    const fs::path& wallet_path = fs::absolute(name, GetWalletDir());
+    const fs::path& wallet_path = fs::absolute((name == "") ? GetWalletDir() : (GetWalletDir() / name));
```
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/wallet/wallet.cpp:3783]: In commit "refactor: replace boost::filesystem with std::filesystem" (f449c26f30bb8e223d4d7833c579d555a0005daa)

re: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r548015393

> same: "Why not just GetWalletDir() / name even if name is empty?"

See https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-750430904, this avoids adding an empty path component and trailing slash if name is empty. This code should be simpler when this is rebased after #20932

File: src/util/system.cpp [hunk 8]
```diff
@@ -728,16 +730,19 @@ const fs::path &GetDataDir(bool fNetSpecific)
...
         }
     } else {
         path = GetDefaultDataDir();
     }
-    if (fNetSpecific)
-        path /= BaseParams().DataDir();
+    if (fNetSpecific) {
+        if (!BaseParams().DataDir().empty()) {
+            path /= BaseParams().DataDir();
+        }
```
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/util/system.cpp:744]: In commit "refactor: replace boost::filesystem with std::filesystem" (f449c26f30bb8e223d4d7833c579d555a0005daa)

re: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r548018984

> similar to "Why not just GetWalletDir() / name even if name is empty?", is another `if` branch really needed here?

See https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-750430904, this avoids adding an empty path component and trailing slash if the base datadir is empty

File: src/wallet/wallettool.cpp (hunk 4 above)
Comment (ryanofsky) [reply src/wallet/wallettool.cpp:108]: In commit "refactor: replace boost::filesystem with std::filesystem" (f449c26f30bb8e223d4d7833c579d555a0005daa)

re: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r547333061

> Why not just `GetWalletDir() / name` even if `name` is empty?

See https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-750430904, this avoids adding an empty path component and trailing slash if name is empty. This code should be simpler when this is rebased after #20932

**Review by ryanofsky — COMMENTED** [review]
Now that #20932 is merged, the messier path joining code and bugs here can disappear when this is rebased. The call sites where AbsPathJoin is used should no longer have to change. And the [`AbsPathJoin`](https://github.com/bitcoin/bitcoin/blob/7f653c3b22f0a5267822eec017aea6a16752c597/src/fs.cpp#L34-L38) implementation can simply be changed to return `path.empty() ? base : base / path` instead of `fs::absolute(path, base)`.

**Comment by kiminuo** [comment]
I have attempted to do the rebase with the `fsbridge::AbsPathJoin` modification: 

* https://github.com/kiminuo/bitcoin/tree/use_std_filesystem_tmp
* https://github.com/bitcoin/bitcoin/compare/master...kiminuo:use_std_filesystem_tmp?expand=1 comparison with master
* git range-diff:
   ```bash
   PREV=8d148b93bb50fe5bfdd6e488f60dced2ded06c88 N=5 && git range-diff `git merge-base --all HEAD $PREV`...$PREV HEAD~$N...HEAD
   ```

**Review by kaycoinsUSA — APPROVED** [review]
Thanks

**Comment by fanquake** [comment]
Thanks @ryanofsky, @kiminuo & others who have commented. I've rebased to account for #20932 and made changes as suggested by Russ.

File: src/util/system.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (kiminuo) [reply src/util/system.cpp:744]: @fanquake I believe this one should be:

```c++
path = fsbridge::AbsPathJoin(path, BaseParams().DataDir());
```

**Comment by kiminuo** [comment]
I can see that `[depends, sanitizers: thread (TSan), no gui] [focal]` check (https://github.com/bitcoin/bitcoin/pull/20744/checks?check_run_id=1747977815) fails so I have run: `MAKEJOBS="-j15" FILE_ENV="./ci/test/00_setup_env_native_tsan.sh" ./ci/test_run_all.sh` to get:

```
test  2021-01-22T13:56:39.722000Z TestFramework.node0 (DEBUG): Node stopped 
 test  2021-01-22T13:56:39.723000Z TestFramework.node1 (DEBUG): Node stopped 
 test  2021-01-22T13:56:39.723000Z TestFramework (WARNING): Not cleaning up dir /home/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193 
 test  2021-01-22T13:56:39.723000Z TestFramework (ERROR): Test failed. Test logging available at /home/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193/test_framework.log 
 test  2021-01-22T13:56:39.746000Z TestFramework (ERROR): 
 test  2021-01-22T13:56:39.754000Z TestFramework (ERROR): Hint: Call /home/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/home/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193' to consolidate all logs 
 test  2021-01-22T13:56:39.754000Z TestFramework (ERROR): 
 test  2021-01-22T13:56:39.754000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log. 
 test  2021-01-22T13:56:39.754000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues 
 test  2021-01-22T13:56:39.755000Z TestFramework (ERROR): 


TEST                                             | STATUS    | DURATION

wallet_hd.py                                     | ✖ Failed  | 45 s

ALL                                              | ✖ Failed  | 45 s (accumulated) 
```

and then `docker attach <ID>` and combined logs per instructions:

```
node1 2021-01-22T13:56:25.176678Z [httpworker.2] error copying wallet.dat to /home/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193/node1/hd.bak - filesystem error: in equivalent: Operation not supported [/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193/node1/regtest/wallets/wallet.dat] [/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193/node1/hd.bak] 
 test  2021-01-22T13:56:38.577000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 126, in main
                                       self.run_test()
                                     File "/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_hd.py", line 46, in run_test
                                       self.nodes[1].backupwallet(os.path.join(self.nodes[1].datadir, "hd.bak"))
                                     File "/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: Error: Wallet backup failed! (-4)
```

and now the files tested on equivalence:

* File `/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193/node1/regtest/wallets` doe/wallet.dat` does exist.
* File `/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20210122_135553/wallet_hd_193/node1/hd.bak` does NOT exist.

And now why is that?

I have put together two samples for `fs::equivalent`:

```cpp
// Run with: g++ --std=c++17 equivalent.cpp17.cpp && ./a.out

#include <string>
#include <iostream>
#include <filesystem>
namespace fs = std::filesystem;

int main()
{
    fs::path pathSrc = "/home/user/a.log";
    fs::path pathDest = "/home/user/b.log";
    bool success = fs::equivalent(pathSrc, pathDest);

    std::cout << "Result is: " << (int)success << "\n";

    // # Case "Both files do not exist"
    // 
    // Exception is thrown:
    // 
    // > terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
    // > what():  filesystem error: cannot check file equivalence: No such file or directory [/home/user/a.log] [/home/user/b.log]
    // > Aborted (core dumped)

    // # Case "pathSrc exists, pathDest does not"
    //
    // No exception. Std output is:
    // > Result is: 0

    // # Case "Both pathSrc and pathDest exist but are different."
    //
    // No exception. Std output is:
    // > Result is: 0    

    // # Case "Both pathSrc and pathDest exist and b.log is symlink for a.log." (`ln -s a.log b.log`)
    //
    // No exception. Std output is:
    // > Result is: 0    
}
```

and Boost variant:

```
// Run with: g++ equivalent.boost.cpp -lboost_system -lboost_filesystem && ./a.out

#include <string>
#include <iostream>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
namespace fs = boost::filesystem;

int main()
{
    fs::path pathSrc = "/home/user/a.log";
    fs::path pathDest = "/home/user/b.log";
    bool success = fs::equivalent(pathSrc, pathDest);

    std::cout << "Result is: " << (int)success << "\n";

    // # Case "Both files do not exist"
    //
    // Exception is thrown:
    // 
    // terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
    //  what():  boost::filesystem::equivalent: Operation not permitted: "/home/user/a.log", "/home/user/b.log"
    // Aborted (core dumped)

    // # Case "pathSrc exists, pathDest does not"
    //
    // No exception. Std output is:
    // > Result is: 0

    // # Case "Both pathSrc and pathDest exist but are different."
    //
    // No exception. Std output is:
    // > Result is: 0    

    // # Case "Both pathSrc and pathDest exist and b.log is symlink for a.log." (`ln -s a.log b.log`)
    //
    // No exception. Std output is:
    // > Result is: 0    
}
```
So these samples shows that `fs::equivalent` behaves similarly in both implementations using `g++`.

And now finally, when I run the sample in Docker:

```
clang++ -stdlib=libc++ --std=c++17 equivalent.cpp17.cpp && ./a.out  # /home/user/a.log EXISTS!

// returns:
// > terminating with uncaught exception of type std::__1::__fs::filesystem::filesystem_error: filesystem error: in equivalent: Operation not supported [/home/user/a.log] [/home/user/b.log]
// > Aborted (core dumped)

clang++ --std=c++17 equivalent.cpp17.cpp && ./a.out 
// returns:
// > Result is: 0
```

So it looks like `-stdlib=libc++` is the culprit. Can anybody verify?

File: src/util/system.cpp [hunk 9]
```diff
@@ -1258,16 +1263,6 @@ void SetupEnvironment()
...
-#endif
-    // The path locale is lazy initialized and to avoid deinitialization errors
-    // in multithreading environments, it is set explicitly by the main thread.
-    // A dummy locale is used to extract the internal default locale, used by
-    // fs::path, which is then used to explicitly imbue the path.
-    std::locale loc = fs::path::imbue(std::locale::classic());
-#ifndef WIN32
-    fs::path::imbue(loc);
-#else
-    fs::path::imbue(std::locale(loc, new std::codecvt_utf8_utf16<wchar_t>()));
```
Comment (ryanofsky) [inline src/util/system.cpp:1270]: In commit "refactor: replace boost::filesystem with std::filesystem" (7810d151f5219e634b431c5393771616c759aef7)

Mentioned in a previous comment but I think a better workaround for lack of `path::imbue` than current approach of calling `fs::u8path` manually would be to use namespace solution from https://stackoverflow.com/questions/42765168/change-narrow-string-encoding-or-missing-stdfilesystempathimbue to call it automatically on windows (and not assume any encoding on other platforms)

File: doc/dependencies.md [hunk 10]
```diff
@@ -7,11 +7,11 @@ These are the dependencies currently used by Bitcoin Core. You can find instruct
 | --- | --- | --- | --- | --- | --- |
 | Berkeley DB | [4.8.30](https://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html) | 4.8.x | No |  |  |
 | Boost | [1.71.0](https://www.boost.org/users/download/) | [1.58.0](https://github.com/bitcoin/bitcoin/pull/19667) | No |  |  |
-| Clang |  | [5.0+](https://releases.llvm.org/download.html) (C++17 support) |  |  |  |
+| Clang |  | [7.0+](https://releases.llvm.org/download.html) (C++17 & std::filesystem support) |  |  |  |
```
Comment (ryanofsky) [inline doc/dependencies.md:10]: In commit "build: remove boost::filesystem" (9f37a39b11b240f75b97fb565e6d8cf44972ec49)

This change seems like it belongs in previous commit "refactor: replace boost::filesystem with std::filesystem" (7810d151f5219e634b431c5393771616c759aef7) instead of this one.

File: doc/dependencies.md [hunk 11]
```diff
@@ -7,11 +7,11 @@ These are the dependencies currently used by Bitcoin Core. You can find instruct
...
 | Expat | [2.2.7](https://libexpat.github.io/) |  | No | Yes |  |
 | fontconfig | [2.12.1](https://www.freedesktop.org/software/fontconfig/release/) |  | No | Yes |  |
 | FreeType | [2.7.1](https://download.savannah.gnu.org/releases/freetype) |  | No |  | [Yes](https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk) (Android only) |
-| GCC |  | [7+](https://gcc.gnu.org/) (C++17 support) |  |  |  |
+| GCC |  | [8.1+](https://gcc.gnu.org/) (C++17 & std::filesystem support) |  |  |  |
```
Comment (ryanofsky) [inline doc/dependencies.md:14]: In commit "build: remove boost::filesystem" (9f37a39b11b240f75b97fb565e6d8cf44972ec49)

This change seems like it belongs in previous commit "refactor: replace boost::filesystem with std::filesystem" (7810d151f5219e634b431c5393771616c759aef7) instead of this one.

File: configure.ac [hunk 12]
```diff
@@ -77,6 +77,9 @@ AX_CXX_COMPILE_STDCXX([17], [noext], [mandatory])
 dnl Check if -latomic is required for <std::atomic>
 CHECK_ATOMIC
 
+dnl check if -lstdc++fs is required for std::filesystem
+CHECK_FILESYSTEM
```
Comment (ryanofsky) [inline configure.ac:81]: In commit "refactor: replace boost::filesystem with std::filesystem" (7810d151f5219e634b431c5393771616c759aef7)

It would be nice to split this commit up into two commits to separate the build system changes from the c++ code changes. The build system changes can be a first commit and the c++ code changes can be a second commit.

File: depends/hosts/darwin.mk [hunk 13]
```diff
@@ -1,4 +1,4 @@
-OSX_MIN_VERSION=10.14
+OSX_MIN_VERSION=10.15
```
Comment (ryanofsky) [inline depends/hosts/darwin.mk:1]: In commit "build: set OSX_MIN_VERSION to 10.15" (db29710bc12f97d9de78fb177322a8ac41f7c87d)

Would be good to consolidate all the config, makefile, and documentation changes adding build support for std::filesystem into a single atomic commit. Right now they are scattered across three commits and everything seems very mixed up:

- [ ] 7810d151f5219e634b431c5393771616c759aef7 refactor: replace boost::filesystem with std::filesystem (2/5)
- [ ] 9f37a39b11b240f75b97fb565e6d8cf44972ec49 build: remove boost::filesystem (3/5)
- [ ] db29710bc12f97d9de78fb177322a8ac41f7c87d build: set OSX_MIN_VERSION to 10.15 (4/5)

Better organization would be:

1. Add std::filesystem build support updating build files & minimum required versions
2. Switch c++ code from boost::filesystem to std::filesystem
3. Remove boost::filesystem

**Review by ryanofsky — APPROVED** [review]
Code review ACK f0667f1d4289b65ac92c70db30e2123179f611e1. No major issues and nothing that couldn't be fixed later, but:

- It seems like there might be a macos `backupwallet` failure: https://cirrus-ci.com/task/5475027611025408?command=ci#L3029. It's unclear what would cause it, since I wouldn't expect there to be path handling differences between linux and macos.
- Windows character set conversion doesn't seem as robust as it could be (see review comments)
- Commit organization doesn't seem as clear as it could be (see review comments)

**Comment by ryanofsky** [comment]
Oh, it looks like kiminuo tracked down the wallet_hd backupwallet failure earlier (https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-765467226) to a problem with certain platforms throwing when calling fs::equivalent on non-existent paths. Simple fix might be to define a wrapper function for the affected platforms catching the specific exception or checking for existence before calling fs::equivalent

File: src/test/script_tests.cpp [hunk 14]
```diff
@@ -1727,7 +1727,7 @@ BOOST_AUTO_TEST_CASE(script_assets_test)
     bool exists = fs::exists(path);
     BOOST_WARN_MESSAGE(exists, "File $DIR_UNIT_TEST_DATA/script_assets_test.json not found, skipping script_assets_test");
     if (!exists) return;
-    fs::ifstream file(path);
+    std::ifstream file(path);
     BOOST_CHECK(file.is_open());
```
[the remark this answers is not in the document]
Comment (fanquake) [reply src/test/script_tests.cpp:1731]: Reverted to `fsbridge::ifstream`.

File: ci/test/00_setup_env_win64.sh (hunk 2 above)
Comment (fanquake) [reply ci/test/00_setup_env_win64.sh]: Gitian has now been bumped.

File: ci/test/00_setup_env_native_nowallet.sh (hunk 1 above)
Comment (MarcoFalke) [reply ci/test/00_setup_env_native_nowallet.sh:10]: Still not addressed?

Comment (fanquake) [reply ci/test/00_setup_env_native_nowallet.sh:10]: That's why it hasn't been marked as resolved.

**Comment by fanquake** [comment]
@ryanofsky thanks for the comments. I've reordered and split the commits up more cleanly now. I've marked some comments as  resolved,  however some  are still outstanding, and I'm planning on addressing shortly. I'll also be going back over the discussion in #19245, as i think that contains answers to some queries.

File: src/test/util_tests.cpp (hunk 3 above)
Comment (fanquake) [reply src/test/util_tests.cpp:53]: > Why this change? Does it break with + "/"?

Yes, at ef8c98b1a54280f279f5319f386c44026893bf1f this currently fails with the trailing slash:
```bash
error: in "util_tests/util_datadir": check dd_norm == GetDataDir() has failed ["/var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_common_Bitcoin Core/873b1e644e770a9d5cdfc8f89323a344256001e7cedc14e18f2ae7c4a8ea8f94" != "/var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/test_common_Bitcoin Core/873b1e644e770a9d5cdfc8f89323a344256001e7cedc14e18f2ae7c4a8ea8f94/"]
```

File: ci/test/00_setup_env_native_nowallet.sh (hunk 1 above)
Comment (fanquake) [reply ci/test/00_setup_env_native_nowallet.sh]: This has now been dropped.

File: src/wallet/load.cpp (hunk 5 above)
Comment (fanquake) [reply src/wallet/load.cpp]: This has been rebased post #20932, so marking this as resolved.

**Review by ryanofsky — COMMENTED** [review]
Thanks for updates, commits are simpler now! It looks what's left to be done are debugging test failures and fixing windows encoding:

* 32-bit test failure "Value too large for defined data type" from https://cirrus-ci.com/task/4942042640941056 is mysterious, as it seems like it should only happen with really large files https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Value-too-large-for-defined-data-type which we shouldn't be creating. Problem happens in many tests, so at least it's not test-specific.

* Windows failure "C:/projects/bitcoin/src/test/dbwrapper_tests.cpp(412): error: in "dbwrapper_tests/unicodepath": check fs::exists(lockPath) has failed" from https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/37725701#L335 looks like a unicode error caused by dropping `imbue` (see below).

* Windows walletinit_verify_walletdir_no_trailing2 failure in https://cirrus-ci.com/task/5243515519107072?command=ci#L5082 looks like a broken test that was never testing what the author intended to test. I think the test and "trailing2" map entry could be deleted entirely, ideally in an preceding commit or PR. Also the test setup uses an awkward `m_walletdir_path_cases` map that seems like it is pointless and just obfuscates test behavior. Maybe that could be removed too.

* Right now this PR is dropping path `imbue`, and trying to use ad-hoc `u8path` calls as a workaround. Earlier comments: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571104004, https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571114426. Manual `u8path` calls are error-prone and we don't actually want them on POSIX. (POSIX path strings should be passed straight through to the fs::path constructor without assuming a particular encoding). On windows, we do want `u8path` calls whenever converting any string to a path. Unlike POSIX, windows natively uses wide strings for arguments, environment variables and paths, so to work correctly on windows we either need to use wide strings internally, or do wide <-> narrow conversions at the borders of windows API interactions. We've chosen the latter approach, and can stick with it here by overriding the path(std::string) constructor as described https://stackoverflow.com/questions/42765168/change-narrow-string-encoding-or-missing-stdfilesystempathimbue

File: src/test/util_tests.cpp (hunk 3 above)
Comment (fanquake) [reply src/test/util_tests.cpp:54]: I've added to the commit message, so will mark this as resolved.

**Comment by kiminuo** [comment]
I attempted to debug the failing ARM test. My debugging efforts led me to this line: https://github.com/fanquake/bitcoin/blob/1bdd927b20fab4aeb5e7119cc298b2a09bf1bc52/src/test/util/setup_common.cpp#L124 which fails with `what():  filesystem error: cannot remove all: Value too large for defined data type [...]`

Interestingly, the command `fs::remove_all` fails even if the folder is empty (I modified it just for fun). It happens always.

**Comment by kiminuo** [comment]
> Does it help if the folder name only contains 128 bit of randomness (as opposed to the 512 bits)?

The error is the same even for `/tmp/test_common_Bitcoin_Core/35c` where: 
* `test_common_Bitcoin Core` -> `test_common_Bitcoin_Core` and 
* `35c` is a very short folder name. 
* It does not matter whether I try to `remove_all` on `/tmp/test_common_Bitcoin_Core/35c` path or `/tmp/test_common_Bitcoin_Core/35c/` path (see the trailing slash).

So this does not seem to be the issue. 

I have also tried to copy `/tmp/test_common_Bitcoin_Core/35c` to `/home/user/bitcoin/bitcoin/ci/scratch/out/arm-linux-gnueabihf` and delete that folder and it does not work too so it's not about `/tmp`.

At this point, it *looks* like it does not work at all for directories (full or empty). However, deleting `/home/user/bitcoin/bitcoin/ci/scratch/out/arm-linux-gnueabihf/35c/test.txt` (i.e. a file) finished without an error when deleted with `fs::remove_all(path)`.

(btw: Is this https://github.com/gcc-mirror/gcc/commits/releases/gcc-8/libstdc%2B%2B-v3/src/filesystem/ops.cc useful? `arm-linux-gnueabihf-g++ --version` reports `arm-linux-gnueabihf-g++ (Debian 8.3.0-2) 8.3.0`)

**Comment by ryanofsky** [comment]
The "cannot remove all: Value too large for defined data type" bug mentioned

* https://github.com/bitcoin/bitcoin/pull/20744#pullrequestreview-589081075
* https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-810279549

seems to be reported externally https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93201. Probably easiest workaround is just to avoid remove_all and write a simple recursive remove function.

The remaining errors seem unicode related and probably fixed by implementing the suggested imbue workaround.

**Comment by kiminuo** [comment]
@ryanofsky I have narrowed the failing ARM issue down to:

```c++
auto iterator = fs::directory_iterator(m_path_root); // where m_path_root = /tmp/test_common_Bitcoin Core/29248e247aad6a68595f5e097d311e923c00300291f160ee2254ed8b5b4668c4
```

which throws:

```
/tmp/test_common_Bitcoin Core/29248e247aad6a68595f5e097d311e923c00300291f160ee2254ed8b5b4668c4
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: Value too large for defined data type [/tmp/test_common_Bitcoin Core/29248e247aad6a68595f5e097d311e923c00300291f160ee2254ed8b5b4668c4]
```

Interestingly 

```c++
auto status = fs::status(m_path_root);
```

does not throw.

**Comment by MarcoFalke** [comment]
The gcc bug is fixed on all branches, but is seems that gcc for arm on debian buster didn't receive the patch? This should be a relative edge-case platform and I think we can just bump the ci config from buster to bullseye to fix the problem. (It does fix it for me locally).

**Comment by kiminuo** [comment]
> The gcc bug is fixed on all branches, but is seems that gcc for arm on debian buster didn't receive the patch? 

Might be so.

> This should be a relative edge-case platform and I think we can just bump the ci config from buster to bullseye to fix the problem. (It does fix it for me locally).

Bullseye is not [stable](https://www.debian.org/releases/bullseye/) yet. Maybe gcc-9 instead of gcc-8 on buster would suffice here to be less aggressive in version bumps? Anyway, I'm kind of worried that this would mean to delay this PR by a Bitcoin Core version or two.

**Comment by MarcoFalke** [comment]
Assigned the 23.0 milestone, because rushing this into 0.22 might be too aggressive. See also https://github.com/bitcoin/bitcoin/issues/20460#issuecomment-789502720

In a year from now (when this is going to be releases), debian:buster may have bumped the gcc-8 to include the fix, or bullseye may have been released as stable. So I think re-implementing std::fs features in our code base is not needed.

**Comment by laanwj** [comment]
> So I think re-implementing std::fs features in our code base is not needed.

Agree on the general idea. It is slightly disappointing but there is no rush. If time will solve the issues automatically there is no need to spend work and reviewer time on doing some in-between thing.

**Comment by MarcoFalke** [comment]
Branch-off is in only 3 months, so I think it is fine to drink some tea in the meantime and wait a bit

**Comment by kiminuo** [comment]
This is probably useful for the Win64 test failure:

```cpp
// Run with: x86_64-w64-mingw32-g++ --std=c++17 --static paths.cpp17.cpp && wine ./a.exe
// For comparison: g++ --std=c++17 --static paths.cpp17.cpp && ./a.out

#include <string>
#include <iostream>
#include <filesystem>
namespace fs = std::filesystem;

int main()
{
    // Basically copied from init_test_fixture.cpp:
    fs::path m_cwd = fs::current_path();

    std::string sep;
    sep += fs::path::preferred_separator;

    fs::path m_datadir = fs::current_path();

    fs::path default_path = m_cwd / "wallets";
    fs::path custom = m_datadir / "my_wallets";
    fs::path nonexistent = m_datadir / "path_does_not_exist";
    fs::path file = m_datadir / "not_a_directory.dat";
    fs::path trailing = m_datadir / "wallets" / sep;

    // *sep* is "appended" and not "concatenated".
    // https://en.cppreference.com/w/cpp/filesystem/path/append
    // https://en.cppreference.com/w/cpp/filesystem/path/concat
    fs::path trailing2 = m_datadir / "wallets" / sep / sep;

    std::cout << "default path: " << default_path << "\n";
    std::cout << "custom: " << custom << "\n";
    std::cout << "nonexistent: " << nonexistent << "\n";
    std::cout << "file: " << file << "\n";
    std::cout << "trailing: " << trailing << "\n";
    std::cout << "trailing2: " << trailing2 << "\n";

    // Demonstrates "+=" behavior
    fs::path trailing_plus = m_datadir / "wallets";
    trailing_plus += sep;

    std::cout << "trailing_plus: " << trailing_plus << "\n";
    std::cout << "absolute(trailing_plus): " << fs::absolute(trailing_plus) << "\n";
    std::cout << "canonical(trailing_plus): " << fs::canonical(trailing_plus) << "\n"; // Directory must exist! Otherwise an exception is thrown.

    // See "normalize algorithm" here: https://en.cppreference.com/w/cpp/filesystem/path 
    std::cout << "trailing_plus.lexically_normal(): " << trailing_plus.lexically_normal() << "\n";

    std::cout << "end\n"; // breakpoint line :)
}
```

<details>
  <summary>`x86_64-w64-mingw32-g++ --std=c++17 --static paths.cpp17.cpp && wine ./a.exe` output</summary>

  ```
default path: "Z:\\home\\user\\bitcoin\\wallets"
custom: "Z:\\home\\user\\bitcoin\\my_wallets"
nonexistent: "Z:\\home\\user\\bitcoin\\path_does_not_exist"
file: "Z:\\home\\user\\bitcoin\\not_a_directory.dat"
trailing: "Z:\\"
trailing2: "Z:\\"
trailing_plus: "Z:\\home\\user\\bitcoin\\wallets\\"
absolute(trailing_plus): "Z:\\home\\user\\bitcoin\\wallets\\"
canonical(trailing_plus): "Z:\\home\\user\\bitcoin\\wallets"
trailing_plus.lexically_normal(): "Z:\\home\\user\\bitcoin\\wallets\\"
end
  ```
</details>

<details>
  <summary>`g++ --std=c++17 --static paths.cpp17.cpp && ./a.out` output</summary>

  ```
default path: "/home/bitcoin/wallets"
custom: "/home/bitcoin/my_wallets"
nonexistent: "/home/bitcoin/path_does_not_exist"
file: "/home/bitcoin/not_a_directory.dat"
trailing: "/"
trailing2: "/"
trailing_plus: "/home/bitcoin/wallets/"
absolute(trailing_plus): "/home/bitcoin/wallets/"
canonical(trailing_plus): "/home/bitcoin/wallets"
trailing_plus.lexically_normal(): "/home/bitcoin/wallets/"
end
  ```
</details>

**Comment by theStack** [comment]
Concept ACK
Will test on Linux and also OpenBSD soon (let's see if there are any issues on FFS2).

**Comment by promag** [comment]
Concept ACK.

**Comment by hebasto** [comment]
Concept ACK.

**Comment by MarcoFalke** [comment]
unrelated ci error:

```
In file included from node/blockstorage.cpp:5:
./node/blockstorage.h:37:13: error: ‘atomic_bool’ in namespace ‘std’ does not name a type
 extern std::atomic_bool fImporting;
             ^~~~~~~~~~~
```

Fixed in commit facf8b0adb41fad6a93b9a041d4ce135eaeff5be of #22242

**Comment by MarcoFalke** [comment]
Rebase to fix the ci issue?

**Comment by kiminuo** [comment]
Would https://github.com/bitcoin/bitcoin/pull/22336/commits/17eff90922f005e88cba33fba1d14225e0474f93 from #22336 help?

**Comment by kiminuo** [comment]
Regarding Android CI error: Currently, Android NDK 21 is used in the master branch, but Android NDK 22 is [necessary](https://github.com/android/ndk/wiki/Changelog-r22#changes) for std::filesystem support. 

Qt [works with Android NDK 21](https://doc.qt.io/qt-5/android-getting-started.html#installing-the-prerequisites) but not with NDK 22 out of the box - it did not work for me and I'm not sure how to fix it, build gurus here will understand it much better.

**Comment by hebasto** [comment]
> Qt [works with Android NDK 21](https://doc.qt.io/qt-5/android-getting-started.html#installing-the-prerequisites) but not with NDK 22 out of the box - it did not work for me and I'm not sure how to fix it, build gurus here will understand it much better.

See #22074.

**Comment by kiminuo** [comment]
> > Qt [works with Android NDK 21](https://doc.qt.io/qt-5/android-getting-started.html#installing-the-prerequisites) but not with NDK 22 out of the box - it did not work for me and I'm not sure how to fix it, build gurus here will understand it much better.
> 
> See #22074.

Thank you. That's the error I can see.

**Comment by fanquake** [comment]
Now that we've branch of for 22.x, we can actually think about merging this. I've rebased on master (which should fix the Android build issues) and included some more changes from @kiminuo. That should mean that what's left to finish up here is the Windows changes, which I'd like to get to shortly.

**Comment by hebasto** [comment]
> That should mean that what's left to finish up here is the Windows changes, which I'd like to get to shortly.

As this pr discussion is pretty long, here are Windows related comments in one place:
- https://github.com/bitcoin/bitcoin/pull/20744#pullrequestreview-584505139
- https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571099540
- https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571104004
- https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571114426
- https://github.com/bitcoin/bitcoin/pull/20744#pullrequestreview-589081075

**Comment by hebasto** [comment]
748a989fffa2f86876c366f6c3a58637e8588be8 "build: set OSX_MIN_VERSION to 10.15"

> This is required to use std::filesystem on macOS.

Documented in [Xcode 11 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-11-release-notes).

**Comment by hebasto** [comment]
748a989fffa2f86876c366f6c3a58637e8588be8 "build: set OSX_MIN_VERSION to 10.15"

Here're other places where the version 10.14 should be updated/dropped:
```
$ git grep -n -e '10\.14' -- ':(exclude)doc/release-notes/*'
contrib/devtools/test-symbol-check.py:139:        self.assertEqual(call_symbol_check(cc, source, executable, ['-Wl,-platform_version','-Wl,macos', '-Wl,10.14', '-Wl,11.4']),
doc/build-osx.md:118:Note: Apple has included a useable `sqlite` package since macOS 10.14.
doc/release-notes.md:51:using the Linux kernel, macOS 10.14+, and Windows 7 and newer.  Bitcoin
doc/release-notes.md:56:From Bitcoin Core 22.0 onwards, macOS versions earlier than 10.14 are no longer supported.
share/qt/Info.plist.in:6:  <string>10.14.0</string>
```

File: ci/test/00_setup_env_native_nowallet.sh [hunk 15]
```diff
@@ -8,7 +8,7 @@ export LC_ALL=C.UTF-8
 
 export CONTAINER_NAME=ci_native_nowallet
 export DOCKER_NAME_TAG=ubuntu:18.04  # Use bionic to have one config run the tests in python3.6, see doc/dependencies.md
-export PACKAGES="python3-zmq clang-5.0 llvm-5.0"  # Use clang-5 to test C++17 compatibility, see doc/dependencies.md
+export PACKAGES="python3-zmq clang-7 llvm-7 libstdc++-8-dev"  # Use clang-7 to test C++17 compatibility, see doc/dependencies.md
```
Comment (hebasto) [inline ci/test/00_setup_env_native_nowallet.sh:11]: Update `doc/dependencies.md` as well?

**Comment by hebasto** [comment]
Approach ACK c5c3d5de39ee80aad8fa0c7700d42a872c11c225.

**Comment by MarcoFalke** [comment]
```
+ env CONFIG_SITE=/bitcoin/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --enable-reduce-exports --disable-bench --disable-gui-tests --disable-fuzz-binary 'CFLAGS=-O2 -g -fno-ident' 'CXXFLAGS=-O2 -g -fno-ident' LDFLAGS=-Wl,--no-insert-timestamp
configure: loading site script /bitcoin/depends/x86_64-w64-mingw32/share/config.site
checking for x86_64-w64-mingw32-pkg-config... /root/.guix-profile/bin/pkg-config --static
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-w64-mingw32
checking for a BSD-compatible install... /root/.guix-profile/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32-strip... x86_64-w64-mingw32-strip
checking for a thread-safe mkdir -p... /root/.guix-profile/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-w64-mingw32-g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of x86_64-w64-mingw32-g++... none
checking whether x86_64-w64-mingw32-g++ supports C++17 features with -std=c++17... yes
checking whether std::atomic can be used without link library... yes
checking whether std::filesystem can be used without link library... no
checking whether std::filesystem needs -lstdc++fs... no
configure: error: in `/distsrc-base/distsrc-4bd690d8c420-x86_64-w64-mingw32':
configure: error: cannot figure out how to use std::filesystem
See `config.log' for more details

**Comment by fanquake** [comment]
Rebased.

>  Here're other places where the version 10.14 should be updated/dropped:

Updated those that were relevant.

> Can remove this: https://github.com/bitcoin/bitcoin/pull/20586/files#r656885645

Included.

Note that progress is still being made here. Someone else is currently looking at the Windows portion of the changes.

**Comment by dongcarl** [comment]
Concept ACK

**Review by hebasto — COMMENTED** [review]
In the commit _"build: set OSX_MIN_VERSION to 10.15"_ (edeed577501693e0b8e8f0c8c5d1ccdc47587557) the following change is also required:
```diff
--- a/contrib/devtools/symbol-check.py
+++ b/contrib/devtools/symbol-check.py
@@ -217,7 +217,7 @@ def check_MACHO_libraries(filename) -> bool:
 
 def check_MACHO_min_os(filename) -> bool:
     binary = lief.parse(filename)
-    if binary.build_version.minos == [10,14,0]:
+    if binary.build_version.minos == [10,15,0]:
         return True
     return False
 
```

**Comment by hebasto** [comment]
On Windows the only test fails: https://github.com/bitcoin/bitcoin/blob/5e3380b9f59481fc18e05b9d651c3c733abe4053/src/test/dbwrapper_tests.cpp#L401-L412

Could be related to #17641, https://github.com/google/leveldb/issues/755, https://github.com/google/leveldb/pull/760

cc @sipsorcery @laanwj

**Comment by kiminuo** [comment]
> 
> 
> On native Win64 the only test fails:
> 
> https://github.com/bitcoin/bitcoin/blob/5e3380b9f59481fc18e05b9d651c3c733abe4053/src/test/dbwrapper_tests.cpp#L401-L412
> 
> Could be related to #17641, [google/leveldb#755](https://github.com/google/leveldb/issues/755), [google/leveldb#760](https://github.com/google/leveldb/pull/760)

Some observations, maybe it helps somebody to fix the issue:

### Setting locale

[Adding](https://github.com/bitcoin/bitcoin/pull/19245/files#diff-00b29588edfbcf3aeb68a4bcdc4278543f755fa428ae8194a280436386f8654fR439) `std::setlocale(LC_ALL, "en_US.UTF-8");` makes the test pass.

### Original test

```cpp
BOOST_AUTO_TEST_CASE(unicodepath)
{
    // Attempt to create a database with a UTF8 character in the path.
    // On Windows this test will fail if the directory is created using
    // the ANSI CreateDirectoryA call and the code page isn't UTF8.
    // It will succeed if created with CreateDirectoryW.
    fs::path ph = m_args.GetDataDirBase() / "test_runner_₿_🏃_20191128_104644";
    CDBWrapper dbw(ph, (1 << 20));

    fs::path lockPath = ph / "LOCK";
    BOOST_CHECK(fs::exists(lockPath));
}
```

My Visual Studio debugger shows that path `fs::path ph = m_args.GetDataDirBase() / "test_runner_₿_🏃_20191128_104644";` is garbled once created. Likely `"test_runner_₿_🏃_20191128_104644"` is intepreted using some some local codepage.

### Modified test with euro sign

(No pun intended :))

```cpp
BOOST_AUTO_TEST_CASE(unicodepath)
{
    // Attempt to create a database with a UTF8 character in the path.
    // On Windows this test will fail if the directory is created using
    // the ANSI CreateDirectoryA call and the code page isn't UTF8.
    // It will succeed if created with CreateDirectoryW.
    // fs::path ph = m_args.GetDataDirBase() / "test_runner_₿_🏃_20191128_104644"; // REMOVED
    fs::path ph = m_args.GetDataDirBase() / L"test_runner_€_20191128_104644"; // ADDED
    CDBWrapper dbw(ph, (1 << 20));

    fs::path lockPath = ph / "LOCK";
    BOOST_CHECK(fs::exists(lockPath));
}
```

This test leads on my computer to creating of two folders in `C:\Users\kimi\AppData\Local\Temp\test_common_Bitcoin Core\efd602083fe69783d5e6eff1220a12770bd2168d338ae233e260bae6a10c6068`:

* `test_runner_�_20191128_104644`
* `test_runner_€_20191128_104644`

`€` was used because it can be represented by two bytes.

Note that using `L"test_runner_₿_🏃_20191128_104644"` leads to `class std::system_error: No mapping for the Unicode character exists in the target multi-byte code page.` error which seems to make sense to me.

### `std::filesystem::u8path`

I had no success with this method really.

(https://stackoverflow.com/questions/30829364/open-utf8-encoded-filename-in-c-windows/69037041#69037041)

**Comment by hebasto** [comment]
My own research confirms @kiminuo's one.

**Comment by hebasto** [comment]
> [Adding](https://github.com/bitcoin/bitcoin/pull/19245/files#diff-00b29588edfbcf3aeb68a4bcdc4278543f755fa428ae8194a280436386f8654fR439) `std::setlocale(LC_ALL, "en_US.UTF-8");` makes the test pass.

From MS [docs](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem?view=msvc-160):
> Interconversions between these [pathname] representations are mediated, as needed, by the use of one or more `codecvt` facets. If no specific locale object is specified, these facets are obtained from the global locale.

**Comment by hebasto** [comment]
Recently [added](https://github.com/bitcoin/bitcoin/pull/22922) to Windows CI task functional tests are broken with  this branch.

**Comment by hebasto** [comment]
Win64 CI task failed due to an unrelated issue:
```
https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip: WinHttpReceiveResponse() failed: 12030
```

so going to re-run it.

File: src/test/dbwrapper_tests.cpp [hunk 16]
```diff
@@ -404,6 +404,7 @@ BOOST_AUTO_TEST_CASE(unicodepath)
     // On Windows this test will fail if the directory is created using
     // the ANSI CreateDirectoryA call and the code page isn't UTF8.
     // It will succeed if created with CreateDirectoryW.
+    std::setlocale(LC_ALL, "en_US.UTF-8");
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/test/dbwrapper_tests.cpp:407]: and

```diff
--- a/test/lint/lint-locale-dependence.sh
+++ b/test/lint/lint-locale-dependence.sh
@@ -44,6 +44,7 @@ KNOWN_VIOLATIONS=(
     "src/node/blockstorage.cpp:.*atoi"
     "src/qt/rpcconsole.cpp:.*atoi"
     "src/rest.cpp:.*strtol"
+    "src/test/dbwrapper_tests.cpp:.*setlocale"
     "src/test/dbwrapper_tests.cpp:.*snprintf"
     "src/test/fuzz/locale.cpp"
     "src/test/fuzz/parse_numbers.cpp:.*atoi"
```

**Comment by ryanofsky** [comment]
I didn't really get an chance to test and finish test this yet, but here is my attempt at improving the encoding situation on windows using the path(std::string) constructor override I mentioned earlier: 099e0207808687e3af2148e7c31353677b866d72 ([branch](https://github.com/ryanofsky/bitcoin/commits/review.20744.7-edit))

References:

- https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571104004
- https://github.com/bitcoin/bitcoin/pull/20744#discussion_r571114426
- https://github.com/bitcoin/bitcoin/pull/20744#pullrequestreview-589081075

I also see there are a lot of path::string() calls that should probably be replaced by path::u8string() calls for logging / rpc / display purposes, but this would be another followup

File: src/test/dbwrapper_tests.cpp (hunk 16 above)
[the remark this answers is not in the document]
Comment (fanquake) [reply src/test/dbwrapper_tests.cpp:408]: added & added

**Comment by fanquake** [comment]
I'm seeing functional test failures on macOS again due to differences in paths `/var/` vs `/private/var`, where the former is a symlink to the later. I have a recollection of seeing this previously, and thought we'd fixed/worked around it.

> I didn't really get an chance to test and finish test this yet, but here is my attempt at improving the encoding situation on windows using the path(std::string) constructor override I mentioned earlier: 099e020 (branch)

Thanks. I'll take a look at testing / including this shortly.

One other thing we'll likely need to do here is move Guix to using a newer version of mingw-w64. iirc we're currently using 7, but I'm pretty sure we'll required 8, which is available in Guix. cc @dongcarl.

**Comment by ryanofsky** [comment]
I had second thoughts about the path(std::string) constructor approach I was trying above. I think it adds to much magic. Better not to make a custom path class that differs subtly from the standard path class on windows, just to be able to do magic implicit conversions, when explicit conversions would be clearer anyway. So starting over.

---

### Windows encoding bugfix, attempt 2

#### Summary

The implicit `path <=> std::string` conversions done by the [`std::filesystem::path(std::string)` constructor](https://en.cppreference.com/w/cpp/filesystem/path/path) and [`std::filesystem::path::string()` method](https://en.cppreference.com/w/cpp/filesystem/path/string) generally work well on linux, but are unsafe and broken for our purposes on Windows. Solution is to disable these methods and start using safer, more explicit `path <=> std::string` conversion functions instead.

#### Details

On POSIX, paths natively are 8-bit strings that do not specify any particular encoding, so they can be straightforwardly converted to and from `std::string` objects with no transformations. On Windows, paths natively are unicode strings that have to be encoded or decoded in some way to be represented in `std::string` objects. Ideally, the way we would convert paths to `std::string` is by encoding them as UTF-8 (technically a ["wobbly"](https://github.com/rust-lang/rust/issues/12056) variation of UTF-8 to handle some edge cases). This is what the previous boost path class did after imbueing it with a locale. But with the new `std::filesystem::path` class, imbueing a locale is not possible. So the standard `path(std::string)` constructor and `path::string()` methods will no longer use UTF-8. Instead they will use different encodings depending on the local system's current [code page](https://docs.microsoft.com/en-us/windows/win32/intl/code-pages) which makes these functions unsafe and useless for our purposes. In Windows versions since May 2019 it is possible to change the build in a way that would make these functions always use UTF-8. But if we want to keep providing the same behavior and level of compatibility that we had with boost we need to  stop using calling these functions and start doing explicit conversions. So I think the simplest and best way forward is just to prevent the bad string functions from being called, and to update the calling code to use explicit conversions. I implemented this here: 3e88c9f6b4e84ab5da78f4862266b5ff13bb8fc0 ([tag](https://github.com/ryanofsky/bitcoin/commits/review.20744.8-edit.1))

It's kind of a big commit, but the majority of it is just introducing and calling new `PathToString` and `PathFromString` functions and I can easily split it out into a standalone PR that does not depend on anything else here.

**Comment by kiminuo** [comment]
@ryanofsky The `unicodepath` test passes for me on Windows 10 with your patch ([3e88c9f](https://github.com/bitcoin/bitcoin/commit/3e88c9f6b4e84ab5da78f4862266b5ff13bb8fc0) ([tag](https://github.com/ryanofsky/bitcoin/commits/review.20744.8-edit.1)). Nice work.

**Comment by ryanofsky** [comment]
I posted a version of this PR rebased on top of #22937 here: e03ede894b86c793a33e84eade230c35d35457df,  ([tag](https://github.com/ryanofsky/bitcoin/commits/pr/stdfs.4))

**Comment by hebasto** [comment]
> I posted a version of this PR rebased on top of #22937 here: [e03ede8](https://github.com/bitcoin/bitcoin/commit/e03ede894b86c793a33e84eade230c35d35457df), ([tag](https://github.com/ryanofsky/bitcoin/commits/pr/stdfs.4))

Testing...

**Comment by hebasto** [comment]
> I posted a version of this PR rebased on top of #22937 here: [e03ede8](https://github.com/bitcoin/bitcoin/commit/e03ede894b86c793a33e84eade230c35d35457df), ([tag](https://github.com/ryanofsky/bitcoin/commits/pr/stdfs.4))

The version with green CI for the Windows MSVC build is here:
- [branch](https://github.com/hebasto/bitcoin/commits/pr22937-0914-COMBINED)
- [CI tests](https://cirrus-ci.com/build/5991788159696896)

**Comment by ryanofsky** [comment]
#22937 was updated with fixes above. Rebased version of this PR after that one is: aeabf62ae14a0a281ffc865bfd4975ba65be9419, ([tag](https://github.com/ryanofsky/bitcoin/commits/pr/stdfs.5))

File: doc/dependencies.md [hunk 17]
```diff
@@ -7,11 +7,11 @@ These are the dependencies currently used by Bitcoin Core. You can find instruct
 | --- | --- | --- | --- | --- | --- |
 | Berkeley DB | [4.8.30](https://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index.html) | 4.8.x | No |  |  |
 | Boost | [1.71.0](https://www.boost.org/users/download/) | [1.64.0](https://github.com/bitcoin/bitcoin/pull/22320) | No |  |  |
-| Clang<sup>[ \* ](#note1)</sup> |  | [5.0+](https://releases.llvm.org/download.html) (C++17 support) |  |  |  |
+| Clang<sup>[ \* ](#note1)</sup> |  | [7.0+](https://releases.llvm.org/download.html) (C++17 & std::filesystem support) |  |  |  |
```
Comment (MarcoFalke) [inline doc/dependencies.md:10]: in the doc commit: Does #22339 also need to be updated?

Comment (fanquake) [reply doc/dependencies.md:10]: Gunna split more of this out. Will address.

**Comment by fanquake** [comment]
Rebased this after #22994 & #22993. Going to split out a couple more of the commits here shortly.

File: test/functional/wallet_multiwallet.py [hunk 18]
```diff
@@ -141,7 +141,7 @@ def wallet_file(name):
 
         # should raise rpc error if wallet path can't be created
         err_code = -4 if self.options.descriptors else -1
-        assert_raises_rpc_error(err_code, "boost::filesystem::create_directory:", self.nodes[0].createwallet, "w8/bad")
+        assert_raises_rpc_error(err_code, "filesystem error:", self.nodes[0].createwallet, "w8/bad")
```
Comment (hebasto) [inline test/functional/wallet_multiwallet.py:144]: 1c655826850235fbf13dc90daf66e2b3facdc9ba

MSVC implementation of `std::filesystem` has different error messages:

```suggestion
        assert_raises_rpc_error(err_code, "filesystem error:" if sys.platform != 'win32' else "create_directories:", self.nodes[0].createwallet, "w8/bad")
```

(and `import sys`, of course).

Comment (MarcoFalke) [reply test/functional/wallet_multiwallet.py:144]: Wouldn't it make more sense to use EXEEXT to avoid issues when the tests are run in wine or so?

**Comment by fanquake** [comment]
Rebased after the merge of #23060. All prerequisites that were part of this PR have now been merged. The next step to moving to `std::filesystem` should be #22937.

File: test/lint/lint-includes.sh [hunk 19]
```diff
@@ -54,8 +54,6 @@ EXPECTED_BOOST_INCLUDES=(
     boost/algorithm/string/replace.hpp
     boost/algorithm/string/split.hpp
     boost/date_time/posix_time/posix_time.hpp
-    boost/filesystem.hpp
-    boost/filesystem/fstream.hpp
```
Comment (hebasto) [inline test/lint/lint-includes.sh:58]: Removing of `boost/filesystem/fstream.hpp` should be done in the _"refactor: replace boost::filesystem with std::filesystem"_ commit (5fb92bab5f8c6c07bb668d7a7f2203f389a4956d) to let it pass `test/lint/lint-includes.sh`.

**Comment by fanquake** [comment]
I've modified the `std::filesystem` macro to try using `-lc++fs` if `-lstdc++fs` doesn't work. Should fix the issues in the nowallet CI, which uses Clang 7 and libc++.

> Removing of boost/filesystem/fstream.hpp should be done in the 

Done.

**Comment by hebasto** [comment]
> That should mean that what's left to finish up here is the Windows changes, which I'd like to get to shortly.

Any update about cross-compiling for Windows?

**Comment by dongcarl** [comment]
> One other thing we'll likely need to do here is move Guix to using a newer version of mingw-w64. iirc we're currently using 7, but I'm pretty sure we'll required 8, which is available in Guix. cc @dongcarl.

I'm not sure upgrading to mingw-w64 v8 will affect anything, could you link me to the specific failure that makes you think this is required?

**Comment by fanquake** [comment]
I've rebased to account for #22937 added a commit for Guix to pass `--enable-libstdcxx-filesystem-ts=yes` to our mingw GCC build. However libstdc++ is failing to build it's filesystem component. @dongcarl could you take a look? The full GCC build output is here: https://gist.github.com/fanquake/c040358952075b054cda7786e3e98563.

**Review by ryanofsky — COMMENTED** [review]
Suggested some simplifications below. (These were previously part of the branch I posted earlier https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-921033707)

**Review by ryanofsky — COMMENTED** [review]
Finally finished going through commit 6316193878d66bb35dbf96f8ec2047591e3bdb46 (in branch e4d50b8f0367e9ac3bb6189c9299cdda9c9d7c7e) and I think it will look good with all the suggested changes. After these changes, I'm still not sure if would be 100% refactoring because of possible `system_complete` and `absolute` differences mentioned in the commit description about extra slashes, but the the only place these could possibly be show up is in the middle regtest/testnet GetDataDir paths, so they would be harmless and the commit message already mentions this. And aside from that there are no other places I would see behavior changing at all.

**Review by ryanofsky — COMMENTED** [review]
Reviewing b70c84348ac7a8e427a1183f894c73e52c734529 (in branch f53be20eade794e55470473f03a8d05d57691c87)

---

re: https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-948476630

> > Any idea why the windows unit test failed?
> 
> ```shell
> test/util_tests.cpp(72): error: in "util_tests/util_datadir": check dd_norm == args.GetDataDirBase() has failed ["C:\\users\\root\\Temp\\test_common_Bitcoin Core\\04ef3851bd5ebef826abb443ef652d2eee95c19cbcefc481267df04b8f0df460" != ""]
> ```

The  test that's failing is:

```c++
    args.ForceSetArg("-datadir", fs::PathToString(dd_norm) + "/.//");
    args.ClearPathCache();
    BOOST_CHECK_EQUAL(dd_norm, args.GetDataDirBase());
```

because args.GetDataDirBase() is returning `""`, because windows does not consider `"dir/.//"` to be a valid directory, so `path = ""` in `GetDataDir` is hit:

```c++
    std::string datadir = GetArg("-datadir", "");
    if (!datadir.empty()) {
        path = fs::absolute(fs::PathFromString(datadir));
        if (!fs::is_directory(path)) {
            path = "";
            return path;
        }
```

Possible fix 1:

```diff
diff --git a/src/util/system.cpp b/src/util/system.cpp
index 03af96dc3cf..0e026a35347 100644
--- a/src/util/system.cpp
+++ b/src/util/system.cpp
@@ -429,7 +429,7 @@ const fs::path& ArgsManager::GetDataDir(bool net_specific) const
 
     std::string datadir = GetArg("-datadir", "");
     if (!datadir.empty()) {
-        path = fs::absolute(fs::PathFromString(datadir));
+        path = fs::absolute(StripRedundantLastElementsOfPath(fs::PathFromString(datadir)));
         if (!fs::is_directory(path)) {
             path = "";
             return path;
```

Possible fix 2:

```diff
diff --git a/src/test/util_tests.cpp b/src/test/util_tests.cpp
index b1300d06ba6..f6e2e7907fb 100644
--- a/src/test/util_tests.cpp
+++ b/src/test/util_tests.cpp
@@ -69,7 +69,12 @@ BOOST_AUTO_TEST_CASE(util_datadir)
 
     args.ForceSetArg("-datadir", fs::PathToString(dd_norm) + "/.//");
     args.ClearPathCache();
+#ifndef WIN32
     BOOST_CHECK_EQUAL(dd_norm, args.GetDataDirBase());
+#else
+    // Windows does not consider "datadir/.//" to be a valid directory path.
+    BOOST_CHECK(args.GetDataDirBase().empty());
+#endif

---

```

re: https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-948482134

> Shouldn't we stick to the only namespace -- `fsbridge` or `std`?

I'd assume we should probably either use `fsbridge` in all application code, or else should drop it entirely.

File: src/init.cpp [hunk 20]
```diff
@@ -118,7 +118,7 @@ static fs::path GetPidFile(const ArgsManager& args)
 
 [[nodiscard]] static bool CreatePidFile(const ArgsManager& args)
 {
-    fsbridge::ofstream file{GetPidFile(args)};
+    fsbridge::ofstream file{static_cast<std::filesystem::path>(GetPidFile(args))};
```
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/init.cpp:121]: re: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r733637362

I was looking into this again, thinking passing `path.native()` might be a third alternative, but it doesn't work because there's no constructor https://en.cppreference.com/w/cpp/io/basic_ifstream/basic_ifstream that accepting the `wstring` on windows like the one accepting the wide character pointer returned by `path.c_str()`.

**Comment by fanquake** [comment]
> Does switching to GCC 9 in the Guix building system look more preferable?

I'd rather we switch to GCC 10. I'm currently upstreaming some changes, i.e https://lists.gnu.org/archive/html/guix-patches/2021-11/msg00346.html, to fixup the GCC 10 build in Guix, and will open a separate PR proposing that change.

File: build_msvc/vcpkg.json [hunk 21]
```diff
@@ -3,7 +3,6 @@
   "version-string": "1",
   "dependencies": [
     "berkeleydb",
-    "boost-filesystem",
```
[the remark this answers is not in the document]
Comment (fanquake) [reply build_msvc/vcpkg.json:6]: Going to resolve this as I don't think there's anything we can do here. Even if it is still being built, we aren't using it.

**Comment by fanquake** [comment]
I've rebased this on master and #23778 (dropping 9604eda1abe6ffc02c97e3434c3c2c4ce1250794 which was the "backport std::filesystem to GCC" commit). I've also addressed a number of the comments, including sticking to using `fsbridge` and removing the use of the `static_casts` in favour of passing `path.c_str()`, as well as included some suggestions to fix test failures. There are still a couple failures in the Windows unit tests that need to be addressed.

**Comment by fanquake** [comment]
Addressed:
> The syscall "sendfile" (syscall number 40) is not allowed by the syscall sandbox in thread "httpworker.0".

File: src/rpc/request.cpp [hunk 22]
```diff
@@ -85,7 +85,7 @@ bool GenerateAuthCookie(std::string *cookie_out)
      */
     fsbridge::ofstream file;
     fs::path filepath_tmp = GetAuthCookieFile(true);
-    file.open(filepath_tmp);
+    file.open(filepath_tmp.c_str());
```
Comment (martinus) [inline src/rpc/request.cpp:88]: Is the `c_str()` actually needed? On my system (g++ 11.1) this also compiles when I write `file.open(filepath_tmp);`. This calls `operator string_type() const { return _M_pathname; }` from `std::fileystem::path`.

Or maybe add `operator string_type() const = delete;` to explicitly delete that conversion in the path wrapper

**Review by martinus — APPROVED** [review]
tested ACK, fixes the boost 1.78 issue #23846 for me. All tests work for me, and bitcoind is syncing. Could only do light code review as I don't know too much about the details

File: src/rpc/request.cpp (hunk 22 above)
Comment (ryanofsky) [reply src/rpc/request.cpp:88]: c_str is needed on some platform (mingw, IIRC) because of an `_If_fs_path` requirement there which requires std::filesystem::path class argument or a string argument, and won't accept a std::filesystem::path subclass like fs::path (https://github.com/bitcoin/bitcoin/pull/20744#discussion_r733637362, https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-948358014)

Comment (martinus) [reply src/rpc/request.cpp:88]: Thanks!

**Comment by MarcoFalke** [comment]
```
 test  2022-01-10T08:47:25.172000Z TestFramework (INFO): Restoring wallets on node 3 using backup files 
 test  2022-01-10T08:47:25.172000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 133, in try_rpc
                                       fun(*args, **kwds)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\coverage.py", line 49, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 144, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: copy_file: The system cannot find the path specified.:
"C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220110_084607\wallet_backup_228\node0\invalid_wallet_file.bak",
"C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_?_??_20220110_084607\wallet_backup_228\node3\regtest\wallets\res0\wallet.dat" (-1)
                                   During handling of the above exception, another exception occurred:
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_backup.py", line 195, in run_test
                                       self.restore_invalid_wallet()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_backup.py", line 120, in restore_invalid_wallet
                                       assert_raises_rpc_error(-18, error_message, node.restorewallet, wallet_name, invalid_wallet_file)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 124, in assert_raises_rpc_error
                                       assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 137, in try_rpc
                                       raise AssertionError("Unexpected JSONRPC error code %i" % e.error["code"])
                                   AssertionError: Unexpected JSONRPC error code -1

**Comment by fanquake** [comment]
@sipsorcery @kiminuo would either of you be interested in taking a look at the native windows failures / windows related changes in general?

**Comment by hebasto** [comment]
FWIW, both `wallet_backup.py --legacy-wallet` and `wallet_backup.py --descriptors` passed locally on Windows 10 Pro 21H1 (build 19043.1415).

**Comment by kiminuo** [comment]
@fanquake I'll try my best to have a look in a day or two.

**Review by hebasto — COMMENTED** [review]
This comment https://github.com/bitcoin/bitcoin/blob/4bc11affebc983d6849a05b42b026fea25a3512e/src/util/system.cpp#L1076-L1081 needs to be updated, no?

**Comment by hebasto** [comment]
> @sipsorcery @kiminuo would either of you be interested in taking a look at the native windows failures / windows related changes in general?

The failing test was added in #23721. @w0xlt maybe you also could be interested in this problem?

**Comment by achow101** [comment]
The Win64 failure appears to be an issue with unicode characters in the path.

**Comment by hebasto** [comment]
A quick fix for native Windows:
```diff
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -377,7 +377,7 @@ std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const std::string
     }
 
     auto wallet_file = wallet_path / "wallet.dat";
-    fs::copy_file(backup_file, wallet_file);
+    fs::copy_file(fs::u8path(backup_file), wallet_file);
 
     auto wallet = LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings);
 
```

Sure, it can be refactored nicely.

Maybe, switch type of the `backup_file` parameter in the `RestoreWallet` function from `std::string` to `fs::path`?

**Comment by achow101** [comment]
```diff
diff --git a/src/wallet/interfaces.cpp b/src/wallet/interfaces.cpp
index 64775a5ddb..41c17c53e4 100644
--- a/src/wallet/interfaces.cpp
+++ b/src/wallet/interfaces.cpp
@@ -561,7 +561,7 @@ public:
     {
         DatabaseStatus status;
 
-        return MakeWallet(m_context, RestoreWallet(m_context, backup_file, wallet_name, /*load_on_start=*/true, status, error, warnings));
+        return MakeWallet(m_context, RestoreWallet(m_context, fs::u8path(backup_file), wallet_name, /*load_on_start=*/true, status, error, warnings));
     }
     std::string getWalletDir() override
     {
diff --git a/src/wallet/rpc/backup.cpp b/src/wallet/rpc/backup.cpp
index eb912c68d5..dcf7a24b2a 100644
--- a/src/wallet/rpc/backup.cpp
+++ b/src/wallet/rpc/backup.cpp
@@ -1888,7 +1888,7 @@ RPCHelpMan restorewallet()
     bilingual_str error;
     std::vector<bilingual_str> warnings;
 
-    const std::shared_ptr<CWallet> wallet = RestoreWallet(context, fs::PathToString(backup_file), wallet_name, load_on_start, status, error, warnings);
+    const std::shared_ptr<CWallet> wallet = RestoreWallet(context, backup_file, wallet_name, load_on_start, status, error, warnings);
 
     HandleWalletError(wallet, status, error);
 
diff --git a/src/wallet/wallet.cpp b/src/wallet/wallet.cpp
index c6a8b3e43f..3819ec2002 100644
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -357,12 +357,12 @@ std::shared_ptr<CWallet> CreateWallet(WalletContext& context, const std::string&
     return wallet;
 }
 
-std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const std::string& backup_file, const std::string& wallet_name, std::optional<bool> load_on_start, DatabaseStatus& status, bilingual_str& error, std::vector<bilingual_str>& warnings)
+std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const fs::path& backup_file, const std::string& wallet_name, std::optional<bool> load_on_start, DatabaseStatus& status, bilingual_str& error, std::vector<bilingual_str>& warnings)
 {
     DatabaseOptions options;
     options.require_existing = true;
 
-    if (!fs::exists(fs::u8path(backup_file))) {
+    if (!fs::exists(backup_file)) {
         error = Untranslated("Backup file does not exist");
         status = DatabaseStatus::FAILED_INVALID_BACKUP_FILE;
         return nullptr;
diff --git a/src/wallet/wallet.h b/src/wallet/wallet.h
index cbcdcaf3b8..0acfe8f02a 100644
--- a/src/wallet/wallet.h
+++ b/src/wallet/wallet.h
@@ -60,7 +60,7 @@ std::vector<std::shared_ptr<CWallet>> GetWallets(WalletContext& context);
 std::shared_ptr<CWallet> GetWallet(WalletContext& context, const std::string& name);
 std::shared_ptr<CWallet> LoadWallet(WalletContext& context, const std::string& name, std::optional<bool> load_on_start, const DatabaseOptions& options, DatabaseStatus& status, bilingual_str& error, std::vector<bilingual_str>& warnings);
 std::shared_ptr<CWallet> CreateWallet(WalletContext& context, const std::string& name, std::optional<bool> load_on_start, DatabaseOptions& options, DatabaseStatus& status, bilingual_str& error, std::vector<bilingual_str>& warnings);
-std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const std::string& backup_file, const std::string& wallet_name, std::optional<bool> load_on_start, DatabaseStatus& status, bilingual_str& error, std::vector<bilingual_str>& warnings);
+std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const fs::path& backup_file, const std::string& wallet_name, std::optional<bool> load_on_start, DatabaseStatus& status, bilingual_str& error, std::vector<bilingual_str>& warnings);
 std::unique_ptr<interfaces::Handler> HandleLoadWallet(WalletContext& context, LoadWalletFn load_wallet);
 std::unique_ptr<WalletDatabase> MakeWalletDatabase(const std::string& name, const DatabaseOptions& options, DatabaseStatus& status, bilingual_str& error);
```

**Comment by hebasto** [comment]
> A quick fix for native Windows:
> ...
> Maybe, switch a type of the `backup_file` parameter in the `RestoreWallet` function from `std::string` to `fs::path`?

Please consider #24026.

**Review by hebasto — COMMENTED** [review]
Also a reminder about https://github.com/bitcoin/bitcoin/pull/20744#pullrequestreview-848269313

---

Maybe you'd want to address some comments from #23522:
- https://github.com/bitcoin/bitcoin/pull/23522/files#r750263938
- https://github.com/bitcoin/bitcoin/pull/23522/files#r750264221
- https://github.com/bitcoin/bitcoin/pull/23522/files#r750264602
- https://github.com/bitcoin/bitcoin/pull/23522#issuecomment-971145313

**Comment by fanquake** [comment]
> Also a reminder about #20744 (review)

Done.

> Maybe you'd want to address some comments from #23522:

All should now be addressed. I resolved in that PR.

Fixed up current review comments as well.

**Comment by sipsorcery** [comment]
> @sipsorcery @kiminuo would either of you be interested in taking a look at the native windows failures / windows related changes in general?

My tests so far point to the Windows test failure being a pythin unicode issue.

Running the test using `wallet_backup.py` always passes:
````
c:\Dev\github\sipsorcery_bitcoin>test\functional\wallet_backup.py --descriptors
2022-01-10T21:02:34.014000Z TestFramework (INFO): Initializing test directory C:\Users\aaron\AppData\Local\Temp\bitcoin_func_test_jze1co0z
````

Running the test using `test_runner.py` always fails:
````
c:\Dev\github\sipsorcery_bitcoin>test\functional\test_runner.py --filter="wallet_backup.py --descriptors"
Temporary test directory at C:\Users\aaron\AppData\Local\Temp/test_runner_₿_🏃_20220110_213157
`````

In the latter, failing case there are unicode characters in the path. The python exception message states it can't encode '\u20bf', but as seen in the log message above my console has no issue with it: ₿.

I'll keep digging.

**Comment by hebasto** [comment]
Wrt a failure of a build for Windows in Guix environment -- https://gcc.gnu.org/legacy-ml/libstdc++/2011-06/msg00066.html

**Comment by sipsorcery** [comment]
> @sipsorcery @kiminuo would either of you be interested in taking a look at the native windows failures / windows related changes in general?

@fanquake what are the windows failures with this PR? I'd assumed it was to do with the python functional tests but the I get the same failures before and after this PR.

Relevant results of `test\functional\test_runner.py`:
````
wallet_watchonly.py --usecli --legacy-wallet       | ✓ Passed  | 5 s
feature_backwards_compatibility.py --descriptors   | ○ Skipped | 1 s
feature_backwards_compatibility.py --legacy-wallet | ○ Skipped | 1 s
feature_bind_extra.py                              | ○ Skipped | 0 s
feature_init.py                                    | ○ Skipped | 3 s
feature_syscall_sandbox.py                         | ○ Skipped | 0 s
feature_taproot.py --previous_release              | ○ Skipped | 0 s
feature_txindex_compatibility.py                   | ○ Skipped | 0 s
mempool_compatibility.py                           | ○ Skipped | 0 s
rpc_bind.py --ipv4                                 | ○ Skipped | 1 s
rpc_bind.py --ipv6                                 | ○ Skipped | 0 s
rpc_bind.py --nonloopback                          | ○ Skipped | 0 s
wallet_upgradewallet.py --legacy-wallet            | ○ Skipped | 0 s
feature_config_args.py                             | ✖ Failed  | 13 s
interface_bitcoin_cli.py --descriptors             | ✖ Failed  | 6 s
interface_bitcoin_cli.py --legacy-wallet           | ✖ Failed  | 6 s
interface_rpc.py                                   | ✖ Failed  | 34 s
tool_wallet.py --descriptors                       | ✖ Failed  | 19 s
tool_wallet.py --legacy-wallet                     | ✖ Failed  | 15 s
wallet_multiwallet.py --descriptors                | ✖ Failed  | 3 s
wallet_multiwallet.py --legacy-wallet              | ✖ Failed  | 3 s
wallet_multiwallet.py --usecli                     | ✖ Failed  | 3 s

ALL                                                | ✖ Failed  | 5971 s (accumulated)
````

**Comment by MarcoFalke** [comment]
I think the CI issues are fixed (telling from the green ci?)

**Comment by MarcoFalke** [comment]
@fanquake Is this rfm?

**Comment by hebasto** [comment]
> @fanquake Is this rfm?

Guix Windows build fails.

**Comment by achow101** [comment]
On windows, I am hitting the assert at src/util/system.cpp:258

**Comment by MarcoFalke** [comment]
You forgot to revert dc5d6b0d4793ca978f71f69ef7d6b818794676c2

**Comment by hebasto** [comment]
I've restarted "ARM64 Android APK [focal]" CI build due to unrelated to this PR network issues.

**Review by hebasto — APPROVED** [review]
ACK 45e546c877a30a006ccb24aa465a9f6c1a96554a

File: src/rpc/request.cpp (hunk 22 above)
Comment (MarcoFalke) [reply src/rpc/request.cpp:88]: Wouldn't it be better to somehow do the c_str call hidden inside the fsbridge namespace? Seems a bit odd to force devs to write ugly and unintuitive code just because mingw can't even.

**Comment by MarcoFalke** [comment]
Seems fine to merge, but I am not yet convinced this is all correct:

* There is a `fsbridge::ofstream` constructor that takes a `std::string`. Why is this safe, considering that usually this was passed through `PathFromString`? See also https://github.com/bitcoin/bitcoin/pull/23857#issuecomment-1021995207
* There are a bunch of calls to `c_str()`, which are ugly and not exactly promoting safe code. If they are scattered around in the codebase, reviewers won't be able to see `fs::path{std::string{}.c_str()}` calls, which are less safe than `PathFromString`? See also https://github.com/bitcoin/bitcoin/pull/20744/files#r791853189

File: src/rpc/request.cpp (hunk 22 above)
Comment (ryanofsky) [reply src/rpc/request.cpp:88]: > Wouldn't it be better to somehow do the c_str call hidden inside the fsbridge namespace? Seems a bit odd to force devs to write ugly and unintuitive code just because mingw can't even.

I also like the idea of hiding this in the fsbridge namespace (where there is no need to use c_str() at all), which is why I [originally suggested](https://github.com/bitcoin/bitcoin/pull/20744#discussion_r733637362) fixing this with:

```diff
-    typedef std::ofstream ofstream;
+    class ofstream : public std::ofstream
+    {
+        using std::ofstream::ofstream;
+        ofstream(const fs::path& p) : ofstream(static_cast<const std::filesystem::path&>(p)) {}
+    };
```

But @hebasto preferred the second alternative I suggested, which was calling to c_str() so we went with that approach instead. I still do like not calling c_str() better, but don't have a strong opinion.

**Review by ryanofsky — COMMENTED** [review]
re: https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-1022030719

> Seems fine to merge, but I am not yet convinced this is all correct:
>
>* There is a `fsbridge::ofstream` constructor that takes a `std::string`. Why is this safe, considering that usually this was passed through `PathFromString`? See also [fs: consistently use fsbridge:: for ifstream / ofstream #23857 (comment)](https://github.com/bitcoin/bitcoin/pull/23857#issuecomment-1021995207)

It is not safe to call the fstream `std::string` constructors even with `PathToString`! On windows, this will still do a locale conversion. Briefly skimming the code, I don't see this happening anywhere though.

>* There are a bunch of calls to `c_str()`, which are ugly and not exactly promoting safe code. If they are scattered around in the codebase, reviewers won't be able to see `fs::path{std::string{}.c_str()}` calls, which are less safe than `PathFromString`? See also https://github.com/bitcoin/bitcoin/pull/20744/files#r791853189

To be clear, the reason why `path.c_str()` is safe is because it is equivalent to `path.native().c_str()` which returns `const wchar_t*` on windows not `path.string().c_str()` which returns `const char*`. Using `path.native()` is good, using `path.string()` is bad, using `something.c_str()` is neutral.

File: src/rpc/request.cpp (hunk 22 above)
Comment (hebasto) [reply src/rpc/request.cpp:88]: Sorry, if my words were misleading, but I expressed my preference for `c_str()` over a `static_cast`. I'm ok if it will be hidden in `fsbridge` namespace.

Comment (hebasto) [reply src/rpc/request.cpp:88]: > I still do like not calling c_str() better,

What reasons for?

Comment (ryanofsky) [reply src/rpc/request.cpp:88]: > > I still do like not calling c_str() better,
> 
> What reasons for?

Mainly just for the reason that marco wrote https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-1022030719 that the `.c_str()` calls look ugly and and unsafe even if they are safe. It could be confusing that `path.c_str()` is safe when `path.string().c_str()` is unsafe, and it's nice to just be able to pass plain `path`. Also just passing the path object directly avoids temporary objects. No strong preference though, and no problem with either approach.

Comment (kiminuo) [reply src/rpc/request.cpp:88]: Would it be useful to summarize what one should do and what shouldn't with the new filesystem API with regard to paths? Or is it somewhere? I mean I know ryanofsky wrote many useful comments in this PR and in others. Maybe we can have a few bullet points saying "this is OK, this is not" so that there are actually more people who can review PRs with FS changes.

**Comment by MarcoFalke** [comment]
> It is not safe to call the fstream std::string constructors even with PathToString! On windows, this will still do a locale conversion. Briefly skimming the code, I don't see this happening anywhere though.

I mean Path*From*String. This happens https://github.com/bitcoin/bitcoin/pull/24167/files#diff-9e7b9e5b612b62329bdec3c2d522ae36dca904c291ce6192ae74c9c1b3c5827f in bench.cpp.

File: src/rpc/request.cpp (hunk 22 above)
Comment (ryanofsky) [reply src/rpc/request.cpp:88]: > Would it be useful to summarize what one should do and what shouldn't with the new filesystem API with regard to paths? Or is it somewhere? I mean I know ryanofsky wrote many useful comments in this PR and in others. Maybe we can have a few bullet points saying "this is OK, this is not" so that there are actually more people who can review PRs with FS changes. Just an idea. Feel free to ignore.

I think main recommendation is to use fs::path object wherever possible and avoid representing paths as strings. Beyond that there is a note in developer notes:

>- Use `fs::path::u8string()` and `fs::u8path()` functions when converting path
>  to JSON strings, not `fs::PathToString` and `fs::PathFromString`
>
>   - *Rationale*: JSON strings are Unicode strings, not byte strings, and
>      RFC8259 requires JSON to be encoded as UTF-8.

And a detailed comment on the [`PathToString`](https://github.com/bitcoin/bitcoin/blob/e3699b71c46bf66cfe363fc76ab8761dc39555a7/src/fs.h#L102-L120) function saying when it should be used.

You could write more documentation, but I think current documentation is at least not bad.

**Comment by ryanofsky** [comment]
> I mean Path_From_String. This happens https://github.com/bitcoin/bitcoin/pull/24167/files#diff-9e7b9e5b612b62329bdec3c2d522ae36dca904c291ce6192ae74c9c1b3c5827f in bench.cpp.

I see. There isn't necessarily a bug here if command line arguments are utf-8, but the code is not ideal. More ideally [`benchmark::Args` `output_csv` and `output_json` fields](https://github.com/bitcoin/bitcoin/blob/e3699b71c46bf66cfe363fc76ab8761dc39555a7/src/bench/bench.h#L47-L48) would be `fs::path` not `std::string` members, so any encoding/decoding would happen when the command line argument is parsed, not when the path is accessed.

**Comment by fanquake** [comment]
I've rebased, removed some non-essential changes, (there seemed to be issues with mingw and braced initialization), and given the discussion I have dropped the usage of `.c_str()` in favour of @ryanofsky's [suggested change](https://github.com/bitcoin/bitcoin/pull/20744#discussion_r792736041).

File: src/fs.h [hunk 23]
```diff
@@ -5,46 +5,41 @@
...
 /**
- * Path class wrapper to prepare application code for transition from
- * boost::filesystem library to std::filesystem implementation. The main
- * purpose of the class is to define fs::path::u8string() and fs::u8path()
- * functions not present in boost. It also blocks calls to the
- * fs::path(std::string) implicit constructor and the fs::path::string()
- * method, which worked well in the boost::filesystem implementation, but have
- * unsafe and unpredictable behavior on Windows in the std::filesystem
- * implementation (see implementation note in \ref PathToString for details).
+ * Path class wrapper to blocks calls to the fs::path(std::string) implicit
```
Comment (kiminuo) [inline src/fs.h:23]:
```suggestion
 * Path class wrapper to block calls to the fs::path(std::string) implicit
```

**Comment by MarcoFalke** [comment]
Doesn't compile on windows

**Comment by MarcoFalke** [comment]
Huh? https://cirrus-ci.com/task/5390848991952896?logs=ci#L8767

```
rpc/request.cpp: In function ‘bool GenerateAuthCookie(std::string*)’:
rpc/request.cpp:88:27: error: no matching function for call to ‘fsbridge::ofstream::open(fs::path&)’
   88 |     file.open(filepath_tmp);
      |                           ^

**Comment by prusnak** [comment]
> Huh? https://cirrus-ci.com/task/5390848991952896?logs=ci#L8767

Ah, sorry. I missed that error. There are lots of others related to Qt 5.15.2.

**Comment by prusnak** [comment]
Just for the record:

While trying to reproduce this error I hit another error which is fixed by https://github.com/bitcoin/bitcoin/pull/24131 (I uninstalled `g++-mingw-w64-x86-64` and kept only `g++-mingw-w64-x86-64-posix` installed on my Debian 11 Buster system).

**Comment by prusnak** [comment]
The following changes fix the build on Mingw for me. I have **not** tested the resulting binaries!

Not sure if calling `c_str()` is correct or desired, but at least the changes indicate where are the places which upset the compiler.

Another and probably more clean option is to overload the `ifstream::open`/`ofstream::open` functions to also accept `fs::path` as the first argument.

``` patch
diff --git a/src/qt/guiutil.cpp b/src/qt/guiutil.cpp
index 6f7943f34..0a16356b6 100644
--- a/src/qt/guiutil.cpp
+++ b/src/qt/guiutil.cpp
@@ -427,7 +427,7 @@ bool openBitcoinConf()
     fs::path pathConfig = GetConfigFile(gArgs.GetArg("-conf", BITCOIN_CONF_FILENAME));
 
     /* Create the file */
-    fsbridge::ofstream configFile(pathConfig, std::ios_base::app);
+    fsbridge::ofstream configFile(pathConfig.c_str(), std::ios_base::app);
 
     if (!configFile.good())
         return false;
diff --git a/src/rpc/request.cpp b/src/rpc/request.cpp
index fbb4e5ddd..4fcc656de 100644
--- a/src/rpc/request.cpp
+++ b/src/rpc/request.cpp
@@ -85,7 +85,7 @@ bool GenerateAuthCookie(std::string *cookie_out)
      */
     fsbridge::ofstream file;
     fs::path filepath_tmp = GetAuthCookieFile(true);
-    file.open(filepath_tmp);
+    file.open(filepath_tmp.c_str());
     if (!file.is_open()) {
         LogPrintf("Unable to open cookie authentication file %s for writing\n", fs::PathToString(filepath_tmp));
         return false;
@@ -110,7 +110,7 @@ bool GetAuthCookie(std::string *cookie_out)
     fsbridge::ifstream file;
     std::string cookie;
     fs::path filepath = GetAuthCookieFile();
-    file.open(filepath);
+    file.open(filepath.c_str());
     if (!file.is_open())
         return false;
     std::getline(file, cookie);
diff --git a/src/test/fs_tests.cpp b/src/test/fs_tests.cpp
index d3389c30e..ca25fcb38 100644
--- a/src/test/fs_tests.cpp
+++ b/src/test/fs_tests.cpp
@@ -45,37 +45,37 @@ BOOST_AUTO_TEST_CASE(fsbridge_fstream)
     fs::path tmpfile1 = tmpfolder / "fs_tests_₿_🏃";
     fs::path tmpfile2 = tmpfolder / "fs_tests_₿_🏃";
     {
-        fsbridge::ofstream file(tmpfile1);
+        fsbridge::ofstream file(tmpfile1.c_str());
         file << "bitcoin";
     }
     {
-        fsbridge::ifstream file(tmpfile2);
+        fsbridge::ifstream file(tmpfile2.c_str());
         std::string input_buffer;
         file >> input_buffer;
         BOOST_CHECK_EQUAL(input_buffer, "bitcoin");
     }
     {
-        fsbridge::ifstream file(tmpfile1, std::ios_base::in | std::ios_base::ate);
+        fsbridge::ifstream file(tmpfile1.c_str(), std::ios_base::in | std::ios_base::ate);
         std::string input_buffer;
         file >> input_buffer;
         BOOST_CHECK_EQUAL(input_buffer, "");
     }
     {
-        fsbridge::ofstream file(tmpfile2, std::ios_base::out | std::ios_base::app);
+        fsbridge::ofstream file(tmpfile2.c_str(), std::ios_base::out | std::ios_base::app);
         file << "tests";
     }
     {
-        fsbridge::ifstream file(tmpfile1);
+        fsbridge::ifstream file(tmpfile1.c_str());
         std::string input_buffer;
         file >> input_buffer;
         BOOST_CHECK_EQUAL(input_buffer, "bitcointests");
     }
     {
-        fsbridge::ofstream file(tmpfile2, std::ios_base::out | std::ios_base::trunc);
+        fsbridge::ofstream file(tmpfile2.c_str(), std::ios_base::out | std::ios_base::trunc);
         file << "bitcoin";
     }
     {
-        fsbridge::ifstream file(tmpfile1);
+        fsbridge::ifstream file(tmpfile1.c_str());
         std::string input_buffer;
         file >> input_buffer;
         BOOST_CHECK_EQUAL(input_buffer, "bitcoin");
diff --git a/src/test/settings_tests.cpp b/src/test/settings_tests.cpp
index e7edadc8b..0d1d28fac 100644
--- a/src/test/settings_tests.cpp
+++ b/src/test/settings_tests.cpp
@@ -38,7 +38,7 @@ inline std::ostream& operator<<(std::ostream& os, const std::pair<std::string, u
 inline void WriteText(const fs::path& path, const std::string& text)
 {
     fsbridge::ofstream file;
-    file.open(path);
+    file.open(path.c_str());
     file << text;
 }
 
diff --git a/src/util/settings.cpp b/src/util/settings.cpp
index fd9fe690c..0b181a6e0 100644
--- a/src/util/settings.cpp
+++ b/src/util/settings.cpp
@@ -65,7 +65,7 @@ bool ReadSettings(const fs::path& path, std::map<std::string, SettingsValue>& va
     if (!fs::exists(path)) return true;
 
     fsbridge::ifstream file;
-    file.open(path);
+    file.open(path.c_str());
     if (!file.is_open()) {
       errors.emplace_back(strprintf("%s. Please check permissions.", fs::PathToString(path)));
       return false;
@@ -108,7 +108,7 @@ bool WriteSettings(const fs::path& path,
         out.__pushKV(value.first, value.second);
     }
     fsbridge::ofstream file;
-    file.open(path);
+    file.open(path.c_str());
     if (file.fail()) {
         errors.emplace_back(strprintf("Error: Unable to open settings file %s for writing", fs::PathToString(path)));
         return false;
diff --git a/src/util/system.cpp b/src/util/system.cpp
index 1137d4d75..c6754dbc2 100644
--- a/src/util/system.cpp
+++ b/src/util/system.cpp
@@ -898,7 +898,7 @@ bool ArgsManager::ReadConfigFiles(std::string& error, bool ignore_invalid_keys)
     }
 
     const std::string confPath = GetArg("-conf", BITCOIN_CONF_FILENAME);
-    fsbridge::ifstream stream(GetConfigFile(confPath));
+    fsbridge::ifstream stream(GetConfigFile(confPath).c_str());
 
     // not ok to have a config file specified that cannot be opened
     if (IsArgSet("-conf") && !stream.good()) {
@@ -945,7 +945,7 @@ bool ArgsManager::ReadConfigFiles(std::string& error, bool ignore_invalid_keys)
             const size_t default_includes = add_includes({});
 
             for (const std::string& conf_file_name : conf_file_names) {
-                fsbridge::ifstream conf_file_stream(GetConfigFile(conf_file_name));
+                fsbridge::ifstream conf_file_stream(GetConfigFile(conf_file_name).c_str());
                 if (conf_file_stream.good()) {
                     if (!ReadConfigStream(conf_file_stream, conf_file_name, error, ignore_invalid_keys)) {
                         return false;
diff --git a/src/wallet/db.cpp b/src/wallet/db.cpp
index 9be942e7a..b1efdd819 100644
--- a/src/wallet/db.cpp
+++ b/src/wallet/db.cpp
@@ -86,7 +86,7 @@ bool IsBDBFile(const fs::path& path)
     if (ec) LogPrintf("%s: %s %s\n", __func__, ec.message(), fs::PathToString(path));
     if (size < 4096) return false;
 
-    fsbridge::ifstream file(path, std::ios::binary);
+    fsbridge::ifstream file(path.c_str(), std::ios::binary);
     if (!file.is_open()) return false;
 
     file.seekg(12, std::ios::beg); // Magic bytes start at offset 12
@@ -110,7 +110,7 @@ bool IsSQLiteFile(const fs::path& path)
     if (ec) LogPrintf("%s: %s %s\n", __func__, ec.message(), fs::PathToString(path));
     if (size < 512) return false;
 
-    fsbridge::ifstream file(path, std::ios::binary);
+    fsbridge::ifstream file(path.c_str(), std::ios::binary);
     if (!file.is_open()) return false;
 
     // Magic is at beginning and is 16 bytes long
diff --git a/src/wallet/dump.cpp b/src/wallet/dump.cpp
index 2437c415c..bd6f7d484 100644
--- a/src/wallet/dump.cpp
+++ b/src/wallet/dump.cpp
@@ -28,7 +28,7 @@ bool DumpWallet(CWallet& wallet, bilingual_str& error)
         return false;
     }
     fsbridge::ofstream dump_file;
-    dump_file.open(path);
+    dump_file.open(path.c_str());
     if (dump_file.fail()) {
         error = strprintf(_("Unable to open %s for writing"), fs::PathToString(path));
         return false;
@@ -122,7 +122,7 @@ bool CreateFromDump(const std::string& name, const fs::path& wallet_path, biling
         error = strprintf(_("Dump file %s does not exist."), fs::PathToString(dump_path));
         return false;
     }
-    fsbridge::ifstream dump_file(dump_path);
+    fsbridge::ifstream dump_file(dump_path.c_str());
 
     // Compute the checksum
     CHashWriter hasher(0, 0);
diff --git a/src/wallet/rpc/backup.cpp b/src/wallet/rpc/backup.cpp
index 3190042c5..2f2e83362 100644
--- a/src/wallet/rpc/backup.cpp
+++ b/src/wallet/rpc/backup.cpp
@@ -731,7 +731,7 @@ RPCHelpMan dumpwallet()
     }
 
     fsbridge::ofstream file;
-    file.open(filepath);
+    file.open(filepath.c_str());
     if (!file.is_open())
         throw JSONRPCError(RPC_INVALID_PARAMETER, "Cannot open wallet dump file");
 

```

**Comment by prusnak** [comment]
What is odd is that the following compiles via `x86_64-w64-mingw32-g++-posix -std=c++17 -Wall x.cc` without any issues:

``` cpp
#include <fstream>
#include <filesystem>

namespace fs = std::filesystem;

int main () {
  fs::path p("test");

  std::ofstream ofs;
  ofs.open(p);
  ofs.close();

  std::ifstream ifs;
  ifs.open(p, std::ifstream::in);
  ifs.close();

  return 0;
}
```

**Comment by prusnak** [comment]
> Not sure if calling `c_str()` is correct or desired, but at least the changes indicate where are the places which upset the compiler.

Reading more about how things are implemented in `fs.c`, it seems that we are actively avoiding the default conversions of `std::filesystem::path` to `std::string`, by using our own custom `fs::path`. Therefore the correct thing would be to call `fs::PathToString(foo)` instead of `foo.c_str()` in all places I indicated in my patch above.

**Comment by ryanofsky** [comment]
> Reading more about how things are implemented in `fs.c`, it seems that we are actively avoiding the default conversions of `std::filesystem::path` to `std::string`, by using our own custom `fs::path`. Therefore the correct thing would be to call `fs::PathToString(foo)` instead of `foo.c_str()` in all places I indicated in my patch above.

To be clear we are actively avoiding converting paths to narrow strings, because on windows it will result in possibly incorrect encodings using the current windows code page. Calling fs::PathToString would also be incorrect and does not avoid the problem, because it would convert the wide string to a narrow string as utf8, but then narrow string would be decoded back to a wide string using the current windows code page again (which would be incorrect if the code page is not also UTF-8). Calling `path.c_str()` is correct because it is equivalent to `path.native().c_str()` and avoids encoding / decoding whatsoever.






> In commit "refactor: replace boost::filesystem with std::filesystem" ([b70c843](https://github.com/bitcoin/bitcoin/commit/b70c84348ac7a8e427a1183f894c73e52c734529))
> 
> These static_casts seem to be added because even though `GetPidFile` returns `fs::path` and `fs::path` inherits from `std::filesystem::path`, the `basic_ofstream` constructor has an `_If_fs_path` requirement that needs an exact `std::filesystem::path` match:
> 
> ```c++
>       template<typename _Path, typename _Require = _If_fs_path<_Path>>
>         basic_ofstream(const _Path& __s,
>                        ios_base::openmode __mode = ios_base::out)
>         : basic_ofstream(__s.c_str(), __mode)
>         { }
> ```
> 
> It might be nice to drop the need for these static_casts in `fsbridge` with something like
> 
> ```diff
> -    typedef std::ofstream ofstream;
> +    class ofstream : public std::ofstream
> +    {
> +        using std::ofstream::ofstream;
> +        ofstream(const fs::path& p) : ofstream(static_cast<const std::filesystem::path&>(p)) {}
> +    };
> ```
> 
> Another alternative would just be to pass `path.c_str()` instead of `path` when constructing `ofstream` objects. This should be safe because `c_str` returns a wide string on windows.

https://github.com/bitcoin/bitcoin/pull/20744#discussion_r733637362

**Comment by ryanofsky** [comment]
@fanquake To fix the windows ifstream errors https://cirrus-ci.com/task/5390848991952896?logs=ci#L8810 like:

```
wallet/db.cpp: In function ‘bool wallet::IsSQLiteFile(const fs::path&)’:
wallet/db.cpp:113:51: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(const fs::path&, const openmode&)’
  113 |     fsbridge::ifstream file(path, std::ios::binary);
```

You could either define an fsbridge::ifstream class similar to the fsbridge::ofstream class defining an `fs::path` constructor:

https://github.com/bitcoin/bitcoin/blob/6dd6f6f4df06f61bd0d90db1247428b9d6a6626e/src/fs.h#L177-L182

Or, you could pass `path.c_str()` to `ifstream` constructors (which is equivalent to `path.native().c_str()` and avoids encoding/decoding)`

File: src/fs.h (hunk 23 above)
Comment (fanquake) [reply src/fs.h]: Fixed

**Comment by fanquake** [comment]
> You could either define an fsbridge::ifstream class similar to the fsbridge::ofstream class defining an fs::path constructor:

I've done this, as it seems everyone is in favour of keeping changes constrained to `fs.*` rather than using `c_str()` over the codebase.

**Comment by prusnak** [comment]
The CI still fails on Windows: https://github.com/bitcoin/bitcoin/pull/20744/checks?check_run_id=5016412013

**Comment by hebasto** [comment]
To fix MinGW build, suggesting the following patch:
```diff
--- a/src/fs.h
+++ b/src/fs.h
@@ -175,18 +175,26 @@ namespace fsbridge {
 
     std::string get_filesystem_error_message(const fs::filesystem_error& e);
 
-    class ifstream : public std::ifstream
+    struct ifstream : public std::ifstream
     {
-        using std::ifstream::ifstream;
-    public:
-        ifstream(const fs::path& p) : ifstream(static_cast<const std::filesystem::path&>(p)) {}
+        ifstream() = default;
+        explicit ifstream(const fs::path& p, std::ios_base::openmode mode = std::ios_base::in)
+            : std::ifstream(static_cast<const std::filesystem::path&>(p), mode) {}
+        void open(const fs::path& p, std::ios_base::openmode mode = std::ios_base::in)
+        {
+            std::ifstream::open(static_cast<const std::filesystem::path&>(p), mode);
+        }
     };
 
-    class ofstream : public std::ofstream
+    struct ofstream : public std::ofstream
     {
-        using std::ofstream::ofstream;
-    public:
-        ofstream(const fs::path& p) : ofstream(static_cast<const std::filesystem::path&>(p)) {}
+        ofstream()  = default;
+        explicit ofstream(const fs::path& p, std::ios_base::openmode mode = std::ios_base::out)
+            : std::ofstream(static_cast<const std::filesystem::path&>(p), mode) {}
+        void open(const fs::path& p, std::ios_base::openmode mode = std::ios_base::out)
+        {
+            std::ofstream::open(static_cast<const std::filesystem::path&>(p), mode);
+        }
     };
 };
 
```

**Comment by hebasto** [comment]
I've done some research, and suggesting a--seemingly more elegant--solution: `s/fsbridge::{i,o}fstream/std::{i,o}fstream/g`, and apply the following patch:
```diff
--- a/src/fs.h
+++ b/src/fs.h
@@ -51,6 +51,11 @@ public:
 
     // Disallow std::string conversion method to avoid locale-dependent encoding on windows.
     std::string string() const = delete;
+
+    // Required for path overloads in <fstream>.
+    // See https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=96e0367ead5d8dcac3bec2865582e76e2fbab190
+    path& make_preferred() { std::filesystem::path::make_preferred(); return *this; }
+    path filename() const { return std::filesystem::path::filename(); }
 };
 
 // Disallow implicit std::string conversion for absolute to avoid
@@ -174,20 +179,6 @@ namespace fsbridge {
     };
 
     std::string get_filesystem_error_message(const fs::filesystem_error& e);
-
-    class ifstream : public std::ifstream
-    {
-        using std::ifstream::ifstream;
-    public:
-        ifstream(const fs::path& p) : ifstream(static_cast<const std::filesystem::path&>(p)) {}
-    };
-
-    class ofstream : public std::ofstream
-    {
-        using std::ofstream::ofstream;
-    public:
-        ofstream(const fs::path& p) : ofstream(static_cast<const std::filesystem::path&>(p)) {}
-    };
 };
 
 // Disallow path operator<< formatting in tinyformat to avoid locale-dependen
```

**Comment by fanquake** [comment]
@hebasto I've adapted to take your second approach. Guix builds for all (working) HOSTS will be added to the PR description shortly.

**Comment by hebasto** [comment]
Tested db2b9123bba80829a01a32054f4736a5333d5f75.

Cross-compiled Windows binaries work fine on Windows 10 Pro 21H1 (build 19043.1466).

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
640eb4085dbb9cfe2f0cb2c703fe8f3229274f3c1fa6d65ae3bbc59e5c56ea34  guix-build-db2b9123bba8/output/aarch64-linux-gnu/SHA256SUMS.part
4d45614059ef643196a32c5c3260759e535a79a1d59b3fa341c17337785323f1  guix-build-db2b9123bba8/output/aarch64-linux-gnu/bitcoin-db2b9123bba8-aarch64-linux-gnu-debug.tar.gz
f382e74bdf0f84016d7fc608db8f445d0ecab3baea2393141c801916120f9d8f  guix-build-db2b9123bba8/output/aarch64-linux-gnu/bitcoin-db2b9123bba8-aarch64-linux-gnu.tar.gz
e5ff995a3bc3ee4fb81c5ff162997721fa64d76d958a5e90efbd322be876e5b7  guix-build-db2b9123bba8/output/arm-linux-gnueabihf/SHA256SUMS.part
249d90bd4fd97062d5629f5408dc05b56c053ae1d826f5909a9576e926666dea  guix-build-db2b9123bba8/output/arm-linux-gnueabihf/bitcoin-db2b9123bba8-arm-linux-gnueabihf-debug.tar.gz
714dfd377c314e5466560ab47d857e480bb6aa105671241c4a85ae20527ae54a  guix-build-db2b9123bba8/output/arm-linux-gnueabihf/bitcoin-db2b9123bba8-arm-linux-gnueabihf.tar.gz
518d62f5bcb34939b7a36cb642f5e05465d253b8de6d16ccf25661f326abfe5d  guix-build-db2b9123bba8/output/arm64-apple-darwin/SHA256SUMS.part
474d14000d329381ca52991f4f8ebab6feab8a7afe64cf21d87b267f9a922065  guix-build-db2b9123bba8/output/arm64-apple-darwin/bitcoin-db2b9123bba8-arm64-apple-darwin.tar.gz
733533dbd271ec8088a2bf0ad8e6e34b0aedba2dcb98defc2d333f230582d146  guix-build-db2b9123bba8/output/arm64-apple-darwin/bitcoin-db2b9123bba8-osx-unsigned.dmg
f4f39117cb449ba3433cdf0456cdd7b40f322ba42dbc94b8e9fd6529d57ed11f  guix-build-db2b9123bba8/output/arm64-apple-darwin/bitcoin-db2b9123bba8-osx-unsigned.tar.gz
77b751ea929e38aba0197e6926c18eb4d5a95a9ed44036600148e48711fd409f  guix-build-db2b9123bba8/output/dist-archive/bitcoin-db2b9123bba8.tar.gz
e7ecd03ae71d22f30a8c1852880b616412edbb4b84dca707fefc9ef02cedf09b  guix-build-db2b9123bba8/output/powerpc64-linux-gnu/SHA256SUMS.part
266e70594b214a73aeb885d180cfe7e9c3297f62af7d56aa3ea607f290f6e38c  guix-build-db2b9123bba8/output/powerpc64-linux-gnu/bitcoin-db2b9123bba8-powerpc64-linux-gnu-debug.tar.gz
3fcae959ea5d21fe4224965578cae26f6027c40699f827daf34f65cc877623f2  guix-build-db2b9123bba8/output/powerpc64-linux-gnu/bitcoin-db2b9123bba8-powerpc64-linux-gnu.tar.gz
611f7b329bb03043ffd9d360df107b026b38b605db69a7c03d9bd2d2950f0b24  guix-build-db2b9123bba8/output/powerpc64le-linux-gnu/SHA256SUMS.part
dba36af32dd69bf5a0f0397fe397161ef011501d16f613606da5e795728efe53  guix-build-db2b9123bba8/output/powerpc64le-linux-gnu/bitcoin-db2b9123bba8-powerpc64le-linux-gnu-debug.tar.gz
ea68215c24acb24b5b723917140b0496da054eae3e25308b5ecad3fcfc0ce4f4  guix-build-db2b9123bba8/output/powerpc64le-linux-gnu/bitcoin-db2b9123bba8-powerpc64le-linux-gnu.tar.gz
53ecc1a3b2cafd0a515c27e284ca1b0623bbd79b9a2d7b3f12c60fb4bc99161a  guix-build-db2b9123bba8/output/riscv64-linux-gnu/SHA256SUMS.part
5c9f2979bb85bf897858cef3ca128d1166f594123c07c5abc9fe6a69ed18dfbf  guix-build-db2b9123bba8/output/riscv64-linux-gnu/bitcoin-db2b9123bba8-riscv64-linux-gnu-debug.tar.gz
95fb281e74c81fd01ef16426f216e8f59240481728c5bfc9c9bd9c2eb0dd870f  guix-build-db2b9123bba8/output/riscv64-linux-gnu/bitcoin-db2b9123bba8-riscv64-linux-gnu.tar.gz
6ea751f76e5c6eb95200728bb45c1f2d2eab54259e96899cf2b3582bd47f6124  guix-build-db2b9123bba8/output/x86_64-apple-darwin/SHA256SUMS.part
a8a5d1275f634824aea61925f05f81dff4138c909e89b94a9d432f51d13e3377  guix-build-db2b9123bba8/output/x86_64-apple-darwin/bitcoin-db2b9123bba8-osx-unsigned.dmg
63c99793e3f92da8f935571b0633abb273783667e7be834981da1c771f7a4036  guix-build-db2b9123bba8/output/x86_64-apple-darwin/bitcoin-db2b9123bba8-osx-unsigned.tar.gz
a13dae89eec4568eae3c275009bb61993b5ca28aa264d209c1f47f68ceda9b9d  guix-build-db2b9123bba8/output/x86_64-apple-darwin/bitcoin-db2b9123bba8-osx64.tar.gz
fc917f27708fcb014844445f54715b97a76aae4c202472768e08f84190a8a968  guix-build-db2b9123bba8/output/x86_64-linux-gnu/SHA256SUMS.part
e23b1c6bf6fef11490c8cbea5c8a4014519a6b9e39865e5c0ea70608231382bf  guix-build-db2b9123bba8/output/x86_64-linux-gnu/bitcoin-db2b9123bba8-x86_64-linux-gnu-debug.tar.gz
73cfb2c4f37b8040beb78289712cd752a751ef196fce878f7db27665fa85b426  guix-build-db2b9123bba8/output/x86_64-linux-gnu/bitcoin-db2b9123bba8-x86_64-linux-gnu.tar.gz
```

**Comment by hebasto** [comment]
@fanquake 
> Guix builds for all (working) HOSTS will be added to the PR description shortly.

It seems they lack a build for `aarch64-linux-gnu` arch.

**Comment by fanquake** [comment]
> It seems they lack a build for aarch64-linux-gnu arch.

Added.

File: build-aux/m4/l_filesystem.m4 [hunk 24]
```diff
@@ -0,0 +1,47 @@
+dnl Copyright (c) 2022 The Bitcoin Core developers
+dnl Distributed under the MIT software license, see the accompanying
+dnl file COPYING or http://www.opensource.org/licenses/mit-license.php.
+
+# GCC 9.1 and earlier requires -lstdc++fs
+# Clang 9.0 (libc++) and earlier requires -lc++fs
```
Comment (hebasto) [inline build-aux/m4/l_filesystem.m4:6]: def4c1704d27754398375880d9a0ba8f31a0464d

This comment makes me think that using `CXX='clang++-9 -stdlib=libc++'` ends with linking `-lc++fs`. That is not the case. Tested on tested on Linux Mint 20.2 (x86_64) with [clang-8](https://packages.ubuntu.com/focal/clang-8) and [clang-9](https://packages.ubuntu.com/focal/clang-9).

See https://releases.llvm.org/9.0.0/projects/libcxx/docs/UsingLibcxx.html#using-filesystem

Maybe
```suggestion
# Prior to LLVM 9.0, libc++ provides the implementation of the filesystem library in a separate static library,
# and using of <filesystem> requires to link -lc++fs.
```
or something similar with better wording?

Comment (hebasto) [reply build-aux/m4/l_filesystem.m4:6]: Similar concerns are about gcc comment above as according to https://gcc.gnu.org/gcc-9/changes.html gcc-9 does not require `-lstdc++fs`.

Comment (fanquake) [reply build-aux/m4/l_filesystem.m4:6]: I don't think we need to copy paste all of that in here. We can just change it to: 
```suggestion
# Clang 8.0 (libc++) and earlier requires -lc++fs
```

Comment (hebasto) [reply build-aux/m4/l_filesystem.m4:6]: Hmm, unexpected:
```
$ ./configure CC=gcc-8 CXX=g++-8
...
checking whether std::filesystem can be used without link library... yes
...
```

Comment (fanquake) [reply build-aux/m4/l_filesystem.m4]: Addressed both.

Comment (fanquake) [reply build-aux/m4/l_filesystem.m4]: > Hmm, unexpected:

If you've got other GCC's installed, it's likely not using version 8 of the standard library. Have a look at the verbose compiler output.

**Comment by laanwj** [comment]
Code review ACK 07269321f38e46e9e02f16d7cd135ea90692638d

> I've done this, as it seems everyone is in favour of keeping changes constrained to fs.* rather than using c_str() over the codebase.

Definitely.

**Comment by hebasto** [comment]
Tested 07269321f38e46e9e02f16d7cd135ea90692638d on macOS Catalina 10.15.7 (19H1713): being compiled with Homebrew's packages and run flawlessly.

**Comment by hebasto** [comment]
Tested 07269321f38e46e9e02f16d7cd135ea90692638d on Ubuntu Bionic 18.04.

The third commit b87f9c5edf3895df9650131fcf8551c3ad1d7301 compiled ok, but the last commit fails:
```
$ ./autogen.sh
$ ./configure --without-gui --without-bdb CC=gcc-8 CXX=g++-8
$ make clean
$ make
...
libbitcoin_util.a(libbitcoin_util_a-system.o): In function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
/usr/include/boost/system/error_code.hpp:686: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:689: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:701: undefined reference to `boost::system::generic_category()'
libbitcoin_util.a(libbitcoin_util_a-system.o): In function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
/usr/include/boost/system/error_code.hpp:656: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:659: undefined reference to `boost::system::generic_category()'
libbitcoin_util.a(libbitcoin_util_a-system.o):/usr/include/boost/system/error_code.hpp:206: more undefined references to `boost::system::generic_category()' follow
libbitcoin_util.a(libbitcoin_util_a-system.o): In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:210: undefined reference to `boost::system::system_category()'
libbitcoin_util.a(libbitcoin_util_a-system.o): In function `_GLOBAL__sub_I_BITCOIN_CONF_FILENAME':
/usr/include/boost/asio/error.hpp:230: undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
Makefile:5708: recipe for target 'bitcoind' failed
make[2]: *** [bitcoind] Error 1
...
```

**Comment by MarcoFalke** [comment]
Concept ACK 07269321f38e46e9e02f16d7cd135ea90692638d 🎀

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Concept ACK 07269321f38e46e9e02f16d7cd135ea90692638d 🎀
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgofAv+JlnSIf2qICI4sGlwHKVaOFpBXTij+BiUO/deMkVVE6l34iQxvziFRLLo
gxLGHEZuuvpT6Gg7WK0d/Fn0c3fHvywtF7DCiq299f/8I/Z7y8fKP3d7e2uL57I6
anIWW1QDr0FggeE/oR5Llz6pidZcSfvDDCff/8j1uMng9p/9RKapnNcJFT0ax0mv
nXkKa2axowGT8TkKGs80YPTpPXAPS7Q6sACta6JmRqcRG7ulWVjia5IANWC7aq/A
95HoLJdQ6X4khvQ6627k+vT0eSoPSL7i8dR2S10VBu+aNPFxRgMK2eEBzVLuQ3JN
sFWoW8M3g3dqENu1bsp7zHHmuwcxwn0PeNpKciEp54pooQBNBwWHGjOe5+5gsaar
klFxVV5XjeryXvlWcHjW0J1t7Sr5VCFs9MCsRZilOuyMS2i8FzAbpV6q2mxXue2Y
y6uT2VIbyNPpQwznoiQIiYgCfHRIYaRB4sUoyoAIsJmKDxA4TSoxt2XW23RYrQru
qz+ahi/U
=kXE8
-----END PGP SIGNATURE-----
```


</details>

**Comment by prusnak** [comment]
> Tested [0726932](https://github.com/bitcoin/bitcoin/commit/07269321f38e46e9e02f16d7cd135ea90692638d) on Ubuntu Bionic 18.04.

@hebasto Does this happen with clean checkout? Maybe `make clean` left some artefacts.

**Comment by hebasto** [comment]
> > Tested [0726932](https://github.com/bitcoin/bitcoin/commit/07269321f38e46e9e02f16d7cd135ea90692638d) on Ubuntu Bionic 18.04.
> 
> @hebasto Does this happen with clean checkout? Maybe `make clean` left some artefacts.

The same after `git clean -xdff`.

**Comment by MarcoFalke** [comment]
This only happens with system libs and not depends?

**Comment by hebasto** [comment]
> This only happens with system libs and not depends?

CI [builds](https://github.com/bitcoin/bitcoin/blob/master/ci/test/00_setup_env_native_qt5.sh) with depends, right?

**Comment by MarcoFalke** [comment]
Yes

File: src/test/util_tests.cpp [hunk 25]
```diff
@@ -70,9 +71,12 @@ BOOST_AUTO_TEST_CASE(util_datadir)
     args.ClearPathCache();
     BOOST_CHECK_EQUAL(dd_norm, args.GetDataDirBase());
 
+#ifndef WIN32
+    // Windows does not consider "datadir/.//" to be a valid directory path.
     args.ForceSetArg("-datadir", fs::PathToString(dd_norm) + "/.//");
     args.ClearPathCache();
     BOOST_CHECK_EQUAL(dd_norm, args.GetDataDirBase());
+#endif
```
Comment (ryanofsky) [inline src/test/util_tests.cpp:79]: In commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247)

The way this is written, it's confusing and vague about windows test behavior. Would change this to actually check windows behavior instead of skipping it, and also add more detail to the comment:

```c++
    args.ForceSetArg("-datadir", fs::PathToString(dd_norm) + "/.//");
    args.ClearPathCache();
#ifndef WIN32
    BOOST_CHECK_EQUAL(dd_norm, args.GetDataDirBase());
#else
    // Windows does not consider "datadir/.//" to be a valid directory path, so
    // the check to see if the directory exists returns false on windows, and
    // GetDataDirBase() returns nothing. When this test was originally written
    // GetDataDirBase() function stripped trailing "/" slashes, so the test was
    // the same on all platforms. But as of #20744, trailing slashes are no
    // longer stripped (because it would have complicated the GetDataDirBase
    // implementation), so the test is now platform-specific.
    BOOST_CHECK(args.GetDataDirBase().empty());
#endif
```

I think trying to clarify things here is worth it, because this test is already very confusing (every time I look at it my brain hurts), and most developers are not using windows, so problems that only happen on windows are especially painful to deal with.

(This is also closer to originally suggested fix from https://github.com/bitcoin/bitcoin/pull/20744#pullrequestreview-785640725)

Comment (MarcoFalke) [reply src/test/util_tests.cpp:79]: I think the goal was to not allow the unit test to do random crap to the root dir `/`, outside their assigned m_path_root

File: src/util/system.cpp [hunk 26]
```diff
@@ -243,7 +249,7 @@ namespace {
 fs::path StripRedundantLastElementsOfPath(const fs::path& path)
 {
     auto result = path;
-    while (fs::PathToString(result.filename()) == ".") {
+    while (result.filename().empty() || fs::PathToString(result.filename()) == ".") {
```
Comment (ryanofsky) [inline src/util/system.cpp:252]: In commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247)

Note: Just to explain this change, it's needed because `std path class, unlike boost path class treats paths with trailing slashes as having a final `""` component, instead of a final `"."` component.

This change was originally suggested https://github.com/bitcoin/bitcoin/pull/20744#discussion_r731839209, and a test program for this behavior is https://godbolt.org/z/voadYc8M1)

**Comment by kiminuo** [comment]
Compiled and run on Windows 11:

image

Seems to work fine 🎉

File: src/util/system.cpp [hunk 27]
```diff
@@ -415,7 +421,6 @@ const fs::path& ArgsManager::GetBlocksDirPath() const
     path /= fs::PathFromString(BaseParams().DataDir());
     path /= "blocks";
     fs::create_directories(path);
-    path = StripRedundantLastElementsOfPath(path);
```
Comment (ryanofsky) [inline src/util/system.cpp:418]: In commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247)

Note: Just to explain this change, this line is deleted because the `path` variable is set 2 lines above with literal "blocks" last element, so this line would never do anything, even before this PR. Earlier discussion was https://github.com/bitcoin/bitcoin/pull/20744#discussion_r731366070

**Comment by kiminuo** [comment]
@hebasto I tried to compile on Ubuntu 18.04.6 LTS with your [instructions](https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-1028979276) and I can see the same result.

File: src/util/system.cpp (hunk 26 above)
Comment (kiminuo) [reply src/util/system.cpp:252]: (Unfortunately, links like https://github.com/bitcoin/bitcoin/pull/20744#discussion_r731839209 do not work for me. There are probably too much comments in this PR or it's resolved. I don't know.)

**Comment by MarcoFalke** [comment]
I think this is ready for merge. Any developers (hopefully none) on Ubuntu Bionic can:

* Upgrade to a more recent Ubuntu
* Revert the last commit locally
* Build from depends
* Install a more recent boost


Merging now gives more time for testing in master and we still have about 3 weeks to decide how to fix the build on Ubuntu Bionic, with the easiest being a clean revert of the last commit.

Any other minor fixups (like in the tests) can also land in the next 3 weeks.

**Comment by hebasto** [comment]
#### Guix builds:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
c1f9b326f9be4140f00cebeae5ff8de428a2fb8ecced539fcc36c53f53bfecf4  guix-build-07269321f38e/output/aarch64-linux-gnu/SHA256SUMS.part
b44aca3bcf5ea92a3a6c48c24d6f85576f425f59b73528d4d00c20e950cf2128  guix-build-07269321f38e/output/aarch64-linux-gnu/bitcoin-07269321f38e-aarch64-linux-gnu-debug.tar.gz
27a5553f7bd14797293fc40c5fb131c91e98a61d5481a283f13a1d0497eb5ed8  guix-build-07269321f38e/output/aarch64-linux-gnu/bitcoin-07269321f38e-aarch64-linux-gnu.tar.gz
99e55a88823f6095864a09c9eaa824e24d9ec527380eb394f751c7205b930f69  guix-build-07269321f38e/output/arm-linux-gnueabihf/SHA256SUMS.part
b720b2724fa47fde584f58ed3b587f1d1183523540777fd367ab7e582605cfea  guix-build-07269321f38e/output/arm-linux-gnueabihf/bitcoin-07269321f38e-arm-linux-gnueabihf-debug.tar.gz
c19c247f4e9e0d7f888ac8ba9de1c12d382f48fa828a685d4fe02818a18abd1f  guix-build-07269321f38e/output/arm-linux-gnueabihf/bitcoin-07269321f38e-arm-linux-gnueabihf.tar.gz
55b49ccb38de03bb95101354a16fd8d2190abede5ccc0d9b00b40c0cd526a2f6  guix-build-07269321f38e/output/arm64-apple-darwin/SHA256SUMS.part
baa44752470a6be9acae1c2f8fd1b9bc37afb00971787ea11fbaeddc9ab7c4aa  guix-build-07269321f38e/output/arm64-apple-darwin/bitcoin-07269321f38e-arm64-apple-darwin.tar.gz
ad7df4d8026d5bcce1321cdccc2e1820e8a8bb7e1064ed16e20a7ea354057fd2  guix-build-07269321f38e/output/arm64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.dmg
f342066dc34a14d67c47779a2413a14633a996e8e7ddca89ae0184e23ef99efd  guix-build-07269321f38e/output/arm64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.tar.gz
f6905346a5d48f57805fb062d0247ab5007c89047070a0b3125941dd1a2b8aa6  guix-build-07269321f38e/output/dist-archive/bitcoin-07269321f38e.tar.gz
a1f6c4b2b118dbd89770801f0bcffd2218b82df408cd227e34c40493469bb7a2  guix-build-07269321f38e/output/powerpc64-linux-gnu/SHA256SUMS.part
ba8359426e523bf013d93579c1bedc57380214c8170a9743b64ec1a8a3bbccbf  guix-build-07269321f38e/output/powerpc64-linux-gnu/bitcoin-07269321f38e-powerpc64-linux-gnu-debug.tar.gz
b0bb500c274a683ea28ecbc1e8f18c618a9f8acb00045f80ae43c515288402c0  guix-build-07269321f38e/output/powerpc64-linux-gnu/bitcoin-07269321f38e-powerpc64-linux-gnu.tar.gz
38c85e9589e092cd3aa08996aa383c0ccd5c73208943389741355a6eb7f72537  guix-build-07269321f38e/output/powerpc64le-linux-gnu/SHA256SUMS.part
50fcba7942ff48d91e84c093fda0affc17e46167fe1d5137c6e14c5c41f289d1  guix-build-07269321f38e/output/powerpc64le-linux-gnu/bitcoin-07269321f38e-powerpc64le-linux-gnu-debug.tar.gz
fa08ef1ceca072e014faa95ffee945954b2976fa28f90926b87ab0e5f15f8ca5  guix-build-07269321f38e/output/powerpc64le-linux-gnu/bitcoin-07269321f38e-powerpc64le-linux-gnu.tar.gz
e52dd80a9c306d6aeb544acaa1f4ed560b6b92b5184764a05026d45451aa2e94  guix-build-07269321f38e/output/riscv64-linux-gnu/SHA256SUMS.part
864e0a16c485b4159cec3ee0a83b046f1b1c3bc821670011c5ac5cd09ddfb91f  guix-build-07269321f38e/output/riscv64-linux-gnu/bitcoin-07269321f38e-riscv64-linux-gnu-debug.tar.gz
4a061172181322e7ad0cf06405bf74f4c8683eaba3a67ecfd46158cba7627f62  guix-build-07269321f38e/output/riscv64-linux-gnu/bitcoin-07269321f38e-riscv64-linux-gnu.tar.gz
876d82251853205420dffe7237523fc6ee3d09f78bf74cc03dc71f548446f335  guix-build-07269321f38e/output/x86_64-apple-darwin/SHA256SUMS.part
3f82b2e62c60eee68e7b8fc28e4792e069e3c2cd780ee2d67290ca422cdbc47c  guix-build-07269321f38e/output/x86_64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.dmg
4ccdd4c410cac9d627e54ce83ee4816608681735da3cb93c60c5eb70ca86337a  guix-build-07269321f38e/output/x86_64-apple-darwin/bitcoin-07269321f38e-osx-unsigned.tar.gz
2179d36b2f60e28c15262d4e51f27465b5ae077f60e550345e125683ca611066  guix-build-07269321f38e/output/x86_64-apple-darwin/bitcoin-07269321f38e-osx64.tar.gz
b377e72fe84b6a982b8d414d60c85e6319523dff50dc852a0ba907f6d850ddd0  guix-build-07269321f38e/output/x86_64-linux-gnu/SHA256SUMS.part
8547e2f582ce05ae6a6224793b64efb2eb63f2816bf0bed5d53fcc4786274597  guix-build-07269321f38e/output/x86_64-linux-gnu/bitcoin-07269321f38e-x86_64-linux-gnu-debug.tar.gz
83b64805aa39f31a6fa4c2ed41e029c3be084e6dea06b90fac1ebca5c95bce29  guix-build-07269321f38e/output/x86_64-linux-gnu/bitcoin-07269321f38e-x86_64-linux-gnu.tar.gz
```

**Comment by hebasto** [comment]
ACK 07269321f38e46e9e02f16d7cd135ea90692638d

Agree with @MarcoFalke's [comment](https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-1029054642).

File: src/test/util_tests.cpp (hunk 25 above)
Comment (ryanofsky) [reply src/test/util_tests.cpp:79]: re: https://github.com/bitcoin/bitcoin/pull/20744#discussion_r798597671

> I think the goal was to not allow the unit test to do random crap to the root dir `/`, outside their assigned m_path_root

I don't think that's what's happening here. In any case:

- It is good to replace a vague comment with a specific comment.
- The point of the test is to ensure bitcoin has sane behavior if user uses extra trailing "./" characters in a custom datadir on linux. If we care about this behavior on linux, I don't think think we should say anything goes on windows and not check behavior there. Windows is a 30+ year old operating system with stable path semantics. If path semantics somehow do change, it is a good thing if the test fails, and the test has an understandable comment, we decide can what to do about it.

File: src/util/system.cpp (hunk 26 above)
Comment (ryanofsky) [reply src/util/system.cpp:252]: > (Unfortunately, links like [#20744 (comment)](https://github.com/bitcoin/bitcoin/pull/20744#discussion_r731839209) do not work for me. There are probably too much comments in this PR or it's resolved. I don't know.)

Github struggles with long discusions threads, and these links often they stop working and then start working again. They're the same link used in github notification emails so not special.

File: src/test/util_tests.cpp (hunk 25 above)
Comment (ryanofsky) [reply src/test/util_tests.cpp:79]: In commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247)

I think this change might be able to be reverted actually, because since this test was disabled a `StripRedundantLastElementsOfPath` call was added to `GetDataDir`. It looks like the call was added in the Dec 23 push https://github.com/bitcoin/bitcoin/pull/20744#event-5807965413 https://github.com/bitcoin/bitcoin/compare/f53be20eade794e55470473f03a8d05d57691c87..2c990b05fae7e1bfef2d3f59044c24274812c559#diff-19427b0dd1a791adc728c82e88f267751ba4f1c751e19262cac03cccd2822216R438 without an explanation

File: src/wallet/bdb.cpp [hunk 28]
```diff
@@ -620,12 +621,12 @@ bool BerkeleyDatabase::Backup(const std::string& strDest) const
                     pathDest /= fs::PathFromString(strFile);
 
                 try {
-                    if (fs::equivalent(pathSrc, pathDest)) {
+                    if (fs::exists(pathDest) && fs::equivalent(pathSrc, pathDest)) {
```
Comment (ryanofsky) [inline src/wallet/bdb.cpp:624]: In commit "build: remove boost::filesystem usage" (b87f9c5edf3895df9650131fcf8551c3ad1d7301)

Note: this change was needed because fs::equivalent was throwing an exception if the path didn't exist. Earlier discussion was https://github.com/bitcoin/bitcoin/pull/20744#issuecomment-765467226

File: src/wallet/load.cpp [hunk 29]
```diff
@@ -27,9 +29,9 @@ bool VerifyWallets(WalletContext& context)
 
     if (args.IsArgSet("-walletdir")) {
         fs::path wallet_dir = fs::PathFromString(args.GetArg("-walletdir", ""));
-        boost::system::error_code error;
+        std::error_code error;
         // The canonical path cleans the path, preventing >1 Berkeley environment instances for the same directory
-        fs::path canonical_wallet_dir = fs::canonical(wallet_dir, error).remove_trailing_separator();
+        fs::path canonical_wallet_dir = fs::canonical(wallet_dir, error);
```
Comment (ryanofsky) [inline src/wallet/load.cpp:34]: In commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247)

Note: std canonical function already strips trailing slashes, so this should not be a change in behavior

File: src/wallet/test/init_tests.cpp [hunk 30]
```diff
@@ -73,6 +73,8 @@ BOOST_AUTO_TEST_CASE(walletinit_verify_walletdir_no_trailing)
     BOOST_CHECK_EQUAL(walletdir, expected_path);
 }
 
+#ifndef WIN32
+// Windows does not consider "datadir/wallets//" to be a valid directory path.
```
Comment (ryanofsky) [inline src/wallet/test/init_tests.cpp:77]: In commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247)

What's the behavior if you use this path on windows? I don't think we want bitcoins's behavior undefined and untested in this case. It would be better for users and also clearer in the test code to check what the resulting behavior is on windows and decide if it is good or bad.

Or best thing might be to add a StripRedundantLastElementsOfPath call in the `-walletdir=` parsing code like the one that was added to GetDataDir in this PR, so this test could go back to be enabled and working the same across platforms.

**Review by ryanofsky — COMMENTED** [review]
Partial code review ACK for commit "refactor: replace boost::filesystem with std::filesystem" (41d7166c8a598b604aad6c6b1d88ad46e23be247). I looked at this commit in detail, just not the other commits.

Overall I think this is good, but there is some dodginess going on with trailing / characters in paths, that is showing up in comments here about tests on windows, but could indicate unintended changes in behavior that cause bugs on other platforms. Windows complains more about extra `/` characters in paths but that doesn't mean extra `/` characters don't break things on other platforms, too. For example if there are string comparisons that no longer return true because of extra slashes.

File: src/wallet/test/init_tests.cpp (hunk 30 above)
Comment (MarcoFalke) [reply src/wallet/test/init_tests.cpp:77]: I was assuming that this modifies `gArgs`, but given that the args is local, it should be fine, assuming that the argsmanager doesn't write to disk by itself.

**Comment by hebasto** [comment]
> Tested [0726932](https://github.com/bitcoin/bitcoin/commit/07269321f38e46e9e02f16d7cd135ea90692638d) on Ubuntu Bionic 18.04.
> 
> The third commit [b87f9c5](https://github.com/bitcoin/bitcoin/commit/b87f9c5edf3895df9650131fcf8551c3ad1d7301) compiles ok, but the last commit fails:

Fixed in #24254.
