### PR TITLE
net: fixes #20657 - Advertised address where nobody is listening

### LINKED ISSUE #20657: Advertised address where nobody is listening
Bug reported by @vasild here: (https://github.com/bitcoin-core/gui/pull/86#issuecomment-717789400)

`listen=0` will cause us not to listen on any port, so we would not accept any incoming connections, regardless of whether clearnet or Tor.

> $ bitcoind
...
2020-10-28T08:41:57Z Config file arg: listen="0"
2020-10-28T08:41:57Z Config file arg: listenonion="1"
2020-10-28T08:41:57Z Config file arg: rpcport="8332"
...
2020-10-28T08:42:19Z tor: Got service ID foo, advertising service foo.onion:8333
2020-10-28T08:42:19Z AddLocal(foo.onion:8333,4)

>$ netstat
tcp4       0      0 127.0.0.1.8332         *.*                    LISTEN     
(bitcoind is only listening on the RPC port)

> I guess this can be considered as a bug because it will (I guess) advertise `foo.onion:8333` where nobody is listening.

### PR DESCRIPTION
**Pull request by jadijadi**
If the bitcoind starts when listen=0 but listenonion=1, the daemon will
advertise its onion address but nothing is listening for it.

This update will enforce listenonion=0 when the listen is 0.

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -508,6 +508,7 @@ void SetupServerArgs(NodeContext& node)
     argsman.AddArg("-checkmempool=<n>", strprintf("Run checks every <n> transactions (default: %u, regtest: %u)", defaultChainParams->DefaultConsistencyChecks(), regtestChainParams->DefaultConsistencyChecks()), ArgsManager::ALLOW_ANY | ArgsManager::DEBUG_ONLY, OptionsCategory::DEBUG_TEST);
     argsman.AddArg("-checkpoints", strprintf("Enable rejection of any forks from the known historical chain until block %s (default: %u)", defaultChainParams->Checkpoints().GetHeight(), DEFAULT_CHECKPOINTS_ENABLED), ArgsManager::ALLOW_ANY | ArgsManager::DEBUG_ONLY, OptionsCategory::DEBUG_TEST);
     argsman.AddArg("-deprecatedrpc=<method>", "Allows deprecated RPC method(s) to be used", ArgsManager::ALLOW_ANY | ArgsManager::DEBUG_ONLY, OptionsCategory::DEBUG_TEST);
+    argsman.AddArg("-dropmessagestest=<n>", "Randomly drop 1 of every <n> network messages", ArgsManager::ALLOW_ANY | ArgsManager::DEBUG_ONLY, OptionsCategory::DEBUG_TEST);
```
Comment (prusnak) [inline src/init.cpp:511]: This line does not look like it belongs to this PR

Comment (jadijadi) [reply src/init.cpp:511]: no. what is this? my mistake on copy paste from another check. sorry.

Comment (jadijadi) [reply src/init.cpp]: removed this line

**Comment by amitiuttarwar** [comment]
hi @jadijadi, welcome to the project! 

if a PR gets merged, the commits get preserved in the history on master. here, it looks like the first commit introduces an extraneous change that gets removed in the second commit. please squash them so there are just relevant changes.

**Comment by jadijadi** [comment]
> hi @jadijadi, welcome to the project!
> 
> if a PR gets merged, the commits get preserved in the history on master. here, it looks like the first commit introduces an extraneous change that gets removed in the second commit. please squash them so there are just relevant changes.

Thanks @amitiuttarwar for the welcome, help and being this patient with newcomers :) squashed them into one.

**Comment by Rspigler** [comment]
Concept ACK.

This would fix https://github.com/bitcoin/bitcoin/issues/20657

File: src/init.cpp [hunk 2]
```diff
@@ -827,8 +827,10 @@ void InitParameterInteraction(ArgsManager& args)
             LogPrintf("%s: parameter interaction: -listen=0 -> setting -upnp=0\n", __func__);
         if (args.SoftSetBoolArg("-discover", false))
             LogPrintf("%s: parameter interaction: -listen=0 -> setting -discover=0\n", __func__);
-        if (args.SoftSetBoolArg("-listenonion", false))
+        if (args.GetBoolArg("-listenonion", DEFAULT_LISTEN_ONION)) {
+            args.ForceSetArg("-listenonion", std::string("0"));
             LogPrintf("%s: parameter interaction: -listen=0 -> setting -listenonion=0\n", __func__);
+        }
     }
```
Comment (vasild) [inline src/init.cpp:835]: nit on the commit message: I think it is more common to put "fixes #20657" at the bottom of the commit message on a line of its own, rather than inside the first line. But feel free to ignore this.

File: src/init.cpp [hunk 3]
```diff
@@ -827,8 +827,10 @@ void InitParameterInteraction(ArgsManager& args)
             LogPrintf("%s: parameter interaction: -listen=0 -> setting -upnp=0\n", __func__);
         if (args.SoftSetBoolArg("-discover", false))
             LogPrintf("%s: parameter interaction: -listen=0 -> setting -discover=0\n", __func__);
-        if (args.SoftSetBoolArg("-listenonion", false))
+        if (args.GetBoolArg("-listenonion", DEFAULT_LISTEN_ONION)) {
+            args.ForceSetArg("-listenonion", std::string("0"));
```
[the remark this answers is not in the document]
Comment (Rspigler) [reply src/init.cpp:831]: I think refusing to start (with an error message?) over changing what the user has set is better

[the remark this answers is not in the document]
Comment (jadijadi) [reply src/init.cpp:831]: Agree with you guys. Will update the PR to refuse the start instead of changing the explicitly set parameter.

[the remark this answers is not in the document]
Comment (jadijadi) [reply src/init.cpp]: > I think refusing to start (with an error message?) over changing what the user has set is better

I've sent a new PR with this behavior. Refusing to start looks more UNIXish.

[the remark this answers is not in the document]
Comment (jadijadi) [reply src/init.cpp]: > The rest of `InitParameterInteraction()` uses `SoftSetBoolArg()` which I guess is to avoid overriding a value that has been explicitly set by the user. `InitParameterInteraction()` only flips defaults. I think this behavior is sensible as it minimizes the user's surprise.
> 
> There is some [other code](https://github.com/bitcoin/bitcoin/blob/ddbf7a6f5051b6d7faed54828445d6eaadcd8441/src/init.cpp#L1011-L1024) which refuses to start the application if incompatible options are given - for example `-prune=1 -txindex=1` or `-bind=addr:port -listen=0`.
> 
> Given the above, what about refusing to start if `-listen=0 -listenonion=1` is explicitly given?

Thanks for the idea. I've updated the PR with this behavior.

**Comment by jadijadi** [comment]
> Concept ACK.
> 
> This would fix #20657

Thanks for initial ACK. but based on the comment from @vasild I updated the PR for a more UNIXish behavior: refusing to start with incompatible inputs.

**Review by luke-jr — CHANGES_REQUESTED** [review]
Concept ACK, but this needs changes to `InitParameterInteraction` to handle `-connect` and `-proxy` cleanly (perhaps if `-listenonion` is explicitly set true, soft-set `-listen` true also, as with `-bind` at the top?).

**Comment by jadijadi** [comment]
> Concept ACK, but this needs changes to `InitParameterInteraction` to handle `-connect` and `-proxy` cleanly (perhaps if `-listenonion` is explicitly set true, soft-set `-listen` true also, as with `-bind` at the top?).

Thanks @luke-jr  for the ACK and suggestion. In the initial PR, I was doing this in InitParameterInteraction as you said. But after above discussions, others suggested to do it here and preventing the system from start if the user explicitly set listenionion=1 and listen=0. In all other cases, the system handles the situation properly since the DEFAULT_LISTEN is 1 and DEFAULT_LISTEN_ONION is also 1.

**Review by felipsoarez — COMMENTED** [review]
Concept ACK
I have not tested the code, but I have reviewed it and it looks OK, I agree it can be merged

**Comment by vasild** [comment]
b743feca5bcbdf95ac4993c7b371d05ef1324d99 looks good. The commit message and PR description need to be updated because they refer to the previous incarnation of this PR where it enforced `listenonion=0`.

It works as expected:

```
$ bitcoind -listen=0
InitParameterInteraction: parameter interaction: -listen=0 -> setting -listenonion=0

$ bitcoind -listen=0 -listenonion=1
Error: Cannot set -listen=0 together with -listenonion=1
```

@luke-jr 
> this needs changes to InitParameterInteraction to handle -connect and -proxy cleanly (perhaps if -listenonion is explicitly set true, soft-set -listen true also, as with -bind at the top?).

I am not sure I understand. `-listen` is `true` by default, so if only `bitcoind -listenonion=1` is given, then soft-set `-listen` to `true` would be a noop?

**Review by jarolrod — COMMENTED** [review]
ACK b743feca5bcbdf95ac4993c7b371d05ef1324d99, Tested on macOS 11.2

Confirming the bug referenced here on master. This PR creates an `InitParameterInteraction` to set `listenonion=0` when `listen=0`. This functionality works as intended in my testing.

**Setting `listen=0`**
```
2021-03-04T04:46:56Z InitParameterInteraction: parameter interaction: -listen=0 -> setting -listenonion=0
```

**Attempting to set both `listen` and `listenonion`**
```
Error: Cannot set -listen=0 together with -listenonion=1
```

@jadijadi as others have stated you may want to fix the commit message, how about this as a suggestion for the title:
```
net: do not advertise address where nobody is listening
```

File: src/init.cpp (hunk 2 above)
Comment (jadijadi) [reply src/init.cpp]: moved it to the bottom. thanks for the hint

**Comment by jadijadi** [comment]
> ACK [b743fec](https://github.com/bitcoin/bitcoin/commit/b743feca5bcbdf95ac4993c7b371d05ef1324d99), Tested on macOS 11.2
> 
> ...
> ```
> net: do not advertise address where nobody is listening
> ```

Thanks for the hints. I've updated the PR with the suggested commit message

**Review by vasild — APPROVED** [review]
ACK a38137479bf5e25bf65a62e46b81fc43fb3df75c

**Review by jarolrod — COMMENTED** [review]
ACK a38137479bf5e25bf65a62e46b81fc43fb3df75c

**Comment by prayank23** [comment]
Compiled successfully for Windows using the instructions mentioned here: https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md

1 test failed and this is what I see in logs: 

image

**Review by amitiuttarwar — COMMENTED** [review]
ACK a38137479bf5e25bf65a62e46b81fc43fb3df75c

with several thoughts & questions for further improvements:
- the init params are hard to keep track of & dependent on ordering, so it would be good to add a regression test. @jadijadi - I have a draft here (https://github.com/amitiuttarwar/bitcoin/commit/ec622d153d777bf556ac8f2d74a353bd8f324294) if you'd like to include in this PR or add as a follow-up.
- `-listen` has a lot of parameter interactions, I'm wondering if any other conflicts should similarly cause a failure-to-start instead of quietly failing, eg `-discover`, `i2pacceptincoming`... (cc @vasild if you have more insight into some of these params)
- also would be cool to add test coverage to make explicit the other parameter interactions. for example, this change also disallows setting `-connect=1.1.1.1` with `-listenonion=1`. that seems reasonable but would be nice to capture these sorts of complexities.

**Comment by vasild** [comment]
>     * I'm wondering if any other conflicts should similarly cause a failure-to-start instead of quietly failing, eg `-discover`, `i2pacceptincoming`

If `-listen=0` is given and `-i2pacceptincoming=...` is not given, then the default of the latter is flipped from `1` to `0`. If both are explicitly set: `-listen=0 -i2pacceptincoming=1` then it works as instructed - no binding/listening on local address:port of the machine, but accept incoming I2P connections (they do not need binding/listening, so we don't have a bug like the one with Tor which the current PR aims to resolve).

Is `-listen=0 -i2pacceptincoming=1` contradictory? Maybe, to some extent, it can be perceived as such. Should we abort startup if that is given? Maybe, I am not sure. (but if yes, then that is out of the scope of this PR).

> this change also disallows setting `-connect=1.1.1.1` with `-listenonion=1`

Right. That can be worked around with `-connect=1.1.1.1 -listen=1 -listenonion=1`.

**Comment by hebasto** [comment]
It seems this PR introduced a bug in the GUI: bitcoin-core/gui#567.
