### PR TITLE
ci: Add CentOS 7 build

### LINKED ISSUE #17628: Criteria to drop Trusty Travis
@emilengler attempted removing the Trusty Travis build in #16930, but this was considered premature. Currently this Travis machine is broken (#17626), hopefully temporarily. It seems useful to have a list of criteria ready for when it can safely be dropped:

As @MarcoFalke pointed out:
> This is still used to ensure we can build with the minimum required qt and boost versions

Minimum versions are defined here: https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md

Our minimum QT version is 5.5.1. Trusty ships with 5.2.1, Xenial ships with 5.5.1. So we don't need Trusty for QT.

Our minimum Boost version is 1.47.0. Trusty ships with 1.54 and Xenial ships with 1.58, so neither covers the oldest version. Discussion about the mimimum required boost version is in #8875. We shouldn't drop Trusty until we bump the minimum version to 1.58.

I did not look at other dependencies.

### PR DESCRIPTION
**Pull request by hebasto**
Arguably, CentOS is the most conservative distro of all the popular ones. Thus, it could be a good way to check the Bitcoin Core compatibility with aged dependencies.

Currently, CentOS 7 has:
- Berkeley DB == 4.8.30
- Boost == 1.53.0
- GCC == 4.8.5
- libevent == 2.0.21 < minimum required [2.0.22](https://github.com/bitcoin/bitcoin/blob/master/doc/dependencies.md), but tests passed
- MiniUPnPc == 2.0
- Python == 3.6.8
- qrencode == 3.4.1
- Qt == 5.9.7
- ZeroMQ == 4.1.4

~Please note that this PR is based on the bugfix #17634.~

Also trusty build has been removed for the following reasons:
- https://github.com/bitcoin/bitcoin/issues/17628#issuecomment-559448201:
> Maybe it'd make sense to replace Ubuntu Trusty with Centos 7 as the "check ancient backward compatibililty" Travis run. It's supported until 2024, apparently.

- https://github.com/bitcoin/bitcoin/pull/17635#discussion_r354811792:
> Our travis is currently running at its limit and this doesn't seem like it is adding a lot new coverage compared to the other builds. 

Close #17628

### CODE REVIEW

**Comment by hebasto** [comment]
@laanwj's https://github.com/bitcoin/bitcoin/issues/17628#issuecomment-559448201:
> Maybe it'd make sense to replace Ubuntu Trusty with Centos 7 as the "check ancient backward compatibililty" Travis run. It's supported until 2024, apparently.

**Comment by practicalswift** [comment]
Concept ACK: diversity in testing is good

File: src/qt/recentrequeststablemodel.cpp [hunk 1]
```diff
@@ -214,10 +213,10 @@ void RecentRequestsTableModel::updateDisplayUnit()
     updateAmountColumnTitle();
 }
 
-bool RecentRequestEntryLessThan::operator()(RecentRequestEntry &left, RecentRequestEntry &right) const
+bool RecentRequestEntryLessThan::operator()(const RecentRequestEntry& left, const RecentRequestEntry& right) const
```
Comment (paymog) [inline src/qt/recentrequeststablemodel.cpp]: are these changes required for the centos build to pass?

File: src/qt/peertablemodel.cpp [hunk 2]
```diff
@@ -10,7 +10,7 @@
 
 #include <interfaces/node.h>
 
-#include <algorithm>
+#include <utility>
```
Comment (paymog) [inline src/qt/peertablemodel.cpp]: why the switch from `algorithm` to `utility`?

**Review by paymog — COMMENTED** [review]
I'm new to the bitcoin codebase but this generally LGTM.

File: src/qt/recentrequeststablemodel.cpp (hunk 1 above)
Comment (hebasto) [reply src/qt/recentrequeststablemodel.cpp]: Please look #17634.

File: src/qt/peertablemodel.cpp (hunk 2 above)
Comment (hebasto) [reply src/qt/peertablemodel.cpp]: Please look #17634.

File: src/qt/recentrequeststablemodel.cpp (hunk 1 above)
Comment (paymog) [reply src/qt/recentrequeststablemodel.cpp]: Ah got it. I'm still new to how bitcoin is developed but I think it would be useful if this PR didn't try to merge to master but instead tried to merge into #17634 so that the changes from the PR don't appear here (but that's just a stylistic nit).

Comment (hebasto) [reply src/qt/recentrequeststablemodel.cpp]: From OP:
> Please note that this PR is based on the bugfix #17634.

When/if #17634 is merged this PR will be rebased and commits from #17634 will not appear here.

**Comment by fanquake** [comment]
Concept ACK

**Comment by hebasto** [comment]
Rebased after #17634 has been merged.

File: .travis.yml [hunk 3]
```diff
@@ -118,6 +118,11 @@ jobs:
       env: >-
         FILE_ENV="./ci/test/00_setup_env_i686.sh"
 
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [CentOS 7]  [no depends, only system libs]'
+      env: >-
+        FILE_ENV="./ci/test/00_setup_env_centos.sh"
```
Comment (MarcoFalke) [inline .travis.yml]: nit: This should run on any architecture 

```suggestion
        FILE_ENV="./ci/test/00_setup_env_native_centos.sh"
```

**Review by maflcko — APPROVED** [review]

File: .travis.yml (hunk 3 above)
Comment (hebasto) [reply .travis.yml]: Done.

**Comment by laanwj** [comment]
I think you should do a depends build here.

While the binary must run on CentOS 7 (this was a constraint on the libc version in #17538), it doesn't need to build with the ancient library versions provided there: CentOS 7 does not put a restriction on our minimum dependency versions.

**Comment by laanwj** [comment]
This also implicitly restricts the minimum supported g++ version to 4.8.5, complicating #16684 in the future. But I think we can worry about that then (maybe there's a way to install a newer compiler).

**Comment by hebasto** [comment]
> I think you should do a depends build here.

I have encountered a `libevent` build error on Travis (the local build is ok). Going to debug...

**Comment by MarcoFalke** [comment]
But then, what is the point of using CentOs 7 to get all the old packages (of boost, etc) when a depends build is done anyway?

**Comment by laanwj** [comment]
I don't know. Some of the package versions make sense, for Qt even recent (5.9.7 is from last year), but In the case of libevent the version is absurdly old.

**Comment by MarcoFalke** [comment]
We mostly had issues with compiling against older versions of boost (and qt). If the trusty run is eventually removed, we should have something else to run against an old version of boost.

**Comment by laanwj** [comment]
yes, the boost version is OK; and I don't think we can do a depends build without boost at this point

aj on IRC commented something about "software collections", could this be used to install a newer version of libevent only?

**Comment by hebasto** [comment]
> aj on IRC commented something about "software collections", could this be used to install a newer version of libevent only?

https://www.softwarecollections.org/en/scls/?search=libevent

... nothing.

**Comment by MarcoFalke** [comment]
ACK d88782e3fc897cf1fe63eaa2255ac93fb222f711

**Comment by MarcoFalke** [comment]
A nice follow up (either a new commit or pr) would be to adjust the readme and the list of packages to only the needed ones: `boost-thread boost-test boost-filesystem boost-chrono` instead of the entirety of boost.

**Comment by hebasto** [comment]
> A nice follow up (either a new commit or pr) would be to adjust the readme and the list of packages to only the needed ones: `boost-thread boost-test boost-filesystem boost-chrono` instead of the entirety of boost.

CentOS / Fedora has only one `boost-devel` package.
There is no `boost-{thread|test|filesystem|chrono}-devel` packages, unfortunately.

**Comment by promag** [comment]
ACK d88782e3fc897cf1fe63eaa2255ac93fb222f711.

File: .travis.yml [hunk 4]
```diff
@@ -118,6 +118,11 @@ jobs:
       env: >-
         FILE_ENV="./ci/test/00_setup_env_i686.sh"
 
+    - stage: test
+      name: 'x86_64 Linux  [GOAL: install]  [CentOS 7]  [no depends, only system libs]'
+      env: >-
+        FILE_ENV="./ci/test/00_setup_env_native_centos.sh"
```
Comment (MarcoFalke) [inline .travis.yml]: Our travis is currently running at its limit and this doesn't seem like it is adding a lot new coverage compared to the other builds. What about only running it in cirrus instead of travis?

Comment (hebasto) [reply .travis.yml]: Could CentOS build be a replacement for Trusty build on Travis?

Comment (MarcoFalke) [reply .travis.yml]: Sounds good

File: ci/test/00_setup_env_native_centos.sh [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+#
+# Copyright (c) 2019 The Bitcoin Core developers
+# Distributed under the MIT software license, see the accompanying
+# file COPYING or http://www.opensource.org/licenses/mit-license.php.
+
+export LC_ALL=C.UTF-8
+
+export DOCKER_NAME_TAG=centos:7
+export DOCKER_PACKAGES="gcc-c++ libtool make git python3"
+export PACKAGES="boost-devel libevent-devel libdb4-devel libdb4-cxx-devel miniupnpc-devel zeromq-devel qt5-qtbase-devel qt5-qttools-devel qrencode-devel"
```
Comment (MarcoFalke) [inline ci/test/00_setup_env_native_centos.sh]: Please install python3-zmq, if available. See https://travis-ci.org/bitcoin/bitcoin/jobs/619963005#L3914

File: .travis.yml (hunk 4 above)
Comment (hebasto) [reply .travis.yml]: Should Trusty build be removed from Travis in this PR?

Comment (MarcoFalke) [reply .travis.yml]: Yeah, I think this has been the plan: https://github.com/bitcoin/bitcoin/issues/17628#issuecomment-559448201

File: ci/test/00_setup_env_native_centos.sh (hunk 5 above)
Comment (hebasto) [reply ci/test/00_setup_env_native_centos.sh]: Done.

Comment (MarcoFalke) [reply ci/test/00_setup_env_native_centos.sh]: And https://apps.fedoraproject.org/packages/python3-zmq

File: .travis.yml (hunk 4 above)
Comment (hebasto) [reply .travis.yml]: @emilengler's 5423bd3474581a479b244cb9b599cbefafc64618 has been cherry-picked.

File: ci/test/00_setup_env_native_centos.sh (hunk 5 above)
Comment (hebasto) [reply ci/test/00_setup_env_native_centos.sh]: https://centos.pkgs.org/7/epel-x86_64/python36-zmq-14.7.0-8.el7.x86_64.rpm.html

Comment (MarcoFalke) [reply ci/test/00_setup_env_native_centos.sh]: Ah, please add it then.

Comment (hebasto) [reply ci/test/00_setup_env_native_centos.sh]: Already:

https://github.com/bitcoin/bitcoin/blob/7f3ae224685efaeb6fe714de90e8871d12e55f34/ci/test/00_setup_env_native_centos.sh#L10

Comment (hebasto) [reply ci/test/00_setup_env_native_centos.sh]: https://travis-ci.org/bitcoin/bitcoin/jobs/621765674

**Comment by MarcoFalke** [comment]
ACK 711e0449cf4a0f15cabe0d64094e3add24ad44b0 🚠

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 711e0449cf4a0f15cabe0d64094e3add24ad44b0 🚠
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgl0gv/fWA9rxwx5f/Yr178u4iXUkmIRtbazRKORuGeAEPzOoWCG1hpOWMMUaX+
UUqNn9hEPu5J9lLfZdPItdVLyjKRTFu6Ch2iLmRstrn9Nev6q3wwKNnY6vjNVNdd
KZAJVnA11eEGIcfhhMlTCy7+E4IQB+mI8/+HL/KmHnckhaVfTLBp5ZEt0MUJf/GT
8lQ+/qjr0uUd6dCt6TsqpEitdbA5F8TTGENT9z49AnlDNdFgFjnoI4NMALvwftnw
r+aqwBprafaKyJrl1zcnr1e+2O33kD884+NAINfoVHMQ6VKKQyg9mTqa1yzrLoQu
9qkk1qwxaxL1+XHbux1gyRXQc8J7SnBy7qZg2tOpB1QshaC9CYgukIX540uEFJab
xVitKe0MZLnwIbTx8CATN90bm+/EcmiCmJHunPPWv8A4oJKwPDlIeqIFT4UsfzWy
bDWM4UW3U/0PS+guH1Y8gNIPCUd+J1ECuaHjFbYjeBrnbvK1Wz0sZX8vBE2HfpPN
4gDSSFSh
=UKBg
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `6113c2488002e62c4f29f31002293d1c4fcd8b73206b423cb8ff1244d50cc142  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401086113c2488002e62c4f29f31002293d1c4fcd8b73206b423cb8ff1244d50cc142f0109347bc4e1a2ff197f20410bb15b016e108fff010ae36b64c4595706021eb9aa2a43b264508f1045deb2b36f008fc9aaf38790e84370083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010f77a3d68e63ccf73f37efe2d0ad1ce5108f1045deb2b36f008e1900926dbb25d460083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d)

</details>

**Comment by elichai** [comment]
ACK After merge. I actually think this can *help* us more confidently bump the C++ version in the future (probably will require bumping to CentOS 8)
