### PR TITLE
[QT] fix OSX dock icon window reopening

### LINKED ISSUE #5878: Closed window doesn't show when clicking dock icon
I am using Bitcoin Core version v0.10.0 on OS X Yosemite 10.10.2. If I click the red close button on the window, it disappears as I would expect. But if I click the icon in the dock, the window does not show. I do not remember seeing this behavior in v0.9.

### PR DESCRIPTION
**Pull request by jonasschnelli**
fixes #5878.
Tested on OSX 10.10.

Needs testing on OSX 10.7 till 10.9.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Binaries to test: https://builds.jonasschnelli.ch/pulls/5880/

**Comment by jonasschnelli** [comment]
Tested https://builds.jonasschnelli.ch/pulls/5880/bitcoin-0.10.99-osx-unsigned.dmg on 10.7 and 10.9.
Works fine there.
Assume 10.8 will also work.

File: src/qt/macdockiconhandler.mm [hunk 1]
```diff
@@ -11,52 +11,46 @@
...
 
-@interface DockIconClickEventHandler : NSObject
-{
-    MacDockIconHandler* dockIconHandler;
-}
-
-@end
-
-@implementation DockIconClickEventHandler
+static MacDockIconHandler *s_instance = NULL;
```
Comment (laanwj) [inline src/qt/macdockiconhandler.mm]: Does s_instance ever get freed?

Comment (jonasschnelli) [inline src/qt/macdockiconhandler.mm]: No. It's a singleton pattern and i assume the OS will care about the cleanup.
But i could try to proactive free it within the destructor of `~MacDockIconHandler`. But this might be more or less the same cleanup as the os does.

**Comment by fanquake** [comment]
Tested ACK

File: src/qt/macdockiconhandler.mm (hunk 1 above)
Comment (laanwj) [inline src/qt/macdockiconhandler.mm]: I'd prefer if it was freed. Otherwise it will show up as a memory leak. Would be even better to do it without introducing a singleton, but I suppose that isn't possible.

**Comment by laanwj** [comment]
@fanquake on what version of OSX?

**Comment by fanquake** [comment]
@laanwj 10.9 & 10.10

**Comment by jonasschnelli** [comment]
Updated with @laanwj nits (mem cleanup).
Also removed unused code.
@fanquake mind retesting.
Binaries: https://builds.jonasschnelli.ch/pulls/5880/

**Comment by jonasschnelli** [comment]
Retested on 10.7 and 10.9. Works fine there.

**Comment by fanquake** [comment]
ReACK Checked 10.9 & 10.10

**Comment by laanwj** [comment]
Cherry-picked to 0.10 as 81145a6 and 2c08406
