### PR TITLE
mining: bugfix: Fix duplicate coinbase tx weight reservation

### LINKED ISSUE #21950: Duplicate coinbase transaction space reservation in CreateNewBlock
In `BlockAssembler::CreateNewBlock`, we initiate `nBlockWeight` to 4000 WU, reserving space for
coinbase transaction.

Latter on, while iterating on transactions for block inclusion in `addPackagesTxs`, we verify that candidate package doesn't overflow the max block weight. This check is done in `TestPackage` against `nBlockMaxWeight`. However, default value is DEFAULT_BLOCK_MAX_WEIGHT which is equal to MAX_BLOCK_WEIGHT - 4000 (L20 in `src/policy/policy.cpp`). So block weight assembled is starting at 4000 WU and can't overflow 3996000 WU.

Do we have duplicated coinbase transaction space reservation ? I can see this a safety margin to avoid creating invalid blocks if you create inflated coinbase transaction, at the price of few weight units leftover.

If so, maybe we should leave it as it is but document this behavior, I was surprised hitting this while scratching unrelated tests.

See [comment](https://github.com/bitcoin/bitcoin/pull/11100#discussion_r135124178) in #11100

### PR DESCRIPTION
**Pull request by ismaelsadeeq**
* This PR attempts to fix the duplicate coinbase weight reservation issue we currently have.
* Fixes #21950

We reserve 4000 weight units for coinbase transaction in `DEFAULT_BLOCK_MAX_WEIGHT`

https://github.com/bitcoin/bitcoin/blob/7590e93bc73b3bbac641f05d490fd5c984156b33/src/policy/policy.h#L23

And also reserve additional `4000` weight units in the default `BlockCreationOptions` struct.

https://github.com/bitcoin/bitcoin/blob/7590e93bc73b3bbac641f05d490fd5c984156b33/src/node/types.h#L36-L40

**Motivation**

- This issue was first noticed during a review here https://github.com/bitcoin/bitcoin/pull/11100#discussion_r136157411)
- It was later reported in issue #21950.
- I also came across the bug while writing a test for building the block template. I could not create a block template above `3,992,000` in the block assembler, and this was not documented anywhere. It took me a while to realize that we were reserving space for the coinbase transaction weight twice.

---
This PR fixes this by consolidating the reservation to be in a single location in the codebase.

This PR then adds a new startup option `-blockreservedweight` whose default is `8000` that can be used to lower or increase the block reserved weight for block header, txs count, coinbase tx.

### CODE REVIEW

File: src/node/types.h [hunk 1]
```diff
@@ -37,7 +37,7 @@ struct BlockCreateOptions {
      * scriptSig, witness and outputs. This must include any additional
      * weight needed for larger CompactSize encoded lengths.
      */
-    size_t coinbase_max_additional_weight{4000};
+    size_t coinbase_max_additional_weight{0};
```
Comment (Sjors) [inline src/node/types.h:40]: I don't think setting `coinbase_max_additional_weight` to `0` is the right approach. 

I'll comment on #21950 first.

**Comment by Sjors** [comment]
I'm in favor of fixing this bug, but differently, see https://github.com/bitcoin/bitcoin/issues/21950#issuecomment-2507864614

**Comment by Sjors** [comment]
Something like this should do:

```diff
diff --git a/src/init.cpp b/src/init.cpp
index f79ebe881d..881a254efc 100644
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -54,6 +54,7 @@
 #include <node/mempool_persist_args.h>
 #include <node/miner.h>
 #include <node/peerman_args.h>
+#include <node/types.h>           // for BlockCreateOptions
 #include <policy/feerate.h>
 #include <policy/fees.h>
 #include <policy/fees_args.h>
@@ -645,7 +646,7 @@ void SetupServerArgs(ArgsManager& argsman, bool can_listen_ipc)
     argsman.AddArg("-whitelistrelay", strprintf("Add 'relay' permission to whitelisted peers with default permissions. This will accept relayed transactions even when not relaying transactions (default: %d)", DEFAULT_WHITELISTRELAY), ArgsManager::ALLOW_ANY, OptionsCategory::NODE_RELAY);
 
 
-    argsman.AddArg("-blockmaxweight=<n>", strprintf("Set maximum BIP141 block weight (default: %d)", DEFAULT_BLOCK_MAX_WEIGHT), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
+    argsman.AddArg("-blockmaxweight=<n>", strprintf("Set maximum BIP141 block weight (default: %d). Note that getblocktemplate reserves %d weight units for the pool to customize the coinbase.", DEFAULT_BLOCK_MAX_WEIGHT, node::BlockCreateOptions{}.coinbase_max_additional_weight), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
     argsman.AddArg("-blockmintxfee=<amt>", strprintf("Set lowest fee rate (in %s/kvB) for transactions to be included in block creation. (default: %s)", CURRENCY_UNIT, FormatMoney(DEFAULT_BLOCK_MIN_TX_FEE)), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
     argsman.AddArg("-blockversion=<n>", "Override block version to test forking scenarios", ArgsManager::ALLOW_ANY | ArgsManager::DEBUG_ONLY, OptionsCategory::BLOCK_CREATION);
 
diff --git a/src/policy/policy.h b/src/policy/policy.h
index 4412f2db87..f0c9e822ec 100644
--- a/src/policy/policy.h
+++ b/src/policy/policy.h
@@ -20,7 +20,7 @@ class CFeeRate;
 class CScript;
 
 /** Default for -blockmaxweight, which controls the range of block weights the mining code will create **/
-static constexpr unsigned int DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT - 4000};
+static constexpr unsigned int DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT};
 /** Default for -blockmintxfee, which sets the minimum feerate for a transaction in blocks created by mining code **/
 static constexpr unsigned int DEFAULT_BLOCK_MIN_TX_FEE{1000};
 /** The maximum weight for transactions we're willing to relay/mine */
```

File: src/node/types.h (hunk 1 above)
Comment (ismaelsadeeq) [reply src/node/types.h]: Switched to the approach you suggested.

File: test/functional/mining_basic.py [hunk 2]
```diff
@@ -68,7 +68,7 @@ def mine_chain(self):
         mining_info = self.nodes[0].getmininginfo()
         assert_equal(mining_info['blocks'], 200)
         assert_equal(mining_info['currentblocktx'], 0)
-        assert_equal(mining_info['currentblockweight'], 4000)
+        assert_equal(mining_info['currentblockweight'], 0)
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply test/functional/mining_basic.py]: This is gone now, thanks.

**Comment by ismaelsadeeq** [comment]
Thanks for your review, @Sjors.

I addressed all of your comments.  

> Something like this should do  

Done. Instead of creating `DEFAULT_BLOCK_MAX_WEIGHT` that copies `MAX_BLOCK_WEIGHT`, I've used it directly.  

> Maybe init.cpp should also enforce that -blockmaxweight <= MAX_BLOCK_WEIGHT  

We already clamp the block size in the block assembler, so it will never exceed `MAX_BLOCK_WEIGHT`, but done with a test.  

I've added a functional test and release notes.

**Comment by Sjors** [comment]
> We already clamp the block size in the block assembler

True, but I think it's always better to clearly inform the user when they're trying to do something impossible. That said, not everyone might agree with that. If other reviewers don't like it you can always drop the check.

Will review shortly.

**Comment by Sjors** [comment]
The BitAxe doesn't like it either:

```
₿ (108381) bm1368Module: Job ID: 18, Core: 75/1, Ver: 07702000
₿ (108381) bm1368Module: Invalid job found, 0x18
```

**Comment by Sjors** [comment]
ACK f7a2f125c7b23c4c3c2e5253a6d3e2dcd8d3fe97

I checked that the new `test_block_max_weight` test fails if I undo the changes in e1114bcc0d1b0078a6b3dbb6bbcf28f738f97bd0.

**Review by darosior — COMMENTED** [review]
Could you talk to why it is not a concern for existing deployed pool software which relies on the 8k value? It seems that reducing the default to 4k could at best cause issues to upgrading to a new Bitcoin Core version if noticed or at worst lead to creating an invalid block.

From a quick skim through a block explorer there is a bunch of blocks with a >4k coinbase transaction right now:
- https://blockstream.info/tx/121436b7346a49e12495a9286638636bf4baed0a218ce47867cad510c78030b1
- https://blockstream.info/tx/9017f8200301770d2bac3fc224302ab207ccec2ef42e00eae78a30928fdb40a7
- https://blockstream.info/tx/134a47f4853382ec2b066c580a2b98867e90fe264889b71e562c94fb83991350
- https://blockstream.info/tx/747a8b230bd07e738ad4d5392190121e91da3a8125d1a33ccac4ec21f37cddc0
- https://blockstream.info/tx/9d2203b1c72eddc072b566c4a16ed8757fcba95a3be6f270e17a128e41554b33
- https://blockstream.info/tx/0987ebb31c4d8abd8158d5c7d63af8aea76df8581289ba0d676d7d38923ecd4f

It seems those were all created by a single pool, so it might make sense to look into their software if it's open source, or reach out to them. Also probably a good idea to scan the past year of blocks to see if any other miner was creating coinbase between 4k and 8k.

To be clear i think it makes absolute sense to not double count or at least to clarify the *actual* max block weight Bitcoin Core will use by default. Just want to make sure that lowering the default doesn't lead our users to make an expensive mistake.

**Review by pinheadmz — APPROVED** [review]
ACK f7a2f125c7b23c4c3c2e5253a6d3e2dcd8d3fe97

Built and tested on arm/macos. Confirmed test fails without patch. I noticed [last year](https://github.com/bitcoin/bitcoin/issues/21950#issuecomment-1577337474) that all but one pools' blocks were maxing out at 3996000 but I really appreciate @darosior point about pools that typically build large coinbases.

I wonder if it makes sense for a pool to set their own reserved coinbase weight, or pass in the outputs they want into getblocktemplate as an argument?

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK f7a2f125c7b23c4c3c2e5253a6d3e2dcd8d3fe97
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmdXM54ACgkQ5+KYS2KJ
yTpiAxAAwSCb+I2c2yJmDmlmcZcq8tyNAiHuNxr7r6RWCcIx35TDiELPJaYNBkhj
S4OuTeRV+2CR0VbzCudmkt2MAHPaAlxCv3kgsMe4giI9bKSaHpBlCL5c0Zw3G2f4
Y0GTuCHYXMuK/G6pfMr/ox82AXXjorgVMpxAqAnlAigaebDb0CGwdSWw0by2kYNu
1DH8ivkU2c590cRO5OYZr/9t8HdGLp7ySvnQ4Db/c4lJNC5EmopO0sq31wAcSKpP
ZYlv+eE6tKG8XYABNf78PNXnE4k2gpf3T6Gid+3lTXGAHSdopLJODmlK3UnVbMeH
9d9UaYZ0La5eeGOdRe66iKOyByNI+gOHXE7N0bdmM3xM1OR7LG3CaGxVOx27WSwg
QR/mGG43AbGdOGLbUY9MY6qjQWLeekYYTEQEWiBb22oltvn0vmoWBTZ07rKnkiBL
rbmZzAFHVkyjEZD6AkOxJ7EzeSQb0cAqMFfCC9z8tRJnVLwyvnLU8UUS2xq+NvN/
npKdyC6OLK8F0Rg77oS6oWsJRzcvg5+lzDw54TXyokRYSLEsQCWBsAR2Fjl91C6a
Mf/4SN/d4oHdf1o1MxG+HqNiH+B8kgF5zSRxqmq2H1vPtQzf9Gpam+ol5uWFnXYl
x26/0aESedAhHqoZrpdwqdCRNn5CZoSOnL0f6aiqQVWFzNnwdeE=
=/h/d
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Comment by pinheadmz** [comment]
I ran this branch in Warnet too, filled up a mempool (`"size": 4563,  "bytes": 1377134`) and called GBT from two connected nodes, v27.0 and this branch with expected results: 

```
$ # branch
$ warnet bitcoin rpc tank-0000 getblocktemplate '{\"rules\":[\"segwit\"]}' | jq '[.transactions[].weight] | add '
3995896
$ # v27.0
$ warnet bitcoin rpc tank-0001 getblocktemplate '{\"rules\":[\"segwit\"]}' | jq '[.transactions[].weight] | add '
3991958
```

I'm interested in replaying this test with 6k, 8k, 10k weight coinbase txs too.

**Comment by Sjors** [comment]
> Could you talk to why it is not a concern for existing deployed pool software which relies on the 8k value?

If a pool does not manually set a value for `-maxblockweight` then, before this change, 4000 weight units were reserved for the coinbase and 4000 were unallocated. That effectively makes it a 8000 weight unit reservation.

So it any existing pool relies on that space to be available they could produce an invalid block after upgrading.

> From a quick skim through a block explorer there is a bunch of blocks with a >4k coinbase transaction right now:

To be more precise, we're interested in coinbase transactions of 4000 < size <= 8000, only counting scriptSig, witness and outputs. But the above is enough evidence to be careful here, so I undid my ACK.

> It seems those were all created by a single pool, so it might make sense to look into their software if it's open source,

It being open source is highly unlikely unfortunately.

I see two options:

1. Make it clear in the README that miners should check if their pool software produces large coinbase transactions. This relies a bit too much on people actually reading things.

2. Add a new configuration option `-maxcoinbaseweight` (leaving out "additional" for readability) and make it 8000 by default. Combined with the changes in this PR, it preservers the current behavior.

If we go for option (2) we should probably go ahead and also add `-maxcoinbasesigops` since we know at least one pool patched Bitcoin Core (incorrectly) to have this functionality. See https://bitcoin.stackexchange.com/questions/117837/how-many-sigops-are-in-the-invalid-block-783426

**Comment by ismaelsadeeq** [comment]
Thanks for all your reviews.

Thanks @pinheadmz for testing this with warnet 🚀 

>  It seems that reducing the default to 4k could at best cause issues with upgrading to a new Bitcoin Core version if noticed or at worst lead to creating an invalid block.

This is only the case if the miner starts their node with default configurations. Assuming this PR gets into the next release, miners who want more space for the coinbase can simply start their node with a custom `-blockmaxweight` option, reducing the weight to their preferred value.
@darosior I have a test covering this case in b52aad748efd84dceff84f9d46604375a6e23d1f

This pool should start with `-blockmaxweight=3996000`, which would provide an additional 4,000 weight units, and they are fine. 
However, as @Sjors mentioned, "This relies a bit too much on people actually reading things," and I completely agree.

I also agree it would be very useful to analyze the percentage of coinbase weight usage over the last few years so that we can make an informed decision based on historical data. I will work on this.

---

As it stands, most miners are likely to have coinbases with weights not exceeding 4,000 (note: this claim should be backed with data; I only did a quick review of a few blocks) and current master provides no way for miners to build a block template that fully utilizes the remaining 4,000 weight units of weight. 
And we see some pools using a custom block builder to try to max out the remaining space according to @pinheadmz observations.

We should consider providing a mechanism that allows users to adjust this parameter while preserving the current block behavior.
- One option is to introduce a `-maxcoinbaseweight` parameter as @Sjors suggested.
- Alternatively, if we want to avoid adding a new option, we could reserve 8,000 weight units by default.  When users specify a `-blockmaxweight` lower than 4,000,000, the delta would determine the default coinbase transaction weight. 
     - Users who want 4,000 weight units for the coinbase can set `-blockmaxweight=3996000`.
     - Users who prefer the default 8,000 weight units will just start their node with the default configuration.
     
     
> I'm a bit worried about miners yolo-adjusting this value too low.

(we can prevent too low delta in all approaches, so I think the minimum should be 4000 weight units. This PR already does that)
     
I am open to implementing any of these suggestions in this PR.

File: doc/release-notes-31384.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+- Node and Mining
+
+---
+
+- PR #31384 fixed an issue where duplicate coinbase transaction weight reservation occurred. The `getblocktemplate` RPC will now correctly creates blocks with a weight of `3,996,000` weight units, reserving `4,000` weight units for the coinbase transaction.
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md:5]: Thanks I will change when retouching.

**Comment by Sjors** [comment]
> Alternatively, if we want to avoid adding a new option, we could reserve 8,000 weight units by default.

Maybe that's the best way to keep this PR simple. For Stratum v2 I don't care because we override the value anyway.

**Comment by ismaelsadeeq** [comment]
@darosior @Sjors @pinheadmz 

I've recently analyzed the blockchain for the last two years from 4th December 2022 to 23rd December 2024 to move this forward.

I will cross-write my findings here, but more seen here details can be seen here https://delvingbitcoin.org/t/analyzing-mining-pool-behavior-to-address-bitcoin-cores-double-coinbase-reservation-issue/1351

- Most mining pools adhere to Bitcoin Core’s default setup, keeping coinbase transaction weights well below **4000 WU**. However, two pools stand out:
  - **Ocean.xyz** consistently uses larger coinbase transactions, with an average weight of **6,994 WU**. Their smallest coinbase weight was **5,308 WU** (in block 865820), and their largest reached **9,272 WU** (block 863471). This suggests Ocean.xyz configures its node with a reduced `-blockmaxweight` setting, as their average block size is **3,986,489 WU**, well below the default template size.
  - An **Unknown Pool/miner** also exceeded the default coinbase weight, averaging **7,432 WU**, with a maximum of **7,864 WU** but a very low block weight average which is unusual behavior.
- **F2Pool** blocks have an average weight of **3,997,857 WU**, with some blocks exceeding **3,995,063 WU**. For instance, block **779729** reached **3,998,554 WU** with a coinbase weight of just **1,588 WU**, showcasing their optimal use of the available block weight.
- The majority of pools—such as Foundry USA, Binance Pool, and AntPool—produce blocks averaging around **3,993,000 WU**, consistent with Bitcoin Core’s current behavior. However, this depicts underutilization which is a direct result of the double-reservation bug.
- The small increase in the weights of the blocks among these pools suggests minor additions of transactions by miners after building a block template.

If the double-reservation issue is fixed, block templates will increase to **3,996,000 WU**, aligning theoretical and actual limits. This change benefits pools by allowing full utilization of the block weight while preserving **4000 WU** for coinbase transactions and other small additions.

Miners who need more space, such as Ocean.xyz, can still configure their nodes with a reduced `-blockmaxweight`. For example, setting it to **3,999,000 WU** frees up **1000 WU** for larger coinbase transactions, ensuring compliance with consensus rules.

**Comment by Sjors** [comment]
@ismaelsadeeq thanks for the research!

Ocean in the DATUM documentation indeed requires a reduced `-blockmaxweight=3985000`, so presumably they do something similar in their regular stratum pool: https://github.com/OCEAN-xyz/datum_gateway?tab=readme-ov-file#node-configuration

I still think we should use `-blockmaxweight` (default `4000000`) to refer to the entire block, including coinbase, and then have a separate `-maxcoinbaseweight` (default `8000`). This keeps the same behavior for miners with default settings.

Miners who manually configured `-blockmaxweight` before will, after this update, need to manually set `-maxcoinbaseweight=4000` to preserve the same behaviour. But if they don't do this, it's not dangerous.

Later on we could even deprecate `-blockmaxweight`. Its original purpose was to constrain the block size far below the consensus limit, which nobody is doing anymore.

**Comment by ismaelsadeeq** [comment]
@Sjors 

> I still think we should use -blockmaxweight (default 4000000) 

Agreed this reflects the current behaviour of this PR

> and then have a separate -maxcoinbaseweight (default 8000). This keeps the same behavior for miners with default settings.

> Miners who manually configured -blockmaxweight before will, after this update, need to manually set -maxcoinbaseweight=4000 to preserve the same behaviour. But if they don't do this, it's not dangerous.

Why do we want to preserve the same behavior? Yes, they now have the ability to lower it, but then our default is high above the average of what miners use (almost 4x), and users tend to stick to the default. As a result, they will mine at a disadvantage compared to their counter parties have a custom settings.

Could you clarify the effect of setting it to `4000` in light of the recent findings? I see no reason why we should not set it to `4000`  because it's more than enough for most users, and does not incentivize any custom set-up.

**Comment by Sjors** [comment]
> Could you clarify the effect of setting it to 4000 in light of the recent findings?

It's still not worth the risk imo. Making the default 4000 instead of 8000 provides 0.1% extra fee revenue for miners who don't read the release notes. But there could be a miner out there losing 100% of the block revenue (subsidy + 100% of fees) because they were doing something custom that you didn't detect in the analysis.

In the example of Ocean it _seems_ that their custom `-blockmaxweight` is low enough that this change won't bite them, but without inspecting their software we can't know if there's some edge case where it _does_ matter.

**Comment by ismaelsadeeq** [comment]
> Making the default 4000 instead of 8000 provides 0.1% extra fee revenue for miners who don't read the release notes. But there could be a miner out there losing 100% of the block revenue (subsidy + 100% of fees)

Fair enough.

I've pushed an update [diff](https://github.com/bitcoin/bitcoin/compare/f7a2f125c7b23c4c3c2e5253a6d3e2dcd8d3fe97..cd48e2ccaf24c9594f5987a29e02b924573134ed):

1. Set the default to 8000, based on [this suggestion](https://github.com/bitcoin/bitcoin/pull/31384#issuecomment-2567472713).
2. e504d15cfb4c0b6ed67c46f5aecc47980f233bcb Fixed the accounting of total block weight and total block sigop count to exclude the reserved values for coinbase transaction. These are estimates and can be incorrect when the actual values, which are usually lower, don't match the reserved ones. It's now explicit that the totals do not include the coinbase transaction.

I didn't push the update for `maxcoinbaseweight` because I wanted to suggest making it a runtime option. The requirements can change for each block template, so it might be better to pass it as an RPC parameter in `getblocktemplate` instead of an init parameter. WDYT, @Sjors?

Also, you can skip reviewing the release notes they're  not final yet.

**Comment by Sjors** [comment]
Changing anything about `getblocktemplate` can be tricky in my experience https://github.com/bitcoin/bitcoin/pull/27433#issuecomment-1607709381, because it's defined in BIP22: https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki

So I would leave "making it a runtime option" to a followup. That said, I'm skeptical how useful that would be. Legacy pool software probably won't use it, Ocean has a fixed value that they tell users to configure and modern mining pool software should just use the new Mining IPC interface imo.

File: doc/release-notes-31384.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
+- Node and Mining
+
+---
+
+- PR #31384 fixed an issue where the coinbase transaction weight was being reserved in two different places.
+ The fix ensures the reservation happens in one place, but does not change the previous behaviour by setting the default
+ to the previous value of `8,000`.
+ However, this PR offers the advantage of overriding the default with a user-desired value and allow creating blocks
```
Comment (TheCharlatan) [inline doc/release-notes-31384.md:8]: I'm a bit confused by this second sentence. How does the behaviour introduced here allow for overriding the default?

**Review by sedited — COMMENTED** [review]
Approach ACK

File: src/init.cpp [hunk 5]
```diff
@@ -54,6 +55,7 @@
 #include <node/mempool_persist_args.h>
 #include <node/miner.h>
 #include <node/peerman_args.h>
+#include <node/types.h> // for BlockCreateOptions
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/init.cpp]: fixed

File: src/init.cpp [hunk 6]
```diff
@@ -647,7 +649,7 @@ void SetupServerArgs(ArgsManager& argsman, bool can_listen_ipc)
     argsman.AddArg("-whitelistrelay", strprintf("Add 'relay' permission to whitelisted peers with default permissions. This will accept relayed transactions even when not relaying transactions (default: %d)", DEFAULT_WHITELISTRELAY), ArgsManager::ALLOW_ANY, OptionsCategory::NODE_RELAY);
 
 
-    argsman.AddArg("-blockmaxweight=<n>", strprintf("Set maximum BIP141 block weight (default: %d)", DEFAULT_BLOCK_MAX_WEIGHT), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
+    argsman.AddArg("-blockmaxweight=<n>", strprintf("Set maximum BIP141 block weight (default: %d). Note: default policy is to reserve %d weight units for coinbase transaction.", MAX_BLOCK_WEIGHT, node::BlockCreateOptions{}.coinbase_max_additional_weight), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/init.cpp]: This is gone now.

**Review by ismaelsadeeq — COMMENTED** [review]
Thanks for your feedback @Sjors and your review @TheCharlatan 

I've forced pushed to see [diff](https://github.com/bitcoin/bitcoin/compare/cd48e2ccaf24c9594f5987a29e02b924573134ed..ededdd13f3263df08f7878aa2514d3796436cbfb):
1. Add the `-maxcoinbaseweight` option with default as `8000`.
2.  Address review comments from @TheCharlatan

File: doc/release-notes-31384.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md]: fixed. thanks @pinheadmz

File: src/test/fuzz/mini_miner.cpp [hunk 7]
```diff
@@ -148,9 +148,9 @@ FUZZ_TARGET(mini_miner_selection, .init = initialize_miner)
             }
         }
 
-        // Stop if pool reaches DEFAULT_BLOCK_MAX_WEIGHT because BlockAssembler will stop when the
+        // Stop if pool reaches MAX_BLOCK_WEIGHT because BlockAssembler will stop when the
         // block template reaches that, but the MiniMiner will keep going.
-        if (pool.GetTotalTxSize() + GetVirtualTransactionSize(*tx) >= DEFAULT_BLOCK_MAX_WEIGHT) break;
+        if (pool.GetTotalTxSize() + GetVirtualTransactionSize(*tx) >= MAX_BLOCK_WEIGHT) break;
```
Comment (Sjors) [inline src/test/fuzz/mini_miner.cpp:153]: 354f41f5c76f5f43cbfdddb63660cc77c4a76989: I think this should be `MAX_BLOCK_WEIGHT - coinbase_max_additional_weight`, because later on this fuzzer adds a small coinbase transaction.

(can probably just hardcode something like `- 4000`)

File: src/init.cpp [hunk 8]
```diff
@@ -1017,6 +1017,13 @@ bool AppInitParameterInteraction(const ArgsManager& args)
         }
     }
 
+    if (args.IsArgSet("-blockmaxweight")) {
+        const auto customMaxBlockWeight = args.GetIntArg("-blockmaxweight", MAX_BLOCK_WEIGHT);
```
Comment (Sjors) [inline src/init.cpp:1022]: 6cc658075e1be59ef49a060b36921538acf0edb1 nit: current naming convention uses snake case. Maybe just use `max_block_weight`.

File: src/node/miner.cpp [hunk 9]
```diff
@@ -158,7 +155,7 @@ std::unique_ptr<CBlockTemplate> BlockAssembler::CreateNewBlock(const CScript& sc
     pblocktemplate->vchCoinbaseCommitment = m_chainstate.m_chainman.GenerateCoinbaseCommitment(*pblock, pindexPrev);
     pblocktemplate->vTxFees[0] = -nFees;
 
-    LogPrintf("CreateNewBlock(): block weight: %u txs: %u fees: %ld sigops %d\n", GetBlockWeight(*pblock), nBlockTx, nFees, nBlockSigOpsCost);
+    LogPrintf("CreateNewBlock(): block weight: %u txs: %u fees: %ld sigops %d. (excluding coinbase transaction)\n", nBlockWeight, nBlockTx, nFees, nBlockSigOpsCost);
```
Comment (Sjors) [inline src/node/miner.cpp:160]: 76a95522b322c1a8ab1594ca8bf5ac99ab379c46: to keep log lines short, maybe say `(ex. coinbase)`. Maybe also move it left: `CreateNewBlock(): block weight (ex. coinbase): ...`

File: src/rpc/mining.cpp [hunk 10]
```diff
@@ -418,8 +418,8 @@ static RPCHelpMan getmininginfo()
                     RPCResult::Type::OBJ, "", "",
                     {
                         {RPCResult::Type::NUM, "blocks", "The current block"},
-                        {RPCResult::Type::NUM, "currentblockweight", /*optional=*/true, "The block weight of the last assembled block (only present if a block was ever assembled)"},
-                        {RPCResult::Type::NUM, "currentblocktx", /*optional=*/true, "The number of block transactions of the last assembled block (only present if a block was ever assembled)"},
+                        {RPCResult::Type::NUM, "currentblockweight", /*optional=*/true, "The block weight (excluding coinbase transaction) of the last assembled block (only present if a block was ever assembled)"},
+                        {RPCResult::Type::NUM, "currentblocktx", /*optional=*/true, "The number of block transactions (excluding coinbase transaction) of the last assembled block (only present if a block was ever assembled)"},
```
Comment (Sjors) [inline src/rpc/mining.cpp:422]: 76a95522b322c1a8ab1594ca8bf5ac99ab379c46 nit: `(excluding coinbase)`, since the description already says "transactions"

**Review by Sjors — COMMENTED** [review]
Code reviewed ededdd13f3263df08f7878aa2514d3796436cbfb, almost there.

File: doc/release-notes-31384.md [hunk 11]
```diff
@@ -0,0 +1,12 @@
+- Node and Mining
+
+---
+
+- PR #31384 fixed an issue where the coinbase transaction weight was being reserved in two different places.
+  The fix ensures that the reservation happens in a single place.
+
+- This PR also introduces a new startup option, `-maxcoinbaseweight` (default: `8,000` weight units).
+  All created block template will reserves the default or specified value for the miner coinbase transaction.
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md]: Done

File: src/test/fuzz/mini_miner.cpp (hunk 7 above)
Comment (ismaelsadeeq) [reply src/test/fuzz/mini_miner.cpp]: Nice catch, fixed but without hardcoding.
The comment above also needs to be updated, I did that.

File: src/init.cpp (hunk 8 above)
Comment (ismaelsadeeq) [reply src/init.cpp]: Done!

File: src/rpc/mining.cpp (hunk 10 above)
Comment (ismaelsadeeq) [reply src/rpc/mining.cpp]: Done!

File: src/node/miner.cpp (hunk 9 above)
Comment (ismaelsadeeq) [reply src/node/miner.cpp]: I think ex. is ambiguous so I shortened it by writing tx instead of transaction.

Also this is not logged frequently, only by miners I think.

Comment (Sjors) [reply src/node/miner.cpp]: With #31003 this would be logged every second.

File: doc/release-notes-31384.md [hunk 12]
```diff
@@ -0,0 +1,17 @@
+- Node and Mining
+
+---
+
+- PR #31384 fixed an issue where the coinbase transaction weight was being reserved in two different places.
+  The fix ensures that the reservation happens in a single place.
+
```
Comment (Sjors) [inline doc/release-notes-31384.md:7]: You lost a line here:

```md
- This PR also introduces a new startup option, `-maxcoinbaseweight` (default: `8,000` weight units).
```

**Review by Sjors — APPROVED** [review]
ACK 7452638559e8ccbe00db5ef5a53cb21ffe27d337

File: doc/release-notes-31384.md (hunk 12 above)
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md:7]: Fixed in latest push https://github.com/bitcoin/bitcoin/compare/7452638559e8ccbe00db5ef5a53cb21ffe27d337..2fb833e69627a8f9b1c4b14b60d1df9903adf210

File: test/functional/mining_basic.py [hunk 13]
```diff
@@ -190,6 +192,87 @@ def test_pruning(self):
...
+        )
+
+        # Test block template creation with custom -blockmaxweight
+        custom_block_weight = MAX_BLOCK_WEIGHT - 2000
+        # Reducing the weight by 2000 units will prevent 1 large transaction from fitting into the block.
+        self.restart_node(0, extra_args=[f"-datacarriersize={LARGE_VSIZE}", f"-blockmaxweight={custom_block_weight}"])
+
+        self.log.info("Testing the block template with custom -blockmaxweight to include 9 large and 2 normal transactions.")
+        self.verify_block_template(
+            expected_tx_count=11,
```
Comment (pinheadmz) [inline test/functional/mining_basic.py:257]: b55bb95d8d80175f30d2d4da5c6cfd72e5d8eedd

nit: could be `LARGE_TXS_COUNT + 1` to make it clear the difference from previous template

File: src/init.cpp [hunk 14]
```diff
@@ -650,6 +650,7 @@ void SetupServerArgs(ArgsManager& argsman, bool can_listen_ipc)
 
 
     argsman.AddArg("-blockmaxweight=<n>", strprintf("Set maximum BIP141 block weight (default: %d).", MAX_BLOCK_WEIGHT), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
+    argsman.AddArg("-maxcoinbaseweight=<n>", strprintf("Set the block maximum reserved coinbase transaction weight (default: %d).", node::BlockCreateOptions{}.coinbase_max_additional_weight), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
```
Comment (pinheadmz) [inline src/init.cpp:653]: a45af6af4e7a59cd14ef6e16b8e5e180fa9d564d

Question about this phrasing: what is "maximum" about it? If a user sets `-maxcoinbaseweight=1000` then 1000 weight will always be reserved in block templates, and if the actual coinbase ends up being 50 weight instead of 1000 that extra weight will just be unused and the final block will be smaller than maximum size.

File: src/init.cpp [hunk 15]
```diff
@@ -1024,6 +1025,13 @@ bool AppInitParameterInteraction(const ArgsManager& args)
         }
     }
 
+    if (args.IsArgSet("-maxcoinbaseweight")) {
+        const auto max_coinbase_weight = args.GetIntArg("-maxcoinbaseweight", node::BlockCreateOptions{}.coinbase_max_additional_weight);
+        if (max_coinbase_weight > MAX_BLOCK_WEIGHT) {
```
Comment (pinheadmz) [inline src/init.cpp:1030]: a45af6af4e7a59cd14ef6e16b8e5e180fa9d564d

Should this test against `args.GetIntArg("-blockmaxweight", MAX_BLOCK_WEIGHT)` ? Or, what happens if a user sets `-blockmaxweight=1000 -maxcoinbaseweight=4000` ?

File: doc/release-notes-31384.md [hunk 16]
```diff
@@ -0,0 +1,16 @@
...
+- This PR also introduces a new startup option, `-maxcoinbaseweight` (default: `8,000` weight units).
+  This specifies how many weight units to reserve for the coinbase transaction.
+- Upgrade note: the default of `-maxcoinbaseweight` ensures backward compatibility for users who did
+  not override `-blockmaxweight`.
```
Comment (pinheadmz) [inline doc/release-notes-31384.md:11]: 2fb833e69627a8f9b1c4b14b60d1df9903adf210

You might want to mention the old default of `3996000` here. I was staring at `blockmaxweight=4000000` on the following line for a minute trying to figure out what actually changed.

**Review by pinheadmz — APPROVED** [review]
ACK 2fb833e69627a8f9b1c4b14b60d1df9903adf210

Reviewed each commit, built and ran unit and functional tests on arm/macos. I left a few questions and nits below. 

Test coverage is great and I think this is the right approach to add a coinbase reserved weight option. Also it's a nice way to get those extra 4000 weight for default miners without putting the heavy-coinbase mining pools at risk



I also have one last lingering question which is: when does the miner actually construct their coinbase transaction and is that ever compared to the reserved size? Or do we just ensure it fits in the current block template against MAX_BLOCK_WEIGHT? In either case, how is the miner warned that they may need to reduce their coinbase weight OR restart with a different `-maxcoinbaseweight`?

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 2fb833e69627a8f9b1c4b14b60d1df9903adf210
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmd+3sMACgkQ5+KYS2KJ
yTroqhAAg1FUDuanndz7w+oHkrzpJ1JvmAGoZnaoBU6Rua7FgN97+RgHCv44zPH5
w5knXBMPl77AiM6BSCvfqt/os15Opm+GvU1wkz3oW4w/JvzYuiQK3X3PqQv4eeW2
E46p5dAoClwkzpkqdTKo4AezqiM3tHo+pGuvPLcaUgOFggElt/lYA2yKSvbEocst
kWyw3fW6iXa71u+pONRukWHzRYthBiozrBQu8vPsj7o1xqnUqN+o650kzqT5qHXU
pD9LPJlVUoeAKXg2+uUAlXRa0NI23H+QiRS5z3AKC8Y1frLA9oTFo3RvxcbyP2ux
qIr57H30yEX+DhwG3u4B7TF2O3xcP5+KuKPER7CJ/EYXEYhxzaXW6jOkIbAwEH8b
3mVvN9fPxVHozMeeFHTJl+jQN6Jm6m0SMF85HSkxnvfS1xTRl7/BkQFmy8D2ofVQ
IBeyIaibQCM53uc0MTI5Fr/FdiL4r63GzJopG4fPYmU2pnhZPdX89fgodMtVVmIE
DbgaLOLn+CnnlJcT2kWoP7D3sZdzAvgyLB0yxByjMkRia4tahMrRh/iAjoTuEPr1
LJCw2vDPET/BZogPkJoXVdN9y9mxGu5jn4rHQBYh88oup+Wz1qdJ28H9RztP6XFs
+uDEgRAYVwg0c5fSrRFtoKI+Mk3gtJIU+cQ0YBzaR3E3U8YYANs=
=Fh++
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

File: src/node/miner.cpp [hunk 17]
```diff
@@ -90,18 +90,17 @@ void ApplyArgsManOptions(const ArgsManager& args, BlockAssembler::Options& optio
...
 {
     inBlock.clear();
-
-    // Reserve space for coinbase tx
-    nBlockWeight = m_options.coinbase_max_additional_weight;
-    nBlockSigOpsCost = m_options.coinbase_output_max_additional_sigops;
-
     // These counters do not include coinbase tx
+    nBlockWeight = 0;
+    nBlockSigOpsCost = 0;
```
Comment (luke-jr) [inline src/node/miner.cpp:103]: This changes the meaning of `getmininginfo` fields unexpectedly, and forces us to add in the coinbase reserved size over and over. Seems like it would be better to include it here once.

File: src/policy/policy.h [hunk 18]
```diff
@@ -19,8 +19,6 @@ class CCoinsViewCache;
 class CFeeRate;
 class CScript;
 
-/** Default for -blockmaxweight, which controls the range of block weights the mining code will create **/
-static constexpr unsigned int DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT - 4000};
```
Comment (luke-jr) [inline src/policy/policy.h:23]: This should remain logically separate from consensus constant.

**Review by luke-jr — CHANGES_REQUESTED** [review]

File: doc/release-notes-31384.md (hunk 16 above)
Comment (Sjors) [reply doc/release-notes-31384.md:11]: Good point, maybe add:

```
The previous `-blockmaxweight` default was `3,996,000`. The block template construction code added an additional `4,000` padding. The new default `-maxcoinbaseweight` value was chosen to maintain that behaviour.

File: src/init.cpp (hunk 14 above)
Comment (Sjors) [reply src/init.cpp:653]: Correct.

File: src/init.cpp (hunk 15 above)
Comment (Sjors) [reply src/init.cpp:1030]: Current `ClampOptions` has a comment that specifically permits `-maxcoinbaseweight` to exceed `-blockmaxweight`. It just means that all blocks will be empty. This seems like an unrealistic scenario anyway.

File: src/node/miner.cpp (hunk 17 above)
Comment (Sjors) [reply src/node/miner.cpp:103]: I agree we should not change the `weight` and `sigops` fields in `getblocktemplate` and `getmininginfo`.

We could either adjust the value in the RPC code, or as @luke-jr suggests restore the original behavior here.

Additionally we should clarify the help text for these RPC methods that they include the coinbase reserved weight.

File: src/init.cpp (hunk 14 above)
Comment (Sjors) [reply src/init.cpp:653]: Perhaps `-coinbaseweightreservation` is a better name.

File: src/policy/policy.h (hunk 18 above)
Comment (Sjors) [reply src/policy/policy.h:23]: Seems reasonable to keep and just make it `DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT};`

File: test/functional/mining_basic.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply test/functional/mining_basic.py:79]: Sorry, I think @luke-jr is right and we shouldn't change this: https://github.com/bitcoin/bitcoin/pull/31384/files#r1908533084

**Comment by Sjors** [comment]
> I also have one last lingering question which is: when does the miner actually construct their coinbase transaction and is that ever compared to the reserved size? 

This is entirely up to the pool software. They could call `getblocktemplate` in `proposal` mode (or `checkblock` if #31564 lands).

I think https://github.com/bitcoin/bitcoin/pull/31384/files#r1908533084 should be addressed before merging (and so might as well address the other comments now instead of a followup).

File: src/init.cpp (hunk 14 above)
Comment (ismaelsadeeq) [reply src/init.cpp]: I've taken your suggestion @Sjors.

File: src/node/miner.cpp (hunk 17 above)
Comment (ismaelsadeeq) [reply src/node/miner.cpp]: > This changes the meaning of `getmininginfo` fields unexpectedly, and forces us to add in the coinbase reserved size over and over. Seems like it would be better to include it here once.

> We could either adjust the value in the RPC code, or as @luke-jr suggests restore the original behavior here.

I've reverted and included it but clarify the `getmininginfo` help text.

> I agree we should not change the `weight`, `currentblockweight` and `sigops` fields in `getblocktemplate` and `getmininginfo`.

This only affects `getmininginfo` I think the `weight` and `sigops` results of `getblocktemplate` are for individual transactions in the block template.

File: src/policy/policy.h (hunk 18 above)
Comment (ismaelsadeeq) [reply src/policy/policy.h:23]: Done.

**Comment by ismaelsadeeq** [comment]
Thanks for reviewing @pinheadmz @luke-jr @Sjors 

I've recently foreced pushed from 2fb833e69627a8f9b1c4b14b60d1df9903adf210 to 7ab1344eb13228998bcead7328d5cc0a905971d4 [diff](https://github.com/bitcoin/bitcoin/compare/2fb833e69627a8f9b1c4b14b60d1df9903adf210..7ab1344eb13228998bcead7328d5cc0a905971d4)

Changes were:

1. Reverting https://github.com/bitcoin/bitcoin/commit/76a95522b322c1a8ab1594ca8bf5ac99ab379c46 but improving the help text.
2. Use policy `DEFAULT_MAX_BLOCK_WEIGHT` instead of consensus `MAX_BLOCK_WEIGHT`.
3. Rename `-maxcoinbaseweight` to `-coinbasereservedweight` and improve it's help text.
4. Update the release notes to be more informative.


> I think https://github.com/bitcoin/bitcoin/pull/31384/files#r1908533084 should be addressed before merging (and so might as well address the other comments now instead of a followup).

I believe this is addressed now.

> If you're going to touch the `getblocktemplate` help text, then consider cherry-picking https://github.com/bitcoin/bitcoin/commit/4facb94a481ca121a9117e0992799371bb429da1.

I am not touching `getblocktemplate` help text see https://github.com/bitcoin/bitcoin/pull/31384#discussion_r1909208594

File: src/node/miner.cpp (hunk 17 above)
Comment (Sjors) [reply src/node/miner.cpp]: > I think the `weight` and `sigops` results of `getblocktemplate` are for individual transactions in the block template.

Ah that would make sense, since I tried to add those totals in an early version of #27433.

**Review by Sjors — APPROVED** [review]
ACK 7ab1344eb13228998bcead7328d5cc0a905971d4

Just some feedback on the release notes.

File: doc/release-notes-31384.md [hunk 19]
```diff
@@ -0,0 +1,22 @@
+- Node and Mining
+
+---
+
+- **PR #31384** fixed an issue where the coinbase transaction weight was being reserved in two separate places.
+  Previously, the default `-blockmaxweight` was set to `4,000,000`. The block template generation algorithm should
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md]: Taken, thanks.

File: doc/release-notes-31384.md [hunk 20]
```diff
@@ -0,0 +1,22 @@
...
+- The fix consolidates the reservation into a single place and introduces a new startup option,
+  `-coinbasereservedweight` (default: `8,000` weight units). This option specifies the weight units
+  reserved for the coinbase transaction. The default value of `-coinbasereservedweight` was chosen
+  to preserve the previous behavior.
+
+- **Upgrade Note:** The default `-coinbasereservedweight` ensures backward compatibility for users who did not override
+  `-blockmaxweight` and relied on the previous behavior.
+
+- For users who do not rely on the previous behavior, setting `-coinbasereservedweight=4000`
+  allows block templates of size `3,996,000` WU to be generated.
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md]: fixed

File: doc/release-notes-31384.md [hunk 21]
```diff
@@ -0,0 +1,22 @@
...
+
+- Bitcoin Core will now **fail to start** if the `-blockmaxweight` or `-maxcoinbaseweight` init parameter exceeds
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md]: fixed

**Comment by Sjors** [comment]
re-ACK dba211a9ceafc57a953efc757adfe09c0f3fdb14

**Comment by 0xB10C** [comment]
Concept ACK

**Comment by Sjors** [comment]
@0xB10C pointed out the header always uses 80 bytes and there's few other unavoidable bytes in the block. So it sounds like there should be a minimum value for `-coinbasereservedweight`.

Additionally perhaps it should be renamed to just `-reservedweight` with a clarification in the document comment of how much of that goes to stuff other than the coinbase.

Alternatively we could make `-coinbasereservedweight` refer _only_ to the coinbase, but internally account for these other bytes. That's probably less confusing. We'll end up with a default a bit under `8000` though for simplicity we could keep the round number.

 https://delvingbitcoin.org/t/analyzing-mining-pool-behavior-to-address-bitcoin-cores-double-coinbase-reservation-issue/1351/5?u=sjors

**Comment by 0xB10C** [comment]
From https://github.com/bitcoin/bitcoin/issues/21950#issuecomment-2589450691
> Note that the reserved weight is NOT only used for the coinbase transaction. The block header takes up 320 WU (80 bytes * 4) and the `var_int` for the number of transactions takes up either 4 WU (1 byte `var_int` for up to 252 txns in the block) or 12 WU (3 byte `var_int` for up to 65535 txns). For most mainnet blocks this is an additional 332 WU. See also https://delvingbitcoin.org/t/analyzing-mining-pool-behavior-to-address-bitcoin-cores-double-coinbase-reservation-issue/1351/4?u=0xb10c


Given that this weight is reserved for the coinbase and the header, I don't think we should call it "coinbase reserved weight" or introduce something called `-coinbasereservedweight`. Maybe do `-blockreservedweight` and document that it's for the eheader and coinbase?

**Comment by ismaelsadeeq** [comment]
> Alternatively we could make -coinbasereservedweight refer only to the coinbase, but internally account for these other bytes. That's probably less confusing. We'll end up with a default a bit under 8000 though for simplicity we could keep the round number.

This change will alter the behavior, resulting in a transactions weight of `3992000 - 332 = 3991668` after calling GBT.

I think I prefer the first idea, which is similar to what @0xB10C suggested: renaming coinbasereservedweight to `-blockreservedweight` and setting a minimum value for it.

The minimum value would be:
 - The block header's weight (332 WU)
 - Plus the average coinbase transaction weight (1 input, 2 outputs, 562 WU)
 - Totalling 894 WU (rounded up to 1000 WU).

In the help text, we can clearly indicate this information.

**Comment by Sjors** [comment]
If we're going to set a minimum value for `-blockreservedweight` we should probably just pick the absolute minimum:
- a block with only a coinbase transaction
- header weight + 1 (for the number of transactions)
- the coinbase has 1 input (required by `IsCoinBase()`)
  - just the BIP34 scriptSig
  - no witness commitment
- the coinbase has 1 output (required by `CheckTransaction`)
  - `OP_TRUE` output script (or empty?)

**Comment by ismaelsadeeq** [comment]
Thanks for your review @Sjors  and recent insight from @0xB10C 
I've force pushed from dba211a9ceafc57a953efc757adfe09c0f3fdb14 to ad1bc03245181b00a25ea0182373eddae1c151e1 see [diff](https://github.com/bitcoin/bitcoin/compare/dba211a9ceafc57a953efc757adfe09c0f3fdb14..9475218d1ff5a2cbe8b682252715b10d489c22a5)

Changes
1. Renamed `-coinbasereservedweight` to `-blockreservedweight`
2. Clarified that the reservation is also for block header data
3. Prevent startup when user provided a `-blockreservedweight` lower than `2000` WU
4. Update the release notes

**Comment by Sjors** [comment]
The first commit a7d43645ea353021b2143407ab06336105c82434 changes `coinbaseMaxAdditionalWeight` in the Mining interface to `blockReservedWeight`. This decouples it from the  Stratum v2 concept of `CoinbaseOutputDataSize` which is strictly limited to the outputs added:

> The maximum additional serialized bytes which the pool will add in coinbase transaction outputs

https://github.com/stratum-mining/sv2-spec/blob/main/07-Template-Distribution-Protocol.md#71-coinbaseoutputdatasize-client---server

So I was initially a bit reluctant, but I think it's fine. The Template Provider (sidecar) in https://github.com/Sjors/bitcoin/pull/48 will just have to convert `CoinbaseOutputDataSize` to `blockReservedWeight`. I'll probably just have it add 2000 weight units, so it can never go below the minimum.

Some background...

The Stratum v2 spec gives the following explanation of `CoinbaseOutputDataSize`:

> Ultimately, the pool is responsible for adding coinbase transaction outputs for payouts and other uses, and thus the Template Provider will need to consider this additional block size when selecting transactions for inclusion in a block (to not create an invalid, oversized block). Thus, this message is used to indicate that some additional space in the block/coinbase transaction be reserved for the pool’s use (while always assuming the pool will use the entirety of available coinbase space).

> The Job Declarator MUST discover the maximum serialized size of the additional outputs which will be added by the pool(s) it intends to use this work. It then MUST communicate the maximum such size to the Template Provider via this message. The Template Provider MUST NOT provide `NewMiningJob` messages which would represent consensus-invalid blocks once this additional size — along with a maximally-sized (100 byte) coinbase field — is added. Further, the Template Provider MUST consider the maximum additional bytes required in the output count variable-length integer in the coinbase transaction when complying with the size limits.

By "coinbase field" they refer to coinbase `scriptSig`, which has the extra nonce, pool name, etc.`

The "Job Declarator" is another piece of software that sits between the pool and the Template Provider.

The way I interpret the spec is that it puts the onus of accounting for nitty gritty encoding stuff on the Template Provider.

File: src/rpc/mining.cpp [hunk 22]
```diff
@@ -419,8 +419,8 @@ static RPCHelpMan getmininginfo()
                     RPCResult::Type::OBJ, "", "",
                     {
                         {RPCResult::Type::NUM, "blocks", "The current block"},
-                        {RPCResult::Type::NUM, "currentblockweight", /*optional=*/true, "The block weight of the last assembled block (only present if a block was ever assembled)"},
-                        {RPCResult::Type::NUM, "currentblocktx", /*optional=*/true, "The number of block transactions of the last assembled block (only present if a block was ever assembled)"},
+                        {RPCResult::Type::NUM, "currentblockweight", /*optional=*/true, "The block weight (include coinbase reserved weight) of the last assembled block (only present if a block was ever assembled)"},
```
Comment (Sjors) [inline src/rpc/mining.cpp:422]: 9990552514328da45c19ed294c5bc79562aa12bc nit: "including"

File: src/init.cpp [hunk 23]
```diff
@@ -1022,6 +1023,16 @@ bool AppInitParameterInteraction(const ArgsManager& args)
         }
     }
 
+    if (args.IsArgSet("-blockreservedweight")) {
+        const auto block_reserved_weight = args.GetIntArg("-blockreservedweight", node::BlockCreateOptions{}.block_reserved_weight);
+        if (block_reserved_weight > DEFAULT_BLOCK_MAX_WEIGHT) {
+            return InitError(strprintf(_("Specified -blockreservedweight (%d) exceeds consensus maximum block weight (%d)"), block_reserved_weight, DEFAULT_BLOCK_MAX_WEIGHT));
+        }
+        if (block_reserved_weight < node::BlockCreateOptions{}.minimum_block_reserved_weight) {
+            return InitError(strprintf(_("Specified -blockreservedweight (%d) is lower than minimum sane value of (%d)"), block_reserved_weight, node::BlockCreateOptions{}.minimum_block_reserved_weight));
```
Comment (Sjors) [inline src/init.cpp:1032]: 131eb4e630f958f1b5330bb9d170716c33655880: sane -> safety

File: src/node/types.h [hunk 24]
```diff
@@ -39,6 +41,13 @@ struct BlockCreateOptions {
      * larger CompactSize encoded lengths.
      */
     size_t block_reserved_weight{8000};
+
+    /*
+     * This is a sane minimum value for block_reserved_weight.
+     * Reserving weight for coinbase transaction and block header
+     * below this value will be prevented.
+     */
+    const uint32_t minimum_block_reserved_weight{2000};
```
Comment (Sjors) [inline src/node/types.h:50]: 131eb4e630f958f1b5330bb9d170716c33655880: this should be a constant, not part of `BlockCreateOptions`.

E.g. `MINIMUM_BLOCK_RESERVED_WEIGHT{2000}` defined next to `DEFAULT_BLOCK_MAX_WEIGHT`.

File: src/node/types.h [hunk 25]
```diff
@@ -39,6 +41,13 @@ struct BlockCreateOptions {
      * larger CompactSize encoded lengths.
      */
     size_t block_reserved_weight{8000};
+
+    /*
+     * This is a sane minimum value for block_reserved_weight.
+     * Reserving weight for coinbase transaction and block header
```
Comment (Sjors) [inline src/node/types.h:47]: I would leave out this sentence, or say "Setting a lower value is prevented at startup."

File: src/node/types.h [hunk 26]
```diff
@@ -39,6 +41,13 @@ struct BlockCreateOptions {
      * larger CompactSize encoded lengths.
      */
     size_t block_reserved_weight{8000};
+
+    /*
+     * This is a sane minimum value for block_reserved_weight.
```
Comment (Sjors) [inline src/node/types.h:46]: Maybe add:

> This accounts for the block header, var_int encoding of the transaction count and a minimally viable coinbase transaction. It adds an additional safety margin, because even with a thorough understanding of block serialization, it's easy to make a costly mistake when trying to squeeze every last byte.

File: doc/release-notes-31384.md [hunk 27]
```diff
@@ -0,0 +1,25 @@
...
+- **PR #31384** fixed an issue where block reserved weight for coinbase transaction and headers
+ was done in two separate places. When the node constructs a new block, e.g. a `getblocktemplate`
+ RPC call doesn't generate the coinbase transaction. Instead, it reserves `4,000` weight units (WU)
+ for it and block header info. Before this pull request, the default for `-blockmaxweight` was `3,996,000`,
+ The mining code effectively added another `4,000` weight units (WU) to this reservation, leading to a template
+ size of `3,992,000`.
+
+- The fix consolidates the reservation into a single place and introduces a new startup option,
+  `-blockreservedweight` (default: `8,000` weight units). This option specifies the weight units
+ reserved for the coinbase transaction. The default value of `-blockreservedweight` was chosen
```
Comment (Sjors) [inline doc/release-notes-31384.md:14]: ad1bc03245181b00a25ea0182373eddae1c151e1: the header and

**Review by Sjors — COMMENTED** [review]
Code review ad1bc03245181b00a25ea0182373eddae1c151e1, mostly happy.

**Comment by 0xB10C** [comment]
> Prevent startup when user provided a -blockreservedweight lower than 2000 WU

Maybe @wangchun from F2Pool can confirm if this would work for F2Pool and how many weigh units they currently reserve. And if they do it with a custom patch or `-maxblockweight`.

**Comment by wincss** [comment]
> > Prevent startup when user provided a -blockreservedweight lower than 2000 WU
> 
> Maybe @wangchun from F2Pool can confirm if this would work for F2Pool and how many weigh units they currently reserve. And if they do it with a custom patch or `-maxblockweight`.

We (F2Pool) reserved 2000 WU for the coinbase transaction. This was achieved by patching the source code, ensuring that the check in `src/init.cpp` does not affect us.
In fact, we do not face the "duplicate reservation" issue because the same modification has already been applied in `src/policy/policy.h`.

**Comment by Sjors** [comment]
@wincss thanks for the clarification. You should be able to use `-blockreservedweight=2000 -maxblockweight` after this change. Is there anything else you need a patch for? Fee free to open a Github issue.

File: src/node/types.h [hunk 28]
```diff
@@ -34,11 +34,11 @@ struct BlockCreateOptions {
      */
     bool use_mempool{true};
     /**
-     * The maximum additional weight which the pool will add to the coinbase
-     * scriptSig, witness and outputs. This must include any additional
-     * weight needed for larger CompactSize encoded lengths.
+     * The default reserved weight for the coinbase (scriptSig, witness and outputs)
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply src/node/types.h]: Taken!

File: src/rpc/mining.cpp (hunk 22 above)
Comment (ismaelsadeeq) [reply src/rpc/mining.cpp]: fixed, even better I clarified that it also included the block header and txs count.

File: src/init.cpp (hunk 23 above)
Comment (ismaelsadeeq) [reply src/init.cpp]: Done

File: src/node/types.h (hunk 24 above)
Comment (ismaelsadeeq) [reply src/node/types.h]: Done

File: src/node/types.h (hunk 25 above)
Comment (ismaelsadeeq) [reply src/node/types.h]: Done

File: doc/release-notes-31384.md (hunk 27 above)
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md]: Done

**Comment by ismaelsadeeq** [comment]
Forced pushed from ad1bc03245181b00a25ea0182373eddae1c151e1 to fd3103142de8bcb92b5db6a6501c4c66abc12abd  see [diff](https://github.com/bitcoin/bitcoin/compare/ad1bc03245181b00a25ea0182373eddae1c151e1..fd3103142de8bcb92b5db6a6501c4c66abc12abd)

Changes
1.  Addressed @Sjors comments

**Comment by Sjors** [comment]
ACK fd3103142de8bcb92b5db6a6501c4c66abc12abd

**Comment by ismaelsadeeq** [comment]
Rebased due to conflict with #31583

**Comment by Sjors** [comment]
utACK fd4af64d58901334d907dd0bd38efd303a21374a

Solves a trivial rebase conflict in 9bbdcd84c8582f6a88ae01f207849c41bcb28380 where I added new fields to the `getmininginfo` (documentation).

**Review by pinheadmz — APPROVED** [review]
ACK fd4af64d58901334d907dd0bd38efd303a21374a

This patch consolidates two 4000 WU reservations into one constant, and adjusts configuration parameters to maintain existing behavior. It allows more fine tuned control of block template creation and in particular will allow some mining pools to squeeze an extra 4000 WU of transaction data into new blocks.

Reviewed each commit (again). Built and ran unit and functional tests on macos/arm.
I left a few if-you-touch nits below to improve clarity.

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK fd4af64d58901334d907dd0bd38efd303a21374a
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmedK0sACgkQ5+KYS2KJ
yToizxAAn4RmV88bUEtsgrCkjaQCXee9wsWaerz1cO8XYnbI3wqgc9xQ2lZh1C5X
nds8sazTFHLWWYScFH50eFE45CrPsW5wU9RLkKQofH60w0vOlyrITmVzYSHaGydV
O9xVSD2e2PLW5qHzBj52uGy33yWrXVYFyYvxonVJzC72aVKFqnsJr6Y3pAb0Asva
PzSyM5T1E1e8FULLoTBb2e9AMfVbXZtuosLW4fzRCi4WgctyJBsP/5pz/IuDBV88
FOp9/6d5bFpcsw9hQuJ5mBVerJ4NA7o2qRKOgvGbRFHH1s2ICYqlWbotJnpKDqkY
kvwTWUYIguD2r8gMh6r8fG+O/rS7HUUd5raEfg6iMHyJxzx5dqPmQ/vEEQconVRJ
pfeJ5vxbc609MXu/+JfBBApIvwRfOrIFYjCJ+yi5oJs0BR2Ka5gvf0bOfpAvKkMt
gRDzN1EsmhCNRKEqtYrUWZVD6E1iQbmMGf1ZuE5OnSJWWzb5otBaZgqR6OU2OGBE
z1gvtMzZxWN2q5LjtR6zL3cDlRSpnYzZ1xQ2xvuTr5nr84zmT8jITfEU3MJaQqB8
3l56ifbChppMdBb8IPI0cQzeaJqxkh/EZlAT/D/YhlXLKebigv2MxFgqe0s+aGVp
aSq3TuxH9uv4O6HYYAkHeqTbpXC4g6O4Qj107ck4C/6QLJvOQRM=
=GjoX
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

File: src/init.cpp [hunk 29]
```diff
@@ -1015,6 +1016,23 @@ bool AppInitParameterInteraction(const ArgsManager& args)
...
+    if (args.IsArgSet("-blockmaxweight")) {
+        const auto max_block_weight = args.GetIntArg("-blockmaxweight", DEFAULT_BLOCK_MAX_WEIGHT);
+        if (max_block_weight > DEFAULT_BLOCK_MAX_WEIGHT) {
+            return InitError(strprintf(_("Specified -blockmaxweight (%d) exceeds consensus maximum block weight (%d)"), max_block_weight, DEFAULT_BLOCK_MAX_WEIGHT));
+        }
+    }
+
+    if (args.IsArgSet("-blockreservedweight")) {
+        const auto block_reserved_weight = args.GetIntArg("-blockreservedweight", node::BlockCreateOptions{}.block_reserved_weight);
+        if (block_reserved_weight > DEFAULT_BLOCK_MAX_WEIGHT) {
```
Comment (fjahr) [inline src/init.cpp:1028]: Why not check this against `max_block_weight` instead? The current behavior isn't catastrophic I guess because the clamping later silently fixes this. But it seems like the user is doing something wrong and in the case below we are throwing an error too instead of silently fixing it. Seems a little inconsistent at least.

```suggestion
        if (block_reserved_weight > max_block_weight) {
```

**Review by fjahr — COMMENTED** [review]
Concept ACK

File: test/functional/mining_basic.py [hunk 30]
```diff
@@ -194,6 +196,87 @@ def test_pruning(self):
         assert_equal(result, "inconclusive")
         assert_equal(prune_node.getblock(pruned_blockhash, verbosity=0), pruned_block)
 
+
+    def send_transactions(self, utxos, fee_rate, target_vsize):
```
[the remark this answers is not in the document]
Comment (ismaelsadeeq) [reply test/functional/mining_basic.py:201]: IIUC `send_self_transfer_multi` is creating and broadcasting a single transaction spending multiple UTXO's, in this case I want to create multiple transactions each spending a single UTXO.

**Comment by fjahr** [comment]
> This patch consolidates two 4000 WU reservations into one constant, and adjusts configuration parameters to maintain existing behavior. It allows more fine tuned control of block template creation and in particular will allow some mining pools to squeeze an extra 4000 WU of transaction data into new blocks.

Only an extra 2000 WU, right? Before the change setting setting blockmaxheight to max led to the actual minimum reserved 4000 WU. After the change there is the explicit minimum of 2000 WU reserved. So the delta is 2000 WU. Or did I get something wrong?

File: src/init.cpp (hunk 29 above)
Comment (ismaelsadeeq) [reply src/init.cpp:1028]: My plan is to eventually remove the blockmaxweight option in a follow-up. See last sentence in [this comment](https://github.com/bitcoin/bitcoin/pull/31384#issuecomment-2567472713). The behavior you describe is an edge case that is possible, but as you said, the clamping fixes it.

I think it is consistent to compare using `DEFAULT_BLOCK_MAX_WEIGHT`  because, eventually, the block-reserved weight will be passed through the mining interface.

See the previous discussion on this [here](https://github.com/bitcoin/bitcoin/pull/31384#discussion_r1908522924).

**Comment by pinheadmz** [comment]
> Only an extra 2000 WU, right?

My understanding goes like this: 
Imagine a miner that never needs more than 4000 for their coinbase, and has always used default settings. Their blocks have left behind 4000 empty space. After this patch, that same miner continuing to use default settings will continue to leave 4000 empty space per block. But now with the patch that miner has the option of filling that space with transaction data using `-blockreservedweight=4000`

**Comment by ismaelsadeeq** [comment]
Thanks for your review, @pinheadmz and @fjahr.
I have answered the review questions and will address any nits when a retouch is needed.  

@fjahr, think of it this way:  

In the block assembler, we need to leave some space for the coinbase transaction, block header, and transaction count.  

Previously, we reserved this space in multiple places `4000 WU` twice.  
The `blockmaxweight` was described as `3996000 WU` because we intended to reserve space only once. However, due to duplicate reservations, the actual reserved weight was  `8000WU` resulting in our block template weight to be always below `3992000 WU`.

After this PR:  
- I updated the help text to indicate that the default `blockmaxweight` is `4000000 WU`.  
- I introduced a new option, `blockreservedweight`, allowing miners to customize the reserved space.  
- By default, `blockreservedweight` is set to `8000 WU` to maintain backward compatibility with previous behavior. 

However, miners can reduce this value if they don’t need that much reserved space.  
- For example, by setting `blockreservedweight=4000`, miners will now get blocks with a weight of `3996000 WU`, effectively claiming an extra 0.1 fee. which means they have `4000WU` more I think this is what @pinheadmz meant   

The minimum value for `blockreservedweight` is `2000 WU` because we determined that any value below that is too risky see comments before https://github.com/bitcoin/bitcoin/pull/31384#issuecomment-2591295705.  

Thus, the maximum block template weight that will be created after this change is `3998000 WU`, which is an increase of `6000 WU` compared to the previous behavior.

**Comment by fjahr** [comment]
@ismaelsadeeq @pinheadmz Ok, I see what you are trying to say. But if we are assuming the miner was smart and using the config options available to optimize, then they could have already reached `3996000 WU` by setting `blockmaxweight` to `4000000 WU` before this change, right? This is even mentioned in the release notes... Maybe the docs make it more realistic that miners actually do this but the comment was about behavior change, not the docs. So I think the actual delta made possible by the behavior change is just `2000 WU` and I think that is the fairest characterization.

It comes down to what behavior you expect of the miners: Miners before the change using defaults had `8000 WU` and with configs they could get down to `4000 WU`. After the change with defaults its `4000 WU` and with configs it's `2000 WU`. So the delta comparing default config miners is `4000 WU` and comparing 'smart' config optimizing miners is `2000 WU`. I think `6000 WU` is comparing apples to oranges a bit but you can argue that we can hope that his happens because miners read the new docs and thus are converting from default to 'smart'.

**Comment by ismaelsadeeq** [comment]
> But if we assume the miner was smart and used the available config options to optimize, they could have already reached 3,996,000 WU by setting `blockmaxweight` to 4,000,000 WU before this change, right?  

No, the current behavior on master is that we always reserve `8,000 WU`, regardless of what `blockmaxweight` is. This is actually how I discovered the issue.  

See this test https://github.com/ismaelsadeeq/bitcoin/commit/dbc17d1519247e366b39da54e87d0e866709d16a. It fails on master.  

So, I don’t think your intuition is right

**Comment by fjahr** [comment]
> No, the current behavior on master is that we always reserve 8,000 WU, regardless of what blockmaxweight is. This is actually how I discovered the issue.

Ok, I am very confused now. In the release notes you write this:

```
- Users who manually set `-blockmaxweight` to its maximum value `4,000,000` can lower
`-blockreservedweight` to `4,000` to maintain the previous behaviour.
```

So you are saying setting `-blockreservedweight` to `4,000` will give you a block with `8000 WU` reserved even after the change?

**Comment by fjahr** [comment]
> No, the current behavior on master is that we always reserve 8,000 WU, regardless of what blockmaxweight is. This is actually how I discovered the issue.

Maybe I am still not getting it but re-reading the release notes once more, I don't think they reflect this correctly. They seem to suggest that setting `-blockmaxweight` to `4,000,000` does change something. I think they need to explain what is actually happening so that miners can make the right decision. Worst case (though maybe a bit unlikely): A miner set `-blockmaxweight=4000000` and added a coinbase of `5,000 WU`, maybe not even measuring size, it just works (TM). But this only works because of the actual `8,000 WU` reserved. So the section I quoted above suggest that this miner could now switch to `-blockreservedweight` set to `4,000`. But from my understanding of the code change this creates a block with just `4,000 WU` reserved and when the miner adds their `5,000 WU` coinbase the block is invalid.

File: src/init.cpp [hunk 31]
```diff
@@ -648,6 +648,7 @@ void SetupServerArgs(ArgsManager& argsman, bool can_listen_ipc)
 
 
     argsman.AddArg("-blockmaxweight=<n>", strprintf("Set maximum BIP141 block weight (default: %d)", DEFAULT_BLOCK_MAX_WEIGHT), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
+    argsman.AddArg("-blockreservedweight=<n>", strprintf("Reserve space to account for the largest coinbase transaction that mining software may add to the block and the block header. (default: %d).", node::BlockCreateOptions{}.block_reserved_weight), ArgsManager::ALLOW_ANY, OptionsCategory::BLOCK_CREATION);
```
[the remark this answers is not in the document]
Comment (Sjors) [reply src/init.cpp:651]: Miners don't add the header though.

File: src/init.cpp (hunk 29 above)
Comment (Sjors) [reply src/init.cpp:1028]: Indeed, this could be `MAX_BLOCK_WEIGHT`, but definitely not `max_block_weight`.

The clamping does not prevent someone from creating a 4MB coinbase transaction while otherwise not mining anything by setting `-maxblockweight=0`. As nonsensical as that might be, but dropping `-blockmaxweight` seems better to discuss in a followup.

**Comment by Sjors** [comment]
@pinheadmz wrote:

> some mining pools to squeeze an extra 4000 WU of transaction data into new blocks

@fjahr wrote:

> Only an extra 2000 WU, right?

Just 2000 extra WU. They could already push the effective reservation to 4000 by setting `blockmaxweight=4000000` and there's a minimum value of `-blockreservedweight=2000`.

@ismaelsadeeq wrote:

> No, the current behavior on master is that we always reserve 8,000 WU, regardless of what blockmaxweight is. This is actually how I discovered the issue.

Now I'm confused as well.

**Comment by Sjors** [comment]
You're right though I think, the original code clamps like this:

```cpp
static BlockAssembler::Options ClampOptions(BlockAssembler::Options options)
{
    Assert(options.coinbase_max_additional_weight <= DEFAULT_BLOCK_MAX_WEIGHT);
    Assert(options.coinbase_output_max_additional_sigops <= MAX_BLOCK_SIGOPS_COST);
    // Limit weight to between coinbase_max_additional_weight and DEFAULT_BLOCK_MAX_WEIGHT for sanity:
    // Coinbase (reserved) outputs can safely exceed -blockmaxweight, but the rest of the block template will be empty.
    options.nBlockMaxWeight = std::clamp<size_t>(options.nBlockMaxWeight, options.coinbase_max_additional_weight, DEFAULT_BLOCK_MAX_WEIGHT);
    return options;
}
```

With `DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT - 4000};`

So setting `-blockmaxweight=4000000` was a placebo and we're indeed making it possible to squeeze another 6000 WU.

This requires some changes to the release note.

File: doc/release-notes-31384.md [hunk 32]
```diff
@@ -0,0 +1,25 @@
+- Node and Mining
+
+---
+
+- **PR #31384** fixed an issue where block reserved weight for block header, transactions count,
+ and coinbase transaction was done in two separate places. When the node constructs a new block,
+ e.g. a `getblocktemplate` RPC call doesn't generate the coinbase transaction. Instead, it reserves
+ `4,000` weight units (WU) for those data. Before this pull request, the default for `-blockmaxweight`
+ was `3,996,000`, The mining code effectively added another `4,000` weight units (WU) to this reservation,
+ leading to a template size of `3,992,000`.
```
Comment (Sjors) [inline doc/release-notes-31384.md:10]: We need to clarify this:

> was `3,996,000`,

to

> was `3,996,000` and any higher value was silently clamped to that.

File: src/init.cpp (hunk 31 above)
[the remark this answers is not in the document]
Comment (pinheadmz) [reply src/init.cpp:651]: Then perhaps something like "Reserve space for the fixed-size block header plus the largest coinbase transaction the mining software may add to the block"

File: doc/release-notes-31384.md (hunk 32 above)
Comment (fjahr) [reply doc/release-notes-31384.md:10]: And maybe

```suggestion
 leading to a minimum template size of `3,992,000` in any case.
```

File: doc/release-notes-31384.md [hunk 33]
```diff
@@ -0,0 +1,25 @@
...
+- The fix consolidates the reservation into a single place and introduces a new startup option,
+  `-blockreservedweight` (default: `8,000` weight units). This option specifies the weight units
+ reserved for the block header, transactions count, and coinbase transaction. The default value of
+ `-blockreservedweight` was chosen to preserve the previous behavior.
+
+- **Upgrade Note:** The default `-blockreservedweight` ensures backward compatibility for users who did not override
+  `-blockmaxweight` and relied on the previous behavior.
+
+- Users who manually set `-blockmaxweight` to its maximum value `4,000,000` can lower
+`-blockreservedweight` to `4,000` to maintain the previous behaviour.
```
[the remark this answers is not in the document]
Comment (fjahr) [reply doc/release-notes-31384.md:21]: And maybe add something like "Be careful about lowing -blockreservedweight to 4,000 and ensure that your coinbase transaction does indeed not exceed 4,000 since there were previously always 8,000 WU available".

[the remark this answers is not in the document]
Comment (Sjors) [reply doc/release-notes-31384.md:21]: coinbase transaction, the block header, etc?

File: doc/release-notes-31384.md (hunk 32 above)
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md:10]: thanks I will update

File: src/policy/policy.h [hunk 34]
```diff
@@ -20,7 +20,9 @@ class CFeeRate;
 class CScript;
 
 /** Default for -blockmaxweight, which controls the range of block weights the mining code will create **/
-static constexpr unsigned int DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT - 4000};
+static constexpr unsigned int DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT};
+/** The default reserved weight for the fixed-size block header, transaction count and coinbase transaction. **/
```
Comment (Sjors) [inline src/policy/policy.h:24]: In c961c509bc5d4a8c9e9197cad001d2b7598c8bd7 "miner: bugfix: fix duplicate weight reservation in block assembler": I'd rather keep the explanation in `types.h` since `BlockCreateOptions` is part of an external interface that should make sense without having to dig into internals.

File: src/init.cpp [hunk 35]
```diff
@@ -1015,6 +1015,13 @@ bool AppInitParameterInteraction(const ArgsManager& args)
         }
     }
 
+    if (args.IsArgSet("-blockmaxweight")) {
+        const auto max_block_weight = args.GetIntArg("-blockmaxweight", DEFAULT_BLOCK_MAX_WEIGHT);
+        if (max_block_weight > DEFAULT_BLOCK_MAX_WEIGHT) {
+            return InitError(strprintf(_("Specified -blockmaxweight (%d) exceeds policy default maximum block weight (%d)"), max_block_weight, DEFAULT_BLOCK_MAX_WEIGHT));
```
Comment (Sjors) [inline src/init.cpp:1022]: In 8b8e143a8fdd9c12068c7d7f5bbe5317dd55d22a "init: fail to start when `-blockmaxweight` exceeds `DEFAULT_MAX_BLOCK_WEIGHT`": I think this should only check against consensus.

File: src/init.cpp [hunk 36]
```diff
@@ -1022,6 +1023,16 @@ bool AppInitParameterInteraction(const ArgsManager& args)
         }
     }
 
+    if (args.IsArgSet("-blockreservedweight")) {
+        const auto block_reserved_weight = args.GetIntArg("-blockreservedweight", DEFAULT_BLOCK_RESERVED_WEIGHT);
```
Comment (Sjors) [inline src/init.cpp:1027]: In cd6cca1018f1c4b0c5d73991afbdb19d1b0b9682 "miner: init: add `-blockreservedweight` startup option"

Same as for the earlier commit, imo this should only check against the consensus limit.
https://github.com/bitcoin/bitcoin/pull/31384/commits/cd6cca1018f1c4b0c5d73991afbdb19d1b0b9682#r1938237527

File: src/init.cpp (hunk 35 above)
Comment (ismaelsadeeq) [reply src/init.cpp:1022]: In block assembly, we check against policy. If we were to lower the policy default, users could set a higher value than our policy limit, but the generated block would still be checked against policy, meaning their higher value would have no effect. I think we should be consistent and either check against policy everywhere or remove the policy default and check only against consensus?

File: src/policy/policy.h (hunk 34 above)
Comment (ismaelsadeeq) [reply src/policy/policy.h]: Done in this [push](https://github.com/bitcoin/bitcoin/compare/e7df348288e81dae104df7f8c984cb8eca57da35..6709e185b93d97b9191597acfecb25c33ab43a0a)
Also updated the release note to fix grammar

File: src/init.cpp (hunk 35 above)
Comment (Sjors) [reply src/init.cpp:1022]: Policy is what we put in blocks by default (`DEFAULT_BLOCK_MAX_WEIGHT`). If the user wants to override the default using `-blockmaxweight`, they should only be limited by consensus (`MAX_BLOCK_WEIGHT`).

> but the generated block would still be checked against policy, meaning their higher value would have no effect.

That would be a bug.

**Comment by Sjors** [comment]
Here's a patch that limits the use of `DEFAULT_BLOCK_MAX_WEIGHT` to defaults:

```diff
diff --git a/src/init.cpp b/src/init.cpp
index 41db01b129..f9eb466408 100644
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -19,6 +19,7 @@
 #include <common/args.h>
 #include <common/system.h>
 #include <consensus/amount.h>
+#include <consensus/consensus.h>
 #include <deploymentstatus.h>
 #include <hash.h>
 #include <httprpc.h>
@@ -1018,15 +1019,15 @@ bool AppInitParameterInteraction(const ArgsManager& args)
 
     if (args.IsArgSet("-blockmaxweight")) {
         const auto max_block_weight = args.GetIntArg("-blockmaxweight", DEFAULT_BLOCK_MAX_WEIGHT);
-        if (max_block_weight > DEFAULT_BLOCK_MAX_WEIGHT) {
-            return InitError(strprintf(_("Specified -blockmaxweight (%d) exceeds policy default maximum block weight (%d)"), max_block_weight, DEFAULT_BLOCK_MAX_WEIGHT));
+        if (max_block_weight > MAX_BLOCK_WEIGHT) {
+            return InitError(strprintf(_("Specified -blockmaxweight (%d) exceeds consensus limit (%d)"), max_block_weight, MAX_BLOCK_WEIGHT));
         }
     }
 
     if (args.IsArgSet("-blockreservedweight")) {
         const auto block_reserved_weight = args.GetIntArg("-blockreservedweight", DEFAULT_BLOCK_RESERVED_WEIGHT);
-        if (block_reserved_weight > DEFAULT_BLOCK_MAX_WEIGHT) {
-            return InitError(strprintf(_("Specified -blockreservedweight (%d) exceeds policy default maximum block weight (%d)"), block_reserved_weight, DEFAULT_BLOCK_MAX_WEIGHT));
+        if (block_reserved_weight > MAX_BLOCK_WEIGHT) {
+            return InitError(strprintf(_("Specified -blockreservedweight (%d) exceeds consensus maximum block weight (%d)"), block_reserved_weight, MAX_BLOCK_WEIGHT));
         }
         if (block_reserved_weight < MINIMUM_BLOCK_RESERVED_WEIGHT) {
             return InitError(strprintf(_("Specified -blockreservedweight (%d) is lower than minimum safety value of (%d)"), block_reserved_weight, MINIMUM_BLOCK_RESERVED_WEIGHT));
diff --git a/src/node/miner.cpp b/src/node/miner.cpp
index 091cb436dc..ca4d65ee08 100644
--- a/src/node/miner.cpp
+++ b/src/node/miner.cpp
@@ -67,12 +67,12 @@ void RegenerateCommitments(CBlock& block, ChainstateManager& chainman)
 
 static BlockAssembler::Options ClampOptions(BlockAssembler::Options options)
 {
-    Assert(options.block_reserved_weight <= DEFAULT_BLOCK_MAX_WEIGHT);
+    Assert(options.block_reserved_weight <= MAX_BLOCK_WEIGHT);
     Assert(options.block_reserved_weight >= MINIMUM_BLOCK_RESERVED_WEIGHT);
     Assert(options.coinbase_output_max_additional_sigops <= MAX_BLOCK_SIGOPS_COST);
-    // Limit weight to between block_reserved_weight and DEFAULT_BLOCK_MAX_WEIGHT for sanity:
+    // Limit weight to between block_reserved_weight and MAX_BLOCK_WEIGHT for sanity:
     // block_reserved_weight can safely exceed -blockmaxweight, but the rest of the block template will be empty.
-    options.nBlockMaxWeight = std::clamp<size_t>(options.nBlockMaxWeight, options.block_reserved_weight, DEFAULT_BLOCK_MAX_WEIGHT);
+    options.nBlockMaxWeight = std::clamp<size_t>(options.nBlockMaxWeight, options.block_reserved_weight, MAX_BLOCK_WEIGHT);
     return options;
 }
```

Dropping `-maxblockweight` entirely, along with `DEFAULT_BLOCK_MAX_WEIGHT`, would simplify things, but better left to a followup.

File: src/init.cpp (hunk 36 above)
Comment (ismaelsadeeq) [reply src/init.cpp:1028]: Done!

File: src/init.cpp (hunk 35 above)
Comment (ismaelsadeeq) [reply src/init.cpp]: Fixed!

**Comment by ismaelsadeeq** [comment]
Force-pushed from 6709e185b93d97b9191597acfecb25c33ab43a0a to 386eecff5f14d508688e6e7374b67cb54aaa7249. 

See [6709e185b9....386eecff5f14](https://github.com/bitcoin/bitcoin/compare/6709e185b93d97b9191597acfecb25c33ab43a0a..386eecff5f14d508688e6e7374b67cb54aaa7249)

- The changes in this push ensure that the consensus `MAX_BLOCK_WEIGHT` is used in block assembler instead of a policy constant `DEFAULT_BLOCK_MAX_WEIGHT`. 
   - The policy value is only used when the user has not provided a custom value. 
   - Currently, this value matches the consensus limit. 
   - Using the consensus limit instead of the policy value prevents bugs, such as the one on the master branch, where clamping to the policy default would prevent user specified higher values from taking effect described in detail in https://github.com/bitcoin/bitcoin/pull/31384/commits/386eecff5f14d508688e6e7374b67cb54aaa7249

- Docs changes

C.I failure seems to be unrelated.

**Comment by fjahr** [comment]
> C.I failure seems to be unrelated.

It does indeed but so far 5 jobs have failed so it might be better to kick the CI since it could be that the unrelated (early) fail masks an actual issue in one of them. I've just asked for this on IRC.

**Review by fjahr — COMMENTED** [review]
Looking good, just curious about the fuzzer change.

I left comments there but I don't want to bikeshed the release notes too much, so feel free to ignore them unless you have to retouch or don't want to address them.

File: src/test/fuzz/mini_miner.cpp [hunk 37]
```diff
@@ -157,9 +158,10 @@ FUZZ_TARGET(mini_miner_selection, .init = initialize_miner)
             }
         }
 
-        // Stop if pool reaches DEFAULT_BLOCK_MAX_WEIGHT because BlockAssembler will stop when the
+        const auto block_adjusted_max_weight = MAX_BLOCK_WEIGHT - DEFAULT_BLOCK_RESERVED_WEIGHT;
```
[the remark this answers is not in the document]
Comment (Sjors) [reply src/test/fuzz/mini_miner.cpp:161]: Agreed (though can wait for a followup).

For the fuzzer it's probably best to push the most extreme value a user can achieve without recompilation.

File: doc/release-notes-31384.md [hunk 38]
```diff
@@ -0,0 +1,34 @@
+- Node and Mining
+
+---
+
+- **PR #31384** fixed an issue where block reserved weight for fixed-size block header, transactions count,
+  and coinbase transaction was done in two separate places.
+  Before this pull request, the policy default for the maximum block weight was `3,996,000` WU, calculated by
+  subtracting `4,000 WU` from the `4,000,000 WU` consensus limit to account for the fixed-size block header,
+  transactions count, and coinbase transaction. During block assembly, Bitcoin Core clamped custom `-blockmaxweight`
+  value to not be more than the policy default.
```
[the remark this answers is not in the document]
Comment (Sjors) [reply doc/release-notes-31384.md:10]: The word "policy" generally refers to the mempool, so I agree it could be confusing to use that term here. "the default" should be fine.

**Comment by Sjors** [comment]
ACK 386eecff5f14d508688e6e7374b67cb54aaa7249

(I didn't study the release notes again, but those can be changed later anyway)

File: src/test/fuzz/mini_miner.cpp (hunk 37 above)
[the remark this answers is not in the document]
Comment (fjahr) [reply src/test/fuzz/mini_miner.cpp:161]: Ok, granted I didn't study the whole fuzz test before I wrote this. I think it can still be done but I will try to address this in a small follow-up so this doesn't hold up this PR.

**Comment by fjahr** [comment]
Code review ACK 386eecff5f14d508688e6e7374b67cb54aaa7249

Further editing of the release notes can be done as part of the actual release process.

File: src/policy/policy.h [hunk 39]
```diff
@@ -21,7 +21,13 @@ class CScript;
 
 /** Default for -blockmaxweight, which controls the range of block weights the mining code will create **/
 static constexpr unsigned int DEFAULT_BLOCK_MAX_WEIGHT{MAX_BLOCK_WEIGHT};
+/** Default for -blockreservedweight **/
 static constexpr unsigned int DEFAULT_BLOCK_RESERVED_WEIGHT{8000};
+/** This accounts for the block header, var_int encoding of the transaction count and a minimally viable
+ * coinbase transaction. It adds an additional safety margin, because even with a thorough understanding
+ * of block serialization, it's easy to make a costly mistake when trying to squeeze every last byte.
+ * Setting a lower value is prevented at startup. */
+static constexpr unsigned int MINIMUM_BLOCK_RESERVED_WEIGHT{2000};
```
Comment (glozow) [inline src/policy/policy.h]: nit: maybe all of these should live in miner.h?

File: doc/release-notes-31384.md [hunk 40]
```diff
@@ -0,0 +1,34 @@
...
+
+  Users who manually set `-blockmaxweight` to its maximum value of `4,000,000 WU` should be aware that this
+  value previously had no effect since it was clamped to `3,996,000 WU`.
+
+  Users lowering `-blockreservedweight` should ensure that the total weight (for the block header, transaction count, and coinbase transaction)
+   does not exceed the reduced value.
+
+  As a safety check, Bitcoin core will **fail to start** when `-blockreservedweight` init parameter value is lower than `2000` weight units.
+
+  Bitcoin Core will also **fail to start** if the `-blockmaxweight` or `-blockreservedweight` init parameter exceeds
```
Comment (glozow) [inline doc/release-notes-31384.md:33]: Maybe also clearly state how they interact? What if you set `-blockreservedweight` higher than `-blockmaxweight`?

**Review by glozow — COMMENTED** [review]
utACK 386eecff5f14d508688e6e7374b67cb54aaa7249, nonblocking nits. I do think the release notes should be clarified more

File: src/policy/policy.h (hunk 39 above)
Comment (Sjors) [reply src/policy/policy.h]: I guess it's a philosophical question. There's mempool policy and there's the defaults we set for miners, which typically match. But the `*_WEIGHT` constants here have no effect on the mempool, so are they policy?

But there's another consideration: `miner.{h,cpp}` consists mostly of utility code, and so doesn't seem like a good place to put these important constants. We could introduce `mining_defaults.h`, but it seems simpler to keep them here.

File: doc/release-notes-31384.md (hunk 40 above)
Comment (Sjors) [reply doc/release-notes-31384.md:33]: That's an absurd thing to do, so I'm worried that explaining it just makes the text hard to follow. That could miners to ignore the import warning about setting this value too low.

Comment (glozow) [reply doc/release-notes-31384.md:33]: Or have a test for the expected behavior? A comment in the options-handling code? I don't think it should be unspecified.

File: src/policy/policy.h (hunk 39 above)
Comment (glozow) [reply src/policy/policy.h]: Meh good point miner policy is policy, resolving.

File: doc/release-notes-31384.md (hunk 40 above)
Comment (ismaelsadeeq) [reply doc/release-notes-31384.md:33]: There are two cases to this.

1. When the `-blockmaxweight` is default (`4,000,000 WU`), and you set a higher block reserved weight, the node will fail to start, there is a test for this in this PR


2. When `-blockmaxweight` is custom i.e lower that (`4,000,000 WU`) and you set a block reserved weight to a value
       a) > `4,000,000WU` the node will fail to start (There is a test for this)
        b) < `4000,000 WU` the node will start but all generated block template will be empty when the value is higher than the custom`-blockmaxweight` value. ( No test for this, and it's an absurd behavior as @Sjors mentioned I didn't add the test because we would want to removed `-blockmaxweight` in the future since we now have `-blockreservedweight`

Comment (Sjors) [reply doc/release-notes-31384.md:33]: It's explained in `BlockAssembler::Options ClampOptions`, though we should probably point to that from elsewhere.

Comment (ismaelsadeeq) [reply doc/release-notes-31384.md:33]: Also see https://github.com/bitcoin/bitcoin/pull/31384#discussion_r1937951204

Comment (Sjors) [reply doc/release-notes-31384.md:33]: (our comments came in at the same time)

Comment (glozow) [reply doc/release-notes-31384.md:33]: Ok, makes sense to get rid of `-blockmaxweight`. What do you think the plan for that should be? If I understand you correctly that users should really only use one of them, should we be deprecating it at the same time as introducing `-blockreservedweight`?

Comment (ismaelsadeeq) [reply doc/release-notes-31384.md:33]: I think we should deprecate it in next release and then remove it later.

Because ocean mining currently heavily rely on `-blockmaxweight`

**Review by pinheadmz — APPROVED** [review]
ACK 386eecff5f14d508688e6e7374b67cb54aaa7249

Minor changes since last ACK, addressing my comments: 
- Use consensus values instead of policy
- Define `DEFAULT_BLOCK_RESERVED_WEIGHT`
- Release notes updates, these have been bikeshed quite a bit. I'm happy with them but will continue to review changes there is others disagree.
<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 386eecff5f14d508688e6e7374b67cb54aaa7249
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmemZ+AACgkQ5+KYS2KJ
yTplexAAme9e8fU88TsuM3ZFaW5PTIaPpZoTOg5i0Vx2OCSEuEJK11iRGsGvy2yg
RXnG8wmn9HTUpR6xzFPLlgdty8IMFoAZWqegTj5/ftXlsI6QFxmOvjakg9a+rAPb
IhVNSkdHQe29yolrDoxVqy/CyQ/cdhciOOqrBXN20XkNDU7hzBuZNIUWAwgrbnLG
HPsXkxAV6RDSn3SzORW8QKrLtcC4u/0Qs/OvPgVLJscgREzyuOzRWD1F7oyzT/Mp
ARKIwus3UwndQ8Qee/bUfzTL+sYZw/bSakmIvQSeB31Olj2aNv/zQVIEcF+Cowv3
IienAhpT8RF25ZWl5vUFR633W9sVVxUIbKjG85dXvW6u+5r9L6s/TCdsavjWf+XD
EzGJSpzD8ca+OLnfCusN49IVSzgXsXITNg2mnX7C5KFEDFWayx9cAhPRooCLOmKz
vxxblg1y/pLBWj33x+C0Utyv8wBlONu/JvBGN8wyQ1N1GMrawcJusP+I73/jKu8P
11xlR8BVdnBx5ZR8povwxlo4bAYD4n6jgW8BjcEjx0p2yQs2FDIZWhZhv1FIM2B4
vXJhjtc/RDMMq851r9LMoH+m6oy64oxWAa6XZOdIqdDJHHDlHgDMaHsbDLHllfDT
5ZltgoPTw14DnrKWfzHbby4aTNKtTgYgNB1dfOoBHGcQK8iXwk8=
=/Hay
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Comment by fjahr** [comment]
I gave it a shot and changed it to this:

"Due to a bug the default block reserved weight for fixed-size block header, transactions count, and coinbase transaction was reserved twice and could not be lowered further. As a result the total reserved weight was always `8,000 WU`, meaning that even when specifying a `-blockmaxweight` higher than the default (even to the max `4,000,000 WU`), the actual block size never exceeded `3,992,000 WU`.  The fix consolidates the reservation into a single place and introduces a new startup option, `-blockreservedweight` which specifies the reserved weight directly. The default value of `-blockreservedweight` is set to `8,000 WU` to ensure backward compatibility for users who relied on the previous behavior of `-blockmaxweight`. The minimum value is set at `2,000 WU`. Users setting `-blockreservedweight` below the default should ensure that the total weight of their block header, transaction count, and coinbase transaction does not exceed the reduced value or they may risk mining an invalid block."

Feel free to improve it further in the wiki.

**Comment by ismaelsadeeq** [comment]
Thanks for the ping @glozow I will amend the suggestions in the wiki
