### PR TITLE
http: fix submission during shutdown race

### LINKED ISSUE #34573: bug: uncaught exception from RPC invocation during shutdown
The new thread pool introduced in https://github.com/bitcoin/bitcoin/pull/33689 [will throw an exception](https://github.com/bitcoin/bitcoin/blob/07b924775e4ff5dbfb9f2e7549fd13db8ec5c61b/src/util/threadpool.h#L162) (which will not be caught and lead to an unclean exit) if an RPC is called during shutdown.

```
2026-02-11T18:56:34Z [http:debug] Received a POST request for / from 10.89.0.6:58998
2026-02-11T18:56:34Z [http:debug] Interrupting HTTP server
2026-02-11T18:56:34Z [rpc:debug] Interrupting HTTP RPC server
2026-02-11T18:56:34Z [all:info] http_pool_1 thread exit
2026-02-11T18:56:34Z [all:info] http_pool_0 thread exit
2026-02-11T18:56:34Z [rpc:debug] Interrupting RPC
terminate called after throwing an instance of 'std::runtime_error'
  what():  No active workers; cannot accept new tasks
```

*This was found with a test running on [Antithesis](https://antithesis.com/).*

### PR DESCRIPTION
**Pull request by furszy**
Fixes #34573.

As mentioned in https://github.com/bitcoin/bitcoin/issues/34573#issuecomment-3891596958, the ThreadPool PR (#33689) revealed an existing issue.

Before that PR, we were returning an incorrect error "Request rejected because http work queue depth exceeded" during shutdown for unhandled requests (we were not differentiating between "queue depth exceeded" and "server interrupted" errors). Now, with the ThreadPool inclusion, we return the proper error but we don't handle it properly.

This PR improves exactly that. Handling the missing error and properly returning it to the user.

The race can be reproduced as follows:

1) The server receives an http request.
2) Processing of the request is delayed, and shutdown is triggered in the meantime.
3) During shutdown, the libevent callback is unregistered and the threadpool interrupted.
4) The delayed request (step 2) resumes and tries to submit a task to the now-interrupted server.

Reproduction test can be found https://github.com/bitcoin/bitcoin/pull/34577#issuecomment-3902672521.

Also, to prevent this kind of issue from happening again, this PR changes task submission
to return the error as part of the function's return value using `util::Expected` instead of
throwing the exception. Unlike exceptions, which require extra try-catch blocks and can be
ignored, returning `Expected` forces callers to explicitly handle failures, and attributes
like `[[nodiscard]]` allow us catch unhandled ones at compile time.

### CODE REVIEW

File: src/test/threadpool_tests.cpp [hunk 1]
```diff
@@ -44,6 +44,13 @@ BOOST_FIXTURE_TEST_SUITE(threadpool_tests, ThreadPoolFixture)
         }                                                                         \
     } while (0)
 
+// Helper to unwrap a valid pool submission
+template <typename F> [[nodiscard]]
+auto Submit(ThreadPool& pool, F&& fn)
```
Comment (hodlinator) [inline src/test/threadpool_tests.cpp]: Nice helper! Was actually experimenting with changing `ThreadPool::Submit()` to return `util::Expected` yesterday (suffering from lack of knowledge of `std::invoke_result_t<F>` though). It was *so* cumbersome to adapt these test without realizing a helper would be useful. :)
 
nit: The going style seems to be `[[nodiscard]]` on the same line as the return type:

```C++
template <typename F>
[[nodiscard]] auto Submit(ThreadPool& pool, F&& fn)
```

Examples from master:
https://github.com/bitcoin/bitcoin/blob/07b924775e4ff5dbfb9f2e7549fd13db8ec5c61b/src/util/overflow.h#L14-L15
https://github.com/bitcoin/bitcoin/blob/07b924775e4ff5dbfb9f2e7549fd13db8ec5c61b/src/test/fuzz/util.h#L84-L85

Same style nit goes for `ThreadPool::Submit()`.

File: src/util/threadpool.h [hunk 2]
```diff
@@ -151,20 +153,20 @@ class ThreadPool
...
             LOCK(m_mutex);
             if (m_interrupt || m_workers.empty()) {
-                throw std::runtime_error("No active workers; cannot accept new tasks");
+                return util::Unexpected<std::string>("No active workers; cannot accept new tasks");
             }
             m_work_queue.emplace(std::move(task));
         }
         m_cv.notify_one();
-        return future;
+        return util::Expected<decltype(future), std::string>(std::move(future));
```
Comment (hodlinator) [inline src/util/threadpool.h]: nit: Can replace with:
```C++
        return {std::move(future)};
```

File: src/util/threadpool.h [hunk 3]
```diff
@@ -151,20 +153,20 @@ class ThreadPool
...
+    util::Expected<std::future<std::invoke_result_t<F>>, std::string> Submit(F&& fn) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
-        std::packaged_task task{std::forward<F>(fn)};
+        std::packaged_task<std::invoke_result_t<F>()> task{std::forward<F>(fn)};
         auto future{task.get_future()};
         {
             LOCK(m_mutex);
             if (m_interrupt || m_workers.empty()) {
-                throw std::runtime_error("No active workers; cannot accept new tasks");
+                return util::Unexpected<std::string>("No active workers; cannot accept new tasks");
```
Comment (hodlinator) [inline src/util/threadpool.h]: nit: No need to specify `Unexpected` template arg:
 ```suggestion
                 return util::Unexpected{"No active workers; cannot accept new tasks"};
```

File: src/httpserver.cpp [hunk 4]
```diff
@@ -276,7 +276,12 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
             req->WriteReply(HTTP_INTERNAL_SERVER_ERROR, err_msg);
         };
 
-        [[maybe_unused]] auto _{g_threadpool_http.Submit(std::move(item))};
+        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
+            LogWarning("Request rejected during server shutdown");
+            hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Request rejected during server shutdown");
+            return;
+        }
+
```
Comment (hodlinator) [inline src/httpserver.cpp]: meganit: Superfluous newline after `if`-block before end of outer block.

```suggestion
```

**Comment by andrewtoth** [comment]
> The race can be reproduced as follows:

Can this be made into a functional regression test?

File: src/httpserver.cpp [hunk 5]
```diff
@@ -211,7 +211,7 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
             }
         }
     }
-    auto hreq{std::make_unique<HTTPRequest>(req, *static_cast<const util::SignalInterrupt*>(arg))};
+    auto hreq{std::make_shared<HTTPRequest>(req, *static_cast<const util::SignalInterrupt*>(arg))};
```
Comment (hodlinator) [inline src/httpserver.cpp:214]: remark: Was experimenting with having `ThreadPool::Submit()` take a "task_creator" lambda that only gets called when no error condition in `Submit` occurs, it would then return the inner lambda which would take ownership of the `unique_ptr` as on master. Even though I have a distaste for `shared_ptr`, your version is more elegant.

File: src/test/fuzz/threadpool.cpp
Comment (hodlinator) [inline src/test/fuzz/threadpool.cpp:1]: Commit message suggestion for 241367d021d210f25e427e7bb35c676b293ff28a:
```diff
threadpool: make Submit return Expected instead of throwing

Unlike exceptions, which can be ignored as they require extra try-catch
blocks, returning expected errors forces callers to always handle
submission failures.

+ Not throwing an exception also happens to fix unclean shutdown bug
+ #34573 since we no longer throw when attempting to Submit() from http_request_cb().
```

**Comment by furszy** [comment]
> Can this be made into a functional regression test?

The "processing request is delayed" step means manually placing a `sleep()` inside the libevent callback `http_request_cb()` to progress on the server shutdown concurrently. Then we need to `sleep()` during shutdown, just after `InterruptHTTPServer()`, to resume the request processing before shutdown occurs.
So, the short answer is no. Sadly races aren't easy to replicate deterministically in functional tests.
We will surely be able to exercise more scenarios like this one, in unit tests, after the new http server inclusion (libevent removal path), which will bring better encapsulation.

That being said, could provide a `sleep()`-based patch to replicate it locally.

File: src/httpserver.cpp
Comment (hodlinator) [inline src/httpserver.cpp:1]: Commit message suggestion for 5326821cbffbef388421af082d43c7bc6bcc48f7:

Given that I think the unclean shutdown is already fixed in the first commit by using `util::Expected` instead of throwing exceptions, I think this is somewhat more correct for the second:
```
http: properly respond to HTTP request during shutdown

Makes sure we respond to the client as the HTTP request attempts to submit a task to
the threadpool during server shutdown.

Roughly what happens:

1) The server receives an HTTP request and starts calling http_request_cb().
2) Meanwhile on another thread, shutdown is triggered which calls InterruptHTTPServer()
   and unregisters http_request_cb() and interrupts the thread pool.
3) The request (step 1) resumes and tries to submit a task
   to the now-interrupted server.

This fix detects failed submissions immediately, and the server
responds with HTTP_SERVICE_UNAVAILABLE.
```
I don't think it's necessary to classify this as a race condition. I guess it depends on how you define it.

**Review by hodlinator — COMMENTED** [review]
Concept ACK 5326821cbffbef388421af082d43c7bc6bcc48f7

File: src/test/threadpool_tests.cpp (hunk 1 above)
Comment (furszy) [reply src/test/threadpool_tests.cpp]: Done as suggested. [[nodiscard]] inlined.
Also, credits to ryanofsky for the helper function idea <3. I was about to use a macro.

File: src/util/threadpool.h (hunk 2 above)
Comment (furszy) [reply src/util/threadpool.h]: Cool. Done as suggested. Thanks.

File: src/util/threadpool.h (hunk 3 above)
Comment (furszy) [reply src/util/threadpool.h]: Cool. Done as suggested. Thanks.

File: src/httpserver.cpp (hunk 4 above)
Comment (furszy) [reply src/httpserver.cpp]: Done.

File: src/test/fuzz/threadpool.cpp
Comment (furszy) [reply src/test/fuzz/threadpool.cpp:1]: Sure. Done as suggested. Thanks.

File: src/httpserver.cpp
Comment (furszy) [reply src/httpserver.cpp:1]: Taken, thanks!

> I don't think it's necessary to classify this as a race condition. I guess it depends on how you define it.

There is a thread (shutdown - main thread) modifying a resource (thread pool) just before another thread (libevent http handler) accesses it. It is pretty much a race condition to me.

**Comment by furszy** [comment]
Updated per feedback, thanks @hodlinator!

File: src/util/threadpool.h [hunk 6]
```diff
@@ -151,20 +153,20 @@ class ThreadPool
      * Note: Ignoring the returned future requires guarding the task against
      * uncaught exceptions, as they would otherwise be silently discarded.
      */
-    template <class F> [[nodiscard]] EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
-    auto Submit(F&& fn)
+    template <class F>
+    [[nodiscard]] util::Expected<std::future<std::invoke_result_t<F>>, std::string> Submit(F&& fn) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
```
Comment (andrewtoth) [inline src/util/threadpool.h]: Can this be `noexcept` now?

Comment (furszy) [reply src/util/threadpool.h]: Sure, done as suggested.

File: src/httpserver.cpp
Comment (hodlinator) [reply src/httpserver.cpp:1]: > There is a thread (shutdown - main thread) modifying a resource (thread pool) just before another thread (libevent http handler) accesses it. It is pretty much a race condition to me.

Fair.

File: src/httpserver.cpp [hunk 7]
```diff
@@ -276,7 +276,11 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
             req->WriteReply(HTTP_INTERNAL_SERVER_ERROR, err_msg);
         };
 
-        [[maybe_unused]] auto _{g_threadpool_http.Submit(std::move(item))};
+        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
+            LogWarning("Request rejected during server shutdown");
+            hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Request rejected during server shutdown");
+            return;
+        }
```
Comment (hodlinator) [inline src/httpserver.cpp:285]: 1. Log the inner error string (currently it's never read).
2. Even though we know it in the context of this PR/issue - I think it's a bit overly presumptuous to claim we are shutting down. All this outer logic knows is that `Submit()` failed. Would go with more neutral language.
```suggestion
        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
            LogWarning("Request rejected by thread pool: %s", res.error());
            hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Request rejected by thread pool");
            return;
        }
```
(I was experimenting with changing `ThreadPool::Submit()` to enforce the queue depth by itself, which would be another potential reason for it to fail).

**Comment by hodlinator** [comment]
Thanks for incorporating my earlier feedback btw!

File: src/httpserver.cpp (hunk 7 above)
Comment (furszy) [reply src/httpserver.cpp:285]: The `LogWarning` change makes sense, but the `WriteReply` one isn't really appropriate. Have in mind that `WriteReply` is an user-facing response, and referring to the "thread pool" there leaks internal details that do not help the user understand what happened nor what to do next.

> (I was experimenting with changing ThreadPool::Submit() to enforce the queue depth by itself, which would be another potential reason for it to fail).

I briefly thought about this and ended up discarding the idea because there is no other known use-case that requires it for now. Capping the pool is required when the pool faces user's requests, and all other applications we have for it are purely internal (parallel index sync, block inputs fetching, wallet rescan, kernel validation signals, etc). Ideally, we should only generalize features into the thread pool class only when we plan to use them in more than one place.

Comment (furszy) [reply src/httpserver.cpp:285]: We currently don't have a simple way to detect shutdown from within the libevent request callback to be able to differentiate between states, and we shouldn't pollute code just because of this. Submission can only fail because of a shutdown atm.
We will be able to access more information from within this function after the libevent removal path, as the new server provides better encapsulation.

Comment (hodlinator) [reply src/httpserver.cpp:285]: Yeah, I can agree on not being to specific with the internals in user-facing messages and omitting thread pool.
```suggestion
        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
            LogWarning("Request rejected by thread pool: %s", res.error());
            hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Request rejected, probably due to server shutdown");
            return;
        }
```
If you want to keep the current very assertive wording "Request rejected during server shutdown" I would suggest returning a one-value error `enum` instead of the `std::string` in `util::Expected` and having:

```suggestion
        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
            switch (res.error()) {
            case ThreadPool::SubmitError::Interrupted:
                LogWarning("Request rejected during server shutdown");
                hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Request rejected during server shutdown");
                return;
            } // no default case, so the compiler can warn about missing cases
        }
```

Comment (hodlinator) [reply src/httpserver.cpp:285]: > I briefly thought about this and ended up discarding the idea because there is no other known use-case that requires it for now. Capping the pool is required when the pool faces user's requests, and all other applications we have for it are purely internal (parallel index sync, block inputs fetching, wallet rescan, kernel validation signals, etc). Ideally, we should only generalize features into the thread pool class only when we plan to use them in more than one place.

I was worried about multiple threads calling `Submit()` and doing the queue depth check on the outside in a racy way where they both pass and then both `Submit()` and exceed the depth by one. But libevent probably only calls `http_request_cb()` from one thread so we should be fine right now. Thanks for laying out your reasoning, makes sense.

Comment (furszy) [reply src/httpserver.cpp:285]: > If you want to keep the current very assertive wording "Request rejected during server shutdown" I would suggest returning a one-value error enum instead of the std::string in util::Expected

I'm not convinced we should add an error code enum when we’re not expecting to expand it anytime soon. It would force everyone using the pool to add a bunch of boilerplate code for no real gain.
We could differentiate states now, without waiting for the post-libevent encapsulation, by checking whether the pool was interrupted too. Still, it feels like overthinking this for no real reason.
I would focus on fixing the issue here and keep the code simple for now. We can always adapt/modify it when more pool use-cases get merged.

Comment (hodlinator) [reply src/httpserver.cpp:285]: True, I am probably somewhat biased by my earlier experiments. Maybe it would be cleaner for `Submit()` to return `std::optional<std::future<std::invoke_result_t<F>>>` instead of `util::Expected<std::future<std::invoke_result_t<F>>, std::string>` after all - as long as there is only one single cause of failure?

Comment (furszy) [reply src/httpserver.cpp:285]: > Maybe it would be cleaner for `Submit()` to return `std::optional<std::future<std::invoke_result_t<F>>>` instead of `util::Expected<std::future<std::invoke_result_t<F>>, std::string>` after all - as long as there is only one single cause of failure?

Hmm, good observation. Thinking further.. there are currently two possible errors during submission that are currently under the same error message: 1) a non-started pool and 2) an interrupted pool. The first one is actually a logical error rather than one during runtime, and we should probably assert/assume that cannot happen. Will think more about this.

**Comment by andrewtoth** [comment]
> That being said, could provide a sleep()-based patch to replicate it locally.

Here is a diff, along with a functional test `rpc_http_shutdown_race.py`. Applying this to the base commit 07b924775e4ff5dbfb9f2e7549fd13db8ec5c61b will fail with a remote disconnected error, and applying to this patch 542879da7b66e890d2c1bf668ab5680e939541f8 will pass. 

```diff
diff --git a/src/httpserver.cpp b/src/httpserver.cpp
index 671e119642..d2de754183 100644
--- a/src/httpserver.cpp
+++ b/src/httpserver.cpp
@@ -18,6 +18,7 @@
 #include <util/strencodings.h>
 #include <util/threadnames.h>
 #include <util/threadpool.h>
+#include <util/time.h>
 #include <util/translation.h>
 
 #include <condition_variable>
@@ -257,6 +258,7 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
             hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Work queue depth exceeded");
             return;
         }
+        UninterruptibleSleep(2s);
 
         auto item = [req = std::move(hreq), in_path = std::move(path), fn = i->handler]() {
             std::string err_msg;
@@ -446,6 +448,7 @@ void InterruptHTTPServer()
     }
     // Interrupt pool after disabling requests
     g_threadpool_http.Interrupt();
+    UninterruptibleSleep(2s);
 }
 
 void StopHTTPServer()
diff --git a/test/functional/rpc_http_shutdown_race.py b/test/functional/rpc_http_shutdown_race.py
new file mode 100755
index 0000000000..f91cdee9f3
--- /dev/null
+++ b/test/functional/rpc_http_shutdown_race.py
@@ -0,0 +1,42 @@
+#!/usr/bin/env python3
+# Copyright (c) The Bitcoin Core developers
+# Distributed under the MIT software license, see the accompanying
+# file COPYING or http://www.opensource.org/licenses/mit-license.php.
+"""Test that an in-flight RPC during shutdown receives 503."""
+
+from test_framework.test_framework import BitcoinTestFramework
+from test_framework.util import assert_equal, str_to_b64str
+
+import http.client
+import urllib.parse
+
+class RpcHttpShutdownRaceTest(BitcoinTestFramework):
+    def set_test_params(self):
+        self.num_nodes = 1
+        self.setup_clean_chain = True
+
+    def run_test(self):
+        url = urllib.parse.urlparse(self.nodes[0].url)
+        authpair = f"{url.username}:{url.password}"
+        headers = {"Authorization": f"Basic {str_to_b64str(authpair)}"}
+
+        conn = http.client.HTTPConnection(url.hostname, url.port, timeout=10)
+        conn.connect()
+        conn.request("POST", "/", '{"method":"getblockchaininfo","id":1}', headers)
+
+        # Trigger shutdown outside RPC callback path so the in-flight request
+        # is interrupted before submitting to the pool.
+        self.nodes[0].process.terminate()
+
+        resp = conn.getresponse()
+        body = resp.read()
+        assert_equal(resp.status, http.client.SERVICE_UNAVAILABLE)
+        assert b"Request rejected during server shutdown" in body
+        node = self.nodes[0]
+        self.wait_until(lambda: node.process.poll() is not None, timeout=20)
+        stderr = node.stderr.read().decode("utf-8", errors="replace").strip()
+        node.is_node_stopped(expected_stderr=stderr, expected_ret_code=node.process.returncode)
+
+
+if __name__ == '__main__':
+    RpcHttpShutdownRaceTest(__file__).main()
diff --git a/test/functional/test_runner.py b/test/functional/test_runner.py
index cdfa8c1022..0d21907677 100755
--- a/test/functional/test_runner.py
+++ b/test/functional/test_runner.py
@@ -201,6 +201,7 @@ BASE_SCRIPTS = [
     'wallet_reindex.py',
     'wallet_reorgsrestore.py',
     'interface_http.py',
+    'rpc_http_shutdown_race.py',
     'interface_rpc.py',
     'interface_usdt_coinselection.py',
     'interface_usdt_mempool.py',
```

File: src/httpserver.cpp (hunk 7 above)
Comment (andrewtoth) [reply src/httpserver.cpp:285]: I think `Expected` is the appropriate return value here. It is an unexpected failure to submit a task, rather than the result being "not found" or "not existing" as a `nullopt` would imply.

**Review by andrewtoth — APPROVED** [review]
ACK 542879da7b66e890d2c1bf668ab5680e939541f8

This fixes the unclean shutdown race condition. It's too bad we can't have a regression test without adding sleeps.

**Comment by furszy** [comment]
Thanks for the reproduction patch @andrewtoth! Added link to the PR description.

> This fixes the unclean shutdown race condition. It's too bad we can't have a regression test without adding sleeps.

A small reflection about this.

We can't expect to be able to cover everything in functional tests. Simply because they live on a higher level and have no access to internals to exercise race conditions.

These types of scenarios belong to the unit tests land. But for that to happen, the surrounding code has to be properly encapsulated. Which is not the case for the http server, as there is currently no class for it, we basically import an entire file with global variables and static functions (and up to a few days ago, we had no tests for the work queue at all and this race condition was already there, just hidden returning an incorrect error message instead).

The only way to replicate scenarios like this one atm, on a unit test, would be to manually copy paste startup and shutdown. Which is not really scalable nor maintainable.

Still, we will get better soon, the libevent removal path @pinheadmz is working on also brings better encapsulation that we can use to deeply cover the area.

File: src/httpserver.cpp (hunk 7 above)
Comment (hodlinator) [reply src/httpserver.cpp:285]: `optional` doesn't strictly mean "found/not found", IMO it's closer to "may be set or not". `Submit()` is not a query type function, we are submitting to a thread pool and should be getting a `std::future` back.

The user-code and messages here immediately draw the conclusion that failure to submit means we are shutting down, so it is not *that* unexpected. Having a string as the error approaches stringly typed coding which should also be avoided (potentially returning different strings for different error conditions makes user code worse).

As long as we only have one combined error condition (not started *or* interrupted), I think `optional` makes the most sense. If we separate the two I think `util::Unexpected{enum SubmitError { NotStarted, Interrupted }}` makes more sense.

PS. I'm sorry if this feels nit-picky, I would probably let it slide if it was more of a leaf-type component.

Comment (furszy) [reply src/httpserver.cpp:285]: I went one step back and asked myself why added the submission exception in the first place (3.5 years ago). Should have remembered the reasoning sooner and not gotten obnubilated by our new shiny `util::Expected` toy.. sorry.

Thread pools are a well-studied structure, and most languages and libraries handle submission errors in the same way:
* Java's ExecutorService throws `RejectedExecutionException` after shutdown().
* Python's `ThreadPoolExecutor` raises a `RuntimeError` after shutdown().
* Boost.Asio treats submission after stop or shutdown as misuse.

So, the principle is the same everywhere: a thread pool is a resource with a lifecycle. Once you cross the shutdown boundary, submitting work isn't normal control flow anymore, and it should be treated differently.

For us, that means:
* "Pool not started": that's a bug in the calling code. We can either Assume it or throw a `logic_error`. Callers can't recover from this anyway.
* "Pool interrupted": is a hard lifecycle boundary. Submitting after `Interrupt()` should throw a dedicated `interrupted_exception`. Not everyone has to worry about this.
* Otherwise: strong guarantee. If you get a future back, your task will run.

Will re-accommodate the code to follow this principles again. I'm inclined towards being consistent with existing libraries and not reinvent the wheel.

Let me know if you guys have any reservation about this.

File: src/util/threadpool.h [hunk 8]
```diff
@@ -17,6 +18,7 @@
 #include <queue>
 #include <stdexcept>
 #include <thread>
+#include <type_traits>
 #include <utility>
 #include <vector>
```
Comment (ismaelsadeeq) [inline src/util/threadpool.h:23]: In "threadpool: make Submit return Expected instead of throwing" 818e2edadc11dca226539ddee945f0acf6e53814

This introduces inconsistency. In `Start`, we throw a runtime error as a result of multiple calls to `Start`, or possibly an exception could occur when thread creation fails for some reason. 

 I'm also a bit conflicted here. Why are we using `util::Expected`? Shouldn't the client be patched to handle throws when interacting with the thread pool? It's likely that we throw for some cases, and still back to an issue like the unclean shutdown we are fixing here?

**Review by ismaelsadeeq — COMMENTED** [review]
Concept ACK

@furszy, it would be nice if you share a branch with a reproducer. 

edit: see https://github.com/bitcoin/bitcoin/pull/34577#issuecomment-3902672521 for reproducer

File: src/util/threadpool.h (hunk 8 above)
Comment (furszy) [reply src/util/threadpool.h:23]: Yes. Please see https://github.com/bitcoin/bitcoin/pull/34577#discussion_r2813012276. Same conclusion there. I'm changing the current PR approach now. I shouldn't have gotten obnubilated by our shiny new `util::Expected` toy.

File: src/httpserver.cpp (hunk 7 above)
Comment (hodlinator) [reply src/httpserver.cpp:285]: I think the way Java and Python throw exceptions is dated. It's what got us into the situation with this PR in the first place, returning an error by value is a safer pattern IMO. That's why Rust opted to not support exceptions.

File: src/util/threadpool.h (hunk 8 above)
Comment (hodlinator) [reply src/util/threadpool.h:23]: `Start()` could probably `Assume()` or `assert()` instead of throw, it seems to be a bit of a logic error to `Start()` twice without stopping.

File: src/httpserver.cpp (hunk 7 above)
Comment (furszy) [reply src/httpserver.cpp:285]: > I think the way Java and Python throw exceptions is dated. It's what got us into the situation with this PR in the first place, returning an error by value is a safer pattern IMO. That's why Rust opted to not support exceptions.

It seems low-level Rust panics/aborts when submitting a task to an interrupted pool. What they have is a `try_spawn` wrapper (`TrySubmit` for us) that behaves in the way you describe. See [rusty_pool](https://docs.rs/rusty_pool/latest/rusty_pool/struct.ThreadPool.html#method.spawn) or [tokio-threadpool](https://docs.rs/tokio-threadpool/latest/tokio_threadpool/struct.ThreadPool.html#method.spawn).

>  It's what got us into the situation with this PR in the first place

Well, realistically speaking, the race was already there. We were returning the wrong error message before. The exception actually helped us catch it.

Comment (andrewtoth) [reply src/httpserver.cpp:285]: Agree with @hodlinator. Changing to exceptions is a step backwards. Modern error handling should use `std::expected`, which we can't use yet.
Also agree to use an enum for the different error cases, instead of using a std::optional. It's ok if we don't check the value yet in production code, but we can update the test cases to assert the proper error.

File: src/util/threadpool.h (hunk 8 above)
Comment (andrewtoth) [reply src/util/threadpool.h:23]: > obnubilated

lol

Throwing exceptions should be deprecated IMO, and we should aim to use the more modern `Expected` approach for errors. If an error is unrecoverable, `abort` instead of throwing an exception.

File: src/httpserver.cpp (hunk 7 above)
Comment (andrewtoth) [reply src/httpserver.cpp:285]: > Well, realistically speaking, the race was already there. We were returning the wrong error message before. The exception actually helped us catch it.

The previous race would return an error to the caller. The exception caused the node to crash. Using `Expected` prevents this kind of error from occurring because the caller is forced to handle the error instead of forgetting to wrap in try/catch.

File: src/util/threadpool.h (hunk 8 above)
Comment (sedited) [reply src/util/threadpool.h:23]: > Throwing exceptions should be deprecated IMO

I disagree with this as a general statement. For example, throwing an exception is the standard way to indicate an error in a constructor, as utilized all over the standard library. We also use the standard library very extensively, which makes extensive use of exceptions, and will require us to handle them for as long as we use it.

Comment (andrewtoth) [reply src/util/threadpool.h:23]: Right, we can't return an `Expected` from a constructor like we can return a `Result` in Rust when creating an object. Other than that, though, I don't think there's a need to throw an exception. We still need to catch exceptions, of course. I didn't suggest we stop doing that!

File: src/httpserver.cpp (hunk 7 above)
Comment (furszy) [reply src/httpserver.cpp:285]: > The previous race would return an error to the caller. The exception caused the node to crash. Using Expected prevents this kind of error from occurring because the caller is forced to handle the error instead of forgetting to wrap in try/catch.

Yes, that’s pretty much the PR description. What I meant above is that it’s great we’re here, because it means we’ve caught something new. That comment at least wasn't a pro exceptions argument. It was a pro thread pool inclusion argument really.

File: src/util/threadpool.h [hunk 9]
```diff
@@ -208,4 +223,15 @@ class ThreadPool
     }
 };
 
+static constexpr std::string_view SubmitErrorString(ThreadPool::SubmitError err) noexcept {
```
Comment (hodlinator) [inline src/util/threadpool.h]: `static` on a free function means that it should be local to the translation unit without any exported symbols. AFAIK we only use it for functions in .CPP files. `inline` would make more sense, but is already implied by `constexpr`.

```suggestion
constexpr std::string_view SubmitErrorString(ThreadPool::SubmitError err) noexcept {
```

File: src/httpserver.cpp
Comment (hodlinator) [inline src/httpserver.cpp:462]: IMO stopping the `ThreadPool` before we stop the libevent [dispatch loop](https://libevent.org/libevent-book/Ref3_eventloop.html) is the wrong order. Would ideally do something like the following patch:

<details><summary>Patch for HTTP shutdown order</summary>

```diff
http: Correct shutdown order of libevent vs ThreadPool

g_threadpool_http is initialized before the libevent dispatch loop in g_thread_http,
so it should be deinitialized in the reverse order. Exit the event loop first so
that we stop trying to Submit() new tasks to the pool before stopping it. (We will
still interrupt the pool earlier on, so submission-attempts can still fail).

Also:
* Delete the accept sockets before exiting the loop.
* Free eventHTTP from our own thread as events are no longer processed (this also fixes a frequent memory leak where eventHTTP would not be freed).

diff --git a/src/httpserver.cpp b/src/httpserver.cpp
index 578c4ec693..ec821dd0b0 100644
--- a/src/httpserver.cpp
+++ b/src/httpserver.cpp
@@ -457,15 +457,20 @@ void StopHTTPServer()
 {
     LogDebug(BCLog::HTTP, "Stopping HTTP server\n");
 
-    LogDebug(BCLog::HTTP, "Waiting for HTTP worker threads to exit\n");
-    g_threadpool_http.Stop();
-
-    // Unlisten sockets, these are what make the event loop running, which means
-    // that after this and all connections are closed the event loop will quit.
+    // Unlisten sockets
     for (evhttp_bound_socket *socket : boundSockets) {
         evhttp_del_accept_socket(eventHTTP, socket);
     }
     boundSockets.clear();
+
+    if (eventBase) {
+        LogDebug(BCLog::HTTP, "Finishing processing of event loop callbacks\n");
+        event_base_loopexit(eventBase, nullptr);
+    }
+
+    LogDebug(BCLog::HTTP, "Waiting for HTTP worker threads to exit\n");
+    g_threadpool_http.Stop();
+
     {
         if (const auto n_connections{g_requests.CountActiveConnections()}; n_connections != 0) {
             LogDebug(BCLog::HTTP, "Waiting for %d connections to stop HTTP server\n", n_connections);
@@ -473,13 +478,8 @@ void StopHTTPServer()
         g_requests.WaitUntilEmpty();
     }
     if (eventHTTP) {
-        // Schedule a callback to call evhttp_free in the event base thread, so
-        // that evhttp_free does not need to be called again after the handling
-        // of unfinished request connections that follows.
-        event_base_once(eventBase, -1, EV_TIMEOUT, [](evutil_socket_t, short, void*) {
-            evhttp_free(eventHTTP);
-            eventHTTP = nullptr;
-        }, nullptr, nullptr);
+        evhttp_free(eventHTTP);
+        eventHTTP = nullptr;
     }
     if (eventBase) {
         LogDebug(BCLog::HTTP, "Waiting for HTTP event thread to exit\n");
```

</details>

Doing the above allows for merging the `ThreadPool`'s constructor with `Start()` and merging the destructor with `Stop()`.
* This follows from not allowing calling `Start()` twice, which is implicit in a constructor. The new assert in `Start()` becomes unnecessary.
* Having `Stop()` logic only happen during destruction also implies that only a single thread should have access to the `ThreadPool` instance at that time. This would prevent the potential race condition I found here: https://github.com/bitcoin/bitcoin/pull/34562#discussion_r2800811310

<details><summary>Patch to merge ThreadPool ctor with Start() and dtor with Stop()</summary>

```diff
util: Merge ThreadPool ctor with Start(), and ThreadPool dtor with Stop().

HTTP now wraps the pool in std::optional.

diff --git a/src/httpserver.cpp b/src/httpserver.cpp
index ec821dd0b0..8ca5b7771e 100644
--- a/src/httpserver.cpp
+++ b/src/httpserver.cpp
@@ -75,7 +75,7 @@ static std::vector<HTTPPathHandler> pathHandlers GUARDED_BY(g_httppathhandlers_m
 //! Bound listening sockets
 static std::vector<evhttp_bound_socket *> boundSockets;
 //! Http thread pool - future: encapsulate in HttpContext
-static ThreadPool g_threadpool_http("http");
+static std::optional<ThreadPool> g_threadpool_http;
 static int g_max_queue_depth{100};
 
 /**
@@ -252,7 +252,7 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
 
     // Dispatch to worker thread
     if (i != iend) {
-        if (static_cast<int>(g_threadpool_http.WorkQueueSize()) >= g_max_queue_depth) {
+        if (static_cast<int>(g_threadpool_http->WorkQueueSize()) >= g_max_queue_depth) {
             LogWarning("Request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting");
             hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Work queue depth exceeded");
             return;
@@ -276,7 +276,7 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
             req->WriteReply(HTTP_INTERNAL_SERVER_ERROR, err_msg);
         };
 
-        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
+        if (auto res = g_threadpool_http->Submit(std::move(item)); !res.has_value()) {
             // Both SubmitError::Inactive and SubmitError::Interrupted mean shutdown
             LogWarning("HTTP request rejected during server shutdown: '%s'", SubmitErrorString(res.error()));
             hreq->WriteReply(HTTP_SERVICE_UNAVAILABLE, "Request rejected during server shutdown");
@@ -438,7 +438,7 @@ void StartHTTPServer()
 {
     int rpcThreads = std::max((long)gArgs.GetIntArg("-rpcthreads", DEFAULT_HTTP_THREADS), 1L);
     LogInfo("Starting HTTP server with %d worker threads\n", rpcThreads);
-    g_threadpool_http.Start(rpcThreads);
+    g_threadpool_http.emplace("http", rpcThreads);
     g_thread_http = std::thread(ThreadHTTP, eventBase);
 }
 
@@ -450,7 +450,7 @@ void InterruptHTTPServer()
         evhttp_set_gencb(eventHTTP, http_reject_request_cb, nullptr);
     }
     // Interrupt pool after disabling requests
-    g_threadpool_http.Interrupt();
+    g_threadpool_http->Interrupt();
 }
 
 void StopHTTPServer()
@@ -469,7 +469,7 @@ void StopHTTPServer()
     }
 
     LogDebug(BCLog::HTTP, "Waiting for HTTP worker threads to exit\n");
-    g_threadpool_http.Stop();
+    g_threadpool_http.reset();
 
     {
         if (const auto n_connections{g_requests.CountActiveConnections()}; n_connections != 0) {
diff --git a/src/util/threadpool.h b/src/util/threadpool.h
index e1f2d86ed0..7a3d77e453 100644
--- a/src/util/threadpool.h
+++ b/src/util/threadpool.h
@@ -87,13 +87,6 @@ private:
     }
 
 public:
-    explicit ThreadPool(const std::string& name) : m_name(name) {}
-
-    ~ThreadPool()
-    {
-        Stop(); // In case it hasn't been stopped.
-    }
-
     /**
      * @brief Start worker threads.
      *
@@ -104,12 +97,11 @@ public:
      * initialization and idle shutdown patterns, callers must provide their
      * own synchronization.
      */
-    void Start(const int num_workers) noexcept EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
+    explicit ThreadPool(const std::string& name, const int num_workers) noexcept EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
+        : m_name(name)
     {
         assert(num_workers > 0);
         LOCK(m_mutex);
-        assert(m_workers.empty());
-        m_interrupt = false; // Reset
 
         // Create workers
         m_workers.reserve(num_workers);
@@ -126,7 +118,7 @@ public:
      *
      * Must be called from a controller (non-worker) thread.
      */
-    void Stop() EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
+    ~ThreadPool() EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
         // Notify workers and join them
         std::vector<std::thread> threads_to_join;
```

</details>

Curious to hear what others think. This is not blocking for me within this PR. I haven't thoroughly tested the libevent change beyond running functional tests and I can understand not wanting to touch libevent behavior. Maybe the change to `ThreadPool` should wait until #32061 lands.

**Review by hodlinator — COMMENTED** [review]
The CI MSan failure in p2p_private_broadcast.py[^1] possibly stems from the I2P network being unstable[^2].

[^1]: https://github.com/bitcoin/bitcoin/actions/runs/22083305828/job/63812732359?pr=34577#step:11:3388
[^2]: https://stacker.news/items/1434628

File: src/httpserver.cpp
Comment (furszy) [reply src/httpserver.cpp:462]: > IMO stopping the `ThreadPool` before we stop the libevent [dispatch loop](https://libevent.org/libevent-book/Ref3_eventloop.html) is the wrong order

Just to be precise with this, the ordering is wrong but it is not really an issue, because (1) `InterruptHTTPServer` replaces the handler for one that rejects all incoming requests. And (2) even if we would be handling requests, the pool would just reject the work and we would return a clear error message now.

I agree with the first patch, but I think we should limit ourselves to refactoring libevent code while trying to avoid behavior changes at this point (unless we see a very clear benefit behind them). Modifications there require additional research time for an unmaintained library.

Moving the pool shutdown to the end of the function should give us the same behavior without touching the libevent code.

> Doing the above allows for merging the ThreadPool's constructor with Start() and merging the destructor with Stop().

RAII the pool was brought up a few times before; I implemented it too. It’s not a bad idea, but I’ve been trying not to introduce it too early and first gather more use cases. Mainly because it would make lazy startup and idle shutdown patterns harder to implement. It would also require pool configurations to be stored in a separate structure and dup them when the pool gets constructed.

File: src/util/threadpool.h (hunk 9 above)
Comment (furszy) [reply src/util/threadpool.h]: Sure. Done. The `static` was moved from when this was a class method.

**Comment by furszy** [comment]
rebased to get latest CI changes.

File: src/util/threadpool.h (hunk 8 above)
Comment (furszy) [reply src/util/threadpool.h:23]: Updated. Got convinced keeping the `Expected` approach here is the best path to follow. Thanks everyone for the discussion!

File: src/httpserver.cpp
Comment (hodlinator) [reply src/httpserver.cpp:462]: > Mainly because it would make lazy startup and idle shutdown patterns harder to implement.

Yup, it took me a little while to figure out I needed to use `optional::emplace()` to in-place construct the pool in my suggested patch. Probably first time I used that in code I wrote.

> It would also require pool configurations to be stored in a separate structure and dup them when the pool gets constructed.

Didn't run into such issues in this instance FWIW.

---

Interesting that more RAII style was brought up earlier, it does feel like a natural fit if we didn't have libevent to navigate. Anyway, I'm happy we have this primitive now, sorry I didn't have bandwidth to review it earlier.

**Review by hodlinator — APPROVED** [review]
ACK 9d45a1b1bbccf21aa7750f5741af4d6edfd3dc48

**Review by andrewtoth — APPROVED** [review]
ACK 9d45a1b1bbccf21aa7750f5741af4d6edfd3dc48

File: src/httpserver.cpp
Comment (furszy) [reply src/httpserver.cpp:462]: > Interesting that more RAII style was brought up earlier, it does feel like a natural fit if we didn't have libevent to navigate

we have some enthusiastic RAII fans around here.

File: src/httpserver.cpp [hunk 10]
```diff
@@ -276,7 +276,12 @@ static void http_request_cb(struct evhttp_request* req, void* arg)
             req->WriteReply(HTTP_INTERNAL_SERVER_ERROR, err_msg);
         };
 
-        [[maybe_unused]] auto _{g_threadpool_http.Submit(std::move(item))};
+        if (auto res = g_threadpool_http.Submit(std::move(item)); !res.has_value()) {
```
Comment (pinheadmz) [inline src/httpserver.cpp:279]: 379a9201b1aabffe5f19dbabf1fe4fd57e8fefba

I'm also interested in trying to save `unique_ptr` for `hreq` and tried some hacks like @hodlinator but nothing great came out of that. If nothing else could we `Assume(hreq.use_count() == 1)` in this block and also below where we send `404`? This would just clarify that we don't reply to a request outside a worker thread unless we're sure the worker thread is nonexistent.

Comment (furszy) [reply src/httpserver.cpp:279]: Done as suggested. Thanks.

**Comment by furszy** [comment]
Updated per @pinheadmz feedback, thanks.
Only added a `shared_pointer.use_count() == 1` check to be completely sure the request is destroyed upon submission failure.

**Review by Eunovo — COMMENTED** [review]
Tested ACK https://github.com/bitcoin/bitcoin/pull/34577/commits/a6fc8a43f3f5b7605ebcd24212e01524c86a9189

Confirmed using diff from https://github.com/bitcoin/bitcoin/pull/34577#issuecomment-3902672521

**Review by hodlinator — APPROVED** [review]
re-ACK a6fc8a43f3f5b7605ebcd24212e01524c86a9189

**Comment by fanquake** [comment]
@dergoegge does this resolve #34573 for you?

**Review by pinheadmz — APPROVED** [review]
ACK a6fc8a43f3f5b7605ebcd24212e01524c86a9189

Built and tested on arm64/macos. Reviewed each commit, gave feedback which was addressed. I compared the results of the suggested functional test against modified code between master and branch, ran the test without the modified code between master and branch, and observed all those trials with Wireshark to confirm that the PR improves HTTP server behavior during shutdown.

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK a6fc8a43f3f5b7605ebcd24212e01524c86a9189
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmmW/0sACgkQ5+KYS2KJ
yTomKxAAhc0LeceulNUcjufbNhrpCSGYCK3n+5BrLLKObfQbngO1OnOW3wOEVBjt
RwwpJpwa7nIX2U9YoLWDEJKb5HmdozJZAIWHRuuX2qALOkEr/oguBYZEtan72DDq
cvtm+d6jncur1FnieRTDIdj8/YFkJPIv4dtGyxuy7f3VF0cODuk2fE7oZ+NIQdzN
rMcgI4757HIltYxJRuTVAt7KtvfZuMye/6UufBOcjz159vM+uUi6ORGORzf6EUk9
N3ZF+6DWrQrRjWi0k195t9i0TVDlF/eND2DZmEkK5Jrt+ZjcTMoUaQ3Wj2WoRRfd
XQ5CL9jzw0g8v6LMdYaVmAOfJbIzoF1H9NMWx1a7dwTkaABClXvm0QjB8N14kbhZ
S3inDNJ0hTfyoEeXyHk+Ui+TMj1TutFq1kLvN5TUT+lDE/e/rybL9cKNQvl8NrEk
CtD2mIXLf0vJynpo/hOEO4IP6WzUJjl/6gyrhJ3Dli6xLUznNsPnFB0YgNd2+tPk
0xr/SQ0DTn5GVzOkw9E5jkvDjoVKRbV1sZaw039cBL3ika7ckvt3pEumKj+zZ+IK
IVZ/mXSrfCVKxy3WfY9eQjgjp0A5gogpTQR/MHq1TQ3Pa0v0Qn18bdw0mvm32R8f
DXw8cVQj0JZEP2XiOxD3G2v6rtYK+vnnFQUpxhgcbNSND/8Fpg8=
=Q/ll
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

File: src/util/threadpool.h [hunk 11]
```diff
@@ -97,15 +97,17 @@ class ThreadPool
...
-     * from the queue. If the pool is already started, throws.
+     * from the queue.
      *
-     * Must be called from a controller (non-worker) thread.
+     * Calling Start() on an already-running pool is a logic error. For lazy
+     * initialization and idle shutdown patterns, callers must provide their
+     * own synchronization.
      */
-    void Start(int num_workers) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
+    void Start(const int num_workers) noexcept EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
```
Comment (sedited) [inline src/util/threadpool.h]: Not sure about marking this as `noexcept`. Exceptions here would be caught by `AppInit` and we'd shutdown gracefully. There a bunch of functions that do still throw here, e.g. std::system_error when spawning the thread fails. Do we really gain anything by terminating immediately?

Comment (furszy) [reply src/util/threadpool.h]: Agree on removing `noexcept`.

And this is probably a good moment to align on the broader design philosophy so we have some common foundations going forward.

The way I'm seeing it after some back and forth: there are two fundamentally different kinds of failures, and they deserve different treatment. Plus we have a special third rule that is even more important to us than any design decision.

The first is environment related failures: things like an allocation failure, IO error, thread spawning failing due to the OS is out of resources, etc. These can happen even in perfectly correct code. For these, throwing makes sense. Even if the caller can't fully recover, it at least gets the chance to shut down gracefully, flush state, log something useful. Hard termination throws all of that away.

The second kind is logic errors: things that cannot happen if the code is correct. A double `Start()` call is a good example of this. That's not the OS misbehaving, that's a bug in the caller. Throwing a `std::runtime_error` implies the caller might catch it and carry on, when really we want to say "this shouldn't happen, and if it does, something is just wrong". An assertion is more direct here. It's not an error to be handled, it's a violation of the API contract.

The third rule that applies only to us (Bitcoin-Core) is that we want to minimize assertions in code that can be accessed through the P2P layer. We don't want to be logically honest here, we want to guard against someone triggering a crash remotely.

----------

Maybe if we agree on this, we could add it to one of our .md guidelines. So we don't have to revive this type of discussions every time someone suggests to add a `noexcept` or to change an exception for an assertion in risky places.

Thoughts?

**Comment by furszy** [comment]
Due to the upcoming release freeze, decided to drop the last commit https://github.com/bitcoin/bitcoin/commit/a6fc8a43f3f5b7605ebcd24212e01524c86a9189 to keep this PR focused strictly on fixing the race.

That commit was a design improvement rather than a direct fix, so it makes sense to handle it separately. We can reintroduce it in a follow-up once we align on the overall design direction https://github.com/bitcoin/bitcoin/pull/34577#discussion_r2828661015 (if possible).

PR ready to go.

**Review by sedited — APPROVED** [review]
ACK 726b3663cc8e2164d4e9452f12f5866f5e8f6f1a

**Review by pinheadmz — APPROVED** [review]
re-ACK 726b3663cc8e2164d4e9452f12f5866f5e8f6f1a

Change since last review, dropped tip commit which doesn't affect the bug fix targeting by the rest of the branch.

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 726b3663cc8e2164d4e9452f12f5866f5e8f6f1a
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmmXTMUACgkQ5+KYS2KJ
yTrnag/+IVOKcTiwVPKY0LS+i96t8qwCDeBCYH22b7pzwdDbQ8Bmnhg42Bz5kSQq
XuGPXt4sAn0MjGiC7EpAIErA+yhT/nrf1QuOyJslSUz+6BnO491trzZAdPJ9cnyF
13x4AY2mYs/fLFCfKVk7QhW5U+0XfgqcVD/BNsPtmBfcA6ClXUmFatBL3Mb+P1Y8
H26shtJUz3If+HAM6d5Iey/IoMgS6ENgaLr+4weMRej6JYpNfU2cC4+G9vs/WgRL
+W2K+Fs+Ose2lMLwg+Py6m7vmtrrb1PzuYYGw2B07qsHOP9aGGN+SLDEVs/tEMeY
YUVY0vWnplCG0NMo+VQoMa4xchaMNVpLN1Haa4nwBDWOxSn64t3a9E/EFh+9X3Z/
fLppj+2KrUqCeJ6eN/bJB2sAutq+oZSMFwgybqArPQ9KSMSoNAwoUYySphMmeEkW
JC6NcCTNkI1ZzVrZChizJPYLoGVF7YKWnlo2lLR74/l99+auKQAmTxBIl5hlctoB
4Fv3tgqS+iKrPe9g1mrgGRInhCwsvXVU9tZtgXChzQGuecfQYaESmWVJ1RvqzbQx
fUSbShCOT7iYs7OK+7j5BwPyIBgRoDEf9A9fJ8+/QlYSkQRnTMqux90AtdWXKm/V
Pde7ojKRmACJsuC2hLnE/Ympa63+EwSBf1xZXiLKNtCauVlQCpo=
=TWiX
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

**Review by andrewtoth — APPROVED** [review]
ACK 726b3663cc8e2164d4e9452f12f5866f5e8f6f1a

**Comment by achow101** [comment]
ACK 726b3663cc8e2164d4e9452f12f5866f5e8f6f1a

File: src/util/threadpool.h (hunk 11 above)
Comment (hodlinator) [reply src/util/threadpool.h]: > The first is environment related failures: things like an allocation failure, IO error, thread spawning failing due to the OS is out of resources, etc. These can happen even in perfectly correct code. For these, throwing makes sense. Even if the caller can't fully recover, it at least gets the chance to shut down gracefully, flush state, log something useful. Hard termination throws all of that away.

I think it's fairly hard to recover from OOM, IO errors or failing to spawn threads, so wouldn't aim to use exceptions in this case. Exiting with a clear error in the log/stderr and/or crash dump seems realistic and sufficient.

Agree it would be good to document, if we can agree. ;)

Some compilers/stdlibs allow for disabling exceptions btw. Not advocating for it in this project, just FYI. I guess one gets a hard crash instead of stack unwinding when throwing from constructors etc.

**Review by hodlinator — APPROVED** [review]
re-ACK 726b3663cc8e2164d4e9452f12f5866f5e8f6f1a

**Comment by dergoegge** [comment]
> does this resolve https://github.com/bitcoin/bitcoin/issues/34573 for you?

I did re-run the test that found this new crash issue yesterday and it looks like it's fixed.

Fuzzing/property-based tests take some time to run. If I get pinged to re-test something it'd make sense to wait for me to follow up before merge. Otherwise I'll likely stop responding to these pings and will open a new issue if something wasn't fixed.

**Comment by ismaelsadeeq** [comment]
> Fuzzing/property-based tests take some time to run. If I get pinged to re-test something it'd make sense to wait for me to follow up before merge. Otherwise I'll likely stop responding to these pings and will open a new issue if something wasn't fixed.

Maybe it would be helpful to let the maintainers/contributors know you're looking into it/ i.e re-running tests after getting pinged, so they know whether to wait or move forward?
If an issue wasn't fixed after a fix is merged and resolved, opening a new issue seems fair.

**Comment by dergoegge** [comment]
In this case at least one maintainer knew, but in general they can expect me to follow up and if it's urgent they can also ping me elsewhere.

**Comment by furszy** [comment]
In this case, the crash reproducer script made it straightforward to proceed, and I think people didn't wanted to bother you further since the cause was clear @dergoegge.

What we could have done better was waiting for your feedback on the issue before closing it, I agree. And, at the same time, I also agree that a brief coordination message "running fuzzers, will update soon" would have been very helpful for all of us as well.

I mean, I think we all understand that everyone here is busy and overloaded with parallel projects and tasks, and we all work across different time zones, so being a bit more public on our actions would help minimize misunderstandings.
