### PR TITLE
test: Test that migration automatically repairs corrupted metadata with doubled derivation path

### LINKED ISSUE #29109: Old wallet.dat: Error reading wallet database: keymeta found with unexpected path / All keys read correctly, but transaction data or address metadata may be missing or incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When starting bitcoind with an old wallet (created July 2019, probably `v0.17.x` or `v0.18.x`) the log records 2 errors and one warning that are not self-explanatory.

Might be related to #19051

### Expected behaviour

No warning/errors are shown or the errors/warnings are more detailed as to what's going on.

### Steps to reproduce

Run v26.0 with a very old `wallet.dat` file. I wasn't able to reproduce this with a wallet.dat file created in `v0.12.x`, `v0.16.3` or `v0.18.x`. I'm not sure how to reproduce this without uploading the specific `wallet.dat` file (I'm not able to, sorry).

## Log from v26.0.0

```
2023-12-18T13:24:00Z Bitcoin Core version v26.0.0 (release build)
2023-12-18T13:24:00Z Using the 'x86_shani(1way,2way)' SHA256 implementation
2023-12-18T13:24:00Z Using RdSeed as an additional entropy source
2023-12-18T13:24:00Z Using RdRand as an additional entropy source
[..]
2023-12-18T13:24:00Z Using at most 125 automatic connections (1024 file descriptors available)
2023-12-18T13:24:00Z Using 16 MiB out of 16 MiB requested for signature cache, able to store 524288 elements
2023-12-18T13:24:00Z Using 16 MiB out of 16 MiB requested for script execution cache, able to store 524288 elements
2023-12-18T13:24:00Z Script verification uses 7 additional threads
2023-12-18T13:24:00Z scheduler thread start
[..]
2023-12-18T13:24:00Z Using wallet directory /home/foobar/.bitcoin
2023-12-18T13:24:00Z init message: Verifying wallet(s)…
2023-12-18T13:24:00Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2023-12-18T13:24:00Z Using wallet /home/foobar/.bitcoin/wallet.dat
2023-12-18T13:24:00Z BerkeleyEnvironment::Open: LogDir=/home/foobar/.bitcoin/database ErrorFile=/home/foobar/.bitcoin/db.log
[..]
2023-12-18T13:24:00Z init message: Loading block index…
2023-12-18T13:24:00Z Assuming ancestors of block 00000000000000000001a0a448d6cf2546b06801389cc030b2b18c6491266815 have valid signatures.
2023-12-18T13:24:00Z Setting nMinimumChainWork=000000000000000000000000000000000000000052b2559353df4117b7348b64
2023-12-18T13:24:00Z Opening LevelDB in /home/foobar/.bitcoin/blocks/index
2023-12-18T13:24:00Z Opened LevelDB successfully
2023-12-18T13:24:00Z Using obfuscation key for /home/foobar/.bitcoin/blocks/index: 0000000000000000
2023-12-18T13:24:03Z LoadBlockIndexDB: last block file = 3945
2023-12-18T13:24:03Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=51, size=84327429, heights=817322...817411, time=2023-11-18...2023-11-19)
2023-12-18T13:24:03Z Checking all blk files are present...
2023-12-18T13:24:04Z Initializing chainstate Chainstate [ibd] @ height -1 (null)
2023-12-18T13:24:04Z Opening LevelDB in /home/foobar/.bitcoin/chainstate
2023-12-18T13:24:04Z Opened LevelDB successfully
2023-12-18T13:24:04Z Using obfuscation key for /home/foobar/.bitcoin/chainstate: 9735fc6504867afd
2023-12-18T13:24:04Z Loaded best chain: hashBestChain=0000000000000000000290f359a90a5d57160fd27954703351c6f1bf838941e0 height=816997 date=2023-11-16T10:24:28Z progress=0.983619
2023-12-18T13:24:04Z Opening LevelDB in /home/foobar/.bitcoin/chainstate
2023-12-18T13:24:04Z Opened LevelDB successfully
2023-12-18T13:24:04Z Using obfuscation key for /home/foobar/.bitcoin/chainstate: 9735fc6504867afd
2023-12-18T13:24:04Z [Chainstate [ibd] @ height 816997 (0000000000000000000290f359a90a5d57160fd27954703351c6f1bf838941e0)] resized coinsdb cache to 8.0 MiB
2023-12-18T13:24:04Z [Chainstate [ibd] @ height 816997 (0000000000000000000290f359a90a5d57160fd27954703351c6f1bf838941e0)] resized coinstip cache to 440.0 MiB
2023-12-18T13:24:04Z init message: Verifying blocks…
2023-12-18T13:24:04Z Verifying last 6 blocks at level 3
2023-12-18T13:24:04Z Verification progress: 0%
2023-12-18T13:24:05Z Verification progress: 16%
2023-12-18T13:24:05Z Verification progress: 33%
2023-12-18T13:24:05Z Verification progress: 50%
2023-12-18T13:24:05Z Verification progress: 66%
2023-12-18T13:24:05Z Verification progress: 83%
2023-12-18T13:24:06Z Verification progress: 99%
2023-12-18T13:24:06Z Verification: No coin database inconsistencies in last 6 blocks (26158 transactions)
2023-12-18T13:24:06Z  block index            5148ms
2023-12-18T13:24:06Z init message: Loading wallet…
2023-12-18T13:24:06Z BerkeleyEnvironment::Open: LogDir=/home/foobar/.bitcoin/database ErrorFile=/home/foobar/.bitcoin/db.log
2023-12-18T13:24:06Z [default wallet] Wallet file version = 10500, last client version = 220000

2023-12-18T13:24:06Z [default wallet] Error reading wallet database: keymeta found with unexpected path
2023-12-18T13:24:06Z [default wallet] Error reading wallet database: keymeta found with unexpected path

2023-12-18T13:24:06Z [default wallet] Legacy Wallet Keys: 657 plaintext, 0 encrypted, 657 w/ metadata, 657 total.
2023-12-18T13:24:06Z [default wallet] Descriptors: 0, Descriptor Keys: 0 plaintext, 0 encrypted, 0 total.
2023-12-18T13:24:06Z [default wallet] Wallet completed loading in               8ms
2023-12-18T13:24:06Z [default wallet] setKeyPool.size() = 600
2023-12-18T13:24:06Z [default wallet] mapWallet.size() = 51
2023-12-18T13:24:06Z [default wallet] m_address_book.size() = 100

2023-12-18T13:24:06Z Warning: Error reading /home/foobar/.bitcoin/wallet.dat! All keys read correctly, but transaction data or address metadata may be missing or incorrect.

2023-12-18T13:24:06Z Setting NODE_NETWORK on non-prune mode
2023-12-18T13:24:06Z block tree size = 821776
2023-12-18T13:24:06Z nBestHeight = 816997
2023-12-18T13:24:06Z initload thread start
2023-12-18T13:24:06Z torcontrol thread start
2023-12-18T13:24:06Z Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2023-12-18T13:24:06Z initload thread exit
2023-12-18T13:24:06Z Bound to 127.0.0.1:8334
2023-12-18T13:24:06Z Bound to [::]:8333
2023-12-18T13:24:06Z Bound to 0.0.0.0:8333
2023-12-18T13:24:06Z Loaded 1 addresses from "anchors.dat"
2023-12-18T13:24:06Z 1 block-relay-only anchors will be tried for connections.
2023-12-18T13:24:06Z init message: Starting network threads…
[..]
```

## Log from v25.1.0

The error/warning is slightly different.

Instead of

> Warning: Error reading /home/foobar/.bitcoin/wallet.dat! All keys read correctly, but transaction data or address metadata may be missing or incorrect.

it logs

> Warning: Error reading /home/foobar/.bitcoin/wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

v26.0

### Operating system and version

Ubuntu 22.04 LTS

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by achow101**
A bug in 0.21.x and 22.x resulted in some wallets having invalid derivation paths that are the concatenation of two derivation paths. These appear only when inactive hd chains are topped up.
    
Since key metadata is a legacy wallet only record, migrating legacy wallets to descriptor wallets will fix this issue as all key metadata records are deleted. The derivation path information is derived on-the-fly from the descriptor that is produced for the inactive hd chain.
    
Thus we only need a test to verify that the derivation paths are good, and that all key metadata records are deleted from the migrated wallet.

### CODE REVIEW

File: src/wallet/walletdb.cpp [hunk 1]
```diff
@@ -669,10 +688,23 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
     });
     result = std::max(result, keymeta_res.m_result);
 
+    // Update any changed metadata
+    if (updated_metas.size()) {
+        LegacyScriptPubKeyMan* spkm = pwallet->GetLegacyScriptPubKeyMan();
+        Assert(spkm);
+        LOCK(spkm->cs_KeyStore);
+        for (const auto& pubkey : updated_metas) {
+            w_batch.WriteKeyMetadata(spkm->mapKeyMetadata.at(pubkey.GetID()), pubkey, true);
```
Comment (furszy) [inline src/wallet/walletdb.cpp:704]: nit: should check `WriteKeyMetadata` return value.

**Review by furszy — COMMENTED** [review]
Code review ACK 078c2d74c2779dd459e42daf67ab450fbf223506. Nothing blocking, just tiny nits.

File: src/wallet/walletdb.cpp [hunk 2]
```diff
@@ -669,10 +688,23 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
         }
+
+        pwallet->GetOrCreateLegacyScriptPubKeyMan()->LoadKeyMetadata(vchPubKey.GetID(), keyMeta);
+
         return DBErrors::LOAD_OK;
     });
     result = std::max(result, keymeta_res.m_result);
 
+    // Update any changed metadata
+    if (updated_metas.size()) {
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/walletdb.cpp]: Done

File: src/wallet/walletdb.cpp [hunk 3]
```diff
@@ -527,7 +527,7 @@ static LoadResult LoadRecords(CWallet* pwallet, DatabaseBatch& batch, const std:
     return LoadRecords(pwallet, batch, key, prefix, load_func);
 }
 
-static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch, int last_client) EXCLUSIVE_LOCKS_REQUIRED(pwallet->cs_wallet)
+static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch, WalletBatch& w_batch, int last_client) EXCLUSIVE_LOCKS_REQUIRED(pwallet->cs_wallet)
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/walletdb.cpp]: I've made `m_batch` public so that we can just pass the `WalletBatch` but still use the underlying batch object. However I'm not sure if that's something we want to do in the long term.

File: src/wallet/walletdb.cpp (hunk 1 above)
Comment (achow101) [reply src/wallet/walletdb.cpp]: Done

File: src/wallet/walletdb.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (furszy) [reply src/wallet/walletdb.cpp]: > I've made `m_batch` public so that we can just pass the `WalletBatch` but still use the underlying batch object. However I'm not sure if that's something we want to do in the long term, but I think it should be okay.

Yeah.. I'm not happy reading all the the `batch.m_batch` usages neither but np.

**Review by furszy — COMMENTED** [review]
ACK 9db2d8b

**Review by furszy — COMMENTED** [review]
ACK 1c3462e908994f0d63c1f39b5908f48d083dd10e

Could minimize the first commit diff https://github.com/furszy/bitcoin-core/commit/145737e46e71859608334ab738817f7b323df367.

**Comment by achow101** [comment]
cc @davidgumberg

File: src/wallet/walletdb.cpp [hunk 4]
```diff
@@ -629,13 +629,32 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
+                }
+                // If there is a key origin, make sure that path matches
+                if (keyMeta.has_key_origin && path != keyMeta.key_origin.path) {
+                    // Detect if this metadata has a bad derivation path from a bug in inactive hd key derivation that was present in 0.21 and 22.x
+                    // See https://github.com/bitcoin/bitcoin/issues/29109
+                    // Markers for bad derivation:
+                    // - 6 indexes
+                    // - path[5] == path[2] + 1
+                    // - path[0:2] == path[3:5]
+                    // - path[3:6] matches hdKeypath
```
Comment (rkrux) [inline src/wallet/walletdb.cpp:645]: I had been wondering why such a path can't occur besides this case, this comment in `DeriveNewChildKey` function answers it: https://github.com/bitcoin/bitcoin/blob/28.x/src/wallet/scriptpubkeyman.cpp#L1129

File: test/functional/wallet_backwards_compatibility.py [hunk 5]
```diff
@@ -128,6 +128,77 @@ def test_v19_addmultisigaddress(self):
...
+        wallet = node_v22.get_wallet_rpc(wallet_name)
+
+        # Make a dump of the wallet to get an unused address
+        dump_path = node_v22.wallets_path / f"{wallet_name}.dump"
+        wallet.dumpwallet(dump_path)
+        addr = None
+        seed = None
+        with open(dump_path, encoding="utf8") as f:
+            for line in f:
+                if "hdkeypath=m/0'/0'/9'" in line:
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:152]: I spent some time trying to understand why this one is picked here only to realise later that 9 is the last index at this chain because of keypool size set to 10 at the top of this test here: https://github.com/bitcoin/bitcoin/pull/29124/commits/e92dc1a3d36be02a8b16eed26159a43cfbe3dbcc#diff-b5055a65809b46e2775f6e28aa6eb8171e3fcc7a535cce5687a548b9ff233669R44

This 9 and 10 can be tied to each other with a constant for better readability.

Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:152]: Can this happen for internal keychain as well?

File: test/functional/wallet_backwards_compatibility.py [hunk 6]
```diff
@@ -128,6 +128,77 @@ def test_v19_addmultisigaddress(self):
...
+        wallet.unloadwallet()
+        # Receive at addr to trigger inactive chain topup on next load
+        self.nodes[0].sendtoaddress(addr, 1)
+        self.generate(self.nodes[0], 1, sync_fun=self.no_op)
+        self.sync_all(nodes=[self.nodes[0], node_master, node_v22])
+        node_v22.loadwallet(wallet_name)
+
+        # Dump again to find bad hd keypath
+        bad_deriv_path = "m/0'/0'/9'/0'/0'/10'"
+        good_deriv_path = "m/0'/0'/10'"
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:169]: Similar tying to a constant here if possible.

File: test/functional/wallet_backwards_compatibility.py [hunk 7]
```diff
@@ -128,6 +128,77 @@ def test_v19_addmultisigaddress(self):
...
+
+        # Make a dump of the wallet to get an unused address
+        dump_path = node_v22.wallets_path / f"{wallet_name}.dump"
+        wallet.dumpwallet(dump_path)
+        addr = None
+        seed = None
+        with open(dump_path, encoding="utf8") as f:
+            for line in f:
+                if "hdkeypath=m/0'/0'/9'" in line:
+                    addr = line.split(" ")[4].split("=")[1]
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:153]: Reference for line format: https://github.com/bitcoin/bitcoin/blob/28.x/src/wallet/rpc/backup.cpp#L778-L802

**Review by rkrux — COMMENTED** [review]
Build and tests successful at e92dc1a3d36be02a8b16eed26159a43cfbe3dbcc
Some initial comments, will give it another pass again.

**Review by rkrux — APPROVED** [review]
tACK e92dc1a3d36be02a8b16eed26159a43cfbe3dbcc

Thanks for this PR, I enjoyed reviewing it. I ran the tests and debugged the compatibility test.

Can / Will this also be back-ported to the affected version or is the affected version too far back to be back-ported into?

File: test/functional/wallet_backwards_compatibility.py [hunk 8]
```diff
@@ -128,6 +128,77 @@ def test_v19_addmultisigaddress(self):
...
+        verify_wallet.keypoolrefill(12)
+        assert_equal(verify_wallet.getaddressinfo(bad_path_addr)["hdkeypath"], good_deriv_path)
+
+        # Load into master, the path should now be fixed
+        backup_path = node_v22.wallets_path / f"{wallet_name}.bak"
+        wallet.backupwallet(backup_path)
+        with node_master.assert_debug_log(expected_msgs=["Repairing derivation path for"]):
+            node_master.restorewallet(wallet_name, backup_path)
+        wallet_master = node_master.get_wallet_rpc(wallet_name)
+        assert_equal(wallet_master.getaddressinfo(bad_path_addr)["hdkeypath"], good_deriv_path)
```
[the remark this answers is not in the document]
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py:194]: `ischange` does not actually look at the derivation path. Instead it looks at some heuristics which result in derived-but-not-yet-requested external addresses being identified as change.

File: src/wallet/walletdb.h [hunk 9]
```diff
@@ -302,8 +302,8 @@ class WalletBatch
     //! Registers db txn callback functions
     void RegisterTxnListener(const DbTxnListener& l);
 
-private:
     std::unique_ptr<DatabaseBatch> m_batch;
+private:
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/walletdb.h:306]: Going to leave this as is.

File: test/functional/wallet_backwards_compatibility.py (hunk 5 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Added a constant.

File: test/functional/wallet_backwards_compatibility.py (hunk 6 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

File: test/functional/wallet_backwards_compatibility.py [hunk 10]
```diff
@@ -128,6 +128,77 @@ def test_v19_addmultisigaddress(self):
...
+                    bad_path_addr = line.split(" ")[4].split("=")[1]
+        assert bad_path_addr is not None
+        assert_equal(wallet.getaddressinfo(bad_path_addr)["hdkeypath"], bad_deriv_path)
+
+        # Verify that this addr is actually at m/0'/0'/10' by making a new wallet with the same seed
+        node_v22.createwallet(wallet_name="path_verify", descriptors=False, blank=True)
+        verify_wallet = node_v22.get_wallet_rpc("path_verify")
+        verify_wallet.sethdseed(True, seed)
+        # Bad addr is after keypool, so need to generate it by refilling
+        verify_wallet.keypoolrefill(12)
```
[the remark this answers is not in the document]
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

**Comment by achow101** [comment]
Updated this to work even after the legacy wallet is deleted.

File: test/functional/wallet_backwards_compatibility.py [hunk 11]
```diff
@@ -128,6 +128,79 @@ def test_v19_addmultisigaddress(self):
...
+                    bad_path_addr = line.split(" ")[4].split("=")[1]
+        assert bad_path_addr is not None
+        assert_equal(wallet.getaddressinfo(bad_path_addr)["hdkeypath"], bad_deriv_path)
+
+        # Verify that this addr is actually at m/0'/0'/10' by making a new wallet with the same seed
+        node_v22.createwallet(wallet_name="path_verify", descriptors=False, blank=True)
+        verify_wallet = node_v22.get_wallet_rpc("path_verify")
+        verify_wallet.sethdseed(True, seed)
+        # Bad addr is after keypool, so need to generate it by refilling
+        verify_wallet.keypoolrefill(LAST_KEYPOOL_INDEX + 2)
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:184]: This was using 12 earlier, now 11. Fine since the test passes.

**Review by rkrux — COMMENTED** [review]
reACK 78cb0df4d5b9cc30dbe60a6cf24ab6cac5d3f421

I reviewed the range diff.
```
git range-diff e92dc1a3d36be02a8b16eed26159a43cfbe3dbcc...78cb0df4d5b9cc30dbe60a6cf24ab6cac5d3f421
```

Newer changes are related to using the constant `LAST_KEYPOOL_INDEX` as suggested and use `migratewallet` instead of `restorewallet` due to which the format of `good_deriv_path` is changed from `'` to 'h'. Using `migratewallet` is fine because it also ends up calling `LoadLegacyWalletRecords` internally where the bug fix lies, and additionally it also ensures the fix works for the newer wallets.

File: src/wallet/walletdb.cpp [hunk 12]
```diff
@@ -634,13 +634,32 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
+                    return DBErrors::NONCRITICAL_ERROR;
+                }
+                // If there is a key origin, make sure that path matches
+                if (keyMeta.has_key_origin && path != keyMeta.key_origin.path) {
+                    // Detect if this metadata has a bad derivation path from a bug in inactive hd key derivation that was present in 0.21 and 22.x
+                    // See https://github.com/bitcoin/bitcoin/issues/29109
+                    // Markers for bad derivation:
+                    // - 6 indexes
+                    // - path[5] == path[2] + 1
+                    // - path[0:2] == path[3:5]
```
Comment (murchandamus) [inline src/wallet/walletdb.cpp:649]: Isn’t the line 648 in contradiction with line 649?

Looking at https://github.com/bitcoin/bitcoin/issues/29109, I’m thinking that the indices are referring to the elements separated by "/" after "m" of the hdkeypath variable here.

```diff
-[..] hdkeypath=m/0'/0'/299'/0'/0'/300'
+[..] hdkeypath=m/0'/0'/300'
```

I am wondering whether this should be:

```suggestion
                    // - path[5] == path[2] + 1
                    // - path[0:1] == path[3:4]
```

File: src/wallet/walletdb.cpp [hunk 13]
```diff
@@ -634,13 +634,32 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
+                    // - path[3:6] matches hdKeypath
```
Comment (murchandamus) [inline src/wallet/walletdb.cpp:650]: If we only have six indexes, should this perhaps be path[3:5]?

```suggestion
                    // - path[3:5] matches hdKeypath
```

**Review by murchandamus — COMMENTED** [review]
Concept ACK

File: src/wallet/walletdb.cpp (hunk 12 above)
Comment (murchandamus) [reply src/wallet/walletdb.cpp:649]: Oh, are these ranges meant to be exclusive of the second parameter?

File: src/wallet/walletdb.cpp [hunk 14]
```diff
@@ -634,13 +634,32 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
+                    if (keyMeta.key_origin.path.size() == 6
+                        && keyMeta.key_origin.path[5] == keyMeta.key_origin.path[2] + 1
+                        && keyMeta.key_origin.path[0] == keyMeta.key_origin.path[3]
+                        && keyMeta.key_origin.path[1] == keyMeta.key_origin.path[4]
```
Comment (rkrux) [inline src/wallet/walletdb.cpp:654]: Before suggesting, I checked whether this function is going to stick around after the legacy wallet removal but after taking a cursory look at https://github.com/bitcoin/bitcoin/pull/28710, I see it will.

In which case, I feel going at these checks in order would be slightly easier on the eyes. Might be nitty but easier for me at least.

```diff
-                        && keyMeta.key_origin.path[5] == keyMeta.key_origin.path[2] + 1
-                        && keyMeta.key_origin.path[0] == keyMeta.key_origin.path[3]
-                        && keyMeta.key_origin.path[1] == keyMeta.key_origin.path[4]
+                        && keyMeta.key_origin.path[3] == keyMeta.key_origin.path[0]
+                        && keyMeta.key_origin.path[4] == keyMeta.key_origin.path[1]
+                        && keyMeta.key_origin.path[5] == keyMeta.key_origin.path[2] + 1
```

File: src/wallet/walletdb.cpp (hunk 4 above)
Comment (rkrux) [reply src/wallet/walletdb.cpp:650]: Could be helpful to add a comment here either referring it or copy-pasting the linked comment.

**Review by rkrux — CHANGES_REQUESTED** [review]
Concept ACK 78cb0df4d5b9cc30dbe60a6cf24ab6cac5d3f421

File: src/wallet/walletdb.cpp (hunk 4 above)
Comment (achow101) [reply src/wallet/walletdb.cpp]: Expanded the comment a little bit.

File: src/wallet/walletdb.cpp (hunk 12 above)
Comment (achow101) [reply src/wallet/walletdb.cpp]: Changed as suggested. Also added a bit more of an explainer to the comment that should make it clearer.

File: src/wallet/walletdb.cpp (hunk 14 above)
Comment (achow101) [reply src/wallet/walletdb.cpp]: Done

File: test/functional/wallet_backwards_compatibility.py [hunk 15]
```diff
@@ -126,6 +127,77 @@ def test_v19_addmultisigaddress(self):
...
+
+    def test_v22_inactivehdchain_path(self):
+        self.log.info("Testing inactive hd chain bad derivation path cleanup")
+        # 0.21.x and 22.x would both produce bad derivation paths when topping up an inactive hd chain
+        # Make sure that this is being detected and automatically cleaned up
+        node_master = self.nodes[1]
+        node_v22 = self.nodes[self.num_nodes - 5]
+        wallet_name = "bad_deriv_path"
+        node_v22.createwallet(wallet_name=wallet_name, descriptors=False)
+        wallet = node_v22.get_wallet_rpc(wallet_name)
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:139]: Nit if retouched:

```diff
- wallet = node_v22.get_wallet_rpc(wallet_name)
+ bad_deriv_wallet = node_v22.get_wallet_rpc(wallet_name)
```

For easy identification because this wallet is used across the whole test where other wallets are also created later down.

File: test/functional/wallet_backwards_compatibility.py [hunk 16]
```diff
@@ -126,6 +127,77 @@ def test_v19_addmultisigaddress(self):
...
+        wallet.dumpwallet(dump_path)
+        bad_path_addr = None
+        with open(dump_path, encoding="utf8") as f:
+            for line in f:
+                if f"hdkeypath={bad_deriv_path}" in line:
+                    bad_path_addr = line.split(" ")[4].split("=")[1]
+        assert bad_path_addr is not None
+        assert_equal(wallet.getaddressinfo(bad_path_addr)["hdkeypath"], bad_deriv_path)
+
+        # Verify that this addr is actually at m/0'/0'/10' by making a new wallet with the same seed
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:176]:
```diff
- # Verify that this addr is actually at m/0'/0'/10' by making a new wallet with the same seed
+ # Verify that this bad derivation path addr is actually at m/0'/0'/10' by making a new wallet with the same seed but with a higher keypool size

**Review by rkrux — APPROVED** [review]
tACK bdcd435b48d4979751e6dd74cb996073721e5c9d

Build and functional tests good, I left few clarification nits if you end up retouching.

The main change detects bad derivation paths when loading the metadata within legacy wallet records, updates the metadata in the legacy SPKM, and then writes the updated metadata in the DB. 

> git range-diff 78cb0df...bdcd435

Newer changes are improving the bad derivation path detection inline comments that makes it easier to follow by appearing consistent with the code right below, reusing `LAST_KEYPOOL_INDEX` in the node setup of the functional test and rebase changes - using `HasLegacyRecords()`, using an updated functional test node count.

The addition of the detection of the bad derivation path in the `LoadFunc` is slightly distracting when I read the `LoadLegacyWalletRecords()` as a whole but I have not suggested changes because this is legacy wallet and intended to be used less now. 

The comprehensive functional test covers the buggy scenario along with its resolution. Also, the original issue #29109 is resolved for the user after using this fix that gives more confidence as well.

File: src/wallet/walletdb.cpp [hunk 17]
```diff
@@ -697,10 +717,26 @@ static DBErrors LoadLegacyWalletRecords(CWallet* pwallet, DatabaseBatch& batch,
...
     });
     result = std::max(result, keymeta_res.m_result);
 
+    // Update any changed metadata
+    if (!updated_metas.empty()) {
+        LegacyDataSPKM* spkm = pwallet->GetLegacyDataSPKM();
+        Assert(spkm);
+        LOCK(spkm->cs_KeyStore);
+        for (const auto& pubkey : updated_metas) {
+            if (!batch.WriteKeyMetadata(spkm->mapKeyMetadata.at(pubkey.GetID()), pubkey, true)) {
```
[the remark this answers is not in the document]
Comment (furszy) [reply src/wallet/walletdb.cpp:733]: Also, another nit; could batch the db writes and fail if commit fails.

File: test/functional/wallet_backwards_compatibility.py [hunk 18]
```diff
@@ -126,6 +127,77 @@ def test_v19_addmultisigaddress(self):
...
+        verify_wallet.keypoolrefill(LAST_KEYPOOL_INDEX + 2)
+        assert_equal(verify_wallet.getaddressinfo(bad_path_addr)["hdkeypath"], good_deriv_path.replace("h", "'"))
+
+        # Load into master, the path should now be fixed
+        backup_path = node_v22.wallets_path / f"{wallet_name}.bak"
+        wallet.backupwallet(backup_path)
+        wallet_dir_master = os.path.join(node_master.wallets_path, wallet_name)
+        os.makedirs(wallet_dir_master, exist_ok=True)
+        shutil.copy(backup_path, os.path.join(wallet_dir_master, "wallet.dat"))
+        with node_master.assert_debug_log(expected_msgs=["Repairing derivation path for"]):
```
[the remark this answers is not in the document]
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

File: test/functional/wallet_backwards_compatibility.py (hunk 15 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

File: test/functional/wallet_backwards_compatibility.py (hunk 16 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

File: test/functional/wallet_backwards_compatibility.py [hunk 19]
```diff
@@ -126,6 +127,77 @@ def test_v19_addmultisigaddress(self):
...
+        verify_wallet.keypoolrefill(LAST_KEYPOOL_INDEX + 2)
+        assert_equal(verify_wallet.getaddressinfo(bad_path_addr)["hdkeypath"], good_deriv_path.replace("h", "'"))
+
+        # Load into master, the path should now be fixed
+        backup_path = node_v22.wallets_path / f"{wallet_name}.bak"
+        bad_deriv_wallet.backupwallet(backup_path)
+        wallet_dir_master = os.path.join(node_master.wallets_path, wallet_name)
+        os.makedirs(wallet_dir_master, exist_ok=True)
+        shutil.copy(backup_path, os.path.join(wallet_dir_master, "wallet.dat"))
+        with node_master.assert_debug_log(expected_msgs=["Repairing derivation path for"], unexpected_msgs=["Unable to write repaired ketmeta for"]):
```
Comment (DrahtBot) [inline test/functional/wallet_backwards_compatibility.py:190]: (✨ LLM generated, experimental)

ketmeta → keymeta

**Review by rkrux — APPROVED** [review]
reACK 670d02bc380c22fa4c985b72e8209f475ed0e7d0

```
git range-diff bdcd435...670d02b
```

Using `find` instead of `at` now, few other functional test naming & comments changes done as suggested earlier.

**Comment by achow101** [comment]
@furszy has uncovered that it seems like migrating legacy to descriptors also solves the problem. Since removal of the legacy wallet is close, I will look into this a bit further and probably turn this PR into just a test.

**Comment by achow101** [comment]
Removed the fix commit since we are expecting legacy wallets to go away soon, and migration is a valid way to fix this problem. The remaining test commit is updated to work without the automatic repair being logged. It additionally is changed to check that no `keymeta` records exist after the migration.

File: test/functional/wallet_backwards_compatibility.py [hunk 20]
```diff
@@ -126,6 +127,86 @@ def test_v19_addmultisigaddress(self):
...
+        assert_equal(bad_deriv_wallet_master.getaddressinfo(bad_path_addr)["hdkeypath"], good_deriv_path)
+        bad_deriv_wallet_master.unloadwallet()
+
+        # If we have sqlite3, verify that there are no keymeta records
+        try:
+            import sqlite3
+            wallet_db = node_master.wallets_path / wallet_name / "wallet.dat"
+            conn = sqlite3.connect(wallet_db)
+            with conn:
+                # Retrieve all records that have the keymeta prefix
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:203]: Nit:
```diff
- # Retrieve all records that have the keymeta prefix
+ # Retrieve all records that have the "keymeta" prefix, rest of the key data is the pubkey that differs for each record
```

File: test/functional/wallet_backwards_compatibility.py [hunk 21]
```diff
@@ -126,6 +127,86 @@ def test_v19_addmultisigaddress(self):
...
+                keymeta_rec = conn.execute("SELECT value FROM main where key >= x'076b65796d6574' AND key < x'076b65796d6575'").fetchone()
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:204]: Isn't [076b65796d6574, 076b65796d6575) a little too wide of a search range? 

"keymeta" in hex is "6b65796d657461", prepending it with the compact size length "07" should make the key prefix "076b65796d657461" in the serialised form imo, making the range as [076b65796d657461, 076b65796d657462)

File: test/functional/wallet_backwards_compatibility.py [hunk 22]
```diff
@@ -126,6 +127,86 @@ def test_v19_addmultisigaddress(self):
         wallet = node_v19.get_wallet_rpc("w1_v19")
         assert wallet.getaddressinfo(address_18075)["solvable"]
 
+
+    def test_v22_inactivehdchain_path(self):
+        self.log.info("Testing inactive hd chain bad derivation path cleanup")
+        # 0.21.x and 22.x would both produce bad derivation paths when topping up an inactive hd chain
+        # Make sure that this is being detected and automatically cleaned up
```
Comment (rkrux) [inline test/functional/wallet_backwards_compatibility.py:134]:
```diff
- # Make sure that this is being detected and automatically cleaned up
+ # Make sure that this it is being automatically cleaned up during migration
```

**Review by rkrux — COMMENTED** [review]
Nice that the migration flow can fix it automatically and no new custom handling is required now while loading the legacy wallets!

File: test/functional/wallet_backwards_compatibility.py (hunk 20 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

File: test/functional/wallet_backwards_compatibility.py (hunk 21 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Oops yes, fixed.

File: test/functional/wallet_backwards_compatibility.py (hunk 22 above)
Comment (achow101) [reply test/functional/wallet_backwards_compatibility.py]: Done

**Review by rkrux — COMMENTED** [review]
LGTM, ACK bfcf5c5ab1fdba46d492aa0872c3d5f9a4a87633 - it's just one functional test now, a detailed one at that.

Couple of observations/questions after rotating the seed and unloading the wallet that I found noteworthy enough to share here.

1. The `listreceivedbyaddress` RPC doesn't  show any entry for `addr` to which the 1 BTC was sent, but `listunspent` RPC does show.

2. The `desc` field in the `bad_deriv_wallet.listunspent` and `bad_deriv_wallet_master.listunspent` calls for the same `addr` was different slightly as I see `'` was used in the former & `h` in the latter due to which the checksum differs. Is this the default behaviour in migration? I vaguely recall reading about it somewhere else too.

-> bad_deriv_wallet.listunspent
```
desc': "wpkh([7c198af4/0'/0'/9']03ef7ecec2fc90ce130c7a244762d7dae68f0176977debc2bfe9839c7b097342ff)#jlrcq70p"
```

-> bad_deriv_wallet_master.listunspent
```
'desc': 'wpkh([7c198af4/0h/0h/9h]03ef7ecec2fc90ce130c7a244762d7dae68f0176977debc2bfe9839c7b097342ff)#4n2zmzyr'
```

**Comment by achow101** [comment]
> 1. The `listreceivedbyaddress` RPC doesn't  show any entry for `addr` to which the 1 BTC was sent, but `listunspent` RPC does show.

This is expected since we didn't get `addr` through normal means, and it therefore is missing expected items for receiving addresses like an address book entry.

> 2. The `desc` field in the `bad_deriv_wallet.listunspent` and `bad_deriv_wallet_master.listunspent` calls for the same `addr` was different slightly as I see `'` was used in the former & `h` in the latter due to which the checksum differs. Is this the default behaviour in migration? I vaguely recall reading about it somewhere else too.

This is expected. In a bunch of places, the standard hardened derivation marker is `'`. However, for descriptors, since #26076, we use `h` instead as it is easier to copy-paste in terminals.

**Review by murchandamus — COMMENTED** [review]
ACK bfcf5c5ab1fdba46d492aa0872c3d5f9a4a87633

**Review by furszy — COMMENTED** [review]
utACK bfcf5c5ab1fdba46d492aa0872c3d5f9a4a87633

**Review by rkrux — APPROVED** [review]
re-ACK c7e2b9e2644442b147880becb8a659f3d00092d9

```
git range-diff bfcf5c5ab1fdba46d492aa0872c3d5f9a4a87633..c7e2b9e2644442b147880becb8a659f3d00092d9
```

The range-diff contains only rebase changes now that #31250 is merged.

**Review by furszy — COMMENTED** [review]
utACK c7e2b9e2644442b147880becb8a659f3d00092d9
