### PR TITLE
Fix CPUID subleaf iteration

### LINKED ISSUE #17523: bitcoind broken on latest master
Bitcoind takes up 100% cpu, log file not written to. Even bitcoind --help isn't working.

**Expected behavior**

Run normally

**Actual behavior**

100% cpu usage, no output

**To reproduce**

Compile current master and try to run bitcoind

**System information**

latest master

Debian Buster
VM with 28 Xeon Platinum cores, 64GB RAM, SSD storage

Compiled  from  v0.19.0.1 tag and it's working.

### PR DESCRIPTION
**Pull request by sipa**
This fixes #17523.

The code to determine which CPUID subleaves to explore was incorrect in #17270. The new code here is based on Intel's reference documentation for CPUID (a document called "Intel® Processor Identification and the CPUID Instruction - Application Note 485", which I cannot actually find on their own website).

### CODE REVIEW

**Comment by mb300sd** [comment]
Tested. Changes fixed the issue for me.

**Comment by fanquake** [comment]
[Intel® Processor Identification and the CPUID Instruction - Application Note 485](https://github.com/bitcoin/bitcoin/files/3866527/241618-038.pdf)

File: src/randomenv.cpp [hunk 1]
```diff
@@ -198,12 +198,23 @@ void AddAllCPUID(CSHA512& hasher)
     AddCPUID(hasher, 0, 0, ax, bx, cx, dx); // Returns max leaf in ax
     uint32_t max = ax;
     for (uint32_t leaf = 1; leaf <= max; ++leaf) {
+        uint32_t maxsub = 0;
         for (uint32_t subleaf = 0;; ++subleaf) {
```
Comment (mzumsande) [inline src/randomenv.cpp]: I am not an expert on CPUID, but how about an emergency break after some number of subleaves - or was it a deliberate decision to construct the inner loop in a way that it can possibly run infinitely when certain assumptions are wrong, or might be in the future?

Comment (sipa) [reply src/randomenv.cpp]: I guess the question is whether we want to have any chance of catching weird systems that return non-compliant CPUID values. If we add an upper bound, we'll probably never ever see a bug report like this one.

Comment (mzumsande) [reply src/randomenv.cpp]: True, I am not sure if catching those justifies the inconvenience for affected users who might not be able to run bitcoin on their system without waiting for a patch (considering that CPUID is just one of many static entropy sources).

**Review by jonatack — COMMENTED** [review]
Tested ba2c5fe147 by building, running tests and bitcoind. I was unaffected by the issue but running bitcoind appears unaffected by this change.

```
$ uname -a
Linux purity 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
```

File: src/randomenv.cpp (hunk 1 above)
Comment (laanwj) [reply src/randomenv.cpp]: I think this depends on the chance that there actually CPUs out there, suitable for running nodes, that are not compliant with this. 

I feel slightly uneasy with potentially infinite loops over hardware registers like this, OTOH I understand @sipa's point.

> I guess the question is whether we want to have any chance of catching weird systems that return non-compliant CPUID values.

It could log a message when it hits the upper bound. And if you make it a high enough value you'd still get reports, just that bitcoind startup is slow instead of doesn't start at all.
(which is probably preferable :smile:)

Comment (laanwj) [reply src/randomenv.cpp]: It's only a uint32_t. How long does a full wrap-around take?

**Comment by laanwj** [comment]
Concept ACK. Thanks @mb300sd for catching this before a release.

File: src/randomenv.cpp (hunk 1 above)
Comment (jonatack) [reply src/randomenv.cpp]: In this case, I'd be tempted to begin with failing painfully and adapt if needed.

Comment (sipa) [reply src/randomenv.cpp]: @laanwj A full 32-bit wrap-around would mean SHA512 hashing 96 GiB of data. Too long, I'm sure.

I've added a commit to limit the number of iterations.

**Comment by laanwj** [comment]
ACK f93fc61c65d605eae2d3e2c98bdd30ae587fcdab

**Comment by jonatack** [comment]
ACK f93fc61c65d605eae2d3e2c98bdd30ae587fcdab code review, tested rebased on current master bb862d7 with Debian 4.19 x86_64

**Review by mzumsande — COMMENTED** [review]
ACK f93fc61, reviewed code and compared with the intel doc, tested on an AMD and an Intel processor.
