### PR TITLE
Avoid non-trivial global constants in SHA-NI code

### LINKED ISSUE #18456: bitcoin-qt/bitcoind crashes upon startup of crypto/sha256_shani. Illegal instruction
Version 0.19.1 compiles fine. Configured with debugging enabled on Ubuntu 18.04.3 LTS

When running with gdb:-

```
(gdb) run
Starting program: /home/bitcoin/src/qt/bitcoind
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000555555ebddf8 in _mm_set_epi64x (__q0=289644378169868803, __q1=868365760874482187) at /usr/lib/gcc/x86_64-linux-gnu/7/include/emmintrin.h:592
592       return __extension__ (__m128i)(__v2di){ __q0, __q1 };
(gdb) bt
#0  0x0000555555ebddf8 in _mm_set_epi64x (__q0=289644378169868803, __q1=868365760874482187) at /usr/lib/gcc/x86_64-linux-gnu/7/include/emmintrin.h:592
#1  __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at crypto/sha256_shani.cpp:19
#2  0x0000555555ebdea9 in _GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm () at crypto/sha256_shani.cpp:357
#3  0x0000555555f1f54d in __libc_csu_init ()
#4  0x00007ffff3879b28 in __libc_start_main (main=0x5555555c1ffc <main(int, char**)>, argc=1, argv=0x7fffffffe478, init=0x555555f1f500 <__libc_csu_init>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe468) at ../csu/libc-start.c:266
#5  0x00005555555c1e7a in _start ()
```

### PR DESCRIPTION
**Pull request by sipa**
This is a potential solution for #18456.

It seems that the compiler cannot turn `_mm_set_epi64x(<constant>,<constnant>)` into a constant itself, and thus emits a global initializer for the `MASK`, `INIT0`, and `INIT1` global constants in the sha-ni SHA256 implementation.

Change this by turning them into dumb byte arrays, loading them into an SSE variable whenever needed.

Tested on a SHA-NI capable machine. I do not observe any obvious performance impact (but this is hard to measure, it's already very fast...).

### CODE REVIEW

File: src/crypto/sha256_shani.cpp [hunk 1]
```diff
@@ -11,13 +11,11 @@
...
 #include <immintrin.h>
 
-
-
 namespace {
 
-const __m128i MASK = _mm_set_epi64x(0x0c0d0e0f08090a0bULL, 0x0405060700010203ULL);
-const __m128i INIT0 = _mm_set_epi64x(0x6a09e667bb67ae85ull, 0x510e527f9b05688cull);
-const __m128i INIT1 = _mm_set_epi64x(0x3c6ef372a54ff53aull, 0x1f83d9ab5be0cd19ull);
+const uint8_t MASK[16] alignas(__m128i) = {0x03, 0x02, 0x01, 0x00, 0x07, 0x06, 0x05, 0x04, 0x0b, 0x0a, 0x09, 0x08, 0x0f, 0x0e, 0x0d, 0x0c};
```
Comment (elichai) [inline src/crypto/sha256_shani.cpp:16]: This fails to compile on clang.
Try moving the `alignas` to the beginning of the expression:
`alignas(__m128i) const uint8_t MASK[16] = {0x03, 0x02, 0x01, 0x00, 0x07, 0x06, 0x05, 0x04, 0x0b, 0x0a, 0x09, 0x08, 0x0f, 0x0e, 0x0d, 0x0c};`

**Review by elichai — COMMENTED** [review]
Looking at the source of this function: https://github.com/gcc-mirror/gcc/blob/4a3895903c29ed85da6fcb886f31ff23d4c6e935/gcc/config/i386/emmintrin.h#L694
It seems to be doing just a read operation from that location, so I'm not too worried about the performance of this

And looking at godbolt you seem to be right, it initializes it in the global initializers https://godbolt.org/z/M2b6cg

**Comment by MarcoFalke** [comment]
Alternative suggested on IRC, which might compile on clang:

```cpp
[13:29] <aj> +inline __m128i MASK() { return _mm_set_epi64x(0x0c0d0e0f08090a0bULL, 0x0405060700010203ULL); }

File: src/crypto/sha256_shani.cpp (hunk 1 above)
Comment (sipa) [reply src/crypto/sha256_shani.cpp:16]: Done.

**Comment by sipa** [comment]
@MarcoFalke Going to try https://github.com/bitcoin/bitcoin/pull/18553#discussion_r404630179 first.

**Comment by elichai** [comment]
Looks Good.
Can someone with SHA-NI run this under valgrind and sanitizers? I'm a bit afraid this violates some weird C++ rule (I find manually modifying alignments quite scary)

**Comment by laanwj** [comment]
Code review ACK 850847309458f43fc7ce6c13fa08c86e1cae042a

**Comment by laanwj** [comment]
I've diffed the code generated by `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`. The only difference with this patch seems to be that the following initialization code is removed:
```diff
--- ./src/crypto/crypto_libbitcoin_crypto_shani_a-sha256_shani.o.new_d  2020-04-09 14:01:43.009818616 +0200
+++ ./src/crypto/crypto_libbitcoin_crypto_shani_a-sha256_shani.o.old_d  2020-04-09 14:01:37.073839875 +0200
@@ -1,5 +1,5 @@
 
-./src/crypto/crypto_libbitcoin_crypto_shani_a-sha256_shani.o.new:     file format elf64-x86-64
+./src/crypto/crypto_libbitcoin_crypto_shani_a-sha256_shani.o.old:     file format elf64-x86-64
 
 
 Disassembly of section .text:
@@ -1163,3 +1163,28 @@
     1502:      48 83 c4 68             add    $0x68,%rsp
     1506:      c3                      retq   
     1507:      e8 00 00 00 00          callq  150c <_ZN15sha256d64_shani14Transform_2wayEPhPKh+0x115c>
+
+Disassembly of section .text.startup:
+
+0000000000000000 <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm>:
+   0:  48 83 ec 18             sub    $0x18,%rsp
+   4:  66 0f 6f 05 00 00 00    movdqa 0x0(%rip),%xmm0        # c <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0xc>
+   b:  00 
+   c:  64 48 8b 04 25 28 00    mov    %fs:0x28,%rax
+  13:  00 00 
+  15:  48 89 44 24 08          mov    %rax,0x8(%rsp)
+  1a:  31 c0                   xor    %eax,%eax
+  1c:  0f 29 05 00 00 00 00    movaps %xmm0,0x0(%rip)        # 23 <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0x23>
+  23:  48 8b 44 24 08          mov    0x8(%rsp),%rax
+  28:  64 48 33 04 25 28 00    xor    %fs:0x28,%rax
+  2f:  00 00 
+  31:  66 0f 6f 05 00 00 00    movdqa 0x0(%rip),%xmm0        # 39 <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0x39>
+  38:  00 
+  39:  0f 29 05 00 00 00 00    movaps %xmm0,0x0(%rip)        # 40 <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0x40>
+  40:  66 0f 6f 05 00 00 00    movdqa 0x0(%rip),%xmm0        # 48 <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0x48>
+  47:  00 
+  48:  0f 29 05 00 00 00 00    movaps %xmm0,0x0(%rip)        # 4f <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0x4f>
+  4f:  75 05                   jne    56 <_GLOBAL__sub_I__ZN12sha256_shani9TransformEPjPKhm+0x56>
+  51:  48 83 c4 18             add    $0x18,%rsp
+  55:  c3                      retq   
+  56:  e8 00 00 00 00          callq  5b <.LC5+0xb>
```
This means that there is no extra overhead, at least with this compiler.

**Comment by MarcoFalke** [comment]
@rebroad This should fix your issue #18456

**Comment by theuni** [comment]
LGTM.

@MarcoFalke does clang have problems with the fix here? If so, @ajtowns's solution could be tweaked to be even simpler:
```patch
diff --git a/src/crypto/sha256_shani.cpp b/src/crypto/sha256_shani.cpp
index 92f67710fb..b139bceb37 100644
--- a/src/crypto/sha256_shani.cpp
+++ b/src/crypto/sha256_shani.cpp
@@ -15,9 +15,9 @@

 namespace {

-const __m128i MASK = _mm_set_epi64x(0x0c0d0e0f08090a0bULL, 0x0405060700010203ULL);
-const __m128i INIT0 = _mm_set_epi64x(0x6a09e667bb67ae85ull, 0x510e527f9b05688cull);
-const __m128i INIT1 = _mm_set_epi64x(0x3c6ef372a54ff53aull, 0x1f83d9ab5be0cd19ull);
+#define MASK _mm_set_epi64x(0x0c0d0e0f08090a0bULL, 0x0405060700010203ULL)
+#define INIT0 _mm_set_epi64x(0x6a09e667bb67ae85ull, 0x510e527f9b05688cull)
+#define INIT1  _mm_set_epi64x(0x3c6ef372a54ff53aull, 0x1f83d9ab5be0cd19ull)

 void inline  __attribute__((always_inline)) QuadRound(__m128i& state0, __m128i& state1, uint64_t k1, uint64_t k0)
 {
```
I assume the compiler would be smart enough to avoid actually doing the load each time.

**Comment by MarcoFalke** [comment]
Clang on travis is green now

**Comment by theuni** [comment]
Sidenote: we could potentially add a check for illegal instructions in the .text.startup section in one of our python binary checking tools. Though we'd have to create a per-arch blacklist/whitelist to define "illegal".

**Comment by laanwj** [comment]
> Sidenote: we could potentially add a check for illegal instructions in the .text.startup section in one of our python binary checking tools. Though we'd have to create a per-arch blacklist/whitelist to define "illegal".

My idea was to forbid `.text.startup` sections in all 'special' compilation units, e.g. those compiled with non-default instruction sets. I think that's easier to implement than instruction white/blacklists.

**Comment by theuni** [comment]
@laanwj Aha, even simpler.

**Comment by elichai** [comment]
Sounds like it solved the problem: https://github.com/bitcoin/bitcoin/issues/18456#issuecomment-612577320

ACK 85084730945a8f43fc7ce6c13fa08c86e1cae042a
