### PR TITLE
tracing: do not use `coin` after move in `CCoinsViewCache::AddCoin`

### LINKED ISSUE #25640: Tracing: coins.cpp:102:22: error: 'coin' used after it was moved [bugprone-use-after-move]
This may be fine because `int` values aren't touched by a `std::move`, but it seems brittle and confusing:

```
coins.cpp:102:22: error: 'coin' used after it was moved [bugprone-use-after-move,-warnings-as-errors]
           (uint32_t)coin.nHeight,
                     ^
coins.cpp:96:21: note: move occurred here
    it->second.coin = std::move(coin);
                    ^
```

### PR DESCRIPTION
**Pull request by rodentrabies**
This is fix for https://github.com/bitcoin/bitcoin/issues/25640.

### CODE REVIEW

File: src/coins.cpp [hunk 1]
```diff
@@ -99,9 +99,9 @@ void CCoinsViewCache::AddCoin(const COutPoint &outpoint, Coin&& coin, bool possi
     TRACE5(utxocache, add,
            outpoint.hash.data(),
            (uint32_t)outpoint.n,
-           (uint32_t)coin.nHeight,
-           (int64_t)coin.out.nValue,
-           (bool)coin.IsCoinBase());
+           (uint32_t)it->second.coin.nHeight,
+           (int64_t)it->second.coin.out.nValue,
+           (bool)it->second.coin.IsCoinBase());
```
Comment (jonatack) [inline src/coins.cpp:104]: utACK

An alternative would be to move the TRACE5 call before the std::move.

**Comment by 0xB10C** [comment]
ACK f8e228476f54b36beacc3fd09038dfeebdac6b3c

Changes look good. Ran the functional usdt interface tests (with the commits from #25528 cherry-picked). This [branch](https://github.com/0xB10C/bitcoin/tree/2022-07-bugprone-use-after-move-with-ci) is currently running in the CI here https://cirrus-ci.com/build/4542423555637248.
