### PR TITLE
qt: fix confirmed transaction labeled "open" (#13299)

### LINKED ISSUE #13299: wallet / qt: confirmed transaction labeled "open"
When syncing after a period of being offline, a transaction that the wallet received during the offline period was seen in a block, and the transactions tab in the QT ui showed the transaction.  However the transactions was not shown as "confirmed" but instead "open".  Also, the number of confirmations seems to be incorrect.

I expected the clock icon that fills in as it downloads more blocks, followed by a check mark once it sees 6 confirmations.

Instead there was no icon, and a mouse-over showed "open for next 130 blocks".  This confused me as the transaction wasn't a coinbase tx, didn't use op_csv or anything like that.  The transaction did have a locktime, but the bitcoind wallet has been setting that for a while.

Eventually the icon switched directly to a check-mark, and a mouse-over showed the number of confirmations.  However, the number of confirmations is too low by about 30 (a bit of a guess as I get tx details and then check the block height the UI reports it's synced to).

The receiving address was a bech32 native segwit v0 address, which may be related.  I asked @theuni and he pointed out code around here: https://github.com/bitcoin/bitcoin/blob/048ac8326b6952244f6e4453f4f8f6ab423eb926/src/qt/transactionrecord.cpp#L177 
which looks related; the ui may not be updating finality properly.

system:
0.16.0, linux, downloaded from bitcoincore.org, checked gpg sig.

Ubuntu 16.04, laptop hard drive.

This is not a huge issue but I think it could be confusing to users as it indicates that the transaction is not confirmed even though it really is.  The UI eventually displays confirmed though.

### PR DESCRIPTION
**Pull request by hebasto**
Fix #13299.

Since the default `nSequence` is `0xFFFFFFFE` and locktime is enabled, the checking `wtx.is_final` is meaningless until the syncing has completed (ref: #1026).

This PR makes the wallet mark a transaction "Unconfirmed" instead of misleading "Open for NNN more blocks" when syncing after a period of being offline.

Before this PR (with the issue):
screenshot from 2018-12-12 15-56-23

With this PR (the issue has been resolved):
screenshot from 2018-12-12 15-54-41

### CODE REVIEW

File: src/qt/transactionrecord.cpp [hunk 1]
```diff
@@ -172,10 +174,11 @@ void TransactionRecord::updateStatus(const interfaces::WalletTxStatus& wtx, int
...
     status.cur_num_blocks = numBlocks;
 
-    if (!wtx.is_final)
-    {
-        if (wtx.lock_time < LOCKTIME_THRESHOLD)
-        {
+    QDateTime currentDate = QDateTime::currentDateTime();
+    qint64 secs = blockDate.secsTo(currentDate);
+
+    if ((secs < 90 * 60) && !wtx.is_final) {
```
Comment (practicalswift) [inline src/qt/transactionrecord.cpp]: This `90 * 60` is meant to match the `if(secs < 90*60)` in `src/qt/bitcoingui.cpp`, right? If so, I suggest adding a common constant to make sure these values stay in sync over time :-)

Comment (hebasto) [reply src/qt/transactionrecord.cpp]: Nice. Which file is a proper place for this common constant?

Comment (practicalswift) [reply src/qt/transactionrecord.cpp]: I don't know the QT code well enough to give a good recommendation here. I'll let other developers fill in :-)

Comment (ken2812221) [reply src/qt/transactionrecord.cpp]: What is 90*60? How do you get this number?

Comment (hebasto) [reply src/qt/transactionrecord.cpp]: As @practicalswift mentioned above:

https://github.com/bitcoin/bitcoin/blob/36323e2ac6cca134de47b06c3f6403de91ee9eda/src/qt/bitcoingui.cpp#L838-L842

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
Screenshots added.

File: src/qt/transactionrecord.cpp (hunk 1 above)
Comment (hebasto) [reply src/qt/transactionrecord.cpp]: Ref #1026

**Comment by hebasto** [comment]
@practicalswift @ken2812221 
Your comments has been addressed.

**Comment by hebasto** [comment]
Rebased on top of 3e21b690d1aedb73a7dc2bc5d2ff1b011b52d927.

File: src/qt/transactiontablemodel.cpp [hunk 2]
```diff
@@ -193,8 +192,8 @@ class TransactionTablePriv
             // simply re-use the cached status.
             interfaces::WalletTxStatus wtx;
             int numBlocks;
-            if (wallet.tryGetTxStatus(rec->hash, wtx, numBlocks) && rec->statusUpdateNeeded(numBlocks)) {
-                rec->updateStatus(wtx, numBlocks);
+            if (wallet_model->wallet().tryGetTxStatus(rec->hash, wtx, numBlocks) && rec->statusUpdateNeeded(numBlocks)) {
+                rec->updateStatus(wtx, numBlocks, QDateTime::fromTime_t(wallet_model->node().getLastBlockTime()));
```
Comment (promag) [inline src/qt/transactiontablemodel.cpp]: Should avoid evaluating `QDateTime::fromTime_t(wallet_model->node().getLastBlockTime())` for each record mostly because of excessive `cs_main` locks.

File: src/qt/transactionrecord.h [hunk 3]
```diff
@@ -8,6 +8,7 @@
 #include <amount.h>
 #include <uint256.h>
 
+#include <QDateTime>
```
Comment (promag) [inline src/qt/transactionrecord.h]: nit, here a forward declaration would do.

File: src/qt/transactionrecord.h [hunk 4]
```diff
@@ -23,6 +24,8 @@ struct WalletTxStatus;
 class TransactionStatus
 {
 public:
+    static constexpr int TIME_AGO_OF_LAST_BLOCK_IN_SECONDS = 90 * 60;
```
Comment (promag) [inline src/qt/transactionrecord.h]: nit, this name is kind of weird to me.

File: src/qt/bitcoingui.cpp [hunk 5]
```diff
@@ -16,6 +16,7 @@
 #include <qt/optionsmodel.h>
 #include <qt/platformstyle.h>
 #include <qt/rpcconsole.h>
+#include <qt/transactionrecord.h>
```
Comment (promag) [inline src/qt/bitcoingui.cpp]: Maybe the constant is in the wrong place?

**Review by promag — COMMENTED** [review]
Concept ACK.

File: src/qt/transactionrecord.h (hunk 4 above)
Comment (hebasto) [reply src/qt/transactionrecord.h]: @promag 
Good naming is hard :)
Would you mind proposing a better name?

File: src/qt/bitcoingui.cpp (hunk 5 above)
Comment (hebasto) [reply src/qt/bitcoingui.cpp]: Yes, this place seems inappropriate. The reason was to avoid circular dependencies.
@promag Could you point out a more appropriate place?

**Comment by hebasto** [comment]
@promag Thank you for your review.
Your comments have been addressed. Would you mind re-reviewing?

**Comment by jonasschnelli** [comment]
utACK fb3ce75807c50055a97f573fc72bf44d997ea218

**Comment by laanwj** [comment]
utACK fb3ce75807c50055a97f573fc72bf44d997ea218

File: src/chain.h [hunk 6]
```diff
@@ -18,15 +18,23 @@
...
  * MAX_FUTURE_BLOCK_TIME.
  */
-static const int64_t TIMESTAMP_WINDOW = MAX_FUTURE_BLOCK_TIME;
+static constexpr int64_t TIMESTAMP_WINDOW = MAX_FUTURE_BLOCK_TIME;
+
+/**
+ * Maximum gap between node time and block time used
+ * for the "Catching up..." mode in GUI.
+ *
+ * Ref: https://github.com/bitcoin/bitcoin/pull/1026
```
Comment (MarcoFalke) [inline src/chain.h]: nit: instead of an external link you could inline the information (I guess the fp rate?)
