### PR TITLE
rpc: fix race condition in gettxoutsetinfo

### LINKED ISSUE #34263: rpc: Assertion '!pindex || pindex->GetBlockHash() == view->GetBestBlock()' failed during `gettxoutsetinfo`
The `CHECK_NONFATAL`  check [here](https://github.com/bitcoin/bitcoin/blob/abc6a3a4eb9814a7f17e40f7a4d330cbef86bff0/src/rpc/blockchain.cpp#L976) may fail when `gettxoutsetinfo` is called.

```
rpc/blockchain.cpp:976 std::optional<kernel::CCoinsStats> GetUTXOStats(CCoinsView *, node::BlockManager &, kernel::CoinStatsHashType, const std::function<void ()> &, const CBlockIndex *, bool): Assertion `!pindex || pindex->GetBlockHash() == view->GetBestBlock()' failed.
```

I've not written a test for this, but looking at the code, it seems that there is a race where the coins view's best block gets updated in between [here](https://github.com/bitcoin/bitcoin/blob/abc6a3a4eb9814a7f17e40f7a4d330cbef86bff0/src/rpc/blockchain.cpp#L1054C9-L1054C15) and [here](https://github.com/bitcoin/bitcoin/blob/abc6a3a4eb9814a7f17e40f7a4d330cbef86bff0/src/rpc/blockchain.cpp#L976) (e.g. because a new block is connected), causing the check to fail (resulting in an assertion failure in debug builds).

See attached debug logs for an example.

[gettxoutsetinfo_check_nonfatal.log](https://github.com/user-attachments/files/24566483/gettxoutsetinfo_check_nonfatal.log)

*This was found with a test running on [Antithesis](https://antithesis.com/).*

### PR DESCRIPTION
**Pull request by w0xlt**
Fixes #34263

A `CHECK_NONFATAL` assertion failure could occur in `gettxoutsetinfo` when a new block was connected between capturing `pindex` and validating it in `GetUTXOStats()`.

The fix removes the early `pindex` capture since `ComputeUTXOStats()` independently fetches the current best block under lock. The response now uses `stats.hashBlock` and `stats.nHeight` (the actual computed values) instead of the potentially stale `pindex`.

### CODE REVIEW

**Comment by fjahr** [comment]
Concept ACK

Do you have a hint on how to reproduce the failure?

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -969,12 +969,6 @@ static std::optional<kernel::CCoinsStats> GetUTXOStats(CCoinsView* view, node::B
         }
     }
 
-    // If the coinstats index isn't requested or is otherwise not usable, the
-    // pindex should either be null or equal to the view's best block. This is
-    // because without the coinstats index we can only get coinstats about the
-    // best block.
-    CHECK_NONFATAL(!pindex || pindex->GetBlockHash() == view->GetBestBlock());
```
Comment (luke-jr) [inline src/rpc/blockchain.cpp:1005]: Why remove this? Now that pindex is null, it should pass...

**Comment by luke-jr** [comment]
I believe there is still a race, just not properly handled with this PR.

ComputeUTXOStats sets nHeight and hashBlock without any lock held, and before/separately from acquiring the view's cursor.

**Comment by w0xlt** [comment]
> Do you have a hint on how to reproduce the failure?

To make a test that reliably reproduces the race condition detected by the Antithesis tool, we would need a way to force `CoinsDB()->GetBestBlock()` to change between the initial capture of `pindex` and the subsequent `GetUTXOStats()` call. There is currently no deterministic “pause point” in the code to do this.

Given that, the PR instead removes the early capture of pindex, eliminating this scenario.

> ComputeUTXOStats sets nHeight and hashBlock without holding any lock, and before (or separately from) acquiring the view’s cursor.

Done in 8305f29. Thanks.

File: src/rpc/blockchain.cpp (hunk 1 above)
Comment (w0xlt) [reply src/rpc/blockchain.cpp:1005]: I removed it because it seemed redundant given the current `gettxoutsetinfo` flow (normally `pindex` is `nullptr` unless querying a specific block, which already requires the index).
However, it may be better to keep it to prevent future misuse of the function with a stale pindex.

Reintroduced in 0672e1c

**Comment by w0xlt** [comment]
CI error is unrelated.

**Comment by maflcko** [comment]
> There is currently no deterministic “pause point” in the code to do this.

It would be possible to add an `UninterruptibleSleep(100ms);` (or so) in the right place to make this deterministic? Having such a patch would make testing easier.

**Comment by w0xlt** [comment]
@maflcko @fjahr 

The below commit adds a test that fails on master with the following AssertionError:
```gettxoutsetinfo failed: Internal bug detected: !pindex || pindex->GetBlockHash() == view->GetBestBlock()```
The error appears in the logs on master, but the test passes on this PR.
https://github.com/w0xlt/bitcoin/commit/beca478400c47a646f11ed4a057ff637592dbc67

Not sure if it should be added here because since it introduces test code in `gettxoutsetinfo`.

File: src/kernel/coinstats.cpp [hunk 2]
```diff
@@ -149,21 +148,27 @@ static bool ComputeUTXOStats(CCoinsView* view, CCoinsStats& stats, T hash_obj, c
 
 std::optional<CCoinsStats> ComputeUTXOStats(CoinStatsHashType hash_type, CCoinsView* view, node::BlockManager& blockman, const std::function<void()>& interruption_point)
 {
-    CBlockIndex* pindex = WITH_LOCK(::cs_main, return blockman.LookupBlockIndex(view->GetBestBlock()));
+    std::unique_ptr<CCoinsViewCursor> pcursor;
+    CBlockIndex* pindex;
+    {
+        LOCK(::cs_main);
+        pindex = blockman.LookupBlockIndex(view->GetBestBlock());
+        pcursor = view->Cursor();
```
Comment (sedited) [inline src/kernel/coinstats.cpp:155]: It doesn't really make a difference, since we are holding cs_main here, but might it be a bit clearer, if we'd read `GetBestBlock` from the cursor?

```diff
diff --git a/src/kernel/coinstats.cpp b/src/kernel/coinstats.cpp
index e1d3fff5ea..c9049ea7a3 100644
--- a/src/kernel/coinstats.cpp
+++ b/src/kernel/coinstats.cpp
@@ -151,7 +151,3 @@ std::optional<CCoinsStats> ComputeUTXOStats(CoinStatsHashType hash_type, CCoinsV
-    std::unique_ptr<CCoinsViewCursor> pcursor;
-    CBlockIndex* pindex;
-    {
-        LOCK(::cs_main);
-        pindex = blockman.LookupBlockIndex(view->GetBestBlock());
-        pcursor = view->Cursor();
-    }
+    std::unique_ptr<CCoinsViewCursor> pcursor = view->Cursor();
+    CBlockIndex* pindex = WITH_LOCK(::cs_main, return blockman.LookupBlockIndex(pcursor->GetBestBlock()));
```

**Review by sedited — COMMENTED** [review]
Concept ACK

File: src/kernel/coinstats.cpp (hunk 2 above)
Comment (w0xlt) [reply src/kernel/coinstats.cpp:155]: Thanks for the suggestion! Adopted the `pcursor->GetBestBlock()` approach - it does make the intent clearer since `pindex` is explicitly tied to the cursor's  snapshot.

One thing to note: `cs_main` is still held during `Cursor()` because internally `CCoinsViewDB::Cursor()` calls `GetBestBlock()` and `NewIterator()` as two separate  operations. 

So if I understand correctly, without the lock, a concurrent `FlushStateToDisk` could slip between them, causing the cursor's `hashBlock` to be from a different state than its iterator data - the same kind of mismatch this PR is fixing. I changed the diff to:

```diff
diff --git a/src/kernel/coinstats.cpp b/src/kernel/coinstats.cpp
index e1d3fff5ea..79da8ea4d4 100644
--- a/src/kernel/coinstats.cpp
+++ b/src/kernel/coinstats.cpp
@@ -152,8 +152,8 @@ std::optional<CCoinsStats> ComputeUTXOStats(CoinStatsHashType hash_type, CCoinsV
     CBlockIndex* pindex;
     {
         LOCK(::cs_main);
-        pindex = blockman.LookupBlockIndex(view->GetBestBlock());
         pcursor = view->Cursor();
+        pindex = blockman.LookupBlockIndex(pcursor->GetBestBlock());
     }
     CCoinsStats stats{Assert(pindex)->nHeight, pindex->GetBlockHash()};
```

**Review by sedited — APPROVED** [review]
ACK f3bf63ec4f028cf9ee0820226f44fcbe26d358c9

**Review by fjahr — COMMENTED** [review]
utACK f3bf63ec4f028cf9ee0820226f44fcbe26d358c9

Code changes look good to me. I didn't try to reproduce the race.

**Comment by fanquake** [comment]
cc @dergoegge if you want to re-run through antithesis.

File: src/rpc/blockchain.cpp [hunk 3]
```diff
@@ -1104,7 +1103,7 @@ static RPCHelpMan gettxoutsetinfo()
 
             // If a specific block was requested and the index has already synced past that height, we can return the
             // data already even though the index is not fully synced yet.
-            if (pindex->nHeight > summary.best_block_height) {
+            if (pindex && pindex->nHeight > summary.best_block_height) {
```
Comment (rkrux) [inline src/rpc/blockchain.cpp:1106]: In 5e77072fa60110a00d2bff31798d58b6c10bd3da "rpc: fix race condition in gettxoutsetinfo"

Can move the pindex declaration below now that it is not used earlier.
```diff
diff --git a/src/rpc/blockchain.cpp b/src/rpc/blockchain.cpp
index c631a93674..aea8521a02 100644
--- a/src/rpc/blockchain.cpp
+++ b/src/rpc/blockchain.cpp
@@ -1065,7 +1065,6 @@ static RPCHelpMan gettxoutsetinfo()
 {
     UniValue ret(UniValue::VOBJ);
 
-    const CBlockIndex* pindex{nullptr};
     const CoinStatsHashType hash_type{ParseHashType(self.Arg<std::string_view>("hash_type"))};
     bool index_requested = request.params[2].isNull() || request.params[2].get_bool();
 
@@ -1082,6 +1081,7 @@ static RPCHelpMan gettxoutsetinfo()
         blockman = &active_chainstate.m_blockman;
     }
 
+    const CBlockIndex* pindex{nullptr};
     if (!request.params[1].isNull()) {
         if (!g_coin_stats_index) {
             throw JSONRPCError(RPC_INVALID_PARAMETER, "Querying specific block heights requires coinstatsindex");
(END)
```

File: src/kernel/coinstats.cpp [hunk 4]
```diff
@@ -109,9 +109,8 @@ static void ApplyStats(CCoinsStats& stats, const std::map<uint32_t, Coin>& outpu
 
 //! Calculate statistics about the unspent transaction output set
 template <typename T>
-static bool ComputeUTXOStats(CCoinsView* view, CCoinsStats& stats, T hash_obj, const std::function<void()>& interruption_point)
+static bool ComputeUTXOStats(CCoinsView* view, CCoinsStats& stats, T hash_obj, const std::function<void()>& interruption_point, std::unique_ptr<CCoinsViewCursor> pcursor)
```
Comment (rkrux) [inline src/kernel/coinstats.cpp:112]: In f3bf63ec4f028cf9ee0820226f44fcbe26d358c9 "kernel: acquire coinstats cursor and block info atomically"

`stats` was being generated partially in both these `ComputeUTXOStats` functions, which reads oddly to me. Now that the `pcursor` is also moved and passed to this function, which reads oddly as well, I believe we can refactor this function in this PR to completely build the `stats` inside this function.
A side benefit is that by removing the `stats` and `pcursor` arguments, the function signature becomes quite similar to its namesake, which in turn becomes a straightforward wrapper of this function.

Builds fine, unit tests pass.
```diff
diff --git a/src/kernel/coinstats.cpp b/src/kernel/coinstats.cpp
index 49b51d64f3..69c4b44f2f 100644
--- a/src/kernel/coinstats.cpp
+++ b/src/kernel/coinstats.cpp
@@ -109,9 +109,17 @@ static void ApplyStats(CCoinsStats& stats, const std::map<uint32_t, Coin>& outpu
 
 //! Calculate statistics about the unspent transaction output set
 template <typename T>
-static bool ComputeUTXOStats(CCoinsView* view, CCoinsStats& stats, T hash_obj, const std::function<void()>& interruption_point, std::unique_ptr<CCoinsViewCursor> pcursor)
+static std::optional<CCoinsStats> ComputeUTXOStats(T hash_obj, CCoinsView* view, node::BlockManager& blockman, const std::function<void()>& interruption_point)
 {
+    std::unique_ptr<CCoinsViewCursor> pcursor;
+    CBlockIndex* pindex;
+    {
+        LOCK(::cs_main);
+        pcursor = view->Cursor();
+        pindex = blockman.LookupBlockIndex(pcursor->GetBestBlock());
+    }
     assert(pcursor);
+    CCoinsStats stats{Assert(pindex)->nHeight, pindex->GetBlockHash()};
 
     Txid prevkey;
     std::map<uint32_t, Coin> outputs;
@@ -130,7 +138,7 @@ static bool ComputeUTXOStats(CCoinsView* view, CCoinsStats& stats, T hash_obj, c
             stats.coins_count++;
         } else {
             LogError("%s: unable to read value\n", __func__);
-            return false;
+            return std::nullopt;
         }
         pcursor->Next();
     }
@@ -142,42 +150,27 @@ static bool ComputeUTXOStats(CCoinsView* view, CCoinsStats& stats, T hash_obj, c
     FinalizeHash(hash_obj, stats);
 
     stats.nDiskSize = view->EstimateSize();
-
-    return true;
+    return stats;
 }
 
 std::optional<CCoinsStats> ComputeUTXOStats(CoinStatsHashType hash_type, CCoinsView* view, node::BlockManager& blockman, const std::function<void()>& interruption_point)
 {
-    std::unique_ptr<CCoinsViewCursor> pcursor;
-    CBlockIndex* pindex;
-    {
-        LOCK(::cs_main);
-        pcursor = view->Cursor();
-        pindex = blockman.LookupBlockIndex(pcursor->GetBestBlock());
-    }
-    CCoinsStats stats{Assert(pindex)->nHeight, pindex->GetBlockHash()};
-
-    bool success = [&]() -> bool {
+    return [&]() -> std::optional<CCoinsStats> {
         switch (hash_type) {
         case(CoinStatsHashType::HASH_SERIALIZED): {
             HashWriter ss{};
-            return ComputeUTXOStats(view, stats, ss, interruption_point, std::move(pcursor));
+            return ComputeUTXOStats(ss, view, blockman, interruption_point);
         }
         case(CoinStatsHashType::MUHASH): {
             MuHash3072 muhash;
-            return ComputeUTXOStats(view, stats, muhash, interruption_point, std::move(pcursor));
+            return ComputeUTXOStats(muhash, view, blockman, interruption_point);
         }
         case(CoinStatsHashType::NONE): {
-            return ComputeUTXOStats(view, stats, nullptr, interruption_point, std::move(pcursor));
+            return ComputeUTXOStats(nullptr, view, blockman, interruption_point);
         }
         } // no default case, so the compiler can warn about missing cases
         assert(false);
     }();
-
-    if (!success) {
-        return std::nullopt;
-    }
-    return stats;
 }
 
 static void FinalizeHash(HashWriter& ss, CCoinsStats& stats)

```

**Review by rkrux — COMMENTED** [review]
Concept ACK f3bf63ec4f028cf9ee0820226f44fcbe26d358c9 for removal of the race condition.

Suggested some refactoring.

**Comment by dergoegge** [comment]
> if you want to re-run through antithesis.

Looks like this fixes it

**Comment by Mechanizm101** [comment]
[github-recovery-codes 3.txt](https://github.com/user-attachments/files/26084193/github-recovery-codes.3.txt)

File: src/rpc/blockchain.cpp (hunk 3 above)
Comment (w0xlt) [reply src/rpc/blockchain.cpp:1106]: Both suggestions look really great. Since the current code has already been tested with Antithesis, I’d prefer to apply them in a follow-up PR - unless reviewers want to re-run the tests.

File: src/kernel/coinstats.cpp (hunk 4 above)
Comment (w0xlt) [reply src/kernel/coinstats.cpp:112]: Same as above: https://github.com/bitcoin/bitcoin/pull/34451#discussion_r2955374341

**Comment by fanquake** [comment]
The refactors can be proposed in a new PR, as the changes already here will be backported.

**Comment by fanquake** [comment]
Backported to 31.x in #34800.

**Comment by rkrux** [comment]
I've raised the follow-up PR here: #34908.
