### PR TITLE
Fixes ZMQ startup with bad arguments.

### LINKED ISSUE #7496: wrong zmq argument causes core dump or infinite loop
`bitcoin-0.12.0/bin/bitcoin-qt -testnet -server -zmqpubhashblock=127.0.0.1`

It's very unclear what the format of "address" should be, so I just tried a bunch. This is 0.12rc3.

The above causes an infinite loop at startup. "Verifying wallet" and when quitting the scary window "Do not shut down the computer until this window disappears." Luckily nothing is corrupted by just killing it and trying again.

Missing .// in the address causes assertion + core dump. At least less scary/confusing than above.

```
bitcoin-0.12.0/bin/bitcoin-qt -testnet -server -debug=1 -zmqpubhashblock=tcp://127.0.0.1:28332 -zmqpuawtx=tcp://127.0.0.1:28332 -zmqpubhashtx=tcp://127.0.0.1:28332 -zmqpubrawblock=tcp:127.0.0.1:28332
bitcoin-qt: zmq/zmqpublishnotifier.cpp:92: virtual void CZMQAbstractPublishNotifier::Shutdown(): Assertion `psocket' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by mrbandrews**
Fixes #7496.

A bad ZMQ argument caused the code to create a socket but not destroy it and later in the shutdown code, zmq_destroy() hangs as a result.

This also removes a gratuitous call to the Shutdown method of ZMQNotificationInterface; the code calls the destructor right after returning, which calls Shutdown.

### CODE REVIEW

File: src/zmq/zmqnotificationinterface.cpp [hunk 1]
```diff
@@ -100,7 +100,6 @@ bool CZMQNotificationInterface::Initialize()
 
     if (i!=notifiers.end())
     {
-        Shutdown();
```
Comment (promag) [inline src/zmq/zmqnotificationinterface.cpp]: NACK, this implies that the caller calls `Shutdown()` if return is false.

Comment (laanwj) [inline src/zmq/zmqnotificationinterface.cpp]: The destructor will call it, which will be invoked automatically whether Initialize returns false or not.

**Comment by laanwj** [comment]
utACK 0040118

File: src/zmq/zmqnotificationinterface.cpp (hunk 1 above)
Comment (promag) [inline src/zmq/zmqnotificationinterface.cpp]: @laanwj assuming you delete the object.. nevertheless `Initialize()` should be all or nothing. Removing the call to `Shutdown()` leaves the notification interface partially initialised.

Comment (mrbandrews) [inline src/zmq/zmqnotificationinterface.cpp]: @promag CreateWithArguments deletes the object if initialization fails

Comment (promag) [inline src/zmq/zmqnotificationinterface.cpp]: @mrbandrews @laanwj right, forgot `Initialize()` is protected. I take it back.

**Comment by promag** [comment]
utACK 0040118.

File: src/zmq/zmqnotificationinterface.cpp (hunk 1 above)
Comment (laanwj) [inline src/zmq/zmqnotificationinterface.cpp]: > assuming you delete the object

Sure. But well if not that's a memory leak, and thus a bug in self.

**Comment by sipa** [comment]
utACK

**Comment by dcousens** [comment]
utACK 0040118
