### PR TITLE
rpc: Fix gui shutdown when waitfor* cmds are called from RPC console

### LINKED ISSUE #17495: gui: hang after calling any waitfor* cmds from RPC console
After calling any of the `waitfor*` commands in the GUI RPC console, trying to shutdown / `bitcoin-cli stop` will hang `bitcoin-qt`.

### PR DESCRIPTION
**Pull request by hebasto**
On master (7eed413e72a236b6f1475a198f7063fd24929e23), if the GUI has been started with`-server=1`, `bitcoin-qt` hangs on shutdown during calling any of the `waitfor*` commands in the GUI RPC console.

This PR suggests minimal changes to fix this bug.

Fix #17495

### CODE REVIEW

**Comment by hebasto** [comment]
While the Travis-to-GitHub connection is broken, here is Travis's [build of this PR](https://travis-ci.org/github/bitcoin/bitcoin/builds/667841108).

**Review by promag — COMMENTED** [review]
Concept ACK. Have you considered doing this in `BitcoinApplication::requestShutdown` or even between `app.exec()` and `app.requestShutdown()` in qt/bitcoin.cpp?

**Comment by hebasto** [comment]
@promag 
> Have you considered doing this in `BitcoinApplication::requestShutdown` or even between `app.exec()` and `app.requestShutdown()` in qt/bitcoin.cpp?

Yes, I have. `InterruptRPC(); StopRPC();` could be placed just before the following line
https://github.com/bitcoin/bitcoin/blob/5f9cd62f33fb4d440173b9c376cadf4887e81e9d/src/qt/bitcoin.cpp#L316

What are benefits of such approach while it requires to add `#include <rpc/server.h>` to `qt/bitcoin.cpp`?

Also, please note, that #17659 suggests to streamline the `bitcoin-qt` shutdown routine and leave the only `QApplication::exec()` call.

File: src/qt/rpcconsole.cpp [hunk 1]
```diff
@@ -687,7 +687,12 @@ void RPCConsole::setClientModel(ClientModel *model)
         startExecutor();
     }
     if (!model) {
-        // Client model is being set to 0, this means shutdown() is about to be called.
+        // Client model is being set to nullptr, this means shutdown() is about to be called.
+        if (gArgs.GetBoolArg("-server", false)) {
+            InterruptRPC();
```
Comment (jonasschnelli) [inline src/qt/rpcconsole.cpp:692]: This feels to be the wrong place to call shutdown/init functions. Shouldn't this be called through bitcoin.cpp?

**Comment by jonasschnelli** [comment]
Concept ACK

**Comment by hebasto** [comment]
Updated 29f5e02601730298020827c837db23ac6c7a8010  -> 368530de424fcb73541b089ec555a44abe475a6d ([pr18452.01](https://github.com/hebasto/bitcoin/commits/pr18452.01) -> [pr18452.02](https://github.com/hebasto/bitcoin/commits/pr18452.02), [diff](https://github.com/hebasto/bitcoin/compare/pr18452.01..pr18452.02)):

- addressed @promag's [comment](https://github.com/bitcoin/bitcoin/pull/18452#pullrequestreview-383475251)
> Concept ACK. Have you considered doing this in `BitcoinApplication::requestShutdown` or even between `app.exec()` and `app.requestShutdown()` in qt/bitcoin.cpp?

- addressed @jonasschnelli's [comment](https://github.com/bitcoin/bitcoin/pull/18452#discussion_r405414822)
> This feels to be the wrong place to call shutdown/init functions. Shouldn't this be called through bitcoin.cpp?

File: src/qt/rpcconsole.cpp (hunk 1 above)
Comment (hebasto) [reply src/qt/rpcconsole.cpp]: [Done](https://github.com/bitcoin/bitcoin/pull/18452#issuecomment-611024400).

**Review by promag — COMMENTED** [review]
Code review ACK 368530de424fcb73541b089ec555a44abe475a6d, the approach looks better.

File: src/qt/bitcoin.cpp [hunk 2]
```diff
@@ -311,6 +312,11 @@ void BitcoinApplication::requestShutdown()
     // Request node shutdown, which can interrupt long operations, like
     // rescanning a wallet.
     m_node.startShutdown();
+    // Stop RPC for clean shutdown if waitfor* commands are executed.
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/qt/bitcoin.cpp:315]: There are other `NodeImpl::startShutdown()` call sites that are irrelevant to the problem:
https://github.com/bitcoin/bitcoin/blob/2b9a4a13324ac3f0adf712d01fb8f2ba914cdc8f/src/qt/splashscreen.cpp#L141

and

https://github.com/bitcoin/bitcoin/blob/2b9a4a13324ac3f0adf712d01fb8f2ba914cdc8f/src/qt/splashscreen.cpp#L223

[the remark this answers is not in the document]
Comment (promag) [reply src/qt/bitcoin.cpp:315]: I did check those and TBH I think it's still fine.

[the remark this answers is not in the document]
Comment (hebasto) [reply src/qt/bitcoin.cpp:315]: > I did check those and TBH I think it's still fine.

To be clear, what exactly is "still fine" in your opinion: pr code or your suggestion to move to the `NodeImpl` ?

**Comment by hebasto** [comment]
Updated 368530de424fcb73541b089ec555a44abe475a6d  -> 59b55ccf9aae2f75e86245434be26e1f1a729659 ([pr18452.02](https://github.com/hebasto/bitcoin/commits/pr18452.02) -> [pr18452.03](https://github.com/hebasto/bitcoin/commits/pr18452.03), [diff](https://github.com/hebasto/bitcoin/compare/pr18452.02..pr18452.03)):

- addressed @promag's [comment](https://github.com/bitcoin/bitcoin/pull/18452#discussion_r406707140)
> I think you could move this to `NodeImpl::startShutdown`?

File: src/qt/bitcoin.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (hebasto) [reply src/qt/bitcoin.cpp]: [Implemented](https://github.com/bitcoin/bitcoin/pull/18452#issuecomment-612135003).

**Comment by promag** [comment]
Tested ACK 59b55ccf9aae2f75e86245434be26e1f1a729659.

File: src/rpc/server.cpp [hunk 3]
```diff
@@ -285,21 +287,28 @@ void StartRPC()
...
 
 void StopRPC()
 {
+    // This function could be called twice if the GUI has been started with -server=1.
+    assert(!g_rpc_running);
+    if (g_rpc_stopped) return;
     LogPrint(BCLog::RPC, "Stopping RPC\n");
     deadlineTimers.clear();
     DeleteAuthCookie();
+    g_rpc_stopped = true;
```
Comment (luke-jr) [inline src/rpc/server.cpp:311]: Race?

Comment (hebasto) [reply src/rpc/server.cpp:311]: https://github.com/bitcoin/bitcoin/blob/59b55ccf9aae2f75e86245434be26e1f1a729659/src/rpc/server.cpp#L24

**Comment by hebasto** [comment]
Updated 59b55ccf9aae2f75e86245434be26e1f1a729659  -> 2d7b6bc6c9c49ac95c7aa97d9f753aec97456e0b ([pr18452.03](https://github.com/hebasto/bitcoin/commits/pr18452.03) -> [pr18452.04](https://github.com/hebasto/bitcoin/commits/pr18452.04), [diff](https://github.com/hebasto/bitcoin/compare/pr18452.03..pr18452.04)):

- addressed @luke-jr's [comment](https://github.com/bitcoin/bitcoin/pull/18452#discussion_r413417576)
> Race?

File: src/rpc/server.cpp (hunk 3 above)
Comment (hebasto) [reply src/rpc/server.cpp]: [Updated](https://github.com/bitcoin/bitcoin/pull/18452#issuecomment-620300495).

**Comment by hebasto** [comment]
Rebased 2d7b6bc6c9c49ac95c7aa97d9f753aec97456e0b  -> da73f1513a637a9f347b64de66564d6cdb2541f8 ([pr18452.04](https://github.com/hebasto/bitcoin/commits/pr18452.04) -> [pr18452.05](https://github.com/hebasto/bitcoin/commits/pr18452.05)) due to the conflict with #18814.

**Comment by jonasschnelli** [comment]
utACK da73f1513a637a9f347b64de66564d6cdb2541f8
