### PR TITLE
log: Fix log message for -par=1

### LINKED ISSUE #17139: log, doc: Confusing log message
```
bitcoind -par=1
```

Excerpt from the `debug.log`:

```
Using 0 threads for script verification
```

Zero? I guess not ;)

### PR DESCRIPTION
**Pull request by hebasto**
Fix #17139

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

File: src/init.cpp [hunk 1]
```diff
@@ -1256,10 +1256,12 @@ bool AppInitMain(NodeContext& node)
     InitSignatureCache();
     InitScriptExecutionCache();
 
-    LogPrintf("Using %u threads for script verification\n", nScriptCheckThreads);
     if (nScriptCheckThreads) {
+        LogPrintf("Using %u threads concurrently for script verification\n", nScriptCheckThreads);
         for (int i=0; i<nScriptCheckThreads-1; i++)
             threadGroup.create_thread([i]() { return ThreadScriptCheck(i); });
+    } else {
+        LogPrintf("Using the only thread for script verification\n");
```
Comment (laanwj) [inline src/init.cpp]: Concept ACK, my only comment would be that `-par=0` and `-par=1` do the same thing, but log different messages.

Comment (hebasto) [reply src/init.cpp]: Not exactly:
https://github.com/bitcoin/bitcoin/blob/08e29473126d5cc4df6d2b3f368c6f6f641c0bd8/src/init.cpp#L380

Comment (laanwj) [reply src/init.cpp]: I'm not talking about the input argument, but the already-processed value we end up with here.

Comment (hebasto) [reply src/init.cpp]: After this code
https://github.com/bitcoin/bitcoin/blob/08e29473126d5cc4df6d2b3f368c6f6f641c0bd8/src/init.cpp#L1064-L1071

is executed in `AppInitParameterInteraction()`, `nScriptCheckThreads==1` is an impossible value.

Comment (laanwj) [reply src/init.cpp]: Ok, so it will never log `Using 1 threads concurrently for script verification`?

Comment (hebasto) [reply src/init.cpp]: Sure.

Comment (practicalswift) [inline src/init.cpp]: Something feels a bit off with the wording here. What about "Using one thread for script verification"?

Comment (laanwj) [reply src/init.cpp]: It's not just any thread though, it's the main thread. No additional threads are spawned. I think that's what he's trying to convey.

Comment (practicalswift) [reply src/init.cpp]: "Validation concurrency disabled: using the main thread for script validation."

Comment (hebasto) [reply src/init.cpp]: Isn't this the thread:
https://github.com/bitcoin/bitcoin/blob/feb1a8c03aff0d37730d80eee7a05cc7e4729850/src/init.cpp#L1267
?

Comment (laanwj) [reply src/init.cpp]: That spawns the scheduler thread, which is unrelated to script verification.

Comment (MarcoFalke) [reply src/init.cpp]: On `-par=1`, it will inline the calls into the current thread. See also:

```
git grep '\-par=' test

Comment (MarcoFalke) [inline src/init.cpp]:
```suggestion
        LogPrintf("Script verification is done in the main thread\n");
```

Comment (laanwj) [reply src/init.cpp]: But script verification is always done in the main thread, the other threads are only additional :smile:

Comment (practicalswift) [reply src/init.cpp]: "Script verification is done in the main thread only (no validation concurrency)"

Comment (laanwj) [reply src/init.cpp]: or "Script verification uses N additional threads" where N can be 0…

Comment (hebasto) [reply src/init.cpp]: > Yeah, let's make it a one-line "fix"

Not sure about "one-line fix" as actual _additional_ threads number is `nScriptCheckThreads-1`.

Comment (hebasto) [reply src/init.cpp]: True, it is shorter than conditional operator ;)

**Comment by hebasto** [comment]
All comments have been addressed.

File: src/init.cpp (hunk 1 above)
Comment (jnewbery) [reply src/init.cpp]: I don't think this should be `nScriptCheckThreads-1`. `nScriptCheckThreads` is the number of threads that are dedicated to script checking, so:

- if `nScriptCheckThreads` >= 2, then log "Script verification uses {nScriptCheckThreads} additional threads"
- if `nScriptCheckThreads` == 0, then script checking is done on the main thread so log "Script verification uses 0 additional threads"
- `nScriptCheckThreads` cannot == 1 because of the logic in init.cpp

so you just want:

`LogPrintf("Script verification uses %d dedicated threads\m", nScriptCheckThreads);`

The log is already essentially correct. I think you just need to add the word 'dedicated' or 'additional' (I prefer 'dedicated').

Comment (sipa) [reply src/init.cpp]: That's not correct; it should be `LogPrintf("Script verification uses %d dedicated threads\m", nScriptCheckThreads - 1);` then.

**Comment by jnewbery** [comment]
Tested ACK 8a0ca5e9de021ce2f722b321f27208a7bc7110f7

If we wanted to be completely explicit we could log "Script verification uses main thread and %d dedicated threads\n"

**Comment by laanwj** [comment]
ACK 8a0ca5e9de021ce2f722b321f27208a7bc7110f7

> If we wanted to be completely explicit we could log "Script verification uses main thread and %d dedicated threads\n"

I know bitcoin core is lacking in user documentation, but I don't think the debug log is the place for it :smile: 
The value is now correct, which is good for troubleshooting.

File: src/init.cpp (hunk 1 above)
Comment (laanwj) [reply src/init.cpp]: @sipa The `std::max(nScriptCheckThreads-1, 0)` bound is there because nScriptCheckThreads might be zero at this point.
