### PR TITLE
util: Set safe permissions for data directory and `wallets/` subdir

### LINKED ISSUE #13371: -sysperms=false (default) doesn't appear to do anything
Despite -sysperms=false (default) docs saying files will be created with perms 077, none of my default-created datadirs appear to have any permissions aside from 0600. Maybe I'm misreading the docs but it appears umask(077) isnt doing anything.

### LINKED ISSUE #15902: Wrong permissions for datadir and walletdir
On my Linux Mint 19.1:
```bash
$ umask
0022
```

After the first run of `bitcoin-qt -sysperm=false` the `0700` permissions are expected for both the datadir (`~/.bitcoin`) and the walletdir (`~/.bitcoin/wallets`).

Actually, the directories are created with such access permissions:
```bash
$ stat ~/.bitcoin | grep Uid
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ hebasto)   Gid: ( 1000/ hebasto)
$ stat ~/.bitcoin/wallets | grep Uid
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ hebasto)   Gid: ( 1000/ hebasto)
```

Refs:
- #4286
- #13371
- #13389

NOTE: reading through the initial PR #4286 makes me think it was controversial. Is it a better and simpler way to just get rid of `-sysperm` option? I believe a user who needs this option can easily run `chown` command.

### LINKED ISSUE #22595: `make install` creates files/folders with bad permissions if custom umask is used
The `make install` script, which most users would run via `sudo` to install into `/usr/local`, will use the current umask of the root user when creating certain files and directories. If one uses a restrictive umask by default (e.g. `umask 077`), this means that only the root user will be able to use the full Bitcoin package.

**Expected behavior**

The install script creates all directories and files, including man pages, etc., with permissions `644` / `755`.

**Actual behavior**

Certain folders are created using the default umask, e.g.:

- /usr/local/share/man/man1/
- /usr/local/lib/pkgconfig/
- [...]

This means that only root can access files in these folders and other users won't be able to read the man pages (for example).

**To reproduce**

```bash
$ ./autogen.sh
$ make
$ sudo -iu root
% umask 077
% make install
```

**System information**

OS: Linux
bitcoind version: HEAD

### PR DESCRIPTION
**Pull request by hebasto**
On master (1e7564eca8a688f39c75540877ec3bdfdde766b1) docs say:
```
$ ./src/bitcoind -help | grep -A 3 sysperms
  -sysperms
       Create new files with system default permissions, instead of umask 077
       (only effective with disabled wallet functionality)

```

Basing on that, one could expect that running `bitcoind` first time will create data directory and `wallets/` subdirectory with safe 0700 permissions.

But that is not the case:
```
$ stat .bitcoin | grep id
Access: (0775/drwxrwxr-x)  Uid: ( 1000/ hebasto)   Gid: ( 1000/ hebasto)
$ stat .bitcoin/wallets | grep id
Access: (0775/drwxrwxr-x)  Uid: ( 1000/ hebasto)   Gid: ( 1000/ hebasto)
```

Both directories, in fact, are created with system default permissions.

With this PR:
```
$ stat .bitcoin/wallets | grep id
Access: (0700/drwx------)  Uid: ( 1000/ hebasto)   Gid: ( 1000/ hebasto)
$ stat .bitcoin/wallets | grep id
Access: (0700/drwx------)  Uid: ( 1000/ hebasto)   Gid: ( 1000/ hebasto)
```

---

This PR:
- is alternative to bitcoin/bitcoin#13389 
- fixes bitcoin/bitcoin#15902 
- fixes bitcoin/bitcoin#22595
- closes bitcoin/bitcoin#13371
- reverts bitcoin/bitcoin#4286

Changes in behavior: removed `-sysperms` command-line argument / configure option. The related discussions are here:
- https://github.com/bitcoin/bitcoin/pull/13389#issuecomment-395306690
- https://github.com/bitcoin/bitcoin/pull/13389#issuecomment-539906114
- https://github.com/bitcoin/bitcoin/pull/13389#discussion_r279160472

If users rely on non-default access permissions, they could use `chmod`.

### CODE REVIEW

File: src/util/system.cpp [hunk 1]
```diff
@@ -741,6 +750,10 @@ const fs::path &GetBlocksDir()
 
 const fs::path &GetDataDir(bool fNetSpecific)
 {
+#ifndef WIN32
```
Comment (laanwj) [inline src/util/system.cpp]: GetDataDir, a getter, is not the place to do things such as set the umask. Please don't add these kind of side-effects.

**Comment by laanwj** [comment]
Concept ACK on removing `-sysperms`.

File: src/util/system.cpp (hunk 1 above)
Comment (hebasto) [reply src/util/system.cpp]: Maybe `GetDataDir` is not a proper name for this function as it already has an intended side-effect:
https://github.com/bitcoin/bitcoin/blob/ddd3cd30cb050fe9b8738778beecba1d8bd50d52/src/util/system.cpp#L777-L780

Comment (laanwj) [reply src/util/system.cpp]: I know. I kind of want to get rid of that too. But don't add any more.

**Comment by hebasto** [comment]
@laanwj 
Thank you for your review. All your comments have been addressed.

File: src/util/system.cpp [hunk 2]
```diff
@@ -65,6 +65,15 @@
 
 #include <thread>
 
+#ifndef WIN32
+static const int private_umask = 077;
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/util/system.cpp]: Done.

File: src/util/system.cpp (hunk 1 above)
Comment (hebasto) [reply src/util/system.cpp]: Done.

File: src/util/system.h [hunk 3]
```diff
@@ -35,6 +35,10 @@
 
 #include <boost/thread/condition_variable.hpp> // for boost::thread_interrupted
 
+#ifndef WIN32
+void SetDefaultUmask();
```
Comment (laanwj) [inline src/util/system.h]: Wouldn't `SetupEnvironment` be the right place for this? Or is that too early?

Comment (hebasto) [reply src/util/system.h]: Currently, `SetDefaultUmask()` is called just before the first possible disk write.

`SetupEnvironment()` seems too broad, as it is called in utilities too. And, yes, I think it is too early. But I could be wrong ;)

Comment (laanwj) [reply src/util/system.h]: But does that matter? What would be the consequences of setting it too early? Why wouldn't we want to set the umask for the utilties?

Comment (hebasto) [reply src/util/system.h]: > Wouldn't `SetupEnvironment` be the right place for this?

Agree.

**Comment by hebasto** [comment]
@laanwj Thank you for review. Your comment has been addressed.

**Comment by hebasto** [comment]
@promag Would you mind reviewing this PR?

**Comment by hebasto** [comment]
Rebased 7213e8cbe685556365021176d686f45bdd036dae -> 67b12091c78b0183aa9dc451d176b16f832d93f7 ([pr17127.04](https://github.com/hebasto/bitcoin/commits/pr17127.04) -> [pr17127.05](https://github.com/hebasto/bitcoin/commits/pr17127.05)) due to the conflict with #15761.

**Comment by hebasto** [comment]
Rebased 67b12091c78b0183aa9dc451d176b16f832d93f7 -> 297e61cdb8293c0bfd1d43f22eefbece3f541802 ([pr17127.05](https://github.com/hebasto/bitcoin/commits/pr17127.05) -> [pr17127.06](https://github.com/hebasto/bitcoin/commits/pr17127.06)) due to the conflict with #16224.

**Comment by jonasschnelli** [comment]
utACK 297e61cdb8293c0bfd1d43f22eefbece3f541802

**Comment by hebasto** [comment]
Rebased 297e61cdb8293c0bfd1d43f22eefbece3f541802 -> 337a7709502f562b764cce78f6de1d1a744cebd8 ([pr17127.06](https://github.com/hebasto/bitcoin/commits/pr17127.06) -> [pr17127.07](https://github.com/hebasto/bitcoin/commits/pr17127.07)) due to the conflict with #15935.

**Comment by hebasto** [comment]
Rebased 337a7709502f562b764cce78f6de1d1a744cebd8 -> 788143749f7a71d0b3af12275e2fde7dc74ff03d ([pr17127.07](https://github.com/hebasto/bitcoin/commits/pr17127.07) -> [pr17127.08](https://github.com/hebasto/bitcoin/commits/pr17127.08)) due to the conflict with #19561.

**Comment by hebasto** [comment]
Rebased 788143749f7a71d0b3af12275e2fde7dc74ff03d -> 677617651e5b831da8d12f769a47d2957400d987 ([pr17127.08](https://github.com/hebasto/bitcoin/commits/pr17127.08) -> [pr17127.09](https://github.com/hebasto/bitcoin/commits/pr17127.09)) due to the conflict with #19779.

**Comment by hebasto** [comment]
Rebased 677617651e5b831da8d12f769a47d2957400d987 -> ef8ed07715f90bc156a4d4015ea1db9ee975963d ([pr17127.09](https://github.com/hebasto/bitcoin/commits/pr17127.09) -> [pr17127.10](https://github.com/hebasto/bitcoin/commits/pr17127.10)) due to the conflict with #15367.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by hebasto** [comment]
Rebased ef8ed07715f90bc156a4d4015ea1db9ee975963d -> 9b105d7289a793eaa30ae8fe7937b1356969758b ([pr17127.10](https://github.com/hebasto/bitcoin/commits/pr17127.10) -> [pr17127.11](https://github.com/hebasto/bitcoin/commits/pr17127.11)) due to the conflict with #20744.

**Comment by hebasto** [comment]
PR description has been updated.

**Review by willcl-ark — APPROVED** [review]
ACK 9b105d7289a793eaa30ae8fe7937b1356969758b

The test datadir will have the following files created in it after node shutdown:

banlist.json, debug.log, fee_estimates.dat, mempool.dat, peers.dat, settings.json

Would it be worth adding a permissions test for e.g debug.log to check that the correct umask is also being applied to files?

**Comment by willcl-ark** [comment]
> Sorry, but I didn't quite get your suggestion. Mind elaborating it?

My fault for not being clearer!

You added a test for [directory permissions](https://github.com/hebasto/bitcoin/blob/20191013-permissions/test/functional/feature_fs_permissions.py#L19-L23), but not not one for files. As files and folders will be created with different permissions,  it might make sense to add this at the same time?

For directories the test covers `datadir` and `walletsdir`. For files I was suggesting we could test `debug.log`.

**Comment by willcl-ark** [comment]
This also fixes https://github.com/bitcoin/bitcoin/issues/22595

**Comment by hebasto** [comment]
Updated 9b105d7289a793eaa30ae8fe7937b1356969758b -> 07c496d01b7ab03451b1d8278cef2652540ff191 ([pr17127.11](https://github.com/hebasto/bitcoin/commits/pr17127.11) -> [pr17127.12](https://github.com/hebasto/bitcoin/commits/pr17127.12)):
- rebased
- addressed @willcl-ark's [comment](https://github.com/bitcoin/bitcoin/pull/17127#issuecomment-1332405771)

**Review by willcl-ark — APPROVED** [review]
ACK 07c496d01

Might want to add this to the release notes too?

File: src/util/system.cpp [hunk 4]
```diff
@@ -64,6 +64,16 @@
 #include <thread>
 #include <typeinfo>
 
+#ifndef WIN32
+namespace {
+constexpr mode_t private_umask = 0077;
```
Comment (fanquake) [inline src/util/system.cpp:69]: Is there a reason to add 10 lines here, and another `#ifndef`, instead of putting the 2 lines of code where they are actually used? i.e why not just:
```cpp
#ifndef WIN32
    constexpr mode_t private_umask = 0077;
    umask(private_umask);
#endif
```
in `SetupEnvironment()`?

**Comment by hebasto** [comment]
Updated 07c496d01b7ab03451b1d8278cef2652540ff191 -> 15c7105a2ddc720ed0cac0fe7995755cad437880 ([pr17127.12](https://github.com/hebasto/bitcoin/commits/pr17127.12) -> [pr17127.13](https://github.com/hebasto/bitcoin/commits/pr17127.13)):
- rebased
- addressed @fanquake's [comment](https://github.com/bitcoin/bitcoin/pull/17127#discussion_r1063355778)

File: src/util/system.cpp (hunk 4 above)
Comment (hebasto) [reply src/util/system.cpp]: Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/17127#issuecomment-1417887067).

**Review by john-moffett — COMMENTED** [review]
Approach ACK 15c7105a2ddc720ed0cac0fe7995755cad437880

I agree that this may warrant an explicit release note considering a command line option is being dropped.

**Comment by hebasto** [comment]
Updated 15c7105a2ddc720ed0cac0fe7995755cad437880 -> c9ba4f9ecb1a282d98e7456a84ca84362b161757 ([pr17127.13](https://github.com/hebasto/bitcoin/commits/pr17127.13) -> [pr17127.14](https://github.com/hebasto/bitcoin/commits/pr17127.14), [diff](https://github.com/hebasto/bitcoin/compare/pr17127.13..pr17127.14)):

- addressed @john-moffett's comments

File: src/i2p.cpp [hunk 5]
```diff
@@ -336,7 +336,7 @@ void Session::GenerateAndSavePrivateKey(const Sock& sock)
 {
     DestGenerate(sock);
 
-    // umask is set to 077 in init.cpp, which is ok (unless -sysperms is given)
+    // umask is set to 077 in init.cpp, which is ok.
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/i2p.cpp]: Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/17127#issuecomment-1418911048).

File: src/rpc/request.cpp [hunk 6]
```diff
@@ -86,7 +86,7 @@ bool GenerateAuthCookie(std::string *cookie_out)
     std::string cookie = COOKIEAUTH_USER + ":" + HexStr(rand_pwd);
 
     /** the umask determines what permissions are used to create this file -
-     * these are set to 077 in init.cpp unless overridden with -sysperms.
+     * these are set to 077 in init.cpp.
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/rpc/request.cpp]: Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/17127#issuecomment-1418911048).

**Comment by john-moffett** [comment]
ACK c9ba4f9ecb1a282d98e7456a84ca84362b161757

**Review by willcl-ark — APPROVED** [review]
ACK c9ba4f9ecb1a282d98e7456a84ca84362b161757
