### PR TITLE
qt: Fix deprecated QCharRef usage

### LINKED ISSUE #18080: gui: deprecated QCharRef usage in splashscreen
Noticed today while building [master](8a56f79d491271120abc3843c46e9dda44edd308).

```bash
GUI: Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
```

From a quick look the issue is somewhere in [splashscreen.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/qt/splashscreen.cpp). 

You should see the warning if you quit while the splashscreen is still displayed. Likely requires a recent version of Qt (I'm using 5.14.1).

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by hebasto**
From Qt docs:
- [`QKeyEvent::text()`](https://doc.qt.io/qt-5/qkeyevent.html#text):
> Return values when modifier keys such as Shift, Control, Alt, and Meta are pressed differ among platforms and could return an empty string.

- [`QString::operator[]()`](https://doc.qt.io/qt-5/qstring.html#operator-5b-5d):

> **Note:** Before Qt 5.14 it was possible to use this operator to access a character at an out-of-bounds position in the string, and then assign to such a position, causing the string to be automatically resized. Furthermore, assigning a value to the returned `QCharRef` would cause a detach of the string, even if the string has been copied in the meanwhile (and the `QCharRef` kept alive while the copy was taken). These behaviors are deprecated, and will be changed in a future version of Qt.

Since Qt 5.14 this causes a `QCharRef` warning if any modifier key is pressed while the splashscreen is still displayed.

Fix #18080.

Note: Ctrl+Q will also close the spashscreen now.

### CODE REVIEW

**Comment by brakmic** [comment]
Concept ACK.

**Review by brakmic — APPROVED** [review]
Tested on macOS Catalina 10.15.3 with Qt 5.14.1

**Review by jonasschnelli — APPROVED** [review]
utACK ac57859e53167f4ff3da467b616b0902c93701a9

**Comment by hebasto** [comment]
@brakmic 
> Tested on macOS Catalina 10.15.3 with Qt 5.14.1

Thank you for your review and testing.

Usually, when a reviewer approves PR, he [starts his message](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#code-review) with `ACK top_commit_hash` ;)

File: src/qt/splashscreen.cpp [hunk 1]
```diff
@@ -137,7 +137,7 @@ SplashScreen::~SplashScreen()
 bool SplashScreen::eventFilter(QObject * obj, QEvent * ev) {
     if (ev->type() == QEvent::KeyPress) {
         QKeyEvent *keyEvent = static_cast<QKeyEvent *>(ev);
-        if(keyEvent->text()[0] == 'q') {
+        if (keyEvent->key() == Qt::Key_Q) {
```
Comment (laanwj) [inline src/qt/splashscreen.cpp]: I think this slightly changes the behavior from accepting 'q' to 'q' and 'Q' (shift-q). But I'm fine with this, personally.
