### PR TITLE
fuzz: keep `coins_view` fuzzers within caller contracts

### LINKED ISSUE #34645: oss-fuzz: coins_view_overlay: ASSERT: m_dirty_count == 0
https://issues.oss-fuzz.com/issues/486389268
```bash
Command: /mnt/scratch0/clusterfuzz/resources/platform/linux/unshare -c -n /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_bitcoin-core_83aef6625aaeafa301867de74608b320f3c923fe/revisions/coins_view_overlay -rss_limit_mb=2560 -timeout=60 -runs=100 /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-e84f31ab73616c1a282fb40ce4e33abd394fb911
	Time ran: 0.49608683586120605
	
	INFO: Running with entropic power schedule (0xFF, 100).
	INFO: Seed: 360939801
	INFO: Loaded 1 modules   (603691 inline 8-bit counters): 603691 [0x55a793000eb0, 0x55a7930944db),
	INFO: Loaded 1 PC tables (603691 PCs): 603691 [0x55a7930944e0,0x55a7939ca790),
	/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_bitcoin-core_83aef6625aaeafa301867de74608b320f3c923fe/revisions/coins_view_overlay: Running 1 inputs 100 time(s) each.
	Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-e84f31ab73616c1a282fb40ce4e33abd394fb911
	coins.cpp:283 void CCoinsViewCache::Flush(bool): Assertion `m_dirty_count == 0` failed.
	==241== ERROR: libFuzzer: deadly signal
	    #0 0x55a7909aa551 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
	    #1 0x55a79089bff8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
	    #2 0x55a79087eb45 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:231:3
	    #3 0x7f08d19c041f in libpthread.so.0
	    #4 0x7f08d17b400a in __libc_signal_restore_set /build/glibc-B3wQXB/glibc-2.31/sysdeps/unix/sysv/linux/internal-signals.h:86:3
	    #5 0x7f08d17b400a in raise /build/glibc-B3wQXB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:48:3
	    #6 0x7f08d1793858 in abort /build/glibc-B3wQXB/glibc-2.31/stdlib/abort.c:79:7
	    #7 0x55a7915cc5e2 in assertion_fail(std::__1::source_location const&, std::__1::basic_string_view<char, std::__1::char_traits<char>>) [bitcoin-core/src/util/check.cpp:41](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/util/check.cpp#L41):5
	    #8 0x55a79128c7ea in inline_assertion_check<false, bool> [bitcoin-core/src/util/check.h:90](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/util/check.h#L90):13
	    #9 0x55a79128c7ea in CCoinsViewCache::Flush(bool) [bitcoin-core/src/coins.cpp:283](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/coins.cpp#L283):5
	    #10 0x55a790c4dea7 in operator() [bitcoin-core/src/test/fuzz/coins_view.cpp:135](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/test/fuzz/coins_view.cpp#L135):34
	    #11 0x55a790c4dea7 in CallOneOf<(lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:116:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:134:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:137:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:140:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:146:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:160:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:164:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:167:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:173:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:181:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:189:13), (lambda at /src/bitcoin-core/src/test/fuzz/coins_view.cpp:197:13)> [bitcoin-core/src/test/fuzz/util.h:42](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/test/fuzz/util.h#L42):27
	    #12 0x55a790c4dea7 in TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool) [bitcoin-core/src/test/fuzz/coins_view.cpp:114](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/test/fuzz/coins_view.cpp#L114):9
	    #13 0x55a790c4c486 in coins_view_overlay_fuzz_target(std::__1::span<unsigned char const, 18446744073709551615ul>) [bitcoin-core/src/test/fuzz/coins_view.cpp:404](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/test/fuzz/coins_view.cpp#L404):5
	    #14 0x55a7912282f4 in operator() /usr/local/include/c++/v1/__functional/function.h:274:12
	    #15 0x55a7912282f4 in operator() /usr/local/include/c++/v1/__functional/function.h:772:10
	    #16 0x55a7912282f4 in test_one_input [bitcoin-core/src/test/fuzz/fuzz.cpp:88](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/test/fuzz/fuzz.cpp#L88):5
	    #17 0x55a7912282f4 in LLVMFuzzerTestOneInput [bitcoin-core/src/test/fuzz/fuzz.cpp:216](https://github.com/bitcoin/bitcoin/blob/ee2065fdeaca91caaad9eb7daeeffe939441d804/src/test/fuzz/fuzz.cpp#L216):5
	    #18 0x55a79088022d in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:619:13
	    #19 0x55a790869f42 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:329:6
	    #20 0x55a79086fe10 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:865:9
	    #21 0x55a79089c9a2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
	    #22 0x7f08d1795082 in __libc_start_main /build/glibc-B3wQXB/glibc-2.31/csu/libc-start.c:308:16
	    #23 0x55a79086302d in _start
	
	NOTE: libFuzzer has rudimentary signal handlers.
	      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
	SUMMARY: libFuzzer: deadly signal
```

### PR DESCRIPTION
**Pull request by l0rinc**
### Problem
This is an alternative approach to #34647, fixes #34645.

### Fix
First, add `CheckedSub` and use it for decrements of `m_dirty_count` and `cachedCoinsUsage`, so unsigned underflows turn into immediate failures instead of silently wrapping and only failing later.

<details><summary>Assertion `j <= i' failed.</summary>

```bash
util/overflow.h:44 T CheckedSub(const T, const U) [T = unsigned long, U = bool]: Assertion `j <= i' failed.
==72817== ERROR: libFuzzer: deadly signal
    #0 0x556e9225eab5 in __sanitizer_print_stack_trace (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x191dab5) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #1 0x556e921acafc in fuzzer::PrintStackTrace() (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x186bafc) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #2 0x556e92191bb7 in fuzzer::Fuzzer::CrashCallback() (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x1850bb7) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #3 0x7164cfc458cf  (/lib/x86_64-linux-gnu/libc.so.6+0x458cf) (BuildId: ae7440bbdce614e0e79280c3b2e45b1df44e639c)
    #4 0x7164cfca49bb in __pthread_kill_implementation nptl/pthread_kill.c:43:17
    #5 0x7164cfca49bb in __pthread_kill_internal nptl/pthread_kill.c:89:10
    #6 0x7164cfca49bb in pthread_kill nptl/pthread_kill.c:100:10
    #7 0x7164cfc4579d in raise signal/../sysdeps/posix/raise.c:26:13
    #8 0x7164cfc288cc in abort stdlib/abort.c:73:3
    #9 0x556e92f9d591 in assertion_fail(std::source_location const&, std::basic_string_view<char, std::char_traits<char>>) /mnt/my_storage/bitcoin/src/util/check.cpp:41:5
    #10 0x556e9250daf0 in bool&& inline_assertion_check<false, bool>(bool&&, std::source_location const&, std::basic_string_view<char, std::char_traits<char>>) /mnt/my_storage/bitcoin/src/util/check.h:90:13
    #11 0x556e9250daf0 in unsigned long CheckedSub<unsigned long, bool>(unsigned long, bool) /mnt/my_storage/bitcoin/src/util/overflow.h:44:5
    #12 0x556e9250daf0 in CoinsViewCacheCursor::NextAndMaybeErase(std::pair<COutPoint const, CCoinsCacheEntry>&) /mnt/my_storage/bitcoin/src/coins.h:282:25
    #13 0x556e92507eb2 in (anonymous namespace)::MutationGuardCoinsViewCache::BatchWrite(CoinsViewCacheCursor&, uint256 const&) /mnt/my_storage/bitcoin/src/test/fuzz/coins_view.cpp:90:75
    #14 0x556e92c17a2b in CCoinsViewCache::Flush(bool) /mnt/my_storage/bitcoin/src/coins.cpp:282:11
    #15 0x556e924fb732 in TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_1::operator()() const /mnt/my_storage/bitcoin/src/test/fuzz/coins_view.cpp:135:34
    #16 0x556e924fb732 in unsigned long CallOneOf<TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_0, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_1, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_2, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_3, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_4, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_5, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_6, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_7, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_8, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_9, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_10, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_11>(FuzzedDataProvider&, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_0, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_1, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_2, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_3, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_4, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_5, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_6, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_7, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_8, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_9, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_10, TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool)::$_11) /mnt/my_storage/bitcoin/src/test/fuzz/util.h:42:27
    #17 0x556e924fb732 in TestCoinsView(FuzzedDataProvider&, CCoinsViewCache&, CCoinsView&, bool) /mnt/my_storage/bitcoin/src/test/fuzz/coins_view.cpp:114:9
    #18 0x556e92503b0c in coins_view_overlay_fuzz_target(std::span<unsigned char const, 18446744073709551615ul>) /mnt/my_storage/bitcoin/src/test/fuzz/coins_view.cpp:404:5
    #19 0x556e92bcb7a5 in std::function<void (std::span<unsigned char const, 18446744073709551615ul>)>::operator()(std::span<unsigned char const, 18446744073709551615ul>) const /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/bits/std_function.h:593:9
    #20 0x556e92bcb7a5 in test_one_input(std::span<unsigned char const, 18446744073709551615ul>) /mnt/my_storage/bitcoin/src/test/fuzz/fuzz.cpp:88:5
    #21 0x556e92bcb7a5 in LLVMFuzzerTestOneInput /mnt/my_storage/bitcoin/src/test/fuzz/fuzz.cpp:216:5
    #22 0x556e9219318f in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x185218f) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #23 0x556e92192799 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x1851799) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #24 0x556e92194139 in fuzzer::Fuzzer::MutateAndTestOne() (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x1853139) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #25 0x556e92194c95 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x1853c95) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #26 0x556e92181255 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x1840255) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #27 0x556e921ad696 in main (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x186c696) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)
    #28 0x7164cfc2a577 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #29 0x7164cfc2a63a in __libc_start_main csu/../csu/libc-start.c:360:3
    #30 0x556e921757e4 in _start (/mnt/my_storage/bitcoin/build_fuzz/bin/fuzz+0x18347e4) (BuildId: d77c4d5f9dfd38ea06fab463f49341735205e109)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 PersAutoDict-CopyPart- DE: "\005\000"-; base unit: ecb626aff8724f0fdde38a0a6965718f2096d474
artifact_prefix='/tmp/fuzz_artifacts/'; Test unit written to /tmp/fuzz_artifacts/crash-1d19026c1a23f08bfe693fd684a56ce51187c6e5
./build_fuzz/bin/fuzz /tmp/fuzz_corpus/coins_view_overlay -max_total_time=3600 -rss_limit_mb=2560 -artifact_prefix=/tmp/fuzz_artifacts/ >fuzz-16.log 2>&1
```

</details>

The coins view fuzz targets can call `AddCoin`/`AddCoins` and construct `BatchWrite` cursors in ways that violate `CCoinsViewCache` caller contracts. These invalid states can trigger `BatchWrite` `std::logic_error` and can desync dirty-entry accounting (caught by `Assume(m_dirty_count == 0)` currently).

Make the fuzzer avoid generating invalid states instead of catching and resetting:
* Derive `AddCoin`’s `possible_overwrite` from `PeekCoin`, so `possible_overwrite=false` is only used when the outpoint is absent - similarly to https://github.com/bitcoin/bitcoin/blob/67c0d1798e6147f48d4bafc2c9e5ff30f2a62340/src/test/fuzz/coinscache_sim.cpp#L312-L317 
- Only use `AddCoins(check=false)` when we have confirmed the txid has no unspent outputs; otherwise fall back to `check=true` so `AddCoins` determines overwrites via the view.
- When constructing a `CoinsViewCacheCursor`, avoid setting `FRESH` when the parent already has an unspent coin, and ensure `FRESH` implies `DIRTY`.

### Fuzzing
The original error could be reproduced in ~10 minutes using `coins_view_overlay`. I ran the `coins_view`, `coins_view_db`, `coins_view_overlay`, and `coinscache_sim` fuzzers for this PR overnight and they didn't fail anymore.

### CODE REVIEW

File: src/util/overflow.h [hunk 1]
```diff
@@ -31,6 +32,13 @@ template <class T>
     return i + j;
 }
 
+template <std::unsigned_integral T, std::unsigned_integral U>
+[[nodiscard]] constexpr T CheckedSub(const T i, const U j) noexcept
+{
+    Assume(i >= T{j});
```
Comment (maflcko) [inline src/util/overflow.h]: not sure we want subtraction return a different layout than addition (one returns option, the other does not). Same for left-shift. See also https://doc.rust-lang.org/std/primitive.u64.html#method.checked_sub

Comment (l0rinc) [reply src/util/overflow.h]: How would we use that in prod, though? The current calls are not critical, and in production we would not want to crash.

Comment (maflcko) [reply src/util/overflow.h]: Not sure. Maybe put the `Assume` in the source code directly? An alternative could be to come up with a different name, so that similarly named functions are not behaving completely different.

File: src/test/fuzz/coins_view.cpp [hunk 2]
```diff
@@ -280,19 +280,14 @@ void TestCoinsView(FuzzedDataProvider& fuzzed_data_provider, CCoinsViewCache& co
...
-                try {
-                    AddCoins(coins_view_cache, transaction, height, possible_overwrite);
-                    expected_code_path = true;
-                } catch (const std::logic_error& e) {
-                    if (e.what() == std::string{"Attempted to overwrite an unspent coin (when possible_overwrite is false)"}) {
-                        assert(!possible_overwrite);
-                        expected_code_path = true;
+                const bool check_for_overwrite{transaction.IsCoinBase() || fuzzed_data_provider.ConsumeBool() || [&] {
+                    for (uint32_t i{0}; i < transaction.vout.size(); ++i) {
+                        if (coins_view_cache.PeekCoin(COutPoint{transaction.GetHash(), i})) return true;
```
Comment (sipa) [inline src/test/fuzz/coins_view.cpp:263]: It's slightly unfortunate that this requires correctness of `PeekCoin` in order for the test to be meaningful; ideally the fuzzing harness itself knows whether it's a potential overwrite. However, since `coinscache_sim` already uses such an approach, this seems fine here.

File: src/test/fuzz/coins_view.cpp [hunk 3]
```diff
@@ -211,26 +198,20 @@ void TestCoinsView(FuzzedDataProvider& fuzzed_data_provider, CCoinsViewCache& co
                         }
                         coins_cache_entry.coin = *opt_coin;
                     }
+                    // Avoid setting FRESH for an outpoint that already exists unspent in the parent view.
+                    bool fresh{fuzzed_data_provider.ConsumeBool() && !coins_view_cache.PeekCoin(random_out_point)};
```
Comment (sipa) [inline src/test/fuzz/coins_view.cpp]: Swap these two conditions so that no fuzz input is consumed when PeekCoin returns false?

File: src/util/overflow.h (hunk 1 above)
Comment (sipa) [reply src/util/overflow.h]: It's simple enough that just an `Assume(x >= y); x -= y;` inline seems fine.

Comment (l0rinc) [reply src/util/overflow.h]: If you mean we don't need the `T{j}` cast, that broke for me on windows:
```
"D:\a\bitcoin\bitcoin\build\ALL_BUILD.vcxproj" (default target) (1) ->
"D:\a\bitcoin\bitcoin\build\src\test\fuzz\fuzz.vcxproj" (default target) (5) ->
"D:\a\bitcoin\bitcoin\build\src\wallet\bitcoin_wallet.vcxproj" (default target) (12) ->
D:\a\bitcoin\bitcoin\src\util\overflow.h(44,5): warning C4804: '<=': unsafe use of type 'bool' in operation [D:\a\bitcoin\bitcoin\build\src\wallet\bitcoin_wallet.vcxproj]
```

Comment (sipa) [reply src/util/overflow.h]: If that's in response to my comment, I meant avoiding `CheckSub` and just having the `Assume()`s at the call site like @maflcko suggested.

Comment (l0rinc) [reply src/util/overflow.h]: I think I can do better than that, lemme' try something...

Comment (l0rinc) [reply src/util/overflow.h]: The result is cleaner than before, thanks for the suggestions, added you both as coauthors.
It's called `TrySub` now and it modifies the first param and returns a `bool` allowing the call sites to `Assume` cleanly. This avoids the previous repetition and brings the assertions to the call-site.

File: src/test/fuzz/coins_view.cpp (hunk 2 above)
Comment (l0rinc) [reply src/test/fuzz/coins_view.cpp:263]: Yes, added https://github.com/bitcoin/bitcoin/blob/67c0d1798e6147f48d4bafc2c9e5ff30f2a62340/src/test/fuzz/coinscache_sim.cpp#L312-L317 to the commit and PR description

File: src/test/fuzz/coins_view.cpp (hunk 3 above)
Comment (l0rinc) [reply src/test/fuzz/coins_view.cpp]: I assumed the fuzzer is less expensive, but it makes sense not to burn bytes on a decision that can't matter.
Switched in the other cases, too.

File: src/util/overflow.h [hunk 4]
```diff
@@ -31,6 +31,14 @@ template <class T>
     return i + j;
 }
 
+template <std::unsigned_integral T, std::unsigned_integral U>
+[[nodiscard]] constexpr bool TrySub(T& i, const U j) noexcept
```
Comment (sipa) [inline src/util/overflow.h:35]: Very nitty, but:

* I think the name is slightly misleading, as there is no reason why subtracting would ever fail on an unsigned type, so it is not clear what is being "tried". The name should suggest that it avoids wraparound.
* It's unfortunate that this has a runtime impact even outside fuzzing. It's obviously fine within the context of this PR (nothing in it is *that* performance critical), but in that context just `Assume(x >= y); x -= y;` is fine too. If we're introducing this as a new generic utility function that's usable anywhere, I think `bool ret = i >= T{j}; i -= T{j}; return ret;` is nicer, because in contexts where the return value is ignored, it is exactly equivalent to just a subtraction, and may be optimized to it.

**Review by sipa — COMMENTED** [review]
ACK 3281824ecfa72c4f69ab69c94003b7f5a82c7265. Ran the 4 relevant fuzz tests for ~1 CPU day each. Will run more overnight.

**Comment by achow101** [comment]
ACK 3281824ecfa72c4f69ab69c94003b7f5a82c7265

File: src/util/overflow.h (hunk 4 above)
Comment (l0rinc) [reply src/util/overflow.h:35]: > no reason why subtracting would ever fail on an unsigned type

`TrySub` is meant as "try to subtract without wraparound": if `i < j`, it leaves `i` unchanged (hence the `Try` prefix) and returns `false`, so callers can act.

> It's unfortunate that this has a runtime impact even outside fuzzing

> I think bool ret = i >= T{j}; i -= T{j}; return ret; is nicer, because in contexts where the return value is ignored, it is exactly equivalent to just a subtraction

Do we want to be exactly equivalent though?
The current cheap branching prevents the accounting counters from wrapping, so even if accounting is wrong elsewhere, the values stay closer to what we expect.

---

I have tried a few variants to see the effect of the change (plain subtraction vs return + internal `Assume` vs mutating `TrySub` + caller `Assume` with `[[unlikely]]`), see https://godbolt.org/z/nf9nT9Mjj
<details><summary>Details</summary>

Both compilers emit the same single subtract (plus the bool zero-extend in the bool case).
For example, `GCC`:

```asm
sub_return_size:
    sub     QWORD PTR [rdi], rsi
    ret
```

and for `bool`:

```asm
sub_return_bool:
    movzx   esi, sil
    sub     QWORD PTR [rdi], rsi
    ret
```

So return + internal `Assume` has zero codegen cost in non-abort builds, and adding `[[unlikely]]` doesn't seem to change anything there either.

----

Result 2: Only the mutating `TrySub` variant changes semantics (avoids wrap), and it necessarily adds a branch. `[[unlikely]]` didn't change codegen here either.
GCC (`size_t` case):

```asm
sub_trysub_size:
    mov     rax, QWORD PTR [rdi]
    cmp     rax, rsi
    jb      .Lskip
    sub     rax, rsi
    mov     QWORD PTR [rdi], rax
.Lskip:
    ret
```
`clang` emits the same idea, just as `sub` then `jb` then `store`:
```asm
sub_trysub_size:
    mov     rax, qword ptr [rdi]
    sub     rax, rsi
    jb      .Lskip
    mov     qword ptr [rdi], rax
.Lskip:
    ret
```

…and the `sub_trysub_unlikely_*` versions were identical to `sub_trysub_*` for both compilers (so `[[unlikely]]` doesn't seem to buy anything here either; the cold path is already the taken jump).

Note: I have experimented a bit with `__builtin_sub_overflow()`, it does change `GCC` codegen slighly to the same `sub; jb` shape `clang` already emits (removing the explicit `cmp`), but I’m not sure it’s an actual win, so I’ll leave it for a follow-up.

</details>

Comment (sipa) [reply src/util/overflow.h:35]: (this is all very nitty, and no reason to hold up this PR)

> TrySub is meant as "try to subtract without wraparound": if i < j, it leaves i unchanged (hence the Try prefix) and returns false, so callers can act.

Yes, I understand what it does. My point is that this is not clear from the name "TrySub", because it doesn't suggest anything about avoiding wrapping (which is perfectly well-defined behavior on unsigned types).

> Do we want to be exactly equivalent though?

If our assumptions are wrong, I don't think we care about what actually happens to the `m_dirty_count` value, it's going to be meaningless regardless. So I would suggest using whatever is fastest, and I'm guessing that `x -= y;` is faster than `if (x >= y) x -= y;`.

File: src/test/fuzz/coins_view.cpp [hunk 5]
```diff
@@ -215,26 +198,20 @@ void TestCoinsView(FuzzedDataProvider& fuzzed_data_provider, CCoinsViewCache& co
                         }
                         coins_cache_entry.coin = *opt_coin;
                     }
+                    // Avoid setting FRESH for an outpoint that already exists unspent in the parent view.
+                    bool fresh{!coins_view_cache.PeekCoin(random_out_point) && fuzzed_data_provider.ConsumeBool()};
+                    bool dirty{fresh || fuzzed_data_provider.ConsumeBool()};
```
Comment (andrewtoth) [inline src/test/fuzz/coins_view.cpp:203]: nit: I think this is backwards. `fresh` is dependent on `dirty`, not vice versa. See https://github.com/bitcoin/bitcoin/pull/33018/changes/797fcc4eac6cf218deb8ef0a22af0887da29ed71.

I also don't think this change to dirty is relevant to the fix here. We only need to gate fresh on `PeekCoin`. The exception being thrown is not relevant to FRESH-but-not-DIRTY. It's actually reducing coverage here.

**Review by andrewtoth — APPROVED** [review]
ACK 3281824ecfa72c4f69ab69c94003b7f5a82c7265

Fuzzed `coins_view_overlay` overnight with no issues.

File: src/test/fuzz/coins_view.cpp (hunk 5 above)
Comment (l0rinc) [reply src/test/fuzz/coins_view.cpp:203]: I don't have the capacity at the moment to react to this in detail.
Is this important to do it here, or do you think we can tackle it independently in https://github.com/bitcoin/bitcoin/pull/33018?

Comment (andrewtoth) [reply src/test/fuzz/coins_view.cpp:203]: This isn't a blocker. The change here fixes the linked issue.

Comment (l0rinc) [reply src/test/fuzz/coins_view.cpp:203]: I have addressed this in https://github.com/bitcoin/bitcoin/pull/34864
