### PR TITLE
log: don't log total disk read time in ConnectTip bench

### LINKED ISSUE #27635: --with-sanitizers=float-divide-by-zero crash with -debug=bench in Chainstate::ConnectTip
Not sure if this UB causes issues with any compiler. clang is fine, see:

* `-fsanitize=float-divide-by-zero`: Floating point division by zero. This is undefined per the C and C++ standards, but is defined by Clang (and by ISO/IEC/IEEE 60559 / IEEE 754) as producing either an infinity or NaN value, so is not included in `-fsanitize=undefined`.

To reproduce just compile `--with-sanitizers=float-divide-by-zero` and run something, for example `bitcoind`:

```
UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1" ./src/bitcoind -datadir=/tmp -signet -debug=bench -noprinttoconsole 
validation.cpp:2839:5: runtime error: division by zero
```

`float-divide-by-zero` is enabled by OSS-Fuzz, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58887

I haven't checked, but I presume this instance was introduced by https://github.com/bitcoin/bitcoin/pull/24216

### PR DESCRIPTION
**Pull request by Sjors**
The " Load block from disk" log introduced in #24216 incorrectly assumed `num_blocks_total` would be greater than 0. This is not guaranteed until the `ConnectBlock` call right below it.

The total and average metric is not very useful because it does not distinguish between blocks read from disk and those loaded from memory. So rather than fixing the divide by zero issue, we just drop the metric.

Fixes #27635

### CODE REVIEW

File: src/validation.cpp [hunk 1]
```diff
@@ -2834,12 +2833,11 @@ bool Chainstate::ConnectTip(BlockValidationState& state, CBlockIndex* pindexNew,
...
     // Apply the block atomically to the chain state.
     const auto time_2{SteadyClock::now()};
-    time_read_from_disk_total += time_2 - time_1;
     SteadyClock::time_point time_3;
-    LogPrint(BCLog::BENCH, "  - Load block from disk: %.2fms [%.2fs (%.2fms/blk)]\n",
-             Ticks<MillisecondsDouble>(time_2 - time_1),
-             Ticks<SecondsDouble>(time_read_from_disk_total),
-             Ticks<MillisecondsDouble>(time_read_from_disk_total) / num_blocks_total);
+    // When adding aggregate statistics in the future, keep in mind that
+    // num_blocks_total may be zero until the ConnectBlock() call below.
```
Comment (Sjors) [inline src/validation.cpp:2838]: Fwiw I think this warning is useful because many of the bench logs use `/ num_blocks_total` and `ConnectTip` has an `assert(num_blocks_total > 0)` just a few lines down.

Comment (Sjors) [reply src/validation.cpp:2838]: We also call `ConnectTip()` from `TestBlockValidity()` and `VerifyDB()`. Do you know how the counter is supposed to behave in those cases?

Comment (Sjors) [reply src/validation.cpp:2838]: Happy to review such a change, but I barely remember making the original PR and am not very familiar with the bench logging.

**Review by arnonrdp — APPROVED** [review]

**Comment by willcl-ark** [comment]
tACK bc862fad29

I was able to reproduce dropping the commit from this pull (and on master):

```log
2023-05-30T09:27:25Z loadblk thread start
validation.cpp:2839:5: runtime error: division by zero
2023-05-30T09:27:25Z [bench]   - Load block from disk: 0.06ms [0.00s (infms/blk)]
2023-05-30T09:27:25Z [bench]   - Connect total: 0.36ms [0.00s (0.36ms/blk)]
2023-05-30T09:27:25Z [bench]   - Flush: 0.03ms [0.00s (0.03ms/blk)]
2023-05-30T09:27:25Z [bench]   - Writing chainstate: 0.02ms [0.00s (0.02ms/blk)]
```

and after this pull:

```log
2023-05-30T09:30:30Z loadblk thread start
2023-05-30T09:30:30Z [bench]   - Load block from disk: 0.06ms
2023-05-30T09:30:30Z [bench]   - Connect total: 0.09ms [0.00s (0.09ms/blk)]
2023-05-30T09:30:30Z [bench]   - Flush: 0.03ms [0.00s (0.03ms/blk)]
2023-05-30T09:30:30Z [bench]   - Writing chainstate: 0.02ms [0.00s (0.02ms/blk)]
```

**Review by willcl-ark — APPROVED** [review]
