### PR TITLE
Qt: pass clientmodel changes from walletframe to walletviews

### LINKED ISSUE #18090: gui: Crash if shutdown during processNewTransaction
i.e call `generatetoaddress` and shutdown `bitcoin-qt`:

```bash
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x45)
    frame #0: 0x0000000100268cae bitcoin-qt`WalletView::processNewTransaction(this=0x00000001280ce250, parent=0x00007ffeefbfcf78, start=3, (null)=3) at walletview.cpp:136:61
   133 	void WalletView::processNewTransaction(const QModelIndex& parent, int start, int /*end*/)
   134 	{
   135 	    // Prevent balloon-spam when initial block download is in progress
-> 136 	    if (!walletModel || !clientModel || clientModel->node().isInitialBlockDownload())
   137 	        return;
   138 	
   139 	    TransactionTableModel *ttm = walletModel->getTransactionTableModel();
Target 0: (bitcoin-qt) stopped.
```

```bash
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x45)
  * frame #0: 0x0000000100268c7d bitcoin-qt`WalletView::processNewTransaction(this=0x000000010df82250, parent=0x00007ffeefbfcf78, start=19, (null)=19) at walletview.cpp:139:50
    frame #1: 0x000000010026c134 bitcoin-qt`QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2>, QtPrivate::List<QModelIndex const&, int, int>, void, void (WalletView::*)(QModelIndex const&, int, int)>::call(f=f0 8b 26 00 01 00 00 00 00 00 00 00 00 00 00 00, o=0x000000010df82250, arg=0x00007ffeefbfcfb0)(QModelIndex const&, int, int), WalletView*, void**) at qobjectdefs_impl.h:152:13
    frame #2: 0x000000010026c006 bitcoin-qt`void QtPrivate::FunctionPointer<void (WalletView::*)(QModelIndex const&, int, int)>::call<QtPrivate::List<QModelIndex const&, int, int>, void>(f=f0 8b 26 00 01 00 00 00 00 00 00 00 00 00 00 00, o=0x000000010df82250, arg=0x00007ffeefbfcfb0)(QModelIndex const&, int, int), WalletView*, void**) at qobjectdefs_impl.h:185:13
    frame #3: 0x000000010026bec4 bitcoin-qt`QtPrivate::QSlotObject<void (WalletView::*)(QModelIndex const&, int, int), QtPrivate::List<QModelIndex const&, int, int>, void>::impl(which=1, this_=0x0000000127e5f2a0, r=0x000000010df82250, a=0x00007ffeefbfcfb0, ret=0x0000000000000000) at qobjectdefs_impl.h:414:17
    frame #4: 0x0000000104e326e2 QtCore`___lldb_unnamed_symbol2576$$QtCore + 1138
    frame #5: 0x0000000104db29c0 QtCore`QAbstractItemModel::endInsertRows() + 272
    frame #6: 0x00000001001e375f bitcoin-qt`TransactionTablePriv::updateWallet(this=0x000000012af59850, wallet=0x000000012af15d50, hash=0x00007ffeefbfd498, status=0, showTransaction=true) at transactiontablemodel.cpp:147:29
    frame #7: 0x00000001001e2a7b bitcoin-qt`TransactionTableModel::updateTransaction(this=0x000000012af59710, hash=0x000000010560c830, status=0, showTransaction=true) at transactiontablemodel.cpp:251:11
    frame #8: 0x000000010027dcdd bitcoin-qt`TransactionTableModel::qt_static_metacall(_o=0x000000012af59710, _c=InvokeMetaMethod, _id=0, _a=0x00000001056202b0) at moc_transactiontablemodel.cpp:91:21
    frame #9: 0x0000000104e2addd QtCore`QObject::event(QEvent*) + 957
    frame #10: 0x0000000104082bcd QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    frame #11: 0x0000000104084005 QtWidgets`QApplication::notify(QObject*, QEvent*) + 581
    frame #12: 0x0000000104e00994 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #13: 0x0000000104e01a43 QtCore`QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 691
```

### PR DESCRIPTION
**Pull request by jonasschnelli**
Fixes #18090 

We currently don't pass `clientmodel` changes from the `walletframe` to the `walletviews` leading to possible invalid access during shutdown because all walletviews miss the nullifying of the clientmodel.

TODO: needs investigation if this is should be backported.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
This only affects tests (`generateto*`), so doesn't need backport?

**Comment by jonasschnelli** [comment]
Very likely only `generateto*` calls that are affected. Though there could be other calls that have this shutdown race.

File: src/qt/walletframe.cpp [hunk 1]
```diff
@@ -37,6 +37,10 @@ WalletFrame::~WalletFrame()
 void WalletFrame::setClientModel(ClientModel *_clientModel)
 {
     this->clientModel = _clientModel;
+
+    QMap<WalletModel*, WalletView*>::const_iterator i;
+    for (i = mapWalletViews.constBegin(); i != mapWalletViews.constEnd(); ++i)
```
Comment (promag) [inline src/qt/walletframe.cpp]: nit, `auto i =`, also add `{`.

**Review by promag — COMMENTED** [review]
Code review ACK ce2e941f6b4216d40fcafd5ad942082318747469.

Follow up, also because lately I've been addressing removing circular dependencies, I think we should make clear the lifecycle of these objects. For instance, considering the following order of instantiation `ClientModel` -> `BitcoinGUI` -> `WalletFrame` -> `WalletModel` -> `WalletView` then we could drop these `setClient` and `setModel` and receive the necessary objects in the constructors. Then destruction order should be reverse.

**Comment by emilengler** [comment]
tACK ce2e941f6b4216d40fcafd5ad942082318747469

Only affected me when contacting through the RPC HTTP Server, not through the Qt console.

File: src/qt/walletframe.cpp (hunk 1 above)
Comment (jonasschnelli) [reply src/qt/walletframe.cpp]: fixed.

**Comment by laanwj** [comment]
Good catch, code review ACK 2af3e16ca917acd85c2d4f709f6d486519d6af0d
