### PR TITLE
Fix Issue #9775 (Check returned value of fopen)

### LINKED ISSUE #9775: Check returned value of fopen()
[util.cpp#L216](https://github.com/bitcoin/bitcoin/blob/master/src/util.cpp#L216) 
if `fopen `failed, a null file pointer could be passed to `FileWriteStr(vMsgsBeforeOpenLog->front(), fileout);`

### PR DESCRIPTION
**Pull request by kirit93**
Making sure file is opened before writing string to file to avoid seg faults in case open() returns a NULL pointer. 

Attempts to fix #9775

### CODE REVIEW

File: src/util.cpp [hunk 1]
```diff
@@ -164,7 +164,7 @@ class CInit
             delete ppmutexOpenSSL[i];
         OPENSSL_free(ppmutexOpenSSL);
     }
-}
+};
```
Comment (laanwj) [inline src/util.cpp]: Adding a ; here is wrong.

Comment (kirit93) [inline src/util.cpp]: I removed the semicolon in the latest commit.

**Comment by MarcoFalke** [comment]
Please also remove the trailing whitespace

**Comment by kirit93** [comment]
Hey I just noticed this issue has been closed. Do we still need this fix?

**Comment by laanwj** [comment]
This issue hasn't been closed, we still need it. There were just some comments.

Looks good to me now. Could you squash to one commit? (e.g. follow https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits)
