### PR TITLE
p2p: change `CInv::type` from `int` to `uint32_t`, fix UBSan warning

### LINKED ISSUE #19678: UBSan warning when fuzzing with -fsanitize=integer
When fuzzing the `process_messages` harness with `-fsanitize=integer` and taking care to use the ubsan suppressions file, I get the following crasher:

```
INFO: Seed: 2176449341
INFO: Loaded 1 modules   (204269 inline 8-bit counters): 204269 [0x555d1700aeb0, 0x555d1703cc9d), 
INFO: Loaded 1 PC tables (204269 PCs): 204269 [0x555d1703cca0,0x555d1735ab70), 
INFO:     7752 files found in /root/qa-assets/fuzz_seed_corpus/process_messages
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
INFO: seed corpus: files: 7752 min: 1b max: 3984182b total: 71282676b rss: 81Mb
protocol.h:420:42: runtime error: implicit conversion from type 'int' of value -168430091 (32-bit, signed) to type 'unsigned int' changed the value to 4126537205 (32-bit, unsigned)
    #0 0x555d1630b5ff in CInv::IsGenTxMsg() const /root/bitcoin/src/./protocol.h:420:42
    #1 0x555d1630b5ff in ProcessMessage(CNode&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CDataStream&, std::chrono::duration<long, std::ratio<1l, 1000000l> >, CChainParams const&, ChainstateManager&, CTxMemPool&, CConnman&, BanMan*, std::atomic<bool> const&) /root/bitcoin/src/net_processing.cpp:3696:25
    #2 0x555d1632d971 in PeerLogicValidation::ProcessMessages(CNode*, std::atomic<bool>&) /root/bitcoin/src/net_processing.cpp:3842:9
    #3 0x555d1632fec5 in non-virtual thunk to PeerLogicValidation::ProcessMessages(CNode*, std::atomic<bool>&) /root/bitcoin/src/net_processing.cpp
    #4 0x555d162a1f3e in ConnmanTestMsg::ProcessMessagesOnce(CNode&) /root/bitcoin/src/./test/util/net.h:26:56
    #5 0x555d162a1f3e in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) /root/bitcoin/src/test/fuzz/process_messages.cpp:74:21
    #6 0x555d16954bd6 in LLVMFuzzerTestOneInput /root/bitcoin/src/test/fuzz/fuzz.cpp:45:5
    #7 0x555d16231751 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/root/bitcoin/src/test/fuzz/process_messages+0x649751)
    #8 0x555d16230e95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/root/bitcoin/src/test/fuzz/process_messages+0x648e95)
    #9 0x555d162337b7 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/root/bitcoin/src/test/fuzz/process_messages+0x64b7b7)
    #10 0x555d16233b19 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/root/bitcoin/src/test/fuzz/process_messages+0x64bb19)
    #11 0x555d162227ee in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/root/bitcoin/src/test/fuzz/process_messages+0x63a7ee)
    #12 0x555d1624b632 in main (/root/bitcoin/src/test/fuzz/process_messages+0x663632)
    #13 0x7f247597fb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #14 0x555d161f7569 in _start (/root/bitcoin/src/test/fuzz/process_messages+0x60f569)

SUMMARY: UndefinedBehaviorSanitizer: implicit-integer-sign-change protocol.h:420:42 in 
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x6e,0x6f,0x74,0x66,0x6f,0x75,0x6e,0x64,0x0,0x1,0x7f,0x99,0x2,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xa5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0xf5,0x99,0x99,0x99,0x99,0x99,0x99,0x99,0x99,0x99,0x99,0x99,0x99,0xdc,0x1,0x7c,0x0,0x0,0x0,0x0,0x0,0x0,0xc0,
notfound\x00\x01\x7f\x99\x02\x00\x00\x00\x00\x00\x00\x00\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xa5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\xf5\x99\x99\x99\x99\x99\x99\x99\x99\x99\x99\x99\x99\xdc\x01|\x00\x00\x00\x00\x00\x00\xc0
artifact_prefix='./'; Test unit written to ./crash-6d18289c14a3cab8896d942d6c4021b2b6895a1e
Base64: bm90Zm91bmQAAX+ZAgAAAAAAAAClpaWlpaWlpaWlpaWlpaWlpaX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1mZmZmZmZmZmZmZmZ3AF8AAAAAAAAwA==
```

The problem occurs because `type` is an `int` and gets converted in the comparison. I feel like `type` should be `uint32_t` but felt I'd make an issue to see if this should be a suppression instead :).
https://github.com/bitcoin/bitcoin/blob/a78742830aa35bf57bcb0a4730977a1e5a1876bc/src/protocol.h#L420

### PR DESCRIPTION
**Pull request by jonatack**
Fixes UBSan implicit-integer-sign-change issue per https://github.com/bitcoin/bitcoin/pull/19610#issuecomment-680686460.

Credit to Crypt-iQ for finding and reporting the issue and to vasild for the original review suggestion in https://github.com/bitcoin/bitcoin/pull/19590#pullrequestreview-455788826.

Closes #19678.

### CODE REVIEW

File: src/protocol.h [hunk 1]
```diff
@@ -425,7 +425,7 @@ class CInv
     // Combined-message helper methods
     bool IsGenTxMsg()     const { return type == MSG_TX || type == MSG_WTX || type == MSG_WITNESS_TX; }
 
-    int type;
+    uint32_t type;
```
Comment (laanwj) [inline src/protocol.h:428]: ACK on using a sized type here.
However, changing from signed to unsigned is, in principle, a P2P protocol change.
This needs to be carefully reviewed for potential unexpected by-effects.

**Comment by MarcoFalke** [comment]
According to https://en.bitcoin.it/wiki/Protocol_documentation#Inventory_Vectors (section written in 2010 by "MagicalTux") this is unsigned. Though, our python tests also treat this as signed. https://btcinformation.org/en/developer-reference#inv doesn't say anything about signedness.

Would be good to at least update the python test framework and also add a p2p test.

**Comment by jonatack** [comment]
> Would be good to at least update the python test framework and also add a p2p test.

Updated the python test framework and added a test. Was unsure what kind of test to add; this one tests the framework change.

**Comment by jonatack** [comment]
> Would be good to at least update the python test framework and also add a p2p test.

Updated the python test framework and added a test for the framework change.

File: test/functional/p2p_invalid_messages.py [hunk 2]
```diff
@@ -125,6 +128,16 @@ def test_msgtype(self):
             conn.sync_with_ping(timeout=1)
         self.nodes[0].disconnect_p2ps()
 
+    def test_inv_msg_with_negative_type(self):
+        self.log.info("Test inv with negative type raises argument out of range error")
+        invalid_inv = msg_inv([CInv(t=-1, h=1)])  # inv type must be an unsigned integer
+        try:
+            self.nodes[0].add_p2p_connection(P2PInterface()).send_message(invalid_inv)
+        except struct.error as e:
```
Comment (MarcoFalke) [inline test/functional/p2p_invalid_messages.py:136]: We generally don't test the test framework. Sending an uint32_t{-1} and observing the node doesn't crash with sanitizers enabled should be a sufficient smoke test. Maybe add an assert_debug_log to observe how the inv will be formatted.

```
            LogPrint(BCLog::NET, "got inv: %s  %s peer=%d\n", inv.ToString(), fAlreadyHave ? "have" : "new", pfrom.GetId());

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:136]: Thanks for the tip. The temporary framework test helped me see an issue with the framework update, will drop it and try your suggestion.

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:137]: Thanks Marco. Trying some stuff to see how the CI reacts to it.

File: test/functional/p2p_invalid_messages.py [hunk 3]
```diff
@@ -125,6 +129,27 @@ def test_msgtype(self):
...
+        try:
+            self.nodes[0].add_p2p_connection(P2PInterface()).build_message(inv_with_signed_type)
+        except struct.error as e:
+            assert_equal("argument out of range", str(e))
+        else:
+            raise AssertionError("No exception raised")
+
+        # Repeat, passing signed integer CInv type format to override default.
+        LE_signed_int = "<i"  # Python format chars for little-endian signed int
+        inv_with_signed_type = msg_inv([CInv(t=-MSG_TX, h=1, f=LE_signed_int)])
```
Comment (MarcoFalke) [inline test/functional/p2p_invalid_messages.py:144]:
```suggestion
        inv_with_signed_type = msg_inv([CInv(t=0xffffffff, h=1)])
```

Serialized -1 as signed integer is identical to 0xffffffff serialized as unsigned integer, so might as well use the latter

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:144]: That was breaking this method in messages.py::CInv with KeyError: 4294967295
```python
    def __repr__(self):
        return "CInv(type=%s hash=%064x)" \
            % (self.typemap[abs(self.type)], self.hash)
```

**Comment by practicalswift** [comment]
Concept ACK

Thanks for fixing UBSan fuzzing finds!

File: test/functional/p2p_invalid_messages.py (hunk 3 above)
Comment (MarcoFalke) [reply test/functional/p2p_invalid_messages.py:144]: Even when adding type `0xffffffff: "Error"`?

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:144]: Travis seem happy. I have the following minor cleanups in mind but will wait for feedback before pushing.
```diff
test/functional/p2p_invalid_messages.py
@@ -142,12 +142,12 @@ class InvalidMessagesTest(BitcoinTestFramework):
         LE_signed_int = "<i"  # Python format chars for little-endian signed int
         inv_with_signed_type = msg_inv([CInv(t=-MSG_TX, h=1, f=LE_signed_int)])
-        with self.nodes[0].assert_debug_log(["got inv: 0xffffffff 00000"]):
+        with self.nodes[0].assert_debug_log(["got inv: 0xffffffff "]):
             self.nodes[0].add_p2p_connection(P2PInterface()).send_message(inv_with_signed_type)
 
         # Sanity check with valid unsigned inv type and same format override.
         inv_with_unsigned_type = msg_inv([CInv(t=MSG_WTX, h=1, f=LE_signed_int)])
-        with self.nodes[0].assert_debug_log(["got inv: wtx 0000"]):
+        with self.nodes[0].assert_debug_log(["got inv: wtx "]):

test/functional/test_framework/messages.py
@@ -251,7 +251,7 @@ class CInv:
     def __init__(self, t=0, h=0, f="<I"):
         self.type = t
         self.hash = h
-        self.inv_type_format = f  # default format is unsigned int
+        self.inv_type_format = f  # default is little endian unsigned int
```

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:144]: > Even when adding type `0xffffffff: "Error"`?

Didn't think of it :D thanks, trying.

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:144]: Great--that simplifies things.

Comment (jonatack) [reply test/functional/p2p_invalid_messages.py]: Done, simplified, good idea. LMK if we should drop the first test.

**Comment by practicalswift** [comment]
@jonasnick Just to confirm: if the test changes we're dropped in this change set (keeping only the changes to `src/protocol.{cpp,h}`) then all functional tests would still pass, right?

File: test/functional/p2p_invalid_messages.py [hunk 4]
```diff
@@ -125,6 +128,22 @@ def test_msgtype(self):
             conn.sync_with_ping(timeout=1)
         self.nodes[0].disconnect_p2ps()
 
+    def test_inv_msg_with_signed_integer_type(self):
+        self.log.info("Test inv message with MSG_TX type as signed int raises out of range error")
+        inv_with_signed_type = msg_inv([CInv(t=-MSG_TX, h=1)])
+        try:
+            self.nodes[0].add_p2p_connection(P2PInterface()).build_message(inv_with_signed_type)
+        except struct.error as e:
```
Comment (MarcoFalke) [inline test/functional/p2p_invalid_messages.py:136]: imo could drop the test framework self-test

**Comment by jonatack** [comment]
> @jonasnick Just to confirm: if the test changes we're dropped in this change set (keeping only the changes to `src/protocol.{cpp,h}`) then all functional tests would still pass, right?

Right. I pushed the changes to `src/protocol.{h/cpp}` several times in other PR changesets (#19610, #19611) before dropping them, and the CI passes.

File: test/functional/p2p_invalid_messages.py (hunk 4 above)
Comment (jonatack) [reply test/functional/p2p_invalid_messages.py:136]: Done, but I think both of these tests only tested the framework change anyway.

**Comment by jnewbery** [comment]
> According to https://en.bitcoin.it/wiki/Protocol_documentation#Inventory_Vectors (section written in 2010 by "MagicalTux") this is unsigned. Though, our python tests also treat this as signed. https://btcinformation.org/en/developer-reference#inv doesn't say anything about signedness.

btcinformation.org does show this as uint32_t: https://btcinformation.org/en/developer-reference#data-messages. That was added by @harding to the bitcoin.org developer docs here: https://github.com/bitcoin-dot-org/Bitcoin.org/commit/1634212dd5550bb9b610341668b4b7b5fa3690a5#diff-693f5b3e9d88b97c899694c8d1656cbbR110

Note that even though comparing an int to a uint32_t causes a UBSan warning, it's not actually undefined behaviour: https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#:~:text=%2Dfsanitize%3Dimplicit%2Dinteger%2D,the%20new%20value%20is%20negative. However, I think it's still worth changing this, so that we're always comparing / xor'ing a uint32_t with a uint32_t, so concept ACK.

**Comment by jonatack** [comment]
Great links @jnewbery, thanks.

> Note that even though comparing an int to a uint32_t causes a UBSan warning, it's not actually undefined behaviour: [clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#:~:text=%2Dfsanitize%3Dimplicit%2Dinteger%2D,the%20new%20value%20is%20negative](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#:~:text=%2Dfsanitize%3Dimplicit%2Dinteger%2D,the%20new%20value%20is%20negative).

"-fsanitize=implicit-integer-sign-change: Implicit conversion between integer types, if that changes the sign of the value...issues caught by this sanitizer are not undefined behavior, but are often unintentional."

File: test/functional/test_framework/messages.py [hunk 5]
```diff
@@ -244,27 +244,28 @@ class CInv:
...
         r = b""
-        r += struct.pack("<i", self.type)
+        r += struct.pack("<I", self.type)
         r += ser_uint256(self.hash)
         return r
 
     def __repr__(self):
         return "CInv(type=%s hash=%064x)" \
-            % (self.typemap[self.type], self.hash)
+            % (self.typemap[abs(self.type)], self.hash)
```
Comment (laanwj) [inline test/functional/test_framework/messages.py:268]: I don't think this `abs(…)` is correct. There should be no reason to take an absolute value here, convert, say, `-1` to `1`.

File: test/functional/test_framework/messages.py [hunk 6]
```diff
@@ -244,27 +244,28 @@ class CInv:
         MSG_TX | MSG_WITNESS_FLAG: "WitnessTx",
         MSG_BLOCK | MSG_WITNESS_FLAG: "WitnessBlock",
         MSG_FILTERED_BLOCK: "filtered Block",
-        4: "CompactBlock",
-        5: "WTX",
+        MSG_CMPCT_BLOCK: "CompactBlock",
+        MSG_WTX: "WTX",
+        0xffffffff: "Error",
```
Comment (laanwj) [inline test/functional/test_framework/messages.py:249]: I'd prefer to report anything that is unkonwn as "Error" instead of specifically adding `0xffffffff`  here.

File: test/functional/test_framework/messages.py (hunk 5 above)
Comment (jonatack) [reply test/functional/test_framework/messages.py:268]: It was to not allow shallow errors of type `KeyError` to hide deeper issues.

File: test/functional/test_framework/messages.py (hunk 6 above)
Comment (jonatack) [reply test/functional/test_framework/messages.py:249]: This was only needed for the test. I tried a few [different tests](https://github.com/bitcoin/bitcoin/commit/6c0f4aefe373bb89188e91464326dabf0f9f3397]. [This one](https://github.com/bitcoin/bitcoin/commit/1ab179b78d63c7e96af7dbad6caf3efb82afa01a) doesn't require adding entries to `typemap`. I don't think any of the tests cover the code change, only the test framework change.

Comment (jonatack) [reply test/functional/test_framework/messages.py:249]: I'm not sure what to do here. This was only needed for the test. I tried a few [different tests](https://github.com/bitcoin/bitcoin/commit/6c0f4aefe373bb89188e91464326dabf0f9f3397); the first one doesn't require adding entries to `typemap`. I don't think any of the tests cover the CInv::type code change, only the test framework change.

File: test/functional/test_framework/messages.py (hunk 5 above)
Comment (jonatack) [reply test/functional/test_framework/messages.py]: Dropped this line.

File: test/functional/test_framework/messages.py (hunk 6 above)
Comment (jonatack) [reply test/functional/test_framework/messages.py]: Dropped this line.

**Comment by jonatack** [comment]
Thanks everyone for your feedback. I wrote a [few tests](https://github.com/bitcoin/bitcoin/commit/6c0f4aefe373bb89188e91464326dabf0f9f3397) but they all covered the change to the CInv class in the test framework, not the CInv change in `protocol.{h,cpp}`, so I've dropped them in the latest push.

**Comment by laanwj** [comment]
Thanks for addressing the comments, the code changes look good to me now.

**Review by vasild — APPROVED** [review]
ACK 7984c39be

All the values we ever assign to `CInv::type` are non-negative within the reach of a signed 32 bit integer. `GetDataMsg` is `uint32_t` and in some places we `|=` a variable of type `uint32_t` into `CInv::type`:

https://github.com/bitcoin/bitcoin/blob/bab4cce1b0eedc1a51692aaf83ba54dd0a9d17e6/src/net_processing.cpp#L2717

So it makes sense to have `CInv::type` as `uint32_t`.

Actually serializing a signed integer in the way we do it is not portable, it just works because all platforms use [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement), but that's not guaranteed.

**Comment by laanwj** [comment]
> All the values we ever assign to CInv::type are non-negative within the reach of a signed 32 bit integer. GetDataMsg is uint32_t and in some places we |= a variable of type uint32_t into CInv::type

Bitwise arithmetic should definitely use unsigned integers, good point.

**Comment by laanwj** [comment]
ACK 407175e0c2bc797599ebd9c0a1f2ec89ad7af136
