### PR TITLE
Test whether created sockets are select()able

### LINKED ISSUE #6411: connection limit calculation for select() is overly ambitious with -txindex
Running an unmodified 0.10.2 node I got this fail, seeming to indicate that it was trying to add an fd which was higher than the max for select. Node has -txindex and usually has a ton of connections (it has the max fd count set higher than default st. its maxconnections is limited by its select limits, not by max fd count limits).

Core was generated by `/home/matt/bitcoind'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f327f0c0528 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f327f0c0528 in raise () from /usr/lib/libc.so.6
#1  0x00007f327f0c193a in abort () from /usr/lib/libc.so.6
#2  0x00007f327f0febb2 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f327f184ff7 in __fortify_fail () from /usr/lib/libc.so.6
#4  0x00007f327f1831c0 in __chk_fail () from /usr/lib/libc.so.6
#5  0x00007f327f184f67 in __fdelt_warn () from /usr/lib/libc.so.6
#6  0x00007f328199fa5e in ThreadSocketHandler () at net.cpp:820
#7  0x00007f32819a7c11 in TraceThread<void (*)()> (name=0x7f3281b857a1 "net", func=0x7f328199eff0 <ThreadSocketHandler()>) at util.h:214
#8  0x00007f3280ddfa85 in ?? () from /usr/lib/libboost_thread.so.1.58.0
#9  0x00007f327f436354 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f327f174bfd in clone () from /usr/lib/libc.so.6
(gdb)

### PR DESCRIPTION
**Pull request by sipa**
This provides a belt-and-suspends check against file descriptor overflowing, to fix #6411.

### CODE REVIEW

File: src/net.cpp [hunk 1]
```diff
@@ -385,6 +385,12 @@ CNode* ConnectNode(CAddress addrConnect, const char *pszDest)
     if (pszDest ? ConnectSocketByName(addrConnect, hSocket, pszDest, Params().GetDefaultPort(), nConnectTimeout, &proxyConnectionFailed) :
                   ConnectSocket(addrConnect, hSocket, nConnectTimeout, &proxyConnectionFailed))
     {
+        if (!IsSelectableSocket(hSocket)) {
+            LogPrintf("Cannot create connection: non-selectable socket created (file descriptor limit exceeded?)\n");
```
Comment (luke-jr) [inline src/net.cpp]: Suggest removing " (file descriptor limit exceeded?)" since this description is inaccurate and likely to confuse someone trying to debug it.

Comment (sipa) [inline src/net.cpp]: "non-selectable socket created" is completely unhelpful for indicating the reason or helping debug it. So I prefer to explain it a bit at least. Do you have a better suggestion?

**Comment by ajweiss** [comment]
select() is also used in netbase, seems it would make sense to check there.  Also, if connect() were to return an EINVAL for any reason, that could trigger this in netbase.  Have you considered just printing the fd value?  For language I'd go simple "invalid file descriptor %ud from netbase on connect".

File: src/net.cpp (hunk 1 above)
Comment (laanwj) [inline src/net.cpp]: I'd say the file descriptor limit exceeded is the part of the message that matters most.

**Comment by laanwj** [comment]
utACK

File: src/net.cpp (hunk 1 above)
Comment (luke-jr) [inline src/net.cpp]: " (socket cannot be included in fdset)" perhaps? The actual fd limit very much has *not* been exceeded in most situations you'd get this error...

File: src/compat.h [hunk 2]
```diff
@@ -92,4 +92,12 @@ typedef u_int SOCKET;
 size_t strnlen( const char *start, size_t max_len);
 #endif // HAVE_DECL_STRNLEN
 
+bool static inline IsSelectableSocket(SOCKET s) {
+#ifdef WIN32
+    return true;
```
Comment (luke-jr) [inline src/compat.h]: return s != INVALID_SOCKET; ?

File: src/net.cpp (hunk 1 above)
Comment (laanwj) [inline src/net.cpp]: Well OK @luke-jr is right in that this is not "the" file descriptor limit, just the **select** file descriptor limit. Let's just name the beast as it is:
`Cannot create connection: non-selectable socket created (>=FD_SETSIZE)`

File: src/compat.h (hunk 2 above)
Comment (laanwj) [inline src/compat.h]: Don' think it should double as "is this an error return value"

**Comment by sipa** [comment]
Updated. The test is now done also in netbase (causing simple failure, as netbase does not usually print error messages), and when creating a listen socket.

**Comment by laanwj** [comment]
Needs backport to 0.11 and 0.10

**Comment by sipa** [comment]
Se my branches nonselectsocket-0.11 and nonselectsocket-0.10.

File: src/net.cpp [hunk 3]
```diff
@@ -1597,6 +1608,13 @@ bool BindListenPort(const CService &addrBind, string& strError, bool fWhiteliste
         LogPrintf("%s\n", strError);
         return false;
     }
+    if (!IsSelectableSocket(hListenSocket))
+    {
+        strError = strprintf("Error: Couldn't create a listenable socket for incoming connections");
```
Comment (laanwj) [inline src/net.cpp]: `strprintf` doesn't work without arguments (and is redundant)

**Comment by sipa** [comment]
@laanwj Done.

**Comment by laanwj** [comment]
This brings up a warning, as SOCKET is defined as unsigned int:
```
compat.h: In function ‘bool IsSelectableSocket(SOCKET)’:
compat.h:99:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
     return (s >= 0 && s < FD_SETSIZE);
```

**Comment by laanwj** [comment]
@sipa are you planning to fix the warning or should we not hold this up on that?

**Comment by laanwj** [comment]
Backported to 0.11 as e8b87c8f78fd66ebeb10ce5dfcf72b0a5e73f120
Warning fixed in 89289d875da108c42ca013f33597eda46cb6eb53 (e8b87c8f78fd66ebeb10ce5dfcf72b0a5e73f120 in 0.11)
