### PR TITLE
test: avoid stack overflow in `FindChallenges` via manual iteration

### LINKED ISSUE #32341: ctest -C Debug fails on vs2022 (miniscript_tests (SEGFAULT))
cmd: `ctest --output-on-failure --stop-on-failure -j $NUMBER_OF_PROCESSORS -C Debug`

The full log and config is in  the comment below: https://github.com/bitcoin/bitcoin/issues/32341#issuecomment-2828857830. Which was motivated by  https://github.com/bitcoin/bitcoin/pull/32339 attempting to use a windows debug build.

### PR DESCRIPTION
**Pull request by l0rinc**
`FindChallenges` explores the `Miniscript` node tree by going deep into the first child's subtree, then the second, and so on - effectively performing a pre-order Traversal (Depth-First Search) recursively, using the call stack which can result in stack overflows on Windows debug builds.

This change replaces the recursive implementation with an iterative version using an explicit stack. The new implementation also performs a pre-order depth-first traversal, though it processes children in right-to-left order (rather than left-to-right) due to the LIFO nature of the stack. Since both versions store results in a `std::set`, which automatically sorts and deduplicates elements, the exact traversal order doesn't affect the final result.

It is an alternative to increasing the Windows stack size, as proposed in #32349, and addresses the issue raised in #32341 by avoiding deep recursion altogether.

The change is done in two commits:
* add a new iterative `FindChallenges` method and rename the old method to `*_recursive` (to simplify the next commit where we remove it), asserting that its result matches the original;
* remove the original recursive implementation.

This approach avoids ignoring the `misc-no-recursion` warning as well.

I tried modifying the new method to store results in a vector instead, but it demonstrated that the deduplication provided by `std::set` was necessary. One example showing the need for deduplication:

Recursive (using set):
```
  (6, 9070746)
  (6, 19532513)
  (6, 3343376967)
```
Iterative (using vector attempt):
```
  (6, 19532513)
  (6, 9070746)
  (6, 3343376967)
  (6, 9070746)  // Duplicate entry
```

The performance of the test is the same as before, with the recursive method.

Fixes https://github.com/bitcoin/bitcoin/issues/32341

### CODE REVIEW

**Comment by hebasto** [comment]
cc @darosior

**Comment by hebasto** [comment]
[Here](https://github.com/hebasto/bitcoin-core-nightly/actions/runs/14667837569/job/41166981753) is a "Windows, Debug" CI job for this branch in https://github.com/hebasto/bitcoin-core-nightly.

**Review by darosior — COMMENTED** [review]
Concept ACK. Should this marked as Fixes https://github.com/bitcoin/bitcoin/issues/32341?

**Comment by l0rinc** [comment]
> miniscript_tests (SEGFAULT)

This was the original failure in debug mode

> [Here](https://github.com/hebasto/bitcoin-core-nightly/actions/runs/14667837569/job/41166981753) is a "Windows, Debug" CI job

While the build is till running, this test passed alerady:
 ```python
 89/140 Test  # 60: miniscript_tests .....................   Passed  126.23 sec
 ```
 
 > Should this marked as Fixes https://github.com/bitcoin/bitcoin/issues/32341?
 
 Added it to the description

File: src/test/miniscript_tests.cpp [hunk 1]
```diff
@@ -347,7 +377,9 @@ struct MiniScriptTest : BasicTestingSetup {
 /** Run random satisfaction tests. */
 void TestSatisfy(const KeyConverter& converter, const std::string& testcase, const NodeRef& node) {
     auto script = node->ToScript(converter);
-    auto challenges = FindChallenges(node); // Find all challenges in the generated miniscript.
+    const auto challenges_recursive{FindChallenges_recursive(node)};
+    const auto challenges{FindChallenges(node)}; // Find all challenges in the generated miniscript.
+    BOOST_CHECK(std::vector{challenges_recursive} == std::vector{challenges});
```
Comment (hodlinator) [inline src/test/miniscript_tests.cpp]: In bd89f7eff0dc6c44c6a0b96883c3816fe0919f95, why not just:
```C++
    BOOST_CHECK(challenges_recursive == challenges);
```
?
https://en.cppreference.com/w/cpp/container/set/operator_cmp claims the complexity is linear with the size.

**Review by hodlinator — APPROVED** [review]
ACK 2e533cf86a42b3416c1164d04089e80ffe622dd6

Prefer this alternative of switching to an iterative algorithm (instead of bumping the stack space #32349).

On master we do a depth-first gathering of challenges, the new stack based version {Edit: ~does breadth-first~ changes the traversal order somewhat}, but result is put in a `std::set` so traversal order does not matter.

**Review by hebasto — APPROVED** [review]
ACK 2e533cf86a42b3416c1164d04089e80ffe622dd6, I have reviewed the code and it looks OK.

If we put refactoring aside, the changes in this PR could be much smaller and easier to review with `git diff --ignore-all-space`:
```diff
--- a/src/test/miniscript_tests.cpp
+++ b/src/test/miniscript_tests.cpp
@@ -297,9 +297,13 @@ using miniscript::operator""_mst;
 using Node = miniscript::Node<CPubKey>;
 
 /** Compute all challenges (pubkeys, hashes, timelocks) that occur in a given Miniscript. */
-// NOLINTNEXTLINE(misc-no-recursion)
-std::set<Challenge> FindChallenges(const NodeRef& ref) {
+std::set<Challenge> FindChallenges(const NodeRef& root) {
     std::set<Challenge> chal;
+    std::vector<const Node*> stack;
+    stack.push_back(root.get());
+    while (!stack.empty()) {
+        const Node* ref{stack.back()};
+        stack.pop_back();
         for (const auto& key : ref->keys) {
             chal.emplace(ChallengeType::PK, ChallengeNumber(key));
         }
@@ -317,8 +321,8 @@ std::set<Challenge> FindChallenges(const NodeRef& ref) {
             chal.emplace(ChallengeType::HASH160, ChallengeNumber(ref->data));
         }
         for (const auto& sub : ref->subs) {
-        auto sub_chal = FindChallenges(sub);
-        chal.insert(sub_chal.begin(), sub_chal.end());
+            stack.push_back(sub.get());
+        }
     }
     return chal;
 }
```

**Comment by l0rinc** [comment]
> On master we do a depth-first gathering of challenges, the new stack based version does breadth-first, but result is put in a std::set so traversal order does not matter.

I've reworded the commit message to make this clearer.
The original method is pre-order depth-first, where the children are processed in the same order they appear (Left-to-right). The new method is still pre-order depth-first, but children are inserted in the reverse order (Right-to-left). But as you mention, it's in a set, so the iteration order will still be the same.

> the changes in this PR could be much smaller and easier to review

You mean to avoid the use of the switch statement? If you feel strongly about it I can revert that, but the code seemed easy to review in either way.

File: src/test/miniscript_tests.cpp (hunk 1 above)
Comment (l0rinc) [reply src/test/miniscript_tests.cpp]: This helped me debug the mentioned vector conversion, but it's not important anymore, so your suggestion also works.

**Comment by hebasto** [comment]
> > the changes in this PR could be much smaller and easier to review
> 
> 
> 
> You mean to avoid the use of the switch statement? If you feel strongly about it I can revert that, but the code seemed easy to review in either way.

I mean to squash all changes into a single commit with functionality changes only. Refactoring changes, such as introducing the `switch` statement, could be added in a separate commit.

But not a strong opinion, though.

**Comment by l0rinc** [comment]
Since CI is checking every commit, I have split out the introduction of the new algorithm, demonstrating that it results in the same output as the original.
I'm not sure how to do that in a single commit - unless I add it as a test, which didn't seem necessary here.

**Comment by hebasto** [comment]
@theuni 

Due to your https://github.com/bitcoin/bitcoin/pull/31367#issuecomment-2524210640, you might b e interested in reviewing this PR.

**Review by sipa — COMMENTED** [review]
utACK 7e8ef959d0637ca5543ed33d3919937e0d053e70

File: src/test/miniscript_tests.cpp [hunk 2]
```diff
@@ -347,7 +348,7 @@ struct MiniScriptTest : BasicTestingSetup {
 /** Run random satisfaction tests. */
 void TestSatisfy(const KeyConverter& converter, const std::string& testcase, const NodeRef& node) {
     auto script = node->ToScript(converter);
-    auto challenges = FindChallenges(node); // Find all challenges in the generated miniscript.
+    const auto challenges{FindChallenges(node.get())}; // Find all challenges in the generated miniscript.
```
Comment (hodlinator) [inline src/test/miniscript_tests.cpp:351]: nit:
If you re-touch, it would be nicer to abide by the Sonar suggestion "...or a reference" with:
```suggestion
    const auto challenges{FindChallenges(*node)}; // Find all challenges in the generated miniscript.
```
and
```C++
std::set<Challenge> FindChallenges(const Node& root)
```
to signify `nullptr` being unsupported.

**Review by hodlinator — APPROVED** [review]
re-ACK 7e8ef959d0637ca5543ed33d3919937e0d053e70

nit: Would switch order of:
* e400ac53524d143467740e2f59698a7c94644c21 refactor: simplify repeated comparisons in `FindChallenges`
* f670836112c01feb3cb71618192e9c0c2e55767f test: remove old recursive `FindChallenges_recursive` implementation

This way CI should compare the `switch`-statement iterative version against the recursive one before it is removed. (Something I liked about what I last reviewed).

**Comment by darosior** [comment]
My review was requested but since Pieter and Hodlinator beat me to it i think this had enough review already?

**Comment by l0rinc** [comment]
If you don't have time to review, a concept ack would still be useful

**Comment by achow101** [comment]
ACK 7e8ef959d0637ca5543ed33d3919937e0d053e70

**Review by jonatack — COMMENTED** [review]
Post-merge ACK
