### PR TITLE
Notify on removal

### LINKED ISSUE #9479: -walletnotify isn't fired on transactions that were in the mempool and then evicted due to a tx in a new block conflicting them.
This is to track the regression introduced in master, which needs fixing for 0.14. See #9240, #9371, etc.

### PR DESCRIPTION
**Pull request by morcos**
Fixes #9479 

This is my alternative to reverting #9240 

@sipa 
@laanwj 

I think we have to decide which one of these 3 choices we like best:

- walletnotify, zmq notification and UI notification on all transactions evicted from the mempool for any reason => merge this PR or something similar
- walletnotify, zmq notification and UI notification on only transactions evicted from the mempool due to conflicts (prior behavior) => revert #9240
- No walletnotify, zmq notification and UI notification on any transactions evicted from the mempool including due to conflicts => do nothing

I'm not sure this PR is the perfect solution, but I found txConflicted confusing, and I'm hoping this is at least a bit of a clearer overall picture.

Feedback welcome.

### CODE REVIEW

File: src/txmempool.cpp [hunk 1]
```diff
@@ -469,11 +469,43 @@ void CTxMemPool::removeUnchecked(txiter it)
...
+}
+
+std::vector<CTransactionRef>  CTxMemPool::stopTrackingRemovals() {
+    LOCK(cs);
+    assert(trackRemovalsCount);
+    trackRemovalsCount--;
+    if (trackRemovalsCount == 0) {
+        std::vector<CTransactionRef> temp(std::move(removedTxs));
+        removedTxs.clear();
+        return std::move(temp);
```
Comment (sipa) [inline src/txmempool.cpp]: It's better to have a single return statement that returns a local variable over using std::move:

```c++
    ...
    std::vector<CTransactionRef> temp;
    if (trackRemovalsCount == 0) {
        temp.emplace_back(std::move(removedTxs));
        removedTxs.clear();
    }
    return temp;
}
```

This allows the compiler to use NVRO (named return value optimization) - the `temp` variable essentially becomes an alias for the returned object.

Comment (ryanofsky) [inline src/txmempool.cpp]: Using swap in the middle count be a nice way to simplify this:

```
    std::vector<CTransactionRef> temp;
    if (trackRemovalsCount == 0)
        temp.swap(removedTxs);
    return temp;
```

File: src/txmempool.cpp [hunk 2]
```diff
@@ -469,11 +469,43 @@ void CTxMemPool::removeUnchecked(txiter it)
...
     mapLinks.erase(it);
+    if (!minedInBlock) {
+        if (trackRemovalsCount) {
+            removedTxs.emplace_back(it->GetSharedTx());
+        }
+        else {
+            // If there are ever intentionally removals that are not
+            // meant to be tracked (so they can be notified on), then
+            // this log message can be removed.
+            LogPrint("mempool", "MemPoolRemovalTracker not tracking removed transaction %s\n",hash.ToString());
```
Comment (rebroad) [inline src/txmempool.cpp]: Is this the only notification, or is the GUI notified also?

**Comment by dcousens** [comment]
> walletnotify, zmq notification and UI notification on all transactions evicted from the mempool for any reason

A ZMQ notification that anything has been removed from the mempool (conflicts, accepted into a block, expired, ...) would be ideal for me.

**Comment by dcousens** [comment]
Is there a way to isolate these changes to the wallet code only?
I understand it is to fix a problem there,  but ideally I'd rather see just a primitive mechanism in the mempool for removal events,  and the wallet then handle that with a "mempool removal tracker" and such.

**Comment by laanwj** [comment]
> I'd rather see just a primitive mechanism in the mempool for removal events, and the wallet then handle that with a "mempool removal tracker" and such.

In #8549 I had added a specific signal on the mempool to be notified of removed transactions, even with a reason field.
I think this was slightly more elegant than having a stateful StartTracking/StopTracking in the mempool itself and keeping a vector there. A client could easily handle the part of accumulating notifications into a vector itself, if that is desired.

**Comment by jonasschnelli** [comment]
Agree with @laanwj: the reason enum is really what we should have for mempool removal notifications: https://github.com/bitcoin/bitcoin/pull/8549/files#diff-d8e6fe13399f13c42a93ec8326c60614R150

**Comment by dcousens** [comment]
Agree with @laanwj,  I actually thought that was merged and was wondering why this wasn't using it.

File: src/txmempool.cpp (hunk 2 above)
Comment (morcos) [inline src/txmempool.cpp]: about the error?  this is the only log of the fact that a removal happened without notification.

**Comment by morcos** [comment]
@laanwj ah, sorry I hadn't seen #8549.  The reason I did it this way instead of trying to do notifications from the mempool directly was because we had just gone to such much effort to remove other notifications from happening within cs_main during the block connection logic.  

It would be very easy to add to this PR the ability to distinguish between: "added", "removed", "appeared in a disconnected block", but slightly more involved to distinguish between the various "removed" reasons.

Whichever approach we take, I think it's a step in the right direction towards cleaning up the notification design and we should keep going.  Note for example that even after #8549, I think "rawtx" and "hashtx" notifications are also happening on transactions in disconnected blocks (and before #9240 in transactions removed due to conflict), which doesn't seem to be the intent.

**Comment by morcos** [comment]
rebased

**Comment by morcos** [comment]
.. and added @ryanofsky's suggested cleanup

**Comment by sipa** [comment]
It seems strange to have a constraint that the mempool is either in a tracking or non-tracking state... the mempool object itself shouldn't need to know or care that there is at most one entity interested in seeing its removals.

Would it be possible to instead have a callback installed from the mempool to notify whatever is interested of removed transactions?

**Comment by morcos** [comment]
Yes @laanwj had a similar comment.
What I wanted to accomplish was that the notifications (or at least some of the potentially time consuming ones) happened outside of the critical path.  The same as the change we recently made with transactions in connected blocks.  But perhaps there is a better way to design that where the mempool just fires off its notifications immediately, but there can be a helper class that subscribes and appropriately batches them before passing them on?  It's a bit tricky to imagine how some removals caused by limiting inside ATMP should be fired immediately and some shouldn't, but there ought to be a way.

In any case I'm open to a suggestion on redesigning that aspect of it.

**Comment by sipa** [comment]
The receiver of the mempool-removal event notifications can also still add things to a queue for later processing, i mean. It doesn't need to be the mempool that does the batching - as that inherently only works for a single consumer of event.

**Comment by morcos** [comment]
OK I've redone this in a way that is hopefully more appealing.

The first commit is stolen (and slightly tweaked) from #8549 and will lay the ground work for a more flexible notification system on mempool actions. 

Then I introduce a minimal `MemPoolConflictRemovalTracker` which should exactly mimic the behavior of txConflicted that was removed in #9240.  I wouldn't argue that we want to keep this class in the long run, but as a regression fix for 0.14, I think this most clearly accomplishes the goal while moving us in a forward direction.

In the future we will want to rethink exactly what notifications need to fire on mempool removals and when.  Most of the wallet functionality that is called by SyncTransaction is a no-op on mempool removals except for downstream notifications.   This is documented.

File: src/validation.cpp [hunk 3]
```diff
@@ -157,6 +157,39 @@ namespace {
...
+    void NotifyEntryRemoved(CTransactionRef txRemoved, MemPoolRemovalReason reason) {
+        if (reason == MemPoolRemovalReason::CONFLICT) {
+            conflictedTxs.push_back(txRemoved);
+        }
+    }
+
+    ~MemPoolConflictRemovalTracker() {
+        pool.NotifyEntryRemoved.disconnect(boost::bind(&MemPoolConflictRemovalTracker::NotifyEntryRemoved, this, _1, _2));
+        for (const auto& tx : conflictedTxs) {
+            GetMainSignals().SyncTransaction(*tx, NULL, CMainSignals::SYNC_TRANSACTION_NOT_IN_BLOCK);
```
Comment (theuni) [inline src/validation.cpp]: Seems like a good time to split up SyncTransaction.

How about dropping the SYNC_TRANSACTION_NOT_IN_BLOCK kludge, and adding a new signal for mempool removals? I suspect @TheBlueMatt's recent-removed-tx-cache could benefit from that as well.

Comment (TheBlueMatt) [inline src/validation.cpp]: I do that half way in #9570, lets leave this until the code is not in flux?

File: src/validation.cpp [hunk 4]
```diff
@@ -2446,6 +2479,14 @@ bool ActivateBestChain(CValidationState &state, const CChainParams& chainparams,
...
         ConnectTrace connectTrace;
         bool fInitialDownload;
+        { // TODO: Tempoarily ensure that mempool removals are notified before
+          // connected transactions.  This shouldn't matter, but the abandoned
+          // state of transactions in our wallet is currently cleared when we
+          // receive another notification and there is a race condition where
+          // notification of a connected conflict might cause an outside process
+          // to abandon a transaction and then have it inadvertantly cleared by
+          // the notification that the conflicted transaction was evicted.
+        MemPoolConflictRemovalTracker mrt(mempool);
```
Comment (TheBlueMatt) [inline src/validation.cpp]: I believe you need some lock held here so that no two threads could be calling mempool.NotifyEntryRemoved.connect at the same time, however I agree you dont want to SyncTransaction with cs_main held. You could add a static mutex here, or you could create the object with cs_main, then std::move it to a dummy which will be destroyed without cs_main.

**Comment by TheBlueMatt** [comment]
I believe this breaks #9570. Even if its rebased on #9570 (so that SyncTransaction becomes SyncTransactions and they're all batched together), the multiple per-block SyncTransactions calls will still expose wallet state as of mid-block to RPC clients. I'm not sure how exactly we should go about fixing this, but one way might be to take @theuni's suggestion for 0.14 and split SyncTransaction to SyncTransactionsFromBlock(vTxnConnected, vTxnConflicted) and TransactionAddedToMemPool(tx) so that we can hold the cs_wallet lock the whole time in SyncTransactionsFromBlock.

File: src/validation.cpp (hunk 4 above)
Comment (morcos) [inline src/validation.cpp]: Hmm I guess you're right..  Perhaps I need to go back to reference counting these things..

**Comment by morcos** [comment]
Yeah ....  frustrating...   Ideally we wouldn't actually be calling the wallet part of SyncTransaction for these transactions anyway.  But I suspect that for 0.14 we should just be fine with wallet state being inspectable between these.  As you point out it should have basically no effect...  (it really shouldn't be unabandoning anything, that would imply some other logic was broken)

**Comment by morcos** [comment]
OK this has been rebased on #9583 which automagically fixes the lesser synchronization issues here if these notifications are also moved inside cs_main.

The ugly scope hack to have removals notified before connections I think should be removed after we tidy up abandoned logic in some future PR.  I believe the natural order of notifications should be chainstate changes before mempool changes...

**Comment by TheBlueMatt** [comment]
utACK 094e4b33839404d9c18200fc30d9a993a3dc106f

File: src/validation.cpp [hunk 5]
```diff
@@ -3597,7 +3642,7 @@ bool CVerifyDB::VerifyDB(const CChainParams& chainparams, CCoinsView *coinsview,
             return error("VerifyDB(): *** ReadBlockFromDisk failed at %d, hash=%s", pindex->nHeight, pindex->GetBlockHash().ToString());
         // check level 1: verify block validity
         if (nCheckLevel >= 1 && !CheckBlock(block, state, chainparams.GetConsensus()))
-            return error("%s: *** found bad block at %d, hash=%s (%s)\n", __func__, 
+            return error("%s: *** found bad block at %d, hash=%s (%s)\n", __func__,
```
Comment (laanwj) [inline src/validation.cpp]: μ-nit: please don't include space changes in otherwise unchanged lines/functions

**Comment by laanwj** [comment]
Looks good to me now. utACK 094e4b3

File: src/validation.cpp (hunk 5 above)
Comment (morcos) [inline src/validation.cpp]: heh.  sure.  i'll pass that on to the commit author. :)

**Comment by ryanofsky** [comment]
@jnewbery pointed out the PR description here became out of date and doesn't reflect the change that was actually merged

re: https://github.com/bitcoin/bitcoin/pull/9371#issue-98389524

> I think we have to decide which one of these 3 choices we like best:
>
>- walletnotify, zmq notification and UI notification on all transactions evicted from the mempool for any reason => merge this PR or something similar
>- walletnotify, zmq notification and UI notification on only transactions evicted from the mempool due to conflicts (prior behavior) => revert #9240
>- No walletnotify, zmq notification and UI notification on any transactions evicted from the mempool including due to conflicts => do nothing

Initially this PR implemented the first choice behavior ([commits](https://github.com/bitcoin/bitcoin/commits/f3baf89e0de30d551e701c16cdba66062ab12df0)), but it was changed in https://github.com/bitcoin/bitcoin/pull/9371#issuecomment-273571462 to implement second choice behavior instead. That behavior got broken again in 7e89994133725125dddbfa8d45484e3b9ed51c6e from #16624 and we are currently discussing how to restore it in #18325
