### PR TITLE
test: Fix inconsistent lock order in wallet_tests/CreateWallet

### LINKED ISSUE #19049: test: Potential deadlock in wallet_tests/CreateWalletFromFile
Building master (df303ceb650521dc7b1ba91e0eea383c387a5860) on Linux Mint 19.3 (x86_64, bionic codebase):
```
$ ./configure --with-sanitizers=thread && make clean && make
$ TSAN_OPTIONS="suppressions=test/sanitizer_suppressions/tsan" ./src/test/test_bitcoin --run_test=wallet_tests/CreateWalletFromFile
Running 1 test case...
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
==================
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=31793)
  Cycle in lock order graph: M134059 (0x7b6400004cc8) => M133094 (0x56527c390c60) => M134059

  Mutex M133094 acquired here while holding mutex M134059 in main thread:
    #0 pthread_mutex_lock <null> (libtsan.so.0+0x3fadb)
    #1 __gthread_mutex_lock /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:748 (test_bitcoin+0xd17c11)
    #2 __gthread_recursive_mutex_lock /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:810 (test_bitcoin+0xd17c11)
    #3 std::recursive_mutex::lock() /usr/include/c++/7/mutex:107 (test_bitcoin+0xd17c11)
    #4 std::unique_lock<std::recursive_mutex>::lock() /usr/include/c++/7/bits/std_mutex.h:267 (test_bitcoin+0xd17c11)
    #5 UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::Enter(char const*, char const*, int) sync.h:131 (test_bitcoin+0xd17c11)
    #6 UniqueLock<AnnotatedMixin<std::recursive_mutex>, std::unique_lock<std::recursive_mutex> >::UniqueLock(AnnotatedMixin<std::recursive_mutex>&, char const*, char const*, int, bool) sync.h:152 (test_bitcoin+0xd17c11)
    #7 CWallet::CreateWalletFromFile(interfaces::Chain&, WalletLocation const&, bilingual_str&, std::vector<bilingual_str, std::allocator<bilingual_str> >&, unsigned long) wallet/wallet.cpp:4004 (test_bitcoin+0xd397de)
    #8 TestLoadWallet wallet/test/wallet_tests.cpp:37 (test_bitcoin+0x703587)
    #9 wallet_tests::CreateWalletFromFile::test_method() wallet/test/wallet_tests.cpp:782 (test_bitcoin+0x72013e)
    #10 CreateWalletFromFile_invoker wallet/test/wallet_tests.cpp:700 (test_bitcoin+0x721452)
    #11 boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) /usr/include/boost/function/function_template.hpp:118 (test_bitcoin+0xe05fb)
    #12 boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) <null> (libboost_unit_test_framework.so.1.65.1+0x4b2cd)
    #13 __libc_start_main <null> (libc.so.6+0x21b96)

    Hint: use TSAN_OPTIONS=second_deadlock_stack=1 to get more informative warning message

  Mutex M134059 acquired here while holding mutex M133094 in main thread:
    #0 pthread_mutex_lock <null> (libtsan.so.0+0x3fadb)
    #1 __gthread_mutex_lock /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:748 (test_bitcoin+0x71e053)
    #2 __gthread_recursive_mutex_lock /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:810 (test_bitcoin+0x71e053)
    #3 std::recursive_mutex::lock() /usr/include/c++/7/mutex:107 (test_bitcoin+0x71e053)
    #4 AnnotatedMixin<std::recursive_mutex>::lock() sync.h:90 (test_bitcoin+0x71e053)
    #5 operator() wallet/test/wallet_tests.cpp:780 (test_bitcoin+0x71e053)
    #6 _M_invoke /usr/include/c++/7/bits/std_function.h:316 (test_bitcoin+0x71e677)
    #7 std::function<void (std::unique_ptr<interfaces::Wallet, std::default_delete<interfaces::Wallet> >)>::operator()(std::unique_ptr<interfaces::Wallet, std::default_delete<interfaces::Wallet> >) const /usr/include/c++/7/bits/std_function.h:706 (test_bitcoin+0xd39850)
    #8 CWallet::CreateWalletFromFile(interfaces::Chain&, WalletLocation const&, bilingual_str&, std::vector<bilingual_str, std::allocator<bilingual_str> >&, unsigned long) wallet/wallet.cpp:4006 (test_bitcoin+0xd39850)
    #9 TestLoadWallet wallet/test/wallet_tests.cpp:37 (test_bitcoin+0x703587)
    #10 wallet_tests::CreateWalletFromFile::test_method() wallet/test/wallet_tests.cpp:782 (test_bitcoin+0x72013e)
    #11 CreateWalletFromFile_invoker wallet/test/wallet_tests.cpp:700 (test_bitcoin+0x721452)
    #12 boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) /usr/include/boost/function/function_template.hpp:118 (test_bitcoin+0xe05fb)
    #13 boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) <null> (libboost_unit_test_framework.so.1.65.1+0x4b2cd)
    #14 __libc_start_main <null> (libc.so.6+0x21b96)

SUMMARY: ThreadSanitizer: lock-order-inversion (potential deadlock) (/usr/lib/x86_64-linux-gnu/libtsan.so.0+0x3fadb) in __interceptor_pthread_mutex_lock
==================
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found
WARNING: too long mutex cycle found

*** No errors detected
ThreadSanitizer: reported 1 warnings
```

---

The ThreadSanitizer does not report this issue on CI as the binaries are built with the `--disable-wallet` option: https://github.com/bitcoin/bitcoin/blob/df303ceb650521dc7b1ba91e0eea383c387a5860/ci/test/00_setup_env_native_tsan.sh#L14

UPDATE: This issue is caused by #16426 that has been merged on 2020-05-01.

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- fixes #19049 that was caused by #16426
- removes `wallet_tests::CreateWallet` suppression from the `test/sanitizer_suppressions/tsan`

The example of the improved `CheckLastCritical()`/`LEAVE_CRITICAL_SECTION()` log (could be got when compiled without the last commit):
```
2020-09-20T08:34:28.429485Z [test] INCONSISTENT LOCK ORDER DETECTED
2020-09-20T08:34:28.429493Z [test] Current lock order (least recent first) is:
2020-09-20T08:34:28.429501Z [test]  'walletInstance->cs_wallet' in wallet/wallet.cpp:4007 (in thread 'test')
2020-09-20T08:34:28.429508Z [test]  'cs_wallets' in wallet/wallet.cpp:4089 (in thread 'test')
```

Currently, there are other "naked" `LEAVE_CRITICAL_SECTION()` in the code base:
https://github.com/bitcoin/bitcoin/blob/b99a1633b270e0e89479b2bb2ae19a8a8dc0fa05/src/rpc/mining.cpp#L698

https://github.com/bitcoin/bitcoin/blob/b99a1633b270e0e89479b2bb2ae19a8a8dc0fa05/src/checkqueue.h#L208

### CODE REVIEW

**Comment by promag** [comment]
> This change reveals a bug in the wallet_tests/CreateWalletFromFile test,
that will be fixed in the following commit.

@hebasto I'm not following, how is it revealed?

**Comment by hebasto** [comment]
@promag 
> > This change reveals a bug in the wallet_tests/CreateWalletFromFile test,
> > that will be fixed in the following commit.
> 
> @hebasto I'm not following, how is it revealed?

```
$ git checkout 7ac14ec58740226af85401f879f37f09755b990b
$ ./autogen.sh && ./configure --enable-debug && make clean && make
$ src/test/test_bitcoin --run_test=wallet_tests/CreateWalletFromFile
Running 1 test case...
wallet/test/wallet_tests.cpp:786 wallet->wallet()->cs_wallet was not most recent critical section locked, details in debug log.
unknown location(0): fatal error: in "wallet_tests/CreateWalletFromFile": signal: SIGABRT (application abort requested)
wallet/test/wallet_tests.cpp(785): last checkpoint

*** 1 failure is detected in the test module "Bitcoin Core Test Suite"
^C
$ tail -4 '/tmp/test_common_Bitcoin Core/03a41ec8724b4ea8adc603b0dc139290a6f9c765607df0bc277823d7b0165c20/regtest/debug.log'
2020-09-21T09:16:36.739551Z [test] INCONSISTENT LOCK ORDER DETECTED
2020-09-21T09:16:36.739557Z [test] Current lock order (least recent first) is:
2020-09-21T09:16:36.739562Z [test]  'walletInstance->cs_wallet' in wallet/wallet.cpp:4007 (in thread 'test')
2020-09-21T09:16:36.739568Z [test]  'cs_wallets' in wallet/wallet.cpp:4089 (in thread 'test')
```

**Comment by promag** [comment]
Thanks @hebasto, I tried `make check` instead. I'd suggest to add `[skip ci]` to that commit body

**Comment by hebasto** [comment]
@promag 
> Thanks @hebasto, I tried `make check` instead.

```
$ make check
...
2020-09-21T09:41:56.850457Z [test] INCONSISTENT LOCK ORDER DETECTED
2020-09-21T09:41:56.850463Z [test] Current lock order (least recent first) is:
2020-09-21T09:41:56.850470Z [test]  'walletInstance->cs_wallet' in wallet/wallet.cpp:4007 (in thread 'test')
2020-09-21T09:41:56.850475Z [test]  'cs_wallets' in wallet/wallet.cpp:4089 (in thread 'test')
wallet/test/wallet_tests.cpp:786 wallet->wallet()->cs_wallet was not most recent critical section locked, details in debug log.
make[3]: *** [Makefile:20887: wallet/test/wallet_tests.cpp.test] Error 1
make[3]: Leaving directory '/home/hebasto/guix/GitHub/bitcoin/src'
make[2]: *** [Makefile:19327: check-am] Error 2
make[2]: Leaving directory '/home/hebasto/guix/GitHub/bitcoin/src'
make[1]: *** [Makefile:19012: check-recursive] Error 1
make[1]: Leaving directory '/home/hebasto/guix/GitHub/bitcoin/src'
make: *** [Makefile:798: check-recursive] Error 1
```

**Comment by hebasto** [comment]
Updated 283ddf104573fcf2ae648147e5ecf24c776246df -> d89c332c597a1129aa9fd3293bd37e7ab90171eb ([pr19982.03](https://github.com/hebasto/bitcoin/commits/pr19982.03) -> [pr19982.04](https://github.com/hebasto/bitcoin/commits/pr19982.04), [diff](https://github.com/hebasto/bitcoin/compare/pr19982.03..pr19982.04)):

- addressed @promag's [comment](https://github.com/bitcoin/bitcoin/pull/19982#issuecomment-696001691):
> I'd suggest to add `[skip ci]` to that commit body

**Comment by promag** [comment]
Oh I did't have `--enable-debug`.

File: src/wallet/test/wallet_tests.cpp [hunk 1]
```diff
@@ -776,16 +778,18 @@ BOOST_FIXTURE_TEST_CASE(CreateWalletFromFile, TestChain100Setup)
...
     addtx_count = 0;
-    auto handler = HandleLoadWallet([&](std::unique_ptr<interfaces::Wallet> wallet) EXCLUSIVE_LOCKS_REQUIRED(wallet->wallet()->cs_wallet) {
+    auto handler = HandleLoadWallet([&](std::unique_ptr<interfaces::Wallet> wallet) EXCLUSIVE_LOCKS_REQUIRED(wallet->wallet()->cs_wallet, cs_wallets) {
             BOOST_CHECK(rescan_completed);
             m_coinbase_txns.push_back(CreateAndProcessBlock({}, GetScriptForRawPubKey(coinbaseKey.GetPubKey())).vtx[0]);
             block_tx = TestSimpleSpend(*m_coinbase_txns[2], 0, coinbaseKey, GetScriptForRawPubKey(key.GetPubKey()));
             m_coinbase_txns.push_back(CreateAndProcessBlock({block_tx}, GetScriptForRawPubKey(coinbaseKey.GetPubKey())).vtx[0]);
             mempool_tx = TestSimpleSpend(*m_coinbase_txns[3], 0, coinbaseKey, GetScriptForRawPubKey(key.GetPubKey()));
             BOOST_CHECK(chain->broadcastTransaction(MakeTransactionRef(mempool_tx), DEFAULT_TRANSACTION_MAXFEE, false, error));
+            LEAVE_CRITICAL_SECTION(cs_wallets);
```
Comment (promag) [inline src/wallet/test/wallet_tests.cpp:788]: Can't we refactor the test to remove these (LEAVE/ENTER)CRITICAL_SECTION? Looks like this block could go after `TestLoadWallet`?

Comment (hebasto) [reply src/wallet/test/wallet_tests.cpp:788]: I don't think so as `HandleLoadWallet()` puts a lambda closure into the `g_load_wallet_fns` which in turn is used by `CWallet::Create()`: https://github.com/bitcoin/bitcoin/blob/b99a1633b270e0e89479b2bb2ae19a8a8dc0fa05/src/wallet/wallet.cpp#L4090-L4092

**Review by ariard — COMMENTED** [review]
Code Review ACK d89c332, feel free to take comments,  thanks for fixing this.

AFAICT this deadlock wasn't catch by CI at #16426 merge because LEAVE_CRITICAL didn't call neither `potential_deadlock_detected` or `CheckLastCritical`. Otherwise if a new lock would have been taken in the rest of `CreateWalletFromFile` it should have been detected.

So this PR does improve deadlock detection by flagging any lock order inconsistency even if it didn't materialize in an effective one as this case sounds to suggest ?

File: src/sync.cpp [hunk 2]
```diff
@@ -182,20 +182,28 @@ void EnterCritical(const char* pszName, const char* pszFile, int nLine, void* cs
...
+    LogPrintf("INCONSISTENT LOCK ORDER DETECTED\n");
+    LogPrintf("Current lock order (least recent first) is:\n");
+    for (const LockStackItem& i : lock_stack) {
+        LogPrintf(" %s\n", i.second.ToString());
+    }
+    if (g_debug_lockorder_abort) {
+        tfm::format(std::cerr, "%s:%s %s was not most recent critical section locked, details in debug log.\n", file, line, guardname);
+        abort();
+    }
+    throw std::logic_error(strprintf("%s was not most recent critical section locked", guardname));
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/sync.cpp:206]: Also it can throw in "naked" `LEAVE_CRITICAL_SECTION` that we have in the code base.

File: src/test/sync_tests.cpp [hunk 3]
```diff
@@ -55,4 +75,26 @@ BOOST_AUTO_TEST_CASE(potential_deadlock_detected)
...
+#endif // DEBUG_LOCKORDER
+
+    RecursiveMutex rmutex1, rmutex2;
+    TestInconsistentLockOrderDetected(rmutex1, rmutex2);
+    // The second test ensures that lock tracking data have not been broken by exception.
+    TestInconsistentLockOrderDetected(rmutex1, rmutex2);
+
+    Mutex mutex1, mutex2;
+    TestInconsistentLockOrderDetected(mutex1, mutex2);
+    // The second test ensures that lock tracking data have not been broken by exception.
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/test/sync_tests.cpp:92]: I'll address this comment if the reviewers request any other changes.

**Review by ryanofsky — APPROVED** [review]
Code review ACK d89c332c597a1129aa9fd3293bd37e7ab90171eb. Impressive work by hebasto not only debugging and fixing the buggy wallet test, but also improving deadlock detection, and improving deadlock detection output, and writing new deadlock detection tests!

@hebasto if you feel like adding more information to #19049, I'd be curious to know more you debugged this, since I gave up there struggling to figure out which locks were involved

**Comment by ryanofsky** [comment]
Note to anyone else interested in reviewing this that the change is simpler than it probably looks.

The actual bugfix in the third commit is very straightforward and just two lines. The first two commits are just improvements to error handling and debug output in lock order code, ignoring a big whitespace diff in the first commit.

**Comment by hebasto** [comment]
@ryanofsky 
> @hebasto if you feel like adding more information to #19049, I'd be curious to know more you debugged this, since I gave up there struggling to figure out which locks were involved

Our own lock stack being printed at some points appears very useful for debugging.

**Comment by hebasto** [comment]
Rebased d89c332c597a1129aa9fd3293bd37e7ab90171eb -> e2dc75f88fed8a4c0ca4baab485715001dce03d0 ([pr19982.04](https://github.com/hebasto/bitcoin/commits/pr19982.04) -> [pr19982.05](https://github.com/hebasto/bitcoin/commits/pr19982.05)) due to the conflict with #20285.

Also updated comments as [requested](https://github.com/bitcoin/bitcoin/pull/19982#discussion_r493716292) by @ariard.

File: src/test/sync_tests.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (hebasto) [reply src/test/sync_tests.cpp]: [Updated](https://github.com/bitcoin/bitcoin/pull/19982#issuecomment-727253125).

**Comment by hebasto** [comment]
Rebased d15646b4accabc2129fb4fa7049fb09c8def1c56 -> f2933e7a8636df9d428f89afb7208d35bb4c4041 ([pr19982.06](https://github.com/hebasto/bitcoin/commits/pr19982.06) -> [pr19982.07](https://github.com/hebasto/bitcoin/commits/pr19982.07)) due to the conflict with #19337.

**Review by ryanofsky — APPROVED** [review]
Code review ACK f2933e7a8636df9d428f89afb7208d35bb4c4041. Since last review just rebase updating test name and tweaking comments

**Comment by ryanofsky** [comment]
Notes that might be helpful to other reviewers: https://github.com/bitcoin/bitcoin/pull/19982#issuecomment-717520816.

The actual fix is very simple and contained in the third commit. The other two commits are error checking improvements.

File: src/test/reverselock_tests.cpp [hunk 4]
```diff
@@ -48,12 +48,22 @@ BOOST_AUTO_TEST_CASE(reverselock_errors)
...
+    bool error_thrown = false;
     try {
         REVERSE_LOCK(lock2);
         BOOST_CHECK(false); // REVERSE_LOCK(lock2) succeeded
-    } catch(...) { }
+    } catch(const std::logic_error& e) {
+        BOOST_CHECK_EQUAL(e.what(), "lock2 was not most recent critical section locked");
+        error_thrown = true;
+    }
+    BOOST_CHECK(error_thrown);
```
Comment (vasild) [inline src/test/reverselock_tests.cpp:63]: `BOOST_CHECK_EXCEPTION()` can help simplify this:

```suggestion
    BOOST_CHECK_EXCEPTION(REVERSE_LOCK(lock2), std::logic_error, HasReason("lock2 was not most recent critical section locked"));
```

File: src/test/sync_tests.cpp [hunk 5]
```diff
@@ -64,6 +64,26 @@ void TestDoubleLock(bool should_throw)
...
+    ENTER_CRITICAL_SECTION(mutex2);
+#ifdef DEBUG_LOCKORDER
+    bool error_thrown = false;
+    try {
+        LEAVE_CRITICAL_SECTION(mutex1);
+    } catch (const std::logic_error& e) {
+        BOOST_CHECK_EQUAL(e.what(), "mutex1 was not most recent critical section locked");
+        error_thrown = true;
+    }
+    BOOST_CHECK(error_thrown);
```
Comment (vasild) [inline src/test/sync_tests.cpp:81]: ditto:
```suggestion
    BOOST_CHECK_EXCEPTION(LEAVE_CRITICAL_SECTION(mutex1), std::logic_error, HasReason("mutex1 was not most recent critical section locked"));
```

**Review by vasild — APPROVED** [review]
ACK f2933e7a

```
lock m1
lock m2
unlock m1
unlock m2
```

the above was allowed before this PR and is forbidden after the PR. Such code cannot cause deadlock or any other issue and is legit. However it looks strange, may be a signal of a problem elsewhere and better be avoided. In our code in particular it would also brick the debugging mechanisms because `LeaveCritical()` from `unlock m1` would remove the wrong lock from the lock stack (`m2`).

I think it is ok to enforce "locks should be released in reverse order in which they were acquired"

**Comment by hebasto** [comment]
Updated f2933e7a8636df9d428f89afb7208d35bb4c4041 -> 608e14a2b69665b33df046cb96c74fefa2613969 ([pr19982.07](https://github.com/hebasto/bitcoin/commits/pr19982.07) -> [pr19982.08](https://github.com/hebasto/bitcoin/commits/pr19982.08), [diff](https://github.com/hebasto/bitcoin/compare/pr19982.07..pr19982.08)):

- addressed @vasild's comments

File: src/test/reverselock_tests.cpp (hunk 4 above)
Comment (hebasto) [reply src/test/reverselock_tests.cpp]: Thanks! [Updated](https://github.com/bitcoin/bitcoin/pull/19982#issuecomment-737757832).

File: src/test/sync_tests.cpp (hunk 5 above)
Comment (hebasto) [reply src/test/sync_tests.cpp]: [Updated](https://github.com/bitcoin/bitcoin/pull/19982#issuecomment-737757832).

**Comment by practicalswift** [comment]
Concept ACK

Nice work!

**Review by promag — COMMENTED** [review]
Tested ACK 608e14a2b69665b33df046cb96c74fefa2613969.

As expected `make check` fails on 79bfd2e27280eb0ad794b1f3389f4b00b38376b3 with `./configure --enable-debug`.

**Comment by vasild** [comment]
ACK 608e14a

**Comment by hebasto** [comment]
Rebased 608e14a2b69665b33df046cb96c74fefa2613969 -> e1e68b6305beb47ebf7ee48f14e12fdebdfea1ef ([pr19982.08](https://github.com/hebasto/bitcoin/commits/pr19982.08) -> [pr19982.09](https://github.com/hebasto/bitcoin/commits/pr19982.09)) due to the conflict with #19425.

**Comment by MarcoFalke** [comment]
review ACK e1e68b6305beb47ebf7ee48f14e12fdebdfea1ef 💂

<details><summary>Show signature and timestamp</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK e1e68b6305beb47ebf7ee48f14e12fdebdfea1ef 💂
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjlrAv/QIaj8D90XXyl/5Sw/WeG+cGB2diICRF1Pbv4qvEvG7sr+ETsScHeJvK2
TVlXBWujZcYo50jpPMl9j8XcnLR9MfnT0GYTwOi+z+fcXmi4NULQRqx6JrNQS0Cb
cZQXp/2BNo1cMBEKmUmfnG221SzZ+rKuhiJXBte3JprpIhQyJTMvSAwW1yoVwwfJ
P4OQp0gvW+kOt1+Gy3DK7u9DLN848blddAvwqKaH276oemN92iClv7O9YUJAs4qS
gWLnyFGOMhUICJVOKYzneSAWBM+xRC/Ujx1pE1V18uv+F9lqjZIS95V2OLEHu8CQ
OBRHx1LqruQOHvpS/SC3317KCv68QJtCuiz254G5zxGFsMBAl9wGY2XZjBYdiazD
7GTUVSXzVwa474uVJRPVnuLvKLF0IgqDGrNQo2t/x1kW+8qJ23UpuKOhJ+1nOReG
6la8BU2ng9UKcvlwJ6PqFN/0A/GlLeNzfGPGxT1OzRtyu/4wrFeDvPxvLd5jXyJx
Ea6eO6Vm
=A3Z6
-----END PGP SIGNATURE-----
```

[Timestamp of file with hash `b9199fb93572c3373d95d9880b18d20bf1295e74f013c4bf476dda6306523525  -`](https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e892940108b9199fb93572c3373d95d9880b18d20bf1295e74f013c4bf476dda6306523525f010da2c62a757542fd879817580b266e15c08fff01004c131de85c554ea50a2c75fad89468308f1045fd2750af008e97fda1fa5d603840083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6dfff0103dd78594f830c93c940147a5cacf971c08f020980fb04d33d342b30a0a84444844216be116040cfcc12e36ee162f169576b89a08f1045fd2750bf008cc46e9b6be844c5d0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff0104af3ad5f958442e38d0d5d3ae232b4f708f120e64c8b7a5843431bbb5d9d2da849a214b28785e454c2dd8ca339cae25d139dfd08f1045fd2750af008c758d6593bebbde30083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010e0515a94d692d5e2981ec609d3c55f3208f1045fd2750bf00850ad4303c4fb8ac60083dfe30d2ef90c8e232268747470733a2f2f6274632e63616c656e6461722e636174616c6c6178792e636f6d)

</details>

**Review by ryanofsky — APPROVED** [review]
Code review ACK e1e68b6305beb47ebf7ee48f14e12fdebdfea1ef. Just trivial rebase and suggested switch to BOOST_CHECK_EXCEPTION since last review

**Review by vasild — APPROVED** [review]
ACK e1e68b630
