### PR TITLE
config: allow setting -proxy per network

### LINKED ISSUE #24450: Apparently CJDNS network does not work with Tor on mainnet.
Apparently CJDNS network does not work with Tor on mainnet.

**Expected behavior**

Both networks should work.

**Actual behavior**

When monitoring connections via `./src/bitcoin-cli  -netinfo 4`, this does not show any CJDNS peers if Tor is enabled.
If the Tor proxy is commented out in the configuration file, the CJDNS peers will be connected.

**To reproduce**

Install Tor, I2P and CJDNS services on Fedora / Debian.

Add the following items to `bitcoin.conf` file:
```
[main]
proxy=127.0.0.1:9050
cjdnsreachable=1
i2pacceptincoming=1
i2psam=127.0.0.1:7656
addnode=fcc7:be49:ccd1:dc91:3125:f0da:457d:8ce
addnode=fc32:17ea:e415:c3bf:9808:149d:b5a2:c9aa
addnode=sedndhv5vpcgdmykyi5st4yqhdxl3hpdtglta4do435wupahhx6q.b32.i2p:0
addnode=zsxwyo6qcn3chqzwxnseusqgsnuw3maqnztkiypyfxtya4snkoka.b32.i2p:0
addnode=wwbw7nqr3ahkqv62cuqfwgtneekvvpnuc4i4f6yo7tpoqjswvcwa.b32.i2p:0
addnode=opnyfyeiibe5qo5a3wbxzbb4xdiagc32bbce46owmertdknta5mi7uyd.onion:8333
addnode=rp7k2go3s5lyj3fnj6zn62ktarlrsft2ohlsxkyd7v3e3idqyptvread.onion:8333
addnode=xqt25cobm5zqucac3634zfght72he6u3eagfyej5ellbhcdgos7t2had.onion:8333
```
Run Bicoin Core. With the configuration above, there can be IPv4, onion and I2P peers, but not CJDNS.
Stop Bitcoin Core, comment out `proxy=127.0.0.1:9050` and restart it. There can be IPv4, CJDNS and I2P

**System information**
Bitcoin Core was compiled from master (last commit `ee8c9971256`). Ran on Fedora Linux 35. 
Same behavior observed on Debian 11.

### PR DESCRIPTION
**Pull request by vasild**
`-proxy=addr:port` specifies the proxy for all networks (except I2P). Previously only the Tor proxy could have been specified separately via `-onion=addr:port`.

Make it possible to specify separately the proxy for IPv4, IPv6, Tor and CJDNS by e.g. `-proxy=addr:port=ipv6`. Or remove the proxy for a given network, e.g. `-proxy=0=cjdns`.

Resolves: https://github.com/bitcoin/bitcoin/issues/24450

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -1189,31 +1204,34 @@ bool CheckHostPortOptions(const ArgsManager& args) {
...
+        {"-bind",            false,               true},
+        {"-rpcbind",         false,               false},
+        {"-torcontrol",      false,               false},
+        {"-whitebind",       false,               false},
+        {"-zmqpubhashblock", true,                false},
+        {"-zmqpubhashtx",    true,                false},
+        {"-zmqpubrawblock",  true,                false},
+        {"-zmqpubrawtx",     true,                false},
+        {"-zmqpubsequence",  true,                false},
     }) {
```
Comment (vasild) [inline src/init.cpp:1221]: note: `-bind` was added here. I guess before it was omitted because this loop did not support `=whatever` suffix. Now it does.

**Review by caesrcd — COMMENTED** [review]
ACK 6a9f04688f

I have reviewed the code, unit tests, and functional tests. I built the project and ran a node using the `-proxy=0=cjdns` parameter to verify the behavior. Confirmed that CJDNS correctly bypasses the general proxy as intended. Manual testing was performed on Arch Linux, and the node successfully connected over CJDNS directly without using the proxy.

**Review by pablomartin4btc — COMMENTED** [review]
If the user sets `-proxy=addr:port=tor` then `-onion=` shouldn't be allowed, no? Otherwise one could set 2 diff proxies for Tor(?).

Also, in [Tor's documentation](https://github.com/bitcoin/bitcoin/tree/master/doc/tor.md):

```
-proxy=ip:port  Set the proxy server. If SOCKS5 is selected (default), this proxy
                server will be used to try to reach .onion addresses as well.
```

So, shouldn't `-proxy=0=cjdns` be the default if `-cjdnsreachable` when `-proxy=addr:port`?

File: src/init.cpp [hunk 2]
```diff
@@ -1572,30 +1590,64 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
         }
 
-        if (!addrProxy.IsValid())
-            return InitError(strprintf(_("Invalid -proxy address or hostname: '%s'"), proxyArg));
+        Proxy proxy;
+        if (!proxy_str.empty() && proxy_str != "0") {
+            if (IsUnixSocketPath(proxy_str)) {
+                proxy = Proxy{proxy_str, /*tor_stream_isolation=*/proxyRandomize};
+            } else {
+                const std::optional<CService> addr{Lookup(proxy_str, 9050, fNameLookup)};
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/init.cpp]: Done.

**Comment by vasild** [comment]
`6a9f04688f...2059eaa692`: address suggestions

> If the user sets `-proxy=addr:port=tor` then `-onion=` shouldn't be allowed, no? Otherwise one could set 2 diff proxies for Tor(?).

I think that is ok, assuming the expectation is that later options override earlier ones. For example, without this PR, `-proxy=x -onion=y` is supposed to set the Tor proxy to `y`, overriding the earlier `x`. Updated `tor.md` to mention that.

> So, shouldn't `-proxy=0=cjdns` be the default if `-cjdnsreachable` when `-proxy=addr:port`?

Could be, but I do not like these "automatically set `x` only if `y` and `z` are true, otherwise something else". That would also change the default behavior in a breaking way - for people that use `-proxy` which does support CJDNS it will stop working. Maybe there are no such users, but we can't know for sure.

**Comment by pablomartin4btc** [comment]
>> Otherwise one could set 2 diff proxies for Tor(?).

> I think that is ok, assuming the expectation is that later options override earlier ones. For example, without this PR, `-proxy=x -onion=y` is supposed to set the Tor proxy to `y`, overriding the earlier `x`. Updated `tor.md` to mention that.

Ok.
 
> > So, shouldn't `-proxy=0=cjdns` be the default if `-cjdnsreachable` when `-proxy=addr:port`?
> 
> Could be, but I do not like these "automatically set `x` only if `y` and `z` are true, otherwise something else". That would also change the default behavior in a breaking way - for people that use `-proxy` which does support CJDNS it will stop working. Maybe there are no such users, but we can't know for sure.

Ok, but since the [previous statement](https://github.com/bitcoin/bitcoin/pull/32425#pullrequestreview-2818995555) (`-proxy=`...) from [Tor's doc](https://github.com/bitcoin/bitcoin/tree/master/doc/tor.md) combined with:

`-onlynet=onion  Make automatic outbound connections only to .onion addresses.`

Maybe we should give a warning at least (and perhaps suggesting: `-proxy=0=cjdns`) because that (`-proxy=ip[:<port>] -onlynet=onion -cjdnsreachable`) would make CJDNS not to work (?).

I think a more long term solution could be to add the possibility of having a separate proxy for CJDNS, as suggested on the [issue](https://github.com/bitcoin/bitcoin/issues/24450) by other commenters there.

**Review by caesrcd — COMMENTED** [review]
ACK 2059eaa692ff614c41dee50f4bc2d2946e5d42af

I have tested the code.

**Comment by 1440000bytes** [comment]
Concept ACK 

Multiple proxies for different networks would be useful. Might need release notes if this eventually gets merged.

File: doc/tor.md [hunk 3]
```diff
@@ -32,33 +32,43 @@ You can use the `getnodeaddresses` RPC to fetch a number of onion peers known to
...
+        set this if it's the same as the generic -proxy. You can use -onion=0 to
+        explicitly disable access to onion services.
+        ------------------------------------------------------------------------
+        Note: Only the -proxy option sets the proxy for DNS requests; with
+        -onion they will not route over Tor, so use -proxy if you have privacy
+        concerns.
+        ------------------------------------------------------------------------
+
+    If -proxy or -onion is specified multiple times, later occurences override
+    earlier ones and command line overrides the config file.
```
Comment (pinheadmz) [inline doc/tor.md:53]: Since you're touching this doc, you could also add a note about UNIX sockets which I should've added in #27375 ;-)

e.g.
```
UNIX domain sockets may be used for proxy connections. Set `-onion` or `-proxy`
to the local socket path with the prefix `unix:` (e.g. `-onion=unix:/home/me/torsocket`).
```

**Review by pinheadmz — APPROVED** [review]
ACK 2059eaa692ff614c41dee50f4bc2d2946e5d42af

Built and ran all tests on macos/arm64. Reviewed both commits and left a few nits.
Played with the feature on mainnet, and connected to all networks:

```
         ipv4    ipv6   onion   cjdns   total   block  manual
in          0       0       0       0       0
out         1       1       2       7      11       0       7
total       1       1       2       7      11
```

Even used tor's ipv4 and unix sockets for separate proxies ;-)

`bcd -debug=tor -debug=net -proxy=unix:/Users/matthewzipkin/tor/sock -proxy=127.0.0.1:9050=ipv6  -cjdnsreachable -proxy=0=cjdns`


<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 2059eaa692ff614c41dee50f4bc2d2946e5d42af
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmgiWz0ACgkQ5+KYS2KJ
yTp0Ag/+JZCDfs0ILvoCRuuUN74qNh1vlvS9eqie3d32quX4wjYE8ZQC4Ov18xlv
8nOCKzDu369bixp1N6HlQXqa41w0x0KbAshMHWsHwolKr5MumQTfOp6mcnMaD1J4
zbS1Jbyigs7x+ukeVLW22CH9I64GUGQuizmzuWA2/cR0ehFtkLsKyG/5HCSeQU4H
/VzzEGcYNeqKKroLKKswqbkcVSrzhz8I1P7ZOEMhYQ6kDTZ5YVKGhbqcb8n2S8nJ
Tr5GY72gx8WY+LwgLM3nuesus8jYSVKSwleWCGxm2uqKdAkLcBQajBnJy1kgIYO0
ieAMypz9OF8zYls6VvhuTZseTvMWIM0ai37/1YUS8R3Dk3c9habUhv2GoxEpHmZb
2vcJ133qtVRNj9ZWAy987lmXKz1m3imrH+SGGUdG0etaHjs6qz0JnFxv11/xTzaB
SBFc8nalkIG/RZqy72i3WskMdOxkywkVx2fzN5RYZdpxSb2krlaOVln3On60H8iW
Ewnk+MioS0s/1mvp+u31YG5GzRhqO4mCtQMG5IE2W+k58q1gMvq6uQtasgWGu9LX
ZihaLz2cxeHxCqQFaFP1rL54IB/2MWXWXOBCEp24JQT/LXAfq1sacikd1PzaI/T8
tVQcYWs1W3ZORKjqMhWaPEpXurz5mstul/zV/BkRcod6E9XgJPw=
=65/9
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

File: src/init.cpp [hunk 4]
```diff
@@ -1572,30 +1590,64 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
         }
 
-        if (!addrProxy.IsValid())
-            return InitError(strprintf(_("Invalid -proxy address or hostname: '%s'"), proxyArg));
+        Proxy proxy;
+        if (!proxy_str.empty() && proxy_str != "0") {
+            if (IsUnixSocketPath(proxy_str)) {
+                proxy = Proxy{proxy_str, /*tor_stream_isolation=*/proxyRandomize};
+            } else {
+                const std::optional<CService> addr{Lookup(proxy_str, DEFAULT_TOR_SOCKS_PORT, fNameLookup)};
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/init.cpp:1615]: Yes, that is the same in `master` so no change in behavior by this PR. In master it is using a magic number `9050` whereas here it uses the constant `DEFAULT_TOR_SOCKS_PORT`.

`-proxy=127.0.0.1=cjdns` would be interpreted as `-proxy=127.0.0.1:9050=cjdns` which might be the correct config, or if not then the user could use `-proxy=127.0.0.1:1234=cjdns` to specify another port.

Personally, I would favor a more dumb implementation that does not do such automations and guessings on behalf of the user. Such an implementation would require the port to always be provided and refuse to start if not.

File: doc/tor.md (hunk 3 above)
Comment (vasild) [reply doc/tor.md:53]: Done.

**Comment by vasild** [comment]
`2059eaa692...e98c51fcce`: address suggestions

**Review by pinheadmz — APPROVED** [review]
ACK e98c51fcce9ae3f441a416cab32a5c85756c6c64

Trivial changes since last ACK. Built and tested again on mainnet, this time added i2p as well, connected to peers on every network we support. Tried various proxy settings.

The code change is small and mostly just contained in `init.cpp`. We used to call `SetProxy()` on every network type with the same proxy endpoint, this new code parses more fine-grained config options and sets separate proxies based on the options.

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK e98c51fcce9ae3f441a416cab32a5c85756c6c64
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmgjTV8ACgkQ5+KYS2KJ
yToKAw/6AgyTgGUOnk+VxgZGTTFufgNES5uvasHJtpkvcNYf9boWGpVQXBxf9ePc
BR7ly5C1+Tmvv6X36FwLE+mhNbXHIK178lfWFs+CMMeeuEThwR7LapGSbdAZGa+l
RxXxAx49/Ns5wMnMXPS+7mDp3CKAk1HRm1u1AN5k99RcyXdG5QUqfCb5QctckTUZ
jS17RuzONdJxW34Xd+p2nfsbKYUBy0YQPfLyxjy4e3KaStmpQTtp0HIKampli4t4
GhJiD+Yxj3ohJHqMS7so7jFo6nXqYw9k8wNUdaZTySBwMk2vDzRYesoBuXQZqM+j
xV9KReg1zxbtJTtW4cC38Rr3qRJJm4AKUNQmybs5aDfT07UAe2Ocd+b2lX97Pg4L
EyFCneylgs9mY+XH6UJpbOMihGWjAzZ63dRGrnMEFwZuNOmSBCSqPgQNjqSyBnU1
Cwj8liKCzr+mYwgWSA1M57BJGc0ZYeIPOEi8NEBzwejtQN6ljESmtWXh3kgKcXyb
VE2e3KJvCTTtdjI8r6nk2cNGKDMwgzeJp1DAAMEj2xOT7rI0qYc1tdr4HUGhhl0w
TiCeCenZhgPyTocW0xVFTzAmvhm+WCHp6Epyucjo0hnK4esw965z2N3B+4tmCfMY
B6VJFHuUqaerSIlvFzI8QpJsP9UBUUe2VS+XXhBv1VnlNuGewDM=
=PiAP
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

**Review by caesrcd — COMMENTED** [review]
reACK e98c51fcce

**Review by danielabrozzoni — COMMENTED** [review]
Code Review ACK e98c51fcce9ae3f441a416cab32a5c85756c6c64

I have reviewed the code, and it looks good to me.
I run the tests locally and did some very limited manual testing, mimicking the functional test behavior (passing in `-proxy=...=network` and checking the `getnetworkinfo` output)

File: src/init.cpp [hunk 5]
```diff
@@ -1569,33 +1587,66 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
-        SetProxy(NET_IPV6, addrProxy);
-        SetProxy(NET_CJDNS, addrProxy);
-        SetNameProxy(addrProxy);
-        onion_proxy = addrProxy;
+        if (net_str.empty()) { // For all networks.
+            ipv4_proxy = ipv6_proxy = name_proxy = cjdns_proxy = onion_proxy = proxy;
+        } else if (net_str == "ipv4") {
+            ipv4_proxy = name_proxy = proxy;
+        } else if (net_str == "ipv6") {
+            ipv6_proxy = name_proxy = proxy;
```
Comment (luke-jr) [inline src/init.cpp:1630]: I'm not sure this logic is ideal. If you set an all-network proxy, but then disable it for IPv6, you might be expecting name resolution to use the proxy. Or maybe not.

File: src/init.cpp [hunk 6]
```diff
@@ -1569,33 +1587,66 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+    // -proxy sets a proxy for outgoing network traffic, possibly per network.
+    // -noproxy, -proxy=0 or -proxy="" can be used to remove the proxy setting, this is the default
+    Proxy ipv4_proxy;
+    Proxy ipv6_proxy;
+    Proxy onion_proxy;
+    Proxy name_proxy;
+    Proxy cjdns_proxy;
+    for (const std::string& param_value : args.GetArgs("-proxy")) {
+        const auto eq_pos{param_value.rfind('=')};
+        const std::string proxy_str{param_value.substr(0, eq_pos)}; // e.g. 127.0.0.1:9050=ipv4 -> 127.0.0.1:9050
```
Comment (luke-jr) [inline src/init.cpp:1600]: string_view?

**Review by luke-jr — COMMENTED** [review]
Probably an improvement as-is, but might want to think through the name proxy logic

File: doc/tor.md [hunk 7]
```diff
@@ -32,33 +32,53 @@ You can use the `getnodeaddresses` RPC to fetch a number of onion peers known to
...
+        the functions provided by the operating system, most likely resulting in
+        them being done over the clearnet to the DNS servers of the internet
+        service provider.
+        ------------------------------------------------------------------------
+
+If -proxy or -onion is specified multiple times, later occurences override
+earlier ones and command line overrides the config file. UNIX domain sockets may
+be used for proxy connections. Set `-onion` or `-proxy` to the local socket path
+with the prefix `unix:` (e.g. `-onion=unix:/home/me/torsocket`).
+
```
Comment (luke-jr) [inline doc/tor.md:64]: Did you want to indent this?

File: src/init.cpp [hunk 8]
```diff
@@ -1569,33 +1587,66 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+            ipv6_proxy = name_proxy = proxy;
+        } else if (net_str == "tor" || net_str == "onion") {
+            onion_proxy = proxy;
+        } else if (net_str == "cjdns") {
+            cjdns_proxy = proxy;
+        } else {
+            return InitError(strprintf(_("Unrecognized network in -proxy='%s': '%s'"), param_value, net_str));
+        }
+    }
+    if (ipv4_proxy.IsValid()) {
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/init.cpp:1639]: Right. But I prefer to be explicit rather than feed `SetProxy()` an invalid value and rely on it doing the "right thing". It is not documented what `SetProxy()` would do with an invalid input, so I prefer to have these checks.

File: src/init.cpp (hunk 5 above)
Comment (vasild) [reply src/init.cpp:1630]: That would require some convoluted juggling with the parameters. Like:

1. `-proxy=addr:port=ipv6` sets the "ipv6" and "name" proxy, so that just a single `-proxy=1.2.3.4:5678=ipv6` works as expected. However:
2. `-proxy=0=ipv6` removes _only_ the "ipv6" proxy and not the "name" proxy, so that what you describe works: `-proxy=addr:port -proxy=0=ipv6`.

Another option would be to provide a separate name proxy, e.g. `-proxy=addr:port=name` or `-proxy=addr:port=dns`. But then users will probably forget to set it an be surprised that `-proxy=addr:port=ipv4` does DNS requests without of the proxy. Then it would be tempting for us to automatically set the "name" proxy from the "ipv4" or "ipv6" proxy which is another convoluted automation.

I prefer to keep it simple as it is now, without having mismatching enable/disable logic (1. and 2. above) or automatically setting parameters based on other parameters.

File: src/init.cpp (hunk 6 above)
Comment (vasild) [reply src/init.cpp:1600]: That would make the string_view point to the temporary returned by `substr()`. That temporary is destroyed after the end of the statement, so the string_view remains with a dangling pointer. Like in the example in https://en.cppreference.com/w/cpp/string/basic_string/operator_basic_string_view which says "// Bad: holds a dangling pointer".

Or a small standalone program to demonstrate:

```cpp
int main(int, char**)
{
    std::string s{"abcd"};
    std::string_view sv{s.substr(2)};
    std::cout << sv << "\n";
    return 0;
}
```
Compile with `clang -fsanitize=address` and run:
```
==13945==ERROR: AddressSanitizer: stack-use-after-scope on address ...
```

File: doc/tor.md (hunk 7 above)
Comment (vasild) [reply doc/tor.md:64]: No, because when indented then it is rendered as a code block.

OK:
---

## 1. Run Bitcoin Core behind a Tor proxy

The first step is running Bitcoin Core behind a Tor proxy. This will already anonymize all
outgoing connections, but more is possible.

    -proxy=ip[:port]
        Set the proxy server. It will be used to try to reach .onion addresses
        as well. You need to use -noonion or -onion=0 to explicitly disable
        outbound access to onion services.

    -proxy=ip[:port]=tor
    or
    -onion=ip[:port]
        Set the proxy server for reaching .onion addresses. You do not need to
        set this if it's the same as the generic -proxy. You can use -onion=0 to
        explicitly disable access to onion services.
        ------------------------------------------------------------------------
        Note: The proxy for DNS requests is taken from
        -proxy=addr:port or
        -proxy=addr:port=ipv4 or
        -proxy=addr:port=ipv6
        (last one if multiple options are given). It is not taken from
        -proxy=addr:port=tor or
        -onion=addr:port.
        If no proxy for DNS requests is configured, then they will be done using
        the functions provided by the operating system, most likely resulting in
        them being done over the clearnet to the DNS servers of the internet
        service provider.
        ------------------------------------------------------------------------

If -proxy or -onion is specified multiple times, later occurences override
earlier ones and command line overrides the config file. UNIX domain sockets may
be used for proxy connections. Set `-onion` or `-proxy` to the local socket path
with the prefix `unix:` (e.g. `-onion=unix:/home/me/torsocket`).

    -listen
        When using -proxy, listening is disabled by default. If you want to                                                                                             
        manually configure an onion service (see section 3), you'll need to
        enable it explicitly.

    -connect=X
    -addnode=X
    -seednode=X
        When behind a Tor proxy, you can specify .onion addresses instead of IP
        addresses or hostnames in these parameters. Such addresses can also be
        exchanged with other P2P nodes.

    -onlynet=onion
        Make automatic outbound connections only to .onion addresses. Inbound
        and manual connections are not affected by this option. It can be
        specified multiple times to allow multiple networks, e.g. onlynet=onion,
        onlynet=i2p, onlynet=cjdns.

In a typical situation, this suffices to run behind a Tor proxy:

    ./bitcoind -proxy=127.0.0.1:9050

NOT OK:
---

## 1. Run Bitcoin Core behind a Tor proxy

The first step is running Bitcoin Core behind a Tor proxy. This will already anonymize all
outgoing connections, but more is possible.

    -proxy=ip[:port]
        Set the proxy server. It will be used to try to reach .onion addresses
        as well. You need to use -noonion or -onion=0 to explicitly disable
        outbound access to onion services.

    -proxy=ip[:port]=tor
    or
    -onion=ip[:port]
        Set the proxy server for reaching .onion addresses. You do not need to
        set this if it's the same as the generic -proxy. You can use -onion=0 to
        explicitly disable access to onion services.
        ------------------------------------------------------------------------
        Note: The proxy for DNS requests is taken from
        -proxy=addr:port or
        -proxy=addr:port=ipv4 or
        -proxy=addr:port=ipv6
        (last one if multiple options are given). It is not taken from
        -proxy=addr:port=tor or
        -onion=addr:port.
        If no proxy for DNS requests is configured, then they will be done using
        the functions provided by the operating system, most likely resulting in
        them being done over the clearnet to the DNS servers of the internet
        service provider.
        ------------------------------------------------------------------------

    If -proxy or -onion is specified multiple times, later occurences override
    earlier ones and command line overrides the config file. UNIX domain sockets may
    be used for proxy connections. Set `-onion` or `-proxy` to the local socket path
    with the prefix `unix:` (e.g. `-onion=unix:/home/me/torsocket`).

    -listen
        When using -proxy, listening is disabled by default. If you want to                                                                                             
        manually configure an onion service (see section 3), you'll need to
        enable it explicitly.

    -connect=X
    -addnode=X
    -seednode=X
        When behind a Tor proxy, you can specify .onion addresses instead of IP
        addresses or hostnames in these parameters. Such addresses can also be
        exchanged with other P2P nodes.

    -onlynet=onion
        Make automatic outbound connections only to .onion addresses. Inbound
        and manual connections are not affected by this option. It can be
        specified multiple times to allow multiple networks, e.g. onlynet=onion,
        onlynet=i2p, onlynet=cjdns.

In a typical situation, this suffices to run behind a Tor proxy:

    ./bitcoind -proxy=127.0.0.1:9050

**Comment by 1440000bytes** [comment]
Configured 2 tor proxies with different circuits for ipv4 and ipv6 and they are working as expected:

```
$ curl --socks5-hostname 127.0.0.1:9050 http://ipv4.icanhazip.com
45.90.185.109

$ curl --socks5-hostname [::1]:9053 http://ipv6.icanhazip.com
2605:6400:30:f174:1:1:1:1
```

Used these proxies to run `bitcoind`:

```
bitcoind -signet -proxy=127.0.0.1:9050=ipv4 -proxy=[::1]:9053=ipv6 
```

I see the proxies in `getnetworkinfo` and some outbound peers in `getpeerinfo`:

```
  {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "127.0.0.1:9050",
      "proxy_randomize_credentials": true
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "[::1]:9053",
      "proxy_randomize_credentials": true
    },
```

However, I am getting an error when I stop bitcoind in the logs:

```
2025-05-19T22:28:07Z Shutdown: In progress...
2025-05-19T22:28:07Z addcon thread exit
2025-05-19T22:28:07Z dnsseed thread exit
2025-05-19T22:28:07Z msghand thread exit
2025-05-19T22:28:07Z net thread exit
2025-05-19T22:28:08Z [error] Error while reading proxy response
```

It could be because of unreliable Tor connectivity. I tried increasing the timeout in https://github.com/bitcoin/bitcoin/blob/33f8f8ae4cedda2515c9d6123213c528bb82b7ee/src/netbase.cpp#L40 but it made no difference.

**Review by 1440000bytes — COMMENTED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/32425/commits/e98c51fcce9ae3f441a416cab32a5c85756c6c64

<details>
<summary>Signature</summary>

<pre>
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK e98c51fcce9ae3f441a416cab32a5c85756c6c64
-----BEGIN PGP SIGNATURE-----

iHUEARYKAB0WIQSSUwYqT5LWNFkIXKYtIwUgISpZAQUCaCuzGQAKCRAtIwUgISpZ
AVt3AP98Co6T1/S4RqaIWypoL4NI1B1PhTPdRdFdvPP0sHWxIgD/SlBxLKNBIehf
tvLSnyIV9cvCBRefydIJCTf+dS06tAw=
=D/ae
-----END PGP SIGNATURE-----
</pre>
</details>

File: src/init.cpp (hunk 6 above)
Comment (achow101) [inline src/init.cpp:1600]: In ca5781e23a8f299ff4f143d2355218f551e65944 "config: allow setting -proxy per network"

nit: `Split()`? (from `src/util/string.h`)

File: src/init.cpp [hunk 9]
```diff
@@ -1189,31 +1204,34 @@ bool CheckHostPortOptions(const ArgsManager& args) {
...
+        {"-zmqpubhashblock", true,                false},
+        {"-zmqpubhashtx",    true,                false},
+        {"-zmqpubrawblock",  true,                false},
+        {"-zmqpubrawtx",     true,                false},
+        {"-zmqpubsequence",  true,                false},
     }) {
-        for (const std::string& socket_addr : args.GetArgs(arg)) {
+        for (const std::string& param_value : args.GetArgs(param_name)) {
+            const std::string param_value_hostport{
+                suffix_allowed ? param_value.substr(0, param_value.rfind('=')) : param_value};
```
Comment (achow101) [inline src/init.cpp:1224]: In ca5781e23a8f299ff4f143d2355218f551e65944 "config: allow setting -proxy per network"

nit: I think using `Split()` would make this easier to read

**Comment by glozow** [comment]
Needs release note?

**Comment by vasild** [comment]
> Needs release note?

Right. Done in https://github.com/bitcoin/bitcoin/pull/32727

File: src/init.cpp (hunk 6 above)
Comment (vasild) [reply src/init.cpp:1600]: What about this:

```diff
diff --git a/src/init.cpp b/src/init.cpp
index 77dc74f690..08ec964e25 100644
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -1190,14 +1190,20 @@ bool CheckHostPortOptions(const ArgsManager& args) {
         {"-zmqpubhashtx",    true,                false},
         {"-zmqpubrawblock",  true,                false},
         {"-zmqpubrawtx",     true,                false},
         {"-zmqpubsequence",  true,                false},
     }) {
         for (const std::string& param_value : args.GetArgs(param_name)) {
-            const std::string param_value_hostport{
-                suffix_allowed ? param_value.substr(0, param_value.rfind('=')) : param_value};
+            const auto parts{util::SplitString(param_value, '=')};
+            if (!suffix_allowed && parts.size() >= 2) {
+                return InitError(strprintf(_("Invalid value for %s: contains '=': '%s'"), param_name, param_value));
+            }
+            if (parts.size() >= 3) {
+                return InitError(strprintf(_("Invalid value for %s: contains too many '=': '%s'"), param_name, param_value));
+            }
+            const auto param_value_hostport{parts.at(0)};
             std::string host_out;
             uint16_t port_out{0};
             if (!SplitHostPort(param_value_hostport, port_out, host_out)) {
 #ifdef HAVE_SOCKADDR_UN
                 // Allow unix domain sockets for some options e.g. unix:/some/file/path
                 if (!unix || !param_value.starts_with(ADDR_PREFIX_UNIX)) {
@@ -1568,20 +1574,20 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
     Proxy ipv4_proxy;
     Proxy ipv6_proxy;
     Proxy onion_proxy;
     Proxy name_proxy;
     Proxy cjdns_proxy;
     for (const std::string& param_value : args.GetArgs("-proxy")) {
-        const auto eq_pos{param_value.rfind('=')};
-        const std::string proxy_str{param_value.substr(0, eq_pos)}; // e.g. 127.0.0.1:9050=ipv4 -> 127.0.0.1:9050
+        const auto parts{util::SplitString(param_value, '=')};
+        const auto& proxy_str{parts.at(0)};
         std::string net_str;
-        if (eq_pos != std::string::npos) {
-            if (eq_pos + 1 == param_value.length()) {
+        if (parts.size() == 2) {
+            net_str = ToLower(parts[1]);
+            if (net_str.empty()) {
                 return InitError(strprintf(_("Invalid -proxy address or hostname, ends with '=': '%s'"), param_value));
             }
-            net_str = ToLower(param_value.substr(eq_pos + 1)); // e.g. 127.0.0.1:9050=ipv4 -> ipv4
         }
 
         Proxy proxy;
         if (!proxy_str.empty() && proxy_str != "0") {
             if (IsUnixSocketPath(proxy_str)) {
                 proxy = Proxy{proxy_str, /*tor_stream_isolation=*/proxyRandomize};
diff --git a/test/functional/feature_proxy.py b/test/functional/feature_proxy.py
index ba8a0212a6..651bdb8d4c 100755
--- a/test/functional/feature_proxy.py
+++ b/test/functional/feature_proxy.py
@@ -446,12 +446,22 @@ class ProxyTest(BitcoinTestFramework):
 
         self.log.info("Test passing trailing '=' raises expected init error")
         self.nodes[1].extra_args = ["-proxy=127.0.0.1:9050="]
         msg = "Error: Invalid -proxy address or hostname, ends with '=': '127.0.0.1:9050='"
         self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
 
+        self.log.info("Test passing '=' raises expected init error when '=' is not allowed")
+        self.nodes[1].extra_args = ["-onion=a=b"]
+        msg = "Error: Invalid value for -onion: contains '=': 'a=b'"
+        self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
+
+        self.log.info("Test passing too many '=' raises expected init error")
+        self.nodes[1].extra_args = ["-proxy=127.0.0.1:9050=ipv4=x"]
+        msg = "Error: Invalid value for -proxy: contains too many '=': '127.0.0.1:9050=ipv4=x'"
+        self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
+
         self.log.info("Test passing unrecognized network raises expected init error")
         self.nodes[1].extra_args = ["-proxy=127.0.0.1:9050=foo"]
         msg = "Error: Unrecognized network in -proxy='127.0.0.1:9050=foo': 'foo'"
         self.nodes[1].assert_start_raises_init_error(expected_msg=msg)
 
         self.log.info("Test passing proxy only for IPv6")
```

Better? Append to https://github.com/bitcoin/bitcoin/pull/32727?
