### PR TITLE
More user-friendly error message when partially signing

### LINKED ISSUE #9988: signrawtransaction shows errors after partially signing a multisig transaction
#### If so, please list the steps to reproduce below:
1. Follow the steps in https://gist.github.com/gavinandresen/3966071

### Expected behaviour
The first `signrawtransaction` command should be successful and return a partially signed transaction that can be sent to the other cosigners for signing.

### Actual behaviour
Instead `signrawtransaction` fails and does not return a partially signed transaction.

### What version of bitcoin-core are you using?
This was reported for 0.14.0. However we have determined that it affects 0.11.1 and later, and likely 0.11.0. It does not affect 0.10.3.

It appears that the bug is caused by [this `VerifyScript` call](https://github.com/bitcoin/bitcoin/blob/master/src/rpc/rawtransaction.cpp#L849) which was introduced in 8ac2a4e1788426329b842eea7121b8eac7875c76 which has been a part of all versions since 0.11.0rc1.

See also: https://bitcointalk.org/index.php?topic=1823847.msg18164848#msg18164848

### PR DESCRIPTION
**Pull request by meshcollider**
When partially signing a transaction using `signrawtransaction`, if the wallet doesn't have access to a key, it will output a scary error message `"error": "Operation not valid with the current stack size"`, yet it will partially sign the transaction anyway. This puts a lot of users off, because they don't realise the signing actually succeeded for some inputs. This catches that specific error when signing, and outputs a friendlier message which says `Unable to sign input, invalid stack size (possibly missing key)`. 

This is the best way I could think of to fix the issue, but please let me know if you come up with a better way to do it :)

Fixes https://github.com/bitcoin/bitcoin/issues/9988

### CODE REVIEW

File: src/rpc/rawtransaction.cpp [hunk 1]
```diff
@@ -873,7 +873,13 @@ UniValue signrawtransaction(const JSONRPCRequest& request)
 
         ScriptError serror = SCRIPT_ERR_OK;
         if (!VerifyScript(txin.scriptSig, prevPubKey, &txin.scriptWitness, STANDARD_SCRIPT_VERIFY_FLAGS, TransactionSignatureChecker(&txConst, i, amount), &serror)) {
-            TxInErrorToJSON(txin, vErrors, ScriptErrorString(serror));
+            if(serror == SCRIPT_ERR_INVALID_STACK_OPERATION) {
+                // we haven't been able to sign this input and verification failed, could be attempting to partially sign
```
Comment (promag) [inline src/rpc/rawtransaction.cpp]: Nit:
```cpp
// Unable to sign input and verification failed (possible attempt to partially sign).
```

File: src/rpc/rawtransaction.cpp [hunk 2]
```diff
@@ -873,7 +873,13 @@ UniValue signrawtransaction(const JSONRPCRequest& request)
...
+                TxInErrorToJSON(txin, vErrors, "Unable to sign input, invalid stack size (possibly missing key)");
+            } else {
+               // some other issue
```
Comment (promag) [inline src/rpc/rawtransaction.cpp]: Nit, remove comment.

**Review by promag — COMMENTED** [review]
Care to add a test for expected output?

File: src/rpc/rawtransaction.cpp [hunk 3]
```diff
@@ -873,7 +873,13 @@ UniValue signrawtransaction(const JSONRPCRequest& request)
 
         ScriptError serror = SCRIPT_ERR_OK;
         if (!VerifyScript(txin.scriptSig, prevPubKey, &txin.scriptWitness, STANDARD_SCRIPT_VERIFY_FLAGS, TransactionSignatureChecker(&txConst, i, amount), &serror)) {
-            TxInErrorToJSON(txin, vErrors, ScriptErrorString(serror));
+            if(serror == SCRIPT_ERR_INVALID_STACK_OPERATION) {
```
Comment (promag) [inline src/rpc/rawtransaction.cpp]: Missing space after `if`.

**Comment by laanwj** [comment]
utACK, to me honest this caught me off-guard too the first time I used multi-signed transactions.

**Comment by achow101** [comment]
utACK df10edfd03fe4c9d1eca43a17ac4c54a14ac4832

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11288/commits/df10edfd03fe4c9d1eca43a17ac4c54a14ac4832

I've come across this as well too. thanks.
