### PR TITLE
init: disallow reindex-chainstate when pruning

### LINKED ISSUE #24242: -reindex-chainstate with -prune hangs
Steps to reproduce:

* Create a datadir that is pruned
* Start with `-prune=550 -reindex-chainstate`
* Hangs with idle CPU

(`-reindex` works)

### PR DESCRIPTION
**Pull request by mzumsande**
The combination of `-reindex-chainstate` and `-prune` currently makes the node stuck in an endless loop:

- `LoadChainstate()` will wipe the existing chainstate (so we have no genesis block anymore). It won't clean up unusable block files by calling `CleanupBlockRevFiles()` as for full `-reindex`.
- `ThreadImport()` has [logic](https://github.com/bitcoin/bitcoin/blob/91d12344b1e51809c1ef6b630b631a6da00267c3/src/node/blockstorage.cpp#L855) of reloading Genesis after reindexing. This is what makes full `-reindex` work with `-prune` but it's not executed for `-reindex-chainstate`.
- Since we still don't have a genesis block, init will wait for it forever in an endless loop ([code](https://github.com/bitcoin/bitcoin/blob/91d12344b1e51809c1ef6b630b631a6da00267c3/src/init.cpp#L1630-L1640)).

Fix this by disallowing `-reindex-chainstate` together with `-prune`. This is discouraged in the help for `-reindex-chainstate` anyway ("When in pruning mode or if blocks on disk might be corrupted, use full -reindex instead.") but wasn't enforced.

Fixes #24242

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -853,12 +853,14 @@ bool AppInitParameterInteraction(const ArgsManager& args)
...
     }
 
-    // if using block pruning, then disallow txindex and coinstatsindex
+    // if using block pruning, then disallow txindex and coinstatsindex and reindex-chainstate
     if (args.GetIntArg("-prune", 0)) {
         if (args.GetBoolArg("-txindex", DEFAULT_TXINDEX))
             return InitError(_("Prune mode is incompatible with -txindex."));
         if (args.GetBoolArg("-coinstatsindex", DEFAULT_COINSTATSINDEX))
             return InitError(_("Prune mode is incompatible with -coinstatsindex."));
+        if (args.GetBoolArg("-reindex-chainstate", false))
```
Comment (MarcoFalke) [inline src/init.cpp:862]: nit for new code

```suggestion
        if (args.GetBoolArg("-reindex-chainstate", false)) {
```

**Review by maflcko — APPROVED** [review]
ACK. Thx

File: src/init.cpp [hunk 2]
```diff
@@ -853,12 +853,14 @@ bool AppInitParameterInteraction(const ArgsManager& args)
...
+            return InitError(_("Prune mode is incompatible with -reindex-chainstate. Use full -reindex instead."));
```
Comment (jonatack) [inline src/init.cpp:863]: Might be good to update -prune as well
```diff
-    argsman.AddArg("-prune=<n>", strprintf("Reduce storage requirements by enabling pruning (deleting) of old blocks. This allows the pruneblockchain RPC to be called to delete specific blocks, and enables automatic pruning of old blocks if a target size in MiB is provided. This mode is incompatible with -txindex and -coinstatsindex. "
+    argsman.AddArg("-prune=<n>", strprintf("Reduce storage requirements by enabling pruning (deleting) of old blocks. This allows the pruneblockchain RPC to be called to delete specific blocks, and enables automatic pruning of old blocks if a target size in MiB is provided. This mode is incompatible with -txindex, -coinstatsindex, and -reindex-chainstate. "
```

**Comment by jonatack** [comment]
Approach ACK

File: src/init.cpp (hunk 2 above)
Comment (mzumsande) [reply src/init.cpp:863]: Hmm, can you imagine a situation where this would help anyone? In contrast to the index options, `-reindex-chainstate` doesn't enable some additional optional feature, but is a one-time measure to recover when from a corrupted chainstate. So I would think at the point where you chose to enable pruning, you probably don't care or need to know about `reindex-chainstate` at all. Or is the general strategy to list all interactions for completeness?

File: src/init.cpp (hunk 1 above)
Comment (mzumsande) [reply src/init.cpp:862]: done

**Comment by MarcoFalke** [comment]
cr ACK 4be1e1dab94bcbf30a7ffcfb036be0fe62872f82

File: src/init.cpp [hunk 3]
```diff
@@ -853,12 +853,15 @@ bool AppInitParameterInteraction(const ArgsManager& args)
         nLocalServices = ServiceFlags(nLocalServices | NODE_COMPACT_FILTERS);
     }
 
-    // if using block pruning, then disallow txindex and coinstatsindex
+    // if using block pruning, then disallow txindex and coinstatsindex and reindex-chainstate
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/init.cpp:856]: Actually I think it could make sense to remove it here. Looks like #24539 forgot to update the comment, so one option would be to go through the pain of updating #24539 (and causing more merge conflicts), or the other option to just remove it? wdyt?

**Comment by MarcoFalke** [comment]
cr ACK b2813980b81034ff9b40bd45080fa67dea475d39

File: src/init.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (mzumsande) [reply src/init.cpp]: Makes sense, I removed it - I agree that it is self-explanatory and only leads to merge conflicts.
