### PR TITLE
refactor: Fix "modernize-use-starts-ends-with" clang-tidy warning

### LINKED ISSUE #124: Tidy error on Bitcoin Core CI
```
[22:21:15.870] /ci_container_base/src/ipc/process.cpp:75:17: error: use starts_with instead of compare() == 0 [modernize-use-starts-ends-with,-warnings-as-errors]
[22:21:15.870]    75 |     if (address.compare(0, 4, "unix") == 0 && (address.size() == 4 || address[4] == ':')) {
[22:21:15.870]       |                 ^~~~~~~~~~~~~       ~~~~~~
[22:21:15.870]       |                 starts_with(        )
[22:21:15.870] 850 warnings generated.
[22:21:15.870] 
[22:21:15.870] ^^^ ⚠️ Failure generated from clang-tidy
```

https://github.com/bitcoin/bitcoin/pull/30975/checks?check_run_id=34105951022

### PR DESCRIPTION
**Pull request by hebasto**
This PR is a follow-up to #31306 and fixes the "modernize-use-starts-ends-with" warning in the multiprocess code (see https://github.com/bitcoin/bitcoin/pull/30975#issuecomment-2527008761).

Fixes https://github.com/chaincodelabs/libmultiprocess/issues/124.

### CODE REVIEW

File: src/ipc/process.cpp [hunk 1]
```diff
@@ -72,7 +72,7 @@ static bool ParseAddress(std::string& address,
                   struct sockaddr_un& addr,
                   std::string& error)
 {
-    if (address.compare(0, 4, "unix") == 0 && (address.size() == 4 || address[4] == ':')) {
+    if (address.starts_with("unix") && (address.size() == 4 || address[4] == ':')) {
```
Comment (l0rinc) [inline src/ipc/process.cpp:75]: I think we can simplify this further:
```suggestion
    if (address == "unix" || address.starts_with("unix:")) {
```

**Review by l0rinc — CHANGES_REQUESTED** [review]

File: src/ipc/process.cpp (hunk 1 above)
Comment (hebasto) [reply src/ipc/process.cpp]: The suggestion has been accepted.

**Review by theuni — APPROVED** [review]
utACK df27ee9f024f69a8bdac8b0ee3bd7882f6a54294

This is much more readable too :)

**Review by ryanofsky — APPROVED** [review]
Code review ACK df27ee9f024f69a8bdac8b0ee3bd7882f6a54294
