### PR TITLE
Fix locking on WSL using flock instead of fcntl

### LINKED ISSUE #18622: Multiple bitcoind instances can point to the same -walletdir on Windows
I was building Bitcoin Core on my Windows machine, on WSL/Ubuntu. I tried to run the tests and ran into a problem. The test in `test/functional/wallet_multiwallet.py` failed. Follows the output of the test: 

```
mtrycz@LAPTOP-00AACAV2:~/git/bitcoin/test/functional$ ./test_runner.py wallet_multiwallet.py
Temporary test directory at /tmp/test_runner_₿_🏃_20200413_152720
Remaining jobs: [wallet_multiwallet.py]
1/1 - wallet_multiwallet.py failed, Duration: 9 s

stdout:
2020-04-13T13:27:20.407000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0
2020-04-13T13:27:24.947000Z TestFramework (INFO): Do not allow -zapwallettxes with multiwallet
2020-04-13T13:27:25.745000Z TestFramework (INFO): Do not allow -salvagewallet with multiwallet
2020-04-13T13:27:26.278000Z TestFramework (INFO): Do not allow -upgradewallet with multiwallet
2020-04-13T13:27:29.060000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/mtrycz/git/bitcoin/test/functional/test_framework/test_framework.py", line 112, in main
    self.run_test()
  File "/home/mtrycz/git/bitcoin/test/functional/wallet_multiwallet.py", line 152, in run_test
    self.nodes[1].assert_start_raises_init_error(['-walletdir=' + competing_wallet_dir], exp_stderr, match=ErrorMatch.PARTIAL_REGEX)
  File "/home/mtrycz/git/bitcoin/test/functional/test_framework/test_node.py", line 460, in assert_start_raises_init_error
    self._raise_assertion_error(assert_msg)
  File "/home/mtrycz/git/bitcoin/test/functional/test_framework/test_node.py", line 157, in _raise_assertion_error
    raise AssertionError(self._node_msg(msg))
AssertionError: [node 1] bitcoind should have exited with expected error Error: Error initializing wallet database environment \"\S+competing_walletdir\"!
2020-04-13T13:27:29.113000Z TestFramework (INFO): Stopping nodes
2020-04-13T13:27:29.215000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0
2020-04-13T13:27:29.215000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0/test_framework.log
2020-04-13T13:27:29.215000Z TestFramework (ERROR): Hint: Call /home/mtrycz/git/bitcoin/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0' to consolidate all logs


stderr:



TEST                  | STATUS    | DURATION

wallet_multiwallet.py | ✖ Failed  | 9 s

ALL                   | ✖ Failed  | 9 s (accumulated)
Runtime: 9 s
```

I traced the cause to a node being able to open a wallet that is already open by another node. 

To the best of my understanding mutliple bitcoind instances shouldn't be able to point to the same datadirs or walletdirs. On Windows it is possible to have multiple bitcoind instances to point to the same walletdir, leading to possible data corruption. To the best of my understanding this is not possible on Linux (can't confirm atm).

Manual test plan:
1. Download the latest Windows release binaries (version v.0.19.1)
1. Create two directories, for example `C:\node0` and `C:\node1`; create a `bitcoin.conf` file in `C:\node1` with a single line `rpcport=8333` (otherwise the second node will fail for an unrelated reason)
1. Open a command prompt and run `bitcoind.exe -datadir=C:\node0 -walletdir=D:\bchwallettest`
2. Open a second prompt and run `bitcoind.exe -datadir=C:\node1 -walletdir=D:\bchwallettest`
3. Expect the second node to fail at startup

I've run this test myself and can confirm that the second node erroneously starts. The bug was reproduced on Windows 10 Pro, both in cmd and in WSL shell, with the latest release v.0.19.1.

### PR DESCRIPTION
**Pull request by meshcollider**
Fixes #18622

A bug in WSL means that fcntl does not exclusively lock files, allowing multiple instances of bitcoin to use the same datadir. If we instead use flock, it works correctly. Passes Travis, but testing on some OS variety would be sensible.

From what I can tell, flock and fcntl don't work with each other on linux, so it would still be possible to run a node with this code change and a node before it with the same datadir (this isn't true for Mac/FreeBSD). flock also doesn't support NFS on MacOS and linux<2.6.12 while fcntl did. See here for example: https://gavv.github.io/articles/file-locks/

If changing to flock for all systems is inadvisable, it would also be possible to just detect WSL and use flock when on that platform to avoid the bug.

### CODE REVIEW

**Comment by laanwj** [comment]
If this is a bug in WSL, why not wait for them to fix it instead? I don't think it's desirable to change our handling of locks on all UNIX platforms just for a bug in their implementation. If we need is, please add it for WSL only and add a comment that it can be removed again when the upstream bug is fixed.

**Comment by laanwj** [comment]
Can you please test that this fixes your issue @mtrycz.

**Comment by meshcollider** [comment]
@wumpus the bug was reported upstream in 2017 with no fix in sight, so it seems it is up to us

**Comment by mtrycz** [comment]
I've ran my test plan (from the related issue), and I can confirm that the test fails in the latest master `9e8e813d` and the `v0.19.1` tag, and that it passes in this Pull Request.

**Comment by wumpus** [comment]
Github @wumpus is not bitcoin wumpus.

File: src/fs.cpp [hunk 1]
```diff
@@ -52,15 +55,26 @@ bool FileLock::TryLock()
...
-    lock.l_whence = SEEK_SET;
-    lock.l_start = 0;
-    lock.l_len = 0;
-    if (fcntl(fd, F_SETLK, &lock) == -1) {
-        reason = GetErrorReason();
-        return false;
+    // Exclusive file locking is broken on WSL using fcntl (issue #18622)
+    // This workaround can be removed once the bug on WSL is fixed
+    struct utsname uname_data;
+    if (uname(&uname_data) == 0 && std::string(uname_data.version).find("Microsoft") != std::string::npos) {
```
Comment (sipa) [inline src/fs.cpp:61]: This condition should probably be cached in a static bool local variable.

Comment (meshcollider) [reply src/fs.cpp:61]: @sipa it isn't "win32" because its the linux subsystem, so it runs in the non-windows branch

Comment (sipa) [reply src/fs.cpp:61]: Ugh.

**Comment by mtrycz** [comment]
I have ran `test/functional/test_runner.py` several times both on master and this PR. 

The specific issue is solved for WSL on this PR's code. 

There are also several test failures (on both branches) that are reproducible, and some that are non-deterministic. If this sounds new, should I open a new issue with this?

File: src/fs.cpp (hunk 1 above)
Comment (sipa) [reply src/fs.cpp:61]: Still, please cache the result.

File: src/fs.cpp [hunk 2]
```diff
@@ -52,15 +55,35 @@ bool FileLock::TryLock()
...
-    lock.l_start = 0;
-    lock.l_len = 0;
-    if (fcntl(fd, F_SETLK, &lock) == -1) {
-        reason = GetErrorReason();
-        return false;
+
+    // Exclusive file locking is broken on WSL using fcntl (issue #18622)
+    // This workaround can be removed once the bug on WSL is fixed
+    // Cache the result to avoid multiple system calls
+    static bool is_wsl_cache_exists = false;
```
Comment (sipa) [inline src/fs.cpp:62]: It's a crazy edge case, and unlikely on realistic platforms, but this is technically UB if two threads simultaneously reach the `if (!is_wsl_cache_exists)` check. The most C++ish solution is this I think: https://github.com/sipa/bitcoin/commit/9470c59e7290774972f94250d04caae161bc7678.

**Comment by luke-jr** [comment]
Is there any reason we can't check/take both locks?

**Comment by meshcollider** [comment]
Thanks @sipa, updated :)

**Comment by laanwj** [comment]
I'm removing this from the 0.20.0 milestone. It's not a regression in 0.20, it's an upstream bug in "Linux emulation", and I think this fix is not quite ready yet.

**Comment by laanwj** [comment]
Code review ACK e8fa0a3d2025509fcddc59fc618e91371542cf87

File: src/fs.cpp [hunk 3]
```diff
@@ -47,20 +50,38 @@ FileLock::~FileLock()
     }
 }
 
+static bool IsWSL()
```
Comment (laanwj) [inline src/fs.cpp:53]: I just realized after merging that we could shortcut this check to `false` on non-x86 platforms. But it doesn't matter too much.

**Comment by MarcoFalke** [comment]
Tagged with " Needs backport (0.20) "

**Comment by cculianu** [comment]
Note that this patch only answers the question `IsWSL?` for WSL ver 1.  Ver 2 returns a totally different `uts_name.version` string as such:

**WSL2 uts_name.version string:** `#1 SMP Wed Feb 19 06:37:35 UTC 2020`

```bash
$ uname -a
Linux DESKTOP-TPEL8HN 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I am running on Win10 WSL2 with Ubuntu 20.04.  See the attached C++ test program to convince yourself.

```c++
#include <iostream>
#include <string>

#include <sys/file.h>
#include <sys/utsname.h>

static bool IsWSL(std::string *out = nullptr) {
	struct utsname uname_data;
	auto res = uname(&uname_data);
	std::string ver{uname_data.version};
	bool ret = res == 0 && ver.find("Microsoft") != std::string::npos;
	if (out) *out = std::move(ver);
	return ret;
}

int main()
{
	using std::cout;

	std::string ver;
	auto b = IsWSL(&ver);
	cout << "Ver: " << ver << '\n';
	cout << "IsWSL?: " << b << '\n';
	return 0;
}
```

---

I don't know if the bug #18622 is still an issue on WSL2.  I'm going to try and determine this and write back here when I do.

**Comment by cculianu** [comment]
Follow-up: Can confirm that the upstream bug from microsoft on `fcntl` `F_SETLK` is fixed on WSL2.  The linux/unix execution path that is taken on WSL2 (because `IsWSL()` returns false here leads to correct behavior and the lock succeeds.

Suggest: Rename this function to `IsWSL1` to make it clearer when it will return true and/or add a comment to that effect...
