### PR TITLE
random: fix crash on some 64bit platforms

### LINKED ISSUE #10611: Gitian build (current master) crashes on OSX
Nighly build from 2017-06-15 crashes (https://bitcoin.jonasschnelli.ch/build/176)
Nighy build from 2017-06-14 works fine (https://bitcoin.jonasschnelli.ch/build/175)

Relevant commit must be between 228c319a and fbf5d3ba.

```shell
jonasschnelli@Jonass-MBP:~/Documents/bitcoin/bitcoin$ ~/Downloads/bitcoin-0.14.n/bin/bitcoind --regtest
Abort trap: 6
jonasschnelli@Jonass-MBP:~/Documents/bitcoin/bitcoin$ lldb ~/Downloads/bitcoin-0.14.n/bin/bitcoind
(lldb) target create "/Users/jonasschnelli/Downloads/bitcoin-0.14.n/bin/bitcoind"
Current executable set to '/Users/jonasschnelli/Downloads/bitcoin-0.14.n/bin/bitcoind' (x86_64).
(lldb) run --regtest
Process 29763 launched: '/Users/jonasschnelli/Downloads/bitcoin-0.14.n/bin/bitcoind' (x86_64)
Process 29763 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff94f74d42 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff94f74d42 <+10>: jae    0x7fff94f74d4c            ; <+20>
    0x7fff94f74d44 <+12>: movq   %rax, %rdi
    0x7fff94f74d47 <+15>: jmp    0x7fff94f6dcaf            ; cerror_nocancel
    0x7fff94f74d4c <+20>: retq   
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff94f74d42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff950625bf libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff94eda4bb libsystem_c.dylib`__abort + 140
    frame #3: 0x00007fff94edad7e libsystem_c.dylib`__stack_chk_fail + 205
    frame #4: 0x0000000100270364 bitcoind`___lldb_unnamed_symbol4989$$bitcoind + 228
    frame #5: 0x0000000100046660 bitcoind`___lldb_unnamed_symbol475$$bitcoind + 32
    frame #6: 0x0000000100003be9 bitcoind`___lldb_unnamed_symbol1$$bitcoind + 2665
    frame #7: 0x00000001000042a1 bitcoind`___lldb_unnamed_symbol2$$bitcoind + 49
    frame #8: 0x00007fff94e46235 libdyld.dylib`start + 1
(lldb) 
```

### PR DESCRIPTION
**Pull request by theuni**
Fixes #10611. Credit @sipa.

rbx needs to be stashed in a 64bit register on 64bit platforms. With this crash in particular, it was holding a stack canary which was not properly restored after the cpuid.

Split out the x86+PIC case so that x86_64 doesn't have to worry about it.

### CODE REVIEW

**Comment by sipa** [comment]
utACK b9b87481fd69e5caa15f580a19a5e0a58ad5f6a6

File: src/random.cpp [hunk 1]
```diff
@@ -73,9 +73,15 @@ static constexpr uint32_t CPUID_F1_ECX_RDRAND = 0x40000000;
 static void RDRandInit()
 {
     //! When calling cpuid function #1, ecx register will have this set if RDRAND is available.
```
Comment (sipa) [inline src/random.cpp]: While you're at it, can you move this comment down to after the #endif? It's intended to clarify the CPUID_F1_ECX_RDRAND constant.

Comment (theuni) [inline src/random.cpp]: Done

**Comment by jonasschnelli** [comment]
tested ACK 9af207c810b5c4b09ccbdec75582b3e34e32e8cc (OSX 10.12 only) full static build via gitian: https://bitcoin.jonasschnelli.ch/build/181
Confirmed that it fixes #10611

**Comment by sipa** [comment]
utACK 9af207c810b5c4b09ccbdec75582b3e34e32e8cc

**Comment by sipa** [comment]
> Fixes #10611. Credit @sipa.

You can also add a blame for introducing the bug in the first place.

**Review by gmaxwell — APPROVED** [review]
utACK
