### PR TITLE
psbt: check that various indexes and amounts are within bounds

### LINKED ISSUE #17149: Potential PSBT issues found by the PSBT fuzzer
Potential PSBT issues found by the PSBT fuzzer (#17136):

```
$ src/test/fuzz/psbt
…
==8112==ERROR: AddressSanitizer: heap-use-after-free on address 0x6070001083f0 at pc 0x55a5d650f41b bp 0x7ffe03cc3c90 sp 0x7ffe03cc3c88
READ of size 8 at 0x6070001083f0 thread T0
    #0 0x55a5d650f41a in CTxOut::operator=(CTxOut const&) src/./primitives/transaction.h:133:7
    #1 0x55a5d8362e8d in PartiallySignedTransaction::GetInputUTXO(CTxOut&, int) const src/psbt.cpp:72:14
    #2 0x55a5d6dae419 in AnalyzePSBT(PartiallySignedTransaction) src/node/psbt.cpp:32:19
    #3 0x55a5d64b27d7 in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) src/test/fuzz/psbt.cpp:28:35
…

$ src/test/fuzz/psbt
…
AddressSanitizer:DEADLYSIGNAL
=================================================================
==22238==ERROR: AddressSanitizer: SEGV on unknown address 0x6098001079e0 (pc 0x55880d55c50f bp 0x7fff8d03d8f0 sp 0x7fff8d03d860 T0)
==22238==The signal is caused by a READ memory access.
    #0 0x55880d55c50e in CTxOut::operator=(CTxOut const&) src/./primitives/transaction.h:133:7
    #1 0x55880f3b6a83 in SignPSBTInput(SigningProvider const&, PartiallySignedTransaction&, int, int, SignatureData*, bool) src/psbt.cpp:262:14
    #2 0x55880f3b81ff in FinalizePSBT(PartiallySignedTransaction&) src/psbt.cpp:311:21
    #3 0x55880d500ee9 in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) src/test/fuzz/psbt.cpp:62:11
…

$ src/test/fuzz/psbt
…
node/psbt.cpp:82:26: runtime error: signed integer overflow: 7857790368227518552 + 6582955728264977243 cannot be represented in type 'long'
    #0 0x55a8b66b13ee in AnalyzePSBT(PartiallySignedTransaction)::$_0::operator()(long, CTxOut const&) const src/node/psbt.cpp:82:26
    #1 0x55a8b66b1043 in long std::accumulate<__gnu_cxx::__normal_iterator<CTxOut*, std::vector<CTxOut, std::allocator<CTxOut> > >, long, AnalyzePSBT(PartiallySignedTransaction)::$_0>(__gnu_cxx::__normal_iterator<CTxOut*, std::vector<CTxOut, std::allocator<CTxOut> > >, __gnu_cxx::__normal_iterator<CTxOut*, std::vector<CTxOut, std::allocator<CTxOut> > >, long, AnalyzePSBT(PartiallySignedTransaction)::$_0) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_numeric.h:154:11
    #2 0x55a8b66aeecf in AnalyzePSBT(PartiallySignedTransaction) src/node/psbt.cpp:80:27
    #3 0x55a8b5db1a17 in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) src/test/fuzz/psbt.cpp:28:35
…

$ src/test/fuzz/psbt
…
policy/feerate.cpp:18:34: runtime error: signed integer overflow: -7497025602362688435 * 1000 cannot be represented in type 'long'
    #0 0x5587f480b863 in CFeeRate::CFeeRate(long const&, unsigned long) src/policy/feerate.cpp:18:34
    #1 0x5587f327051f in AnalyzePSBT(PartiallySignedTransaction) src/node/psbt.cpp:116:22
    #2 0x5587f2971ac7 in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) src/test/fuzz/psbt.cpp:28:35
…
```

### PR DESCRIPTION
**Pull request by achow101**
Fixes #17149

Two classes of issues were found by the psbt fuzzer: values out of range and causing overflows, and prevout indexes being out of range. This PR fixes both.

When accessing a specific output using the index given in the tx, check that it is actually a possible output before trying to access the output.

When summing and checking amounts for `decodepsbt` and `analyzepsbt`, make sure that the values are actually valid money values.. Otherwise, stop summing and don't show the fee. For `analyzepsbt`, return that the next role is the Creator since the Creator needs to remake the transaction to be valid.

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for addressing this issue quickly! :) Will test.

**Comment by practicalswift** [comment]
With this patch applied the PSBT fuzzer appears to be unable to trigger the problematic conditions listed in the issue #17149.

However, I noticed that using the following 202 byte input:

```
70736274ff01009a020000000258e87a21b56daf0c23be8e7070456c336f
7cbaa5c8757924f545887bb282dd750000000000ffffffff838d0427d0ec
650a68aa46bb0b098aea4422c071b2ca78352a077959d07cea1d01000000
00ffffffff0270aaf00800000000160014d85c2b71d0060b09c9886aeb81
5e50991dda124d00e1f5050000000016001400aea9a2e5f0f876a588df55
46e8742d202020ffff603016000001012000c2eb0b000000001714a9b7f5
faff09090010610000db2a077959d07cea1d01000000
```

The following UBSan condition is triggered:

```
prevector.h:452:19: runtime error: reference binding to misaligned address 0x7fff2c5dc562 for type 'prevector<28, unsigned char, unsigned int, int>::size_type' (aka 'unsigned int'), which requires 4 byte alignment
0x7fff2c5dc562: note: pointer points here
 ff ff  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00
              ^
    #0 0x56183e4f724f in prevector<28u, unsigned char, unsigned int, int>::swap(prevector<28u, unsigned char, unsigned int, int>&) src/./prevector.h:452:9
    #1 0x56183e4ec6fa in prevector<28u, unsigned char, unsigned int, int>::operator=(prevector<28u, unsigned char, unsigned int, int>&&) src/./prevector.h:272:9
    #2 0x56183e4ec6fa in CScript::operator=(CScript&&) src/./script/script.h:390
    #3 0x56183f407fa9 in ProduceSignature(SigningProvider const&, BaseSignatureCreator const&, CScript const&, SignatureData&) src/script/sign.cpp:240:23
    #4 0x56183f30c8a3 in SignPSBTInput(SigningProvider const&, PartiallySignedTransaction&, int, int, SignatureData*, bool) src/psbt.cpp:285:24
    #5 0x56183e7eb0e8 in AnalyzePSBT(PartiallySignedTransaction) src/node/psbt.cpp:54:29
    #6 0x56183e393014 in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) src/test/fuzz/psbt.cpp:28:35
…
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prevector.h:452:19 in
```

Might be worth tackling that one as well?

**Comment by achow101** [comment]
What do I need to run in order to get the same error?

**Comment by MarcoFalke** [comment]
Something like this:

```
#check out this branch
./configure --disable-ccache --enable-fuzz --with-sanitizers=fuzzer,address,undefined CC=clang CXX=clang++
make -j 9
export LSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/lsan"
export TSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/tsan"
export UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1"
#run this fuzzer with the seed
./src/test/fuzz/this_fuzzer -runs=1 ./the_input

**Comment by MarcoFalke** [comment]
Not sure how to translate the base16 seed into a binary seed with the command line, though

**Comment by practicalswift** [comment]
@MarcoFalke 

```
$ xxd -r -p > seed <<< "70736274ff01009a020000000258e87a21b56daf0c23be8e7070456c336f
7cbaa5c8757924f545887bb282dd750000000000ffffffff838d0427d0ec
650a68aa46bb0b098aea4422c071b2ca78352a077959d07cea1d01000000
00ffffffff0270aaf00800000000160014d85c2b71d0060b09c9886aeb81
5e50991dda124d00e1f5050000000016001400aea9a2e5f0f876a588df55
46e8742d202020ffff603016000001012000c2eb0b000000001714a9b7f5
faff09090010610000db2a077959d07cea1d01000000"
$ head -c4 seed
psbt
```

:)

**Comment by practicalswift** [comment]
@achow101 

```
$ CC=clang CXX=clang++ ./configure --enable-fuzz \
      --with-sanitizers=address,fuzzer,undefined
$ make
$ mkdir psbt-seeds/
$ xxd -r -p > psbt-seeds/seed <<< "70736274ff01009a020000000258e87a21b56daf0c23be8e7070456c336f
7cbaa5c8757924f545887bb282dd750000000000ffffffff838d0427d0ec
650a68aa46bb0b098aea4422c071b2ca78352a077959d07cea1d01000000
00ffffffff0270aaf00800000000160014d85c2b71d0060b09c9886aeb81
5e50991dda124d00e1f5050000000016001400aea9a2e5f0f876a588df55
46e8742d202020ffff603016000001012000c2eb0b000000001714a9b7f5
faff09090010610000db2a077959d07cea1d01000000"
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1" src/test/fuzz/psbt psbt-seeds/
…
prevector.h:452:19: runtime error: reference binding to misaligned address 0x7fff2c5dc562 for type 'prevector<28, unsigned char, unsigned int, int>::size_type' (aka 'unsigned int'), which requires 4 byte alignment
0x7fff2c5dc562: note: pointer points here
 ff ff  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00
              ^
    #0 0x56183e4f724f in prevector<28u, unsigned char, unsigned int, int>::swap(prevector<28u, unsigned char, unsigned int, int>&) src/./prevector.h:452:9
    #1 0x56183e4ec6fa in prevector<28u, unsigned char, unsigned int, int>::operator=(prevector<28u, unsigned char, unsigned int, int>&&) src/./prevector.h:272:9
    #2 0x56183e4ec6fa in CScript::operator=(CScript&&) src/./script/script.h:390
    #3 0x56183f407fa9 in ProduceSignature(SigningProvider const&, BaseSignatureCreator const&, CScript const&, SignatureData&) src/script/sign.cpp:240:23
    #4 0x56183f30c8a3 in SignPSBTInput(SigningProvider const&, PartiallySignedTransaction&, int, int, SignatureData*, bool) src/psbt.cpp:285:24
    #5 0x56183e7eb0e8 in AnalyzePSBT(PartiallySignedTransaction) src/node/psbt.cpp:54:29
    #6 0x56183e393014 in test_one_input(std::vector<unsigned char, std::allocator<unsigned char> > const&) src/test/fuzz/psbt.cpp:28:35
…
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prevector.h:452:19 in
```

:)

**Comment by achow101** [comment]
I'm not really sure why that happens.

```
diff --git a/src/script/sign.cpp b/src/script/sign.cpp
index 0ed92e8d5b..be24d002ad 100644
--- a/src/script/sign.cpp
+++ b/src/script/sign.cpp
@@ -237,7 +237,11 @@ bool ProduceSignature(const SigningProvider& provider, const BaseSignatureCreato
     if (P2SH) {
         result.push_back(std::vector<unsigned char>(subscript.begin(), subscript.end()));
     }
-    sigdata.scriptSig = PushAll(result);
+    if (result.size() == 0) {
+        sigdata.scriptSig.clear();
+    } else {
+        sigdata.scriptSig = PushAll(result);
+    }
 
     // Test solution
     sigdata.complete = solved && VerifyScript(sigdata.scriptSig, fromPubKey, &sigdata.scriptWitness, STANDARD_SCRIPT_VERIFY_FLAGS, creator.Checker());
```

fixes the problem, but it's more signing code than not. ISTM we should see this elsewhere too but it doesn't seem like it.

**Comment by practicalswift** [comment]
@achow101 

> ISTM we should see this elsewhere too but it doesn't seem like it.

Isn't the difference that the *move* assignment operator is used in this case whereas the other non-warning cases you're referring to use the *copy* assignment operator?

If I'm correct then these two should trigger the UBSan warning:

```
sigdata.scriptSig = PushAll(result);
```

```
CString script_sig = PushAll(result);
sigdata.scriptSig = std::move(script_sig);
```

Whereas this won't trigger the UBSan warning:

```
CString script_sig = PushAll(result);
sigdata.scriptSig = script_sig;
```

Could that be the case?

**Comment by achow101** [comment]
> Isn't the difference that the _move_ assignment operator is used in this case whereas the other non-warning cases you're referring to use the _copy_ assignment operator?

What I meant was that we should see this same error for any fuzzers that hit ProduceSignature. But I think we just don't have any fuzzers that reach ProduceSignature.

**Comment by achow101** [comment]
I've added a commit which adds a copy constructor and copy `operator=` to `CScript` which fixes the UBSan warning.

**Comment by practicalswift** [comment]
@achow101 Good! Then we should be able to get rid of this UBSan suppression? :)

https://github.com/bitcoin/bitcoin/blob/b8f041af2d2c89afdc14f8c632dfb7fecb535cb5/test/sanitizer_suppressions/ubsan#L2

**Comment by practicalswift** [comment]
Judging from my testing we can get rid of both these UBSan suppressions as part of this PR:

https://github.com/bitcoin/bitcoin/blob/b8f041af2d2c89afdc14f8c632dfb7fecb535cb5/test/sanitizer_suppressions/ubsan#L1-L2

Great!

File: src/script/script.h [hunk 1]
```diff
@@ -411,6 +411,7 @@ class CScript : public CScriptBase
     CScript(const_iterator pbegin, const_iterator pend) : CScriptBase(pbegin, pend) { }
     CScript(std::vector<unsigned char>::const_iterator pbegin, std::vector<unsigned char>::const_iterator pend) : CScriptBase(pbegin, pend) { }
     CScript(const unsigned char* pbegin, const unsigned char* pend) : CScriptBase(pbegin, pend) { }
+    CScript(const CScript& a) : CScript(a.begin(), a.end()) {}
```
Comment (laanwj) [inline src/script/script.h]: Might want to add a comment describing why this explicit copy constructor (which seems to be redundant) was added, otherwise it might be removed again with the next 'clean up warnings' PR.

Comment (practicalswift) [reply src/script/script.h]: Agreed! That is also why it is important to remove the UBSan suppressions as part of this PR: to catch the consequence non-refactoring nature of such a mistaken change :)

These needs to go:

https://github.com/bitcoin/bitcoin/blob/b8f041af2d2c89afdc14f8c632dfb7fecb535cb5/test/sanitizer_suppressions/ubsan#L1-L2

**Comment by practicalswift** [comment]
@achow101 Can you remove the UBSan suppressions? That will allow Travis to confirm that you've solved the alignment issue. Then this PR should be ready to go AFAICT.

@fanquake Would you mind adding waiting for author-tag? :)

File: src/psbt.cpp [hunk 2]
```diff
@@ -69,6 +69,9 @@ bool PartiallySignedTransaction::GetInputUTXO(CTxOut& utxo, int input_index) con
     PSBTInput input = inputs[input_index];
     int prevout_index = tx->vin[input_index].prevout.n;
     if (input.non_witness_utxo) {
+        if (prevout_index >= input.non_witness_utxo->vout.size()) {
```
Comment (practicalswift) [inline src/psbt.cpp]: I'm afraid this will trigger a sign-compare warning when compiling with Clang due to LHS being `int` and the RHS being `unsigned long` (`size_t`).

File: src/script/script.h (hunk 1 above)
Comment (achow101) [reply src/script/script.h]: Added a comment and removed the suppressions.

File: src/psbt.cpp (hunk 2 above)
Comment (achow101) [reply src/psbt.cpp]: Fixed

**Comment by practicalswift** [comment]
ACK db30e5bd6fb51913a4ce2177097be3ebcabab146 assuming Travis is happy too -- diff looks correct

File: src/node/psbt.cpp [hunk 3]
```diff
@@ -79,9 +84,16 @@ PSBTAnalysis AnalyzePSBT(PartiallySignedTransaction psbtx)
         // Get the output amount
         CAmount out_amt = std::accumulate(psbtx.tx->vout.begin(), psbtx.tx->vout.end(), CAmount(0),
             [](CAmount a, const CTxOut& b) {
+                if (!MoneyRange(a) || !MoneyRange(b.nValue) || !MoneyRange(a + b.nValue)) {
+                    return CAmount(-1);
+                }
```
Comment (MarcoFalke) [inline src/node/psbt.cpp]: Are you sure this is correct? This will reset the intermediate result to -1, and then accumulate all remaining values.

Comment (achow101) [reply src/node/psbt.cpp]: -1 will fail MoneyRange so later values that go through this will also always return -1.

Comment (MarcoFalke) [reply src/node/psbt.cpp]: Correct. Thx.

File: src/script/script.h [hunk 4]
```diff
@@ -412,6 +412,9 @@ class CScript : public CScriptBase
     CScript(std::vector<unsigned char>::const_iterator pbegin, std::vector<unsigned char>::const_iterator pend) : CScriptBase(pbegin, pend) { }
     CScript(const unsigned char* pbegin, const unsigned char* pend) : CScriptBase(pbegin, pend) { }
 
+    // Define a copy constructor so that operator= is a copy instead of a move to avoid undefined behavior
```
Comment (MarcoFalke) [inline src/script/script.h]: could explain how this would otherwise be undefined behavior and why this can't be fixed in `prevector.h`?

Comment (achow101) [reply src/script/script.h]: I'm not sure why it would be undefined behavior,  but UBSan was triggering on it. I think prevector already has a copy constructor?

Comment (MarcoFalke) [reply src/script/script.h]: In that case I'd prefer to leave the third commit for a separate pull request. Changing those parts of the code without understanding why for the sole reason to please a sanitizer seems worrisome

Comment (achow101) [reply src/script/script.h]: I've dropped the commit.

**Comment by practicalswift** [comment]
ACK a2800d704870cf120127a98769ed97b06c35042e -- diff looks correct

File: src/node/psbt.cpp [hunk 5]
```diff
@@ -85,9 +90,16 @@ PSBTAnalysis AnalyzePSBT(PartiallySignedTransaction psbtx)
...
                 return a += b.nValue;
             }
         );
+        if (out_amt == -1) {
```
Comment (promag) [inline src/node/psbt.cpp]: e769f25031a63c378f2efeb957b90a72a8524a5e

Also use `!MoneyRange(out_amt)`?

File: src/node/psbt.h [hunk 6]
```diff
@@ -41,6 +41,14 @@ struct PSBTAnalysis {
         next = PSBTRole::CREATOR;
         error = err_msg;
     }
+
+    void Reset() {
```
Comment (promag) [inline src/node/psbt.h]: e769f25031a63c378f2efeb957b90a72a8524a5e

nit, `{` in new line?

File: src/node/psbt.cpp [hunk 7]
```diff
@@ -31,6 +32,10 @@ PSBTAnalysis AnalyzePSBT(PartiallySignedTransaction psbtx)
         // Check for a UTXO
         CTxOut utxo;
         if (psbtx.GetInputUTXO(utxo, i)) {
+            if (!MoneyRange(in_amt) || !MoneyRange(utxo.nValue) || !MoneyRange(in_amt + utxo.nValue)) {
+                result.Reset();
+                return result;
```
Comment (promag) [inline src/node/psbt.cpp]: e769f25031a63c378f2efeb957b90a72a8524a5e

Why not `return {};` instead of `Reset`? Same below, and then drop `PSBTAnalysis::Reset()`.

File: src/rpc/rawtransaction.cpp [hunk 8]
```diff
@@ -1203,7 +1214,12 @@ UniValue decodepsbt(const JSONRPCRequest& request)
         outputs.push_back(out);
 
         // Fee calculation
-        output_value += psbtx.tx->vout[i].nValue;
+        if (MoneyRange(output_value) && MoneyRange(psbtx.tx->vout[i].nValue) && MoneyRange(output_value + psbtx.tx->vout[i].nValue)) {
```
Comment (promag) [inline src/rpc/rawtransaction.cpp]: e769f25031a63c378f2efeb957b90a72a8524a5e

Unnecessary check `MoneyRange(output_value)` - starts with zero and next value is already checked. Same with `total_in`.

File: src/node/psbt.cpp [hunk 9]
```diff
@@ -31,6 +32,9 @@ PSBTAnalysis AnalyzePSBT(PartiallySignedTransaction psbtx)
         // Check for a UTXO
         CTxOut utxo;
         if (psbtx.GetInputUTXO(utxo, i)) {
+            if (!MoneyRange(in_amt) || !MoneyRange(utxo.nValue) || !MoneyRange(in_amt + utxo.nValue)) {
```
Comment (promag) [inline src/node/psbt.cpp]: Drop first check, same below.

File: src/node/psbt.cpp (hunk 5 above)
Comment (achow101) [reply src/node/psbt.cpp]: Done

File: src/node/psbt.h (hunk 6 above)
Comment (achow101) [reply src/node/psbt.h]: Removed Reset

File: src/node/psbt.cpp (hunk 7 above)
Comment (achow101) [reply src/node/psbt.cpp]: Removed Reset

File: src/rpc/rawtransaction.cpp (hunk 8 above)
Comment (achow101) [reply src/rpc/rawtransaction.cpp]: Done

File: src/node/psbt.cpp (hunk 9 above)
Comment (achow101) [reply src/node/psbt.cpp]: Done, but the check below is necessary. It's how the accumulator is guaranteed to return -1.

**Comment by achow101** [comment]
I've added some more to this.

I've added a couple of tests. In doing so, I also found a few additional places that we needed checks.

Additionally, I've replaced the `Reset` calls with the new `SetInvalid` so that we can return proper errors.

**Comment by practicalswift** [comment]
ACK 2dd91b86cd7ef09fa3ae280bfe99db8cfb6fe531 -- diff looks correct

File: src/node/psbt.cpp (hunk 9 above)
Comment (promag) [reply src/node/psbt.cpp]: > but the check below is necessary.

Oh yeah sorry.

File: src/psbt.cpp [hunk 10]
```diff
@@ -66,8 +66,11 @@ bool PartiallySignedTransaction::AddOutput(const CTxOut& txout, const PSBTOutput
 bool PartiallySignedTransaction::GetInputUTXO(CTxOut& utxo, int input_index) const
 {
     PSBTInput input = inputs[input_index];
```
Comment (Sjors) [inline src/psbt.cpp]: nit: `inputs.at(input_index)`

File: src/node/psbt.cpp [hunk 11]
```diff
@@ -31,9 +32,17 @@ PSBTAnalysis AnalyzePSBT(PartiallySignedTransaction psbtx)
...
         CTxOut utxo;
         if (psbtx.GetInputUTXO(utxo, i)) {
+            if (!MoneyRange(utxo.nValue) || !MoneyRange(in_amt + utxo.nValue)) {
+                result.SetInvalid(strprintf("PSBT is not valid. Input %u has invalid value", i));
+                return result;
+            }
             in_amt += utxo.nValue;
             input_analysis.has_utxo = true;
         } else {
+            if (input.non_witness_utxo && psbtx.tx->vin[i].prevout.n >= input.non_witness_utxo->vout.size()) {
```
Comment (Sjors) [inline src/node/psbt.cpp]: nit: `vin.at(i)` (also in the `FinalizeAndExtractPSBT` loops)

Comment (achow101) [reply src/node/psbt.cpp]: meh. don't feel like changing

File: src/psbt.cpp (hunk 10 above)
Comment (achow101) [reply src/psbt.cpp]: Unrelated style changes are unrelated

**Comment by practicalswift** [comment]
@Sjors Do you ACK the changes also with the nits unaddressed? If so please consider ACK:ing - it would be good to get this reviewed (and merged).

It bothers me that an RPC call with a malformed PSBT can bring down Bitcoin Core :)

File: src/psbt.cpp (hunk 10 above)
Comment (Sjors) [reply src/psbt.cpp]: It's not a style change, `at` checks these array indexes "are within bounds" and throws an exception otherwise. There's a bunch of places in this code where we don't use iterators and assume that two arrays are the same size.

**Comment by Sjors** [comment]
@practicalswift I haven't reviewed the rest of the code yet. My suggestions for improvements should not hold back merging.

File: src/psbt.cpp (hunk 10 above)
Comment (gwillen) [reply src/psbt.cpp]: Throwing an exception here would actually be rude, yes? So it would be better to establish invariants that ensure we are in-bounds, or else add a bounds check ourselves otherwise?

**Comment by gwillen** [comment]
@achow101 what would you say to the alternate approach of having something like an all-in-one-place PSBT sanity checker? Could be added to IsSane() (which I would prefer), or if you think it might be too heavyweight (but I don't think so), a new method.

Then we can immediately check every PSBT at the point of parsing, and not have to worry thereafter.

If you're amenable, I would be happy to make a candidate CL.

(If you're not amenable, then utACK to this one. But I'm concerned that the piecemeal approach will both clutter the code with checks that are redundant across different methods, AND still miss stuff that we'll have to add more checks for later.)

**Comment by achow101** [comment]
@gwillen I don't think that we should have these checks at parse time. It's useful to have `decodepsbt` be able to decode psbts that are correctly formatted but logically incorrect (as we are doing here). Doing these checks at parse time would mean that `decodepsbt` would fail.

**Comment by gwillen** [comment]
That makes sense. What do you think about having two separate checks -- a basic validity check at parse time, and a more thorough check that can be run before doing anything with the PSBT (other than displaying it as JSON)?

I think it's probably a hazard to allow PSBTs to hang around which have inconsistencies that can lead to e.g. reading off the end of vectors, and count on individual use code paths to check this every time. Even if we fix this specific case, I feel like it's going to hit us again in the future.

**Comment by achow101** [comment]
I think it makes to have a general consistency check for other commands. But I think we should still do error checking like this as a belt-and-suspenders. We could add the general consistency check in another pr.

File: src/psbt.cpp (hunk 10 above)
Comment (promag) [reply src/psbt.cpp]: > establish invariants that ensure we are in-bounds

Agree, I think it makes no sense to add bound checks here.

In any case, here or followup this could use
```
const_reference operator[]( size_type pos ) const;
```
since `PSBTInput` is not that trivial.

**Review by promag — COMMENTED** [review]
Code review ACK 2dd91b86cd7ef09fa3ae280bfe99db8cfb6fe531, also ran the tests. However tests still pass if the new checks `... >= input.non_witness_utxo->vout.size()` are removed.

File: src/psbt.cpp (hunk 10 above)
Comment (gwillen) [reply src/psbt.cpp]: That would just mean changing "PSBTInput input" to "const PSBTInput& input"?

Comment (promag) [reply src/psbt.cpp]: Yes.

**Comment by achow101** [comment]
> However tests still pass if the new checks `... >= input.non_witness_utxo->vout.size()` are removed.

Really? It fails for me. I removed the second commit and kept just the test from it. That test fails.

**Comment by promag** [comment]
Try running the test with
```diff
--- a/src/wallet/psbtwallet.cpp
+++ b/src/wallet/psbtwallet.cpp
@@ -44,9 +44,6 @@ TransactionError FillPSBT(const CWallet* pwallet, PartiallySignedTransaction& ps
         if (!input.witness_utxo.IsNull()) {
             script = input.witness_utxo.scriptPubKey;
         } else if (input.non_witness_utxo) {
-            if (txin.prevout.n >= input.non_witness_utxo->vout.size()) {
-                return TransactionError::MISSING_INPUTS;
-            }
             script = input.non_witness_utxo->vout[txin.prevout.n].scriptPubKey;
         } else {
             // There's no UTXO so we can just skip this now
```
And I think I've tried with another.

**Comment by achow101** [comment]
I've added test cases for the `SignPSBTInput` and `FillPSBT` checks. Since the `SignPSBTInput` check can't be reached via RPC (it gets caught by `FillPSBT` or `AnalyzePSBT`), I added the test case to the `psbt_updater_test` unit test.

**Comment by practicalswift** [comment]
ACK deaa6dd144f5650b385658a0c4f9a014aff8dde2 -- only change since last ACK was the addition of tests

Would be great to have this merged - this PR greatly improves the robustness of the PSBT code :)

**Comment by gwillen** [comment]
tested ACK deaa6dd, would also like to see this merged!

**Comment by practicalswift** [comment]
I really hoped this fix would make it to 0.19.1 :\

It doesn't feel good to ship with a known heap use-after-free bug (see #17149) which is reachable via RPC. 

Now that we that RPC whitelisting is merged (#12763) we no longer have the luxury of assuming that all RPC access is from fully trusted RPC consumers.

Thus the previous "the RPC consumer is also the node operator" assumption that may have allowed us to take RPC flaws somewhat lightly in the past no longer holds in all cases (it may still hold in the case of RPC functions such as `stop` which are unlikely to be whitelisted for non-trusted users) :)

**Comment by promag** [comment]
IMO we should keep recommending trusted clients regardless of their whitelist. I hope RPC whitelisting doesn't give the impression that now the RPC interface can be made public..

**Comment by practicalswift** [comment]
@promag I agree and in an ideal world all users would read and follow our recommendations :)

Unfortunately a non-negligible subset of our users still expose their RPC ports publicly as can be verified empirically by running an Internet-wide TCP port scan using say [`masscan`](https://github.com/robertdavidgraham/masscan) (impressive software: an Internet-wide single-port scan can be as quick as six minutes given a good connection/NIC!) or similar.

One approach to this could be: _"OK, those users screwed up badly. They didn't read our recommendations. Their loss. Not our problem as developers."_

Another could be: _"Oh gosh, that's unfortunate! Let's try to mitigate the effect of that by making the RPC interface reasonably robust and secure also in the presence user screwups."_

The latter approach is certainly more convenient from a _developer_ perspective, but I don't think that approach is in the best interest of our _users_ :)

**Comment by sipa** [comment]
These are not in conflict. We should obviously fix bugs in RPC, even if they only affect careless users (by whatever definition). At the same time, we still shouldn't recommend exposing RPC to the public, because it was not designed for that.

**Comment by practicalswift** [comment]
> We should obviously fix bugs in RPC, even if they only affect careless users (by whatever definition).

Agreed.

Let's get rid of the heap use-after-free bug this PR fixes :)

Please review :)

> At the same time, we still shouldn't recommend exposing RPC to the public, because it was not designed for that.

Agreed.

**Comment by practicalswift** [comment]
Very glad to see this one merged!

We have another PSBT related issued to resolve too: the misaligned pointer use in `ProduceSignature(…)` (via `prevector`). While not PSBT specific the function `ProduceSignature(…)` is reachable from `AnalyzePSBT` (via `SignPSBTInput`):

```
prevector.h:453:19: runtime error: reference binding to misaligned address 0x7f63f89a4022 for type 'prevector<28, unsigned char, unsigned int, int>::size_type' (aka 'unsigned int'), which requires 4 byte alignment
 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00
              ^ 
    #0 0x5652760202ce in prevector<28u, unsigned char, unsigned int, int>::swap(prevector<28u, unsigned char, unsigned int, int>&) src/./prevector.h:453:9
    #1 0x56527601ff0e in prevector<28u, unsigned char, unsigned int, int>::operator=(prevector<28u, unsigned char, unsigned int, int>&&) src/./prevector.h:273:9
    #2 0x56527601ff0e in CScript::operator=(CScript&&) src/./script/script.h:390:7
    #3 0x565276094236 in ProduceSignature(SigningProvider const&, BaseSignatureCreator const&, CScript const&, SignatureData&) src/script/sign.cpp:240:23
    #4 0x565276042ef8 in SignPSBTInput(SigningProvider const&, PartiallySignedTransaction&, int, int, SignatureData*, bool) src/psbt.cpp:285:24
    #5 0x565275fdad45 in AnalyzePSBT(PartiallySignedTransaction) src/node/psbt.cpp:64:29
```

Thus anyone interested in PSBT robustness might want to review #17708 too :)
