### PR TITLE
qt: Add workaround for QProgressDialog bug on macOS

### LINKED ISSUE #15016: [GUI] progress window size
Information in the progress window (example: rescan) is displayed capped to fixed size instead of contents.

screenshot 2018-12-21 at 14 58 20

### PR DESCRIPTION
**Pull request by hebasto**
Fix #15016.

Refs:
- [QTBUG-65750: QProgressDialog too small width at larger font size on Mac](https://bugreports.qt.io/browse/QTBUG-65750)
- [QTBUG-70357: QProgressDialog is too narrow to fit the text of its label](https://bugreports.qt.io/browse/QTBUG-70357)

With this PR:
screenshot from 2018-12-26 22-01-30

### CODE REVIEW

**Comment by HashUnlimited** [comment]
As a workaround this seems to work for the specific case, tried with extra long wallet names.

Thanks for the links btw, out of curiosity I have also tried to apply the same to a different project where Qt's dialog margins are overruled by style sheets - no effect there (this just for info).

**Comment by jonasschnelli** [comment]
Thanks for the fix...
But isn't it possible to add a QLayout and have the dialogue autoresize like other windows?
However, this seems to work as well.

**Review by donaloconnor — APPROVED** [review]
utACK https://github.com/bitcoin/bitcoin/pull/15040/commits/1f7ac92cf88ff7e6b10aaa49e174805a5823bfa2

**Comment by jonasschnelli** [comment]
utACK 1f7ac92cf88ff7e6b10aaa49e174805a5823bfa2

File: src/qt/bitcoingui.cpp [hunk 1]
```diff
@@ -1242,6 +1243,12 @@ void BitcoinGUI::showProgress(const QString &title, int nProgress)
     if (nProgress == 0)
     {
         progressDialog = new QProgressDialog(title, "", 0, 100);
+#ifdef Q_OS_MAC
```
Comment (promag) [inline src/qt/bitcoingui.cpp]: Move the implementation to something like:
```cpp
void GUIUtil::PolishProgressDialog(QProgressDialog* dialog)
{
#ifdef Q_OS_MAC
    // Workaround for macOS-only Qt bug; see: QTBUG-65750, QTBUG-70357.
    const int margin = (dialog->fontMetrics()).width("X");
    progressDialog->resize(dialog->width() + (2 * margin), progressDialog->height());
#else
    Q_UNUSED(dialog);
#endif
}
```

Comment (hebasto) [reply src/qt/bitcoingui.cpp]: Thank you @promag. Will do.

**Comment by hebasto** [comment]
@promag your comment has been addressed.

Also a little of obvious code styling added.

File: src/qt/guiutil.cpp [hunk 2]
```diff
@@ -933,4 +935,16 @@ bool ItemDelegate::eventFilter(QObject *object, QEvent *event)
     return QItemDelegate::eventFilter(object, event);
 }
 
+void PolishProgressDialog(QProgressDialog* dialog)
+{
+#ifdef Q_OS_MAC
+    // Workaround for macOS-only Qt bug; see: QTBUG-65750, QTBUG-70357.
+    const int margin = (dialog->fontMetrics()).width("X");
```
Comment (promag) [inline src/qt/guiutil.cpp]: nit `const int margin = dialog->fontMetrics().width("X");`

File: src/qt/guiutil.cpp [hunk 3]
```diff
@@ -933,4 +935,16 @@ bool ItemDelegate::eventFilter(QObject *object, QEvent *event)
...
+    dialog->resize(dialog->width() + (2 * margin), dialog->height());
```
Comment (promag) [inline src/qt/guiutil.cpp]: nit, `dialog->width() + 2 * margin`.

**Review by promag — COMMENTED** [review]
utACK 2b06881, just 2 minor nits.

**Comment by hebasto** [comment]
@promag all nits are fixed.

**Comment by hebasto** [comment]
@Sjors would you mind reviewing this PR?

**Comment by Sjors** [comment]
tACK 7c572c4 on macOS 10.14.2

**Review by promag — COMMENTED** [review]
utACK 7c572c4.

**Comment by jonasschnelli** [comment]
Tested ACK 7c572c488dcf84438d64da4ca920a48810044a72

**Comment by HashUnlimited** [comment]
That might go a bit off-topic here but since @hebasto seems to be experienced in this area, have you ever thought about bringing the tabs to Apple’ touchbar?

**Comment by Sjors** [comment]
@HashUnlimited that's probably too much OS-specific customisation. I don't think the benefits of that feature would outweigh the cost of maintaining it. Feel free to make a Github issue with that feature suggestion if you feel strongly about it though.
