### PR TITLE
[net] Remove assert(nMaxInbound > 0)

### LINKED ISSUE #9007: Assertion failed: (nMaxInbound > 0), function AcceptConnection, file net.cpp, line 973.
Current bitcoin-master on testnet, `maxconnections=8` in the config file. Running in VM that doesn't have public IP and is not reachable from the Internet.

Wait until you have 8 peers.

```
telnet localhost 18333
```

It will result in:

```
Assertion failed: (nMaxInbound > 0), function AcceptConnection, file net.cpp, line 973.
```

First found in https://github.com/bitcoin/bitcoin/pull/8996, but can be reproduced on master.

### PR DESCRIPTION
**Pull request by maflcko**
nMaxInbound might very well be 0 or -1, if the user prefers to keep
a small number of maxconnections.

Note: nMaxInbound of -1 means that the user set maxconnections
to 8 or less, but we still want to keep an additional slot for
the feeler connection.

Closes #9007

### CODE REVIEW

**Comment by sipa** [comment]
Isn't there some behaviour we want when the actual value (based on number of connections, not maximum number) <= 0, like cancelling the attempt?

**Comment by laanwj** [comment]
> Isn't there some behaviour we want when the actual value (based on number of connections, not maximum number) <= 0, like cancelling the attempt?

I've checked the code below it and I think there is no danger from this value reaching <0. The only thing that actually uses nMaxInBound is:
```
    if (nInbound >= nMaxInbound)
    {
        if (!AttemptToEvictConnection()) {
            // No connection to evict, disconnect the new connection
            LogPrint("net", "failed to find an eviction candidate - connection dropped (full)\n");
            CloseSocket(hSocket);
            return;
        }
    }
```
So it will try to evict all connections, just like when nMaxInbound would be 0, which I think makes sense.

utACK https://github.com/bitcoin/bitcoin/pull/9008/commits/fa1c3c2eb0a1853ed0e0662fc2bdbca51e05ccf5

File: src/net.cpp [hunk 1]
```diff
@@ -970,7 +970,6 @@ void CConnman::AcceptConnection(const ListenSocket& hListenSocket) {
     CAddress addr;
     int nInbound = 0;
     int nMaxInbound = nMaxConnections - (nMaxOutbound + nMaxFeeler);
```
Comment (laanwj) [inline src/net.cpp]: Maybe it would be wise to cap this to 0 explicitly, as no one will be expecting this to be negative in future maintenance.
```
int nMaxInbound = std::max(nMaxConnections - (nMaxOutbound + nMaxFeeler), 0);
```

**Comment by laanwj** [comment]
Theoretically we could stop listening for inbound connections completely if this is <=0, however, whitelisted connections are probably an exception? There are some potential traps there that can create additional unexpected behavior changes. I think this pull is safe and we can do that later.

**Comment by gmaxwell** [comment]
> Theoretically we could stop listening for inbound connections completely if this is <=0, however, whitelisted connections are probably an exception? 

Probably the logic should be changed further in the future, if you set maxconnections to 5 and -listen=1 -connect=gateway.host  I would expect you to end up with 5 connections, not 1.

But ACK getting rid of the assert, good move for now and telling people to set maxconnections to a small number used to be common advice for people concerned with memory and bandwidth (we now use less memory per peer, so less reason)... I also checked that the negative is fine with the current code.

File: src/net.cpp (hunk 1 above)
Comment (MarcoFalke) [inline src/net.cpp]: I disagree at just blindly capping this at 0. There are only two ways imo:

* Add a comment which says this may be negative
* Rework the "-maxconnections" code to not allow negative numbers here

Comment (laanwj) [inline src/net.cpp]: I don't think a negative value for something called `nMaxOutbound` makes sense. There should never be a difference in behavior between no outgoing connections, or negative outgoing connections. But ok, this needs a different solution anyway at a higher level.
