### PR TITLE
Fix PSBT deserialization of 0-input transactions

### LINKED ISSUE #13958: decodepsbt fails for PSBT with no inputs
Reported by @kallewoof here: https://github.com/bitcoin/bitcoin/pull/13917#issuecomment-412459298

```
$ ./bitcoin-cli createpsbt "[]" "[{\"$(./bitcoin-cli getnewaddress)\":0.01}]"
cHNidP8BACoCAAAAAAFAQg8AAAAAABepFG6Rty1Vk+fUOR4v9E6R6YXDFkHwhwAAAAAAAA==
$ ./bitcoin-cli decodepsbt cHNidP8BACoCAAAAAAFAQg8AAAAAABepFG6Rty1Vk+fUOR4v9E6R6YXDFkHwhwAAAAAAAA==
error code: -22
error message:
TX decode failed CDataStream::read(): end of data: unspecified iostream_category error
```

### PR DESCRIPTION
**Pull request by achow101**
0-input transactions can be ambiguously deserialized as being witness transactions. Since the unsigned transaction is never serialized as a witness transaction as it has no witnesses, we should always deserialize it as a non-witness transaction and set the serialization flags as such.

When a transaction is serliazed for the non-witness-utxo, it is always a valid network transaction and thus it should be always be deserialized as a witness transaction and the deserialzation flags are set as such.

Fixes #13958

### CODE REVIEW

File: src/script/sign.h [hunk 1]
```diff
@@ -302,6 +302,9 @@ struct PSBTInput
                     } else if (key.size() != 1) {
                         throw std::ios_base::failure("Non-witness utxo key is more than one byte type");
                     }
+                    // Set the stream to unserialize with witness since this is always a valid network transaction
```
Comment (sipa) [inline src/script/sign.h]: You can instead use `UnserializeFromVector(OverrideStream(&s, s.GetType(), s.GetVersion() & ~SERIALIZE_TRANSACTION_NO_WITNESS);` to avoid permanently changing the flags on `s` (similar below).

**Comment by sipa** [comment]
Would you mind also just dropping the witness after reading the non-witness UTXO field (and/or before writing)?

File: src/script/sign.h (hunk 1 above)
Comment (achow101) [reply src/script/sign.h]: Done

**Comment by achow101** [comment]
> Would you mind also just dropping the witness after reading the non-witness UTXO field (and/or before writing)?

Done.

**Comment by sipa** [comment]
utACK bd19cc78cfc455cf06e120adb0d12c2f96ba8fca

File: src/script/sign.h [hunk 2]
```diff
@@ -223,7 +223,8 @@ struct PSBTInput
         // If there is a non-witness utxo, then don't add the witness one.
         if (non_witness_utxo) {
             SerializeToVector(s, PSBT_IN_NON_WITNESS_UTXO);
-            SerializeToVector(s, non_witness_utxo);
+            OverrideStream<Stream> os(&s, s.GetType(), s.GetVersion() | SERIALIZE_TRANSACTION_NO_WITNESS);
```
Comment (Empact) [inline src/script/sign.h]: nit: could use the `WithOrVersion` helper here:
https://github.com/bitcoin/bitcoin/blob/ddc3ec92b0e655a3da21ac2e85ec2e7ecb66c65b/src/streams.h#L66-L70

File: src/streams.h [hunk 3]
```diff
@@ -61,6 +61,7 @@ class OverrideStream
 
     int GetVersion() const { return nVersion; }
     int GetType() const { return nType; }
+    size_t size() const { return stream->size(); }
```
Comment (Empact) [inline src/streams.h]: nit: could be nice to put `size` with `read`, `write`, as they are all delegated.

**Comment by laanwj** [comment]
utACK bd19cc78cfc455cf06e120adb0d12c2f96ba8fca

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13960/commits/bd19cc78cfc455cf06e120adb0d12c2f96ba8fca

**Comment by fanquake** [comment]
Will be backported in #13976

**Comment by dongcarl** [comment]
> When a transaction is serliazed for the non-witness-utxo, it is always a valid network transaction and thus it should be always be deserialized as a witness transaction and the deserialzation flags are set as such.

Surely you mean "...it should be always be deserialized as a _**non-witness**_ transaction..."

**Comment by sipa** [comment]
@dongcarl No. "Deserialized as a witness transaction" here means "permit witnesses, and if ambiguous, prefer the interpretation with witness over the one with 0 inputs". As it's always a valid fully-signed transaction, it can't have 0 inputs, and thus we should indeed prefer the witness version.

**Comment by dongcarl** [comment]
@sipa Makes sense!
