### PR TITLE
test: Remove intermittently failing and not very meaningful `BOOST_CHECK` in `cnetaddr_basic`

### LINKED ISSUE #21682: intermittent unit test failure: test/net_tests.cpp(311): error: in "net_tests/cnetaddr_basic": check addr_str == scoped_addr || addr_str == "fe80:0:0:0:0:0:0:1" has failed
https://cirrus-ci.com/task/5470546704990208?logs=ci#L4527

### PR DESCRIPTION
**Pull request by practicalswift**
Remove intermittently failing and not very meaningful `BOOST_CHECK` in `cnetaddr_basic`.

Fixes #21682.

Rationale from https://github.com/bitcoin/bitcoin/issues/21682#issuecomment-819897122:

> I've looked at that test before and I don't think that specific `BOOST_CHECK` makes much sense TBH :)
> 
> 1.) I don't understand why we test if `ToString()` output includes `%zone_index`: it clearly doesn't on some platforms, so we cannot rely on it anyways. Then why test it?
> 
> 2.) And perhaps more fundamentally: why would we even _want_ to have `%zone_index` in our textual `ToString()` output? I think the expectation is to get say `fe80::1ff:fe23:4567:890a` (without zone index) and not say `fe80::1ff:fe23:4567:890a%eth2 ` or `fe80::1ff:fe23:4567:890a%3 `when doing `ipv6_addr.ToString()` :)

### CODE REVIEW

**Comment by jonatack** [comment]
@practicalswift Thank you for your concerns that have been helpful.  I've updated #21690 to fix the new issue and make the scoped addr assertion be per-platform (macOS, and all others). I hope it addresses your feedback to make the coverage more meaningful.

**Comment by jonatack** [comment]
(Whether it's better now or not, thanks to your feedback, you made me improve it more than I would have done otherwise.)

**Comment by MarcoFalke** [comment]
review ACK 63631beef6a0046390469971adf4500718ab34ad

I don't have any background in ip addresses, but it seems fine to remove a recently added test that intermittently fails. Looks like #21690 reworks the test. That pull can land after rebase+review.

**Comment by jonatack** [comment]
Note that the test was added seven months ago and no issues reported until this week.

Re-working the test was not needed to fix this issue. It was only done in reponse to extraneous, new feedback unrelated to the issue.

**Comment by MarcoFalke** [comment]
I am seeing intermittent issues for years that are still waiting for someone to report an issue on. So a lack of a report doesn't imply the issue didn't exist when it was introduced.

**Comment by jonatack** [comment]
Sure, but the fix I proposed was a smaller change than this one and did not drop coverage and context. I tried to improve things constructively. Well, I tried.

File: src/test/net_tests.cpp [hunk 1]
```diff
@@ -307,9 +307,6 @@ BOOST_AUTO_TEST_CASE(cnetaddr_basic)
     BOOST_REQUIRE(addr.IsValid());
     BOOST_REQUIRE(addr.IsIPv6());
     BOOST_CHECK(!addr.IsBindAny());
-    const std::string addr_str{addr.ToString()};
-    BOOST_CHECK(addr_str == scoped_addr || addr_str == "fe80:0:0:0:0:0:0:1");
-    // The fallback case "fe80:0:0:0:0:0:0:1" is needed for macOS 10.14/10.15 and (probably) later.
```
Comment (jonatack) [inline src/test/net_tests.cpp:312]: This change orphaned the documentation in line 303. Fixed in #21961.

**Comment by jonatack** [comment]
> Rationale from [#21682 (comment)](https://github.com/bitcoin/bitcoin/issues/21682#issuecomment-819897122):
> 
> > I've looked at that test before and I don't think that specific `BOOST_CHECK` makes much sense TBH :)
> > 1.) I don't understand why we test if `ToString()` output includes `%zone_index`: it clearly doesn't on some platforms, so we cannot rely on it anyways. Then why test it?
> > 2.) And perhaps more fundamentally: why would we even _want_ to have `%zone_index` in our textual `ToString()` output? I think the expectation is to get say `fe80::1ff:fe23:4567:890a` (without zone index) and not say `fe80::1ff:fe23:4567:890a%eth2 ` or `fe80::1ff:fe23:4567:890a%3 `when doing `ipv6_addr.ToString()` :)

I hope both #21961 and #21690 clear this up.
