### PR TITLE
RPC: creates possibility to preserve labels on importprivkey

### LINKED ISSUE #13087: importprivkey unsets labels set with importaddress and importpubkey
### Expected behavior:

1. `importaddress` or `importpubkey` a watching-only address or pubkey with a label
2. Receive a transaction to that address; observe that the label has been applied to that transaction
3. `importprivkey` the private key for that address without specifying any change to the label
4. Have the previous label still applied to the transaction after the import.

### Observed behavior on 0.15 and current master:

Steps 1-3 the same.
4. Previous label is replaced with the default empty label ("")

Problem seems to have occurred on 0.15 and affects the latest master (see subsequent details).  I'd suspect all versions are affected, i.e. it's not a regression.

### Steps to reproduce

```bash
## For testing
ADDRESS=2N6Y2wdhd91mQnZ8qCeH6hT5aZZygXFnNjP
PRIVKEY=cQriWp98xU9ghRvDKbzkRcgcecQLezjYwtPUjLNN5kzT8GbdnxQt

## Starting a fresh regtest (i.e. ~/.bitcoin/regtest/ previously deleted)
$ bitcoind -daemon -regtest
Bitcoin server starting

## Import the address with a label and no rescan
$ bitcoin-cli -regtest importaddress $ADDRESS "Watch-only test" false

## Mine a generation tx to the address (regular spending works too)
$ bitcoin-cli -regtest generatetoaddress 1 $ADDRESS > /dev/null

## Bury the generation tx so it shows up in the wallet
$ bitcoin-cli -regtest generate 100 > /dev/null

## See that the address label was applied to the tx
$ bitcoin-cli -regtest listunspent | jq .[].label
"Watch-only test"

## Import the private key.  Note the 'label' parameter is not explicitly passed
$ bitcoin-cli -regtest importprivkey $PRIVKEY

## See that the address label has been set to empty :-(
$ bitcoin-cli -regtest listunspent | jq .[].label
```

Same thing happens if `importpubkey` is substituted for `importaddress`.  I haven't tested `importmulti` for either address/pubkey or privkey import, nor have I tested using named parameters.

### Use case

I was watching-only addresses from my cold wallet, then moved my coins to new addresses and (after some confirmations) imported the old private keys so that I could sell fork coins.  I didn't realize until now when I was trying to do some bookkeeping that all my old cold wallet labels were reset (happily, I have backups, so nothing is lost but time).

### Possibly related issues

- #12698 looks related but the poster there says that it works on mainnet.  I discovered my problem from actual use on mainnet and reproduced on regtest.

### PR DESCRIPTION
**Pull request by marcoagner**
Closes #13087.

As discussed in the issue, this is a feature request instead of a bug report since the behaviour was as intended (i.e. label with default: `''`). With this, the old behaviour is kept while the possibility to achieve the preservation of labels, as expected in the open issue, is added.

### CODE REVIEW

**Comment by promag** [comment]
There is no need for a new parameter, check if label is null instead.

**Comment by promag** [comment]
Concept ACK, a test would be nice.

**Comment by marcoagner** [comment]
Thank you, @promag.
I added some functional tests for this specific behavior between importaddress and importprivkey.
If everything is alright, I'll squash and rebase as necessary.

File: src/wallet/rpcdump.cpp [hunk 1]
```diff
@@ -151,9 +151,12 @@ UniValue importprivkey(const JSONRPCRequest& request)
         CKeyID vchAddress = pubkey.GetID();
         {
             pwallet->MarkDirty();
-            // We don't know which corresponding address will be used; label them all
+
+            // We don't know which corresponding address will be used; label all new addresses and preserve the rest
             for (const auto& dest : GetAllDestinationsForKey(pubkey)) {
-                pwallet->SetAddressBook(dest, strLabel, "receive");
+                bool has_label = pwallet->mapAddressBook.find(dest) != pwallet->mapAddressBook.end() && !pwallet->mapAddressBook[dest].name.empty();
```
Comment (promag) [inline src/wallet/rpcdump.cpp]: I was thinking in something like
```cpp
if (request.params[1].isNull()) {
    const auto& it = pwallet->mapAddressBook.find(dest);
    if (it != pwallet->mapAddressBook.end()) strLabel = it->second;
}
pwallet->SetAddressBook(dest, strLabel, "receive");
```

Comment (marcoagner) [reply src/wallet/rpcdump.cpp]: Hm, I see. Yeah.. this behavior seems better. Thanks!
Updating this and the test.

**Comment by marcoagner** [comment]
Updated with the right behavior.
I will squash and rebase it as necessary in the morning, thanks.

**Review by promag — COMMENTED** [review]
Update PR title.

**Comment by harding** [comment]
Tested ACK 74877f3b10072e1975c931bb296212e008cd8c58 .  This is exactly the behavior I desired, thanks @marcoagner!

File: src/wallet/rpcdump.cpp [hunk 2]
```diff
@@ -151,8 +151,15 @@ UniValue importprivkey(const JSONRPCRequest& request)
...
             pwallet->MarkDirty();
-            // We don't know which corresponding address will be used; label them all
+
+            // We don't know which corresponding address will be used;
+            // label all new addresses, and label existing addresses if a
+            // label was passed.
             for (const auto& dest : GetAllDestinationsForKey(pubkey)) {
+                if (request.params[1].isNull()) {
+                    const auto& it = pwallet->mapAddressBook.find(dest);
+                    if (it != pwallet->mapAddressBook.end()) strLabel = it->second.name;
```
[the remark this answers is not in the document]
Comment (promag) [reply src/wallet/rpcdump.cpp]: Good catch! Suggestion:
```cpp
if (it == pwallet->mapAddressBook.end()) {
    pwallet->SetAddressBook(dest, strLabel, "receive")
} else {
    pwallet->SetAddressBook(dest, it->second.name, "receive")
}
```

[the remark this answers is not in the document]
Comment (promag) [reply src/wallet/rpcdump.cpp]: There should be a test ensuring the correct behaviour.

[the remark this answers is not in the document]
Comment (marcoagner) [reply src/wallet/rpcdump.cpp]: Yes, makes sense. I will update it and add a test for the correct behaviour as soon as I can.

**Comment by marcoagner** [comment]
I'm back to this. The new commit keeps the the already tested behaviour (passing tests added on this PR et al) and passes new test for the multiple destinations bug spotted by @Empact.

**Comment by luke-jr** [comment]
This still changes behaviour: the default is now `null` (ie, current label) instead of `""`.

I don't particularly care what the default is (`null` makes more sense), but the change should be documented and noted in release notes.

**Comment by promag** [comment]
Agree with @luke-jr regarding the behaviour change.

**Comment by marcoagner** [comment]
I added a `release-notes-pr13381.md` file documenting the change.
Let me know if I missed something or should document this somewhere else.
Thanks!

**Comment by harding** [comment]
@marcoagner Thanks for adding the release notes!  I thought maybe the behavior change could be described more simply with the addition of a few examples; see below from some proposed text.  I also changed the heading so that it's clear that only a small part of the importprivkey API is being changed (I also removed the `code style` from the heading as those don't display well in headings on parts of BitcoinCore.org, but that's a local problem so feel free to add back the backtics if you like them).

```markdown
RPC importprivkey: new label behavior
-------------------------------------

Previously, `importprivkey`automatically added the default empty label
("") to all addresses associated with imported private keys.  Now it
defaults to using any existing label for those addresses.  For example:

- Old behavior: you import a watch-only address with the label "cold
  wallet".  Later, you import the corresponding private key using the
  default settings.  The address's label is changed from "cold wallet"
  to "".

- New behavior: you import a watch-only address with the label "cold
  wallet".  Later, you import the corresponding private key using the
  default settings.  The address's label remains "cold wallet".

In both the previous and current case, if you directly specify a label
during the import, that label will override whatever previous label the
addresses may have had.  Also in both cases, if none of the addresses
previously had a label, they will still receive the default empty label
("").  Examples:

- You import a watch-only address with the label "temporary".  Later you
  import the corresponding private key with the label "final".  The
  address's label will be changed to "final".

- You import a private key for an address that was not previously in the
  wallet.  It's addresses will receive the default empty label ("").
```

**Comment by marcoagner** [comment]
@harding That's much better, thanks.
I'm changing to that on the next commit with some small differences.
Here's the diff so it's easier to spot my edits:
```diff
4,5c4,5
< Previously, `importprivkey`automatically added the default empty label
< ("") to all addresses associated with imported private keys.  Now it
---
> Previously, `importprivkey` automatically added the default empty label
> ("") to all addresses associated with the imported private keys.  Now it
21c21
< ("").  Examples:
---
> ("") as default.  Examples:
28c28,29
<   wallet.  It's addresses will receive the default empty label ("").
---
>   wallet using the default settings.  Its addresses will receive the
>   default empty label ("").
```
Seems good?

**Comment by harding** [comment]
@marcoagner LGTM, although the two uses of 'default' in this clause is a tiny bit awkward IMO (but, it's clear, which is all that really matters):

> they will still receive the default empty label ("") as default.

Maybe that second-to-last sentence could have its adverbial phrase "using the default settings" moved next to the verb it modifies, "import", e.g.:

> You use the default settings to import a private key for an address that was not previously in the wallet.

Thanks for updating, and thanks especially for catching my misuse of the apostrophe in the possessive its.  :man_facepalming:

**Comment by marcoagner** [comment]
@harding I changed both parts pointed in your last comment. Thanks for the attention and help with this; I think we've now nailed this part. :)

**Comment by marcoagner** [comment]
Could anybody review 6115b5231954a38c400fa4808627dbb8e239ea68, please? One month in the freezer and is (hopefully) simple. :)

File: src/wallet/rpcdump.cpp [hunk 3]
```diff
@@ -151,9 +151,17 @@ UniValue importprivkey(const JSONRPCRequest& request)
...
         {
             pwallet->MarkDirty();
-            // We don't know which corresponding address will be used; label them all
+
+            // We don't know which corresponding address will be used;
+            // label all new addresses, and label existing addresses if a
+            // label was passed.
             for (const auto& dest : GetAllDestinationsForKey(pubkey)) {
-                pwallet->SetAddressBook(dest, strLabel, "receive");
+                const auto& it = pwallet->mapAddressBook.find(dest);
```
Comment (sipa) [inline src/wallet/rpcdump.cpp]: Nit: It's slightly confusing to use a reference type here; `find` returns an iterator by value.

**Review by sipa — COMMENTED** [review]
utACK 6115b5231954a38c400fa4808627dbb8e239ea68. Didn't review the tests.

Non-blocking nit only.

File: test/functional/wallet_import_with_label.py [hunk 4]
```diff
@@ -0,0 +1,126 @@
+#!/usr/bin/env python3
+# Copyright (c) 2018 The Bitcoin Core developers
+# Distributed under the MIT software license, see the accompanying
+# file COPYING or http://www.opensource.org/licenses/mit-license.php.
+"""Test the behavior of RPC importprivkey on set and unset labels of
+watch-only addresses.
```
Comment (promag) [inline test/functional/wallet_import_with_label.py]: Drop `of watch-only`?

File: test/functional/wallet_import_with_label.py [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+    assert_equal,
+)
+
+
+class ImportWithLabel(BitcoinTestFramework):
+    def set_test_params(self):
+        self.num_nodes = 2
+        self.setup_clean_chain = True
+
+    def setup_network(self):
```
Comment (promag) [inline test/functional/wallet_import_with_label.py]: Can be removed.

File: src/wallet/rpcdump.cpp [hunk 6]
```diff
@@ -151,9 +151,16 @@ UniValue importprivkey(const JSONRPCRequest& request)
...
-            // We don't know which corresponding address will be used; label them all
+
+            // We don't know which corresponding address will be used;
+            // label all new addresses, and label existing addresses if a
+            // label was passed.
             for (const auto& dest : GetAllDestinationsForKey(pubkey)) {
-                pwallet->SetAddressBook(dest, strLabel, "receive");
+                if (!request.params[1].isNull()) {
+                    pwallet->SetAddressBook(dest, strLabel, "receive");
+                } else if (pwallet->mapAddressBook.count(dest) == 0) {
```
Comment (sipa) [inline src/wallet/rpcdump.cpp]: Given that the branches for the two `if` statements are identical, why write it as a single `if (!request.params[1].isNull() || pwallet->mapAddressBook.count(dest)) {` ?

**Review by sipa — COMMENTED** [review]
utACK 1d4fdb33349a60cac1926f83586826ba62b1a451

File: src/wallet/rpcdump.cpp (hunk 6 above)
Comment (marcoagner) [reply src/wallet/rpcdump.cpp]: Just to try to make it clear in the code that the `request.params[1]` has precedence. Bad idea?

Comment (marcoagner) [reply src/wallet/rpcdump.cpp]: No reason besides it since AFAIK putting the look up as second condition in the `||` statement will not call it if there is a `params[1]` in the first condition.

File: test/functional/wallet_import_with_label.py [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+    assert_equal,
+)
+
+
+class ImportWithLabel(BitcoinTestFramework):
+    def set_test_params(self):
+        self.num_nodes = 2
+        self.setup_clean_chain = True
+
+    def run_test(self):
```
Comment (MarcoFalke) [inline test/functional/wallet_import_with_label.py]: The skip-if-no-wallet might have to be added to this test?

**Comment by MarcoFalke** [comment]
Lets see what travis says

File: test/functional/wallet_import_with_label.py (hunk 7 above)
Comment (marcoagner) [reply test/functional/wallet_import_with_label.py]: You're right. I was not aware, thanks.

File: test/functional/wallet_import_with_label.py [hunk 8]
```diff
@@ -0,0 +1,126 @@
...
+                      "its label.")
+        priv_key4 = self.nodes[0].dumpprivkey(address4)
+        self.nodes[1].importprivkey(priv_key4)
+        address_assert4 = self.nodes[1].getaddressinfo(address4)
+
+        assert(address_assert4.get('embedded'))
+
+        bcaddress_assert = self.nodes[1].getaddressinfo(
+                address_assert4['embedded']['address']
+                )
```
[the remark this answers is not in the document]
Comment (marcoagner) [reply test/functional/wallet_import_with_label.py]: Hm, nice. Didn't know this `black`, thanks. 
I was using Flake8. Besides the double-quotes for strings, it seems that `black` has a longer default line length, but I'm okay with (actually prefer) that. :)
I will just rebase, re-run tests, and provide a new commit.

**Comment by marcoagner** [comment]
`wallet_basic.py` passed locally but seems to have failed on appveyor :thinking:

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13381/commits/a6b5ec18ff39ef3ccd19ec0e6db9ae00602d8938

**Comment by sipa** [comment]
utACK a6b5ec18ff39ef3ccd19ec0e6db9ae00602d8938

**Comment by jonasschnelli** [comment]
utACK a6b5ec18ff39ef3ccd19ec0e6db9ae00602d8938
