### PR TITLE
net: Fix Discover() not running when using -bind=0.0.0.0:port

### LINKED ISSUE #31293: Discover() will not run if listening on any address with an explicit bind=0.0.0.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

https://github.com/bitcoin/bitcoin/blob/85bcfeea23568053ea09013fb8263fa1511d7123/src/init.cpp#L1890-L1892

`Discover()` will run only if we are listening on all addresses (`bind_on_any` is `true`). However if `-bind=0.0.0.0:port` is explicitly given, then `bind_on_any` will end up being `false` and thus `Discover()` will not run when it should.

### Expected behaviour

Discover own addresses even if `-bind=0.0.0.0:port` is given.

### Steps to reproduce

Use `-bind=0.0.0.0:port`.

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@85bcfeea23568053ea09013fb8263fa1511d7123

### Operating system and version

Windows 3.11

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by b-l-u-e**
This PR fixes two related issues with address discovery when using explicit bind addresses in Bitcoin Core:

  -  #31293
  -  #31336

When using `-bind=0.0.0.0:port` (or `-bind=::`), the `Discover()` function was not being executed because the code only checked the `bind_on_any` flag. This led to two problems:
- The node would not discover its own local addresses if an explicit "any" bind was used.
- The functional test `feature_bind_port_discover.py` would fail, as it expects local addresses to be discovered in these cases.

This PR:
1. Checks both `bind_on_any` and any bind addresses using `IsBindAny()`
   Ensures `Discover()` runs when binding to 0.0.0.0 or ::, even if specified explicitly.
2. Ensures correct address discovery
   The node will now discover its own addresses when using explicit "any" binds, matching user expectations and fixing the test.
3. Maintains backward compatibility
   The semantic meaning of `bind_on_any` is preserved as defined in `net.h`:  
   > "True if the user did not specify -bind= or -whitebind= and thus we should bind on 0.0.0.0 (IPv4) and :: (IPv6)"
4. Updates the test to use dynamic ports
   The functional test `feature_bind_port_discover.py` is updated to use dynamic ports instead of hardcoded ones, improving reliability.

References

- Implementation follows the approach proposed in my [review comment on #31492](https://github.com/bitcoin/bitcoin/pull/31492#issuecomment-2941773645).

Closes #31293

The #31336 has the overall test failure and requires both this PR and #33362 to be fully resolved.

### CODE REVIEW

**Comment by yuvicc** [comment]
Concept ACK

Removing duplicate code from `DefaultOnionServiceTarget()` is better IMO

**Review by PeterWrighten — COMMENTED** [review]
utACK 776b7ee
I consider you could report error message when running in original codebase, and in comparison with this PR one. Or you can find related issue and declare to fix them, it could be clearer for reviewers.

File: src/init.cpp [hunk 1]
```diff
@@ -2024,7 +2024,17 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
         StartTorControl(onion_service_target);
     }
 
-    if (connOptions.bind_on_any) {
+    bool should_discover = connOptions.bind_on_any;
+    if (!should_discover) {
+        for (const auto& bind_addr : connOptions.vBinds) {
```
Comment (yuvicc) [inline src/init.cpp]: What about `-whitebind` here? 
There was a patch suggestion from vasild [here](https://github.com/bitcoin/bitcoin/pull/31492/files#r2071427640)

Comment (yuvicc) [reply src/init.cpp]: ahh my bad its already checked with `bind_on_any` bool.

**Review by yuvicc — COMMENTED** [review]
lgtm ACK 776b7ee5855f7572798eff3014030bcc53aa7393

File: src/init.cpp (hunk 1 above)
Comment (vasild) [reply src/init.cpp]: > its already checked with `bind_on_any` bool.

I do not think so - the `bind_on_any` bool will be true if `-whitebind` and `-bind` are not given. The current patch will not run `Discover()` if `-whitebind=0.0.0.0` is used but it should. Here is an example patch to fix that:

```diff
--- i/src/init.cpp
+++ w/src/init.cpp
@@ -2030,12 +2030,20 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
             if (bind_addr.IsBindAny()) {
                 should_discover = true;
                 break;
             }
         }
     }
+    if (!should_discover) {
+        for (const auto& whitebind : connOptions.vWhiteBinds) {
+            if (whitebind.m_service.IsBindAny()) {
+                should_discover = true;
+                break;
+            }
+        }
+    }
     
     if (should_discover) {
         // Only add all IP addresses of the machine if we would be listening on
         // any address - 0.0.0.0 (IPv4) and :: (IPv6).
         Discover();
     }
```
you can amend it to 705fe35719 `net: Fix Discover() not running when using -bind=0.0.0.0:port`

File: src/init.cpp [hunk 2]
```diff
@@ -2024,7 +2024,17 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
         StartTorControl(onion_service_target);
     }
```
Comment (vasild) [inline src/init.cpp:2142]: Would be nice to keep the [length of lines in commit messages shorter](https://dev.to/noelworden/improving-your-commit-message-with-the-50-72-rule-3g79).

File: test/functional/feature_bind_port_discover.py [hunk 3]
```diff
@@ -25,16 +26,17 @@
...
 class BindPortDiscoverTest(BitcoinTestFramework):
     def set_test_params(self):
         # Avoid any -bind= on the command line. Force the framework to avoid adding -bind=127.0.0.1.
         self.setup_clean_chain = True
         self.bind_to_localhost_only = False
+        # Get dynamic ports for each node from the test framework
+        self.bind_port_0 = p2p_port(0)
+        self.bind_port_1 = p2p_port(1)
         self.extra_args = [
-            ['-discover', f'-port={BIND_PORT}'], # bind on any
```
Comment (vasild) [inline test/functional/feature_bind_port_discover.py:36]: The testing framework will add `-bind=0.0.0.0`, we want to test this. But we also want to test if no `-bind` is given at all. Here is a patch to do that and also to test `-whitebind=0.0.0.0`:

```diff
--- i/test/functional/feature_bind_port_discover.py
+++ w/test/functional/feature_bind_port_discover.py
@@ -26,23 +26,47 @@ from test_framework.util import (
 ADDR1 = '1.1.1.1'
 ADDR2 = '2.2.2.2'
 
 class BindPortDiscoverTest(BitcoinTestFramework):
     def set_test_params(self):
         # Avoid any -bind= on the command line. Force the framework to avoid adding -bind=127.0.0.1.
-        self.setup_clean_chain = True
         self.bind_to_localhost_only = False
         # Get dynamic ports for each node from the test framework
-        self.bind_port_0 = p2p_port(0)
-        self.bind_port_1 = p2p_port(1)
+        self.bind_ports = [
+            p2p_port(0),
+            p2p_port(2), # node0 will use their port + 1 for onion listen, which is the same as p2p_port(1), so avoid collision
+            p2p_port(3),
+            p2p_port(4),
+        ]
         self.extra_args = [
-            ['-discover', f'-port={self.bind_port_0}'], # bind on any
-            ['-discover', f'-bind={ADDR1}:{self.bind_port_1}'],
+            ['-discover', f'-port={self.bind_ports[0]}', '-listen=1'], # Without any -bind
+            ['-discover', f'-bind=0.0.0.0:{self.bind_ports[1]}'], # Explicit -bind=0.0.0.0
+            ['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}'], # Explicit -whitebind=0.0.0.0
+            ['-discover', f'-bind={ADDR1}:{self.bind_ports[3]}'], # Explicit -bind=routable_addr
         ]
         self.num_nodes = len(self.extra_args)
 
+    def setup_network(self):
+        """
+        BitcoinTestFramework.setup_network() without connecting node0 to node1,
+        we don't need that and avoiding it makes the test faster.
+        """
+        self.setup_nodes()
+
+    def setup_nodes(self):
+        """
+        BitcoinTestFramework.setup_nodes() with overriden has_explicit_bind=True
+        for each node and without the chain setup.
+        """
+        self.add_nodes(self.num_nodes, self.extra_args)
+        # TestNode.start() will add -bind= to extra_args if has_explicit_bind is
+        # False. We do not want any -bind= thus set has_explicit_bind to True.
+        for node in self.nodes:
+            node.has_explicit_bind = True
+        self.start_nodes()
+
     def add_options(self, parser):
         parser.add_argument(
             "--ihave1111and2222", action='store_true', dest="ihave1111and2222",
             help=f"Run the test, assuming {ADDR1} and {ADDR2} are configured on the machine",
             default=False)
 
@@ -51,33 +75,39 @@ class BindPortDiscoverTest(BitcoinTestFramework):
             raise SkipTest(
                 f"To run this test make sure that {ADDR1} and {ADDR2} (routable addresses) are "
                 "assigned to the interfaces on this machine and rerun with --ihave1111and2222")
 
     def run_test(self):
         self.log.info(
-                "Test that if -bind= is not passed then all addresses are "
+                "Test that if -bind= is not passed or -bind=0.0.0.0 is used then all addresses are "
                 "added to localaddresses")
-        found_addr1 = False
-        found_addr2 = False
-        for local in self.nodes[0].getnetworkinfo()['localaddresses']:
-            if local['address'] == ADDR1:
-                found_addr1 = True
-                assert_equal(local['port'], self.bind_port_0)
-            if local['address'] == ADDR2:
-                found_addr2 = True
-                assert_equal(local['port'], self.bind_port_0)
-        assert found_addr1
-        assert found_addr2
+        for i in [0, 1, 2]:
+            found_addr1 = False
+            found_addr2 = False
+            for local in self.nodes[i].getnetworkinfo()['localaddresses']:
+                if local['address'] == ADDR1:
+                    found_addr1 = True
+                    assert_equal(local['port'], self.bind_ports[i])
+                if local['address'] == ADDR2:
+                    found_addr2 = True
+                    assert_equal(local['port'], self.bind_ports[i])
+            if not found_addr1:
+                self.log.error(f"Address {ADDR1} not found in node{i}'s local addresses: {local}")
+                assert False
+            if not found_addr2:
+                self.log.error(f"Address {ADDR2} not found in node{i}'s local addresses: {local}")
+                assert False
 
         self.log.info(
-                "Test that if -bind= is passed then only that address is "
+                "Test that if -bind=routable_addr is passed then only that address is "
                 "added to localaddresses")
         found_addr1 = False
-        for local in self.nodes[1].getnetworkinfo()['localaddresses']:
+        i = 3
+        for local in self.nodes[i].getnetworkinfo()['localaddresses']:
             if local['address'] == ADDR1:
                 found_addr1 = True
-                assert_equal(local['port'], self.bind_port_1)
+                assert_equal(local['port'], self.bind_ports[i])
             assert_not_equal(local['address'], ADDR2)
         assert found_addr1
 
 if __name__ == '__main__':
     BindPortDiscoverTest(__file__).main()
```

**Review by vasild — COMMENTED** [review]
Approach ACK 776b7ee585

File: src/init.cpp (hunk 1 above)
Comment (b-l-u-e) [reply src/init.cpp]: thank you for the suggestion.

File: test/functional/feature_bind_port_discover.py (hunk 3 above)
Comment (b-l-u-e) [reply test/functional/feature_bind_port_discover.py:36]: thank you for the suggestion..i will make changes

**Comment by b-l-u-e** [comment]
vasild about the `self.extra_args` configuration.

In your patch, node 2 only has `-whitebind=0.0.0.0` without any onion bind:
```python
['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}'], # Explicit -whitebind=0.0.0.0
```

But, when I tried this configuration, I encountered port conflicts because the test framework automatically adds an onion bind to node 2, which conflicts with the port already used by node 1.

Test Results:

Without dummy onion bind (your suggested configuration):
```
Error: Unable to bind to 127.0.0.1:12866 on this computer. Bitcoin Core is probably already running.
Error: Failed to listen on any port. Use -listen=0 if you want this.
```

With dummy onion bind current implementation:
```
TestFramework (INFO): Tests successful
```

The issue is that when using only `-whitebind=0.0.0.0`, the test framework automatically adds an onion bind to the same node, causing a port conflict with other nodes in the test.

So, I added a dummy onion bind:
```python
['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}', f'-bind=127.0.0.1:{self.bind_ports[2]+100}=onion']
```

This ensures the test runs  while still testing the intended `-whitebind=0.0.0.0` functionality.

File: test/functional/feature_bind_port_discover.py [hunk 4]
```diff
@@ -52,28 +78,34 @@ def skip_test_if_missing_module(self):
...
+                    assert_equal(local['port'], self.bind_ports[i])
+                if local['address'] == ADDR2:
+                    found_addr2 = True
+                    assert_equal(local['port'], self.bind_ports[i])
+            if not found_addr1:
+                self.log.error(f"Address {ADDR1} not found in node{i}'s local addresses: {local}")
+                assert False
+            if not found_addr2:
+                self.log.error(f"Address {ADDR2} not found in node{i}'s local addresses: {local}")
+                assert False
```
Comment (pinheadmz) [inline test/functional/feature_bind_port_discover.py:106]: The variable `local` in these lines is being used outside the `for` loop which defines it. If `localaddresses` is empty `[]` the error message itself will cause an error.

**Review by pinheadmz — APPROVED** [review]
ACK ad3f60b0ea59dbbe7aedcfdcca1caddefffe6976

Built and tested on macos/arm64 and debian/x86. Reviewed code changes which are minimal, this PR searches bind settings for 0.0.0.0 specifically to call Discover() which attempts to add local addresses for peer advertising. Also adds test coverage using `1.1.1.1` and `2.2.2.2` which I was able to set up and check locally on both platforms. Also tested on main.

I would really like to know if its possible to run this test in CI as [vasild suggested here](https://github.com/bitcoin/bitcoin/issues/31293#issuecomment-2497792487) and if so, should probably be added to this PR

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK ad3f60b0ea59dbbe7aedcfdcca1caddefffe6976
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmh2awsACgkQ5+KYS2KJ
yTouuhAAmT1tLlOOKdhryZE9K+44Bcsn6prMoLono71Dzf+U+hkQpfxaCcwlI17c
hIW51zz/KZWTudgkDLSWU1RMhCDxMk8XFRdh47TD13OhOVrFJF3Al/uCrMFTXOB5
mPX2c7v6xOvx6DRlqZlCNDKKTOV1gPIM3+vyScmPA68Vh4ibxwzfYK9Lr0ss92fA
ceyCZttPOV6v57dazDn2Lm3siGWfS0+urnwf02TIlShklfW6+juz9AWfa8cmHw8E
GjO0D/r6BNW0TSeHSgt8jpxkVuGxl6opVkn+295hkZ4m9PM44eq7C1avK3yL9exl
LlsGdk9e/vsesJZne+hnppux1xivbfRbze0Z2J3fOpSdckU8mL8TpJlnyoRbQXAo
l3Cawmarwjm7sSQBRZsnAHNw6dN8qQ3ICkCPvK86UG8GLXhG76hcQBZY/NmwMqg7
hl8Np64L3bpH8dHU1Q/9gxHy6h3lPw9GNiOZFaQVvGQZicTzY7WxjhHcAevEHDvu
h9JxUBUPyroHxQkX2vDVBiyLM5pz8FtUOb7MWj5K0bFE1fg6IuY8XZog4BC/zWUL
eTLX330l883y2WoUrILAyrSe1B0HSt0SEh5yOqdwaBAuJ3lcvpht50D+0Z3wPvXU
FShlGSxgvUHBAaDSf/7aG3d48uYkoSKKnek5i65RZIG1oViucUE=
=snJ5
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

File: test/functional/feature_bind_port_discover.py [hunk 5]
```diff
@@ -91,10 +91,10 @@ def run_test(self):
                     found_addr2 = True
                     assert_equal(local['port'], self.bind_ports[i])
             if not found_addr1:
-                self.log.error(f"Address {ADDR1} not found in node{i}'s local addresses: {local}")
+                self.log.error(f"Address {ADDR1} not found in node{i}'s local addresses: {self.nodes[i].getnetworkinfo()['localaddresses']}")
                 assert False
             if not found_addr2:
-                self.log.error(f"Address {ADDR2} not found in node{i}'s local addresses: {local}")
+                self.log.error(f"Address {ADDR2} not found in node{i}'s local addresses: {self.nodes[i].getnetworkinfo()['localaddresses']}")
```
Comment (pinheadmz) [inline test/functional/feature_bind_port_discover.py]: If you really want to log the RPC output, you could capture it in a variable just before the `for local in...` and then iterate that variable inside the for loop, and print it in the error message. It's easy to reproduce this if you need to test it (I had trouble getting 1.1.1.1 and 2.2.2.2 set up on my machine for this test!)

**Review by pinheadmz — COMMENTED** [review]
Thanks for fixing the nit in the test.

In general, nit-fixes should be squashed (not added as an extra commit) so the final commit history is clean and perfect ;-)

Also I think you rebased on master which is ok, but it makes review slightly harder because my local copy of your branch is now dozens of commits different from the current state of the PR. I used `git range-diff` to isolate the changes which is why its not like, a super hard rule, but again in general, try not to rebase on master unless you *have to* (to fix a conflict, include other merged commits, etc)

File: test/functional/feature_bind_port_discover.py [hunk 6]
```diff
@@ -25,19 +26,44 @@
...
+            p2p_port(3),
+            p2p_port(4),
+        ]
         self.extra_args = [
-            ['-discover', f'-port={BIND_PORT}'], # bind on any
-            ['-discover', f'-bind={ADDR1}:{BIND_PORT}'],
+            ['-discover', f'-port={self.bind_ports[0]}', '-listen=1'], # Without any -bind
+            ['-discover', f'-bind=0.0.0.0:{self.bind_ports[1]}'], # Explicit -bind=0.0.0.0
+            # Explicit -whitebind=0.0.0.0, add dummy onion bind to avoid port conflict
+            ['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}', f'-bind=127.0.0.1:{self.bind_ports[2]+100}=onion'],
```
Comment (vasild) [inline test/functional/feature_bind_port_discover.py]: The testing framework is designed so that it can run parallel executions on the same machine. For example, running two separate tests independently at the same time. To avoid port collisions between such independent executions is has `p2p_port(n)` and `tor_port(n)` which allocate ports in a range which (hopefully) will not overlap with the range from another test that executes concurrently (e.g. in another terminal). This `+100` seems a odds with this, maybe it could cause collisions.

I would suggest to use only use `p2p_port()` or `tor_port()`. Something like this:

```diff
--- i/test/functional/feature_bind_port_discover.py
+++ w/test/functional/feature_bind_port_discover.py
@@ -8,12 +8,13 @@ Test that -discover does not add all interfaces' addresses if we listen on only
 
 from test_framework.test_framework import BitcoinTestFramework, SkipTest
 from test_framework.util import (
     assert_equal,
     assert_not_equal,
     p2p_port,
+    tor_port,
 )
 
 # We need to bind to a routable address for this test to exercise the relevant code
 # and also must have another routable address on another interface which must not
 # be named "lo" or "lo0".
 # To set these routable addresses on the machine, use:
@@ -37,14 +38,14 @@ class BindPortDiscoverTest(BitcoinTestFramework):
             p2p_port(3),
             p2p_port(4),
         ]
         self.extra_args = [
             ['-discover', f'-port={self.bind_ports[0]}', '-listen=1'], # Without any -bind
             ['-discover', f'-bind=0.0.0.0:{self.bind_ports[1]}'], # Explicit -bind=0.0.0.0
-            # Explicit -whitebind=0.0.0.0, add dummy onion bind to avoid port conflict
-            ['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}', f'-bind=127.0.0.1:{self.bind_ports[2]+100}=onion'],
+            # Explicit -whitebind=0.0.0.0, add onion bind to avoid port conflict
+            ['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}', f'-bind=127.0.0.1:{tor_port(3)}=onion'],
             ['-discover', f'-bind={ADDR1}:{self.bind_ports[3]}'], # Explicit -bind=routable_addr
         ]
         self.num_nodes = len(self.extra_args)
 
     def setup_network(self):
         """
```

Note: the above patch avoids having `nodes[2]` bind on the same port for whitebind and tor. Without the above patch:

```
Command-line arg: whitebind="0.0.0.0:11107"
...
Bound to 0.0.0.0:11107
Bound to 127.0.0.1:11107
```
with it:
```
Command-line arg: whitebind="0.0.0.0:13642"
...
Bound to 0.0.0.0:13642
Bound to 127.0.0.1:23642
```
if you got it conflicting with the port of `nodes[1]`, then that is a different issue.

**Review by vasild — COMMENTED** [review]
Almost ACK a9b7542b6ea1af770d93cbbf5bb55dae6841334f

> I encountered port conflicts because the test framework automatically adds an onion bind to node 2, 

Hmm, I think it is not the test framework but `bitcoind` itself that adds the onion bind. To figure out how `bitcoind` is started, e.g. for `nodes[2]` I look at `/tmp/bitcoin_func_test_.../node2/regtest/debug.log` for the lines like:
```
...
Config file arg: [regtest] shrinkdebugfile="0"
Config file arg: [regtest] unsafesqlitesync="1"
Command-line arg: bind="127.0.0.1:23642=onion"
Command-line arg: datadir="/tmp/bitcoin_func_test_h7qvveos/node2"
...
```
> which conflicts with the port already used by node 1

Are you sure it is `nodes[1]` and `nodes[2]` conflicting? What is the error message? What is the output of `./test/functional/combine_logs.py |grep 'Bound to'`? I got `nodes[2]` to bind the whitebind and tor on the same port, see my comment below.

**Comment by b-l-u-e** [comment]
My initial assessment that the test framework was automatically adding an onion bind was incorrect... it is `bitcoind` itself that handles the onion bind based on configuration.

about `nodes[1]` and `nodes[2]` conflicting, sorry for the confusion in my previous comment. The primary port conflict I was encountering was not between `nodes[1]` and `nodes[2]`, but rather within `nodes[2]` itself. 

 the issue was raised because `bitcoind` attempted to bind to **`127.0.0.1` on `self.bind_ports[2]`** (due to the `whitebind=0.0.0.0` argument), while also potentially trying to establish an implicit bind or an onion bind on the same port for `127.0.0.1`. This caused the `FailedToStartError: Unable to bind to 127.0.0.1:[port] on this computer.`

suggestion to use `tor_port(3)` to allocate the onion bind port is implemented in the latest commit. the onion bind for `127.0.0.1` uses a distinct, framework-managed port, resolves the binding conflict within `nodes[2]` and aligning with the test framework's design for parallel execution.

**Comment by vasild** [comment]
Better squash the last two commits into one.

**Review by vasild — APPROVED** [review]
ACK 1dc6b1e8b04363107b4b44cbf42f8a25f2efabfe

Thank you!

**Review by pinheadmz — APPROVED** [review]
ACK 1dc6b1e8b04363107b4b44cbf42f8a25f2efabfe

Built and tested on macos/arm64. Reviewed code, minimal changes since last ACK, addressing clean-ups in the test. Tested on mainnet and compared against master to check that local address was discovered when `-bind=0.0.0.0`

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 1dc6b1e8b04363107b4b44cbf42f8a25f2efabfe
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmiA9C8ACgkQ5+KYS2KJ
yTpmvhAAkvyMzMl7iYnSoSFwv/PJs0zGzXbr+iYzp8IrIoNNS7tTZj5S3a4uc6LA
i2aWgAG8NfEcW696R42h6bL2XTIRmLvxbYQyhpZAZRWK9oydK27e2sopsdQFJVxa
+wWcRqjhPLt7vOqzp/BkEQwlU60GLEZ7k52/xfs873F9MhU/u37DD2PkcNvf9nAQ
Y3fNlJYFEA1RBNIBLWTEwkYtKeWS+n2un+nj1APTqHH6rNHRODSYWe/LU2GG2et0
r2JTPEr0bADMi0P5+K8CZEUSsIcnDEcYc+UmayDEKvQu6kvZHXg0LQuNMHRlo7fM
uns5ZK5O+e4AVlBdICGRC70+qWL2C7WOd87gOFqsUYYyz1poYgnvEYHb+mHQh9Ti
juXof2FvxmV6cgdyZJtsAW78poT7Iwkb5Kn3767gum+Y4cGAAOUthVkwxFSZLBuI
j8T5oNC6AUcKegNhrwYD8uZJta/RNGW0Rzud1MQklE4lvmAwSKPJbDR9yHhuwh7R
XFaJmjIR7lE+RGEisQ3fO9FI8KmiUZgovHLaRzBITcTDINhtbyakWeanZHgqto8+
KCsIsoaM/Gk+QCvZifCfdrMxSuTickcCU8XQS53RhTgskAYxluQ4DFGputFi55T7
rXH1m+1hjgF0CmHF4PtiR8uApS1M8KmEnveepIUNbrrjxnTll6o=
=2P0/
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

**Review by mzumsande — COMMENTED** [review]
Does the changed test succeed for others? I tried to follow the instructions and get

```
 test  2025-07-23T21:50:01.787971Z TestFramework (ERROR): Address 1.1.1.1 not found in node0's local addresses: [] 
 test  2025-07-23T21:50:01.788044Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "XXX/bitcoin/32757_bind0000/test/functional/test_framework/test_framework.py", line 195, in main
                                       self.run_test()
                                     File "XXX/32757_bind0000/build/test/functional/feature_bind_port_discover.py", line 97, in run_test
                                       assert False
```
It also fails on master with the different error `assert found_addr1` like #31336 describes.
As an aside, `ifconfig` is deprecated by many linux versions and should probably be replaced by `ip` (though not necessary to do it here).

[Edit]: Using Ubuntu 24.04.2 LTS

**Comment by pinheadmz** [comment]
Test worked for me on mac and failed as expected without 1.1.1.1 and 2.2.2.2

On my system the command was 
`ifconfig en0 alias 1.1.1.1`

**Comment by mzumsande** [comment]
> ifconfig en0 alias 1.1.1.1

ok, you don't add it to the loopback interface.
But the instructions for Linux
`ifconfig lo:0 1.1.1.1/32 up && ifconfig lo:1 2.2.2.2/32 up  # to set up`
do that, while `IFF_LOOPBACK` addresses are being filtered out [here](https://github.com/bitcoin/bitcoin/blob/e17fb86382eafb7ccfddb56bca981f6a12201c85/src/common/netif.cpp#L340). So I don't think the problem from https://github.com/bitcoin/bitcoin/issues/31336 is fixed by this as the OP says.

**Comment by achow101** [comment]
Also seeing @mzumsande's observation if I add the addresses to loopback, but not if I add them to a different interface.

I think it's reasonable to filter out all loopback addresses, so the resolution is probably to just update the instructions to have the addresses bound to a non-loopback interface.

**Comment by pinheadmz** [comment]
If @b-l-u-e is going to retouch to update the instructions in the test comment I'd also really like to see those instructions executed in a CI test as well.

**Comment by mzumsande** [comment]
For me it would also be ok to leave the resolution of #31336 for a separate PR - but this PR shouldn't claim to solve the issue then.

**Comment by b-l-u-e** [comment]
found the issues raised and found the cause.

The test was failing because the instructions were wrong. The original instructions said to use loopback interfaces (`lo:0`, `lo:1`), but the code filters out loopback addresses (line 340 in `netif.cpp`).

This is  what the issue #31336 was reported  so following the instructions got empty local addresses.

tested both scenarios
- Non-loopback interface (`wlo1`): Test passes 
- Loopback interface (`lo`): Test fails as expected

updated the test instructions to be more educational and flexible

-  Uses `ip` commands for Linux
- Uses placeholder names instead of assuming specific interfaces
-  Provides instructions for Linux, macOS, and FreeBSD
-  Explains why loopback interfaces don't work

regarding #31336
This doesn't fix the core loopback filtering issue in #31336. But, it does fix the immediate problem where users following the test instructions get confused

**Comment by Zeegaths** [comment]
I ran these commands on Ubuntu 22.04:

sudo ip addr add 1.1.1.1/32 dev wlo1
sudo ip addr add 2.2.2.2/32 dev wlo1

./build/bin/bitcoind -regtest -bind=0.0.0.0:18444 -discover -daemon
./build/bin/bitcoin-cli -regtest getnetworkinfo | grep -A 10 "localaddresses"

**Result on master:**
"localaddresses": [
  ],
  "warnings": [
    "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
  ]


**Result on PR:**
 "localaddresses": [
    {
      "address": "1.1.1.1",
      "port": 18444,
      "score": 1
    },
    {
      "address": "2.2.2.2",
      "port": 18444,
      "score": 1
    }

Conclusion:
PR successfully fixes the issue described in #31293. When using explicit -bind=0.0.0.0, the Discover() function now correctly runs and discovers local addresses, whereas on master it returns empty localaddresses.

**Review by vasild — APPROVED** [review]
ACK 210dd4061193f221a05c630ef5819f36dde9b15f

It suffices to prefix only the first line of the commit message with "test:".

File: test/functional/feature_bind_port_discover.py [hunk 7]
```diff
@@ -10,34 +10,68 @@
 from test_framework.util import (
     assert_equal,
     assert_not_equal,
+    p2p_port,
+    tor_port,
 )
 
 # We need to bind to a routable address for this test to exercise the relevant code
 # and also must have another routable address on another interface which must not
 # be named "lo" or "lo0".
```
Comment (vasild) [inline test/functional/feature_bind_port_discover.py]: If you retouch, this comment is also outdated and needs a tweak, for example:

```suggestion
# We need to bind to a routable address for this test to exercise the relevant code
# and also must have another routable address. Those addresses must be on an interface
# that is UP and is not a loopback interface (IFF_LOOPBACK).
```

**Comment by vasild** [comment]
> I would really like to know if its possible to run this test in CI ...

> `IFF_LOOPBACK` addresses are being filtered out [here](https://github.com/bitcoin/bitcoin/blob/e17fb86382eafb7ccfddb56bca981f6a12201c85/src/common/netif.cpp#L340). So I don't think the problem from https://github.com/bitcoin/bitcoin/issues/31336 is fixed by this as the OP says.

Both resolved in https://github.com/bitcoin/bitcoin/pull/33362

File: test/functional/feature_bind_port_discover.py (hunk 7 above)
Comment (b-l-u-e) [reply test/functional/feature_bind_port_discover.py]: Thanks for the feedback I will make changes

**Comment by b-l-u-e** [comment]
> Are you still working on this?

Yes am still working on this 
Caught up on something else

**Review by vasild — APPROVED** [review]
ACK e0463f38f15c2bf51b6fd99da369c2ad5271f13e

File: src/init.cpp [hunk 8]
```diff
@@ -2123,7 +2123,26 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
 
-    if (connOptions.bind_on_any) {
+    bool should_discover = connOptions.bind_on_any;
+    if (!should_discover) {
```
Comment (frankomosh) [inline src/init.cpp:2144]: tiny nit(feel free to ignore)

These nested checks could be flattened for readability.  I think eliminating the double-negative (`!should_discover`) pattern would make the logic more declarative?

**Review by frankomosh — COMMENTED** [review]
Code Review ACK [e0463f3](https://github.com/bitcoin/bitcoin/pull/32757/commits/e0463f38f15c2bf51b6fd99da369c2ad5271f13e)

Maybe you could clarify the PR description to reflect that it closes #31293, and #31336 would only be fully resolved with #33362. I think this would accurately reflect that #31336 requires both PRs.

File: src/init.cpp (hunk 8 above)
Comment (b-l-u-e) [reply src/init.cpp:2144]: thank you for the feedback

**Review by vasild — APPROVED** [review]
ACK 69b54df21b0c4dab235ea66525850787bdc963d9

File: test/functional/feature_bind_port_discover.py [hunk 9]
```diff
@@ -10,34 +10,67 @@
...
-            ['-discover', f'-bind={ADDR1}:{BIND_PORT}'],
+            ['-discover', f'-port={self.bind_ports[0]}', '-listen=1'], # Without any -bind
+            ['-discover', f'-bind=0.0.0.0:{self.bind_ports[1]}'], # Explicit -bind=0.0.0.0
+            # Explicit -whitebind=0.0.0.0, add onion bind to avoid port conflict
+            ['-discover', f'-whitebind=0.0.0.0:{self.bind_ports[2]}', f'-bind=127.0.0.1:{tor_port(3)}=onion'],
+            ['-discover', f'-bind={ADDR1}:{self.bind_ports[3]}'], # Explicit -bind=routable_addr
         ]
         self.num_nodes = len(self.extra_args)
 
+    def setup_network(self):
```
Comment (NicolaLS) [inline test/functional/feature_bind_port_discover.py:56]: nit: this improvement should be in a separate commit

Comment (b-l-u-e) [reply test/functional/feature_bind_port_discover.py:56]: Done split into a separate commits

**Comment by NicolaLS** [comment]
tested ACK bb00fd2142288be2da169a3b6ed398a01626827d

Reviewed code changes and tested on macos/arm64 the `feature_bind_port_discover.py` test fails on master because `Discover` is never called, with this PR `Discover` is called when any of whitebind/bind addresses are [IsBindAny](https://github.com/bitcoin/bitcoin/blob/35e6444fdc4068adc79082648f9889ad593e623b/src/netaddress.cpp#L303) (`0.0.0.0` and `::`). The test was improved (documentation/don't connect nodes as chain) and passes now.

I tested that this builds and the test passes I did not manually test this in regtest for example. The test is simple to understand and passes which gives me enough confidence without more testing.

This closes #31293 and prepares for #33362 

Question: would it make sense to also test IPv6 `::` not only `0.0.0.0` here?

**Comment by sedited** [comment]
This has six stale ACKs. Could previous reviewers take another look here?

**Comment by pinheadmz** [comment]
code review bb00fd2142288be2da169a3b6ed398a01626827d

Built and tested on macos/arm64 and debian/x86 and compared against master using lldb, the updated functional test, and playing with the parameters running the node on main net.


In my opinion, the second commit could be removed, since #33362 is fixing the test and running it in CI. Ideally that would be merged before this PR so we can see the test pass before and after the `Discover()` patch.

Otherwise I approve commits 1 and 3, the patch and test

**Review by pinheadmz — APPROVED** [review]
ACK bb00fd2142288be2da169a3b6ed398a01626827d

On second thought actually, keep all 3 commits so we can at least run the test locally. There's another PR to run the test in CI and it can merge before or after.

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK bb00fd2142288be2da169a3b6ed398a01626827d
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCAA5FiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmnXu7cbFIAAAAAABAAO
bWFudTIsMi41KzEuMTIsMCwzAAoJEOfimEtiick6v1wP/RWxuHr/KNsP6PK8mZjg
q17Sa5MD/JRZcXiQpJ07md6PZUvkNu/B+8+vfHEOv9TUMIGzBGh6hztTViXeNVKA
FASlTjVB0+tqu69UqHbgyNxSDjWsXaFNDky45i/RdN7c/88R1uffJGzKVuxY4lBd
967FE/rAh8NMAz+vmhZig65d5K6G6vXFe1Y3+ZgiQDvwznyBP+cIoCSX+W421MrI
XA2/rT3yZOFtRm6XzdZ2h0QWdaqPgCaLSCkmcqyWTOAvgRc291/oC7TX11+U9z4+
0dYgOmzXqJdtG5alwT3wYG0arkZqtAgP9h7cOdLTNRhx8ejSRpGhfyP9ClDWSjrW
LiI57TRKcIlmoKKMN8QBC71Ks/RXw4ojcP/tleK6Seo8c7dkUIvazYKLGDhPKVIj
/SHm1QJgt8Mhwv8k8oWVE/3/m/H7u2I9TjqIo9S9tLF7GXTjEyC51cFJRGt2iCN5
brloq6AKzVYQg+Hf4wwcRcBu0wl2Cknhouvb0Vf0+ajG14zNrHe2U2nT8Y71st98
UCZkmgGEjc/E4VkE9tqBKN0jom4FQamRJDX+VoTrB5ybtrhAg5OlotCfr0agHa54
1xQE079JqRWj+0zDa9yCOtoibbxsnVzvtSmkHzuDEFFalYI+fmH2P3K3YdvH8pxx
luDgr9Jem5GLVQgEc4BJhPye
=Pw5H
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/E61773CD6E01040E2F1BD78CE7E2984B6289C93A)
</details>

**Review by vasild — APPROVED** [review]
ACK bb00fd2142288be2da169a3b6ed398a01626827d

<details>
<summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK bb00fd2142288be2da169a3b6ed398a01626827d
-----BEGIN PGP SIGNATURE-----

iQQzBAEBCAAdFiEE5k2NRWFNsHVF2czBVN8G9ktVy78FAmnX2dEACgkQVN8G9ktV
y7+5CB/8CTAG996zvexTMe7AXOjAMRuXDCH6+uz+M8codANBqu4hPjCAW+YwUX/B
EM4KjUbTMkm2IGeQWR7Ez6ZpRGqvm51Xpuhslh82KH6Ps1i6yPkA8Wy+F8NHfry7
NX3Zqbxqb+12THPQ+vtobAdeerdh2MFhyCNVVpIV8wPo0BVEjrYlOpe1EgWAeVOZ
tZU628DJC9dJ9BfPk/QGNS/ztwdW84iU/HwXhwTdr6dKmDNiIs5F5V1z1wNRLxk4
NL6f35R483fHfHpqOPubf+ZgetbgvsrweNfMosRdGPLtHaivG2MMYsAdQUOHjYwp
TWVP9LEnd1AeSHwMJ5SWxWnD0pThMbkSAgiCFWJZ0X3i/KMwvVCeXca1tc7hVvey
PBLLzM4bRlmpeGug22ehlDAsmGDCOp6RM0r54LtrqrbnbM28hWGtKiTK2EsvbvK1
vpBNdt8x6DviSHJQowOAumshoyaSO0p8ouAsR37nbn38VGFwvW6OKcEzU0nJ/oBX
vKXkPsKOceKtGqZDwKNmhjzj81JvYWOE41MWod4BjwbLD4mgBdF0MSmePbQPkZs2
dCROstPIJLNVwYloR9tKZUtmL9t8lqbhl3BRSoM6r+JtNQvAVmcS1SYfEcyWyWYM
XGG/AOUh8iwrfDcvRfnV49wKzYQkH82tFeDjo2wIUAKQeD3Cb17zFFCv1p2qrk6D
dLDZFRwQEEY1HbTfQBFPx5tkBW9te8fuHb7+YXbRsTy44P+ziT2lvXDMWe4ru5Li
BQPlECJA0msGLDImdxve5Inl3MMsSuhYs8W+M47pstH5Cu+AcYS3KAy9TaUHKyRl
JnzJAO4z3ikvjn02gAA4wUiVSy7R3ZkGbGREXeCMSWQ5SOOwtQTtCLMYnCdRmKsk
w9LyKIqVcKPcC3agIAeKiYkpsVq+tSVSVGys6O9eES826SE+QSmCpTU3j8SEIq/e
4oWEKIr1DyIxWP7R0FTAeQrk0YTJ8FSSGNuspahVHvk1Qm0Z2COLbARHpSkXRU6h
5a9tWc5+yudR8a5eVbMHGanMqZQjnwty84ijCIWoA+6gSeY+XYZ73TmuHCYYjwSE
FuRQ9/s5lBLz8I13hLGrWacjziDKWAva+lKe2Ii+y77z0JNGDSSUMMkzBOkRHX/W
6k+Tnnp7ToBtVor2R7/SE4isyMsnPwTtlMdxR18tBwYzQCzIH3DKsn+/WaLCnYSD
DvMIpueM/b/K9wxfQ3XBktPa5cA+OlgMYyuy/RHnnGN322B36GWJeOBMO18IOXKw
slK+tojYYIc+QTDI5XmikDWsMt0+zsZ8A24QXhq9xO7ZBX/07NpWqGwzXFklPyyE
FRljSj2jTc1uAnKRkW8t7wiwtXRmCQ==
=S9rL
-----END PGP SIGNATURE-----
```

vasild's public key is [on openpgp.org](https://keys.openpgp.org/vks/v1/by-fingerprint/850E138BA9C0923881DFD55FCE712013582E2230)
</details>

File: test/functional/feature_bind_port_discover.py [hunk 10]
```diff
@@ -70,28 +85,35 @@ def skip_test_if_missing_module(self):
...
+            localaddresses = self.nodes[i].getnetworkinfo()['localaddresses']
+            for local in localaddresses:
+                if local['address'] == ADDR1:
+                    found_addr1 = True
+                    assert_equal(local['port'], self.bind_ports[i])
+                if local['address'] == ADDR2:
+                    found_addr2 = True
+                    assert_equal(local['port'], self.bind_ports[i])
+            if not found_addr1:
+                self.log.error(f"Address {ADDR1} not found in node{i}'s local addresses: {localaddresses}")
```
Comment (achow101) [inline test/functional/feature_bind_port_discover.py:102]: In bb00fd2142288be2da169a3b6ed398a01626827d "test: use dynamic ports and add coverage in feature_bind_port_discover"

nit: `assert` can carry an error message, there's no need to do a check and log like this. (for future reference, no followup needed)

**Review by achow101 — COMMENTED** [review]
ACK bb00fd2142288be2da169a3b6ed398a01626827d
