### PR TITLE
[Tests] Suppress output in test_bitcoin for expected errors

### LINKED ISSUE #15944: Path error messages while executing test_bitcoin
Compiled bitcoin-0.18.0.tar.gz from https://bitcoin.org/bin/bitcoin-core-0.18.0/ on Ubuntu 18.04.2 LTS (using [this](http://Bitkoins.nl/maken.txt) (simple) bash script). The compilation went well (had to add doxygen to suppress a warning message). When running the test: `test_bitcoin` in `bitcoin-0.18.0/src/test/`, I get the following error messages (multiple times):

`Error: Specified -walletdir "/tmp/test_bitcoin/1556861148_943311758/tempdir/path_does_not_exist" does not exist`

and

`Error: Specified -walletdir "/tmp/test_bitcoin/1556861730_643733972/tempdir/not_a_directory.dat" is not a directory`

and

`Error: Specified -walletdir "wallets" is a relative path`

Note that at the end it still says: `*** No errors detected`

### PR DESCRIPTION
**Pull request by gertjaap**
Closes #15944 

This adds two methods to noui, that allows temporarily suppressing (and then resuming) the output from `noui`. For situations where errors are expected, it's confusing for the test binary to output an error and then conclude with `No errors detected`.

It also uses this supress/reconnect in the tests that currently produce verbose errors when running `test_bitcoin`.

Output of `test_bitcoin` on current master:
```
gertjaap@gjdesktop:~/src/bitcoin$ src/test/test_bitcoin
Running 351 test cases...
Error: Specified -walletdir "/tmp/test_common_Bitcoin Core/1561389554_943311758/tempdir/path_does_not_exist" does not exist
Error: Specified -walletdir "/tmp/test_common_Bitcoin Core/1561389554_643733972/tempdir/not_a_directory.dat" is not a directory
Error: Specified -walletdir "wallets" is a relative path

*** No errors detected
```

Output after this code is merged:

```
gertjaap@gjdesktop:~/src/bitcoin$ src/test/test_bitcoin
Running 351 test cases...

*** No errors detected
```

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

Thanks for working on this: those expected errors are really annoying.

Nice first-time contribution! Welcome! :-)

**Comment by laanwj** [comment]
Thanks for tackling this, this has been bothering me for a while.

File: src/noui.h [hunk 1]
```diff
@@ -17,4 +19,16 @@ void noui_InitMessage(const std::string& message);
 /** Connect all bitcoind signal handlers */
 void noui_connect();
 
+/** Suppress all bitcoind signal handlers. Used to suppress output during test runs that produce expected errors */
+void noui_suppress();
+
+/** Non-GUI handlers, which just ignore the message. Connected when calling noui_suppress.
```
Comment (laanwj) [inline src/noui.h]: I don't think there's a need to have these three functions externally exposed in the header, they're only used in `noui_suppress`

File: src/wallet/test/init_tests.cpp [hunk 2]
```diff
@@ -7,6 +7,10 @@
 #include <test/setup_common.h>
 #include <wallet/test/init_test_fixture.h>
 
+extern void noui_connect();
```
Comment (laanwj) [inline src/wallet/test/init_tests.cpp]: Why are these `extern void`s here? Doesn't including the header that defines them (`noui.h`) suffice?

File: src/noui.h [hunk 3]
```diff
@@ -5,6 +5,8 @@
 #ifndef BITCOIN_NOUI_H
 #define BITCOIN_NOUI_H
 
+#include <boost/signals2/connection.hpp>
```
Comment (laanwj) [inline src/noui.h]: I don't think these includes need to be added here, better include them in the `cpp` file if they're used there to avoid the boost stuff having to be processed for every compilation unit.

Comment (gertjaap) [reply src/noui.h]: Adjusted

File: src/wallet/test/init_tests.cpp (hunk 2 above)
Comment (gertjaap) [reply src/wallet/test/init_tests.cpp]: Given the noui_connect() was there when I started, I followed the same convention. Have changed it now, removed the `extern void`s and included `noui.h` in stead.

File: src/noui.h (hunk 1 above)
Comment (gertjaap) [reply src/noui.h]: Adjusted

**Comment by gertjaap** [comment]
Addressed review comments and squashed

**Review by mzumsande — APPROVED** [review]
ACK 6d7bcf9, reviewed code and tested his (also checked that reconnect works by suppressing only the first of the three loud tests).
Nice to get rid of these error messages, this might also encourage more negative unit tests that people might have shied away from in fear of spamming stderr even more.

File: src/noui.cpp [hunk 4]
```diff
@@ -4,15 +4,18 @@
 // file COPYING or http://www.opensource.org/licenses/mit-license.php.
 
 #include <noui.h>
-
-#include <ui_interface.h>
-#include <util/system.h>
-
+#include <boost/signals2/connection.hpp>
```
Comment (MarcoFalke) [inline src/noui.cpp]: Why is this line moved?

File: src/noui.cpp [hunk 5]
```diff
@@ -53,7 +56,39 @@ void noui_InitMessage(const std::string& message)
...
+}
+
+bool noui_ThreadSafeMessageBoxSuppressed(const std::string& message, const std::string& caption, unsigned int style)
+{
+    return false;
+}
+
+bool noui_ThreadSafeQuestionSuppressed(const std::string& /* ignored interactive message */, const std::string& message, const std::string& caption, unsigned int style)
+{
+    return false;
```
Comment (MarcoFalke) [inline src/noui.cpp]: Instead of ignoring the message in the test, shouldn't the test check for the correct messag?

File: src/noui.cpp (hunk 4 above)
Comment (gertjaap) [reply src/noui.cpp]: I incorrectly assumed that these imports were alphabetically sorted. This turns out not to be the case. I'll revert this

File: src/noui.cpp (hunk 5 above)
Comment (gertjaap) [reply src/noui.cpp]: While that's a nice feature to have, this isn't being done currently as well. It would require a much bigger change to achieve that, giving the opportunity to the caller of noui_supress to supply an expected error, or noui_suppress to retain whatever messages are being thrown to it, and adding a method to retrieve them in the test and do assertions on it. I would however prefer to do this in an additional PR on top of this one.

Comment (MarcoFalke) [reply src/noui.cpp]: Right now at least the test runner can check for the correct reason by reading the stdour (or err). You take that option without providing an alternative.

Comment (practicalswift) [reply src/noui.cpp]: Is that feature used somewhere?

If not I suggest that feature can be added when needed.

Would be nice to get this merged.

Comment (gertjaap) [reply src/noui.cpp]: I don't think i'm taking any option away: The suppressing only happens when you explicitly call `noui_suppress()`. So the default is to still print it to stdout, which could be useful if a test needs it. The places that are producing the unwanted output were not using stdout and i'm providing a way for those tests to selectively suppress it.

**Comment by gertjaap** [comment]
Addressed review comment & squashed

File: src/noui.cpp (hunk 5 above)
Comment (MarcoFalke) [reply src/noui.cpp]: I don't think there is a use case in suppressing the output with no option to read it

Comment (gertjaap) [reply src/noui.cpp]: The output is not being checked as it stands. If not checking the output is a problem in itself, then that deserves a fix _too_, but is not the scope of what I was aiming for with this PR.

**Comment by laanwj** [comment]
So a future change after this would be to make it possible to catch the output, and retrieve it for checking, as well as suppressing it. I think that could be done in a future PR and do think this making the test output not contain unexpected errors is an improvement, as-is.

**Comment by l2a5b1** [comment]
Suppressing the output is one way to solve to issue.

However, I don't think that we are addressing the fundamental issue, which is that `VerifyWallets` doesn't propagate error information to the caller. Instead `VerifyWallets` keeps that information to itself.

Functions like `VerifyWallets`, which don't provide error information to the caller and seem to use logging of the error message as a substitute, should ideally return an expected success or error object to the caller to allow it to handle *recoverable errors*.

With a Rust-like `Result<T, E>` type we can address #15944 in a generic way, as follows:

```
// VerifyWallet returns an error object of type std::string.
Result<void, std::string> result = VerifyWallets(...);

// The caller handles recoverable errors in the way it deems appropriate.
if (error result) {
    log error;
    return;
}
```

I dropped WIP code here https://github.com/bitcoin/bitcoin/compare/master...l2a5b1:feature/result-type?expand=1 that shows how we can handle recoverable errors with a `Result<T,E>` type as an alternative to returning a `bool` and hiding error information from the caller.

This code also fixes #15944 but it does this by way of propagating the error information to the caller, allowing the caller to log the error message or to ignore it in the tests.

If suppressing output is however preferred then this PR seems like a nice way to do it!

**Comment by MarcoFalke** [comment]
I do like the idea of a `Result` type. Are there any C++ libraries that use or offer (or plan to offer) such a type? I.e boost or the standard library.

This sounds like it would benefit from a project-wide discussion. Maybe open a brainstorming issue or raise the topic in one of the meetings.

**Comment by laanwj** [comment]
Yess, I too prefer rust's method of error handling, but I think asking a first-time contributor to rewrite the project's general error-handling methodology is a bit wild, please take that into account here.

**Comment by KaosGhostNINJA** [comment]
Already working on fix for that error type scenario may not be exactly the
way rust method. I  think  it will have the same effect  will see🤞better
then a rewrite anyway.

**Comment by gertjaap** [comment]
I like the suggestion @l2a5b1 made, of a `Result<T, E>` return value to functions that now return `bool` and don't propagate error info. I think the project would benefit a lot from something like that. That said, it seems like something we should discuss in broader perspective as @MarcoFalke suggested. I'd be happy to contribute to that discussion and/or help implementing the preferred solution.

I enjoy thinking about larger refactoring as much as the next guy, and if this PR triggers a broader discussion that ends up improving Bitcoin's error-handling, then I'll take that as a win. I do however think that this broader discussion might take time and effort, where this PR provides an - in my view - acceptable solution to the problem it's addressing _today_, and is solving something people are actually annoyed by for some time.

**Comment by l2a5b1** [comment]
ACK 7a0c224 - tested and reviewed.

Thanks @gertjaap! I will take the suggestion pertaining to propagating errors somewhere else.

File: src/noui.cpp [hunk 6]
```diff
@@ -53,7 +59,39 @@ void noui_InitMessage(const std::string& message)
...
+    noui_InitMessageConn = uiInterface.InitMessage_connect(noui_InitMessageSuppressed);
+}
+
+void noui_reconnect()
+{
+    noui_ThreadSafeMessageBoxConn.disconnect();
+    noui_ThreadSafeQuestionConn.disconnect();
+    noui_InitMessageConn.disconnect();
+    noui_connect();
+}
```
Comment (l2a5b1) [inline src/noui.cpp]: Add newline :)

**Comment by laanwj** [comment]
ACK 7a0c2242890549b6dddac4cc6f1840a528469f2a
