### PR TITLE
Warn unrecognised sections in the config file

### LINKED ISSUE #14702: Warn if unrecognised sections are present in bitcoin.conf
Suggested by @MarcoFalke after #14627 and possibly #14420. We should warn if an unrecognised/incorrect section is present in bitcoin.conf. i.e `[testnet]` is present instead of `[test]`.

### PR DESCRIPTION
**Pull request by AkioNak**
This PR intends to resolve #14702.

In the config file, sections are specified by square bracket pair "[]"$,
or included in the option name itself which separated by a period"(.)".

Typicaly, [testnet] is not a correct section name and specified options
in that section are ignored but user cannot recognize what is happen.

So, add some log-warning messages if unrecognized section names are
present in the config file after checking section only args.

note: Currentry, followings are out of scope of this PR.
1) Empty section name or option name can describe.
e.g. [] , .a=b, =c
2) Multiple period characters can exist in the section name and option name.
e.g. [c.d.e], [..], f.g.h.i=j, ..=k

### CODE REVIEW

File: src/util/system.cpp [hunk 1]
```diff
@@ -402,6 +408,26 @@ void ArgsManager::WarnForSectionOnlyArgs()
...
+    for (const auto& arg: m_config_args) {
+        if ((pos = arg.first.rfind('.')) != std::string::npos) {
+            m_config_sections.insert(arg.first.substr(1, pos - 1));
+        }
+    }
+    std::set_difference(
+        m_config_sections.begin(), m_config_sections.end(),
+        m_available_sections.begin(), m_available_sections.end(),
+        std::inserter(diff, diff.end()));
+    for (const auto& name: diff) {
```
Comment (promag) [inline src/util/system.cpp]: nit, add space before `:`. Same throughout.

File: src/util/system.h [hunk 2]
```diff
@@ -148,6 +148,8 @@ class ArgsManager
     std::string m_network GUARDED_BY(cs_args);
     std::set<std::string> m_network_only_args GUARDED_BY(cs_args);
     std::map<OptionsCategory, std::map<std::string, Arg>> m_available_args GUARDED_BY(cs_args);
+    std::set<std::string> m_config_sections GUARDED_BY(cs_args);
+    std::set<std::string> m_available_sections GUARDED_BY(cs_args);
```
Comment (promag) [inline src/util/system.h]: This could be a static const variable in system.cpp?

File: src/util/system.h [hunk 3]
```diff
@@ -170,6 +172,11 @@ class ArgsManager
      */
     void WarnForSectionOnlyArgs();
 
+    /**
+     * Log warnings for unrecognized section names in the config file.
+     */
+    void WarnForUnrecognizedSection();
```
Comment (promag) [inline src/util/system.h]: nit, const.

File: src/util/system.cpp [hunk 4]
```diff
@@ -833,7 +859,9 @@ static bool GetConfigOptions(std::istream& stream, std::string& error, std::vect
         str = TrimString(str, pattern);
         if (!str.empty()) {
             if (*str.begin() == '[' && *str.rbegin() == ']') {
-                prefix = str.substr(1, str.size() - 2) + '.';
+                prefix = str.substr(1, str.size() - 2);
```
Comment (promag) [inline src/util/system.cpp]: nit
```cpp
const std::string section = str.substr(1, str.size() - 2);
sections.insert(section);
prefix = section + '.';
```

**Review by promag — COMMENTED** [review]
Tested ACK but I'd like to get feedback on my comments, looks like it has unnecessary changes.

File: src/util/system.cpp [hunk 5]
```diff
@@ -402,6 +408,26 @@ void ArgsManager::WarnForSectionOnlyArgs()
...
 
+void ArgsManager::WarnForUnrecognizedSection()
+{
+    std::string::size_type pos;
+    std::set<std::string> diff;
+
+    LOCK(cs_args);
+    for (const auto& arg: m_config_args) {
+        if ((pos = arg.first.rfind('.')) != std::string::npos) {
+            m_config_sections.insert(arg.first.substr(1, pos - 1));
```
[the remark this answers is not in the document]
Comment (AkioNak) [reply src/util/system.cpp]: Moved them to ```GetConfigOptions```.

File: src/util/system.cpp (hunk 1 above)
Comment (AkioNak) [reply src/util/system.cpp]: done.

File: src/util/system.h (hunk 2 above)
Comment (AkioNak) [reply src/util/system.h]: Yes. changed to a static const valiable.

File: src/util/system.h (hunk 3 above)
Comment (AkioNak) [reply src/util/system.h]: dono.

File: src/util/system.cpp (hunk 4 above)
Comment (AkioNak) [reply src/util/system.cpp]: done.

**Comment by AkioNak** [comment]
@promag I've fixed what you pointed out. Please re-review :-)

File: src/util/system.cpp [hunk 6]
```diff
@@ -820,7 +841,7 @@ static std::string TrimString(const std::string& str, const std::string& pattern
     return str.substr(front, end - front + 1);
 }
 
-static bool GetConfigOptions(std::istream& stream, std::string& error, std::vector<std::pair<std::string, std::string>> &options)
+static bool GetConfigOptions(std::istream& stream, std::string& error, std::vector<std::pair<std::string, std::string>> &options, std::set<std::string> &sections)
```
Comment (promag) [inline src/util/system.cpp]: nit, space should be after `&` for new code.

File: src/util/system.cpp [hunk 7]
```diff
@@ -356,6 +356,13 @@ static bool InterpretNegatedOption(std::string& key, std::string& val)
     return false;
 }
 
+// Section names to be recognized in the config file.
+const std::set<std::string> ArgsManager::m_available_sections{
```
Comment (promag) [inline src/util/system.cpp]: IMO this doesn't have to be exposed in the class and currently it's only necessary in this unit. Suggestion: `static const std::set<std::string> G_CONFIG_SECTIONS{...}` and remove from header.

**Review by promag — COMMENTED** [review]
Thanks, looks good to me, just adding 2 small comments for your consideration.

File: src/util/system.cpp (hunk 6 above)
Comment (AkioNak) [reply src/util/system.cpp]: Oh, thanks.

File: src/util/system.cpp (hunk 7 above)
Comment (AkioNak) [reply src/util/system.cpp]: I agree with your opinion. I will fix it tomorrow.

File: src/util/system.cpp (hunk 6 above)
Comment (AkioNak) [reply src/util/system.cpp]: done.

File: src/util/system.cpp (hunk 7 above)
Comment (AkioNak) [reply src/util/system.cpp]: @promag fixed and move it just before the place to refer it.

File: src/util/system.h [hunk 8]
```diff
@@ -170,6 +171,11 @@ class ArgsManager
      */
     void WarnForSectionOnlyArgs();
```
Comment (MarcoFalke) [inline src/util/system.h]: For completeness, could make this const as well?

File: src/util/system.cpp [hunk 9]
```diff
@@ -402,6 +402,27 @@ void ArgsManager::WarnForSectionOnlyArgs()
...
+{
+    std::set<std::string> diff;
+
+    LOCK(cs_args);
+    std::set_difference(
+        m_config_sections.begin(), m_config_sections.end(),
+        G_CONFIG_SECTIONS.begin(), G_CONFIG_SECTIONS.end(),
+        std::inserter(diff, diff.end()));
+    for (const auto& name : diff) {
+        LogPrintf("Warning: Section [%s] is not recognized.\n", name);
```
Comment (MarcoFalke) [inline src/util/system.cpp]: Hmm. This only ends up in the debug log. However, I think that warnings could as well be printed out. (See how `InitError()` does it.)

Not sure if that suggestion makes sense, but if applied you could probably also write a test case like this:

```diff
diff --git a/test/functional/feature_config_args.py b/test/functional/feature_config_args.py
index 88a9aadc7b..55ef46d253 100755
--- a/test/functional/feature_config_args.py
+++ b/test/functional/feature_config_args.py
@@ -33,6 +33,11 @@ class ConfArgsTest(BitcoinTestFramework):
             conf.write('server=1\nrpcuser=someuser\nrpcpassword=some#pass')
         self.nodes[0].assert_start_raises_init_error(expected_msg='Error reading configuration file: parse error on line 3, using # in rpcpassword can be ambiguous and should be avoided')
 
+        with open(inc_conf_file_path, 'w', encoding='utf-8') as conf:
+            conf.write('testneettt.datadir=1')
+        self.restart_node(0)
+        self.nodes[0].stop_node(expected_stderr='Warning: Section [testneettt] is not recognized.')
+
         with open(inc_conf_file_path, 'w', encoding='utf-8') as conf:
             conf.write('')  # clear

**Review by maflcko — APPROVED** [review]
utACK 23e3619c924560f31a01f5cdb31b4bda9df93324 (Could squash commits?)

File: src/util/system.h (hunk 8 above)
Comment (AkioNak) [reply src/util/system.h]: sure.

File: src/util/system.cpp (hunk 9 above)
Comment (AkioNak) [reply src/util/system.cpp]: @MarcoFalke Thanks for your suggestion. I think it will be more useful. I'll try it.

File: src/util/system.h (hunk 8 above)
Comment (AkioNak) [reply src/util/system.h]: done.

File: src/util/system.cpp (hunk 9 above)
Comment (AkioNak) [reply src/util/system.cpp]: done.

Comment (AkioNak) [reply src/util/system.cpp]: I could not write a test case for WarnForSectionOnlyArgs().
Because I could not found simple way that how to produce the situation that WarnForSectionOnlyArgs() warn and to continue to run through the test.

File: src/util/system.cpp [hunk 10]
```diff
@@ -398,7 +399,30 @@ void ArgsManager::WarnForSectionOnlyArgs()
         if (!found_result.first) continue;
 
         // otherwise, issue a warning
-        LogPrintf("Warning: Config setting for %s only applied on %s network when in [%s] section.\n", arg, m_network, m_network);
+        const std::string msg = strprintf("Config setting for %s only applied on %s network when in [%s] section.", arg, m_network, m_network);
+        uiInterface.ThreadSafeMessageBox(msg, "", CClientUIInterface::MSG_WARNING);
```
[the remark this answers is not in the document]
Comment (AkioNak) [reply src/util/system.cpp]: Addressed. Please re-review.

**Comment by MarcoFalke** [comment]
utACK ecfc35ce9bfb297f01344f565bfa771bf3c6ac72. Thanks for fixing up all the feedback!

File: src/util/system.cpp [hunk 11]
```diff
@@ -398,8 +400,28 @@ void ArgsManager::WarnForSectionOnlyArgs()
...
     }
+    return unsuitables;
+}
+
+// Section names to be recognized in the config file.
+static const std::set<std::string> G_CONFIG_SECTIONS{
+    CBaseChainParams::REGTEST,
+    CBaseChainParams::TESTNET,
+    CBaseChainParams::MAIN
+};
```
Comment (MarcoFalke) [inline src/util/system.cpp]: nit: Could reduce scope even further and move it into the function below? (Keeping the `static const` ...)

**Review by maflcko — COMMENTED** [review]
I haven't looked at the appveyor failure but it could be caused by static initialization issues based on ordering (a global is initialized on another globals value, but before the other global was initialized). So maybe `G_CONFIG_SECTIONS` is just the set with the empty string in it on appveyor?

Could at least rule that out by trying the refactoring I suggested in this review.

File: test/functional/feature_config_args.py [hunk 12]
```diff
@@ -33,6 +33,11 @@ def test_config_file_parser(self):
             conf.write('server=1\nrpcuser=someuser\nrpcpassword=some#pass')
         self.nodes[0].assert_start_raises_init_error(expected_msg='Error reading configuration file: parse error on line 3, using # in rpcpassword can be ambiguous and should be avoided')
 
+        with open(inc_conf_file_path, 'w', encoding='utf-8') as conf:
+            conf.write('testnot.datadir=1\n[testnet]\n')
+        self.restart_node(0)
+        self.nodes[0].stop_node(expected_stderr='Warning: Section [testnet] is not recognized.\nWarning: Section [testnot] is not recognized.')
```
Comment (AkioNak) [inline test/functional/feature_config_args.py]: Self review: ```os.linesep``` is better way to represent multiple lines in ```expected_stderr```.

File: src/util/system.cpp (hunk 11 above)
Comment (AkioNak) [reply src/util/system.cpp]: Fixed.

File: test/functional/feature_config_args.py (hunk 12 above)
Comment (AkioNak) [reply test/functional/feature_config_args.py]: Fixed.

**Comment by MarcoFalke** [comment]
re-utACK 3fb09b9889665a24b34f25e9d1385a05058a28b7

Only change was the suggested refactoring to fix the appveyor build.

**Comment by promag** [comment]
utACK 3fb09b9.
