### PR TITLE
rpc: replace wallet raw pointers with references (#18592 rebased)

### LINKED ISSUE #18590: rpc: raw pointers should be replaced with shared_ptr
While working on this PR https://github.com/bitcoin/bitcoin/pull/18570 I ran into a bit confusing situation where in one function a **CWallet reference** was expected while two others dealt with **CWallet pointers**. My initial reaction was: `let's harmonize them by making them references`. However, not being part of the PR itself I did't change anything and completed the PR first.

Now, after having analyzed the `rpcwallet.cpp` code I came to the conclusion that:

* converting them all into references is not the solution as they're originally **shared_ptr**s
* but also: there is no (visible) reason why every RPC function should begin like this:

```cpp
std::shared_ptr<CWallet> const pwallet = GetWalletForJSONRPCRequest(request);
const CWallet* const pwallet = wallet.get();
```

This clearly defeats the purpose of shared pointers for no obvious reason. *Maybe I am missing something?*

In my (unpublished) [code changes](https://github.com/brakmic/bitcoin/commit/0b3ee615491edf6f542631bf6ae6f72eac406550) all raw pointers got replaced with **shared_ptr**s but kept their original names (that is, *pwallet*). In the end, they're pointers too, so the most of the original code remained untouched.

However, some of the helper functions couldn't be changed because external code is accessing them and I didn't want to make this task "virulent". So I introduced new ("Ref") variants that expect **shared_ptr** parameters, namely: 

```cpp
void EnsureWalletRefIsUnlocked(const std::shared_ptr<CWallet>);
bool EnsureWalletRefIsAvailable(const std::shared_ptr<CWallet>, bool avoidException);
```

I have tested the code, with python and boost-tests, and could not find any errors. 
But before opening a PR I would like to open a discussion about this. 

Is there any reason to keep on working with raw pointers when every function call actually begins with *shared_ptr*s?

Regards,

### PR DESCRIPTION
**Pull request by fanquake**
This is a rebased #18592.

> This PR replaces raw pointers in `rpcwallet.cpp` and `rpcdump.cpp` with **shared_ptr**. The motivation for this PR is described here https://github.com/bitcoin/bitcoin/issues/18590

> It seems that this PR is indirectly related to this issue: https://github.com/bitcoin/bitcoin/pull/13063#discussion_r186740049

> Notice: I have deliberately **not** changed the class `WalletRescanReserver ` whose constructor expects a raw pointer, because it's external and affects other areas, which I didn't touch to avoid making this PR "viral".

> Fixes https://github.com/bitcoin/bitcoin/issues/18590

### CODE REVIEW

**Comment by MarcoFalke** [comment]
(edited title)

File: src/wallet/rpcdump.cpp [hunk 1]
```diff
@@ -1768,20 +1758,20 @@ RPCHelpMan listdescriptors()
         },
         [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
 {
-    std::shared_ptr<CWallet> const wallet = GetWalletForJSONRPCRequest(request);
-    if (!wallet) return NullUniValue;
+    std::shared_ptr<CWallet> const pwallet = GetWalletForJSONRPCRequest(request);
```
Comment (jnewbery) [inline src/wallet/rpcdump.cpp:1761]: Our style is no longer to use `pthing` as the name for pointer variables, but I guess you did this to be consistent with the other functions in this file.

**Review by jnewbery — COMMENTED** [review]
utACK 199c81f5fb54fa9d944968bf35c505e3941ddf67

I think this would be much easier to review if it was split into two commits:

1. Remove all the `CWallet* const pwallet = wallet.get()` lines and rename wallet to pwallet.
2. Change the function signatures to take references instead of pointers.

**Comment by practicalswift** [comment]
Super Strong Concept ACK for safety reasons: pre-conditions should be stated explicitly and be enforced at compile-time where possible.

Thanks for tackling these!

I stumbled upon a similar case in the networking code the other day. More generally it seems like there are a few functions in our case base where we take `T*` instead of `T&` in places where we don't safely handle the `nullptr` case. That's quite confusing and potentially dangerous. I think it makes sense to convert these from `T*` to `T&` gradually over time. This PR is a good start :)

---

More specifically …

```c++
void f_1(T& t) { t.foo(); }
```

… is preferable over …

```c++
void f_2(T* t) { t->foo(); }
```

Live demo:

```c++
$ cat nullptr-deref.cpp
#include <iostream>

struct T {
    void foo() { std::cout << this << "->foo()\n"; }
};

void f_1(T& t) { t.foo(); }

void f_2(T* t) { t->foo(); }

int main(void)
{
    T t;
    f_1(t);
    f_2(&t);

    // f_1(nullptr); // compile time error: no known conversion from nullptr_t to T&
    f_2(nullptr);
}
$ clang++ -o nullptr-deref nullptr-deref.cpp && ./nullptr-deref
0x7fff9e191234->foo()
0x7fff9e191234->foo()
0->foo()
$ g++ -o nullptr-deref nullptr-deref.cpp && ./nullptr-deref
0x7fff9e191234->foo()
0x7fff9e191234->foo()
0->foo()
$ clang++ -fsanitize=undefined -o nullptr-deref nullptr-deref.cpp && ./nullptr-deref
0x7fff9e191234->foo()
0x7fff9e191234->foo()
nullptr-deref.cpp:10:21: runtime error: member call on null pointer of type 'T'
nullptr-deref.cpp:5:10: runtime error: member call on null pointer of type 'T *'
0->foo()
```

Note how `void f_1(nullptr)` gives a nice compile-time error whereas `f_2(nullptr)` gives a run-time WTF (at best) :)

File: src/wallet/rpcdump.cpp (hunk 1 above)
Comment (fanquake) [reply src/wallet/rpcdump.cpp:1761]: Yea it's done to keep the diff to a minimum, otherwise we'd also have to rename all the pwallet usage in each function.

**Comment by fanquake** [comment]
> I think this would be much easier to review if it was split into two commits:

This is now split into two commits.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 7c90c67b7e6f598f9ffdc136ded2b533b78ed044. Changes easy to review with `--word-diff-regex=. -U0`
