### PR TITLE
util: Revert "common: Close non-std fds before exec in RunCommandJSON"

### LINKED ISSUE #32524: intermittent issue in rpc_signer.py (enumeratesigners timeout) under GLIBCXX debug mode
https://cirrus-ci.com/task/5094568045051904?logs=ci#L4419

```
[18:26:32.573] test_framework.authproxy.JSONRPCException: 'enumeratesigners' RPC took longer than 1200.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
```

Looking at the full log, the test is just idle and then times out. However, there is no indication why the RPC does not proceed.

### LINKED ISSUE #32855: intermittent timeout in wallet_signer.py : 'createwallet' RPC took longer than 1200.000000 seconds
in the `multiprocess, i686, DEBUG` task in `self.nodes[1].createwallet(wallet_name='hww_disconnect', disable_private_keys=True, external_signer=True)`,

https://cirrus-ci.com/task/5704849158832128?logs=ci#L2967:

```
 node1 2025-06-26T14:05:40.072184Z [msghand] [net_processing.cpp:3452] [ProcessMessage] [net] received: pong (8 bytes) peer=0 
 test  2025-06-26T14:05:43.222938Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/ci_container_base/test/functional/test_framework/authproxy.py", line 174, in _get_response
                                       http_response = self.__conn.getresponse()
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/usr/lib/python3.12/http/client.py", line 1428, in getresponse
                                       response.begin()
                                     File "/usr/lib/python3.12/http/client.py", line 331, in begin
                                       version, status, reason = self._read_status()
                                                                 ^^^^^^^^^^^^^^^^^^^
                                     File "/usr/lib/python3.12/http/client.py", line 292, in _read_status
                                       line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/usr/lib/python3.12/socket.py", line 707, in readinto
                                       return self._sock.recv_into(b)
                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                   TimeoutError: timed out
                                   During handling of the above exception, another exception occurred:
                                   Traceback (most recent call last):
                                     File "/ci_container_base/test/functional/test_framework/test_framework.py", line 190, in main
                                       self.run_test()
                                     File "/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/wallet_signer.py", line 59, in run_test
                                       self.test_disconnected_signer()
                                     File "/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/wallet_signer.py", line 246, in test_disconnected_signer
                                       self.nodes[1].createwallet(wallet_name='hww_disconnect', disable_private_keys=True, external_signer=True)
                                     File "/ci_container_base/test/functional/test_framework/coverage.py", line 50, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/ci_container_base/test/functional/test_framework/authproxy.py", line 137, in __call__
                                       response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/ci_container_base/test/functional/test_framework/authproxy.py", line 111, in _request
                                       return self._get_response()
                                              ^^^^^^^^^^^^^^^^^^^^
                                     File "/ci_container_base/test/functional/test_framework/authproxy.py", line 176, in _get_response
                                       raise JSONRPCException({
                                   test_framework.authproxy.JSONRPCException: 'createwallet' RPC took longer than 1200.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
 test  2025-06-26T14:05:43.230396Z TestFramework (DEBUG): Closing down network thread

### LINKED ISSUE #33015: intermittent timeout in wallet_signer.py : sendall timed out
https://cirrus-ci.com/task/6466141373071360?logs=ci#L1714:
```bash
[17:24:42.699]  node1 2025-07-18T21:24:35.153536Z [scheduler] [net.cpp:2387] [void CConnman::DumpAddresses()] [net] Flushed 0 addresses to peers.dat  0ms 
[17:24:42.699]  node0 2025-07-18T21:24:35.182594Z [scheduler] [net.cpp:2387] [void CConnman::DumpAddresses()] [net] Flushed 0 addresses to peers.dat  1ms 
[17:24:42.699]  test  2025-07-18T21:24:41.997879Z TestFramework (ERROR): Called Process failed with 'error: timeout on transient error: Could not connect to the server 127.0.0.1:21617 (error code 0 - "timeout reached") 
[17:24:42.699]                                    Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
[17:24:42.699]                                    Use "bitcoin-cli -help" for more info.
[17:24:42.699]                                    '
[17:24:42.699]                                    Traceback (most recent call last):
[17:24:42.699]                                      File "/ci_container_base/test/functional/test_framework/test_framework.py", line 195, in main
[17:24:42.699]                                        self.run_test()
[17:24:42.699]                                      File "/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/wallet_signer.py", line 58, in run_test
[17:24:42.699]                                        self.test_valid_signer()
[17:24:42.699]                                      File "/ci_container_base/ci/scratch/build-i686-pc-linux-gnu/test/functional/wallet_signer.py", line 212, in test_valid_signer
[17:24:42.699]                                        res = hww.sendall(recipients=[{dest:0.5}, hww.getrawchangeaddress()], add_to_wallet=False)
[17:24:42.699]                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[17:24:42.699]                                      File "/ci_container_base/test/functional/test_framework/test_node.py", line 873, in __call__
[17:24:42.699]                                        return self.cli.send_cli(self.command, *args, **kwargs)
[17:24:42.699]                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[17:24:42.699]                                      File "/ci_container_base/test/functional/test_framework/test_node.py", line 950, in send_cli
[17:24:42.699]                                        raise subprocess.CalledProcessError(returncode, p_args, output=cli_stderr)
[17:24:42.699]                                    subprocess.CalledProcessError: Command '['bitcoin', '-m', 'rpc', '-nonamed', '-datadir=/ci_container_base/ci/scratch/test_runner/test_runner_₿_🏃_20250718_205643/wallet_signer_218/node1', '-rpcwallet=hww', '-named', 'sendall', 'recipients=[{"bcrt1qw74qtc8277thn0y0v8qd5xahn583utnftrn6f5": 0.5}, "bcrt1q9klcdx4zrgf7m95zhpwfm0lalk92a2rh3swq85"]', 'add_to_wallet=false']' returned non-zero exit status 1.
[17:24:42.699]  test  2025-07-18T21:24:42.002020Z TestFramework (DEBUG): Closing down network thread 
```

### PR DESCRIPTION
**Pull request by maflcko**
After a fork() in a multithreaded program, the child can safely
call only async-signal-safe functions (see [signal-safety(7)](https://www.man7.org/linux/man-pages/man7/signal-safety.7.html))
until such time as it calls execv.

The standard library (`std` namespace) is not async-signal-safe. Also, `throw`, isn't.

There was an alternative implementation using `readdir` (https://github.com/bitcoin/bitcoin/pull/32529), but that isn't async-signal-safe either, and that implementation was still using `throw`.

So temporarily revert this feature.

A follow-up in the future can add it back, using only async-signal-safe functions, or by using a different approach.

Fixes https://github.com/bitcoin/bitcoin/issues/32524
Fixes https://github.com/bitcoin/bitcoin/issues/33015
Fixes https://github.com/bitcoin/bitcoin/issues/32855

For reference, a failure can manifest in the GCC debug mode:

* While `fork`ing, a debug mode mutex is held (by any other thread).
* The `fork`ed child tries to use the stdard libary before `execv` and deadlocks.

This may look like the following:

```
(gdb) thread apply all bt 

Thread 1 (Thread 0xf58f4b40 (LWP 774911) "b-httpworker.2"):
#0  0xf7f4f589 in __kernel_vsyscall ()
#1  0xf79e467e in ?? () from /lib32/libc.so.6
#2  0xf79eb582 in pthread_mutex_lock () from /lib32/libc.so.6
#3  0xf7d93bf2 in ?? () from /lib32/libstdc++.so.6
#4  0xf7d93f36 in __gnu_debug::_Safe_iterator_base::_M_attach(__gnu_debug::_Safe_sequence_base*, bool) () from /lib32/libstdc++.so.6
#5  0x5668810a in __gnu_debug::_Safe_iterator_base::_Safe_iterator_base (this=0xf58f13ac, __seq=0xf58f13f8, __constant=false) at /bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/debug/safe_base.h:91
#6  0x56ddfb50 in __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<int*, std::__cxx1998::vector<int, std::allocator<int> > >, std::__debug::vector<int, std::allocator<int> >, std::forward_iterator_tag>::_Safe_iterator (this=0xf58f13a8, __i=3, __seq=0xf58f13f8) at /bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/debug/safe_iterator.h:162
#7  0x56ddfacb in __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<int*, std::__cxx1998::vector<int, std::allocator<int> > >, std::__debug::vector<int, std::allocator<int> >, std::bidirectional_iterator_tag>::_Safe_iterator (this=0xf58f13a8, __i=3, __seq=0xf58f13f8) at /bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/debug/safe_iterator.h:539
#8  0x56ddfa5b in __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<int*, std::__cxx1998::vector<int, std::allocator<int> > >, std::__debug::vector<int, std::allocator<int> >, std::random_access_iterator_tag>::_Safe_iterator (this=0xf58f13a8, __i=3, __seq=0xf58f13f8) at /bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/debug/safe_iterator.h:687
#9  0x56ddd3f6 in std::__debug::vector<int, std::allocator<int> >::begin (this=0xf58f13f8) at /bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/debug/vector:300
#10 0x57d83701 in subprocess::detail::Child::execute_child (this=0xf58f156c) at ./util/subprocess.h:1372
#11 0x57d80a7c in subprocess::Popen::execute_process (this=0xf58f1cd8) at ./util/subprocess.h:1231
#12 0x57d6d2b4 in subprocess::Popen::Popen<subprocess::input, subprocess::output, subprocess::error, subprocess::close_fds> (this=0xf58f1cd8, cmd_args="fake.py enumerate", args=..., args=..., args=..., args=...) at ./util/subprocess.h:964
#13 0x57d6b597 in RunCommandParseJSON (str_command="fake.py enumerate", str_std_in="") at ./common/run_command.cpp:27
#14 0x57a90547 in ExternalSigner::Enumerate (command="fake.py", signers=std::__debug::vector of length 0, capacity 0, chain="regtest") at ./external_signer.cpp:28
#15 0x56defdab in enumeratesigners()::$_0::operator()(RPCHelpMan const&, JSONRPCRequest const&) const (this=0xf58f2ba0, self=..., request=...) at ./rpc/external_signer.cpp:51
...
(truncated, only one thread exists)
```

### CODE REVIEW

**Comment by fanquake** [comment]
ACK - to stop the flow of CI failures.

cc @hebasto @laanwj.

File: src/common/run_command.cpp [hunk 1]
```diff
@@ -24,7 +24,7 @@ UniValue RunCommandParseJSON(const std::string& str_command, const std::string&
 
     if (str_command.empty()) return UniValue::VNULL;
 
-    auto c = sp::Popen(str_command, sp::input{sp::PIPE}, sp::output{sp::PIPE}, sp::error{sp::PIPE}, sp::close_fds{true});
```
Comment (Sjors) [inline src/common/run_command.cpp:27]: Maybe only change this and don't undo the already upstreamed change (yet)?

**Comment by Sjors** [comment]
> call only async-signal-safe functions

Is this related? https://github.com/arun11299/cpp-subprocess/issues/53

File: src/common/run_command.cpp (hunk 1 above)
Comment (Sjors) [reply src/common/run_command.cpp:27]: Oh never mind, we didn't upstream this ourselves, it was already there and we copied it here.

Comment (maflcko) [reply src/common/run_command.cpp:27]: > Maybe only change this and don't undo the already upstreamed change (yet)?

I don't understand what you are referring to. Can you provide a link?

**Comment by maflcko** [comment]
> Is this related? [arun11299/cpp-subprocess#53](https://github.com/arun11299/cpp-subprocess/issues/53)

Yes. My recommendation would be to fix this upstream. I currently don't plan to do it, so anyone else is free to pick it up.

**Comment by Sjors** [comment]
Concept ACK

I agree it makes sense to fix upstream first.

How do you verify a reverted merge commit? I guess this worked:

```sh
git checkout maflcko/2507-tempoary-revert
git cherry-pick 4f5e04da135080291853f71e6f81dd0302224c3a^..a0eed55398f882d9390e50582b10272d18f2b836
git diff maflcko/2507-tempoary-revert~1
```

So do I understand correctly from the man page you linked to that `close()` and `getpid` and are already signal safe, and it's just `throw` and `sysconf` that are the problem?

**Comment by maflcko** [comment]
> it's just `throw` and `sysconf` that are the problem?

No, all of the C++ standard libary is problematic as well. (See the pull description and the bt)



> How do you verify a reverted merge commit? I guess this worked:

I typed `git revert -m1 31d3eebfb92ae0521e18225d69be95e78fb02672`, but `git` is very flexible and you can type many different things to arrive at the same result.

**Comment by darosior** [comment]
Concept ACK...

**Review by darosior — APPROVED** [review]
ACK faa1c3e80d95552bdc2c0e717065ebf8d510138f

**Review by naiyoma — COMMENTED** [review]
Concept ACK 


From POSIX.1-2017 fork() documentation:

_'A process shall be created with a single thread. If a multi-threaded process calls fork(), the new process shall contain a replica of the calling thread and its entire address space, possibly including the states of mutexes and other resources. Consequently, to avoid errors, the child process may only execute async-signal-safe operations until such time as one of the exec functions is called.'_

**Comment by fanquake** [comment]
ACK faa1c3e80d95552bdc2c0e717065ebf8d510138f

**Review by weezyb0893 — COMMENTED** [review]
Stop

**Review by FranciscoBelchior — COMMENTED** [review]
Concluiu

**Comment by laanwj** [comment]
Posthumous ACK

> After a fork() in a multithreaded program, the child can safely
> call only async-signal-safe functions (see [signal-safety(7)](https://www.man7.org/linux/man-pages/man7/signal-
> safety.7.html))
> until such time as it calls execv.

TIL

**Comment by laanwj** [comment]
Note that strictly, the current (inefficient loop) subprocess implementation of fd closing in upstream isn't async signal safe as it calls `sysconf(_SC_OPEN_MAX)` in the child process ( https://github.com/arun11299/cpp-subprocess/blob/master/cpp-subprocess/subprocess.hpp#L1941 ).

Sadly:

> POSIX.1-2001  and POSIX.1-2001 TC2 required the functions fpathconf(3), pathconf(3), and sysconf(3) to be async-signal-safe, but this requirement was removed in POSIX.1-2008.

It also throws in case `sysconf` fails, which is even worse. As the maximum fd limit value is inherited to subprocesses, it would be valid to move the call to `sysconf` to before the `fork()` to fix this.

---

This may be interesting to port over: https://docs.rs/close_fds/latest/close_fds/#async-signal-safety-in-this-crate
(implementation is here: https://docs.rs/close_fds/latest/src/close_fds/closefds/close.rs.html)

It is a rust implementation of "close all FDs" which is claimed to be efficient on all common platforms, as well as async signal safe. It implements this in terms of direct kernel calls, which are (when used carefully enough) async signal safe.
