### PR TITLE
gui: Fix async open wallet call order

### LINKED ISSUE #15455: gui: Opening wallet dialog doesn't close for certain wallet names
When you open wallets with exotic names, i.e `🦹🏿‍♂️` (Emoji Version 11), via the "Open Wallet" menu, the opening wallet dialog never closes, even after the wallet has finished loading.

screen shot 2019-02-21 at 2 34 06 pm

### PR DESCRIPTION
**Pull request by promag**
Fixes #15455. Must call `OpenWalletActivity::open` asynchronously only after all connections are made to the `OpenWalletActivity` instance, otherwise signals can be missed.

### CODE REVIEW

File: src/qt/bitcoingui.cpp [hunk 1]
```diff
@@ -396,6 +396,7 @@ void BitcoinGUI::createActions()
                     connect(activity, &OpenWalletActivity::opened, this, &BitcoinGUI::setCurrentWallet);
                     connect(activity, &OpenWalletActivity::finished, activity, &QObject::deleteLater);
                     connect(activity, &OpenWalletActivity::finished, dialog, &QObject::deleteLater);
+                    QMetaObject::invokeMethod(activity, "open");
```
Comment (promag) [inline src/qt/bitcoingui.cpp]: Note, removed the unnecessary explicit `Qt::QueuedConnection` argument. The default `Qt::AutoConnection` is enough since the activity thread is not the current thread.

Comment (Sjors) [reply src/qt/bitcoingui.cpp]: Nit: check the [return bool](https://doc.qt.io/qt-5/qmetaobject.html#invokeMethod), and maybe write a log message if this is false, or abort.

**Review by Sjors — APPROVED** [review]
tACK 01e25ff6ad

File: src/qt/bitcoingui.cpp (hunk 1 above)
Comment (promag) [reply src/qt/bitcoingui.cpp]: Thanks, done.

**Comment by fanquake** [comment]
tACK a720a98. 

Checked this fixes #15455, and that `🦹🏿‍♂️` wallets load correctly.

File: src/qt/bitcoingui.cpp [hunk 2]
```diff
@@ -396,6 +396,8 @@ void BitcoinGUI::createActions()
                     connect(activity, &OpenWalletActivity::opened, this, &BitcoinGUI::setCurrentWallet);
                     connect(activity, &OpenWalletActivity::finished, activity, &QObject::deleteLater);
                     connect(activity, &OpenWalletActivity::finished, dialog, &QObject::deleteLater);
+                    bool invoked = QMetaObject::invokeMethod(activity, "open");
+                    assert(invoked);
```
Comment (laanwj) [inline src/qt/bitcoingui.cpp]: When can this fail?

**Comment by laanwj** [comment]
utACK a720a983015c9ef8cc814c16a5b9ef6379695817

File: src/qt/bitcoingui.cpp (hunk 2 above)
Comment (promag) [reply src/qt/bitcoingui.cpp]: If the slot is renamed it would still compile. With Qt 5.10 it is possible to invoke like `QMetaObject::invokeMethod(activity, &OpenWalletActivity::open).

Comment (laanwj) [reply src/qt/bitcoingui.cpp]: Thanks!
