### PR TITLE
Handle the result of posix_fallocate system call

### LINKED ISSUE #15624: flatfile_tests fail on alpine linux
File size checks fails and I haven't figured out why, but next I'd look into how `posix_fallocate` works on alpine linux.

Log:

```
$ cat /etc/alpine-release 
3.9.2

$ git log --oneline -1
e45b7f20e Merge #15618: refactor: Remove unused function

$ ./src/test/test_bitcoin -t flatfile_tests
Running 4 test cases...
Version using posix_fallocate
test/flatfile_tests.cpp(94): error: in "flatfile_tests/flatfile_allocate": check fs::file_size(seq.FileName(FlatFilePos(0, 0))) == 100 has failed [0 != 100]
test/flatfile_tests.cpp(98): error: in "flatfile_tests/flatfile_allocate": check fs::file_size(seq.FileName(FlatFilePos(0, 99))) == 100 has failed [0 != 100]
Version using posix_fallocate
test/flatfile_tests.cpp(102): error: in "flatfile_tests/flatfile_allocate": check fs::file_size(seq.FileName(FlatFilePos(0, 99))) == 200 has failed [0 != 200]
Version using posix_fallocate
test/flatfile_tests.cpp(116): error: in "flatfile_tests/flatfile_flush": check fs::file_size(seq.FileName(FlatFilePos(0, 1))) == 100 has failed [0 != 100]

*** 4 failures are detected in the test module "Bitcoin Core Test Suite"
```

### PR DESCRIPTION
**Pull request by lucayepa**
The system call `posix_fallocate` is not supported on some filesystems.

- catches the result of posix_allocate and fall back to the default behaviour if the return value is different from 0 (success)

Fixes #15624

### CODE REVIEW

**Comment by gmaxwell** [comment]
OR-ing the fallback version with linux might be clearer than sticking in a bunch of returns and leaving in a chunk of dead code that some static analysis tools may warn about.

**Comment by lucayepa** [comment]
Do you think we can consider the Linux part in the fallback? I don't know if posix_allocate can be called on every platform. It will become something like:
```
#if defined(WIN32)
...
#elif defined(MAC_OSX)
...
#endif
    // Linux and fallback version
 (this calls posix_fallocate for every other platform)
```
This way the system call `posix_fallocate` would be called for every fallback platform. I don't know if this is a good idea.

**Comment by gmaxwell** [comment]
No but you can do
#if win32
#elif mac 
#else 
  #if linux
  #endif
  fallback
#endif

**Comment by lucayepa** [comment]
This sounds great. I indent the nested #if to be consistent with the style of the rest of the code.

I also add here a link for reference to the first introduction of the system call: #2229.

**Comment by gmaxwell** [comment]
Style ACK. :)  (should get some testing on an impacted filesystem)

**Comment by MarcoFalke** [comment]
utACK eb18d9af0686d79fad9761aacc8cda76b9ebe9a3

**Comment by lucayepa** [comment]
Just tested on an affected filesystem (unionf on Debian stable), using strace to check the system calls sent to the system. The success return value of posix_fallocate is obviously zero. Somehow in a previous version I had the '!', but then I pushed the wrong one, without it. I just force-pushed the good version, I just tested with strace.

Affected filesystem (fallocate result is EOPNOTSUPP, and the fallback code is activated):
```
$ strace test/test_bitcoin -t flatfile_tests 2>&1 | grep -A 5 fallocate | tail -6
fallocate(3, 0, 0, 100)                 = -1 EOPNOTSUPP (Operation not supported)
fcntl(3, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
fstat(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
fstatfs(3, {f_type=FUSE_SUPER_MAGIC, f_bsize=4096, f_blocks=2047598, f_bfree=712591, f_bavail=603651, f_files=524288, f_ffree=411273, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_NODEV|ST_RELATIME}) = 0
pwrite64(3, "\0", 1, 99)                = 1
close(3)                                = 0
```

Ext4 filesystem (fallocate result is zero, that means success, and no other code is activated):
```
$ strace test/test_bitcoin -t flatfile_tests 2>&1 | grep -A 1 fallocate | tail -2
fallocate(3, 0, 0, 100)                 = 0
close(3)                                = 0
```

File: src/util/system.cpp [hunk 1]
```diff
@@ -1089,11 +1089,12 @@ void AllocateFileRange(FILE *file, unsigned int offset, unsigned int length) {
...
     }
     ftruncate(fileno(file), fst.fst_length);
-#elif defined(__linux__)
+#else
+    #if defined(__linux__)
     // Version using posix_fallocate
     off_t nEndPos = (off_t)offset + length;
-    posix_fallocate(fileno(file), 0, nEndPos);
-#else
+    if (!posix_fallocate(fileno(file), 0, nEndPos)) return;
```
Comment (MarcoFalke) [inline src/util/system.cpp]: Might be cleaner to just compare `0 == posix_fallocate(...`

Comment (lucayepa) [reply src/util/system.cpp]: Yes, I agree. 0 == ... is more expressive and less error prone.

**Comment by MarcoFalke** [comment]
utACK 5d35ae3326624da3fe5dcb4047c9a7cec6665cab

**Comment by sipa** [comment]
utACK 5d35ae3326624da3fe5dcb4047c9a7cec6665cab, though the Yoda condition is an uncommon style in this project.

**Review by luke-jr — APPROVED** [review]
Probably would be better to have configure check for `posix_fallocate` availability instead of using `__linux__`, but since it's already that way, this is strictly an improvement.

utACK

**Comment by hebasto** [comment]
utACK 5d35ae3326624da3fe5dcb4047c9a7cec6665cab

**Comment by practicalswift** [comment]
utACK 5d35ae3326624da3fe5dcb4047c9a7cec6665cab
