### PR TITLE
validation: Add eligible ancestors of reconsidered block to setBlockIndexCandidates

### LINKED ISSUE #16444: Assertion `setBlockIndexCandidates.count(pindex)' failed
This happened on travis as part of a pull request that only modified ATMP logic. So the assertion can likely also be hit on a clean master.

https://travis-ci.org/bitcoin/bitcoin/jobs/562128739#L4513 (in `rpc_invalidateblock.py`)

### PR DESCRIPTION
**Pull request by mzumsande**
When we call `reconsiderblock` for some block,  `Chainstate::ResetBlockFailureFlags` puts the descendants of that block into `setBlockIndexCandidates` (if they meet the criteria, i.e. have more work than the tip etc.), but never put any ancestors into the set even though we do clear their failure flags.

I think that this is wrong, because `setBlockIndexCandidates` should always contain all eligible indexes that have at least as much work as the current tip, which can include ancestors of the reconsidered block. This is being checked by `CheckBlockIndex()`, which could fail if it was invoked after `ActivateBestChain` connects a block and releases `cs_main`:
``` diff
diff --git a/src/validation.cpp b/src/validation.cpp
index 7b04bd9a5b..ff0c3c9f58 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -3551,6 +3551,7 @@ bool Chainstate::ActivateBestChain(BlockValidationState& state, std::shared_ptr<
             }
         }
         // When we reach this point, we switched to a new tip (stored in pindexNewTip).
+        m_chainman.CheckBlockIndex();
 
         if (exited_ibd) {
             // If a background chainstate is in use, we may need to rebalance our
```
makes `rpc_invalidateblock.py` fail on master.

Even though we don't currently have a `CheckBlockIndex()` in that place, after `cs_main` is released other threads could invoke it, which is happening in the rare failures of #16444 where an invalid header received from another peer could trigger a `CheckBlockIndex()` call that would fail.

Fix this by adding eligible ancestors to `setBlockIndexCandidates` in `Chainstate::ResetBlockFailureFlags` (also simplifying that function a bit).

Fixes #16444

### CODE REVIEW

**Review by sedited — APPROVED** [review]
ACK 4a76a8300f295e8eab0ea8ab1ea1580450f131c8

This has been the behaviour since reconsiderblock was introduced ~10 years ago https://github.com/bitcoin/bitcoin/commit/9b0a8d3152b43b63c99878d0223a1681993ad608#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2R2176 .

**Review by stratospher — COMMENTED** [review]
tested ACK 4a76a8300f295e8eab0ea8ab1ea1580450f131c8.

makes sense that `setBlockIndexCandidates` should ideally contain all block indices with as much/more work than current tip regardless of whether it is an ancestor/descendant.

I've tested it by demonstrating a situation where the chain tip doesn't get correctly updated on master - https://github.com/stratospher/bitcoin/commit/57959f9b659f9df13aca3d08b2a14adc9588ac07, feel free to cherry-pick if useful.

File: src/validation.cpp [hunk 1]
```diff
@@ -3839,7 +3839,7 @@ void Chainstate::ResetBlockFailureFlags(CBlockIndex *pindex) {
 
     // Remove the invalidity flag from this block and all its descendants and ancestors.
     for (auto& [_, block_index] : m_blockman.m_block_index) {
-        if (!block_index.IsValid() && (block_index.GetAncestor(nHeight) == pindex || pindex->GetAncestor(block_index.nHeight) == &block_index)) {
+        if ((block_index.nStatus & BLOCK_FAILED_MASK) && (block_index.GetAncestor(nHeight) == pindex || pindex->GetAncestor(block_index.nHeight) == &block_index)) {
```
Comment (TheCharlatan) [inline src/validation.cpp:3842]: Nice catch! How about removing the default argument altogether:
```diff
diff --git a/src/chain.h b/src/chain.h
index c6d1640768..f5bfdb2fb4 100644
--- a/src/chain.h
+++ b/src/chain.h
@@ -295 +295 @@ public:
-    bool IsValid(enum BlockStatus nUpTo = BLOCK_VALID_TRANSACTIONS) const
+    bool IsValid(enum BlockStatus nUpTo) const
diff --git a/src/test/fuzz/chain.cpp b/src/test/fuzz/chain.cpp
index 0363f317b6..09053e4815 100644
--- a/src/test/fuzz/chain.cpp
+++ b/src/test/fuzz/chain.cpp
@@ -33 +33 @@ FUZZ_TARGET(chain)
-        (void)disk_block_index->IsValid();
+        (void)disk_block_index->IsValid(BLOCK_VALID_TRANSACTIONS);
```

Comment (mzumsande) [reply src/validation.cpp:3842]: Good idea - done!

**Comment by mzumsande** [comment]
Looks like there is a intermittent failure in the added test - I'll look into it soon.

**Review by sedited — APPROVED** [review]
Re-ACK 843f7860298081d0a8d12294d23b962f5586a862

**Comment by mzumsande** [comment]
[843f786](https://github.com/bitcoin/bitcoin/commit/843f7860298081d0a8d12294d23b962f5586a862) to [8cc3ac6](https://github.com/bitcoin/bitcoin/commit/8cc3ac6c2328873e57c31f237d194c5f22b6748a): rebased due to conflict with https://github.com/bitcoin/bitcoin/pull/31405

**Review by sedited — APPROVED** [review]
Re-ACK 8cc3ac6c2328873e57c31f237d194c5f22b6748a

**Review by stratospher — APPROVED** [review]
reACK 8cc3ac6.

**Comment by achow101** [comment]
ACK 8cc3ac6c2328873e57c31f237d194c5f22b6748a
