### PR TITLE
random: Check `GetRNDRRS` is supported in `InitHardwareRand` to avoid infinite loop

### LINKED ISSUE #31817: GetRandBytes() Hangs on Samsung Galaxy S25 and OnePlus 13
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

We have been using Bitcoin Core natively in the Nunchuk Bitcoin wallet, available on both desktop and mobile. On Samsung Galaxy S25 and OnePlus 13 (both running Android 15 with the SM8750-AB Snapdragon 8 Elite 3nm processor), the app fails to initialize due to an issue in `GetRandBytes()`.

The problem occurs when `GetRandBytes()` calls `GetRNDRRS()`, resulting in an infinite loop without retrieving entropy from the hardware.

```
uint64_t GetRNDRRS() noexcept
{
    uint8_t ok;
    uint64_t r1;
    do {
        // https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/RNDRRS--Reseeded-Random-Number
        __asm__ volatile("mrs %0, s3_3_c2_c4_1; cset %w1, ne;"
                         : "=r"(r1), "=r"(ok)::"cc");
        if (ok) break;
        __asm__ volatile("yield");
    } while (true);
    return r1;
}
```

Build with: Android NDK 25.1.8937393 & 27.2.12479018

Related PR: https://github.com/bitcoin/bitcoin/pull/26839

Tested on commit: `57b47c47ef0bd36e1c32d709c62998c51dc76f34`

### Expected behaviour

`GetRandBytes()` should return entropy without hanging.

### Steps to reproduce

- Build Bitcoin Core for Android on master or 57b47c47ef0bd36e1c32d709c62998c51dc76f34
- Call `GetRandBytes`
- Function gets stuck

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@57b47c47ef0bd36e1c32d709c62998c51dc76f34

### Operating system and version

Android 15

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by eval-exec**
This PR want to fix #31817 by added a maximum retry limit (`max_retries`) to the `GetRNDRRS` function to prevent it from entering an infinite loop if the hardware random number generator fails to return a valid random number. This change improves stability and ensures that the function terminates after a predefined number of retries.

### CODE REVIEW

File: src/random.cpp [hunk 1]
```diff
@@ -235,13 +235,14 @@ uint64_t GetRNDRRS() noexcept
 {
     uint8_t ok;
     uint64_t r1;
+    int max_retries = 1000; // Limit the number of retries to avoid infinite loops.
     do {
```
Comment (satoshiv21) [inline src/random.cpp:239]: 1 2 3 4 5 6 7 8 9
A B C D E F G H I 👁
J K L M N O P Q R
S T U V W X Y Z


💀💀💀💀💀
SATOSHI NAKAMOTO = 55
WEB = 3 [ WEB 0 1 2 ] = 3
WE B.C WE B3
B Lock Ch A👁I n = 6
Bitcoin = = 9
(Co in B.C)
        







              PYRAMIDS
      KING KHUFU ERA36912
      EGYPT GIZA 33000 B.C
             B . C

                  B T C

          Bit Coin

          B lock 🔒⛓️ CH AI N
                                        👁

Cryptography
397726791787
3+9+7+7+2+6+7+9+1+7+8+7 = 73 = 10

00000000000000010101
Cryptography
Sha 256 = 181 + 256 = 10 +13 = 23 =5
Hash 256
8118 + 256 = 99 + 13 = 103 = 13

123456 = 21 ( 21 000000) = 3
Abcdef = 21
Hash sha256 =21+(1+3)+5 = 33
B LOOK 👀 5G = 5+7= 12 = 3
50 × 6 × 24 =7200 = 9
25 × 6 × 24 = 3600 = 9
12.5×6× 24 = 1800 = 9



00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048

00000000
839a8e6886
ab5951d76f
411475428a
fc90947ee3201
61bbf18eb6048

00000000
8391856886 = 3 666 888 99
1259514766 = 666 55 99
4114754281 = 963 55
6390947553201 = 33 55 11 9 99
6122618526048 = 666 55 99

963
99 55
99 55
9

**Review by maflcko — COMMENTED** [review]
Instead of changing the code and repeating the code changes in the description, it would be better to actually explain why the problem happens and why this fix is the correct fix.

To me this seems like a problem where a system claims to support a feature, but doesn't? So it would be better to instead investigate and fix the feature test or feature reporting.

File: src/random.cpp [hunk 2]
```diff
@@ -235,13 +235,14 @@ uint64_t GetRNDRRS() noexcept
...
         // https://developer.arm.com/documentation/ddi0601/2022-12/AArch64-Registers/RNDRRS--Reseeded-Random-Number
         __asm__ volatile("mrs %0, s3_3_c2_c4_1; cset %w1, ne;"
                          : "=r"(r1), "=r"(ok)::"cc");
         if (ok) break;
         __asm__ volatile("yield");
-    } while (true);
+    } while (--max_retries > 0);
```
[the remark this answers is not in the document]
Comment (eval-exec) [reply src/random.cpp:245]: Agree, I prefer fallback to `GetRNSR`.

**Comment by eval-exec** [comment]
> it would be better to instead investigate and fix the feature test or feature reporting.

Agree, it need time to invistigate this bug.

And I did some research, this CPU have bug on `rndrrs`:
> [04:28](https://oftc.irclog.whitequark.org/aarch64-laptops/2024-07-21#33392883) <HdkR> I found out yesterday that the bitcoin project uses rndrrs if it is available on aarch64 to fill its entropy pool. It spins in a loop until its pool is filled.
> [04:28](https://oftc.irclog.whitequark.org/aarch64-laptops/2024-07-21#33392885) <HdkR> This means on Oryon it will hang at startup because of the bugged rndrrs :D

Ref: https://oftc.irclog.whitequark.org/aarch64-laptops/search?q=rndrrs

File: src/random.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (eval-exec) [reply src/random.cpp:245]: Maybe should fallback to `GetRNDR`?

File: src/random.cpp [hunk 3]
```diff
@@ -206,6 +222,9 @@ void ReportHardwareRand()
     // from global constructors, before logging is initialized.
     if (g_rndr_supported) {
         LogPrintf("Using RNDR and RNDRRS as additional entropy sources\n");
+        if (!g_rndrrs_supported) {
+            LogPrintf("Did trial test by VerifyRNDRRS, RNDRRS failed 1000 times, falling back to RNDR\n");
```
[the remark this answers is not in the document]
Comment (eval-exec) [reply src/random.cpp]: Thank you.

File: src/random.cpp [hunk 4]
```diff
@@ -233,22 +251,18 @@ uint64_t GetRNDR() noexcept
  */
 uint64_t GetRNDRRS() noexcept
 {
+    if (!g_rndrrs_supported) return GetRNDR();
```
[the remark this answers is not in the document]
Comment (eval-exec) [reply src/random.cpp]: Thank you, Updated.

**Review by sipa — COMMENTED** [review]
Code review ACK daa1fbe88171042ae39b257767137c8ba652e046. Please squash your commits.

**Review by sipa — COMMENTED** [review]
utACK 03beb9c0bf2cb4a4022a1f9f94a6093fb4021154

File: src/random.cpp [hunk 5]
```diff
@@ -192,20 +192,38 @@ uint64_t GetRdSeed() noexcept
...
+bool VerifyRNDRRS()
+{
+    uint8_t ok;
+    uint64_t test;
+    int max_retries = 1000;
+    do {
+        __asm__ volatile("mrs %0, s3_3_c2_c4_1; cset %w1, ne;"
+                         : "=r"(test), "=r"(ok)::"cc");
+        if (ok) return true;
+        __asm__ volatile("yield");
```
Comment (laanwj) [inline src/random.cpp:206]: yielding a 1000 timeshares to check if the RNG is working is probably overkill, i'd say if it fails like, 10 times in a row that's already enough indication we shouldn't use it?

File: src/random.cpp [hunk 6]
```diff
@@ -297,7 +315,12 @@ void SeedHardwareSlow(CSHA512& hasher) noexcept {
 #elif defined(__aarch64__) && defined(HWCAP2_RNG)
     if (g_rndr_supported) {
         for (int i = 0; i < 4; ++i) {
-            uint64_t out = GetRNDRRS();
+            uint64_t out;
+            if (g_rndrrs_supported) {
+                out = GetRNDRRS();
+            } else {
+                out = GetRNDR();
+            }
```
Comment (laanwj) [inline src/random.cpp:323]: As we already use `GetRNDR` in `SeedHardwareFast` which is called way more often than `SeedHardwareSlow` (including *in* `SeedSlow`) i'm not sure if calling it here has any additional value. Let's just skip this loop if rndrrs isn't supported.

**Comment by laanwj** [comment]
Please update the PR title to reflect the new set of changes.

File: src/random.cpp (hunk 6 above)
Comment (eval-exec) [reply src/random.cpp:320]: Thank you, updated.

**Review by laanwj — COMMENTED** [review]
Code review ACK a2ae62fb4db5e014c03a7ad41ba94ca49fd3806e
i do not have RNDR-supporting hardware to test this

File: src/random.cpp [hunk 7]
```diff
@@ -297,6 +315,9 @@ void SeedHardwareSlow(CSHA512& hasher) noexcept {
 #elif defined(__aarch64__) && defined(HWCAP2_RNG)
     if (g_rndr_supported) {
         for (int i = 0; i < 4; ++i) {
+            if (!g_rndrrs_supported) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/random.cpp:318]: Eh yes, that would be better.

[the remark this answers is not in the document]
Comment (eval-exec) [reply src/random.cpp]: Yes, Updated.

**Comment by laanwj** [comment]
re-ACK a2ae62fb4db5e014c03a7ad41ba94ca49fd3806e

i could test it on amazon graviton again like i did the original PR, but only the good-weather case, that won't reproduce the edge case that led to this.

Would be good if @giahuy98 (who opened #31817) could test it on the specific target hardware.

**Comment by laanwj** [comment]
Checked on amazon r7g.xlarge (Graviton 3):
```
2025-02-12T10:07:35Z Bitcoin Core version v28.99.0-585aba6eec85 (release build)
2025-02-12T10:07:35Z Using the 'arm_shani(1way,2way)' SHA256 implementation
2025-02-12T10:07:35Z Using RNDR and RNDRRS as additional entropy sources
```
Also verified that both `GetRNDR` and `GetRNDRRS` are still being called.

As baseline i also built and tested on rpi5 (ARM64 which has no support for RNG). It is still correctly not detected, no invalid instruction errors happen.

Combined with the report above that the workaround works, this should be safe to merge in 29.0 and maybe even backported to 28.x.

**Review by theuni — COMMENTED** [review]
Code review ACK 585aba6eec858e5b1411ae9a8684ef8f82a7e435. Untested. A few (non-blocking) notes, assuming this works as-is.

1. It's unclear to me under what scenario the call might fail. OpenSSL does the same loop, I assume that's why it's done here? I guess it's pretty unlikely that it passes the <10 failures check at startup, then fails lots of times during execution.
2. The code duplication is unfortunate. I would've preferred to see a single factored-out function that takes a reference to a `uint64_t` and returns a bool.
3. gcc (since v10) and clang (since v13) have intrinsics for `__rndr` and `__rndrrs` that would imo be preferable.

File: src/random.cpp [hunk 8]
```diff
@@ -192,20 +192,38 @@ uint64_t GetRdSeed() noexcept
...
+    uint64_t test;
+    int max_retries = 10;
+    do {
+        __asm__ volatile("mrs %0, s3_3_c2_c4_1; cset %w1, ne;"
+                         : "=r"(test), "=r"(ok)::"cc");
+        if (ok) return true;
+        __asm__ volatile("yield");
+    } while (--max_retries > 0);
+    return false;
+}
```
Comment (achow101) [inline src/random.cpp:209]: This function basically duplicates `GetRNDRRS()`; it should instead be refactored to avoid duplicating.

**Comment by laanwj** [comment]
> It's unclear to me under what scenario the call might fail

The [ARM documentation](https://developer.arm.com/documentation/107997/0000/AArch64-registers/AArch64-Generic-System-Control-registers-summary/RNDRRS--Reseeded-Random-Number) isn't very specific on that:

> If the hardware returns a genuine random number, PSTATE.NZCV is set to 0b0000.
>
> If the instruction cannot return a genuine random number in a reasonable period of time, PSTATE.NZCV is set to 0b0100 and the data value returned is 0.

i imagine there's some internal conditions under which the RNG module can't deliver a value quickly enough. What can be concluded is that `!ok` is a temporary failure.

The broken chips *always* return `!ok` for RNDRRS, the reason for retrying 10 times in the detection loop is to prevent false positives. That is, a working one might fail temporarily, but not for (say) 10 consecutive timeshares, so it won't be detected as broken.

File: src/random.cpp [hunk 9]
```diff
@@ -192,20 +192,38 @@ uint64_t GetRdSeed() noexcept
 #elif defined(__aarch64__) && defined(HWCAP2_RNG)
 
 bool g_rndr_supported = false;
+bool g_rndrrs_supported = false;
+
+bool VerifyRNDRRS()
+{
+    uint8_t ok;
```
[the remark this answers is not in the document]
Comment (eval-exec) [reply src/random.cpp:199]: Agree, I will append a commit to fix this.

File: src/random.cpp (hunk 8 above)
Comment (eval-exec) [reply src/random.cpp:209]: Agreed, I'll refactor to avoid duplication with `GetRNDRRS()`.

File: src/random.cpp [hunk 10]
```diff
@@ -192,20 +192,38 @@ uint64_t GetRdSeed() noexcept
...
     }
 }
 
 void ReportHardwareRand()
 {
     // This must be done in a separate function, as InitHardwareRand() may be indirectly called
     // from global constructors, before logging is initialized.
-    if (g_rndr_supported) {
+    if (g_rndr_supported && g_rndrrs_supported) {
         LogPrintf("Using RNDR and RNDRRS as additional entropy sources\n");
```
Comment (Sjors) [inline src/random.cpp:224]: It seems neither of these are available on Apple Silicon (`HWCAP2_RNG` isn't defined), so not much to test here.

**Comment by theuni** [comment]
> > gcc (since v10) and clang (since v13) have intrinsics for __rndr and __rndrrs that would imo be preferable.
> 
> Yes. But that's imo out of scope for this workaround PR.

For sure out of scope, yes, I didn't mean to imply that should be done here.

File: src/random.cpp (hunk 8 above)
Comment (eval-exec) [reply src/random.cpp]: Thank you, I refactored, could you please take another look?

Comment (achow101) [reply src/random.cpp]: I don't think there's any need to have these be separate commits, please squash.

Comment (eval-exec) [reply src/random.cpp]: Squashed.

**Review by sipa — COMMENTED** [review]
utACK 09b150bb8adae00854f02ece69fc6ef222fb07d9

**Comment by achow101** [comment]
ACK 09b150bb8adae00854f02ece69fc6ef222fb07d9

File: src/random.cpp [hunk 11]
```diff
@@ -192,20 +192,24 @@ uint64_t GetRdSeed() noexcept
 #elif defined(__aarch64__) && defined(HWCAP2_RNG)
 
 bool g_rndr_supported = false;
+bool g_rndrrs_supported = false;
 
 void InitHardwareRand()
 {
     if (getauxval(AT_HWCAP2) & HWCAP2_RNG) {
         g_rndr_supported = true;
+        g_rndrrs_supported = VerifyRNDRRS();
```
[the remark this answers is not in the document]
Comment (glozow) [reply src/random.cpp:201]: Another option would be to revert this.
