### PR TITLE
ci: Move travis workarounds to .travis.yml

### LINKED ISSUE #19171: travis arm64 errors: sudo: unable to resolve host travis-job-bitcoin-bitcoin-694885469
Seeing "sudo: unable to resolve host travis-job-bitcoin-bitcoin-" errors two different PRs in the travis ARM build followed by timeouts:

https://travis-ci.org/github/bitcoin/bitcoin/jobs/694723263
https://travis-ci.org/github/bitcoin/bitcoin/jobs/694879056
https://travis-ci.org/github/bitcoin/bitcoin/jobs/694885469

I tried restarting the first job repeatedly (maybe 5 times) but it kept failing in the same way. Then I rebased and it happened again, and it happened again on another PR. It doesn't seem to happen on all PRs, even other PRs with the same base, but once it happens it seems to stick.

### PR DESCRIPTION
**Pull request by maflcko**
It seems odd to have travis related workarounds in the general ci config files. Fix that oddity by moving the travis related workarounds to the travis yaml file.

For unexplained reasons, this should also work around and thus close #19171

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Run 1 passed: https://travis-ci.org/github/bitcoin/bitcoin/builds/698236561

**Comment by hebasto** [comment]
Has anyone an explanation?

File: ci/test/05_before_script.sh [hunk 1]
```diff
@@ -33,9 +33,7 @@ if [ -z "$NO_DEPENDS" ]; then
   else
     SHELL_OPTS="CONFIG_SHELL="
   fi
-  # Temporary workaround for https://github.com/bitcoin/bitcoin/issues/16368
-  python3 -c 'import time; [print(".") or time.sleep(500) for _ in range(4)]' &
```
Comment (MarcoFalke) [inline ci/test/05_before_script.sh:37]: I believe the issue was that this `print` did nothing, because by default `flush=False` (see https://docs.python.org/3.8/library/functions.html#print ).

Testing locally and on travis x86, it did always happen to print, just not on travis arm.

File: ci/test/06_script_b.sh [hunk 2]
```diff
@@ -21,8 +21,6 @@ if [ -n "$USE_VALGRIND" ]; then
   END_FOLD
 fi
 
-bash -c "${CI_WAIT}" &  # Print dots in case the tests take a long time to run
-
```
Comment (hebasto) [inline ci/test/06_script_b.sh:25]: This deletion is also necessary?

Comment (MarcoFalke) [reply ci/test/06_script_b.sh:25]: `CI_WAIT` no longer exists and this should be a no-op

Comment (hebasto) [reply ci/test/06_script_b.sh:25]: Yes, `CI_WAIT` was dropped from the `.travis.yml` in #18929.

**Review by hebasto — APPROVED** [review]
ACK fa7166759789c1282609ff3ab2e80d4f70910a9f, I have reviewed the code and it looks OK, I agree it can be merged.
