### PR TITLE
ZMQ: Support UNIX domain sockets

### LINKED ISSUE #29802: Invalid port specified in -zmqpubrawtx when using IPC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

This error is being returned if IPC is specified instead of tpc:

> Error: Invalid port specified in -zmqpubrawtx: 'ipc:///root/snap/bitcoin-core/common/.bitcoin/bitcoind.tx.raw

### Expected behaviour

IPC should correctly work

### Steps to reproduce

```
# cat ~/snap/bitcoin-core/common/.bitcoin/bitcoin.conf

server=1
rpcuser=<censored>
rpcpassword=<censored>
zmqpubhashtx=tcp://127.0.0.1:29000
zmqpubhashblock=tcp://127.0.0.1:29001
zmqpubrawblock=tcp://127.0.0.1:29002
zmqpubsequence=tcp://127.0.0.1:29004
zmqpubrawtx=ipc:///root/snap/bitcoin-core/common/.bitcoin/bitcoind.tx.raw
```

### Relevant log output

```
2024-04-04T07:58:25Z Bitcoin Core version v26.0.0 (release build)
2024-04-04T07:58:25Z Using the 'x86_shani(1way,2way)' SHA256 implementation
2024-04-04T07:58:25Z Using RdSeed as an additional entropy source
2024-04-04T07:58:25Z Using RdRand as an additional entropy source
2024-04-04T07:58:25Z Default data directory /root/snap/bitcoin-core/common/.bitcoin
2024-04-04T07:58:25Z Using data directory /root/snap/bitcoin-core/common/.bitcoin
2024-04-04T07:58:25Z Config file: /root/snap/bitcoin-core/common/.bitcoin/bitcoin.conf
2024-04-04T07:58:25Z Config file arg: rpcpassword=****
2024-04-04T07:58:25Z Config file arg: rpcuser=****
2024-04-04T07:58:25Z Config file arg: server="1"
2024-04-04T07:58:25Z Config file arg: zmqpubhashblock="tcp://127.0.0.1:29001"
2024-04-04T07:58:25Z Config file arg: zmqpubhashtx="tcp://127.0.0.1:29000"
2024-04-04T07:58:25Z Config file arg: zmqpubrawblock="tcp://127.0.0.1:29002"
2024-04-04T07:58:25Z Config file arg: zmqpubrawtx="ipc:///root/snap/bitcoin-core/common/.bitcoin/bitcoind.tx.raw"
2024-04-04T07:58:25Z Config file arg: zmqpubsequence="tcp://127.0.0.1:29004"
2024-04-04T07:58:25Z Using at most 125 automatic connections (65536 file descriptors available)
2024-04-04T07:58:25Z Using 16 MiB out of 16 MiB requested for signature cache, able to store 524288 elements
2024-04-04T07:58:25Z Using 16 MiB out of 16 MiB requested for script execution cache, able to store 524288 elements
2024-04-04T07:58:25Z Script verification uses 15 additional threads
2024-04-04T07:58:25Z scheduler thread start
2024-04-04T07:58:25Z Binding RPC on address ::1 port 8332
2024-04-04T07:58:25Z Binding RPC on address 127.0.0.1 port 8332
2024-04-04T07:58:25Z [http] creating work queue of depth 16
2024-04-04T07:58:25Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
2024-04-04T07:58:25Z [http] starting 4 worker threads
2024-04-04T07:58:25Z Using wallet directory /root/snap/bitcoin-core/common/.bitcoin/wallets
2024-04-04T07:58:25Z init message: Verifying wallet(s)…
2024-04-04T07:58:25Z Using /16 prefix for IP bucketing
2024-04-04T07:58:25Z init message: Loading P2P addresses…
2024-04-04T07:58:25Z Loaded 63406 addresses from peers.dat  101ms
2024-04-04T07:58:25Z init message: Loading banlist…
2024-04-04T07:58:25Z SetNetworkActive: true
2024-04-04T07:58:25Z Error: Invalid port specified in -zmqpubrawtx: 'ipc:///root/snap/bitcoin-core/common/.bitcoin/bitcoind.tx.raw'
Error: Invalid port specified in -zmqpubrawtx: 'ipc:///root/snap/bitcoin-core/common/.bitcoin/bitcoind.tx.raw'
2024-04-04T07:58:25Z Shutdown: In progress...
2024-04-04T07:58:25Z scheduler thread exit
2024-04-04T07:58:25Z Flushed fee estimates to fee_estimates.dat.
2024-04-04T07:58:25Z Shutdown: done
```

### How did you obtain Bitcoin Core

Other

### What version of Bitcoin Core are you using?

v26.0.0

### Operating system and version

Ubuntu 22.04.4 LTS

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by pinheadmz**
This is a follow-up to https://github.com/bitcoin/bitcoin/pull/27375, allowing ZMQ notifications to be published to a UNIX domain socket.

Fortunately, libzmq handles unix sockets already, all we really have to do to support it is allow the format in the actual option.

[libzmq](https://libzmq.readthedocs.io/en/latest/zmq_ipc.html) uses the prefix `ipc://` as opposed to `unix:` which is [used by Tor](https://gitlab.torproject.org/tpo/core/tor/-/blob/main/doc/man/tor.1.txt?ref_type=heads#L1475) and now also by [bitcoind](https://github.com/bitcoin/bitcoin/blob/a85e5a7c9ab75209bc88e49be6991ba0a467034e/doc/release-notes-27375.md?plain=1#L5) so we need to switch that internally.

As far as I can tell, [LND](https://github.com/lightninglabs/gozmq/blob/d20a764486bf506bc045642e455bc7f0d21b232a/zmq.go#L38) supports `ipc://` and `unix://` (notice the double slashes).

With this patch, LND can connect to bitcoind using unix sockets:

Example:

*bitcoin.conf*:
```
zmqpubrawblock=unix:/tmp/zmqsb
zmqpubrawtx=unix:/tmp/zmqst
```

*lnd.conf*:
```
bitcoind.zmqpubrawblock=ipc:///tmp/zmqsb
bitcoind.zmqpubrawtx=ipc:///tmp/zmqst
```

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Concept ACK

**Comment by pinheadmz** [comment]
> 🐙 This pull request conflicts with the target branch and [needs rebase](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#rebasing-changes).

Relax bot! sheesh. I'm gonna wait until #27375 gets approved

File: src/init.cpp [hunk 1]
```diff
@@ -1273,30 +1273,34 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+        const bool unix{port_option.second};
+        for (const std::string& socket_addr : args.GetArgs(arg)) {
             std::string host_out;
             uint16_t port_out{0};
             if (!SplitHostPort(socket_addr, port_out, host_out)) {
 #if HAVE_SOCKADDR_UN
-                // Allow unix domain sockets for -proxy and -onion e.g. unix:/some/file/path
-                if ((port_option != "-proxy" && port_option != "-onion") || socket_addr.find(ADDR_PREFIX_UNIX) != 0) {
-                    return InitError(InvalidPortErrMsg(port_option, socket_addr));
+                // Allow unix domain sockets for some options e.g. unix:/some/file/path
```
Comment (luke-jr) [inline src/init.cpp:1297]: Prefer we just allow it for everything and error somewhere else

File: src/netaddress.h [hunk 2]
```diff
@@ -33,8 +33,9 @@
  */
 static constexpr int ADDRV2_FORMAT = 0x20000000;
 
-/** Prefix for unix domain socket addresses (which are local filesystem paths) */
-const std::string ADDR_PREFIX_UNIX = "unix:";
+/** Prefixes for unix domain socket addresses (which are local filesystem paths) */
+const std::string ADDR_PREFIX_UNIX = "unix:"; // example unix:/root/path/to/file
+const std::string ADDR_PREFIX_IPC = "ipc://"; // example icp:///root/path/to/file
```
Comment (luke-jr) [inline src/netaddress.h:38]: ipc*

File: src/init.cpp [hunk 3]
```diff
@@ -1314,30 +1314,33 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+        {"-onion",                  true},
+        {"-proxy",                  true},
+        {"-rpcbind",                false},
+        {"-torcontrol",             false},
+        {"-whitebind",              false},
+        {"-zmqpubhashblock",        true},
+        {"-zmqpubhashtx",           true},
+        {"-zmqpubrawblock",         true},
+        {"-zmqpubrawtx",            true},
+        {"-zmqpubsequence",         true}
```
Comment (pinheadmz) [inline src/init.cpp:1329]: unix socket support for i2psam and rpcbind will be implemented in future work, so this little matrix is anticipating that

File: src/init.cpp [hunk 4]
```diff
@@ -1314,30 +1314,33 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+        for (const std::string& socket_addr : args.GetArgs(arg)) {
             std::string host_out;
             uint16_t port_out{0};
             if (!SplitHostPort(socket_addr, port_out, host_out)) {
 #if HAVE_SOCKADDR_UN
-                // Allow unix domain sockets for -proxy and -onion e.g. unix:/some/file/path
-                if ((port_option != "-proxy" && port_option != "-onion") || socket_addr.find(ADDR_PREFIX_UNIX) != 0) {
-                    return InitError(InvalidPortErrMsg(port_option, socket_addr));
+                // Allow unix domain sockets for some options e.g. unix:/some/file/path
+                if (!unix || socket_addr.find(ADDR_PREFIX_UNIX) != 0) {
```
Comment (tdb3) [inline src/init.cpp:1339]: If adjusted to:
```c
if (!unix || (socket_addr.find(ADDR_PREFIX_UNIX) != 0 && socket_addr.find(ADDR_PREFIX_IPC) != 0))
```

it seems like support for both forms (`unix:` and `ipc://`) might be achievable. 

If I'm not missing something, 
https://github.com/bitcoin/bitcoin/blob/7b4c7bdb35eda125781d14535a69dc6b9898069d/src/zmq/zmqnotificationinterface.cpp#L63
would allow `ipc://` to pass through (while also normalizing `unix:` to `ipc://`).

Was there a reason/rationale to use only `unix:` rather than both forms?  I would guess that folks familiar with ZMQ would be used to using `ipc://`, so it may be more straightforward to them to include support for that form.

I'm ok with either approach (supporting only `unix:` or supporting both `unix:` and `ipc://`).

**Review by tdb3 — COMMENTED** [review]
ACK 7b4c7bdb35eda125781d14535a69dc6b9898069d
Nice addition to the suite of unix domain socket support (e.g. PR #27375, etc.)!

Performed code review.
Built and ran all functional tests (all passed, including `interface_zmq.py`)

Since bitcoind uses the `unix:` form, the unused form (`ipc:///tmp/mysocket`) was tested and bitcoind startup errors out (as expected).  Inline nit discusses this.

Another malformed format (e.g. `notvalid:///tmp/sock`) was also tested and errors out (as expected).

It was too tempting not to try LND with ZMQ unix domain sockets!
Ran LND 0.17.4 and bitcoind (this PR branch) on signet, configured as follows:

bitcoin.conf:
```
...
zmqpubrawblock=unix:/tmp/zmqpubrawblock
zmqpubrawtx=unix:/tmp/zmqpubrawtx
...
```
(also ran bitcoind with `ipc:///tmp/zmqpubrawblock` and `ipc:///tmp/zmqpubrawtx` as described in the nit comment and that was successful as well)

lnd.conf:
```
...
bitcoind.zmqpubrawblock=ipc:///tmp/zmqpubrawblock
bitcoind.zmqpubrawtx=ipc:///tmp/zmqpubrawtx
...
```

Using https://github.com/mechpen/sockdump, unix socket traffic was sniffed on each socket file.
ZMQ traffic was observed (e.g. rawblock, rawtx), so seems to be working well!  Great work!

File: src/init.cpp (hunk 4 above)
Comment (pinheadmz) [reply src/init.cpp:1339]: Heh yeah actually the branch used to be exactly like this but after #27375 got revised I simplified it. I'm open to discuss options, we could support any combination of `unix:` `unix://` `ipc:` `ipc://` or use a regex to cover them all. The motivation for keeping it simple isn't super strong but goes like this:

- Tor and libzmq only support one prefix each, and not even the same one. Meanwhile LND supports another set of prefixes.
- We would also need to update `IsUnixSocketPath()` to be more flexible 
- We'd also need a new function `GetUnixPathFromArg()` or something to replace lines like this that only expect one prefix:

https://github.com/bitcoin/bitcoin/blob/015ac13dcc964a31ef06dfdb565f88f901607f0e/src/netbase.cpp#L649

Comment (tdb3) [reply src/init.cpp:1339]: Ah, thanks for the explanation.  TLDR:  After some thought, my vote is support only the `unix:` prefix.

Some thoughts for posterity.  Seems like the following are (generally) the case:
- Supporting a straightforward and uniform way to indicate usage of UNIX domain sockets makes sense (and can be less confusing to the user).  Currently Core supports unix domain sockets with `-proxy` and `-onion` (thanks to PR 27375!), and the goal is to add it for more areas, so whatever prefix is chosen should be reasonable for each of the options that can use it.
  - In the long run, support for UNIX domain sockets would be added for ZMQ (this PR), with I2P SAM proxy, on Windows, and in the GUI.  I'm not seeing use of a single prefix `unix:` being an issue for any of these applications (even in Windows, where the socket type is still called `AF_UNIX` AFAIK).
  - Users typically experience confusion when there are many possible ways to accomplish the goal (e.g. "Wait, which prefix should I use?")
  - There would be a ripple effect for guides written in the future (e.g. some tutorials/guides would state to use one prefix, and some would state to use another).  This could add confusion for users.
- Some prefixes make more sense for some options than others.  `unix:` seems to be the most straightforward and universally applicable.  `ipc://` could possibly make sense for ZMQ options since ZMQ uses the prefix, but it wouldn't make much sense for `-proxy` with Tor, so may even be a little confusing to support it there.
- Supporting multiple indicators (e.g. `unix:`, `ipc://`, etc.) simultaneously means more code and more complexity to maintain.  The added value for users accustomed to using `ipc://` with non-Bitcoin ZMQ application seems minimal compared to the effort for code maintenance.  These users could simply start using `unix:` for Bitcoin application.
- More code and more complexity typically means more bugs, vulns, more review burden, etc.  If there was a massive value gain it might be worth the effort, but doesn't like that's the case here.

**Comment by Sjors** [comment]
@wiz you may find this interesting, since Mempool also uses ZMQ

File: src/netbase.h [hunk 5]
```diff
@@ -27,8 +27,9 @@ static const int DEFAULT_CONNECT_TIMEOUT = 5000;
 //! -dns default
 static const int DEFAULT_NAME_LOOKUP = true;
 
-/** Prefix for unix domain socket addresses (which are local filesystem paths) */
-const std::string ADDR_PREFIX_UNIX = "unix:";
+/** Prefixes for unix domain socket addresses (which are local filesystem paths) */
+const std::string ADDR_PREFIX_UNIX = "unix:"; // used by bitcoind, example "unix:/root/path/to/file"
+const std::string ADDR_PREFIX_IPC = "ipc://"; // used by libzmq, example "ipc:///root/path/to/file"
```
Comment (laanwj) [inline src/netbase.h:32]: Let's move this prefix to some zmq specific header or implementation file, no need for it to be in `netbase.h`.

File: src/zmq/zmqnotificationinterface.cpp [hunk 6]
```diff
@@ -57,7 +58,10 @@ std::unique_ptr<CZMQNotificationInterface> CZMQNotificationInterface::Create(std
     {
         std::string arg("-zmq" + entry.first);
         const auto& factory = entry.second;
-        for (const std::string& address : gArgs.GetArgs(arg)) {
+        for (std::string& address : gArgs.GetArgs(arg)) {
+            // libzmq uses prefix "ipc://" for UNIX domain sockets
+            ReplaceAll(address, ADDR_PREFIX_UNIX, ADDR_PREFIX_IPC);
```
Comment (laanwj) [inline src/zmq/zmqnotificationinterface.cpp:63]: Is `ReplaceAll` the right function to use here? 
Sure, it's unlikely for it to appear multiple times, but from a principle of least surprise angle, it'd make sense to only replace the prefix.

**Comment by pinheadmz** [comment]
Rebasing on master since one commit was merged separately in #29649

**Review by tdb3 — COMMENTED** [review]
crACK for 21d0e6c7b7c7af7f6e54a45829b4fbfba6923b86.  Changes lgtm. Will follow up with some testing within the next few days as time allows.

**Review by guggero — APPROVED** [review]
Tested and code review ACK 21d0e6c7b7c7

Thanks a lot for the fix!

**Comment by tdb3** [comment]
> crACK for [21d0e6c](https://github.com/bitcoin/bitcoin/commit/21d0e6c7b7c7af7f6e54a45829b4fbfba6923b86). Changes lgtm. Will follow up with some testing within the next few days as time allows.

re ACK for 21d0e6c7b7c7af7f6e54a45829b4fbfba6923b86

Retested the following:
 - using "ipc:///tmp/mysocket" form in bitcoin.conf causes error and quit (as expected, since it's not unix:/)
 - using "notvalid:///tmp/sock" in bitcoin.conf causes error and quit (as expected, since it's not unix:/)
 - Running with LND 0.17.4 on signet with UNIX sockets for ZMQ (bitcoin.conf and lnd.conf as described above in https://github.com/bitcoin/bitcoin/pull/27679#pullrequestreview-1938090332)

File: src/init.cpp [hunk 7]
```diff
@@ -1301,30 +1301,33 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
...
+        {"-whitebind",              false},
+        {"-zmqpubhashblock",        true},
+        {"-zmqpubhashtx",           true},
+        {"-zmqpubrawblock",         true},
+        {"-zmqpubrawtx",            true},
+        {"-zmqpubsequence",         true}
     }) {
-        for (const std::string& socket_addr : args.GetArgs(port_option)) {
+        const std::string arg{port_option.first};
+        const bool unix{port_option.second};
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/init.cpp:1319]: No warnings for me locally using
```
x86_64-w64-mingw32-g++-posix (GCC) 13-posix
```

[the remark this answers is not in the document]
Comment (fanquake) [reply src/init.cpp:1319]: > No warnings for me locally using

Did you turn on the relevant warning flag

[the remark this answers is not in the document]
Comment (hebasto) [reply src/init.cpp:1319]: > > No warnings for me locally using
> 
> Did you turn on the relevant warning flag

My bad! :facepalm:
