### PR TITLE
qt: fix opening bitcoin.conf via Preferences on macOS

### LINKED ISSUE #15409: The configuration file could not be opened.
Describe the issue
`The configuration file could not be opened.` when clicking on `Open Configuration File`

What behavior did you expect?
Expected to open bitcoin.conf

How reliably can you reproduce the issue, what are the steps to do so?
Lanuch Bitcoin Core

What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?
https://bitcoin.org/en/download
v0.17.1

What type of machine are you observing the error on (OS/CPU and disk type)?
OSX

### PR DESCRIPTION
**Pull request by web3shannon**
Fix #15409. The QT wallet fail to open the configuration file on Mac, when these is no default application for `*.conf` files.

Here is a feasible way to solve this bug. When `QDesktopServices::openUrl` fails to open `file:///path/bitcoin.conf` with its default application, use `QProcess::startDetached` to run `open -t /path/bitcoin.conf` command instead, so as to open the configuration file with system's default text editor.

### CODE REVIEW

**Comment by fanquake** [comment]
> to run "open -t qtum.conf

What is `qtum.conf` ?

**Comment by shannon1916** [comment]
Sorry. Since I find this bug initially in the Qtum blockchain, I wrote it wrong...

**Comment by hebasto** [comment]
The mentioned issue #15409 is related to the setting a default application to open `*.conf` files.
This can be easily achieved via macOS GUI.

`/usr/bin/open -t` forces to open a file with default text editor. This implies the setting a default application to open `*.conf` files will not work, right?

@shannon1916 your PR description could be edited using [this GitHub tips](https://help.github.com/en/articles/closing-issues-using-keywords) ;)

**Comment by shannon1916** [comment]
@hebasto The PR description is modified as you suggest.

And, `/usr/bin/open -t` only works when `QDesktopServices::openUrl` fails, as detailed in the PR description.

**Comment by hebasto** [comment]
Concept ACK. Will test.

**Comment by hebasto** [comment]
tACK 57b30ce16cf6d4d2e6a30e70ede7f2bdd5fbc003 (macOS 10.13.6)

As my system already has a default app to open `*.conf` files, the next patch was applied for testing purpose:
```diff
diff --git a/src/util/system.cpp b/src/util/system.cpp
index 6925bda4e..a5e24c0f3 100644
--- a/src/util/system.cpp
+++ b/src/util/system.cpp
@@ -72 +72 @@ const int64_t nStartupTime = GetTime();
-const char * const BITCOIN_CONF_FILENAME = "bitcoin.conf";
+const char * const BITCOIN_CONF_FILENAME = "bitcoin.conftest";
```

File: src/qt/guiutil.cpp [hunk 1]
```diff
@@ -399,7 +400,13 @@ bool openBitcoinConf()
     configFile.close();
 
     /* Open bitcoin.conf with the associated application */
-    return QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+    bool res = QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+#if defined(Q_OS_MAC)
+    if (!res)
+        res = QProcess::startDetached("/usr/bin/open", QStringList() << "-t" << boostPathToQString(pathConfig));
```
Comment (hebasto) [inline src/qt/guiutil.cpp]: nit: could `if` statement be placed in braces?

micronit: using an initializer list is shorter: `QStringList{"-t", boostPathToQString(pathConfig)}`

File: src/qt/guiutil.cpp [hunk 2]
```diff
@@ -399,7 +400,13 @@ bool openBitcoinConf()
     configFile.close();
 
     /* Open bitcoin.conf with the associated application */
-    return QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+    bool res = QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+#if defined(Q_OS_MAC)
```
Comment (hebasto) [inline src/qt/guiutil.cpp]: nit: `#ifdef` is more common in Bitcoin Core code base ;)

File: src/qt/guiutil.cpp (hunk 1 above)
Comment (shannon1916) [reply src/qt/guiutil.cpp]: fixed in the new commit

File: src/qt/guiutil.cpp (hunk 2 above)
Comment (shannon1916) [reply src/qt/guiutil.cpp]: fixed in the new commit

**Comment by shannon1916** [comment]
@hebasto The default app for `*.conf` files can be set in `System Preferences -> Default Apps -> Extensions`, as shown below
image

**Comment by jonasschnelli** [comment]
Too bad this required a MAC #ifdef and a fixed path to an executable. But I guess it's an acceptable fix.
utACK 0ebaa3ad8c252e8d6da37ac62ed568237bbb4bad

File: src/qt/guiutil.cpp [hunk 3]
```diff
@@ -399,7 +400,14 @@ bool openBitcoinConf()
     configFile.close();
 
     /* Open bitcoin.conf with the associated application */
-    return QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+    bool res = QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+#ifdef Q_OS_MAC
+    if (!res) {
```
Comment (laanwj) [inline src/qt/guiutil.cpp]: I think this needs a comment why this fallback is necessary.

Comment (shannon1916) [reply src/qt/guiutil.cpp]: A comment like https://github.com/bitcoin/bitcoin/blob/master/src/qt/guiutil.cpp#L944 ?

**Review by fanquake — COMMENTED** [review]
Concept ACK

Have checked that this change works on `macOS` with and without a `.conf` file already in place. 
In the later case a blank `.conf` is created and opened.

Will re-ack post comment fix-up and squash.

File: src/qt/guiutil.cpp (hunk 3 above)
Comment (hebasto) [reply src/qt/guiutil.cpp]: IMO, this issue is not a _Qt_ bug. This PR addressed macOS-specific behavior.
May I suggest a comment `// Workaround for macOS-specific behavior; see #15409.` ?

Comment (shannon1916) [reply src/qt/guiutil.cpp]: Done

**Comment by hebasto** [comment]
re-ACK 6e6494b3fb345848025494cb7a79c5bf8f35e417

**Comment by fanquake** [comment]
tACK https://github.com/bitcoin/bitcoin/commit/6e6494b3fb345848025494cb7a79c5bf8f35e417 on macOS 10.14.x

Using master (c7cfd20a77ce57d200b3b9e5e0dfb0d63818abdc) you cannot open `bitcoin.conf` through the preferences menu:

Screen Shot 2019-06-03 at 9 56 04 am

Using this PR (6e6494b3fb345848025494cb7a79c5bf8f35e417):

Opening an existing `bitcoin.conf` works, and if one doesn't exist, a blank one is created and opened.

```bash
lldb Bitcoin-Qt.app -- -regtest
(lldb) target create "Bitcoin-Qt.app"
Current executable set to 'Bitcoin-Qt.app' (x86_64).
(lldb) settings set -- target.run-args  "-regtest"
(lldb) run
Process 40791 launched: '/Users/michael/github/bitcoin/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt' (x86_64)
2019-06-03 10:00:00.852544-0400 Bitcoin-Qt[40791:8481788] MessageTracer: Falling back to default whitelist
2019-06-03 10:00:07.232235-0400 open[40799:8481923] MessageTracer: Falling back to default whitelist
2019-06-03 10:00:19.079914-0400 open[40928:8482455] MessageTracer: Falling back to default whitelist
```

File: src/qt/guiutil.cpp [hunk 4]
```diff
@@ -399,7 +400,15 @@ bool openBitcoinConf()
     configFile.close();
 
     /* Open bitcoin.conf with the associated application */
-    return QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+    bool res = QDesktopServices::openUrl(QUrl::fromLocalFile(boostPathToQString(pathConfig)));
+#ifdef Q_OS_MAC
+    // Workaround for macOS-specific behavior; see #15409.
+    if (!res) {
+        res = QProcess::startDetached("/usr/bin/open", QStringList{"-t", boostPathToQString(pathConfig)});
```
Comment (promag) [inline src/qt/guiutil.cpp]: Just `"open"`?

Comment (hebasto) [reply src/qt/guiutil.cpp]:
```
high-sierra:~ hebasto$ /usr/bin/open
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-s <partial SDK name>][-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.
      -s                For -h, the SDK to use; if supplied, only SDKs whose names contain the argument value are searched.
                        Otherwise the highest versioned SDK in each platform is used.
```

Comment (hebasto) [reply src/qt/guiutil.cpp]: The explicit path seems better, right?

Comment (laanwj) [reply src/qt/guiutil.cpp]: As this is an OS specific hack, I think hardcoding the path seems fine, it's always that.

**Comment by fanquake** [comment]
Backported in #16035.
