### PR TITLE
http: bugfix: allow server shutdown in case of remote client disconnection

### LINKED ISSUE #27722: bitcoind hangs waiting for `g_requests.empty()`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

bitcoind hangs 

### Expected behaviour

bitcoind shouldn't hang

I was able to dump the running threads and it was stuck waiting for `g_requests` to be empty. The issue seems to be that this callback may not actually be called in case of error: https://github.com/bitcoin/bitcoin/blob/22139f6e83a2bedd2dad9f280567d2c76c54252f/src/httpserver.cpp#L222-L227

See this issue https://github.com/libevent/libevent/issues/589 for more details. I think what happens is that interrupting `bitcoin-cli` before it has received the reply calls the error callback and then the success callback is never called.

I think this is also a memory leak since `g_requests` won't get cleaned up. Whether it's severe or not probably depends on the caller and what type of requests they are making. This new code was introduced here https://github.com/bitcoin/bitcoin/pull/26742

### Steps to reproduce

I was running a simple shell script in 4 terminal windows for fun:

```
#!/bin/bash

for i in {1..50000}
do
	./src/bitcoin-cli -rpcuser=admin -rpcpassword=pass getrawtransaction 217819875434324c412d5e938f7f3c1670fb60814974cf7958f1fac90ee5afb7
done
```

I was messing around with this script and randomly Ctrl-C'd each terminal window in rapid succession and then when I waited up to a minute and Ctrl-C'd bitcoind, it didn't shutdown. I can reproduce it pretty reliably as well.

Compilation commands:
```
./autogen.sh; ./configure --without-wallet --with-gui=no --disable-zmq; make -j4
```

Run-time options (note that I was able to reproduce this with the default number of rpcthreads as well):
```
./src/bitcoind -txindex -rpcthreads=1 -debug
```

Output of `gcc --version`:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Output of `g++ --version`:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

My libevent version is 2.1.12

### Relevant log output

```
^C2023-05-22T20:56:10Z [http] Interrupting HTTP server
2023-05-22T20:56:10Z [rpc] Interrupting HTTP RPC server
2023-05-22T20:56:10Z [rpc] Interrupting RPC
2023-05-22T20:56:10Z tor: Thread interrupt
2023-05-22T20:56:10Z Shutdown: In progress...
2023-05-22T20:56:10Z [rpc] Stopping HTTP RPC server
2023-05-22T20:56:10Z torcontrol thread exit
2023-05-22T20:56:10Z [http] Unregistering HTTP handler for / (exactmatch 1)
2023-05-22T20:56:10Z addcon thread exit
2023-05-22T20:56:10Z [http] Unregistering HTTP handler for /wallet/ (exactmatch 0)
2023-05-22T20:56:10Z [rpc] Stopping RPC
2023-05-22T20:56:10Z net thread exit
2023-05-22T20:56:10Z [rpc] RPC stopped.
2023-05-22T20:56:10Z [http] Stopping HTTP server
2023-05-22T20:56:10Z [http] Waiting for HTTP worker threads to exit
2023-05-22T20:56:10Z [http] Exited http event loop
2023-05-22T20:56:10Z [http] Waiting for 1 requests to stop HTTP server
```

The important bit is the very last log line. bitcoind was still alive and periodically printed log lines about feeding dynamic environment data into the RNG.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

17acb2782a66f033238340e4fb81009e7f79e97a

### Operating system and version

macOS intel

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by stickies-v**
#26742 significantly increased the http server shutdown speed, but also introduced a bug (#27722 - see https://github.com/bitcoin/bitcoin/issues/27722#issuecomment-1559453982 for steps to reproduce on master) that causes http server shutdown to halt in case of a remote client disconnection. This happens because `evhttp_request_set_on_complete_cb` is never called and thus the request is never removed from `g_requests`.

This PR fixes that bug, and improves robustness of the code by encapsulating the request tracking logic. Earlier approaches (#27909, #27245, #19434) attempted to resolve this but [imo are fundamentally unsafe](https://github.com/bitcoin/bitcoin/pull/27909#discussion_r1265614783) because of differences in lifetime between an `evhttp_request` and `evhttp_connection`.

We don't need to keep track of open requests or connections, we just [need to ensure](https://github.com/bitcoin/bitcoin/pull/19420#issue-648067169) that there are no active requests on server shutdown. Because a connection can have multiple requests, and a request can be completed in various ways (the request actually being handled, or the client performing a remote disconnect), keeping a counter per connection seems like the approach with the least overhead to me.

Fixes #27722

### CODE REVIEW

**Comment by stickies-v** [comment]
cc @vasild - to follow up on our conversation last week

**Review by theStack — COMMENTED** [review]
Concept ACK

Haven't looked at the code changes yet, but can confirm that with this branch the problem as described in https://github.com/bitcoin/bitcoin/issues/27722#issuecomment-1559453982 can't be reproduced anymore on my machine.

**Comment by fanquake** [comment]
cc @Crypt-iQ @erikarvstedt

**Comment by josibake** [comment]
Concept ACK

**Comment by erikarvstedt** [comment]
Concept ACK

The nix-bitcoin test suite is now succeeding with this PR.

It seems there's no simpler strategy for implementing this:
- libevent doesn't allow attaching user data to connections
- [@vasild's suggestion](https://github.com/bitcoin/bitcoin/pull/27909/files#r1329921718) that avoids adding a connection tracking map doesn't work for multiple requests with a single connection (because only the last registered callback gets called).

Here's a [small fixup](https://github.com/erikarvstedt/bitcoin/commit/7eaf2b94330db55d64a8e5535fb87177f8e88808) that avoids a double map lookup in `RemoveRequest`.

**Comment by stickies-v** [comment]
> Here's a [small fixup](https://github.com/erikarvstedt/bitcoin/commits/2023-09/http-use-conn-counter-ea) that avoids a double map lookup in `RemoveRequest`.

Excellent suggestion, thank you. Force pushed to incorporate this - otherwise no changes.

**Comment by erikarvstedt** [comment]
[fixup! `AddRequest`: simplify, avoid double map lookup](https://github.com/erikarvstedt/bitcoin/commits/2023-09/http-use-conn-counter-ea-2)

**Comment by erikarvstedt** [comment]
[fixup! `AddRequest`: simplify, avoid double map lookup
](https://github.com/erikarvstedt/bitcoin/commits/2023-09/http-use-conn-counter-ea-2)

File: src/httpserver.cpp [hunk 1]
```diff
@@ -535,7 +527,7 @@ void StopHTTPServer()
     boundSockets.clear();
     {
         if (g_requests.CountActiveConnections() != 0) {
-            LogPrint(BCLog::HTTP, "Waiting for %d requests to stop HTTP server\n", g_requests.CountActiveRequests());
+            LogPrint(BCLog::HTTP, "Waiting for %d connections to stop HTTP server\n", g_requests.CountActiveConnections());
```
Comment (theStack) [inline src/httpserver.cpp]: to avoid grabbing the mutex twice in a row in the request tracker, could call `.CountActiveConnections` only once:
```
        if (auto connections = g_requests.CountActiveConnections(); connections != 0) {
            LogPrint(BCLog::HTTP, "Waiting for %d connections to stop HTTP server\n", connections);
        }
```

**Comment by stickies-v** [comment]
> [fixup! `AddRequest`: simplify, avoid double map lookup ](https://github.com/erikarvstedt/bitcoin/commits/2023-09/http-use-conn-counter-ea-2)

Makes sense, thank you. Force pushed to incorporate this - otherwise no changes.

**Review by theStack — COMMENTED** [review]
Light ACK a86f3f46b786d1dd60ff55b987df784107008d11

Code looks good and the bugfix approach seems solid (I'm not too familiar with libevent internals though).

Is there a simple way to trigger the "multiple-requests-per-connection" case (maybe with our functional test framework's `AuthServiceProxy`)? I've only tested the typical "one request per connection" scenario via bitcoin-cli so far.

**Review by vasild — COMMENTED** [review]
Approach ACK e3cd46c66b2d6ca866583d5ff406c62533e74d99

File: src/httpserver.cpp (hunk 1 above)
Comment (vasild) [reply src/httpserver.cpp]: Calling `CountActiveConnections()` just once will also avoid a weird message like "Waiting for 0 connections to stop HTTP server" which can happen if the function is called two times and the first call returns >0 and the second call returns 0 (the connection was closed in the meantime, after the first and before the second call).

**Comment by willcl-ark** [comment]
Approach ACK

I started with a light code review but decided to make my own minimal diff (without the connection tracking) and ended up reimplementing #27909. I've now actually read all the context, including why the approach from 27909 is less desirable, and agree with the approach here.

Incidentally, I still cannot reproduce the original issue on my system with libevent version `2.1.12-stable-8ubuntu3`. I tried with a remote `bitcoin-cli` to try and rule out some local networking-fu, but master and 25.0 still seem happy to shutdown for me no matter if there are remote-closed connections outstanding... FWIW This does mean that, without a test included, I can't actually "test" that this fix does something new.

However I can confirm that the changes here _also_ work for me:

```log
2023-10-03T09:35:35Z [http] Received a POST request for / from 127.0.0.1:51856
2023-10-03T09:35:38Z [http] Received a POST request for / from 127.0.0.1:60486
2023-10-03T09:35:38Z [http] Interrupting HTTP server
2023-10-03T09:35:38Z [http] Unregistering HTTP handler for / (exactmatch 1)
2023-10-03T09:35:38Z [http] Unregistering HTTP handler for /wallet/ (exactmatch 0)
2023-10-03T09:35:38Z [http] Stopping HTTP server
2023-10-03T09:35:38Z [http] Waiting for HTTP worker threads to exit
2023-10-03T09:35:38Z [http] Waiting for 3 connections to stop HTTP server
2023-10-03T09:35:38Z [http] Waiting for HTTP event thread to exit
2023-10-03T09:35:38Z [http] Exited http event loop
2023-10-03T09:35:38Z [http] Stopped HTTP server
```

I'd be happy to ACK this if the suggestion from @theStack was addressed.

**Review by stickies-v — COMMENTED** [review]
Force pushed to incorporate all outstanding review comments, thank you @theStack @vasild @willcl-ark for your review.


> Is there a simple way to trigger the "multiple-requests-per-connection" case (maybe with our functional test framework's `AuthServiceProxy`)? I've only tested the typical "one request per connection" scenario via bitcoin-cli so far.

I'll work on that, don't think it can be done with bitcoin-cli. I also would like to add some unit testing on `HTTPRequestTracker`, but from earlier work I've found that mocking `evhttp_request` objects proved to be a huge pain to get the memory sanitizers to pass, so I'm not sure I'll be able to get that working for this PR either (welcoming contributions there).

File: src/httpserver.cpp [hunk 2]
```diff
@@ -149,10 +150,58 @@ static GlobalMutex g_httppathhandlers_mutex;
...
+    std::unordered_map<const evhttp_connection*, size_t> m_tracker GUARDED_BY(m_mutex);
+
+    void RemoveConnectionInternal(const decltype(m_tracker)::iterator it) EXCLUSIVE_LOCKS_REQUIRED(m_mutex)
+    {
+        m_tracker.erase(it);
+        if (m_tracker.empty()) m_cv.notify_all();
+    }
+public:
+    //! Increase request counter for the associated connection by 1
+    void AddRequest(evhttp_request* req)
```
Comment (vasild) [inline src/httpserver.cpp:173]: You need this:

```diff
diff --git i/src/httpserver.cpp w/src/httpserver.cpp
index d9203f8715..069511563c 100644
--- i/src/httpserver.cpp
+++ w/src/httpserver.cpp
@@ -167,37 +167,40 @@ private:
     {
         m_tracker.erase(it);
         if (m_tracker.empty()) m_cv.notify_all();
     }
 public:
     //! Increase request counter for the associated connection by 1
-    void AddRequest(evhttp_request* req)
+    void AddRequest(evhttp_request* req) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
         const evhttp_connection* conn{Assert(evhttp_request_get_connection(Assert(req)))};
         WITH_LOCK(m_mutex, ++m_tracker[conn]);
     }
     //! Decrease request counter for the associated connection by 1, remove connection if counter is 0
-    void RemoveRequest(evhttp_request* req)
+    void RemoveRequest(evhttp_request* req) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
         const evhttp_connection* conn{Assert(evhttp_request_get_connection(Assert(req)))};
         LOCK(m_mutex);
         auto it{m_tracker.find(conn)};
         if (it != m_tracker.end() && it->second > 0) {
             if (--(it->second) == 0) RemoveConnectionInternal(it);
         }
     }
     //! Remove a connection entirely
-    void RemoveConnection(const evhttp_connection* conn)
+    void RemoveConnection(const evhttp_connection* conn) EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
         LOCK(m_mutex);
         auto it{m_tracker.find(Assert(conn))};
         if (it != m_tracker.end()) RemoveConnectionInternal(it);
     }
-    size_t CountActiveConnections() const { return WITH_LOCK(m_mutex, return m_tracker.size()); }
+    size_t CountActiveConnections() const EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
+    {
+        return WITH_LOCK(m_mutex, return m_tracker.size());
+    }
     //! Wait until there are no more connections with active requests in the tracker
-    void WaitUntilEmpty() const
+    void WaitUntilEmpty() const EXCLUSIVE_LOCKS_REQUIRED(!m_mutex)
     {
         WAIT_LOCK(m_mutex, lock);
         m_cv.wait(lock, [this]() EXCLUSIVE_LOCKS_REQUIRED(m_mutex) { return m_tracker.empty(); });
     }
 };
 //! Track active requests
```

`Mutex` has stronger requirements/guarantees. Or, in other words, `GlobalMutex` is a `Mutex` with silenced warnings because of whatever reasons.

**Review by vasild — COMMENTED** [review]
aab70f4485dab0653f3df940c29e97f8c88b0bd6 LGTM, just missing thread safety annotations:

**Comment by vasild** [comment]
> Is there a simple way to trigger the "multiple-requests-per-connection" case

I did this:
1. Prepare `/tmp/reqests`:
```
POST / HTTP/1.1
Host: 127.0.0.1
Content-Type: application/json
Authorization: Basic X91hj28...
Content-Length: 37

{"method":"help","params":[],"id":1}
POST / HTTP/1.1
Host: 127.0.0.1
Content-Type: application/json
Authorization: Basic X91hj28...
Content-Length: 58

{"method":"waitforblockheight","params":[1000000],"id":1}
```
where `X91hj28...` is stolen beforehand using `tcpdump` from a normal `bitcoin-cli help` session.

2. Then run `nc 127.0.0.1 8332 < /tmp/requests`.

This is doing two requests one after another and the second one hangs. I don't think it is possible to do two concurrent requests in one connection (at least not in HTTP 1.x).

File: src/httpserver.cpp (hunk 2 above)
Comment (stickies-v) [reply src/httpserver.cpp]: Thank you, fixed!

**Comment by stickies-v** [comment]
Force pushed to address [thread safety annotations comment](https://github.com/bitcoin/bitcoin/pull/28551#pullrequestreview-1655011953), thank you for the quick re-review!

**Review by vasild — APPROVED** [review]
ACK 68f23f57d77bc172ed39ecdd4d2d5cd5e13cf483

File: src/httpserver.cpp [hunk 3]
```diff
@@ -149,10 +151,68 @@ static GlobalMutex g_httppathhandlers_mutex;
 static std::vector<HTTPPathHandler> pathHandlers GUARDED_BY(g_httppathhandlers_mutex);
 //! Bound listening sockets
 static std::vector<evhttp_bound_socket *> boundSockets;
+
+/**
+ * @brief Helps keep track of open `evhttp_connection`s with active `evhttp_requests`
```
Comment (theStack) [inline src/httpserver.cpp:155]: tiny nit (if you have to retouch):
```suggestion
 * @brief Helps keep track of open `evhttp_connection`s with active `evhttp_request`s
```

**Review by theStack — APPROVED** [review]
ACK 68f23f57d77bc172ed39ecdd4d2d5cd5e13cf483

**Comment by fanquake** [comment]
Added to #28487 for backporting to 25.x.

**Comment by willcl-ark** [comment]
post-merge ACK based on `git range-diff a86f3f46b786d1dd60ff55b987df784107008d11...68f23f57d77bc172ed39ecdd4d2d5cd5e13cf483`
