### PR TITLE
ci: Move DEBUG=1 to centos task

### LINKED ISSUE #32524: intermittent issue in rpc_signer.py (enumeratesigners timeout) under GLIBCXX debug mode
https://cirrus-ci.com/task/5094568045051904?logs=ci#L4419

```
[18:26:32.573] test_framework.authproxy.JSONRPCException: 'enumeratesigners' RPC took longer than 1200.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
```

Looking at the full log, the test is just idle and then times out. However, there is no indication why the RPC does not proceed.

### PR DESCRIPTION
**Pull request by maflcko**
The glibcxx debug mode has many bugs in prior gcc releases:

* https://github.com/bitcoin/bitcoin/issues/32524#issuecomment-2890411766
* https://github.com/bitcoin/bitcoin/issues/31436#issuecomment-2530717875
* ...

Instead of working around all of them, just use the existing `ci_native_centos` task with gcc-14 to have it enabled. This also follows the logic of other sanitizers (tsan, asan, ubsan, msan, valgrind, ...) to generally prefer the latest version of the sanitizer for the latests features and bugfixes.

Fixes #32524.

Also, while touching the `ci_native_previous_releases`, increase g0 to g2, so that it is easier for developers to use gdb inside the CI without having to re-compile

### CODE REVIEW

**Review by hebasto — COMMENTED** [review]
Changes look correct. Waiting for CI.

**Review by hebasto — APPROVED** [review]
ACK fa58d6cdab000df288501db4a71487804b08ba4b.

File: ci/test/00_setup_env_native_previous_releases.sh [hunk 1]
```diff
@@ -20,8 +20,8 @@ export BITCOIN_CONFIG="\
  -DWITH_ZMQ=ON -DBUILD_GUI=ON -DREDUCE_EXPORTS=ON \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_C_FLAGS='-funsigned-char' \
- -DCMAKE_C_FLAGS_DEBUG='-g0 -O2' \
+ -DCMAKE_C_FLAGS_DEBUG='-g2 -O2' \
```
Comment (fanquake) [inline ci/test/00_setup_env_native_previous_releases.sh:23]: Any reason to set this to `-g2`, rather than `-g3` (the default for the Debug build type)?.

**Review by fanquake — APPROVED** [review]
ACK fa58d6cdab000df288501db4a71487804b08ba4b
