### PR TITLE
gui: Fix manual coin control with multiple wallets loaded

### LINKED ISSUE #15725: Manual coin control dialog interacts badly with multiple wallets
The coin control dialog has a single static CCoinControl object (declared in CoinControlDialog::coinControl) that it uses for all purposes.

This causes an inappropriate mixing of state between different wallets, when multiple are loaded at the same time and you flip back and forth between them while using coin control on the sending page.

For example, pick a wallet, use coin control to select a UTXO, hit OK. Then switch to a different wallet -- so far nothing will be wrong -- but now open coin control again. The UTXO in the other wallet is still selected (it will show in the summary at the top), but is not visible and can't be unselected. If you now click 'ok', the main send pane will show that there is a UTXO (from the other wallet) selected.

I can't reproduce this 100% reliably, but if I have several wallets open I can reliably make "weird broken shit" happen with a few tries.

When I try to perform a send in this state (having selected a UTXO that does not belong to the current wallet) I get an insufficient balance error (even though both the current wallet and the selected UTXO have sufficient balance.)

I think the only reasonable and correct way to fix this is to rip out the static CCoinControl object, and replace it with a per-wallet one. I am happy to do this ... at some point.

### PR DESCRIPTION
**Pull request by promag**
This PR ensures each loaded wallet has a dedicated coin control in the send view which is manipulated by the coin control dialog.

This is an alternative to #17457. Two main differences are:
 - scope reduced - no unnecessary changes unrelated to the fix;
 - approach taken - coin control instance now belongs to the send view.

All problems raised in #17457 reviews no longer apply due to the approach taken - https://github.com/bitcoin/bitcoin/pull/17457#pullrequestreview-319297589 and https://github.com/bitcoin/bitcoin/pull/17457#issuecomment-555920829)

No change in behavior if only one wallet is loaded.

Closes #15725.

### CODE REVIEW

**Comment by promag** [comment]
If possible tag 0.20. @Sjors @hebasto @gwillen would ❤️ some reviews.

**Review by ryanofsky — APPROVED** [review]
Code review ACK a8b5f1b133d4f23975a3fbfb7a415b17261466ee. Code changes are very straightforward, just replacing global CCoinControl object with SendCoinsDialog member. Not sure if this means coin control settings are reset between payments. It would be good to note in the PR description or release notes if single wallet behavior is affected

**Comment by promag** [comment]
> Not sure if this means coin control settings are reset between payments.

Yes, and new change shows if coin control dialog is opened again.

> It would be good to note in the PR description or release notes if single wallet behavior is affected

Yes, at least that's what I expect - I'll note it.

File: src/qt/coincontroldialog.h [hunk 1]
```diff
@@ -43,20 +43,18 @@ class CoinControlDialog : public QDialog
...
 public:
-    explicit CoinControlDialog(const PlatformStyle *platformStyle, QWidget *parent = nullptr);
+    explicit CoinControlDialog(CCoinControl& coin_control, WalletModel* model, const PlatformStyle *platformStyle, QWidget *parent = nullptr);
     ~CoinControlDialog();
 
-    void setModel(WalletModel *model);
-
     // static because also called from sendcoinsdialog
-    static void updateLabels(WalletModel*, QDialog*);
+    static void updateLabels(CCoinControl& m_coin_control, WalletModel*, QDialog*);
```
Comment (hebasto) [inline src/qt/coincontroldialog.h:50]: Why `updateLabels()` remains `static`?

**Review by hebasto — CHANGES_REQUESTED** [review]
Approach ACK a8b5f1b133d4f23975a3fbfb7a415b17261466ee, tested on Linux Mint 19.3: #15725 is [fixed](https://github.com/bitcoin/bitcoin/issues/15725#issuecomment-624408591).

File: src/qt/coincontroldialog.h (hunk 1 above)
Comment (promag) [reply src/qt/coincontroldialog.h:50]: That's unrelated to the fix. I do plan to pick the refactor done in #17457.

**Review by hebasto — APPROVED** [review]
ACK a8b5f1b133d4f23975a3fbfb7a415b17261466ee

**Comment by jonasschnelli** [comment]
Concept ACK.
Will detail review and test soon.
Could be a 0.20 bugfix.

File: src/qt/coincontroldialog.cpp [hunk 2]
```diff
@@ -136,6 +137,13 @@ CoinControlDialog::CoinControlDialog(const PlatformStyle *_platformStyle, QWidge
         sortView(settings.value("nCoinControlSortColumn").toInt(), (static_cast<Qt::SortOrder>(settings.value("nCoinControlSortOrder").toInt())));
 
     GUIUtil::handleCloseWindowShortcut(this);
+
+    if(_model->getOptionsModel() && _model->getAddressTableModel())
```
Comment (Sjors) [inline src/qt/coincontroldialog.cpp:141]: This needs an assert that `_model` isn't `nullptr`.

File: src/qt/coincontroldialog.h (hunk 1 above)
Comment (Sjors) [reply src/qt/coincontroldialog.h:50]: Ok, that's good to know.

**Review by Sjors — APPROVED** [review]
tACK a8b5f1b133d4f23975a3fbfb7a415b17261466ee

File: src/qt/coincontroldialog.cpp (hunk 2 above)
Comment (promag) [reply src/qt/coincontroldialog.cpp:141]: This will crash anyway.

Comment (Sjors) [reply src/qt/coincontroldialog.cpp:141]: assert crashes are marginally easier to debug afaik

Comment (promag) [reply src/qt/coincontroldialog.cpp:141]: Yes. But note that the model is received in the constructor and this dialog is instanced in `SendCoinsDialog` which already has the model set.

I'll add the assertion if I had to push again for some reason or if others think the same.

**Comment by jonasschnelli** [comment]
utACK a8b5f1b133d4f23975a3fbfb7a415b17261466ee

File: src/qt/coincontroldialog.cpp [hunk 3]
```diff
@@ -584,12 +580,6 @@ void CoinControlDialog::updateLabels(WalletModel *model, QDialog* dialog)
         label->setVisible(nChange < 0);
 }
 
-CCoinControl* CoinControlDialog::coinControl()
```
Comment (laanwj) [inline src/qt/coincontroldialog.cpp:587]: Thanks for getting rid of this.
