### PR TITLE
Stop parsing JSON after first finished construct.

### LINKED ISSUE #6558: UniValue should only parse the first JSON construct of a line
The current parser `UniValue::read` continues until it gets to the end of the parsed string (`JTOK_NONE`) or until an error occurs while lexing (`JTOK_ERR`).  If the string contains, for instance, multiple top-level objects or arrays, they are all parsed and only the last is saved in the `UniValue` object.  On the other hand, parsing fails if a valid object is followed by garbage.  (While parsing does *not* fail, surprisingly, if the string starts with a `JTOK_ERR`.)

I think this behaviour is highly confusing and should be changed.  I'm willing to work on this myself, but would like to discuss it before starting.  My suggestion is the following:

Reading from a string should only parse until a full JSON construct is found (object or array as now, or a single number/string/keyword).  Afterwards, parsing should stop and discard any trailing parts of the string completely.  I want to add also the option to return (in an optional output argument) the position where parsing stopped, so that the caller may get everything in there or check that no unparsed content remains; I do not think that Bitcoin currently needs this functionality, but it is almost "for free" and may be useful in the future.

Does this sound like a good idea, or is there a problem with my plan that I missed?

### PR DESCRIPTION
**Pull request by domob1812**
Fix https://github.com/bitcoin/bitcoin/issues/6558.  In particular, stop parsing JSON after the first object or array is finished.  Check that no other garbage follows, and fail the parser if it does.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Thanks!

Tested ACK.

**Comment by laanwj** [comment]
utACK. Looks good to me. I remember solving a similar problem in json::spirit shortly ago.

**Comment by domob1812** [comment]
Yeah, I actually noticed this due to an inconsistent behaviour between json_spirit and UniValue.  (Note, though, that a different inconsistency remains.  While the new behaviour of UniValue is to error out with anything after the first construct, json_spirit just stops parsing and *ignores* everything that follows.)

**Comment by laanwj** [comment]
> json_spirit just stops parsing and ignores everything that follows

Yes, that's what I fixed. I also changed it to error out with trailing garbage. But I didn't notice that UniValue brought back that behavior because the bug (#6226) didn't return: `ParseNonRFCJSONValue` wraps the value in an array to be able to have top-level numbers and booleans, so it was already non-tolerant of trailing garbage.

File: src/univalue/univalue_read.cpp [hunk 1]
```diff
@@ -377,9 +377,11 @@ bool UniValue::read(const char *raw)
         default:
             return false;
         }
-    }
+    } while (!stack.empty ());
 
-    if (stack.size() != 0)
+    /* Check that nothing follows the initial construct (parsed above).  */
+    tok = getJsonToken(tokenVal, consumed, raw);
```
Comment (laanwj) [inline src/univalue/univalue_read.cpp]: Nit: I'd move the definitions of tokenval and consumed here, as they're only used here.

Comment (domob1812) [inline src/univalue/univalue_read.cpp]: Well, they are also used in the loop.  That's why I moved them above it.  Of course, we could also define them *both* locally in the loop *and* then here.  Would you prefer that?

Comment (laanwj) [inline src/univalue/univalue_read.cpp]: Not necessary. I missed that, then, sorry.
