### PR TITLE
ci: Switch to gcr.io mirror to avoid rate limits

### LINKED ISSUE #31797: CI: Failed pulls from docker.io causing jobs to fail
```terminal
[15:50:52.950] STEP 1/7: FROM docker.io/debian:bookworm
[15:50:52.956] Trying to pull docker.io/library/debian:bookworm...
[15:51:23.200] time="2025-02-04T15:51:23-05:00" level=warning msg="Failed, retrying in 2s ... (1/3). Error: initializing source docker://debian:bookworm: reading manifest bookworm in docker.io/library/debian: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
[15:51:55.409] time="2025-02-04T15:51:55-05:00" level=warning msg="Failed, retrying in 2s ... (2/3). Error: initializing source docker://debian:bookworm: reading manifest bookworm in docker.io/library/debian: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
[15:52:57.833] time="2025-02-04T15:52:57-05:00" level=warning msg="Failed, retrying in 2s ... (3/3). Error: copying system image from manifest list: determining manifest MIME type for docker://debian:bookworm: reading manifest sha256:f6008b2d1c096556ec301a0c76fe0b40657594ffcfa43aaf63ca9d40767f9a63 in docker.io/library/debian: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
[15:53:30.043] Error: creating build container: initializing source docker://debian:bookworm: reading manifest bookworm in docker.io/library/debian: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
[15:53:30.051] 
[15:53:30.051] Exit status: 125

```

https://cirrus-ci.com/task/6014627928080384
https://github.com/bitcoin/bitcoin/pull/31384/checks?check_run_id=36674073808

### PR DESCRIPTION
**Pull request by maflcko**
dockerhub seems to have recently started to increase their rate limits further, beyond what is documented, even to the extent where pulling the same image twice at the same time results in a ban. See https://github.com/bitcoin/bitcoin/issues/31797#issuecomment-2656374222

Fix all issues by just using another mirror, as documented in https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images

Fixes https://github.com/bitcoin/bitcoin/issues/31797

### CODE REVIEW

File: ci/test/00_setup_env_native_asan.sh [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
 export LC_ALL=C.UTF-8
 
-export CI_IMAGE_NAME_TAG="docker.io/ubuntu:24.04"
+export CI_IMAGE_NAME_TAG="mirror.gcr.io/ubuntu:24.04"
```
Comment (0xB10C) [inline ci/test/00_setup_env_native_asan.sh:9]: the ASAN job (and others) currently runs on a GitHub hosted runner and these are exempt from the rate-limiting: https://github.com/actions/runner-images/issues/1445#issuecomment-714832439

**Comment by 0xB10C** [comment]
Agree that this is the better than having to modify all CI machines and deployments. I did some light testing on my runners and didn't see any problems in fetching the images. The CI passing here indicate the same. While switching the GitHub Actions tasks to the new images probably isn't necessary due to being exempt from the rate-limiting (https://github.com/bitcoin/bitcoin/pull/31906#discussion_r1961960848), I don't think it hurts.


ACK fa8de4706a01322fd8ab8e491d297b97f001ecff
