### PR TITLE
miner: fix empty mempool case for waitNext()

### LINKED ISSUE #9: sv2feedelta=0 doesn't push new templates
Original issue: https://github.com/Sjors/bitcoin/issues/98

### PR DESCRIPTION
**Pull request by Sjors**
Block template fees are calculated by looping over `new_tmpl->vTxFees` and return (early) once the `fee_threshold` is exceeded.

This left an edge case when the mempool is empty, which this commit fixes and adds a test for.

Also update `test/functional/interface_ipc.py` to reflect the new behavior,

Fixes https://github.com/Sjors/sv2-tp/issues/9

### CODE REVIEW

**Comment by Sjors** [comment]
This is not worth the effort to backport imo.

**Comment by Sjors** [comment]
@sipa I ended up updating `test/functional/interface_ipc.py` to reflect the new behavior, but I'm not sure what the original test tried to do in #33201.

**Review by sedited — APPROVED** [review]
ACK 2e8fff3f17366e9c2ba054023ad8bd89ac51d584

**Comment by Raimo33** [comment]
Concept ACK. this is a subtle bug which would result in an infinite loop.
Approach NACK. the proposed solution adds branching complexity for a case which is extremely unlikely.

allow me to propose a more elegant and modern solution: c23a65414f239c0d867d13f1be02a232096c1f9d

**Comment by Sjors** [comment]
Great idea, I integrated @Raimo33's approach.

**Comment by Raimo33** [comment]
> Great idea, I integrated @Raimo33's approach.

please add me as co-author or cherry-pick my commit

**Comment by Sjors** [comment]
@Raimo33 I did, see `Co-authored-by` in commit message.

**Review by sipa — COMMENTED** [review]
utACK 8f7673257a1a86717c1d83770dc857fc254df107

**Comment by optout21** [comment]
Concept ACK

Maybe add the new test in a first commit (showing how it fails), and then the fix in a new commit?
For test change without fix, and fix in see commits 3a7e58ec81fb2caeef1cf369d47b0a247d923180 and 3220ce81b1df090895daa32dfb5a1af003d6d88b

**Comment by Sjors** [comment]
@optout21 the test-each-commit job enforces that each commit has a passing test.

**Comment by optout21** [comment]
> @optout21 the test-each-commit job enforces that each commit has a passing test.

I'm not sure I understand this correctly, but if you mean that all tests should pass with each commit -- yes, first commit has test checks matching the non-fixed code (i.e. `BOOST_REQUIRE(should_be_nullptr == nullptr);`), and fix commit also adapts this one check. It's more clear looking at the fix commit what is the change in behavior, if adding the test and fix are separated.
Leaving in one commit is also fine in this PR IMHO.

File: src/node/miner.cpp [hunk 1]
```diff
@@ -522,18 +523,13 @@ std::unique_ptr<CBlockTemplate> WaitAndCreateNewBlock(ChainstateManager& chainma
...
             }
 
-            CAmount new_fees = 0;
-            for (CAmount fee : new_tmpl->vTxFees) {
-                new_fees += fee;
-                Assume(options.fee_threshold != MAX_MONEY);
-                if (new_fees >= current_fees + options.fee_threshold) return new_tmpl;
-            }
+            // Check if fees increased enough to return the new template
+            const CAmount new_fees = std::accumulate(new_tmpl->vTxFees.begin(), new_tmpl->vTxFees.end(), CAmount{0});
```
Comment (zaidmstrr) [inline src/node/miner.cpp:530]: Using `std::accumulate` in line 526 seems good, but using it in line 530 has some performance impact. `std::accumulate` search for the whole vector despite the condition already being met. With this it increases the best-case time complexity and some average-case complexity from `Ω(k)` (where k <= n) to `Ω(n)`. Any caller calling this with frequent polling might face some milliseconds of performance issues in some cases.
I feel like the approach in commit [2e8fff3](https://github.com/bitcoin/bitcoin/commit/2e8fff3f17366e9c2ba054023ad8bd89ac51d584) is more optimal than this one with the constant work of `O(1)`.

**Review by zaidmstrr — COMMENTED** [review]
Concept ACK [8f76732](https://github.com/bitcoin/bitcoin/pull/33566/commits/8f7673257a1a86717c1d83770dc857fc254df107)

File: src/node/miner.cpp (hunk 1 above)
Comment (Raimo33) [reply src/node/miner.cpp:530]: you're talking about theoretical complexity. but I'm almost certain that the `std::accumulate` approach is orders of magnitude faster in practice when you measure absolute time. this is because avoiding a branch at every iteration allows for optimizations such as SIMD vectorization, or even simply a better data access pattern which is more cache friendly.

I'd love to see some benchmarks!

Comment (Sjors) [reply src/node/miner.cpp:530]: I think the reduced code complexity is worth losing the early return. After cluster cluster mempool this calculation will probably be replaced anyway.

**Comment by optout21** [comment]
ACK 8f7673257a1a86717c1d83770dc857fc254df107

File: src/node/miner.cpp (hunk 1 above)
Comment (cedwies) [reply src/node/miner.cpp:530]: I ran a small external python simulation to get a rough sense of how often the early-exit fee loop would actually stop much earlier than a full sum under realistic mempool conditions.

Using a model with **3000 txs** (fees = feerate × vsize, realistic feerate ranges, small per-tick mempool drift, and occasional high-fee arrivals), the results were:
– `threshold=0`: **median touch fraction ≈ 0.97**, meaning in a typical run the loop still scans about 97% of transactions before returning; about 43 % of trials didn’t beat the old total at all.
– `threshold=100.000`: **median = 1.0**, early exit never triggered within a tick.

On my machine (Apple M2 Max), summing all 3000 fees takes about **0.4 µs,** so the median time saved by early-exit was around **0.01 µs (10 ns)** (essentially negligible).
This could suggest that early-exit almost never helps in practice, while the `std::accumulate` has the benefits already discussed.

**Comment by cedwies** [comment]
tACK 8f76732

Reviewed and tested. The empty mempool case (`fee_threshold==0`) now behaves as expected and is covered by tests.

File: src/node/miner.cpp (hunk 1 above)
Comment (zaidmstrr) [reply src/node/miner.cpp:530]: Thanks for the benchmarking. But I think to simulate the actual mempool behaviour is complicated. The order of transactions inside mempool is not very deterministic based on fee. So we can't predict that our threshold always will be hit at the last stages of search, even though it searches till the last in most of the cases, but that's not for all.  The function also uses polling, so if you increase the number of executions, the time will increase a bit. But as Sjors said, this calculation will be removed by cluster mempool work later on. So I think we can go with this for now.

**Comment by Sjors** [comment]
@glozow thanks, can you add a backport label for 30.x?

**Comment by fanquake** [comment]
Backported to `30.x` in #33609.
