### PR TITLE
wallet: Update transactions with current mempool after load

### LINKED ISSUE #15591: balance wrong after unloading wallet and loading it again
Have two wallets used by this instance of bitcoind. The default wallet has balance 0.02861762.
Initially reported balance is correct but after unloading the wallet and then loading it again, the balance is wrong. Neither of the wallets have the reported balance.

I expected the balance to be the same as initially reported.
```
btc@ubuntu:~$ bitcoin-cli  -getinfo
{
  "version": 170100,
  "protocolversion": 70015,
  "walletversion": 159900,
  "balance": 0.02861762,
...

btc@ubuntu:~$ bitcoin-cli  loadwallet wallet2
btc@ubuntu:~$ bitcoin-cli unloadwallet ""
btc@ubuntu:~$ bitcoin-cli loadwallet ""
btc@ubuntu:~$ bitcoin-cli unloadwallet wallet2
btc@ubuntu:~$ bitcoin-cli  -getinfo
{
  "version": 170100,
  "protocolversion": 70015,
  "walletversion": 159900,
  "balance": 0.01012607,
...
```
The balance 0.01012607 is wrong and I have no idea where that number came from.
Restarting the process results in correct balance again.

ubuntu package for bionic

### PR DESCRIPTION
**Pull request by promag**
Fixes #15591.

### CODE REVIEW

**Comment by promag** [comment]
If it's the right fix then it needs:
 - update to functional test
 - backport to 0.17 and 0.18.

**Comment by gmaxwell** [comment]
Do we also need to think about how this interacts with restoring the mempool from disk? e.g. is there a race condition where some transactions being loaded would be missed?

**Comment by promag** [comment]
IIUC if the mempool is loaded after postInitProcess then TransactionAddedToMempool is already called.

**Comment by laanwj** [comment]
Ordering checks out:

- `CWallet::postInitProcess()` is called first: current mempool will be used, wallet will be notified when transactions added to mempool in `LoadMempool()`
 - `LoadMempool()` called first:  `CWallet::postInitProcess()` will process all the transactions

As for concurrency:

`CWallet::postInitProcess()` locks the mempool for the duration of loading transactions from it. `LoadMempool()` locks the mempool for every individual transaction inserted. This means that it is posible for `CWallet::postInitProcess()` to be called *while* the mempool is being loaded. If it manages to get the lock, it will process the current transactions in the mempool, potentially partially complete.

Is the wallet already registered at this point (before `CWallet::postInitProcess()`) for receiving `TransactionAddedToMempool ` events? If so, there is no race, but it might get some transactions multiple time (I think that's harmless?), if not, it will start receiving transactions again after registering and miss some in that timeframe.

**Comment by promag** [comment]
Wallet ins registered in `CWallet::CreateWalletFromFile`: https://github.com/bitcoin/bitcoin/blob/7b13c646457980f44599412f243694fa682a1abf/src/wallet/wallet.cpp#L4386
which happens before `CWallet::postInitProcess`, so I think there's no race.

**Comment by promag** [comment]
> but it might get some transactions multiple time (I think that's harmless?)

I also think that trying to improve that is not worth the pain/complexity. But it may cost a bit for large wallets and a large mempool. I'm happy to followup something to improve that.

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -4401,6 +4401,12 @@ void CWallet::postInitProcess()
     // Add wallet transactions that aren't already in a block to mempool
     // Do this here as mempool requires genesis block to be loaded
     ReacceptWalletTransactions();
+
+    // Update wallet transactions with current mempool transactions.
+    LOCK(::mempool.cs);
```
Comment (promag) [inline src/wallet/wallet.cpp]: nit, this lock is not at the begin of a scope, could move this to a new `CWallet` member.

**Comment by laanwj** [comment]
> I also think that trying to improve that is not worth the pain/complexity. But it may cost a bit for large wallets and a large mempool. I'm happy to followup something to improve that.

I agree, just wanted to cover all possible scenarios.

**Comment by promag** [comment]
Moved the fix to `LoadWallet()`, which is used to dynamically load wallets - and so the startup behavior isn't changed.

Also added a test.

**Comment by MarcoFalke** [comment]
```
 node1 2019-03-23T13:08:34.742866Z POTENTIAL DEADLOCK DETECTED 
 node1 2019-03-23T13:08:34.742874Z Previous lock order was: 
 node1 2019-03-23T13:08:34.742883Z  (1) ::mempool.cs  wallet/wallet.cpp:152 
 node1 2019-03-23T13:08:34.742898Z  (2) cs_main  interfaces/chain.cpp:264 
 node1 2019-03-23T13:08:34.742912Z Current lock order is: 
 node1 2019-03-23T13:08:34.742921Z  (2) cs_main  init.cpp:1475 
 node1 2019-03-23T13:08:34.742934Z  (2) cs_main  validation.cpp:4300 
 node1 2019-03-23T13:08:34.742947Z  (1) cs  txmempool.cpp:593 
```

**Comment by promag** [comment]
@MarcoFalke fixed.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -146,6 +146,15 @@ std::shared_ptr<CWallet> LoadWallet(interfaces::Chain& chain, const WalletLocati
     }
     AddWallet(wallet);
     wallet->postInitProcess();
+
+    {
+        // Update wallet transactions with current mempool transactions.
+        LOCK2(cs_main, ::mempool.cs);
+        for (const CTxMemPoolEntry& entry : ::mempool.mapTx) {
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: The wallet module is not allowed to call directly into the node. This should be an interface method.

Comment (promag) [reply src/wallet/wallet.cpp]: Right, added 51cb2eb and then refactored `LoadWallet` to use it.

**Comment by MeshCollider** [comment]
tested ACK https://github.com/bitcoin/bitcoin/pull/15652/commits/3e31d680c55101c476a4a3db488cd29fb3dbea23, cannot reproduce #15591 with this fix

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -146,6 +146,15 @@ std::shared_ptr<CWallet> LoadWallet(interfaces::Chain& chain, const WalletLocati
     }
     AddWallet(wallet);
     wallet->postInitProcess();
+
+    {
+        // Update wallet transactions with current mempool transactions.
+        auto locked_chain = chain.lock();
+        for (const CTransactionRef& tx : locked_chain->getMemoryPoolTransactions()) {
+            wallet->TransactionAddedToMempool(tx);
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: Could there be a race, since we don't take cs_main when removing txs from the mempool?

I.e. a tx is first removed due to eviction, the wallet is notified and then it is re-added here.

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -146,6 +146,15 @@ std::shared_ptr<CWallet> LoadWallet(interfaces::Chain& chain, const WalletLocati
     }
     AddWallet(wallet);
     wallet->postInitProcess();
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: Any reason not to do this in `postInitProcess`?

I understand that this is also called when the `createwallet` rpc is called, but the post-init seems useless in that case anyway.

I'd suggest:
* Remove `postInitProcess` from `createwallet`, because the wallet is fresh and there couldn't be any txs that need to be exchanged between mempool and wallet
* Rename `postInitProcess` to `postLoadProcess`, since it is not needed on init, but on load
* Move the below code into `postLoadProcess` with mempool::cs hold while adding the txs.

**Review by maflcko — COMMENTED** [review]
Concept ACK

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (promag) [reply src/wallet/wallet.cpp]: I agree, `postInitProcess` is "pre dynamic wallet support". However I'd prefer to refactor in a different PR, this is a bug fix.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (promag) [reply src/wallet/wallet.cpp]: Indeed, between `getMemoryPoolTransactions` and `TransactionAddedToMempool` a tx can be evicted.

I see 2 solutions:
 - lock the wallet before the loop so that `TransactionRemovedFromMempool` comes after this
 - add a way to lock the mempool in `interfaces::` but not sure if this is wanted? cc @ryanofsky

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (MarcoFalke) [reply src/wallet/wallet.cpp]: Fine with doing the rename et al. later, but is there any reason not to put it in `postInitProcess`? IIRC it was in there previously in this pull

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (MarcoFalke) [reply src/wallet/wallet.cpp]: If you move the loop into `postInitProcess`, you can just take a `LOCK(::mempool.cs)` in there

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (promag) [reply src/wallet/wallet.cpp]: Yes, could be moved back there.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (promag) [reply src/wallet/wallet.cpp]: @MarcoFalke `postInitProcess` is wallet module, should not use that right? https://github.com/bitcoin/bitcoin/pull/15652#discussion_r268407542

Comment (MarcoFalke) [reply src/wallet/wallet.cpp]: Yeah, you'd have to move it to the interface

Alternatively you could add it to `handleNotifications` as suggested by @ryanofsky, but then it would also be called for `createwallet`, which seems a bit wasteful

Comment (promag) [reply src/wallet/wallet.cpp]: @ryanofsky nice, I thought of something like `replayMemoryPoolNotifications`. However I'm not sure if these notifications should come after `ReacceptWalletTransactions`?

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -146,6 +146,7 @@ std::shared_ptr<CWallet> LoadWallet(interfaces::Chain& chain, const WalletLocati
...
+
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: in commit 596f91d20732a1714395e9f6e5d1e6c41f14a2e5:

Could remove empty hunk to avoid having to solve conflicts in a backport?

File: src/interfaces/chain.cpp [hunk 6]
```diff
@@ -367,6 +367,13 @@ class ChainImpl : public Chain
     {
         return MakeUnique<RpcHandlerImpl>(command);
     }
+    void notifyMemoryPoolTransactions(Notifications& notifications) override
+    {
+        LOCK2(::cs_main, ::mempool.cs);
```
Comment (MarcoFalke) [inline src/interfaces/chain.cpp]: Not sure how to solve the deadlock warning. Maybe take cs_wallet before both of these?

```
node1 2019-03-25T17:06:10.586193Z Leaving InitialBlockDownload (latching to false) 
 node1 2019-03-25T17:06:10.586301Z POTENTIAL DEADLOCK DETECTED 
 node1 2019-03-25T17:06:10.586314Z Previous lock order was: 
 node1 2019-03-25T17:06:10.586326Z  ::cs_main  interfaces/chain.cpp:372 
 node1 2019-03-25T17:06:10.586335Z  (1) ::mempool.cs  interfaces/chain.cpp:372 
 node1 2019-03-25T17:06:10.586350Z  cs_main  interfaces/chain.cpp:264 
 node1 2019-03-25T17:06:10.586359Z  (2) cs_wallet  wallet/wallet.cpp:1230 
 node1 2019-03-25T17:06:10.586386Z Current lock order is: 
 node1 2019-03-25T17:06:10.586397Z  cs_main  interfaces/chain.cpp:264 
 node1 2019-03-25T17:06:10.586406Z  (2) cs_wallet  wallet/wallet.cpp:1871 
 node1 2019-03-25T17:06:10.586419Z  (1) pool.cs  validation.cpp:580

File: src/interfaces/chain.h [hunk 7]
```diff
@@ -269,6 +269,9 @@ class Chain
     //! Register handler for RPC. Command is not copied, so reference
     //! needs to remain valid until Handler is disconnected.
     virtual std::unique_ptr<Handler> handleRpc(const CRPCCommand& command) = 0;
+
+    //! Notify handler of all memory pool transactions.
+    virtual void notifyMemoryPoolTransactions(Notifications& notifications) = 0;
```
Comment (ryanofsky) [inline src/interfaces/chain.h]: Could you call this notifyMempoolTransactions? I'd like to converge on _mempool_ spelling rather than _memPool_ or _memoryPool_. Currently we have:

<pre>
Chain::hasDescendantsIn<i>Mempool</i>
Chain::<i>mempool</i>MinFee
Chain::Notifications::TransactionAddedTo<i>Mempool</i>
Chain::Notifications::TransactionRemovedFrom<i>Mempool</i>
Chain::Lock::submitTo<i>MemoryPool</i>
</pre>

so the only existing exception is the `Chain::Lock` method, which I want to go away anyway.

File: src/interfaces/chain.cpp (hunk 6 above)
Comment (ryanofsky) [reply src/interfaces/chain.cpp]: re: https://github.com/bitcoin/bitcoin/pull/15652#discussion_r268760261

> Not sure how to solve the deadlock warning. Maybe take cs_wallet before both of these?

It looks like you need to do the opposite and release cs_wallet before calling this.

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (ryanofsky) [reply src/wallet/wallet.cpp]: re: https://github.com/bitcoin/bitcoin/pull/15652#discussion_r268645607

> Alternatively you could add it to handleNotifications as suggested by @ryanofsky, but then it would also be called for createwallet, which seems a bit wasteful

Agree, this would be too wasteful. Having the separate method to replay notifications is probably better.

> I'm not sure if these notifications should come after ReacceptWalletTransactions?

I'm not 100% sure, but I don't think I see a problem if notifications about what's already in the mempool happen before the wallet adds more transactions to the mempool. I think what you have now basically seems good though.

File: src/interfaces/chain.cpp (hunk 6 above)
Comment (MarcoFalke) [reply src/interfaces/chain.cpp]: The lock order is `cs_main, cs_wallet, ::mempool.cs`, no?

Comment (MarcoFalke) [reply src/interfaces/chain.cpp]: I can get the functional tests to pass with the diff

```diff
diff --git a/src/interfaces/chain.cpp b/src/interfaces/chain.cpp
index cb76461647..94e7a7ad53 100644
--- a/src/interfaces/chain.cpp
+++ b/src/interfaces/chain.cpp
@@ -367,9 +367,9 @@ public:
     {
         return MakeUnique<RpcHandlerImpl>(command);
     }
-    void notifyMemoryPoolTransactions(Notifications& notifications) override
+    void notifyMemoryPoolTransactions(Notifications& notifications, RecursiveMutex&cs_wallet) override
     {
-        LOCK2(::cs_main, ::mempool.cs);
+        LOCK2(::cs_main, cs_wallet);         LOCK(::mempool.cs);
         for (const CTxMemPoolEntry& entry : ::mempool.mapTx) {
             notifications.TransactionAddedToMempool(entry.GetSharedTx());
         }
diff --git a/src/interfaces/chain.h b/src/interfaces/chain.h
index 3fa63d83be..b53d170645 100644
--- a/src/interfaces/chain.h
+++ b/src/interfaces/chain.h
@@ -7,6 +7,7 @@
 
 #include <optional.h>               // For Optional and nullopt
 #include <primitives/transaction.h> // For CTransactionRef
+#include <sync.h> // For RecursiveMutex
 
 #include <memory>
 #include <stddef.h>
@@ -271,7 +272,7 @@ public:
     virtual std::unique_ptr<Handler> handleRpc(const CRPCCommand& command) = 0;
 
     //! Notify handler of all memory pool transactions.
-    virtual void notifyMemoryPoolTransactions(Notifications& notifications) = 0;
+    virtual void notifyMemoryPoolTransactions(Notifications& notifications,RecursiveMutex&cs_wallet) = 0;
 };
 
 //! Interface to let node manage chain clients (wallets, or maybe tools for
diff --git a/src/wallet/wallet.cpp b/src/wallet/wallet.cpp
index 554ee62547..d72201679a 100644
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -4404,7 +4404,7 @@ void CWallet::postInitProcess()
     ReacceptWalletTransactions();
 
     // Update wallet transactions with current mempool transactions.
-    m_chain.notifyMemoryPoolTransactions(*this);
+    m_chain.notifyMemoryPoolTransactions(*this, cs_wallet);
 }
 
 bool CWallet::BackupWallet(const std::string& strDest)

File: src/interfaces/chain.h (hunk 7 above)
Comment (promag) [reply src/interfaces/chain.h]: Will do.

**Comment by promag** [comment]
Updated, moved to where the locks are held in the right order. Needs squash though.

**Comment by Sjors** [comment]
818b127 makes the new test pass on macOS. Don't forget to rename the "wip" commit.

**Comment by MarcoFalke** [comment]
Please squash to make it ready for review

File: src/wallet/wallet.cpp [hunk 8]
```diff
@@ -1890,6 +1890,9 @@ void CWallet::ReacceptWalletTransactions()
         CValidationState state;
         wtx.AcceptToMemoryPool(*locked_chain, state);
     }
+
+    // Update wallet transactions with current mempool transactions.
+    chain().notifyMempoolTransactions(*this);
```
Comment (jnewbery) [inline src/wallet/wallet.cpp]: I don't like this going in `ReacceptWalletTransactions()` for a couple of reasons:

- The name `ReacceptWalletTransactions()` suggests to me that we're reaccepting wallet transactions back into the mempool (which is what the function currently does). Adding functionality to fetch mempool txs back into the wallet changes the definition of this function so that it no longer matches the name.
- `ReacceptWalletTransactions()` is called by various import* RPCs, which don't need to refetch the mempool txs into the wallet.

I suggest moving this call into `postInitProcessing()` which is only called when a wallet is loaded.

File: src/interfaces/chain.h [hunk 9]
```diff
@@ -269,6 +269,9 @@ class Chain
     //! Register handler for RPC. Command is not copied, so reference
     //! needs to remain valid until Handler is disconnected.
     virtual std::unique_ptr<Handler> handleRpc(const CRPCCommand& command) = 0;
+
+    //! Notify handler of all memory pool transactions.
+    virtual void notifyMempoolTransactions(Notifications& notifications) = 0;
```
Comment (jnewbery) [inline src/interfaces/chain.h]: nit: I'd prefer the name `getMempoolTransactions()` or `fetchMempoolTransactions()`. Notify to me signifies that the wallet is subscribing and getting a notification, whereas this interface function is actually used by the wallet to actively fetch the mempool transactions.

**Review by jnewbery — COMMENTED** [review]
Great stuff @promag . Thanks for this, and for adding a test.

I have a couple of small suggestions inline, which I've implemented here: https://github.com/jnewbery/bitcoin/tree/pr15652.0

File: src/wallet/wallet.cpp (hunk 8 above)
Comment (promag) [reply src/wallet/wallet.cpp]: Fixed.

File: src/interfaces/chain.h (hunk 9 above)
Comment (promag) [reply src/interfaces/chain.h]: > I'd prefer the name `getMempoolTransactions()` or `fetchMempoolTransactions()`.

I think these are confusing since the function is void.

Comment (promag) [reply src/interfaces/chain.h]: > Notify to me signifies that the wallet is subscribing and getting a notification

The "standard" for that is `handleX`, like `handleNotifications`.

File: src/wallet/wallet.cpp (hunk 8 above)
Comment (promag) [reply src/wallet/wallet.cpp]: > I suggest moving this call into `postInitProcessing()` which is only called when a wallet is loaded.

This was attempted before but there was a locking order problem, and was for that reason that I've placed `notifyMempoolTransactions` here. I've included 0994e3121 to address that.

The important thing to ensure is https://github.com/bitcoin/bitcoin/pull/15652#discussion_r268783330.

**Comment by MarcoFalke** [comment]
utACK 3bf22a78c2e9951a7e7febb20577f2b6ac178bfc

File: src/interfaces/chain.h (hunk 9 above)
Comment (ryanofsky) [reply src/interfaces/chain.h]: re: https://github.com/bitcoin/bitcoin/pull/15652#discussion_r269275899

Agree with John the name is not great. I think I'd probably call it `pushMempoolNotifications`.

More importantly, though, I think this needs to have a comment saying how it relates to `handleNotifications`. A good comment might be:

"Synchronously send TransactionAddedToMempool notifications about all current mempool entries to the specified handler. To avoid race conditions where out of date TransactionAddedFromMempool / TransactionRemovedFromMempool asynchronous notifications previously requested through `handleNotifications` would arrive during or after this call, this will block waiting for any previous asynchronous notifications to complete, and prevent new asynchronous notifications from being sent until this returns."

I will say writing this makes me think the interface is overcomplicated. I guess I'd prefer my original suggestion of just sending `TransactionAddedFromMempool` notifications atomically in the same place the handler is registered: https://github.com/bitcoin/bitcoin/pull/15652#discussion_r268675190. Marco pointed out this would be wasteful in the case of `createwallet` calls https://github.com/bitcoin/bitcoin/pull/15652#discussion_r268710750, but the notifications could be optional if the waste is too much.

Comment (jnewbery) [reply src/interfaces/chain.h]: `requestMempoolTransactions()`?

Agree with Russ about adding a comment.

Comment (promag) [reply src/interfaces/chain.h]: > just sending TransactionAddedFromMempool notifications atomically in the same place the handler is registered

I understand it is cleaner but it is weird to have receive notifications before `handleNotifications` return. Thanks for the comment!

Eeny, meeny, miny, moe `requestMempoolTransactions`, after all we want to be notified of mempool transactions.

**Comment by jnewbery** [comment]
utACK 78ce8e91031ea8a87c55deeb060071d7dc26358e

File: src/interfaces/chain.h (hunk 9 above)
Comment (ryanofsky) [reply src/interfaces/chain.h]: > but it is weird to receive notifications before handleNotifications return

This is the current behavior and it isn't weird. Notifications start to arrive when RegisterValidationInterface is called, and can happen before that function returns, much less before handleNotifications returns.

**Comment by ryanofsky** [comment]
I think there's probably still a race condition here because add/remove notifications scheduled before the request for mempool transactions could arrive after the request:

https://github.com/bitcoin/bitcoin/blob/656a15e5394d8d841619b5b186fa0f9c8be0322b/src/validationinterface.cpp#L155

https://github.com/bitcoin/bitcoin/blob/656a15e5394d8d841619b5b186fa0f9c8be0322b/src/validationinterface.cpp#L138

You might need to block waiting for previous notifications.

File: src/interfaces/chain.h (hunk 9 above)
Comment (promag) [reply src/interfaces/chain.h]: > This is the current behavior

Currently `cs_main` and cs_wallet` are locked when `handleNotifications` is called so that doesn't happen, but otherwise you are right.

File: src/interfaces/chain.cpp [hunk 10]
```diff
@@ -367,6 +367,13 @@ class ChainImpl : public Chain
     {
         return MakeUnique<RpcHandlerImpl>(command);
     }
+    void requestMempoolTransactions(Notifications& notifications) override
```
Comment (ryanofsky) [inline src/interfaces/chain.cpp]: re: https://github.com/bitcoin/bitcoin/pull/15652#issuecomment-477271519

> You might need to block waiting for previous notifications.

One way to do this:

```c++
void requestMempoolTransactions(Notifications& notifications) override
{
    std::promise<void> promise;
    CallFunctionInValidationInterfaceQueue([&] {
        LOCK2(::cs_main, ::mempool.cs);
        for (const CTxMemPoolEntry& entry : ::mempool.mapTx) {
            notifications.TransactionAddedToMempool(entry.GetSharedTx());
        }
        promise.set_value();
    });
    promise.get_future().wait();
}
```

Comment (ryanofsky) [reply src/interfaces/chain.cpp]: Previous suggestion in https://github.com/bitcoin/bitcoin/pull/15652/files#r269965497 isn't exception safe. Also, cs_main needs to be released before calling this.

Probably better:

```c++
void requestMempoolTransactions(Notifications& notifications) override
{
    std::packaged_task<void()> task([&] {
        LOCK2(::cs_main, ::mempool.cs);
        for (const CTxMemPoolEntry& entry : ::mempool.mapTx) {
            notifications.TransactionAddedToMempool(entry.GetSharedTx());
        }
    });
    CallFunctionInValidationInterfaceQueue([&] { task(); });
    task.get_future().get();
}
```

Comment (promag) [reply src/interfaces/chain.cpp]: Thanks @ryanofsky!

Comment (promag) [reply src/interfaces/chain.cpp]: Haven't finished but it looks like there will be a lock order issue - cs_main -> mempool.cs -> cs_main -> cs_wallet.

Comment (ryanofsky) [reply src/interfaces/chain.cpp]: re: https://github.com/bitcoin/bitcoin/pull/15652#discussion_r270050754

> Haven't finished but it looks like there will be a lock order issue - cs_main -> mempool.cs -> cs_main -> cs_wallet.

That does seem like a problem. One way to fix it would be to release main and mempool locks before calling TransactionAddedToMempool, by pushing the transactions to a vector, releasing the locks and then looping over the vector.

Alternately if you changed the function to `pushMempoolTransactions(std::function<void(std::vector<CTransactionRef> push_fn))` you could release the locks and then send the vector to the wallet directly. Both of these changes would be nice optimizations for #10102, since passing a vector once across the socket is more efficient than calling `TransactionAddedToMempool` repeatedly and requiring lots of roundtrip traffic.

**Comment by ryanofsky** [comment]
Sorry for the churn and for keeping suggesting new code changes. If you want to go with a simple change that fixes the original bug and can be backported, but maybe is less efficient or has some obscure race conditions, that seems fine.

**Comment by promag** [comment]
@ryanofsky no problem at all! I think this is ready now.

File: src/interfaces/chain.cpp (hunk 10 above)
Comment (ryanofsky) [reply src/interfaces/chain.cpp]: re: https://github.com/bitcoin/bitcoin/pull/15652#discussion_r269965497

Current code looks ok, but I think I was misguided in making this thread because previous code in d94847f20c750d88a0aefa572155d54f8e39c144 was also ok. I think:

1) I was right to point out there's a race condition where normal mempool add/remove notifications triggered before the `requestMempoolTransactions` call could arrive out of order during and after the call
2) I was wrong to assume that the race condition would actually cause a problem. There is no problem if an unknown transaction is removed or an already added transaction is added again.
3) I was wrong to think that my proposed changes would actually prevent add/remove notifications from arriving out of order. In fact, they would only prevent older add/remove notifications from arriving _during_ the `requestMempoolTransactions` call, not _after_ the call.

So, I think if you want go back to the simpler implementation in d94847f20c750d88a0aefa572155d54f8e39c144 that would be fine.

Or if you did want to prevent obsolete add/remove notifications from arriving _after_ the `requestMempoolTransactions` call in addition to _during_, you'd need acquire the locks before calling `CallFunctionInValidationInterfaceQueue` and also fill the vector at the same time:

```c++
void requestMempoolTransactions(Notifications& notifications) override
{
    std::vector<CTransactionRef> transactions;
    std::packaged_task<void()> task([&] {
        for (const CTransactionRef& tx : transactions) {
            notifications.TransactionAddedToMempool(tx);
        }
    });
    {
        LOCK2(::cs_main, ::mempool.cs);
        for (const CTxMemPoolEntry& entry : ::mempool.mapTx) {
            transactions.push_back(entry.GetSharedTx());
        }
        CallFunctionInValidationInterfaceQueue([&] { task(); });
    }
    AssertLockNotHeld(::cs_main);
    AssertLockNotHeld(::mempool.cs);
    task.get_future().get();
}
```

**Review by ryanofsky — APPROVED** [review]
utACK 3c3dfe8fde151070272f3fea70cd27150ffd1c03

**Comment by MarcoFalke** [comment]
If the branch that had d94847f in works without a `future` include and is correct, I'd prefer that

**Comment by ryanofsky** [comment]
> If the branch that had d94847f in works without a future include and is correct, I'd prefer that

Branch is correct but the `requestMempoolTransactions` comment there doesn't accurately describe what the function does. Comment could just be updated to warn that `requestMempoolTransactions` is not synchronized with `handleNotifications`, and obsolete `handleNotifications` notifications could arrive during and after notifications sent by `requestMempoolTransactions` (but that this is harmless because wallet will ignore notifications about removed transactions it doesn't know about or added transactions that are already added).

File: src/interfaces/chain.cpp (hunk 10 above)
Comment (promag) [reply src/interfaces/chain.cpp]: > I was wrong to assume that the race condition would actually cause a problem. There is no problem if an unknown transaction is removed or an already added transaction is added again.

Right, just unnecessary extra work, which is not an issue I think.

**Comment by MarcoFalke** [comment]
re-utACK 78ce8e91031ea8a87c55deeb060071d7dc26358e

Only change since my last review is renaming a method and adding a comment. (Haven't read the comment)

**Comment by jnewbery** [comment]
utACK 78ce8e91031ea8a87c55deeb060071d7dc26358e modulo the comment change that Russ requested.

**Comment by MarcoFalke** [comment]
Tested that 78ce8e91031ea8a87c55deeb060071d7dc26358e fails the test when run without compiling the bitcoind changes.

**Review by ryanofsky — APPROVED** [review]
utACK 78ce8e91031ea8a87c55deeb060071d7dc26358e. Lot of things I don't like about this PR but this seems fine as a fix, and thanks for considering all my suggestions.

In my opinion the nearest-best fix was https://github.com/bitcoin/bitcoin/commits/3c3dfe8fde151070272f3fea70cd27150ffd1c03, because it didn't require new postInitProcess / ReacceptWalletTransactions locking added in this version of the PR. The new locking is more complicated than it first appears, because it relies on locking cs_main recursively, and may be deadlock-prone because it sometimes is and sometimes isn't holding the cs_main lock when sending TransactionAdded notifications. (I would prefer to never be holding cs_main when sending _any_ notification, which would have been the case after #15632 with the other version of this PR.)

In case anyone wants to clean this up in the future, I think the ideal solution would be to combine https://github.com/bitcoin/bitcoin/commits/3c3dfe8fde151070272f3fea70cd27150ffd1c03 with perfectly ordered cs_main free notifications implemented in https://github.com/bitcoin/bitcoin/pull/15652#discussion_r270460939, and also dropping the requestMempoolTransactions function entirely, just replacing it with an optional new mempool parameter to handleNotifications (optional callback function taking a std::vector\<CTransactionRef> argument).

**Review by ryanofsky — APPROVED** [review]
utACK 4bf1b1cefa9723bf2cfa8b1a938757abc99bb17b. Only change is code comment in second commit.

**Comment by MarcoFalke** [comment]
re-utACK 4bf1b1cefa

Only the comment changed, didn't look at either the old or new comment.

**Comment by jnewbery** [comment]
utACK 4bf1b1cefa9723bf2cfa8b1a938757abc99bb17b

**Comment by ryanofsky** [comment]
Merge commit 5a2a9b5b0603c1206e4419ffd0fd0d4939813fc2 seems to be missing an ack: https://github.com/bitcoin/bitcoin/pull/15652#pullrequestreview-221199549

**Comment by MarcoFalke** [comment]
This is an upstream issue on GitHub, I believe. Will follow up with some details shortly

**Comment by MarcoFalke** [comment]
Comments:
* https://api.github.com/repos/bitcoin/bitcoin/issues/15652/comments
Review summary comments:
* https://api.github.com/repos/bitcoin/bitcoin/pulls/15652/reviews

They are showing my "Concept ACK" above, but for some reason not your utACK...

**Comment by MarcoFalke** [comment]
Will follow up with GitHub support

**Comment by fanquake** [comment]
Backported in https://github.com/bitcoin/bitcoin/pull/15691.
