### PR TITLE
descriptors: Try pubkeys of both parities when retrieving the private keys for an xonly pubkey in a descriptor

### LINKED ISSUE #31589: P2TR Spending Bug - Signing Transaction Failed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Some Segwit Version 1 Addresses generated with [Achow101's Rust-Vanitygen](https://github.com/achow101/rust-vanitygen), or more generally some random Addresses imported using the `tr(<WIF Private Key>)` Descriptor, cause an issue when spending coins using them. Generally, the "Signing transaction failed" error occurs and the transaction is not created. Though, a workaround still allows to spend the coins.

I don't know if the issue is exclusive to P2TR, but never encountered such problems with Vanity Version 0 Addresses in the past... I also did not encounter such issue with P2TR Addresses directly generated in Bitcoin Core with `getnewaddress` or so.

Maybe it is the same issue as #5828, which was however not been reported with a concrete and reproducible example, and was closed since long... If so, then it would mean that other Address Types may be affected as TapRoot did not exist at this time. I have not found other duplicates, but sorry if I missed one...

### Expected behaviour

Being able to spend using these Addresses without workarounds.

### Steps to reproduce

* Optional: Generate a Vanity P2TR Address with the [Achow101's Rust-Vanitygen](https://github.com/achow101/rust-vanitygen), modding it or converting the Private Key from Mainnet to Testnet if necessary. Or simply some [random WIF Private Key](https://learnmeabitcoin.com/technical/keys/private-key/wif/). Some Addresses will work, others exhibit the present issue... It seems that there is a significant proportion falling in the second case...
* For convenience, you can simply use this one made for this Bug Report:
```
internal_privkey: cNKAo2ZRsaWKcP481cEfj3astPyBrfq56JBtLeRhHUvTSuk2z4MR
internal_pubkey: ac414af4b822d67307fe81bef0a72ddf0be9e6ff129eb1270b1168126f619619
Address: tb1ptestamfzz5zguhrad6xuf7afua0csz5m6k2qclpnpkvsl20t856sxz2d89
```
* Import the Address, for example in Testnet4 via the Bitcoin-Qt Console: 
```
importdescriptors '[{"desc": "tr(cNKAo2ZRsaWKcP481cEfj3astPyBrfq56JBtLeRhHUvTSuk2z4MR)#vhsk8sfh", "timestamp":0}]'
```
* Optional: get some coins from a Testnet4 Faucet (or any other source) for this tb1ptestamfzz5zguhrad6xuf7afua0csz5m6k2qclpnpkvsl20t856sxz2d89 Address. When I submitted the Issue, there were some coins left...
* Optional: Send some amount involving this Address. Immediately after importing the Address, it appears that there is no particular issue. See Transaction [a301d660523de70542d30490052f9e04ba3f9b5e26482745c7dbdc952802f103](https://mempool.space/testnet4/tx/a301d660523de70542d30490052f9e04ba3f9b5e26482745c7dbdc952802f103).
* Restart Bitcoin Core, and try sending again some amount. The interface now shows a "Signing transaction failed" dialog followed by "Transaction creation failed!". Or, in the Console,
```
sendtoaddress tb1qn9rvr53m7qvrpysx48svuxsgahs88xfsskx367 0.0001
Signing transaction failed (code -6)
```
* However, if a new Wallet is created, and the Descriptor is imported again as above, sending coins is possible again (until Bitcoin Core is restarted again). The process can be repeated to further reuse the Address (which is obviously not practical).

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

master@228aba2c4d9ac0b2ca3edd3c2cdf0a92e55f669b

### Operating system and version

Debian 13 Testing

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by achow101**
When a `ConstPubkeyProvider` is xonly, the stored pubkey does not necessarily have the correct parity bit. `ToPrivateString()` is correctly handling this by looking up the keys for both parity bits, but `GetPrivKey` does not. This results in not finding the private key when it is actually available if its pubkey has the other parity bit value.

To fix this, this key finding is refactored into `GetPrivKey()` so that its behavior is corrected, and `ToPrivateString()` is changed to use `GetPrivKey()` as well.

Additionally, the descriptor test checks are updated to include a check for `ExpandPrivate()` to verify that both the parsed public and private descriptors produce `SigningProvider`s with the same contents.

Fixes #31589

### CODE REVIEW

**Comment by jonatack** [comment]
Concept ACK

File: src/script/descriptor.cpp [hunk 1]
```diff
@@ -321,18 +334,8 @@ class ConstPubkeyProvider final : public PubkeyProvider
             arg.GetKey(m_pubkey.GetID(), key);
         }
         if (!key.IsValid()) return false;
-        ret = EncodeSecret(key);
         return true;
```
Comment (furszy) [inline src/script/descriptor.cpp:337]: nit: 
```c++
return key.IsValid();
```

File: src/script/descriptor.cpp [hunk 2]
```diff
@@ -312,6 +312,19 @@ class ConstPubkeyProvider final : public PubkeyProvider
     bool ToPrivateString(const SigningProvider& arg, std::string& ret) const override
     {
         CKey key;
+        if (GetPrivKey(/*pos=*/0, arg, key)) {
+            ret = EncodeSecret(key);
+            return true;
+        }
+        return false;
```
Comment (furszy) [inline src/script/descriptor.cpp:319]: nano nit:
``` c++
CKey key;
if (!GetPrivKey(/*pos=*/0, arg, key)) return false;
ret = EncodeSecret(key);
return true;
```

**Review by furszy — COMMENTED** [review]
looking good, only left few nits. No need to tackle them. Will test it properly in the coming days.

**Review by theStack — APPROVED** [review]
Concept and code-review ACK 116ed1d543641006f74bf089c23714259b6d4904

commit message / PR description micro-nit: haven't seen the term "evenness" before in this context, I think we usually call it "parity bit" (as in [BIP-341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#cite_note-10))

**Review by furszy — COMMENTED** [review]
q: why not store the id belonging to the pubkey with the correct parity bit inside the `SigningProvider` arg at the point where such a structure is loaded? (which most likely happens inside `ParsePubkeyInner()`).

**Comment by achow101** [comment]
> q: why not store the id belonging to the pubkey with the correct parity bit inside the `SigningProvider` arg at the point where such a structure is loaded? (which most likely happens inside `ParsePubkeyInner()`).

The pubkey in the descriptor has no parity bit information at all, and parsing is context independent.

File: src/script/descriptor.cpp (hunk 1 above)
Comment (achow101) [reply src/script/descriptor.cpp]: Done

File: src/script/descriptor.cpp (hunk 2 above)
Comment (achow101) [reply src/script/descriptor.cpp]: Done

File: src/script/descriptor.cpp [hunk 3]
```diff
@@ -312,6 +312,19 @@ class ConstPubkeyProvider final : public PubkeyProvider
...
+    }
+    bool ToNormalizedString(const SigningProvider& arg, std::string& ret, const DescriptorCache* cache) const override
+    {
+        ret = ToString(StringType::PUBLIC);
+        return true;
+    }
+    bool GetPrivKey(int pos, const SigningProvider& arg, CKey& key) const override
+    {
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/script/descriptor.cpp]: Done

**Comment by achow101** [comment]
> commit message / PR description micro-nit: haven't seen the term "evenness" before in this context, I think we usually call it "parity bit" (as in [BIP-341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#cite_note-10))

Fixed those.

**Comment by Pttn** [comment]
ACK c0045e6cee06bc0029fb79b5a531aa1f2b817424
Solves the issue, looks good to me, thank you for working on this!

File: src/test/descriptor_tests.cpp [hunk 4]
```diff
@@ -62,6 +62,15 @@ bool EqualDescriptor(std::string a, std::string b)
...
 }
 
+bool EqualSigningProviders(const FlatSigningProvider& a, const FlatSigningProvider& b)
+{
+    return a.scripts == b.scripts
+        && a.pubkeys == b.pubkeys
+        && a.origins == b.origins
+        && a.keys == b.keys
+        && a.tr_trees == b.tr_trees;
+}
```
Comment (davidgumberg) [inline src/test/descriptor_tests.cpp:72]: nit: The equality operator could be explicitly defaulted for `SigningProvider`:

```diff
diff --git a/src/script/signingprovider.h b/src/script/signingprovider.h
index 5b1da681f8..8262db0b52 100644
--- a/src/script/signingprovider.h
+++ b/src/script/signingprovider.h
@@ -153,6 +153,7 @@ class SigningProvider
 {
 public:
     virtual ~SigningProvider() = default;
+    virtual bool operator==(const SigningProvider&) const = default;
```

**Review by furszy — COMMENTED** [review]
ACK c0045e6cee06bc0029fb79b5a531aa1f2b817424

**Comment by davidgumberg** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/31590/commits/c0045e6cee06bc0029fb79b5a531aa1f2b817424

I think this fixes #31589, and fixes a bug in miniscript parsing of xonly pubkeys. [^1]

[^1]: I think there might still be an issue with `ConstPubkeyProvider::GetSize()`, I'll try to look into this and open a follow-up if necessary.

**Review by theStack — APPROVED** [review]
re-ACK c0045e6cee06bc0029fb79b5a531aa1f2b817424

File: src/script/descriptor.cpp [hunk 5]
```diff
@@ -331,7 +323,8 @@ class ConstPubkeyProvider final : public PubkeyProvider
     }
     bool GetPrivKey(int pos, const SigningProvider& arg, CKey& key) const override
```
Comment (rkrux) [inline src/script/descriptor.cpp:324]: Why does `GetPrivKey` of `ConstPubkeyProvider` not end up using the `pos` argument? Is it because it's supposed to be a "constant" provider?

**Review by rkrux — COMMENTED** [review]
Concept ACK c0045e6cee06bc0029fb79b5a531aa1f2b817424

build and unit tests successful.

nit in pr title: 

```diff
- "descriptors: Try pubkeys of both evenness when retrieving the private keys for an xonly pubkey in a descriptor"
+ "descriptors: Try pubkeys of both parities when retrieving the private keys for an xonly pubkey in a descriptor"
```

**Comment by kevkevinpal** [comment]
Concept and Code review ACK [c0045e6](https://github.com/bitcoin/bitcoin/pull/31590/commits/c0045e6cee06bc0029fb79b5a531aa1f2b817424)

fixes issue and looks good to me!

File: src/script/descriptor.cpp (hunk 5 above)
Comment (achow101) [reply src/script/descriptor.cpp:324]: `pos` is really only used by `BIP32PubkeyProvider` to indicate child derivation index. Since no other `PubkeyProvider` can do derivation, it is ignored for all of them.
