### PR TITLE
rpc: Make unloadwallet wait for complete wallet unload

### LINKED ISSUE #14917: wallet_multiwallet --usecli fails with "Duplicate -wallet filename specified"
On master, reported on IRC, appveyor and travis (macos):

Example backtrace:

```
wallet_multiwallet.py --usecli failed, Duration: 56 s
stdout:
2018-12-10T19:52:57.293000Z TestFramework (INFO): Initializing test directory C:\Users\appveyor\AppData\Local\Temp\1\test_runner_20181210_194416\wallet_multiwallet_70
2018-12-10T19:53:18.569000Z TestFramework (INFO): Do not allow -zapwallettxes with multiwallet
2018-12-10T19:53:19.332000Z TestFramework (INFO): Do not allow -salvagewallet with multiwallet
2018-12-10T19:53:19.839000Z TestFramework (INFO): Do not allow -upgradewallet with multiwallet
2018-12-10T19:53:32.857000Z TestFramework (INFO): Check for per-wallet settxfee call
2018-12-10T19:53:33.296000Z TestFramework (INFO): Test dynamic wallet loading
2018-12-10T19:53:36.907000Z TestFramework (INFO): Load first wallet
2018-12-10T19:53:37.476000Z TestFramework (INFO): Load second wallet
2018-12-10T19:53:38.049000Z TestFramework (INFO): Load remaining wallets
2018-12-10T19:53:41.485000Z TestFramework (INFO): Test dynamic wallet creation.
2018-12-10T19:53:43.012000Z TestFramework (INFO): Test dynamic wallet unloading
2018-12-10T19:53:47.773000Z TestFramework (INFO): Test wallet backup
2018-12-10T19:53:52.517000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "C:\projects\bitcoin\test\functional\test_framework\test_framework.py", line 173, in main
    self.run_test()
  File "C:\projects\bitcoin/test/functional/wallet_multiwallet.py", line 315, in run_test
    self.nodes[0].loadwallet(wallet_name)
  File "C:\projects\bitcoin\test\functional\test_framework\test_node.py", line 400, in __call__
    return self.cli.send_cli(self.command, *args, **kwargs)
  File "C:\projects\bitcoin\test\functional\test_framework\test_node.py", line 453, in send_cli
    raise JSONRPCException(dict(code=int(code), message=message))
test_framework.authproxy.JSONRPCException: Wallet file verification failed: Error loading wallet w2. Duplicate -wallet filename specified. (-4)

### PR DESCRIPTION
**Pull request by promag**
Currently the `unloadwallet` RPC is asynchronous, it only signals the intent to unload the wallet and then returns the response to the client. The actual unload can happen later and the client has no way to be notified of that.

This PR makes the `unloadwallet` RPC synchronous, meaning that it blocks until the wallet is fully unloaded.

Replaces #14919, fixes #14917.

### CODE REVIEW

**Comment by promag** [comment]
@ryanofsky @MarcoFalke

**Comment by laanwj** [comment]
Concept ACK - I think this can be useful outside of the tests, as well.

> Also I'd like to discuss the wait default value, currently it avoid changing behavior. If wait=true is considered the correct behavior then this could be backport to 0.17.2?

Strictly spoken this is a feature, not a bugfix, though if it's optional and improves testing I think a point can be made to backport it anyhow.

**Comment by ryanofsky** [comment]
Code change looks ok, but this shouldn't be an option. Making `wait=false` the default makes `unloadwallet` pointlessly difficult to use, and inconsistent with other methods, including closely related methods like `createwallet` and `loadwallet`.

If you think there is reason to support `wait=false`, I think you need to say what the use-case is, and why it wouldn't be better served by having the client make a fully asynchronous JSON-RPC request, instead of using this half-asynchronous/half-synchronous `wait` option that doesn't (I guess?) block on acquiring `cs_wallet`, but does block on the network connection and on acquiring `cs_wallets`, and on whatever the UI currently does in `NotifyUnload` (or will do in the future).

Also, if you want to keep the `async=false` option, it would be good to have a test to ensure that it doesn't acquire `cs_wallet` and `cs_main`. This would be easy to write as a c++ unit test which acquires the locks in one thread and calls `unloadwallet` in another.

**Comment by promag** [comment]
Changed to synchronous unload. Added some sleeps to see if there were connection timeout, but didn't manage to cause one.

> doesn't (I guess?) block on acquiring `cs_wallet`

no it doesn't, it waits until the weak pointer is expired. An alternative is to keep the shared pointer to force the unload in the RPC thread.

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -81,13 +81,33 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
     return nullptr;
 }
 
+static std::mutex g_wallet_release_mutex;
+static std::condition_variable g_wallet_release_cond;
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: It seems more common in bitcoin code to abbreviate condition variables as `cv` instead of `cond` and name locks `lock` instead of `lk`.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -81,13 +81,33 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
+    {
+        std::unique_lock<std::mutex> lk(g_wallet_release_mutex);
+
+        wallet->WalletLogPrintf("Releasing wallet\n");
+        wallet->BlockUntilSyncedToCurrentChain();
+        wallet->Flush();
+        delete wallet;
+    }
+
+    g_wallet_release_cond.notify_all();
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: I think we need to confirm that `!weak_wallet.expired()` in the other thread is true at the point of this call (and guaranteed by the c++ standard to be true). Otherwise there could be a lost-wakeup bug here because this would be signalling the condition variable before the condition is true.

Comment (promag) [reply src/wallet/wallet.cpp]: Good catch, I'll investigate.

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -81,13 +81,33 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
+static std::mutex g_wallet_release_mutex;
+static std::condition_variable g_wallet_release_cond;
+
+void WaitForWalletRelease(std::shared_ptr<CWallet>& wallet)
+{
+    std::weak_ptr<CWallet> weak_wallet(wallet);
+    wallet.reset();
+
+    std::unique_lock<std::mutex> lk(g_wallet_release_mutex);
+    while (!weak_wallet.expired()) {
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: It looks like this might not be sufficient if we want to guarantee that the wallet is really destroyed. From https://en.cppreference.com/w/cpp/memory/weak_ptr/expired:

> The destructor for the managed object may not yet have been called, but this object's destruction is imminent (or may have already happened).

A more reliable but cumbersome approach might be to add wallet members:

```c++
std::promise<void> m_unload_promise;
std:shared_future<void> m_unload_future = m_unload_promise.get_future();
```

and call `m_unloaded_promise.set_value()` in the destructor, and then `future.wait()` here.

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -81,13 +81,46 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
+    wallet.reset();
+    {
+        std::unique_lock<std::mutex> lock(g_wallet_release_mutex);
+        while (g_unloading_wallet_set.count(pwallet)) {
+            g_wallet_release_cv.wait(lock);
+        }
+    }
+    // Now it's safe to close and delete the wallet.
+    pwallet->WalletLogPrintf("Releasing wallet\n");
+    pwallet->BlockUntilSyncedToCurrentChain();
```
Comment (promag) [inline src/wallet/wallet.cpp]: Not sure about this, I think it should be called before `UnregisterValidationInterface` otherwise `SyncWithValidationInterfaceQueue` does nothing than waiting..

File: src/wallet/wallet.cpp (hunk 2 above)
Comment (promag) [reply src/wallet/wallet.cpp]: This no longer applies, @ryanofsky concern was valid.

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -82,13 +82,46 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
 static void ReleaseWallet(CWallet* wallet)
 {
-    wallet->WalletLogPrintf("Releasing wallet\n");
-    wallet->BlockUntilSyncedToCurrentChain();
-    wallet->Flush();
-    delete wallet;
+    {
+        std::unique_lock<std::mutex> lock(g_wallet_release_mutex);
+        // Assert that there was an explict UnloadWallet call.
+        assert(g_unloading_wallet_set.erase(wallet) == 1);
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: Would suggest:

```c++
size_t erased = g_unloading_wallet_set.erase(wallet) == 1
assert(erased == 1);
```

Even though we don't support building bitcoin with NDEBUG, I think most people just expect asserts to contain error checking, not code that is important to run.

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (ryanofsky) [reply src/wallet/wallet.cpp]: This does seem unnecessary. But I'd also expect this code to calling UnregisterValidationInterface before flushing. I.e. stop requesting new notifications, then save state, instead of saving state first and then hoping new notifications don't arrive after the flush...

**Review by ryanofsky — COMMENTED** [review]
This change seems like it should work, but multiwallet test is failing. There's some problem with combine_logs on travis, but locally I see:

```
AssertionError: [node 0] Expected message "BerkeleyBatch: Can't open database w8_copy \(duplicates fileid \w+ from w8\)" does not partially match stderr:
"bitcoind: wallet/wallet.cpp:95: void ReleaseWallet(CWallet*): Assertion `g_unloading_wallet_set.erase(wallet) == 1' failed."
```

**Comment by promag** [comment]
@ryanofsky looks you started reviewing before my latest push?

File: src/wallet/wallet.cpp [hunk 6]
```diff
@@ -82,15 +82,59 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
+// Custom deleter for shared_ptr<CWallet>.
+static void ReleaseWallet(CWallet* wallet)
+{
+    bool unloading{false};
+    {
+        LOCK(g_wallet_release_mutex);
+        unloading = g_unloading_wallet_set.erase(wallet) == 1;
+    }
+    if (unloading) {
+        // Delegate wallet deletion for UnloadWallet caller.
```
Comment (promag) [inline src/wallet/wallet.cpp]: `Delegate wallet deletion to UnloadWallet caller`

File: src/wallet/wallet.cpp [hunk 7]
```diff
@@ -82,15 +82,59 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
+        g_wallet_release_cv.notify_all();
+    } else {
+        // Delegate wallet deletion for UnloadWallet caller.
```
Comment (promag) [inline src/wallet/wallet.cpp]: Could say it's not necessary to call `NotifyUnload` because at this point there are no shared pointers to this wallet.

**Review by promag — COMMENTED** [review]
Self review, 2 comments must be fixed.

**Comment by promag** [comment]
@ryanofsky would appreciate another review! 😄ty

**Comment by gmaxwell** [comment]
Concept ACK.

File: src/wallet/wallet.cpp [hunk 8]
```diff
@@ -82,15 +82,63 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
     wallet->BlockUntilSyncedToCurrentChain();
     wallet->Flush();
+    UnregisterValidationInterface(wallet);
     delete wallet;
 }
 
+// Custom deleter for shared_ptr<CWallet>.
+static void ReleaseWallet(CWallet* wallet)
+{
+    bool unloading{false};
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: Is there a reason this needs to delegate deletion? It seems if you removed the DeleteWallet call from UnloadWallet, you could simplify this function to just:

```c++
DeleteWallet(wallet);
LOCK(g_wallet_release_mutex);
g_unloading_wallet_set.erase(wallet);
g_wallet_release_cv.notify_all();
```

File: src/wallet/wallet.h [hunk 9]
```diff
@@ -54,6 +54,10 @@ void StopWallets();
 //! Close all wallets.
 void UnloadWallets();
 
+//! Unloads and deletes the wallet.
+//  Blocks current thread until the wallet is deleted.
+void UnloadWallet(std::shared_ptr<CWallet>&& wallet);
```
Comment (ryanofsky) [inline src/wallet/wallet.h]: Comment could say that it's not necessary to call this function unless you need to block waiting the unload.

File: src/wallet/wallet.cpp [hunk 10]
```diff
@@ -82,15 +82,63 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
+    // Mark wallet for unloading.
+    CWallet* pwallet = wallet.get();
+    {
+        LOCK(g_wallet_release_mutex);
+        assert(g_unloading_wallet_set.insert(pwallet).second);
+    }
+    // The wallet can be in use so it's not possible to explicitly unload here.
+    // Notify the unload intent so that all remaining shared pointers are
+    // released.
+    pwallet->NotifyUnload();
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: Could we `assert(NotifyUnload.empty())` in the wallet destructor to verify delete isn't happening too early and clients are fully detached?

**Review by ryanofsky — APPROVED** [review]
utACK 7aed2bb1f06ec505507d28f623b4973ae314c3f. This seems right but I suggested a simplification. It would also be good to update the description and add a release note.

File: src/wallet/wallet.cpp (hunk 8 above)
Comment (promag) [reply src/wallet/wallet.cpp]: No strong reason, just thought the unload burden/time should be left to the `unloadwallet` caller. The way you suggest both the `unloadwallet` caller and the last wallet client wait for the complete unload.

File: src/wallet/wallet.cpp (hunk 10 above)
Comment (promag) [reply src/wallet/wallet.cpp]: Will try.

File: src/wallet/wallet.h (hunk 9 above)
Comment (promag) [reply src/wallet/wallet.h]: Will improve comment.

File: src/wallet/wallet.cpp (hunk 8 above)
Comment (ryanofsky) [reply src/wallet/wallet.cpp]: > just thought the unload burden/time should be left to the unloadwallet caller. 

Interesting. That seems like a legitimate optimization for the last RPC using the wallet. Personally, I think I'd still choose the simplification over the optimization, but if you want to keep the optimization it'd be good to have a comment saying why it's better to delete on the unload thread than the release thread.

**Comment by promag** [comment]
Updated after @ryanofsky review, added release notes and updated description.

**Comment by gmaxwell** [comment]
Concept ACK.

**Review by ryanofsky — APPROVED** [review]
utACK c2ae9d9c295ca75f6653892b5f5e1ad6f5c1a9e7. Changes since last review were adding documentation and assert. Also fixing unrelated (I think) encrypted_batch potential memory leak in CWallet destructor.

**Comment by laanwj** [comment]
utACK c2ae9d9c295ca75f6653892b5f5e1ad6f5c1a9e7

**Comment by jnewbery** [comment]
Lightly tested ACK, although I have a preference for @ryanofsky's proposed simplification here: https://github.com/bitcoin/bitcoin/pull/14941#discussion_r245133485

**Comment by promag** [comment]
Pushed the simplification, also split code from assertions.

File: src/wallet/wallet.cpp [hunk 11]
```diff
@@ -82,15 +82,56 @@ std::shared_ptr<CWallet> GetWallet(const std::string& name)
...
 {
     wallet->WalletLogPrintf("Releasing wallet\n");
     wallet->BlockUntilSyncedToCurrentChain();
     wallet->Flush();
+    UnregisterValidationInterface(wallet);
     delete wallet;
 }
 
+// Custom deleter for shared_ptr<CWallet>.
+// If the release is due to a UnloadWallet call then deletion is delegated to
```
Comment (jnewbery) [inline src/wallet/wallet.cpp]: This comment needs to be updated with the latest change.

Also nit: s/a UnloadWallet/an UnloadWallet/

**Review by jnewbery — COMMENTED** [review]
Looks good. Comment needs updating, and I'd squash the new commit 'fixup: Russ simplification' into 'rpc: Make unloadwallet wait for complete wallet unload'

File: src/wallet/wallet.cpp [hunk 12]
```diff
@@ -102,19 +102,11 @@ static void DeleteWallet(CWallet* wallet)
...
-    }
-    if (unloading) {
-        // Delegate wallet deletion to UnloadWallet caller, just wake it up.
-        g_wallet_release_cv.notify_all();
-    } else {
-        // UnloadWallet was not called, just delete the wallet since there's no
-        // more shared pointers to the wallet.
-        DeleteWallet(wallet);
-    }
+    DeleteWallet(wallet);
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: Would suggest inlining `DeleteWallet` here. This function is only called from this one place, and I can't think of any other place where it would be safe to call.

**Review by ryanofsky — APPROVED** [review]
utACK e6cfc2b566b5a036d884754363b95ac94808907d. Only change since last review is new commit.

File: src/wallet/wallet.cpp (hunk 12 above)
Comment (promag) [reply src/wallet/wallet.cpp]: Good point.

**Comment by promag** [comment]
Latest changes in 4a50dce.

**Comment by jnewbery** [comment]
utACK 645e905c327411555073fa7964b36f652998059f
