### PR TITLE
rpc: Add WWW-Authenticate header to 401 response

### LINKED ISSUE #7462: Java Authenticator broken for 0.12 RPC server on Linux
I'm in the process of testing 0.12 in our dev environment for one of our java-based services. This service makes RPC requests to bitcoind, but when I upgrade from 0.11 to 0.12 every request now gets a 401 "unauthorized" response.

The RPC server is clearly still functional because I can query it manually via cURL. However, breaking Java's Authenticator may be problematic - it is the recommended way to authenticate according to the wiki: https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)

One strange thing to note is that usage of Java Authenticator still works on OS X with Core 0.12. This appears to be a platform-specific issue. I'm not sure about Windows.

I was able to implement a workaround by setting the authentication in the HTTP request manually as shown in http://www.avajava.com/tutorials/lessons/how-do-i-connect-to-a-url-using-basic-authentication.html

### PR DESCRIPTION
**Pull request by laanwj**
A WWW-Authenticate header must be present in the 401 response to make clients know that they can authenticate, and how.

```
WWW-Authenticate: Basic realm="jsonrpc"
```

Should fix #7462.

### CODE REVIEW

**Comment by jlopp** [comment]
:+1: fixes Java's Authenticator as I reported in #7462

File: src/httprpc.cpp [hunk 1]
```diff
@@ -21,6 +21,9 @@
 #include <boost/algorithm/string.hpp> // boost::trim
 #include <boost/foreach.hpp> //BOOST_FOREACH
 
+/** WWW-Authenticate to present with 401 Unauthorized response */
+static const char *WWW_AUTH_HEADER_DATA = "Basic realm=\"jsonrpc\"";
```
Comment (MarcoFalke) [inline src/httprpc.cpp]: Nit:

```diff
diff --git a/src/httprpc.cpp b/src/httprpc.cpp
index 5d54d8f..a447a3e 100644
--- a/src/httprpc.cpp
+++ b/src/httprpc.cpp
@@ -25 +25 @@
-static const char *WWW_AUTH_HEADER_DATA = "Basic realm=\"jsonrpc\"";
+static const char* WWW_AUTH_HEADER_DATA = "Basic realm=\"jsonrpc\"";
@@ -157 +157 @@ static bool HTTPReq_JSONRPC(HTTPRequest* req, const std::string &)
-        req->WriteHeader("WWW-Authenticate",WWW_AUTH_HEADER_DATA);
+        req->WriteHeader("WWW-Authenticate", WWW_AUTH_HEADER_DATA);
@@ -170 +170 @@ static bool HTTPReq_JSONRPC(HTTPRequest* req, const std::string &)
-        req->WriteHeader("WWW-Authenticate",WWW_AUTH_HEADER_DATA);
+        req->WriteHeader("WWW-Authenticate", WWW_AUTH_HEADER_DATA);

**Comment by MarcoFalke** [comment]
Concept ACK  5bac0a9

**Comment by paveljanik** [comment]
ACK

**Comment by laanwj** [comment]
Cherry-picked to 0.12 as b2f2b85ad5f3456c0a14f36602122d393f01f7fe
