### PR TITLE
Wallet: Fix error handling (copy_file failure in RestoreWallet, and in general via interfaces)

### LINKED ISSUE #661: Attempt to restore a non-readable wallet.dat silently crashes the GUI client
```
2022-09-04T19:17:59Z GUI: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy file: Permission denied [/tmp/usehd0.dat] [/home/dev/.bitcoin/regtest/wallets/nonHD/wallet.dat]
Aborted
```

Two issues here:

1. Unhandled exceptions should be displayed in the GUI before quitting.
2. Failure to restore a wallet should not crash.

### PR DESCRIPTION
**Pull request by luke-jr**
Bug 1: `copy_file` can throw exceptions, but `RestoreWallet` is expected to return a nullptr with a populated `errors` parameter. This is fixed by wrapping `copy_file` and `LoadWallet` (for good measure) in a `try` block, and converting any exceptions to the intended return style.

Bug 2: `util::Result` turns what would have been a `false` unique_ptr into a `true` nullptr result, which leads to nullptr dereferences in at least the 3 cases of wallet creation/loading/restoring. This is fixed by keeping the pointer as a plain `std::unique_ptr` until actually returning it (ie, after the nullptr check).

Fixes https://github.com/bitcoin-core/gui/issues/661

### CODE REVIEW

**Review by w0xlt — APPROVED** [review]
Tested ACK https://github.com/bitcoin/bitcoin/pull/26005/commits/c1cd7b4ac60d00dec369b3fe8f883cad07fbe833.

Not sure if https://github.com/bitcoin/bitcoin/pull/26005/commits/b60a2ce138f4549e7233542e21cd96e0d8e0b5f8 ("Bugfix: Wallet: Wrap RestoreWallet content in a try block ...") is needed.
See https://github.com/bitcoin/bitcoin/pull/22541#discussion_r680143817.

**Comment by luke-jr** [comment]
>Not sure if b60a2ce ("Bugfix: Wallet: Wrap RestoreWallet content in a try block ...") is needed.
See #22541 (comment).

Without it, the GUI crashes quite uncleanly (https://github.com/bitcoin-core/gui/issues/661).

File: src/wallet/interfaces.cpp [hunk 1]
```diff
@@ -570,15 +574,23 @@ class WalletLoaderImpl : public WalletLoader
...
+            return std::move(wallet);
+        } else {
+            return util::Error{error};
+        }
     }
     util::Result<std::unique_ptr<Wallet>> restoreWallet(const fs::path& backup_file, const std::string& wallet_name, std::vector<bilingual_str>& warnings) override
     {
         DatabaseStatus status;
         bilingual_str error;
-        util::Result<std::unique_ptr<Wallet>> wallet{MakeWallet(m_context, RestoreWallet(m_context, backup_file, wallet_name, /*load_on_start=*/true, status, error, warnings))};
```
Comment (MarcoFalke) [inline src/wallet/interfaces.cpp:580]: This was likely introduced in fa475e9c7977a952617738f2ee8cf600c07d4df8, and 07df6cda1468ed45ac227ac6f0169b040e5c0bf3

**Comment by achow101** [comment]
The `try` should probably be moved up to also include the `TryCreateDirectories` as well? If I change the permissions on the entire `wallets/` directory, it still crashes.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -394,10 +394,17 @@ std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const fs::path& b
...
     auto wallet_file = wallet_path / "wallet.dat";
-    fs::copy_file(backup_file, wallet_file, fs::copy_options::none);
+    std::shared_ptr<CWallet> wallet;
 
-    auto wallet = LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings);
+    try {
+        fs::copy_file(backup_file, wallet_file, fs::copy_options::none);
 
+        wallet = LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings);
+    } catch (const std::exception& e) {
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp:403]: In commit "Bugfix: Wallet: Wrap RestoreWallet content in a try block to ensure exceptions become returned errors and incomplete wallet directory is removed" (b60a2ce138f4549e7233542e21cd96e0d8e0b5f8)

This might just be difference of opinion about defensive programming, but IMO it makes code harder to reason about and maintain if it is catching exceptions that are never expected to be thrown. I think it would be better to only catch fs::filesystem_exception not std::exception, and only catch exceptions if copy_file throws, not if LoadWallet throws. I also think an error text like "failed to copy wallet" is better than "unexpected exception." Possible suggestion:

```diff
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -394,17 +394,16 @@ std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const fs::path& b
     }
 
     auto wallet_file = wallet_path / "wallet.dat";
-    std::shared_ptr<CWallet> wallet;
-
+    status = DatabaseStatus::SUCCESS;
     try {
         fs::copy_file(backup_file, wallet_file, fs::copy_options::none);
-
-        wallet = LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings);
-    } catch (const std::exception& e) {
-        wallet.reset();  // just in case
-        if (!error.empty()) error += Untranslated("\n");
-        error += strprintf(Untranslated("Unexpected exception: %s"), e.what());
+    } catch (const fs::filesystem_error& e) {
+        error += Untranslated(strprintf(("Failed to copy wallet: %s"), e.what()));
+        status = DatabaseStatus::FAILED_CREATE;
     }
+
+    auto wallet = status == DatabaseStatus::SUCCESS ? LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings) : nullptr;
+
     if (!wallet) {
         fs::remove(wallet_file);
         fs::remove(wallet_path);
```

**Review by ryanofsky — APPROVED** [review]
Code review ACK c1cd7b4ac60d00dec369b3fe8f883cad07fbe833

File: src/wallet/wallet.cpp (hunk 2 above)
Comment (luke-jr) [reply src/wallet/wallet.cpp:403]: The GUI cannot handle _any_ exception here, so either we catch everything, or we have to modify the GUI to check for other exceptions and "crash" cleanly... IMO it's strictly better to fail to load the wallet, than to kill the program (cleanly or not).

**Comment by luke-jr** [comment]
> The try should probably be moved up to also include the TryCreateDirectories as well? If I change the permissions on the entire wallets/ directory, it still crashes.

Done

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -379,25 +379,31 @@ std::shared_ptr<CWallet> RestoreWallet(WalletContext& context, const fs::path& b
...
+            status = DatabaseStatus::FAILED_ALREADY_EXISTS;
+            return nullptr;
+        }
 
-    auto wallet = LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings);
+        fs::copy_file(backup_file, wallet_file, fs::copy_options::none);
 
+        wallet = LoadWallet(context, wallet_name, load_on_start, options, status, error, warnings);
+    } catch (const std::exception& e) {
+        wallet.reset();  // just in case
```
Comment (furszy) [inline src/wallet/wallet.cpp:403]: would remove this as it cannot realistically happen

**Review by furszy — APPROVED** [review]
Code review ACK b298beed

File: src/wallet/wallet.cpp (hunk 2 above)
Comment (achow101) [reply src/wallet/wallet.cpp:402]: I agree with @ryanofsky. `LoadWallet` shouldn't throw any exceptions, and having it in this try-catch makes it seem like it could. The places within `LoadWallet` which are expected to throw already have their own try-catch blocks so that it returns an error rather than throwing an exception.

Comment (luke-jr) [reply src/wallet/wallet.cpp:402]: The whole point is to catch *unexpected* exceptions...

Comment (furszy) [reply src/wallet/wallet.cpp:402]: I do agree with ryanofsky and achow101 here. I don't think that we want to add try/catch everywhere around the sources if the functions aren't meant to throw exceptions (if they throw, then we have a bug in our sources that has to be solved).

I think that a better design would be to create a general safe connection function for `QTimer::singleShot` calls.
Just made a quick draft of it in https://github.com/bitcoin-core/gui/pull/666.

Comment (achow101) [reply src/wallet/wallet.cpp:402]: > The whole point is to catch _unexpected_ exceptions...

I think then it would be better to implement some overarching exception handling in the GUI rather than handling them individually like this.

Comment (luke-jr) [reply src/wallet/wallet.cpp:402]: Anything higher level wouldn't know to just abort loading the wallet rather than kill the entire program.

Comment (achow101) [reply src/wallet/wallet.cpp:402]: RPC seems to be able to handle unexpected exceptions fine?

**Comment by achow101** [comment]
ACK b298beed38fba06d354e44778e6ecb3526feec1d

File: src/wallet/interfaces.cpp [hunk 4]
```diff
@@ -560,8 +560,12 @@ class WalletLoaderImpl : public WalletLoader
         options.create_flags = wallet_creation_flags;
         options.create_passphrase = passphrase;
         bilingual_str error;
-        util::Result<std::unique_ptr<Wallet>> wallet{MakeWallet(m_context, CreateWallet(m_context, name, /*load_on_start=*/true, options, status, error, warnings))};
-        return wallet ? std::move(wallet) : util::Error{error};
+        std::unique_ptr<Wallet> wallet{MakeWallet(m_context, CreateWallet(m_context, name, /*load_on_start=*/true, options, status, error, warnings))};
+        if (wallet) {
+            return std::move(wallet);
```
Comment (achow101) [inline src/wallet/interfaces.cpp:565]:
```
wallet/interfaces.cpp: In member function ‘virtual util::Result<std::unique_ptr<interfaces::Wallet> > wallet::{anonymous}::WalletLoaderImpl::createWallet(const std::string&, const SecureString&, uint64_t, std::vector<bilingual_str>&)’:
wallet/interfaces.cpp:565:29: warning: redundant move in return statement [-Wredundant-move]
  565 |             return std::move(wallet);
      |                    ~~~~~~~~~^~~~~~~~
```

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (luke-jr) [reply src/wallet/wallet.cpp]: At least not with the current C++17 standard. Replaced it with an assert.

File: src/wallet/interfaces.cpp (hunk 4 above)
Comment (luke-jr) [reply src/wallet/interfaces.cpp]: Removed redundant move.

File: src/wallet/wallet.cpp (hunk 2 above)
Comment (luke-jr) [reply src/wallet/wallet.cpp:402]: Changing how the GUI handles unexpected exceptions in general is outside the scope of this PR.

File: src/wallet/interfaces.cpp [hunk 5]
```diff
@@ -560,8 +560,12 @@ class WalletLoaderImpl : public WalletLoader
         options.create_flags = wallet_creation_flags;
         options.create_passphrase = passphrase;
         bilingual_str error;
-        util::Result<std::unique_ptr<Wallet>> wallet{MakeWallet(m_context, CreateWallet(m_context, name, /*load_on_start=*/true, options, status, error, warnings))};
-        return wallet ? std::move(wallet) : util::Error{error};
+        std::unique_ptr<Wallet> wallet{MakeWallet(m_context, CreateWallet(m_context, name, /*load_on_start=*/true, options, status, error, warnings))};
+        if (wallet) {
+            return wallet;
```
Comment (achow101) [inline src/wallet/interfaces.cpp:565]: ... CI doesn't like this either.

```
wallet/interfaces.cpp:565:20: error: call to implicitly-deleted copy constructor of 'std::unique_ptr<interfaces::Wallet>'
            return wallet;
                   ^~~~~~
/tmp/cirrus-ci-build/ci/scratch/msan/build/include/c++/v1/memory:1553:3: note: copy constructor is implicitly deleted because 'unique_ptr<interfaces::Wallet>' has a user-declared move constructor
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
./util/result.h:44:14: note: passing argument to parameter 'obj' here
    Result(T obj) : m_variant{std::in_place_index_t<1>{}, std::move(obj)} {}
             ^
```

I think this will work:

```suggestion
            return {std::move(wallet)};
```

Comment (luke-jr) [reply src/wallet/interfaces.cpp:565]: 🤨

**Comment by achow101** [comment]
ACK c3e536555aa3a7db773170671da1256a2ace2094
