### PR TITLE
Prevent mutex lock fail even if --enable-debug

### LINKED ISSUE #15227: bitcoind terminated with uncaught exception if configure --debug-enabled
After #14955 was merged, bitcoind terminate with uncaught exception if build with **```configure --debug-enabled```** on my mac. 

Actual output is following:
```
$ ./src/bitcoind
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Abort trap: 6
```
Backtrace is following:
```
$ lldb ./src/bitcoind
(lldb) target create "./src/bitcoind"
Current executable set to './src/bitcoind' (x86_64).
(lldb) run
Process 73375 launched: './src/bitcoind' (x86_64)
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Process 73375 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff6588423e libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff6588423e <+10>: jae    0x7fff65884248            ; <+20>
    0x7fff65884240 <+12>: movq   %rax, %rdi
    0x7fff65884243 <+15>: jmp    0x7fff6587e3b7            ; cerror_nocancel
    0x7fff65884248 <+20>: retq   
Target 0: (bitcoind) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff6588423e libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff6593ac1c libsystem_pthread.dylib`pthread_kill + 285
    frame #2: 0x00007fff657ed1c9 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff62e6e231 libc++abi.dylib`abort_message + 231
    frame #4: 0x00007fff62e6e3b5 libc++abi.dylib`default_terminate_handler() + 241
    frame #5: 0x00007fff64678c8f libobjc.A.dylib`_objc_terminate() + 105
    frame #6: 0x00007fff62e79dfe libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #7: 0x00007fff62e79e73 libc++abi.dylib`std::terminate() + 51
    frame #8: 0x0000000100003efb bitcoind`__clang_call_terminate + 11
    frame #9: 0x0000000100344803 bitcoind`(anonymous namespace)::RNGState::MixExtract(this=<unavailable>, out="", num=32, hasher=0x00007ffeefbfe3f8, strong_seed=<unavailable>) at random.cpp:355 [opt]
    frame #10: 0x0000000100343fbd bitcoind`ProcRand(out="", num=32, level=FAST) at random.cpp:497 [opt]
    frame #11: 0x0000000100343efd bitcoind`GetRandBytes(buf=<unavailable>, num=<unavailable>) at random.cpp:513 [opt]
    frame #12: 0x000000010015a38b bitcoind`::__cxx_global_var_init.3() at sigcache.cpp:68 [opt]
    frame #13: 0x0000000100d8dcc8 dyld`ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 518
    frame #14: 0x0000000100d8dec6 dyld`ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
    frame #15: 0x0000000100d890da dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 358
    frame #16: 0x0000000100d88254 dyld`ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 134
    frame #17: 0x0000000100d882e8 dyld`ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 74
    frame #18: 0x0000000100d77774 dyld`dyld::initializeMainExecutable() + 199
    frame #19: 0x0000000100d7c78f dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6237
    frame #20: 0x0000000100d764f6 dyld`dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 1154
    frame #21: 0x0000000100d76036 dyld`_dyld_start + 54
(lldb) quit
```

[how to reproduce the issue]
```
cd (path_to bitcoin_repo)
git reset --hard 6e6b3b944d12a252a0fd9a1d68fec9843dd5b4f8
make clean ; make distclean ; ./autogen.sh && ./configure --enable-debug && make -j9
./src/bitcoind
```
[Bitcoin Core version]
 - commit 6e6b3b944d12a252a0fd9a1d68fec9843dd5b4f8

[machine]
 - MacBook Pro
   (macOS Mojave 10.14.2/Intel Core i7 2.2GHz/memory 16GB/SSD 256GB)

[extra information]
- bitcoin-qt, test_bitcoin and bench_bitcoin have also same problem. 
- There is no problem until #14970 (commit ace87ea2b00a84b7a76e75f1ec93d1a4dce83f6f) was merged.

### PR DESCRIPTION
**Pull request by AkioNak**
This PR intends to resolve #15227.

```configure --enable-debug```  enables ```#ifdef DEBUG_LOCKORDER```.

Then ```lockdata``` (in sync.cpp) will be initialized same as other static objects.

But unfortunately, ```lockdata.push_lock()``` was called before its initialization (via initializing ```signatureCache``` which is declared in ```script/sigcache.cpp```) on macOS.

This PR apply the "Construct On First Use Idiom" to ```lockdata``` to prevent it.

edited --- fix typo.

### CODE REVIEW

File: src/sync.cpp [hunk 1]
```diff
@@ -73,7 +73,11 @@ struct LockData {
     LockOrders lockorders;
     InvLockOrders invlockorders;
     std::mutex dd_mutex;
-} static lockdata;
+};
+LockData& get_lockdata() {
```
Comment (sipa) [inline src/sync.cpp]: Nit: function naming style (`GetLockData` ?).

File: src/sync.cpp [hunk 2]
```diff
@@ -73,7 +73,11 @@ struct LockData {
...
+    static LockData* lockdata = new LockData();
```
Comment (sipa) [inline src/sync.cpp]: Can you use a `std::unique_ptr<LockData>` here instead? This code will technically cause a memory leak (as the `LockData` won't get cleaned up at shutdown).

**Review by sipa — COMMENTED** [review]
Concept ACK

File: src/sync.cpp (hunk 2 above)
Comment (kallewoof) [reply src/sync.cpp]: Hm? Why would it cause a leak? All memory used by a process is always released upon shutdown.

**Comment by kallewoof** [comment]
Tested ACK

Master branch `make check` results in failures (see below); with this PR, `make check` exits successfully.
```
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
../build-aux/test-driver: line 107: 29548 Abort trap: 6           "$@" > $log_file 2>&1
```

File: src/sync.cpp (hunk 2 above)
Comment (sipa) [reply src/sync.cpp]: @kallewoof Yes, that's why I say technically. We generally ain to follow that rule though, as it means leak detection systems like valgrind don't report spurious leaks.

Comment (kallewoof) [reply src/sync.cpp]: I thought valgrind was intelligent about static vars inside functions, and always considered this type of expression to be acceptable. I guess a unique pointer is less dirty though, so concept ACK on the change.

Comment (sipa) [reply src/sync.cpp]: @kallewoof Good point, I hadn't considered that actually. Some googling indicates that in cases like this, the memory would indeed be counted as still reachable rather than lost.

Still, using a unique_ptr here comes at no cost, and is more obviously correct.

Comment (practicalswift) [reply src/sync.cpp]: The consensus must be that we should aim for zero bytes "still reachable" when exiting, right? :-)

Comment (promag) [reply src/sync.cpp]: Is this thread safe?

Comment (sipa) [reply src/sync.cpp]: Yes, since C++11 the language guarantees that the static initializer is only run once. If it is invoked from multiple threads simultaneously, only the first will complete, and the others will wait for the first to run and use the same result.

**Comment by Sjors** [comment]
Tested 6a5e3c2 on macOS without GUI, as follows:

Toggling `--enable-debug` produced some compiler headaches for me, so I cleaned up in between.

Testing with `--enable-debug`:

```sh
# on master
make distclean
./autogen.sh
./configure --disable-bench --with-miniupnpc=no --with-incompatible-bdb --with-zmq --without-gui --enable-debug
make && make check
# test fails

# switch to this branch
make && make check
# tests pass
```

Testing without `--enable-debug`, tests pass on master and with this change.

File: src/sync.cpp (hunk 2 above)
Comment (promag) [reply src/sync.cpp]: Could just be `static LockData lockdata;` right?

**Review by promag — CHANGES_REQUESTED** [review]
Tested ACK, but I think you could make it:
```cpp
// Construct On First Use Idiom ...
LockData& GetLockData()
{
    static LockData lockdata;
    return lockdata;
}
```

**Comment by sipa** [comment]
utACK 416bf1b74aecfda51fa9d41b57e39fd0d488e742. Squash?

**Comment by kallewoof** [comment]
tACK b09dab0

(It somehow escaped me that you could just do a static instance like that without making it a pointer. Mind blown. :)

File: src/sync.cpp [hunk 3]
```diff
@@ -73,7 +73,11 @@ struct LockData {
     LockOrders lockorders;
     InvLockOrders invlockorders;
     std::mutex dd_mutex;
-} static lockdata;
+};
+LockData& GetLockData() {
```
[the remark this answers is not in the document]
Comment (AkioNak) [reply src/sync.cpp]: @promag Thanks for your reviewing.
Does this mean that the scope of ```GetLockData()``` should be compile-unit local same as original ```lockdata``` to prevent external calling?

[the remark this answers is not in the document]
Comment (promag) [reply src/sync.cpp]: Yes linkage changed, but I don't think it warrants a PR.
