### PR TITLE
wallet, rpc: explicit fee rate follow-ups/fixes for 0.21

### LINKED ISSUE #20219: RPC bumpfee error with explicit feerate
RPC bumpfee with an explicit feerate using `conf_target` and `estimate_mode` errors with `JSONRPCException: JSON integer out of range (-1)`.

### PR DESCRIPTION
**Pull request by jonatack**
Follow-up to #11413 providing a base to build on for #19543:

- bugfix for `bumpfee` raising a JSON error with explicit feerates, fixes issue #20219 
- adds explicit feerate test coverage for `bumpfee`, `fundrawtransaction`, `walletcreatefundedpsbt`, `send`, `sendtoaddress`, and `sendmany`
- improves a few related RPC error messages and `ParseConfirmTarget()` / error message
- fixes/improves the explicit fee rate information in the 6 RPC helps, of which 2 were also missing `conf_target` sat/B units

This provides a spec and regression coverage for the potential next step of a universal `sat/vB` feerate argument (see #19543), as well as immediate coverage and minimum fixes for 0.21.

### CODE REVIEW

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -3461,7 +3461,6 @@ static RPCHelpMan bumpfee_helper(std::string method_name)
             if (options.exists("fee_rate")) {
                 throw JSONRPCError(RPC_INVALID_PARAMETER, "conf_target can't be set with fee_rate. Please provide either a confirmation target in blocks for automatic fee estimation, or an explicit fee rate.");
             }
-            coin_control.m_confirm_target = ParseConfirmTarget(conf_target, pwallet->chain().estimateMaxBlocks());
```
Comment (jonatack) [inline src/wallet/rpcwallet.cpp:3464]: This action is now performed in `SetFeeEstimateMode()` and calling it in bumpfee beforehand was causing an error with explicit feerates.

File: src/wallet/rpcwallet.cpp [hunk 2]
```diff
@@ -3785,8 +3788,9 @@ RPCHelpMan getaddressinfo()
                         {RPCResult::Type::STR_HEX, "pubkey", /* optional */ true, "The hex value of the raw public key for single-key addresses (possibly embedded in P2SH or P2WSH)."},
                         {RPCResult::Type::OBJ, "embedded", /* optional */ true, "Information about the address embedded in P2SH or P2WSH, if relevant and known.",
                         {
-                            {RPCResult::Type::ELISION, "", "Includes all getaddressinfo output fields for the embedded address, excluding metadata (timestamp, hdkeypath, hdseedid)\n"
-                            "and relation to the wallet (ismine, iswatchonly)."},
+                            {RPCResult::Type::ELISION, "",
+                                    "Includes all getaddressinfo output fields for the embedded address, excluding metadata (timestamp,\n"
+                                    "hdkeypath, hdseedid) and relation to the wallet (ismine, iswatchonly)."},
```
Comment (jonatack) [inline src/wallet/rpcwallet.cpp:3793]: Fixup requested in https://github.com/bitcoin/bitcoin/pull/19200#discussion_r438781980.

**Comment by jonatack** [comment]
Pushed a few improvements. Should be ready for review.

File: test/functional/wallet_bumpfee.py [hunk 3]
```diff
@@ -100,28 +99,55 @@ def run_test(self):
...
-        })
-        assert_raises_rpc_error(-8, "Invalid estimate_mode parameter", node.bumpfee, txid, {
-            "estimate_mode": Decimal("3.141592"),
-        })
-        # confTarget and conf_target
-        assert_raises_rpc_error(-8, "confTarget and conf_target options should not both be set", node.bumpfee, txid, {
-            "confTarget": 123,
-            "conf_target": 456,
-        })
+    def test_invalid_parameters(self, rbf_node, peer_node, dest_address):
```
Comment (Xekyo) [inline test/functional/wallet_bumpfee.py:102]: This is a bit hard to review. My approach would currently be to check line by line whether all test cases are accounted for but that would probably be easier if the reordering of code and the refactoring to traverse the test cases had been separated into two commits. What would a reviewer usually be expected to do here?

Alternatively, I suspect that there might be better diff tools that can follow a change like this. :thinking:

File: src/rpc/util.cpp [hunk 4]
```diff
@@ -272,11 +272,12 @@ UniValue DescribeAddress(const CTxDestination& dest)
 
 unsigned int ParseConfirmTarget(const UniValue& value, unsigned int max_target)
 {
-    int target = value.get_int();
-    if (target < 1 || (unsigned int)target > max_target) {
-        throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("Invalid conf_target, must be between %u - %u", 1, max_target));
+    const int target{value.get_int()};
```
Comment (Xekyo) [inline src/rpc/util.cpp:275]: What is the advantage of this construction over the previous line?

File: src/rpc/util.cpp [hunk 5]
```diff
@@ -272,11 +272,12 @@ UniValue DescribeAddress(const CTxDestination& dest)
...
+    const unsigned int unsigned_target{static_cast<unsigned int>(target)};
+    if (target < 1 || unsigned_target > max_target) {
```
Comment (Xekyo) [inline src/rpc/util.cpp:277]: Would this not fail if the value of the input was between `MAX_INT` if `max_target` were between `MAX_INT` and `MAX_UNSIGNED_INT`?

Comment (Xekyo) [reply src/rpc/util.cpp:277]: I assume this is safe, because `max_target` is 1000 blocks, but I did spend a few minutes staring at this.

File: test/functional/rpc_fundrawtransaction.py [hunk 6]
```diff
@@ -672,6 +674,53 @@ def test_option_feerate(self):
...
+            # With no arguments passed, expect fee of 141 sats/b.
+            assert_approx(node.fundrawtransaction(rawtx)["fee"], vexp=0.00000141, vspan=0.00000001)
+            # Expect fee to be 10,000x higher when explicit fee 10,000x greater is specified.
+            result = node.fundrawtransaction(rawtx, {"conf_target": feerate, "estimate_mode": unit})
+            assert_approx(result["fee"], vexp=0.0141, vspan=0.0001)
+
+        for field, feerate in {"conf_target": 0.1, "estimate_mode": "sat/b"}.items():
+            self.log.info("Test fundrawtxn raises RPC error if both feeRate and {} are passed".format(field))
+            assert_raises_rpc_error(
+                -8, "Cannot specify both {} and feeRate".format(field),
```
Comment (Xekyo) [inline test/functional/rpc_fundrawtransaction.py:697]: So now we have `fee rate`, `feeRate` and `fee_rate` in one PR. The horrors. :sweat_smile:

File: test/functional/rpc_psbt.py [hunk 7]
```diff
@@ -174,8 +174,11 @@ def run_test(self):
             elif out['scriptPubKey']['addresses'][0] == p2pkh:
                 p2pkh_pos = out['n']
 
+        inputs = [{"txid": txid, "vout": p2wpkh_pos}, {"txid": txid, "vout": p2sh_p2wpkh_pos}, {"txid": txid, "vout": p2pkh_pos}]
+        addr = {self.nodes[1].getnewaddress(): 29.99}
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py:178]: Nit: since this is an address and amount, how about "receiver_output"?

File: test/functional/rpc_psbt.py [hunk 8]
```diff
@@ -186,14 +189,15 @@ def run_test(self):
         assert_equal(walletprocesspsbt_out['complete'], True)
         self.nodes[1].sendrawtransaction(self.nodes[1].finalizepsbt(walletprocesspsbt_out['psbt'])['hex'])
 
-        # feeRate of 0.1 BTC / KB produces a total fee slightly below -maxtxfee (~0.05280000):
-        res = self.nodes[1].walletcreatefundedpsbt([{"txid":txid,"vout":p2wpkh_pos},{"txid":txid,"vout":p2sh_p2wpkh_pos},{"txid":txid,"vout":p2pkh_pos}], {self.nodes[1].getnewaddress():29.99}, 0, {"feeRate": 0.1, "add_inputs": True})
+        self.log.info("Test feeRate of 0.1 BTC / KB produces a total fee slightly below -maxtxfee (~0.05280000)")
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py]: Nit: "K" is the symbol for Kelvin, it's "kB", also remove spacing like below for consistency. :nerd_face:

File: test/functional/rpc_psbt.py [hunk 9]
```diff
@@ -186,14 +189,15 @@ def run_test(self):
...
+        res = self.nodes[1].walletcreatefundedpsbt(inputs, addr, 0, {"feeRate": 0.1, "add_inputs": True})
         assert_approx(res["fee"], 0.055, 0.005)
 
-        # feeRate of 10 BTC / KB produces a total fee well above -maxtxfee
+        self.log.info("Test feeRate of 10 BTC/KB produces total fee well above -maxtxfee and raises RPC error")
         # previously this was silently capped at -maxtxfee
-        assert_raises_rpc_error(-4, "Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate)", self.nodes[1].walletcreatefundedpsbt, [{"txid":txid,"vout":p2wpkh_pos},{"txid":txid,"vout":p2sh_p2wpkh_pos},{"txid":txid,"vout":p2pkh_pos}], {self.nodes[1].getnewaddress():29.99}, 0, {"feeRate": 10, "add_inputs": True})
-        assert_raises_rpc_error(-4, "Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate)", self.nodes[1].walletcreatefundedpsbt, [{"txid":txid,"vout":p2wpkh_pos},{"txid":txid,"vout":p2sh_p2wpkh_pos},{"txid":txid,"vout":p2pkh_pos}], {self.nodes[1].getnewaddress():1}, 0, {"feeRate": 10, "add_inputs": False})
+        for bool_add, addr in {True: addr, False: {self.nodes[1].getnewaddress(): 1}}.items():
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py:234]: Still getting used to this, but totally see what you're doing now. :)

File: test/functional/rpc_psbt.py [hunk 10]
```diff
@@ -189,10 +189,46 @@ def run_test(self):
         assert_equal(walletprocesspsbt_out['complete'], True)
         self.nodes[1].sendrawtransaction(self.nodes[1].finalizepsbt(walletprocesspsbt_out['psbt'])['hex'])
 
-        self.log.info("Test feeRate of 0.1 BTC / KB produces a total fee slightly below -maxtxfee (~0.05280000)")
+        self.log.info("Test feeRate of 0.1 BTC / KB produces a total fee at or slightly below -maxtxfee (~0.05290000)")
         res = self.nodes[1].walletcreatefundedpsbt(inputs, addr, 0, {"feeRate": 0.1, "add_inputs": True})
         assert_approx(res["fee"], 0.055, 0.005)
 
+        self.log.info("Test passing walletcreatefundedpsbt explicit feerate with conf_target and estimate_mode")
+        for unit, feerate in {"btc/kb": 0.1, "sat/b": 10000}.items():
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py:197]: Probably not the right place to bring this up, but the explicit specifying of the unit does seem really error prone as mentioned in the comments of #19543 before.

File: test/functional/rpc_psbt.py [hunk 11]
```diff
@@ -189,10 +189,46 @@ def run_test(self):
...
+        for mode in ["unset", "economical", "conservative", "btc/kb", "sat/b"]:
+            self.log.debug("{}".format(mode))
+            for k, v in {"string": "", "object": {"foo": "bar"}}.items():
+                assert_raises_rpc_error(-3, "Expected type number for conf_target, got {}".format(k),
+                    lambda: self.nodes[1].walletcreatefundedpsbt(inputs, addr, 0, {"estimate_mode": mode, "conf_target": v, "add_inputs": True}))
+            if mode in ["btc/kb", "sat/b"]:
+                assert_raises_rpc_error(-3, "Amount out of range",
+                    lambda: self.nodes[1].walletcreatefundedpsbt(inputs, addr, 0, {"estimate_mode": mode, "conf_target": -1, "add_inputs": True}))
+                assert_raises_rpc_error(-4, "Fee rate (0.00000000 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
+                    lambda: self.nodes[1].walletcreatefundedpsbt(inputs, addr, 0, {"estimate_mode": mode, "conf_target": 0, "add_inputs": True}))
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py:226]: Zero often being some sort of special case, what happens with values between 0 and 0.00001000? Maybe we should also test `0.00000999`.

File: src/wallet/rpcwallet.cpp [hunk 12]
```diff
@@ -4034,7 +4034,7 @@ static RPCHelpMan send()
                     {"locktime", RPCArg::Type::NUM, /* default */ "0", "Raw locktime. Non-0 value also locktime-activates inputs"},
                     {"lock_unspents", RPCArg::Type::BOOL, /* default */ "false", "Lock selected unspent outputs"},
                     {"psbt", RPCArg::Type::BOOL,  /* default */ "automatic", "Always return a PSBT, implies add_to_wallet=false."},
-                    {"subtract_fee_from_outputs", RPCArg::Type::ARR, /* default */ "empty array", "A JSON array of integers.\n"
+                    {"subtract_fee_from_outputs", RPCArg::Type::ARR, /* default */ "empty array", "Outputs to subtract the fee from, specified as integer indices.\n"
```
Comment (Xekyo) [inline src/wallet/rpcwallet.cpp:4043]: Oh my, great improvement!

File: src/rpc/util.cpp (hunk 4 above)
Comment (jonatack) [reply src/rpc/util.cpp:275]: Little: constness, and while changing the line, updated the style. It's not essential, to be sure. Initially, the function was touched to fix the error message. Then, I saw the function has two old C-style conversions and replaced them with one preferred static cast. Then, made the non-mutated variables const.

File: test/functional/rpc_psbt.py (hunk 10 above)
Comment (jonatack) [reply test/functional/rpc_psbt.py:197]: Yes. It would be good to replace this with the fixed-unit `feerate_sat_vb` argument before the 0.21 branch-off.

File: test/functional/rpc_psbt.py (hunk 11 above)
Comment (jonatack) [reply test/functional/rpc_psbt.py:226]: Agreed--started doing just that today for the new arg [`0f2eb16` (#20231)](https://github.com/bitcoin/bitcoin/pull/20231/commits/0f2eb167ddfa7d2612708d09e05189f969699121#diff-047f185450ff2093df390b522db9b6aa1c87353abf7e7a99c00390db8c707f6eR375), will update here.

File: test/functional/wallet_bumpfee.py [hunk 13]
```diff
@@ -132,6 +134,13 @@ def test_simple_bumpfee_succeeds(self, mode, rbf_node, peer_node, dest_address):
     if mode == "fee_rate":
         bumped_psbt = rbf_node.psbtbumpfee(rbfid, {"fee_rate": NORMAL})
         bumped_tx = rbf_node.bumpfee(rbfid, {"fee_rate": NORMAL})
+    elif mode == BTC_MODE:
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py:163]: I agree, it's a redundant feature here that adds to the confusion...while using a different code path, so the test is needed.

File: test/functional/wallet_bumpfee.py (hunk 3 above)
Comment (jonatack) [reply test/functional/wallet_bumpfee.py:102]: Sorry about that. Yes, there are a few options. In this case, a helpful one might be

`git show 6fa5686 -w --color-moved=dimmed-zebra`

For other cases, maybe git show or git diff with `--word-diff`.

Or to ignore all added lines having a matching identical removed line (empty result proves move-only):

`git diff 6fa5686f~1..6fa5686f | grep -E '^[+-][^+-]' | cut -b2- | sort | uniq -c | grep -v '^ *2'`

People like practicalswift, promag, MarcoFalke, jnewbery, and harding likely know some more good ones.

File: test/functional/rpc_psbt.py (hunk 7 above)
Comment (jonatack) [reply test/functional/rpc_psbt.py:178]: Good idea. Changed it to `outputs`:
```diff
         inputs = [{"txid": txid, "vout": p2wpkh_pos}, {"txid": txid, "vout": p2sh_p2wpkh_pos}, {"txid": txid, "vout": p2pkh_pos}]
-        addr = {self.nodes[1].getnewaddress(): 29.99}
+        outputs = [{self.nodes[1].getnewaddress(): 29.99}]
```

File: test/functional/rpc_psbt.py (hunk 8 above)
Comment (jonatack) [reply test/functional/rpc_psbt.py]: Done.

File: test/functional/wallet_bumpfee.py [hunk 14]
```diff
@@ -168,24 +168,54 @@ def test_simple_bumpfee_succeeds(self, mode, rbf_node, peer_node, dest_address):
 
 
 def test_feerate_args(self, rbf_node, peer_node, dest_address):
-    self.log.info('Test fee_rate args')
+    self.log.info('Test feerate args')
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Reverted. This line goes away in the following commit.

File: test/functional/wallet_bumpfee.py [hunk 15]
```diff
@@ -168,24 +168,54 @@ def test_simple_bumpfee_succeeds(self, mode, rbf_node, peer_node, dest_address):
...
-
     assert_raises_rpc_error(-4, "is too high (cannot be higher than", rbf_node.bumpfee, rbfid, {"fee_rate": TOO_HIGH})
-    self.clear_mempool()
 
+    self.log.info("Test explicit feerate raises RPC error if estimate_mode is passed without a conf_target")
+    assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": NORMAL, "estimate_mode": BTC_MODE})
+    assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": 10, "estimate_mode": SAT_MODE})
+
+    self.log.info("Test explicit feerate raises RPC error if both fee_rate and conf_target are passed")
+    msg = "Cannot specify both conf_target and fee_rate. Please provide either a confirmation " \
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Done, changed to `error_both`.

File: test/functional/rpc_psbt.py (hunk 11 above)
Comment (jonatack) [reply test/functional/rpc_psbt.py:226]: Added
```python
for unit, feerate in {"SAT/B": 0.99999999, "BTC/KB": 0.00000999}.items():
    self.log.info("- raises RPC error 'fee rate too low' if conf_target {} and estimate_mode {} are passed".format(feerate, unit))
    assert_raises_rpc_error(-4, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
        lambda: self.nodes[1].walletcreatefundedpsbt(inputs, outputs, 0, {"estimate_mode": unit, "conf_target": feerate, "add_inputs": True}))
```

File: test/functional/wallet_bumpfee.py [hunk 16]
```diff
@@ -168,24 +168,54 @@ def test_simple_bumpfee_succeeds(self, mode, rbf_node, peer_node, dest_address):
...
+          "target in blocks for automatic fee estimation, or an explicit fee rate."
+    assert_raises_rpc_error(-8, msg, rbf_node.bumpfee, rbfid, {"conf_target": NORMAL, "fee_rate": NORMAL})
+
+    self.log.info("Test invalid conf_target settings")
+    for field in ["confTarget", "conf_target"]:
+        assert_raises_rpc_error(-8, msg, rbf_node.bumpfee, rbfid, {field: 1, "fee_rate": NORMAL})
+    too_high = "is too high (cannot be higher than -maxtxfee"
+    assert_raises_rpc_error(-4, too_high, lambda: rbf_node.bumpfee(rbfid, {"estimate_mode": BTC_MODE, "conf_target": 2009}))
+    assert_raises_rpc_error(-4, too_high, lambda: rbf_node.bumpfee(rbfid, {"estimate_mode": SAT_MODE, "conf_target": 2009 * 10000}))
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Nice find! added:
```diff
         assert_raises_rpc_error(-8, "Insufficient total fee", rbf_node.bumpfee, rbfid, {"fee_rate": INSUFFICIENT})
+        assert_raises_rpc_error(-8, "Insufficient total fee", rbf_node.bumpfee, rbfid,
+                                {"conf_target": INSUFFICIENT, "estimate_mode": BTC_MODE})
+        assert_raises_rpc_error(-8, "Insufficient total fee", rbf_node.bumpfee, rbfid,
+                                {"conf_target": 1, "estimate_mode": SAT_MODE})
```

File: test/functional/wallet_bumpfee.py [hunk 17]
```diff
@@ -168,24 +168,54 @@ def test_simple_bumpfee_succeeds(self, mode, rbf_node, peer_node, dest_address):
...
     assert_raises_rpc_error(-8, "Insufficient total fee", rbf_node.bumpfee, rbfid, {"fee_rate": INSUFFICIENT})
-
     assert_raises_rpc_error(-3, "Amount out of range", rbf_node.bumpfee, rbfid, {"fee_rate": -1})
-
     assert_raises_rpc_error(-4, "is too high (cannot be higher than", rbf_node.bumpfee, rbfid, {"fee_rate": TOO_HIGH})
-    self.clear_mempool()
 
+    self.log.info("Test explicit feerate raises RPC error if estimate_mode is passed without a conf_target")
+    assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": NORMAL, "estimate_mode": BTC_MODE})
+    assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": 10, "estimate_mode": SAT_MODE})
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Good find. Fixed the error message to now print `Selected estimate_mode <MODE> requires a fee rate specified in conf_target` and updated the tests.
```diff
+++ b/src/wallet/rpcwallet.cpp
@@ -214,7 +214,7 @@ static void SetFeeEstimateMode(const CWallet* pwallet, CCoinControl& cc, const U
 
     if (cc.m_fee_mode == FeeEstimateMode::BTC_KB || cc.m_fee_mode == FeeEstimateMode::SAT_B) {
         if (estimate_param.isNull()) {
-            throw JSONRPCError(RPC_INVALID_PARAMETER, "Selected estimate_mode requires a fee rate");
+            throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("Selected estimate_mode %s requires a fee rate specified in conf_target", estimate_mode.get_str()));
         }
```
```diff
+++ b/test/functional/wallet_bumpfee.py
-        assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": HIGH, "estimate_mode": BTC_MODE})
-        assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": 1000, "estimate_mode": SAT_MODE})
+        for unit, fee_rate in {"SAT/B": 100, "BTC/KB": NORMAL}.items():
+            assert_raises_rpc_error(-8, "Selected estimate_mode {} requires a fee rate specified in conf_target".format(unit),
+                                    rbf_node.bumpfee, rbfid, {"fee_rate": fee_rate, "estimate_mode": unit})
```

File: test/functional/wallet_bumpfee.py [hunk 18]
```diff
@@ -168,24 +168,54 @@ def test_simple_bumpfee_succeeds(self, mode, rbf_node, peer_node, dest_address):
...
     # Bumping to just above minrelay should fail to increase total fee enough, at least
     assert_raises_rpc_error(-8, "Insufficient total fee", rbf_node.bumpfee, rbfid, {"fee_rate": INSUFFICIENT})
-
     assert_raises_rpc_error(-3, "Amount out of range", rbf_node.bumpfee, rbfid, {"fee_rate": -1})
-
     assert_raises_rpc_error(-4, "is too high (cannot be higher than", rbf_node.bumpfee, rbfid, {"fee_rate": TOO_HIGH})
-    self.clear_mempool()
 
+    self.log.info("Test explicit feerate raises RPC error if estimate_mode is passed without a conf_target")
+    assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate", rbf_node.bumpfee, rbfid, {"fee_rate": NORMAL, "estimate_mode": BTC_MODE})
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Updated the log message to "fee rate".

**Comment by jonatack** [comment]
@Xekyo thanks for the excellent feedback--I have been building on it, writing more tests, finding a few more things, will push an update tomorrow.

File: test/functional/wallet_bumpfee.py (hunk 17 above)
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Done in fc572172

File: test/functional/wallet_bumpfee.py (hunk 16 above)
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_bumpfee.py]: Done in 1697a40

**Comment by jonatack** [comment]
Hopefully addressed the (excellent) review feedback and also added missing explicit fee rate coverage in `wallet_basic.py` for RPCs sendtoaddress and sendmany and in `wallet_send.py` for RPC send. Found some bugs and inconsistent behavior in RPC send, some of which I notated with `TODO` comments in the tests, but left the fixes for follow-ups as I've spent a ton of time here already going through all these RPCs and the release branch-off isn't far away.

**Comment by Xekyo** [comment]
Just seeing this now. Aiming to take a look tomorrow.

File: test/functional/wallet_basic.py [hunk 19]
```diff
@@ -252,9 +254,9 @@ def run_test(self):
         node_0_bal += Decimal('10')
         assert_equal(self.nodes[0].getbalance(), node_0_bal)
 
-        # Sendmany with explicit fee (SAT/B)
+        self.log.info("Test explicit fee (sendmany as sat/B)")
         # Throw if no conf_target provided
-        assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate",
+        assert_raises_rpc_error(-8, "Selected estimate_mode sat/b requires a fee rate to be specified in conf_target",
```
[the remark this answers is not in the document]
Comment (Xekyo) [reply test/functional/wallet_basic.py:259]: I just saw the value below in the `estimate_mode` the input in 260 is matching. I conclude that the string is case-insensitive, and the purpose was to test the insensitivity. I'd prefer an approach where a single style was used across all tests, and then one test checked the case insensitivity of the estimate_mode explicitly, but I don't think it's pertinent to make the actual change in this PR.

File: test/functional/wallet_bumpfee.py (hunk 16 above)
[the remark this answers is not in the document]
Comment (Xekyo) [reply test/functional/wallet_bumpfee.py]: Wonderful, thanks!

File: test/functional/wallet_bumpfee.py [hunk 20]
```diff
@@ -173,19 +173,50 @@ def test_feerate_args(self, rbf_node, peer_node, dest_address):
...
-    assert_raises_rpc_error(-8, "conf_target can't be set with fee_rate. Please provide either a confirmation target in blocks for automatic fee estimation, or an explicit fee rate.", rbf_node.bumpfee, rbfid, {"fee_rate": NORMAL, "confTarget": 1})
-
     assert_raises_rpc_error(-3, "Unexpected key totalFee", rbf_node.bumpfee, rbfid, {"totalFee": NORMAL})
-    assert_raises_rpc_error(-8, "conf_target can't be set with fee_rate. Please provide either a confirmation target in blocks for automatic fee estimation, or an explicit fee rate.", rbf_node.bumpfee, rbfid, {"fee_rate":0.00001, "confTarget": 1})
-
-    # Bumping to just above minrelay should fail to increase total fee enough, at least
-    assert_raises_rpc_error(-8, "Insufficient total fee", rbf_node.bumpfee, rbfid, {"fee_rate": INSUFFICIENT})
 
+    # For each fee mode, bumping to just above minrelay should fail to increase the total fee enough.
+    for options in [{"fee_rate": INSUFFICIENT}, {"conf_target": INSUFFICIENT, "estimate_mode": BTC_MODE}, {"conf_target": 1, "estimate_mode": SAT_MODE}]:
```
Comment (Xekyo) [inline test/functional/wallet_bumpfee.py]: I was originally thinking here:

> I'm confused by the ` {"conf_target": 1, "estimate_mode": SAT_MODE}`. Fitting the theme, I would expect the `conf_target` to be below `minRelayTxFeeRate`. But IIUC, 1 sat/B would be exactly the `minRelayTxFeeRate`. Is it possible that this should be … oh. … `INSUFFICIENT` also appears to be exactly the `minRelayTxFeeRate`. … Oh, this is for bumping. Duh.

Nevermind, carry on! :ok_hand: Thanks for adding this.

File: test/functional/rpc_fundrawtransaction.py [hunk 21]
```diff
@@ -672,6 +674,59 @@ def test_option_feerate(self):
...
+                assert_raises_rpc_error(-3, "Amount out of range",
+                    lambda: self.nodes[1].fundrawtransaction(rawtx, {"estimate_mode": mode, "conf_target": -1}))
+                assert_raises_rpc_error(-4, "Fee rate (0.00000000 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
+                    lambda: self.nodes[1].fundrawtransaction(rawtx, {"estimate_mode": mode, "conf_target": 0}))
+            else:
+                for n in [-1, 0, 1009]:
+                    assert_raises_rpc_error(-8, "Invalid conf_target, must be between 1 and 1008",
+                        lambda: self.nodes[1].fundrawtransaction(rawtx, {"estimate_mode": mode, "conf_target": n}))
+
+        for unit, fee_rate in {"SAT/B": 0.99999999, "BTC/KB": 0.00000999}.items():
```
Comment (Xekyo) [inline test/functional/rpc_fundrawtransaction.py:724]: Nit: Since this is new code, I'm surprised by the variations in the estimate_mode case, but not feeling strongly about it.

File: test/functional/rpc_fundrawtransaction.py [hunk 22]
```diff
@@ -672,6 +674,59 @@ def test_option_feerate(self):
...
+            self.log.info("- raises RPC error 'fee rate too low' if conf_target {} and estimate_mode {} are passed".format(fee_rate, unit))
+            assert_raises_rpc_error(-4, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
```
Comment (Xekyo) [inline test/functional/rpc_fundrawtransaction.py:726]: :+1:

File: test/functional/rpc_psbt.py [hunk 23]
```diff
@@ -186,15 +189,17 @@ def run_test(self):
...
         self.nodes[1].sendrawtransaction(self.nodes[1].finalizepsbt(walletprocesspsbt_out['psbt'])['hex'])
 
-        # feeRate of 0.1 BTC / KB produces a total fee slightly below -maxtxfee (~0.05280000):
-        res = self.nodes[1].walletcreatefundedpsbt([{"txid":txid,"vout":p2wpkh_pos},{"txid":txid,"vout":p2sh_p2wpkh_pos},{"txid":txid,"vout":p2pkh_pos}], {self.nodes[1].getnewaddress():29.99}, 0, {"feeRate": 0.1, "add_inputs": True})
+        self.log.info("Test walletcreatefundedpsbt feeRate of 0.1 BTC/kB produces a total fee at or slightly below -maxtxfee (~0.05290000)")
+        res = self.nodes[1].walletcreatefundedpsbt(inputs, outputs, 0, {"feeRate": 0.1, "add_inputs": True})
         assert_approx(res["fee"], 0.055, 0.005)
 
-        # feeRate of 10 BTC / KB produces a total fee well above -maxtxfee
+        self.log.info("Test walletcreatefundedpsbt feeRate of 10 BTC/KB produces total fee well above -maxtxfee and raises RPC error")
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py:241]: Nit: kelvinbytes

I know, I know, "kilo" is the odd one out because generally the prefixes for multiples are capitalized. Just being a bit of a unit nerd here.

(To be clear, when I mark a comment with "Nit:" I consider it optional for the author to address it.)

File: test/functional/rpc_psbt.py [hunk 24]
```diff
@@ -174,8 +174,11 @@ def run_test(self):
             elif out['scriptPubKey']['addresses'][0] == p2pkh:
                 p2pkh_pos = out['n']
 
+        inputs = [{"txid": txid, "vout": p2wpkh_pos}, {"txid": txid, "vout": p2sh_p2wpkh_pos}, {"txid": txid, "vout": p2pkh_pos}]
+        outputs = [{self.nodes[1].getnewaddress(): 29.99}]
```
Comment (Xekyo) [inline test/functional/rpc_psbt.py:178]: Love how much more readable the tests below become. Good improvement.

File: test/functional/wallet_send.py [hunk 25]
```diff
@@ -224,8 +226,10 @@ def run_test(self):
         assert_equal(self.nodes[1].decodepsbt(res1["psbt"])["fee"],
                      self.nodes[1].decodepsbt(res2["psbt"])["fee"])
         # but not at the same time
-        self.test_send(from_wallet=w0, to_wallet=w1, amount=1, arg_conf_target=1, arg_estimate_mode="economical",
-                       conf_target=1, estimate_mode="economical", add_to_wallet=False, expect_error=(-8,"Use either conf_target and estimate_mode or the options dictionary to control fee rate"))
+        for mode in ["unset", "economical", "conservative", "btc/kb", "sat/b"]:
+            self.test_send(from_wallet=w0, to_wallet=w1, amount=1, arg_conf_target=1, arg_estimate_mode="economical",
```
Comment (Xekyo) [inline test/functional/wallet_send.py:230]: I noticed that both `arg_estimate_mode` and `estimate_mode` appear in these test parameters. That seems odd. I wonder whether both pertain to the same value. If one of them would supersede the other, and that happened to be `arg_estimate_mode`, we would actually only be testing for `economical` here. If they actually do refer both to the same value, they should probably both be set to `=mode`.

File: test/functional/wallet_send.py [hunk 26]
```diff
@@ -246,19 +250,61 @@ def run_test(self):
...
+            self.test_send(from_wallet=w0, to_wallet=w1, amount=1, conf_target=-1, estimate_mode=mode,
+                expect_error=(-3, "Amount out of range"))
+            self.test_send(from_wallet=w0, to_wallet=w1, amount=1, conf_target=0, estimate_mode=mode,
+                expect_error=(-4, "Fee rate (0.00000000 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)"))
+
+        for mode in ["foo", Decimal("3.141592")]:
+            self.test_send(from_wallet=w0, to_wallet=w1, amount=1, conf_target=0.1, estimate_mode=mode,
+                expect_error=(-8, "Invalid estimate_mode parameter"))
+            # TODO: these 2 equivalent sends with an invalid estimate_mode arg should both fail, but they do not...why?
+            # self.test_send(from_wallet=w0, to_wallet=w1, amount=1, arg_conf_target=0.1, arg_estimate_mode=mode,
```
Comment (Xekyo) [inline test/functional/wallet_send.py:286]: The only difference I see in this line is that it now uses `arg_conf_target` where `conf_target` was used in 284 and `arg_estimate_mode` where `estimate_mode` was used. Potentially, the sanitation for those parameters are different?

File: src/wallet/rpcwallet.cpp [hunk 27]
```diff
@@ -440,7 +440,8 @@ static RPCHelpMan sendtoaddress()
                     {"subtractfeefromamount", RPCArg::Type::BOOL, /* default */ "false", "The fee will be deducted from the amount being sent.\n"
                                          "The recipient will receive less bitcoins than you enter in the amount field."},
                     {"replaceable", RPCArg::Type::BOOL, /* default */ "wallet default", "Allow this transaction to be replaced by a transaction with higher fees via BIP 125"},
-                    {"conf_target", RPCArg::Type::NUM, /* default */ "wallet default", "Confirmation target (in blocks), or fee rate (for " + CURRENCY_UNIT + "/kB or " + CURRENCY_ATOM + "/B estimate modes)"},
+                    {"conf_target", RPCArg::Type::NUM, /* default */ "wallet -txconfirmtarget", "Confirmation target (in blocks)\n"
```
Comment (Xekyo) [inline src/wallet/rpcwallet.cpp:443]: I see that the third argument here has changed from `"wallet default"` to `"wallet -txconfirmtarget"`, but it's not clear to me what the effect of that would be.

**Review by murchandamus — COMMENTED** [review]
Looks good to me. There are two spots where I wonder whether I found an actual issue, the rest are just nits that I consider optional.

File: test/functional/wallet_send.py (hunk 25 above)
Comment (jonatack) [reply test/functional/wallet_send.py:230]: Good point. In RPC send, `conf_target` and `estimate_mode` can be both args (`arg_estimate_mode` in this test file, which sets up its own mini-framework) and options (`estimate_mode` in the test).

There seem to be some oddities or bugs caused by this, e.g. the commented-out tests in lines 289-292. The send RPC is marked as experimental, but these should be fixed or made consistent with the other RPCs after this is merged. I started to look into it but didn't find a fix quickly, and the PR is already quite large and the deadline for 0.21 branch-off this weekend is looming.

File: test/functional/wallet_send.py (hunk 26 above)
Comment (jonatack) [reply test/functional/wallet_send.py:286]: Yes, there seems to be a bug: per the code in rpcwallet.cpp, these should behave the same whether passed as an arg or an option, but they do not.

File: src/wallet/rpcwallet.cpp (hunk 27 above)
Comment (jonatack) [reply src/wallet/rpcwallet.cpp:443]: This is the RPC help output the user sees. The idea was to make the `conf_target` help correct (some were missing the sat/B mention), consistent and helpful across the 6 RPCs. The txconfirmtarget mention in some of the `conf_target` helps seems more useful info than just "wallet default", so I made them all the same/consistent.

Comment (jonatack) [reply src/wallet/rpcwallet.cpp:443]: This is the RPC help output the user sees. The idea was to make the `conf_target` help correct (some were missing the sat/B mention), consistent and helpful across the 6 RPCs. The txconfirmtarget mention in some of the `conf_target` helps seems more useful info than just "wallet default", so I made them all the same/consistent. Open to disagreement about that :)

File: test/functional/rpc_psbt.py (hunk 23 above)
Comment (jonatack) [reply test/functional/rpc_psbt.py:241]: done

File: test/functional/rpc_fundrawtransaction.py (hunk 21 above)
Comment (jonatack) [reply test/functional/rpc_fundrawtransaction.py:724]: made them all the same

File: test/functional/wallet_basic.py [hunk 28]
```diff
@@ -421,7 +421,7 @@ def run_test(self):
             assert prebalance > 2
             address = self.nodes[1].getnewaddress()
             # Throw if no conf_target provided
-            assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate",
+            assert_raises_rpc_error(-8, "Selected estimate_mode BTc/Kb requires a fee rate to be specified in conf_target",
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:431]: I suppose I'll make them all proper-cased in wallet_basic, and lowercased in fundrawtransaction, so they are less jarring while still testing the case insensitivity.

File: test/functional/wallet_basic.py [hunk 29]
```diff
@@ -447,15 +454,15 @@ def run_test(self):
...
-            self.log.info("test explicit fee (sendtoaddress as sat/b)")
+
+            self.log.info("Test explicit fee (sendtoaddress as sat/B)")
             self.nodes[0].generate(1)
             prebalance = self.nodes[2].getbalance()
             assert prebalance > 2
             address = self.nodes[1].getnewaddress()
             # Throw if no conf_target provided
-            assert_raises_rpc_error(-8, "Selected estimate_mode requires a fee rate",
+            assert_raises_rpc_error(-8, "Selected estimate_mode SAT/b requires a fee rate to be specified in conf_target",
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:465]: made sat/B

File: test/functional/wallet_basic.py [hunk 30]
```diff
@@ -447,15 +454,15 @@ def run_test(self):
             fee = prebalance - postbalance - Decimal('1')
             assert_fee_amount(fee, tx_size, Decimal('0.00002500'))
 
-            # send with explicit sat/b fee
             self.sync_all(self.nodes[0:3])
-            self.log.info("test explicit fee (sendtoaddress as sat/b)")
+
+            self.log.info("Test explicit fee (sendtoaddress as sat/B)")
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:459]: agree, done

File: test/functional/wallet_basic.py (hunk 19 above)
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:259]: good eye, done

File: test/functional/wallet_basic.py [hunk 31]
```diff
@@ -413,15 +421,14 @@ def run_test(self):
             self.nodes[0].generate(1)
             self.sync_all(self.nodes[0:3])
 
-            # send with explicit btc/kb fee
-            self.log.info("test explicit fee (sendtoaddress as btc/kb)")
+            self.log.info("Test explicit fee (sendtoaddress as BTC/kB)")
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:424]: done

File: test/functional/wallet_basic.py [hunk 32]
```diff
@@ -252,9 +254,9 @@ def run_test(self):
         node_0_bal += Decimal('10')
         assert_equal(self.nodes[0].getbalance(), node_0_bal)
 
-        # Sendmany with explicit fee (SAT/B)
+        self.log.info("Test explicit fee (sendmany as sat/B)")
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:257]: done

File: test/functional/wallet_basic.py [hunk 33]
```diff
@@ -226,9 +228,9 @@ def run_test(self):
         assert_equal(self.nodes[2].getbalance(), node_2_bal)
         node_0_bal = self.check_fee_amount(self.nodes[0].getbalance(), node_0_bal + Decimal('10'), fee_per_byte, self.get_vsize(self.nodes[2].gettransaction(txid)['hex']))
 
-        # Sendmany with explicit fee (BTC/kB)
```
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:229]: Good eye! Done

File: src/wallet/rpcwallet.cpp (hunk 27 above)
Comment (jonatack) [reply src/wallet/rpcwallet.cpp:443]: e.g. before
```
7. conf_target      (numeric, optional, default=wallet default) Confirmation target (in blocks), or fee rate (for BTC/kB or sat/B estimate modes)
```
after
```
7. conf_target      (numeric, optional, default=wallet -txconfirmtarget) Confirmation target (in blocks)
                    or fee rate (for BTC/kB and sat/B estimate modes)
```

File: test/functional/wallet_basic.py (hunk 28 above)
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:431]: Oh wait, in wallet_basic.py I'd rather not touch the units in the original tests by @kallewoof. They were set this way on purpose. See closed PR #20041 that wanted to change them.

[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:431]: I'll add "case insensitive" to the logging so it's clear to future readers of the test code.

**Comment by jonatack** [comment]
Thanks @Xekyo, updated units and comments per `git diff c80e227 0be2900`.

<details><summary><code>git diff c80e227 0be2900</code></summary><p>

```diff
diff --git a/test/functional/rpc_fundrawtransaction.py b/test/functional/rpc_fundrawtransaction.py
index a0e1d1b8a3..85ecb40354 100755
--- a/test/functional/rpc_fundrawtransaction.py
+++ b/test/functional/rpc_fundrawtransaction.py
@@ -721,7 +721,7 @@ class RawTransactionsTest(BitcoinTestFramework):
                     assert_raises_rpc_error(-8, "Invalid conf_target, must be between 1 and 1008",
                         lambda: self.nodes[1].fundrawtransaction(rawtx, {"estimate_mode": mode, "conf_target": n}))
 
-        for unit, fee_rate in {"SAT/B": 0.99999999, "BTC/KB": 0.00000999}.items():
+        for unit, fee_rate in {"sat/B": 0.99999999, "BTC/kB": 0.00000999}.items():
             self.log.info("- raises RPC error 'fee rate too low' if conf_target {} and estimate_mode {} are passed".format(fee_rate, unit))
             assert_raises_rpc_error(-4, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
                 lambda: self.nodes[1].fundrawtransaction(rawtx, {"estimate_mode": unit, "conf_target": fee_rate, "add_inputs": True}))
diff --git a/test/functional/rpc_psbt.py b/test/functional/rpc_psbt.py
index 31a28d6ae7..28bcc516c6 100755
--- a/test/functional/rpc_psbt.py
+++ b/test/functional/rpc_psbt.py
@@ -238,7 +238,7 @@ class PSBTTest(BitcoinTestFramework):
             assert_raises_rpc_error(-4, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
                 lambda: self.nodes[1].walletcreatefundedpsbt(inputs, outputs, 0, {"estimate_mode": unit, "conf_target": fee_rate, "add_inputs": True}))
 
-        self.log.info("Test walletcreatefundedpsbt feeRate of 10 BTC/KB produces total fee well above -maxtxfee and raises RPC error")
+        self.log.info("Test walletcreatefundedpsbt feeRate of 10 BTC/kB produces total fee well above -maxtxfee and raises RPC error")
         # previously this was silently capped at -maxtxfee
         for bool_add, outputs_array in {True: outputs, False: [{self.nodes[1].getnewaddress(): 1}]}.items():
             assert_raises_rpc_error(-4, "Fee exceeds maximum configured by user (e.g. -maxtxfee, maxfeerate)",
diff --git a/test/functional/wallet_basic.py b/test/functional/wallet_basic.py
index 584be1da94..411ae3db29 100755
--- a/test/functional/wallet_basic.py
+++ b/test/functional/wallet_basic.py
@@ -228,7 +228,7 @@ class WalletTest(BitcoinTestFramework):
         assert_equal(self.nodes[2].getbalance(), node_2_bal)
         node_0_bal = self.check_fee_amount(self.nodes[0].getbalance(), node_0_bal + Decimal('10'), fee_per_byte, self.get_vsize(self.nodes[2].gettransaction(txid)['hex']))
 
-        self.log.info("Test explicit fee (sendmany as BTC/kB)")
+        self.log.info("Test case-insensitive explicit fee rate (sendmany as BTC/kB)")
         # Throw if no conf_target provided
         assert_raises_rpc_error(-8, "Selected estimate_mode bTc/kB requires a fee rate to be specified in conf_target",
             self.nodes[2].sendmany,
@@ -254,7 +254,7 @@ class WalletTest(BitcoinTestFramework):
         node_0_bal += Decimal('10')
         assert_equal(self.nodes[0].getbalance(), node_0_bal)
 
-        self.log.info("Test explicit fee (sendmany as sat/B)")
+        self.log.info("Test case-insensitive explicit fee rate (sendmany as sat/B)")
         # Throw if no conf_target provided
         assert_raises_rpc_error(-8, "Selected estimate_mode sat/b requires a fee rate to be specified in conf_target",
             self.nodes[2].sendmany,
@@ -283,7 +283,7 @@ class WalletTest(BitcoinTestFramework):
         assert_equal(self.nodes[0].getbalance(), node_0_bal)
 
         # Test setting explicit fee rate just below the minimum.
-        for unit, fee_rate in {"BTC/KB": 0.00000999, "SAT/B": 0.99999999}.items():
+        for unit, fee_rate in {"BTC/kB": 0.00000999, "sat/B": 0.99999999}.items():
             self.log.info("Test sendmany raises 'fee rate too low' if conf_target {} and estimate_mode {} are passed".format(fee_rate, unit))
             assert_raises_rpc_error(-6, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
                 self.nodes[2].sendmany, amounts={address: 10}, estimate_mode=unit, conf_target=fee_rate)
@@ -421,7 +421,7 @@ class WalletTest(BitcoinTestFramework):
             self.nodes[0].generate(1)
             self.sync_all(self.nodes[0:3])
 
-            self.log.info("Test explicit fee (sendtoaddress as BTC/kB)")
+            self.log.info("Test case-insensitive explicit fee rate (sendtoaddress as BTC/kB)")
             self.nodes[0].generate(1)
             self.sync_all(self.nodes[0:3])
             prebalance = self.nodes[2].getbalance()
@@ -456,7 +456,7 @@ class WalletTest(BitcoinTestFramework):
 
             self.sync_all(self.nodes[0:3])
 
-            self.log.info("Test explicit fee (sendtoaddress as sat/B)")
+            self.log.info("Test case-insensitive explicit fee rate (sendtoaddress as sat/B)")
             self.nodes[0].generate(1)
             prebalance = self.nodes[2].getbalance()
             assert prebalance > 2
@@ -489,7 +489,7 @@ class WalletTest(BitcoinTestFramework):
             assert_fee_amount(fee, tx_size, Decimal('0.00002000'))
 
             # Test setting explicit fee rate just below the minimum.
-            for unit, fee_rate in {"BTC/KB": 0.00000999, "SAT/B": 0.99999999}.items():
+            for unit, fee_rate in {"BTC/kB": 0.00000999, "sat/B": 0.99999999}.items():
                 self.log.info("Test sendtoaddress raises 'fee rate too low' if conf_target {} and estimate_mode {} are passed".format(fee_rate, unit))
                 assert_raises_rpc_error(-6, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)",
                     self.nodes[2].sendtoaddress, address=address, amount=1, estimate_mode=unit, conf_target=fee_rate)
diff --git a/test/functional/wallet_send.py b/test/functional/wallet_send.py
index a6002b67f0..5840a24404 100755
--- a/test/functional/wallet_send.py
+++ b/test/functional/wallet_send.py
@@ -271,7 +271,7 @@ class WalletSendTest(BitcoinTestFramework):
         fee = self.nodes[1].decodepsbt(res["psbt"])["fee"]
         assert_fee_amount(fee, Decimal(len(res["hex"]) / 2), Decimal("0.00003"))
 
-        # TODO: This test should pass with all modes, e.g. with the next line uncommented.
+        # TODO: This test should pass with all modes, e.g. with the next line uncommented, for consistency with the other explicit feerate RPCs.
         # for mode in ["unset", "economical", "conservative", "btc/kb", "sat/b"]:
         for mode in ["btc/kb", "sat/b"]:
             self.test_send(from_wallet=w0, to_wallet=w1, amount=1, conf_target=-1, estimate_mode=mode,
@@ -285,24 +285,24 @@ class WalletSendTest(BitcoinTestFramework):
             # TODO: these 2 equivalent sends with an invalid estimate_mode arg should both fail, but they do not...why?
             # self.test_send(from_wallet=w0, to_wallet=w1, amount=1, arg_conf_target=0.1, arg_estimate_mode=mode,
             #     expect_error=(-8, "Invalid estimate_mode parameter"))
-            # assert_raises_rpc_error(-8, "Invalid estimate_mode parameter", lambda: w0.send({w0.getnewaddress(): 1}, 0.1, mode))
+            # assert_raises_rpc_error(-8, "Invalid estimate_mode parameter", lambda: w0.send({w1.getnewaddress(): 1}, 0.1, mode))
 
-        # TODO: These tests should pass but they do not.
+        # TODO: These tests should pass for consistency with the other explicit feerate RPCs, but they do not.
         # for mode in ["unset", "economical", "conservative", "btc/kb", "sat/b"]:
         #     self.log.debug("{}".format(mode))
         #     for k, v in {"string": "", "object": {"foo": "bar"}}.items():
         #         self.test_send(from_wallet=w0, to_wallet=w1, amount=1, conf_target=v, estimate_mode=mode,
         #             expect_error=(-3, "Expected type number for conf_target, got {}".format(k)))
 
-        # TODO: error should use sat/b
+        # TODO: error should use sat/B instead of BTC/kB if sat/B is selected.
         # Test setting explicit fee rate just below the minimum.
-        for unit, fee_rate in {"SAT/B": 0.99999999, "BTC/KB": 0.00000999}.items():
+        for unit, fee_rate in {"sat/B": 0.99999999, "BTC/kB": 0.00000999}.items():
             self.log.info("Explicit fee rate raises RPC error 'fee rate too low' if conf_target {} and estimate_mode {} are passed".format(fee_rate, unit))
             self.test_send(from_wallet=w0, to_wallet=w1, amount=1, conf_target=fee_rate, estimate_mode=unit,
                 expect_error=(-4, "Fee rate (0.00000999 BTC/kB) is lower than the minimum fee rate setting (0.00001000 BTC/kB)"))
 
         self.log.info("Explicit fee rate raises RPC error if estimate_mode is passed without a conf_target")
-        for unit, fee_rate in {"SAT/B": 100, "BTC/KB": 0.001}.items():
+        for unit, fee_rate in {"sat/B": 100, "BTC/kB": 0.001}.items():
             self.test_send(from_wallet=w0, to_wallet=w1, amount=1, estimate_mode=unit,
                 expect_error=(-8, "Selected estimate_mode {} requires a fee rate to be specified in conf_target".format(unit)))

```
</p></details>

File: test/functional/wallet_send.py (hunk 25 above)
Comment (Xekyo) [reply test/functional/wallet_send.py:230]: Okay, since this is only in a test, it may be fine to keep track of it, but not get too hung up on fixing every little bit before the merge.

File: src/wallet/rpcwallet.cpp (hunk 27 above)
Comment (Xekyo) [reply src/wallet/rpcwallet.cpp:443]: I see. That looks like a good change to me.

**Comment by Xekyo** [comment]
Just ran the functional tests (for the previous commit I reviewed), which takes a surprisingly long time. Luckily, the first hit on an internet search for how to run the functional tests was this guide by some Jon Atack, made it really easy to get set up. :laughing:

**Comment by Xekyo** [comment]
Changes look great to me. 
utack `0be2900` 
currently running functional tests.

File: test/functional/wallet_basic.py (hunk 28 above)
[the remark this answers is not in the document]
Comment (Xekyo) [reply test/functional/wallet_basic.py:431]: Cool, thanks for digging up the context. I still think it would be better to test case insensitivity of an argument in one dedicated test and then make all the other tests use the canonical writing, but it's definitely out of scope here.

**Comment by sipa** [comment]
@Xekyo You can run them in parallel; if you have sufficient RAM pretty extremely even. `test_runner.py -j60` works fine on my 4-core 32 GIB RAM system, taking 3m46s. A lot of the time consists of processing waiting for each other, so it's not actually CPU bound.

File: test/functional/wallet_basic.py (hunk 28 above)
[the remark this answers is not in the document]
Comment (jonatack) [reply test/functional/wallet_basic.py:431]: Agree, and in a way that's what we've done: The added tests use canonical units and the original tests in wallet_basic.py do case insensitive unit testing and are now described as such.

**Comment by jonatack** [comment]
> You can run them in parallel; if you have sufficient RAM pretty extremely even. `test_runner.py -j60` works fine on my 4-core 32 GIB RAM system

Good point; I'll mention that in the guide.

**Comment by Xekyo** [comment]
tack (functional tests only) 0be29000c011dec0722481dbebb159873da6fa54

**Review by kallewoof — COMMENTED** [review]
Concept/Tested ACK 0be29000c011dec0722481dbebb159873da6fa54

It feels like this touches a fair bit of code that is unrelated to the explicit fee rate stuff, but maybe it's related and I'm just not seeing it. Otherwise looks good.

(I was unable to run test_runner with any kind of -j flags, though both machines had bitcoin daemons running which it claims could cause problems.)

File: src/wallet/rpcwallet.cpp [hunk 34]
```diff
@@ -3373,7 +3376,7 @@ static RPCHelpMan bumpfee_helper(std::string method_name)
         "The command will pay the additional fee by reducing change outputs or adding inputs when necessary. It may add a new change output if one does not already exist.\n"
         "All inputs in the original transaction will be included in the replacement transaction.\n"
         "The command will fail if the wallet or mempool contains a transaction that spends one of T's outputs.\n"
-        "By default, the new fee will be calculated automatically using estimatesmartfee.\n"
+        "By default, the new fee will be calculated automatically using the estimatesmartfee RPC.\n"
```
[the remark this answers is not in the document]
Comment (jonatack) [reply src/wallet/rpcwallet.cpp:3379]: Thanks @kallewoof--the idea was to help users know what estimatesmartfee is and where to look for more info without grepping the codebase, even though it's less exact than writing, say, "using CBlockPolicyEstimator::estimateSmartFee in src/fees.cpp". I don't feel strongly about it though.

**Comment by jonatack** [comment]
> @Xekyo You can run them in parallel; if you have sufficient RAM pretty extremely even. `test_runner.py -j60` works fine on my 4-core 32 GiB RAM system, taking 3m46s. A lot of the time consists of processes waiting for each other, so it's not actually CPU bound.

I have a sloow 4-core 32GB RAM laptop and `test/functional/test_runner.py -j60` does run much faster--good tip.

**Review by meshcollider — COMMENTED** [review]
Code review + functional test run ACK 0be29000c011dec0722481dbebb159873da6fa54

Very nice improvements & cleanups, thanks jonatack!

**Comment by jonatack** [comment]
Thank you @Xekyo, @kallewoof and @meshcollider!

File: test/functional/wallet_send.py (hunk 26 above)
Comment (jonatack) [reply test/functional/wallet_send.py:286]: > Yes, there seems to be a bug in the `send` RPC: per the code in `wallet/rpcwallet.cpp`, these should behave the same whether passed as an arg or an option, but they do not.

Fixed in #20305.
