### PR TITLE
util/check: Don't use a lambda for Assert/Assume

### LINKED ISSUE #21596: How to tell compilers to not drop the lock stack when using Assume/Assert?
It would be nice if there was a way to tell compilers not to drop the lock stack and thus issue warnings when accessing a symbol that needs a lock inside `Assume`/`Assert`.

Hit by (at least): @ajtowns , @jnewbery , me.

### LINKED ISSUE #24654: util/check.h Assert/Assume: namespacing issues
The `Assert`/`Assume` macros are implemented via lambda functions to allow the result of the assertion to both be evaluated (and trigger an abort) and be returned without having the expression be evaluated twice.

This causes some ugly namespacing issues though. Because there's a function call, clang's thread safety annotations don't get passed through (as the lambda is unannotated), possibly causing an unnecessary compiler error because the compiler loses track that a mutex is held when a guarded variable is accessed.

It also seems that gcc (but not clang) gets confused about member functions (but not member variables), eg:

```c++
class TestAssert
{
public:
    int variable = 3;
    int test_1(void) { return variable; }
    int test_2(void) {
        auto x = [&]() {
            Assert(test_1() == 3);
        };
        x();
        return ++variable;
    }
};
```

results in:

```
test/util_tests.cpp:91:26: error: cannot call member function ‘int util_tests::TestAssert::test_1()’ without object
   91 |             Assert(test_1() == 3);
```

requiring you to write `Assert(this->test_1() == 3)` instead.

### PR DESCRIPTION
**Pull request by ajtowns**
Using a lambda creates a couple of odd namespacing issues, in particular making clang's thread safety analysis less helpful, and confusing gcc when calling member functions. Fix this by not using a lambda.

Fixes #21596
Fixes #24654

### CODE REVIEW

File: src/wallet/test/wallet_test_fixture.h [hunk 1]
```diff
@@ -19,10 +19,13 @@ namespace wallet {
 /** Testing setup and teardown for wallet.
  */
 struct WalletTestingSetup : public TestingSetup {
-    explicit WalletTestingSetup(const std::string& chainName = CBaseChainParams::MAIN);
+    WalletTestingSetup() : WalletTestingSetup(CBaseChainParams::MAIN) { }
+    explicit WalletTestingSetup(const std::string& chainName);
+    WalletTestingSetup(const WalletTestingSetup&) = delete;
+    WalletTestingSetup(WalletTestingSetup&&) = delete;
```
Comment (MarcoFalke) [inline src/wallet/test/wallet_test_fixture.h:25]: The changes look unrelated? Also, anything with a unique_ptr member should have them deleted already, before and after the changes here.

File: src/wallet/test/wallet_test_fixture.h [hunk 2]
```diff
@@ -19,10 +19,13 @@ namespace wallet {
...
     ~WalletTestingSetup();
 
-    std::unique_ptr<interfaces::WalletLoader> m_wallet_loader = interfaces::MakeWalletLoader(*m_node.chain, *Assert(m_node.args));
+    std::unique_ptr<interfaces::WalletLoader> m_wallet_loader;
```
Comment (MarcoFalke) [inline src/wallet/test/wallet_test_fixture.h:28]: I presume this is to silence clang TS warnings? If so, could mention it in the commit body.

File: src/test/util_tests.cpp [hunk 3]
```diff
@@ -78,6 +78,29 @@ BOOST_AUTO_TEST_CASE(util_datadir)
     BOOST_CHECK_EQUAL(dd_norm, args.GetDataDirBase());
 }
 
+namespace {
+class NoCopyOrMove
+{
+public:
+    int i = 0;
```
Comment (MarcoFalke) [inline src/test/util_tests.cpp:85]:
```suggestion
    int i;
```

nit: Can leave un-initialized for clarity, since the default value is never used.

File: src/test/util_tests.cpp [hunk 4]
```diff
@@ -89,6 +112,14 @@ BOOST_AUTO_TEST_CASE(util_check)
     // Check that Assume can be used as unary expression
     const bool result{Assume(two == 2)};
     Assert(result);
+
+    // Check that Assert doesn't require copy/move
+    NoCopyOrMove x{9};
+    Assert(x).i += 3;
+    Assert(x).test();
```
Comment (MarcoFalke) [inline src/test/util_tests.cpp:119]: Maybe check the return value, if that was the point?

File: src/test/util_tests.cpp [hunk 5]
```diff
@@ -78,6 +78,29 @@ BOOST_AUTO_TEST_CASE(util_datadir)
...
+    NoCopyOrMove& operator=(NoCopyOrMove&&) = delete;
+
+    operator bool() const { return i != 0; }
+
+    int getp1() { return i + 1; }
+    int test() {
+        // Check that Assume can be used within a lambda and still call methods
+        [&]() { Assume(getp1()); }();
+        if (Assume(getp1() != 5)) return 3;
+        return 9;
```
Comment (MarcoFalke) [inline src/test/util_tests.cpp:99]: Looks like it would be sufficient to return a `bool` with either `true` or `false`, here?

File: src/test/util_tests.cpp [hunk 6]
```diff
@@ -89,6 +112,14 @@ BOOST_AUTO_TEST_CASE(util_check)
...
     const bool result{Assume(two == 2)};
     Assert(result);
+
+    // Check that Assert doesn't require copy/move
+    NoCopyOrMove x{9};
+    Assert(x).i += 3;
+    Assert(x).test();
+
+    // Check nested Asserts
+    Assert( Assert(x).i != 5 );
```
Comment (MarcoFalke) [inline src/test/util_tests.cpp:122]: clang-format new code?

**Review by maflcko — APPROVED** [review]
Looks good, some nits.

File: src/wallet/test/wallet_test_fixture.h (hunk 2 above)
Comment (ajtowns) [reply src/wallet/test/wallet_test_fixture.h:28]: `Assert` uses `__func__` which is not defined outside of a function body, but the initializer list counts as part of the constructor body.

File: src/test/util_tests.cpp (hunk 4 above)
Comment (ajtowns) [reply src/test/util_tests.cpp:120]: Point was mostly to call `test()`

**Comment by ajtowns** [comment]
Nits picked

**Comment by MarcoFalke** [comment]
Tested with diff:

```diff
diff --git a/src/test/util_tests.cpp b/src/test/util_tests.cpp
index 1881573e7a..d7328ff450 100644
--- a/src/test/util_tests.cpp
+++ b/src/test/util_tests.cpp
@@ -84,7 +84,7 @@ BOOST_AUTO_TEST_CASE(util_check)
     const std::unique_ptr<int> p_two = Assert(std::make_unique<int>(2));
     // Check that Assert works on lvalues and rvalues
     const int two = *Assert(p_two);
-    Assert(two == 2);
+    Assert(two != 2);
     Assert(true);
     // Check that Assume can be used as unary expression
     const bool result{Assume(two == 2)};
```

Before:

```
$ ./src/test/test_bitcoin -t util_tests/util_check --catch_system_errors=no 
Running 1 test case...
test_bitcoin: test/util_tests.cpp:87: auto util_tests::util_check::test_method()::(anonymous class)::operator()() const: Assertion `"two != 2" && check' failed.
Aborted (core dumped)
```

With this pull:

```
$ ./src/test/test_bitcoin -t util_tests/util_check --catch_system_errors=no 
Running 1 test case...
test/util_tests.cpp:87 test_method: Assertion `two != 2' failed.
Aborted (core dumped)

File: src/test/util_tests.cpp [hunk 7]
```diff
@@ -78,6 +78,30 @@ BOOST_AUTO_TEST_CASE(util_datadir)
...
+    NoCopyOrMove() = delete;
+    NoCopyOrMove(const NoCopyOrMove&) = delete;
+    NoCopyOrMove(NoCopyOrMove&&) = delete;
+    NoCopyOrMove& operator=(const NoCopyOrMove&) = delete;
+    NoCopyOrMove& operator=(NoCopyOrMove&&) = delete;
+
+    operator bool() const { return i != 0; }
+
+    int get_ip1() { return i + 1; }
+    bool test() {
```
Comment (MarcoFalke) [inline src/test/util_tests.cpp:97]: clang-format nit (in case you retouch for other reasons)

```suggestion
    bool test()
    {
```

File: src/util/check.h [hunk 8]
```diff
@@ -46,15 +46,26 @@ class NonFatalCheckError : public std::runtime_error
 #error "Cannot compile without assertions!"
 #endif
 
+/** Helper for Assert() */
+void assertion_fail(const char* file, int line, const char* func, const char* assertion);
+
 /** Helper for Assert() */
 template <typename T>
-T get_pure_r_value(T&& val)
+inline T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
```
Comment (MarcoFalke) [inline src/util/check.h:54]: nit: All `template`s are inline.

```suggestion
T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
```

File: src/util/check.h [hunk 9]
```diff
@@ -46,15 +46,26 @@ class NonFatalCheckError : public std::runtime_error
...
 {
+    if (!val) assertion_fail(file, line, func, assertion);
```
Comment (MarcoFalke) [inline src/util/check.h:56]: nit: I think it is better to use a new line unless it is a trivial single statement like `return` or `continue` or `break` ...
```suggestion
    if (!val) {
        assertion_fail(file, line, func, assertion);
    }
```

**Review by maflcko — APPROVED** [review]
Left some more nits (can be ignored).

ACK 3bcffa1146beb40e28bd1bcfaccf72e0d138c9c0 🐤

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 3bcffa1146beb40e28bd1bcfaccf72e0d138c9c0 🐤
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgTQgv9HP5fwUc67QUWBjyLMXITzFCx7fUOKh97aePdHaegYMjauudEKiY5TOTi
Ks9HFnnirQmNq23B21wTGlkJBRkGIG16v3S5dS7iDGETGepXDBc1myBJv5u2AElG
l4IKxqWPVs9EUAzpDaNo9nxXrz0O3xPlUVDPA46zVl+IUDM8gZ3t8uqEoJAly7Jj
9FMreyD2riiKrZ9+dEIhAsJ08/Ski9lwxforRvVvk5a8dIztKgScjHWP+TcL5bTA
ICA6d5TF6Zbl1SpTgNFNM+Yw9rCiND+4Z/k8zDUYnrt0dF13I4uDHG1FX8xgTvL/
yxj/0/PC8gZfphOPWnL++06MMtKuplTY5TJD3pcC2MJZORU/fJp+w1RKvhaaf0/W
ZZzK2rj9kGeKOofSRKvqWq7zgd+8L8GK1xtV6AsCzuMGoEruXZlF0BI/CiLF1b0z
hzunflN07ltCAl0R2LpAJ1YDazE/vY+A25K6iktkAhXpB0+6WGNGFjk1BKeXU3lX
xDrgwPRG
=7L0O
-----END PGP SIGNATURE-----
```


</details>

File: src/util/check.h [hunk 10]
```diff
@@ -46,15 +46,26 @@ class NonFatalCheckError : public std::runtime_error
...
 /** Identity function. Abort if the value compares equal to zero */
-#define Assert(val) ([&]() -> decltype(get_pure_r_value(val)) { auto&& check = (val); assert(#val && check); return std::forward<decltype(get_pure_r_value(val))>(check); }())
+#define Assert(val) inline_assertion_check(val, __FILE__, __LINE__, __func__, #val)
+
+/** Helper for Assume() */
+template <typename T>
+inline T&& skip_assumption_check(T&& val)
+{
+    return std::forward<T>(val);
+}
```
Comment (MarcoFalke) [inline src/util/check.h:68]: It might be possible to remove the separate helpers and just use the same function for both:

```diff
diff --git a/src/util/check.h b/src/util/check.h
index 3fa49c0a3e..4c2ee4501b 100644
--- a/src/util/check.h
+++ b/src/util/check.h
@@ -51,21 +51,22 @@ void assertion_fail(const char* file, int line, const char* func, const char* as
 
 /** Helper for Assert() */
 template <typename T>
-inline T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
+T&& maybe_abort_on_check(bool IS_ASSERT, T&& val, const char* file, int line, const char* func, const char* assertion)
 {
-    if (!val) assertion_fail(file, line, func, assertion);
+    if (!val) {
+        if (IS_ASSERT // Abort inside Assert()
+#ifdef ABORT_ON_FAILED_ASSUME
+            || true // Abort inside Assume()
+#endif
+        ) {
+            assertion_fail(file, line, func, assertion);
+        }
+    }
     return std::forward<T>(val);
 }
 
 /** Identity function. Abort if the value compares equal to zero */
-#define Assert(val) inline_assertion_check(val, __FILE__, __LINE__, __func__, #val)
-
-/** Helper for Assume() */
-template <typename T>
-inline T&& skip_assumption_check(T&& val)
-{
-    return std::forward<T>(val);
-}
+#define Assert(val) maybe_abort_on_check(true, val, __FILE__, __LINE__, __func__, #val)
 
 /**
  * Assume is the identity function.
@@ -77,10 +78,6 @@ inline T&& skip_assumption_check(T&& val)
  * - For non-fatal errors in interactive sessions (e.g. RPC or command line
  *   interfaces), CHECK_NONFATAL() might be more appropriate.
  */
-#ifdef ABORT_ON_FAILED_ASSUME
-#define Assume(val) Assert(val)
-#else
-#define Assume(val) skip_assumption_check(val)
-#endif
+#define Assume(val) maybe_abort_on_check(false, val, __FILE__, __LINE__, __func__, #val)
 
 #endif // BITCOIN_UTIL_CHECK_H

**Comment by jonatack** [comment]
Concept ACK, testing

**Comment by MarcoFalke** [comment]
Looks like this also intentionally or accidentally fixes #21596, as the value is no longer evaluated inside the function, but before passing it to the function as parameter?

Also, it fixes the nesting issue that is fixed only in C++20 (#23363)?


Quite amazing that this relatively simple patch fixes three bugs.

File: src/util/check.h (hunk 10 above)
Comment (ajtowns) [reply src/util/check.h]: Made it a template argument instead of a function param, used `if constexpr` and left the `!val` as the inner `if`, but otherwise taken up.

**Review by jonatack — COMMENTED** [review]
ACK 3bcffa1146beb40e28bd1bcfaccf72e0d138c9c0

If #24672 is reverted with the following diff
```diff
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -1541,7 +1541,7 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
 
     // ********************************************************* Step 8: start indexers
     if (args.GetBoolArg("-txindex", DEFAULT_TXINDEX)) {
-        if (const auto error{WITH_LOCK(cs_main, return CheckLegacyTxindex(*Assert(chainman.m_blockman.m_block_tree_db)))}) {
+        if (const auto error{CheckLegacyTxindex(*Assert(chainman.m_blockman.m_block_tree_db))}) {
             return InitError(*error);
         }
```
then with this pull Clang thread safety analysis is now able to detect the missing lock that on current master was previously undetected
```
  CXX      node/libbitcoin_node_a-blockstorage.o
init.cpp:1544:77: error: passing variable 'm_block_tree_db' by reference requires holding mutex 'cs_main' [-Werror,-Wthread-safety-reference]
        if (const auto error{CheckLegacyTxindex(*Assert(chainman.m_blockman.m_block_tree_db))}) {
                                                                            ^
1 error generated.
```

**Comment by ajtowns** [comment]
Nits picked again

**Review by maflcko — APPROVED** [review]
Couldn't find more nits.

ACK 2ef47ba6c57a12840499a13908ab61aefca6cb55 🚢

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

ACK 2ef47ba6c57a12840499a13908ab61aefca6cb55 🚢
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUjUxwv7BclwGFAkVZZoIl0/IF1gA7gkGSNIRdHWw0oS+fOvd7SLO369yYsTParO
DdQ8FLTNoptoKsSJ2C6CyNl1zZ0WV7Wvndj66uFjsHntn5N4OWwBm+731zyBMRJo
xbOloJXrcLj5Aw1KXBCuKN4mylLN/PFythzdq2+VnAtjOTjw59JYKpqktfSQAXS3
+51l9BCZJf/F2G4pa1y8yKqyeuAr+IGsC/4SvFybXCaFLiRAR8A+4/TFsAmTJnYn
T3csvAXoLJDfdn0/mGV2d5pSlPwxqvIMJdhW01cm4Oj2BDgPdsSUizLiTATtTvIG
69a2nOO9mDBNbtfj7Wy/BATVRMQDVBxZeafdbCYtUO7/BjyAzAE7hSOODAMtv98p
XQFfDvhBZSsuYEaADQELDx1FqNn7fqz7I/NjiWZbz9+onINH8t+IDlO+qUcChQ3w
aIX/q1FjmZVxWtqf/kiKyann0Gx3plqjnBFSv/54P0K3D5s4yS1BWNSZOGyciGb+
Cm6dc3hb
=xsn6
-----END PGP SIGNATURE-----
```


</details>

**Review by jonatack — COMMENTED** [review]
Tested re-ACK 2ef47ba6c57a12840499a13908ab61aefca6cb55

Nice updates in the last push.

<details><summary>couple of nits</summary><p>

not worth changing unless you retouch for something else

```diff
diff --git a/src/test/util_tests.cpp b/src/test/util_tests.cpp
index b5d8411e1d..95d84593aa 100644
--- a/src/test/util_tests.cpp
+++ b/src/test/util_tests.cpp
@@ -79,9 +79,8 @@ BOOST_AUTO_TEST_CASE(util_datadir)

-class NoCopyOrMove
+struct NoCopyOrMove
 {
-public:
     int i;
     explicit NoCopyOrMove(int i) : i{i} { }
 
diff --git a/src/util/check.cpp b/src/util/check.cpp
index 2a9f885560..56d66f78c6 100644
--- a/src/util/check.cpp
+++ b/src/util/check.cpp
@@ -8,7 +8,7 @@
 
 void assertion_fail(const char* file, int line, const char* func, const char* assertion)
 {
-    auto str = strprintf("%s:%s %s: Assertion `%s' failed.\n", file, line, func, assertion);
+    const auto str = strprintf("%s:%s %s: Assertion `%s' failed.\n", file, line, func, assertion);
     fwrite(str.data(), 1, str.size(), stderr);
     std::abort();
 }
```
</p></details>

**Comment by jnewbery** [comment]
This appears to have introduced build warnings for me on master, when building with gcc 9:

```
./util/check.h: In instantiation of ‘T&& inline_assertion_check(T&&, const char*, int, const char*, const char*) [with bool IS_ASSERT = false; T = bool]’:
./validation.h:207:13:   required from here
./util/check.h:54:49: warning: parameter ‘file’ set but not used [-Wunused-but-set-parameter]
   54 | T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
      |                                     ~~~~~~~~~~~~^~~~
./util/check.h:54:59: warning: parameter ‘line’ set but not used [-Wunused-but-set-parameter]
   54 | T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
      |                                                       ~~~~^~~~
./util/check.h:54:77: warning: parameter ‘func’ set but not used [-Wunused-but-set-parameter]
   54 | T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
      |                                                                 ~~~~~~~~~~~~^~~~
./util/check.h:54:95: warning: parameter ‘assertion’ set but not used [-Wunused-but-set-parameter]
   54 | T&& inline_assertion_check(T&& val, const char* file, int line, const char* func, const char* assertion)
      |                                                                                   ~~~~~~~~~~~~^~~~~~~~~
  CXX      test/test_bitcoin-txrequest_tests.o
```

configure options:

```
Options used to compile and link:
  external signer = yes
  multiprocess    = no
  with experimental syscall sandbox support = yes
  with libs       = yes
  with wallet     = no
  with gui / qt   = yes
    with qr       = no
  with zmq        = yes
  with test       = yes
  with fuzz binary = yes
  with bench      = yes
  with upnp       = no
  with natpmp     = no
  use asm         = yes
  USDT tracing    = no
  sanitizers      = 
  debug enabled   = no
  gprof enabled   = no
  werror          = no
  LTO             = no

  target os       = linux-gnu
  build os        = linux-gnu

  CC              = /usr/bin/ccache gcc
  CFLAGS          = -pthread -g -O2
  CPPFLAGS        =  -fmacro-prefix-map=$(abs_top_srcdir)=.  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -DPROVIDE_FUZZ_MAIN_FUNCTION
  CXX             = /usr/bin/ccache g++ -std=c++17
  CXXFLAGS        =   -fdebug-prefix-map=$(abs_top_srcdir)=.  -fstack-reuse=none -Wstack-protector -fstack-protector-all -fcf-protection=full -fstack-clash-protection  -Wall -Wextra -Wformat -Wformat-security -Wvla -Wredundant-decls -Wdate-time -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Woverloaded-virtual -Wsuggest-override -Wimplicit-fallthrough  -Wno-unused-parameter -Wno-deprecated-copy   -g -O2 -fno-extended-identifiers
  LDFLAGS         =  -lpthread  -Wl,-z,relro -Wl,-z,now -Wl,-z,separate-code -pie  
  ARFLAGS         = cr
```

```
→ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
→ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Updating to gcc-10 removes the warnings.

**Comment by jnewbery** [comment]
I'd vote for the third (mark them used), with a comment that this is to workaround behaviour in gcc-9 and can be removed when the minimum gcc version is 10 or higher.

**Comment by ajtowns** [comment]
> This appears to have introduced build warnings for me on master, when building with gcc 9:

Looks like this is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81676 which wasn't fixed until gcc 10

**Comment by ajtowns** [comment]
Looks like another workaround might be to say `inline_assertion_check(T&& val, [[maybe_unused]] const char* file, [[maybe_unused]] int line, [[maybe_unused]] const char* func, [[maybe_unused]] const char* assertion)` -- https://en.cppreference.com/w/cpp/language/attributes/maybe_unused
