### PR TITLE
qt: test: Create at most one testing setup

### LINKED ISSUE #16288: tests: make check currently broken on macOS
```bash
git checkout master && git clean -fxd && ./autogen.sh && ./configure && make check -j8
.....
Running tests: torcontrol_tests from test/torcontrol_tests.cpp
Running tests: transaction_tests from test/transaction_tests.cpp
Running tests: txindex_tests from test/txindex_tests.cpp
../build-aux/test-driver: line 107: 85583 Abort trap: 6           "$@" > $log_file 2>&1
FAIL: qt/test/test_bitcoin-qt

cat src/test-suite.log 
==============================================
   Bitcoin Core 0.18.99: src/test-suite.log
==============================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: qt/test/test_bitcoin-qt
=============================

********* Start testing of AppTests *********
Config: Using QtTest library 5.12.3, Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.1 (clang-1001.0.46.4) (Apple))
PASS   : AppTests::initTestCase()
WARNING: AppTests::appTests() Skipping AppTests on mac build with 'minimal' platform set due to Qt bugs. To run AppTests, invoke with 'test_bitcoin-qt -platform cocoa' on mac, or else use a linux or windows build.
   Loc: [qt/test/apptests.cpp(61)]
PASS   : AppTests::appTests()
PASS   : AppTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 1ms
********* Finished testing of AppTests *********
********* Start testing of URITests *********
Config: Using QtTest library 5.12.3, Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.1 (clang-1001.0.46.4) (Apple))
PASS   : URITests::initTestCase()
PASS   : URITests::uriTests()
PASS   : URITests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of URITests *********
********* Start testing of RPCNestedTests *********
Config: Using QtTest library 5.12.3, Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 10.0.1 (clang-1001.0.46.4) (Apple))
PASS   : RPCNestedTests::initTestCase()
Assertion failed: (secp256k1_context_sign == nullptr), function ECC_Start, file key.cpp, line 349.
FAIL qt/test/test_bitcoin-qt (exit status: 134)
```

Looks like it's been failing since #16252, cc @MarcoFalke.

```bash
git checkout bc948d4cfd6da2effa8c2ae619e11e83207c6fbc && git clean -fxd && ./autogen.sh && ./configure && make check -j8
....
Running tests: db_tests from wallet/test/db_tests.cpp
PASS: qt/test/test_bitcoin-qt
Running tests: psbt_wallet_tests from wallet/test/psbt_wallet_tests.cpp
============================================================================
Testsuite summary for Bitcoin Core 0.18.99
============================================================================
# TOTAL: 1
# PASS:  1
```

### PR DESCRIPTION
**Pull request by maflcko**
It is assumed that ideally only one BasicTestingSetup exists at any point in time for each process (due to use of globals).

This assumption is violated in the GUI tests, as a testing setup is created as the first step of the `main` function and then (sometimes) another one for the following test cases.

So, the gui tests create two testing setups:
* `BasicTestingSetup` in `main` (added in fa4a04a5a942d582c62773d815c7e1e9897975d0)
* a testing setup for individual test cases

Avoid that by destructing the testing setup in main after creation and then move the explicit `ECC_Stop` to the only places where it is needed (before and after `apptests`).

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@fanquake @jonasschnelli pls test on macos

**Comment by Sjors** [comment]
fa3b441 works for me on macOS 10.14.5

**Comment by ryanofsky** [comment]
Why's this closed? It's confusing when a PR or issue is closed with no comment.

File: src/qt/test/rpcnestedtests.cpp [hunk 1]
```diff
@@ -34,9 +34,6 @@ void RPCNestedTests::rpcNestedTests()
     tableRPC.appendCommand("rpcNestedTest", &vRPCCommands[0]);
     //mempool.setSanityCheck(1.0);
 
-    ECC_Stop(); // Already started by the common test setup, so stop it to avoid interference
```
Comment (ryanofsky) [inline src/qt/test/rpcnestedtests.cpp]: In commit "qt: test: Create at most one testing setup" (fac5bb8f2e135090cc21bdde80ff2adc4c1a1401)

It seems better to keep these lines here than to move them to main with the comment "started by the AppTests later on". Why move code that is specific to apptests outside of apptests?

Similarly it seems like the BasicTestingSetup object in main could just be an apptests member if it's going to be destroyed as soon as apptests finish.

**Review by ryanofsky — APPROVED** [review]
utACK fac5bb8f2e135090cc21bdde80ff2adc4c1a1401

Change seems fine, but I'm also confused about why the issue #16288 was closed (also without comment). Does this PR not fix that issue? Or is a different fix for the issue better? Or is the issue not valid?

**Comment by MarcoFalke** [comment]
The comment was by github, it said:

>  MarcoFalke closed this in #16289 19 hours ago 

So the issue itself was already fixed with the linked pull request.

**Comment by Sjors** [comment]
#16289 was the easiest way to fix a broken master branch for macOS tests, but this PR seems like a more thorough long term solution. I don't entirely understand the original problem though.

**Comment by ryanofsky** [comment]
Thanks, I didn't understand the github comment. I also don't fully understand the original issue, or why BasicTestingSetup can't seem to clean up after itself, and seems to need additional ECC_Stop() / DisconnectTestLogger() calls.

File: src/qt/test/rpcnestedtests.cpp (hunk 1 above)
Comment (MarcoFalke) [reply src/qt/test/rpcnestedtests.cpp]: Fixed

**Comment by MarcoFalke** [comment]
> I also don't fully understand the original issue, or why BasicTestingSetup can't seem to clean up after itself

It does clean up after itself, but the assumption is that ideally only one BasicTestingSetup exists at any point in time for each process (due to use of globals).

We violate this assumption in the GUI tests, as a testing setup is created as the first step of the `main` function and then (sometimes) another one for the following test cases.

File: src/qt/test/apptests.cpp [hunk 2]
```diff
@@ -82,6 +83,8 @@ void AppTests::appTests()
     // Reset global state to avoid interfering with later tests.
     AbortShutdown();
     UnloadBlockIndex();
+    ECC_Stop();
```
Comment (ryanofsky) [inline src/qt/test/apptests.cpp]: In commit "qt: test: Create at most one testing setup" (999999bb11de41136b165e679b5828c4786a2f0f)

Why are ECC_Stop and DisconnectTestLogger needed here? Aren't they about to be called in the BasicTestingSetup destructor on the next line? It might be helpful to say something in a comment here, depending on the reason.

**Review by ryanofsky — APPROVED** [review]
utACK 999999bb11de41136b165e679b5828c4786a2f0f. It definitely seems good to have only have one
BasicTestingSetup active at a time.

File: src/qt/test/apptests.cpp (hunk 2 above)
Comment (MarcoFalke) [reply src/qt/test/apptests.cpp]: Removed

**Comment by laanwj** [comment]
> It definitely seems good to have only have one BasicTestingSetup active at a time.

would it make sense to enforce this with an assertion? we intentionally not trying to support this case, so crashing the tests with an assertion seems preferable to the unexpected problems that might happen otherwise

**Comment by MarcoFalke** [comment]
There sort of already is an assertion in `ECC_Start()`, which can not be called twice, unless there is a `ECC_Stop()` in between. The same is true for opening the debug log twice.

This was missed in the GUI tests because it was intentionally overwritten (by calling `ECC_Stop` and closing the debug log file)

**Comment by laanwj** [comment]
> This was missed in the GUI tests because it was intentionally overwritten (by calling ECC_Stop and closing the debug log file)

Whoops.

code review ACK faa1e0fb1712b1f94334e42794163f79988270fd
