### PR TITLE
p2p: Avoid InitError when downgrading peers.dat

### LINKED ISSUE #24188: Avoid InitError when downgrading peers.dat
See https://github.com/bitcoin/bitcoin/pull/22762#issuecomment-951063826

This can be fixed by creating a new exception type and catching it in the right place.

#### Useful skills:

* C++ exceptions
* Addrman serialization
* Functional tests

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by junderw**
fixes #24188 (also see https://github.com/bitcoin/bitcoin/pull/22762#issuecomment-951063826)
When downgrading, a peers.dat with a future version that has a minimum
required version larger than the downgraded Bitcoin Core version would cause an InitError.

This commit changes this behavior to overwrite the existing peers.dat with
a new empty one.

### CODE REVIEW

**Comment by junderw** [comment]
Part of the reason why I am using strncmp is because AddrMan (AddrManImpl) -> Unserialize might be called somewhere else, so I didn't want to touch it.

I should probably re-work AddrManImpl to use a new exception class that wraps around std::ios_base::failure and only throw exception in the case of version mismatch... but I wanted to get feedback first.

**Comment by MarcoFalke** [comment]
Yeah, I think it should be thrown directly where the version is read

**Comment by junderw** [comment]
Fixed.

Also, 2 jobs on the first commit's CI have been running for 10 hours... is this caused by my strncmp?

**Comment by junderw** [comment]
On second look, I wonder if we should also `LogPrintf` the `e.what()` right before we `LogPrintf` `"Creating new peers.dat..."`?

**Review by kallewoof — COMMENTED** [review]
ACK 96c9d9c7efa13128df74cebf8dda7d1e5db1f9c6

**Review by luke-jr — CHANGES_REQUESTED** [review]
IMO should be squashed

**Comment by junderw** [comment]
Squashed.

File: src/addrdb.cpp [hunk 1]
```diff
@@ -196,6 +196,11 @@ std::optional<bilingual_str> LoadAddrman(const std::vector<bool>& asmap, const A
         addrman = std::make_unique<AddrMan>(asmap, /* deterministic */ false, /* consistency_check_ratio */ check_addrman);
         LogPrintf("Creating peers.dat because the file was not found (%s)\n", fs::quoted(fs::PathToString(path_addr)));
         DumpPeerAddresses(args, *addrman);
+    } catch (const InvalidAddrManVersionError&) {
+        // Addrman can be in an inconsistent state after failure, reset it
+        addrman = std::make_unique<AddrMan>(asmap, /* deterministic */ false, /* consistency_check_ratio */ check_addrman);
+        LogPrintf("Creating new peers.dat because the file version was not compatible (%s)\n", fs::quoted(fs::PathToString(path_addr)));
+        DumpPeerAddresses(args, *addrman);
```
Comment (luke-jr) [inline src/addrdb.cpp:203]: Would be nice to deduplicate the common code here somehow.

Maybe just a single common catch of std::exception, with `if(DbNotFoundError) else if (InvalidAddrManVersionError) else return` then the common re-init logic?

File: src/addrdb.cpp [hunk 2]
```diff
@@ -196,6 +196,11 @@ std::optional<bilingual_str> LoadAddrman(const std::vector<bool>& asmap, const A
         addrman = std::make_unique<AddrMan>(asmap, /* deterministic */ false, /* consistency_check_ratio */ check_addrman);
         LogPrintf("Creating peers.dat because the file was not found (%s)\n", fs::quoted(fs::PathToString(path_addr)));
         DumpPeerAddresses(args, *addrman);
+    } catch (const InvalidAddrManVersionError&) {
+        // Addrman can be in an inconsistent state after failure, reset it
+        addrman = std::make_unique<AddrMan>(asmap, /* deterministic */ false, /* consistency_check_ratio */ check_addrman);
+        LogPrintf("Creating new peers.dat because the file version was not compatible (%s)\n", fs::quoted(fs::PathToString(path_addr)));
```
Comment (luke-jr) [inline src/addrdb.cpp:202]: I wonder if the old file should be backed up first.

**Review by luke-jr — APPROVED** [review]
utACK, w/ some thoughts for improvement (can be followups)

File: src/addrdb.cpp (hunk 2 above)
Comment (junderw) [reply src/addrdb.cpp:202]: I am not sure if that would be useful. Anyone who cares about which peers they connect to is probably managing a conf file filled with add peer directives.

File: src/addrdb.cpp (hunk 1 above)
Comment (junderw) [reply src/addrdb.cpp:203]: 👍 I will do a follow up once this is merged.

File: src/addrdb.cpp (hunk 2 above)
Comment (prayank23) [reply src/addrdb.cpp:202]: Agree with _luke-jr_

Comment (junderw) [reply src/addrdb.cpp:202]: I just saw your issue on knots.

I will make a backup at `peers.dat.bak`.

Comment (junderw) [reply src/addrdb.cpp]: The behavior has changed to back up to .bak file. Please let me know what you think of the commit before I squash it.

File: src/addrdb.cpp [hunk 3]
```diff
@@ -197,9 +197,12 @@ std::optional<bilingual_str> LoadAddrman(const std::vector<bool>& asmap, const A
         LogPrintf("Creating peers.dat because the file was not found (%s)\n", fs::quoted(fs::PathToString(path_addr)));
         DumpPeerAddresses(args, *addrman);
     } catch (const InvalidAddrManVersionError&) {
+        if (!RenameOver(path_addr, (fs::path)path_addr + ".bak")) {
+            throw std::exception();
```
Comment (kallewoof) [inline src/addrdb.cpp:201]:
```C++
throw std::runtime_error{"Failed to rename invalid peer.dat file. Please move or delete it try again."};
```

Comment (junderw) [reply src/addrdb.cpp:201]: Doesn't this error get caught by the catch below (which catches exception)?

Comment (kallewoof) [reply src/addrdb.cpp:201]: Ah yeah didn't realize this was caught later, I thought you just hard-crashed. Either way, you do want it to be caught and handled below, but the wording here is a bit redundant. Maybe just "Failed to move invalid peer.dat file aside."?

Comment (junderw) [reply src/addrdb.cpp]: Actually, it looks like throwing here bypasses the later catch.

Comment (junderw) [reply src/addrdb.cpp]: Maybe I should refactor the other comment from Luke to make things cleaner.

File: test/functional/feature_addrman.py [hunk 4]
```diff
@@ -68,17 +68,16 @@ def run_test(self):
             self.start_node(0, extra_args=["-checkaddrman=1"])
         assert_equal(self.nodes[0].getnodeaddresses(), [])
 
-        self.log.info("Check that addrman from future cannot be read")
+        self.log.info("Check that addrman from future is overwritten with new addrman")
         self.stop_node(0)
         write_addrman(peers_dat, lowest_compatible=111)
```
Comment (prayank23) [inline test/functional/feature_addrman.py:73]: Is it possible to do this using some hidden RPC?

Comment (junderw) [reply test/functional/feature_addrman.py:73]: Nope. This is a python function that literally just writes a dummy (but valid) peers.dat file to disk.

File: src/addrdb.cpp [hunk 5]
```diff
@@ -196,6 +196,15 @@ std::optional<bilingual_str> LoadAddrman(const std::vector<bool>& asmap, const A
         addrman = std::make_unique<AddrMan>(asmap, /* deterministic */ false, /* consistency_check_ratio */ check_addrman);
         LogPrintf("Creating peers.dat because the file was not found (%s)\n", fs::quoted(fs::PathToString(path_addr)));
         DumpPeerAddresses(args, *addrman);
+    } catch (const InvalidAddrManVersionError&) {
+        if (!RenameOver(path_addr, (fs::path)path_addr + ".bak")) {
+            addrman = nullptr;
+            return strprintf(_("Failed to rename invalid peer.dat file. Please move or delete it and try again."));
```
Comment (luke-jr) [inline src/addrdb.cpp:202]: peer`s`.dat

**Comment by MarcoFalke** [comment]
Assigned 23.0

**Comment by michaelfolkson** [comment]
@junderw: Can you explain why you made this WIP? One of multiple considerations for whether it should be included in the 23.0 milestone or not.

**Comment by junderw** [comment]
@michaelfolkson I made this PR primarily to help contribute with an issue that I found on the issue tracker that I thought would be fairly straightforward and maybe save someone at least a few minutes of dev time.

It was also an issue that I agreed with. @MarcoFalke and @sipa had recommended that a downgrade of peers.dat should not result in a crash, and I thought that was reasonable.

1. I wanted to contribute back to the project I benefit greatly from.
2. The issue was straightforward.
3. I agreed with the consensus at the time between the two people who put forward the issue.

Thanks.

**Comment by junderw** [comment]
Sorry, I misunderstood. I made it WIP because I thought I still hadn't finished all the outstanding issues with the PR.

After reviewing my own commit I understand I was just confused.

There's a spelling error I'll fix right now.

**Review by ghost — APPROVED** [review]
tACK https://github.com/bitcoin/bitcoin/pull/24201/commits/772c9ba8ccfa7247042be10771cca3c8de7e8568

nit: 

1. Not sure about squashing of some commits or the order and type
2. Suggestion by @luke-jr still not addressed to change `peer` to `peers`

**Comment by junderw** [comment]
Unrelated test failed for some reason.

**Comment by prayank23** [comment]
> Unrelated test failed for some reason.

I don't think that's an issue 

Maybe you can follow 1 or 2 or both:

1. Squash commits according to [docs](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits)
2. Have 2 commits:
    ```
    1st commit: net (src/addrman.h , src/addrman.cpp and src/addrdb.cpp)
    ```
    ```
    2nd commit: test (test/functional/feature_addrman.py)
    ```

**Comment by junderw** [comment]
Squashed all commits into one.

**Review by ghost — APPROVED** [review]
reACK https://github.com/bitcoin/bitcoin/pull/24201/commits/d41ed3215355582879c8eb6c99c2da33852f6cb1

**Review by kallewoof — COMMENTED** [review]
reACK d41ed3215355582879c8eb6c99c2da33852f6cb1

**Comment by michaelfolkson** [comment]
Sorry for the confusion @junderw :) Great to see this has been merged. Thanks!
