### PR TITLE
wallet: Automatically add receiving destinations to the address book

### LINKED ISSUE #19856: Some transactions are not shown in listtransactions output
I have two bitcoin core full nodes. I have one wallet.dat file on both nodes. One node is a master and second node is a reserve. Master signs and sends transactions. Reserve node only receives updates from network. I create new addresses on the master node only and the reserve node derives the same addresses.

I don’t use any other commands on the reserve node. The reserve node creates addresses automatically after receiving a transaction to a new address. This process is possible due to using BIP32 key derivation from one master key.

So, I have constantly synchronized master and reserve nodes. If there are problems with the master, then I switch to the reserve.

I see some strange behavior appear during this process. Some transactions are not shown in the `listtransactions` output. I did a research an found that only "in-wallet" transactions are not shown in the `listransactions`. The "in-wallet" transactions are transactions that were sent with sender’s and receiver’s keys, which are stored in my wallet. I also found that new addresses on the reserve node are created whithout a label.

After adding a label to the address the problem is gone. But adding a label requires additional steps I want to avoid.

**Expected Behavior**

Results of `listtransactions` also shown "in-wallet" transactions to addresses without labels

**Current Behavior**

Results of `listtransactions` doesn’t shown "in-wallet" transactions to addresses without labels

**Possible Solution**

- Automatic adding of a default label to the addresses, derived to the reserve node.

- Print transactions sent to addresses without labels in `listtransactions`.

**Steps to Reproduce**

1.  Run and sync full nodes A and B.

2.  Stop nodes A and B.

3.  Copy wallet.dat from node A to node B.

4.  Run nodes A and B

5.  Use `getnewaddress` method on node A 10 times. Let’s assume the 10-th address is `$ADDRESS`.

6.  Use `sendtoaddress` method on node A. Send 0.001 coins from another address to the `$ADDRESS`. `bitcoin-cli sendtoaddress $ADDRESS 0.001`. Let’s assume the result txid is `$TXID`.

7.  Use `listtransaction "*"` method on node B. You don’t see the `$TXID` transaction in list.

8.  Use `gettransactions`, or `listunspent` methods on node B. You can see the transaction details. Wallet balance changed on node B and is equal to node A.

9.  Use `getaddressinfo $ADDRESS` method on node A. You can see that address had the default label (`""`).

10. Use `getaddressinfo $ADDRESS` method on node B. You can see that the address doesn’t have any label.

**Context (Environment)**

The problem is occured on any version of bitcoin core testnet and mainnet. The problem is also occured on litecoin and any bitcoin-based coins.

### LINKED ISSUE #20293: The listtransactions command does not display transactions when restoring a wallet from a backup
In March, I made a backup of the wallet and continued using the node. In October, I restored my old backup. After restoring the backup, I found that the listtransactions command stopped displaying some transactions made during the period from March to October.

**Expected behavior**

The listtransactions command displays all transactions in the restored wallet.

**Actual behavior**

The listtransactions command in the restored wallet does not display some transactions since the backup.

**To reproduce**

1. Run bitcoin core in regtest mode
2. Create a new address A and generate 101 blocks with sending a reward to the created address A
3. Create a wallet backup
4. Create new address B
5. Send transaction to address B, write TXID
6. Generate 1 block with sending a reward to address A
7. View getaddressinfo B. Verify labels are not an empty list
8. View listtransactions. Make sure there is a TXID transaction present
9. Stop bitcoin core
10. Restore backup
11. Run bitcoin core
12. View getaddressinfo B and listtransactions. Detect that the address does not have a label set and that listtransactions does not contain a TXID transaction.

**System information**

Bitcoin Core 0.20.1 on Debian GNU / Linux.

### PR DESCRIPTION
**Pull request by S3RK**
This PR fixes certain use-cases when **send-to-self** transactions are missing from `listtransactions` output.

1. When a receiving address is generated externally to the wallet
(e.g. same wallet running on two nodes, or by 3rd party from xpub)
2. When restoring backup with lost metadata, but keypool gap is not exceeded yet

When the block is connected or tx added to mempool we already mark used keys. This PR extends this logic to determine whether the destination is a receiving one and if yes add it to the address book with empty label.

Works both for legacy and descriptors wallets.
- For legacy it uses the internal flag from the keypool entry. Caveat: because we don't know which script type would be used we add all possible destinations for such keys.
- For descriptor wallets it uses internal flag for the script pub key manager. Caveat: it only works for active descriptors.

fixes #19856
fixes #20293

### CODE REVIEW

File: src/wallet/scriptpubkeyman.h [hunk 1]
```diff
@@ -481,9 +493,13 @@ class LegacyScriptPubKeyMan : public ScriptPubKeyMan, public FillableSigningProv
     void LearnAllRelatedScripts(const CPubKey& key);
 
     /**
-     * Marks all keys in the keypool up to and including reserve_key as used.
+     * Marks all keys in the keypool up to and including the provided key as used.
+     *
+     * @param keypool_id determines the last key to makr as used
```
Comment (achow101) [inline src/wallet/scriptpubkeyman.h:498]: In fec5ded232ca37b8a965ce09a3940ccb6ce43249 "Return used destinations from ScriptPubKeyMan::MarkUnusedAddresses"

typo: makr - > mark

```suggestion
     * @param keypool_id determines the last key to mark as used
```

File: src/wallet/scriptpubkeyman.cpp [hunk 2]
```diff
@@ -354,15 +354,22 @@ bool LegacyScriptPubKeyMan::TopUpInactiveHDChain(const CKeyID seed_id, int64_t i
...
+    std::vector<WalletDestination> result;
     // extract addresses and check if they match with an unused keypool key
     for (const auto& keyid : GetAffectedKeys(script, *this)) {
         std::map<CKeyID, int64_t>::const_iterator mi = m_pool_key_to_index.find(keyid);
         if (mi != m_pool_key_to_index.end()) {
             WalletLogPrintf("%s: Detected a used keypool key, mark all keypool keys up to this key as used\n", __func__);
-            MarkReserveKeysAsUsed(mi->second);
+            for (const auto& keypool : MarkReserveKeysAsUsed(mi->second)) {
+                // derive all possible destinations as any of them could have been used
+                for (const auto& type: LEGACY_OUTPUT_TYPES) {
```
Comment (achow101) [inline src/wallet/scriptpubkeyman.cpp:368]: In fec5ded232ca37b8a965ce09a3940ccb6ce43249 "Return used destinations from ScriptPubKeyMan::MarkUnusedAddresses"

nit: space before `:`

```suggestion
                for (const auto& type : LEGACY_OUTPUT_TYPES) {
```

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -1059,7 +1059,19 @@ bool CWallet::AddToWalletIfInvolvingMe(const CTransactionRef& ptx, CWalletTx::Co
...
+                for (auto& dest : spk_man->MarkUnusedAddresses(txout.scriptPubKey)) {
+                    // If internal flag is not defined try to infer it from the ScriptPubKeyMan
+                    if (!dest.internal.has_value()) {
+                        dest.internal = IsInternalScriptPubKeyMan(spk_man);
+                    }
+
+                    // If this is a receiving address and it's not in the address book yet
+                    // (e.g. it wasn't generated on this node or we're restoring from backup)
+                    // add it to the address book for proper transaction accounting
+                    if (!dest.internal.value_or(true) && !FindAddressBookEntry(dest.dest, /* allow_change= */ false)) {
```
Comment (achow101) [inline src/wallet/wallet.cpp:1073]: In cbb90fbc00e345100587cd47926c6c7fc5487628 "Automatically add labels to detected receiving addresses"

Shouldn't we be marking everything that doesn't have `dest.internal` as a receiving address? i.e.

```suggestion
                   if (!dest.internal.value_or(false) && !FindAddressBookEntry(dest.dest, /* allow_change= */ false)) {
```

File: src/wallet/scriptpubkeyman.h (hunk 1 above)
Comment (S3RK) [reply src/wallet/scriptpubkeyman.h]: Done

File: src/wallet/scriptpubkeyman.cpp (hunk 2 above)
Comment (S3RK) [reply src/wallet/scriptpubkeyman.cpp]: Done

File: src/wallet/wallet.cpp (hunk 3 above)
Comment (S3RK) [reply src/wallet/wallet.cpp]: I want to be conservative and skip if we can't determine if that's an change or receiving destination. But the code is not obvious and I restructured it to make it explicit.

**Comment by achow101** [comment]
ACK c97c2a99bf5aed073cc28967c5d47a33ec618752

**Review by dgs2019 — APPROVED** [review]

File: src/wallet/scriptpubkeyman.cpp [hunk 4]
```diff
@@ -1820,19 +1833,32 @@ bool DescriptorScriptPubKeyMan::TopUp(unsigned int size)
...
+    std::vector<WalletDestination> result;
     if (IsMine(script)) {
         int32_t index = m_map_script_pub_keys[script];
         if (index >= m_wallet_descriptor.next_index) {
             WalletLogPrintf("%s: Detected a used keypool item at index %d, mark all keypool items up to this item as used\n", __func__, index);
-            m_wallet_descriptor.next_index = index + 1;
+            auto out_keys = std::make_unique<FlatSigningProvider>();
+            std::vector<CScript> scripts_temp;
+            while (index >= m_wallet_descriptor.next_index) {
+                if (!m_wallet_descriptor.descriptor->ExpandFromCache(m_wallet_descriptor.next_index, m_wallet_descriptor.cache, scripts_temp, *out_keys)) {
```
Comment (S3RK) [inline src/wallet/scriptpubkeyman.cpp:1847]: @achow101 I believe expanding from cache is enough here. But want to confirm.

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -1062,8 +1064,23 @@ bool CWallet::AddToWalletIfInvolvingMe(const CTransactionRef& ptx, CWalletTx::Co
 
             // loop though all outputs
             for (const CTxOut& txout: tx.vout) {
-                for (const auto& spk_man_pair : m_spk_managers) {
-                    spk_man_pair.second->MarkUnusedAddresses(txout.scriptPubKey);
+                const auto& spk_man = GetScriptPubKeyMan(txout.scriptPubKey);
```
Comment (S3RK) [inline src/wallet/wallet.cpp:1067]: @achow101 I think it's technically possible to have two descriptors producing same scriptPubKey. Wdyt?

Comment (achow101) [reply src/wallet/wallet.cpp:1067]: Ah, that is indeed possible. In that case, we should keep this loop.

File: src/wallet/wallet.cpp [hunk 6]
```diff
@@ -3276,6 +3276,29 @@ DescriptorScriptPubKeyMan* CWallet::GetDescriptorScriptPubKeyMan(const WalletDes
...
+
+    const auto desc_spk_man = dynamic_cast<DescriptorScriptPubKeyMan*>(spk_man);
+    if (!desc_spk_man) {
+        throw std::runtime_error(std::string(__func__) + ": unexpected ScriptPubKeyMan type.");
+    }
+
+    LOCK(desc_spk_man->cs_desc_man);
+    const auto& type = desc_spk_man->GetWalletDescriptor().descriptor->GetOutputType();
+
+    return GetScriptPubKeyMan(*type, /* internal= */ true) == desc_spk_man;
```
Comment (meshcollider) [inline src/wallet/wallet.cpp:3316]: Should check `if (type)` or `has_value()` to ensure it has a value before calling `*type`

File: src/wallet/scriptpubkeyman.cpp [hunk 7]
```diff
@@ -1448,7 +1458,10 @@ void LegacyScriptPubKeyMan::MarkReserveKeysAsUsed(int64_t keypool_id)
         batch.ErasePool(index);
         WalletLogPrintf("keypool index %d removed\n", index);
         it = setKeyPool->erase(it);
+        result.push_back(keypool);
```
Comment (meshcollider) [inline src/wallet/scriptpubkeyman.cpp:1461]: I think this is better as `std::move(keypool)`?

File: test/functional/wallet_listtransactions.py [hunk 8]
```diff
@@ -210,5 +214,63 @@ def get_unconfirmed_utxo_entry(node, txid_to_match):
...
+        self.connect_nodes(0, 1)
+        self.connect_nodes(1, 2)
+        self.connect_nodes(2, 0)
+
+        addr1 = self.nodes[0].getnewaddress("pizza1", 'legacy')
+        addr2 = self.nodes[0].getnewaddress("pizza2", 'p2sh-segwit')
+        addr3 = self.nodes[0].getnewaddress("pizza3", 'bech32')
+
+        self.log.info("Send to externally generated addresses")
+        # send to N+2 address to test the keypool gap
```
Comment (meshcollider) [inline test/functional/wallet_listtransactions.py:238]: What does `N+2` mean here (and below)?
(I understand based on the code that `N` is meant to be the "first" key that node[0] and therefore also node[2] generates but the comment is confusing).

**Review by meshcollider — COMMENTED** [review]
Concept ACK

File: src/wallet/wallet.cpp (hunk 5 above)
Comment (S3RK) [reply src/wallet/wallet.cpp]: Returned the cycle and removed `GetScriptPubKeyMan` function to avoid such mistakes in the future

File: src/wallet/wallet.cpp (hunk 6 above)
Comment (S3RK) [reply src/wallet/wallet.cpp:3306]: Active descriptors always have `type` defined, added assertion

File: src/wallet/scriptpubkeyman.cpp (hunk 7 above)
Comment (S3RK) [reply src/wallet/scriptpubkeyman.cpp]: Done

File: test/functional/wallet_listtransactions.py (hunk 8 above)
Comment (S3RK) [reply test/functional/wallet_listtransactions.py]: Yes. I updated the comments

**Comment by laanwj** [comment]
Code review ACK 3d71d16d1eb4173c70d4c294559fc2365e189856

**Comment by luke-jr** [comment]
This breaks "walletconflicts"

Note: My `bugfix_rpc_getbalance_hacky` branch tests this by accident.

**Comment by S3RK** [comment]
@luke-jr I'm not sure what exactly is the broken scenario, happy to debug or write a test for it. It seems to me that `CWallet::GetLegacyBalance` in `bugfix_rpc_getbalance_hacky` branch makes an incorrect assumption that incoming txs will be in `mapTxSpends`. But `mapTxSpends` contains only spends

**Comment by luke-jr** [comment]
>I'm not sure what exactly is the broken scenario, happy to debug or write a test for it. 

"walletconflicts" no longer returns other transactions that conflict with the transaction.

This is an issue in master, not just my branch. I only mentioned my branch because it's how I found it.

>But mapTxSpends contains only spends

IIRC, it's not supposed to only be spends from this wallet, but also spends *to* this wallet.

I'm not sure if that's why "walletconflicts" is broken now, or not (though the comment for mapTxSpends suggests it may be)

**Comment by achow101** [comment]
@luke-jr Does reverting d04566415e16ae685af066384f346dff522c068f fix your issue?

**Comment by luke-jr** [comment]
>@luke-jr Does reverting d045664 fix your issue?

Right, sorry I wasn't specific on which commit.

**Comment by S3RK** [comment]
Created #24083 with a revert
