### PR TITLE
[gui] Defer coin control instancing

### LINKED ISSUE #12312: QT ignores -changetype=bech32 when coin control features are enabled
Steps to reproduce:

1. put `changetype=bech32` in bitcoin.conf or launch QT with `-changetype=bech32`
2. send money to any legacy address
3. use `decoderawtransaction` to see that the change address is `bech32`, as expected since #12119

4. enable Coin Control in settings menu
5. send money to any legacy address
6. use `decoderawtransaction` to see that the change address is now `p2sh-segwit`

### PR DESCRIPTION
**Pull request by promag**
Defer the GUI coin control instancing so that argument processing
is taken into account for the default coin control values.

Fixes #12312

### CODE REVIEW

**Comment by promag** [comment]
Note to reviewers, I would like to refactor the code, specially to remove there (or some) static values, but I though maybe we should fix the problem first.

**Comment by instagibbs** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/12327/commits/b3e74d626e6c2109492f490a4c8271b4b0bd52c2

This should fix both `g_change_type;` and `signalRbf` being set at instance time to variables not yet set globally. Other settings are set per-usage of `CCoinControl` or are simply not used when not explicitly set, such as `m_feerate`.

**Comment by laanwj** [comment]
> Note to reviewers, I would like to refactor the code, specially to remove there (or some) static values, 

Yes, we should get rid of the global coincontrol object and just pass it around and store it where necessary. But indeed, not a priority for fixing this.

File: src/qt/coincontroldialog.cpp [hunk 1]
```diff
@@ -600,6 +599,13 @@ void CoinControlDialog::updateLabels(WalletModel *model, QDialog* dialog)
         label->setVisible(nChange < 0);
 }
 
+CCoinControl* CoinControlDialog::coinControl()
+{
+    static CCoinControl* coin_control = nullptr;
+    if (!coin_control) coin_control = new CCoinControl();
```
Comment (laanwj) [inline src/qt/coincontroldialog.cpp]: I think we leak this pointer?

File: src/qt/coincontroldialog.cpp [hunk 2]
```diff
@@ -379,11 +378,11 @@ void CoinControlDialog::viewItemChanged(QTreeWidgetItem* item, int column)
         COutPoint outpt(uint256S(item->text(COLUMN_TXHASH).toStdString()), item->text(COLUMN_VOUT_INDEX).toUInt());
 
         if (item->checkState(COLUMN_CHECKBOX) == Qt::Unchecked)
-            coinControl->UnSelect(outpt);
+            CoinControlDialog::coinControl()->UnSelect(outpt);
```
Comment (laanwj) [inline src/qt/coincontroldialog.cpp]: No need to prefix with  `CoinControlDialog::` here, this is still in the class.

File: src/qt/coincontroldialog.cpp (hunk 1 above)
Comment (promag) [reply src/qt/coincontroldialog.cpp]: It was leaking already.

File: src/qt/coincontroldialog.cpp (hunk 2 above)
Comment (promag) [reply src/qt/coincontroldialog.cpp]: I know, but this way it's clear it's a static member.

Comment (laanwj) [reply src/qt/coincontroldialog.cpp]: Let's not do that, we intend to make it non-static field later anyway, so this seems moving the wrong direction.

File: src/qt/coincontroldialog.cpp (hunk 1 above)
Comment (laanwj) [reply src/qt/coincontroldialog.cpp]: But wouldn't that be a one-line change, to use `static unique_ptr<CCoinControl> coin_control;`? Or am I missing something?

**Comment by promag** [comment]
Pushed a commit with @laanwj suggestion if others want to suggest other way.

**Comment by laanwj** [comment]
I think ideally we'd instantiate the CCoinControl at a defined time during the GUI initialization process, instead at first use. But this works I guess...

File: src/qt/coincontroldialog.cpp (hunk 1 above)
Comment (kekimusmaximus) [reply src/qt/coincontroldialog.cpp]: Do a Meyer's singleton

`
CCoinControl& CoinControlDialog::coinControl()
{
    static CCoinControl coin_control;
    return coin_control;
}
`

No pointers, no leaks.

Comment (promag) [reply src/qt/coincontroldialog.cpp]: In that case when is coin_control instanced? I think the problem remains, but please correct me if I'm wrong.

Comment (promag) [reply src/qt/coincontroldialog.cpp]: For now, pushed with `std::unique_ptr` as suggested by @laanwj.

Comment (laanwj) [reply src/qt/coincontroldialog.cpp]: Thanks!

I think @kekimusmaximus's solution also works, static within a function is initialized on first use.

Comment (promag) [reply src/qt/coincontroldialog.cpp]: That's new to me, I'll change to that instead.

**Comment by MeshCollider** [comment]
utACK after squash

**Comment by jonasschnelli** [comment]
utACK 29e7f9f7a2afa6836fbbe7371000805dfb8ec638 , please squash.

**Comment by promag** [comment]
Done @jonasschnelli @MeshCollider.

**Comment by Sjors** [comment]
Tested. Enabling coin control now honors `-changetype` for me, and also uses a native segwit change address when sending to a bech32 address.
