### PR TITLE
Avoid ugly exception in log on unknown inv type

### LINKED ISSUE #9110: CInv::GetCommand(): type=1373179482 unknown type
It seems that bitcoin{d,-qt} can be crashed by being sent an inv of an unknown type. At least, it caused mine to:-

```
2016-11-08 00:45:36.470 ProcessMessages(getdata, 397 bytes): CHECKSUM ERROR expected=6d9dbcdf was=a1046737 peer=39585
2016-11-08 00:45:36.481 

************************
EXCEPTION: St12out_of_range       
CInv::GetCommand(): type=1373179482 unknown type       
bitcoin in ProcessMessages()       

2016-11-08 00:45:36.482 ProcessMessages(getdata, 397 bytes) FAILED peer=39585
2016-11-08 00:45:36.487 

************************
EXCEPTION: St12out_of_range       
CInv::GetCommand(): type=1373179482 unknown type       
bitcoin in msghand       

```

If the `throw std::out_of_range(strprintf("CInv::GetCommand(): type=%d unknown type", type));` in protocol.cpp supposed to cause the program to end?

### PR DESCRIPTION
**Pull request by laanwj**
It is unexpected behavior for `ToString` to raise an exception. It is expected to do a best-effort attempt at formatting but never fail.

Catch the exception and simply print unknown inv types as hexadecimal.

Before:
```
************************
EXCEPTION: St12out_of_range       
CInv::GetCommand(): type=666 unknown type       
bitcoin in ProcessMessages()       
```

After:
```
2016-11-09 10:08:20 got inv: 0x0000029a 0000000000000000000000000000000000000000000000000000000000000000  have peer=1
```

Fixes #9110.

### CODE REVIEW

File: src/protocol.cpp [hunk 1]
```diff
@@ -181,7 +181,11 @@ std::string CInv::GetCommand() const
 
 std::string CInv::ToString() const
 {
-    return strprintf("%s %s", GetCommand(), hash.ToString());
+    try {
+        return strprintf("%s %s", GetCommand(), hash.ToString());
+    } catch(const std::out_of_range &) {
+        return strprintf("0x%08x %s", type, hash.ToString());
```
Comment (rebroad) [inline src/protocol.cpp]: perfect

**Comment by paveljanik** [comment]
I'd prefer `try` first and then one final line with `return`, ie. one exit route even if this is very simple.

**Comment by laanwj** [comment]
Can we just decide to merge this (or not) instead of bombarding a two-line
logging only change to death with bikeshedding?

**Comment by paveljanik** [comment]
NACK I prefer the other solution #9113. No need to throw an exception at all. It also fixes the problem for other callers.

**Comment by laanwj** [comment]
Fucking damnit do we really need two pulls for this non issue

**Comment by theuni** [comment]
utACK e9f25ddd0063f7ea65595178d04370d27344305c. Safer to fix it at the site of the problem for now.

**Comment by fanquake** [comment]
utACK e9f25dd
