### PR TITLE
rpc: document RPC_TRANSACTION_ALREADY_IN_CHAIN exception

### LINKED ISSUE #5638: RPC_TRANSACTION_ALREADY_IN_CHAIN exception race condition in sendrawtransaction
I discovered a race condition in sendrawtransaction. For details: see my comment in https://github.com/bitcoin/bitcoin/commit/1d46fe3327f6645fd79b442cd72ef422418c1a50.

If you send a raw transaction which has already been broadcasted, then you don't know whether you'll receive an RPC_TRANSACTION_ALREADY_IN_CHAIN exception, since you don't know whether a new block has just been received, which includes the transaction. There are use cases where such RPC_TRANSACTION_ALREADY_IN_CHAIN occurrences do not indicate an error; however, since this type of occurrence is very rare, developers are not likely to be aware of the possibility, and silence the exception. As a result, applications can potentially experience hard-to-diagnose, very rare errors.

I think the core of the problem is that sendrawtransaction tries to combine two use cases:
A: publish a transaction on the Bitcoin network
B: re-transmit an already known transaction to peers
RPC_TRANSACTION_ALREADY_IN_CHAIN might make sense for B, but for A (which is, IMHO, the primary use case) it is confusing.

### PR DESCRIPTION
**Pull request by jarolrod**
It is not documented in the `RPCHelpMan` of `sendrawtransaction` that if you attempt to send a transaction which already exists in a block, an `RPC_TRANSACTION_ALREADY_IN_CHAIN` exception will be raised. It is best to make developers aware of this so that it can be properly caught and avoid any headaches.

Closes #5638

### CODE REVIEW

File: src/rpc/rawtransaction.cpp [hunk 1]
```diff
@@ -819,7 +819,9 @@ static RPCHelpMan sendrawtransaction()
                 "\nNote that the transaction will be sent unconditionally to all peers, so using this\n"
                 "for manual rebroadcast may degrade privacy by leaking the transaction's origin, as\n"
                 "nodes will normally not rebroadcast non-wallet transactions already in their mempool.\n"
-                "\nAlso see createrawtransaction and signrawtransactionwithkey calls.\n",
+                "\nAlso see createrawtransaction and signrawtransactionwithkey calls.\n"
+                "\nNOTE: an RPC_TRANSACTION_ALREADY_IN_CHAIN exception will be raised if you are\n"
+                "attempting to send a transaction that already exists in a block.\n",
```
Comment (jonatack) [inline src/rpc/rawtransaction.cpp:824]: suggestion to improve, tighten this up, and remove  "Note that" and "NOTE:"
```diff
+++ b/src/rpc/rawtransaction.cpp
@@ -816,12 +816,11 @@ static RPCHelpMan sendrawtransaction()
 {
     return RPCHelpMan{"sendrawtransaction",
                 "\nSubmit a raw transaction (serialized, hex-encoded) to local node and network.\n"
-                "\nNote that the transaction will be sent unconditionally to all peers, so using this\n"
+                "\nThe transaction will be sent unconditionally to all peers, so using sendrawtransaction\n"
                 "for manual rebroadcast may degrade privacy by leaking the transaction's origin, as\n"
                 "nodes will normally not rebroadcast non-wallet transactions already in their mempool.\n"
-                "\nAlso see createrawtransaction and signrawtransactionwithkey calls.\n"
-                "\nNOTE: an RPC_TRANSACTION_ALREADY_IN_CHAIN exception will be raised if you are\n"
-                "attempting to send a transaction that already exists in a block.\n",
+                "\nRPC_TRANSACTION_ALREADY_IN_CHAIN will be raised if the transaction already exists in a block.\n"
+                "\nRelated RPCs: createrawtransaction, signrawtransactionwithkey\n",
```

Comment (jonatack) [reply src/rpc/rawtransaction.cpp:824]: which would change the help from
```
Submit a raw transaction (serialized, hex-encoded) to local node and network.

Note that the transaction will be sent unconditionally to all peers, so using this
for manual rebroadcast may degrade privacy by leaking the transaction's origin, as
nodes will normally not rebroadcast non-wallet transactions already in their mempool.

Also see createrawtransaction and signrawtransactionwithkey calls.

NOTE: an RPC_TRANSACTION_ALREADY_IN_CHAIN exception will be raised if you are
attempting to send a transaction that already exists in a block.
```
to
```
Submit a raw transaction (serialized, hex-encoded) to local node and network.

The transaction will be sent unconditionally to all peers, so using sendrawtransaction
for manual rebroadcast may degrade privacy by leaking the transaction's origin, as
nodes will normally not rebroadcast non-wallet transactions already in their mempool.

RPC_TRANSACTION_ALREADY_IN_CHAIN will be raised if the transaction already exists in a block.

Related RPCs: createrawtransaction, signrawtransactionwithkey
```

**Review by jonatack — COMMENTED** [review]
Concept ACK

I agree with https://github.com/bitcoin/bitcoin/issues/5638#issuecomment-69590222 that returning a `{'in_chain': bool, 'in_mempool': bool, 'tx_hash': hash}` structure would be better but this step doesn't hurt and while touching this we can improve the help.

**Comment by jarolrod** [comment]
updated fa614af69ac72b5250d3408e4c56f083f3ab6254 -> 35bc72a1bcc6c7bb7618803490fc7957d070dc02

Implemented @jonatack suggestions

File: src/rpc/rawtransaction.cpp (hunk 1 above)
Comment (jarolrod) [reply src/rpc/rawtransaction.cpp]: Thanks, this is much better :)

File: src/rpc/rawtransaction.cpp [hunk 2]
```diff
@@ -816,10 +816,11 @@ static RPCHelpMan sendrawtransaction()
 {
     return RPCHelpMan{"sendrawtransaction",
                 "\nSubmit a raw transaction (serialized, hex-encoded) to local node and network.\n"
-                "\nNote that the transaction will be sent unconditionally to all peers, so using this\n"
+                "\nThe transaction will be sent unconditionally to all peers, so using sendrawtransaction\n"
                 "for manual rebroadcast may degrade privacy by leaking the transaction's origin, as\n"
                 "nodes will normally not rebroadcast non-wallet transactions already in their mempool.\n"
-                "\nAlso see createrawtransaction and signrawtransactionwithkey calls.\n",
+                "\nRPC_TRANSACTION_ALREADY_IN_CHAIN will be raised if the transaction already exists in a block\n"
```
Comment (MarcoFalke) [inline src/rpc/rawtransaction.cpp:822]: This makes it sound like the only exception that can be thrown

Comment (jarolrod) [reply src/rpc/rawtransaction.cpp:822]: We can either document every exception that can be thrown or revert back to specifying that this is a note.
```suggestion
                "\nNOTE: an RPC_TRANSACTION_ALREADY_IN_CHAIN will be raised if the transaction already exists in a block\n"
```

Comment (jonatack) [reply src/rpc/rawtransaction.cpp:822]: I would avoid both adding note this/note that (IIRC I added the first note but have since seen review feedback to avoid needless "note: "s, which I agree with) and listing all the exceptions. Is there a concrete suggestion how this change can be improved?

Comment (MarcoFalke) [reply src/rpc/rawtransaction.cpp:822]: "This may throw if the transaction couldn't be added to the mempool"

Comment (jarolrod) [reply src/rpc/rawtransaction.cpp:822]: > "This may throw if the transaction couldn't be added to the mempool"

That still sounds like it's the only exception which may be thrown. It also sounds like it's the only reason that a transaction fails to enter the mempool.

**Review by felipsoarez — COMMENTED** [review]
NACK, as i understand it, it is an unnecessary note, as discussed earlier, to avoid unnecessary notes.

File: src/rpc/rawtransaction.cpp (hunk 2 above)
Comment (jonatack) [reply src/rpc/rawtransaction.cpp:822]: As-is seems more explicit but I don't have a strong opinion regarding it versus Marco's suggestion (thanks for the proposal!) I think they are both an improvement and don't see the implication that this the only exception.￼￼

**Comment by jarolrod** [comment]
> NACK, as i understand it, it is an unnecessary note, as discussed earlier, to avoid unnecessary notes.

See: #5638

Yes, it would be more useful to change the code so that the function returns a `{'in_chain': bool, 'in_mempool': bool, 'tx_hash': hash} structure`, but an [argument](https://github.com/bitcoin/bitcoin/issues/5638#issuecomment-69590222) is made against that. It's worthwhile to evaluate if this is still the case, but outside the scope of this PR.

This PR implements the proposed [solution](https://github.com/bitcoin/bitcoin/issues/5638#issuecomment-69616004) of documenting the exception so that developers don't find themselves frustrated by this and don't have to resort to looking to the source code.

**Comment by jonatack** [comment]
Yes, I did not mean to suggest that adding helpful documentation was a bad idea.

File: src/rpc/rawtransaction.cpp (hunk 2 above)
Comment (jonatack) [inline src/rpc/rawtransaction.cpp:822]:
```suggestion
                "\nRPC_TRANSACTION_ALREADY_IN_CHAIN will be raised if the transaction already exists in a block.\n"
```

**Comment by jonatack** [comment]
ACK modulo missing full stop line 822 (and/or taking Marco's suggestion, no strong opinion from me on that)

File: src/rpc/rawtransaction.cpp (hunk 2 above)
Comment (jonatack) [reply src/rpc/rawtransaction.cpp:822]: Maybe 

```
A specific exception, RPC_TRANSACTION_ALREADY_IN_CHAIN, will be raised if the transaction cannot be added to the mempool.
```

Comment (jonatack) [reply src/rpc/rawtransaction.cpp:822]: Maybe:

```
This will throw a specific exception, RPC_TRANSACTION_ALREADY_IN_CHAIN, if the transaction cannot be added to the mempool.
```

**Comment by jarolrod** [comment]
updated  35bc72a ->  74d23bf

Addressed the issue of wording around the exception by combining both suggestions from @jonatack and @MarcoFalke

File: src/rpc/rawtransaction.cpp (hunk 2 above)
Comment (jarolrod) [reply src/rpc/rawtransaction.cpp]: addressed in  74d23bf

Comment (jarolrod) [reply src/rpc/rawtransaction.cpp]: addressed in  74d23bf

**Review by jonatack — COMMENTED** [review]
ACK 74d23bf7fbb6169ec658c36af57cd1f937823d9c

**Comment by MarcoFalke** [comment]
I'd still prefer to document exceptions/return codes/error values better, but that might be a task to solve for all RPCs
