### PR TITLE
sign: don't assume we are parsing a sane TapMiniscript

### LINKED ISSUE #29851: fuzz, rpc: Internal bug in `finalizepsbt` "CHECK_NONFATAL(last - first == 32)"
```
$ echo "ZmluYWxpemVwc2J0XABwc2J0/wEAo6ujYwMDAwMDmAAAANUABQAAY2xlYXJiDAAAAAAAAABgAPX///8A6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACTAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAwoDAwMDAwMDAwMDAwAK8wEDAHFkAAAAAAAAAAAAZQAAAAAAAAAAANzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3NzcAAAAAD8/Pz8/Pz8/Pz8/Pz8/P0Y/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz89Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/Pz8/AAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAB3YWlwb2ZicmxvY2sDAwMD/fz8/AAK8wEDAHFkAAB+f39/o6Ojo6OjAgMDAwMDAAD/////AAAADg4ODg4OMDAwMDAnMDAwMDEzNDYwODkwNTUxMzA3NzYwDg5TU1NTSgMAJlNTU1NTU1NTU1MODg4ODg4ODgAODg4ODg4OAAAAIhUCAgICAhEREWNQDg4AAA4AAAoOMDEzNDYwODkwNTUxMzA3NzYwMDYODg4ODg5uZXR3b3JrY2xlYXJiYW5uZWQODg4Oog4ODg4ODg4ODgUAAAAKDg4ODgAAAKIVAgsLCwAAAAAAAAAA/////wAAAI4ODg4ODg4ODg4OAAAAAAAAAGAAAAAIAAAAAGRlc2NymXB0b3JfamFyc2UAAAAAAAAAAIAAAAAAAQAAAAAAAAADCgMDAwMDAwMDAwMDAArzAQMAYGT/AAAAAAAAAABlAAAAAAAAAAAA3Nzc3Nzc3Nz/AAQA3NzcycnJycLCwsLCwsLCwsLCwsLCwjw9PT09Fz02yMnJyf///////wIAAAAAAh4eNzc3ITYYGBgYGBgeHh4eGQAAAAAAAAAAALGSkpKSkpJrAGybm5KSwHhpbWF0ZS1tZW1vcnkA/////////wMAAAAAAAAAAGAAAAAAAAAAAAAACQAAQAAAAAAAAAAAAAAAAJDNAAAAAAAAAAAAAAAAAAsAYAAAAAAAAAAAZGVzY3KZcHRvcl9qx4cBAQEBKwL/ZABlcAAAMQ4ODg45OTMyDg4ODg4ODg4OIAAAAA4ODg4Oog4ODg4ODvsNDg4ODgABAQEBKwL/ZABlcAAAIlEgAwMcHBwDAwAL8wEDJnBmAQAAAAAAAAAAAAAAAAAAgAAtNzMmKiUAAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAhwEBAQFjJGFiZmZhSWFhDg42Dg4OCg5dDg4ODgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgYGCgnGBgYGBgYGBgYA4ODjUODg4ODlsOAASlOsDbuSYODg4AAAABFyAAsQAADg4ODg4ODusOAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPomByEAAAH+//8AAAABAn4UAAAAAImJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJ/4lByon68P//AAIAAwAwAQg4MDM1MA4ODg4ODg1PT09PT09PT09PT09PT08ODg4OAAAAAAAAMAAAAAoAAAIAAABQUFBQUFBQUDQ5OZ45OXk5Uzn/dTAwMDAwJzAwMDAxMzQ2MDg5MDU1AwOsA/38/DEzMDc3NjAwNg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg6iDg4ODg4ODg4ODgAODg4ODg4OAAAAohUCCwsL1gAAAAAAAAD/////AAAADg4ODg4OMDAwMDAnMDAwMDEzNDYwODkwNTWJfzA3NzYwMDYODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OogIADg4ODg4ODg4ADg4O1dXV1dXV1dXVZVxnXGdlZRUVFWVcZztcZ2UVZTAxMzQ2MDg5MDI3NTY1Mzg4MDAzDg4ODg4ODjA4OTA1NTEzMDc3NugDNw4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg6iDg4ODg4ODg4ODgAODg4ODg4OAAAAIm8CAgICAhEREWNQDg4AAA4AAAoOAnYnYnYnYnYwNTUxMzA3NzYwMDcODg4ODg4ODg4ODg4ODg58C9Qy5q1ATA4ODg4ODg7tDQ4ODg6iDg4ODg4ODg4ODgAODg4ODg4OAAAAohUCCwsLAAAAAAAAAAD/////AAAADg4ODg4ODg4ODg6JiYmJiYmJiYmJiYmJiYmJiYmJiYmJif+JQcqJ+vD//wACAE4AAAAIODAzNTAODg4ODg4ODg4ODg4ODg4Oog4ODg4ODg4ODgAAAAAAADAAAAAKAAACAAAAUFBQUFBQUFA0OTmeOTmNOVM5/3UwMDAwMCcwMDAwMTM0NjA4OTA1NDEzMDc3NjAwNg4ODg4ODg4ODg40NDI4Dg4ODg4ODp0OuRPusldPDg4ODg4ODg4ODgAODg7/Dg4OAAAiIhU5njk5eTlTOf91MDAwMDAn//8AADEzNDYwODkwNTUxMzA3NzYwMDYODg4ODg4ODg4ODg4ODg4ODg4ODg4yDg4ODg4ODqIOADA4MDM1MQ4ODg4ODg4ODg4ODg4ODg6iDg4ODg4AAAEAAAAAAAAAAAAAAAAAAAAAAAAAAIeHh4eHh4eHh8DAv8CvAAAAAAAAAAAAAAAAAAAAAAILMDAnMDAwMDEABwEOJ9+pGDUxHh4eHh4eHh4eHjMwNzc2MDA2Dg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODqIODg4ODg4ODg4OAA4ODg4ODg4AADAwy8vLy9PLy8vLy8t+y8vLy8vLy8vLy8vLDg5ycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycg4ODg4OBg4ODv9cbP+JdGmhiX+JiYlgAPYAAAAAAGxByon68P90/2kDMTMkiYmJicqJ+g==" | base64 --decode > rpc-36c31074f1f8e97885c2957d0b327b2e7f334cbc.crash
$ FUZZ=rpc ./src/test/fuzz/fuzz rpc-36c31074f1f8e97885c2957d0b327b2e7f334cbc.crash
fuzz_libfuzzer: test/fuzz/rpc.cpp:385: void rpc_fuzz_target(FuzzBufferType): Assertion `error_msg.find("trigger_internal_bug") != std::string::npos' failed.
```

### PR DESCRIPTION
**Pull request by darosior**
The script provided for signature might be externally provided, for instance by way of 'finalizepsbt'. Therefore the script might be ill-crafted, so don't assume pubkeys are always 32 bytes.

Thanks to Niklas for finding this.

FIxes https://github.com/bitcoin/bitcoin/issues/29851.

### CODE REVIEW

**Review by dergoegge — APPROVED** [review]
utACK bdf2ef2c94cae2b0e2cdac1866322b4f9f7c7a7b

File: src/test/script_tests.cpp [hunk 1]
```diff
@@ -1254,6 +1254,30 @@ BOOST_AUTO_TEST_CASE(script_combineSigs)
...
+    TaprootBuilder builder;
+    builder.Add(0, {invalid_pubkey}, 0xc0);
+    XOnlyPubKey nums{ParseHex("50929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0")};
+    builder.Finalize(nums);
+    prev.vout.emplace_back(0, GetScriptForDestination(builder.GetOutput()));
+    curr.vin.emplace_back(COutPoint{prev.GetHash(), 0});
+    sig_data.tr_spenddata = builder.GetSpendData();
+
+    // SignSignature can fail but it shouldn't raise an exception (nor crash).
+    SignSignature(keystore, CTransaction(prev), curr, 0, SIGHASH_ALL, sig_data);
```
Comment (achow101) [inline src/test/script_tests.cpp:1278]: I think it would be good to check that `SignSignature` fails here:

```suggestion
    BOOST_CHECK(!SignSignature(keystore, CTransaction(prev), curr, 0, SIGHASH_ALL, sig_data));
```

Comment (darosior) [reply src/test/script_tests.cpp]: I think it emphases the wrong thing: we are not testing it's failing, we are testing it's not crashing. That's why i didn't do it. Anyways it's not really important and there is already a comment highlighting this. Done.

**Comment by achow101** [comment]
ACK 4d8d21320eba54571ff63931509cd515c3e20339

**Review by furszy — COMMENTED** [review]
ACK 4d8d21320eba54571ff63931509cd515c3e20339 with a small nuance that could be tackled in a follow-up by someone else (or never).

As this was found by the RPC fuzzer, it would be nice to re-use those inputs and craft a functional test, rather than covering it on a unit test. This is because functional tests can be ported across releases with the bug fix, while unit tests might not be easy to port due to some internal changes. Plus, in the long term, unit tests require more maintenance work.

**Comment by fanquake** [comment]
Backported to 27.x in #29888.

**Comment by glozow** [comment]
backported to 26.x in #29899
