### PR TITLE
wallet: detecting duplicate wallet by comparing the db filename.

### LINKED ISSUE #14538: loadwallet command crashes bitcoind
`bitcoin-cli loadwallet "wallet.dat"` command causes bitcoind crash

log info:
```
bitcoind: wallet/db.cpp:236: BerkeleyEnvironment::VerifyResult BerkeleyEnvironment::Verify(const string&, BerkeleyEnvironment::recoverFunc_type, std::__cxx11::string&): Assertion `mapFileUseCount.count(strFile) == 0' failed.
Aborted (core dumped)
```

Bitcoin Core Daemon version `v0.17.0.0-ge1ed37edaedc85b8c3468bd9a726046344036243`

### PR DESCRIPTION
**Pull request by ken2812221**
Fix #14538

Fix crash attempting to load the same wallet with different path strings that resolve to the same absolute path. The primary check which prevents loading the same wallet twice is:

https://github.com/bitcoin/bitcoin/blob/6b8d0a2164b30eab76e7bccb1ffb056a10fba406/src/wallet/db.cpp#L44

But this check is skipped if both wallet paths resolve to the same absolute path, due to caching here:

https://github.com/bitcoin/bitcoin/blob/6b8d0a2164b30eab76e7bccb1ffb056a10fba406/src/wallet/db.cpp#L467

Meanwhile a secondary check for duplicate wallets is not reliable because it based on a literal comparison, instead of comparison using absolute paths:

https://github.com/bitcoin/bitcoin/blob/6b8d0a2164b30eab76e7bccb1ffb056a10fba406/src/wallet/wallet.cpp#L3853

This PR fixes the latter check to compare the absolute path of a new wallet being loaded to absolute paths of wallets already loaded, so there should no longer be any way to load the same wallet more than once.

### CODE REVIEW

**Comment by ryanofsky** [comment]
Would prefer to check this at database level, rather than in higher level wallet code. I think it's better if high level code just passes along wallet paths and isn't concerned with how data is stored in them.

I posted a tweaked version of this PR at 40a6475e59950838be532b0a2c58f4359eae5625 which moves the check. @ken2812221, could you incorporate 40a6475e59950838be532b0a2c58f4359eae5625 into this PR if you think it makes sense?

**Comment by ken2812221** [comment]
@ryanofsky The element in mapDb can be loaded lazily. 
For example: If it is a new wallet or the other wallet in same directory just unloaded, the element in mapDb dies not exist.
So the only vector that store the wallets we load is `vpwallets`.

**Comment by ryanofsky** [comment]
> @ryanofsky The element in mapDb is not always exist.

Good catch. I think a small refactoring could fix this: 9c945d011abde24f8649d877e694d392e1a5727e. And then the fix would change slightly to aef19be5851ceb3b324fd80756060a00aad8e61c.

I pushed a branch with these two commits to: https://github.com/ryanofsky/bitcoin/commits/pr/bloaded

I think this is a better than checking for wallet.dat files outside the database layer, but let me know what you think, and feel free to use the code or commits in this PR if you think this approach makes sense.

**Review by ryanofsky — APPROVED** [review]
utACK aef19be5851ceb3b324fd80756060a00aad8e61c

**Review by ryanofsky — APPROVED** [review]
utACK b0375538375eb0c419b308d1015723ab64d53294. Only change since last review is rebase.

@promag, this might be an easy PR for to you review. First commit is just refactoring that doesn't change behavior. Second commit is the actual fix.

@ken2812221, it might help for this to have a more complete PR description.

---

Suggested PR description:

Fix crash attempting to load the same wallet with different path strings that resolve to the same absolute path. The primary check which prevents loading the same wallet twice is:

https://github.com/bitcoin/bitcoin/blob/6b8d0a2164b30eab76e7bccb1ffb056a10fba406/src/wallet/db.cpp#L44

But this check is skipped if both wallet paths resolve to the same absolute path, due to caching here:

https://github.com/bitcoin/bitcoin/blob/6b8d0a2164b30eab76e7bccb1ffb056a10fba406/src/wallet/db.cpp#L467

Meanwhile a secondary check for duplicate wallets is not reliable because it based on a literal comparison, instead of comparison using absolute paths:

https://github.com/bitcoin/bitcoin/blob/6b8d0a2164b30eab76e7bccb1ffb056a10fba406/src/wallet/wallet.cpp#L3853

This PR fixes the latter check to compare the absolute path of a new wallet being loaded to absolute paths of wallets already loaded, so there should no longer be any way to load the same wallet more than once.

File: src/wallet/db.cpp [hunk 1]
```diff
@@ -463,7 +463,8 @@ BerkeleyBatch::BerkeleyBatch(BerkeleyDatabase& database, const char* pszMode, bo
         if (!env->Open(false /* retry */))
             throw std::runtime_error("BerkeleyBatch: Failed to open database environment.");
 
-        pdb = env->mapDb[strFilename];
+        BerkeleyDatabase& database = env->m_databases.at(strFilename).get();
```
Comment (promag) [inline src/wallet/db.cpp]: Some comments here:
 - there's a slight change when replacing `map::operator[]` with `map::at`, maybe worth a comemnt or an assertion?
 - also, isn't this equivalent to the above `database` argument?
 - is this is really necessary then you could avoid shadowing `database`.

File: src/wallet/db.h [hunk 2]
```diff
@@ -115,13 +117,22 @@ class BerkeleyDatabase
...
+        auto inserted = env->m_databases.emplace(strFile, std::ref(*this));
+        assert(inserted.second);
         if (mock) {
             env->Close();
             env->Reset();
             env->MakeMock();
         }
     }
 
+    ~BerkeleyDatabase() {
```
Comment (promag) [inline src/wallet/db.h]: nit, could add `final` to class since this is not virtual.

**Comment by ken2812221** [comment]
@ryanofsky Thanks for your review. I would take your suggestion.

File: src/wallet/db.cpp [hunk 3]
```diff
@@ -56,9 +56,8 @@ bool WalletDatabaseFileId::operator==(const WalletDatabaseFileId& rhs) const
     return memcmp(value, &rhs.value, sizeof(value)) == 0;
 }
 
-BerkeleyEnvironment* GetWalletEnv(const fs::path& wallet_path, std::string& database_filename)
+void SplitWalletPath(const fs::path& wallet_path, fs::path& env_directory, std::string& database_filename)
```
Comment (promag) [inline src/wallet/db.cpp]: Could be `static`?

File: src/wallet/db.cpp (hunk 1 above)
Comment (ryanofsky) [reply src/wallet/db.cpp]: re: https://github.com/bitcoin/bitcoin/pull/14552#discussion_r230800120

Oh, I didn't even realize there was a `database` argument being shadowed above. Should just delete this line and use the existing `database`, which points to the same thing.

File: src/wallet/db.cpp [hunk 4]
```diff
@@ -563,12 +581,11 @@ void BerkeleyEnvironment::CloseDb(const std::string& strFile)
 {
     {
         LOCK(cs_db);
-        if (mapDb[strFile] != nullptr) {
+        BerkeleyDatabase& database = m_databases.at(strFile).get();
```
Comment (promag) [inline src/wallet/db.cpp]: Same as above, there's a slight change when replacing map::operator[] with map::at, maybe worth a comment or an assertion?

File: src/wallet/db.h (hunk 2 above)
Comment (ken2812221) [reply src/wallet/db.h]: `final` can only be added to virtual method.

Comment (promag) [reply src/wallet/db.h]: @ken2812221 I mean `class BerkeleyDatabase final`.

Comment (ryanofsky) [reply src/wallet/db.h]: Change would be unrelated to this PR, and IMO, it's better only to use final when you have virtual methods and actual optimizations this would allow or bugs it would prevent. There's a core guideline that touches on this: http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-final

Comment (promag) [reply src/wallet/db.h]: Nice thanks.

**Comment by promag** [comment]
utACK 15c93f0.

File: src/wallet/db.cpp [hunk 5]
```diff
@@ -71,6 +70,24 @@ BerkeleyEnvironment* GetWalletEnv(const fs::path& wallet_path, std::string& data
...
+
+bool IsWalletLoaded(const fs::path& wallet_path)
+{
+    fs::path env_directory;
+    std::string database_filename;
+    SplitWalletPath(wallet_path, env_directory, database_filename);
+    LOCK(cs_db);
+    auto env = g_dbenvs.find(env_directory.string());
+    if (env == g_dbenvs.end()) return false;
+    auto db = env->second.m_databases.find(database_filename);
```
Comment (laanwj) [inline src/wallet/db.cpp]: I think this is leaking the implementation detail of `m_databases`, wouldn't checking whether a database exists ideally be a responsibility of the database environment. e.g. add a `IsDatabaseLoaded` on `DBenv`?

Comment (promag) [reply src/wallet/db.cpp]: Note that `BerkeleyEnvironment::mapDb` is currently used outside. I consider this a bugfix so any improvement/refactor could come next.

**Comment by ryanofsky** [comment]
utACK 591203149f1700f594f781862e88cbbfe83d8d37. Just minor tweaks since last review: replacing map::at exception with assert, adding IsDatabaseLoaded.

@promag and @MarcoFalke, I've noticed that in your recent reviews you've been advocating replacing exceptions with asserts or return codes. Maybe one of you can write up some guidelines about when to use exceptions in the developer guide. Personally, I tend to like exceptions and think that whatever drawbacks they have will be fixed by new c++ features like `throws`/`std::error` in 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0709r0.pdf (see §4.1.1 "Elevator Pitch")

File: src/wallet/db.cpp (hunk 5 above)
Comment (ryanofsky) [reply src/wallet/db.cpp]: Resolved by adding `IsDatabaseLoaded`

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/14552/commits/591203149f1700f594f781862e88cbbfe83d8d37, looks good

**Comment by ryanofsky** [comment]
Can this be merged? It fixes an ugly bug and has some refactoring changes I want to build on. If it can't be merged, maybe it could be added to https://github.com/bitcoin/bitcoin/projects/8

**Comment by MarcoFalke** [comment]
Is this for backport?

File: src/wallet/db.h [hunk 6]
```diff
@@ -43,7 +45,7 @@ class BerkeleyEnvironment
 public:
     std::unique_ptr<DbEnv> dbenv;
     std::map<std::string, int> mapFileUseCount;
-    std::map<std::string, Db*> mapDb;
+    std::map<std::string, std::reference_wrapper<BerkeleyDatabase>> m_databases;
```
Comment (promag) [inline src/wallet/db.h]: Shouldn't this be guarded by `cs_db`?
