### PR TITLE
bug-fix macos: give free bytes to F_PREALLOCATE

### LINKED ISSUE #17827: Blocks directory on macOS uses more disk space than expected
It seems the Initial Block Download (IBD) on macOS Catalina uses a lot more disk space than expected, and will result in an unsuccesful download even when 480 GB of free disk space is available at the beginning. 

**Expected behavior**

That the Initial Block Download finishes after using _about_ 284 GB of disk space, as indicated by the Welcome window.

ibd-480-GB-available-at-least-284-GB-required

**Actual behavior**

When the download reaches 52% completion, over 284 GB of disk space has already been consumed. If the download is left to run, the machine will run out of disk space and Bitcoin Core will stop/quit before completing the download.

Looking a bit into the Bitcoin directory and what could be causing it, the files prefixed _rev_ in the _blocks_ folder are a lot larger than they are when compared to a previous blockchain downloaded on Linux.

Comparing the rev*.dat files with a previous successful IBD on Linux (below mounted with ext4fuse), the rev files use at most 23M, and the total is 32G:
```
blocks # pwd
/Users/erik/linux-ext4/bitcoin/.bitcoin/blocks

blocks # du -ch rev*.dat | sort -n
6.0M	rev01866.dat
 12M	rev00311.dat
 12M	rev00328.dat
 13M	rev00314.dat
 14M	rev00295.dat
 14M	rev00309.dat
 ...
 21M	rev01206.dat
 21M	rev01291.dat
 23M	rev01036.dat
 32G	total
```

On Mac, the rev files will be significantly larger than 23M. You can see that the files can get as large as 184M, and in this case where 22.8% of the blockchain had been downloaded, we were already using 48G for just the rev files, 107G for the whole data directory.
```
$ tail -n 1 /Users/erik/Library/Application\ Support/Bitcoin/debug.log
2019-12-29T07:30:29Z UpdateTip: new best=0000000000000000025930ce69bc9fcfae882de7231457f09534da493e114c52 height=399555 version=0x00000004 log2_work=84.162383 tx=111703322 date='2016-02-22T08:57:07Z' progress=0.228149 cache=466.9MiB(3406855txo)

$ du -ch /Users/erik/Library/Application\ Support/Bitcoin/blocks/rev*.dat | sort -n
 16M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00003.dat
 17M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00056.dat
 18M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00006.dat
 20M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00000.dat
 21M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00450.dat
 24M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00078.dat
 27M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00002.dat
 ...
171M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00232.dat
172M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00266.dat
172M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00334.dat
174M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00256.dat
175M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00143.dat
175M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00275.dat
177M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00132.dat
177M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00204.dat
178M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00337.dat
184M	/Users/erik/Library/Application Support/Bitcoin/blocks/rev00208.dat
 48G	total

$ du -ch /Users/erik/Library/Application\ Support/Bitcoin
 91M	/Users/erik/Library/Application Support/Bitcoin/blocks/index
105G	/Users/erik/Library/Application Support/Bitcoin/blocks
1.8G	/Users/erik/Library/Application Support/Bitcoin/chainstate
2.0M	/Users/erik/Library/Application Support/Bitcoin/wallets
107G	/Users/erik/Library/Application Support/Bitcoin
107G	total
```

Here you can see the Linux-Mac diff side by side:
linux-vs-mac

**To reproduce**

- Download and install Bitcoin Core 0.19.0.1 on a Mac with a fresh install of macOS Catalina 10.15.2
- Start Bitcoin Core and select the default data directory and leave the prune checkbox unchecked (see picture at the start of the report)
- After downloading ~55% of the blockchain, check the disk space use of the ~/Library/Application Support/Bitcoin folder, it should now already exceed 284 GB
- If you had 480 GB of free space when starting the download, you should not be able to finish the download before running out of disk space

**Possible workaround**

Based on https://bitcoin.stackexchange.com/questions/11104/what-is-the-database-for/11108#11108 it seems the rev*.dat files can be removed to free up disk space. By deleting the earlier ones created I was able to free up enough space continue and complete the IBD on the Mac mini. However, doing so may lead to side effects that I am unaware of.

**System information**

bitcoin-0.19.0.1-osx.dmg downloaded from https://bitcoin.org/en/download 

Machine 1:
- Mac mini (Late 2012)
- 2,5 GHz Dual-Core Intel Core i5
- 16 GB 1600 MHz DDR3
- macOS Catalina 10.15.2 (fresh install on a 500 GB SSD)

Machine 2: 
- MacBook Pro (15-inch, 2018) 
- 2,6 GHz 6-Core Intel Core i7
- 32 GB 2400 MHz DDR4
- macOS Catalina 10.15.2 (upgraded from Mojave)

### PR DESCRIPTION
**Pull request by kallewoof**
The macos manpage for `fcntl` (for `F_PEOFPOSMODE`) states:

> Allocate from the physical end of file.  In this case, fst_length indicates the number of newly allocated bytes desired.

This would result in the rev files being essentially pre-allocating 2x their necessary size (this is the case for block files as well, but these are flushed down to their right sizes every time) as they would pre-allocate `pos + length` **free** bytes, rather than allocating `length` bytes after `pos`, as expected.

Fixes #17827.

### CODE REVIEW

**Comment by sipa** [comment]
So this code has been wrong for 7 years? Why do we only notice the effect now?

**Comment by fanquake** [comment]
> So this code has been wrong for 7 years? Why do we only notice the effect now?

It’s likely this issue only started occurring with the introduction of APFS, which is quite recent.

**Comment by kallewoof** [comment]
@sipa I suspect the OS eventually reclaims pre-allocated space, but it seems block files are not suffering from this kind of issue, so I'm honestly not sure. The docs clearly indicate we were using it wrong, though.

**Comment by kallewoof** [comment]
On my machine (APFS encrypted volume), I was seeing rev00002.dat hitting 20 MB around block 135k. After this patch (currently at block 151k) I see
```Bash
$ du -ch *.dat
128M	blk00000.dat
128M	blk00001.dat
128M	blk00002.dat
128M	blk00003.dat
128M	blk00004.dat
 96M	blk00005.dat
 20M	rev00000.dat
 17M	rev00001.dat
 17M	rev00002.dat
 17M	rev00003.dat
 17M	rev00004.dat
 10M	rev00005.dat
834M	total
```

**Comment by kallewoof** [comment]
Looking closely at the run on master, the files are blowing up 2x in size until they are no longer used, at which point they are truncated to the correct size. This applies to blk files as well.

Running on this PR, the 2x blowup is not occurring for either files, but the resulting file sizes are, as noted above, the same.

So I don't see the permanent growth that is reported in the issue...

Running macos 10.14.6 (Mojave). User is running Catalina, so perhaps I would see the problem if I upgraded.

**Comment by kallewoof** [comment]
Enlightening read: https://www.mail-archive.com/filesystem-dev@lists.apple.com/msg00226.html

**Comment by IPGlider** [comment]
Tested on MacOS 10.15.2 on an APFS volume and the problem disappears. Also tested on a mounted HFS+ disk volume and the problem disappears.

**Comment by fanquake** [comment]
Concept ACK

**Comment by eriknylund** [comment]
I ran this on machine 2 in the issue report and can confirm that there is no blowup.

- MacBook Pro (15-inch, 2018)
- 2,6 GHz 6-Core Intel Core i7
- 32 GB 2400 MHz DDR4
- macOS Catalina 10.15.2 (upgraded from Mojave)

Tested on an APFS unencrypted disk image with 3 GB in size and let it run until the image was full:
```
$ ./bitcoind -datadir=/Volumes/APFS
2020-01-09T19:43:17Z UpdateTip: 
new best=000000000000059cfb1620756c7a88b679dfcbedc1d3c255dbc0f09481f8021b
height=191055 version=0x00000001 log2_work=68.451374 tx=5349799 
date='2012-07-27T17:15:53Z' progress=0.010844 cache=292.8MiB(2160691txo)
2020-01-09T19:43:19Z *** Disk space is too low!

$ cd /Volumes/APFS/blocks/

$ du -ch *.dat
128M	blk00000.dat
128M	blk00001.dat
128M	blk00002.dat
128M	blk00003.dat
128M	blk00004.dat
128M	blk00005.dat
128M	blk00006.dat
128M	blk00007.dat
128M	blk00008.dat
128M	blk00009.dat
128M	blk00010.dat
128M	blk00011.dat
128M	blk00012.dat
128M	blk00013.dat
128M	blk00014.dat
128M	blk00015.dat
128M	blk00016.dat
 48M	blk00017.dat
 20M	rev00000.dat
 17M	rev00001.dat
 16M	rev00002.dat
 17M	rev00003.dat
 18M	rev00004.dat
 18M	rev00005.dat
 19M	rev00006.dat
 18M	rev00007.dat
 19M	rev00008.dat
 18M	rev00009.dat
 19M	rev00010.dat
 18M	rev00011.dat
 18M	rev00012.dat
 18M	rev00013.dat
 19M	rev00014.dat
 18M	rev00015.dat
 19M	rev00016.dat
5.0M	rev00017.dat
2.5G	total
```

Tested on a Mac OS Extended (HFS+) unencrypted disk image with 3 GB in size:
```
$ ./bitcoind -datadir=/Volumes/HFS+/
2020-01-09T20:13:51Z UpdateTip: 
new best=00000000000004e055fbb153a6371891f7dc52adbe525b3a5cf3b9413fde7551 
height=189775 version=0x00000001 log2_work=68.414219 tx=5084658 
date='2012-07-19T07:39:48Z' progress=0.010306 cache=285.6MiB(2101977txo)
2020-01-09T20:13:51Z Error: Disk space is too low!

$ cd /Volumes/HFS+/blocks/

$ du -ch *.dat
128M	blk00000.dat
128M	blk00001.dat
128M	blk00002.dat
128M	blk00003.dat
128M	blk00004.dat
128M	blk00005.dat
128M	blk00006.dat
128M	blk00007.dat
128M	blk00008.dat
128M	blk00009.dat
128M	blk00010.dat
128M	blk00011.dat
128M	blk00012.dat
128M	blk00013.dat
128M	blk00014.dat
128M	blk00015.dat
 64M	blk00016.dat
 19M	rev00000.dat
 17M	rev00001.dat
 16M	rev00002.dat
 16M	rev00003.dat
 17M	rev00004.dat
 17M	rev00005.dat
 18M	rev00006.dat
 18M	rev00007.dat
 18M	rev00008.dat
 18M	rev00009.dat
 18M	rev00010.dat
 18M	rev00011.dat
 18M	rev00012.dat
 18M	rev00013.dat
 18M	rev00014.dat
 18M	rev00015.dat
8.0M	rev00016.dat
2.3G	total
```

**Comment by eriknylund** [comment]
I also built a Bitcoin-Qt.dmg and started a fresh download on machine 1 in the issue report, to verify that I can successfully complete the initial block download on the Mac mini with 480 GB of free disk space at the start. ETA 3 days.

**Comment by fanquake** [comment]
I've just finished a from scratch sync using this PR + 17892, on an macOS (APFS) machine. Data directory is the expected size. No longer seeing very large rev*.dat files, most are between 16 and 21mb.

**Comment by eriknylund** [comment]
> I also built a Bitcoin-Qt.dmg and started a fresh download on machine 1 in the issue report, to verify that I can successfully complete the initial block download on the Mac mini with 480 GB of free disk space at the start. ETA 3 days.

> I've just finished a from scratch sync using this PR + 17892, on an macOS (APFS) machine. Data directory is the expected size. No longer seeing very large rev*.dat files, most are between 16 and 21mb.

The IBD is now complete and the estimate is spot on. 280 GB of disk space is used.
```
Bitcoin % pwd
/Users/erik/Library/Application Support/Bitcoin

Bitcoin % du -h .
 92M	./blocks/index
276G	./blocks
3.7G	./chainstate
2.0M	./wallets/database
4.0M	./wallets
280G	.

Bitcoin % tail debug.log
2020-01-12T17:17:44Z UpdateTip: 
new best=000000000000000000141d63c0a927235c7e21b39f8c632f9b7e70a9f3fb1659 
height=612543 version=0x3fffe000 log2_work=91.544872 tx=492581053 
date='2020-01-12T17:17:13Z' progress=1.000000 cache=259.8MiB(1712729txo) 
warning='71 of last 100 blocks have unexpected version'
```

**Comment by eriknylund** [comment]
Looking a bit more into the rev files I see what is most likely the truncation issue @kallewoof discovered in https://github.com/bitcoin/bitcoin/issues/17890
```
Bitcoin % du -h blocks/rev00337.dat blocks/rev01037.dat blocks/rev01036.dat
 23M	blocks/rev00337.dat
 24M	blocks/rev01037.dat
 27M	blocks/rev01036.dat
Bitcoin % ls -lh blocks/rev00337.dat blocks/rev01037.dat blocks/rev01036.dat
-rw-------  1 erik  staff    21M Jan 10 10:46 blocks/rev00337.dat
-rw-------  1 erik  staff    23M Jan 11 12:56 blocks/rev01036.dat
-rw-------  1 erik  staff    21M Jan 11 12:58 blocks/rev01037.dat
```

**Comment by kallewoof** [comment]
Thanks! Yeah, we will have to do a one time run-through of all the rev files to clean up the excess use, or we will end up with wasted space for everyone.. I'm honestly not sure why this isn't affecting other systems though. The finalize issue is not mac specific (only the over-preallocating issue is).

**Comment by kallewoof** [comment]
This made me realize that this actually is a bug in the operating system. I couldn't explain why this didn't happen to earlier versions, but I believe I can now.

The bug is that ftruncate does not return pre-allocated disk space.

Before, we would over-preallocate and then immediately truncate back down to the expected size. This worked in pre-APFS land, but APFS has a bug which leaves the pre-allocated space as occupied by the file, even though we call ftruncate.

I will make a minimal test case displaying this behavior and submit a report to Apple.

File: src/util/system.cpp [hunk 1]
```diff
@@ -978,13 +978,13 @@ void AllocateFileRange(FILE *file, unsigned int offset, unsigned int length) {
...
     fst.fst_offset = 0;
-    fst.fst_length = (off_t)offset + length;
+    fst.fst_length = length; // mac os fst_length takes the # of free bytes to allocate, not desired file size
     fst.fst_bytesalloc = 0;
     if (fcntl(fileno(file), F_PREALLOCATE, &fst) == -1) {
         fst.fst_flags = F_ALLOCATEALL;
         fcntl(fileno(file), F_PREALLOCATE, &fst);
     }
-    ftruncate(fileno(file), fst.fst_length);
+    ftruncate(fileno(file), (off_t)offset + length);
```
Comment (Empact) [inline src/util/system.cpp]: nit: could `static_cast`

**Comment by Empact** [comment]
Code review ACK https://github.com/bitcoin/bitcoin/pull/17887/commits/5de93dced1a2d10b21ce0afa3bfb293cf58071e9 also checked `man fcntl` locally

File: src/util/system.cpp (hunk 1 above)
Comment (kallewoof) [reply src/util/system.cpp]: Done

**Comment by fanquake** [comment]
@arvidn Any chance you could comment here, given you patched an [APFS related issue in libtorrent](https://github.com/arvidn/libtorrent/pull/2450) some time ago?

**Comment by arvidn** [comment]
This patch changes the behavior of `AllocateFileRange()`, which is documented to:

> this function tries to make a particular range of a file allocated (corresponding to disk space) it is advisory, and the range specified in the arguments will never contain live data

It doesn't seem like this patch correctly implements the documented behavior. It might fix an issue in how `AllocateFileRange()` is used, but there still seems to be a mismatch in how `AllocateFileRange()` behaves on other operating systems and what it's documented to use.

If I understand the mailing list post Dominic Giampaolo correctly, in order to implement the documented behavior of `AllocateFileRange()` you would also need to `stat()` the file and set:

```
fst.fst_length = offset + length - st_size;
```

and if `offset + length` < `st_size`, skip the `fcntl()` call entirely.

**Comment by kallewoof** [comment]
@arvidn The docs for `F_PREALLOCATE` indicate that `fst_length` is the amount of free space desired.

>            F_PEOFPOSMODE   Allocate from the physical end of file.  In this case, fst_length indicates the number of newly allocated bytes desired.

**Comment by arvidn** [comment]
> but I believe offset is already (supposed to be) equal to st_size

Right, this patch makes that assumption. The windows implementation does not make this assumption, nor does the documentation state it will make this assumption.

**Comment by kallewoof** [comment]
I see what you mean. I don't think it matters in this case either way, but it's worth pointing out.

**Comment by kallewoof** [comment]
Either way, that's unrelated to the question which is how to properly pre-allocate (and more importantly, how to return unused space at the end) on APFS.

**Comment by kallewoof** [comment]
Pushed a comment regarding the assumption `<file size> == offset` in the OSX version.

File: src/util/system.cpp [hunk 2]
```diff
@@ -974,17 +974,19 @@ void AllocateFileRange(FILE *file, unsigned int offset, unsigned int length) {
     SetEndOfFile(hFile);
 #elif defined(MAC_OSX)
     // OSX specific version
+    // NOTE: Contrary to other OS versions, the OSX version assumes that
+    // NOTE: offset is the size of the file.
```
Comment (laanwj) [inline src/util/system.cpp]: Wouldn't it make sense to add an assertion here? Implementing a function differently than documented on a OS could turn into a troubleshooting nightmare at some point.

Comment (kallewoof) [reply src/util/system.cpp]: You would have to check file size, in which case you might as well do what @arvidn suggested. It depends on the impact of checking the file size (once per MB of data for rev files). I initially wrote code to do just that, but it felt wasteful. If people think it's fine, I can switch to this (or if there's a more optimized variant).

```diff
diff --git a/src/util/system.cpp b/src/util/system.cpp
index d9fc38c91..3edcf5bc3 100644
--- a/src/util/system.cpp
+++ b/src/util/system.cpp
@@ -974,11 +974,17 @@ void AllocateFileRange(FILE *file, unsigned int offset, unsigned int length) {
     SetEndOfFile(hFile);
 #elif defined(MAC_OSX)
     // OSX specific version
+    long pos = ftell(file);
+    fseek(file, 0L, SEEK_END);
+    long filesize = ftell(file);
+    fseek(file, pos, SEEK_SET);
+    if (offset + length <= filesize) return;
     fstore_t fst;
     fst.fst_flags = F_ALLOCATECONTIG;
     fst.fst_posmode = F_PEOFPOSMODE;
     fst.fst_offset = 0;
-    fst.fst_length = length; // mac os fst_length takes the # of free bytes to allocate, not desired file size
+    // mac os fst_length takes the # of free bytes to allocate, not desired file size
+    fst.fst_length = static_cast<off_t>(offset) + length - filesize;
     fst.fst_bytesalloc = 0;
     if (fcntl(fileno(file), F_PREALLOCATE, &fst) == -1) {
         fst.fst_flags = F_ALLOCATEALL;
```

Comment (laanwj) [reply src/util/system.cpp]: Yes, that seems wasteful.

Another solution would be to remove the `offset` parameter and define the function to always work relative to the end of the file, for all platforms. This also avoids using the function in the wrong away.

Comment (kallewoof) [reply src/util/system.cpp]: I think the main reason why it is there in the first place is to avoid the seek part when possible. It basically functions as a cache approximating the file size. It will overshoot by a small amount (depending on the size of whatever is being written that doesn't currently fit), but it's mostly accurate, and I think for performance reasons this is done that way. After all, only the *preallocate* part overshoots - the `ftruncate` call adjusts the file size to the expected value (..except it doesn't -- see #17892).

We could of course remove the offset completely, but I think it would be an unnecessary performance loss with very little gain.

In practice, we end up over-pre-allocating up to the maximum possible value of an entry written into the respective files; for rev files, I assume this is usually in the few kbs range, and for blk files, I assume it's a couple of MBs since blocks are around that size. Analysis on this as below.

===

Given:
* `required` = bytes needed
* `position` = current position inside file
* `chunk_size` = the size of each chunk in the file (1 MB for rev files)
* `allocation` = current file allocation (pre-allocated space)
* `filesize` = current file *size*, i.e. whatever we truncated it to (this is identical to `allocation` on systems except OSX, and is in part mitigated by the fix here)
* `old_chunks = (position + chunk_size - 1) / chunk_size`
* `new_chunks = (position + required + chunk_size - 1) / chunk_size`

For the case where `new_chunks > old_chunks`, there is a discrepancy in `position` vs `filesize` that is between `0..chunk_size-1` (not greater, because the code never allocates more chunks than needed).
* The `offset` is set to the former, and thus the assumed file size is in the range `[filesize - chunk_offset + 1 .. filesize]`.
* The `length` is set to the value `new_chunks * chunk_size - position`, i.e. `position + required + chunk_size - 1 - position = required + chunk_size - 1`.

Results:
* Expectation: pre-allocate `required + chunk_size - 1` free bytes to get a file with size `position + required + chunk_size - 1` bytes, then truncate to that size.
* Result: pre-allocate `required + chunk_size - 1` free bytes to get a file with size `filesize + required + chunk_size - 1` bytes, then truncate to `position + required + chunk_size - 1` bytes (this is currently not functional on APFS).
* I.e. we end up with up to `chunk_size` more bytes in the pre-allocation stage.
* For the rev case, we end up over-pre-allocating up to 1 extra MB of space that we keep bumping (fairly randomly in the range 0..1024*1024, though in practice this value is capped at the size of the biggest entry we write into rev files).
* For the blk case, we over-pre-allocate up to 16 MB, but since blocks are capped at a few MBs, this ends up being a few MBs in practice.

If you spot any errors, let me know and I'll update.

**Comment by eriknylund** [comment]
> ```
> === BLOCK FILE INFO STATS (blocks 0 .. 50000) ===
> BLOCKS: 49877 additions, 12276387 total space, 246.1 bytes/addition
> REVS:   49437 additions, 2365864 total space, 47.9 bytes/addition
> 
> === BLOCK FILE INFO STATS (blocks 50000 .. 100000) ===
> BLOCKS: 49996 additions, 48138897 total space, 962.9 bytes/addition
>      3 allocations; 30243 over, 0 under => 10081.0 over/alloc, 0.0 under/alloc
> REVS:   49838 additions, 7405309 total space, 148.6 bytes/addition
>      7 allocations; 30309 over, 0 under => 4329.9 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 100000 .. 150000) ===
> BLOCKS: 50003 additions, 626534873 total space, 12529.9 bytes/addition
>      38 allocations; 414684 over, 0 under => 10912.7 over/alloc, 0.0 under/alloc
> REVS:   49910 additions, 76723416 total space, 1537.2 bytes/addition
>      78 allocations; 140190 over, 0 under => 1797.3 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 150000 .. 200000) ===
> BLOCKS: 49984 additions, 2449096762 total space, 48997.6 bytes/addition
>      147 allocations; 8693387 over, 0 under => 59138.7 over/alloc, 0.0 under/alloc
> REVS:   50221 additions, 329612289 total space, 6563.2 bytes/addition
>      329 allocations; 2841940 over, 0 under => 8638.1 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 200000 .. 250000) ===
> BLOCKS: 50085 additions, 6683661512 total space, 133446.4 bytes/addition
>      397 allocations; 35292223 over, 0 under => 88897.3 over/alloc, 0.0 under/alloc
> REVS:   50444 additions, 898707532 total space, 17815.9 bytes/addition
>      886 allocations; 10750386 over, 0 under => 12133.6 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 250000 .. 300000) ===
> BLOCKS: 49928 additions, 8774861776 total space, 175750.3 bytes/addition
>      526 allocations; 67195634 over, 0 under => 127748.4 over/alloc, 0.0 under/alloc
> REVS:   49276 additions, 1193450599 total space, 24219.7 bytes/addition
>      1181 allocations; 21881254 over, 0 under => 18527.7 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 300000 .. 350000) ===
> BLOCKS: 50051 additions, 14839754426 total space, 296492.7 bytes/addition
>      886 allocations; 188673758 over, 0 under => 212950.1 over/alloc, 0.0 under/alloc
> REVS:   50406 additions, 2084855624 total space, 41361.3 bytes/addition
>      2037 allocations; 61869705 over, 0 under => 30373.0 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 350000 .. 400000) ===
> BLOCKS: 50070 additions, 27257622944 total space, 544390.3 bytes/addition
>      1627 allocations; 549589308 over, 0 under => 337793.1 over/alloc, 0.0 under/alloc
> REVS:   50443 additions, 3878444863 total space, 76887.7 bytes/addition
>      3785 allocations; 183316201 over, 0 under => 48432.3 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 400000 .. 450000) ===
> BLOCKS: 49953 additions, 39828992105 total space, 797329.3 bytes/addition
>      2385 allocations; 943542364 over, 0 under => 395615.2 over/alloc, 0.0 under/alloc
> REVS:   49951 additions, 5365225097 total space, 107409.8 bytes/addition
>      5276 allocations; 296906600 over, 0 under => 56274.9 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 450000 .. 500000) ===
> BLOCKS: 50037 additions, 47505676936 total space, 949411.0 bytes/addition
>      2840 allocations; 1300043016 over, 0 under => 457761.6 over/alloc, 0.0 under/alloc
> REVS:   50030 additions, 6404583587 total space, 128014.9 bytes/addition
>      6284 allocations; 385011825 over, 0 under => 61268.6 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 500000 .. 550000) ===
> BLOCKS: 50006 additions, 43443126157 total space, 868758.2 bytes/addition
>     2599 allocations; 1225858445 over, 0 under => 471665.4 over/alloc, 0.0 under/alloc
> REVS:   50019 additions, 5910980004 total space, 118174.7 bytes/addition
>     5800 allocations; 376748454 over, 0 under => 64956.6 over/alloc, 0.0 under/alloc
> 
> === BLOCK FILE INFO STATS (blocks 550000 .. 600000) ===
> BLOCKS: 49998 additions, 53633781103 total space, 1072718.5 bytes/addition
>     3211 allocations; 1685246556 over, 0 under => 524835.4 over/alloc, 0.0 under/alloc
> REVS:   49982 additions, 6957171383 total space, 139193.5 bytes/addition
>     6833 allocations; 476667594 over, 0 under => 69759.6 over/alloc, 0.0 under/alloc
> ```

I'm curious to know, how did you go about collecting these stats?

**Comment by eriknylund** [comment]
ACK 75163f4729c10c40d2843da28a8c79ab89193f6a built locally. All tests passing. Manual test as per my previous comment above on an older commit, using an APFS unencrypted disk image with 3 GB.

Are there any new tests that would make sense to add for this change?

**Review by eriknylund — APPROVED** [review]
I prefer this over the more complicated approach involving file size checks. It fixes the blow-up problem without adding more lines of code.

**Comment by kallewoof** [comment]
@eriknylund 

> I'm curious to know, how did you go about collecting these stats?

I simply patched Bitcoin Core directly and re-ran IBD. I did some polishing on the final output, though. The branch is called 'macos-f_preallocate_fix-benchmarked' if you wanna see: https://github.com/kallewoof/bitcoin/tree/macos-f_preallocate_fix-benchmarked

**Comment by Sjors** [comment]
@kallewoof wrote:
> I suspect the OS eventually reclaims pre-allocated space, but it seems block files are not suffering from this kind of issue, so I'm honestly not sure. The docs clearly indicate we were using it wrong, though.

Maybe. I have the blockchain on my macOS Catalina machine (APFS with encryption). Most historical rev files are ~17 MB but starting from `rev01835.dat` (October 22, 2019) I'm seeing many big ones (up to 171MB). `blk` files don't have this issue. Catalina was released on October 7th and I upgraded on the 9th according to `softwareupdate --history`. There was another system update on the 15th. I did sync Bitcoin Core multiple times in the interim, covering about 10 rev files which are normal size.

Note that Finder just shows ~17 MB sizes.

When I sync a fresh node from scratch I see rev files get as large as 100 MB, though usually shrinking back a bit when it moves the next one:
Schermafbeelding 2020-01-21 om 14 47 19
 
With this PR rev files don't grow over 19 MB.

I also tried starting a (testnet) node that was previously synced on master, but a day behind, and it didn't complain.

**Comment by kallewoof** [comment]
@Sjors Thanks for testing! Yeah, that comment is outdated. I will update it. I described it in detail here: https://github.com/bitcoin/bitcoin/pull/17887#issuecomment-573504904

**Comment by dongcarl** [comment]
Concept ACK, great find!

**Comment by fjahr** [comment]
Hm, I could not reproduce the issue with the current master (631df3ee87ec93e1fc748715671cdb5cff7308e6) in a way indicated here: https://github.com/bitcoin/bitcoin/pull/17887#issuecomment-571591432

I started a new IBD and let it run up to ~220k blocks. Checked the blocks folder every couple of minutes and never saw a `.rev` file larger than 20M, not even the most recent one as described by @Sjors .

Here are my file sizes: https://gist.github.com/fjahr/a56a2c81217b255f448f2b53928c93db

System: macOS Catalina 10.15.2, APFS (Encrypted), 2016 MBP

Happy to test again if that's helpful. Based on the information I read here, I can't tell why my results are different from everyone else.

**Comment by Sjors** [comment]
I ran with `--enable-debug` though.

**Comment by bg002h** [comment]
My sizes using this pull request, running Catalina and an unencrypted APFS disk:

https://pastebin.com/W53SX4xg

Running master:

https://pastebin.com/0Sj2XXny

All file sizes for both this PR and master don't seem any different while running or after shutdown.

**Comment by Sjors** [comment]
@bg002h `ls -alFh` won't see the issue. Try `du -ch` instead.

**Comment by bg002h** [comment]
@Sjors Thx for the tip!

I reformatted my NVME raid to APFS, encrypted, case sensitive since the above.

For master, I see: 
https://pastebin.com/GeqsZhmh (rev 50 was 45M)

running this PR (pastern is down):
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
.
.
.
128M	blk00052.dat
 16M	blk00053.dat
8.0K	index
 19M	rev00000.dat
 16M	rev00001.dat
 16M	rev00002.dat
 16M	rev00003.dat
 16M	rev00004.dat
 17M	rev00005.dat
 17M	rev00006.dat
 17M	rev00007.dat
 18M	rev00008.dat
 18M	rev00009.dat
 17M	rev00010.dat
 17M	rev00011.dat
 18M	rev00012.dat
 18M	rev00013.dat
 17M	rev00014.dat
 17M	rev00015.dat
 18M	rev00016.dat
 17M	rev00017.dat
 17M	rev00018.dat
 17M	rev00019.dat
 17M	rev00020.dat
 17M	rev00021.dat
 17M	rev00022.dat
 17M	rev00023.dat
 17M	rev00024.dat
 17M	rev00025.dat
 17M	rev00026.dat
 17M	rev00027.dat
 17M	rev00028.dat
 17M	rev00029.dat
 17M	rev00030.dat
 17M	rev00031.dat
 17M	rev00032.dat
 17M	rev00033.dat
 17M	rev00034.dat
 17M	rev00035.dat
 17M	rev00036.dat
 17M	rev00037.dat
 17M	rev00038.dat
 17M	rev00039.dat
 17M	rev00040.dat
 17M	rev00041.dat
 17M	rev00042.dat
 17M	rev00043.dat
 17M	rev00044.dat
 17M	rev00045.dat
 17M	rev00046.dat
 17M	rev00047.dat
 17M	rev00048.dat
 17M	rev00049.dat
 17M	rev00050.dat
 17M	rev00051.dat
 17M	rev00052.dat
2.0M	rev00053.dat *in progress*
7.5G	total

**Comment by bg002h** [comment]
using master, and checking du repeatedly during blk1, rev1 gets pretty big before being trimmed back:

cg@Brians-MacBook-Pro blocks % du -ch *
576M	blk00000.dat
8.0K	index
190M	rev00000.dat
766M	total

The behavior is not observed using this PR:

bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
8.0K	index
 17M	rev00000.dat
145M	total
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
8.0K	index
 18M	rev00000.dat
146M	total
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
8.0K	index
 19M	rev00000.dat
147M	total
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
8.0K	index
 19M	rev00000.dat
147M	total
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
8.0K	index
 19M	rev00000.dat
147M	total
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
 16M	blk00001.dat
8.0K	index
 19M	rev00000.dat
1.0M	rev00001.dat
164M	total
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
 16M	blk00001.dat
8.0K	index
 19M	rev00000.dat
1.0M	rev00001.dat
164M	total
bcg@Brians-MacBook-Pro blocks % 
bcg@Brians-MacBook-Pro blocks % du -ch *
128M	blk00000.dat
 96M	blk00001.dat
8.0K	index
 19M	rev00000.dat
 12M	rev00001.dat
255M	total

**Comment by fjahr** [comment]
> I ran with `--enable-debug` though.

Strange, I double checked and still not seeing any large rev files with `--enable-debug`...

**Comment by kallewoof** [comment]
`--enable-debug` should not matter in this case.

**Comment by maaku** [comment]
FWIW I'm able to reproduce this on gitian-built clients as far back as 0.12.

File: src/util/system.cpp (hunk 2 above)
Comment (laanwj) [reply src/util/system.cpp]: I think that's correct.
Though I would expect the seek to be of negligible performance compared to the allocation of disk space itself.

But it's always possible to do that later; if people tested that this fixes the issue let's not make further changes here.

**Comment by laanwj** [comment]
code review ACK 75163f4729c10c40d2843da28a8c79ab89193f6a
I have checked  [the documentation](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fcntl.2.html) that the new use of `F_PREALLOCATE` is correct.

**Comment by fanquake** [comment]
Being backported to 0.19 in #17988.

**Comment by kallewoof** [comment]
Apple responded to my bug report regarding this, in case people are curious: https://openradar.appspot.com/radar?id=4930713610616832
