### PR TITLE
Fix RPCTimerInterface ordering issue

### LINKED ISSUE #7316: walletpassphrase timeout doesn't work in bitcoin-qt
If I am running `bitcoind` then `bitcoin-cli walletpassphrase $pass 5` will unlock my wallet for 5 seconds.

But if I am running `bitcoin-qt` then the same command will unlock my wallet indefinitely, and show an error in the debug.log:

    GUI: QObject::startTimer: Timers can only be used with threads started with QThread

I built from the master branch, commit b1cf0058d9b3d3e218f1dc31ee688e5beb21f573.

### PR DESCRIPTION
**Pull request by jonasschnelli**
Dispatching a `QThread` from a non Qt thread is not allowed. Always use the `HTTPRPCTimerInterface` (non QT) to dispatch `RPCRunLater` threads.

Agree that using the order of `timerInterfaces` is not the best way of identifying the type of the timer interface.

fixes #7316

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Tested ACK 9490ec3, indeed fixes https://github.com/bitcoin/bitcoin/issues/7316#issuecomment-169938133.

Tag "Backport" missing?

**Comment by jonasschnelli** [comment]
Discussed with @laanwj on IRC and i'll try now to remove the set of timers, I think having only one timer makes things more stable for future changes.

**Comment by laanwj** [comment]
Concept ACK, but the change in logic needs to be more explicit. This is too fragile against refactors/reorders (at least for master, for 0.12 as a quick last minute patch it'd be acceptable...).

**Comment by jonasschnelli** [comment]
Added a commit that removes the `std::vector` for RPCTimerInterfaces (just one pointer now). Also added a function (`RPCSetTimerInterfaceIfUnset`) that prevents setting a Qt bases timer interface if already only is set.
Not meant for back porting (will open "the" simple fix for 0.12).

File: src/rpcserver.h [hunk 1]
```diff
@@ -100,10 +100,12 @@ class RPCTimerInterface
     virtual RPCTimerBase* NewTimer(boost::function<void(void)>& func, int64_t millis) = 0;
 };
 
-/** Register factory function for timers */
-void RPCRegisterTimerInterface(RPCTimerInterface *iface);
-/** Unregister factory function for timers */
-void RPCUnregisterTimerInterface(RPCTimerInterface *iface);
+/** Set the factory function for timers */
+void RPCSetTimerInterface(RPCTimerInterface *iface);
+/** Set the factory function for timer, but only, it unset */
```
Comment (laanwj) [inline src/rpcserver.h]: typo: if unset

**Comment by laanwj** [comment]
Nice, uTACK

File: src/rpcserver.h (hunk 1 above)
Comment (jonasschnelli) [inline src/rpcserver.h]: Thanks. Fixed.

File: src/qt/rpcconsole.cpp [hunk 2]
```diff
@@ -278,7 +278,9 @@ RPCConsole::RPCConsole(const PlatformStyle *platformStyle, QWidget *parent) :
 #endif
     // Register RPC timer interface
     rpcTimerInterface = new QtRPCTimerInterface();
-    RPCRegisterTimerInterface(rpcTimerInterface);
+    // avoid accidentailly overwrite an existing, non QTThread
```
Comment (laanwj) [inline src/qt/rpcconsole.cpp]: s/accidentiailly overwrite/accidentally overwriting

Comment (jonasschnelli) [inline src/qt/rpcconsole.cpp]: Thanks. Force push fixed.
