### PR TITLE
Fix ScanForWalletTransactions to return an enum indicating scan result: success / failure / user_abort

### LINKED ISSUE #11450: ScanForWalletTransactions return value is incorrectly documented
`ScanForWalletTransactions()` has the following comment about its return value:

```
 * Returns null if scan was successful. Otherwise, if a complete rescan was not
 * possible (due to pruning or corruption), returns pointer to the most recent
 * block that could not be scanned.
```

This is not strictly true. If `abortrescan` is called, then `ScanForWalletTransactions()` will return `nullptr`, even though the scan wasn't successful to the tip.

This in turn causes a minor bug in `importmulti`, where the call doesn't return the correct error and warning about potentially not finding transactions if `abortrescan` was called.

I think the correct fix is for `ScanForWalletTransactions()` to inform the caller that the rescan was aborted.

### PR DESCRIPTION
**Pull request by Empact**
Return the failed block as an out arg.

Fixes #11450.

/cc #12275

### CODE REVIEW

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -3767,16 +3767,13 @@ UniValue rescanblockchain(const JSONRPCRequest& request)
...
+    const CBlockIndex* stopBlock = nullptr;
+    if (pwallet->ScanForWalletTransactions(pindexStart, pindexStop, stopBlock, reserver, true)) {
         stopBlock = pindexStop ? pindexStop : pChainTip;
-    }
-    else {
-        throw JSONRPCError(RPC_MISC_ERROR, "Rescan failed. Potentially corrupted data files.");
+    } else if (pwallet->IsAbortingRescan()) {
+        throw JSONRPCError(RPC_MISC_ERROR, "Rescan aborted.");
+    } else {
+        throw JSONRPCError(RPC_MISC_ERROR, strprintf("Rescan failed. Potentially corrupted data files. Failed at height %i.", stopBlock->nHeight));
```
Comment (Empact) [inline src/wallet/rpcwallet.cpp]: Note I added the failure height here. Happy to remove, but I assume it could be helpful.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -4167,11 +4167,11 @@ CWallet* CWallet::CreateWalletFromFile(const std::string& name, const fs::path&
         nStart = GetTimeMillis();
         {
             WalletRescanReserver reserver(walletInstance);
-            if (!reserver.reserve()) {
+            const CBlockIndex* stop_block = nullptr;
+            if (!reserver.reserve() || !walletInstance->ScanForWalletTransactions(pindexRescan, nullptr, stop_block, reserver, true)) {
```
Comment (Empact) [inline src/wallet/wallet.cpp]: Note this did not previously fail when ScanForWalletTransactions failed, so this removes a silent failure.

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -1791,7 +1791,7 @@ CBlockIndex* CWallet::ScanForWalletTransactions(CBlockIndex* pindexStart, CBlock
         }
         ShowProgress(_("Rescanning..."), 100); // hide progress dialog in GUI
     }
-    return ret;
+    return (!fAbortRescan && !failed_block);
```
Comment (Empact) [inline src/wallet/wallet.cpp]: Alternatively, this could be `(!pindex && !failed_block)`

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -1708,9 +1709,10 @@ int64_t CWallet::RescanFromTime(int64_t startTime, const WalletRescanReserver& r
  * from or to us. If fUpdate is true, found transactions that already
  * exist in the wallet will be updated.
  *
- * Returns null if scan was successful. Otherwise, if a complete rescan was not
- * possible (due to pruning or corruption), returns pointer to the most recent
- * block that could not be scanned.
+ * Returns true if scan was successful. If a complete rescan was not
+ * possible (due to pruning or corruption), returns false and sets failed_block
+ * to the most recent block that could not be scanned. If the rescan was aborted
+ * before it could complete, returns false and does not set failed_block.
```
Comment (jonasschnelli) [inline src/wallet/wallet.cpp]: Not sure if in this PR, but would it make sense to just return an `enum` to better distinct between `fail`, `ok` and `user-aborted`?

File: src/wallet/wallet.cpp [hunk 5]
```diff
@@ -1719,7 +1721,7 @@ int64_t CWallet::RescanFromTime(int64_t startTime, const WalletRescanReserver& r
  * the main chain after to the addition of any new keys you want to detect
  * transactions for.
  */
-CBlockIndex* CWallet::ScanForWalletTransactions(CBlockIndex* pindexStart, CBlockIndex* pindexStop, const WalletRescanReserver &reserver, bool fUpdate)
+bool CWallet::ScanForWalletTransactions(const CBlockIndex* const pindexStart, const CBlockIndex* const pindexStop, const CBlockIndex*& failed_block, const WalletRescanReserver& reserver, bool fUpdate)
```
Comment (promag) [inline src/wallet/wallet.cpp]: *Output* arguments could be last?

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (promag) [reply src/wallet/wallet.cpp]: Could be done here IMO, not a big change and would be a lot better IMO.

File: src/qt/test/wallettests.cpp [hunk 6]
```diff
@@ -156,7 +156,8 @@ void TestGUI()
         LOCK(cs_main);
         WalletRescanReserver reserver(&wallet);
         reserver.reserve();
-        wallet.ScanForWalletTransactions(chainActive.Genesis(), nullptr, reserver, true);
+        const CBlockIndex* stop_block = nullptr;
+        wallet.ScanForWalletTransactions(chainActive.Genesis(), nullptr, stop_block, reserver, true);
```
Comment (promag) [inline src/qt/test/wallettests.cpp]: Could assert return value and `stop_block` value?

File: src/wallet/wallet.cpp (hunk 2 above)
Comment (promag) [reply src/wallet/wallet.cpp]: I think this is ok. This just adds another case where `walletInstance` is leaked on error.

**Review by promag — COMMENTED** [review]
Concept ACK.

File: src/wallet/wallet.cpp (hunk 2 above)
Comment (Empact) [reply src/wallet/wallet.cpp]: Should we be switching `walletInstance` to RAII then?

File: src/wallet/wallet.cpp [hunk 7]
```diff
@@ -1763,14 +1764,14 @@ CBlockIndex* CWallet::ScanForWalletTransactions(CBlockIndex* pindexStart, CBlock
                 if (pindex && !chainActive.Contains(pindex)) {
                     // Abort scan if current block is no longer active, to prevent
                     // marking transactions as coming from the wrong block.
-                    ret = pindex;
+                    failed_block = pindex;
```
[the remark this answers is not in the document]
Comment (Empact) [reply src/wallet/wallet.cpp]: Not sure about that - my inclination is to maintain stricter checking at the risk of spurious failures over less strict checking at the risk of silent failure. How about opening a separate PR for that so it can be considered separately?

File: src/wallet/wallet.cpp [hunk 8]
```diff
@@ -1695,8 +1695,9 @@ int64_t CWallet::RescanFromTime(int64_t startTime, const WalletRescanReserver& r
     }
 
     if (startBlock) {
-        const CBlockIndex* const failedBlock = ScanForWalletTransactions(startBlock, nullptr, reserver, update);
-        if (failedBlock) {
+        const CBlockIndex* failedBlock = nullptr;
+        // TODO: this should take into account failure by ScanResult::USER_ABORTED
```
Comment (Empact) [inline src/wallet/wallet.cpp]: I'll address this todo in a follow-up.

File: src/wallet/wallet.cpp (hunk 4 above)
Comment (Empact) [reply src/wallet/wallet.cpp]: Updated to return an enum.

File: src/wallet/wallet.cpp (hunk 5 above)
Comment (Empact) [reply src/wallet/wallet.cpp]: Made it second-to-last due to default value for update arg.

File: src/wallet/wallet.h [hunk 9]
```diff
@@ -914,7 +914,13 @@ class CWallet final : public CCryptoKeyStore, public CValidationInterface
     void BlockDisconnected(const std::shared_ptr<const CBlock>& pblock) override;
     bool AddToWalletIfInvolvingMe(const CTransactionRef& tx, const CBlockIndex* pIndex, int posInBlock, bool fUpdate);
     int64_t RescanFromTime(int64_t startTime, const WalletRescanReserver& reserver, bool update);
-    CBlockIndex* ScanForWalletTransactions(CBlockIndex* pindexStart, CBlockIndex* pindexStop, const WalletRescanReserver& reserver, bool fUpdate = false);
+
+    enum class ScanResult : int {
+        SUCCESS = 0,
```
Comment (jonasschnelli) [inline src/wallet/wallet.h]: nit: not sure if SUCCESS should use a non C-ish, non null positive value (1 probably)

Comment (MarcoFalke) [reply src/wallet/wallet.h]: note that there is no need for an `enum class` to derive from int or even specify values for the members.

**Comment by Empact** [comment]
Dropped explicit values and type from `ScanResult` enum.

**Comment by Empact** [comment]
Rebased and updated to accommodate #12507.

**Comment by Empact** [comment]
Rebased and moved the shutdown / abort handling inline.

**Review by sabran125 — COMMENTED** [review]
indicating the requested changes

**Review by DocOBITCOIN — APPROVED** [review]

File: src/wallet/rpcwallet.cpp [hunk 10]
```diff
@@ -3912,16 +3912,19 @@ UniValue rescanblockchain(const JSONRPCRequest& request)
...
         stopBlock = pindexStop ? pindexStop : pChainTip;
-    }
-    else {
+        break;
+    case CWallet::ScanResult::FAILURE:
         throw JSONRPCError(RPC_MISC_ERROR, "Rescan failed. Potentially corrupted data files.");
+    case CWallet::ScanResult::USER_ABORT:
+        throw JSONRPCError(RPC_MISC_ERROR, "Rescan aborted.");
+    default:
+        throw JSONRPCError(RPC_MISC_ERROR, strprintf("Unexpected rescan result: %i.", static_cast<int>(result)));
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp]: Should remove the default case, so instead of a runtime-error the compiler can warn about missing cases.
```suggestion
        // no default case, so the compiler can warn about missing cases
```

**Review by maflcko — COMMENTED** [review]
Concept ACK. Needs rebase

**Comment by Empact** [comment]
Rebased. @MarcoFalke could you remove "Up for grabs"?

File: src/qt/test/wallettests.cpp [hunk 11]
```diff
@@ -144,7 +144,12 @@ void TestGUI()
         LOCK(cs_main);
         WalletRescanReserver reserver(wallet.get());
         reserver.reserve();
-        wallet->ScanForWalletTransactions(chainActive.Genesis(), nullptr, reserver, true);
+        const CBlockIndex* const null_block = nullptr;
+        const CBlockIndex* stop_block = nullptr;
```
Comment (MarcoFalke) [inline src/qt/test/wallettests.cpp]: nit: No need to initialize a return value. In fact this might look like you are passing in something.

Also could inline nullptr for null_block below for brevity.

File: src/wallet/rpcwallet.cpp [hunk 12]
```diff
@@ -3297,16 +3297,18 @@ UniValue rescanblockchain(const JSONRPCRequest& request)
         }
     }
 
-    const CBlockIndex* stopBlock = pwallet->ScanForWalletTransactions(pindexStart, pindexStop, reserver, true);
-    if (!stopBlock) {
-        if (pwallet->IsAbortingRescan()) {
-            throw JSONRPCError(RPC_MISC_ERROR, "Rescan aborted.");
-        }
-        // if we got a nullptr returned, ScanForWalletTransactions did rescan up to the requested stopindex
+    const CBlockIndex* stopBlock = nullptr;
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp]: nit: No need to initialize a return value. In fact this might look like you are passing in something.

File: src/wallet/rpcwallet.cpp [hunk 13]
```diff
@@ -3297,16 +3297,18 @@ UniValue rescanblockchain(const JSONRPCRequest& request)
...
+    CWallet::ScanResult result =
+        pwallet->ScanForWalletTransactions(pindexStart, pindexStop, reserver, stopBlock, true);
+    switch (result) {
+    case CWallet::ScanResult::SUCCESS:
         stopBlock = pindexStop ? pindexStop : pChainTip;
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp]: Why are you overriding the return value?

File: src/wallet/test/wallet_tests.cpp [hunk 14]
```diff
@@ -50,7 +50,9 @@ BOOST_FIXTURE_TEST_CASE(rescan, TestChain100Setup)
         AddKey(wallet, coinbaseKey);
         WalletRescanReserver reserver(&wallet);
         reserver.reserve();
-        BOOST_CHECK_EQUAL(nullBlock, wallet.ScanForWalletTransactions(oldTip, nullptr, reserver));
+        const CBlockIndex* stop_block = nullptr;
+        BOOST_CHECK_EQUAL(wallet.ScanForWalletTransactions(oldTip, nullptr, reserver, stop_block), CWallet::ScanResult::SUCCESS);
+        BOOST_CHECK_EQUAL(nullBlock, stop_block);
```
Comment (MarcoFalke) [inline src/wallet/test/wallet_tests.cpp]: pIndexStop was nullptr, so this should be tip instead?

File: src/wallet/test/wallet_tests.cpp [hunk 15]
```diff
@@ -279,7 +283,10 @@ class ListCoinsTestingSetup : public TestChain100Setup
         AddKey(*wallet, coinbaseKey);
         WalletRescanReserver reserver(wallet.get());
         reserver.reserve();
-        wallet->ScanForWalletTransactions(chainActive.Genesis(), nullptr, reserver);
+        const CBlockIndex* const null_block = nullptr;
+        const CBlockIndex* stop_block = nullptr;
+        BOOST_CHECK_EQUAL(wallet->ScanForWalletTransactions(chainActive.Genesis(), nullptr, reserver, stop_block), CWallet::ScanResult::SUCCESS);
+        BOOST_CHECK_EQUAL(stop_block, null_block);
```
Comment (MarcoFalke) [inline src/wallet/test/wallet_tests.cpp]: Should be tip instead of null_block?

File: src/wallet/wallet.cpp [hunk 16]
```diff
@@ -1619,18 +1620,20 @@ int64_t CWallet::RescanFromTime(int64_t startTime, const WalletRescanReserver& r
  * from or to us. If fUpdate is true, found transactions that already
  * exist in the wallet will be updated.
  *
- * Returns null if scan was successful. Otherwise, if a complete rescan was not
- * possible (due to pruning or corruption), returns pointer to the most recent
- * block that could not be scanned.
+ * @param[in] pindexStop if not a nullptr, the scan will stop at this block-index
+ * @param[out] failed_block if FAILURE is returned, will be set to the most
+ *    recent block that could not be scanned.
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: nit: could return `last_block`, which will either be "the most recent block that could not be scanned" (failure/abort) or "pindexStop/::chainActive.Tip()" (success)

**Review by maflcko — APPROVED** [review]
Concept ACK, but I'd prefer it the block was returned in the case of success as well. (Otherwise it is up to the caller to *guess* which was the last successfully scanned block, since the tip can change without holding cs_main at the call site)

File: src/wallet/rpcwallet.cpp (hunk 13 above)
Comment (Empact) [reply src/wallet/rpcwallet.cpp]: This has been the behavior since the rpc's introduction in c77170fbdb

Comment (MarcoFalke) [reply src/wallet/rpcwallet.cpp]: I can pick this up and address my feedback middle of next week. (Let me know if you are currently busy or want to take a stab at this.)

File: src/wallet/test/wallet_tests.cpp (hunk 14 above)
Comment (MeshCollider) [reply src/wallet/test/wallet_tests.cpp]: @MarcoFalke `stop_block` is only set if the scan failed, it isn't set to tip if the scan succeeds

File: src/wallet/test/wallet_tests.cpp (hunk 15 above)
Comment (MeshCollider) [reply src/wallet/test/wallet_tests.cpp]: Same here as the other case :)

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13076/commits/b52abc7164ba6403124e409af2e3ee2e2dad7f24

I agree with Marco that returning the last successful block is probably a good idea, but with that and the other comments, at least this doesn't appear to make things worse, so it could be addressed in follow-ups if not here :)

**Comment by ryanofsky** [comment]
> I agree with Marco that returning the last successful block is probably a good idea

Returning the last failed block instead of the last successful block is needed for importmulti. Importmulti uses the last failed block to return success for keys with birthdays after that block, and failures for keys with older birthdays.

I tried to clarify this in #12275 by returning both values (`last_scanned` and `last_failed`):

```c++
    struct ScanResult
    {
        const CBlockIndex* first_scanned = nullptr;
        const CBlockIndex* last_scanned = nullptr;
        const CBlockIndex* first_failed = nullptr;
        const CBlockIndex* last_failed = nullptr;
    };
```

Which I still think would be an improvement over the current code.

**Comment by MeshCollider** [comment]
@ryanofsky I think I mis-explained, I mean in the case of success - the failure case behaviour should remain unchanged

File: src/qt/test/wallettests.cpp (hunk 11 above)
Comment (Empact) [reply src/qt/test/wallettests.cpp]: Removed the initialization of the out var, though this required setting the out var to null in the method for consistent behavior under test. Seems like a good change to me as this seems more predictable.

Can't inline the `null_block` vars as that results in template ambiguity around `<ostream, nullptr_t>`

File: src/wallet/wallet.cpp (hunk 8 above)
Comment (Empact) [reply src/wallet/wallet.cpp]: Follow-up is here, I'll wait to open until this is accepted:
https://github.com/Empact/bitcoin/tree/rescan-from-time

File: src/qt/test/wallettests.cpp [hunk 17]
```diff
@@ -146,7 +146,13 @@ void TestGUI()
         auto locked_chain = wallet->chain().lock();
         WalletRescanReserver reserver(wallet.get());
         reserver.reserve();
-        wallet->ScanForWalletTransactions(chainActive.Genesis(), nullptr, reserver, true);
+        const CBlockIndex* const null_block = nullptr;
+        const CBlockIndex *stop_block, *failed_block;
+        QCOMPARE(
+            wallet->ScanForWalletTransactions(chainActive.Genesis(), nullptr, reserver, failed_block, stop_block, true /* fUpdate */),
+            CWallet::ScanResult::SUCCESS);
+        QCOMPARE(stop_block, null_block);
```
Comment (MarcoFalke) [inline src/qt/test/wallettests.cpp]: Travis failure:

```
********* Start testing of WalletTests *********
Config: Using QtTest library 5.9.6, Qt 5.9.6 (i386-little_endian-ilp32 static release build; by GCC 7.3.0)
PASS   : WalletTests::initTestCase()
FAIL!  : WalletTests::walletTests() Compared pointers are not the same
   Loc: [qt/test/wallettests.cpp(154)]
PASS   : WalletTests::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 245ms
********* Finished testing of WalletTests *********

Comment (Empact) [reply src/qt/test/wallettests.cpp]: Thanks! Solved.

**Review by ryanofsky — APPROVED** [review]
utACK bd3b0361d840bff95988a048abf70ade94d80524

**Comment by jonasschnelli** [comment]
utACK bd3b0361d840bff95988a048abf70ade94d80524

**Comment by MarcoFalke** [comment]
utACK bd3b0361d8

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/13076/commits/bd3b0361d840bff95988a048abf70ade94d80524

File: src/wallet/wallet.cpp [hunk 18]
```diff
@@ -1647,8 +1652,8 @@ CBlockIndex* CWallet::ScanForWalletTransactions(CBlockIndex* pindexStart, CBlock
         assert(pindexStop->nHeight >= pindexStart->nHeight);
     }
 
-    CBlockIndex* pindex = pindexStart;
-    CBlockIndex* ret = nullptr;
+    const CBlockIndex* pindex = pindexStart;
+    failed_block = nullptr;
```
Comment (ryanofsky) [inline src/wallet/wallet.cpp]: Code is not setting `stop_block` null here, which seems unintended and could lead to uninitialized variables. Would be good to fix this or add documentation if it was done intentionally.

File: src/wallet/wallet.cpp (hunk 8 above)
Comment (Empact) [reply src/wallet/wallet.cpp]: #14942

File: src/wallet/wallet.cpp (hunk 18 above)
Comment (Empact) [reply src/wallet/wallet.cpp]: Ah, right, the code does contradict the comments on line 1634. How about I fix this in #14942?
