### PR TITLE
net: Replace libnatpmp with built-in PCP+NATPMP implementation

### LINKED ISSUE #17012: Add IPv6 pinhole support using UPnP / NAT-PMP
Our current UPnP support works for IPv4 by requesting a port forward. It doesn't work with IPv6 when the user is behind a firewall (which was the default for my modem at least).

More recent versions of [libupnp](https://github.com/miniupnp/miniupnp) support requesting a IPv6 pinhole.

I haven't checked if the same could be done with NAT-PMP (#11902). That may be preferable to updating libupnp.

UPnP is baked into the GUI release binaries, though it's turned off by default in the settings dialog.

### PR DESCRIPTION
**Pull request by laanwj**
Continues #30005. Closes #17012..

This PR adds PCP (Port Control Protocol) from [RFC6887](https://datatracker.ietf.org/doc/html/rfc6887).  This adds, in addition to the existing IPv4 port mapping (which now uses PCP, with fallback to NAT-PMP), support for IPv6 pinholing-that is, opening a port on the firewall to make it reachable.

PCP, like NAT-PMP is a simple UDP-based protocol, and the implementation is self-contained, so this gets rid of lthe libnatpnp dependency without adding a new one. It should otherwise be a drop-in replacement. NAT-PMP fallback is implemented so this will not make router support worse.

For now it is disabled by default, though in the future (not in this PR) we could consider enable it by default to increase the number of connectable nodes without adding significant attack surface.

To test:
```bash
bitcoind -regtest -natpmp=1 -debug=net
```

(most of the changes in this PR are, ironically, removing the libnatpmp dependency and associated build system and build docs)

## TODO

- [x] Default gateway discovery on Linux / FreeBSD
- [x] Default gateway discovery on Windows
- [x] Default gateway discovery on MacOS
- [x] Either solve FreeBSD compile issue (probably upstream issue) or remove FreeBSD support

## Things to consider for follow-up PRs

- https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1658764974 avoid unreachable nets (not given to -onlynet=)

- https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1658949236 could announce an addr:port where we do not listen (no -bind)

- https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1684368824 could announce the wrong port because it uses GetListenPort()
 
- https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1679709347 if we requested one port but another was assigned, then which one to use in the renewal?

- https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1772017020 Use `GetAdapterAddresses` to discover local addresses for Windows #31014

- Unit testing: the code is set up to use Sock to support testing harnesses, but none have been written yet. It will also be necessary to createa a mockable steady_clock for this. #31022

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK

**Comment by theuni** [comment]
Whoa :)

**Review by Sjors — COMMENTED** [review]
RFC6887 appendix A describes how a router that supports NAP-PMP but not PCP, will return `UNSUPP_VERSION`. A log message could encourage users to try `-upnp` instead (if not already enabled). Or upgrade their ancient router firmware :-)

Got distracted during review, will continue later. I'll look into how we can preserve a previously selected NatPMP checkbox in the GUI.

**Comment by theuni** [comment]
Regarding the custom lib/self-impl discussion in #30005: 
Taking a quick look at the implementation here, I think it's simple enough for us to maintain ourselves. If a nice canonical lib ever emerges we could always jump to it, as there are only a few basic functions and presumably we could probably switch them out close to 1:1.

That said, it is a little rough to review as
- It needs to be compared to the letter of the spec, with the assumption that @laanwj is evil or has mis-implemented (I doubt that :)
- It needs to be very defensive, though the attack surface seems quite minimal
- It needs to be aware of real-world violators/benders/extenders of the spec (if any? I have no idea.)

But it seems worth the effort to me.

**Comment by laanwj** [comment]
Rebased for #29984

File: src/init.cpp [hunk 1]
```diff
@@ -760,8 +757,8 @@ void InitParameterInteraction(ArgsManager& args)
         // do not map ports or try to retrieve public IP when not listening (pointless)
         if (args.SoftSetBoolArg("-upnp", false))
             LogPrintf("%s: parameter interaction: -listen=0 -> setting -upnp=0\n", __func__);
-        if (args.SoftSetBoolArg("-natpmp", false)) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/init.cpp:763]: Yes, good point.

**Comment by laanwj** [comment]
> That said, it is a little rough to review as
>  It needs to be compared to the letter of the spec, with the assumption that @laanwj is evil or has mis-implemented (I doubt that :)

If you're more comfortable comparing it against another implementation there's:
- A kinda haphazard windows implementation here: https://github.com/moonlight-stream/GS-IPv6-Forwarder/blob/master/GSv6Fwd/pcp.cpp
- Miniupnpd's pcp server implementation https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/pcpserver.c

> It needs to be aware of real-world violators/benders/extenders of the spec (if any? I have no idea.)

Miniupnpd's is, likely, the most common server implementation in the wild. It's been tested against that.

> If a nice canonical lib ever emerges we could always jump to it

Maybe, but at some point there's not much difference between implementing a simple request/reply protocol and using a library. At least the RFC is unambigiously documented, which can't be said of many FOSS ABI's. Also, @fanquake has been hoping for a solution that doesn't introduce a library dependency.

File: src/util/pcp.cpp [hunk 2]
```diff
@@ -0,0 +1,236 @@
...
+        return CNetAddr(addr6);
+    }
+}
+
+std::optional<MappingResult> PCPRequestPortMap(const PCPMappingNonce &nonce, const CNetAddr &gateway, const CNetAddr &bind, uint16_t port, uint32_t lifetime, int num_tries, bool option_prefer_failure)
+{
+    struct sockaddr_storage dest_addr, bind_addr;
+    socklen_t dest_addrlen = sizeof(struct sockaddr_storage), bind_addrlen = sizeof(struct sockaddr_storage);
+
+    LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "pcp: Requesting port mapping for addr %s port %d from gateway %s\n", bind.ToStringAddr(), port, gateway.ToStringAddr());
```
Comment (davidgumberg) [inline src/util/pcp.cpp:83]: nit:
```suggestion
    LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "pcp: Requesting port mapping for addr %s port %d from gateway %s\n", bind.ToStringAddr(), port, gateway.ToStringAddr());
```

**Comment by luke-jr** [comment]
Would prefer this in two steps (add PCP, then remove NAT-PMP)

**Comment by laanwj** [comment]
> Would prefer this in two steps (add PCP, then remove NAT-PMP)

i'm not planning to do this, the build system commits are already set up this way, but doing it throughout would involve adding another setting in Qt just to remove it later. Same for adding a third mechanism in `portmap.cpp`. Agree with @sjors that having a forest of different port mapping settings is confusing to the user.

**Review by Sjors — COMMENTED** [review]
Tested on Ubuntu 24.04 I'm getting in bound via IPv4 and IPv6.

When a GUI user previously had NAT-PMP selected there would be a `"natpmp": true` field in `settings.json`.

We need to rename this to `"tcp"` in order for the box to remain checked.

Maybe @ryanofsky has an idea how to do this elegantly?

A little hack that works is to put the following at the end of `ReadSettings()` in `settings.cpp`: 

```cpp
    // Migrate settings:
    if (values.contains("natpmp")) {
        auto el = values.extract("natpmp");
        el.key() = "pcp";
        values.insert(std::move(el));
    }
```

A bit nicer would be to have a `MigrateSettingsFile()` that's called between `ReadSettingsFile` and `WriteSettingsFile` in `init.cpp`.

(not to be confused with `OptionsModel::checkAndMigrate()` which is called _before_ settings.json is read)

---

Maybe you can split `src/util/netif.h` off into a separate PR, along with b06edec229d5cfc8d0d1a19bd723852e6bcfd9d9.

**Comment by Sjors** [comment]
In terms of which IPv6 address to use, my understanding is this:

1. In the olden days the IPv6 address contained part of the MAC address. This ensured uniqueness, but was bad for mobile device privacy; no matter where you went, part of your IP address was constant. Such addresses always (?) contain `0xfffe`. See https://datatracker.ietf.org/doc/html/rfc7707
2. A new standard was introduced that uses a hash of both the MAC address and the prefix, ensuring it's stable if you stay on the same network, but changes when you move. See https://datatracker.ietf.org/doc/html/rfc7217#page-19
3. There's also temporary addresses, which are rotated every couple of hours. See https://datatracker.ietf.org/doc/html/rfc8981

If we were able to tell which one one is which, then I think we should pick only one, in order of preference: (2), (3), (1). This reflects our desire to actually get inbound connections, even after a shutdown, while at the same time not doxxing ourselves when on the move (mainly for laptops, perhaps mobile in the future).

We can easily detect type (1) by looking for `0xfffe` at the right position (and then least prefer it).

I believe you can detect (2) by looking for `IFA_F_STABLE_PRIVACY` in `flags` of the `inet6_ifaddr` struct. It seems `getifaddrs` doesn't have access to that. Neither does `/proc/net/if_inet6` since https://patchwork.ozlabs.org/project/netdev/patch/1386680189-7852-1-git-send-email-jiri@resnulli.us/

Afaik there's also no guarantee about the order of results.

So maybe we should just pick one at random rather than announce all three. This also seems orthogonal to PCP.

File: src/mapport.cpp [hunk 3]
```diff
@@ -47,105 +44,73 @@ static std::atomic<MapPortProtoFlag> g_mapport_current_proto{MapPortProtoFlag::N
...
-            if (private_port == pm.privateport && pm.lifetime > 0) {
-                g_mapport_external_port = pm.mappedpublicport;
-                const CService external{external_ipv4_addr, pm.mappedpublicport};
-                if (!external_ip_discovered && fDiscover) {
-                    AddLocal(external, LOCAL_MAPPED);
-                    external_ip_discovered = true;
+        // IPv6
+        std::optional<CNetAddr> gateway6 = QueryDefaultGateway(NET_IPV6);
+        if (!gateway6) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "pcp: Could not determine IPv6 default gateway\n");
```
Comment (Sjors) [inline src/mapport.cpp:87]: 6cf4809c6b93e1720dfdfe4e3320cfd8939686b6: This is `::Warning` worthy.

**Review by Sjors — COMMENTED** [review]
Regarding gateway discovery on macOS and Windows, the NatPMP C code is probably as good a place to start as any: https://github.com/miniupnp/libnatpmp/blob/master/getgateway.c

I tested that `-natpmp` works (before this PR) on macOS 14.4.1.

You already implemented the `USE_PROC_NET_ROUTE` approach, which unfortunately is the shortest of them.

Here's another one: https://github.com/libpcp/pcp/blob/master/libpcp/src/net/gateway.c

Life would be so much easier if RFC6887 had allowed you to send the request to some random destination on the internet and just have the router intercept it (with Hop Limit 1 for privacy).

One creative cross-platform way to find the default gateway is, like `traceroute`, to send an ICMP(v6) message towards a random IPv4/6 address (via TCP), with Hop Limit set to 1, wait for the `Destination Unreachable Message` response and get the origin IP. https://datatracker.ietf.org/doc/html/rfc792

If PCP servers announced themselves via DNS-Based Service Discovery [rfc6763](https://www.rfc-editor.org/rfc/rfc6763.html) that would also make things easier. But waiting for an amendment of / followup to rfc792 and all routers to implement it ... would take a while. And then you need support _that_ protocol (mostly fetching and parsing DNS TXT records).

**Comment by laanwj** [comment]
Thanks!

On Windows (Vista and higher, which is all we care about) getting the default gateway is straightforward, there's `GetBestRoute2` that does all the work. It's part of netioapi which we already need for interface enumeration. MacOS's sysctl is a bit uglier.

> If PCP servers announced themselves via DNS-Based Service Discovery [rfc6763](https://www.rfc-editor.org/rfc/rfc6763.html) that would also make things easier.

i don't think it really would, we'd need some special library for DNS access, getting TXT records isn't built into libc.

**Comment by laanwj** [comment]
> Maybe you can split src/util/netif.h off into a separate PR, along with https://github.com/bitcoin/bitcoin/commit/b06edec229d5cfc8d0d1a19bd723852e6bcfd9d9.

Sure, could do that.

> So maybe we should just pick one at random rather than announce all three. This also seems orthogonal to PCP.

Thanks, that's interesting.

One problem is that routers might fail to pinhole some of the addresses. For example, Fritz!Box refuses to open ports on temporary privacy ones, which aren't a distinguishable range or type (on purpose). Might end up having no open port at all, or only for a temporary address lifetime. So for this PR, i prefer to keep the "announce all publicly routable" that is the current `Discover()` behavior for now.

Fine with discussing changes to IPv6 address choosing behavior later, as you say, it's orthogonal to adding PCP.

File: src/mapport.cpp (hunk 3 above)
Comment (laanwj) [reply src/mapport.cpp:87]: It's hidden as debug because at the moment this is shown when the user doesn't have IPv6. Could boost this to warning if we do the address check first, then don't bother looking for a default gateway if there's none. Will do that.

File: src/qt/optionsdialog.cpp [hunk 4]
```diff
@@ -108,9 +108,7 @@ OptionsDialog::OptionsDialog(QWidget* parent, bool enableWallet)
 #ifndef USE_UPNP
     ui->mapPortUpnp->setEnabled(false);
 #endif
-#ifndef USE_NATPMP
-    ui->mapPortNatpmp->setEnabled(false);
-#endif
+    ui->mapPortPCP->setEnabled(false);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/qt/optionsdialog.cpp:111]: Whoops, yes, it's `setEnabled`.

File: src/mapport.cpp (hunk 3 above)
Comment (laanwj) [reply src/mapport.cpp:87]: Will keep this open but leave it as-is for now. For IPv4 i'm not currently sure how to check if we have (Internet) networking besides checking for a default gateway, and i'd like to keep the two paths reasonably symmetric. Just checking for publicly routable addresses isn't going to cut it for IPv4.

**Comment by laanwj** [comment]
- Rebased for a trivial merge conflict related to clang installation in `.github/workflows/ci.yml`.
- Addressed a few comments.

File: src/util/netif.cpp [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+#include <netbase.h>
+#include <util/readwritefile.h>
+#include <util/sock.h>
+#include <util/strencodings.h>
+
+#ifdef HAVE_LINUX_ROUTE_H
+
+#include <linux/route.h>
+
+std::optional<CNetAddr> QueryDefaultGateway(Network network)
```
Comment (vasild) [inline src/util/netif.cpp:19]: The following patch uses a netlink socket to get the information from the kernel, that is supported on (at least) Linux and FreeBSD>=13.2:

<details>
<summary>[patch] get default gateway using a netlink socket</summary>

```diff
--- a/src/test/netbase_tests.cpp
+++ b/src/test/netbase_tests.cpp
@@ -1,25 +1,34 @@
 // Copyright (c) 2012-2022 The Bitcoin Core developers
 // Distributed under the MIT software license, see the accompanying
 // file COPYING or http://www.opensource.org/licenses/mit-license.php.
 
+#include <compat/compat.h>
 #include <net_permissions.h>
 #include <netaddress.h>
 #include <netbase.h>
 #include <netgroup.h>
 #include <protocol.h>
 #include <serialize.h>
 #include <streams.h>
 #include <test/util/setup_common.h>
 #include <util/strencodings.h>
+#include <util/syserror.h>
 #include <util/translation.h>
 
 #include <string>
 
 #include <boost/test/unit_test.hpp>
 
+#ifdef __linux__
+#include <linux/rtnetlink.h>
+#elif defined(__FreeBSD__)
+#include <netlink/netlink.h>
+#include <netlink/netlink_route.h>
+#endif
+
 using namespace std::literals;
 
 BOOST_FIXTURE_TEST_SUITE(netbase_tests, BasicTestingSetup)
 
 static CNetAddr ResolveIP(const std::string& ip)
 {
@@ -610,7 +619,100 @@ BOOST_AUTO_TEST_CASE(isbadport)
             ++total_bad_ports;
         }
     }
     BOOST_CHECK_EQUAL(total_bad_ports, 80);
 }
 
+std::optional<CNetAddr> QueryDefaultGateway(Network network)
+{
+    Assume(network == NET_IPV4 || network == NET_IPV6);
+
+    // Create a netlink socket.
+
+    const int s{socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE)};
+    if (s < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "socket(AF_NETLINK): %s\n", SysErrorString(errno));
+        return std::nullopt;
+    }
+    Sock sock{static_cast<SOCKET>(s)};
+
+    // Send request.
+
+    struct {
+        nlmsghdr hdr; ///< Request header.
+        rtmsg data; ///< Request data, a "route message".
+        nlattr dst_hdr; ///< One attribute, conveying the route destination address.
+        char dst_data[16]; ///< Route destination address. To query the default route we use 0.0.0.0/0 or [::]/0. For IPv4 the first 4 bytes are used.
+    } request;
+
+    // Whether to use the first 4 or 16 bytes from request.attr_dst_data.
+    const size_t dst_data_len = network == NET_IPV4 ? 4 : 16;
+
+    memset(&request, 0x0, sizeof(request));
+
+    request.hdr.nlmsg_type = RTM_GETROUTE;
+    request.hdr.nlmsg_flags = NLM_F_REQUEST;
+#ifdef __linux__
+    request.hdr.nlmsg_flags |= NLM_F_DUMP;
+#endif
+    request.hdr.nlmsg_len = NLMSG_LENGTH(sizeof(rtmsg) + sizeof(nlattr) + dst_data_len);
+    request.hdr.nlmsg_seq = 0; // Sequence number, used to match which reply is to which request. Irrelevant for us because we send just one request.
+    request.data.rtm_family = network == NET_IPV4 ? AF_INET : AF_INET6;
+    request.data.rtm_dst_len = 0; // Prefix length.
+#ifdef __FreeBSD__
+    request.data.rtm_flags = RTM_F_PREFIX;
+#endif
+    request.dst_hdr.nla_type = RTA_DST;
+    request.dst_hdr.nla_len = sizeof(nlattr) + dst_data_len;
+
+    if (sock.Send(&request, sizeof(request), 0) != sizeof(request)) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "send() to netlink socket: %s\n", SysErrorString(errno));
+        return std::nullopt;
+    }
+
+    // Receive response.
+
+    char response[4096];
+    ssize_t response_len;
+    do {
+        response_len = sock.Recv(response, sizeof(response), 0);
+    } while (response_len < 0 && (errno == EINTR || errno == EAGAIN));
+    if (response_len < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "recv() from netlink socket: %s\n", SysErrorString(errno));
+        return std::nullopt;
+    }
+
+    for (nlmsghdr* hdr = (nlmsghdr*)response; NLMSG_OK(hdr, response_len); hdr = NLMSG_NEXT(hdr, response_len)) {
+        rtmsg* r = (rtmsg*)NLMSG_DATA(hdr);
+        int remaining_len = RTM_PAYLOAD(hdr);
+        // Iterate over the attributes.
+        for (rtattr* attr = RTM_RTA(r); RTA_OK(attr, remaining_len); attr = RTA_NEXT(attr, remaining_len)) {
+            if (attr->rta_type == RTA_GATEWAY) {
+                if (network == NET_IPV4) {
+                    Assume(sizeof(in_addr) == RTA_PAYLOAD(attr));
+                    return CNetAddr{in_addr{.s_addr = *static_cast<decltype(in_addr::s_addr)*>(RTA_DATA(attr))}};
+                } else {
+                    Assume(sizeof(in6_addr) == RTA_PAYLOAD(attr));
+                    in6_addr gw;
+                    std::memcpy(&gw, RTA_DATA(attr), sizeof(gw));
+                    return CNetAddr{gw};
+                }
+            }
+        }
+    }
+
+    return std::nullopt;
+}
+
+BOOST_AUTO_TEST_CASE(netlink)
+{
+    for (const auto net : {NET_IPV4, NET_IPV6}) {
+        const auto gw{QueryDefaultGateway(net)};
+        if (gw.has_value()) {
+            printf("Default %s gateway: %s\n", GetNetworkName(net).c_str(), gw->ToStringAddr().c_str());
+        } else {
+            printf("No %s default gateway.\n", GetNetworkName(net).c_str());
+        }
+    }
+}
+
 BOOST_AUTO_TEST_SUITE_END()
```
</details>

I find the netlink interface a somewhat difficult to grasp.

https://man7.org/linux/man-pages/man7/netlink.7.html
https://man7.org/linux/man-pages/man7/rtnetlink.7.html
https://man7.org/linux/man-pages/man3/rtnetlink.3.html
https://stackoverflow.com/questions/11788326/extract-current-route-from-netlink-message-code-attached
https://www.rfc-editor.org/rfc/rfc3549

**Review by vasild — COMMENTED** [review]
Concept ACK

File: src/util/netif.cpp (hunk 5 above)
Comment (laanwj) [reply src/util/netif.cpp:19]: Huh interesting. i didn't know netlink worked for multiple operating systems, that's much better.

Comment (laanwj) [reply src/util/netif.cpp:19]: Is it possible to get the `scope_id` for IPv6 addresses? At least my router gives me an link-scope address.

**Comment by laanwj** [comment]
Added a (mostly untested for now) Windows implementation of `QueryDefaultGateway`, if someone could test this it'd be very helpful. i will try in WINE later.

File: src/util/netif.cpp (hunk 5 above)
Comment (vasild) [reply src/util/netif.cpp:24]: Here is a standalone program to get the default gateway using a netlink socket:

<details>
<summary>netlink_get_default_route.cc</summary>

```cc
#include <arpa/inet.h>
#include <assert.h>
#include <errno.h>
#include <net/if.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#ifdef __linux__
#include <linux/rtnetlink.h>
#elif defined(__FreeBSD__)
#include <netlink/netlink.h>
#include <netlink/netlink_route.h>
#endif

void QueryDefaultGateway(sa_family_t family)
{
    // Create a netlink socket.

    int sock = socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE);
    if (sock < 0) {
        perror("socket(AF_NETLINK)");
        return;
    }

    // Send request.

    struct {
        nlmsghdr hdr; ///< Request header.
        rtmsg data; ///< Request data, a "route message".
        nlattr dst_hdr; ///< One attribute, conveying the route destination address.
        char dst_data[16]; ///< Route destination address. To query the default route we use 0.0.0.0/0 or [::]/0. For IPv4 the first 4 bytes are used.
    } request{};

    // Whether to use the first 4 or 16 bytes from request.attr_dst_data.
    const size_t dst_data_len = family == AF_INET ? 4 : 16;

    request.hdr.nlmsg_type = RTM_GETROUTE;
    request.hdr.nlmsg_flags = NLM_F_REQUEST;
#ifdef __linux__
    // XXX some strange behavior:
    // Linux IPv4 - this must be present, otherwise no gateway is found
    // Linux IPv6 - this must be present, otherwise no gateway is found
    // FreeBSD IPv4 - does not matter, the gateway is found with or without this
    // FreeBSD IPv6 - this must be absent, otherwise no gateway is found
    request.hdr.nlmsg_flags |= NLM_F_DUMP;
#endif
    request.hdr.nlmsg_len = NLMSG_LENGTH(sizeof(rtmsg) + sizeof(nlattr) + dst_data_len);
    request.hdr.nlmsg_seq = 0; // Sequence number, used to match which reply is to which request. Irrelevant for us because we send just one request.
    request.data.rtm_family = family;
    request.data.rtm_dst_len = 0; // Prefix length.
    //request.data.rtm_table = RT_TABLE_MAIN;
    //request.data.rtm_protocol = RTPROT_STATIC;
    //request.data.rtm_scope = RT_SCOPE_UNIVERSE;
    //request.data.rtm_type = RTN_UNICAST;
#ifdef __FreeBSD__
    // XXX some strange behavior:
    // Linux IPv4 - this must be absent, otherwise no gateway is found
    // Linux IPv6 - this must be absent, otherwise no gateway is found
    // FreeBSD IPv4 - does not matter, the gateway is found with or without this
    // FreeBSD IPv6 - this must be present, otherwise no gateway is found
    request.data.rtm_flags = RTM_F_PREFIX;
#endif
    request.dst_hdr.nla_type = RTA_DST;
    request.dst_hdr.nla_len = sizeof(nlattr) + dst_data_len;

    if (send(sock, &request, request.hdr.nlmsg_len, 0) != request.hdr.nlmsg_len) {
        fprintf(stderr, "send() failed to send %u bytes\n", request.hdr.nlmsg_len);
        close(sock);
        return;
    }

    // Receive response.

    char response[4096];
    ssize_t response_len;
    do {
        response_len = recv(sock, response, sizeof(response), 0);
    } while (response_len < 0 && (errno == EINTR || errno == EAGAIN));
    if (response_len < 0) {
        fprintf(stderr, "recv(): %s\n", strerror(errno));
        close(sock);
        return;
    }

    for (nlmsghdr *hdr = (nlmsghdr*)response; NLMSG_OK(hdr, response_len); hdr = NLMSG_NEXT(hdr, response_len)) {
        rtmsg* r = (rtmsg*)NLMSG_DATA(hdr);
        int remaining_len = RTM_PAYLOAD(hdr);

        // Iterate over the attributes.
        rtattr* rta_gateway = nullptr;
        int scope_id = 0;
        for (rtattr *attr = RTM_RTA(r); RTA_OK(attr, remaining_len); attr = RTA_NEXT(attr, remaining_len)) {
            if (attr->rta_type == RTA_GATEWAY) {
                rta_gateway = attr;
            } else if (attr->rta_type == RTA_OIF) {
                assert(sizeof(int) == RTA_PAYLOAD(attr));
                memcpy(&scope_id, RTA_DATA(attr), sizeof(scope_id));
            }
        }

        // Found gateway?
        if (rta_gateway != nullptr) {
            char buf[256];
            printf("%s gateway: %s",
                   family == AF_INET ? "IPv4" : "IPv6",
                   inet_ntop(r->rtm_family, RTA_DATA(rta_gateway), buf, sizeof(buf)));
            if (family == AF_INET6) {
                printf(", scope id: %d\n", scope_id);
            } else {
                printf("\n");
            }
        }
    }

    close(sock);
}

int main(int argc, char** argv)
{
    QueryDefaultGateway(AF_INET);
    QueryDefaultGateway(AF_INET6);
    return 0;
}
```
</details>

Ideally the `#ifdef __linux__` / `#ifdef __FreeBSD__` parts should not be needed. I am not sure if this is due to the above program doing something wrong or is due to a difference in Linux vs FreeBSD implementations. @AlexanderChernikov, @markjdb, any ideas?

File: src/util/netif.cpp [hunk 6]
```diff
@@ -0,0 +1,206 @@
...
+    request.data.rtm_family = network == NET_IPV4 ? AF_INET : AF_INET6;
+    request.data.rtm_dst_len = 0; // Prefix length.
+#ifdef __FreeBSD__
+    request.data.rtm_flags = RTM_F_PREFIX;
+#endif
+    request.dst_hdr.nla_type = RTA_DST;
+    request.dst_hdr.nla_len = sizeof(nlattr) + dst_data_len;
+
+    if (sock.Send(&request, sizeof(request), 0) != sizeof(request)) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "send() to netlink socket: %s\n", SysErrorString(errno));
```
Comment (vasild) [inline src/util/netif.cpp:63]: I realized that in the IPv4 case this would send the trailing 16-4=12 bytes from `request.dst_data[]`. This seems harmless, but better send exactly what's needed:

```suggestion
    if (sock.Send(&request, request.hdr.nlmsg_len, 0) != request.hdr.nlmsg_len) {
        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "send() to netlink socket: %s\n", SysErrorString(errno));
```

Also, I am not sure if we should worry about partial writes with netlink sockets, maybe the send can be interrupted? There is a convenience method `Sock::SendComplete()`:

```cc
    try {
        CThreadInterrupt intr;
        sock.SendComplete(Span{reinterpret_cast<const unsigned char*>(&request), request.hdr.nlmsg_len}, 5s, intr);
    } catch (const std::runtime_error& e) {
        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "writing to netlink socket: %s\n", e.what());
        return std::nullopt;
    }
```

Comment (laanwj) [reply src/util/netif.cpp:63]: It's a datagram (packet socket), so *partial* writes and reads cannot happen. Every packet is interpreted as a new one. Using `SendComplete` would be a bug.

Truncated and corrupted packets could happen in the case of UDP, but as NETLINK is a communication interface with the kernel, that would be rare. No retries are needed. Would still want to detect it and error out gracefully, though, for robustness.

**Comment by laanwj** [comment]
i have no idea, also no idea how to get that information; to be honest if we can remotely avoid it, i'd prefer not to implement unnecessary compatibility stuff, this is already a lot to ask people to review as-is.

**Comment by laanwj** [comment]
> Yeah, fair enough. Absent any reports of "doesn't work on my router while nat-pmp worked" (which we're quite unlikely to get) there is really no way to assess that.

For what it's worth, initial support for PCP was added in miniupnpd in [2013](https://github.com/miniupnp/miniupnp/commit/9e1ffd5cd9836053cfd83d95014c729ad0e36872). So the implementation wasn't lagging much behind the standard. Of course, not all routers use miniupnpd but it's extremely common.

**Comment by laanwj** [comment]
MacOS implementation of default gateway finding was added as well (i've tested it on MacOS Monterey, but could always use more). This concludes the coverage of default gateway-finding on the major platforms.

**Comment by laanwj** [comment]
Squashed all fixme's into their logical commit. This should be in a good state for review now. The only TODO that is left to do is the Qt settings migration, i could use some help with that because i don't really know the new mechanism.

**Comment by laanwj** [comment]
> Trying this with -pcp=1 on my home internet connection:

Thanks for testing!
The received packet is not a valid PCP response (too short). But interpreting it as one anyway, the version byte is 0x00, result code is 0x01 (UNSUPP_VERSION). So you might have one of those routers that supports NAT-PMP only.

**Comment by laanwj** [comment]
> @laanwj This is a router provided by Verizon (a large US ISP) in 2021.

That's curious, especially as NAT-PMP doesn't have any IPv6 support. i'm assuming you don't have any output for IPv6?

**Comment by laanwj** [comment]
> The only TODO that is left to do is the Qt settings migration 

Avoiding this complexity is another reason to add a NAT-PMP fallback, then we'd be right to keep the option named the same and only change the descriptions.

**Comment by Sjors** [comment]
> Avoiding this complexity is another reason to add a NAT-PMP fallback, then we'd be right to keep the option named the same and only change the descriptions.

If you think such a fallback is easier than dealing with QT settings migration :-)

We can just sort them PCP, NAT-PMP, UPNP in the GUI. If we also add the word "recommended" to PCP, it should mitigate choice-paralysis. Then in the future we can add a little green dot to indicate that it actually works.

I can test on Windows, (Intel) macOS and Linux.

**Comment by laanwj** [comment]
> If you think such a fallback is easier than dealing with QT settings migration :-)

Yes. It also avoids having to rename the command-line option. It would make the new code a drop-in replacement that also supports IPv6, no change for users.

**Comment by Sjors** [comment]
Restarting the node with the same port seems to trigger the `NO_RESOURCES` error with IPv6. I guess that's because the previous "lease" is still valid.

**Comment by Sjors** [comment]
If we auto-renew every 20 minutes then I guess that's fine. Maybe just add a comment somewhere that we _could_ explicitly close the mapping upon shutdown.

File: src/util/netif.cpp [hunk 7]
```diff
@@ -0,0 +1,275 @@
...
+#include <config/bitcoin-config.h> // IWYU pragma: keep
+
+#include <util/netif.h>
+
+#include <logging.h>
+#include <netbase.h>
+#include <util/check.h>
+#include <util/sock.h>
+#include <util/syserror.h>
+
```
Comment (Sjors) [inline src/util/netif.cpp:14]: bebfafcf98d8ed1432407b7603991d54f7cc26c2: it would be useful to have a quick recap here of which strategy is used by `QueryDefaultGateway` for which OS.

I think it will be (slightly) more readable to have a single `QueryDefaultGateway` implementation which then calls `QueryDefaultGatewayWindows`, `QueryDefaultGatewayMac` and `QueryDefaultGatewayLinuxBSD`.

It can start with:

```cpp
Assume(network == NET_IPV4 || network == NET_IPV6)
```

and end with

```cpp
#else return std::nullopt;
```

File: src/util/netif.cpp [hunk 8]
```diff
@@ -0,0 +1,275 @@
...
+#if defined(__linux__) || defined(__FreeBSD__)
+
+#if defined(__linux__)
+#include <linux/rtnetlink.h>
+#elif defined(__FreeBSD__)
```
Comment (Sjors) [inline src/util/netif.cpp:19]: Presumably this only exists in (the rather recent) FreeBSD >= 13.2? For older versions we need to use the same method as macOS? If so, then we probably need to check this stuff in configure.

Comment (Sjors) [reply src/util/netif.cpp:19]: That said, it looks like FreeBSD 12 is pretty much unusable: https://forums.freebsd.org/threads/freebsd-12-2-stable-pkg-update-failed.92034/#post-640223

Comment (laanwj) [reply src/util/netif.cpp:19]: If so i would prefer not supporting it at all for older FreeBSD. It's so rare compared to the other operating systems already, and most of the userbase will be setting their own firewall. But we indeed need to check that it doesn't cause a compilation error.

**Comment by laanwj** [comment]
Okay - added a NAT-PMP fallback and removed all user visible option changes, except for documentation.

File: src/init.cpp [hunk 9]
```diff
@@ -556,11 +556,7 @@ void SetupServerArgs(ArgsManager& argsman)
 #else
     hidden_args.emplace_back("-upnp");
 #endif
-#ifdef USE_NATPMP
-    argsman.AddArg("-natpmp", strprintf("Use NAT-PMP to map the listening port (default: %u)", DEFAULT_NATPMP), ArgsManager::ALLOW_ANY, OptionsCategory::CONNECTION);
-#else
-    hidden_args.emplace_back("-natpmp");
-#endif // USE_NATPMP
+    argsman.AddArg("-natpmp", strprintf("Use PCP or NATPMP to map the listening port (default: %u)", DEFAULT_NATPMP), ArgsManager::ALLOW_ANY, OptionsCategory::CONNECTION);
```
Comment (Sjors) [inline src/init.cpp:559]: Concept ACK on keep just using `-natpmp` for both PCP and NATPMP.

Comment (laanwj) [reply src/init.cpp]: Whoops, fixed

File: src/util/netif.cpp (hunk 8 above)
Comment (laanwj) [reply src/util/netif.cpp:20]: Added a version check for at least 13.2.

File: src/util/netif.cpp [hunk 10]
```diff
@@ -0,0 +1,275 @@
...
+#endif
+
+std::optional<CNetAddr> QueryDefaultGateway(Network network)
+{
+    Assume(network == NET_IPV4 || network == NET_IPV6);
+
+    // Create a netlink socket.
+    const int s{socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE)};
+    if (s < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "socket(AF_NETLINK): %s\n", SysErrorString(errno));
```
Comment (Sjors) [inline src/util/netif.cpp:32]: 82b0bff51fedff2ce5e47cae1c75b9172766d8ef: the `SysErrorString` documentation says you should call `NetworkErrorString`, though that will in turn just call `SysErrorString`, since this is never called under `WIN32`.

File: src/util/netif.cpp [hunk 11]
```diff
@@ -0,0 +1,275 @@
...
+        char dst_data[16]; ///< Route destination address. To query the default route we use 0.0.0.0/0 or [::]/0. For IPv4 the first 4 bytes are used.
+    } request{};
+
+    // Whether to use the first 4 or 16 bytes from request.attr_dst_data.
+    const size_t dst_data_len = network == NET_IPV4 ? 4 : 16;
+
+    request.hdr.nlmsg_type = RTM_GETROUTE;
+    request.hdr.nlmsg_flags = NLM_F_REQUEST;
+#ifdef __linux__
+    request.hdr.nlmsg_flags |= NLM_F_DUMP;
```
Comment (Sjors) [inline src/util/netif.cpp:51]: 82b0bff51fedff2ce5e47cae1c75b9172766d8ef Why only on linux? It seems to exist on FreeBSD too: https://man.freebsd.org/cgi/man.cgi?netlink(4)

File: src/util/netif.cpp [hunk 12]
```diff
@@ -0,0 +1,275 @@
...
+#endif
+    request.hdr.nlmsg_len = NLMSG_LENGTH(sizeof(rtmsg) + sizeof(nlattr) + dst_data_len);
+    request.hdr.nlmsg_seq = 0; // Sequence number, used to match which reply is to which request. Irrelevant for us because we send just one request.
+    request.data.rtm_family = network == NET_IPV4 ? AF_INET : AF_INET6;
+    request.data.rtm_dst_len = 0; // Prefix length.
+#ifdef __FreeBSD__
+    request.data.rtm_flags = RTM_F_PREFIX;
```
Comment (Sjors) [inline src/util/netif.cpp:58]: 82b0bff51fedff2ce5e47cae1c75b9172766d8ef: any idea what this does?

File: src/util/netif.cpp [hunk 13]
```diff
@@ -0,0 +1,275 @@
...
+        rtmsg* r = (rtmsg*)NLMSG_DATA(hdr);
+        int remaining_len = RTM_PAYLOAD(hdr);
+
+        // Iterate over the attributes.
+        rtattr *rta_gateway = nullptr;
+        int scope_id = 0;
+        for (rtattr* attr = RTM_RTA(r); RTA_OK(attr, remaining_len); attr = RTA_NEXT(attr, remaining_len)) {
+            if (attr->rta_type == RTA_GATEWAY) {
+                rta_gateway = attr;
+            } else if (attr->rta_type == RTA_OIF) {
```
Comment (Sjors) [inline src/util/netif.cpp:90]: 82b0bff51fedff2ce5e47cae1c75b9172766d8ef: IIUC this gets the scope id (https://datatracker.ietf.org/doc/html/rfc4007), but we don't do anything with that except in `IPv6ToString`. So maybe we should just ignore this value (`CNetAddr` initialiser defaults it to 0).

If we can't drop it, can we be sure that we encounter `RTA_OIF` _before_ `RTA_GATEWAY`? Otherwise `if (rta_gateway != nullptr)` could trigger prematurely.

**Review by Sjors — COMMENTED** [review]
Took a cursory look at the linux / bsd approach.

File: src/util/netif.cpp (hunk 13 above)
Comment (Sjors) [reply src/util/netif.cpp:90]: I see this was added here: https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1603876259

Comment (laanwj) [reply src/util/netif.cpp:90]: The scope ID is extremely important for the default gateway, as it tends to be a scope-local address.

Comment (laanwj) [reply src/util/netif.cpp:90]: > If we can't drop it, can we be sure that we encounter RTA_OIF before RTA_GATEWAY? Otherwise if (rta_gateway != nullptr) could trigger prematurely.

AFAIK the order of the attributes within a record can be arbitrary. But how can this go wrong? The `rta_gateway` check is only after going over all the attributes, right?

File: src/util/netif.cpp (hunk 10 above)
Comment (laanwj) [reply src/util/netif.cpp:32]: Right, will update this (though yeah for POSIX operating systems there's no difference).

File: src/util/netif.cpp (hunk 11 above)
Comment (laanwj) [reply src/util/netif.cpp:51]: For the FreeBSD versus Linux differences see the comments in the standalone tool here: https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1604635967
The netlink calls behave differently on Linux and FreeBSD, we don't know why this is.

File: src/util/netif.cpp (hunk 13 above)
Comment (Sjors) [reply src/util/netif.cpp:90]: > The rta_gateway check is only after going over all the attributes, right?

Oh wait, I misread the indentation, yes.

Comment (Sjors) [reply src/util/netif.cpp:90]: > The scope ID is extremely important for the default gateway, as it tends to be a scope-local address.

Aha: https://blogs.infoblox.com/ipv6-coe/fe80-1-is-a-perfectly-valid-ipv6-default-gateway-address/

File: src/util/netif.cpp (hunk 11 above)
Comment (Sjors) [reply src/util/netif.cpp:51]: Ah, some of these comments are worth preserving until we know more or can point to clear documentation elsewhere. I compressed them a bit:

```
    // Linux IPv4 / IPv6 - this must be present, otherwise no gateway is found
    // FreeBSD IPv4 - does not matter, the gateway is found with or without this
    // FreeBSD IPv6 - this must be absent, otherwise no gateway is found
    request.hdr.nlmsg_flags |= NLM_F_DUMP;

#ifdef __FreeBSD__
    // Linux IPv4 / IPv6 this must be absent, otherwise no gateway is found
    // FreeBSD IPv4 - does not matter, the gateway is found with or without this
    // FreeBSD IPv6 - this must be present, otherwise no gateway is found
    request.data.rtm_flags = RTM_F_PREFIX;

```

Comment (laanwj) [reply src/util/netif.cpp:51]: Sure, will add that.
FWIW, this is why i initially went with parsing the route tables from `/proc/net/...`, for Linux that's the most straightforward implementation. Netlink is a bit finnicky, though it should be stable (for the same OS) because it's what the tools like `ip` use.

**Comment by laanwj** [comment]
> Success! My node is reachable publicly, without configuration.

Nice!!! Thanks for testing again.

File: src/util/netif.cpp [hunk 14]
```diff
@@ -0,0 +1,275 @@
...
+        destination_address.si_family = AF_INET;
+    } else if(network == NET_IPV6) {
+        destination_address.si_family = AF_INET6;
+    } else {
+        return std::nullopt;
+    }
+
+    status = GetBestInterfaceEx((sockaddr*)&destination_address, &best_if_idx);
+    if (status != NO_ERROR) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "Could not get best interface for default route: %s\n", SysErrorString(status));
```
Comment (Sjors) [inline src/util/netif.cpp:146]: Unlike the linux code, here it does matter to call `NetworkErrorString`, because it calls `Win32ErrorString`, which calls `FormatMessage(W)` as the docs recommend: https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestinterfaceex  

My understanding is that using `strerror_s` (called by SysErrorString) here would be wrong:  https://stackoverflow.com/a/20057368

I wonder if we can prevent doing that by accident.

Comment (Sjors) [reply src/util/netif.cpp:146]: That said, this Windows code is a lot simpler than the Linux stuff above (ducks...).

Comment (laanwj) [reply src/util/netif.cpp:146]: OHH, my thinking was that it's a WIN32 API function, not a network function. So i thought `SysErrorString` would be correct. But i think you're right. "SysError" is more like "posix errno emulation error". Which is not what is needed here.

Comment (laanwj) [reply src/util/netif.cpp:146]: > That said, this Windows code is a lot simpler than the Linux stuff above (ducks...).

You mean that centrally-controlled proprietary OSes sometimes have well-documented API's that consider use-cases, while FOSS often uses haphazard grabbag API's that were grown in accordance with one tool (where everyone is expected to parse text output of-)... or some custom library, with equally confusing interface. you can just say that out loud here you know... 😓 
Standards like RFCs, and POSIX (ignoring everyone's custom extensions) are rare exceptions.

File: src/util/netif.cpp [hunk 15]
```diff
@@ -0,0 +1,275 @@
...
+}
+
+std::optional<CNetAddr> QueryDefaultGateway(Network network)
+{
+    // MacOS: Get default gateway from route table.
+    // See man page for route(4) for the format.
+    Assume(network == NET_IPV4 || network == NET_IPV6);
+    int family;
+    if (network == NET_IPV4) {
+        family = AF_INET;
```
Comment (Sjors) [inline src/util/netif.cpp:195]: Alternatively you could store `net.route.0.inet[4].flags.gateway` here and use `sysctlbyname` below, avoiding the need to construct `mib[]`. Not sure if that's better though, because it's nice to be able to lookup constants like `NET_RT_FLAGS` in headers.

Comment (laanwj) [reply src/util/netif.cpp:195]: i prefer using constants to string based APIs, if given the choice. This avoids say, typos.

File: src/util/netif.cpp [hunk 16]
```diff
@@ -0,0 +1,275 @@
...
+    // Leave interface_luid at all-zeros to use interface index instead.
+    status = GetBestRoute2(&interface_luid, best_if_idx, nullptr, &destination_address, 0, &best_route, &best_source_address);
+    if (status != NO_ERROR) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "Could not get best route for default route for interface index %d: %s\n",
+                best_if_idx, SysErrorString(status));
+        return std::nullopt;
+    }
+
+    if (network == NET_IPV4) {
+        Assume(best_route.NextHop.si_family == AF_INET);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:160]: OK, you're right, this could happen: https://learn.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_ipforward_row2

> NextHop
>
> Type: [SOCKADDR_INET](https://learn.microsoft.com/en-us/windows/desktop/api/ws2ipdef/ns-ws2ipdef-sockaddr_inet)
>
> For a remote route, the IP address of the next system or gateway en route. If the route is to a local loopback address or an IP address on the local link, the next hop is unspecified (all zeros). For a local loopback route, this member should be an IPv4 address of 0.0.0.0 for an IPv4 route entry or an IPv6 address of 0::0 for an IPv6 route entry.

File: src/util/netif.cpp (hunk 15 above)
Comment (laanwj) [reply src/util/netif.cpp:195]: Seems we could factor out `AddressFamilyFromNetwork` at least, this is repeated in literally every implementation 😄

File: src/util/netif.cpp (hunk 7 above)
Comment (laanwj) [reply src/util/netif.cpp:14]: OK, i went for `QueryDefaultGatewayImpl` for now, with an outer function. Naming it different things on different platforms means having to repeat the `#ifdef` forest, which isn't really worth the slight increase in clarity imo.

File: src/util/netif.cpp [hunk 17]
```diff
@@ -0,0 +1,287 @@
...
+    }
+    std::vector<std::byte> buf(l);
+    if (sysctl(mib, sizeof(mib) / sizeof(int), buf.data(), &l, 0, 0) < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "Could not get sysctl data of routing table: %s\n", SysErrorString(errno));
+        return std::nullopt;
+    }
+    const struct rt_msghdr* rt = nullptr;
+    for (const std::byte* p = buf.data(); p < buf.data() + buf.size(); p += rt->rtm_msglen) {
+        // Iterate over routing entry addresses, get destination and gateway (if present).
+        rt = (const struct rt_msghdr*)p;
```
Comment (Sjors) [inline src/util/netif.cpp:197]: Do we want to check `rt->rtm_errno` first?

File: src/util/netif.cpp [hunk 18]
```diff
@@ -0,0 +1,287 @@
...
+        const struct sockaddr* sa = (const struct sockaddr*)(rt + 1);
```
Comment (Sjors) [inline src/util/netif.cpp:198]:
```cpp
// We only read from this address if a rtm_addrs bit flag is set.
```

File: src/util/netif.cpp [hunk 19]
```diff
@@ -0,0 +1,287 @@
...
+        std::optional<CNetAddr> dst;
+        std::optional<CNetAddr> gateway;
+        for (int i = 0; i < RTAX_MAX; i++) {
+            if (rt->rtm_addrs & (1 << i)) {
+                if (i == RTAX_DST) {
+                    dst = FromSockAddr(sa);
+                } else if (i == RTAX_GATEWAY) {
+                    gateway = FromSockAddr(sa);
+                }
```
Comment (Sjors) [inline src/util/netif.cpp:207]:
```cpp
// Skip sockaddr entries for bit flags we're not interested in,
// move cursor.
```

File: src/util/netif.cpp [hunk 20]
```diff
@@ -0,0 +1,287 @@
...
+                sa = (const struct sockaddr*)((std::byte*)sa + ROUNDUP(sa->sa_len));
```
Comment (Sjors) [inline src/util/netif.cpp:208]: This seems quite brittle and I don't fully understand it. I did test that it seems necessary, e.g. doing `sa++;` causes it to not map IPv6 ports. If I look at `struct sockaddr_storage` I'm seeing `_SS_ALIGNSIZE   (sizeof(__int64_t)`, but using `uint64_t` instead of `uint32_t` in your `ROUNDUP` also doesn't work.

**Review by Sjors — COMMENTED** [review]
Finished macOS review of QueryDefaultGatewayImpl.

File: src/util/netif.cpp (hunk 20 above)
Comment (laanwj) [reply src/util/netif.cpp:208]: i'm not sure either, i see it in some other libraries, but no alignment is mentioned in the manual page for `route` at all. Leaving out `ROUNDUP` works fine btw. Might just delete it.

File: src/util/netif.cpp [hunk 21]
```diff
@@ -0,0 +1,287 @@
...
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "Could not get sysctl length of routing table: %s\n", SysErrorString(errno));
+        return std::nullopt;
+    }
+    std::vector<std::byte> buf(l);
+    if (sysctl(mib, sizeof(mib) / sizeof(int), buf.data(), &l, 0, 0) < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "Could not get sysctl data of routing table: %s\n", SysErrorString(errno));
+        return std::nullopt;
+    }
+    const struct rt_msghdr* rt = nullptr;
+    for (const std::byte* p = buf.data(); p < buf.data() + buf.size(); p += rt->rtm_msglen) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:195]: i don't think so, the pointer needs to advance by the size of the specific message, which is part of that message.

File: src/util/netif.cpp [hunk 22]
```diff
@@ -0,0 +1,287 @@
...
+
+static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t family)
+{
+    // MacOS: Get default gateway from route table.
+    // See man page for route(4) for the format.
+
+    // net.route.0.inet[6].flags.gateway
+    int mib[] = {CTL_NET, PF_ROUTE, 0, family, NET_RT_FLAGS, RTF_GATEWAY};
+    size_t l = 0;
+    if (sysctl(mib, sizeof(mib) / sizeof(int), 0, &l, 0, 0) < 0) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:185]: i'm not sure it makes sense to duplicate documentation that's already in the manual pages. Like if we're doing this here, why not for every system call we make. Do parameter names like `*newp=` `oldp=` even elucidate much?

Agree re using `nullptr` where possible.

File: src/util/netif.cpp (hunk 18 above)
Comment (laanwj) [reply src/util/netif.cpp:198]: Yes, it's a minor optimization, we could always construct a CNetAddr if we wanted, but if we know we're not going to use it anyway might as well skip it.

File: src/util/netif.cpp (hunk 17 above)
Comment (laanwj) [reply src/util/netif.cpp:197]: Well, i guess it wouldn't hurt checking (or adding an `Assume`), but i don't think the routing table is supposed to contain error entries.

File: src/util/netif.cpp (hunk 20 above)
Comment (Sjors) [reply src/util/netif.cpp:208]: > Also they're variable-length

That makes sense. Whereas `rt_msghdr` is fixed length I guess, so you're able to use `rt + 1` above.

File: src/util/netif.cpp (hunk 17 above)
Comment (Sjors) [reply src/util/netif.cpp:193]: Mmm, I thought perhaps it would return a single error entry to indicate failure.

File: src/util/netif.cpp (hunk 22 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:181]: `oldlenp=` does because it's key to the trick of how we get the length first. I find these variable name hints useful to e.g. search for them.

File: src/util/pcp.cpp [hunk 23]
```diff
@@ -0,0 +1,517 @@
...
+    uint8_t response[PCP_MAX_SIZE];
+    bool got_response = false;
+    int recvsz = 0;
+    for (int ntry = 0; !got_response && ntry < num_tries; ++ntry) {
+        if (ntry > 0) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "%s: Retrying (%d)\n", protocol, ntry);
+        }
+        // Dispatch packet to gateway.
+        if (sock.Send(request.data(), request.size(), 0) != static_cast<ssize_t>(request.size())) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "%s: Could not send request: %s\n", protocol, NetworkErrorString(WSAGetLastError()));
```
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/pcp.cpp:228]: Update: this happens when I'm connected with a physical LAN cable _and_ wifi. So the warning was safe to ignore, but I'm still curious about it.

File: src/util/netif.cpp (hunk 21 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:191]: Possible alternative, makes it a bit more clear that we rely on `rt->rtm_msglen` to be correct. A `for` loop gives a false sense of safety. No strong feelings though.

```cpp
    std::byte* p = buf.data();
    while (true) {
        rt = (const struct rt_msghdr*)p;
        // ...

        p += rt->rtm_msglen;
        if (p == buf.data() + buf.size()) break;
        assert(p < buf.data() + buf.size());
    }
```

[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:191]: And maybe:

```cpp
// rt_msghdr is followed by zero or more sockaddrs, as indicated by rtm_addrs
auto sa = (const struct sockaddr*)(p + sizeof(rt_msghdr));
```

File: src/util/netif.cpp (hunk 18 above)
Comment (Sjors) [reply src/util/netif.cpp:194]: How about:

```cpp
// rt_msghdr is followed by zero or more sockaddrs, as indicated by rtm_addrs
auto sa = (const struct sockaddr*)(p + sizeof(rt_msghdr));
```

File: src/util/netif.cpp (hunk 20 above)
Comment (laanwj) [reply src/util/netif.cpp]: Right, let's add `sizeof(rt_msghdr)` manually instead of doing the +1 trick.

> That makes sense. Whereas rt_msghdr is fixed length I guess, so you're able to use rt + 1 above (I'm still a bit terified that compilers don't care).

If we can hardcode the assumption that `sa_len` is the first byte (which it is) then we can avoid casting and dereferencing sockaddr, anywhere.

Comment (laanwj) [reply src/util/netif.cpp]: Currently i have the following, having changed the pointer arithmetic to byte offsets:
```c++
    // Iterate over messages (each message is a routing table entry).
    for (size_t msgptr = 0; msgptr < buf.size(); ) {
        const struct rt_msghdr* rt = (const struct rt_msghdr*)(buf.data() + msgptr);
        // Iterate over addresses within entry, get destination and gateway (if present).
        // Pointer to address data within message, starts after header.
        size_t saptr = msgptr + sizeof(rt_msghdr);
        std::optional<CNetAddr> dst;
        std::optional<CNetAddr> gateway;
        for (int i = 0; i < RTAX_MAX; i++) {
            if (rt->rtm_addrs & (1 << i)) {
                const struct sockaddr* sa = (const struct sockaddr*)(buf.data() + saptr);
                if (i == RTAX_DST) {
                    dst = FromSockAddr(sa);
                } else if (i == RTAX_GATEWAY) {
                    gateway = FromSockAddr(sa);
                }
                // Skip to next address.
                saptr += sa->sa_len;
            }
        }
        // Found default gateway?
        if (dst && gateway && dst->IsBindAny()) { // Route to 0.0.0.0 or :: ?
            return *gateway;
        }
        // Skip to next message.
        msgptr += rt->rtm_msglen;
    }
```

File: src/util/pcp.cpp (hunk 23 above)
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:228]: If it appears after the IPv4 gateway log message it's for the IPv4 gateway, if it's after the IPv6 one it's for the IPv6 gateway. No more than two gateways are ever used. i don't think adding it to every log message is worth it.

File: src/util/netif.cpp (hunk 18 above)
Comment (laanwj) [reply src/util/netif.cpp:194]: i moved the cast to the if() inside the inner loop.

File: src/util/netif.cpp (hunk 20 above)
Comment (Sjors) [reply src/util/netif.cpp]: That indeed looks better.

The *ptr variables are no longer actually pointers, so I suggest renaming them:

msgptr -> msg_pos
within entry - within message
saptr -> sa_pos
next_msgptr -> next_msg_pos

Let's set and check next_msgptr _before_ saptr and make it const.

File: src/util/netif.cpp (hunk 17 above)
Comment (laanwj) [reply src/util/netif.cpp]: From what i understand, the error signalling and many of the flags and operations in the `rt_msghdr` are used with `PF_ROUTE` sockets, interactively. `sysctl` stores a read-only copy of the routing table data so that non-root users can access it.
Graned, it's kind of a weird API.

File: src/util/pcp.cpp (hunk 23 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/pcp.cpp:228]: I'm a bit surprise that when we ask for the default gateway, we get results for both network connections. But I guess we're not asking for the _default_ gateway on macOS, but rather all of them?

**Comment by Sjors** [comment]
Ok, happy with `QueryDefaultGateway(Impl)` as of 9a265c6d75136991125730b8a6a901e95cfeb8f6, except for not compiling on BSD 13.2:

```
util/netif.cpp:84:82: error: use of undeclared identifier 'typeof'; did you mean 'typeid'?
    for (nlmsghdr* hdr = (nlmsghdr*)response; NLMSG_OK(hdr, response_len); hdr = NLMSG_NEXT(hdr, response_len)) {
```

It also throws a warning:

```
util/netif.cpp:84:47: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
    for (nlmsghdr* hdr = (nlmsghdr*)response; NLMSG_OK(hdr, response_len); hdr = NLMSG_NEXT(hdr, response_len)) {
```

File: src/util/pcp.cpp (hunk 23 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/pcp.cpp:228]: Oh I think I get it. In `ProcessPCP` (`mapport.cpp`) we call `PCPRequestPortMap` for every IPv6 address we have, as determined by `GetLocalAddresses()`.

Each port map request is made to the default gateway. This is scope-local addresses, see https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1610568498 
So unlike with IPv4, where a gateway like 192.168.1.1 is reachable through both network connections, the IPv6 default gateway is only reachable through _one_ connection.

And indeed we don't have to "fix" this. Section 2.3 says:

> for a given IP address of a host, only one default route exists to reach other hosts on the Internet from that source IP address

PCP itself doesn't support this kind of setup either.

The only thing that matters is that nodes in the outside world can connect to us, we don't care which of the two network connections ends up getting used.

I guess if I were to turn off the wifi, and that happened to have been the default gateway, I won't get new inbound connections until 20 minutes have passed and we request a new mapping via the LAN default gateway. Haven't tested this.

**Comment by laanwj** [comment]
Do you know what's the minimum FreeBSD version it can be compiled on? Let's bump the version to that.

**Comment by Sjors** [comment]
> Do you know what's the minimum FreeBSD version it can be compiled on? Let's bump the version bound to that.

I'll spin up some more recent VMs to test, probably next week though.

File: src/util/pcp.cpp [hunk 24]
```diff
@@ -0,0 +1,517 @@
...
+
+            // Receive response.
+            recvsz = sock.Recv(response, sizeof(response), MSG_DONTWAIT);
+            if (recvsz < 0) {
+                LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "%s: Could not receive response: %s\n", protocol, NetworkErrorString(WSAGetLastError()));
+                return std::nullopt; // Network-level error, probably no use retrying.
+            }
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "%s: Received response of %d bytes: %s\n", protocol, recvsz, HexStr(Span(response, recvsz)));
+
+            if (check_packet(Span<uint8_t>(response, recvsz))) {
```
Comment (Sjors) [inline src/util/pcp.cpp:252]: It seems like the gateway can keep us waiting forever by sending an invalid response at least once per second. Should be give up at some point?

**Review by Sjors — COMMENTED** [review]
`pcp.{h,cpp}` (mostly) look good to me as well, but I haven't tested the NAT-PMP fallback. As do the changes to `mapport.{h,cpp}`.

Next on my review list is the remaining code that drops the old Nat-PMP dependency, but that's all a lot simpler.

**Comment by laanwj** [comment]
1cbbcba42cf1c050022a73cb02b9d385fa184f2e: squashed all fixups to clean up the list of commits, no other changes

File: src/util/pcp.cpp (hunk 24 above)
Comment (laanwj) [reply src/util/pcp.cpp:252]: The chrono timepoint/duration stuff kind of confuses me. Would this be the idea? (assuming `timeout` is  per retry). `sock.Wait` takes milliseconds while the steady clock returns microseconds, so the cast seems unavoidable.
```diff
         }
 
         // Wait for response(s) until we get a valid response, a network error, or time out.
-        while (true) {
+        auto cur_time = std::chrono::time_point_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now());
+        auto deadline = cur_time + timeout;
+        while ((cur_time = std::chrono::time_point_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now())) < deadline) {
             Sock::Event occurred = 0;
-            if (!sock.Wait(std::chrono::milliseconds(1000), Sock::RECV, &occurred)) {
+            if (!sock.Wait(deadline - cur_time, Sock::RECV, &occurred)) {
                 LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "%s: Could not wait on socket: %s\n", protocol, NetworkErrorString(WSAGetLastError()));
                 return std::nullopt; // Network-level error, probably no use retrying.
             }
```

**Comment by laanwj** [comment]
> The first two commits of https://github.com/bitcoin/bitcoin/pull/26812 would make it possible to test and fuzz how this code interacts with a router.

So ive been thinking about this, do we have a mockable replacement for `Sock socket(int domain, int type, int protocol)`? i was thinking of passing in a `SocketFactory` (please don't kill me, this could be just a functor 😅 ). It's slightly nicer than passing in a pre-made `Sock` because it allows testing the "create a socket of the right family" logic.
(also ping @vasild)

File: src/util/pcp.cpp (hunk 24 above)
Comment (laanwj) [reply src/util/pcp.cpp:255]: The timeout is still one second per try (so three seconds in total maximum, given current retries), it's just not possible to extend it indefinitely anymore by sending rejected packets.

**Comment by Sjors** [comment]
> Do you know what's the minimum FreeBSD version it can be compiled on? Let's bump the version bound to that.

Just tried on 14.0 with its default clang 16 and I get the same error. So we should either find a workaround or disable FreeBSD for this feature and a TODO comment. I don't know how popular this is as a desktop distro?

**Review by Sjors — COMMENTED** [review]
Finished the rest of my code review and tested 97ae5d4eefe4 again on Intel macOS 14.5, Ubuntu 24.04 and Windows. 

I noticed that the renewal for IPv6 fails (at least on Ubuntu and macOS) with `NO_RESOURCES`. IPv4 renewal works fine. Ten minutes later it tries again and the mapping succeeds.

IIUC OPNsense uses miniupnpd 2.3.1, which is two years behind but [at first glance](https://github.com/miniupnp/miniupnp/compare/miniupnpd_2_3_1...miniupnpd_2_3_6) I don't see any recent fixes related to renewals, nor any open issues.s

One possible explanation could be that the router doesn't implement the protocol correctly, in terms of when it allows renewal. If that's the case, it may be worth implementing the recommended retry intervals. We should also log the approximate time remaining so it's a bit easier to debug the router behavior.

--- 

Windows decided to quarantine bitocin-qt.exe (built with guix). I haven't seen that before in earlier tests, so I wonder if it's related to this change.



The timing suggests it happened 10 minutes after the ports were intially opened, so I'm guessing a renewal attempt triggered it, but I forgot to turn on more verbose logging.

File: src/net.h [hunk 25]
```diff
@@ -148,7 +148,7 @@ enum
     LOCAL_NONE,   // unknown
     LOCAL_IF,     // address a local interface listens on
     LOCAL_BIND,   // address explicit bound to
-    LOCAL_MAPPED, // address reported by UPnP or NAT-PMP
+    LOCAL_MAPPED, // address reported by UPnP or PCP
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/net.h:151]: Sure, ok, really i'm just considering NAT-PMP to be PCPv0.

**Comment by laanwj** [comment]
> I noticed that the renewal for IPv6 fails (at least on Ubuntu and macOS) with NO_RESOURCES. IPv4 renewal works fine. Ten minutes later it tries again and the mapping succeeds.

Is this after re-launching bitcoind? Mind that restarting will roll a new mapping nonce, which means that from the point of your router it's a new application trying to get the port, which will prevent it from making the mapping until the old mapping expires. But that should go away after one cycle and not happen again the next one, as the nonce is stored and reused for renewals (as is specified in the RFC).

i doubt this has anything to do with specifiic intervals. If renewal is avoided while there is already a mapping *at all* then there will be holes in reachability, which is worse than some spurious errors.

> Windows decided to quarantine bitocin-qt.exe (built with guix). I haven't seen that before in earlier tests, so I wonder if it's related to this change.

Possible, but that would be strange, given that we're not communicating to any different ports than before. Were you building with libnatpmp before?

**Comment by Sjors** [comment]
> Is this after re-launching bitcoind? 

No, I hadn't run the node in a while. At startup it opens the port, only renewal fails. Leaving the node running, this seems to happen half the time, as you would expect: port is opened, renewal fails, mapping expires, so opening succeeds again, renewal fails, etc.

> Were you building with libnatpmp before? 

No, I had that disabled in the past. I'll see if I can trigger it again with more detailed logs. But you're right, it might be an existing issue.

**Comment by laanwj** [comment]
> No, I hadn't run the node in a while. At startup it opens the port, only renewal fails. Leaving the node running, this seems to happen half the time, as you would expect: port is opened, renewal fails, mapping expires, so opening succeeds again, renewal fails, etc.

This is the opposite from what's expected.

- But it only happens for IPv6, not IPv4. i wonder if that's because IPv4 is the first mapping created? Maybe it doesn't like the same nonce being used for multiple different mappings existing at the same time?
Maybe try putting the IPv6 block first and see if it reverses the issue? Or at least makes it succeed for the first IPv6 address.

- Alternatively, maybe try generating a new nonce every call to `PCPRequestPortMap`. This violates the protocol but ... if it's implemented wrongly on the server this may trigger it to generate a fresh mapping. i dunno...

**Comment by Sjors** [comment]
On macOS I recompiled with `PORT_MAPPING_REANNOUNCE_PERIOD` set to 5 minutes and IPv4 commented out. At startup it adds three mappings. After a few minutes at renewal it complains with `NO_RESOURCES`. Trying some other things...

**Comment by laanwj** [comment]
> After a few minutes at renewal it complains with NO_RESOURCES.

Does it complain for all three mappings?

**Comment by Sjors** [comment]
Yes, for all three.

I then recompiled and set the renewal interval at 6/8 - 7/8. Started the node again (using a fresh port). Same pattern: three mappings succeeed, at renewal all three complain about NO_RESOURCES. (And then a few minutes later they succesfully get a mapping again).

**Comment by Sjors** [comment]
Actually this might an existing bug: https://github.com/miniupnp/miniupnp/commit/7bd0877b8fd9a1c1c59cdf426b4640b3cee2bf61

I'll see if I can convince OPNsense to ship >= 2.3.6

**Comment by laanwj** [comment]
That does look like an issue that would affect renewal, but i'm not sure it would cause this specific issue, if i understand correctly it'd bump the renewal timestamp so far it would live forever. It wouln't make it complain about the port being used. Unless it's an old mapping that sticks around. But that wouldn'e explain why it only happens on renewal.

As for generating a new nonce every time, this is what i meant:
```diff
diff --git a/src/mapport.cpp b/src/mapport.cpp
index e28ed52a58f393d463db91b596e10d5202856dbc..4084324baad97065f9bd290865a8bbefa34271ac 100644
--- a/src/mapport.cpp
+++ b/src/mapport.cpp
@@ -45,10 +45,6 @@ static constexpr auto PORT_MAPPING_RETRY_PERIOD{5min};

 static bool ProcessPCP()
 {
-    // The same nonce is used for all mappings, this is allowed by the spec, and simplifies keeping track of them.
-    PCPMappingNonce pcp_nonce;
-    GetRandBytes(pcp_nonce);
-
     bool ret = false;
     bool no_resources = false;
     const uint16_t private_port = GetListenPort();
@@ -86,6 +82,8 @@ static bool ProcessPCP()
             // Open a port mapping on whatever local address we have toward the gateway.
             struct in_addr inaddr_any;
             inaddr_any.s_addr = htonl(INADDR_ANY);
+            PCPMappingNonce pcp_nonce;
+            GetRandBytes(pcp_nonce);
             auto res = PCPRequestPortMap(pcp_nonce, *gateway4, CNetAddr(inaddr_any), private_port, requested_lifetime);
             MappingError* pcp_err = std::get_if<MappingError>(&res);
             if (pcp_err && *pcp_err == MappingError::UNSUPP_VERSION) {
@@ -105,6 +103,8 @@ static bool ProcessPCP()
             // Try to open pinholes for all routable local IPv6 addresses.
             for (const auto &addr: GetLocalAddresses()) {
                 if (!addr.IsRoutable() || !addr.IsIPv6()) continue;
+                PCPMappingNonce pcp_nonce;
+                GetRandBytes(pcp_nonce);
                 auto res = PCPRequestPortMap(pcp_nonce, *gateway6, addr, private_port, requested_lifetime);
                 handle_mapping(res);
             }
```

**Comment by Sjors** [comment]
> generating a new nonce every time for every mapping

That doesn't seem like a good idea. IIUC the nonce is used to recognise the requesting application, and to distinguish a renew request from some other app trying to use the same port.

**Comment by laanwj** [comment]
> That doesn't seem like a good idea. IIUC the nonce is used to recognise the requesting application, and to distinguish a renew request from some other app trying to use the same port.

It's not supposed to be a good idea, but i wonder if it works around the issue with your router, if they implemented the protocol wrongly. i honestly have no idea what could be the problem here i'm just guessing.

File: src/util/pcp.cpp [hunk 26]
```diff
@@ -0,0 +1,520 @@
...
+#include <util/netif.h>
+#include <util/readwritefile.h>
+#include <util/sock.h>
+#include <util/strencodings.h>
+
+// RFC6886 NAT-PMP and RFC6887 Port Control Protocol (PCP) implementation.
+// NAT-PMP and PCP use network byte order (big-endian).
+
+// NAT-PMP (v0) protocol constants.
+//! NAT-PMP uses a fixed server port number (RPC6887 section 1.1).
```
Comment (Sjors) [inline src/util/pcp.cpp:22]: RPC -> RFC (in a few other places too)

**Comment by laanwj** [comment]
FWIW, i'm not seeing that problem on TurrisOS (openwrt) with miniupnpd 2.3.3. Renewals work fine, both with 20 minute and 5 minute reannounce period. So it's either something that was solved in the meantime, or something different in your networking situation.

**Comment by Sjors** [comment]
Both our setups are at miniupnpd 2.3.3; the plugin description incorrectly says 2.3.1: https://github.com/opnsense/plugins/issues/4003#issuecomment-2133421334

So perhaps there's a difference in how miniupnpd controls the router / firewall itself, which causes the renewal to fail on my end. This is above my pay grade...

**Comment by laanwj** [comment]
i've been trying to build the package myself, and there's miniupnpd-nftables and miniupnpd-iptables, do you know which one you have? i see i have -iptables installed at the moment, it appears.

File: src/util/netif.cpp (hunk 8 above)
Comment (laanwj) [reply src/util/netif.cpp:20]: Right, that's good to know. However the current problem is that we can't compile this for *any* FreeBSD version. Looks like the  `MLMSG` etc macros don't work in C++, because `typeof` is used.

Comment (laanwj) [reply src/util/netif.cpp:20]: That would probably work, but that'd be a really invasive workaround build system wise.

Comment (theuni) [reply src/util/netif.cpp:20]: Yes, please don't do that :)

Comment (laanwj) [reply src/util/netif.cpp:20]: My expectation is that a `#define typeof __typeof__` around just the use of that macro on FreeBSD could fix it. Just haven't been able to try it out.

Comment (vasild) [reply src/util/netif.cpp:20]: This is the upstream fix: https://github.com/freebsd/freebsd-src/pull/1070.

The suggested workaround to define `typeof` is ok:

```diff
diff --git i/src/util/netif.cpp w/src/util/netif.cpp
index 845b8aed1d..1840974a83 100644
--- i/src/util/netif.cpp
+++ w/src/util/netif.cpp
@@ -9,18 +9,24 @@
 #include <logging.h>
 #include <netbase.h>
 #include <util/check.h>
 #include <util/sock.h>
 #include <util/syserror.h>
 
+#ifdef __FreeBSD__
+#include <osreldate.h>
+#endif
+
 // Linux and FreeBSD 13.2+
-#if defined(__linux__) || (defined(__FreeBSD__) && __FreeBSD_version >= 1302000)
+#if defined(__linux__) || __FreeBSD_version >= 1302000
 
 #if defined(__linux__)
 #include <linux/rtnetlink.h>
 #elif defined(__FreeBSD__)
+// Workaround https://github.com/freebsd/freebsd-src/pull/1070.
+#define typeof __typeof
 #include <netlink/netlink.h>
 #include <netlink/netlink_route.h>
 #endif
 
 static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t family)
 {
@@ -77,14 +83,13 @@ static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t family)
     } while (recv_result < 0 && (errno == EINTR || errno == EAGAIN));
     if (recv_result < 0) {
         LogPrintLevel(BCLog::NET, BCLog::Level::Error, "recv() from netlink socket: %s\n", NetworkErrorString(errno));
         return std::nullopt;
     }
 
-    size_t response_len = static_cast<size_t>(recv_result);
-    for (nlmsghdr* hdr = (nlmsghdr*)response; NLMSG_OK(hdr, response_len); hdr = NLMSG_NEXT(hdr, response_len)) {
+    for (nlmsghdr* hdr = (nlmsghdr*)response; NLMSG_OK(hdr, recv_result); hdr = NLMSG_NEXT(hdr, recv_result)) {
         rtmsg* r = (rtmsg*)NLMSG_DATA(hdr);
         int remaining_len = RTM_PAYLOAD(hdr);
 
         // Iterate over the attributes.
         rtattr *rta_gateway = nullptr;
         int scope_id = 0;
```

The above patch does two more things:
* `__FreeBSD_version` was not defined at the time it was checked, so `__FreeBSD_version >= 1302000` was always false. Include the header that defines it.
* Silence a warning about signed vs unsigned integer comparison.

I tested this by reverting the upstream fix - `s/__typeof/typeof` in my `/usr/include/netlink/netlink.h`. Confirming that it gives the typeof error, then applying to above workaround and confirming that it compiles.

Comment (laanwj) [reply src/util/netif.cpp:20]: Thanks!

> Silence a warning about signed vs unsigned integer comparison.

Oh no. Pretty sure i had to do the `response_len` thing to work around another error about signed-unsigned integer comparison in the i686 CI run.

**Review by MaxJitphanu — COMMENTED** [review]
1

File: src/util/netif.cpp (hunk 8 above)
Comment (vasild) [reply src/util/netif.cpp:20]: On my Linux distro I have:

```cpp
struct nlmsghdr {          
        __u32           nlmsg_len;
...
#define NLMSG_OK(nlh,len) ((len) >= (int)sizeof(struct nlmsghdr) && \
                           (nlh)->nlmsg_len >= sizeof(struct nlmsghdr) && \
                           (nlh)->nlmsg_len <= (len))
```
So, the second argument of `NLMSG_OK()` - `len` is compared against 1. `(int)sizeof...` and 2. `...->nlmsg_len` (which is `__u32`). The only difference on FreeBSD is that in 2. it is compared against `(int)(_hdr)->nlmsg_len` - an explicitly cast `nlmsg_len` to `int` (`nlmsg_len` is `uint32_t` on FreeBSD).

I do not get a warning when compiling that code on Linux:
```cpp
    ssize_t response_len;
...
    for (nlmsghdr *hdr = (nlmsghdr*)response; NLMSG_OK(hdr, response_len); hdr = NLMSG_NEXT(hdr, response_len)) {
```
I am not sure why. I should get a warning about `__u32 <= ssize_t`, right?

Comment (laanwj) [reply src/util/netif.cpp:24]: > I am not sure why. I should get a warning about __u32 <= ssize_t, right?

Comparing an unsigned type against a larger signed type does what one would expect: it gets casted to the larger signed type before comparison.
This is why on 64-bit platforms this is fine.
However on 32-bit platforms, `ssize_t` is 32 bit. So there it warns.

Comment (vasild) [reply src/util/netif.cpp:24]: I see, then defining `recv_result` as `int64_t` instead of `ssize_t` should be ok on all platforms?

File: src/util/netif.cpp [hunk 27]
```diff
@@ -0,0 +1,300 @@
...
+
+static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t family)
+{
+    // Create a netlink socket.
+    const int s{socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE)};
+    if (s < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "socket(AF_NETLINK): %s\n", NetworkErrorString(errno));
+        return std::nullopt;
+    }
+    Sock sock{static_cast<SOCKET>(s)};
```
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:39]: @vasild I haven't had a chance to thoroughly review the second commit. Making a separate PR could help.

File: src/util/netif.cpp (hunk 8 above)
Comment (laanwj) [reply src/util/netif.cpp:24]: Will try

**Comment by Sjors** [comment]
I was able to build b4535d48aed26c3b3f61c8839b041d076b02d132 on my BSD 13.2 VM.

Opening ports fails, maybe because it's a VM, but "Address family not supported by protocol family" seems an odd error for that.

```
2024-05-23T01:58:47Z [net:error] socket(AF_NETLINK): Address family not supported by protocol family (47)
2024-05-23T01:58:47Z [net] portmap: Could not determine IPv4 default gateway
2024-05-23T01:58:47Z [net:error] socket(AF_NETLINK): Address family not supported by protocol family (47)
2024-05-23T01:58:47Z addcon thread start
2024-05-23T01:58:47Z [net] portmap: Could not determine IPv6 default gateway
```

**Comment by laanwj** [comment]
Thanks for testing. Sounds like AF_NETLINK is not actually supported on that kernel, even though the necessary stuff is in the headers.

File: src/util/netif.cpp (hunk 27 above)
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:39]: SGTM.

> That address_family is the first argument to the socket(2) syscall. What's needed is to extend CreateSock*() with the other two arguments - type and protocol. I can do that.

Yes, for specifying UDP (and NETLINK, but i do not intend to make a test framework for that) it would need all three arguments.

[the remark this answers is not in the document]
Comment (vasild) [reply src/util/netif.cpp:39]: Done in the topmost commit in https://github.com/vasild/bitcoin/commits/extend_CreateSock/.
Separate PR or include in this PR?

[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:39]: This PR is already quite large, so let's make a fresh one that this can rebase on if needed.

**Comment by Sjors** [comment]
With a bridged network it indeed works.

Also, as suggested by @vasild, doing `kldload /boot/kernel/netlink.ko` makes things work on FreeBSD 13.2.

File: src/util/netif.cpp (hunk 27 above)
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:39]: Agree adding fuzzing/testing makes sense as a follow-up PR. It's already big enough, and also i don't want to interfere with review by doing more active development here than address review comments.

[the remark this answers is not in the document]
Comment (vasild) [reply src/util/netif.cpp:39]: Opened https://github.com/bitcoin/bitcoin/pull/30202 "netbase: extend CreateSock() to support creating arbitrary sockets"

[the remark this answers is not in the document]
Comment (vasild) [reply src/util/netif.cpp:39]: > Making a separate PR could help

Done, the first two commits from https://github.com/bitcoin/bitcoin/pull/26812 extracted into a separate PR: https://github.com/bitcoin/bitcoin/pull/30205

[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:39]: I got a bit confused about these two new PR's, but I guess they are orthogonal.

**Comment by laanwj** [comment]
> Maybe too late or has been looked at. A PCP/NAT-PMP library https://github.com/libpcp/pcp

Yes, some revievers have been looking at it as reference/comparison.

This has been said before but: implementing a self-contained version of the RFCs here is intentional, we don't want to introduce a dependency on a third-party library. It shoudn't be needed for a straightforward fixed packet-based protocol. The intent is to have code that integrates with bitcoin core's frameworks for logging, networking and testing. At some point we want to be confident enough about it to enable it by default.

**Comment by laanwj** [comment]
Force push: rebased for small conflict in `src/Makefile.am`, collected fixup commits, no other changes.

**Comment by Sjors** [comment]
Tested faacd264417bd7f3f08c5ff497458030b3a54fbc on Intel macOS 13.6.7, FreeBSD 13.2, Windows and Ubuntu 24.04.

File: doc/build-osx.md [hunk 28]
```diff
@@ -134,20 +134,6 @@ Skip if you do not need this functionality.
...
-###### libnatpmp
-
-libnatpmp may be used for NAT-PMP port mapping.
-Skip if you do not need this functionality.
-
-``` bash
-brew install libnatpmp
-```
-
-Note: UPnP and NAT-PMP support will be compiled in and disabled by default.
```
Comment (Sjors) [inline doc/build-osx.md:146]: 3fdc97a2bf7d1ec774d2ffa00502188158c64724: this line could be moved to the `miniupnpc` section above:

```
Note: UPnP support will be compiled in, but disabled by default.
```

File: doc/build-osx.md [hunk 29]
```diff
@@ -134,20 +134,6 @@ Skip if you do not need this functionality.
...
-Check out the [further configuration](#further-configuration) section for more information.
```
Comment (Sjors) [inline doc/build-osx.md:147]: 3fdc97a2bf7d1ec774d2ffa00502188158c64724: I don't know why this was here in the first place, seems fine to drop.

File: src/init.cpp [hunk 30]
```diff
@@ -1808,7 +1804,6 @@ bool AppInitMain(NodeContext& node, interfaces::BlockAndHeaderTipInfo* tip_info)
     LogPrintf("nBestHeight = %d\n", chain_active_height);
     if (node.peerman) node.peerman->SetBestBlock(chain_active_height, std::chrono::seconds{best_block_time});
 
-    // Map ports with UPnP or NAT-PMP.
```
Comment (Sjors) [inline src/init.cpp:1811]: 57e23f3b4d9cc5bdba421e47def9f3b2335d4cfb: nit, no need to drop this

**Review by Sjors — APPROVED** [review]
tACK faacd264417bd7f3f08c5ff497458030b3a54fbc

Tested on Intel macOS 13.6.7, FreeBSD 13.2, Windows and Ubuntu 24.04.

Letting Windows run a bit longer to see if its "defender" leaves us alone now.

**Review by sipa — COMMENTED** [review]
Just a quick look so far.

File: src/util/netif.cpp [hunk 31]
```diff
@@ -0,0 +1,305 @@
...
+#include <util/check.h>
+#include <util/sock.h>
+#include <util/syserror.h>
+
+#ifdef __FreeBSD__
+#include <osreldate.h>
+#endif
+
+// Linux and FreeBSD 13.2+
+#if defined(__linux__) || __FreeBSD_version >= 1400000
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:20]: sure, we could do that again, but i don't want people to have to bother with weird error messages and having to load kernel modules, probably this should work out of the box or not at all

File: src/util/pcp.h [hunk 32]
```diff
@@ -0,0 +1,68 @@
...
+
+//! Try to open a port using RFC 6886 NAT-PMP. IPv4 only.
+//!
+//! * gateway: Destination address for PCP requests (usually the default gateway).
+//! * port: Internal port, and desired external port.
+//! * lifetime: Requested lifetime in seconds for mapping. The server may assign as shorter or longer lifetime. A lifetime of 0 deletes the mapping.
+//! * num_tries: Number of tries in case of no response.
+//!
+//! Returns the external_ip:external_port of the mapping if successful, otherwise a MappingError.
+std::variant<MappingResult, MappingError> NATPMPRequestPortMap(const CNetAddr &gateway, uint16_t port, uint32_t lifetime, int num_tries = 3, std::chrono::milliseconds timeout_per_try = std::chrono::milliseconds(1000));
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.h:54]: It would be great to cut down on the verbosity here, but as this is a header, i don't think we want to use `using` there because that will leak into anything that includes it? Or am i misunderstanding?

File: src/util/netif.cpp (hunk 31 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:20]: Good point, maybe just add a comment about this. FreeBSD 13 won't be EOL for another two years, so someone else might wonder.

[the remark this answers is not in the document]
Comment (vasild) [reply src/util/netif.cpp:20]: The comment says 13.2+ but the code says 1400000

File: src/util/netif.cpp [hunk 33]
```diff
@@ -0,0 +1,305 @@
...
+    return std::nullopt;
+}
+
+#else
+
+// Dummy implementation.
+static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t family)
+{
+    (void)family;
+    return std::nullopt;
```
Comment (vasild) [inline src/util/netif.cpp:242]: nit, can drop the parameter name for an unused parameter and the `void` cast:
```suggestion
static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t)
{
    return std::nullopt;
```

File: src/util/netif.cpp [hunk 34]
```diff
@@ -0,0 +1,305 @@
...
+    }
+}
+
+std::vector<CNetAddr> GetLocalAddresses()
+{
+    std::vector<CNetAddr> addresses;
+#ifdef WIN32
+    char pszHostName[256] = "";
+    if (gethostname(pszHostName, sizeof(pszHostName)) != SOCKET_ERROR)
+    {
```
Comment (vasild) [inline src/util/netif.cpp:277]: style: `{` should be on the same line as `if` or `for` (also in a few places below).

**Review by vasild — COMMENTED** [review]
Posting review midway, up to 237792601fb911cf2e5abebc9226d63f4cd35cec (incl)

File: src/util/netif.cpp [hunk 35]
```diff
@@ -0,0 +1,305 @@
...
+
+static std::optional<CNetAddr> QueryDefaultGatewayImpl(sa_family_t family)
+{
+    // Create a netlink socket.
+    const int s{socket(AF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE)};
+    if (s < 0) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Error, "socket(AF_NETLINK): %s\n", NetworkErrorString(errno));
+        return std::nullopt;
+    }
+    Sock sock{static_cast<SOCKET>(s)};
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:39]: sure, though i don't intend to add mocking for netlink sockets (that's just too OS specific), but for the UDP socket creation it'd be useful

File: src/util/pcp.cpp [hunk 36]
```diff
@@ -0,0 +1,520 @@
...
+
+            // Receive response.
+            recvsz = sock.Recv(response, sizeof(response), MSG_DONTWAIT);
+            if (recvsz < 0) {
+                LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "%s: Could not receive response: %s\n", protocol, NetworkErrorString(WSAGetLastError()));
+                return std::nullopt; // Network-level error, probably no use retrying.
+            }
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "%s: Received response of %d bytes: %s\n", protocol, recvsz, HexStr(Span(response, recvsz)));
+
+            if (check_packet(Span<uint8_t>(response, recvsz))) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:255]: Unfortunately, that gives a new warning, because the `int` isn't the exact type:
```
../../src/util/pcp.cpp:258:41: warning: narrowing conversion of ‘recvsz’ from ‘int’ to ‘std::size_t’ {aka ‘long unsigned int’} [-Wnarrowing]
  258 |             if (check_packet({response, recvsz})) {
```
Could add a `static_cast` but i don't think it's much of an improvement in that case?

File: src/util/netif.cpp [hunk 37]
```diff
@@ -0,0 +1,305 @@
...
+                std::memcpy(&scope_id, RTA_DATA(attr), sizeof(scope_id));
+            }
+        }
+
+        // Found gateway?
+        if (rta_gateway != nullptr) {
+            if (family == AF_INET) {
+                Assume(sizeof(in_addr) == RTA_PAYLOAD(rta_gateway));
+                in_addr gw;
+                std::memcpy(&gw, RTA_DATA(rta_gateway), sizeof(gw));
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:110]: It's an OS API, it's very unlikely to fail, so i don't want to add a specific log message for it. i'm fine with it just returning nullptr.

**Comment by laanwj** [comment]
Force push: rebased to get `CreateSock()` from #30202.

**Comment by laanwj** [comment]
Force push was to squash all fixups (no other changes).

File: src/util/pcp.h [hunk 38]
```diff
@@ -0,0 +1,68 @@
+// Copyright (c) 2024 The Bitcoin Core developers
+// Distributed under the MIT software license, see the accompanying
+// file COPYING or https://www.opensource.org/licenses/mit-license.php.
+
+#ifndef BITCOIN_UTIL_PCP_H
+#define BITCOIN_UTIL_PCP_H
+
+#include <netaddress.h>
+
+#include <variant>
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.h:10]: Will add, thanks!

File: src/util/netif.h [hunk 39]
```diff
@@ -0,0 +1,20 @@
+// Copyright (c) 2024 The Bitcoin Core developers
+// Distributed under the MIT software license, see the accompanying
+// file COPYING or https://www.opensource.org/licenses/mit-license.php.
+
+#ifndef BITCOIN_UTIL_NETIF_H
+#define BITCOIN_UTIL_NETIF_H
+
+#include <netaddress.h>
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.h:8]: i don't disagree with doing this, but `netif.h` is only included in two places: `net.cpp` and `pcp.cpp`, both of which use `netaddress.h` anyway. Not sure it's worth adding a change in `netaddress.h` in this PR for.

File: src/util/pcp.cpp [hunk 40]
```diff
@@ -0,0 +1,524 @@
...
+
+    LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "pcp: Requesting port mapping for addr %s port %d from gateway %s\n", bind.ToStringAddr(), port, gateway.ToStringAddr());
+
+    // Validate addresses, make sure they're the same network family.
+    if (!CService(gateway, PCP_SERVER_PORT).GetSockAddr((struct sockaddr*)&dest_addr, &dest_addrlen)) return MappingError::NETWORK_ERROR;
+    if (!CService(bind, 0).GetSockAddr((struct sockaddr*)&bind_addr, &bind_addrlen)) return MappingError::NETWORK_ERROR;
+    if (dest_addr.ss_family != bind_addr.ss_family) return MappingError::NETWORK_ERROR;
+
+    // Create UDP socket (IPv4 or IPv6 based on provided gateway).
+    auto sock{CreateSock(dest_addr.ss_family, SOCK_DGRAM, IPPROTO_UDP)};
```
Comment (vasild) [inline src/util/pcp.cpp:400]: I guess this is acceptable, but just mentioning: my understanding of RFC 6887 is that the server can send unsolicited messages with updates at any time, in case of address changes. When `PCPRequestPortMap()` ends, then this `sock` will go out of scope, will be closed and we will miss such replies.

File: configure.ac [hunk 41]
```diff
@@ -160,12 +160,6 @@ AC_ARG_WITH([miniupnpc],
   [use_upnp=$withval],
   [use_upnp=auto])
 
-AC_ARG_WITH([natpmp],
```
Comment (vasild) [inline configure.ac:163]: Commit a749ab8cfe `build: Drop libnatpmp from build system` leaves some mentions of "natpmp" in `configure.ac` which are later removed by 6f4bc73e39 `depends: Drop natpmp and associated option from depends`. I think all removals of "natpmp" from `configure.ac` belong to one commit.

File: ci/test/00_setup_env_mac_native.sh [hunk 42]
```diff
@@ -11,7 +11,7 @@ export HOST=x86_64-apple-darwin
 # Therefore, `--break-system-packages` is needed.
 export PIP_PACKAGES="--break-system-packages zmq"
 export GOAL="install"
-export BITCOIN_CONFIG="--with-gui --with-miniupnpc --with-natpmp --enable-reduce-exports"
```
Comment (vasild) [inline ci/test/00_setup_env_mac_native.sh:14]: When usages of `--with-natpmp` are removed from the CI in commit 40908bbb88 `ci: Remove natpmp build option` then this option is already nonexistent, meaning that in the intermediate commits the CI is broken. Maybe reorder the commits so the CI one is before the `--with-natpmp` removal (a749ab8cfe `build: Drop libnatpmp from build system`) or squash them into one commit.

**Review by vasild — COMMENTED** [review]
Approach ACK 23916f2a7717b463799207b4b81b5795f2e9d7e3

File: src/mapport.cpp [hunk 43]
```diff
@@ -46,104 +43,96 @@ using namespace std::chrono_literals;
...
-                    external_ip_discovered = true;
-                }
-                LogPrintf("natpmp: Port mapping successful. External address = %s\n", external.ToStringAddrPort());
-                return true;
-            } else {
-                LogPrintf("natpmp: Port mapping failed.\n");
+            // Try to open pinholes for all routable local IPv6 addresses.
+            for (const auto &addr: GetLocalAddresses()) {
+                if (!addr.IsRoutable() || !addr.IsIPv6()) continue;
+                auto res = PCPRequestPortMap(pcp_nonce, *gateway6, addr, private_port, requested_lifetime);
```
[the remark this answers is not in the document]
Comment (vasild) [reply src/mapport.cpp:109]: Also, it just occurred to me, `GetLocalAddresses()` operates regardless of `-bind=` options. If the machine has two IPv6 addresses but `-bind=` has been used and only one of them specified, then we shouldn't do mapping for the other one (where nobody is listening).

File: src/util/pcp.cpp (hunk 40 above)
Comment (laanwj) [reply src/util/pcp.cpp:400]: i don't think that's the case in practice? but even so, doing this differently would really complicate things too much, changes in network configuration would be noticed the next update interval anyway?

File: src/util/pcp.cpp [hunk 44]
```diff
@@ -0,0 +1,524 @@
...
+std::optional<std::vector<uint8_t>> PCPSendRecv(Sock &sock, const std::string &protocol, Span<const uint8_t> request, int num_tries,
+        std::chrono::milliseconds timeout_per_try,
+        std::function<bool(Span<const uint8_t>)> check_packet)
+{
+    using namespace std::chrono;
+    // UDP is a potentially lossy protocol, so we try to send again a few times.
+    uint8_t response[PCP_MAX_SIZE];
+    bool got_response = false;
+    int recvsz = 0;
+    for (int ntry = 0; !got_response && ntry < num_tries; ++ntry) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:227]: No, this doesn't implement the exact retry logic, it seems excessively complicated for communicating with a local router, and re-using the same code for NAT-PMP and PCP keeps the code straighforward.

File: src/util/pcp.cpp [hunk 45]
```diff
@@ -0,0 +1,524 @@
...
+    ofs += PCP_HDR_SIZE;
+
+    // Fill in MAP request packet, See RFC6887 Figure 9.
+    // Randomize mapping nonce (this is repeated in the response, to be able to
+    // correlate requests and responses, and used to authenticate changes to the mapping).
+    std::memcpy(request.data() + ofs + PCP_MAP_NONCE_OFS, nonce.data(), PCP_MAP_NONCE_SIZE);
+    request[ofs + PCP_MAP_PROTOCOL_OFS] = PCP_PROTOCOL_TCP;
+    WriteBE16(request.data() + ofs + PCP_MAP_INTERNAL_PORT_OFS, port);
+    WriteBE16(request.data() + ofs + PCP_MAP_EXTERNAL_PORT_OFS, port);
+    if (!PCPWrapAddress(Span(request).subspan(ofs + PCP_MAP_EXTERNAL_IP_OFS, ADDR_IPV6_SIZE), bind)) return MappingError::NETWORK_ERROR;
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:452]: This is intentional. For IPv4 we provide the all-zeroes address, because the router will use its own (NAT), for IPv6 we *want* the external address to be the same as the local address (NAT is not a thing, we want pinholing).

File: src/util/pcp.cpp [hunk 46]
```diff
@@ -0,0 +1,524 @@
...
+            // Handle MAP opcode response. See RFC6887 Figure 10.
+            // Check that returned mapping nonce matches our request.
+            if (response.subspan(PCP_HDR_SIZE + PCP_MAP_NONCE_OFS, PCP_MAP_NONCE_SIZE) != Span(nonce)) {
+                LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "pcp: Mapping nonce mismatch\n");
+                return false; // Wasn't response to what we expected, try receiving next packet.
+            }
+            uint8_t protocol = response[PCP_HDR_SIZE + 12];
+            uint16_t internal_port = ReadBE16(response.data() + PCP_HDR_SIZE + 16);
+            if (protocol != PCP_PROTOCOL_TCP || internal_port != port) {
+                LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "pcp: Response protocol or port doesn't match request\n");
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:483]: As we receive the UDP packet at all, i think that should be correct. But sure...

File: src/mapport.cpp [hunk 47]
```diff
@@ -46,104 +43,96 @@ using namespace std::chrono_literals;
...
+    uint32_t actual_lifetime = 0;
+    std::chrono::milliseconds sleep_time;
+
+    // Local functor to handle result from PCP/NATPMP mapping.
+    auto handle_mapping = [&](std::variant<MappingResult, MappingError> &res) -> void {
+        if (MappingResult* mapping = std::get_if<MappingResult>(&res)) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Info, "portmap: Added mapping %s\n", mapping->ToString());
+            AddLocal(mapping->external, LOCAL_MAPPED);
+            ret = true;
+            actual_lifetime = std::min(actual_lifetime, mapping->lifetime);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/mapport.cpp:66]: Again, i intentionally use a simple imlementation here. i don't want to complicate the code too much. As i understand, this covers the practical cases. It chooses the minimum because we don't want holes in coverage while renewing the mapping more than necessary doesn't hurt.

File: src/mapport.cpp [hunk 48]
```diff
@@ -46,104 +43,96 @@ using namespace std::chrono_literals;
...
-    } else {
-        LogPrintf("natpmp: sendpublicaddressrequest() failed with %d error.\n", r_send);
-    }
 
-    return false;
-}
+        // IPv6
+        std::optional<CNetAddr> gateway6 = QueryDefaultGateway(NET_IPV6);
+        if (!gateway6) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "portmap: Could not determine IPv6 default gateway\n");
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/mapport.cpp:102]: Yes, that makes sense, in the case of onlynet=ipv6 we wouldn't want to advertise a port on ipv4 and vice versa.

File: src/mapport.cpp [hunk 49]
```diff
@@ -46,104 +43,96 @@ using namespace std::chrono_literals;
...
+        if (!gateway4) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "portmap: Could not determine IPv4 default gateway\n");
         } else {
-            LogPrintf("natpmp: readnatpmpresponseorretry() for public address failed with %d error.\n", r_read);
+            LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "portmap: gateway [IPv4]: %s\n", gateway4->ToStringAddr());
+
+            // Open a port mapping on whatever local address we have toward the gateway.
+            struct in_addr inaddr_any;
+            inaddr_any.s_addr = htonl(INADDR_ANY);
+            auto res = PCPRequestPortMap(pcp_nonce, *gateway4, CNetAddr(inaddr_any), private_port, requested_lifetime);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/mapport.cpp:90]: i've thought about this, but due to how bitcoin handles non-standard ports, we really want the configured external port, not another one, i think it makes sense to keep trying to get it, even if the router assigns us a different one once.

File: src/mapport.cpp (hunk 43 above)
[the remark this answers is not in the document]
Comment (laanwj) [reply src/mapport.cpp:109]: >  Why make mappings for all local IPv6 addresses?

It's the sensible choice IMO. Some routers will assign a whole bunch of routable IPv6 addresses but only allow pinholing for some. It's doesn't hurt to try.

> Also, it just occurred to me, GetLocalAddresses() operates regardless of -bind= option

Yes. But mind that `-natpmp` and `-pnp` are set to 0 if  `-bind` is specified. In that case we assume the user has a more complex configuration and will just do their own mapping.

File: src/util/pcp.cpp [hunk 50]
```diff
@@ -0,0 +1,524 @@
...
+    request[ofs + PCP_HDR_VERSION_OFS] = PCP_VERSION;
+    request[ofs + PCP_HDR_OP_OFS] = PCP_REQUEST | PCP_OP_MAP;
+    WriteBE32(request.data() + ofs + PCP_HDR_LIFETIME_OFS, lifetime);
+    if (!PCPWrapAddress(Span(request).subspan(ofs + PCP_REQUEST_HDR_IP_OFS, ADDR_IPV6_SIZE), internal)) return MappingError::NETWORK_ERROR;
+
+    ofs += PCP_HDR_SIZE;
+
+    // Fill in MAP request packet, See RFC6887 Figure 9.
+    // Randomize mapping nonce (this is repeated in the response, to be able to
+    // correlate requests and responses, and used to authenticate changes to the mapping).
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:447]: Yes, i initially had the wrong idea of what it did, should update the comment.

File: src/util/pcp.cpp [hunk 51]
```diff
@@ -0,0 +1,524 @@
...
+    // Create UDP socket (IPv4 or IPv6 based on provided gateway).
+    auto sock{CreateSock(dest_addr.ss_family, SOCK_DGRAM, IPPROTO_UDP)};
+    if (!sock) {
+        LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "pcp: Could not create UDP socket: %s\n", NetworkErrorString(WSAGetLastError()));
+        return MappingError::NETWORK_ERROR;
+    }
+
+    // Make sure that we send from requested destination address, anything else will be
+    // rejected by a security-conscious router.
+    if (sock->Bind((struct sockaddr*)&bind_addr, bind_addrlen) != 0) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/pcp.cpp:408]: NATPMP is IPv4 only. In the case of IPv4 we don't need to explicitly bind. We don't do this for PCP either (hence passing the BIND_ANY address).

File: src/mapport.cpp (hunk 43 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/mapport.cpp:109]: >> I think it is going to result in multiple mappings on the same external IPv6 address but on different ports.

> i don't think so? We only request one mapping per IPv6 address at most.

Afaik PCP always uses a pinhole, which does not involve assinging a (different) port.

We do end up with our node being announced multiple times with different IP addresses, which could cause some other node to connect to use twice. That can already happen when you have IPv4 and IPv6 (and Tor and I2P) enabled.

If we're really worried about this, it might make sense to try each IPv6 address sequentially and stop when one is acknowledged. I think that can wait for a followup.

File: src/mapport.cpp (hunk 49 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/mapport.cpp:90]: Indeed. Maybe just add a comment that this is intentional.

**Comment by Sjors** [comment]
Compared to faacd264417bd7f3f08c5ff497458030b3a54fbc I'm now getting "Could not determine [IPv4/IPv6] default gateway". The changes to `defined(__APPLE__)` in `netif.cpp` don't give me any immediate hint of what could explain this.

File: src/util/netif.cpp [hunk 52]
```diff
@@ -0,0 +1,299 @@
...
+        // Iterate over addresses within message, get destination and gateway (if present).
+        // Address data starts after header.
+        size_t sa_pos = msg_pos + sizeof(struct rt_msghdr);
+        std::optional<CNetAddr> dst, gateway;
+        for (int i = 0; i < RTAX_MAX; i++) {
+            if (rt->rtm_addrs & (1 << i)) {
+                // 2 is just sa_len + sa_family, the theoretical minimum size of a socket address.
+                if ((sa_pos + 2) > next_msg_pos) return std::nullopt;
+                const struct sockaddr* sa = (const struct sockaddr*)(buf.data() + sa_pos);
+                if (sa->sa_len < 2 || (sa_pos + sa->sa_len) > next_msg_pos) return std::nullopt;
```
Comment (Sjors) [inline src/util/netif.cpp:215]: 9a067b5ac154154ec9008a0e8f2d8f03e994a589: this is triggered on my Intel macOS 14.5 machine. If I comment out the `if` statement it works fine.

Comment (Sjors) [reply src/util/netif.cpp:215]:
```
msg_pos=0 sizeof(rt_msghdr)=92 buf.size()=10948
```

Comment (Sjors) [reply src/util/netif.cpp:215]: For IPv4:

```
sa->sa_len=16 sa_pos=92 next_msg_pos=144
sa->sa_len=16 sa_pos=108 next_msg_pos=144
sa->sa_len=0 sa_pos=124 next_msg_pos=144
2024-07-08T12:24:02Z [mapport] [net] portmap: Could not determine IPv4 default gateway
```

For IPv6:

```
sa->sa_len=28 sa_pos=92 next_msg_pos=180
sa->sa_len=28 sa_pos=120 next_msg_pos=180
sa->sa_len=0 sa_pos=148 next_msg_pos=180
2024-07-08T12:24:02Z [mapport] [net] portmap: Could not determine IPv6 default gateway
```

Comment (Sjors) [reply src/util/netif.cpp:215]: Or maybe the following:

```cpp
            if (rt->rtm_addrs & (1 << i)) {
                // 2 is just sa_len + sa_family, the theoretical minimum size of a socket address.
                if ((sa_pos + 2) > next_msg_pos) return std::nullopt;
                const struct sockaddr* sa = (const struct sockaddr*)(buf.data() + sa_pos);
                fprintf(stderr, "i=%d sa->sa_len=%hhu sa_pos=%lu next_msg_pos=%zu\n", i, sa->sa_len, sa_pos, next_msg_pos);
                if (sa->sa_len >= 2 && (sa_pos + sa->sa_len) <= next_msg_pos) {
                    if (i == RTAX_DST) {
                        dst = FromSockAddr(sa);
                    } else if (i == RTAX_GATEWAY) {
                        gateway = FromSockAddr(sa);
                    }
                }
                // Skip to next address.
                sa_pos += sa->sa_len;
```

On macOS `RTAX_DST` is 0 and `RTAX_GATEWAY` is 1. 

```
i=0 sa->sa_len=16 sa_pos=92 next_msg_pos=144
i=1 sa->sa_len=16 sa_pos=108 next_msg_pos=144
i=2 sa->sa_len=0 sa_pos=124 next_msg_pos=144
i=5 sa->sa_len=0 sa_pos=124 next_msg_pos=144
```

As for the i=2 and i=5:

```cpp
/*
 * Index offsets for sockaddr array for alternate internal encoding.
 */
#define RTAX_DST        0       /* destination sockaddr present */
#define RTAX_GATEWAY    1       /* gateway sockaddr present */
#define RTAX_NETMASK    2       /* netmask sockaddr present */
#define RTAX_GENMASK    3       /* cloning mask sockaddr present */
#define RTAX_IFP        4       /* interface name sockaddr present */
#define RTAX_IFA        5       /* interface addr sockaddr present */
#define RTAX_AUTHOR     6       /* sockaddr for author of redirect */
#define RTAX_BRD        7       /* for NEWADDR, broadcast or p-p dest addr */
#define RTAX_MAX        8       /* size of array to allocate */
```

File: src/mapport.cpp (hunk 49 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/mapport.cpp:90]: Ok, I am fine with just adding a comment and leave the code as is. This is probably too edge case to bother complicating the code with it, but just mentioning why I think it is better to keep using the initially assigned port even if it is different than the one we requested:

* We request port `8333`, but for whatever reason the router assigns `15000` with an external address let's say `1.2.3.4`.
* We start using and advertise `1.2.3.4:15000` to other peers, it propagates into nodes' addrmans. The ones that actually connect to us will have it as good in their tried tables.
* Eventually we renew but try port `8333` as in the initial PCP request. This time it succeeds so we get `8333`, or it is still unavailable, but we get another random port e.g. `16000`. We start advertising `1.2.3.4:8333` or `1.2.3.4:16000` and the good old `1.2.3.4:15000` is now junk in nodes' addrmans. This can repeat over and over with different random ports.

File: src/util/pcp.cpp (hunk 40 above)
Comment (vasild) [reply src/util/pcp.cpp:400]: Yes, missed updates should result in us advertising the wrong (old) address only until the next renewal.

File: src/mapport.cpp (hunk 49 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/mapport.cpp:90]: > due to how bitcoin handles non-standard ports, we really want the configured external port

Bitcoin Core had a strong preference to connect to peers that listen on port `8333`. Is this what you mean? That was removed at some point.

File: src/util/pcp.cpp (hunk 51 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/util/pcp.cpp:408]: I admit I am somewhat confused.

Do we assume that for IPv6, address translation is never done (e.g. https://www.rfc-editor.org/rfc/rfc6296) and that for IPv6 we only need to pinhole the firewall?

> For IPv6 we know what internal address we want, and what external address we want

You mean that both internal and external are the same and we get that from `GetLocalAddresses()`?

File: src/util/pcp.cpp (hunk 45 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/util/pcp.cpp:452]: Would all-zeros work as well for IPv6 / pinholing? If yes, then this can probably be simplified to always pass all-zeros.

File: src/mapport.cpp (hunk 43 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/mapport.cpp:109]: Ok, I was having NAT in mind when I wrote "is going to result in multiple mappings on the same external IPv6 address". Sorry for the noise.

[the remark this answers is not in the document]
Comment (vasild) [reply src/mapport.cpp:109]: In addition to the `-bind` [thing](https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1658949236) there is also a complication with the port: if `-bind=10.0.0.1:20000 -bind=[5566::1]:30000` has been used, then `GetListenPort()`, currently used by `mapport.cpp`, is not the right thing to do because it would return `20000`.

To resolve both, we could get the listening addresses + the correct ports from:
1. `AddLocal()` / `mapLocalHost`, is called after bind (good), but also from other places and after the bind it is called only if `fDiscover` is true (bad).
2. `CConnman::vhListenSocket`, has sockets that used `BF_DONT_ADVERTISE` during bind. Those should be omitted.
3. `-bind` arguments, could get it from `init.cpp / connOptions`. Need to duplicate some of the logic of `CConnman::InitBinds()`.
4. introduce a new global list of `addr:port`, similar but not identical to `mapLocalHost`, seems imperfect because the list is almost the same as `mapLocalHost`, ideally those addresses should be in one place with proper flags to distinguish them (or maybe not?).

Here is a crude implementation of 4:

<details>
<summary>[patch] do 4.</summary>

```diff
diff --git a/src/mapport.cpp b/src/mapport.cpp
index a1d584dae9..56d21e792b 100644
--- a/src/mapport.cpp
+++ b/src/mapport.cpp
@@ -48,13 +48,13 @@ static bool ProcessPCP()
     // The same nonce is used for all mappings, this is allowed by the spec, and simplifies keeping track of them.
     PCPMappingNonce pcp_nonce;
     GetRandBytes(pcp_nonce);
 
     bool ret = false;
     bool no_resources = false;
-    const uint16_t private_port = GetListenPort();
+    const uint16_t private_port = GetListenPort(); // XXX could be the wrong port if -bind is used
     // Multiply the reannounce period by two, as we'll try to renew approximately halfway.
     const uint32_t requested_lifetime = std::chrono::seconds(PORT_MAPPING_REANNOUNCE_PERIOD * 2).count();
     uint32_t actual_lifetime = 0;
     std::chrono::milliseconds sleep_time;
 
     // Local functor to handle result from PCP/NATPMP mapping.
@@ -101,14 +101,18 @@ static bool ProcessPCP()
         if (!gateway6) {
             LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "portmap: Could not determine IPv6 default gateway\n");
         } else {
             LogPrintLevel(BCLog::NET, BCLog::Level::Debug, "portmap: gateway [IPv6]: %s\n", gateway6->ToStringAddr());
 
             // Try to open pinholes for all routable local IPv6 addresses.
-            for (const auto &addr: GetLocalAddresses()) {
-                if (!addr.IsRoutable() || !addr.IsIPv6()) continue;
+            const auto addresses =
+                WITH_LOCK(g_addresses_for_port_map.mutex, return g_addresses_for_port_map.addresses);
+            for (const auto& addr : addresses) {
+                if (!addr.IsIPv6()) {
+                    continue;
+                }
                 auto res = PCPRequestPortMap(pcp_nonce, *gateway6, addr, private_port, requested_lifetime);
                 handle_mapping(res);
             }
         }
 
         // Log message if we got NO_RESOURCES.
diff --git a/src/net.cpp b/src/net.cpp
index 7c6babc389..b621e76696 100644
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -112,12 +112,15 @@ static const uint64_t RANDOMIZER_ID_ADDRCACHE = 0x1cf2e4ddd306dda9ULL; // SHA256
 // Global state variables
 //
 bool fDiscover = true;
 bool fListen = true;
 GlobalMutex g_maplocalhost_mutex;
 std::map<CNetAddr, LocalServiceInfo> mapLocalHost GUARDED_BY(g_maplocalhost_mutex);
+
+AddressesForPortMap g_addresses_for_port_map;
+
 std::string strSubVersion;
 
 size_t CSerializedNetMsg::GetMemoryUsage() const noexcept
 {
     // Don't count the dynamic memory used for the m_type string, by assuming it fits in the
     // "small string" optimization area (which stores data inside the object itself, up to some
@@ -3151,14 +3154,17 @@ bool CConnman::Bind(const CService& addr_, unsigned int flags, NetPermissionFlag
         if ((flags & BF_REPORT_ERROR) && m_client_interface) {
             m_client_interface->ThreadSafeMessageBox(strError, "", CClientUIInterface::MSG_ERROR);
         }
         return false;
     }
 
-    if (addr.IsRoutable() && fDiscover && !(flags & BF_DONT_ADVERTISE) && !NetPermissions::HasFlag(permissions, NetPermissionFlags::NoBan)) {
-        AddLocal(addr, LOCAL_BIND);
+    if (addr.IsRoutable() && !(flags & BF_DONT_ADVERTISE) && !NetPermissions::HasFlag(permissions, NetPermissionFlags::NoBan)) {
+        if (fDiscover) {
+            AddLocal(addr, LOCAL_BIND);
+        }
+        WITH_LOCK(g_addresses_for_port_map.mutex, g_addresses_for_port_map.addresses.push_back(addr));
     }
 
     return true;
 }
 
 bool CConnman::InitBinds(const Options& options)
diff --git a/src/net.h b/src/net.h
index 11cb01a95d..ae08603e64 100644
--- a/src/net.h
+++ b/src/net.h
@@ -175,12 +175,17 @@ struct LocalServiceInfo {
     uint16_t nPort;
 };
 
 extern GlobalMutex g_maplocalhost_mutex;
 extern std::map<CNetAddr, LocalServiceInfo> mapLocalHost GUARDED_BY(g_maplocalhost_mutex);
 
+extern struct AddressesForPortMap {
+    Mutex mutex;
+    std::vector<CService> addresses GUARDED_BY(mutex);
+} g_addresses_for_port_map;
+
 extern const std::string NET_MESSAGE_TYPE_OTHER;
 using mapMsgTypeSize = std::map</* message type */ std::string, /* total bytes */ uint64_t>;
 
 class CNodeStats
 {
 public:
```
</details>

File: src/util/netif.cpp (hunk 52 above)
Comment (laanwj) [reply src/util/netif.cpp:215]: hm... `sa_len=0` is really strange because it doesn't know how to advance, there isn't even place for the size! (which it just read in the line above it!) it should at least break out of the loop in that case

**Comment by laanwj** [comment]
i still intend to do this, but honestly i've kind of lost track of the scope. Can we first aim to fix the bugs here, then merge an implementation that at least doesn't have more problems than the current `libnatpmp` implementation?

Then later on we can make sure all edge cases with `bind`, `listenport`, routers assigning different ports, etc. are handled.

File: src/util/netif.cpp (hunk 52 above)
Comment (Sjors) [reply src/util/netif.cpp:215]: I'm a bit confused where you want this code to go...

**Comment by Sjors** [comment]
@laanwj I suggest adding a "Suggested Followups" section to the PR description, where you can list known issues that can be punted.

File: src/util/netif.cpp (hunk 52 above)
Comment (laanwj) [reply src/util/netif.cpp:215]: yeah no problem, i'll push the change as a commit (after rebase, i guess)

Comment (Sjors) [reply src/util/netif.cpp]: It works again with 26436dce049d4215a112a1147b624c0435dbc8a6.

Comment (laanwj) [reply src/util/netif.cpp]: Thanks for testing, apperently we over-simplified that. WIl keep it like this.

File: src/mapport.cpp [hunk 53]
```diff
@@ -46,104 +43,96 @@ using namespace std::chrono_literals;
...
+        if (actual_lifetime < 30) {
+            LogPrintLevel(BCLog::NET, BCLog::Level::Warning, "portmap: Got impossibly short mapping lifetime of %d seconds\n", actual_lifetime);
+            return false;
         }
-    }
+        // RFC6887 11.2.1 recommends that clients send their first renewal packet at a time chosen with uniform random
+        // distribution in the range 1/2 to 5/8 of expiration time.
+        std::chrono::seconds sleep_time_min(actual_lifetime / 2);
+        std::chrono::seconds sleep_time_max(actual_lifetime * 5 / 8);
+        sleep_time = sleep_time_min + GetRandMillis(sleep_time_max - sleep_time_min);
```
Comment (Sjors) [inline src/mapport.cpp]: 4ef4eee3b7806ad3710c12cbf4e305a814ba8b40: this commit still uses `GetRandMillis`

Comment (Sjors) [reply src/mapport.cpp]: Oh nvm, the fixup! commit isn't squashed yet.

**Comment by Sjors** [comment]
@laanwj is there anything you still want to change here, or should we review it as is first?

**Comment by laanwj** [comment]
Well. At the least i still need to port it to the new build system (and rebase and squash). There are likely some other smaller comments and nits here and there that i can easily address, but it's kind of become a mess (no one's fault but github and how it handles PRs with lots of comments), so need to take some time to sort it out.

**Comment by laanwj** [comment]
Did a rebase for the changes since last master, including CMake and comparing Span<> using `std::equal_range`. No other changes.

> https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1658764974 avoid unreachable nets (not given to -onlynet=)
> https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1658949236 could announce an addr:port where we do not listen (no -bind)
> https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1684368824 could announce the wrong port because it uses GetListenPort()
> https://github.com/bitcoin/bitcoin/pull/30043#discussion_r1679709347 if we requested one port but another was assigned, then which one to use in the renewal?

i agree these are reasonably important, but i'm not going to do them in the scope of this PR. This is more or less equivalent with regard to these edge cases as the current NATPMP code that it replaces. It's  usefulas-is for most normal home users.

(sorry, this already scope crept so much from the initial "IPv6 pinholing support" that this was, let's just try to agree on these changes now)

**Comment by Sjors** [comment]
re-utACK 6ea0eb954bc810da71cd057c116f5c2d359a1f37

Tested against my OPNsense router running miniupnpd 2.3.6 with pf backend, on Intel macOS 13.7 and 15.0, Ubuntu 24.04, FreeBSD 14 and Windows 11.

File: src/util/pcp.cpp [hunk 54]
```diff
@@ -0,0 +1,524 @@
...
+constexpr size_t PCP_HDR_SIZE = 24;
+//! Map request and response size in bytes (RFC6887 section 11.1).
+constexpr size_t PCP_MAP_SIZE = 36;
+
+// Header offsets shared between request and responses (RFC6887 7.1, 7.2), relative to start of packet.
+//!  Version field (1 byte).
+constexpr size_t PCP_HDR_VERSION_OFS = NATPMP_HDR_VERSION_OFS;
+//!  Opcode field (1 byte).
+constexpr size_t PCP_HDR_OP_OFS = NATPMP_HDR_OP_OFS;
+//!  Requested lifetime (request), granted lifetime (response) (2 bytes).
```
Comment (achow101) [inline src/util/pcp.cpp:121]: In cbb053c5f6fa63b08fe8fb200b143cca64fc0626 "net: Add PCP and NATPMP implementation"

Lifetime is 4 bytes.

File: src/util/pcp.cpp [hunk 55]
```diff
@@ -0,0 +1,524 @@
...
+        if (!addr.GetIn6Addr(&addr6)) return false;
+        std::memcpy(wrapped_addr.data(), &addr6, ADDR_IPV6_SIZE);
+        return true;
+    } else {
+        return false;
+    }
+}
+
+//! Unwrap PCP-encoded address according to RFC6887.
+CNetAddr PCPUnwrapAddress(Span<const uint8_t> wrapped_addr)
```
Comment (achow101) [inline src/util/pcp.cpp:203]: In cbb053c5f6fa63b08fe8fb200b143cca64fc0626 "net: Add PCP and NATPMP implementation"

`CNetAddr` has a `SetLegacyIPv6` method which does the same thing. Could use that instead of duplicating implementation.

File: src/util/netif.cpp [hunk 56]
```diff
@@ -0,0 +1,303 @@
...
+    }
+}
+
+std::vector<CNetAddr> GetLocalAddresses()
+{
+    std::vector<CNetAddr> addresses;
+#ifdef WIN32
+    char pszHostName[256] = "";
+    if (gethostname(pszHostName, sizeof(pszHostName)) != SOCKET_ERROR) {
+        addresses = LookupHost(pszHostName, 0, true);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/util/netif.cpp:281]: Completely agree, but i think it's out of scope for this PR to change this. This function was literally transplanted from net.cpp.

File: src/util/pcp.cpp (hunk 54 above)
Comment (laanwj) [reply src/util/pcp.cpp:121]: Thanks, will update

File: src/util/pcp.cpp (hunk 55 above)
Comment (Sjors) [reply src/util/pcp.cpp:203]: Maybe the other way around, replace the `CNetAddr` implementation with what you wrote here. But that sounds like a followup.

File: src/util/netif.cpp (hunk 56 above)
[the remark this answers is not in the document]
Comment (Sjors) [reply src/util/netif.cpp:281]: Agree that fixing satoshi-isms can be done in a followup.

File: src/util/pcp.cpp (hunk 55 above)
Comment (laanwj) [reply src/util/pcp.cpp:203]: Wouldn't that have the same conceptual issue, but the other way around? eg locking the bitcoin implementation to RFC6887 specifics. 

It didn't feel right, it's different specifications coming from a different place that somehow in a parallel evolution ended up similarly.

Now looking at `SetLegacyIPv6` i see the differences: 
- there's the TORV2 case. It just marks the addess as invalid, which it would be anyway, so *that* wouldn't be problematic here.
- there's also the `NET_INTERNAL` case, which makes no sense in this context.

i think it's the second one that made me doubt the most-i have no idea what else we'd want to encode into addresses IPv6 in the future, but it shouldn't interfere with the PCP implementation.

**Review by vasild — APPROVED** [review]
ACK 6c89fab9fddb8952ed2ba13048cd87856a2f9397 (modulo squashing the fixup commit)

Thank you!

**Comment by ffrediani** [comment]
Great improvement to have more home nodes serving content back to network in IPv6, specially in times of IPv4 exhaustion.

What would be the configuration in bitcoin.conf file ?

nat=1 will keep doing for IPv4 only ?
pcp=1 will do for IPv6 only or for both and replace/complement the existing IPv4 and replace nat=1 in the future ?

**Comment by laanwj** [comment]
Force push: auto-squashed the fixup commit.

> In this PR, natpmp=1 controls both PCP and NAT-PMP.

Yes, after initial discussion we decided to add no new command line, or UI options. PCP is regarded a newer version of NATPMP (which is strictly true) that has some extra mapping features as well as IPv6 support.

**Review by vasild — APPROVED** [review]
ACK 5c7cacf649a6b474b876a7d219c7dc683a25e33d

**Comment by Sjors** [comment]
ACK 5c7cacf649a6b474b876a7d219c7dc683a25e33d

Just a documentation squash since my last test and review.

**Comment by achow101** [comment]
ACK 5c7cacf649a6b474b876a7d219c7dc683a25e33d

**Comment by fanquake** [comment]
From the tidy job (https://api.cirrus-ci.com/v1/task/4831368570470400/logs/ci.log):
```bash
[21:19:24.426] Built target bitcoin_crypto_avx2
[21:19:26.500] Error: netif.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::CNetAddr(in_addr const&)', can suppess with:
[21:19:26.500]     SUPPRESS["netif.cpp.o netaddress.cpp.o _ZN8CNetAddrC1ERK7in_addr"]=1
[21:19:26.502] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::CNetAddr(in_addr const&)', can suppess with:
[21:19:26.502]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZN8CNetAddrC1ERK7in_addr"]=1
[21:19:26.516] Error: netif.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::CNetAddr(in6_addr const&, unsigned int)', can suppess with:
[21:19:26.516]     SUPPRESS["netif.cpp.o netaddress.cpp.o _ZN8CNetAddrC1ERK8in6_addrj"]=1
[21:19:26.517] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::CNetAddr(in6_addr const&, unsigned int)', can suppess with:
[21:19:26.517]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZN8CNetAddrC1ERK8in6_addrj"]=1
[21:19:26.530] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CService::SetSockAddr(sockaddr const*)', can suppess with:
[21:19:26.530]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZN8CService11SetSockAddrEPK8sockaddr"]=1
[21:19:26.542] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CService::CService(in_addr const&, unsigned short)', can suppess with:
[21:19:26.542]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZN8CServiceC1ERK7in_addrt"]=1
[21:19:26.554] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CService::CService(CNetAddr const&, unsigned short)', can suppess with:
[21:19:26.554]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZN8CServiceC1ERK8CNetAddrt"]=1
[21:19:26.567] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CService::CService()', can suppess with:
[21:19:26.567]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZN8CServiceC1Ev"]=1
[21:19:26.579] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::GetIn6Addr(in6_addr*) const', can suppess with:
[21:19:26.579]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZNK8CNetAddr10GetIn6AddrEP8in6_addr"]=1
[21:19:26.590] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::ToStringAddr[abi:cxx11]() const', can suppess with:
[21:19:26.590]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZNK8CNetAddr12ToStringAddrB5cxx11Ev"]=1
[21:19:26.603] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::GetInAddr(in_addr*) const', can suppess with:
[21:19:26.603]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZNK8CNetAddr9GetInAddrEP7in_addr"]=1
[21:19:26.617] Error: netif.cpp.o depends on netaddress.cpp.o symbol 'CNetAddr::IsBindAny() const', can suppess with:
[21:19:26.617]     SUPPRESS["netif.cpp.o netaddress.cpp.o _ZNK8CNetAddr9IsBindAnyEv"]=1
[21:19:26.631] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CService::GetSockAddr(sockaddr*, unsigned int*) const', can suppess with:
[21:19:26.631]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZNK8CService11GetSockAddrEP8sockaddrPj"]=1
[21:19:26.645] Error: pcp.cpp.o depends on netaddress.cpp.o symbol 'CService::ToStringAddrPort[abi:cxx11]() const', can suppess with:
[21:19:26.645]     SUPPRESS["pcp.cpp.o netaddress.cpp.o _ZNK8CService16ToStringAddrPortB5cxx11Ev"]=1
[21:19:26.669] Error: Unexpected dependencies were detected. Check previous output.
```

**Comment by glozow** [comment]
Removing the "Needs release note label" since there are notes for #31130. Lmk if this doesn't sound right.

**Comment by laanwj** [comment]
i've checked the 31330 release notes, they're kind of brief but get the gist of the change. 

We might want to add a sentence that the NAT-PMP/PCP implementation was replaced. It's not super important to end users but if they encounter problems they'll want to report it.

Also "Setting `-upnp` will now return an error" won't be correct after #31916 is merged.

i'll open a PR for this.

**Comment by glozow** [comment]
Thank you @laanwj! Would you mind adding it to the release notes draft actually, instead of opening a PR? https://github.com/bitcoin-core/bitcoin-devwiki/wiki/29.0-Release-Notes-draft

**Review by algreenofficial — COMMENTED** [review]
.
