### PR TITLE
script, assumeutxo: Enhance validations in utxo_snapshot.sh

### LINKED ISSUE #27841: Stuck chainstate when utxo_snapshot.sh fails
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

IBD/chainstate gets stuck if utxo_snapshot.sh fails. No new blocks are downloaded. Restarting bitcoind does not help. Taking another snapshot __at an earlier height__ or reindex is required to repair.

utxo_snapshot.sh output:
```
Rewinding chain back to height 788440 (by invalidating 000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7); this may take a while
Generating UTXO snapshot...
error code: -8
error message:
/home/chris/Desktop/assumeutxo/test/utxo-788440.dat already exists. If you are sure this is what you want, move it out of the way first
```

Note that moving the file or choosing another filename and rerunning does not fix. But taking another snapshot at an earlier height will.

### Expected behaviour

If utxo_snapshot.sh fails, bitcoind should cancel rewind and recover.

Also, if a filepath that already exists is passed to utxosnapshot.sh, it should early exit before rewinding. This could perhaps be considered a separate issue.

### Steps to reproduce

1. Create a dummy file for the purpose of the test e.g. `echo "some bytes so file is not empty" > ./utxo-788440.dat`
2. Run bitcoind and wait for it to sync
3. Run utxosnapshot.sh with some blockheight and a filepath __that already exists__ e.g. `./contrib/devtools/utxo_snapshot.sh 788440 ./utxo-788440.dat ./src/bitcoin-cli`
4. Wait for chain rewind to happen, snapshot to be generated and write to disk fail
5. Observe bitcoind is now stuck with an invalid block at the rewind height

### Relevant log output

```
2023-06-08T23:51:50Z [httpworker.3] UpdateTip: new best=000000000000000000014a9d36f6a19aca593f0c228ae1b1b6fe33361fa67be1 height=788440 version=0x2001e000 log2_work=94.162204 tx=832727241 date='2023-05-06T02:54:13Z' progress=0.987258 cache=790.3MiB(1245160txo)
2023-06-08T23:51:50Z [httpworker.3] InvalidChainFound: invalid block=000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7  height=788441  log2_work=94.162217  date=2023-05-06T02:55:43Z
2023-06-08T23:51:50Z [httpworker.3] InvalidChainFound:  current best=000000000000000000014a9d36f6a19aca593f0c228ae1b1b6fe33361fa67be1  height=788440  log2_work=94.162204  date=2023-05-06T02:54:13Z
```

```
Rewinding chain back to height 788440 (by invalidating 000000000000000000052ac0ce9b8f1a2e7691771e6386f770432c9443dc2af7); this may take a while
Generating UTXO snapshot...
error code: -8
error message:
/home/chris/Desktop/assumeutxo/test/utxo-788440.dat already exists. If you are sure this is what you want, move it out of the way first
```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v25.99.0-3dc6fd620e28

### Operating system and version

Linux 6.3.1-arch2-1

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by pablomartin4btc**
This PR resolves #27841 and some more:

- Ensure that the snapshot height is higher than the pruned block height when the node is pruned (Suggested by @Sjors [here](https://github.com/bitcoin/bitcoin/pull/28553#issuecomment-1804941396)).

- Validate the correctness of the file path and check if the file already exists (@hazeycode's [#27845](https://github.com/bitcoin/bitcoin/pull/27845)).

- Make network activity disablement optional for the user (Suggested by @Sjors [here](https://github.com/bitcoin/bitcoin/pull/16899#discussion_r342735815) and [here](https://github.com/bitcoin/bitcoin/pull/16899#issuecomment-536520911)).

- Ensure the `reconsiderblock` command is triggered on exit (@hazeycode's same PR as above), even in the case of user interruption (Ctrl-C).

In order to perform some testing please follow the instructions in the description of previous @hazeycode's PR #27845.

### CODE REVIEW

**Comment by Sjors** [comment]
Concept ACK

File: contrib/devtools/utxo_snapshot.sh [hunk 1]
```diff
@@ -26,6 +28,57 @@ OUTPUT_PATH="${1}"; shift;
 # Most of the calls we make take a while to run, so pad with a lengthy timeout.
 BITCOIN_CLI_CALL="${*} -rpcclienttimeout=9999999"
 
+# Check if the node is pruned and get the pruned block height
+PRUNED=$( ${BITCOIN_CLI_CALL} getblockchaininfo | grep 'pruneheight' | awk '{print $2}' | tr -d ',' )
```
Comment (Sjors) [inline contrib/devtools/utxo_snapshot.sh:32]: On macOS 13.6 this silently exists with `-1` when a node is _not_ pruned (`pruneheight` is not set).

File: contrib/devtools/utxo_snapshot.sh [hunk 2]
```diff
@@ -26,6 +28,57 @@ OUTPUT_PATH="${1}"; shift;
...
+  cleanup
+  exit 1
+}
+
+# Trap for normal exit and Ctrl-C
+trap cleanup EXIT
+trap early_exit INT
+
+# Prompt the user to disable network activity
+read -p "Do you want to disable network activity (setnetworkactive false) before running invalidateblock? (Y/n): " -r
```
Comment (Sjors) [inline contrib/devtools/utxo_snapshot.sh:72]: If I abort here with `ctrl + c` it tries to cleanup, so maybe move the `trap` calls down a bit?

File: contrib/devtools/utxo_snapshot.sh [hunk 3]
```diff
@@ -26,6 +28,57 @@ OUTPUT_PATH="${1}"; shift;
...
+
+# Validate that the path is correct
+if [[ "${OUTPUT_PATH}" != "-" && ! -d "$(dirname "${OUTPUT_PATH}")" ]]; then
+  (>&2 echo "Error: The directory $(dirname "${OUTPUT_PATH}") does not exist.")
+  exit 1
+fi
+
+function cleanup {
+  (>&2 echo "Restoring chain to original height; this may take a while")
+  ${BITCOIN_CLI_CALL} reconsiderblock "${PIVOT_BLOCKHASH}"
```
Comment (Sjors) [inline contrib/devtools/utxo_snapshot.sh:53]: Note that once `invalidateblock` has been called, this won't stop it. It will go all the way back and then forward again.

**Review by Sjors — COMMENTED** [review]
A few suggestions after testing and reviewing 3cb390f3c59d3ed0475f1be0c886d46a044fa898.

File: contrib/devtools/utxo_snapshot.sh (hunk 1 above)
Comment (pablomartin4btc) [reply contrib/devtools/utxo_snapshot.sh:32]: I'll update it with an alternative, as I don't have an instance with macOS, please let me know if that would work better now.

File: contrib/devtools/utxo_snapshot.sh (hunk 2 above)
Comment (pablomartin4btc) [reply contrib/devtools/utxo_snapshot.sh:72]: Yes! I'll do, but the `reconsiderblock` won't do anything, the issue I see now is that `PIVOT_BLOCKHASH` wasn't initialised so perhaps it fails there.

File: contrib/devtools/utxo_snapshot.sh (hunk 3 above)
Comment (pablomartin4btc) [reply contrib/devtools/utxo_snapshot.sh:53]: Same as in the previous PR #27845. We could add more context in the output message and perhaps we could update the documentation as well:
https://github.com/bitcoin/bitcoin/blob/5800c558eb5efb4839ed00d6967e43306d68e1c3/doc/design/assumeutxo.md?plain=1#L42-L45

**Comment by pablomartin4btc** [comment]
> By the way, at some point when a bash script gets very complicated, it may be better to convert it to Python.

I do agree, but so far I think it's manageable. I'm happy to convert it if more reviewers see other issues there.

File: contrib/devtools/utxo_snapshot.sh (hunk 2 above)
Comment (pablomartin4btc) [reply contrib/devtools/utxo_snapshot.sh:68]: done.

File: contrib/devtools/utxo_snapshot.sh (hunk 1 above)
Comment (pablomartin4btc) [reply contrib/devtools/utxo_snapshot.sh]: Done, pls let me know.

**Comment by pablomartin4btc** [comment]
Addressed @Sjors's feedback.

cc @jamesob as he reviewed #27845, @ryanofsky & @theStack

**Comment by Sjors** [comment]
tACK 11b7269d83a56f919f9dddb7f7c72a96d428627f

**Review by BrandonOdiwuor — COMMENTED** [review]
Concept ACK

**Review by BrandonOdiwuor — APPROVED** [review]
tested ACk 11b7269d83a56f919f9dddb7f7c72a96d428627f

1. Successfully tested error handling added and chainstate can be automatically recovered if an error occurs e.g when the snapshot file already exists or user interruption by `ctrl + c`
2. Successfully tested the option to enable or disable network activity

File: contrib/devtools/utxo_snapshot.sh [hunk 4]
```diff
@@ -1,13 +1,15 @@
...
-# Copyright (c) 2019 The Bitcoin Core developers
+# Copyright (c) 2019-2023 The Bitcoin Core developers
 # Distributed under the MIT software license, see the accompanying
 # file COPYING or http://www.opensource.org/licenses/mit-license.php.
 #
 export LC_ALL=C
 
 set -ueo pipefail
 
+NETWORK_DISABLED=false
```
Comment (ryanofsky) [inline contrib/devtools/utxo_snapshot.sh:11]: In commit "script: Enhance validations in utxo_snapshot.sh" (11b7269d83a56f919f9dddb7f7c72a96d428627f)

Assignment seems a little out of place here, would suggest moving it below `PRUNE=...` with other variable assignments.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 11b7269d83a56f919f9dddb7f7c72a96d428627f

**Comment by ryanofsky** [comment]
Note: this actually had 3 acks. DrahtBot didn't count https://github.com/bitcoin/bitcoin/pull/28852#pullrequestreview-1741060818 due to capitalization
