### PR TITLE
wallet: Derive inactive HD chains in additional places

### LINKED ISSUE #24335: Segmentation Fault in V21 and V22 releases
OS: Ubuntu 20.04.
Releases: Bitcoin Core V21 and V22.

The problem:
I have a lot of HD wallets, with the first transaction in Dic 2017, encrypted, not checked for 5 years.

It starts reescaning and segmentation fault error. Tried with bitcoin-qt, bitcoind, reindex the whole blockchain, and still segmentation fault.
After loading the GUI, load the wallet, again it closes with segmentation fault

V21 and V22 downloaded and checked for signatures and hashes.

The same wallets, if checked after mid-2018-2019 (a year or more) work.

The machine is a DELL inspiron with 16Gb of ram (dbcache=8000). Tried a lot of other things (-rescan, etc) that didn't work.

All other wallets work fine, no problems, but these ones fail with newer versions of bitcoin core. Run bitcoin-wallet info, the wallets are ok, (not corrupted or anything).

If I do the reindex while the wallet is loaded, it crashes the moment the reindex gets to Dic 2017-Jan 2018. Then I reestart without the wallet loaded and it finishes reindexing OK.

In the log says it loads the wallet OK (5s :)), starts reescaning and then nothing else (it crashes).

It crashes 4 or 5 seconds after reescaning (really fast) both bitcoin-qt and bitcoind.

### PR DESCRIPTION
**Pull request by achow101**
Currently inactive HD chains are only derived from at the time a key in that chain is found to have been used. However, at that time, the wallet may not be able to derive keys (e.g. it is locked). Currently we would just move on and not derive any new keys, however this could result in missing funds.

This PR resolves this problem by adding memory only variables to `CHDChain` which track the highest known index. `TopUp` is modified to always try to top up the inactive HD chains, and this process will use the new variables to determine how much to top up. In this way, after an encrypted wallet is unlocked, the inactive HD chains will be topped up and hopefully funds will not be missed.

Note that because these variables are not persisted to disk (because `CHDChain`s for inactive HD chains are not written to disk), if an encrypted wallet is not unlocked in the same session as a key from an inactive chain is found to be used, then it will not be topped up later unless more keys are found.

Additionally, wallets which do not have upgraded key metadata will not derive any keys from inactive HD chains. This is resolved by using the derivation path string in `CKeyMetadata.hdKeypath` to determine what indexes to derive.

### CODE REVIEW

**Comment by achow101** [comment]
Ready for review, supersedes #23277

**Comment by laanwj** [comment]
Concept ACK

**Comment by achow101** [comment]
Rebased for hidden merge conflict.

File: src/wallet/scriptpubkeyman.cpp [hunk 1]
```diff
@@ -1258,44 +1258,70 @@ bool LegacyScriptPubKeyMan::TopUp(unsigned int kpSize)
...
-        // count amount of available keys (internal, external)
-        // make sure the keypool of external and internal keys fits the user selected target (-keypool)
-        int64_t missingExternal = std::max(std::max((int64_t) nTargetSize, (int64_t) 1) - (int64_t)setExternalKeyPool.size(), (int64_t) 0);
-        int64_t missingInternal = std::max(std::max((int64_t) nTargetSize, (int64_t) 1) - (int64_t)setInternalKeyPool.size(), (int64_t) 0);
+    // Top up key pool
+    unsigned int nTargetSize;
+    if (kpSize > 0)
+        nTargetSize = kpSize;
+    else
+        nTargetSize = std::max(gArgs.GetIntArg("-keypool", DEFAULT_KEYPOOL_SIZE), (int64_t) 0);
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.cpp:1285]: Since you're touching this, please make it braces or same line to be inline with the style guide

File: src/wallet/scriptpubkeyman.cpp [hunk 2]
```diff
@@ -1258,44 +1258,70 @@ bool LegacyScriptPubKeyMan::TopUp(unsigned int kpSize)
...
+    int64_t target = std::max((int64_t) nTargetSize, (int64_t) 1);
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.cpp:1286]: please make this not use c-style cast

```
int64_t{1}

File: src/wallet/scriptpubkeyman.cpp [hunk 3]
```diff
@@ -1258,44 +1258,70 @@ bool LegacyScriptPubKeyMan::TopUp(unsigned int kpSize)
...
+        missingExternal = std::max(target - (chain.nExternalChainCounter - chain.m_next_external_index), (int64_t) 0);
+        missingInternal = std::max(target - (chain.nInternalChainCounter - chain.m_next_internal_index), (int64_t) 0);
+    }
 
-        if (!IsHDEnabled() || !m_storage.CanSupportFeature(FEATURE_HD_SPLIT))
-        {
-            // don't create extra internal keys
-            missingInternal = 0;
+    if (!IsHDEnabled() || !m_storage.CanSupportFeature(FEATURE_HD_SPLIT))
+    {
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.cpp:1301]: same line
```suggestion
    if (!IsHDEnabled() || !m_storage.CanSupportFeature(FEATURE_HD_SPLIT)) {
```

File: src/wallet/scriptpubkeyman.cpp [hunk 4]
```diff
@@ -1258,44 +1258,70 @@ bool LegacyScriptPubKeyMan::TopUp(unsigned int kpSize)
...
+        // don't create extra internal keys
+        missingInternal = 0;
+    }
+    bool internal = false;
+    WalletBatch batch(m_storage.GetDatabase());
+    for (int64_t i = missingInternal + missingExternal; i--;)
+    {
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.cpp:1308]:
```suggestion
    for (int64_t i = missingInternal + missingExternal; i--;) {
```

File: src/wallet/scriptpubkeyman.h [hunk 5]
```diff
@@ -354,6 +354,7 @@ class LegacyScriptPubKeyMan : public ScriptPubKeyMan, public FillableSigningProv
      */
     bool TopUpInactiveHDChain(const CKeyID seed_id, int64_t index, bool internal);
 
+    bool TopUpChain(CHDChain& chain ,unsigned int size);
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.h:357]:
```suggestion
    bool TopUpChain(CHDChain& chain, unsigned int size);
```

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
some formatting suggestions (can also just run clang-diff-format.py)

File: src/wallet/scriptpubkeyman.cpp (hunk 1 above)
Comment (achow101) [reply src/wallet/scriptpubkeyman.cpp]: Done

File: src/wallet/scriptpubkeyman.cpp (hunk 2 above)
Comment (achow101) [reply src/wallet/scriptpubkeyman.cpp]: Done

File: src/wallet/scriptpubkeyman.cpp (hunk 3 above)
Comment (achow101) [reply src/wallet/scriptpubkeyman.cpp]: Done

File: src/wallet/scriptpubkeyman.cpp (hunk 4 above)
Comment (achow101) [reply src/wallet/scriptpubkeyman.cpp]: Done

File: src/wallet/scriptpubkeyman.h (hunk 5 above)
Comment (achow101) [reply src/wallet/scriptpubkeyman.h]: Done

File: src/wallet/scriptpubkeyman.cpp [hunk 6]
```diff
@@ -1258,44 +1258,69 @@ bool LegacyScriptPubKeyMan::TopUp(unsigned int kpSize)
...
-            // don't create extra internal keys
-            missingInternal = 0;
+    // Top up key pool
+    unsigned int nTargetSize;
+    if (kpSize > 0) {
+        nTargetSize = kpSize;
+    } else {
+        nTargetSize = std::max(gArgs.GetIntArg("-keypool", DEFAULT_KEYPOOL_SIZE), int64_t{0});
+    }
+    int64_t target = std::max((int64_t) nTargetSize, int64_t{1});
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.cpp:1287]: avoid c-style casts
```suggestion
    int64_t target = std::max(int64_t(nTargetSize), int64_t{1});
```

File: src/wallet/scriptpubkeyman.cpp [hunk 7]
```diff
@@ -1258,44 +1258,69 @@ bool LegacyScriptPubKeyMan::TopUp(unsigned int kpSize)
...
+
+    // count amount of available keys (internal, external)
+    // make sure the keypool of external and internal keys fits the user selected target (-keypool)
+    int64_t missingExternal;
+    int64_t missingInternal;
+    if (chain == m_hd_chain) {
+        missingExternal = std::max(target - (int64_t)setExternalKeyPool.size(), int64_t{0});
+        missingInternal = std::max(target - (int64_t)setInternalKeyPool.size(), int64_t{0});
```
Comment (PastaPastaPasta) [inline src/wallet/scriptpubkeyman.cpp:1295]:
```suggestion
        missingExternal = std::max(target - int64_t(setExternalKeyPool.size()), int64_t{0});
        missingInternal = std::max(target - int64_t(setInternalKeyPool.size()), int64_t{0});
```

**Comment by achow101** [comment]
Do we want this for 23.0? It fixes a segfault that a number of people have run into.

File: src/wallet/walletdb.cpp [hunk 8]
```diff
@@ -556,9 +556,9 @@ ReadKeyValue(CWallet* pwallet, CDataStream& ssKey, CDataStream& ssValue,
                 }
                 if (internal) {
                     chain.nVersion = CHDChain::VERSION_HD_CHAIN_SPLIT;
-                    chain.nInternalChainCounter = std::max(chain.nInternalChainCounter, index);
```
Comment (instagibbs) [inline src/wallet/walletdb.cpp:559]: seems like a bugfix that we could PR/test separately?

File: test/functional/wallet_inactive_hdchains.py [hunk 9]
```diff
@@ -0,0 +1,193 @@
...
+
+        # Setup both wallets with the same HD seed
+        seed = get_generate_key()
+        base_wallet.sethdseed(True, seed.privkey)
+        test_wallet.sethdseed(True, seed.privkey)
+
+        # Generate a new HD seed on the test wallet
+        test_wallet.sethdseed()
+
+        # Get the address at index 6
```
Comment (instagibbs) [inline test/functional/wallet_inactive_hdchains.py:54]: where are these magic numbers coming from?

File: test/functional/wallet_inactive_hdchains.py [hunk 10]
```diff
@@ -0,0 +1,193 @@
...
+        test_wallet.gettransaction(txid)
+
+        # The test wallet will not be able to generate the topped up keypool
+        # until it is unlocked. So it still should not know about the second address
+        assert not test_wallet.getaddressinfo(addr2)["ismine"]
+        test_wallet.walletpassphrase("pass", 1)
+
+        # The test wallet should now know about the second address as it
+        # should have generated it in the inactive chain's keypool
+        assert test_wallet.getaddressinfo(addr2)["ismine"]
```
Comment (instagibbs) [inline test/functional/wallet_inactive_hdchains.py:119]: seems kind of racey, do a while not true loop?

File: test/functional/wallet_inactive_hdchains.py [hunk 11]
```diff
@@ -0,0 +1,193 @@
...
+
+    def test_without_upgraded_keymeta(self):
+        # Test that it is possible to top up inactive hd chains even if there is no key origin
+        # in CKeyMetadata. This tests for the segfault reported in
+        # https://github.com/bitcoin/bitcoin/issues/21605
+        self.log.info("Test that topping up inactive HD chains does not need upgraded key origin")
+        default = self.nodes[0].get_wallet_rpc(self.default_wallet_name)
+
+        self.nodes[0].createwallet(wallet_name="keymeta_base", descriptors=False, blank=True)
+        self.nodes[1].createwallet_passthrough(wallet_name="keymeta_test")
```
Comment (instagibbs) [inline test/functional/wallet_inactive_hdchains.py:134]: I assume this is important, probably needs a comment on what this is doing because I don't understand it

File: test/functional/wallet_inactive_hdchains.py (hunk 9 above)
Comment (achow101) [reply test/functional/wallet_inactive_hdchains.py]: Not entirely sure, but probably something to do with the keypool defaults. However these don't make sense with the keypool options we are using in the test, so I've changed this to match those.

File: test/functional/wallet_inactive_hdchains.py (hunk 10 above)
Comment (achow101) [reply test/functional/wallet_inactive_hdchains.py:89]: Done, but with `gettransaction`.

File: test/functional/wallet_inactive_hdchains.py (hunk 11 above)
Comment (achow101) [reply test/functional/wallet_inactive_hdchains.py:115]: Added a comment.

It's because we override createwallet in the test framework so that passing `--descriptors` will autofill the descriptor parameter. But that doesn't work for old nodes, so we need a passthrough function.

**Comment by laanwj** [comment]
> Do we want this for 23.0? 

Yes, definitely.

**Comment by fanquake** [comment]
@GITErnesO @IvRRimum are you able to test this change?

**Comment by GITErnesO** [comment]
> @GITErnesO @IvRRimum are you able to test this change?

I have 7 empty wallets that throw this error.
I'm still trying to build from sources.

I gave one of the wallets that throw this error to achow101 so my guess is that he checked that now it works OK.
And my guess is that it is the same issue for the other wallets.

If I can get and RC or an internal version I will check all the 7 wallets.
I'll also continue to build from sources, so I can compile a version with this pull and test the wallets.
