### PR TITLE
util: Remove brittle and confusing sp::Popen(std::string)

### LINKED ISSUE #32574: `system_tests/run_command` test fails on illumos OS
On OpenIndiana:
```
./test/system_tests.cpp(54): error: in "system_tests/run_command": check what.find(tfm::format("RunCommandParseJSON error: process(%s) returned", command)) != std::string::npos has failed
./test/system_tests.cpp(55): error: in "system_tests/run_command": check what.find(expected) != std::string::npos has failed
```

Same on [OmniOS](https://github.com/hebasto/bitcoin-core-nightly/actions/runs/15121791773/job/42505618501):
```
./test/system_tests.cpp(54): error: in "system_tests/run_command": check what.find(tfm::format("RunCommandParseJSON error: process(%s) returned", command)) != std::string::npos has failed
./test/system_tests.cpp(55): error: in "system_tests/run_command": check what.find(expected) != std::string::npos has failed
```

### PR DESCRIPTION
**Pull request by maflcko**
The subprocess Popen call that accepts a full `std::string` has many issues:

* It promotes brittle and broken code, where spaces are not properly quoted. Example: https://github.com/bitcoin/bitcoin/pull/33929#discussion_r2590523065
* The internally used `util::split` function does incorrectly split on spaces, instead of using `shlex.split`.
* It is redundant and not needed, because a vector interface already exists.

Fix all issues by removing it and just using the vector interface.

This pull request should not change any behavior: Note that the command taken from `gArgs.GetArg("-signer", "")` is still passed through the `sp::util::split` helper, just like before. Fixing that is left for a follow-up, so that this change here is basically just a refactor.

This also fixes a unit test bug as a side-effect: Fixes https://github.com/bitcoin/bitcoin/issues/32574.

### CODE REVIEW

**Comment by maflcko** [comment]
Hmm. Looks like all tests passed, except the Windows system unit tests using `echo`. No idea why that could be. I guess Unlike Bash, the Windows cmd internal echo command does not strip quotes from its arguments, It prints them literally?

Let me just pass them as a single string in the Windows tests. This  seems more correct anyway.

**Comment by sedited** [comment]
Concept ACK

**Comment by maflcko** [comment]
Actually, I don't think my attempt works, because cmd.exe + echo will double quote here, which is not valid json. I guess I don't really have a choice than to preserve the exact test case here and manually rip the command into meaningless space-separated tokens, like it is done on current master.

Will push that and add a comment in the unit test.

**Comment by maflcko** [comment]
Looks like i accidentally fixed a bug. To confirm the broken output on current master, the following diff can be used:

```diff
diff --git a/src/test/system_tests.cpp b/src/test/system_tests.cpp
index 0b7cc5b21f..e51b2040cf 100644
--- a/src/test/system_tests.cpp
+++ b/src/test/system_tests.cpp
@@ -67,6 +67,7 @@ BOOST_AUTO_TEST_CASE(run_command)
         const std::string expected{"err"};
         BOOST_CHECK_EXCEPTION(RunCommandParseJSON(command), std::runtime_error, [&](const std::runtime_error& e) {
             const std::string what(e.what());
+            std::cout << what << std::endl;
             BOOST_CHECK(what.find(strprintf("RunCommandParseJSON error: process(%s) returned", command)) != std::string::npos);
             BOOST_CHECK(what.find(expected) != std::string::npos);
             return true;
```

It will print:

```
$ ./bld-cmake/bin/test_bitcoin -t system_tests
Running 1 test case...
RunCommandParseJSON error: process(sh -c 'echo err 1>&2 && false') returned 2: err: -c: line 1: unexpected EOF while looking for matching `''


*** No errors detected

**Comment by maflcko** [comment]
i dropped the trailing newline from the checked string in the last commit. I guess on Windows it is not called `\n`. CI is green now.

**Review by hebasto — COMMENTED** [review]
Concept ACK.

The `Popen` constructor that accepts `std::vector<std::string>` was used in @theStack's initial [approach](https://github.com/bitcoin/bitcoin/issues/24907#issuecomment-1466087049). Then it was [changed](https://github.com/bitcoin/bitcoin/pull/28981#issuecomment-1837238921).

It's nice to see it working now.

**Comment by maflcko** [comment]
> It's nice to see it working now.

Heh, this should be seen more like a refactor and I don't think this pull request changes any external visible behavior. The unit test bugfix is just an accidental side-effect. If you had quoting issues, i think it would be good to know them, so that a future bugfix that fixes `sp::util::split` (which is still used here) can be better  tested.

**Comment by maflcko** [comment]
I guess that means porting shlex.split  to C++, or something. But this can be done later. I think it is fine to just improve the unit tests for now.

**Comment by hebasto** [comment]
> > It's nice to see it working now.
> 
> Heh, this should be seen more like a refactor and I don't think this pull request changes any external visible behavior. The unit test bugfix is just an accidental side-effect. If you had quoting issues, i think it would be good to know them, so that a future bugfix that fixes `sp::util::split` (which is still used here) can be better tested.

It seems you have just hacked the quoting issue around and documented it:https://github.com/bitcoin/bitcoin/blob/fac2b1eea6db57d6f0b3671ae1fdb7912253538b/src/test/system_tests.cpp#L31 :)

**Comment by maflcko** [comment]
Yeah, but I don't think this has anything to do with subprocess. I am happy to push another version there, if someone finds one that works. But I don't have Windows to test this locally. Also, I don't think it is worth it to spend more time with the absurd cmd.exe+echo behavior on Windows,, because https://github.com/bitcoin/bitcoin/pull/33929 will remove that line of code anyway.

> cmd.exe generally having the most absurd behavior.

Source: https://web.archive.org/web/20250323114027/secure.phabricator.com/T13209

**Review by hebasto — COMMENTED** [review]
Tested fac2b1eea6db57d6f0b3671ae1fdb7912253538b on OpenIndiana:
```
$ uname -a
SunOS openindiana 5.11 illumos-2671fc51ca i86pc i386 i86pc
```

**Review by hebasto — COMMENTED** [review]
Approach ACK fac2b1eea6db57d6f0b3671ae1fdb7912253538b.

This resolves https://github.com/bitcoin/bitcoin/pull/33929#discussion_r2590523065.

Going to run more tests before final ACK.

**Comment by hebasto** [comment]
cc @Sjors @theStack

**Comment by luke-jr** [comment]
There is a fundamental design difference between *nix and Windows in this regard. While *nix passes an array of individual arguments, Windows just passes a complete argument string, and it is merely convention how the called program splits/handles that string. The standard `echo` on Windows indeed does not handle it like you would expect coming from *nix.

**Comment by maflcko** [comment]
Joining the args for Windows is responsibility of the subprocess library. This is currently  (in this pull and on master) done in `quote_argument`.

I don't see another approach here, other than to ifdef WINDOWS every subprocess args related code at every single call site with separate handling for Windows and non-Windows. So removing `sp::Popen(std::string)` is the correct approach in my eyes.

**Comment by theStack** [comment]
Concept ACK

**Review by hebasto — APPROVED** [review]
ACK fac2b1eea6db57d6f0b3671ae1fdb7912253538b, I have reviewed the code and it looks OK.

File: src/util/subprocess.h
Comment (janb84) [inline src/util/subprocess.h:1]: Nit, I think that lines 1016-1017 also can be removed now ? 

```C
  // Command in string format
  std::string args_;
```

**Review by janb84 — COMMENTED** [review]
Concept ACK fac2b1eea6db57d6f0b3671ae1fdb7912253538b

Did a code review, left one NIT.

Not sure what's the current policy is on IWYU but there are some suggestions on changed files: run_command.cpp, external_signer.cpp, external_signer.h  (system_tests.cpp mostly false positives on boost)

**Comment by maflcko** [comment]
> Not sure what's the current policy is on IWYU but there are some suggestions on changed files: run_command.cpp, external_signer.cpp, external_signer.h (system_tests.cpp mostly false positives on boost)

I think for they will be fixed+enforced by CI step-by-step for now. Once they are cleanly enforced globally, they'll be changed as part of the pull request.

File: src/util/subprocess.h
Comment (maflcko) [reply src/util/subprocess.h:1]: thx, done. Also, this is unrelated to the changes here, so I've submitted the same patch upstream.

**Review by janb84 — COMMENTED** [review]
cr ACK fa48d421636c256069010bc03c121c36ed9c0a0c

code review, looks good.

In addition, I have run a windows MSVC build & test, both ran without issues:
<details>

```powershell
141/152 Test #122: txvalidationcache_tests ..............   Passed   10.55 sec
142/152 Test #151: walletdb_tests .......................   Passed    0.26 sec
143/152 Test #147: wallet_crypto_tests ..................   Passed    1.16 sec
144/152 Test #152: walletload_tests .....................   Passed    0.42 sec
145/152 Test #146: spend_tests ..........................   Passed    6.60 sec
146/152 Test #118: txpackage_tests ......................   Passed   25.61 sec
147/152 Test   #3: secp256k1_noverify_tests .............   Passed   53.55 sec
148/152 Test #130: validation_block_tests ...............   Passed   28.59 sec
149/152 Test #149: wallet_tests .........................   Passed   24.26 sec
150/152 Test #138: coinselector_tests ...................   Passed   27.87 sec
151/152 Test #132: validation_chainstatemanager_tests ...   Passed   33.11 sec
152/152 Test   #4: secp256k1_tests ......................   Passed   83.98 sec

100% tests passed, 0 tests failed out of 152

Total Test time (real) =  84.63 sec

The following tests did not run:
         90 - script_assets_tests (Skipped)
PS C:\Users\user\source\repos\bitcoin>
```

</details>

File: src/test/system_tests.cpp [hunk 1]
```diff
@@ -69,7 +69,7 @@ BOOST_AUTO_TEST_CASE(run_command)
         const std::string expected{"err"};
         BOOST_CHECK_EXCEPTION(RunCommandParseJSON(command), std::runtime_error, [&](const std::runtime_error& e) {
             const std::string what(e.what());
-            BOOST_CHECK(what.find(strprintf("RunCommandParseJSON error: process(%s) returned", util::Join(command, " "))) != std::string::npos);
+            BOOST_CHECK(what.find(strprintf("RunCommandParseJSON error: process(%s) returned %s: %s", util::Join(command, " "), 1, "err")) != std::string::npos);
```
Comment (fjahr) [inline src/test/system_tests.cpp:72]: nit

```suggestion
            BOOST_CHECK(what.find(strprintf("RunCommandParseJSON error: process(%s) returned %d: %s", util::Join(command, " "), 1, "err")) != std::string::npos);
```

**Review by fjahr — COMMENTED** [review]
Code review ACK fa48d421636c256069010bc03c121c36ed9c0a0c

Change looks like a good improvement.

File: src/test/system_tests.cpp (hunk 1 above)
Comment (maflcko) [reply src/test/system_tests.cpp:72]: I prefer %s in tinyformat, and this will fix itself anyway with std::format in  a year or two

**Comment by avva7788** [comment]
Отправлено из мобильной Почты Mail


вторник, 17 февраля 2026 г. в 21:47 +04:00 от ***@***.***  ***@***.***>:

**Review by hebasto — APPROVED** [review]
re-ACK fa48d421636c256069010bc03c121c36ed9c0a0c.

**Comment by fanquake** [comment]
Possible this also fixed #31506.

**Comment by fanquake** [comment]
> and this will fix itself anyway with std::format in a year or two

@maflcko can you open an issue to track this / the current `std::format` blockers?

**Comment by maflcko** [comment]
> > and this will fix itself anyway with std::format in a year or two
> 
> @maflcko can you open an issue to track this / the current `std::format` blockers?

Sure, done in https://github.com/bitcoin/bitcoin/issues/34979
