### PR TITLE
Always flush block and undo when switching to new file

### LINKED ISSUE #6923: UndoReadFromDisk: Checksum mismatch
As part of serious hammering as part of #6917 testing I think I found a new crash corruption issue (possibly a rare one).

The leveldb database was still OK, however the start-up check fails in a new place: in the undo data check:
https://github.com/bitcoin/bitcoin/blob/master/src/main.cpp#L1494

Haven't analysed the details but will keep the data around.

### PR DESCRIPTION
**Pull request by sipa**
Previously, the undo files weren't being flushed during a reindex because fKnown was set to true in FindBlockPos. That is the correct behaviour for block files as they aren't being touched, but undo files are
touched.

This changes the behaviour to always flush when switching to a new file (even for block files, though that isn't really necessary).

Intended to fix #6923.

### CODE REVIEW

**Comment by sipa** [comment]
@jonasschnelli @laanwj You may want to test this.

**Comment by laanwj** [comment]
I expect that this fixes the issue. #6923 seemed to be a case of a truncated undo file (there was a strangely-sized old undo file and a very small new one). Although I don't fully remember if it happened during `-reindex`. May well be the case.

Will test.

File: src/main.cpp [hunk 1]
```diff
@@ -2528,7 +2526,14 @@ bool FindBlockPos(CValidationState &state, CDiskBlockPos &pos, unsigned int nAdd
         pos.nPos = vinfoBlockFile[nFile].nSize;
     }
 
-    nLastBlockFile = nFile;
+    if (nFile != nLastBlockFile) {
+        if (!fKnown) {
+            LogPrintf("Leaving block file %i: %s\n", nFile, vinfoBlockFile[nFile].ToString());
+        }
+        FlushBlockFile(!fKnown);
```
Comment (morcos) [inline src/main.cpp]: So on a reindex this means undo files still won't be truncated I suppose?

**Comment by morcos** [comment]
utACK

Would an alternative option be to at the end of the reindex loop, go through and flush all the undo files.  It seems if you crash during a reindex, you don't care about the state of the undo files, its only if you were to crash after reindex before they were flushed that you would have a problem?

Such alternative option would potentially have problems in the event of new blocks being written during reindex, but thats already a problem, see #6691.

**Comment by jgarzik** [comment]
tested ACK

**Comment by jonasschnelli** [comment]
Tested ACK.

**Comment by laanwj** [comment]
> It seems if you crash during a reindex, you don't care about the state of the undo file

I don't understand your reasoning here. The point of this PR is to avoid corruption in the undo files when there is a crash during reindex. It can then pick up where it left off next time the application is launched.

**Comment by paveljanik** [comment]
This change brought a new compiler warning:
```
main.cpp:2554:15: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
    if (nFile != nLastBlockFile) {
        ~~~~~ ^  ~~~~~~~~~~~~~~
1 warning generated.
```
