### PR TITLE
clang-tidy: Fix `modernize-use-default-member-init` in headers and force to check all headers

### LINKED ISSUE #26703: ci: clang-tidy does not check header files?
Inside the CI env `FILE_ENV="./ci/test/00_setup_env_native_tidy.sh"` clang-tidy only checks our cpp files and not our header files?

Currently it passes on master, however if manually invoked on a header file, it will fail:

```
# clang-tidy-15 -p=/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu -quiet /bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.cpp && echo $?
543 warnings generated.
1086 warnings generated.
0

# clang-tidy-15 -p=/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu -quiet /bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h && echo $?
408 warnings generated.
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:192:19: error: std::move of the const variable 'name' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
        : m_names{std::move(name)},
                  ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:193:18: error: std::move of the const variable 'type' of the trivially-copyable type 'const RPCArg::Type' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
          m_type{std::move(type)},
                 ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:194:22: error: std::move of the const variable 'fallback' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_fallback{std::move(fallback)},
                     ^~~~~~~~~~        ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:195:25: error: std::move of the const variable 'description' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_description{std::move(description)},
                        ^~~~~~~~~~           ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:208:19: error: std::move of the const variable 'name' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
        : m_names{std::move(name)},
                  ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:209:18: error: std::move of the const variable 'type' of the trivially-copyable type 'const RPCArg::Type' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
          m_type{std::move(type)},
                 ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:210:19: error: std::move of the const variable 'inner' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_inner{std::move(inner)},
                  ^~~~~~~~~~     ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:211:22: error: std::move of the const variable 'fallback' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_fallback{std::move(fallback)},
                     ^~~~~~~~~~        ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:212:25: error: std::move of the const variable 'description' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_description{std::move(description)},
                        ^~~~~~~~~~           ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:275:18: error: std::move of the const variable 'type' of the trivially-copyable type 'const RPCResult::Type' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
        : m_type{std::move(type)},
                 ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:276:22: error: std::move of the const variable 'm_key_name' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_key_name{std::move(m_key_name)},
                     ^~~~~~~~~~          ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:277:19: error: std::move of the const variable 'inner' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_inner{std::move(inner)},
                  ^~~~~~~~~~     ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:280:25: error: std::move of the const variable 'description' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_description{std::move(description)},
                        ^~~~~~~~~~           ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:281:18: error: std::move of the const variable 'cond' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_cond{std::move(cond)}
                 ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:302:18: error: std::move of the const variable 'type' of the trivially-copyable type 'const RPCResult::Type' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
        : m_type{std::move(type)},
                 ^~~~~~~~~~    ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:303:22: error: std::move of the const variable 'm_key_name' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_key_name{std::move(m_key_name)},
                     ^~~~~~~~~~          ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:304:19: error: std::move of the const variable 'inner' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_inner{std::move(inner)},
                  ^~~~~~~~~~     ~
/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/rpc/util.h:307:25: error: std::move of the const variable 'description' has no effect; remove std::move() or make the variable non-const [performance-move-const-arg,-warnings-as-errors]
          m_description{std::move(description)},
                        ^~~~~~~~~~           ~

### PR DESCRIPTION
**Pull request by hebasto**
This PR:
- fixes the only [remained](https://github.com/bitcoin/bitcoin/pull/26705#issuecomment-1353742082) check in headers, i.e., `modernize-use-default-member-init`
- forces `clang-tidy` check all headers

Closes bitcoin/bitcoin#26703.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
concept ack, but it might be good to create one pull/commit for each bugfix. For example, it might be easier to review if there was a separate pull/commit to fix broken `std::move`.

**Comment by aureleoules** [comment]
Could this be done with a scripted-diff script using the clang-tidy -fix-errors command?

**Comment by RandyMcMillan** [comment]
Concept ACK

I agree with @MarcoFalke

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/26705/commits/fac1a47c203bb1351b344038443d72b8de4f14e2

**Comment by hebasto** [comment]
> concept ack, but it might be good to create one pull/commit for each bugfix.

Please review:
- [ ] https://github.com/bitcoin/bitcoin/pull/26707
- [ ] https://github.com/bitcoin/bitcoin/pull/26708
- [ ] https://github.com/bitcoin-core/gui/pull/685

Drafting this PR for now.

**Comment by hebasto** [comment]
> it might be good to create one pull/commit for each bugfix.

The next one is https://github.com/bitcoin/bitcoin/pull/26710 :)

**Comment by hebasto** [comment]
Please review #26707 first.

**Comment by hebasto** [comment]
Rebased and ready for reviewing.

File: src/node/utxo_snapshot.h [hunk 1]
```diff
@@ -13,7 +13,7 @@
 
 #include <optional>
 
-extern RecursiveMutex cs_main;
+extern RecursiveMutex cs_main; // NOLINT(readability-redundant-declaration)
```
Comment (MarcoFalke) [inline src/node/utxo_snapshot.h:16]: https://github.com/bitcoin/bitcoin/pull/26965

**Comment by hebasto** [comment]
> So this is only fixing `modernize-use-default-member-init`, and no other remaining checks?
> 
> Edit: Modulo [#26705 (comment)](https://github.com/bitcoin/bitcoin/pull/26705#discussion_r1086340098)

That's true.

File: src/node/utxo_snapshot.h (hunk 1 above)
Comment (hebasto) [reply src/node/utxo_snapshot.h:16]: > #26965

Yeah, it would be nice if #26965 go first.

**Comment by hebasto** [comment]
Rebased. The PR description has been updated.

**Review by maflcko — APPROVED** [review]
review ACK b0e916913cedb8154419ec818bb9094a72fc8379 🍹

<details><summary>Show signature</summary>

Signature:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

review ACK b0e916913cedb8154419ec818bb9094a72fc8379 🍹
-----BEGIN PGP SIGNATURE-----

iQGzBAEBCgAdFiEE+rVPoUahrI9sLGYTzit1aX5ppUgFAlwqrYAACgkQzit1aX5p
pUgbsgwAulUHjNHcytUabJBoaqpKSZ+tuqsd7gFyApI1CC7025pswCu+Ph1iCICt
rpOLfGLvKaWkDF54XUANxTSmk4xP9hnfYdRgllcVi7zbRg1I3Tnr3J5zt2L1PYQH
AcZ+p1fIZautxpg1440WHwlbJL3F8e84rQ2WPRJlpFt5gN9LuKKMVVvZpALna669
kMVk2G9995kbpzDzQWPXYl0LC5aDwdeOIui+DUcHKzIYywTpMAHCMk1F4hUF1J6Q
JdJ/X2pjNpxgRhCL2rdzZ47pZMUWfEMLMs0BslbCmg/6OdKa1NrtHCQZ1FOy+T3v
/Y9D+Z1L7Ku9tzQPzADOy8oL410DZtrchANrlUVBoLBz34uWMHgp/jNqvqvy1jzh
2+4bNe+K8srE1E3y5mUvY68ddB6+4rE05mmKyBd9Rycg5XNsKVAsoZasbD0jBX9C
adldbvwYXjOlIxXlllGGDrOB5m7kqHmWTaCN+SzjRyR/1Gy+a6epas/WHkiYHyuC
HkGz+8hB
=QqPj
-----END PGP SIGNATURE-----
```


</details>

File: src/span.h [hunk 2]
```diff
@@ -107,7 +107,7 @@ class Span
 
 
 public:
-    constexpr Span() noexcept : m_data(nullptr), m_size(0) {}
+    constexpr Span() noexcept : m_data(nullptr) {}
```
Comment (MarcoFalke) [inline src/span.h:110]: Any reason why nullptr isn't fixed as well?

Comment (hebasto) [reply src/span.h:110]: Yeah, it has been overlooked. The `clang-tidy` does not complain, though.

Comment (MarcoFalke) [reply src/span.h:110]: I guess it refrains because there are multiple constructors: https://github.com/llvm/llvm-project/blob/78f88082de3627ea04501c83a08f52cf1e60b4f7/clang-tools-extra/test/clang-tidy/checkers/modernize/use-default-member-init.cpp#L56
