### PR TITLE
Separate core memory usage computation in core_memusage.h

### LINKED ISSUE #6441: Compile error on OSX
The symptom:
```
In file included from primitives/transaction.cpp:6:
In file included from ./primitives/transaction.h:10:
./memusage.h:14:10: fatal error: 'boost/foreach.hpp' file not found
#include <boost/foreach.hpp>
         ^
1 error generated.
```

Cause is transaction.h including memusage.h, which includes boost headers... but libbitcoinconsensus is supposed to be boost-free.

@sipa will be working on a fix.

@theuni : it'd be nice if one of the Travis builds had a pristine build environment for libbitcoinconsensus to make sure no extra dependencies crept in.

### PR DESCRIPTION
**Pull request by sipa**
Remove support for computing recursive memory usage from memusage.h, making it more easy to plug in other functions.

Furthermore, move the computation of memory usage of core data structures from primitives/*, to reduce its dependencies, specifically on boost.

Should fix #6441.

### CODE REVIEW

File: src/core_memusage.h [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        mem += RecursiveDynamicUsage(*it);
+    }
+    return mem;
+}
+
+static inline size_t RecursiveDynamicUsage(const CBlockLocator& locator) {
+    return memusage::DynamicUsage(locator.vHave);
+}
+
+#endif // BITCOIN_PRIMITIVES_TRANSACTION_H
```
Comment (Diapolo) [inline src/core_memusage.h]: Nit: Wrong end comment :).

**Comment by laanwj** [comment]
utACK, looks like the good solution to me

File: src/core_memusage.h (hunk 1 above)
Comment (sipa) [inline src/core_memusage.h]: Thanks, fixed!
