### PR TITLE
Add test util to populate mempool with random transactions, fix #24634 bug

### LINKED ISSUE #24634: bench: `MempoolCheck` actually runs with `check_ratio = 0`
For `MempoolCheck`, it seems that the intention was to have a mempool with `check_ratio = 1` (see `-checkmempool=1`):

https://github.com/bitcoin/bitcoin/blob/e66630cc87c017f40ec29f6c1edf2ed5a286e49d/src/bench/mempool_stress.cpp#L102-L116

However in the subsequent line in the above snippet, a `CTxMemPool` gets constructed with no arguments, which means that `check_ratio` will default to 0:

https://github.com/bitcoin/bitcoin/blob/e66630cc87c017f40ec29f6c1edf2ed5a286e49d/src/txmempool.h#L571

Manually specifying `check_ratio` to 1 (according to the original intention) and running the `MempoolCheck` benchmark results in an assertion error:

```
diff --git a/src/bench/mempool_stress.cpp b/src/bench/mempool_stress.cpp
index afa4618e1b..32cdb70539 100644
--- a/src/bench/mempool_stress.cpp
+++ b/src/bench/mempool_stress.cpp
@@ -105,7 +105,7 @@ static void MempoolCheck(benchmark::Bench& bench)
     const int childTxs = bench.complexityN() > 1 ? static_cast<int>(bench.complexityN()) : 2000;
     const std::vector<CTransactionRef> ordered_coins = CreateOrderedCoins(det_rand, childTxs, /* min_ancestors */ 5);
     const auto testing_setup = MakeNoLogFileContext<const TestingSetup>(CBaseChainParams::MAIN, {"-checkmempool=1"});
-    CTxMemPool pool;
+    CTxMemPool pool{nullptr, 1};
     LOCK2(cs_main, pool.cs);
     const CCoinsViewCache& coins_tip = testing_setup.get()->m_node.chainman->ActiveChainstate().CoinsTip();
     for (auto& tx : ordered_coins) AddTx(tx, pool);
```

```sh
$ ./src/bench/bench_bitcoin -filter='MempoolCheck'
...
bench_bitcoin: txmempool.cpp:759: void CTxMemPool::check(const CCoinsViewCache &, int64_t) const: Assertion `mempoolDuplicate.HaveCoin(txin.prevout)' failed.
```

Aside from this problem, we should also probably just re-use the `CTxMemPool` in `TestingSetup`.

Ping @glozow

### PR DESCRIPTION
**Pull request by glozow**
Fixes #24634 by using the `testing_setup`'s actual mempool rather than a locally-declared mempool for running `check()`.

Also creates a test utility for populating the mempool with a bunch of random transactions. I imagine this could be useful in other places as well; it was necessary here because we needed the mempool to contain transactions *spending coins available in the current chainstate*. The existing `CreateOrderedCoins()` is insufficient because it creates coins out of thin air.

Also implements the separate suggestion to use the `TestingSetup` mempool in `ComplexMemPool` bench.

### CODE REVIEW

**Comment by dongcarl** [comment]
Concept ACK

wondering if we shouldn't copy:

https://github.com/bitcoin/bitcoin/blob/254f3cc3684cdb7468e353596a89e8fe7a302b9b/src/init.cpp#L1274

To `ChainTestingSetup`'s ctor. Right now it wouldn't matter if you did

```cpp
auto testing_setup = MakeNoLogFileContext<TestChain100Setup>(CBaseChainParams::REGTEST, {"-checkmempool=0"});
```

The mempool will still be checked.

**Comment by glozow** [comment]
> wondering if we shouldn't copy...

Agree, added something similar.

**Comment by theStack** [comment]
Concept ACK

**Comment by dongcarl** [comment]
@MarcoFalke @JeremyRubin would you be able to chime in on the correctness of this added function? I'm not too familiar with mempool usage.
https://github.com/bitcoin/bitcoin/blob/e51f412d0a0bb532774fc2a68c596f730878b470/src/test/util/setup_common.cpp#L358-L393

**Comment by MarcoFalke** [comment]
Probably not correct, see CI:

```
SUMMARY: AddressSanitizer: heap-use-after-free (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/bench/bench_bitcoin+0xcd7816) (BuildId: 106aeeccd13eff54c783adff615bd4c5272e8a95) in __asan_memcpy

**Comment by glozow** [comment]
Fixed

File: src/test/util/setup_common.cpp [hunk 1]
```diff
@@ -355,6 +355,43 @@ CMutableTransaction TestChain100Setup::CreateValidMempoolTransaction(CTransactio
     return mempool_txn;
 }
 
+std::vector<CTransactionRef> TestChain100Setup::PopulateMempool(FastRandomContext& det_rand, size_t num_transactions, bool submit)
+{
+    std::vector<CTransactionRef> mempool_transactions;
+    std::deque<std::pair<COutPoint, CAmount>> unspent_prevouts;
+    std::transform(m_coinbase_txns.begin(), m_coinbase_txns.end(), std::back_inserter(unspent_prevouts),
+        [](const auto& tx){ return std::make_pair(COutPoint(tx->GetHash(), 0), 50 * COIN); });
```
Comment (JeremyRubin) [inline src/test/util/setup_common.cpp:363]: This is not "correct" necessarily -- you should inspect the`tx->vout[0].value` and not guess 50 coins.

File: src/test/util/setup_common.cpp [hunk 2]
```diff
@@ -355,6 +355,43 @@ CMutableTransaction TestChain100Setup::CreateValidMempoolTransaction(CTransactio
...
+    CScript witnessScript = CScript() << OP_DROP << OP_TRUE;
+    CScript scriptPubKey = GetScriptForDestination(WitnessV0ScriptHash(witnessScript));
+    while (num_transactions > 0 && !unspent_prevouts.empty()) {
+        CMutableTransaction mtx = CMutableTransaction();
+        const auto& [prevout, amount] = unspent_prevouts.front();
+        mtx.vin.push_back(CTxIn(prevout, CScript()));
```
Comment (JeremyRubin) [inline src/test/util/setup_common.cpp:369]: Should you set the scriptWitness  on vin.back()?

File: src/test/util/setup_common.cpp [hunk 3]
```diff
@@ -355,6 +355,43 @@ CMutableTransaction TestChain100Setup::CreateValidMempoolTransaction(CTransactio
...
+        const size_t num_outputs = det_rand.randrange(24) + 1;
+        // Approximately 1000sat "fee," equal output amounts.
+        const CAmount amount_per_output = (amount - 1000) / num_outputs;
+        for (size_t n{0}; n < num_outputs; ++n) {
+            CScript spk = CScript() << CScriptNum(num_transactions + n);
+            mtx.vout.push_back(CTxOut(amount_per_output, spk));
+        }
+        unspent_prevouts.pop_front();
+        CTransactionRef ptx = MakeTransactionRef(mtx);
+        mempool_transactions.push_back(ptx);
```
Comment (JeremyRubin) [inline src/test/util/setup_common.cpp:381]: would it be better to do a swap with random index after this push_back?

That way you get a bit more of a 'arbitrary' txn graph, v.s. this one which will have a very specific structure.

Comment (glozow) [reply src/test/util/setup_common.cpp:385]: Oh, I think you mean random swap for `unspent_prevouts` after insert? Added that. I think we have a decent amount of randomness in the structure that way.

File: src/test/util/setup_common.cpp (hunk 2 above)
Comment (JeremyRubin) [reply src/test/util/setup_common.cpp]: but you just push back'd vin, so it is initialized and dereferencable...

File: src/test/util/setup_common.cpp (hunk 3 above)
Comment (JeremyRubin) [reply src/test/util/setup_common.cpp:387]: correct. random swap with unspent_prevouts.

**Comment by glozow** [comment]
Addressed @JeremyRubin's comments and made the graph more random. Ran the bench 100 times, doesn't seem like the extra randomness increases the variance of the bench results which is good. Also rebased to resolve CI issue.

**Comment by laanwj** [comment]
Code review ACK d2f8f1b307b056d1a54fb02a99da2cb664570904

> Ran the bench 100 times, doesn't seem like the extra randomness increases the variance of the bench results which is good

It shouldn't, right, because of the deterministic random context it will do the same every run? But good to check, of course.

**Comment by glozow** [comment]
> It shouldn't, right, because of the deterministic random context it will do the same every run? But good to check, of course.

Ah my bad, I didn't realize that! Thanks!
