### PR TITLE
[bugfix] wallet: Fix duplicate fileid detection

### LINKED ISSUE #14304: wallet: copied wallet detection problem
```
src/bitcoind -daemon -regtest
src/bitcoin-cli -regtest stop
cp ~/.bitcoin/wallet/wallet.dat ~/.bitcoin/wallet/wallet2.dat
src/bitcoind -daemon -regtest
src/bitcoin-cli -regtest loadwallet wallet2.dat # The first time it would fail to load wallet
src/bitcoin-cli -regtest loadwallet wallet2.dat # The second time it would succeed to load wallet, but this would cause error because of duplicate fileid
```
It would flush `wallet.dat` and close `Db*` in` mapDb['wallet.dat'].second`, so `mapDb['wallet.dat'].second` would be `nullptr`. Then there is no available `Db*` to detect if the wallet fileid is duplicated.

I'm not sure if the issue is related to #14163, but I found this while debugging it.

https://github.com/bitcoin/bitcoin/blob/920c090f63f4990bf0f3b3d1a6d3d8a8bcd14ba0/src/wallet/db.cpp#L32-L53

### PR DESCRIPTION
**Pull request by ken2812221**
The implementation in current master can not detect if the file ID is duplicate with flushed `BerkeleyEnvironment`. This PR would store the file ID in a global variable `g_fileids` and release it when the `BerkeleyDatabase` close. So it won't have to rely on a `Db*`.

Fix #14304

### CODE REVIEW

File: src/wallet/db.cpp [hunk 1]
```diff
@@ -20,6 +21,12 @@
 #include <boost/thread.hpp>
 
 namespace {
+
+struct BerkeleyFileid {
+    u_int8_t value[DB_FILE_ID_LEN];
+};
+std::unordered_map<std::string, BerkeleyFileid> g_fileids;
```
Comment (ryanofsky) [inline src/wallet/db.cpp]: I think it'd be more correct to add a `std::unordered_map<std::string, BerkeleyFileid> m_fileids` member in `BerkeleyEnvironment` member instead of a `g_fileids` global because there can be duplicate filenames if the files are in different directories.

Also, making this a member would be consistent with existing `mapFileUseCount` `mapDb` members there which are also maps indexed by filename. In the future it could be nice to consolidate the 3 maps.

**Review by ryanofsky — COMMENTED** [review]
Great catch, I was surprised to see this bug. It seems like the problem here is that BerkeleyEnvironment::Flush actually fully unloads databases, so the check for duplicate fileids when opening a new database doesn't work at all after flushing.

I wonder if you could make a python test case out of the steps in #14304.

File: src/wallet/db.cpp (hunk 1 above)
Comment (ken2812221) [reply src/wallet/db.cpp]: Updated

File: src/wallet/db.cpp [hunk 2]
```diff
@@ -29,27 +30,24 @@ namespace {
...
     }
 
-    for (const auto& item : env.mapDb) {
-        u_int8_t item_fileid[DB_FILE_ID_LEN];
-        if (item.second && item.second->get_mpf()->get_fileid(item_fileid) == 0 &&
-            memcmp(fileid, item_fileid, sizeof(fileid)) == 0) {
-            const char* item_filename = nullptr;
-            item.second->get_dbname(&item_filename, nullptr);
+    for (const auto& item : env.m_fileids) {
+        if (item.first != filename && memcmp(fileid.value, item.second.value, sizeof(fileid)) == 0) {
```
Comment (promag) [inline src/wallet/db.cpp]: move `memcmp` to `BerkeleyFileid::operator==`?

File: src/wallet/db.cpp [hunk 3]
```diff
@@ -29,27 +30,24 @@ namespace {
...
             throw std::runtime_error(strprintf("BerkeleyBatch: Can't open database %s (duplicates fileid %s from %s)", filename,
-                HexStr(std::begin(item_fileid), std::end(item_fileid)),
-                item_filename ? item_filename : "(unknown database)"));
+                HexStr(std::begin(item.second.value), std::end(item.second.value)), item.first));
         }
     }
+
+    env.m_fileids.emplace(filename, fileid);
```
Comment (ryanofsky) [inline src/wallet/db.cpp]: Since `CheckUniqueFileid` is called on all `BerkeleyEnvironment` instances, this will incorrectly add the filename to unrelated BerkeleyEnvironment instances that don't actually contain `filename`. I'd suggest dropping this line, adding a `BerkeleyFileid& fileid` output parameter to `CheckUniqueFileid`, and passing in `this->env->m_fileids[strFilename]` where `CheckUniqueFileid` is called in `BerkeleyBatch::BerkeleyBatch`.

File: src/fs.cpp [hunk 4]
```diff
@@ -89,7 +89,7 @@ bool FileLock::TryLock()
         return false;
     }
     _OVERLAPPED overlapped = {0};
-    if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, 0, 0, &overlapped)) {
+    if (!LockFileEx(hFile, LOCKFILE_EXCLUSIVE_LOCK | LOCKFILE_FAIL_IMMEDIATELY, 0, -1, -1, &overlapped)) {
```
Comment (ryanofsky) [inline src/fs.cpp]: In commit "util: Fix broken Windows file lock"

Can you describe how the lock is broken?

Comment (ken2812221) [reply src/fs.cpp]: That was introduced by #13862. I assume that it could work with length 0 if it is a exclusive lock, but it doesn't. I would have to specify -1, -1 to make it work.

The boost implementation:

https://github.com/boostorg/interprocess/blob/8b3621353017aa527a22124655c9458d0b64b358/include/boost/interprocess/detail/os_file_functions.hpp#L230-L243

File: src/wallet/db.cpp [hunk 5]
```diff
@@ -826,6 +826,8 @@ void BerkeleyDatabase::Flush(bool shutdown)
             LOCK(cs_db);
```
Comment (ken2812221) [inline src/wallet/db.cpp]: Note that if two or more BerkeleyDatabase share the same BerkeleyEnvironment, the `env` would be a wild pointer after the first call.

File: src/wallet/db.cpp [hunk 6]
```diff
@@ -503,8 +503,8 @@ BerkeleyBatch::BerkeleyBatch(BerkeleyDatabase& database, const char* pszMode, bo
             // be implemented, so no equality checks are needed at all. (Newer
             // versions of BDB have an set_lk_exclusive method for this
             // purpose, but the older version we use does not.)
-            for (const auto& env : g_dbenvs) {
-                CheckUniqueFileid(env.second, strFilename, *pdb_temp);
+            for (auto& env : g_dbenvs) {
```
Comment (ryanofsky) [inline src/wallet/db.cpp]: I think you could restore `auto& env` to `const auto& env` here.

File: src/wallet/db.cpp [hunk 7]
```diff
@@ -29,25 +30,19 @@ namespace {
...
     }
 
-    for (const auto& item : env.mapDb) {
-        u_int8_t item_fileid[DB_FILE_ID_LEN];
-        if (item.second && item.second->get_mpf()->get_fileid(item_fileid) == 0 &&
-            memcmp(fileid, item_fileid, sizeof(fileid)) == 0) {
-            const char* item_filename = nullptr;
-            item.second->get_dbname(&item_filename, nullptr);
+    for (const auto& item : env.m_fileids) {
+        if (item.first != filename && fileid == item.second) {
```
Comment (ryanofsky) [inline src/wallet/db.cpp]: I think `item.first != filename` condition makes the check too loose again because the same filename can exist in different directories (and we'd expect pretty much all wallet directories to have a `wallet.dat` file).

Perhaps change condition to: `if (item.second == fileid && !(&item.second == &fileid))`

File: src/wallet/db.cpp [hunk 8]
```diff
@@ -56,6 +51,11 @@ CCriticalSection cs_db;
 std::map<std::string, BerkeleyEnvironment> g_dbenvs GUARDED_BY(cs_db); //!< Map from directory name to open db environment.
 } // namespace
 
+bool BerkeleyFileid::operator==(const BerkeleyFileid& b) const
+{
+    return memcmp(this, &b, sizeof(BerkeleyFileid)) == 0;
```
Comment (ryanofsky) [inline src/wallet/db.cpp]: It might be safer if memcmp compared just the value field rather than the whole object, since it seems possible the compiler could pad the objects. Maybe:

```
return memcmp(this->field, b.field, sizeof(this->field)) == 0;
```

File: src/wallet/db.cpp (hunk 5 above)
Comment (ryanofsky) [reply src/wallet/db.cpp]: Good catch. This appears to be a bug introduced in 0b82bac76d0f842bd2294a290388536951fbc576 from #13111 and then tweaked in a769461d5e37ddcb771ae836254fdc69177a28c4 in #12493. It seems not directly related to this issue, so probably best addressed separately.

File: src/wallet/db.cpp (hunk 2 above)
Comment (ken2812221) [reply src/wallet/db.cpp]: done

File: src/wallet/db.cpp (hunk 3 above)
Comment (ken2812221) [reply src/wallet/db.cpp]: done

**Review by ryanofsky — COMMENTED** [review]
utACK cb4af1969c03b56bc18b63286627922db86743d2. Thanks for the fix and all the followup!

File: src/wallet/db.cpp [hunk 9]
```diff
@@ -826,6 +826,8 @@ void BerkeleyDatabase::Flush(bool shutdown)
             LOCK(cs_db);
             g_dbenvs.erase(env->Directory().string());
             env = nullptr;
+        } else {
```
[the remark this answers is not in the document]
Comment (ken2812221) [reply src/wallet/db.cpp]: That would cause an access violation on Windows since it's a wild pointer in the second call. Also, since the env is deleted when `g_dbenvs.erase` called, the map doesn't exist anymore.

**Comment by MarcoFalke** [comment]
Is this for backport?

**Comment by ryanofsky** [comment]
> Is this for backport?

Could be backported, but I think the benefit would be very minimal. I think you have to literally copy a wallet database file and use the `loadwallet` RPC in order to trigger the missing error check that this PR restores.

**Review by ryanofsky — COMMENTED** [review]
utACK f936b8d14bfa8c758984430181db20514d34accd. Only change since previous review is adding code comment.

**Comment by ken2812221** [comment]
Rebased

File: test/functional/wallet_multiwallet.py [hunk 10]
```diff
@@ -69,11 +69,13 @@ def wallet_file(name):
...
         #   ''         - to verify default wallet file is created correctly
         wallet_names = ['w1', 'w2', 'w3', 'w', 'sub/w5', os.path.join(self.options.tmpdir, 'extern/w6'), 'w7_symlink', 'w8', '']
+        wallet_exclude = set()
         if os.name == 'nt':
             wallet_names.remove('w7_symlink')
+            wallet_exclude = {'w7'}
         extra_args = ['-wallet={}'.format(n) for n in wallet_names]
         self.start_node(0, extra_args)
-        assert_equal(set(map(lambda w: w['name'], self.nodes[0].listwalletdir()['wallets'])), set(['', 'w3', 'w2', 'sub/w5', 'w7', 'w7', 'w1', 'w8', 'w']))
+        assert_equal(set(map(lambda w: w['name'], self.nodes[0].listwalletdir()['wallets'])), set(['', 'w3', 'w2', os.path.join('sub', 'w5'), 'w7', 'w7', 'w1', 'w8', 'w']) - wallet_exclude)
```
Comment (ryanofsky) [inline test/functional/wallet_multiwallet.py]: Note: It looks os.path.join change is not directly related to this PR, but is just a fix for listwalletdir (added in #14291) on windows.

Comment (ryanofsky) [inline test/functional/wallet_multiwallet.py]: > 'w7', 'w7'

Code precedes this PR, but I think listing w7 twice has no effect.

**Review by ryanofsky — APPROVED** [review]
utACK 02b6bd343da296dc29ea017447b18c9afa13b5e3. Only changes since last review are rebase and listwalletdir fixes.

File: test/functional/wallet_multiwallet.py (hunk 10 above)
Comment (promag) [reply test/functional/wallet_multiwallet.py]: This is changed in #14531.

**Comment by ken2812221** [comment]
Just split appveyor part to #14559 to make this PR easier to review.

File: src/wallet/db.cpp [hunk 11]
```diff
@@ -826,6 +826,10 @@ void BerkeleyDatabase::Flush(bool shutdown)
...
+            // To avoid accessing a map that has already deconstructed, do not call this when shutdown is true. g_dbenvs.erase would also erase this value.
+            // TODO: get rid of wild pointers
+            env->m_fileids.erase(strFile);
```
Comment (ryanofsky) [inline src/wallet/db.cpp]: It might not be clear what "wild pointers" refers to in this todo (laanwj asked about it here: https://github.com/bitcoin/bitcoin/pull/14531#discussion_r227770685). Wild pointers could mean either dead pointers or raw pointers, but I think the TODO is referring to the bug described here: https://github.com/bitcoin/bitcoin/pull/14320#discussion_r220332273. Maybe could be expanded as:

```c++
// TODO: To avoid g_dbenvs.erase erasing the environment prematurely after the
// first database shutdown when multiple databases are open in the same
// environment, should replace raw database `env` pointers with shared or weak
// pointers, or else separate the database and environment shutdowns so
// environments can be shut down after databases.
```

**Review by ryanofsky — COMMENTED** [review]
utACK ef16fc5da6ca6b33d4a92e509d627d908f8ed995. Only change since last review is dropping appveyor commit and related wallet_multiwallet.py test fixes.

File: src/wallet/db.h [hunk 12]
```diff
@@ -18,13 +18,19 @@
...
 #include <string>
+#include <unordered_map>
 #include <vector>
 
 #include <db_cxx.h>
 
 static const unsigned int DEFAULT_WALLET_DBLOGSIZE = 100;
 static const bool DEFAULT_WALLET_PRIVDB = true;
 
+struct BerkeleyFileid {
```
Comment (promag) [inline src/wallet/db.h]: @laanwj suggested `BerkeleyFileId`. I also suggest `WalletDatabaseFileId` or `DBFileId`.

**Comment by ken2812221** [comment]
ef16fc5 -> 4ea7732
1. Rename BerkeleyFileid -> WalletDatabaseFileId (@promag)
2. Added @ryanofsky's comments

**Review by ryanofsky — APPROVED** [review]
utACK 4ea77320c5f0b275876be41ff530bb328ba0cb87. Only changes are fileid class rename and todo comment.

File: src/wallet/db.cpp (hunk 5 above)
Comment (ryanofsky) [reply src/wallet/db.cpp]: Thread https://github.com/bitcoin/bitcoin/pull/14320#discussion_r220332273

> Good catch indeed. The bug was not introduced in 0b82bac but in a769461?

0b82bac76d0f842bd2294a290388536951fbc576 added the call to erase the environment too early and a769461d5e37ddcb771ae836254fdc69177a28c4 just moved the call, IIUC.

**Comment by promag** [comment]
Tested ACK 4ea7732, new test fails without this fix.

**Comment by laanwj** [comment]
utACK 6241eb3224d95ea04c04dcab2dac88687f49440e
