### PR TITLE
wallet/rpc: fix listdescriptors RPC fails to return descriptors with private key information when wallet contains descriptors missing any key

### LINKED ISSUE #32078: listdescriptors true fails with 'Can't get descriptor string' in non-watch-only descriptor wallet
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

When running the command:
```
bitcoin-cli listdescriptors true
```
it fails with the error:
```
error code: -4
error message:
Can't get descriptor string.
```
even though the wallet is not watch-only and is a descriptor wallet.

However, when running:
```
bitcoin-cli listdescriptors false

```
the command works fine and returns descriptor information, but without private keys.

### Expected behaviour

Since the wallet is not watch-only and is a descriptor wallet, the command should succeed, just like listdescriptors false, but with the private key information included.

### Steps to reproduce

Verify that the wallet is a descriptor wallet:

```
{
  "walletname": "BTC",
  "walletversion": 169900,
  "format": "sqlite",
  "keypoolsize_hd_internal": 4000,
  "private_keys_enabled": true,
  "descriptors": true,
  "external_signer": false,
  "blank": false,
}
```

### Relevant log output

I didn't find any related errors in the debug file, but I listed my descriptor for reference

```
{
  "descriptors": [
    {
      "desc": "pkh([761f1ef4/44h/1h/0h]tpubDDeGeaPE1STPq4dQFhc5grg8pn6pqyttBtX6Pkw8cAVKesnJr7wYFF7LKy2ysifbPSKDyBT3hHjAg9rftJdPVKLUrGgan7pmML9CFeDuua6/0/*)#cnspa9u5"
    },
    {
      "desc": "pkh([761f1ef4/44h/1h/0h]tpubDDeGeaPE1STPq4dQFhc5grg8pn6pqyttBtX6Pkw8cAVKesnJr7wYFF7LKy2ysifbPSKDyBT3hHjAg9rftJdPVKLUrGgan7pmML9CFeDuua6/1/*)#f84qqsvv"
    },
    {
      "desc": "pkh([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/100)#t96q85nr"
    },
    {
      "desc": "sh(wpkh([761f1ef4/49h/1h/0h]tpubDDohgQvP57jvmvVzmKFo1JjZjwWRAaYyL7aPG4ZPiiNjnbSDKBHxgPSBmBx9Esjf4HxxeEeRVdkiGRaJmVRofHBMLtQzHxKmRbAg9oMxEmw/0/*))#h40wmz6r"
    },
    {
      "desc": "sh(wpkh([761f1ef4/49h/1h/0h]tpubDDohgQvP57jvmvVzmKFo1JjZjwWRAaYyL7aPG4ZPiiNjnbSDKBHxgPSBmBx9Esjf4HxxeEeRVdkiGRaJmVRofHBMLtQzHxKmRbAg9oMxEmw/1/*))#z5pcra0u"
    },
    {
      "desc": "sh(wsh(multi(2,[761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/2,[761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/3)))#3455mcsd"
    },
    {
      "desc": "tr([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/*)#rrrwmyl6"
    },
    {
      "desc": "tr([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/1,multi_a(2,[761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/2,[761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/3))#teu9thwc"
    },
    {
      "desc": "tr([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/1,{pk([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/2),pk([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/1)})#597an7jq"
    },
    {
      "desc": "tr([761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/1/*)#jhx0x30z"
    },
    {
      "desc": "tr(ca46e9fad132afe73c7efcc02039225d2f4626cf476f6ca91ab56ad2d1956029,multi_a(2,[761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/2,[761f1ef4/86h/1h/0h]tpubDDRksBabSitMWcvdvWwVzhEvwFC9Bf77ASZRGHtoMhYr6AFDChuQtNxEvWqtjNy5Vqmd7DKwh5b41NM1oT3YfNRWBMrbcw53da4NwmJ12Td/0/3))#guq2rvkj"
    },
    {
      "desc": "wpkh([761f1ef4/84h/1h/0h]tpubDCSU3vbXvSzLszkaX4dBv5bsovXH5JqoR6rpCToEJZJ8kiZb3VZkWpoKnf5Sr5aGjxCqbDhfR6Z8JtT5rT3CLj7aC8NfLUjEtxhZB9PNHxs/0/*)#lf9s05rn"
    },
    {
      "desc": "wpkh([761f1ef4/84h/1h/0h]tpubDCSU3vbXvSzLszkaX4dBv5bsovXH5JqoR6rpCToEJZJ8kiZb3VZkWpoKnf5Sr5aGjxCqbDhfR6Z8JtT5rT3CLj7aC8NfLUjEtxhZB9PNHxs/1/*)#waq3jpnt"
    }
  ]
}

```

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

Bitcoin Core RPC client version v28.1.0

### Operating system and version

Windows 11 Home 26100.3476

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by Eunovo**
_TLDR:
Currently, `listdescriptors [private=true]` will fail for a non-watch-only wallet if any descriptor has a missing private key(e.g `tr()`, `multi()`, etc.). This PR changes that while making sure `listdescriptors [private=true]` still fails if there no private keys. Closes #32078_ 

In non-watch-only wallets, it's possible to import descriptors as long as at least one private key is included. It's important that users can still view these descriptors when they need to create a backup—even if some private keys are missing ([#32078 (comment)](https://github.com/bitcoin/bitcoin/issues/32078#issuecomment-2781428475)). This change makes it possible to do so.

This change also helps prevent `listdescriptors true` from failing completely, because one descriptor is missing some private keys.

### Notes
- The new behaviour is applied to all descriptors including miniscript descriptors
- `listdescriptors true` still fails for watch-only wallets to preserve existing behaviour https://github.com/bitcoin/bitcoin/pull/24361#discussion_r920801352
- Wallet migration logic previously used `Descriptor::ToPrivateString()` to determine which descriptor was watchonly. This means that modifying the `ToPrivateString()` behaviour caused descriptors that were previously recognized as "watchonly" to be "non-watchonly". **In order to keep the scope of this PR limited to the RPC behaviour, this PR uses a different method to determine `watchonly` descriptors for the purpose of wallet migration.** A follow-up PR can be opened to update migration logic to exclude descriptors with some private keys from the `watchonly` migration wallet. 

### Relevant PRs
https://github.com/bitcoin/bitcoin/pull/24361
https://github.com/bitcoin/bitcoin/pull/32186

### Testing
Functional tests were added to test the new behaviour

EDIT
**`listdescriptors [private=true]` will still fail when there are no private keys because non-watchonly wallets must have private keys and calling `listdescriptors [private=true]` for watchonly wallet returns an error**

### CODE REVIEW

**Comment by fanquake** [comment]
```bash
/Users/runner/work/bitcoin/bitcoin/src/test/fuzz/miniscript.cpp:1040:42: error: no matching member function for call to 'ToString'
    std::optional<std::string> str{node->ToString(parser_ctx)};
                                   ~~~~~~^~~~~~~~
/Users/runner/work/bitcoin/bitcoin/src/script/miniscript.h:830:17: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    std::string ToString(const CTx& ctx, bool& has_priv_key) const {
                ^
/Users/runner/work/bitcoin/bitcoin/src/test/fuzz/miniscript.cpp:1248:31: error: no matching member function for call to 'ToString'
    const auto str2 = parsed->ToString(parser_ctx);
                      ~~~~~~~~^~~~~~~~
/Users/runner/work/bitcoin/bitcoin/src/script/miniscript.h:830:17: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    std::string ToString(const CTx& ctx, bool& has_priv_key) const {
                ^
2 errors generated.
```

**Comment by vicjuma** [comment]
This PR improves the usability of the `listdescriptors true` RPC, especially for descriptor-based (modern) wallets where some private keys may be missing.

However, it's unclear why someone would create a watch-only wallet and still choose to set `private=true`. Why not just use the default command, `bitcoin-cli listdescriptors` instead of `bitcoin-cli -named listdescriptors private=true`. The former already shows public keys? Unless the user is not certain about the nature of the descriptors they imported. I have used named arguments so that you can get the nature of the command `bitcoin-cli listdescriptors true`

**Comment by achow101** [comment]
Concept NACK

The purpose of the `private` argument is to show the private keys. If there are no private keys to show, I think it is a reasonable error to say that, rather than just showing the public descriptors. I think changing the behavior could result in a footgun where people use it thinking that they are being shown private keys when they actually are not.

**Comment by vicjuma** [comment]
Concept NACK

It's unclear why someone should receive public keys with `private=true`. Why not just use the default command, `bitcoin-cli listdescriptors`, which already shows public keys? I assume the user is certain about the nature of the descriptors they have in their wallet. Maybe if I do not fully understand this PR.

**Comment by rkrux** [comment]
>  If there are no private keys to show, I think it is a reasonable error to say that, rather than just showing the public descriptors.

I have not checked this PR yet but the original intention came from this issue: https://github.com/bitcoin/bitcoin/issues/32078#issuecomment-2781428475

The idea was to show results for descriptors that don't have _all_ the private keys but do have at least one. This is not for the case when the descriptor doesn't have _any_ private key.

I do like how the `importdescriptors` RPC returns a warning when the descriptor contains partial private keys: https://github.com/bitcoin/bitcoin/issues/32078#issuecomment-2783608466. Maybe a similar warning can be returned in this case for `listdescriptors` as well - to avoid the footgun.
```
[
  {
    "success": true,
    "warnings": [
      "Not all private keys provided. Some wallet functionality may return unexpected errors"
    ]
  }
]
```

Regardless of the above point, I do feel that preventing `listdescriptors true` from failing completely in the case a descriptor is missing few private keys is helpful for the user as the other descriptors with all the private keys will be returned in the response.
> This change also helps prevent listdescriptors true from failing completely, because one descriptor is missing some private keys.

**Comment by vicjuma** [comment]
Maybe `-rpcwallet=<wallet>` will come in handy in this situation where you would have to use a different wallet for these situations to prevent the conflicts.

**Comment by achow101** [comment]
> The idea was to show results for descriptors that don't have all the private keys but do have at least one.

I think that's fine to show a result, but I don't think we should show any result if there are no private keys at all.

**Comment by Eunovo** [comment]
> Concept NACK
> 
> The purpose of the `private` argument is to show the private keys. If there are no private keys to show, I think it is a reasonable error to say that, rather than just showing the public descriptors. I think changing the behavior could result in a footgun where people use it thinking that they are being shown private keys when they actually are not.

I think there has been a misunderstanding. **There are private keys to show.** This  PR doesn't change the behaviour of `listdescriptors true` RPC to show any result when there are no private keys. Non-watchonly wallet descriptors must have at least one private key. The RPC still fails for watch only wallets

**Comment by Eunovo** [comment]
> I think that's fine to show a result, but I don't think we should show any result if there are no private keys at all.

No result is shown if there are no private keys

**Comment by rkrux** [comment]
A similar problem happens in `gethdkeys private=true` as well and I think it's due to partial private keys when the following error is thrown:

```
➜  bitcoin git:(list-descriptors-with-partial-keys) ✗ bitcoinclireg -named gethdkeys private=true
error code: -1
error message:
map::at:  key not found
```

It appears to be coming from here when the `xprv` corresponding to the `xpub` can't be found: https://github.com/bitcoin/bitcoin/blob/7763e86afa045910a14ac9b2cd644927a447370b/src/wallet/rpc/wallet.cpp#L822

It's due to mismatch in the count of `wallet_xprvs` and `wallet_xprvs` calculated in the previous loop over `spkms`. 
I can create a separate issue later.

**Comment by rkrux** [comment]
Concept ACK bb14e8ac7d38f3698d76ea3d6dce09e1387d59f3

Started reviewing the PR.

File: src/script/descriptor.h [hunk 1]
```diff
@@ -111,7 +111,12 @@ struct Descriptor {
     /** Whether this descriptor will return one scriptPubKey or multiple (aka is or is not combo) */
     virtual bool IsSingleType() const = 0;
 
-    /** Convert the descriptor to a private string. This fails if the provided provider does not have the relevant private keys. */
+    /** Convert the descriptor to a private string. This uses public keys if the relevant private keys are not in the SigningProvider.
+     *  If none of the relevant private keys are available, the output string in the "out" parameter will not contain any private key information,
+     *  and this function will return "false".
+     *  @param[in] provider The SigningProvider to query for private keys.
+     *  @param[out] out The resulting descriptor string, containing private keys if available.
+     */
```
Comment (rkrux) [inline src/script/descriptor.h:127]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

```diff
+ @return true if at least one private key available
```

File: src/script/descriptor.cpp [hunk 2]
```diff
@@ -686,20 +698,23 @@ class DescriptorImpl : public Descriptor
...
+        bool has_priv_key;
+        ToStringHelper(nullptr, ret, compat_format ? StringType::COMPAT : StringType::PUBLIC, has_priv_key);
         return AddChecksum(ret);
     }
 
     bool ToPrivateString(const SigningProvider& arg, std::string& out) const override
     {
-        bool ret = ToStringHelper(&arg, out, StringType::PRIVATE);
+        bool has_priv_key;
+        assert(ToStringHelper(&arg, out, StringType::PRIVATE, has_priv_key));
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

Fine to add `assert` here because for all intents and purposes I don't suppose there would ever be a case where `ToStringHelper` returns `false` here. Perhaps we can add a helpful assert message here for debugging purposes?

```diff
- assert(ToStringHelper(&arg, out, StringType::PRIVATE, has_priv_key));
+ assert(ToStringHelper(&arg, out, StringType::PRIVATE, has_priv_key), "");
```

File: src/script/miniscript.h [hunk 3]
```diff
@@ -840,10 +841,16 @@ struct Node {
                     (node.fragment == Fragment::OR_I && node.subs[0]->fragment == Fragment::JUST_0) ||
                     (node.fragment == Fragment::OR_I && node.subs[1]->fragment == Fragment::JUST_0));
         };
+        auto toString = [&ctx, &has_priv_key](Key key) -> std::string {
+            bool tmp{false};
+            auto key_str{ctx.ToString(key, tmp)};
+            has_priv_key |= tmp;
```
Comment (rkrux) [inline src/script/miniscript.h]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

Not a bug but `bitwise or` for boolean operations is not ideal.
```diff
- has_priv_key |= tmp;
+ has_priv_key = has_priv_key || tmp;
```

File: test/functional/wallet_listdescriptors.py [hunk 4]
```diff
@@ -126,6 +126,37 @@ def run_test(self):
...
+            'descriptors': [
+                {'active': False,
+                 'desc': tr_desc,
+                 'timestamp': TIME_GENESIS_BLOCK},
+                {'active': False,
+                 'desc': miniscript_desc,
+                 'timestamp': TIME_GENESIS_BLOCK},
+            ],
+        }
+        assert_equal(expected, wallet.listdescriptors(True))
```
Comment (rkrux) [inline test/functional/wallet_listdescriptors.py]: In bb14e8ac7d38f3698d76ea3d6dce09e1387d59f3 "test: Test listdescs with priv works even with missing priv keys"

Nit: I prefer to only check for the data that we really want to assert on, helps in keeping the tests code cleaner as well besides being minutely faster. Checking `desc` for every imported descriptor in this case.

File: src/script/descriptor.cpp [hunk 5]
```diff
@@ -485,7 +488,10 @@ class BIP32PubkeyProvider final : public PubkeyProvider
     bool ToPrivateString(const SigningProvider& arg, std::string& out) const override
     {
         CExtKey key;
-        if (!GetExtKey(arg, key)) return false;
+        if (!GetExtKey(arg, key)) {
+            out = ToString();
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

Nit: To keep it consistent with the other pubkey providers and to make it explicit here. Though a default is specified in `ToString`.
```diff
- out = ToString();
+ out = ToString(StringType::PUBLIC);
```

File: src/script/descriptor.cpp [hunk 6]
```diff
@@ -255,9 +255,9 @@ class OriginPubkeyProvider final : public PubkeyProvider
     bool ToPrivateString(const SigningProvider& arg, std::string& ret) const override
```
Comment (rkrux) [inline src/script/descriptor.cpp:264]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

It would be helpful to update the function doc in `PubkeyProvider` struct to mention the new behaviour.

File: src/script/descriptor.cpp [hunk 7]
```diff
@@ -686,20 +698,23 @@ class DescriptorImpl : public Descriptor
     std::string ToString(bool compat_format) const final
     {
         std::string ret;
-        ToStringHelper(nullptr, ret, compat_format ? StringType::COMPAT : StringType::PUBLIC);
+        bool has_priv_key;
+        ToStringHelper(nullptr, ret, compat_format ? StringType::COMPAT : StringType::PUBLIC, has_priv_key);
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In https://github.com/bitcoin/bitcoin/commit/a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if at least 1 priv key exists"

```diff
- bool has_priv_key;
- ToStringHelper(nullptr, ret, compat_format ? StringType::COMPAT : StringType::PUBLIC, has_priv_key);
+ bool dummy;
+ ToStringHelper(nullptr, ret, compat_format ? StringType::COMPAT : StringType::PUBLIC, dummy);
```

Because there is no use of this variable in `ToString`.
Same for `ToNormalizedString` function down below.

An alternative could be to use a pointer for `has_priv_key` instead of reference because, as noted here, there are use cases for nullptr. The `ToStringHelper` would need to accordingly check for the presence of pointer value though.

File: src/script/miniscript.h [hunk 8]
```diff
@@ -840,10 +841,16 @@ struct Node {
                     (node.fragment == Fragment::OR_I && node.subs[0]->fragment == Fragment::JUST_0) ||
                     (node.fragment == Fragment::OR_I && node.subs[1]->fragment == Fragment::JUST_0));
         };
+        auto toString = [&ctx, &has_priv_key](Key key) -> std::string {
+            bool tmp{false};
+            auto key_str{ctx.ToString(key, tmp)};
```
Comment (rkrux) [inline src/script/miniscript.h]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

```diff
- bool tmp{false};
- auto key_str{ctx.ToString(key, tmp)};
+ bool fragment_has_private_key{false};
+ auto key_str{ctx.ToString(key, fragment_has_private_key)};

File: src/script/descriptor.cpp [hunk 9]
```diff
@@ -1700,8 +1715,9 @@ struct KeyParser {
         return key;
     }
 
-    std::optional<std::string> ToString(const Key& key) const
+    std::string ToString(const Key& key, bool& has_priv_key) const
     {
+        has_priv_key = false;
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

Maybe the pointer approach would avoid forcibly setting variables to false?

File: src/script/descriptor.cpp (hunk 2 above)
Comment (rkrux) [inline src/script/descriptor.cpp]: In a0a458965c944434b1f3e4d83277257793435edb "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

This would also aid readability because under no condition `has_priv_key` can be `false` here.
```cpp
Assume(has_priv_key);
```

**Review by rkrux — COMMENTED** [review]
Partial review bb14e8ac7d38f3698d76ea3d6dce09e1387d59f3

File: src/script/descriptor.h (hunk 1 above)
Comment (Eunovo) [reply src/script/descriptor.h:127]: Done

File: src/script/descriptor.cpp (hunk 2 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I couldn't add an assert message, but I added a comment.

File: src/script/miniscript.h (hunk 3 above)
Comment (Eunovo) [reply src/script/miniscript.h]: Done

File: test/functional/wallet_listdescriptors.py (hunk 4 above)
Comment (Eunovo) [reply test/functional/wallet_listdescriptors.py]: Done

File: src/script/descriptor.cpp (hunk 5 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: Done

File: src/script/descriptor.cpp (hunk 6 above)
Comment (Eunovo) [reply src/script/descriptor.cpp:264]: Done

File: src/script/descriptor.cpp (hunk 7 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: `ToStringHelper` now accepts a pointer to `has_priv_key` in https://github.com/bitcoin/bitcoin/pull/32471/commits/2a1f1f0e32829af43436eb4220164c1be86229bb
It does look cleaner, but there's a need to check for `nullptr` now.

File: src/script/miniscript.h (hunk 8 above)
Comment (Eunovo) [reply src/script/miniscript.h]: Done

File: src/script/descriptor.cpp (hunk 9 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: Done

File: src/script/descriptor.cpp (hunk 2 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I'm confused here. Can you clarify what you're suggesting?

Comment (rkrux) [reply src/script/descriptor.cpp]: I had something like this in mind because in all the descriptors that can be added in a non-watch-only wallet, there must be at least 1 private key that is available. So, it seemed reasonable to me to add an `Assume` here on `has_priv_key` being true. I don't suppose `ToPrivateString` function would be called in any case for a watch-only wallet.
```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index bd85ddd9e2..b22bf3fa4a 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -710,6 +710,7 @@ public:
         // ToStringHelper should never fail for StringType::PRIVATE,
         // because it falls back to StringType::PUBLIC when no private ke
y is available.
         assert(ToStringHelper(&arg, out, StringType::PRIVATE, &has_priv_k
ey));
+        Assume(has_priv_key);
         out = AddChecksum(out);
         return has_priv_key;
     }
```

The `descriptor_tests` unit test did fail for one case when I used an `assert` instead, the functional tests though pass on my system. Maybe I have missed some use case due to which it fails. 
```bash
test/descriptor_tests.cpp:212: info: check parse_priv->ToPrivateString(keys_priv, prv1) has passed
test/descriptor_tests.cpp:216: info: check 'Private ser: combo(L4rK1yDtCWekvXuE6oXD9jCYfFNV2cWRpVuPLBcCU2z8TrisoyY1)#p5326pcv Private desc: combo(L4rK1yDtCWekvXuE6oXD9jCYfFNV2cWRpVuPLBcCU2z8TrisoyY1)' has passed
Assertion failed: (has_priv_key), function ToPrivateString, file descriptor.cpp, line 713.
unknown location:0: fatal error: in "descriptor_tests/descriptor_test": signal: SIGABRT (application abort requested)
test/descriptor_tests.cpp:218: last checkpoint
test/descriptor_tests.cpp:518: Leaving test case "descriptor_test"; testing time: 1795us
```

ISTM that the unit test case is more contrived than the functional tests as the below check fails.
```cpp
BOOST_CHECK(!parse_priv->ToPrivateString(keys_pub, prv1));
```

You can ignore if this doesn't make sense.

Comment (Eunovo) [reply src/script/descriptor.cpp]: `ToPrivateString` will be called on a non-watch-only wallet when the user tries RPC `listdescriptors[private=true]`. In this case, `has_priv_key` will be `false` and the RPC call should fail as expected.

File: src/wallet/scriptpubkeyman.cpp [hunk 10]
```diff
@@ -721,9 +721,27 @@ std::optional<MigrationData> LegacyDataSPKM::MigrateToDescriptor()
...
+            }
+        }
+        for (auto extpubkey : ext_pubkeys) {
+            CKey key;
+            if (GetKey(extpubkey.pubkey.GetID(), key)) {
+                privkey_count += 1;
+            }
+        }
+        size_t pubkey_count{pubkeys.size() + ext_pubkeys.size()};
+        bool watchonly{privkey_count == 0 || pubkey_count > privkey_count};
```
Comment (rkrux) [inline src/wallet/scriptpubkeyman.cpp]: In 2551fdfdd662dfb4077c3059b437acf56bdbaf5b "wallet/migration: use count private key count to identify watchonly descs"

This evaluation of `watchonly` at a barebones level looks great to me! Though maybe we can put this inside a `IsWatchOnly` function in the Descriptor{Impl} class? Reading all these details in the migration flow might be distracting, and moreover this generic function might have its own use cases separate from this later. Following patch builds and tests fine on my system. I have added few minor renaming changes as well. 

<details open>
<summary>Descriptor IsWatchOnly()</summary>

```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index bd85ddd9e2..bf67b8c43e 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -646,6 +646,31 @@ public:
         return false;
     }
 
+    bool IsWatchOnly(const SigningProvider& arg) const override
+    {
+        size_t privkey_count{0};
+        std::set<CPubKey> pubkeys;
+        std::set<CExtPubKey> ext_pubkeys;
+        this->GetPubKeys(pubkeys, ext_pubkeys);
+        auto output_type{this->GetOutputType()};
+        for (auto pubkey : pubkeys) {
+            CKey key;
+            if (arg.GetKey(pubkey.GetID(), key)) {
+                privkey_count += 1;
+            } else if (output_type.has_value() && *output_type == OutputType::BECH32M && arg.GetKeyByXOnly(XOnlyPubKey(pubkey), key)) {
+                privkey_count += 1;
+            }
+        }
+        for (auto extpubkey : ext_pubkeys) {
+            CKey dummy;
+            if (arg.GetKey(extpubkey.pubkey.GetID(), dummy)) {
+                privkey_count += 1;
+            }
+        }
+        size_t pubkey_count{pubkeys.size() + ext_pubkeys.size()};
+        return (privkey_count == 0 || pubkey_count > privkey_count);
+    }
+
     // NOLINTNEXTLINE(misc-no-recursion)
     virtual bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, bool* has_priv_key, const DescriptorCache* cache = nullptr) const
     {
diff --git a/src/script/descriptor.h b/src/script/descriptor.h
index 09e9840645..f2e40b7f7a 100644
--- a/src/script/descriptor.h
+++ b/src/script/descriptor.h
@@ -111,6 +111,9 @@ struct Descriptor {
     /** Whether this descriptor will return one scriptPubKey or multiple (aka is or is not combo) */
     virtual bool IsSingleType() const = 0;
 
+    /** Whether this descriptor doesn't contain any private key material */
+    virtual bool IsWatchOnly(const SigningProvider& provider) const = 0;
+
     /** Convert the descriptor to a private string. This uses public keys if the relevant private keys are not in the SigningProvider.
      *  If none of the relevant private keys are available, the output string in the "out" parameter will not contain any private key information,
      *  and this function will return "false".
diff --git a/src/wallet/scriptpubkeyman.cpp b/src/wallet/scriptpubkeyman.cpp
index 117fdd3a5e..e403bf3bbe 100644
--- a/src/wallet/scriptpubkeyman.cpp
+++ b/src/wallet/scriptpubkeyman.cpp
@@ -721,27 +721,7 @@ std::optional<MigrationData> LegacyDataSPKM::MigrateToDescriptor()
 
         std::vector<CScript> desc_spks;
 
-        size_t privkey_count{0};
-        std::set<CPubKey> pubkeys;
-        std::set<CExtPubKey> ext_pubkeys;
-        desc->GetPubKeys(pubkeys, ext_pubkeys);
-        auto output_type{desc->GetOutputType()};
-        for (auto pubkey : pubkeys) {
-            CKey key;
-            if (GetKey(pubkey.GetID(), key)) {
-                privkey_count += 1;
-            } else if (output_type.has_value() && *output_type == OutputType::BECH32M && GetKeyByXOnly(XOnlyPubKey(pubkey), key)) {
-                privkey_count += 1;
-            }
-        }
-        for (auto extpubkey : ext_pubkeys) {
-            CKey key;
-            if (GetKey(extpubkey.pubkey.GetID(), key)) {
-                privkey_count += 1;
-            }
-        }
-        size_t pubkey_count{pubkeys.size() + ext_pubkeys.size()};
-        bool watchonly{privkey_count == 0 || pubkey_count > privkey_count};
+        bool watchonly = desc->IsWatchOnly(*this);
         if (watchonly && !m_storage.IsWalletFlagSet(WALLET_FLAG_DISABLE_PRIVATE_KEYS)) {
             out.watch_descs.emplace_back(desc->ToString(), creation_time);
 
diff --git a/src/wallet/test/walletload_tests.cpp b/src/wallet/test/walletload_tests.cpp
index 0c69849d0b..29f174be81 100644
--- a/src/wallet/test/walletload_tests.cpp
+++ b/src/wallet/test/walletload_tests.cpp
@@ -26,6 +26,7 @@ public:
     bool IsRange() const override { return false; }
     bool IsSolvable() const override { return false; }
     bool IsSingleType() const override { return true; }
+    bool IsWatchOnly(const SigningProvider&) const override { return false; }
     bool ToPrivateString(const SigningProvider& provider, std::string& out) const override { return false; }
     bool ToNormalizedString(const SigningProvider& provider, std::string& out, const DescriptorCache* cache = nullptr) const override { return false; }
     bool Expand(int pos, const SigningProvider& provider, std::vector<CScript>& output_scripts, FlatSigningProvider& out, DescriptorCache* write_cache = nullptr) const override { return false; };

```
</details>

File: src/script/descriptor.cpp (hunk 2 above)
Comment (rkrux) [reply src/script/descriptor.cpp]: Sorry but I don't understand how the second statement follows the first one above. 
For a non-watch-only wallet, isn't it guaranteed that there must be at least one private key, which should turn `has_priv_key` to `true`?

File: src/wallet/scriptpubkeyman.cpp (hunk 10 above)
Comment (Eunovo) [reply src/wallet/scriptpubkeyman.cpp]: Nice idea. Added you as Co-author in the relevant commit.

File: src/script/descriptor.cpp (hunk 2 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I forgot about the guard I added in https://github.com/bitcoin/bitcoin/pull/32471/commits/4202dca524aeef13e09380804c483d7c5402092d

You are right in the sense that it's not possible for a watch-only to even get to `ToPrivateString()` through the rpc; we could assert `has_priv_key` here. However, the descriptor unit tests often call `ToPrivateString()` on watch-only descriptors; asserting `has_priv_key` causes the tests to fail.

Comment (Eunovo) [reply src/script/descriptor.cpp]: To add this assertion, we will have to remove those checks, and I haven't seen the advantage in doing that.

Comment (rkrux) [reply src/script/descriptor.cpp]: > However, the descriptor unit tests often call ToPrivateString() on watch-only descriptors

Yeah, I don't know why this was done.

> To add this assertion, we will have to remove those checks, and I haven't seen the advantage in doing that.

Agree, doesn't need to be done right now.

**Comment by rkrux** [comment]
Thanks for addressing the comments, I will take one final look and then a-c-k.

Tagging @furszy for review as he noticed this issue as well few months back.

File: src/script/descriptor.h [hunk 11]
```diff
@@ -111,6 +111,9 @@ struct Descriptor {
     /** Whether this descriptor will return one scriptPubKey or multiple (aka is or is not combo) */
     virtual bool IsSingleType() const = 0;
 
+    /** Whether this descriptor contains any private key material */
```
Comment (Sjors) [inline src/script/descriptor.h]: In 2c0a84f1e2ebe98bcf5066acb0de0ba5138c2101 _descriptors: add IsWatchOnly()_: this doesn't describe the actual behavior. IIUC:

```cpp
/** Whether this descriptor is missing any private key material */
```

File: src/script/descriptor.cpp [hunk 12]
```diff
@@ -626,6 +626,31 @@ class DescriptorImpl : public Descriptor
...
+        size_t privkey_count{0};
+        std::set<CPubKey> pubkeys;
+        std::set<CExtPubKey> ext_pubkeys;
+        this->GetPubKeys(pubkeys, ext_pubkeys);
+        auto output_type{this->GetOutputType()};
+        for (auto pubkey : pubkeys) {
+            CKey key;
+            if (arg.GetKey(pubkey.GetID(), key)) {
+                privkey_count += 1;
+            } else if (output_type.has_value() && *output_type == OutputType::BECH32M && arg.GetKeyByXOnly(XOnlyPubKey(pubkey), key)) {
```
Comment (Sjors) [inline src/script/descriptor.cpp]: In https://github.com/bitcoin/bitcoin/commit/2c0a84f1e2ebe98bcf5066acb0de0ba5138c2101 descriptors: add IsWatchOnly(): since c++17 you can safely compare std::optional<T> with T, see item 21 here: https://en.cppreference.com/w/cpp/utility/optional/operator_cmp.html

I also find it easier to read if `privkey_count` and `pubkey_count` are tracked in the same manner, but feel free to ignore:

```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index 98ae29ceb3..a86b4743b3 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -628,26 +628,27 @@ public:

     bool IsWatchOnly(const SigningProvider& arg) const override
     {
+        size_t pubkey_count{0};
         size_t privkey_count{0};
         std::set<CPubKey> pubkeys;
         std::set<CExtPubKey> ext_pubkeys;
         this->GetPubKeys(pubkeys, ext_pubkeys);
-        auto output_type{this->GetOutputType()};
-        for (auto pubkey : pubkeys) {
-            CKey key;
-            if (arg.GetKey(pubkey.GetID(), key)) {
+        for (const CPubKey pubkey : pubkeys) {
+            pubkey_count++;
+            CKey dummy;
+            if (arg.GetKey(pubkey.GetID(), dummy)) {
                 privkey_count += 1;
-            } else if (output_type.has_value() && *output_type == OutputType::BECH32M && arg.GetKeyByXOnly(XOnlyPubKey(pubkey), key)) {
+            } else if (this->GetOutputType() == OutputType::BECH32M && arg.GetKeyByXOnly(XOnlyPubKey(pubkey), dummy)) {
                 privkey_count += 1;
             }
         }
-        for (auto extpubkey : ext_pubkeys) {
+        for (const CExtPubKey extpubkey : ext_pubkeys) {
+            pubkey_count++;
             CKey dummy;
             if (arg.GetKey(extpubkey.pubkey.GetID(), dummy)) {
                 privkey_count += 1;
             }
         }
-        size_t pubkey_count{pubkeys.size() + ext_pubkeys.size()};
         return (privkey_count == 0 || pubkey_count > privkey_count);
     }
```

File: src/test/miniscript_tests.cpp [hunk 13]
```diff
@@ -188,7 +188,7 @@ struct KeyConverter {
         return g_testdata->pkmap.at(keyid);
     }
 
-    std::optional<std::string> ToString(const Key& key) const {
+    std::string ToString(const Key& key, bool* has_priv_key = nullptr) const {
```
Comment (Sjors) [inline src/test/miniscript_tests.cpp]: In b32c2b290f8e4dcb7fe54ee4c81714a3785920a7 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_:

To preserve existing behaviour:

```cpp
if (has_priv_key) *has_priv_key = true;
```

It's a bit worrying that the test passes whether I set this to `false` or `true`. But that's a pre-existing issue, as the following change to the original code doesn't break the test either:

```diff
diff --git a/src/test/miniscript_tests.cpp b/src/test/miniscript_tests.cpp
index 0a32727f37..0989f0c50a 100644
--- a/src/test/miniscript_tests.cpp
+++ b/src/test/miniscript_tests.cpp
@@ -189,7 +189,7 @@ struct KeyConverter {
     }

     std::optional<std::string> ToString(const Key& key) const {
-        return HexStr(ToPKBytes(key));
+        return {};
     }

     miniscript::MiniscriptContext MsContext() const {
```

cc @darosior

**Review by Sjors — COMMENTED** [review]
Mostly happy with d82dcf2eaa7efb3809ae559c8f97f74403a2ccd6, but in  b32c2b290f8e4dcb7fe54ee4c81714a3785920a7 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_ I find the miniscript change hard to follow (mostly because I find the miniscript code itself hard to follow). Can you split that out in a seperate commit that doesn't change behaviour?

Tested with https://github.com/Sjors/bitcoin/pull/91.

Also left some code style suggestions.

File: src/script/descriptor.cpp (hunk 12 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I didn't use this patch, but I put some effort into making the code more readable.

File: src/script/descriptor.h (hunk 11 above)
Comment (Eunovo) [reply src/script/descriptor.h]: Thanks for this. I've updated the comment.

**Comment by Eunovo** [comment]
> Mostly happy with [d82dcf2](https://github.com/bitcoin/bitcoin/commit/d82dcf2eaa7efb3809ae559c8f97f74403a2ccd6), but in [b32c2b2](https://github.com/bitcoin/bitcoin/commit/b32c2b290f8e4dcb7fe54ee4c81714a3785920a7) _descriptor: ToPrivateString() pass if at least 1 priv key exists_ I find the miniscript change hard to follow (mostly because I find the miniscript code itself hard to follow). Can you split that out in a seperate commit that doesn't change behaviour?

I split the original commit into the following commits:
- https://github.com/bitcoin/bitcoin/pull/32471/commits/23431cde206bd6e18f274773f77bd914553bf2cc
- https://github.com/bitcoin/bitcoin/pull/32471/commits/d2b84af58073630f87df32a7b785971fe32cb9be
- https://github.com/bitcoin/bitcoin/pull/32471/commits/49f41141c674f83d0b66262a5b21aad623704264

I'm not sure https://github.com/bitcoin/bitcoin/pull/32471/commits/d2b84af58073630f87df32a7b785971fe32cb9be makes the miniscript change in https://github.com/bitcoin/bitcoin/pull/32471/commits/49f41141c674f83d0b66262a5b21aad623704264 easier to follow. I still think they should be one commit, but let me know if it helps.

@Sjors

File: src/test/miniscript_tests.cpp (hunk 13 above)
Comment (Eunovo) [reply src/test/miniscript_tests.cpp]: `has_priv_key` is only relevant when `ToPrivateString` is called on an actual Descriptor instance. IIUC, this test doesn't do that, so the value of `has_priv_key` does not matter here.
I'm not sure we should set it here, apart from the fact that it doesn't affect the test, the string returned doesn't have a private key.

File: src/script/descriptor.cpp [hunk 14]
```diff
@@ -841,6 +841,38 @@ class DescriptorImpl : public Descriptor
...
+
+        if (pubkey_count == 0) {
+            return true;
+        }
+
+        for (auto pubkey : pubkeys) {
+            CKey key;
+            if (arg.GetKey(pubkey.GetID(), key)) {
+                privkey_count += 1;
+            } else if (output_type.has_value() && output_type == OutputType::BECH32M && arg.GetKeyByXOnly(XOnlyPubKey(pubkey), key)) {
```
Comment (Sjors) [inline src/script/descriptor.cpp]: In 64213213b3691c9d93de95f880f820a640cd3c35 _descriptors: add IsWatchOnly()_: nit: you don't need `output_type.has_value()`

File: src/test/fuzz/miniscript.cpp [hunk 15]
```diff
@@ -124,10 +124,13 @@ struct ParserContext {
         return a < b;
     }
 
-    std::optional<std::string> ToString(const Key& key) const
+    std::string ToString(const Key& key, bool* has_priv_key) const
     {
         auto it = TEST_DATA.dummy_key_idx_map.find(key);
-        if (it == TEST_DATA.dummy_key_idx_map.end()) return {};
+        if (it == TEST_DATA.dummy_key_idx_map.end()) {
```
Comment (Sjors) [inline src/test/fuzz/miniscript.cpp:131]: In 49f41141c674f83d0b66262a5b21aad623704264 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_: maybe for good measure:

```cpp
*has_priv_key = false;
```

In both places it seems better to check that `priv_key` exists, even if that's always the case in this fuzzer. IIUC in that case you can leave out `tmp{false}` and just pass `nullptr` below.

**Review by Sjors — APPROVED** [review]
ACK 45e06e05e7f8d638ecc91a1ba62e1b38a5133a2b

I find that the separation of 23431cde206bd6e18f274773f77bd914553bf2cc makes it easier to follow. The separation of https://github.com/bitcoin/bitcoin/commit/d2b84af58073630f87df32a7b785971fe32cb9be from https://github.com/bitcoin/bitcoin/commit/49f41141c674f83d0b66262a5b21aad623704264 is less useful, but fine by me.

@achow101 can you update your concept opinion based on the updated behaviour? I think it makes sense to return a result if _any_ private key is present in descriptor, rather than all.

File: src/script/descriptor.cpp [hunk 16]
```diff
@@ -841,6 +841,38 @@ class DescriptorImpl : public Descriptor
         return true;
     }
 
+    bool IsWatchOnly(const SigningProvider& arg) const override
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 64213213b3691c9d93de95f880f820a640cd3c35 "descriptors: add IsWatchOnly()"

I think this function can be vastly simplified by calling `GetPrivKey` on all the `PubkeyProvider`, and `IsWatchOnly` on all subdescriptors.

nit: I don't like this function name since whether the descriptor is watchonly depends on the contents of the provided parameter. It's not a property like a `Is*` name implies. Watchonly also is not a property applied to descriptors as private keys are not actually part of the descriptor. Perhaps something like `HavePrivateKeys` instead.

File: src/script/descriptor.cpp [hunk 17]
```diff
@@ -896,24 +896,27 @@ class DescriptorImpl : public Descriptor
     }
 
     // NOLINTNEXTLINE(misc-no-recursion)
-    virtual bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, const DescriptorCache* cache = nullptr) const
+    virtual bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, bool* has_priv_key, const DescriptorCache* cache = nullptr) const
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 49f41141c674f83d0b66262a5b21aad623704264 "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

`has_priv_key` should be a reference not a pointer. The pointer-ness is never used in this function.

File: src/script/descriptor.cpp [hunk 18]
```diff
@@ -922,7 +925,8 @@ class DescriptorImpl : public Descriptor
                     if (!pubkey->ToNormalizedString(*arg, tmp, cache)) return false;
                     break;
                 case StringType::PRIVATE:
-                    if (!pubkey->ToPrivateString(*arg, tmp)) return false;
+                    assert(has_priv_key != nullptr);
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 49f41141c674f83d0b66262a5b21aad623704264 "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

If `has_priv_key` is never supposed to be null, then it should be a reference. Otherwise, this should be an `if`, we should not rely on caller behavior.

File: src/script/descriptor.cpp [hunk 19]
```diff
@@ -949,14 +955,17 @@ class DescriptorImpl : public Descriptor
 
     bool ToPrivateString(const SigningProvider& arg, std::string& out) const override
     {
-        bool ret = ToStringHelper(&arg, out, StringType::PRIVATE);
+        bool has_priv_key{false};
+        // ToStringHelper should never fail for StringType::PRIVATE,
+        // because it falls back to StringType::PUBLIC when no private key is available.
+        assert(ToStringHelper(&arg, out, StringType::PRIVATE, &has_priv_key));
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 49f41141c674f83d0b66262a5b21aad623704264 "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

`assert`s should not have side effects. If we are calling a function to actually do something, it should not be in an `assert`.

However, if the return value of `ToStringHelper` is always supposed to be `true`, then it should not be returning anything anyways. Furthermore, I don't see why `ToStringHelper` doesn't return whether the string has a private key, as we are doing in this function. That would allow us to drop `has_priv_key` from all of the function.

**Review by achow101 — COMMENTED** [review]
Concept ACK

File: src/script/descriptor.cpp (hunk 14 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I rewrote the function, so this comment is now outdated.

File: src/test/fuzz/miniscript.cpp (hunk 15 above)
Comment (Eunovo) [reply src/test/fuzz/miniscript.cpp:131]: Done

File: src/script/descriptor.cpp (hunk 16 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I was able to simplify the code as suggested, and I renamed it to `HavePrivateKeys()`

File: src/script/descriptor.cpp (hunk 17 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: The `has_priv_key` parameter has been removed.

File: src/script/descriptor.cpp (hunk 18 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: Done.

File: src/script/descriptor.cpp (hunk 19 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I refactored the code as suggested and was able to drop `has_priv_key` from the parameter list. Now, `has_priv_key` is returned if `type == StringType::PRIVATE`.

**Comment by Eunovo** [comment]
Thanks for the reviews! I have:
- renamed `IsWatchOnly()` to `HavePrivateKeys()`
- Added a test for `HavePrivateKeys()` to `descriptor_tests`
- Removed the unnecessary asserts from `ToStringHelper()` and `ToPrivateString()`
- Removed `has_priv_key` from `ToStringHelper()` and `ToSubStringHelper()` parameter lists

File: src/script/descriptor.cpp [hunk 20]
```diff
@@ -1418,24 +1425,34 @@ class TRDescriptor final : public DescriptorImpl
     }
     bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, const DescriptorCache* cache = nullptr) const override
     {
-        if (m_depths.empty()) return true;
+        if (m_depths.empty()) {
+            // If there are no sub-descriptors and a PRIVATE string
+            // is requested, return `false` to indicate that the presence
+            // of a private key depends solely on the internal key, not on
+            // any sub-descriptor. This ensures correct behavior for
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In deed439bff638abfc298a3b9c4f3d9f75fa18244 "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

Micro nit if retouched

```diff
-            // of a private key depends solely on the internal key, not on
-            // any sub-descriptor. This ensures correct behavior for
+           // of a private key depends solely on the internal key (which is checked
+           // in the caller), not on any sub-descriptor. This ensures correct behavior for
```

File: src/script/descriptor.cpp [hunk 21]
```diff
@@ -2104,7 +2120,7 @@ struct KeyParser {
         return key;
     }
 
-    std::optional<std::string> ToString(const Key& key) const
+    std::string ToString(const Key& key, bool* has_priv_key = nullptr) const
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In https://github.com/bitcoin/bitcoin/commit/deed439bff638abfc298a3b9c4f3d9f75fa18244 "descriptor: ToPrivateString() pass if at least 1 priv key exists"

Nit: 
```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index b6539ab12e..028a7299e5 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -2120,7 +2120,7 @@ struct KeyParser {
         return key;
     }
 
-    std::string ToString(const Key& key, bool* has_priv_key = nullptr) const
+    std::string ToString(const Key& key, bool*) const
     {
         return m_keys.at(key).at(0)->ToString();
     }
```

File: src/script/descriptor.cpp [hunk 22]
```diff
@@ -1524,11 +1541,12 @@ class StringMaker {
     StringMaker(const SigningProvider* arg LIFETIMEBOUND, const std::vector<std::unique_ptr<PubkeyProvider>>& pubkeys LIFETIMEBOUND, bool priv)
         : m_arg(arg), m_pubkeys(pubkeys), m_private(priv) {}
 
-    std::optional<std::string> ToString(uint32_t key) const
+    std::string ToString(uint32_t key, bool* has_priv_key = nullptr) const
     {
         std::string ret;
         if (m_private) {
-            if (!m_pubkeys[key]->ToPrivateString(*m_arg, ret)) return {};
+            assert(has_priv_key != nullptr);
```
Comment (rkrux) [inline src/script/descriptor.cpp]: In https://github.com/bitcoin/bitcoin/commit/deed439bff638abfc298a3b9c4f3d9f75fa18244 "descriptor: ToPrivateString() pass if at least 1 priv key exists"

Looks like the same argument applies here too?

https://github.com/bitcoin/bitcoin/pull/32471#discussion_r2258451488

> If has_priv_key is never supposed to be null, then it should be a reference.

**Review by rkrux — COMMENTED** [review]
The miniscript code took some time for me to understand.

lgtm ACK 4241edfce6f9a4a51121b39bc20040c14d220551

File: src/script/descriptor.h [hunk 23]
```diff
@@ -111,6 +111,13 @@ struct Descriptor {
     /** Whether this descriptor will return one scriptPubKey or multiple (aka is or is not combo) */
     virtual bool IsSingleType() const = 0;
 
+    /** Whether the given provider has all private keys required by this descriptor.
+     * @return `false` if the descriptor doesn't have any keys or subdescriptors,
+     *         or if the provider does not have all private keys required by
+     *         the descriptor.
+     */
+    virtual bool HavePrivateKeys(const SigningProvider& provider) const = 0;
```
Comment (rkrux) [inline src/script/descriptor.h:119]: In 726181bf5bbf23e188156d2ec2db3e0dcb83b2ee "descriptors: add HavePrivateKeys()"

Naming nit because the function is a part of a singular `Descriptor` class, but I see there is a combination of `Have*` (not my preference) and `Has*` functions in the singular object classes in the codebase, so feel free to ignore.
  
```diff
- virtual bool HavePrivateKeys(const SigningProvider& provider) const = 0;
+ virtual bool HasPrivateKeys(const SigningProvider& provider) const = 0;
```

File: src/script/descriptor.cpp (hunk 20 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: Done

File: src/script/descriptor.cpp (hunk 21 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: Done

File: src/script/descriptor.cpp (hunk 22 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: Fixed

**Review by rkrux — APPROVED** [review]
ACK 46860de809a1e9c7d0a1d716f77e9df7fb0bcd1c

```
git range-diff 4241edf...46860de
```

**Comment by Sjors** [comment]
utACK 46860de809a1e9c7d0a1d716f77e9df7fb0bcd1c

I studied 4d07eff13002384ed59a3b7f592be56a25b88c15 from scratch since it had quite a few changes since my last review.

File: src/script/descriptor.cpp [hunk 24]
```diff
@@ -885,13 +885,16 @@ class DescriptorImpl : public Descriptor
     virtual bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, const DescriptorCache* cache = nullptr) const
     {
         size_t pos = 0;
+        bool has_priv_key{false};
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 4d07eff13002384ed59a3b7f592be56a25b88c15 "descriptor: ToPrivateString() pass if  at least 1 priv key 

`has_priv_key` is a misnomer since for public strings, it has a completely different meaning. I would prefer naming this something more generic, like `any_success`, here and elsewhere.

File: src/script/descriptor.cpp [hunk 25]
```diff
@@ -1418,24 +1425,34 @@ class TRDescriptor final : public DescriptorImpl
...
     bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, const DescriptorCache* cache = nullptr) const override
     {
-        if (m_depths.empty()) return true;
+        if (m_depths.empty()) {
+            // If there are no sub-descriptors and a PRIVATE string
+            // is requested, return `false` to indicate that the presence
+            // of a private key depends solely on the internal key (which is checked
+            // in the caller), not on any sub-descriptor. This ensures correct behavior for
+            // descriptors like tr(internal_key) when checking for private keys.
+            return type == StringType::PRIVATE ? false : true;
```
Comment (achow101) [inline src/script/descriptor.cpp]: In 4d07eff13002384ed59a3b7f592be56a25b88c15 "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

nit: can be simplified to

```suggestion
            return type != StringType::PRIVATE
```

File: src/script/miniscript.h [hunk 26]
```diff
@@ -825,7 +825,7 @@ struct Node {
     }
 
     template<typename CTx>
-    std::optional<std::string> ToString(const CTx& ctx) const {
+    std::string ToString(const CTx& ctx, bool* has_priv_key = nullptr) const {
```
Comment (achow101) [inline src/script/miniscript.h]: In 4d07eff13002384ed59a3b7f592be56a25b88c15 "descriptor: ToPrivateString() pass if  at least 1 priv key exists"

`has_priv_key` does not need to be a pointer here.

File: src/script/descriptor.cpp (hunk 24 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: I think changing `has_priv_key` to `any_success` might make line 897 more confusing.

https://github.com/bitcoin/bitcoin/blob/4d07eff13002384ed59a3b7f592be56a25b88c15/src/script/descriptor.cpp#L897

File: src/script/miniscript.h (hunk 26 above)
Comment (Eunovo) [reply src/script/miniscript.h]: I changed this to use a reference and added an overload that doesn't use the reference; callers that don't need `has_priv_key` can still do `ToString(ctx)`

File: src/script/descriptor.cpp (hunk 24 above)
Comment (rkrux) [reply src/script/descriptor.cpp]: `has_priv_key` is used only for `PRIVATE` type, consider the following that limits its usage to avoid it being considered a misnomer - related unit/functional tests pass.

```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index f29e73e2e6..ef977a5912 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -891,7 +891,7 @@ public:
             std::string tmp;
             bool subscript_res{scriptarg->ToStringHelper(arg, tmp, type, cache)};
             if (type != StringType::PRIVATE && !subscript_res) return false;
-            has_priv_key = has_priv_key || subscript_res;
+            if (type == StringType::PRIVATE) has_priv_key = has_priv_key || subscript_res;
             ret += tmp;
         }
         return type == StringType::PRIVATE ? has_priv_key : true;
```

Comment (Eunovo) [reply src/script/descriptor.cpp]: I refactored the code a bit and changed `has_priv_key` to `any_success`.

**Comment by Eunovo** [comment]
Rebased on master @https://github.com/bitcoin/bitcoin/commit/2d6a0c4649 and refactored the code the based on suggestions from @achow101

File: test/functional/wallet_listdescriptors.py [hunk 27]
```diff
@@ -126,6 +126,29 @@ def run_test(self):
...
         assert_equal(expected, wallet.listdescriptors())
 
+        self.log.info('Test descriptor with missing private keys')
+        node.createwallet(wallet_name='w5', blank=True, descriptors=True)
+        wallet = node.get_wallet_rpc('w5')
+        tr_desc = descsum_create('tr(' + node.get_deterministic_priv_key().key +
+                                 ',{pk(03cdabb7f2dce7bfbd8a0b9570c6fd1e712e5d64045e9d6b517b3d5072251dc204)' +
+                                 ',pk([d34db33f/44h/0h/0h]tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/0)})')
+        miniscript_desc = descsum_create('wsh(and_v(v:ripemd160(095ff41131e5946f3c85f79e44adbcf8e27e080e),multi(1,' + node.get_deterministic_priv_key().key +
+                                            ',tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/0)))')
```
Comment (rkrux) [inline test/functional/wallet_listdescriptors.py]: In 74521dd6d4b65007547e64bda2bfbc6fe497677f "test: Test listdescs with priv works even with missing priv keys"

Consider importing few musig descriptors as well. Noticed this was an issue while reviewing #29675: https://github.com/bitcoin/bitcoin/pull/29675#discussion_r2330079926

Plus minor refactor to use `set` for importing and asserting to make it less redundant to read.

<details open>
<summary>More musig tests and refactoring diff</summary>

```diff
diff --git a/test/functional/wallet_listdescriptors.py b/test/functional/wallet_listdescriptors.py
index ce4859e43f..5204971e33 100755
--- a/test/functional/wallet_listdescriptors.py
+++ b/test/functional/wallet_listdescriptors.py
@@ -127,27 +127,33 @@ class ListDescriptorsTest(BitcoinTestFramework):
         assert_equal(expected, wallet.listdescriptors())
 
         self.log.info('Test descriptor with missing private keys')
-        node.createwallet(wallet_name='w5', blank=True, descriptors=True)
+        node.createwallet(wallet_name='w5', blank=True)
         wallet = node.get_wallet_rpc('w5')
-        tr_desc = descsum_create('tr(' + node.get_deterministic_priv_key().key +
-                                 ',{pk(03cdabb7f2dce7bfbd8a0b9570c6fd1e712e5d64045e9d6b517b3d5072251dc204)' +
-                                 ',pk([d34db33f/44h/0h/0h]tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/0)})')
-        miniscript_desc = descsum_create('wsh(and_v(v:ripemd160(095ff41131e5946f3c85f79e44adbcf8e27e080e),multi(1,' + node.get_deterministic_priv_key().key +
-                                            ',tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/0)))')
-        wallet.importdescriptors([
-            {
-                'desc': tr_desc,
-                'timestamp': TIME_GENESIS_BLOCK,
-            },
-            {
-                'desc': miniscript_desc,
-                'timestamp': TIME_GENESIS_BLOCK,
-            }
-        ])
+
+        expected_descs = {
+            descsum_create('tr(' + node.get_deterministic_priv_key().key +
+                ',{pk(03cdabb7f2dce7bfbd8a0b9570c6fd1e712e5d64045e9d6b517b3d5072251dc204)' +
+                ',pk([d34db33f/44h/0h/0h]tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/0)})'),
+            descsum_create('wsh(and_v(v:ripemd160(095ff41131e5946f3c85f79e44adbcf8e27e080e),multi(1,' + node.get_deterministic_priv_key().key +
+                ',tpubD6NzVbkrYhZ4WaWSyoBvQwbpLkojyoTZPRsgXELWz3Popb3qkjcJyJUGLnL4qHHoQvao8ESaAstxYSnhyswJ76uZPStJRJCTKvosUCJZL5B/0)))'),
+            descsum_create('tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,pk(musig(tprv8ZgxMBicQKsPeNLUGrbv3b7qhUk1LQJZAGMuk9gVuKh9sd4BWGp1eMsehUni6qGb8bjkdwBxCbgNGdh2bYGACK5C5dRTaif9KBKGVnSezxV,tpubD6NzVbkrYhZ4XcACN3PEwNjRpR1g4tZjBVk5pdMR2B6dbd3HYhdGVZNKofAiFZd9okBserZvv58A6tBX4pE64UpXGNTSesfUW7PpW36HuKz)/7/8/*))'),
+            descsum_create('tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,pk(musig(tprv8ZgxMBicQKsPeNLUGrbv3b7qhUk1LQJZAGMuk9gVuKh9sd4BWGp1eMsehUni6qGb8bjkdwBxCbgNGdh2bYGACK5C5dRTaif9KBKGVnSezxV/10,tpubD6NzVbkrYhZ4XcACN3PEwNjRpR1g4tZjBVk5pdMR2B6dbd3HYhdGVZNKofAiFZd9okBserZvv58A6tBX4pE64UpXGNTSesfUW7PpW36HuKz/11)/*))'),
+            descsum_create('tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,{pk(musig(tpubD6NzVbkrYhZ4Wo2WcFSgSqRD9QWkGxddo6WSqsVBx7uQ8QEtM7WncKDRjhFEexK119NigyCsFygA4b7sAPQxqebyFGAZ9XVV1BtcgNzbCRR,tprv8ZgxMBicQKsPen4PGtDwURYnCtVMDejyE8vVwMGhQWfVqB2FBPdekhTacDW4vmsKTsgC1wsncVqXiZdX2YFGAnKoLXYf42M78fQJFzuDYFN)/12/*),pk(musig(tprv8ZgxMBicQKsPeNLUGrbv3b7qhUk1LQJZAGMuk9gVuKh9sd4BWGp1eMsehUni6qGb8bjkdwBxCbgNGdh2bYGACK5C5dRTaif9KBKGVnSezxV,tpubD6NzVbkrYhZ4XWb6fGPjyhgLxapUhXszv7ehQYrQWDgDX4nYWcNcbgWcM2RhYo9s2mbZcfZJ8t5LzYcr24FK79zVybsw5Qj3Rtqug8jpJMy)/13/*)})')
+        }
+
+        descs_to_import = []
+        for desc in expected_descs:
+            descs_to_import.append({'desc': desc, 'timestamp': TIME_GENESIS_BLOCK})
+
+        wallet.importdescriptors(descs_to_import)
         result = wallet.listdescriptors(True)
-        expected_descs = [tr_desc, miniscript_desc]
         actual_descs = [d['desc'] for d in result['descriptors']]
-        assert_equal(actual_descs, expected_descs)
+
+        assert_equal(len(actual_descs), len(expected_descs))
+        for desc in actual_descs:
+            if desc not in expected_descs:
+                raise AssertionError(f"{desc} missing")
+
 
 
 if __name__ == '__main__':

```
</details>

File: src/wallet/rpc/backup.cpp [hunk 28]
```diff
@@ -490,6 +491,9 @@ RPCHelpMan listdescriptors()
     if (!wallet) return UniValue::VNULL;
 
     const bool priv = !request.params[0].isNull() && request.params[0].get_bool();
+    if (wallet->IsWalletFlagSet(WALLET_FLAG_DISABLE_PRIVATE_KEYS) && priv) {
+        throw JSONRPCError(RPC_WALLET_ERROR, "Can't get private descriptor string for watch-only wallets");
```
Comment (rkrux) [inline src/wallet/rpc/backup.cpp:498]: In a797b2ab6ba69732a1b6f1b54b7785d4b802170e "walletrpc: reject listdes with priv key on w-only wallets"

Nit: To make it explicit in the error that the request params combination is invalid.
```diff
- throw JSONRPCError(RPC_WALLET_ERROR, "Can't get private descriptor string for watch-only wallets");
+ throw JSONRPCError(RPC_WALLET_ERROR, "Invalid request to get private descriptor string for watch-only wallets");
```

File: test/functional/wallet_listdescriptors.py (hunk 27 above)
Comment (rkrux) [reply test/functional/wallet_listdescriptors.py]: There appears to be an issue with the following MuSig descriptor that fails the test:

One of the MuSig portion in the descriptor doesn't contain any private key for which the `listdescriptors(true)` returns a `pk()` instead of defaulting to the public keys whereas the `listdescriptors()` works fine.

```python
        desc = descsum_create('tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,{pk(musig(tpubD6NzVbkrYhZ4Wo2WcFSgSqRD9QWkGxddo6WSqsVBx7uQ8QEtM7WncKDRjhFEexK119NigyCsFygA4b7sAPQxqebyFGAZ9XVV1BtcgNzbCRR,tpubD6NzVbkrYhZ4Wc3i6L6N1Pp7cyVeyMcdLrFGXGDGzCfdCa5F4Zs3EY46N72Ws8QDEUYBVwXfDfda2UKSseSdU1fsBegJBhGCZyxkf28bkQ6)/12/*),pk(musig(tprv8ZgxMBicQKsPeNLUGrbv3b7qhUk1LQJZAGMuk9gVuKh9sd4BWGp1eMsehUni6qGb8bjkdwBxCbgNGdh2bYGACK5C5dRTaif9KBKGVnSezxV,tpubD6NzVbkrYhZ4XWb6fGPjyhgLxapUhXszv7ehQYrQWDgDX4nYWcNcbgWcM2RhYo9s2mbZcfZJ8t5LzYcr24FK79zVybsw5Qj3Rtqug8jpJMy)/13/*)})')
        result = wallet.importdescriptors([{
            'desc': desc,
            'timestamp': TIME_GENESIS_BLOCK,
        }])
        result = wallet.listdescriptors(True)
        result = wallet.listdescriptors()
```

Debug Output for `result` object.
```zsh
2025-10-03T09:56:03.473944Z TestFramework (INFO): Test descriptor with missing private keys
'tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,{pk(musig(tpubD6NzVbkrYhZ4Wo2WcFSgSqRD9QWkGxddo6WSqsVBx7uQ8QEtM7WncKDRjhFEexK119NigyCsFygA4b7sAPQxqebyFGAZ9XVV1BtcgNzbCRR,tpubD6NzVbkrYhZ4Wc3i6L6N1Pp7cyVeyMcdLrFGXGDGzCfdCa5F4Zs3EY46N72Ws8QDEUYBVwXfDfda2UKSseSdU1fsBegJBhGCZyxkf28bkQ6)/12/*),pk(musig(tprv8ZgxMBicQKsPeNLUGrbv3b7qhUk1LQJZAGMuk9gVuKh9sd4BWGp1eMsehUni6qGb8bjkdwBxCbgNGdh2bYGACK5C5dRTaif9KBKGVnSezxV,tpubD6NzVbkrYhZ4XWb6fGPjyhgLxapUhXszv7ehQYrQWDgDX4nYWcNcbgWcM2RhYo9s2mbZcfZJ8t5LzYcr24FK79zVybsw5Qj3Rtqug8jpJMy)/13/*)})#jd2qx33n'
[{'success': True,
  'warnings': ['Range not given, using default keypool range',
               'Not all private keys provided. Some wallet functionality may '
               'return unexpected errors']}]
{'wallet_name': 'w5',
 'descriptors': [{'desc': 'tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,{pk(),pk(musig(tprv8ZgxMBicQKsPeNLUGrbv3b7qhUk1LQJZAGMuk9gVuKh9sd4BWGp1eMsehUni6qGb8bjkdwBxCbgNGdh2bYGACK5C5dRTaif9KBKGVnSezxV,tpubD6NzVbkrYhZ4XWb6fGPjyhgLxapUhXszv7ehQYrQWDgDX4nYWcNcbgWcM2RhYo9s2mbZcfZJ8t5LzYcr24FK79zVybsw5Qj3Rtqug8jpJMy)/13/*)})#53ynphm7',
                  'timestamp': 1296688602,
                  'active': False,
                  'range': [0, 0],
                  'next': 0,
                  'next_index': 0}]}
{'wallet_name': 'w5',
 'descriptors': [{'desc': 'tr(03dff1d77f2a671c5f36183726db2341be58feae1da2deced843240f7b502ba659,{pk(musig(tpubD6NzVbkrYhZ4Wo2WcFSgSqRD9QWkGxddo6WSqsVBx7uQ8QEtM7WncKDRjhFEexK119NigyCsFygA4b7sAPQxqebyFGAZ9XVV1BtcgNzbCRR,tpubD6NzVbkrYhZ4Wc3i6L6N1Pp7cyVeyMcdLrFGXGDGzCfdCa5F4Zs3EY46N72Ws8QDEUYBVwXfDfda2UKSseSdU1fsBegJBhGCZyxkf28bkQ6)/12/*),pk(musig(tpubD6NzVbkrYhZ4XqNGAWGWSzmxGWFwVjVTjZxh2fioKbVYi7Jx8fdbprVWsdW7mHwqjchBVas8TLZG4Xwuz4RKU4iaCqiCvoSkFCzQptqk5Y1,tpubD6NzVbkrYhZ4XWb6fGPjyhgLxapUhXszv7ehQYrQWDgDX4nYWcNcbgWcM2RhYo9s2mbZcfZJ8t5LzYcr24FK79zVybsw5Qj3Rtqug8jpJMy)/13/*)})#8396h37a',
                  'timestamp': 1296688602,
                  'active': False,
                  'range': [0, 0],
                  'next': 0,
                  'next_index': 0}]}
```

The following patch in `MuSigPubkeyProvider` seems to fix it.
1. `out` doesn't need to be cleared if no priv keys found. For non watch-only wallets, a descriptor without any private keys can't be imported anyway so there can't be a case wherein we need to propagate this check from `MuSigPubkeyProvider` to `TrDescriptor`. 

**It can be assumed that any other portion of the descriptor will have a private key.**

I haven't verified this^ assumption for every possible scenario and I suggest adding few more cases in this test wherein a private key is present in different portions of the `tr()` descriptor with `musig()`. Few templates for reference from #29675 PR: https://github.com/bitcoin/bitcoin/pull/29675/commits/ac599c4a9cb3b2d424932d3fd91f9eed17426827#diff-c94f9555a2569240d362a00a82764f4714f6c65283e3f96725cf2a1043a296b5R224-R238


2. After this PR, `pubkey->ToPrivateString` defaults to returning the public key in `tmp`, so the subsequent `else` block is redundant now.

 
```diff
diff --git a/src/script/descriptor.cpp b/src/script/descriptor.cpp
index 6eafcaa94c..76d4c8bb02 100644
--- a/src/script/descriptor.cpp
+++ b/src/script/descriptor.cpp
@@ -726,17 +726,14 @@ public:
             std::string tmp;
             if (pubkey->ToPrivateString(arg, tmp)) {
                 any_privkeys = true;
-                out += tmp;
-            } else {
-                out += pubkey->ToString();
             }
+            out += tmp;
         }
         out += ")";
         out += FormatHDKeypath(m_path);
         if (IsRangedDerivation()) {
             out += "/*";
         }
-        if (!any_privkeys) out.clear();
         return any_privkeys;
     }
     bool ToNormalizedString(const SigningProvider& arg, std::string& out, const DescriptorCache* cache = nullptr) const override
```

**Review by rkrux — CHANGES_REQUESTED** [review]
Requesting changes because found an issue with the `musig()` descriptor that can be fixed in this PR itself.

File: src/test/descriptor_tests.cpp [hunk 29]
```diff
@@ -49,7 +49,7 @@ constexpr int SIGNABLE = 1 << 3; // We can sign with this descriptor (this is no
 constexpr int DERIVE_HARDENED = 1 << 4; // The final derivation is hardened, i.e. ends with *' or *h
 constexpr int MIXED_PUBKEYS = 1 << 5;
 constexpr int XONLY_KEYS = 1 << 6; // X-only pubkeys are in use (and thus inferring/caching may swap parity of pubkeys/keyids)
-constexpr int MISSING_PRIVKEYS = 1 << 7; // Not all private keys are available, so ToPrivateString will fail.
+constexpr int MISSING_PRIVKEYS = 1 << 7; // Not all private keys are available, so ToPrivateString will fail and HavePrivateKeys() will return `true`.
```
Comment (DrahtBot) [inline src/test/descriptor_tests.cpp]: Not all private keys are available, so ToPrivateString will fail and HavePrivateKeys() will return true. -> ... will return false. [The comment contradicts the flag name and intent — if private keys are missing, HavePrivateKeys() should be false; the current text stating true is likely a typo and is misleading.]

Comment (rkrux) [reply src/test/descriptor_tests.cpp]: Is this comment in the code correct?

------------------------
`s/HavePrivateKeys/HasAllPrivateKeys` because the current implementation of `HavePrivateKeys` returns `false` immediately if a corresponding private key is not found for a public key; the function doc suggests this too - "Whether the given provider has all private keys required by this descriptor."

Whereas `ToPrivateString` returns `true` if any private key is found, the usage of `any_success` also suggests this.

File: test/functional/wallet_listdescriptors.py (hunk 27 above)
Comment (Eunovo) [reply test/functional/wallet_listdescriptors.py]: Thanks for pointing this out.

> 1. `out` doesn't need to be cleared if no priv keys found. For non watch-only wallets, a descriptor without any private keys can't be imported anyway so there can't be a case wherein we need to propagate this check from `MuSigPubkeyProvider` to `TrDescriptor`.

Yes, there must be a private key somewhere in the descriptor, so the `MusigPubkeyProvider` should not clear the string.

I used your patch and added you as co-author.

File: src/test/descriptor_tests.cpp (hunk 29 above)
Comment (Eunovo) [reply src/test/descriptor_tests.cpp]: I have updated the comment.

File: src/wallet/rpc/backup.cpp (hunk 28 above)
Comment (Eunovo) [reply src/wallet/rpc/backup.cpp:498]: I don't believe the suggested message is an improvement, so I will leave it as is.

**Review by rkrux — APPROVED** [review]
lgtm ACK 8b4d4b3

Thanks for quickly addressing the comments.

```zsh
git range-diff 74521dd...8b4d4b3
```

I have tried to think if the fix covers all the cases that could possibly arise in various descriptors containing private keys partially. Essentially, the `ToPrivateString` function of the descriptor classes returns `true` even if there is a single private key available for it, whereas the newly added `HavePrivateKeys` function returns `true` when all the private keys for the descriptor are available & hence, it's used in the wallet migration code now. 
Very good that the latest push also tests for the missing private keys case in the `else` block in the descriptor unit tests!

Note: I have limited exposure to the `Miniscript` code as of now; I might re-review later that portion again, but looks ok right now.

This issue has popped up in my own local quite a few times where it became hard for me to continue my workflow, hope it gets checked in soon!

File: src/script/descriptor.cpp [hunk 30]
```diff
@@ -841,6 +848,24 @@ class DescriptorImpl : public Descriptor
...
+
+        for (const auto& sub: m_subdescriptor_args) {
+            if (!sub->HavePrivateKeys(arg)) return false;
+        }
+
+        for (const auto& pubkey : m_pubkey_args) {
+            FlatSigningProvider provider;
+            pubkey->GetPrivKey(0, arg, provider);
+            if (provider.keys.empty()) return false;
+        }
```
Comment (w0xlt) [inline src/script/descriptor.cpp:859]: nit: Could reuse one temporary provider to reduce alloc churn.

```suggestion
       FlatSigningProvider tmp_provider;
        for (const auto& pubkey : m_pubkey_args) {
            tmp_provider.keys.clear();
            pubkey->GetPrivKey(0, arg, tmp_provider);
            if (tmp_provider.keys.empty()) return false;
        }
```

Comment (Eunovo) [reply src/script/descriptor.cpp:859]: Done

**Review by w0xlt — COMMENTED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/32471/commits/2b16014dfbe7e249e4929beafb4ce26415206e7a

**Review by rkrux — APPROVED** [review]
reACK 2b16014

```
git range-diff 8b4d4b3...2b16014
```

File: src/script/descriptor.cpp [hunk 31]
```diff
@@ -883,13 +883,17 @@ class DescriptorImpl : public Descriptor
     virtual bool ToStringSubScriptHelper(const SigningProvider* arg, std::string& ret, const StringType type, const DescriptorCache* cache = nullptr) const
     {
         size_t pos = 0;
+        bool is_private{type == StringType::PRIVATE};
+        bool any_success{!is_private};
```
Comment (Sjors) [inline src/script/descriptor.cpp:883]: In 23f8b6035ff6538134be3d3df8a3ab8ba47f86c0 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_: the variable name `any_success` had me confused. If you have to retouch, it would be good to document its meaning or rename it.

```cpp
// If a public string is requested, fail if no subscript returns
a public string. If a  private string is requested, fail if no 
subscript returns a private string.
```

Seems like `any_success` was suggested here: https://github.com/bitcoin/bitcoin/pull/32471#discussion_r2342296606

**Review by Sjors — COMMENTED** [review]
Was in the middle of a review, but had to leave. Some comments.

File: src/script/descriptor.cpp (hunk 31 above)
Comment (Eunovo) [reply src/script/descriptor.cpp:883]: I added comments where `any_success` was used.

**Comment by Eunovo** [comment]
Rebased on master. I updated the Miniscript implementation slightly due to changes from https://github.com/bitcoin/bitcoin/pull/31734

File: src/wallet/test/walletload_tests.cpp [hunk 32]
```diff
@@ -26,6 +26,7 @@ class DummyDescriptor final : public Descriptor {
     bool IsRange() const override { return false; }
     bool IsSolvable() const override { return false; }
     bool IsSingleType() const override { return true; }
+    bool HavePrivateKeys(const SigningProvider&) const override { return true; }
```
Comment (Sjors) [inline src/wallet/test/walletload_tests.cpp]: In 1441145f34f3cf6f9e30599a67defd276c9ef114 _descriptors: add HavePrivateKeys()_ nit: this is an odd default for the test, because e.g. `ToPrivateString` is `false` by default.

File: src/wallet/scriptpubkeyman.cpp [hunk 33]
```diff
@@ -717,10 +717,7 @@ std::optional<MigrationData> LegacyDataSPKM::MigrateToDescriptor()
 
         std::vector<CScript> desc_spks;
 
-        // Make the descriptor string with private keys
-        std::string desc_str;
-        bool watchonly = !desc->ToPrivateString(*this, desc_str);
-        if (watchonly && !m_storage.IsWalletFlagSet(WALLET_FLAG_DISABLE_PRIVATE_KEYS)) {
+        if (!desc->HavePrivateKeys(*this) && !m_storage.IsWalletFlagSet(WALLET_FLAG_DISABLE_PRIVATE_KEYS)) {
```
Comment (Sjors) [inline src/wallet/scriptpubkeyman.cpp:722]: In 7e2af0619058858138fe0b1b942d98324338c0da _wallet/migration: use HavePrivateKeys in place of ToPrivateString_: we should have a comment here to explain what this if condition if trying to achieve. The original comment (now deleted) wasn't great either. Try:

```cpp
// If we can't provide all private keys for this inferred descriptor,
// but this wallet is not watch-only, migrate it to the watch-only wallet.
if (...
```

It's useful to know, as you write in the PR description:

> In order to keep the scope of this PR limited to the RPC behaviour, this PR uses a different method to determine watchonly descriptors for the purpose of wallet migration. A follow-up PR can be opened to update migration logic to exclude descriptors with some private keys from the watchonly migration wallet.

Not sure if we want to further expand the comment, but let's add that to the commit message. That way future devs can understand why migration is inconsistent with RPC behaviour.

I do agree it's good to limit the PR scope in this way.

File: src/test/fuzz/miniscript.cpp [hunk 34]
```diff
@@ -1242,7 +1246,6 @@ FUZZ_TARGET(miniscript_string, .init = FuzzInit)
     if (!parsed) return;
 
     const auto str2 = parsed->ToString(parser_ctx);
-    assert(str2);
```
Comment (Sjors) [inline src/test/fuzz/miniscript.cpp:1245]: In 4dc37d89de0b8b39b3e5ca802067663cfc3bb529 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_: I wouldn't drop this assert; you're still referencing it the next line.

File: src/test/fuzz/miniscript.cpp [hunk 35]
```diff
@@ -1033,7 +1037,7 @@ void TestNode(const MsCtx script_ctx, const NodeRef& node, FuzzedDataProvider& p
 
     // Check that it roundtrips to text representation
     const ParserContext parser_ctx{script_ctx};
-    std::optional<std::string> str{node->ToString(parser_ctx)};
+    auto str{node->ToString(parser_ctx)};
```
Comment (Sjors) [inline src/test/fuzz/miniscript.cpp]: In 4dc37d89de0b8b39b3e5ca802067663cfc3bb529 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_: there's no need to change this?

**Review by Sjors — COMMENTED** [review]
I still need to (re-)review the non-test changes of 4dc37d89de0b8b39b3e5ca802067663cfc3bb529, but everything else looks fine.

I wrote an expansion of the fuzzer so it actually covers `has_priv_key`, see https://github.com/Eunovo/bitcoin/pull/3, but it can wait for a followup.

The commit message for 583797341106abab8e6e9bd4bbaf91d5cc7f0cc9 _walletrpc: reject listdes with priv key on w-only wallets_ could mention that this improves the error message.

File: src/script/descriptor.cpp [hunk 36]
```diff
@@ -1568,11 +1596,10 @@ class MiniscriptDescriptor final : public DescriptorImpl
...
     {
-        if (const auto res = m_node->ToString(StringMaker(arg, m_pubkey_args, type, cache))) {
-            out = *res;
-            return true;
-        }
-        return false;
+        bool has_priv_key{false};
+        auto res = m_node->ToString(StringMaker(arg, m_pubkey_args, type, cache), has_priv_key);
+        if (res) out = *res;
+        return type == StringType::PRIVATE ? has_priv_key : res.has_value();
```
Comment (Sjors) [inline src/script/descriptor.cpp]: In 4dc37d89de0b8b39b3e5ca802067663cfc3bb529 _descriptor: ToPrivateString() pass if  at least 1 priv key exists_:

The following makes it more clear why for private strings we only look at `has_priv_key` and don't care about whether res has a value:

```cpp
if (type == StringType::PRIVATE) {
    Assume(res.has_value());
    return has_priv_key;
} else {
    return res.has_value();
}
```

Or a bit shorter:

```cpp
return res.has_value() && (type != StringType::PRIVATE || has_priv_key);
```

Though in the edge case of `StringType::PRIVATE` with no `res`, this would return false which is a bit unexpected.

File: src/wallet/test/walletload_tests.cpp (hunk 32 above)
Comment (Eunovo) [reply src/wallet/test/walletload_tests.cpp]: Changed to `false`.

File: src/wallet/scriptpubkeyman.cpp (hunk 33 above)
Comment (Eunovo) [reply src/wallet/scriptpubkeyman.cpp:722]: I added your comment as is and updated the commit message.

**Comment by Sjors** [comment]
ACK 165f7283ea56e32ce336f17ac20f6b04357a145d

Just left one more (vague) suggestion above.

File: src/script/descriptor.cpp (hunk 36 above)
Comment (Eunovo) [reply src/script/descriptor.cpp]: The `Assume` check here is useful because we expect res to always have a value, so  I think the longer version is better. I have rebased the PR with the change.

Comment (Sjors) [reply src/script/descriptor.cpp]: Sounds good, I rebased https://github.com/Sjors/bitcoin/pull/108 on top of your latest push to see if it survives the current fuzz corpus sanity check.

**Comment by Sjors** [comment]
ACK 9c7e4771b13d4729fd20ea08b7e2e3209b134fff

**Comment by achow101** [comment]
ACK 9c7e4771b13d4729fd20ea08b7e2e3209b134fff

File: test/functional/wallet_listdescriptors.py [hunk 37]
```diff
@@ -146,6 +146,36 @@ def run_test(self):
...
+            descs_to_import.append({'desc': desc, 'timestamp': TIME_GENESIS_BLOCK})
+
+        wallet.importdescriptors(descs_to_import)
+        result = wallet.listdescriptors(True)
+        actual_descs = [d['desc'] for d in result['descriptors']]
+
+        assert_equal(len(actual_descs), len(expected_descs))
+        for desc in actual_descs:
+            if desc not in expected_descs:
+                raise AssertionError(f"{desc} missing")
```
Comment (w0xlt) [inline test/functional/wallet_listdescriptors.py:176]:
```suggestion
                raise AssertionError(f"Unexpected descriptor: {desc}")
```

File: src/script/descriptor.cpp [hunk 38]
```diff
@@ -1542,11 +1596,15 @@ class MiniscriptDescriptor final : public DescriptorImpl
...
                         const DescriptorCache* cache = nullptr) const override
     {
-        if (const auto res = m_node->ToString(StringMaker(arg, m_pubkey_args, type, cache))) {
-            out = *res;
-            return true;
+        bool has_priv_key{false};
+        auto res = m_node->ToString(StringMaker(arg, m_pubkey_args, type, cache), has_priv_key);
+        if (res) out = *res;
+        if (type == StringType::PRIVATE) {
+            Assume(res.has_value());
```
Comment (w0xlt) [inline src/script/descriptor.cpp:1603]: nit: if the `Assume()` somehow fails in release, out will be empty string rather than undefined.

```suggestion                                                               
            if (!res) out.clear();  
            Assume(res.has_value());
```

**Review by w0xlt — COMMENTED** [review]
reACK https://github.com/bitcoin/bitcoin/pull/32471/commits/9c7e4771b13d4729fd20ea08b7e2e3209b134fff with minor nits

**Review by rkrux — APPROVED** [review]
re-ACK 9c7e4771b13d4729fd20ea08b7e2e3209b134fff

but with a caveat that I have only looked at the range-diff and the latest commit messages this time. I've reviewed this PR before quite a few times and have now developed review fatigue for this PR. I'm relying on my previous acks to bolster this reack. 
```
git range-diff 2b16014...9c7e477
```

File: test/functional/wallet_listdescriptors.py (hunk 37 above)
Comment (Eunovo) [reply test/functional/wallet_listdescriptors.py:176]: Will fix if I retouch.

File: src/script/descriptor.cpp (hunk 38 above)
Comment (Eunovo) [reply src/script/descriptor.cpp:1603]: Will fix if I retouch.

**Comment by rkrux** [comment]
Regarding my earlier comment https://github.com/bitcoin/bitcoin/pull/32471#issuecomment-2897892091 on this PR, I created an issue for it #34378 and raised the corresponding PR #34379.
