### PR TITLE
rpc: Avoid creating non-standard raw transactions

### LINKED ISSUE #14868: Wrong transaction using bitcoin-cli and multiple op_return
Using bitcoin-cli in order to generate a transaction with two op_return generate a wrong transaction.

```
bitcoin-cli createrawtransaction "[]" "{\"data\":\"ee\", \"data\":\"ff\"}"
0200000000020000000000000000036a01ee0000000000000000036a01ee00000000
```

Decoding the hex I obtain the following transaction with two op_return with the same value.

```
bitcoin-cli decoderawtransaction "0200000000020000000000000000036a01ee0000000000000000036a01ee00000000"
{
  "txid": "ed4b691958a573c8569177606c77905ecd07c36eb5eec443f17a45427bb9f5fc",
  "hash": "ed4b691958a573c8569177606c77905ecd07c36eb5eec443f17a45427bb9f5fc",
  "version": 2,
  "size": 34,
  "vsize": 34,
  "weight": 136,
  "locktime": 0,
  "vin": [
  ],
  "vout": [
    {
      "value": 0.00000000,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_RETURN -110",
        "hex": "6a01ee",
        "type": "nulldata"
      }
    },
    {
      "value": 0.00000000,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_RETURN -110",
        "hex": "6a01ee",
        "type": "nulldata"
      }
    }
  ]
}
```

This incorrect behavior is related to the duplicate key "data" in the JSON passed to the "createrawtransaction" command.

The problem is related to the use of `outputs[name_].getValStr()` in an JSON with duplicated keys https://github.com/bitcoin/bitcoin/blob/master/src/rpc/rawtransaction.cpp#L432

Although this kind of transaction wouldn't be relayed, I thought about two possible solutions:
* raise an error as it happens for the use of two identical addresses, maybe calling `JSONRPCError(RPC_INVALID_PARAMETER ...` if more than one "data" field is recognized - easier to implement, 
* creation of the transaction correctly containing the two different op_returns, maybe need to pass one array in the data field of the passed JSON (like `"data": ["ee", "ff"]`) - maybe require API change.

### PR DESCRIPTION
**Pull request by maflcko**
Multiple OP_RETURN outputs in a transaction are not standard and unlikely to be relayed, so avoid creating them.

Apart from that, the logic was broken in that it duplicated the same hex-data for each data output: Closes #14868.

### CODE REVIEW

File: src/rpc/rawtransaction.cpp [hunk 1]
```diff
@@ -413,8 +412,17 @@ CMutableTransaction ConstructTransaction(const UniValue& inputs_in, const UniVal
...
     }
+
+    // Duplicate checking
+    std::set<CTxDestination> destinations;
+    bool has_data{false};
+
     for (const std::string& name_ : outputs.getKeys()) {
         if (name_ == "data") {
+            if (has_data) {
+                throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, duplicate data");
```
Comment (Empact) [inline src/rpc/rawtransaction.cpp]: nit: "duplicate data" could be misleading, as it could refer to the key or the value.

Comment (MarcoFalke) [reply src/rpc/rawtransaction.cpp]: They are key-value pairs and neither the data key, nor the data value are allowed to be duplicate?

**Comment by gmaxwell** [comment]
utACK

File: src/rpc/rawtransaction.cpp (hunk 1 above)
Comment (MarcoFalke) [reply src/rpc/rawtransaction.cpp]: Ok, fixed

**Comment by Empact** [comment]
`rpcwallet.cpp` also calls `ConstructTransaction`, has docs to update.

**Comment by isghe** [comment]
wouldn't be better to use the IsStandardTx function, in "src / policy / policy.cpp", to check if the tx is standard or not? I made a test in https://github.com/isghe/bitcoin/commits/raise-error-createrawtransaction-multi-OP_RETURN and it looks is working good.

I just added on top of https://github.com/bitcoin/bitcoin/pull/14888
```c++
    const CTransaction rawTxCopy (rawTx);
    std::string error;
    if (!IsStandardTx (rawTxCopy, error)) {
        throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter combination: " + error);
    }
```
with this result:
```
$ ./src/bitcoin-cli createrawtransaction "[]" "[{\"mguLQ6eGCHpnmRrDwAjbPpYAHjxY6GneeQ\":\"0.1\"}, {\"data\":\"ee\"}, {\"muLYgM1L3gCzLs1bPX5cVzx3ax1f4vBcpN\":\"0.2\"},{\"data\":\"ff\"}]" | xargs ./src/bitcoin-cli decoderawtransaction
error code: -8
error message:
Invalid parameter combination: multi-op-return
```

**Comment by Empact** [comment]
utACK fa4c8679ed94f215ce895938f7c3c169a2ce101e
@isghe I like 5987b7cadd15cd1b524fec430868ee0c174f06da - open another PR?

**Comment by promag** [comment]
@isghe note that this PR ensures the RPC is correct, rejects duplicate `data` objects, and the error is clear for the client.

utACK fa4c867.

**Comment by isghe** [comment]
before merging this PR I think we should consider also the discussion on https://github.com/bitcoin/bitcoin/pull/14888

**Comment by isghe** [comment]
who decide if a transaction is standard or not? `createrawtransaction` or `IsStandardTx `?

**Comment by laanwj** [comment]
utACK fa4c8679ed94f215ce895938f7c3c169a2ce101e

**Comment by fanquake** [comment]
Removing "Needs Backport" as this is being done in #14893.
