### PR TITLE
[Qt] fix a bug where the SplashScreen will not be hidden during startup

### LINKED ISSUE #7718: Verifying blocks window stays open after the main GUI appears
OSX 10.11.3 running an official 0.12.0 binary.
If you minimise the 'Verifying blocks' window and wait until the GUI has fully loaded, the minimised window is still available, and it will display the same % verified as when you minimised it.

2 windows
minimised

### PR DESCRIPTION
**Pull request by jonasschnelli**
Fixes https://github.com/bitcoin/bitcoin/issues/7718

I guess calling `QWidget::hide()` on a `QWidget::isMinimized()` will not always result in a hidden window.
It's hard to say if this is a bug or a feature.

This little PR will make sure, we de-minimize the splashscreen-window before hiding.

### CODE REVIEW

**Comment by laanwj** [comment]
Though this doesn't hurt, this sounds like an upstream Qt bug to me. Hide should hide no matter what the other window flags are.

Does this happen with all Qt versions?

File: src/qt/splashscreen.cpp [hunk 1]
```diff
@@ -141,6 +141,8 @@ SplashScreen::~SplashScreen()
 void SplashScreen::slotFinish(QWidget *mainWin)
 {
     Q_UNUSED(mainWin);
+    if (isMinimized())
```
Comment (laanwj) [inline src/qt/splashscreen.cpp]: Please add a comment why this is being done

**Comment by jonasschnelli** [comment]
I haven't looked at the Qt code. But I could understand the argument that a minimized window is hidden fro the user perspective (but not closed). For the API perspective, I guess we should do a `showNormal()` before `hide()`.

**Comment by jonasschnelli** [comment]
Added a comment.

**Comment by laanwj** [comment]
> But I could understand the argument that a minimized window is hidden fro the user perspective (but not closed)

But at least up until now, in Qt, hidden really meant hidden. As in: seem closed and be complete inaccessible from the user perspective. A lot of code relies on that being the case.

I'm kind of disappointed about Qt if this is on purpose. Managing window state becomes more and more complex (see how many of the lines of bitcoingui.cpp are spent on just that...).

**Comment by laanwj** [comment]
utACK b3e1348

**Review by weerayut3 — COMMENTED** [review]
/ *ถ้าหน้าต่างถูกย่อเล็กสุด hide () จะถูกละเลย * /
    / *ตรวจสอบให้แน่ใจว่าเรายกเลิกการย่อหน้าต่างสาดก่อนที่จะซ่อน* /
    if ( isMinimized ())
        showNormal ();
    ซ่อน ();
}
