### PR TITLE
Checks for null data transaction before issuing error to debug.log

### LINKED ISSUE #6142: Null data transactions are treated as unknown transaction in log messages
I have an application that makes a lot of listunspent rpc calls and issues a lot of null data OP_RETURN transactions. Bitcoind tracks the addresses that these OP_RETURN transactions are made from and when it calls listunspent (or getbalance or listaccounts) it calls CWalletTx::GetAmounts, which cannot find the output address for the transaction. Since it sees OP_RETURN transactions, it can't find an address and issues the error in debug.log: 

2015-05-15 02:28:42 CWalletTx::GetAmounts: Unknown transaction type found, txid 09c22cb5e360ed4d048a659992ace972c19e2f13e2cbd9eca84c6e1b92626e65

The user level behavior returns the correct results, but because my application has a high volume of rpc calls and transactions, the log very quickly fills up with these extraneous error messages and crashes the application. The simple fix is to check if the transaction is an OP_RETURN, and if it is not issue the debug.log statement.

### PR DESCRIPTION
**Pull request by accraze**
`CWalletTx::GetAmounts` could not find output address for null data transactions, thus issuing an error in debug.log. This change checks to see if the transaction is `OP_RETURN` before issuing error.

resolves #6142

### CODE REVIEW

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -1034,7 +1034,8 @@ void CWalletTx::GetAmounts(list<COutputEntry>& listReceived,
 
         // In either case, we need to get the destination address
         CTxDestination address;
-        if (!ExtractDestination(txout.scriptPubKey, address))
+
+        if (!ExtractDestination(txout.scriptPubKey, address) && txout.scriptPubKey[0] != OP_RETURN)
```
Comment (jonasschnelli) [inline src/wallet/wallet.cpp]: Instead of checking `txout.scriptPubKey[0]` you should probably use `CScript::IsUnspendable()`.

**Comment by jonasschnelli** [comment]
Concept ACK.

**Comment by accraze** [comment]
updated code to check using `CScript::IsUnspendable()`

**Comment by sipa** [comment]
utACK

**Comment by jonasschnelli** [comment]
utACK
