### PR TITLE
util: Add ArgsManager::GetCommand() and use it in bitcoin-wallet

### LINKED ISSUE #20902: wallet tool silently ignores trailing options
Steps to reproduce:

```
$ ./src/bitcoin-wallet -datadir=/tmp  info  -wallet=asdf
Wallet info
===========
Name: 
Format: bdb
Descriptors: no
Encrypted: no
HD (hd seed available): yes
Keypool Size: 2000
Transactions: 0
Address Book: 0
```

(See the mismatching wallet name!)

Compare to:

```
$ ./src/bitcoin-wallet -datadir=/tmp  -wallet=asdf info
Wallet info
===========
Name: asdf
Format: bdb
Descriptors: no
Encrypted: no
HD (hd seed available): yes
Keypool Size: 2000
Transactions: 0
Address Book: 0

### PR DESCRIPTION
**Pull request by maflcko**
This not only moves the parsing responsibility out from the wallet tool, but it also makes it easier to implement bitcoin-util #19937 

Fixes: #20902

### CODE REVIEW

**Comment by practicalswift** [comment]
Concept ACK

File: src/util/system.cpp [hunk 1]
```diff
@@ -310,8 +311,16 @@ bool ArgsManager::ParseParameters(int argc, const char* const argv[], std::strin
...
-            break;
+        if (key[0] != '-') {
+            if (accept_any_command) break;
+            Optional<unsigned int> flags = GetArgFlags(key);
+            if (!flags || !(*flags & ArgsManager::COMMAND)) {
+                error = strprintf("Invalid command '%s'", argv[i]);
+                return false;
+            }
+            m_commands.push_back(key);
+            continue;
```
Comment (ajtowns) [inline src/util/system.cpp:322]: I'm not sure multiple (sub)commands makes sense for us. At present, I think we have:

 * bitcoind - doesn't take subcommands
 * bitcoin-wallet - wants a single subcommand
 * bitcoin-tx - wants multiple instructions with parameters
 * bitcoin-cli - wants to do its own parsing of stuff after the options
 * bitcoin-qt - does its own parsing of stuff after the options for payment server support
 
For bitcoin-util, I think we want it to be more like bitcoin-wallet, and if we were to do a psbt version of bitcoin-tx's multiple commands in order to construct a psbt, I think that would look like `bitcoin-util psbt <subsubcmd> <subsubcmd> ..`.

So I don't think it makes much sense to support multiple subcommands, particularly without letting them have their own params. Which I think means you could have a nicer implementation with something like https://github.com/ajtowns/bitcoin/commits/202101-getcommand which lets you just say `AddCmd(...)` to start introducing new commands, don't have to explicitly set `accept_any_command` when parsing, and can just invoke `GetCommand()` and `GetArguments()` to get the pre-parsed results. Thoughts?

I've added a second commit on that branch that allows the ArgsManager options to come after the command, which is the same as this PR, but differs from current master (which leaves later options up to the command -- so bitcoin-cli treats them as rpc args, while bitcoin-wallet currently just silently ignores them).

File: src/bitcoin-wallet.cpp [hunk 2]
```diff
@@ -33,59 +33,60 @@ static void SetupWalletToolArgs(ArgsManager& argsman)
...
-    argsman.AddArg("create", "Create new wallet file", ArgsManager::ALLOW_ANY, OptionsCategory::COMMANDS);
-    argsman.AddArg("salvage", "Attempt to recover private keys from a corrupt wallet. Warning: 'salvage' is experimental.", ArgsManager::ALLOW_ANY, OptionsCategory::COMMANDS);
-    argsman.AddArg("dump", "Print out all of the wallet key-value records", ArgsManager::ALLOW_ANY, OptionsCategory::COMMANDS);
-    argsman.AddArg("createfromdump", "Create new wallet file from dumped records", ArgsManager::ALLOW_ANY, OptionsCategory::COMMANDS);
+    argsman.AddArg("info", "Get wallet info", ArgsManager::COMMAND, OptionsCategory::COMMANDS);
+    argsman.AddArg("create", "Create new wallet file", ArgsManager::COMMAND, OptionsCategory::COMMANDS);
+    argsman.AddArg("salvage", "Attempt to recover private keys from a corrupt wallet. Warning: 'salvage' is experimental.", ArgsManager::COMMAND, OptionsCategory::COMMANDS);
+    argsman.AddArg("dump", "Print out all of the wallet key-value records", ArgsManager::COMMAND, OptionsCategory::COMMANDS);
+    argsman.AddArg("createfromdump", "Create new wallet file from dumped records", ArgsManager::COMMAND, OptionsCategory::COMMANDS);
```
Comment (ajtowns) [inline src/bitcoin-wallet.cpp:40]: I think this would be a lot better if we could link options to commands (so `-format` could be tied to `createfromdump` directly rather than having it hidden in the help text and having a special cased if statement). Some options would need to be available for multiple (but not all) commands (`-dumpfile` for `dump` and `createfromdump` eg).

This seems like a bit more of an intrusive change to make, and probably doesn't have to be done immediately though.

**Review by ajtowns — COMMENTED** [review]
Concept ACK

File: src/bitcoin-wallet.cpp (hunk 2 above)
Comment (MarcoFalke) [reply src/bitcoin-wallet.cpp:40]: > This seems like a bit more of an intrusive change to make, and probably doesn't have to be done immediately though.

Indeed. Will leave this for a follow-up. This should be a minimal bugfix/feature commit.

File: src/util/system.cpp [hunk 3]
```diff
@@ -518,6 +533,11 @@ void ArgsManager::AddArg(const std::string& name, const std::string& help, unsig
     auto ret = arg_map.emplace(arg_name, Arg{name.substr(eq_index, name.size() - eq_index), help, flags});
     assert(ret.second); // Make sure an insertion actually happened
 
+    if (flags & ArgsManager::COMMAND) {
+        Assert(flags == ArgsManager::COMMAND); // Combination not allowed
+        Assert(name.find('=') == std::string::npos);
+        Assert(name.find('-') == std::string::npos);
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/util/system.cpp]: Thanks, fixed

File: src/util/system.cpp (hunk 1 above)
Comment (MarcoFalke) [reply src/util/system.cpp]: Thanks, took most of your changes

**Comment by MarcoFalke** [comment]
Rebased once more

File: src/util/system.cpp [hunk 4]
```diff
@@ -359,6 +374,19 @@ Optional<unsigned int> ArgsManager::GetArgFlags(const std::string& name) const
     return nullopt;
 }
 
+bool ArgsManager::GetCommand(std::string& cmd, std::vector<std::string>& args) const
```
Comment (ajtowns) [inline src/util/system.cpp:377]: Might be good to call it `AddCommand` and `GetCommand` for consistency?

File: src/util/system.cpp [hunk 5]
```diff
@@ -359,6 +374,19 @@ Optional<unsigned int> ArgsManager::GetArgFlags(const std::string& name) const
...
+{
+    LOCK(cs_args);
+    assert(!m_accept_any_command); // AddCmd must have been called before this
```
Comment (ajtowns) [inline src/util/system.cpp:380]: I wonder if it wouldn't be better to always copy the remaining args into `m_command` and have the only difference be that you get an "unknown command" when `m_accept_any_command` is set

File: src/bitcoin-wallet.cpp [hunk 6]
```diff
@@ -94,33 +95,28 @@ int main(int argc, char* argv[])
...
-                return EXIT_FAILURE;
-            }
-            method = argv[i];
-        }
-    }
-
-    if (method.empty()) {
+    std::string method;
+    std::vector<std::string> cmdargs;
+    if (!args.GetCommand(method, cmdargs)) {
```
Comment (ajtowns) [inline src/bitcoin-wallet.cpp:100]: This feels a bit messy; when trying this for bitcoin-util, I added a `struct CmdArg { string cmd; vector<string> args; };` to track them both.

**Review by ajtowns — COMMENTED** [review]
ACK fad369f04361e2e3a834589b63fab160b9b4e1b2

Looks good; comments are just ideas for consideration. Patch for bitcoin-util at https://github.com/ajtowns/bitcoin/commits/202101-util-addcmd

**Review by fjahr — COMMENTED** [review]
Code review ACK fad369f04361e2e3a834589b63fab160b9b4e1b2

This works, however I liked @ajtowns comments and I think consistency whether `method` or `command` is used would be good. It seems method is getting replaced by command, is that a general naming scheme change?

**Comment by laanwj** [comment]
Concept ACK

File: src/util/system.cpp (hunk 4 above)
Comment (MarcoFalke) [reply src/util/system.cpp]: I took the naming from https://github.com/ajtowns/bitcoin/commit/ff48eb93bd485fb5e722d47690508f2a3506d30c. Nonetheless, changed in the latest force push.

File: src/util/system.cpp (hunk 5 above)
Comment (MarcoFalke) [reply src/util/system.cpp]: Thanks. Fixed, I think

File: src/bitcoin-wallet.cpp (hunk 6 above)
Comment (MarcoFalke) [reply src/bitcoin-wallet.cpp]: Thanks. Fixed, I think

File: src/bitcoin-wallet.cpp [hunk 7]
```diff
@@ -95,21 +95,16 @@ int main(int argc, char* argv[])
...
         tfm::format(std::cerr, "No method provided. Run `bitcoin-wallet -help` for valid methods.\n");
         return EXIT_FAILURE;
     }
+    if (cmdargs.size() != 0) {
+        tfm::format(std::cerr, "Error: Additional arguments provided (%s). Please refer to `-help`. Commands do not take arguments.\n", Join(cmdargs, ", "));
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/bitcoin-wallet.cpp]: Thanks, fixed

File: src/bitcoin-wallet.cpp [hunk 8]
```diff
@@ -95,21 +95,16 @@ int main(int argc, char* argv[])
...
-            if (!method.empty()) {
-                tfm::format(std::cerr, "Error: two methods provided (%s and %s). Only one method should be provided.\n", method, argv[i]);
-                return EXIT_FAILURE;
-            }
-            method = argv[i];
-        }
-    }
-
-    if (method.empty()) {
+    std::string method;
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/bitcoin-wallet.cpp]: Thanks, fixed

File: src/bitcoin-wallet.cpp [hunk 9]
```diff
@@ -95,21 +95,16 @@ int main(int argc, char* argv[])
...
+    std::vector<std::string> cmdargs;
+    if (!args.GetCommand(method, cmdargs)) {
         tfm::format(std::cerr, "No method provided. Run `bitcoin-wallet -help` for valid methods.\n");
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/bitcoin-wallet.cpp:100]: Seems unrelated, so I am going to leave as is for now to minimize the diff

**Comment by MarcoFalke** [comment]
Rebased

File: test/functional/tool_wallet.py [hunk 10]
```diff
@@ -188,6 +188,8 @@ def test_invalid_tool_commands_and_args(self):
         self.assert_raises_tool_error('Invalid command: help', 'help')
         self.assert_raises_tool_error('Error: two methods provided (info and create). Only one method should be provided.', 'info', 'create')
         self.assert_raises_tool_error('Error parsing command line arguments: Invalid parameter -foo', '-foo')
+        self.assert_raises_tool_error('No method provided. Run `bitcoin-wallet -help` for valid methods.')
```
Comment (fjahr) [inline test/functional/tool_wallet.py:191]: in fa06bce4ac17f93decd4ee38c956e7aa55983f0d:

nit: Commit message could have been a bit more descriptive ;)

File: src/util/system.h [hunk 11]
```diff
@@ -248,6 +251,20 @@ class ArgsManager
      */
     const std::list<SectionInfo> GetUnrecognizedSections() const;
 
+    struct Command {
```
Comment (fjahr) [inline src/util/system.h:254]: in fa61b9d1a68820758f9540653920deaeae6abe79:

nit: seeing this now I think I would have named it `CommandCall` or something similar to express that it's command + args. But feel free to ignore my name bikeshedding.

**Review by fjahr — APPROVED** [review]
Code review ACK fa61b9d1a68820758f9540653920deaeae6abe79

Feel free to ignore my nits.

File: src/util/system.h (hunk 11 above)
Comment (MarcoFalke) [reply src/util/system.h:254]: https://github.com/bitcoin/bitcoin/pull/20715#discussion_r557886983 names it `CmdArg`. So I could call it `CommandArg` or `CommandArgs` (because there might be multiple args to the command). Not sure what to do here, but I think I'll leave this as is for now and let the naming committee determine a suitable name and let them change it after merge.

File: test/functional/tool_wallet.py (hunk 10 above)
Comment (MarcoFalke) [reply test/functional/tool_wallet.py:191]: Thanks, will change on the next push

**Comment by ajtowns** [comment]
ACK fa61b9d1a68820758f9540653920deaeae6abe79

Looks good to me, though the third commit has a typo in the description: "dependend". Updated https://github.com/ajtowns/bitcoin/commits/202101-util-addcmd

**Comment by MarcoFalke** [comment]
> third commit has a typo in the description: "dependend".

Good catch. Though, I'll leave this as-is to minimize the re-review backlog.
