### PR TITLE
validation: remove BLOCK_FAILED_CHILD

### LINKED ISSUE #32173: validation: `CheckBlockIndex` crashes during block reconsideration
Functional test to reproduce:

```python
from test_framework.test_framework import BitcoinTestFramework

class CheckBlockIndexBug(BitcoinTestFramework):
    def set_test_params(self):
        self.setup_clean_chain = True
        self.num_nodes = 1

    def run_test(self):
        self.generatetoaddress(self.nodes[0], 1, "2N9hLwkSqr1cPQAPxbrGVUjxyjD11G2e1he");
        hashes = self.generatetoaddress(self.nodes[0], 1, "2N9hLwkSqr1cPQAPxbrGVUjxyjD11G2e1he");
        self.generatetoaddress(self.nodes[0], 1, "2N2CmnxjBbPTHrawgG2FkTuBLcJtEzA86sF");

        res = self.nodes[0].gettxoutsetinfo()
        self.generatetoaddress(self.nodes[0], 3, "2N9hLwkSqr1cPQAPxbrGVUjxyjD11G2e1he");
        self.log.info(self.nodes[0].invalidateblock(res["bestblock"]))
        self.generatetoaddress(self.nodes[0], 3, "2N9hLwkSqr1cPQAPxbrGVUjxyjD11G2e1he");
        self.nodes[0].reconsiderblock(hashes[0])
        self.nodes[0].invalidateblock(hashes[0])
        self.log.info(self.nodes[0].reconsiderblock(res["bestblock"]))

if __name__ == '__main__':
    CheckBlockIndexBug(__file__).main()
```

Stack trace:
```
bitcoind: validation.cpp:5392: void ChainstateManager::CheckBlockIndex(): Assertion `(pindex->nStatus & BLOCK_FAILED_MASK) == 0' failed.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3423379==ERROR: AddressSanitizer: ABRT on unknown address 0x000000343c93 (pc 0x7fb83abf0eec bp 0x7fb8348f16c0 sp 0x7fb8348efc30 T6)
    #0 0x7fb83abf0eec  (/lib/x86_64-linux-gnu/libc.so.6+0x8aeec) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
    #1 0x7fb83aba1fb1 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x3bfb1) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
    #2 0x7fb83ab8c471 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x26471) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
    #3 0x7fb83ab8c394  (/lib/x86_64-linux-gnu/libc.so.6+0x26394) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
    #4 0x7fb83ab9aec1 in __assert_fail (/lib/x86_64-linux-gnu/libc.so.6+0x34ec1) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
    #5 0x5578f6306f64 in ChainstateManager::CheckBlockIndex() /bitcoin/build_fuzz/src/./validation.cpp:5392:13
    #6 0x5578f62fe81a in Chainstate::ActivateBestChain(BlockValidationState&, std::shared_ptr<CBlock const>) /bitcoin/build_fuzz/src/./validation.cpp:3627:16
    #7 0x5578f5d03436 in ReconsiderBlock(ChainstateManager&, uint256) /bitcoin/build_fuzz/src/./rpc/blockchain.cpp:1669:33
    #8 0x5578f5e3fbc7 in reconsiderblock()::$_0::operator()(RPCHelpMan const&, JSONRPCRequest const&) const /bitcoin/build_fuzz/src/./rpc/blockchain.cpp:1694:5
    #9 0x5578f5e3fbc7 in UniValue std::__invoke_impl<UniValue, reconsiderblock()::$_0&, RPCHelpMan const&, JSONRPCRequest const&>(std::__invoke_other, reconsiderblock()::$_0&, RPCHelpMan const&, JSONRPCRequest const&) /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/invoke.h:61:14
    #10 0x5578f5e3fbc7 in std::enable_if<is_invocable_r_v<UniValue, reconsiderblock()::$_0&, RPCHelpMan const&, JSONRPCRequest const&>, UniValue>::type std::__invoke_r<UniValue, reconsiderblock()::$_0&, RPCHelpMan const&, JSONRPCRequest const&>(reconsiderblock()::$_0&, RPCHelpMan const&, JSONRPCRequest const&) /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/invoke.h:114:9
    #11 0x5578f5e3fbc7 in std::_Function_handler<UniValue (RPCHelpMan const&, JSONRPCRequest const&), reconsiderblock()::$_0>::_M_invoke(std::_Any_data const&, RPCHelpMan const&, JSONRPCRequest const&) /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:290:9
    #12 0x5578f717fe3a in std::function<UniValue (RPCHelpMan const&, JSONRPCRequest const&)>::operator()(RPCHelpMan const&, JSONRPCRequest const&) const /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591:9
    #13 0x5578f717fe3a in RPCHelpMan::HandleRequest(JSONRPCRequest const&) const /bitcoin/build_fuzz/src/./rpc/util.cpp:684:20
    #14 0x5578f5dc8455 in CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan (*)())::'lambda'(JSONRPCRequest const&, UniValue&, bool)::operator()(JSONRPCRequest const&, UniValue&, bool) const /bitcoin/build_fuzz/src/./rpc/server.h:101:91
    #15 0x5578f5dc8455 in bool std::__invoke_impl<bool, CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan (*)())::'lambda'(JSONRPCRequest const&, UniValue&, bool)&, JSONRPCRequest const&, UniValue&, bool>(std::__invoke_other, CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan (*)())::'lambda'(JSONR
PCRequest const&, UniValue&, bool)&, JSONRPCRequest const&, UniValue&, bool&&) /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/invoke.h:61:14
    #16 0x5578f5dc8455 in std::enable_if<is_invocable_r_v<bool, CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan (*)())::'lambda'(JSONRPCRequest const&, UniValue&, bool)&, JSONRPCRequest const&, UniValue&, bool>, bool>::type std::__invoke_r<bool, CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan
(*)())::'lambda'(JSONRPCRequest const&, UniValue&, bool)&, JSONRPCRequest const&, UniValue&, bool>(CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan (*)())::'lambda'(JSONRPCRequest const&, UniValue&, bool)&, JSONRPCRequest const&, UniValue&, bool&&) /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/invoke.h:114:9
    #17 0x5578f5dc8455 in std::_Function_handler<bool (JSONRPCRequest const&, UniValue&, bool), CRPCCommand::CRPCCommand(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, RPCHelpMan (*)())::'lambda'(JSONRPCRequest const&, UniValue&, bool)>::_M_invoke(std::_Any_data const&, JSONRPCRequest const&, UniValue&, bool&&) /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:290:
9
    #18 0x5578f6177d47 in std::function<bool (JSONRPCRequest const&, UniValue&, bool)>::operator()(JSONRPCRequest const&, UniValue&, bool) const /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591:9
    #19 0x5578f6177d47 in ExecuteCommand(CRPCCommand const&, JSONRPCRequest const&, UniValue&, bool) /bitcoin/build_fuzz/src/./rpc/server.cpp:512:20
    #20 0x5578f6177d47 in ExecuteCommands(std::vector<CRPCCommand const*, std::allocator<CRPCCommand const*>> const&, JSONRPCRequest const&, UniValue&) /bitcoin/build_fuzz/src/./rpc/server.cpp:477:13
    #21 0x5578f6176b16 in CRPCTable::execute(JSONRPCRequest const&) const /bitcoin/build_fuzz/src/./rpc/server.cpp:497:13
    #22 0x5578f61759e6 in JSONRPCExec(JSONRPCRequest const&, bool) /bitcoin/build_fuzz/src/./rpc/server.cpp:353:31
    #23 0x5578f6512301 in HTTPReq_JSONRPC(std::any const&, HTTPRequest*) /bitcoin/build_fuzz/src/./httprpc.cpp:217:21
    #24 0x5578f653449f in std::function<bool (HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)>::operator()(HTTPRequest*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) const /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591:9
    #25 0x5578f653449f in HTTPWorkItem::operator()() /bitcoin/build_fuzz/src/./httpserver.cpp:60:9
    #26 0x5578f653c305 in WorkQueue<HTTPClosure>::Run() /bitcoin/build_fuzz/src/./httpserver.cpp:115:13
    #27 0x5578f6526470 in HTTPWorkQueueRun(WorkQueue<HTTPClosure>*, int) /bitcoin/build_fuzz/src/./httpserver.cpp:417:12
    #28 0x7fb83af2c4a2  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd44a2) (BuildId: 0c47cec75226c7736517d5acb61e373d541a5023)
    #29 0x5578f56a1b06 in asan_thread_start(void*) asan_interceptors.cpp.o
    #30 0x7fb83abef1f4  (/lib/x86_64-linux-gnu/libc.so.6+0x891f4) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
    #31 0x7fb83ac6f89b  (/lib/x86_64-linux-gnu/libc.so.6+0x10989b) (BuildId: 79005c16293efa45b441fed45f4f29b138557e9e)
```

### PR DESCRIPTION
**Pull request by stratospher**
Fixes https://github.com/bitcoin/bitcoin/issues/32173

even though we have a distinction between `BLOCK_FAILED_VALID` and `BLOCK_FAILED_CHILD` in the codebase,
we don't use it for anything. Whenever we check for BlockStatus, we use `BLOCK_FAILED_MASK` which encompasses both of them.

Since there is no functional difference between `BLOCK_FAILED_VALID` and `BLOCK_FAILED_CHILD` and it's added
code complexity to correctly categorise them (ex: https://github.com/bitcoin/bitcoin/pull/31405#discussion_r1914366243, https://github.com/bitcoin/bitcoin/pull/16856#issuecomment-565506585), we could just remove it.

Looking for conceptual feedback on whether it's better to improve handling of `BLOCK_FAILED_CHILD` in the codebase or remove `BLOCK_FAILED_CHILD`.

Of less relevance, but it would also fix a `reconsiderblock` crash that could happen in the situation mentioned in https://github.com/bitcoin/bitcoin/issues/32173#issuecomment-2767030982

Similar attempt in the past in https://github.com/bitcoin/bitcoin/pull/16856#issuecomment-568073859

### CODE REVIEW

**Comment by sedited** [comment]
Concept ACK

**Review by Prabhat1308 — COMMENTED** [review]
Concept ACK

I think removing is a better option. The only **weak** argument that we could have for not removing is that `BLOCK_FAILED_VALID` right now marks the start of the invalid block chain and is better for debugging manually. However , the burden of maintaining this distinction seems too high for debugging purposes with no actual benefit functionally.

File: src/node/blockstorage.cpp [hunk 1]
```diff
@@ -463,8 +463,10 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
                 pindex->m_chain_tx_count = pindex->nTx;
             }
         }
-        if (!(pindex->nStatus & BLOCK_FAILED_MASK) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_MASK)) {
-            pindex->nStatus |= BLOCK_FAILED_CHILD;
+        if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
+            // if BLOCK_FAILED_CHILD already exists in disk, clear it
```
Comment (maflcko) [inline src/node/blockstorage.cpp]: exists in disk -> exists on disk [“in disk” is nonstandard; use “on disk”]


An alternative wording could be "if ... was persisted, clear it"

**Review by mzumsande — COMMENTED** [review]
Concept ACK

**Review by naiyoma — COMMENTED** [review]
Concept ACK, 

Wondering if the CI failure is related to this issue. ->https://github.com/bitcoin/bitcoin/issues/32855

**Review by yuvicc — COMMENTED** [review]
Concept ACK

The CI failure looks like due to #32855

File: src/node/blockstorage.cpp (hunk 1 above)
Comment (stickies-v) [reply src/node/blockstorage.cpp]: Or:

> // BLOCK_FAILED_CHILD is deprecated, but may still exist on disk. Replace it with BLOCK_FAILED_VALID.

**Review by stickies-v — COMMENTED** [review]
Concept ACK for removing it.

**Review by naiyoma — COMMENTED** [review]
TestedACK 06db700a1315bb655ac7fa12578c626990a22ea5


                      Block 2 (valid)
                        /         \
    (valid)Block height 3         Block height 3 (BLOCK_FAILED_CHILD)
                        |         |
    (valid) Block height 4        Block height 4(BLOCK_FAILED_CHILD)
                        |         |

Before removing BLOCK_FAILED_CHILD,this test(https://github.com/bitcoin/bitcoin/issues/32173#issue-2960274990) would fail at: `self.log.info(self.nodes[0].reconsiderblock(res["bestblock"]))`
(Reconsidering block at height 3 — which has BLOCK_FAILED_CHILD)
This failure happened because:

[This](https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L5297) check fails, block 3 has BLOCK_FAILED_CHILD (not BLOCK_FAILED_VALID).

and so in this assertion -> https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L5363 

`pindex->nStatus & BLOCK_FAILED_MASK) != 0.`

after removing BLOCK_FAILED_CHILD:


 block 3 , status is  BLOCK_FAILED_VALID, and `pindexFirstInvalid` is set correctly.

File: src/validation.cpp [hunk 2]
```diff
@@ -3657,7 +3657,7 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
     assert(pindex);
     if (pindex->nHeight == 0) return false;
 
-    CBlockIndex* to_mark_failed = pindex;
+    CBlockIndex* invalid_walk_tip = pindex;
```
Comment (mzumsande) [inline src/validation.cpp]: commit message ca2421d52792b32754f1801492822b999839ec3a:
"since the previous commit removes BLOCK_FAILED_CHILD" - only the following commit removes it. Or do you mean "any special logic for BLOCK_FAILED_CHILD"?

File: src/chain.h [hunk 3]
```diff
@@ -124,7 +124,8 @@ enum BlockStatus : uint32_t {
 
     BLOCK_FAILED_VALID       =   32, //!< stage after last reached validness failed
     BLOCK_FAILED_CHILD       =   64, //!< Unused flag that was previously set when descending from failed block
-    BLOCK_FAILED_MASK        =   BLOCK_FAILED_VALID | BLOCK_FAILED_CHILD,
+    BLOCK_FAILED_MASK        =   BLOCK_FAILED_VALID | BLOCK_FAILED_CHILD, //!< Unused flag that was previously used as
```
Comment (mzumsande) [inline src/chain.h]: do we need to keep BLOCK_FAILED_MASK in `chain.h` after it's no longer used? After all, it's only used as a mask (unlike BLOCK_FAILED_CHILD).

File: src/validation.cpp [hunk 4]
```diff
@@ -5365,9 +5365,9 @@ void ChainstateManager::CheckBlockIndex() const
         if ((pindex->nStatus & BLOCK_VALID_MASK) >= BLOCK_VALID_SCRIPTS) assert(pindexFirstNotScriptsValid == nullptr); // SCRIPTS valid implies all parents are SCRIPTS valid
         if (pindexFirstInvalid == nullptr) {
             // Checks for not-invalid blocks.
-            assert((pindex->nStatus & BLOCK_FAILED_MASK) == 0); // The failed mask cannot be set for blocks without invalid parents.
+            assert((pindex->nStatus & BLOCK_FAILED_VALID) == 0); // The failed mask cannot be set for blocks without invalid parents.
```
Comment (mzumsande) [inline src/validation.cpp]: comment still mentions a "mask"

**Review by mzumsande — COMMENTED** [review]
Looks good - just some minor comments.

File: src/node/blockstorage.cpp (hunk 1 above)
Comment (stratospher) [reply src/node/blockstorage.cpp]: done.

File: src/validation.cpp (hunk 2 above)
Comment (stratospher) [reply src/validation.cpp]: ah I see how it could be confusing, clarified it to "since the previous commit removes BLOCK_FAILED_CHILD usage in InvalidateBlock"

File: src/chain.h (hunk 3 above)
Comment (stratospher) [reply src/chain.h]: good point. I've removed it since `BLOCK_FAILED_MASK = 96` is never written to disk but only used while reading BlockStatus values. if 96 exists on disk, it is the responsibility of `BLOCK_FAILED_VALID` and `BLOCK_FAILED_CHILD` and we have dealt with those cases.

File: src/validation.cpp (hunk 4 above)
Comment (stratospher) [reply src/validation.cpp]: done.

**Review by sipa — COMMENTED** [review]
Concept ACK

File: src/node/blockstorage.cpp [hunk 5]
```diff
@@ -463,7 +463,7 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
                 pindex->m_chain_tx_count = pindex->nTx;
             }
         }
-        if (!(pindex->nStatus & BLOCK_FAILED_MASK) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_MASK)) {
+        if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
```
Comment (stickies-v) [inline src/node/blockstorage.cpp]: In 8e6c195396304e3c66471e208b1cd59eea02c11c:

This logic seems to deal with some kind of block index corruption (e.g. unclean shutdown) where not all children of an invalid block have been marked as invalid on-disk.

Let's assume a chain of blocks `A -> B -> C`. Do we have strong guarantees that it's impossible that:
- `A` is marked `BLOCK_FAILED_VALID`
- `B` is marked `BLOCK_FAILED_CHILD`
- `C` is not marked invalid

In the above scenario, the `blockstorage.cpp` logic on `master` would mark `C` as `BLOCK_FAILED_CHILD`, whereas on this PR it wouldn't be marked as `BLOCK_FAILED_VALID`. 

Perhaps useful to write a test around this?

File: src/validation.cpp (hunk 2 above)
Comment (stickies-v) [inline src/validation.cpp]: In 507b937eb39866c182b8a8939d2a71a80618f398: I think the `invalid_walk_tip` can (and if so, should) be kept local to the `while (true)` loop. Once that loop is finished, `invalid_walk_tip` should  be equivalent to `pindex`? This better isolates the tip-rewinding logic.

Suggested diff (that also uses `{disconnected,new}_tip` and moved code closer to where it's used for readability):


<details>
<summary>git diff on 507b937eb3</summary>

```diff
diff --git a/src/validation.cpp b/src/validation.cpp
index b8200eb1b6..013ae632e2 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -3657,10 +3657,6 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
     assert(pindex);
     if (pindex->nHeight == 0) return false;
 
-    CBlockIndex* invalid_walk_tip = pindex;
-    bool pindex_was_in_chain = false;
-    int disconnected = 0;
-
     // We do not allow ActivateBestChain() to run while InvalidateBlock() is
     // running, as that could cause the tip to change while we disconnect
     // blocks.
@@ -3692,6 +3688,9 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
         }
     }
 
+    bool pindex_was_in_chain = false;
+    int disconnected = 0;
+
     // Disconnect (descendants of) pindex, and mark them invalid.
     while (true) {
         if (m_chainman.m_interrupt) break;
@@ -3705,8 +3704,8 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
         LOCK(MempoolMutex());
         if (!m_chain.Contains(pindex)) break;
         pindex_was_in_chain = true;
-        invalid_walk_tip = m_chain.Tip();
 
+        CBlockIndex* disconnected_tip{m_chain.Tip()};
         // ActivateBestChain considers blocks already in m_chain
         // unconditionally valid already, so force disconnect away from it.
         DisconnectedBlockTransactions disconnectpool{MAX_DISCONNECTED_TX_POOL_BYTES};
@@ -3718,32 +3717,33 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
         // keeping the mempool up to date is probably futile anyway).
         MaybeUpdateMempoolForReorg(disconnectpool, /* fAddToMempool = */ (++disconnected <= 10) && ret);
         if (!ret) return false;
-        assert(invalid_walk_tip->pprev == m_chain.Tip());
+        CBlockIndex* new_tip{m_chain.Tip()};
+        assert(disconnected_tip->pprev == new_tip);
 
         // We immediately mark the disconnected blocks as invalid.
         // This prevents a case where pruned nodes may fail to invalidateblock
         // and be left unable to start as they have no tip candidates (as there
         // are no blocks that meet the "have data and are not invalid per
         // nStatus" criteria for inclusion in setBlockIndexCandidates).
-        invalid_walk_tip->nStatus |= BLOCK_FAILED_VALID;
-        m_blockman.m_dirty_blockindex.insert(invalid_walk_tip);
-        setBlockIndexCandidates.erase(invalid_walk_tip);
-        setBlockIndexCandidates.insert(invalid_walk_tip->pprev);
+        disconnected_tip->nStatus |= BLOCK_FAILED_VALID;
+        m_blockman.m_dirty_blockindex.insert(disconnected_tip);
+        setBlockIndexCandidates.erase(disconnected_tip);
+        setBlockIndexCandidates.insert(new_tip);
 
         // Mark out-of-chain descendants of the invalidated block as invalid
         // Add any equal or more work headers that are not invalidated to setBlockIndexCandidates
         // Recalculate m_best_header if it became invalid.
-        auto candidate_it = highpow_outofchain_headers.lower_bound(invalid_walk_tip->pprev->nChainWork);
+        auto candidate_it = highpow_outofchain_headers.lower_bound(new_tip->nChainWork);
 
-        const bool best_header_needs_update{m_chainman.m_best_header->GetAncestor(invalid_walk_tip->nHeight) == invalid_walk_tip};
+        const bool best_header_needs_update{m_chainman.m_best_header->GetAncestor(disconnected_tip->nHeight) == disconnected_tip};
         if (best_header_needs_update) {
             // pprev is definitely still valid at this point, but there may be better ones
-            m_chainman.m_best_header = invalid_walk_tip->pprev;
+            m_chainman.m_best_header = new_tip;
         }
 
         while (candidate_it != highpow_outofchain_headers.end()) {
             CBlockIndex* candidate{candidate_it->second};
-            if (candidate->GetAncestor(invalid_walk_tip->nHeight) == invalid_walk_tip) {
+            if (candidate->GetAncestor(disconnected_tip->nHeight) == disconnected_tip) {
                 // Children of failed blocks are marked as BLOCK_FAILED_VALID.
                 candidate->nStatus |= BLOCK_FAILED_VALID;
                 m_blockman.m_dirty_blockindex.insert(candidate);
@@ -3752,7 +3752,7 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
                 candidate_it = highpow_outofchain_headers.erase(candidate_it);
                 continue;
             }
-            if (!CBlockIndexWorkComparator()(candidate, invalid_walk_tip->pprev) &&
+            if (!CBlockIndexWorkComparator()(candidate, new_tip) &&
                 candidate->IsValid(BLOCK_VALID_TRANSACTIONS) &&
                 candidate->HaveNumChainTxs()) {
                 setBlockIndexCandidates.insert(candidate);
@@ -3771,7 +3771,7 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
 
     {
         LOCK(cs_main);
-        if (m_chain.Contains(invalid_walk_tip)) {
+        if (m_chain.Contains(pindex)) {
             // If the to-be-marked invalid block is in the active chain, something is interfering and we can't proceed.
             return false;
         }
@@ -3796,7 +3796,7 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
             }
         }
 
-        InvalidChainFound(invalid_walk_tip);
+        InvalidChainFound(pindex);
     }
 
     // Only notify about a new block tip if the active chain was modified.
@@ -3810,8 +3810,8 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
         // changes.
         (void)m_chainman.GetNotifications().blockTip(
             /*state=*/GetSynchronizationState(m_chainman.IsInitialBlockDownload(), m_chainman.m_blockman.m_blockfiles_indexed),
-            /*index=*/*invalid_walk_tip->pprev,
-            /*verification_progress=*/WITH_LOCK(m_chainman.GetMutex(), return m_chainman.GuessVerificationProgress(invalid_walk_tip->pprev)));
+            /*index=*/*pindex->pprev,
+            /*verification_progress=*/WITH_LOCK(m_chainman.GetMutex(), return m_chainman.GuessVerificationProgress(pindex->pprev)));
 
         // Fire ActiveTipChange now for the current chain tip to make sure clients are notified.
         // ActivateBestChain may call this as well, but not necessarily.

```
</details>

File: src/node/blockstorage.cpp [hunk 6]
```diff
@@ -464,7 +464,8 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
             }
         }
         if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
-            pindex->nStatus |= BLOCK_FAILED_VALID;
+            // BLOCK_FAILED_CHILD is deprecated, but may still exist on disk. Replace it with BLOCK_FAILED_VALID.
+            pindex->nStatus = (pindex->nStatus & ~BLOCK_FAILED_CHILD) | BLOCK_FAILED_VALID;
```
Comment (stickies-v) [inline src/node/blockstorage.cpp:493]: In 2e040d8b3c861c96c536754a82f4352b635c4d01:

It seems like we're trying to cram two different operations into one:
1. ensuring that all descendants of an invalid block are marked as invalid, in case there was any corruption/interruption
2. phasing out now-deprecated `BLOCK_FAILED_CHILD` flags

The current approach doesn't look robust to me, i.e. it won't catch all `BLOCK_FAILED_CHILD` flags. Suggested alternative that is more robust and (imo) more readable:

<details>
<summary>git diff on 2e040d8b3c</summary>

```diff
diff --git a/src/node/blockstorage.cpp b/src/node/blockstorage.cpp
index 47a7d656a8..d0e91e14d3 100644
--- a/src/node/blockstorage.cpp
+++ b/src/node/blockstorage.cpp
@@ -463,11 +463,16 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
                 pindex->m_chain_tx_count = pindex->nTx;
             }
         }
-        if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
+        if (pindex->nStatus & BLOCK_FAILED_CHILD) {
             // BLOCK_FAILED_CHILD is deprecated, but may still exist on disk. Replace it with BLOCK_FAILED_VALID.
             pindex->nStatus = (pindex->nStatus & ~BLOCK_FAILED_CHILD) | BLOCK_FAILED_VALID;
             m_dirty_blockindex.insert(pindex);
         }
+        if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
+            // All descendants of invalid blocks are invalid too.
+            pindex->nStatus = BLOCK_FAILED_VALID;
+            m_dirty_blockindex.insert(pindex);
+        }
         if (pindex->pprev) {
             pindex->BuildSkip();
         }

```
</details>

**Review by stickies-v — COMMENTED** [review]
Approach ACK 2e040d8b3c861c96c536754a82f4352b635c4d01

Intuitively it seems helpful to track something like `BLOCK_FAILED_CHILD`, but since it's been unused for so long it seems the use case isn't really there. Block validation logic is complex and critical and simplifying it is worth the effort, so I think this is the way to go.

File: src/node/blockstorage.cpp (hunk 5 above)
Comment (stratospher) [reply src/node/blockstorage.cpp]: > In the above scenario, the blockstorage.cpp logic on master would mark C as BLOCK_FAILED_CHILD, whereas on this PR it wouldn't be marked as BLOCK_FAILED_VALID

No, this doesn't change logic and both master and this PR would mark `C` as `BLOCK_FAILED_VALID`.

short answer: because we're iterating through block indices in increasing order of heights:

we'd first mark `B` as `BLOCK_FAILED_VALID` (from `BLOCK_FAILED_CHILD`)
`A -> B -> C` would then look like:
- `A` is marked `BLOCK_FAILED_VALID`
- `B` is marked `BLOCK_FAILED_VALID `
- `C` is not marked invalid

we can enter inside the if condition now(`C` isn't `BLOCK_FAILED_VALID` but it's parent is `BLOCK_FAILED_VALID`) and mark `C` as `BLOCK_FAILED_VALID`.

> Let's assume a chain of blocks A -> B -> C. Do we have strong guarantees that it's impossible that:

> A is marked BLOCK_FAILED_VALID
> B is marked BLOCK_FAILED_CHILD
> C is not marked invalid

I don't think this would happen naturally. If we receive a block header which is based on top of an invalid block header in our block index, `AcceptBlockHeader` would mark it as invalid.

Maybe some rare scenario where devs were playing with `invalidateblock` RPC?
- and `invalidateblock` RPC got interrupted before it could finish marking all descendant blocks as invalid
- and they happened to be restarting their node with this commit haha

Still not an issue since we update the invalidity flags during restart in `LoadBlockIndex`.

> Perhaps useful to write a test around this?

makes sense to test this migration behaviour. done in cfadc80.

File: src/node/blockstorage.cpp (hunk 6 above)
Comment (stratospher) [reply src/node/blockstorage.cpp:493]: > The current approach doesn't look robust to me, i.e. it won't catch all BLOCK_FAILED_CHILD flags. Suggested alternative that is more robust and (imo) more readable:

current approach catches all `BLOCK_FAILED_CHILD`. let's discuss it in https://github.com/bitcoin/bitcoin/pull/32950#discussion_r2414186294.

> git diff on https://github.com/bitcoin/bitcoin/commit/2e040d8b3c861c96c536754a82f4352b635c4d01

thanks! would have used the diff if there was a problem with the current approach. 

- current approach uses bit flips.
- the git diff uses an if guard - `if (pindex->nStatus & BLOCK_FAILED_CHILD)`.

I think avoiding bit flips with an if branch actually costs more than just doing the bit flips. we'd also enter into the if branch only once during the transition period and never again. so if it's just readability that is an advantage now, I have a slight preference for the current approach and have left it as such. let me know if I'm missing something!

File: src/validation.cpp (hunk 2 above)
Comment (stratospher) [reply src/validation.cpp]: nice! I like the clearer variable names. used this diff in f284834 and added you as a coauthor. 

1 difference with using `pindex` instead of `to_mark_failed` in [the last couple of lines](https://github.com/bitcoin/bitcoin/pull/32950/commits/f284834170d625b86de05d7b98d91eb8c39ab55e#diff-97c3a52bc5fad452d82670a7fd291800bae20c7bc35bb82686c2c0a4ea7b5b98L3777) - (ex: `InvalidChainFound(to_mark_failed);`) is that:
- `to_mark_failed` used to track the last disconnected block index
- `pindex` is the block index we call `invalidateblock` on

both of them are the same in a normal execution flow. if `invalidateblcok` gets interrupted, they'd be different.
but the remaining code won't be called anyways. so i don't think tracking the last disconnected block index adds any value now and this is better.

**Comment by stratospher** [comment]
thanks @stickies-v! I've addressed your review comments.
- added a test in https://github.com/bitcoin/bitcoin/pull/32950/commits/cfadc8038c08f9804c81af7950164483761f1db5
- used the `{disconnected,new}_tip` variable tracking suggestions in https://github.com/bitcoin/bitcoin/pull/32950#discussion_r2405494993

File: src/test/blockchain_tests.cpp [hunk 7]
```diff
@@ -145,6 +150,26 @@ BOOST_FIXTURE_TEST_CASE(invalidate_block, TestChain100Setup)
...
+        // intentionally mark:
+        //   - block_98: BLOCK_FAILED_VALID (already marked as BLOCK_FAILED_VALID from previous test)
+        //   - block_99: BLOCK_FAILED_CHILD (clear BLOCK_FAILED_VALID from previous test and mark as BLOCK_FAILED_CHILD)
+        //   - block_100: not invalid (clear BLOCK_FAILED_VALID from previous test)
+        LOCK(::cs_main);
+        assert(block_98->nStatus & BLOCK_FAILED_VALID);
+        block_99->nStatus = (block_99->nStatus & ~BLOCK_FAILED_VALID) | BLOCK_FAILED_CHILD;
+        block_100->nStatus = (block_100->nStatus & ~BLOCK_FAILED_VALID);
+
+        // Reload block index to recompute block status validity flags from disk.
```
Comment (stickies-v) [inline src/test/blockchain_tests.cpp]: Note that nothing is written to disk here, this is all happening in-memory. It doesn't look like the actual from-disk behaviour here is easy to test, because that's relying on `BlockManager` internals, so this is probably the closest we can test. (`nStatus` being a non-const public member while `m_dirty_blockindex` being private is... not great)

I think it makes sense to add this as a separate test case, it's not really related to `invalidateblock` and I find targeted tests easier to understand. Suggested diff with a few other improvements:

<details>
<summary>git diff on cfadc8038c</summary>

```diff
diff --git a/src/test/blockchain_tests.cpp b/src/test/blockchain_tests.cpp
index 5422095404..6b9fe75ea8 100644
--- a/src/test/blockchain_tests.cpp
+++ b/src/test/blockchain_tests.cpp
@@ -125,10 +125,6 @@ BOOST_FIXTURE_TEST_CASE(invalidate_block, TestChain100Setup)
     BlockValidationState state;
     auto* orig_tip = active.Tip();
 
-    CBlockIndex* block_100 = active[100];
-    CBlockIndex* block_99 = active[99];
-    CBlockIndex* block_98 = active[98];
-
     int height_to_invalidate = orig_tip->nHeight - 10;
     auto* tip_to_invalidate = active[height_to_invalidate];
     m_node.chainman->ActiveChainstate().InvalidateBlock(state, tip_to_invalidate);
@@ -150,26 +146,6 @@ BOOST_FIXTURE_TEST_CASE(invalidate_block, TestChain100Setup)
         WITH_LOCK(::cs_main, assert(pindex->nStatus & BLOCK_FAILED_VALID));
         pindex = pindex->pprev;
     }
-
-    {
-        // consider the chain of blocks block_98 <- block_99 <- block_100
-        // intentionally mark:
-        //   - block_98: BLOCK_FAILED_VALID (already marked as BLOCK_FAILED_VALID from previous test)
-        //   - block_99: BLOCK_FAILED_CHILD (clear BLOCK_FAILED_VALID from previous test and mark as BLOCK_FAILED_CHILD)
-        //   - block_100: not invalid (clear BLOCK_FAILED_VALID from previous test)
-        LOCK(::cs_main);
-        assert(block_98->nStatus & BLOCK_FAILED_VALID);
-        block_99->nStatus = (block_99->nStatus & ~BLOCK_FAILED_VALID) | BLOCK_FAILED_CHILD;
-        block_100->nStatus = (block_100->nStatus & ~BLOCK_FAILED_VALID);
-
-        // Reload block index to recompute block status validity flags from disk.
-        m_node.chainman->LoadBlockIndex();
-
-        // check block_98, block_99, block_100 is marked as BLOCK_FAILED_VALID after reloading from disk
-        assert(block_98->nStatus & BLOCK_FAILED_VALID);
-        assert(block_99->nStatus & BLOCK_FAILED_VALID);
-        assert(block_100->nStatus & BLOCK_FAILED_VALID);
-    }
 }
 
 BOOST_AUTO_TEST_SUITE_END()
diff --git a/src/test/validation_chainstatemanager_tests.cpp b/src/test/validation_chainstatemanager_tests.cpp
index bf440ca639..a5f4de17c6 100644
--- a/src/test/validation_chainstatemanager_tests.cpp
+++ b/src/test/validation_chainstatemanager_tests.cpp
@@ -557,6 +557,28 @@ BOOST_FIXTURE_TEST_CASE(chainstatemanager_loadblockindex, TestChain100Setup)
     BOOST_CHECK_EQUAL(cs2.setBlockIndexCandidates.size(), num_indexes - last_assumed_valid_idx + 1);
 }
 
+BOOST_FIXTURE_TEST_CASE(loadblockindex_invalid_descendants, TestChain100Setup)
+{
+    LOCK(Assert(m_node.chainman)->GetMutex());
+    // Consider the chain of blocks: grand_parent   <-      parent      <-       child
+    //                            BLOCK_FAILED_VALID   BLOCK_FAILED_CHILD     <not invalid>
+    // Test that when the block index is loaded, all blocks are marked as BLOCK_FAILED_VALID
+    auto* child{m_node.chainman->ActiveChain().Tip()};
+    auto* parent{child->pprev};
+    auto* grand_parent{parent->pprev};
+    grand_parent->nStatus = (grand_parent->nStatus | BLOCK_FAILED_VALID);
+    parent->nStatus = (parent->nStatus & ~BLOCK_FAILED_VALID) | BLOCK_FAILED_CHILD;
+    child->nStatus = (child->nStatus & ~BLOCK_FAILED_VALID);
+
+    // Reload block index to recompute block status validity flags.
+    m_node.chainman->LoadBlockIndex();
+
+    // check grand_parent, parent, child is marked as BLOCK_FAILED_VALID after reloading the block index
+    BOOST_CHECK(grand_parent->nStatus & BLOCK_FAILED_VALID);
+    BOOST_CHECK(parent->nStatus & BLOCK_FAILED_VALID);
+    BOOST_CHECK(child->nStatus & BLOCK_FAILED_VALID);
+}
+
 //! Ensure that snapshot chainstates initialize properly when found on disk.
 BOOST_FIXTURE_TEST_CASE(chainstatemanager_snapshot_init, SnapshotTestSetup)
 {

```
</details>

File: src/node/blockstorage.cpp (hunk 5 above)
Comment (stickies-v) [reply src/node/blockstorage.cpp]: > because we're iterating through block indices in increasing order of heights

Yes you're right, I hadn't factored this in. Thank you for pointing out my mistake, the logic looks correct indeed.

> makes sense to test this migration behaviour. done in https://github.com/bitcoin/bitcoin/commit/cfadc8038c08f9804c81af7950164483761f1db5. 

Thanks, great to have more test coverage!

File: src/node/blockstorage.cpp (hunk 6 above)
Comment (stickies-v) [reply src/node/blockstorage.cpp:493]: > so if it's just readability that is an advantage now, I have a slight preference for the current approach

Okay, no big deal either way. I'm not sure the performance difference is going to show up in any meaningful way so I generally prefer readability until the need for performance improvement is shown (or obvious), but up to you and either is fine.

File: src/validation.cpp (hunk 2 above)
Comment (stringintech) [reply src/validation.cpp]: > but the remaining code won't be called anyways

But previously we would call `InvalidChainFound()` on the last disconnected tip (and the rest of the code after the `m_chain.Contains(to_mark_failed)` check) even if we were interrupted; right?

**Comment by stringintech** [comment]
Concept ACK. Left two comments: [1](https://github.com/bitcoin/bitcoin/pull/32950#discussion_r2489983149) and [2](https://github.com/bitcoin/bitcoin/pull/32950#discussion_r2495351885)

File: src/node/blockstorage.cpp (hunk 5 above)
Comment (stringintech) [reply src/node/blockstorage.cpp]: Related to your discussion:

The cleanup check on line 466 assumes invalid chains on disk always start with `BLOCK_FAILED_VALID`, followed by descendants with `BLOCK_FAILED_CHILD`:

```cpp
if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID))
```

However, if we load a chain where the first invalid block is `BLOCK_FAILED_CHILD` (with a valid parent), none of the blocks in that chain would be cleaned up.

I'm not sure if this scenario is possible in practice (perhaps through incomplete disk writes or edge cases in how master differentiates between the two flags?), but it seems the suggested diff [here](https://github.com/bitcoin/bitcoin/pull/32950#discussion_r2405502780) wouldn't face the same issue.

In general, I think it makes sense to clean up every loaded `BLOCK_FAILED_CHILD` as `BLOCK_FAILED_VALID` during startup (the first step in the diff), regardless of whether the persisted status makes sense in context.

Comment (stratospher) [reply src/node/blockstorage.cpp]: @stringintech great catch! thank you! I've updated the PR to use the diff suggested above.

I forgot the 1 edge case scenario where this is possible -  https://github.com/bitcoin/bitcoin/issues/32173#issuecomment-2767030982.
I ran bitcoind with an inconsistent block index state from the functional test in the issue (`BLOCK_FAILED_CHILD` happens with valid parents) and current logic wouldn't work as you mentioned. but it works on the latest push now.

File: src/validation.cpp (hunk 2 above)
Comment (stratospher) [reply src/validation.cpp]: now that I think about it again, makes sense to call the rest of the code with last disconnected block (and not pindex) for a consistent + graceful shutdown. thanks for catching this!

File: src/test/blockchain_tests.cpp (hunk 7 above)
Comment (stratospher) [reply src/test/blockchain_tests.cpp]: taken. thanks!

**Comment by stratospher** [comment]
thanks for the great catches @stringintech and the nicer tests @stickies-v! I've pushed an [update](https://github.com/bitcoin/bitcoin/compare/cfadc8038c08f9804c81af7950164483761f1db5..b22d8b89c29a0a0d385d38d8ab74e5b940ddf7d5).

**Comment by fanquake** [comment]
Plenty of conceptual buy-in here, just seems that review momentum has stalled. This fixes at least 1, if not two bugs, so would be good to land in `31.x`. I've added it to the milestone.

File: src/node/blockstorage.cpp [hunk 8]
```diff
@@ -487,10 +487,18 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
...
-            pindex->nStatus |= BLOCK_FAILED_CHILD;
+
+        if (pindex->nStatus & BLOCK_FAILED_CHILD) {
+            // BLOCK_FAILED_CHILD is deprecated, but may still exist on disk. Replace it with BLOCK_FAILED_VALID.
+            pindex->nStatus = (pindex->nStatus & ~BLOCK_FAILED_CHILD) | BLOCK_FAILED_VALID;
+            m_dirty_blockindex.insert(pindex);
+        }
+        if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
+            // All descendants of invalid blocks are invalid too.
+            pindex->nStatus = BLOCK_FAILED_VALID;
```
Comment (stickies-v) [inline src/node/blockstorage.cpp]: I don't think we mean to override the entire `nStatus` here, just bitflip? (sorry for getting this wrong in my [suggestion](https://github.com/bitcoin/bitcoin/pull/32950/changes#r2405502780) earlier)
```suggestion
            pindex->nStatus |= BLOCK_FAILED_VALID;
```

The below test change fails without this fix, and passes with.

<details>
<summary>git diff on 16636cc5b9</summary>

```diff
diff --git a/src/node/blockstorage.cpp b/src/node/blockstorage.cpp
index 45c72f5af8..218ee222ef 100644
--- a/src/node/blockstorage.cpp
+++ b/src/node/blockstorage.cpp
@@ -495,7 +495,7 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
         }
         if (!(pindex->nStatus & BLOCK_FAILED_VALID) && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_VALID)) {
             // All descendants of invalid blocks are invalid too.
-            pindex->nStatus = BLOCK_FAILED_VALID;
+            pindex->nStatus |= BLOCK_FAILED_VALID;
             m_dirty_blockindex.insert(pindex);
         }
 
diff --git a/src/test/validation_chainstatemanager_tests.cpp b/src/test/validation_chainstatemanager_tests.cpp
index 40f99690ce..64aac67ccb 100644
--- a/src/test/validation_chainstatemanager_tests.cpp
+++ b/src/test/validation_chainstatemanager_tests.cpp
@@ -601,6 +601,7 @@ BOOST_FIXTURE_TEST_CASE(loadblockindex_invalid_descendants, TestChain100Setup)
     //   - child: not invalid
     // Test that when the block index is loaded, all blocks are marked as BLOCK_FAILED_VALID
     auto* child{m_node.chainman->ActiveChain().Tip()};
+    BOOST_CHECK(child->nStatus & BLOCK_HAVE_DATA);
     auto* parent{child->pprev};
     auto* grand_parent{parent->pprev};
     grand_parent->nStatus = (grand_parent->nStatus | BLOCK_FAILED_VALID);
@@ -614,6 +615,8 @@ BOOST_FIXTURE_TEST_CASE(loadblockindex_invalid_descendants, TestChain100Setup)
     BOOST_CHECK(grand_parent->nStatus & BLOCK_FAILED_VALID);
     BOOST_CHECK(parent->nStatus & BLOCK_FAILED_VALID);
     BOOST_CHECK(child->nStatus & BLOCK_FAILED_VALID);
+
+    BOOST_CHECK(child->nStatus & BLOCK_HAVE_DATA);
 }
 
 //! Ensure that snapshot chainstate can be loaded when found on disk after a

```
</details>

Comment (stratospher) [reply src/node/blockstorage.cpp]: whoops, thank you for catching that!

File: src/node/blockstorage.cpp
Comment (stickies-v) [inline src/node/blockstorage.cpp:1]: I think it's unsafe to place commit [validation: reset BLOCK_FAILED_CHILD to BLOCK_FAILED_VALID when loading from disk](https://github.com/bitcoin/bitcoin/pull/32950/changes/3a8226258e9a22ecad43d3e50daad8eb626d4e8b#r2814993781) after the [validation: remove BLOCK_FAILED_MASK](https://github.com/bitcoin/bitcoin/pull/32950/changes/42263bc30b8cb4655336fa991cf50c4975dcad73) commit. We should only remove `BLOCK_FAILED_MASK` when there can be no more instances of `BLOCK_FAILED_CHILD`. A good flow imo is: 
1) stop producing `BLOCK_FAILED_CHILD` flags
2) migrate legacy data
3) remove `BLOCK_FAILED_MASK`

File: src/validation.cpp [hunk 9]
```diff
@@ -3184,7 +3184,7 @@ CBlockIndex* Chainstate::FindMostWorkChain()
                 // Remove the entire chain from the set.
                 while (pindexTest != pindexFailed) {
                     if (fFailedChain) {
-                        pindexFailed->nStatus |= BLOCK_FAILED_CHILD;
+                        pindexFailed->nStatus |= BLOCK_FAILED_VALID;
```
Comment (stickies-v) [inline src/validation.cpp:3187]: Review note: probably orthogonal to this PR, but it seems strange that we need to do any `nStatus` update at all here. `FindMostWorkChain()` should not be responsible for/have side effects that update block validity. The unit and functional tests pass with the below change, so I think this is a no-op indeed. _(it also passes with `assert(pindexFailed->nStatus & BLOCK_FAILED_CHILD);` on `master`)_

Perhaps useful to address / clean up (if applicable, I'm very much not sure I'm not missing anything) in a separate PR? I think it's best to keep it as-is in this PR to keep the scope narrow. Alternatively, if my understanding is wrong, it could be useful to extend test coverage to catch this mutation, potentially in this PR?

<details>
<summary>git diff on b9653739c4</summary>

```diff
diff --git a/src/validation.cpp b/src/validation.cpp
index 4ec917a0d2..96d3fdf5cb 100644
--- a/src/validation.cpp
+++ b/src/validation.cpp
@@ -3184,8 +3184,7 @@ CBlockIndex* Chainstate::FindMostWorkChain()
                 // Remove the entire chain from the set.
                 while (pindexTest != pindexFailed) {
                     if (fFailedChain) {
-                        pindexFailed->nStatus |= BLOCK_FAILED_VALID;
-                        m_blockman.m_dirty_blockindex.insert(pindexFailed);
+                        assert(pindexFailed->nStatus & BLOCK_FAILED_VALID);
                     } else if (fMissingData) {
                         // If we're missing data, then add back to m_blocks_unlinked,
                         // so that if the block arrives in the future we can try adding

```
</details>

**Review by stickies-v — APPROVED** [review]
ACK b9653739c403bbc9fc2dc932be053bcad7acbe89 modulo [updating the commit ordering](https://github.com/bitcoin/bitcoin/pull/32950#discussion_r2814993781).

Prior to this PR, code was setting `BLOCK_FAILED_CHILD`, but (outside of tests) never directly reading it - always through `BLOCK_FAILED_MASK`. This, in combination with multiple full re-reviews, gives me good confidence that dropping `BLOCK_FAILED_CHILD` is safe, even if the validation logic is complex and I don't always understand all the nuances.

File: src/validation.cpp [hunk 10]
```diff
@@ -3626,32 +3626,33 @@ bool Chainstate::InvalidateBlock(BlockValidationState& state, CBlockIndex* pinde
...
         // Mark out-of-chain descendants of the invalidated block as invalid
         // Add any equal or more work headers that are not invalidated to setBlockIndexCandidates
         // Recalculate m_best_header if it became invalid.
-        auto candidate_it = highpow_outofchain_headers.lower_bound(invalid_walk_tip->pprev->nChainWork);
+        auto candidate_it = highpow_outofchain_headers.lower_bound(new_tip->nChainWork);
 
-        const bool best_header_needs_update{m_chainman.m_best_header->GetAncestor(invalid_walk_tip->nHeight) == invalid_walk_tip};
+        const bool best_header_needs_update{m_chainman.m_best_header->GetAncestor(disconnected_tip->nHeight) == disconnected_tip};
         if (best_header_needs_update) {
             // pprev is definitely still valid at this point, but there may be better ones
```
Comment (mzumsande) [inline src/validation.cpp]: nit: `pprev` -> `new_tip`, it's not clear what pprev refers to after the rename

File: src/chain.h [hunk 11]
```diff
@@ -77,7 +77,7 @@ enum BlockStatus : uint32_t {
     BLOCK_HAVE_MASK          =   BLOCK_HAVE_DATA | BLOCK_HAVE_UNDO,
 
     BLOCK_FAILED_VALID       =   32, //!< stage after last reached validness failed
-    BLOCK_FAILED_CHILD       =   64, //!< descends from failed block
+    BLOCK_FAILED_CHILD       =   64, //!< Unused flag that was previously set when descending from failed block
```
Comment (mzumsande) [inline src/chain.h:80]: nit: "remove BLOCK_FAILED_CHILD" in the commit message may be too strict sind it's still part of the enum - maybe call it "stop using" instead.

File: src/node/blockstorage.cpp
Comment (mzumsande) [reply src/node/blockstorage.cpp:1]: I think it's not too bad because blocks marked as `BLOCK_FAILED_CHILD` on master should have an ancestor  that is `BLOCK_FAILED_VALID`. So they should be marked as invalid anyway on startup - it would only lead to a wrong state if the original marking was already wrong due to an unrelated bug, as in https://github.com/bitcoin/bitcoin/issues/32173#issuecomment-2767030982. 
But I agree in general with the suggested flow and that it's cleaner to do this earlier.

File: src/validation.cpp (hunk 9 above)
Comment (mzumsande) [reply src/validation.cpp:3187]: Good find - I think this is there for historical reasons mostly: For a long time, `BLOCK_FAILED_CHILD` was set on a best-effort basis (just mark the easy ones and don't bother with the rest), and this is a convenient place to correct some spots that were missed.

Some of my past PRs made this more strict (when marking a block as failed, also mark all  descendants immediately as failed), with ed764ea2b4edb3cf1925a4bff5f39567a8be54ac finally adding an assert for this to `CheckBlockIndex` . This means if this update here was still necessary, there should be a hittable assert  in regtest / fuzz tests.

So I agree that we should be able to remove this now, but I would suggest to do that in a separate PR.

Adding an assert here would be way too dangerous in my opinion (some bug in a special constellation, and miners could take down large parts of the network by creating that case), but an `Assume` should be good.

**Review by mzumsande — COMMENTED** [review]
ACK b9653739c403bbc9fc2dc932be053bcad7acbe89  - I agree that moving commit 3a8226258e9a22ecad43d3e50daad8eb626d4e8b to an earlier spot would be good though.

File: src/node/blockstorage.cpp
Comment (stratospher) [reply src/node/blockstorage.cpp:1]: done in [this no code change push](https://github.com/bitcoin/bitcoin/compare/b9653739c403bbc9fc2dc932be053bcad7acbe89..94be9c93f12f9a2abea5bf8be0d732e224a8a9b6).

File: src/validation.cpp (hunk 9 above)
Comment (stratospher) [reply src/validation.cpp:3187]: nice find, I tried out a few scenarios like the one below and found that it doesn't need it since https://github.com/bitcoin/bitcoin/commit/f5149ddb9b7de3559943d7fda0f440e59413dfb5. 

- we receive headers A, B, C, D built on top of normal-chain -> A -> B -> C -> D
- we then receive blocks B, C, D
- we later receive A and find out it is invalid in `ConnectBlock`.

`ConnectBlock` calls `InvalidChainFound` and there's now a `SetBlockFailureFlags` inside since f5149ddb9b7de3559943d7fda0f440e59413dfb5 which marks B,C,D as invalid too. So we wouldn't enter a situation where `FindMostWorkChain` has to mark blocks as invalid since we already dealt with it when the invalid block was found. 

(need to think more about what happens during a race condition between `ForkMostWorkChain` and new header arriving - don't imagine it's a problem since we'd need `cs_main` anyways.)

will open a separate PR for this after some testing.

**Comment by stickies-v** [comment]
re-ACK fb3e1bf9c9772631571ca46d29c50330ebf54dfd

No changes except addressing review comments to:
- improve commit ordering
- docstring update
- commit message update

File: src/node/blockstorage.cpp [hunk 12]
```diff
@@ -487,10 +487,18 @@ bool BlockManager::LoadBlockIndex(const std::optional<uint256>& snapshot_blockha
                 pindex->m_chain_tx_count = pindex->nTx;
             }
         }
+
+        if (pindex->nStatus & BLOCK_FAILED_CHILD) {
+            // BLOCK_FAILED_CHILD is deprecated, but may still exist on disk. Replace it with BLOCK_FAILED_VALID.
+            pindex->nStatus = (pindex->nStatus & ~BLOCK_FAILED_CHILD) | BLOCK_FAILED_VALID;
+            m_dirty_blockindex.insert(pindex);
```
Comment (alexanderwiederin) [inline src/node/blockstorage.cpp:494]: When can we remove this, or is the idea to keep it forever?

**Review by alexanderwiederin — COMMENTED** [review]
Tested locally and reviewed all commits. Question on the migration code is inline.

ACK fb3e1bf9c9772631571ca46d29c50330ebf54dfd

File: src/node/blockstorage.cpp (hunk 12 above)
Comment (stratospher) [reply src/node/blockstorage.cpp:494]: ideally I'd imagine when there's  <100 nodes (that don't have a history of upgrading) in the network remaining, meaning all actively-maintained nodes have already migrated. I guess the number 100 is debatable/too conservative. just taking it as an example.

Comment (alexanderwiederin) [reply src/node/blockstorage.cpp:494]: Not sure how it's done here in core, but I would suggest we open a follow-up issue for the removal and reference it in the comment. What do you think?

**Review by mzumsande — COMMENTED** [review]
re-ACK fb3e1bf9c9772631571ca46d29c50330ebf54dfd

File: src/node/blockstorage.cpp (hunk 12 above)
Comment (sipa) [reply src/node/blockstorage.cpp:494]: This seems so low-cost that we can keep it around for forever, or at least until the next incompatible database change (IIRC, the last one was in 0.15 with per-txout records, and before that, 0.8).

**Review by sipa — COMMENTED** [review]
Posthumous code review ACK fb3e1bf9c9772631571ca46d29c50330ebf54dfd

Did someone test that downgrading to previous releases works?

**Comment by alexanderwiederin** [comment]
> Did someone test that downgrading to previous releases works?

I just tested on regtest. Verified `invalidateblock` and `reconsiderblock` work correctly across old -> new -> old node switches with multiple invalid chains.

**Comment by stratospher** [comment]
> Did someone test that downgrading to previous releases works?

yes! only difference which doesn't have any impact since `BLOCK_FAILED_CHILD` is only written and not used/read anywhere (not even in `CheckBlockIndex`) is this:

- in previous release suppose this chain existed:
genesisblock <- block1 <- block2(`BLOCK_FAILED_VALID`)  <- block3 (`BLOCK_FAILED_CHILD`) <-block4 (`BLOCK_FAILED_CHILD`)
- in new release it would become
genesisblock <- block1 <- block2(`BLOCK_FAILED_VALID`)  <- block3 (`BLOCK_FAILED_VALID`) <-block4 (`BLOCK_FAILED_VALID`)
- if we change to use previous release again, the `nStatus` would still remain the same (since we [only mark blocks which are valid](https://github.com/bitcoin/bitcoin/blob/37cc2a2d953c072a236b657bfd7de5167092a47a/src/node/blockstorage.cpp#L490) as `BLOCK_FAILED_CHILD` in `LoadBlockIndex`)
genesisblock <- block1 <- block2(`BLOCK_FAILED_VALID`)  <- block3 (`BLOCK_FAILED_VALID`) <-block4 (`BLOCK_FAILED_VALID`)

File: src/validation.cpp (hunk 9 above)
Comment (stratospher) [reply src/validation.cpp:3187]: done in https://github.com/bitcoin/bitcoin/pull/34884
