### PR TITLE
rpc: increase the defaults for -rpcthreads and -rpcworkqueue

### LINKED ISSUE #29386: Default rpcthreads value (4) is too small
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I keep having to increase `rpcthreads` about everywhere I'm using bitcoind because without it it's not very robust/performant.

Pasting verbatim my comment in [bdk that just hit the same issue](https://github.com/bitcoindevkit/bdk/pull/1320#issuecomment-1926231768):

> From a perspective of most workloads e.g. asking for blockchain data, `bitcoind` (and `electrs`) acts very much like database software, e.g. posgresql. Postgresql is an [interesting case because it utilizes process-based model](https://tech.slashdot.org/story/23/06/19/1723259/postgresql-reconsiders-its-process-based-model) - meaning it will spawn not just a thread, but a whole process for every client connection - waaay heavier than just a thread.
> 
> Even for that heavy model, the recommendations will be [to limit it around around 500](https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-managing-connections).
> 
> It takes many threads to saturate modern IO device. [Just an example from a yt video I had on hand benchamarking filesystems](https://youtu.be/AhjL1SHku7M?si=ZnSzjDUFpRvorQa5&t=241). Each bar is number of workers. And these are dedicated IO-generating workers, generating heavy load in a tight loop. So in this benchmark, it will take like 4 workers. Possibly one worker is even more threads. But an rpc thread in bitcoind by necessity will be spending lots of time reading things and writing stuff to a tcp connection, doing some checks, re-encodings and what not. To actually get a maximum IO performance there will need to be a lot of them. I'd say 64 per core.
> 
> 
> On my mostly idle laptop at this very moment there are 2k threads running:
> 
> image
> 
> On a modern Linux a thread is just a stack, which due to CoW optimizations will really amount to 1 or 2 pages (4K page size) of physically used memory plus a tiny (1K?) amount to track it all in the kernel.
> 
> There's really not much to save on thread counts in a grand scheme of things.
> 
> Personally, I like to run as lots and lots of tests in parallel, especially any sort of integration and e2e tests, which tend to have lots of dead time - waiting for stuff (like disk and network IO - latency-bound things). The usual limit to this is the available memory. Additional benefit is also that it tends to expose problems more often, as all operations tend to have more ... timing jitter.
> 
> So I'm really surprised that the default in `bitcoind` is 4. That's too little even for an old generation raspberry pi.

I just [noticed the comment in the code](https://github.com/bitcoin/bitcoin/blob/9eeee7caa3f95ee17a645e12d330261f8e3c2dbf/doc/reduce-memory.md?plain=1#L37C1-L39C15):

> For each thread a thread stack needs to be allocated. By default on Linux,
threads take up 8MiB for the thread stack on a 64-bit system, and 4MiB in a
32-bit system.

Only 8MiB of Virtual Memory is allocated, which doesn't really mean anything. Due to CoW mechanism, only the parts of stack that are being used will be allocated as Physical Memory which is the one that actually matters.

### Expected behaviour

NA

### Steps to reproduce

NA

### Relevant log output

NA

### How did you obtain Bitcoin Core

Other

### What version of Bitcoin Core are you using?

na

### Operating system and version

na

### Machine specifications

Linux

### PR DESCRIPTION
**Pull request by vasild**
`rpcthreads` was introduced with a default of 4 in 2013 in 21eb5adadbe3110a8708f2570185566e1f137a49

`rpcworkqueue` was introduced with a default of 16 in 2015 in 40b556d3742a1f65d67e2d4c760d0b13fe8be5b7

Resolves: https://github.com/bitcoin/bitcoin/issues/29386

---

Just bump the ancient default values. There is no perfect default that would fit everybody. This could lead to https://bikeshed.com/

### CODE REVIEW

File: src/httpserver.h [hunk 1]
```diff
@@ -14,8 +14,17 @@ namespace util {
 class SignalInterrupt;
 } // namespace util
 
-static const int DEFAULT_HTTP_THREADS=4;
-static const int DEFAULT_HTTP_WORKQUEUE=16;
+/**
+ * The default value for `-rpcthreads`. This number of threads will be created at startup.
+ */
+static const int DEFAULT_HTTP_THREADS=16;
```
Comment (dergoegge) [inline src/httpserver.h:20]: Maybe we should just  make the default depend on how many cores are available? e.g. default: `num cores / 2`

Comment (andrewtoth) [reply src/httpserver.h:20]: From the linked issue, the user is saying the default of 4 is not enough for a raspi, which has 4 cores. So this would lower that number on a raspi.

Comment (dergoegge) [reply src/httpserver.h:20]: I see, at least something based on the users system instead of picking a random number?

Comment (andrewtoth) [reply src/httpserver.h:20]: Just number of cores would make sense as a default. At least it wouldn't be lower on raspis.

Comment (laanwj) [reply src/httpserver.h:20]: i've always been kind of hestitant about adapting these values to the system automatically; it doesn't only depend on the CPU, but also the expected usage.

For a "fair" work queue it would indeed make sense to pick the number of CPU cores. However, bitcoin core's RPC threads often sleep for various reasons. Eg waiting for I/O, waiting for a lock in another thread, etc. So it's fine to have it a bit higher than the number of cores.
i'd definitely cap the minimum at 4, even for single-core CPUs.

i'm also not sure people running bitcoin core on say, giant 64+-core systems necessarily want 64+ RPC threads. They might be running it on the background as one of many processes, not intending to do a lot of parallel processing with it at all.

**Review by storopoli — APPROVED** [review]
Concept ACK

**Comment by laanwj** [comment]
ACK on increasing the default work queue size. i don't think the RPC work queue uses that much memory. It's fine to set the default a lot higher.

Not sure about the threads.

**Review by tdb3 — COMMENTED** [review]
Approach ACK

Performed a very basic sanity check (on signet) comparing 6463117a29294f6ddc9fafecfd1e9023956cc41b (commit under head) to head (e56fc7ce6a92eae7e80657d9f57a148cc002358d).

Ran `bitcoin-cli gettxoutsetinfo` 8x simultaneously on a system with 4 cores and timed the result (not claiming this to be the best test, just a quick check). The idea was to see if a core-constrained system would see a performance degradation from the PR change.

Without the increase of rpcthreads and rpcworkqueue, times of 57.63s, 59.75s, and 58.80s were observed.
With the increase introduced in the PR, times of 55.41s, 53.08s, 56.91s were observed.

So no performance degradation, and a bit of a performance increase was observed.

Would like to take a look at some other results before full ACK, but seems like a reasonable change.

**Review by andrewtoth — APPROVED** [review]
ACK e56fc7ce6a92eae7e80657d9f57a148cc002358d

Bumping the default threads and work queue enables a lot of workflows by default, like using it with a local address indexer. Right now these users have to manually configure the higher limits.
The higher limits won't increase memory unless they are being used. And these defaults can be set lower on memory constrained systems to disable using them.

**Comment by laanwj** [comment]
> The higher limits won't increase memory unless they are being used. And these defaults can be set lower on memory constrained systems to disable using them.

Not entirely true, every thread has some memory and overhead, even if it's not doing anything. On 32-bit systems the virtual memory space for the stack space of each thread is also significant.

**Review by storopoli — APPROVED** [review]
ACK e56fc7ce6a92eae7e80657d9f57a148cc002358d

**Review by tdb3 — APPROVED** [review]
ACK e56fc7ce6a92eae7e80657d9f57a148cc002358d

Saw performance improvement and no degradation.

**Comment by achow101** [comment]
ACK b9766c9977e58a9ebc358d9879576376e76a72b1

**Comment by dergoegge** [comment]
The docs still say that the default is 4: https://github.com/bitcoin/bitcoin/blob/15717f0ef3960969ee550a4a41741987b86684dc/doc/reduce-memory.md#thread-configuration

**Comment by laanwj** [comment]
@dergoegge Done in #31985
