### PR TITLE
Clamp walletpassphrase timeout to 2^30 seconds and check its bounds

### LINKED ISSUE #12100: unlocking an encrypted wallet for a very long time fails silently
If I unlock an encrypted wallet for 359711509437336256 or less seconds, I can sign transactions with it:

    $ bitcoin-cli walletpassphrase "$x" 359711509437336256
    $ echo $?
    0
    $ bitcoin-cli signrawtransaction $tx | grep complete
      "complete": true

But if I unlock it for 359711509437336257 or more seconds, it appears to have unlocked but I can't sign any transactions:

    $ bitcoin-cli walletpassphrase "$x" 359711509437336257
    $ echo $?
    0
    $ bitcoin-cli signrawtransaction $tx | grep complete
    error code: -13
    error message:
    Error: Please enter the wallet passphrase with walletpassphrase first.

I don't know the significance of that number. It's nowhere near a power of 2.

I was trying to unlock the wallet effectively "forever", so put a big number. If I use too big a number (2^63 or more) I get an error message `JSON integer out of range` but for numbers between 359711509437336257 and 2^63-1 inclusive I get no error, but no actual unlocking.

### PR DESCRIPTION
**Pull request by achow101**
Fixes #12100

Makes the timeout be clamped to 2^30 seconds to avoid the issue with sign flipping with large timeout values and thus relocking the wallet instantly. Unlocking for at most ~34 years should be sufficient.

Also checks that the timeout is not negative to avoid instant relocks.

### CODE REVIEW

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -2298,6 +2298,14 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
     // Alternately, find a way to make request.params[0] mlock()'d to begin with.
     strWalletPass = request.params[0].get_str().c_str();
 
+    // Get the timeout
+    int32_t nSleepTime = request.params[1].get_int();
+    pwallet->nRelockTime = GetTime() + nSleepTime;
```
Comment (luke-jr) [inline src/wallet/rpcwallet.cpp]: Probably shouldn't set this until *after* the sanity checks...

File: src/wallet/rpcwallet.cpp [hunk 2]
```diff
@@ -2298,6 +2298,14 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
     // Alternately, find a way to make request.params[0] mlock()'d to begin with.
     strWalletPass = request.params[0].get_str().c_str();
 
+    // Get the timeout
+    int32_t nSleepTime = request.params[1].get_int();
```
Comment (luke-jr) [inline src/wallet/rpcwallet.cpp]: Probably should use `int`, not `int32_t` (they're not guaranteed to be the same)

Comment (achow101) [reply src/wallet/rpcwallet.cpp]: Done.

File: src/wallet/rpcwallet.cpp (hunk 1 above)
Comment (achow101) [reply src/wallet/rpcwallet.cpp]: Oops, fixed.

File: src/wallet/rpcwallet.cpp [hunk 3]
```diff
@@ -2298,6 +2298,14 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
     // Alternately, find a way to make request.params[0] mlock()'d to begin with.
     strWalletPass = request.params[0].get_str().c_str();
 
+    // Get the timeout
+    int nSleepTime = request.params[1].get_int();
+    // Timeout cannot be negative, otherwise it will relock immediately
+    if (nSleepTime < 0) {
+        throw JSONRPCError(RPC_INVALID_PARAMETER, "Timeout cannot be negative.");
+    }
+    pwallet->nRelockTime = GetTime() + nSleepTime;
```
Comment (luke-jr) [inline src/wallet/rpcwallet.cpp]: Still need to check the passphrase etc first... otherwise we've essentially tricked the wallet into lengthening its unlock time.

File: src/wallet/rpcwallet.cpp [hunk 4]
```diff
@@ -2298,6 +2298,13 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
     // Alternately, find a way to make request.params[0] mlock()'d to begin with.
     strWalletPass = request.params[0].get_str().c_str();
 
+    // Get the timeout
+    int nSleepTime = request.params[1].get_int();
+    // Timeout cannot be negative, otherwise it will relock immediately
+    if (nSleepTime < 0) {
```
Comment (luke-jr) [inline src/wallet/rpcwallet.cpp]: Do we want to allow zero?

File: test/functional/wallet-encryption.py [hunk 5]
```diff
@@ -56,6 +56,11 @@ def run_test(self):
         assert_raises_rpc_error(-14, "wallet passphrase entered was incorrect", self.nodes[0].walletpassphrase, passphrase, 10)
         self.nodes[0].walletpassphrase(passphrase2, 10)
         assert_equal(privkey, self.nodes[0].dumpprivkey(address))
+        self.nodes[0].walletlock()
+
+        # Test timeout bounds
+        assert_raises_rpc_error(-8, "Timeout cannot be negative.", self.nodes[0].walletpassphrase, passphrase, -10)
+        assert_raises_rpc_error(-1, "JSON integer out of range", self.nodes[0].walletpassphrase, passphrase, 2147483648)
```
Comment (luke-jr) [inline test/functional/wallet-encryption.py]: 2147483648 is not guaranteed to be out of range.

File: src/wallet/rpcwallet.cpp (hunk 3 above)
Comment (luke-jr) [reply src/wallet/rpcwallet.cpp]: Displaying the wrong time is kind of a problem, although maybe not a security one.

File: src/wallet/rpcwallet.cpp (hunk 4 above)
Comment (achow101) [reply src/wallet/rpcwallet.cpp]: What would be the point of allowing 0?

Comment (luke-jr) [reply src/wallet/rpcwallet.cpp]: Perhaps to just test if the passphrase is correct. (You're *currently* allowing zero here.)

Comment (achow101) [reply src/wallet/rpcwallet.cpp]: > (You're currently allowing zero here.)

Right.

It doesn't matter either way IMO.

File: test/functional/wallet-encryption.py (hunk 5 above)
Comment (achow101) [reply test/functional/wallet-encryption.py]: How can you guarantee that a number will be out of range?

**Comment by sipa** [comment]
I'd feel more comfortable using int64, but add a clamp (if value is over 100 years, set it to 100 years or so).

File: src/wallet/rpcwallet.cpp (hunk 4 above)
Comment (bolekC) [reply src/wallet/rpcwallet.cpp]: Accepting 2147483647 (years long timeout) does not make too much sense in the time of Meltdown and Spectre vulnerabilities.
Anyway having timeout on the level of single days can be too long for these type of attacks.

**Review by bolekC — COMMENTED** [review]
From user experience point of view when we have "seconds" defined timeout I would expect times maybe up to 1 day. Giving big number does not make sense.

If it is intended to allow days then the timeout should be specified in "days" and not "seconds".

Look at the usability aspect. Anyway I don't have a clue how it is used today in real life.

**Comment by gmaxwell** [comment]
> Giving big number does not make sense.

Yes it does.  A common and recommended configuration on a system with an online wallet which would otherwise not be encrypted is to encrypt and then manually unlock any time the system is restarted.  If we did not allow a setting which was effectively 'until restart' these systems would simply not use encryption.

This configuration saved localbitcoins loss of almost all their funds after a datacenter operator was social engineered, just as a single example.

> If it is intended to allow days then the timeout should be specified in "days" and not "seconds".

Different applications have different scales.  More ordinary CLI user usage typical timeouts are just a few seconds or a few minutes.

> What would be the point of allowing 0?

To trigger a keypool topup. (though I didn't look to see if that would be guaranteed to work, but we should make it do so by performing the topup on unlock while still holding the lock)

> I'd feel more comfortable using int64, but add a clamp (if value is over 100 years, set it to 100 years or so).

That sounds fine, in particular we don't want people who have been happily using 999999999 to find it suddenly returning an error.

**Comment by achow101** [comment]
I have changed this to clamp at 2^31 seconds so the wallet will lock for up to 2^31 seconds which is approximately 68 years. This number was chosen because the `time_t` type that is used for the timer can be a 32 bit signed integer on some systems so this will avoid sign flipping with such systems.

File: src/wallet/rpcwallet.cpp [hunk 6]
```diff
@@ -2298,6 +2298,17 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
     // Alternately, find a way to make request.params[0] mlock()'d to begin with.
     strWalletPass = request.params[0].get_str().c_str();
 
+    // Get the timeout
+    int64_t nSleepTime = request.params[1].get_int64();
```
Comment (bolekC) [inline src/wallet/rpcwallet.cpp]: What was the root cause of  the behaviour described in #12100?
Is it not this line that is causing this strange behaviour?

Comment (achow101) [reply src/wallet/rpcwallet.cpp]: The root cause is that the int64 can have a higher value than what `time_t` can store. This gets around that problem by making `nSleepTime` at most a specific value that is known to be one that `time_t` can store.

**Comment by achow101** [comment]
I don't know why travis is failing.

**Comment by bolekC** [comment]
Maybe add a limit to "help" printout? 
2272:`            "2. timeout            (numeric, required) The time to keep the decryption key in seconds.\n"`

**Comment by bolekC** [comment]
It looks like Travis test fails on 32bit architecture. There is something wrong as you get a lot of messages like:
`JSONRPCException: Error: Please enter the wallet passphrase with walletpassphrase first.`
I don't know yet why you get it yet.

Also you can see that in the log printout there is a wrong value:
`node1 2018-01-08 18:52:07.849526 queue run of timer lockwallet(wallet.dat) in -2147483648 seconds (using HTTP) `
The number is -2147483648 is 1L<<31 on 32bit architecture.
This faulty printout is probably caused by LogPrint string formatting in RPCRunLater:
`LogPrint(BCLog::RPC, "queue run of timer %s in %i seconds (using %s)\n", name, nSeconds, timerInterface->Name());`

**Comment by achow101** [comment]
@bolekC Added some info about the limit to the help output.

I think I fixed the travis error. It has to do with the type of the value being shifted. The log output is correct.

File: test/functional/wallet-encryption.py [hunk 7]
```diff
@@ -56,6 +56,21 @@ def run_test(self):
...
+        self.nodes[0].walletlock()
+
+        # Test timeout bounds
+        assert_raises_rpc_error(-8, "Timeout cannot be negative.", self.nodes[0].walletpassphrase, passphrase2, -10)
+        # Check the timeout
+        # Check a time less than the limit
+        expected_time = int(time.time()) + (1 << 31) - 600
+        self.nodes[0].walletpassphrase(passphrase2, (1 << 31) - 600)
+        actual_time = self.nodes[0].getwalletinfo()['unlocked_until']
+        assert actual_time < expected_time + 5 and actual_time >= expected_time # 5 second buffer
```
Comment (jimpo) [inline test/functional/wallet-encryption.py]: nit: Python allows [chained comparisons](https://docs.python.org/3/reference/expressions.html#comparisons): `expected_time <= actual_time < expected_time + 5`

Comment (achow101) [reply test/functional/wallet-encryption.py]: Done

File: test/functional/wallet-encryption.py [hunk 8]
```diff
@@ -56,6 +56,21 @@ def run_test(self):
...
+        self.nodes[0].walletlock()
+
+        # Test timeout bounds
+        assert_raises_rpc_error(-8, "Timeout cannot be negative.", self.nodes[0].walletpassphrase, passphrase2, -10)
+        # Check the timeout
+        # Check a time less than the limit
+        expected_time = int(time.time()) + (1 << 31) - 600
+        self.nodes[0].walletpassphrase(passphrase2, (1 << 31) - 600)
+        actual_time = self.nodes[0].getwalletinfo()['unlocked_until']
+        assert expected_time <= actual_time < expected_time + 5 # 5 second buffer
```
Comment (MarcoFalke) [inline test/functional/wallet-encryption.py]: Might want to use the provided `assert_greater...` helper methods to give a more verbose output in case of failure.

Current error shows only:

```
File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet-encryption.py", line 68, in run_test
    assert expected_time <= actual_time < expected_time + 5 # 5 second buffer
AssertionError
```

and not by how much it was off.

Comment (achow101) [reply test/functional/wallet-encryption.py]: Done.

**Comment by achow101** [comment]
I changed the clamp to be at 2^31 - 1 seconds. Hopefully that fixes the travis problem with 32-bit linux.

File: src/wallet/rpcwallet.cpp [hunk 9]
```diff
@@ -2298,6 +2298,17 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
...
+    // Timeout cannot be negative, otherwise it will relock immediately
+    if (nSleepTime < 0) {
+        throw JSONRPCError(RPC_INVALID_PARAMETER, "Timeout cannot be negative.");
+    }
+    // Clamp timeout to 2^31 seconds
+    if (nSleepTime > ((int64_t)1 << 31) - 1) {
+        nSleepTime = ((int64_t)1 << 31) - 1;
```
Comment (MarcoFalke) [inline src/wallet/rpcwallet.cpp]: You could use the named constexpr `std::numeric_limits<int32_t>::max()`.

Also, how does that take into account your observation that "the time_t type that is used for the timer can be a 32 bit signed integer on some systems". (Considering that nSleepTime is multiplied by 1000 somewhere down in the call stack)

Comment (achow101) [reply src/wallet/rpcwallet.cpp]: > You could use the named constexpr `std::numeric_limits<int32_t>::max()`.

I'll try that now.

> Also, how does that take into account your observation that "the time_t type that is used for the timer can be a 32 bit signed integer on some systems". (Considering that nSleepTime is multiplied by 1000 somewhere down in the call stack)

It's multiplied by 1000 and then divided by 1000 before going into the `time_t`.

Comment (MarcoFalke) [reply src/wallet/rpcwallet.cpp]: Ah, ok. But since nSleepTime represents a delta, that is added onto `GetTime()`, capping it at the max of int32_t is not enough?

Comment (achow101) [reply src/wallet/rpcwallet.cpp]: The timer itself uses the delta. The only thing that's added is `wallet->nRelockTime` which is only used for display in `getwalletinfo`.

**Comment by laanwj** [comment]
utACK, agree that clamping is marginally better in this specific case, as there is no standardized way to specify "forever" and unlocking for 68 years might was well be forever.

File: src/wallet/rpcwallet.cpp [hunk 10]
```diff
@@ -2269,7 +2269,7 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
             "This is needed prior to performing transactions related to private keys such as sending bitcoins\n"
             "\nArguments:\n"
             "1. \"passphrase\"     (string, required) The wallet passphrase\n"
-            "2. timeout            (numeric, required) The time to keep the decryption key in seconds.\n"
+            "2. timeout            (numeric, required) The time to keep the decryption key in seconds. Limited to at most 2147483647 (2^31 - 1) seconds.\n"
```
Comment (laanwj) [inline src/wallet/rpcwallet.cpp]: The claming semantics need to be in the documentation.

Comment (achow101) [reply src/wallet/rpcwallet.cpp]: Done.

**Comment by bolekC** [comment]
Maybe you can add some more observability from C++ code to debug.log 
It can help to find what is wrong with tests on 32bit.

It looks like you get similar fault as original one but only on 32 bits now. From the log you can see that actual_time is 0. This is taken from pwallet->nRelockTime. So if it is 0 then the wallet is locked. 

I don't see how this can happen. It might be some other fault related to the timers handling? 

I've tested a bit on the official release and I have found that the on 64bits it works fine for
9223372036854775 and lower timeout values
and fails for 
9223372036854776 and bigger timeout values (than again it works and fails in a cyclic way but I'have not found yet the cycle amplitude... maybe tomorrow but it is on the level of 2^53).

The point is that 9223372036854776 is nothing special when it comes to binary representation. This suggests that fault might be somewhere else.

**Comment by achow101** [comment]
@bolekC It has nothing to do with the 64 bit integer but rather overflowing on a 32-bit integer. Actually, this could be a problem related to single precision floats. I'm not sure, so I added debugging output so we can see what is wrong on travis.

**Comment by achow101** [comment]
This travis error continues to confuse me. It does not appear to be a sign issue in the `timeval` struct, yet the wallet is still locking immediately.

**Comment by achow101** [comment]
I got fed up with debugging this thing and just lowered the clamp to 2^30 seconds. I believe that should work and ~34 years is still long enough.

**Comment by MarcoFalke** [comment]
Please adjust the OP, since that ends up in the commit body of the merge commit.

**Comment by achow101** [comment]
@MarcoFalke adjusted

**Comment by achow101** [comment]
> I still think we don't understand the fault's root cause very well.

That's correct. I have no clue why it is failing, although I believe it has to do with floating point numbers. I'm pretty sure the issue has to do with the `timeval` struct, in particular `tv.tv_sec`'s type of `time_t`.

> I suspect QTimer implementation but I have not succeeded to troubleshoot it yet.

We don't use QTimers. Rather it uses `libevent`, so the issue lies in their implementation AFAICT.

**Comment by bolekC** [comment]
Sure it's `libevent`. I've mixed it up. There must be something wrong somewhere :)

**Comment by laanwj** [comment]
> We don't use QTimers. Rather it uses libevent, so the issue lies in their implementation AFAICT.

In the most common case, yes. IIRC it does use QTimers when -server is false in the GUI: in that case libevent isn't initialized. Multiple timer implementations can be registered through `RPCSetTimerInterface`.

**Comment by laanwj** [comment]
Not sure why I didn't think of this sooner: but another thing we can do instead of clamping the time when larger than a certain value, is to not use a timer at all in that case - interpret large numbers as 'infinite', unlocking forever (or until manually re-locked).

This avoids having to cope with timer edge-case behavior entirely.

File: src/wallet/rpcwallet.cpp [hunk 11]
```diff
@@ -2298,6 +2299,17 @@ UniValue walletpassphrase(const JSONRPCRequest& request)
...
     strWalletPass = request.params[0].get_str().c_str();
 
+    // Get the timeout
+    int64_t nSleepTime = request.params[1].get_int64();
+    // Timeout cannot be negative, otherwise it will relock immediately
+    if (nSleepTime < 0) {
+        throw JSONRPCError(RPC_INVALID_PARAMETER, "Timeout cannot be negative.");
+    }
+    // Clamp timeout to 2^30 seconds
+    if (nSleepTime > (int64_t)1 << 30) {
```
Comment (ryanofsky) [inline src/wallet/rpcwallet.cpp]: Could just write 1L instead of casting 1.

**Review by ryanofsky — COMMENTED** [review]
utACK 134cdc7cee3da7c554e40ad947a9cdcbb3069f13

**Comment by ryanofsky** [comment]
> clamping doesn't work very well on every platform

Where are you seeing this? It seems like current implementation should work on every platform. Agree that laanwj's suggestion would make code a little cleaner, but the behavior for all practical purposes would seem identical to what is implemented here.

Also, regardless of anything, current PR seems like an improvement over status the quo.

**Comment by MarcoFalke** [comment]
> Where are you seeing this?

The "magic value" was determined by "ok, `std::numeric_limits<int32_t>::max()` doesn't work, so let's go a bit lower and try again". See

> I got fed up with debugging this thing and just lowered the clamp to 2^30 seconds

> Also, regardless of anything, current PR seems like an improvement over status the quo.

Agree.

File: src/wallet/rpcwallet.cpp (hunk 11 above)
Comment (achow101) [reply src/wallet/rpcwallet.cpp]: I was having some problems with using 1L on 32 bit systems so explicitly casting it like this seemed to be better.

**Comment by MarcoFalke** [comment]
utACK 134cdc7cee3da7c554e40ad947a9cdcbb3069f13

**Comment by achow101** [comment]
> clamping doesn't work very well on every platform

We would still need some magic value where all of the values less than it are valid timeouts. Using `std::numeric_limits<int32_t>::max()` as the cutoff magic value for an infinite timeout would still be problematic as using certain values less than that would still result in invalid timeouts. Changing it from clamping to "infinite timeout cutoff" doesn't resolve that problem.

**Comment by ryanofsky** [comment]
I think the suggestion is to simply not call RPCRunLater if there is an infinite timeout.

**Comment by bolekC** [comment]
Just to remind that **we don't know the root cause** of this behaviour. Suspected is `libevent` library.

Described behaviour is that with big number wallet gets locked immediately so probably timeout is fired right after the command to set timer is given. I have observed also that sometimes this is few seconds delayed if bitcoind is heavily occupied with some tasks. This suggests event handling. 

Find a root cause to have 100% safe solution. I have not debugged it to this level yet (lack of time)

**Comment by ajtowns** [comment]
`0 <= nSleepTime <= 1,073,741,824` in wallet/rpcwallet.cpp is an int64_t, measured in seconds

`pwallet->nRelockTime = GetTime()+nSleepTime` in wallet/rpcwallet.cpp is an int64_t, so will only overflow when GetTime() returns `2**30*(2**33-1)` which is about 292 million millenia away, and it's only used for printing in any event.

`nSleepTime` gets passed to RPCRunLater which multiplies it by 1000 to convert to milliseconds and passes it to RPCTimerInterface::NewTimer as an int64_t. `0 <= 1000*nSleepTime <= 1,073,741,824,000`, which fits in about 40 bits, so still doesn't overflow.

RPCTimerInterface::NewTimer can be either QtRPCTimerInterface (using QTimers) or HTTPRPCTimerInterface (using libevent).

QtRPCTimerInterface passes the millisecond value to QTimer::start(), which in Qt5 accepts a std::chrono::milliseconds which is specced to be at least 45 bits, so is fine. In Qt4.8 it's specced as an int, and if int maxes out at 2**31-1 will overflow if nSleepTime is 2147484 or above, which is about 24 days.

HTTPRPCTimerInterface makes an HTTPRPCTimer, which populates a timeval with `millis/1000` and `(millis%1000)*1000`. The latter should be fine, the former will overflow if time_t maxes out at `2**31-1` and millis is at least `2**31*1000`, ie `nSleepTime >= 2**31` which is already forbidden. The timeval is then passed to libevent's `evtimer_add()`, and libevent then turns the time into an absolute value using `timeradd()` from `<sys/time.h>` which will overflow if the final time overflows time_t, ie the Y2038 bug. This will happen if nSleepTime is greater than about 631,300,000 which is about `2**(29.2)`, decreasing every second as 2038 gets closer.

Trying on Debian/i386, I can confirm that libevent gets an event with a negative timeout in that scenario, which I would expect to behave badle. I can't actually get the event to trigger, however, so I'm not sure if this can be made to cause the wallet to actually be re-locked early. (Checking it's re-locked at the correct time doesn't seem worthwhile, since time_t will have wrapped by then, and who knows what will have broken...)

So if this needs to be improved further, maybe a check along the lines of `nRelockTime < std::numeric_limits<time_t>::max()` could be added.

But as is, I agree this makes things better than the status-quo, so ACK 134cdc7cee3da7c554e40ad947a9cdcbb3069f13 .

**Comment by ajtowns** [comment]
Okay, retrying with the limit being `2**31-1`, I get a libevent timeout at time `-631,298,485` which then gets handled immediately, causing the wallet to be relocked. I don't know why libevent handles that timeout immediately, but appears happy to leave a timeout corresponding to `-2**32` or just after Y2038 pending indefinitely.

**Comment by laanwj** [comment]
> Also, regardless of anything, current PR seems like an improvement over status the quo.

OK, I agree. I was just a bit wary of setting a timer that we assume will never trigger at all, might as well not set it, but indeed this improves on the issue. Can be improved later.
utACK 134cdc7

**Comment by Sjors** [comment]
This change seems to break `wallet_encryption.py` on MacOS, see #12375 by @AkioNak.
