### PR TITLE
rpc: Avoid getchaintxstats invalid results

### LINKED ISSUE #29328: assumeutxo: nTx and nChainTx in RPC results are off
AssumeUtxo mocks the `nTx` value of headers after the last background block and before the snapshot header with `nTx=1`. This means that the `getblockheader` and `getchaintxstats` RPCs return the wrong `nTx` or `txcount` fields for those blocks.

Not sure if anything should be done about this?

### PR DESCRIPTION
**Pull request by maflcko**
The `getchaintxstats` RPC reply during AU background download may return non-zero, but invalid, values for `window_tx_count` and `txrate`.

For example, `txcount` may be zero for a to-be-downloaded block, but may be non-zero for an ancestor block which is already downloaded. Thus, the values returned may be negative (and cause intermediate integer sanitizer violations).

Also, `txcount` may be accurate for the snapshot base block, or a descendant of it. However it may be zero for an ancestor block that still needs to be downloaded. Thus, the values returned may be positive, but wrong.

Fix all issues by skipping the returned value if either `txcount` is unset (equal to zero).
Also, skip `txcount` in the returned value, if it is unset (equal to zero).

Fixes https://github.com/bitcoin/bitcoin/issues/29328

### CODE REVIEW

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -1637,9 +1637,13 @@ static RPCHelpMan getchaintxstats()
                         {RPCResult::Type::STR_HEX, "window_final_block_hash", "The hash of the final block in the window"},
                         {RPCResult::Type::NUM, "window_final_block_height", "The height of the final block in the window."},
                         {RPCResult::Type::NUM, "window_block_count", "Size of the window in number of blocks"},
-                        {RPCResult::Type::NUM, "window_tx_count", /*optional=*/true, "The number of transactions in the window. Only returned if \"window_block_count\" is > 0"},
+                        {RPCResult::Type::NUM, "window_tx_count", /*optional=*/true,
+                         "The number of transactions in the window. "
+                         "Only returned if \"window_block_count\" is > 0 and if txcount is non-zero for the start end end of the window."},
```
Comment (luke-jr) [inline src/rpc/blockchain.cpp:1642]: This is confusing. We know why txcount would be zero, but users might not. Perhaps txcount itself should be omitted when wrong?

**Comment by fjahr** [comment]
Concept ACK, could we add a test for this?

File: src/rpc/blockchain.cpp [hunk 2]
```diff
@@ -1633,13 +1633,19 @@ static RPCHelpMan getchaintxstats()
                     RPCResult::Type::OBJ, "", "",
                     {
                         {RPCResult::Type::NUM_TIME, "time", "The timestamp for the final block in the window, expressed in " + UNIX_EPOCH_TIME},
-                        {RPCResult::Type::NUM, "txcount", "The total number of transactions in the chain up to that point"},
+                        {RPCResult::Type::NUM, "txcount", /*optional=*/true,
```
Comment (fjahr) [inline src/rpc/blockchain.cpp:1636]: Not returning a value here might break downstream projects if they are unlucky since this wasn't optional before. Not sure if deprecation is necessary here but a more safe approach could be to just return 0 if it is unknown. I don't have a strong opinion on it but usually, we are pretty cautious with a change like this.

Comment (fjahr) [reply src/rpc/blockchain.cpp:1636]: Yeah, changing the return value wouldn't be much of a concern, but a missing key has higher potential to crash something.

> When evaluating whether this is a breaking change, I don't think it can affect any downstream projects, because Assume-Utxo is an incomplete, experimental, regtest-only feature. 

(*testnet/regtest-only) I'm pretty much with you here but [others might not be](https://github.com/bitcoin/bitcoin/pull/29612#pullrequestreview-1974818797) though the utxo set dump might also be used in a different context. Feel free to leave the approach as is, I am fine with it.

Comment (Sjors) [reply src/rpc/blockchain.cpp:1636]: We're breaking the format anyway with #29612 so might as well introduce other breaking changes now.

File: src/rpc/blockchain.cpp [hunk 3]
```diff
@@ -1633,13 +1633,19 @@ static RPCHelpMan getchaintxstats()
...
+                         "The total number of transactions in the chain up to that point, if known. "
+                         "It may be unknown when using Assume-Utxo."},
                         {RPCResult::Type::STR_HEX, "window_final_block_hash", "The hash of the final block in the window"},
                         {RPCResult::Type::NUM, "window_final_block_height", "The height of the final block in the window."},
                         {RPCResult::Type::NUM, "window_block_count", "Size of the window in number of blocks"},
-                        {RPCResult::Type::NUM, "window_tx_count", /*optional=*/true, "The number of transactions in the window. Only returned if \"window_block_count\" is > 0"},
+                        {RPCResult::Type::NUM, "window_tx_count", /*optional=*/true,
+                         "The number of transactions in the window. "
+                         "Only returned if \"window_block_count\" is > 0 and if txcount exists for the start end end of the window."},
```
Comment (Sjors) [inline src/rpc/blockchain.cpp:1644]: The window can contain the snapshot height? So then it should really check that _all_ recount values exist.

File: src/rpc/blockchain.cpp [hunk 4]
```diff
@@ -1680,19 +1686,25 @@ static RPCHelpMan getchaintxstats()
...
     if (blockcount > 0) {
-        ret.pushKV("window_tx_count", nTxDiff);
+        if (window_tx_count) {
+            ret.pushKV("window_tx_count", *window_tx_count);
+        }
         ret.pushKV("window_interval", nTimeDiff);
-        if (nTimeDiff > 0) {
-            ret.pushKV("txrate", ((double)nTxDiff) / nTimeDiff);
+        if (nTimeDiff > 0 && window_tx_count) {
+            ret.pushKV("txrate", double(*window_tx_count) / nTimeDiff);
```
Comment (Sjors) [inline src/rpc/blockchain.cpp:1707]:
```
rpc/blockchain.cpp: In function ‘getchaintxstats()::<lambda(const RPCHelpMan&, const JSONRPCRequest&)>’:
rpc/blockchain.cpp:1707:34: warning: ‘*(std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>*)((char*)&window_tx_count + offsetof(const std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>)).std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>::_M_value’ may be used uninitialized [-Wmaybe-uninitialized]
 1707 |             ret.pushKV("txrate", double(*window_tx_count) / nTimeDiff);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~
rpc/blockchain.cpp:1689:16: note: ‘*(std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>*)((char*)&window_tx_count + offsetof(const std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>)).std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>::_M_value’ was declared here
 1689 |     const auto window_tx_count{
      |                ^~~~~~~~~~~~~~~
```

Ubuntu 23.10 with gcc 13.2.0

Which seems spurious, but it goes away with e.g.:

```cpp
    if (blockcount > 0) {
        if (window_tx_count) {
            ret.pushKV("window_tx_count", *window_tx_count);
            if (nTimeDiff > 0) {
                ret.pushKV("txrate", double(*window_tx_count) / nTimeDiff);
            }
        }
        ret.pushKV("window_interval", nTimeDiff);
    }
```

File: src/rpc/blockchain.cpp (hunk 2 above)
Comment (Sjors) [reply src/rpc/blockchain.cpp:1636]: Both are listed as critical for mainnet release in #29616. If one needs a breaking change, it's fine for the other to also make one.

File: src/rpc/blockchain.cpp (hunk 3 above)
Comment (Sjors) [reply src/rpc/blockchain.cpp:1644]: Let's say we have blocks [1,2,3,4,5,6,7,8,9] and block 6 is the snapshot. The background sync just processed block 3, foreground sync is past 9. You ask for the window 1 - 7. In that case `nChainTx` for (1) and (7) are set, but's not set for (4) and (5).

However as you say, this not a problem when subtracting `nChainTx` of block (1) from `nChainTx` of block (7).

File: src/rpc/blockchain.cpp (hunk 4 above)
Comment (Sjors) [reply src/rpc/blockchain.cpp:1707]: > Not sure about changing the code for a broken compiler warning. 

It's also slightly more readable because it checks `window_tx_count` only once.

> I am sure this warning already exists in other parts of the code

This is the only warning thrown.

File: src/rpc/blockchain.cpp (hunk 3 above)
Comment (Sjors) [reply src/rpc/blockchain.cpp:1644]: Yes, it's fine.

**Review by fjahr — COMMENTED** [review]
tACK fa28613a2cc75e5668900a11337e441546f86358

I have written some additional coverage to test the behavior and build my understanding, it could be added here or I can make a follow-up: https://github.com/fjahr/bitcoin/commit/03a0f31dde51c094ad8e3df9f5d72abfe216c981

File: src/rpc/blockchain.cpp [hunk 5]
```diff
@@ -1680,19 +1686,25 @@ static RPCHelpMan getchaintxstats()
...
+    if (pindex->nChainTx) {
+        ret.pushKV("txcount", pindex->nChainTx);
+    }
     ret.pushKV("window_final_block_hash", pindex->GetBlockHash().GetHex());
     ret.pushKV("window_final_block_height", pindex->nHeight);
     ret.pushKV("window_block_count", blockcount);
     if (blockcount > 0) {
-        ret.pushKV("window_tx_count", nTxDiff);
+        if (window_tx_count) {
+            ret.pushKV("window_tx_count", *window_tx_count);
```
[the remark this answers is not in the document]
Comment (fjahr) [reply src/rpc/blockchain.cpp:1704]: Yeah, the explicit check makes it safe. I would just always prefer the safer method and I find it more expressive. But no big deal.

**Comment by fjahr** [comment]
re-ACK fa737100af538f7257e55d88fe1f24246bcce7fc

> I think assert_equal can generally not be used on floating point values, no?

Here is a version with `assert_approx`: https://github.com/fjahr/bitcoin/commit/24e9a37fb502092048206967dfc792d6af126316

**Comment by fjahr** [comment]
re-ACK ef692e52b4121ba3d8de91e45b2d33aff946e8d2

Also reviewed https://github.com/bitcoin/bitcoin/pull/30144 to confirm the failure is ok.

**Comment by fjahr** [comment]
re-ACK 2342b46c451658a418f8e28e50b2ad0e5abd284d

Confirmed only changes were rebase and typo-fix, per `git range-diff master ef692e52b4121ba3d8de91e45b2d33aff946e8d2 2342b46c451658a418f8e28e50b2ad0e5abd284d`.

**Review by mzumsande — COMMENTED** [review]
ACK 2342b46c451658a418f8e28e50b2ad0e5abd284d

I reviewed the code and tested the getchaintxstats output with a snapshot.

**Comment by achow101** [comment]
ACK 2342b46c451658a418f8e28e50b2ad0e5abd284d

**Comment by hebasto** [comment]
This PR introduced a new `-Wmaybe-uninitialized` warning when building with GCC < 13:
- GCC 11:
```
  CXX      rpc/libbitcoin_node_a-blockchain.o
rpc/blockchain.cpp: In function ‘getchaintxstats()::<lambda(const RPCHelpMan&, const JSONRPCRequest&)>’:
rpc/blockchain.cpp:1742:38: warning: ‘*(std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>*)((char*)&window_tx_count + offsetof(const std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>)).std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>::_M_value’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1742 |                 ret.pushKV("txrate", double(*window_tx_count) / nTimeDiff);
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~
```
- GCC 12:
```
  CXX      rpc/libbitcoin_node_a-blockchain.o
rpc/blockchain.cpp: In function ‘getchaintxstats()::<lambda(const RPCHelpMan&, const JSONRPCRequest&)>’:
rpc/blockchain.cpp:1742:38: warning: ‘*(std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>*)((char*)&window_tx_count + offsetof(const std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>)).std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>::_M_value’ may be used uninitialized [-Wmaybe-uninitialized]
 1742 |                 ret.pushKV("txrate", double(*window_tx_count) / nTimeDiff);
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~
rpc/blockchain.cpp:1725:16: note: ‘*(std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>*)((char*)&window_tx_count + offsetof(const std::optional<unsigned int>,std::optional<unsigned int>::<unnamed>.std::_Optional_base<unsigned int, true, true>::<unnamed>)).std::_Optional_payload_base<unsigned int>::_Storage<unsigned int, true>::_M_value’ was declared here
 1725 |     const auto window_tx_count{
      |                ^~~~~~~~~~~~~~~
```
