### PR TITLE
init: Configure reachable networks before we start the RPC server

### LINKED ISSUE #32433: "rpcallowip=" configuration directive doesn't accept RFC4193 addresses
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

I have a local dual-stack network using RFC1918 addresses on IPv4 stack and RFC4193 addresses on IPv6 stack. I would like to restrict the access to RPC ports of Bitcoin Core nodes running in the network based on the source address of the connections. However, Bitcoin Core 29.0 doesn't accept `rpcallowip=` directives that specify addresses under the `[fc00::/7]` IP block.

### Expected behaviour

Bitcoin Core should accept addresses under the `[fc00::/7]` IP block defined via `rpcallowip=` directives, and perform access control according to the list of network blocks specified via configuration or command line.

### Steps to reproduce

Run the command line specified below on a CentOS Stream 9 machine connected to the internet.

```
$ curl --no-progress-meter -L 'https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz' | tar zx && mkdir -p data && ./bitcoin-29.0/bin/bitcoind '-rpcbind=[::]:8332' '-rpcallowip=fc00:db8:c0:ff:ee::/80'
```

### Relevant log output

```
[admin@centos9-stream-a ~]$ curl --no-progress-meter -L 'https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz' | tar zx && mkdir -p data && ./bitcoin-29.0/bin/bitcoind '-rpcbind=[::]:8332' '-rpcallowip=fc00:db8:c0:ff:ee::/80'
2025-05-07T07:10:45Z Bitcoin Core version v29.0.0 (release build)
2025-05-07T07:10:45Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2025-05-07T07:10:45Z Using RdSeed as an additional entropy source
2025-05-07T07:10:45Z Using RdRand as an additional entropy source
2025-05-07T07:10:45Z Default data directory /home/admin/.bitcoin
2025-05-07T07:10:45Z Using data directory /home/admin/.bitcoin
2025-05-07T07:10:45Z Config file: /home/admin/.bitcoin/bitcoin.conf (not found, skipping)
2025-05-07T07:10:45Z Command-line arg: rpcallowip="fc00:db8:c0:ff:ee::/80"
2025-05-07T07:10:45Z Command-line arg: rpcbind="[::]:8332"
2025-05-07T07:10:45Z Using at most 125 automatic connections (1024 file descriptors available)
2025-05-07T07:10:45Z scheduler thread start
2025-05-07T07:10:45Z [error] Invalid -rpcallowip subnet specification: fc00:db8:c0:ff:ee::/80. Valid are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
Error: Invalid -rpcallowip subnet specification: fc00:db8:c0:ff:ee::/80. Valid are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
2025-05-07T07:10:45Z [error] Unable to start HTTP server. See debug log for details.
Error: Unable to start HTTP server. See debug log for details.
2025-05-07T07:10:45Z Shutdown: In progress...
2025-05-07T07:10:45Z scheduler thread exit
2025-05-07T07:10:45Z Shutdown: done
```

--

RFC3849 addresses are accepted:

```
[admin@centos9-stream-a ~]$ curl --no-progress-meter -L 'https://bitcoincore.org/bin/bitcoin-core-29.0/bitcoin-29.0-x86_64-linux-gnu.tar.gz' | tar zx && mkdir -p data && ./bitcoin-29.0/bin/bitcoind '-rpcbind=[::]:8332' '-rpcallowip=2001:db8:c0:ff:ee::/80'
2025-05-07T07:11:56Z Bitcoin Core version v29.0.0 (release build)
2025-05-07T07:11:56Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2025-05-07T07:11:56Z Using RdSeed as an additional entropy source
2025-05-07T07:11:56Z Using RdRand as an additional entropy source
2025-05-07T07:11:56Z Default data directory /home/admin/.bitcoin
2025-05-07T07:11:56Z Using data directory /home/admin/.bitcoin
2025-05-07T07:11:56Z Config file: /home/admin/.bitcoin/bitcoin.conf (not found, skipping)
2025-05-07T07:11:56Z Command-line arg: rpcallowip="2001:db8:c0:ff:ee::/80"
2025-05-07T07:11:56Z Command-line arg: rpcbind="[::]:8332"
2025-05-07T07:11:56Z Using at most 125 automatic connections (1024 file descriptors available)
2025-05-07T07:11:56Z scheduler thread start
2025-05-07T07:11:56Z Binding RPC on address :: port 8332
2025-05-07T07:11:56Z WARNING: the RPC server is not safe to expose to untrusted networks such as the public internet
2025-05-07T07:11:56Z Generated RPC authentication cookie /home/admin/.bitcoin/.cookie
2025-05-07T07:11:56Z Permissions used for cookie: rw-------
2025-05-07T07:11:56Z Using random cookie authentication.
2025-05-07T07:11:56Z Starting HTTP server with 16 worker threads
2025-05-07T07:11:56Z Using wallet directory /home/admin/.bitcoin/wallets
2025-05-07T07:11:56Z init message: Verifying wallet(s)…
2025-05-07T07:11:56Z Using /16 prefix for IP bucketing
2025-05-07T07:11:56Z init message: Loading P2P addresses…
2025-05-07T07:11:56Z Creating peers.dat because the file was not found ("/home/admin/.bitcoin/peers.dat")
2025-05-07T07:11:56Z init message: Loading banlist…
2025-05-07T07:11:56Z Recreating the banlist database
2025-05-07T07:11:56Z SetNetworkActive: true
2025-05-07T07:11:56Z /home/admin/.bitcoin/fee_estimates.dat is not found. Continue anyway.

^C
```

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

Bitcoin Core daemon version v29.0.0

### Operating system and version

CentOS Stream release 9

### Machine specifications

QEMU/KVM virtual machine

### PR DESCRIPTION
**Pull request by pinheadmz**
Closes https://github.com/bitcoin/bitcoin/issues/32433

`MaybeFlipIPv6toCJDNS()` relies on `g_reachable_nets` to distinguish between CJDNS addresses and other IPv6 addresses. In particular, [RFC4193](https://www.rfc-editor.org/rfc/rfc4193#section-3.1) address or "Unique Local Address" with the L-bit unset also begins with the `fc` prefix. #32433 highlights a use case for these addresses that have nothing to do with CJDNS.

On master we don't parse init flags like `-cjdnsreachable` until *after* the HTTP server has started, causing conflicts with `-rpcallowip` because CJDNS doesn't support subnets.

This PR ensures that `NET_CJDNS` is only present in the reachable networks list if set by `-cjdnsreachable` *before* `-rpcallowip` is checked. If it is set all `fc` addresses are assumed to be CJDNS, can not have subnets, and can't be set for `-rpcallowip`.

I also noted this specific parameter interaction in the init help as well as the error message if configured incorrectly.

This can be tested locally:

`bitcoind -regtest -rpcallowip=fc00:dead:beef::/64 -rpcuser=u -rpcpassword=p`

On master this will just throw an error that doesn't even mention IPv6 at all.

On the branch, this will succeed and can be tested by adding the ULA to a local interface.

On linux: `sudo ip -6 addr add fc00:dead:beef::1/64 dev lo`

On macos: `sudo ifconfig lo0 inet6 fc00:dead:beef::1/128 add`

then: `curl -v -g -6 --interface fc00:dead:beef::1 u:p@[::1]:18443 --data '{"method":"getblockcount"}'`

If the `rpcallowip` option is removed, the RPC request will fail to authorize.

Finally, adding `-cjdnsreachable` to the start up command will throw an error and specify the incompatibility:

> RFC4193 is allowed only if -cjdnsreachable=0.

### CODE REVIEW

File: src/httpserver.cpp [hunk 1]
```diff
@@ -227,7 +227,7 @@ static bool InitHTTPAllowList()
         const CSubNet subnet{LookupSubNet(strAllow)};
         if (!subnet.IsValid()) {
             uiInterface.ThreadSafeMessageBox(
-                Untranslated(strprintf("Invalid -rpcallowip subnet specification: %s. Valid are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).", strAllow)),
+                Untranslated(strprintf("Invalid -rpcallowip subnet specification: %s. Valid values are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0), a network/CIDR (e.g. 1.2.3.4/24), all ipv4 (0.0.0.0/0), or all ipv6 (::/0). RFC4193 is allowed only if -cjdnsreachable=0.", strAllow)),
```
Comment (tapcrafter) [inline src/httpserver.cpp:230]: I'm aware brevity is probably prioritized here. But I didn't recognize RFC4193 just from its number, so had to look it up. What about "RFC4193 style IPv6 ULA addresses are only allowed..."?

**Review by tapcrafter — COMMENTED** [review]
tACK 12ff4be9c724c752fe67835419be3ff4d0e65990

<details>

<summary>Test protocol</summary>

## Current error message on master (7710a31f0cb69a04529f39840196826d0b9770ab):

```
$ bitcoind -regtest -rpcallowip=fc00:dead:beef::/64 -rpcuser=u -rpcpassword=p

2025-05-17T16:24:29Z Command-line arg: regtest=""
2025-05-17T16:24:29Z Command-line arg: rpcallowip="fc00:dead:beef::/64"
2025-05-17T16:24:29Z Command-line arg: rpcpassword=****
2025-05-17T16:24:29Z Command-line arg: rpcuser=****
...
2025-05-17T16:24:29Z [error] Invalid -rpcallowip subnet specification: fc00:cafe:babe::/64. Valid are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
Error: Invalid -rpcallowip subnet specification: fc00:dead:beef::/64. Valid are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24).
2025-05-17T16:24:29Z [error] Unable to start HTTP server. See debug log for details.
Error: Unable to start HTTP server. See debug log for details.
```


## Output on 12ff4be9c724c752fe67835419be3ff4d0e65990

```
$ bitcoind -regtest -rpcallowip=fc00:dead:beef::/64 -rpcbind=fc00:dead:beef::1 -cjdnsreachable -onlynet=cjdns -rpcuser=u -rpcpassword=p

2025-05-17T16:33:57Z Command-line arg: cjdnsreachable=""
2025-05-17T16:33:57Z Command-line arg: onlynet="cjdns"
2025-05-17T16:33:57Z Command-line arg: regtest=""
2025-05-17T16:33:57Z Command-line arg: rpcallowip="fc00:dead:beef::/64"
2025-05-17T16:33:57Z Command-line arg: rpcbind="fc00:dead:beef::1"
2025-05-17T16:33:57Z Command-line arg: rpcpassword=****
2025-05-17T16:33:57Z Command-line arg: rpcuser=****
...
2025-05-17T16:33:57Z [error] Invalid -rpcallowip subnet specification: fc00:dead:beef::/64. Valid values are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0), a network/CIDR (e.g. 1.2.3.4/24), all ipv4 (0.0.0.0/0), or all ipv6 (::/0). RFC4193 is allowed only if -cjdnsreachable=0.
Error: Invalid -rpcallowip subnet specification: fc00:dead:beef::/64. Valid values are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0), a network/CIDR (e.g. 1.2.3.4/24), all ipv4 (0.0.0.0/0), or all ipv6 (::/0). RFC4193 is allowed only if -cjdnsreachable=0.
```

Removing the `-rpcallowip` flag does then result in the request being denied as expected:

```shell
$ curl -v -g -6 --interface fc00:dead:beef::1 'u:p@[::1]:18443' --data '{"method":"getblockcount"}'

...
HTTP/1.1 403 Forbidden
...
```

## Using a non-RFC4193 local address

Starting `bitcoind` with a `fd00` local address works without issue:

```shell
$ bitcoind -regtest -rpcallowip=fd00:dead:beef::/64 -rpcbind=fd00:dead:beef::1234 -cjdnsreachable -onlynet=cjdns -rpcuser=u -rpcpassword=p

$ curl -v -g -6 --interface fd00:dead:beef::1234 'u:p@[fd00:dead:beef::1234]:18443' --data '{"method":"getblockcount"}'

...
HTTP/1.1 200 OK
...
</details>

**Review by ryanofsky — APPROVED** [review]
Code review ACK 12ff4be9c724c752fe67835419be3ff4d0e65990

Did not look closely how the RPC binding code works, but the only code change here is moving g_reachable_nets initialization earlier in the InitAppMain function, which makes sense and is safe. There is also a new test and documentation.

Since the g_reachable_nets code has to move anyway, it could be make sense to move it into an `InitReachableNets(args)` or similar helper function so `AppInitMain` could be simpler. But not important, and maybe having a single function is better.

**Review by willcl-ark — APPROVED** [review]
ACK 12ff4be9c724c752fe67835419be3ff4d0e65990

Tested the new behaviour manually and using the new test, checked the moved code block with `--color-moved=dimmed-zebra`.

**Comment by jonatack** [comment]
Concept ACK, will review

**Comment by achow101** [comment]
ACK 12ff4be9c724c752fe67835419be3ff4d0e65990
