### PR TITLE
depends: remove Darwin ENV unsetting

### LINKED ISSUE #21552: ci: ccache does not work for macOS cross-compiling builds
https://cirrus-ci.com/task/6268895175639040?logs=ci#L3869:
```
ccache version 3.7.7
cache directory                     /tmp/ccache_dir
primary config                      /tmp/ccache_dir/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats updated                       Tue Mar 30 01:48:58 2021
stats zeroed                        Tue Mar 30 01:21:25 2021
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
called for link                       10
multiple source files                636
cleanups performed                     0
files in cache                         0
cache size                           0.0 kB
max cache size                     200.0 MB
```

UPD 2023-08-25. See https://github.com/ccache/ccache/issues/1326.

### PR DESCRIPTION
**Pull request by fanquake**
Now that we use the native compiler, and have fixed Qt, and these vars
are (almost) unset in Guix, we can remove the unsetting from our compiler
command here.

I couldn't manage to make a darwin-clang-cross only exclusion of `-lm` work properly
for Qt, so opted for just removing the explicit link entirely. I do not think this should have
any other unwanted side-effects.

Fixes #21552.

### CODE REVIEW

**Comment by hebasto** [comment]
Concept ACK.

**Comment by theuni** [comment]
Whoa, this greatly simplifies things. When/why where these removed in guix? I thought they were pretty fundamental there.

I wonder if we should check for the use of these in depends and bail out if they're set though.

**Comment by fanquake** [comment]
> When/why where these removed in guix? I thought they were pretty fundamental there.

I've added some more cleanup here. We can't remove them entirely (for Darwin) in Guix, because we still need some set during depends, for QT/qmake... However, we can unset them after that, for the main build.

**Comment by fanquake** [comment]
Assuming that #29723 lands first, the commit here adding a patch for librt will be dropped, as that is also patched out of the CMake side in that PR.

**Comment by fanquake** [comment]
Dropped the (autotools) zeromq commit and rebased on top of #29723.

**Comment by fanquake** [comment]
Guix build (aarch64):
```bash
5447a6b0ed155318747354b9db7972716ba5a5c45c956ca39e979c380fe7b25c  guix-build-298c8192a71e/output/arm64-apple-darwin/SHA256SUMS.part
9bc5df1ade9d2a8d9c469ffcbc72ff064c57658474a028270fbeeb4fafb7cff4  guix-build-298c8192a71e/output/arm64-apple-darwin/bitcoin-298c8192a71e-arm64-apple-darwin-unsigned.tar.gz
7aa774a9731f69379ae994a60c7fef3e33d07ebcb5f70b0cc0224e0640f638e2  guix-build-298c8192a71e/output/arm64-apple-darwin/bitcoin-298c8192a71e-arm64-apple-darwin-unsigned.zip
5e0be95ea55819731fad709dbbf75345fbac4de9e764baa40111d225fca2ecf7  guix-build-298c8192a71e/output/arm64-apple-darwin/bitcoin-298c8192a71e-arm64-apple-darwin.tar.gz
d7df88817fcc48b0eb80cdc04cd399f34629f4d15c29535a676a0eb8ebe47d9d  guix-build-298c8192a71e/output/dist-archive/bitcoin-298c8192a71e.tar.gz
a6c604fcb17443886aa710884767d824a9ebf6f99a2da1ba11124fbe0c379b1c  guix-build-298c8192a71e/output/x86_64-apple-darwin/SHA256SUMS.part
2cad928bd4ad6998707a667980ce609c52ef77793415ddf04d9f210a01a3c9fa  guix-build-298c8192a71e/output/x86_64-apple-darwin/bitcoin-298c8192a71e-x86_64-apple-darwin-unsigned.tar.gz
bf41537390da432fd5e72428f41de96ba31862aa00773522fb9879d780e27e25  guix-build-298c8192a71e/output/x86_64-apple-darwin/bitcoin-298c8192a71e-x86_64-apple-darwin-unsigned.zip
7e869a3790854c00518c194b04c75189036b9661eeaa2f8a0797da25c3c7c073  guix-build-298c8192a71e/output/x86_64-apple-darwin/bitcoin-298c8192a71e-x86_64-apple-darwin.tar.gz
```

File: contrib/guix/libexec/build.sh [hunk 1]
```diff
@@ -69,13 +69,22 @@ unset CPLUS_INCLUDE_PATH
...
+case "$HOST" in
+    *darwin*)
+        # Required for qt/qmake
+        export C_INCLUDE_PATH="${NATIVE_GCC}/include"
+        export CPLUS_INCLUDE_PATH="${NATIVE_GCC}/include/c++:${NATIVE_GCC}/include"
+        ;;
+    *)
+        export C_INCLUDE_PATH="${NATIVE_GCC}/include"
+        export CPLUS_INCLUDE_PATH="${NATIVE_GCC}/include/c++:${NATIVE_GCC}/include"
+        export OBJC_INCLUDE_PATH="${NATIVE_GCC}/include"
```
Comment (TheCharlatan) [inline contrib/guix/libexec/build.sh:81]: If I am reading this right, this sets OBJC vars for non-darwin hosts. Is that intended? I would have expected the opposite.

Comment (fanquake) [reply contrib/guix/libexec/build.sh:81]: Heh, yea. These should/would only be needed for macOS, and only for Qt-related code. I guess everything still currently builds even with them unset, because when we compile our objc++ code, we would never be looking in any GCC related include/std-lib/related dirs in any case? Will push some changes.

**Review by sedited — COMMENTED** [review]
Guix build (aarch64):
```
e54a5bec288e01beccb7329fe623269decbac58c8fca182005660e2e0eab9937  guix-build-bda537f7c484/output/aarch64-linux-gnu/SHA256SUMS.part
c4121cc8b7367a3fa16667fce7fae752f243e502e82786be1a4defa512b807fc  guix-build-bda537f7c484/output/aarch64-linux-gnu/bitcoin-bda537f7c484-aarch64-linux-gnu-debug.tar.gz
f6d64868fb78b9667fa486052ab2ade488caad03df577aa1cc4d79fa542c48ae  guix-build-bda537f7c484/output/aarch64-linux-gnu/bitcoin-bda537f7c484-aarch64-linux-gnu.tar.gz
451ff70d68b6925e467dfe3ae69351004f4bfb4973d45ae8f49cd2928f795c4c  guix-build-bda537f7c484/output/arm-linux-gnueabihf/SHA256SUMS.part
869f32187db9fb59f600147c57a166dcc53b78fa5297a750ae416cb01cfce8f0  guix-build-bda537f7c484/output/arm-linux-gnueabihf/bitcoin-bda537f7c484-arm-linux-gnueabihf-debug.tar.gz
61efedeaae40a022d3cb48a4389adbfa1ec1982c1165615effec2e1523d75263  guix-build-bda537f7c484/output/arm-linux-gnueabihf/bitcoin-bda537f7c484-arm-linux-gnueabihf.tar.gz
e3f6d6e8e998bf7e0dae5bfa3b8479091bad2ce87615ee8de16130c6300665cc  guix-build-bda537f7c484/output/arm64-apple-darwin/SHA256SUMS.part
04ff93a466e8c875c88c57a9d31aece2443cf3f06768f5d87a56235a2c7e46cc  guix-build-bda537f7c484/output/arm64-apple-darwin/bitcoin-bda537f7c484-arm64-apple-darwin-unsigned.tar.gz
97f31359809acefcdd71750f93ee821c57834ba04015659f7641509046a95ae2  guix-build-bda537f7c484/output/arm64-apple-darwin/bitcoin-bda537f7c484-arm64-apple-darwin-unsigned.zip
dcdb54e3a62720f67cede2359cb88c6e5b496727b8e33c7fcf61679436b86c6e  guix-build-bda537f7c484/output/arm64-apple-darwin/bitcoin-bda537f7c484-arm64-apple-darwin.tar.gz
d2dbfd4d2e22f9b5155b6488773ead04bb8a4e2e087761122a6e08b4ae0ea006  guix-build-bda537f7c484/output/dist-archive/bitcoin-bda537f7c484.tar.gz
bfb792e4ebaf1b7d42a9f4040e751a5417b79acec24dacc364f2a042b6b19788  guix-build-bda537f7c484/output/powerpc64-linux-gnu/SHA256SUMS.part
30df3def1db919437ab1a54d283170d6a728e5199e3e9c8ee73871645c91b628  guix-build-bda537f7c484/output/powerpc64-linux-gnu/bitcoin-bda537f7c484-powerpc64-linux-gnu-debug.tar.gz
184bb34be85a50fa0f6137e17c57fc7c33c37ce10e06d067c24f45bdc49e50e3  guix-build-bda537f7c484/output/powerpc64-linux-gnu/bitcoin-bda537f7c484-powerpc64-linux-gnu.tar.gz
1f92d6f9f9de4bf44b7e1a2a74cdcab20f71297f3271613a55b9ef36924901a9  guix-build-bda537f7c484/output/riscv64-linux-gnu/SHA256SUMS.part
953506894362070665e16744d5676fa9530e3e58c3d06bbcfe4af77035bf96c9  guix-build-bda537f7c484/output/riscv64-linux-gnu/bitcoin-bda537f7c484-riscv64-linux-gnu-debug.tar.gz
63a47f60fe7fec1d2a8403a7891b349b4ffd7a2c91af57426ea4ace14dab1ca5  guix-build-bda537f7c484/output/riscv64-linux-gnu/bitcoin-bda537f7c484-riscv64-linux-gnu.tar.gz
35ca4b44a0f1d633b7a715a13d3447bade13e4405cb10aa6314a4f0f93a10cd8  guix-build-bda537f7c484/output/x86_64-apple-darwin/SHA256SUMS.part
ae9719518493ef8b411613c973cb37ecc7b21117e84e8695407f01ec948cff90  guix-build-bda537f7c484/output/x86_64-apple-darwin/bitcoin-bda537f7c484-x86_64-apple-darwin-unsigned.tar.gz
114a95bf0de85371236c1cd5769e78861396243cdfa75baad2f87572f168e358  guix-build-bda537f7c484/output/x86_64-apple-darwin/bitcoin-bda537f7c484-x86_64-apple-darwin-unsigned.zip
bc57a7676f8bfe4bdb48be5e9a5d29833db65580cbcf66fe91f145e4a3d6cd47  guix-build-bda537f7c484/output/x86_64-apple-darwin/bitcoin-bda537f7c484-x86_64-apple-darwin.tar.gz
e3597c886089cc37feee7b5683c8062b52d9629288b940c8dbdbda6ca432541c  guix-build-bda537f7c484/output/x86_64-linux-gnu/SHA256SUMS.part
8b7285eb11ec0df84142ec00aa8b9708baa7a69ef9077c6ec5bb9095db7b83b6  guix-build-bda537f7c484/output/x86_64-linux-gnu/bitcoin-bda537f7c484-x86_64-linux-gnu-debug.tar.gz
eabd4a583dcf08d5712d9853dfc34da3ae9b34e66daa3bea1e919eec8d079459  guix-build-bda537f7c484/output/x86_64-linux-gnu/bitcoin-bda537f7c484-x86_64-linux-gnu.tar.gz
1197b6e04c25512f037cf0467aa08db595f78f0e19f539216ac9a1ece38af1c6  guix-build-bda537f7c484/output/x86_64-w64-mingw32/SHA256SUMS.part
70845f68e1f4444a5b0ae78d829a5cb2add8d808989942ee28aae52d36ff5ae0  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64-debug.zip
9756e593fc216a12a4adfb3bff4147f44c3f5e73979348176843463095b612ab  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64-setup-unsigned.exe
f0d8fbce1c4ecc80d65c0d174d49e305b8098ac1b074dcafec8d14e61ba7f859  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64-unsigned.tar.gz
8083b1b4772045331bcf1a9b50676622e639fccf04f16156264a66e006b60905  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64.zip
```

**Comment by hebasto** [comment]
My Guix build:
```
x86_64
e54a5bec288e01beccb7329fe623269decbac58c8fca182005660e2e0eab9937  guix-build-bda537f7c484/output/aarch64-linux-gnu/SHA256SUMS.part
c4121cc8b7367a3fa16667fce7fae752f243e502e82786be1a4defa512b807fc  guix-build-bda537f7c484/output/aarch64-linux-gnu/bitcoin-bda537f7c484-aarch64-linux-gnu-debug.tar.gz
f6d64868fb78b9667fa486052ab2ade488caad03df577aa1cc4d79fa542c48ae  guix-build-bda537f7c484/output/aarch64-linux-gnu/bitcoin-bda537f7c484-aarch64-linux-gnu.tar.gz
451ff70d68b6925e467dfe3ae69351004f4bfb4973d45ae8f49cd2928f795c4c  guix-build-bda537f7c484/output/arm-linux-gnueabihf/SHA256SUMS.part
869f32187db9fb59f600147c57a166dcc53b78fa5297a750ae416cb01cfce8f0  guix-build-bda537f7c484/output/arm-linux-gnueabihf/bitcoin-bda537f7c484-arm-linux-gnueabihf-debug.tar.gz
61efedeaae40a022d3cb48a4389adbfa1ec1982c1165615effec2e1523d75263  guix-build-bda537f7c484/output/arm-linux-gnueabihf/bitcoin-bda537f7c484-arm-linux-gnueabihf.tar.gz
e3f6d6e8e998bf7e0dae5bfa3b8479091bad2ce87615ee8de16130c6300665cc  guix-build-bda537f7c484/output/arm64-apple-darwin/SHA256SUMS.part
04ff93a466e8c875c88c57a9d31aece2443cf3f06768f5d87a56235a2c7e46cc  guix-build-bda537f7c484/output/arm64-apple-darwin/bitcoin-bda537f7c484-arm64-apple-darwin-unsigned.tar.gz
97f31359809acefcdd71750f93ee821c57834ba04015659f7641509046a95ae2  guix-build-bda537f7c484/output/arm64-apple-darwin/bitcoin-bda537f7c484-arm64-apple-darwin-unsigned.zip
dcdb54e3a62720f67cede2359cb88c6e5b496727b8e33c7fcf61679436b86c6e  guix-build-bda537f7c484/output/arm64-apple-darwin/bitcoin-bda537f7c484-arm64-apple-darwin.tar.gz
d2dbfd4d2e22f9b5155b6488773ead04bb8a4e2e087761122a6e08b4ae0ea006  guix-build-bda537f7c484/output/dist-archive/bitcoin-bda537f7c484.tar.gz
bfb792e4ebaf1b7d42a9f4040e751a5417b79acec24dacc364f2a042b6b19788  guix-build-bda537f7c484/output/powerpc64-linux-gnu/SHA256SUMS.part
30df3def1db919437ab1a54d283170d6a728e5199e3e9c8ee73871645c91b628  guix-build-bda537f7c484/output/powerpc64-linux-gnu/bitcoin-bda537f7c484-powerpc64-linux-gnu-debug.tar.gz
184bb34be85a50fa0f6137e17c57fc7c33c37ce10e06d067c24f45bdc49e50e3  guix-build-bda537f7c484/output/powerpc64-linux-gnu/bitcoin-bda537f7c484-powerpc64-linux-gnu.tar.gz
1f92d6f9f9de4bf44b7e1a2a74cdcab20f71297f3271613a55b9ef36924901a9  guix-build-bda537f7c484/output/riscv64-linux-gnu/SHA256SUMS.part
953506894362070665e16744d5676fa9530e3e58c3d06bbcfe4af77035bf96c9  guix-build-bda537f7c484/output/riscv64-linux-gnu/bitcoin-bda537f7c484-riscv64-linux-gnu-debug.tar.gz
63a47f60fe7fec1d2a8403a7891b349b4ffd7a2c91af57426ea4ace14dab1ca5  guix-build-bda537f7c484/output/riscv64-linux-gnu/bitcoin-bda537f7c484-riscv64-linux-gnu.tar.gz
35ca4b44a0f1d633b7a715a13d3447bade13e4405cb10aa6314a4f0f93a10cd8  guix-build-bda537f7c484/output/x86_64-apple-darwin/SHA256SUMS.part
ae9719518493ef8b411613c973cb37ecc7b21117e84e8695407f01ec948cff90  guix-build-bda537f7c484/output/x86_64-apple-darwin/bitcoin-bda537f7c484-x86_64-apple-darwin-unsigned.tar.gz
114a95bf0de85371236c1cd5769e78861396243cdfa75baad2f87572f168e358  guix-build-bda537f7c484/output/x86_64-apple-darwin/bitcoin-bda537f7c484-x86_64-apple-darwin-unsigned.zip
bc57a7676f8bfe4bdb48be5e9a5d29833db65580cbcf66fe91f145e4a3d6cd47  guix-build-bda537f7c484/output/x86_64-apple-darwin/bitcoin-bda537f7c484-x86_64-apple-darwin.tar.gz
e3597c886089cc37feee7b5683c8062b52d9629288b940c8dbdbda6ca432541c  guix-build-bda537f7c484/output/x86_64-linux-gnu/SHA256SUMS.part
8b7285eb11ec0df84142ec00aa8b9708baa7a69ef9077c6ec5bb9095db7b83b6  guix-build-bda537f7c484/output/x86_64-linux-gnu/bitcoin-bda537f7c484-x86_64-linux-gnu-debug.tar.gz
eabd4a583dcf08d5712d9853dfc34da3ae9b34e66daa3bea1e919eec8d079459  guix-build-bda537f7c484/output/x86_64-linux-gnu/bitcoin-bda537f7c484-x86_64-linux-gnu.tar.gz
1197b6e04c25512f037cf0467aa08db595f78f0e19f539216ac9a1ece38af1c6  guix-build-bda537f7c484/output/x86_64-w64-mingw32/SHA256SUMS.part
70845f68e1f4444a5b0ae78d829a5cb2add8d808989942ee28aae52d36ff5ae0  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64-debug.zip
9756e593fc216a12a4adfb3bff4147f44c3f5e73979348176843463095b612ab  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64-setup-unsigned.exe
f0d8fbce1c4ecc80d65c0d174d49e305b8098ac1b074dcafec8d14e61ba7f859  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64-unsigned.tar.gz
8083b1b4772045331bcf1a9b50676622e639fccf04f16156264a66e006b60905  guix-build-bda537f7c484/output/x86_64-w64-mingw32/bitcoin-bda537f7c484-win64.zip
```

**Review by sedited — APPROVED** [review]
ACK bda537f7c484d61a55a72c5856f2d4420664db8f

Tested the gui on macos 12.7.4
