### PR TITLE
multiprocess: Fix high overhead from message logging

### LINKED ISSUE #215: Substantial overhead caused by encoding messages for logging
I'm working on a multiprocess branch that passes a lot of data back and forth between server and client.

When looking at a flamegraph, it's clear that >50% of my client's cpu time is spent on logging (encoding) sends. Likewise for the server with responses.

The culprit is `toString()` from the `params`/`results`/`request`/`response`, which ends up in `kj::_::encodeCEscapeImpl()`, which is _horribly_ slow.

Current master:
Image
Fixed:
Image

As you can see, before removing the logging, 52% of my thread's runtime is spent in `serverInvoke` (which calls `foo.toString()`, which calls `structString()`, which calls `kj::_::encodeCEscapeImpl()`. With the debug lines removed, `serverInvoke` is no longer visible in the flamegraph at all.

I would imagine the sv2 implementation suffers from this as well, though I'm not sure how chatty it is, so I can't speak to the potential impact.

~I'll open a RFC PR which fixes the issue rather naively. A more robust solution would introduce logging categories similar to Bitcoin Core's.~

Edit: See https://github.com/bitcoin-core/libmultiprocess/pull/216.
Also, toned down the original title :)

### PR DESCRIPTION
**Pull request by theuni**
This fixes https://github.com/bitcoin-core/libmultiprocess/issues/215 on Core's side. ~It depends on https://github.com/bitcoin-core/libmultiprocess/pull/220 being merged upstream, and a PR to update our subtree. I've included a subtree merge from my repo here for now, but will rebase on top of the merge from upstream once it's in.~ Edit: Rebased on top of #33518.

For context: before https://github.com/bitcoin-core/libmultiprocess/pull/220, libmultiprocess serializesd every log message parameter, even if that message was ultimately going to be discarded. The upstream PR accomplished 2 main things:
- Creates logging categories, similar to Core's
- Using macros, avoids serializing parameters for disabled log levels.

That allowed the expensive serialization to be skipped, but the default log level is `Trace`. This PR updates our usage of libmultiprocess options to honor our log categories and levels.

Because of the substantial unnecessary overhead (see the [flamegraphs](https://github.com/bitcoin-core/libmultiprocess/issues/215). Logging accounts for 50% of my application's cpu time, and nearly 10% of bitcoin-node's, both of which go to ~0% once fixed), it'd be a shame to ship the first multiprocess binaries without this fixed. So I propose that we also backport this (and the required libmultiprocess subtree merge) ~to v30. Sorry about the timing~ :(

Edit: Didn't make it for v30, but it would still make sense to backport for a v30.1.

### CODE REVIEW

**Comment by sedited** [comment]
Concept ACK

**Comment by Raimo33** [comment]
Concept ACK

I agree with the backporting

File: src/ipc/capnp/protocol.cpp [hunk 1]
```diff
@@ -62,7 +62,10 @@ class CapnpProtocol : public Protocol
     {
         assert(!m_loop);
         mp::g_thread_context.thread_name = mp::ThreadName(exe_name);
-        m_loop.emplace(exe_name, &IpcLogFn, &m_context);
+        mp::LogOptions opts = {
```
Comment (ryanofsky) [inline src/ipc/capnp/protocol.cpp:91]: In commit "multiprocess: update multiprocess EventLoop construction to use options" (7c0015d543b4a6141520a02895342b4a316b60fe)

This is fine to keep if intentional, but could consider passing unnamed temporary like `mp::LogOptions{.log_fn = IpcLogFn}` to simply code and avoid need for std::move, and not keep an empty options object on the stack for the duration of the thread.

**Review by ryanofsky — APPROVED** [review]
Partial code review ACK d6167af132febba14bd0d86d7465aef490c58fea (just reviewed the Bitcoin code changes in last two commits, not the earlier libmultiprocess changes which will disappear when rebased), but this all looks good

**Comment by theuni** [comment]
Rebased on #33518 temporarily to make sure ci is happy with everything combined.

File: src/ipc/capnp/protocol.cpp (hunk 1 above)
Comment (theuni) [reply src/ipc/capnp/protocol.cpp:91]: I only did it this way because it's more readable to me that way, and because I figured there may be more logging options for us to use in the future that would make the in-place init more complicated.

Happy to change it if you feel strongly.

File: src/ipc/capnp/protocol.cpp [hunk 2]
```diff
@@ -30,10 +30,33 @@
...
+{
+    switch (level) {
+        case mp::Log::Trace: return BCLog::Level::Trace;
+        case mp::Log::Debug: return BCLog::Level::Debug;
+        case mp::Log::Info: return BCLog::Level::Info;
+        case mp::Log::Warning: return BCLog::Level::Warning;
+        case mp::Log::Error: return BCLog::Level::Error;
+        case mp::Log::Raise: return BCLog::Level::Error;
+    } // no default case, so the compiler can warn about missing cases
+    assert(false);
```
Comment (theuni) [inline src/ipc/capnp/protocol.cpp]: I'm torn about what to do here, so feedback welcome. Adding another value upstream at any point would cause a crash here. But because we don't know what that future value would be, we can't predict how we should react to it now.

Just commenting because this effectively freezes `mp::Log`, and would require adding new fields to `LogMessage` instead. I'm ok with that, but @ryanofsky might not be.

Comment (Sjors) [reply src/ipc/capnp/protocol.cpp]: In c3f700feb6f650a7ceb62714f2d8eb0d5f1cb2ae _multiprocess: align our logging with libmultiprocess's_:

Adding a level to `mp::Log` could be considered a breaking change, similar to changing a function signature in the `.capnp` file in a breaking way.

But we don't want to treat IPC clients as trusted (in the long run), so crashing doesn't seem right. Maybe instead disconnect and log at the error level?

**Review by Sjors — APPROVED** [review]
ACK c3f700feb6f650a7ceb62714f2d8eb0d5f1cb2ae

---

Not directly related to the changes here, but it's a bit odd that clean disconnects are logged at the `info` level (always visible) while new connections are logged at the `debug` level (requires `-debug=ipc`).

Disconnect:

```
2025-10-08T07:19:16Z [ipc:info] {bitcoin-node-57287/b-capnp-loop-6497836} IPC server destroy N2mp11ProxyServerIN3ipc5capnp8messages6MiningEEE
2025-10-08T07:19:16Z [ipc:info] {bitcoin-node-57287/b-capnp-loop-6497836} IPC server: socket disconnected.
2025-10-08T07:19:16Z [ipc:info] {bitcoin-node-57287/b-capnp-loop-6497836} IPC server destroy N2mp11ProxyServerIN3ipc5capnp8messages4InitEEE
```

Connect (`-debug=ipc`):

```
2025-10-08T07:19:44Z [ipc] {bitcoin-node-57788/b-capnp-loop-6502845} IPC server recv request  #1 Init.construct$Params
2025-10-08T07:19:44Z [ipc] {bitcoin-node-57788/b-capnp-loop-6502845} IPC server send response #1 Init.construct$Results
2025-10-08T07:19:44Z [ipc] {bitcoin-node-57788/b-capnp-loop-6502845} IPC server recv request  #2 Init.makeMining$Params
2025-10-08T07:19:44Z [ipc] {bitcoin-node-57788/b-capnp-loop-6502845} IPC server post request  #2 {bitcoin-node-57788/6502989 (from sv2-tp-57803/6502987)}
2025-10-08T07:19:44Z [ipc] {bitcoin-node-57788/b-capnp-loop-6502845} IPC server send response #2 Init.makeMining$Results
```

The former seems too chatty, the latter too quiet. Maybe only have the "socket disconnected" message be at the `info` level and introduce a "socket connected" message.

File: src/ipc/capnp/protocol.cpp (hunk 2 above)
Comment (theuni) [reply src/ipc/capnp/protocol.cpp]: Agreed about avoiding crashing.

I pushed a change that does something different than what you suggested though: assume an unknown log level should only be seen at our most verbose level, which is Trace.

I think that's ok, as it should cause a compilation warning (missed switch value), but otherwise not much change for the user. As it would be an API break that requires downstream attention, I think that's reasonable.

File: src/ipc/capnp/protocol.cpp (hunk 1 above)
Comment (ryanofsky) [reply src/ipc/capnp/protocol.cpp:91]: re: https://github.com/bitcoin/bitcoin/pull/33517#discussion_r2410969953

Yeah just a tradeoff between having extra variables and having an extra level a nesting. I think having more variables is worse, but no strong opinion and you should follow your preference

File: src/ipc/capnp/protocol.cpp (hunk 2 above)
Comment (ryanofsky) [reply src/ipc/capnp/protocol.cpp]: re: https://github.com/bitcoin/bitcoin/pull/33517#discussion_r2414400956

Not important, but FWIW sjors suggestion makes a little more sense to me to I don't see sending unknown log messages to the trace stream, which is effectively a black hole, as being more conservative. IMO ideal thing to do would be to return `std::optional` and `nullopt` and then log unknown messages at debug level with a prefix like "[unrecognized flags "0x%08x]".

**Review by ryanofsky — APPROVED** [review]
Code review ACK dcaf4b736f9ddfc6a2695ce19221a7f383e43e20. Just rebased onto #33518 and changed assert(false) to log trace and since last review

re: https://github.com/bitcoin/bitcoin/pull/33517#pullrequestreview-3313376282

> The former seems too chatty, the latter too quiet.

Good observations, created https://github.com/bitcoin-core/libmultiprocess/issues/227 to track this

File: src/ipc/capnp/protocol.cpp (hunk 2 above)
Comment (theuni) [reply src/ipc/capnp/protocol.cpp]: By "more conservative", I meant from a Core logging DOS pov.

If libmp ever added a super-duper-verbose mode, imo the safer thing to do would be to black-hole those messages rather than fill the log with them. Sure that would hide issues, but it would also prevent accidental blowups. I don't see that as likely at all, just thinking defensively by default.

I could imagine sending a single "Unrecognized log level specified" warning, but that doesn't really seem worth the complexity for a theoretical/unlikely future issue.

**Comment by fanquake** [comment]
#33518 has gone in, so this could be rebased / undrafted.

**Comment by Sjors** [comment]
CI doesn't look happy. Update: seems fine again.

**Comment by Sjors** [comment]
ACK 0626b90f507db68610a69feec86deb712dd095a1

**Review by sedited — APPROVED** [review]
ACK 0626b90f507db68610a69feec86deb712dd095a1

**Review by sipa — COMMENTED** [review]
utACK 0626b90f507db68610a69feec86deb712dd095a1

**Comment by fanquake** [comment]
Backported to `30.x` in #33609.

**Comment by ryanofsky** [comment]
Just to follow up, I think it was unclear if this change was compatible with the [logging RPC](https://github.com/bitcoin/bitcoin/blob/7d27af98c7cf858b5ab5a02e64f89a857cc53172/src/rpc/node.cpp#L215) that allows log levels to be changed at runtime.

I think it actually is compatible because the current RPC method only allows enabling/disabling categories without adjusting levels. If a way to adjust log levels is added though, a special case like the one added for [libevent](https://github.com/bitcoin/bitcoin/blob/7d27af98c7cf858b5ab5a02e64f89a857cc53172/src/rpc/node.cpp#L259-L262) might need to be added for libmultiprocess as well.

**Comment by theuni** [comment]
Agreed. Thanks for having a look.
