### PR TITLE
script: actually trigger the optimization in BuildScript

### LINKED ISSUE #25682: Redundant code or latent bug
Looking at the code below I can't understand how it is possible for the IF statement conditional expression to become true. cnt is already incremented before the IF statement. Is this not redundant? https://github.com/bitcoin/bitcoin/blob/master/src/script/script.h#L594

I have opened a ticket, https://stackoverflow.com/questions/73088518/reduntant-code-possibly-in-bitcoin-script-h

**Expected behavior**
Possibly doesn't change the behavior. 
 

Not Applicable
**Actual behavior**

**To reproduce**

It is source code issue

**System information**
Not applicable 

Main branch ..https://github.com/bitcoin/bitcoin

Not Applicable

Not Applicable

### PR DESCRIPTION
**Pull request by darosior**
The counter is an optimization over calling `ret.empty()`. It was
suggested that the compiler would realize `cnt` is only `0` on the first
iteration, and not actually emit the check and conditional.

This optimization was actually not triggered at all, since we
incremented `cnt` at the beginning of the first iteration. Fix it by
incrementing at the end instead.

This was reported by Github user "Janus".

Fixes #25682. Note this does *not* change semantics. It only allows the optimization of moving instead of copying on first `CScript` element to actually be reachable.

### CODE REVIEW

File: src/script/script.h [hunk 1]
```diff
@@ -600,6 +599,7 @@ CScript BuildScript(Ts&&... inputs)
             // Otherwise invoke CScript::operator<<.
             ret << input;
         }
+        cnt++;
```
Comment (luke-jr) [inline src/script/script.h:602]:
```suggestion
        ++cnt;
```

**Comment by sipa** [comment]
utACK 00897d0677c2cb6609b90d52b89907c8b50d6de0

**Comment by MarcoFalke** [comment]
review ACK 00897d0677c2cb6609b90d52b89907c8b50d6de0

File: src/script/script.h (hunk 1 above)
Comment (fanquake) [reply src/script/script.h:602]: @darosior did you want to address this comment?

Comment (darosior) [reply src/script/script.h:602]: I was not planning to unless anyone felt strongly otherwise, as it's really a nit..

Comment (jonatack) [reply src/script/script.h:602]: If you're interested (for now or later), in addition to https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#coding-style-c there is further rationale in https://lefticus.gitbooks.io/cpp-best-practices/content/08-Considering_Performance.html#prefer-i-to-i.

Comment (MarcoFalke) [reply src/script/script.h:602]: I haven't yet seen an iterator type where this isn't optimized to the same assembly. Though, if we want this, it might be better enforced with a tidy check than with review comments that invalidate review

Comment (jonatack) [reply src/script/script.h:602]: If we don't want this, it should be removed from the developer notes.

Comment (MarcoFalke) [reply src/script/script.h:602]: Agree. See also https://github.com/bitcoin/bitcoin/pull/24846#issuecomment-1098774606

Comment (sipa) [reply src/script/script.h:602]: Choosing `++v;` over `v++;` is generally good advice if you don't want to go into details, but in practically it really matters for performance in case `v` is a non-trivial, big, type. In this case where it's just an integer it won't make to any difference in the resulting binary code with any compiler created the past 20 years.
