### PR TITLE
 Block ActivateBestChain to empty validationinterface queue

### LINKED ISSUE #11822: Severe memory leak on current master
Sometime during normal operation, my node crashed (possibly due to this issue, but I do not know) and I had to perform a reindex. During this reindex, I noticed that it was consuming upwards of 26 GB of memory and constantly consuming more. Unfortunately this caused my computer to lock up and I had to reboot it to fix that. Starting Core again resulted in a reindex and the same behavior again.

I am using a build of the current master branch on commit 00d25e90db06149fa456b0a8f15b7b68005ff9c5

Machine info:
Ubuntu 17.10
32 GB RAM

I was going to run it in valgrind but it was taking too long to get anywhere remotely past initialization to the part where the memory leak was happening, so I killed that.

Now I am doing `git bisect` to find where the leak was introduced. AFAIK this leak is not present in 0.15.1.

I believe that @sipa experienced the same issue on his odroid but was not able to reproduce the problem.

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This should fix #11822.

It ended up bigger than I hoped for, but its not too gnarly. Note that "
Require no cs_main lock for ProcessNewBlock/ActivateBestChain" is mostly pure code-movement.

### CODE REVIEW

File: src/validation.cpp [hunk 1]
```diff
@@ -2467,12 +2468,23 @@ bool ActivateBestChain(CValidationState &state, const CChainParams& chainparams,
...
     // sanely for performance or correctness!
+    AssertLockNotHeld(cs_main);
 
     CBlockIndex *pindexMostWork = nullptr;
     CBlockIndex *pindexNewTip = nullptr;
     int nStopAtHeight = gArgs.GetArg("-stopatheight", DEFAULT_STOPATHEIGHT);
     do {
         boost::this_thread::interruption_point();
+
+        if (GetMainSignals().CallbacksPending() > 10) {
```
Comment (dcousens) [inline src/validation.cpp]: Should this parameterized? Or at least a configurable constant?
Is there any advantage to tweaking it?

Comment (TheBlueMatt) [reply src/validation.cpp]: During normal (read: non-IBD/reindex) usage, this should virtually never reach 10. During IBD/reindex, your memory is probably better speint in more dbcache than storing blocks you recently connected to eventually give to your wallet. I dont think more knobs is helpful here.

File: src/net_processing.cpp [hunk 2]
```diff
@@ -1032,170 +1040,183 @@ static void RelayAddress(const CAddress& addr, bool fReachable, CConnman* connma
...
-    while (it != pfrom->vRecvGetData.end()) {
-        // Don't bother if send buffer is too full to respond anyway
-        if (pfrom->fPauseSend)
-            break;
+    {
+        LOCK(cs_main);
 
-        const CInv &inv = *it;
-        {
+        while (it != pfrom->vRecvGetData.end() && (it->type == MSG_TX || it->type == MSG_WITNESS_TX)) {
```
Comment (achow101) [inline src/net_processing.cpp]: It seems to me that this expects to see transactions first and then blocks. But can't a `getdata` message have the types in any order?

**Review by achow101 — COMMENTED** [review]
ACK-ish

This definitely is fixing the problem I was seeing, although I have one question below.

File: src/net_processing.cpp (hunk 2 above)
Comment (TheBlueMatt) [reply src/net_processing.cpp]: No, we are allowed to (in fact always have) not finish the full queue before returning, and we do for blocks (always did). A peer shouldn't be able to make us spin giving them 100 blocks before processing any other peers' requests.

**Comment by achow101** [comment]
tACK 3113573c847c76943c065b72d3e7a9edc643fed1

File: src/net_processing.cpp (hunk 2 above)
Comment (achow101) [reply src/net_processing.cpp]: Ok, I see now. I didn't see the break for when the type was a block.

**Review by dcousens — APPROVED** [review]
once-over ACK

**Comment by jamesob** [comment]
tACK https://github.com/bitcoin/bitcoin/pull/11824/commits/3113573c847c76943c065b72d3e7a9edc643fed1

I've been running `-reindex` for over twelve hours and haven't seen an OOM:
```
job@ali:~$ sudo egrep "Kill.*bitcoind" /var/log/syslog || echo "cool"
cool
```

**Comment by jamesob** [comment]
Just hit another OOM, but also realized I was on an outdated version of this branch (HEAD was `151b17da1 Block ActivateBestChain to empty validationinterface queue`). @TheBlueMatt do you recall what changed between `151b17da1` and current HEAD and if it would explain the difference between another OOM or not?

In any case, I'm pulling down the tip of this branch and starting another -reindex.

**Comment by TheBlueMatt** [comment]
@jamesob No, the only differences there were in test_bitcoin.cpp, so that should have had no affect.

**Comment by achow101** [comment]
I haven't seen any OOMs and my node is almost fully reindexed. Granted it did go down sometime last night as it ran out of disk space. It's been running for ~6 hours now and was running for ~14 hours before then.

**Comment by TheBlueMatt** [comment]
Well this definitely fixes *a* bug...just did a reindex to 150k with 0.15, 0.15.1 master and this branch, peak memory usage on this branch and 0.15 and 0.15.1 were all about the same, master was 3x higher...I'll look more into our memory footprint and see what else is hiding.

**Comment by jamesob** [comment]
tACK (again) https://github.com/bitcoin/bitcoin/pull/11824/commits/3113573c847c76943c065b72d3e7a9edc643fed1

Definitely hitting fewer OOMs reindexing on this branch than I was a week ago. :)

**Comment by jamesob** [comment]
My bitcoind process has been running for 37 hours on this branch; memory usage has held steady through and after a partial reindex.

**Comment by TheBlueMatt** [comment]
Rebased.

**Comment by TheBlueMatt** [comment]
Rebased.

**Comment by jonasschnelli** [comment]
Haven't looked at the code, but can confirm that a -reindex OOM/leak issue (#11822) was fixed once I merged in that PR.

File: src/wallet/test/wallet_tests.cpp [hunk 3]
```diff
@@ -627,10 +627,17 @@ class ListCoinsTestingSetup : public TestChain100Setup
...
         CValidationState state;
         BOOST_CHECK(wallet->CommitTransaction(wtx, reservekey, nullptr, state));
+        CMutableTransaction blocktx;
+        {
+        LOCK(wallet->cs_wallet);
+        auto it = wallet->mapWallet.find(wtx.GetHash());
+        BOOST_CHECK(it != wallet->mapWallet.end());
+        blocktx = CMutableTransaction(*it->second.tx);
+        }
+        CreateAndProcessBlock({CMutableTransaction(blocktx)}, GetScriptForRawPubKey(coinbaseKey.GetPubKey()));
```
Comment (ryanofsky) [inline src/wallet/test/wallet_tests.cpp]: In commit "Require no cs_main lock for ProcessNewBlock/ActivateBestChain"

Maybe simplify this using mapWallet.at() instead of .find() and BOOST_CHECK.

File: src/validation.cpp (hunk 1 above)
Comment (ryanofsky) [reply src/validation.cpp]: https://github.com/bitcoin/bitcoin/pull/11824#discussion_r154814580

In commit "Block ActivateBestChain to empty validationinterface queue"

> During normal (read: non-IBD/reindex) usage, this should virtually never reach 10. During IBD/reindex, your memory is probably better speint in more dbcache than storing blocks you recently connected to eventually give to your wallet.

Please write this in a code comment. (How is anybody supposed to know this?)

File: src/validation.cpp [hunk 4]
```diff
@@ -2566,6 +2567,16 @@ bool CChainState::ActivateBestChain(CValidationState &state, const CChainParams&
...
+            // Block until the validation queue drains
+            std::promise<void> promise;
+            CallFunctionInValidationInterfaceQueue([&promise] {
+                promise.set_value();
+            });
+            promise.get_future().wait();
```
Comment (ryanofsky) [inline src/validation.cpp]: In commit "Block ActivateBestChain to empty validationinterface queue"

Could add a CValidationInterface::WaitForPendingCallbacks() method to wrap this up since this is also needed in other places.

**Review by ryanofsky — COMMENTED** [review]
utACK da8903142f807be9295797c0e65f228230ffd467. Locking changes look good, and nice to break up ProcessGetData.

File: src/wallet/test/wallet_tests.cpp (hunk 3 above)
Comment (TheBlueMatt) [reply src/wallet/test/wallet_tests.cpp]: Done.

File: src/validation.cpp (hunk 4 above)
Comment (TheBlueMatt) [reply src/validation.cpp]: Done, in a new commit.

File: src/net_processing.cpp [hunk 5]
```diff
@@ -1038,180 +1038,193 @@ static void RelayAddress(const CAddress& addr, bool fReachable, CConnman* connma
...
+    if (mi != mapBlockIndex.end())
+    {
+        if (mi->second->nChainTx && !mi->second->IsValid(BLOCK_VALID_SCRIPTS) &&
+                mi->second->IsValid(BLOCK_VALID_TREE)) {
+            // If we have the block and all of its parents, but have not yet validated it,
+            // we might be in the middle of connecting it (ie in the unlock of cs_main
+            // before ActivateBestChain but after AcceptBlock).
+            // In this case, we need to run ActivateBestChain prior to checking the relay
+            // conditions below.
+            return true;
```
[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply src/net_processing.cpp]: Valid point, refactored a bit, though LEAVE_CRITICAL_SECTION also isnt sufficient as you need to do the mapBlockIndex lookup again, which I went ahead and did.

File: src/net_processing.cpp [hunk 6]
```diff
@@ -1038,180 +1038,193 @@ static void RelayAddress(const CAddress& addr, bool fReachable, CConnman* connma
     connman->ForEachNodeThen(std::move(sortfunc), std::move(pushfunc));
 }
 
-void static ProcessGetData(CNode* pfrom, const Consensus::Params& consensusParams, CConnman* connman, const std::atomic<bool>& interruptMsgProc)
+// returns true if we need to call ActivateBestChain before responding
+bool static ProcessGetBlockData(CNode* pfrom, const Consensus::Params& consensusParams, const CInv& inv, CConnman* connman, const std::atomic<bool>& interruptMsgProc, bool best_chain_active)
```
[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply src/net_processing.cpp]: Oops, was a bug, fixed in the refactor.

[the remark this answers is not in the document]
Comment (TheBlueMatt) [reply src/net_processing.cpp]: Done. I think.

File: src/validation.cpp (hunk 1 above)
Comment (TheBlueMatt) [reply src/validation.cpp]: Done.

**Comment by Damballahwedo** [comment]
Don't send me anymore pub mail. How can't unsubscribe.

File: src/test/miner_tests.cpp [hunk 7]
```diff
@@ -218,6 +217,8 @@ BOOST_AUTO_TEST_CASE(CreateNewBlock_validity)
     for (unsigned int i = 0; i < sizeof(blockinfo)/sizeof(*blockinfo); ++i)
     {
         CBlock *pblock = &pblocktemplate->block; // pointer for convenience
+        {
+        LOCK(cs_main);
         pblock->nVersion = 1;
```
Comment (sipa) [inline src/test/miner_tests.cpp]: Indentation?

File: src/wallet/test/wallet_tests.cpp [hunk 8]
```diff
@@ -627,10 +627,15 @@ class ListCoinsTestingSetup : public TestChain100Setup
         BOOST_CHECK(wallet->CreateTransaction({recipient}, wtx, reservekey, fee, changePos, error, dummy));
         CValidationState state;
         BOOST_CHECK(wallet->CommitTransaction(wtx, reservekey, nullptr, state));
+        CMutableTransaction blocktx;
+        {
+        LOCK(wallet->cs_wallet);
```
Comment (sipa) [inline src/wallet/test/wallet_tests.cpp]: Indentation?

File: src/validation.cpp (hunk 1 above)
Comment (sipa) [reply src/validation.cpp]: It would be nice to introduce a named constant for this instead.

File: src/validationinterface.h [hunk 9]
```diff
@@ -42,6 +42,16 @@ void UnregisterAllValidationInterfaces();
...
+/**
+ * This is a synonym for the following, which asserts certain locks are not
+ * held:
+ *     std::promise<void> promise;
+ *     CallFunctionInValidationInterfaceQueue([&promise] {
+ *         promise.set_value();
+ *     });
+ *     promise.get_future().wait();
+ */
+void BlockOnValidationInterfaceQueueDrain();
```
Comment (sipa) [inline src/validationinterface.h]: If I understand this correctly, it's not actually waiting until a drain, as new events can be added to the queue before the callback added in this function is executed.

It's more a synchronization point.

**Review by sipa — COMMENTED** [review]
utACK af5a003d3cfdd3f3a26dfd7c2db5dde347b4ab3c (with a few non-blocking nits)

**Comment by sipa** [comment]
utACK 97d2b09c124e6e5803f7fd4503348d9710d1260f

**Comment by Sjors** [comment]
I'm about to try this as well, will let you know if I still see extreme memory use during a reindex.
