### PR TITLE
assumeutxo: Drop block height from metadata

### LINKED ISSUE #30514: implicit-integer-sign-change in ActivateSnapshot
```
$ echo 'dXR4b/8BAPq/tdph' | base64 --decode > ./crash

$ UBSAN_OPTIONS="suppressions=$PWD/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1" FUZZ=utxo_snapshot ./src/test/fuzz/fuzz ./crash
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2946336184
INFO: Loaded 1 modules   (625551 inline 8-bit counters): 625551 [0x572ffe28af78, 0x572ffe323b07), 
INFO: Loaded 1 PC tables (625551 PCs): 625551 [0x572ffe323b08,0x572ffecaf3f8), 
./src/test/fuzz/fuzz: Running 1 inputs 1 time(s) each.
Running: ./crash
validation.cpp:5657:28: runtime error: implicit conversion from type 'uint32_t' (aka 'unsigned int') of value 3275262676 (32-bit, unsigned) to type 'int' changed the value to -1019704620 (32-bit, signed)
    #0 0x572ffc2f8a69 in ChainstateManager::ActivateSnapshot(AutoFile&, node::SnapshotMetadata const&, bool) src/validation.cpp:5657:28
    #1 0x572ffb5b93ac in (anonymous namespace)::utxo_snapshot_fuzz_target(std::span<unsigned char const, 18446744073709551615ul>)::$_0::operator()() const src/test/fuzz/utxo_snapshot.cpp:83:27
    #2 0x572ffb5b6896 in (anonymous namespace)::utxo_snapshot_fuzz_target(std::span<unsigned char const, 18446744073709551615ul>) src/test/fuzz/utxo_snapshot.cpp:96:9
    #3 0x572ffb73ac5d in std::function<void (std::span<unsigned char const, 18446744073709551615ul>)>::operator()(std::span<unsigned char const, 18446744073709551615ul>) const /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/std_function.h:591:9
    #4 0x572ffb73ac5d in LLVMFuzzerTestOneInput src/test/fuzz/fuzz.cpp:209:5

SUMMARY: UndefinedBehaviorSanitizer: implicit-integer-sign-change validation.cpp:5657:28 
```

The reason is that metadata is untrusted input, but it isn't sanitized at that point. I presume it can also be reproduced with the integer sanitizer and:

```diff
diff --git a/test/functional/feature_assumeutxo.py b/test/functional/feature_assumeutxo.py
index 943862f8cf..fcb894c924 100755
--- a/test/functional/feature_assumeutxo.py
+++ b/test/functional/feature_assumeutxo.py
@@ -113,10 +113,10 @@ class AssumeutxoTest(BitcoinTestFramework):
         bogus_block_hash = "0" * 64  # Represents any unknown block hash
         # The height is not used for anything critical currently, so we just
         # confirm the manipulation in the error message
-        bogus_height = 1337
+        bogus_height = -1019704620
         for bad_block_hash in [bogus_block_hash, prev_block_hash]:
             with open(bad_snapshot_path, 'wb') as f:
-                f.write(valid_snapshot_contents[:11] + bogus_height.to_bytes(4, "little") + bytes.fromhex(bad_block_hash)[::-1] + valid_snapshot_contents[47:])
+                f.write(valid_snapshot_contents[:11] + bogus_height.to_bytes(4, "little", signed=True) + bytes.fromhex(bad_block_hash)[::-1] + valid_snapshot_contents[47:])
 
             msg = f"Unable to load UTXO snapshot: assumeutxo block hash in snapshot metadata not recognized (hash: {bad_block_hash}, height: {bogus_height}). The following snapshot heights are available: 110, 200, 299."
             assert_raises_rpc_error(-32603, msg, node.loadtxoutset, bad_snapshot_path)
```

### PR DESCRIPTION
**Pull request by fjahr**
Fixes https://github.com/bitcoin/bitcoin/issues/30514 which has more context and shows how the issue can be reproduced. Since the value in question is removed, there is no test to add to reproduce anything.

This is an alternative approach to #30516 with much of the [code being suggested there](https://github.com/bitcoin/bitcoin/pull/30516#discussion_r1689146902).

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Concept ACK

**Comment by Sjors** [comment]
> I have a slight preference for keeping the block height for informative purposes 

Ditto. If the user tries to load a snapshot during header sync, we can give an indication of how long they have to wait. If we're already past the expected height, we can say something useful about potential forks.  

I'll read up on the discussion.

**Review by BrandonOdiwuor — COMMENTED** [review]
Concept ACK

**Comment by fjahr** [comment]
I have closed #30516 so we can move forward with the approach here. Looking forward to get reviews, thanks!

File: src/node/utxo_snapshot.h [hunk 1]
```diff
@@ -28,16 +28,17 @@ class Chainstate;
 namespace node {
 //! Metadata describing a serialized version of a UTXO set from which an
 //! assumeutxo Chainstate can be constructed.
+//! All metadata fields come from an untrusted file, so must be validated
```
Comment (ismaelsadeeq) [inline src/node/utxo_snapshot.h:31]: nit: could indicate in the commit message `ShapShotMetadata` version was also bumped.

**Review by ismaelsadeeq — APPROVED** [review]
Tested ACK 6a020f019f709b595b68516bb3772b811a962e7c

**Review by mzumsande — COMMENTED** [review]
Concept ACK

The block height should also be removed from the `SnapshotMetadata` constructor and the `utxo_snapshot` fuzz target.

File: src/node/utxo_snapshot.h (hunk 1 above)
Comment (fjahr) [reply src/node/utxo_snapshot.h:31]: done

**Comment by fjahr** [comment]
> The block height should also be removed from the `SnapshotMetadata` constructor and the `utxo_snapshot` fuzz target.

Thanks, I fixed that.

File: src/node/utxo_snapshot.h [hunk 2]
```diff
@@ -28,16 +28,17 @@ class Chainstate;
...
+//! before being used. Thus, new fields should be added only if needed.
 class SnapshotMetadata
 {
-    const uint16_t m_version{1};
-    const std::set<uint16_t> m_supported_versions{1};
+    inline static const uint16_t VERSION{2};
```
Comment (Sjors) [inline src/node/utxo_snapshot.h:35]: I would be fine with keeping the version at 1 since this was never released, the old torrent will probably disappear, and the change here doesn't have backwards compatible support.

Comment (Sjors) [reply src/node/utxo_snapshot.h:35]: Also why drop `m_version`? That seems incompatible with the idea of being able to load older versions.

**Review by theStack — APPROVED** [review]
Code-review ACK 00618e8745192d209c23e3ae873c077e58168957

File: src/node/utxo_snapshot.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (fjahr) [reply src/node/utxo_snapshot.h:35]: Yeah, this fixed https://github.com/bitcoin/bitcoin/runs/28432306724

**Review by ismaelsadeeq — COMMENTED** [review]
Re-ACK 00618e8745192d209c23e3ae873c077e58168957

It looks like C.I failure is unrelated as this [diff](https://github.com/bitcoin/bitcoin/compare/6a020f019f709b595b68516bb3772b811a962e7c..00618e8745192d209c23e3ae873c077e58168957) is the last push.

File: src/node/utxo_snapshot.h (hunk 2 above)
Comment (fjahr) [reply src/node/utxo_snapshot.h:35]: I will leave this unaddressed for now since either way seems ok and we have 3 acks.

**Comment by Sjors** [comment]
New torrent (untested and seeding might take a while to kick in): `magnet:?xt=urn:btih:596c26cc709e213fdfec997183ff67067241440c&dn=utxo-840000.dat&tr=udp%3A%2F%2Ftracker.bitcoin.sprovoost.nl%3A6969`

File: test/functional/feature_assumeutxo.py [hunk 3]
```diff
@@ -98,21 +98,20 @@ def expected_error(msg):
         bogus_block_hash = "0" * 64  # Represents any unknown block hash
         # The height is not used for anything critical currently, so we just
```
Comment (mzumsande) [inline test/functional/feature_assumeutxo.py:99]: nit: could remove comment

**Review by mzumsande — COMMENTED** [review]
ACK 00618e8745192d209c23e3ae873c077e58168957

**Comment by achow101** [comment]
ACK 00618e8745192d209c23e3ae873c077e58168957
