### PR TITLE
validation: Send correct notification during snapshot completion

### LINKED ISSUE #31546: qa: Intermittent `AssertionError: not(10.00000000 == 340)` in `wallet_assumeutxo.py --descriptors`
https://github.com/hebasto/bitcoin/actions/runs/12431224655/job/34708713770:
```
265/315 - wallet_assumeutxo.py --descriptors failed, Duration: 5 s

stdout:
2024-12-20T12:54:28.609000Z TestFramework (INFO): PRNG seed is: 187204816715607970

2024-12-20T12:54:28.641000Z TestFramework (INFO): Initializing test directory D:\a\_temp\test_runner_₿_🏃_20241220_123237\wallet_assumeutxo_48

2024-12-20T12:54:30.237000Z TestFramework (INFO): -- Testing assumeutxo

2024-12-20T12:54:30.237000Z TestFramework (INFO): Creating a UTXO snapshot at height 299

2024-12-20T12:54:31.490000Z TestFramework (INFO): Loading snapshot into second node from D:\a\_temp\test_runner_₿_🏃_20241220_123237\wallet_assumeutxo_48\node0\regtest\utxos.dat

2024-12-20T12:54:31.884000Z TestFramework (INFO): Backup from the snapshot height can be loaded during background sync

2024-12-20T12:54:31.916000Z TestFramework (INFO): Backup from before the snapshot height can't be loaded during background sync

2024-12-20T12:54:31.932000Z TestFramework (INFO): Restarting node to stop at height 359

2024-12-20T12:54:32.812000Z TestFramework (INFO): Restarted node before snapshot validation completed, reloading...

2024-12-20T12:54:33.193000Z TestFramework (INFO): Ensuring snapshot chain syncs to tip. (399)

2024-12-20T12:54:33.246000Z TestFramework (INFO): Ensuring background validation completes

2024-12-20T12:54:33.383000Z TestFramework (INFO): Ensuring wallet can be restored from a backup that was created before the snapshot height

2024-12-20T12:54:33.421000Z TestFramework (ERROR): Assertion failed

Traceback (most recent call last):

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 135, in main

    self.run_test()

  File "D:\a\bitcoin\bitcoin/test/functional/wallet_assumeutxo.py", line 188, in run_test

    assert_equal(n1.getbalance(), 340)

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\util.py", line 77, in assert_equal

    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))

AssertionError: not(10.00000000 == 340)

2024-12-20T12:54:33.474000Z TestFramework (INFO): Stopping nodes
```

### PR DESCRIPTION
**Pull request by mzumsande**
After AssumeUtxo background sync is completed in a `ActivateBestChain()` call, the `GetRole()` function called with `BlockConnected()` returns `ChainstateRole::NORMAL` instead of `ChainstateRole::BACKGROUND` for this chainstate.
This would make the wallet (which ignores `BlockConnected` notifications for the background chainstate) process it, change `m_last_block_processed_height` to the (ancient) snapshot height, and display an incorrect balance.

Fix this by caching the chainstate role before calling `ActivateBestChainStep()`.
Also contains a test for this situation that fails on master.

Fixes #31546

### CODE REVIEW

File: src/validation.cpp [hunk 1]
```diff
@@ -3526,6 +3526,10 @@ bool Chainstate::ActivateBestChain(BlockValidationState& state, std::shared_ptr<
 
                 bool fInvalidFound = false;
                 std::shared_ptr<const CBlock> nullBlockPtr;
+                // BlockConnected signals must be sent for the original role;
+                // in case snapshot validation is completed during ActivateBestChainStep, the
+                // result of GetRole() changes from BACKGROUND to NORMAL.
+               ChainstateRole chainstate_role{this->GetRole()};
```
Comment (fjahr) [inline src/validation.cpp:3532]: nit: could have been `const`

File: test/functional/wallet_assumeutxo.py [hunk 2]
```diff
@@ -57,6 +59,8 @@ def run_test(self):
         """
         n0 = self.nodes[0]
         n1 = self.nodes[1]
+        n2 = self.nodes[2]
+
```
Comment (fjahr) [inline test/functional/wallet_assumeutxo.py:63]: nit: newline not necessary imo

File: test/functional/wallet_assumeutxo.py [hunk 3]
```diff
@@ -192,6 +198,18 @@ def run_test(self):
...
+        n2.restorewallet("w", "backup_w.dat")
+        self.log.info(
+            f"Loading snapshot into third node from {dump_output['path']}")
+        loaded = n2.loadtxoutset(dump_output['path'])
+        self.log.info("Ensuring background validation completes")
+        self.connect_nodes(0, 2)
+        self.wait_until(lambda: len(n2.getchainstates()['chainstates']) == 1)
+
+        self.log.info("Check balance at third node")
+        ensure_for(duration=1, f=lambda: (n2.getbalance() == 34))
```
Comment (fjahr) [inline test/functional/wallet_assumeutxo.py:211]: I like to see `ensure_for` getting used but I think I would have opted for `self.wait_until(lambda: (n2.getbalance() == 34), timeout=5)` or so here. Is there a case I am missing where the balance might change after having been 34 that you are covering with this?

**Review by fjahr — COMMENTED** [review]
tACK ca0753160a8ebc113e08d62c7b6cbe8fa98455e6

Good catch, feel free to ignore my comments unless you have to retouch. I confirmed that the test fails on master and reviewed the code and surrounding behavior.

File: test/functional/wallet_assumeutxo.py (hunk 3 above)
Comment (mzumsande) [reply test/functional/wallet_assumeutxo.py:211]: I used `ensure_for` because otherwise the added test might not always have failed on master before (if the first check had been done immediately, before the incorrect notification was processed by the wallet, the balance would have still been 34).

File: src/validation.cpp (hunk 1 above)
Comment (mzumsande) [reply src/validation.cpp]: done

File: test/functional/wallet_assumeutxo.py (hunk 2 above)
Comment (mzumsande) [reply test/functional/wallet_assumeutxo.py:63]: removed, that was not on purpose

**Comment by mzumsande** [comment]
[ca07531](https://github.com/bitcoin/bitcoin/commit/ca0753160a8ebc113e08d62c7b6cbe8fa98455e6) to [bc43eca](https://github.com/bitcoin/bitcoin/commit/bc43ecaf6dc0830a27296d3a29428814fed07bb1):
Addressed feedback by @fjahr

**Comment by fjahr** [comment]
re-ACK bc43ecaf6dc0830a27296d3a29428814fed07bb1

**Review by furszy — COMMENTED** [review]
Code review ACK bc43ecaf6dc

File: test/functional/wallet_assumeutxo.py [hunk 4]
```diff
@@ -57,6 +59,7 @@ def run_test(self):
         """
```
Comment (TheCharlatan) [inline test/functional/wallet_assumeutxo.py:59]: Should the docs be updated to mention the added node?

**Review by sedited — APPROVED** [review]
lgtm ACK bc43ecaf6dc0830a27296d3a29428814fed07bb1

**Comment by achow101** [comment]
ACK bc43ecaf6dc0830a27296d3a29428814fed07bb1

File: test/functional/wallet_assumeutxo.py (hunk 4 above)
Comment (mzumsande) [reply test/functional/wallet_assumeutxo.py:59]: missed this, it could probably be done in a follow-up such as #30455
