### PR TITLE
util: Work around libstdc++ create_directories issue

### LINKED ISSUE #24257: bitcoind and bitcoin-cli does not supports symbolic link anymore
I just pulled latest master at https://github.com/bitcoin/bitcoin/commit/3ace3a17c9bce606cea05192f0da3ac62ac69dda and I cannot run bitcoind or bitcoin-cli without providing a full path for data directory using `-datadir` option. It was working fine couple of days ago (while running https://github.com/bitcoin/bitcoin/commit/807169e10b4a18324356ed6ee4d69587b96a7c70). I suspect it may be related to latest switch to the standard std::filesystem library https://github.com/bitcoin/bitcoin/pull/20744

**Expected behavior**

I use a symbolic link to point my /home/me/.bitcoin to an external hard drive. When running `bitcoind` from command line, or executing `bitcoin-cli` commands, without using the `-datadir` option, it should not terminate or crash unexpectedly. Those commands should be able to follow the symbolic link and be able to read/write into the final folder.

**Actual behavior**

`bitcoind` and `bitcoin-cli` are not able to follow the symbolic link. `bitcoin-qt` runs fine, even when running it from command line. See below commands examples.

```
# Create a symbolic link
$~/btc-things/bitcoin$ ln -s /media/DATA/Bitcoin /home/me/.bitcoin

# Try to run bitcoind - Crashes
$~/btc-things/bitcoin$ ./bitcoind 


************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Not a directory [/home/me/.bitcoin]       
bitcoin in AppInit()       

bitcoind: chainparamsbase.cpp:35: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.
Aborted (core dumped)

# Run bitcoin-qt, it works fine, the node runs
$~/btc-things/bitcoin$ ./bitcoin-qt 
qt5ct: using qt5ct plugin

# Try to run a bitcoin-cli command to interact with the running node, does not work
$~/btc-things/bitcoin$ ./bitcoin-cli getblockhash 501726


************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Not a directory [/home/me/.bitcoin]       
bitcoin in AppInitRPC()       

# Try the same previous command but give an absolute path for -datadir, works fine
$~/btc-things/bitcoin$ ./bitcoin-cli -datadir=/media/DATA/Bitcoin getblockhash 501726
0000000000000000004b27f9ee7ba33d6f048f684aaeb0eea4befd80f1701126
```

**To reproduce**

Steps are indicated previously.

**System information**

Running `Bitcoin Core version v22.99.0-3ace3a17c9bc`. Self compiled from `master` branch.

I'm using Linux Mint with the following kernel `Linux 5.4.0-96-generic x86_64`.
I'm using an additional hard drive to store the full blockchain (SSD).

I had no prior issues before pulling latest changes. I was previously running at https://github.com/bitcoin/bitcoin/commit/807169e10b4a18324356ed6ee4d69587b96a7c70

### PR DESCRIPTION
**Pull request by laanwj**
Work around libstdc++ issue [PR101510] with create_directories where the leaf already exists as a symlink. Fixes #24257, introduced by the switch to `std::filesystem`. It is meant to be more thorough than #24266, which worked around one instance of the problem.

The issue was [fixed upstream](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=124eaa50e0a34f5f89572c1aa812c50979da58fc), but unfortunately we'll have to carry a fix for it for a while.

This introduces a function `fs::create_directories` which wraps
`std::filesystem::create_directories`. This allows easiliy reverting the
workaround when it is no longer necessary.

### CODE REVIEW

File: src/fs.h [hunk 1]
```diff
@@ -140,6 +140,21 @@ static inline path PathFromString(const std::string& string)
...
+
+/**
+ * Create directory (and if necessary its parents), unless the leaf directory
+ * already exists or is a symlink to an existing directory.
+ * This is a temporary workaround for an issue in libstdc++ that has been fixed
+ * upstream [PR101510].
+ */
+static inline bool create_directories(const std::filesystem::path& p)
+{
+    if (fs::is_symlink(p) && fs::is_directory(p)) {
```
Comment (jonatack) [inline src/fs.h:152]: I could be confused but it reads as though the comment says "or" and the logic says "and"
```suggestion
    if (fs::is_symlink(p) || fs::is_directory(p)) {
```

Comment (laanwj) [reply src/fs.h:152]: Right, `or` would work, but it's not necessary. This `if` statement is to catch the specific situation that is buggy, it doesn't aim to implement anything further.

**Comment by laanwj** [comment]
I'm really confused by the CI output:
```
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py", line 201, in <module>
    main()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py", line 67, in main
    log_events = read_logs(testdir)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py", line 86, in read_logs
    assert next(glob, None) is None #  more than one debug.log, should never happen
  File "/usr/lib64/python3.6/pathlib.py", line 1100, in glob
    for p in selector.select_from(self):
  File "/usr/lib64/python3.6/pathlib.py", line 508, in _select_from
    for p in self.successor._select_from(path, is_dir, exists, scandir):
  File "/usr/lib64/python3.6/pathlib.py", line 559, in _select_from
    for starting_point in self._iterate_directories(parent_path, is_dir, scandir):
  File "/usr/lib64/python3.6/pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/lib64/python3.6/pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/lib64/python3.6/pathlib.py", line 549, in _iterate_directories
    for p in self._iterate_directories(path, is_dir, scandir):
  File "/usr/lib64/python3.6/pathlib.py", line 547, in _iterate_directories
    if entry.is_dir() and not entry.is_symlink():
OSError: [Errno 40] Too many levels of symbolic links: '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_\u20bf_🏃_20220214_135218/wallet_multiwallet_169/node0/regtest/walletdir/self_walletdat_symlink/wallet.dat'
```
This change doesn't actually create any symbolic links, it just tolerates them, so I don't understand.

**Comment by jonatack** [comment]
I've haven't been following the issue, but the code makes sense, `util_tests` are green for me on Debian with clang 13.0.1, but `wallet_multiwallet.py` and `combine_logs.py` both aren't happy.

<details><summary>test/functional/wallet_multiwallet.py</summary><p>

```
2022-02-14T14:25:38.701000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_5_zm4jhi
2022-02-14T14:25:44.906000Z TestFramework (INFO): Do not allow -upgradewallet with multiwallet
2022-02-14T14:25:45.837000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/home/jon/projects/bitcoin/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/home/jon/projects/bitcoin/bitcoin/test/functional/wallet_multiwallet.py", line 192, in run_test
    os.rename(wallet_dir2, wallet_dir())
OSError: [Errno 39] Directory not empty: '/tmp/bitcoin_func_test_5_zm4jhi/node0/regtest/walletdir' -> '/tmp/bitcoin_func_test_5_zm4jhi/node0/regtest/wallets'
</p></details>

File: src/fs.h (hunk 1 above)
Comment (vasild) [reply src/fs.h:152]: Or just `std::filesystem::exists()` would also work, I guess but will have a wider scope.

> catch the specific situation that is buggy

+1

File: src/fs.h [hunk 2]
```diff
@@ -140,6 +140,21 @@ static inline path PathFromString(const std::string& string)
...
 #endif
 }
+
+/**
+ * Create directory (and if necessary its parents), unless the leaf directory
+ * already exists or is a symlink to an existing directory.
+ * This is a temporary workaround for an issue in libstdc++ that has been fixed
+ * upstream [PR101510].
+ */
+static inline bool create_directories(const std::filesystem::path& p)
```
Comment (vasild) [inline src/fs.h:150]: There is also another function:

```cpp
bool create_directories(const std::filesystem::path& p, std::error_code& ec);
```

Is it worth hijacking that too? In case somebody in the future decides to use that one instead?

Comment (laanwj) [reply src/fs.h:150]: I thought about it, but defining a function that's not used felt wrong, somehow. Is there a way to un-define it?

File: src/fs.h (hunk 1 above)
Comment (laanwj) [reply src/fs.h:152]: What if it is a symlink to a file, a device, etc, instead of a directory? I think it should still fail in that case. That's why I didn't use the more general `exists`.

File: src/fs.h (hunk 2 above)
Comment (vasild) [reply src/fs.h:150]: Cool, I did not know `= delete` could be used on non-member functions. It seems it can - https://en.cppreference.com/w/cpp/language/function#Deleted_functions. `static inline` can be skipped.

**Comment by MarcoFalke** [comment]
> I've reverted @MarcoFalke 's proposed change for now. Let's see if this passes CI.

Interesting. For reference, the failed CI is here: https://cirrus-ci.com/build/6366611337641984

It would be good to know why it failed. Otherwise it seems that the same failure that happened on the wallet dir is going to happen on the blocks dir as well, with this patch.

**Comment by laanwj** [comment]
> Otherwise it seems that the same failure that happened on the wallet dir is going to happen on the blocks dir as well, with this patch.

This was the first thing I checked (as it's the problem I'd been suffering from), and it worked fine.

**Comment by jonatack** [comment]
01c5aefa032f1f7d28c132481624e2d74aa1d14b solves the `wallet_multiwallet.py` error in https://github.com/bitcoin/bitcoin/pull/24338#issuecomment-1039151357 for me locally.

File: src/fs.h (hunk 2 above)
Comment (laanwj) [reply src/fs.h:150]: Thanks, will remove the `static inline`.

**Comment by MarcoFalke** [comment]
Ugh, my bad. :man_facepalming:

File: src/test/dbwrapper_tests.cpp [hunk 3]
```diff
@@ -203,7 +203,7 @@ BOOST_AUTO_TEST_CASE(existing_data_no_obfuscate)
 {
     // We're going to share this fs::path between two wrappers
     fs::path ph = m_args.GetDataDirBase() / "existing_data_no_obfuscate";
-    create_directories(ph);
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/test/dbwrapper_tests.cpp:206]: No, no idea, I was surprised too.

**Comment by jonatack** [comment]
utACK  b9dff100ff2e7dfb9f216e98964fe28ef5bac3a9

**Review by w0xlt — COMMENTED** [review]
If the `blocks` directory is a symlink, as mentioned in https://github.com/bitcoin/bitcoin/issues/24257#issuecomment-1036272515, the error below still occurs.

```
************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Not a directory [/home/.../.bitcoin/signet/blocks]       
bitcoin in AppInit()   
```

**Comment by MarcoFalke** [comment]
Is it possible to write a test for this with https://docs.python.org/3.8/library/os.html#os.symlink ? (Like the multiwallet test)

**Comment by laanwj** [comment]
> If the blocks directory is a symlink, as mentioned in https://github.com/bitcoin/bitcoin/issues/24257#issuecomment-1036272515, the error below still occurs.

Strange, it works here on Ubuntu 20.04. The `blocks` directory is a symlink.
```
$ stat ~/.bitcoin/blocks
  File: /home/…/.bitcoin/blocks -> /…/bitcoin/blocks
```

Without this patch I get
```
************************
EXCEPTION: NSt10filesystem7__cxx1116filesystem_errorE       
filesystem error: cannot create directories: Not a directory [/home/…/.bitcoin/blocks]       
bitcoin in AppInit()   
```

With this patch, it works:
```
$ src/bitcoind                                                        
2022-02-15T08:59:11Z Bitcoin Core version v22.99.0-b9dff100ff2e (release build)
…
```

I have checked the same for signet. *Both* making the `signet` directory a link, and `signet/blocks`.

> Is it possible to write a test for this with https://docs.python.org/3.8/library/os.html#os.symlink ? (Like the multiwallet test)

Sure. I'll look into it.

File: src/fs.h (hunk 1 above)
Comment (vasild) [reply src/fs.h:152]: By "fail" you mean to throw an exception or to return `false`? According to the spec, it should return `false` in that case.

File: src/test/dbwrapper_tests.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/test/dbwrapper_tests.cpp:206]: The following compiles:

```cpp
#include <filesystem>
int main() {
    create_directories(std::filesystem::path{"/"});
}

**Review by vasild — COMMENTED** [review]
@w0xlt, @laanwj, I don't have a buggy gcc to experiment, but my guess is that if `signet` is a symlink and inside `blocks` is an ordinary directory, then `is_symlink("signet/blocks")` will return `false`. In this case our condition will be `false` and we will call the buggy/system `create_directories()`. It should return `false` in that case but maybe it throws instead because of the bug?

File: src/test/dbwrapper_tests.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (vasild) [reply src/test/dbwrapper_tests.cpp:206]: Wow! I confirm it compiles with clang 14. But just `create_directories("/");` does not compile: `error: use of undeclared identifier 'create_directories'; did you mean 'std::filesystem::create_directories'?` :mage:

**Comment by w0xlt** [comment]
My bad. The symlink was created using the relative path instead of the absolute one.
Tested with absolute path on Ubuntu 20.04 and this patch worked.

**Comment by w0xlt** [comment]
Yes, the link was broken. The relative path did not exist in the `bitcoind` execution context.

File: src/fs.h [hunk 4]
```diff
@@ -140,6 +140,28 @@ static inline path PathFromString(const std::string& string)
...
+{
+    if (fs::is_symlink(p) && fs::is_directory(p)) {
```
[the remark this answers is not in the document]
Comment (laanwj) [reply src/fs.h:152]: I prefer to keep this fully qualified, just to be sure.

**Comment by laanwj** [comment]
Thanks for doublt-checking @w0xlt.

**Comment by hebasto** [comment]
Concept ACK, reviewing...

File: src/fs.h (hunk 4 above)
Comment (hebasto) [inline src/fs.h:152]: > I prefer to keep this fully qualified, just to be sure, and entirely clear what these refer to in case other functions are wrapped.

Then, maybe
```suggestion
    if (std::filesystem::is_symlink(p) && std::filesystem::is_directory(p)) {
```
?

**Review by hebasto — COMMENTED** [review]
Approach ACK b9dff100ff2e7dfb9f216e98964fe28ef5bac3a9.

Maybe add a [unit test](https://github.com/hebasto/bitcoin/commit/3b64e89e15eb0012d5cc4a05c3f5678cc2b63a4e) which being applied to the master branch passes on systems that have libstdc++ already being patched?

**Review by vasild — APPROVED** [review]
ACK b9dff100ff2e7dfb9f216e98964fe28ef5bac3a9

I managed to reproduce this and played a bit with it. This PR will fix the problem where the last component of the path is a symlink to a directory (instead of just directory).

Assuming buggy system `create_directories()`, then in some cases our newly introduced `create_directories()` still deviates from the standard - e.g. if the last component exists but is not a directory, then we would call the system function which will throw, whereas, according to the standard it should just return `false`. I think this is ok.

File: src/fs.h (hunk 4 above)
Comment (laanwj) [reply src/fs.h:152]: Well, if we override these, we'll likely want to use the overridden versions, right?

File: src/fs.h (hunk 1 above)
Comment (laanwj) [reply src/fs.h:152]: OK. Yeah thanks, but I think it's fine to deviate from the spec in this case, it's fatal in our case.

**Review by vasild — APPROVED** [review]
ACK d035b64aa0d1b23f34698cc20df65dd613b4adf7

**Comment by laanwj** [comment]
New update:
- Guard symlink test to not run on Windows.
- Add `feature_dirsymlinks` functional test that tests running with symlinked `blocks` and `chainstate` directories.

File: src/test/dbwrapper_tests.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/test/dbwrapper_tests.cpp:206]: > Wow! I confirm it compiles with clang 14.

https://en.wikipedia.org/wiki/Argument-dependent_name_lookup

**Review by w0xlt — APPROVED** [review]
tACK 67019cd on Ubuntu 20.04

**Comment by jonatack** [comment]
Haven't been able to make the new unit or functional test fail without the fix commit. With debian testing, tried compiling with an older gcc 8 (Debian 8.4.0-7). Any tips?

File: test/functional/feature_dirsymlinks.py [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+
+import os
+import sys
+
+from test_framework.test_framework import BitcoinTestFramework, SkipTest
+
+
+def rename_and_link(fromname, toname):
+    os.rename(fromname, toname)
+    os.symlink(toname, fromname)
```
Comment (jonatack) [inline test/functional/feature_dirsymlinks.py:16]: pico nit if need to retouch, snakecase `from_name, to_name` and use named arguments in the callers (feel free to ignore)

**Review by jonatack — COMMENTED** [review]
Wasn't able to make the tests fail using gcc 8.4 without the fix but am on debian testing and turns out it has libstdc++ patched. Hopefully another reviewer can see them fail without the fix (thanks for adding them).

re-ACK  67019cde228feef8c41e6c685d62a21e85a2cfd9

File: src/test/fs_tests.cpp [hunk 6]
```diff
@@ -118,4 +118,28 @@ BOOST_AUTO_TEST_CASE(fsbridge_fstream)
     }
 }
 
-BOOST_AUTO_TEST_SUITE_END()
\ No newline at end of file
+#ifndef WIN32
```
Comment (hebasto) [inline src/test/fs_tests.cpp:121]: Could be narrowed to `__MINGW64__`, but `WIN32` is ok as it is coordinated with a new `feature_dirsymlinks.py` test.

File: src/fs.h (hunk 2 above)
Comment (hebasto) [reply src/fs.h:150]: > `static inline` can be skipped.

> Thanks, will remove the `static inline`.

:smile:

**Review by hebasto — APPROVED** [review]
ACK 67019cde228feef8c41e6c685d62a21e85a2cfd9

**Comment by laanwj** [comment]
> Haven't been able to make the new unit or functional test fail without the fix commit. With debian testing, tried compiling with an older gcc 8 (Debian 8.4.0-7). Any tips?

Ubuntu 20.04 is still unpatched, seems the best OS to test this on. Haven't tried it on 22.04 yet. It makes sense for debian testing to be ahead.

File: src/test/fs_tests.cpp (hunk 6 above)
Comment (laanwj) [reply src/test/fs_tests.cpp:121]: WIN32 is "all windows" so I think this is correct. No need to narrow it if we know it's true for all.

File: test/functional/feature_dirsymlinks.py (hunk 5 above)
Comment (laanwj) [reply test/functional/feature_dirsymlinks.py:16]: Yea, that'd be slightly better.

File: src/test/fs_tests.cpp (hunk 6 above)
Comment (hebasto) [reply src/test/fs_tests.cpp:121]: I mean, this test, being applied on top of the master branch, [passes](https://cirrus-ci.com/task/5367730952994816) for MSVC build.

**Review by hebasto — APPROVED** [review]
re-ACK b223c3c21e89f6af76b5401413880923f7c444d6

**Comment by jonatack** [comment]
> Ubuntu 20.04 is still unpatched, seems the best OS to test this on. Haven't tried it on 22.04 yet (edit: just did—also not patched yet). It makes sense for debian testing to be ahead.
> 
> It would be kind of funny if by the time we release, all distros have been patched. That said, the tests are useful to keep.

:+1:

re-ACK b223c3c21e89f6af76b5401413880923f7c444d6 per `git range-diff df08250 67019cd b223c3c`

Nice touch adding the splat to `rename_and_link()` to enforce the named args.

**Comment by fanquake** [comment]
Guix build:
```bash
bash-5.1# find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum
075732c9a4af5d0c3cc09bc7bf8c15ef41c62d0984c4556c2756fb1d684ddc11  guix-build-b223c3c21e89/output/aarch64-linux-gnu/SHA256SUMS.part
fd13a2477eb6400aa00200e46df3dd3734e54f19f156807ba8e0fe2d1659dafb  guix-build-b223c3c21e89/output/aarch64-linux-gnu/bitcoin-b223c3c21e89-aarch64-linux-gnu-debug.tar.gz
8c1c6cd750fdf1cc6f3990a1d15a03076fcdb3fef76916359d76b11370f11e73  guix-build-b223c3c21e89/output/aarch64-linux-gnu/bitcoin-b223c3c21e89-aarch64-linux-gnu.tar.gz
0d957e31ab5645703be7fc62d09c1096677c25b395f97bed11ae7bf1b4da0a44  guix-build-b223c3c21e89/output/arm-linux-gnueabihf/SHA256SUMS.part
44fdc0ddfc86eab2a747f4087bbcf79b532b5d7dd5a77b1ef33b49f5c65a95b9  guix-build-b223c3c21e89/output/arm-linux-gnueabihf/bitcoin-b223c3c21e89-arm-linux-gnueabihf-debug.tar.gz
456b5b91302568e59ee8d5329d065efffcbd7fd76a064cd9c67e7f404dc7249d  guix-build-b223c3c21e89/output/arm-linux-gnueabihf/bitcoin-b223c3c21e89-arm-linux-gnueabihf.tar.gz
3a0c3420152e95c88ac67ecf114e88a43af2b82b17cf5778b66645b4273bf995  guix-build-b223c3c21e89/output/arm64-apple-darwin/SHA256SUMS.part
c2f03f7866bdb1455a277dd2c2539facbf0a64ed256ab226e61422dec60098eb  guix-build-b223c3c21e89/output/arm64-apple-darwin/bitcoin-b223c3c21e89-arm64-apple-darwin.tar.gz
a2093272f16783e68a207fe7ece4f7159dea079c29315f72d4a995201542b514  guix-build-b223c3c21e89/output/arm64-apple-darwin/bitcoin-b223c3c21e89-osx-unsigned.dmg
7c98dcd13c45af6e4039a0cde255818552981c5690dedb764b89bc84c9b09d97  guix-build-b223c3c21e89/output/arm64-apple-darwin/bitcoin-b223c3c21e89-osx-unsigned.tar.gz
c5e1be7e7fd68fc9b0cc87829c94c12dd00386905961b012f778cd1a2eaca1bc  guix-build-b223c3c21e89/output/dist-archive/bitcoin-b223c3c21e89.tar.gz
b6044165141e6dbbf8a2deac093b46bc7216a8f8027a41d551eb6adeb6b35caa  guix-build-b223c3c21e89/output/powerpc64-linux-gnu/SHA256SUMS.part
db025c0407b73aa6ba385d508d3cb9fc5483271fa92bc0cc09065f10230c5d3d  guix-build-b223c3c21e89/output/powerpc64-linux-gnu/bitcoin-b223c3c21e89-powerpc64-linux-gnu-debug.tar.gz
ca4285de33997bd7e6cd3a9ce41038221c488d86c6dcd082c2479d8c18cd0c09  guix-build-b223c3c21e89/output/powerpc64-linux-gnu/bitcoin-b223c3c21e89-powerpc64-linux-gnu.tar.gz
e12d1e7864f79a37639156751b3b03c4e2f9bf9ca53ac9ae279aeabaa1f692ba  guix-build-b223c3c21e89/output/powerpc64le-linux-gnu/SHA256SUMS.part
94b7da0b74207974acb5a3d614397c04acb56a07ae1a97d6e782760ff24271e2  guix-build-b223c3c21e89/output/powerpc64le-linux-gnu/bitcoin-b223c3c21e89-powerpc64le-linux-gnu-debug.tar.gz
7e64a5d5a7f586244684a4c7b275640fb09b82b9591c48b0440b7e5ca16b9781  guix-build-b223c3c21e89/output/powerpc64le-linux-gnu/bitcoin-b223c3c21e89-powerpc64le-linux-gnu.tar.gz
38277de2c4cc5c539796a92e4c97f4dec4eb8a39aee32af97a21fca02e0a3fa7  guix-build-b223c3c21e89/output/riscv64-linux-gnu/SHA256SUMS.part
d89076a6d7c7d693aea0a3ca2ac49e76f2c72ae61261ba1623b34b2d03f4937f  guix-build-b223c3c21e89/output/riscv64-linux-gnu/bitcoin-b223c3c21e89-riscv64-linux-gnu-debug.tar.gz
57741dadfbe3c8b744e3e700a1b8c314d442d99ef3aff281efe4428e5938e8f0  guix-build-b223c3c21e89/output/riscv64-linux-gnu/bitcoin-b223c3c21e89-riscv64-linux-gnu.tar.gz
762aa6260628afbaf5cee1b60a4fcecc7de5453b1b526bbba222c85b33e1ac7f  guix-build-b223c3c21e89/output/x86_64-apple-darwin/SHA256SUMS.part
21a5d675de49c2cc2c94406e1d5b5565c0c04d8c7f21b7d8fde111dd68ffcb9f  guix-build-b223c3c21e89/output/x86_64-apple-darwin/bitcoin-b223c3c21e89-osx-unsigned.dmg
1caf7a2115fc0aac3216cd06cdb4eb3c715299f6e707eb6ebe0cd62acffa2621  guix-build-b223c3c21e89/output/x86_64-apple-darwin/bitcoin-b223c3c21e89-osx-unsigned.tar.gz
81b0cc3cbc308ebc6b778fdfc2f38c550e273883c47f909d12b7e096d3d950ca  guix-build-b223c3c21e89/output/x86_64-apple-darwin/bitcoin-b223c3c21e89-osx64.tar.gz
0a3b41c634a9952c0084fd43f757971e9b55dd099b850b4585621be263ed01cf  guix-build-b223c3c21e89/output/x86_64-linux-gnu/SHA256SUMS.part
c0d461b1006201f2ae202019f06cb4709a2627f0e28a8cd9ebafed6ee8bd8231  guix-build-b223c3c21e89/output/x86_64-linux-gnu/bitcoin-b223c3c21e89-x86_64-linux-gnu-debug.tar.gz
31bcf08af8012bfbff3e417c784ee0d546f916d24495143cff581a23e0bb9690  guix-build-b223c3c21e89/output/x86_64-linux-gnu/bitcoin-b223c3c21e89-x86_64-linux-gnu.tar.gz
c9bb21542cdb876ef9e7dd4b4d18dda2955d56a003b5e06ff171f8480d52bb15  guix-build-b223c3c21e89/output/x86_64-w64-mingw32/SHA256SUMS.part
ccf12d1929669f1edbe80496e7cd48b96eb336de596c46b666802c784aec9808  guix-build-b223c3c21e89/output/x86_64-w64-mingw32/bitcoin-b223c3c21e89-win-unsigned.tar.gz
4f91e09b2ba0b130e101ce3e8616463d8f4a72098c9adc1ac46fa7aa5bf92188  guix-build-b223c3c21e89/output/x86_64-w64-mingw32/bitcoin-b223c3c21e89-win64-debug.zip
6d40204e81732857cf28a32262e9ae4170714627efc81ebe7ddad7b50faa45b1  guix-build-b223c3c21e89/output/x86_64-w64-mingw32/bitcoin-b223c3c21e89-win64-setup-unsigned.exe
9c6881f8734ffa8b0765aa791b10c28e8ce0f983ca35b3ba2ddf2577173cdd58  guix-build-b223c3c21e89/output/x86_64-w64-mingw32/bitcoin-b223c3c21e89-win64.zip
```

**Review by w0xlt — APPROVED** [review]
re-ACK b223c3c

File: test/functional/feature_dirsymlinks.py [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+import os
+import sys
+
+from test_framework.test_framework import BitcoinTestFramework, SkipTest
+
+
+def rename_and_link(*, from_name, to_name):
+    os.rename(from_name, to_name)
+    os.symlink(to_name, from_name)
+    assert os.path.islink(from_name) and os.path.isdir(from_name)
```
Comment (vasild) [inline test/functional/feature_dirsymlinks.py:17]: This will only work with absolute paths.

```sh
$ cd /tmp
$ mkdir -p datadir/regtest/blocks

$ mv datadir/regtest/blocks datadir/regtest/newblocks
$ ln -s datadir/regtest/newblocks datadir/regtest/blocks
$ ls -l datadir/regtest/blocks
lrwxr-xr-x   datadir/regtest/blocks -> datadir/regtest/newblocks
# now /tmp/datadir/regtest/blocks is a symlink to /tmp/datadir/regtest/datadir/regtest/newblocks
```

I think it is ok, coz `self.nodes[0].datadir` is probably an absolute path now, given that the test passes.

**Review by vasild — APPROVED** [review]
ACK b223c3c21e89f6af76b5401413880923f7c444d6

File: test/functional/feature_dirsymlinks.py (hunk 7 above)
Comment (vasild) [reply test/functional/feature_dirsymlinks.py:17]: I verified `self.nodes[0].datadir` is absolute even if a relative one is given on the command line, like: `./test/functional/feature_dirsymlinks.py --tmpdir=foo`

Comment (laanwj) [reply test/functional/feature_dirsymlinks.py:17]: Right. It's a function for the scope of this test, it doesn't aim nor need to work for the general case.
