### PR TITLE
Wallet:  Fix Non-Ranged Descriptors with Range [0,0] Trigger Unexpected Wallet Errors in AddWalletDescriptor

### LINKED ISSUE #31728: Bug: Non-Ranged Descriptors with Range [0,0] Trigger Unexpected Wallet Errors in `AddWalletDescriptor`
**Summary:**

When attempting to add a **non-ranged** descriptor with a start/end range of `[0,0]` via `AddWalletDescriptor`, an error may appear:  
```
UpdateWalletDescriptor: new range must include current range = [0,0].
```
This is unexpected for a non-ranged descriptor, as `[0,0]` should effectively mean “no range.” In some cases, changing the end to `1` (i.e. `[0,1]`) circumvents the issue, but that implies a single-index range rather than a truly non-ranged descriptor.

Further debugging revealed this seems tied to:
1. **Multiple calls** to `AddWalletDescriptor` for the same descriptor.
2. **Internal handling of descriptor ranges** (the wallet expects a valid range for ranged descriptors, but still enforces checks on `start/end` even if the descriptor is meant to be non-ranged).
3. A possible **bug in `UpdateWalletDescriptor`** when it encounters repeated or zero-width ranges.

**What was expected:**
- Specifying `[0,0]` for a non-ranged descriptor (or not specifying a range at all) should *not* fail.
- A truly non-ranged descriptor should not require these range checks.
- `AddWalletDescriptor` should be idempotent

**What actually happens:**
- Repeatedly adding a descriptor (or calling it in a way that triggers `UpdateWalletDescriptor`) with `[0,0]` can cause the wallet to complain that the “new range must include current range = [0,0]”.

**Why this matters:**
- Non-ranged descriptor workflows should be consistent and should not require a dummy range.
- The wallet code should either cleanly ignore range parameters for non-ranged descriptors or handle a `[0,0]` range gracefully.

**Proposed fix or investigation:**
- Review `AddWalletDescriptor` and `UpdateWalletDescriptor` logic to ensure zero-width (`[0,0]`) or absent ranges are handled properly for non-ranged descriptors.
- Confirm if the internal code should treat `[0,0]` as a valid non-ranged descriptor or if that scenario should simply be disallowed/ignored in favor of no range parameters at all.
- Add tests to cover repeatedly adding the same descriptor and verifying correct behavior for non-ranged descriptors.
- Change the wallet::WalletDescriptor to have `std::optional<std::pair<start,end>>` to differentiate unranged v.s. empty ranged descriptors.

This appears to be a minor bug, but it can lead to confusion and error messages when using or experimenting with non-ranged descriptors in custom wallet workflows.

### PR DESCRIPTION
**Pull request by Eunovo**
Closes https://github.com/bitcoin/bitcoin/issues/31728

This PR updates the `DescriptorScriptPubKeyMan` to skip range checks for non-ranged descriptors, which previously caused errors when updating a non-ranged descriptor with the range [0,0]

#### Testing
A unit test was added to test the new behaviour

### CODE REVIEW

**Review by w0xlt — COMMENTED** [review]
Concept ACK.

Functional tests might be necessary.

**Comment by Eunovo** [comment]
> Functional tests might be necessary.

The `importdescriptors` RPC sets the range for all non-ranged descriptors to `[0,1]` in every request so this error cannot be triggered using the RPC.

In https://github.com/bitcoin/bitcoin/issues/31728 @JeremyRubin explains that this error may be unexpectedly triggered when " experimenting with non-ranged descriptors in custom wallet workflows."

File: src/wallet/test/wallet_tests.cpp [hunk 1]
```diff
@@ -73,6 +73,27 @@ static void AddKey(CWallet& wallet, const CKey& key)
...
+        auto key{GenerateRandomKey()};
+        auto desc_str{"combo(" + EncodeSecret(key) + ")"};
+        for (size_t i = 0; i < 2; i++)
+        {
+            FlatSigningProvider provider;
+            std::string error;
+            auto descs{Parse(desc_str, provider, error, /* require_checksum=*/ false)};
+            auto& desc{descs.at(0)};
+            WalletDescriptor w_desc{std::move(desc), 0, 0, 0, 0};
+            auto spk_manager{*Assert(wallet.AddWalletDescriptor(w_desc, provider, "", false))};
```
Comment (shahsb) [inline src/wallet/test/wallet_tests.cpp]: I do not see the call to the function `DescriptorScriptPubKeyMan::CanUpdateToWalletDescriptor()` being made in this test case?

**Comment by shahsb** [comment]
Concept ACK

File: src/wallet/test/wallet_tests.cpp (hunk 1 above)
Comment (Eunovo) [reply src/wallet/test/wallet_tests.cpp:91]: Calling AddWalletDescriptor with a descriptor that's already in wallet, calls UpdateWalletDescriptor which calls CanUpdateWalletDescriptor.  This is what happens on the second call to AddWalletDescriptor.

**Comment by achow101** [comment]
ACK fa0993462b3bc8db40c1a6ea2e7f5fd4a22353a6

**Review by BrandonOdiwuor — COMMENTED** [review]
Code Review ACK fa0993462b3bc8db40c1a6ea2e7f5fd4a22353a6

**Review by rkrux — COMMENTED** [review]
> The importdescriptors RPC sets the range for all non-ranged descriptors to [0,1] in every request so this error cannot be triggered using the RPC.

I checked that the `importdescriptors` adds a 1 to range end if a range is given in the request.

> that this error may be unexpectedly triggered when " experimenting with non-ranged descriptors in custom wallet workflows.

The issue seems quite peculiar in that it highlights an issue within an internal function instead of the full functionality, makes sense to verify the fix using a unit test.

File: src/wallet/test/wallet_tests.cpp [hunk 2]
```diff
@@ -73,6 +73,27 @@ static void AddKey(CWallet& wallet, const CKey& key)
...
 
+BOOST_FIXTURE_TEST_CASE(update_non_range_descriptor, TestingSetup)
+{
+    CWallet wallet(m_node.chain.get(), "", CreateMockableWalletDatabase());
+    {
+        LOCK(wallet.cs_wallet);
+        wallet.SetWalletFlag(WALLET_FLAG_DESCRIPTORS);
+        auto key{GenerateRandomKey()};
+        auto desc_str{"combo(" + EncodeSecret(key) + ")"};
+        for (size_t i = 0; i < 2; i++)
```
Comment (rkrux) [inline src/wallet/test/wallet_tests.cpp:84]: Nit: Although the test name is present but it might be helpful to mention why the loop is there, i.e., to update the descriptor by calling `AddWalletDescriptor` multiple times with the same descriptor.

File: src/wallet/scriptpubkeyman.cpp [hunk 3]
```diff
@@ -2852,6 +2852,11 @@ bool DescriptorScriptPubKeyMan::CanUpdateToWalletDescriptor(const WalletDescript
         return false;
     }
 
+    if (!descriptor.descriptor->IsRange()) {
+        // Skip range check for non-range descriptors
+        return true;
+    }
+
     if (descriptor.range_start > m_wallet_descriptor.range_start ||
```
Comment (rkrux) [inline src/wallet/scriptpubkeyman.cpp:2860]: Nit: Tying these 2 if blocks with an `else if` would be nice, although not necessary because the first if returns.

**Review by rkrux — COMMENTED** [review]
Concept ACK fa0993462b3bc8db40c1a6ea2e7f5fd4a22353a6

I notice while running the unit tests that it warns about a lack of assertions. Maybe it's expecting a boost check?

```bash
wallet/test/wallet_tests.cpp:76: Entering test case "update_non_range_descriptor"
Test case wallet_tests/update_non_range_descriptor did not check any assertions
wallet/test/wallet_tests.cpp:76: Leaving test case "update_non_range_descriptor"; testing time: 38813us
```

**Comment by Eunovo** [comment]
Rebased https://github.com/bitcoin/bitcoin/pull/32344/commits/fa0993462b3bc8db40c1a6ea2e7f5fd4a22353a6 to https://github.com/bitcoin/bitcoin/pull/32344/commits/97d383af6d54b463da64f45680a146d7e93eb146

Simplified update non-range descriptor unit test and fixed this warning:

> I notice while running the unit tests that it warns about a lack of assertions. Maybe it's expecting a boost check?
> 
> ```shell
> wallet/test/wallet_tests.cpp:76: Entering test case "update_non_range_descriptor"
> Test case wallet_tests/update_non_range_descriptor did not check any assertions
> wallet/test/wallet_tests.cpp:76: Leaving test case "update_non_range_descriptor"; testing time: 38813us
> ```

File: src/wallet/test/wallet_tests.cpp (hunk 2 above)
Comment (Eunovo) [reply src/wallet/test/wallet_tests.cpp]: Decided to simplify the test. See https://github.com/bitcoin/bitcoin/pull/32344/commits/97d383af6d54b463da64f45680a146d7e93eb146

File: src/wallet/scriptpubkeyman.cpp (hunk 3 above)
Comment (Eunovo) [reply src/wallet/scriptpubkeyman.cpp:2860]: I wasn't satisfied with how this would look, so I left it as-is.

File: src/wallet/test/wallet_tests.cpp [hunk 4]
```diff
@@ -73,6 +73,25 @@ static void AddKey(CWallet& wallet, const CKey& key)
...
+        auto key{GenerateRandomKey()};
+        auto desc_str{"combo(" + EncodeSecret(key) + ")"};
+        FlatSigningProvider provider;
+        std::string error;
+        auto descs{Parse(desc_str, provider, error, /* require_checksum=*/ false)};
+        auto& desc{descs.at(0)};
+        WalletDescriptor w_desc{std::move(desc), 0, 0, 0, 0};
+        BOOST_CHECK(wallet.AddWalletDescriptor(w_desc, provider, "", false));
+        // Wallet should update the non-range descriptor successfully
+        BOOST_CHECK(wallet.AddWalletDescriptor(w_desc, provider, "", false));
```
Comment (rkrux) [inline src/wallet/test/wallet_tests.cpp:91]: Nice, I did consider removing the loop in the previous review but decided against it so as to simulate a similar flow like this one in a loop: https://github.com/bitcoin/bitcoin/blob/64697529523705f5a411ca893060429afcd5cd47/src/wallet/wallet.cpp#L4131-L4132

However, I did check now that in `GetDescriptorScriptPubKeyMan` the `ScriptPubKeyMan` is gotten via `descriptor.id`, which would remain same whether the `w_desc` reference is same or not.
https://github.com/bitcoin/bitcoin/blob/64697529523705f5a411ca893060429afcd5cd47/src/wallet/wallet.cpp#L3686-L3688

So, overall fine with this approach.

**Review by rkrux — APPROVED** [review]
ACK 97d383a

**Review by furszy — COMMENTED** [review]
It would be good to describe the steps to replicate the issue via RPC.
Including a range in a non-ranged descriptor import should cause the process to fail before reaching the wallet descriptor update function.

This step-by-step description would also allow us to convert the unit test into a functional test, which would be ideal, as it's simpler to maintain.

**Comment by Eunovo** [comment]
> Including a range in a non-ranged descriptor import should cause the process to fail before reaching the wallet descriptor update function.

AFAICT this will cause `importdescriptor` to throw an error with the message "Range should not be specified for an un-ranged descriptor"

**Comment by furszy** [comment]
> > Including a range in a non-ranged descriptor import should cause the process to fail before reaching the wallet descriptor update function.
> 
> AFAICT this will cause `importdescriptor` to throw an error with the message "Range should not be specified for an un-ranged descriptor"

Then how can the user trigger the error being solved here? If it can't be triggered by the user, we're talking about an extra guard rather than a fix — which is fine as well, but it would be better to label the PR differently, since it won't need to be backported.

**Comment by rkrux** [comment]
> Then how can the user trigger the error being solved here? If it can't be triggered by the user, we're talking about an extra guard rather than a fix — which is fine as well, but it would be better to label the PR differently, since it won't need to be backported.

Agree that the PR can be labeled differently.

> When attempting to add a non-ranged descriptor with a start/end range of [0,0] via AddWalletDescriptor, an error may appear

The issue #31728 description states that it is triggered via `AddWalletDescriptor`, which is an internal function & not exposed to the end user. I agree with the expectation set in the issue and this corresponding fix does seem to improve the internal functions and their understanding. 

> it can lead to confusion and error messages when using or experimenting with non-ranged descriptors in custom wallet workflows.

I feel that the issue need not labeled as a 'Bug' because the author mentions it is triggered while experimenting with custom flows.

**Comment by achow101** [comment]
ACK 97d383af6d54b463da64f45680a146d7e93eb146
