### PR TITLE
ci: Do not try to install for fuzz builds

### LINKED ISSUE #32001: ci: `native_fuzz_with_*` jobs are broken
Noticed in https://github.com/bitcoin-core/qa-assets/pull/219.

https://cirrus-ci.com/task/4864208556261376?logs=ci#L7169:
```bash
[100%] Building CXX object src/test/fuzz/CMakeFiles/fuzz.dir/__/__/wallet/test/fuzz/notifications.cpp.o
[100%] Building CXX object src/test/fuzz/CMakeFiles/fuzz.dir/__/__/wallet/test/fuzz/scriptpubkeyman.cpp.o
[100%] Building CXX object src/test/fuzz/CMakeFiles/fuzz.dir/__/__/wallet/test/fuzz/spend.cpp.o
[100%] Building CXX object src/test/fuzz/CMakeFiles/fuzz.dir/__/__/wallet/test/fuzz/wallet_bdb_parser.cpp.o
[100%] Linking CXX executable fuzz
[100%] Built target fuzz
gmake: *** No rule to make target 'install'.  Stop.
Build failure. Verbose build follows.
+ echo 'Build failure. Verbose build follows.'
```

### PR DESCRIPTION
**Pull request by hebasto**
This PR is a follow-up to https://github.com/bitcoin/bitcoin/pull/31844 and extends the changes from fb0546b1c5ebb858605bef4c9fa001782e0ab213 to all fuzz builds in the CI.

Fixes https://github.com/bitcoin/bitcoin/issues/32001.

### CODE REVIEW

File: ci/test/00_setup_env_native_msan.sh [hunk 1]
```diff
@@ -16,7 +16,7 @@ export CONTAINER_NAME="ci_native_msan"
 export PACKAGES="ninja-build"
 # BDB generates false-positives and will be removed in future
 export DEP_OPTS="DEBUG=1 NO_BDB=1 NO_QT=1 CC=clang CXX=clang++ CFLAGS='${MSAN_FLAGS}' CXXFLAGS='${MSAN_AND_LIBCXX_FLAGS}'"
-export GOAL="install"
+export GOAL="all"
```
Comment (dergoegge) [inline ci/test/00_setup_env_native_msan.sh:19]: Why does this need to change? The regular msan job is not broken afaik.

Comment (Sjors) [reply ci/test/00_setup_env_native_msan.sh:19]: It does seem more correct. Perhaps in the future we can even warn users when they're about to install a debug, sanitizer or otherwise potentially very slow binary.

Comment (hebasto) [reply ci/test/00_setup_env_native_msan.sh]: > Why does this need to change? The regular msan job is not broken afaik.

Right. It wasn't my intention. Reverted.

**Comment by hebasto** [comment]
> Where in the CMake code is `$GOAL` processed?
> 
> I see this in the CI code:
> 
> ```shell
> bash -c "cmake --build . $MAKEJOBS --target all $GOAL" 
> ```
> 
> But after that I lost track.

This is the only place.

**Comment by marcofleon** [comment]
> Is it possible to open a PR to the QA repo that demonstrates that this actually fixes the problem?

Trying it here:
https://github.com/bitcoin-core/qa-assets/pull/219

**Review by dergoegge — APPROVED** [review]
utACK a3c3f37e71efc1ad13fcad49b1ac651e5843b26b

This fixes the build issue seen earlier on https://github.com/bitcoin-core/qa-assets/pull/219
