### PR TITLE
miniscript: explicit cast instead of comparing integers of different signs

### LINKED ISSUE #27381: miniscript: comparison of integers of different signs
This is being emitted with [GCC 10.2.1](https://packages.debian.org/bullseye/g++-arm-linux-gnueabihf), in some CI jobs: i.e https://github.com/bitcoin/bitcoin/pull/25972/checks?check_run_id=12423693655, or https://github.com/bitcoin/bitcoin/pull/25972/checks?check_run_id=12423693651 (where we actually turn on all our warning flags with depends builds).
```bash
In file included from test/miniscript_tests.cpp:19:
./script/miniscript.h:1197:71: error: comparison of integers of different signs: 'typename iterator_traits<int *>::difference_type' (aka 'int') and 'const uint32_t' (aka 'const unsigned int') [-Werror,-Wsign-compare]
                    return std::count(subs.begin(), subs.end(), true) >= node.k;
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~
test/miniscript_tests.cpp:346:34: note: in instantiation of function template specialization 'miniscript::Node<CPubKey>::IsSatisfiable<(lambda at test/miniscript_tests.cpp:346:48)>' requested here
        bool satisfiable = node->IsSatisfiable([](const Node&) { return true; });
                                 ^
1 error generated.
```

cc @darosior

### PR DESCRIPTION
**Pull request by darosior**
Fixes #27381

### CODE REVIEW

File: src/script/miniscript.h [hunk 1]
```diff
@@ -1194,7 +1194,7 @@ struct Node {
                 case Fragment::OR_I:
                     return subs[0] || subs[1];
                 case Fragment::THRESH:
-                    return std::count(subs.begin(), subs.end(), true) >= node.k;
+                    return unsigned(std::count(subs.begin(), subs.end(), true)) >= node.k;
```
Comment (stickies-v) [inline src/script/miniscript.h:1197]: Maybe best to avoid C-style casts?

```suggestion
                    return static_cast<uint32_t>(std::count(subs.begin(), subs.end(), true)) >= node.k;
```

**Review by stickies-v — APPROVED** [review]
ACK 9a54d88c8cb0c5d529f388c2ce53008e1ff126dd
