### PR TITLE
Smarter coordination of change and fee in CreateTransaction.

### LINKED ISSUE #9466: Prevent fee overpayment when nFeeNeeded decreases in CreateTransaction iterations
When a pass of CreateTransaction fails to select enough bitcoin to meet the nFeeNeeded the next pass through may select a far smaller collection of inputs.  Currently it will continue to use the old fee amount based on the larger set of inputs, which can cause a non-trivial over-payment.

This may be the cause of the behavior reported here: https://www.reddit.com/r/Bitcoin/comments/5ltw5n/bitcoin_core_v0131_sends_enormously_high_fee/

Long ago fixing this was tricky due to a catch-22 between signing the transaction and knowing how much fee was required.  But after #9465 the whole algorithm will run using a dummy signature, so when there is already a change output fixing up the fee after finding a sufficient transaction should be a matter of a ~2 line change.

### PR DESCRIPTION
**Pull request by morcos**
Resolves #9466 

~~I feel bad making the wallet coin selection even more spaghetti like, but I think this is a huge improvement over the existing code and it's relatively simple to understand.~~

Essentially once you pick coins and if you have change, then try to reduce that change to meet the fee instead of repicking coins.  Since we aim to have change of .01 BTC if we can't make an exact match initially, this is usually more than sufficient to be reduced only slightly to pay for the fee.

I think for 0.15, we could take on a wholesale rewrite of the algorithm, but thats too much to ask for before 0.14. This however might be worthwhile.

~~I'm open to suggestions on how to make this cleaner or clearer.~~

EDIT: suggest viewing diff with `?w=1`

EDIT 2: This is much simpler now.  Also includes another commit to remove further cases of overpaying fees.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Concept ACK

(Tries to solve issue #4082 et al.)

**Comment by gmaxwell** [comment]
Concept ACK but will be simpler when rebased on #9465.

**Comment by morcos** [comment]
This has been rebased on #9465 (thanks @gmaxwell)

It is now much simpler.   
I added a second commit to almost completely resolve #9466

**Comment by gmaxwell** [comment]
Beautiful. utACK.  Should be rebased on the latest nit-update of 9465 (sorry about that), I expect it will do so cleanly.

We should open an issue to also resolve these behaviors when nSubtractFeeFromAmount is used; I can understand why you didn't cover those in this PR.

**Comment by sipa** [comment]
Needs rebase on #9465 merge.

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -2534,8 +2534,17 @@ bool CWallet::CreateTransaction(const vector<CRecipient>& vecSend, CWalletTx& wt
                     return false;
                 }
 
-                if (nFeeRet >= nFeeNeeded)
+                if (nFeeRet >= nFeeNeeded) {
+                    // Reduce fee to only the needed amount if we have change output to increase
+                    // Do not do this if fee was paid by payee
+                    if (nFeeRet > nFeeNeeded && nChangePosInOut != -1 && nSubtractFeeFromAmount == 0) {
```
Comment (sdaftuar) [inline src/wallet/wallet.cpp]: I guess there's an edge case left here, where if there's no change output and the fee difference is very large, then we won't reduce the fee?

It might be nice to refactor the change-adding logic so that we could add change in that scenario, though I don't want to hold up this PR which is already a strict improvement, do you think it's worth adding a comment that points this out though for future reference?

**Review by sdaftuar — COMMENTED** [review]
Looks good, though I guess it needs to be rebased.

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -2550,14 +2534,66 @@ bool CWallet::CreateTransaction(const vector<CRecipient>& vecSend, CWalletTx& wt
                     return false;
                 }
 
-                if (nFeeRet >= nFeeNeeded)
+                if (nFeeRet >= nFeeNeeded) {
+                    // Reduce fee to only the needed amount if we have change output to increase
+                    // Do not do this if fee was paid by payee
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: I might be missing something, but instead of "Do not", the comment should read "TODO". Otherwise, it would imply that it is ok for the payee to lose coins whereas for the payer it is not.

**Review by maflcko — COMMENTED** [review]
utACK 53171a915e17e83814328cc3792554159a950757, though I'd prefer to have the edge cases mentioned by @sdaftuar and me documented as todos.

File: src/wallet/wallet.cpp [hunk 3]
```diff
@@ -2550,14 +2534,66 @@ bool CWallet::CreateTransaction(const vector<CRecipient>& vecSend, CWalletTx& wt
...
+                    }
                     break; // Done, enough fee included.
+                }
+
+                // Try to reduce change to include necessary fee
+                if (nChangePosInOut != -1 && nSubtractFeeFromAmount == 0) {
+                    CAmount additionalFeeNeeded = nFeeNeeded - nFeeRet;
+                    vector<CTxOut>::iterator change_position = txNew.vout.begin()+nChangePosInOut;
+                    // Only reduce change if remaining amount is still a large enough output (CENT/2)
+                    if (change_position->nValue >= CENT/2 + additionalFeeNeeded) {
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: can you explain why CENT is used instead of MIN_CHANGE, please?

File: src/wallet/wallet.cpp [hunk 4]
```diff
@@ -2550,14 +2534,66 @@ bool CWallet::CreateTransaction(const vector<CRecipient>& vecSend, CWalletTx& wt
...
+                        nFeeRet -= extraFeePaid;
+                    }
                     break; // Done, enough fee included.
+                }
+
+                // Try to reduce change to include necessary fee
+                if (nChangePosInOut != -1 && nSubtractFeeFromAmount == 0) {
+                    CAmount additionalFeeNeeded = nFeeNeeded - nFeeRet;
+                    vector<CTxOut>::iterator change_position = txNew.vout.begin()+nChangePosInOut;
+                    // Only reduce change if remaining amount is still a large enough output (CENT/2)
```
Comment (MarcoFalke) [inline src/wallet/wallet.cpp]: nit: No need to mention code specific values in the comment

File: src/wallet/wallet.cpp (hunk 1 above)
Comment (gmaxwell) [inline src/wallet/wallet.cpp]: it's pretty easy to compute exactly the amount of additional fee adding a change output would imply. So the test becomes if not subtractfrom   and excessfee >= CENT/2 + changeaddfee; then set the change to excessfee-changeaddfee.   Doing so without creating a hairball with change added in multiple places... less fun.  

Similarly, the remove side could consider eliminating the change output, if doing so would not overpay by too much. (A conservative value would be the changeaddfee but a larger value would be a lot more useful)  both both probably better done in another PR.

Comment (morcos) [inline src/wallet/wallet.cpp]: Yes my concern is the gap between desired change amounts (CENT/2) and fee overpayments is quite big.  Most of the time even if a fee overpayment was bigger than dust, it wouldn't be so big that you'd actually want to create an output with it.  

I think fixing that should be combined with more robust handling of the minimum output size a wallet would create.  Perhaps then there would be cases where we feel we got unlucky with coin selection and we try again to have less overpayment or more reasonable size change.

The coin selection algorithm is stupid now.  Trying to find an exact match makes no sense in a world where every transaction pays fee.  So I'd rather not continue adding patches and improvements before we try to improve the basic strategy.  I'm happy to give that a shot after 0.14.  And I think we can avoid most of these problems from the beginning...

**Comment by morcos** [comment]
Rebased after #9465 and addressed comments.

**Comment by sipa** [comment]
utACK 20449ef09edf8f4f51a3e531d947dd89973c2a31

**Comment by MarcoFalke** [comment]
utACK 20449ef. Thanks for addressing the feedback so quick!

**Comment by sdaftuar** [comment]
utACK 20449ef09

**Comment by gmaxwell** [comment]
re-ACK.

**Comment by Xekyo** [comment]
(Sorry, just seeing this now.) The proposed fix is much better than the previous behavior (#4082), also especially for computational effort.

However, the issue is due to the order that a transaction is created: Since the fee is being estimated before the inputs are selected, when the number of selected inputs deviates from the initial estimate, the fee estimate is off.  This problem stems from the *effective target* increasing with each collected input, because the effective target is increased by the cost of one input for every input we select.

Instead we could estimate the *fee rate* before the inputs are selected and deduct the cost of each input from its value upon selection. 

`effectiveValue = utxo.value - feePerByte × bytesPerInput`

We'd measure the "effective contribution" of the input towards the fixed cost of `target + transaction overhead + outputs`. That way, we always get the fee right.
If that's not hard to put in now, that would solve the fee estimation right away, without the post-selection change adjustment.

**Comment by Xekyo** [comment]
utACK https://github.com/bitcoin/bitcoin/commit/20449ef09edf8f4f51a3e531d947dd89973c2a31

**Comment by TheBlueMatt** [comment]
utACK 20449ef09edf8f4f51a3e531d947dd89973c2a31

**Comment by RHavar** [comment]
When's a fix for this coming? I've been losing a lot of money, to what I suspect is this bug, just $50 last transaction:
https://live.blockcypher.com/btc/tx/a92a609f1ebdcd5a2b658a35ed562ac8661a90daf773a7a807a71bd8e1990a6a/

$ bitcoin-cli estimatefee 4
0.00101654

$ bitcoin-cli listunspent | grep amount | wc -l
692
