### PR TITLE
wallet: be able to specify a wallet name and passphrase to migratewallet

### LINKED ISSUE #27048: migratewallet help is misleading about encrypted wallets
The help tells me I should unlock my encrypted wallet:

```
> help migratewallet

...
Requires wallet passphrase to be set with walletpassphrase call if wallet is encrypted.
```

But when I do so and attempt to migrate the wallet I'm told that I've entered my password for needlessly:

```
> migratewallet

Error: migratewallet on encrypted wallets is currently unsupported.
```

v24.0.1

### PR DESCRIPTION
**Pull request by achow101**
`migratewallet` currently operates on wallets that are already loaded, however this is not necessarily required, and in the future, not possible once the legacy wallet is removed. So we need to also be able to give the wallet name to migrate.

Additionally, the passphrase is required when migrating a wallet. Since a wallet may not be loaded when we migrate, and as we currently unload wallets when migrating, we need the passphrase to be given to `migratewallet` in order to migrate encrypted wallets.

Fixes #27048

### CODE REVIEW

File: src/wallet/rpc/wallet.cpp [hunk 1]
```diff
@@ -727,16 +729,28 @@ static RPCHelpMan migratewallet()
...
+            util::Result<MigrationResult> res;
+            if (wallet) {
+                if (wallet->IsCrypted()) {
+                    throw JSONRPCError(RPC_WALLET_WRONG_ENC_STATE, "Error: migratewallet on encrypted wallets is currently unsupported.");
+                }
+
+                res = MigrateLegacyToDescriptor(std::move(wallet), context);
+            } else {
+                res = MigrateLegacyToDescriptor(wallet_name, context);
+            }
```
Comment (ishaanam) [inline src/wallet/rpc/wallet.cpp:756]: In 433f9f8d7539efc26b952063d6127315606d248e "rpc: Allow users to specify wallet name for migratewallet"

These lines don't seem to have any test coverage. Also, if `GetWallet` is unable to get the wallet, shouldn't an error be thrown at that point?

**Review by ishaanam — COMMENTED** [review]
Concept ACK

File: src/wallet/wallet.cpp [hunk 2]
```diff
@@ -4112,26 +4112,25 @@ bool DoMigration(CWallet& wallet, WalletContext& context, bilingual_str& error,
 
 util::Result<MigrationResult> MigrateLegacyToDescriptor(std::shared_ptr<CWallet>&& wallet, WalletContext& context)
 {
-    MigrationResult res;
     bilingual_str error;
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp:4115]: It's being used by `MakeWalletDatabase`.

File: src/wallet/rpc/wallet.cpp [hunk 3]
```diff
@@ -727,16 +729,28 @@ static RPCHelpMan migratewallet()
...
-
-            if (wallet->IsCrypted()) {
-                throw JSONRPCError(RPC_WALLET_WRONG_ENC_STATE, "Error: migratewallet on encrypted wallets is currently unsupported.");
+            std::string wallet_name;
+            if (GetWalletNameFromJSONRPCRequest(request, wallet_name)) {
+                if (!(request.params[0].isNull() || request.params[0].get_str() == wallet_name)) {
+                    throw JSONRPCError(RPC_INVALID_PARAMETER, "RPC endpoint wallet and wallet_name parameter specify different wallets");
+                }
+            } else {
+                wallet_name = request.params[0].get_str();
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/rpc/wallet.cpp]: Added an error.

File: src/wallet/rpc/wallet.cpp (hunk 1 above)
Comment (achow101) [reply src/wallet/rpc/wallet.cpp]: > These lines don't seem to have any test coverage.

Tests are added in a later commit.

> Also, if `GetWallet` is unable to get the wallet, shouldn't an error be thrown at that point?

No, `GetWallet` only looks for wallets that have been loaded. But it is necessary to be able to migrate wallets that are not currently loaded. `MigrateLegacyToDescriptor` will try loading the wallet and result in an error if it does not actually exist.

File: src/wallet/wallet.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ishaanam) [reply src/wallet/wallet.cpp:4115]: I don't think that `MakeWalletDatabase` is directly run in this function, the `error` on src/wallet/wallet.cpp:4131 is used for that.

[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp]: Ah, was looking at the wrong line. Removed.

File: test/functional/wallet_migration.py [hunk 4]
```diff
@@ -399,11 +399,47 @@ def test_pk_coinbases(self):
...
+
+        addr = wallet.getnewaddress()
+        txid = default.sendtoaddress(addr, 1)
+        self.generate(self.nodes[0], 1)
+        bals = wallet.getbalances()
+
+        wallet.unloadwallet()
+
+        assert_raises_rpc_error(-8, "RPC endpoint wallet and wallet_name parameter specify different wallets", wallet.migratewallet, "someotherwallet")
+        assert_raises_rpc_error(-8, "Either RPC endpoint wallet or wallet_name parameter must be used", self.nodes[0].migratewallet)
```
Comment (ishaanam) [inline test/functional/wallet_migration.py:434]: To fix failing CI:
```suggestion
        assert_raises_rpc_error(-8, "Either RPC endpoint wallet or wallet_name parameter must be provided", self.nodes[0].migratewallet)
```

Comment (w0xlt) [reply test/functional/wallet_migration.py:434]: This fixes the CI error.

**Review by w0xlt — COMMENTED** [review]
Approach ACK

File: test/functional/wallet_migration.py (hunk 4 above)
Comment (achow101) [reply test/functional/wallet_migration.py:434]: Fixed.

**Review by w0xlt — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/26595/commits/8d957e3b2f56f07d1c0af1c843d396cc29aecb94

**Review by ishaanam — COMMENTED** [review]
ACK 8d957e3b2f56f07d1c0af1c843d396cc29aecb94

**Review by furszy — COMMENTED** [review]
Approach ACK, some comments:

* Thinking that the `MigrateLegacyToDescriptor` overload isn’t really needed, we only call this function from a single place which always receives a wallet name/path.
Could instead decouple the “UnloadWalletForMigration” process into a separate function, and call it at the beginning of the migration process if `GetWallet(wallet_name)` returns a wallet. e.g. https://github.com/furszy/bitcoin-core/commit/456780b255af490a6dd44e710184cf85106f5390
This would let us remove the added `Result` default constructor too.

* Would be good to add a test for a wallet migration by absolute path (the “notloaded” test provides the wallet dir name and relies on the wallet internals to detect it as a directory inside the wallets dir).
e.g.
```python3
# Test migration by absolute path
wallet_file_path = os.path.join(self.nodes[0].datadir, "regtest/wallets", "notloaded")
self.nodes[0].migratewallet(wallet_file_path)
# check migration..
```

**Comment by achow101** [comment]
> * Thinking that the `MigrateLegacyToDescriptor` overload isn’t really needed, we only call this function from a single place which always receives a wallet name/path.
>   Could instead decouple the “UnloadWalletForMigration” process into a separate function, and call it at the beginning of the migration process if `GetWallet(wallet_name)` returns a wallet. e.g. [furszy@456780b](https://github.com/furszy/bitcoin-core/commit/456780b255af490a6dd44e710184cf85106f5390)
>   This would let us remove the added `Result` default constructor too.

Done as suggested

> * Would be good to add a test for a wallet migration by absolute path (the “notloaded” test provides the wallet dir name and relies on the wallet internals to detect it as a directory inside the wallets dir).

Added

File: src/util/result.h [hunk 5]
```diff
@@ -41,6 +41,7 @@ class Result
     friend bilingual_str ErrorString(const Result<FT>& result);
 
 public:
+    Result() = default;
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/util/result.h]: Removed

File: src/wallet/wallet.cpp [hunk 6]
```diff
@@ -4161,6 +4161,9 @@ util::Result<MigrationResult> MigrateLegacyToDescriptor(const std::string& walle
     {
         LOCK(local_wallet->cs_wallet);
 
+        // Unlock the wallet
+        local_wallet->Unlock(passphrase);
+
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp]: Done

**Comment by achow101** [comment]
Rebased for a silent merge conflict.

**Review by furszy — APPROVED** [review]
Code review ACK 7ebfd51

**Comment by achow101** [comment]
Rebased for another silent merge conflict.

**Review by furszy — APPROVED** [review]
rebase diff ACK ee620e99

**Comment by achow101** [comment]
Added a commit to update the help text about encrypted wallets.

**Review by furszy — APPROVED** [review]
ACK 3a6965d5

**Comment by fanquake** [comment]
Looks like this should also be backported to 24.x?

File: src/wallet/rpc/wallet.cpp [hunk 7]
```diff
@@ -738,16 +741,27 @@ static RPCHelpMan migratewallet()
...
+                }
+                wallet_name = request.params[0].get_str();
             }
 
-            WalletContext& context = EnsureWalletContext(request.context);
+            // Note that the walletpassphrase is stored in request.params[1] which is not mlock()ed
+            SecureString wallet_pass;
+            wallet_pass.reserve(100);
+            // TODO: get rid of this .c_str() by implementing SecureString::operator=(std::string)
+            // Alternately, find a way to make request.params[0] mlock()'d to begin with.
```
Comment (john-moffett) [inline src/wallet/rpc/wallet.cpp:760]: Nit: request.params[1]

File: src/wallet/rpc/wallet.cpp [hunk 8]
```diff
@@ -738,16 +741,27 @@ static RPCHelpMan migratewallet()
...
+            wallet_pass = request.params[1].isNull() ? "" : request.params[1].get_str().c_str();
```
Comment (john-moffett) [inline src/wallet/rpc/wallet.cpp:761]: Possibly for another PR (and possibly a dumb question), but why can't we do 

```c++
if (!request.params[1].isNull()) wallet_pass.assign(request.params[1].get_str());
```

rather than use `.c_str()` (and in the other existing places)? This is supported since C++17.

**Review by john-moffett — APPROVED** [review]
tACK 3a6965d5606bb8e8f750341dfd6dac12aa7d4870

**Review by ishaanam — COMMENTED** [review]
reACK 3a6965d5606bb8e8f750341dfd6dac12aa7d4870

Currently if the `wallet_name` does not specify an actual wallet, the following error is thrown:
> Wallet file verification failed. Failed to load database path '/tmp/bitcoin_func_test_w3iehdpt/node0/regtest/wallets/wrong_wallet_name'. Path does not exist. (-4)

It would make more sense to throw a simpler error from `migratewallet` (as opposed to from `MakeDatabase`). This along with the additional test coverage I have suggested below could be implemented in this PR or as a follow-up.

File: src/wallet/rpc/wallet.cpp (hunk 8 above)
Comment (achow101) [reply src/wallet/rpc/wallet.cpp]: I've updated the passphrase handling to match what #27068 does

File: src/wallet/wallet.cpp [hunk 9]
```diff
@@ -4165,32 +4165,19 @@ bool DoMigration(CWallet& wallet, WalletContext& context, bilingual_str& error,
...
-    fs::path backup_path = this_wallet_dir / backup_filename;
-    if (!wallet->BackupWallet(fs::PathToString(backup_path))) {
-        return util::Error{_("Error: Unable to make a backup of your wallet")};
-    }
-    res.backup_path = backup_path;
-
-    // Unload the wallet so that nothing else tries to use it while we're changing it
-    if (!RemoveWallet(context, wallet, /*load_on_start=*/std::nullopt, warnings)) {
-        return util::Error{_("Unable to unload the wallet before migrating")};
+    // If the wallet is still loaded, unload it wallet so that nothing else tries to use it while we're changing it
```
[the remark this answers is not in the document]
Comment (achow101) [reply src/wallet/wallet.cpp]: Fixed

**Comment by achow101** [comment]
> > Wallet file verification failed. Failed to load database path '/tmp/bitcoin_func_test_w3iehdpt/node0/regtest/wallets/wrong_wallet_name'. Path does not exist. (-4)
> 
> It would make more sense to throw a simpler error from `migratewallet` (as opposed to from `MakeDatabase`).

This is the same error that we currently give for `loadwallet`. I'm going to leave it as is so these are consistent with each other, but I agree it could be improved.

**Comment by fanquake** [comment]
@pinheadmz review?

**Review by furszy — APPROVED** [review]
rebase diff ACK 3e521b2e

**Review by john-moffett — APPROVED** [review]
ACK 3e521b2eb13799e11866562cfda4dc0bd3f7d6b9

**Comment by ishaanam** [comment]
reACK 3e521b2eb13799e11866562cfda4dc0bd3f7d6b9

File: test/functional/wallet_migration.py [hunk 10]
```diff
@@ -400,11 +400,72 @@ def test_pk_coinbases(self):
...
+        default = self.nodes[0].get_wallet_rpc(self.default_wallet_name)
+
+        addr = wallet.getnewaddress()
+        txid = default.sendtoaddress(addr, 1)
+        self.generate(self.nodes[0], 1)
+        bals = wallet.getbalances()
+
+        wallet.unloadwallet()
+
+        wallet_file_path = os.path.join(self.nodes[0].datadir, "regtest", "wallets", "noloaded2")
```
Comment (pinheadmz) [inline test/functional/wallet_migration.py:460]: I think you are creating a wallet with the letter "t" in the name, but the path you pass to migratewallet has no "t":

`notloaded2` vs `noloaded2`

I think this isn't causing test failure because `test_unloaded_by_path()` is not added to the `run_test` list ...?

Comment (furszy) [reply test/functional/wallet_migration.py:460]: yeah, the test case is not being called. Nice catch.

Comment (achow101) [reply test/functional/wallet_migration.py]: Nice catch! Fixed.

**Review by john-moffett — APPROVED** [review]
reACK 9486509be65f09174a0cb50a337cac58a0c09de4

**Review by pinheadmz — APPROVED** [review]
ACK 9486509be65f09174a0cb50a337cac58a0c09de4

reviewed code, ran tests, tested on regtest with cli commands

<details><summary>Show Signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

ACK 9486509be65f09174a0cb50a337cac58a0c09de4
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEE5hdzzW4BBA4vG9eM5+KYS2KJyToFAmP2L3gACgkQ5+KYS2KJ
yToaJA/9GCc9Y84y5GfTPsmAUUYV/jFKr5Z9lDIATQca+Ou323CQ76CF00IQiyBB
ECtPlFJSPxaaKac4k5QmwT4BA4EgzcTKKVhjCVlorHyJQYk5yYBD5xOk2G0fPthS
VA3CkmikXrpb7YGcxiKVvDLrOQ3h16+S2CI6/DViChgJ32cGbJ+WjZsqIb0Mx6tR
C7AtMPMjmjzt+oAbuzIhGzCfjglygUngGSIZbIotjRwgQ75ANJEApLYbUNyddz4a
6Pv9+sArKgvkNPzeOMxUbwjR3esTEAR2k70JpnZlxsf3alu6Jp6a8l7XkxZDoh5/
xyT/jdyHCqCiD0ZFpEAc2q4chFZgXzoMr7dcXesSiHzf64F8TStlG7ZKJn0EAPhG
Esal14rEIXh7OHVD5NHF1qOviGgzhrXBmkecbsX2jj0pUpcXg/cqH9Ln0bzYc//b
WBrc8pe1QPijzOlSXiEsHff3eDB8PWgK6uIgLld0y5bOgQ7YD6iex+exROzNcXK6
i5s8hJ8BNR0/sPWUt5zRA+BJ/pdQiHaJ3e1H2/X+UOkQuCKkLsyh1cLf0BI6Y9uJ
tUzgd3XDjh9wAUDPzf16o0mbOHzClK/6ak+wv6+WlubdCQXFMgOJdS3LWdDWgIE0
vwJluifh8hWN+vraJcM2ctDGL4KtdAndJ/UyznTXLBuBhhkmNXI=
=iPeZ
-----END PGP SIGNATURE-----
```

pinheadmz's public key is [on keybase](https://keybase.io/pinheadmz/pgp_keys.asc?fingerprint=e61773cd6e01040e2f1bd78ce7e2984b6289c93a)
</details>

**Review by furszy — COMMENTED** [review]
ACK 9486509b

**Comment by fanquake** [comment]
Added to #26878 for backporting to 24.x.
