### PR TITLE
addrman: Avoid crash on corrupt data, Force Check after deserialize

### LINKED ISSUE #22503: Addrman check failure info.nLastSuccess is 0 even though info.fInTried
Using #22493 + #22500 gives the failure mentioned in the subject line

[crash-2e85f5a8d3623503ed9c668d02dc65c5bb573df1.log](https://github.com/bitcoin/bitcoin/files/6846105/crash-2e85f5a8d3623503ed9c668d02dc65c5bb573df1.log)

### LINKED ISSUE #22504: Addrman check failure info.nRefCount is non-zero even though !info.fInTried
Using #22493 + #22500 gives the failure mentioned in the subject line

[crash-6ddb0b69a79d653752c09a9000e9006f43de75fc.log](https://github.com/bitcoin/bitcoin/files/6846129/crash-6ddb0b69a79d653752c09a9000e9006f43de75fc.log)

### LINKED ISSUE #22519: Addrman check failure: info.nLastSuccess is negative
Using #22493 + #22500 gives the failure mentioned in the subject line

[crash-f11ac19bfb2bcd68149035337afede0e56848596.log](https://github.com/bitcoin/bitcoin/files/6856720/crash-f11ac19bfb2bcd68149035337afede0e56848596.log)

### LINKED ISSUE #22931: Signed Integer-overflow in CAddrInfo::IsTerrible
This may happen when peers.dat is deserialized from disk.

See:

* #22925
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38301

### PR DESCRIPTION
**Pull request by maflcko**
Assert should only be used for program internal logic errors, not to sanitize external user input.

The assert was introduced via the debug-only runtime option `-checkaddrman` in commit 803ef70fd9f65ef800567ff9456fac525bc3e3c2, thus won't need a backport.

Also, it doesn't really make sense to continue when the deserialized addrman doesn't pass the sanity check.

For example, if `nLastSuccess` is negative, it would  later result in integer overflows. Thus, this patch fixes #22931.

Also,
Fixes #22503
Fixes #22504
Fixes #22519

Closes #22498

Steps to test:

```
mkdir -p /tmp/test_235/regtest/
echo 'H4sIAAAAAAAAA/u1f+stZmUGYgELgwPRakfBKBgFo2AUjIJRMApGwSgYBaNgFIyCUTBswdyGpFnLjUKjP9e0bvjYusl6b+L2e7Vs2dd6N//Pua0/xQUALJAn93IQAAA=' | base64 --decode | zcat > /tmp/test_235/regtest/peers.dat
./src/qt/bitcoin-qt -regtest -datadir=/tmp/test_235/ -checkaddrman=1 -printtoconsole | grep -A2 'Loading P2P addresses'
```

Output before:
```
2021-09-10T11:28:37Z init message: Loading P2P addresses…
2021-09-10T11:28:37Z ADDRMAN CONSISTENCY CHECK FAILED!!! err=-16
bitcoin-qt: addrman.cpp:765: void CAddrMan::Check() const: Assertion `false' failed.

(program crashes)
```

Output after:
```
2021-09-10T11:26:00Z init message: Loading P2P addresses…
2021-09-10T11:26:00Z Error: Invalid or corrupt peers.dat (Corrupt data. Consistency check failed with code -16: iostream error). If you believe this is a bug, please report it to https://github.com/bitcoin/bitcoin/issues. As a workaround, you can move the file ("/tmp/test_235/regtest/peers.dat") out of the way (rename, move, or delete) to have a new one created on the next start.

(program exits)
```

### CODE REVIEW

**Comment by mzumsande** [comment]
I agree that corrupt data shouldn't assert.

`Check()` used to be restricted to tests / use of the `checkaddrman` option, it was never run per default. This PR makes it run always for `Unserialize()`, so it introduces stricter rules for the level of inconsistencies we tolerate from peers.dat. 
I think this change of default behavior should be mentioned in the OP and maybe somewhere in the code, because it also introduces new possibilities of p2p addrman poisoning to make us drop our peers.dat - so we should be confident all checks in `Check()` are correct before enabling this.

**Comment by MarcoFalke** [comment]
Thanks, renamed PR title

**Comment by mzumsande** [comment]
Thanks! I think there is a bug in the `addman_serdeser` fuzz test (see CI fail) that would need fixing, see https://github.com/mzumsande/bitcoin/commit/f4840614c0b945460a833ba8e9d0da2df3ce80c3

**Comment by jnewbery** [comment]
With this change, if we have a bug that causes us to write a peers.dat file that's corrupt in any way, then it would mostly be undetected - the addrman would be cleared and startup would continue as normal. As @mzumsande points out, if it's possible to trigger such a bug over p2p, then an adversary could cause victims to lose their entire addrman on restart.

It might be safer to do the `ForceCheck`, but then catch the exception, rename peers.dat to peers.bak, and terminate with some error message like "Corrupt peers.dat file found. addrman database has been wiped and peers.dat has been renamed to peers.bak. Please report this to the Bitcoin Core developers." That way, we'd get bug reports if there was a bug in our serialization code, and there may be a way to salvage the peers.bak file if needed.

File: src/addrman.h [hunk 1]
```diff
@@ -468,7 +468,12 @@ class CAddrMan
             LogPrint(BCLog::ADDRMAN, "addrman lost %i new and %i tried addresses due to collisions or invalid addresses\n", nLostUnk, nLost);
         }
 
-        Check();
+        const int check_code{ForcedCheck()};
+        if (check_code != 0) {
+            throw std::ios_base::failure(strprintf(
+                "Corrupt data. Consistency check failed with code %s.",
+                check_code));
```
Comment (vasild) [inline src/addrman.h:475]: nit: maybe mention "addrman" somewhere in this message. The following looks too generic:
```
2021-08-18T07:12:57Z ERROR: DeserializeDB: Deserialize or I/O error - Corrupt data. Consistency check failed with code -16.: iostream error
```

nit: remove the dot after %s: `with code -16.: iostream error`

**Review by vasild — COMMENTED** [review]
Concept ACK fab42d7dab

I think that the check should also be run (unconditionally) before serialize and if a problem is detected then don't write the corrupted stuff on disk.

Keeping the corrupted `peers.dat` on unserialize seems like a reasonable thing to do, but right now there are no tools to salvage it, so it would be useless. Maybe just stop the startup and ask the user to remove (or rename) the damaged `peers.dat`?

Notice - if it is possible to remotely corrupt `peers.dat`, then currently `master` is even worse than this PR - reading a corrupted `peers.dat` and keep operating with a "corrupted" addrman could lead to undefined behavior.

**Comment by naumenkogs** [comment]
>With this change, if we have a bug that causes us to write a peers.dat file that's corrupt in any way, then it would mostly be undetected - the addrman would be cleared and startup would continue as normal. As @mzumsande points out, if it's possible to trigger such a bug over p2p, then an adversary could cause victims to lose their entire addrman on restart.

> It might be safer to do the ForceCheck, but then catch the exception, rename peers.dat to peers.bak, and terminate with some error message like "Corrupt peers.dat file found. addrman database has been wiped and peers.dat has been renamed to peers.bak. Please report this to the Bitcoin Core developers." That way, we'd get bug reports if there was a bug in our serialization code, and there may be a way to salvage the peers.bak file if needed.

I agree with John.

**Comment by MarcoFalke** [comment]
I agree with @vasild that this is an unrelated bug that already exists. I've created a separate pull to fix that: #22762

**Comment by jonatack** [comment]
The test coverage in #22831 expects a corrupt addrman to raise and abort, so it may need to be updated.

File: src/addrman.h (hunk 1 above)
Comment (MarcoFalke) [reply src/addrman.h]: The new failure mentions the file name `peers.dat`. Is this enough?

```
Error: Invalid or corrupt peers.dat (Corrupt data. Consistency check failed with code -16.: iostream error). If you believe this is a bug, please report it to https://github.com/bitcoin/bitcoin/issues. As a workaround, you can move the file ("/tmp/bitcoin_func_test_ybw3djdd/node0/regtest/peers.dat") out of the way (rename, move, or delete) to have a new one created on the next start.

Comment (MarcoFalke) [reply src/addrman.h]: Thanks, removed dot.

Comment (vasild) [reply src/addrman.h]: `peers.dat` looks even better than `addrman`.

**Comment by MarcoFalke** [comment]
Please review https://github.com/bitcoin/bitcoin/pull/22939 first, which is applies the fix to just one fuzz test (smaller scope).

File: src/addrman.cpp [hunk 2]
```diff
@@ -385,7 +385,12 @@ void CAddrMan::Unserialize(Stream& s_)
         LogPrint(BCLog::ADDRMAN, "addrman lost %i new and %i tried addresses due to collisions or invalid addresses\n", nLostUnk, nLost);
     }
 
-    Check();
+    const int check_code{ForceCheckAddrman()};
+    if (check_code != 0) {
+        throw std::ios_base::failure(strprintf(
+            "Corrupt data. Consistency check failed with code %s",
+            check_code));
```
Comment (vasild) [inline src/addrman.cpp:392]: It would be nice if this mentions "addrman" or "peers.dat". Without it the error message looks too generic, it is unclear where the problem is and the user may freak out that the "corrupt data" applies to the wallet:

> terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  Corrupt data. Consistency check failed with code -1: iostream error

**Review by vasild — APPROVED** [review]
ACK 4fd53056672c227d37bccff0d0d260febf590f8f

`CAddrMan::Unserialize()` already, before this PR, could `throw` if it encounters a corrupted `peers.dat`. I think it is logical to do the same if the consistency checks fail after the unserialize process has finished "successfully". Also, it is important enough and not too expensive to do the consistency checks always, unconditionally, regardless of `-checkaddrman` at the end of unserialize.

(the fuzzer is upset, probably needs some petting)

File: src/addrman.cpp (hunk 2 above)
Comment (MarcoFalke) [reply src/addrman.cpp:392]: Can you explain what code path didn't catch the exception? Raw exceptions shouldn't be displayed to the user at all. See also https://github.com/bitcoin/bitcoin/pull/22734#issue-714811417 on steps to test this pull request.

**Comment by MarcoFalke** [comment]
> (the fuzzer is upset, probably needs some petting)

Thanks. Force pushed to pet the fuzzer and fixup the docs. (no other code changes)

File: src/addrman.cpp (hunk 2 above)
Comment (vasild) [reply src/addrman.cpp:392]: Uff, sorry, I remember this was discussed before. I was misled somehow by the fuzzer output (quoted above).

Comment (MarcoFalke) [reply src/addrman.cpp:392]: No worries. Resolving for now.

**Review by vasild — APPROVED** [review]
ACK fa6f5c9ea4dad2e15065001fef9ae6a9325c632b

**Comment by MarcoFalke** [comment]
@mzumsande @naumenkogs @jnewbery Now that #22762 is merged, I rebased this pull. This should address your concerns.

**Comment by naumenkogs** [comment]
ACK fa6f5c9ea4dad2e15065001fef9ae6a9325c632b

**Comment by MarcoFalke** [comment]
Rebased; Only trivial conflicts in the tests.

**Review by vasild — APPROVED** [review]
ACK fa3669f72f69662049b55ad1a482b4a0f9f7ae40

**Comment by jnewbery** [comment]
Code review ACK fa3669f72f69662049b55ad1a482b4a0f9f7ae40
