### PR TITLE
fs: Make compatible with boost 1.78

### LINKED ISSUE #23846: No match for fs::path operator+= when compiling with Boost 1.78
With Boost 1.78 (installed on my system), I get a compiler error:

```
./fs.h: In function ‘fs::path fs::operator+(fs::path, fs::path)’:
./fs.h:91:8: error: no match for ‘operator+=’ (operand types are ‘fs::path’ and ‘std::remove_reference<fs::path&>::type’ {aka ‘fs::path’})
   91 |     p1 += std::move(p2);
      |     ~~~^~~~~~~~~~~~~~~~
```

It appears that in Boost 1.78, `operator+=` became a template function, and our `path` class which subclasses `boost::filesystem::path::path` no longer has an `operator+=` which will work with it.

I also opened an issue with boost: https://github.com/boostorg/filesystem/issues/223

### PR DESCRIPTION
**Pull request by achow101**
Boost 1.78 removed `operator+` in a way that breaks our usage of it in a subclass. A [proposed workaround](https://github.com/boostorg/filesystem/issues/223#issuecomment-1000230207) for this is to cast the argument to `boost::filesystem::path`, and this is backwards compatible with older versions of boost.

Additionally, it appears that `fs::canonical` no longer removes trailing slashes. This was causing a test to fail. The solution is to explicitly remove the trailing separator in the one place that `fs::canonical` is used.

Lastly, `fs::create_directories` now has an error message saying `create_directories` instead of `create_directory`. This caused wallet_multiwallet.py to fail. The error message check has been updated to be able accept either string.

Fixes #23846

### CODE REVIEW

File: src/fs.h [hunk 1]
```diff
@@ -88,7 +88,7 @@ static inline auto quoted(const std::string& s)
 // Allow safe path append operations.
 static inline path operator+(path p1, path p2)
 {
-    p1 += std::move(p2);
+    p1 += std::move(static_cast<boost::filesystem::path>(p2));
```
Comment (ryanofsky) [inline src/fs.h:91]: In commit "fs: Make compatible with boost 1.78" (575ecd0ff5025bdd2f5cb5e52049aaa202245949)

The static_cast creates an unnecessary temporary here and makes the std::move not have any effect because its argument is already temporary. The right way to write this would be `p1 += static_cast<boost::filesystem::path&&>(p2);`

You could also consider using the alternate fix from https://github.com/bitcoin/bitcoin/issues/23846#issuecomment-1000564006. I think that fix is a little better since it gets rid of the nonstandard + operator in cases where we don't need it and also avoids more temporaries.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 575ecd0ff5025bdd2f5cb5e52049aaa202245949. This looks safe but the code is a little nonsensical, because the static_cast creates an unnecessary temporary, and std::move has no effect moving from a temporary that would already be moved from. I suggested two alternatives if you want to update.

File: src/fs.h (hunk 1 above)
Comment (achow101) [reply src/fs.h]: Changed to the correct cast.

**Review by ryanofsky — APPROVED** [review]
Code review ACK dc5d6b0d4793ca978f71f69ef7d6b818794676c2 🪄

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/24104/commits/dc5d6b0d4793ca978f71f69ef7d6b818794676c2

**Comment by fanquake** [comment]
Given that #23846 is becoming more of an issue for devs, and #20744 is still stuck while we make some final changes and fix Guix, I'm going to go-ahead and merge this.
