### PR TITLE
rpc: `uptime` should begin on application start

### LINKED ISSUE #34423: uptime RPC returns 0 on first invocation
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behaviour

First time `bitcoin-cli uptime` is called, output is always zero.

### Expected behaviour

Expected behavior should be first time invocation of `bitcoin-cli uptime` shows the actual `bitcoind` uptime.

### Steps to reproduce

On Linux:

1. `./build/bin/bitcoind -regtest -daemon`
2. `sleep 10`
3. `./build/bin/bitcoin-cli -regtest uptime`

Output is zero, while non-zero is expected.

### Relevant log output

_No response_

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v30.99.0-c0e6556e4f51

### Operating system and version

Ubuntu 22.04.5 LTS

### Machine specifications

_No response_

### PR DESCRIPTION
**Pull request by l0rinc**
### Problem
#34328 switched uptime to use monotonic time, but `g_startup_time` was a function-local static in `GetUptime()`, meaning it was initialized on first call rather than at program start.
This caused the first uptime RPC to always return 0.

### Fix
Move `g_startup_time` to namespace scope so it initializes at program start, ensuring the first `uptime()` call returns actual elapsed time.

### Reproducer

Revert the fix and run the test or alternatively:

```bash
cmake -B build && cmake --build build --target bitcoind bitcoin-cli -j$(nproc)
./build/bin/bitcoind -regtest -daemon
sleep 10
./build/bin/bitcoin-cli -regtest uptime
./build/bin/bitcoin-cli -regtest stop
```

<details>
<summary>Before (uptime is initialized on first call)</summary>

```bash
Bitcoin Core starting
0
Bitcoin Core stopping
```

</details>

<details>
<summary>After (first uptime call is in-line with sleep)</summary>

```bash
Bitcoin Core starting
10
Bitcoin Core stopping
```
</details>

----

Fixes #34423, added reporter as coauthor.

### CODE REVIEW

File: src/common/system.cpp [hunk 1]
```diff
@@ -37,6 +37,10 @@
 
 using util::ReplaceAll;
 
+namespace {
+    const auto g_startup_time{SteadyClock::now()};
```
Comment (sedited) [inline src/common/system.cpp]: Why not just declare this static?

Comment (sedited) [reply src/common/system.cpp]: Because it is just used in this single translation unit: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#rs-unnamed2 ,

Comment (l0rinc) [reply src/common/system.cpp]: Yes, my IDE explicitly warned about that:
image

File: test/functional/rpc_uptime.py [hunk 2]
```diff
@@ -26,8 +26,11 @@ def _test_negative_time(self):
         assert_raises_rpc_error(-8, "Mocktime must be in the range [0, 9223372036], not -1.", self.nodes[0].setmocktime, -1)
 
     def _test_uptime(self):
-        wait_time = 20_000
+        time.sleep(1) # Do some work before checking uptime
         uptime_before = self.nodes[0].uptime()
+        assert uptime_before > 0, "uptime should begin at app start"
```
Comment (maflcko) [inline test/functional/rpc_uptime.py:31]: nit: Would be nice to use the util helpers consistently:

 
    assert uptime_before > 0, "uptime should begin at app start" -> Use assert_greater_than(uptime_before, 0) (replace bare assert with the functional test helper).

File: src/common/system.cpp [hunk 3]
```diff
@@ -37,6 +37,10 @@
...
+} // namespace
```
Comment (maflcko) [inline src/common/system.cpp]: nit: Could move this right next to the only function that uses it

**Review by maflcko — COMMENTED** [review]
lgtm ACK 44cf02bea99ce429033df6035386f252d5992706

File: test/functional/rpc_uptime.py (hunk 2 above)
Comment (l0rinc) [reply test/functional/rpc_uptime.py:31]: On failure that would only show the values not fulfilling the comparison, not why the uptime should be positive ("uptime should begin at app start")

File: src/common/system.cpp (hunk 1 above)
Comment (l0rinc) [reply src/common/system.cpp]: Added to the commit message:
> Move `g_startup_time` to namespace scope so it initializes at program start, ensuring the first call returns actual elapsed time. Note that we don't need to make it `static` anymore because it is just used in this single translation unit.

File: src/common/system.cpp (hunk 3 above)
Comment (l0rinc) [reply src/common/system.cpp]: Déjà vu :D

I did it originally to minimize the diff - but we're past that now, so it makes sense.

**Comment by maflcko** [comment]
lgtm ACK e67a676df9af5ece5307438ae1b4ddb0730e3482

File: test/functional/rpc_uptime.py (hunk 2 above)
Comment (maflcko) [reply test/functional/rpc_uptime.py:31]: It does print the reason, if it is placed in a comment after the assertion. However, I don't think printing it is important and the comment can also be on the line above. If you think allowing to print reasons for those helpers, it should be trivial to add that feature.

Comment (l0rinc) [reply test/functional/rpc_uptime.py:31]: I have tried modifying them before and they were nacked. If someone else wants to, I can review it, but I'm not planning on using them as they are now, I think they're very noisy

Comment (maflcko) [reply test/functional/rpc_uptime.py:31]: I think the project should try to converge to a common style for newly written code (this is also explained in the dev notes). If you think the style is wrong, it can be changed, but I don't think it is great, if everyone is brewing their own soup and going against the dev notes.

Comment (l0rinc) [reply test/functional/rpc_uptime.py:31]: agree, that's what I tried in that PR, converge to a common style.

**Comment by optout21** [comment]
crACK e67a676df9af5ece5307438ae1b4ddb0730e3482

**Comment by l0rinc** [comment]
rfm?

**Review by musaHaruna — COMMENTED** [review]
Tested ACK [e67a676](https://github.com/bitcoin/bitcoin/pull/34437/changes/e67a676df9af5ece5307438ae1b4ddb0730e3482)

`./build/test/functional/rpc_uptime.py` uptime results  (before and after) before this PR
```
Uptime before: 0
Uptime after: 0
```

`./build/test/functional/rpc_uptime.py` uptime results (before and after) with this PR
```
Uptime before: 1
Uptime after: 1
```
**My understanding of the change in this PR:** 
Before the PR, both `uptime before` and `uptime after` were reported as 0 because the previous implementation stored the startup time as a static variable inside `GetUptime()`, which initializes only when the function is first called; at that moment, `g_startup_time` and `SteadyClock::now()` are effectively equal, so subtracting them always yields zero. After the PR, `g_startup_time` is initialized once at program start in a global anonymous namespace, so `SteadyClock::now() - g_startup_time` now correctly measures the elapsed runtime from program launch. For example, if the program starts at monotonic time 100 seconds and one second passes, calling `GetUptime()` returns `101 − 100 = 1` second. This confirms that uptime now begins counting at program start and is immune to wall-clock jumps (from [#34328](https://github.com/bitcoin/bitcoin/pull/34328)), producing correct, monotonic results. 
I’m open to feedback if this understanding is incorrect.

**Comment by carloantinarella** [comment]
Tested ACK e67a676df9af5ece5307438ae1b4ddb0730e3482
Built and tested manually the same way I did in https://github.com/bitcoin/bitcoin/pull/34328#issuecomment-3797202202.
Works fine.

**Comment by achow101** [comment]
ACK e67a676df9af5ece5307438ae1b4ddb0730e3482
