### PR TITLE
signrawtransactionwithkey: report error when missing redeemScript/witnessScript

### LINKED ISSUE #16249: signrawtransactionwithkey gives confusing error when missing redeemScript
Forgetting to include the redeemscript when invoking signrawtransactionwithkey used to give a useful error:

    $ bitcoin-cli -regtest signrawtransactionwithkey "02000000018a24833c36be23272080d6be8a53e36586b81e0ac447e1298ee58e18cc96bdee0100000000ffffffff0118246bee0000000017a914e139e3904e9e69ecbce87b0fcfb73b1b0e3b9e818700000000" '["cUJ7bUweEgENv4ixezsSyZa2uBJxR37iFLtCt18gSvkjpkj7CmMr"]'  '[{"txid":"eebd96cc188ee58e29e147c40a1eb88665e3538abed680202723be363c83248a","vout":1,"scriptPubKey":"0020f89f2138a58a2042310f297259ca8050bcaecd3a0f3c936edffb7e38e31d775a","amount":"40.00000000"}]'

With 0.17:

    error code: -3
    error message:
    Missing redeemScript

With master/0.18:

    {
      "hex": "02000000018a24833c36be23272080d6be8a53e36586b81e0ac447e1298ee58e18cc96bdee0100000000ffffffff0118246bee0000000017a914e139e3904e9e69ecbce87b0fcfb73b1b0e3b9e818700000000",
      "complete": false,
      "errors": [
        {
          "txid": "eebd96cc188ee58e29e147c40a1eb88665e3538abed680202723be363c83248a",
          "vout": 1,
          "witness": [
          ],
          "scriptSig": "",
          "sequence": 4294967295,
          "error": "Witness program was passed an empty witness"
        }
      ]
    }

### PR DESCRIPTION
**Pull request by ajtowns**
Adding support for "witnessScript" as an alternative to "redeemScript" when using "signrawtransactionwithkey" meant that the `RPCTypeCheckObj()` call in `SignTransaction` can't error out just because either parameter is missing -- it's only a problem if both are missing, which isn't a state `RPCTypeCheckObj()` tests for. This results in the regression described in #16249. This patch adds some code to test for this case and give a similar error, namely:

    error code: -8
    error message:
    Missing redeemScript/witnessScript

Fixes: #16249

### CODE REVIEW

File: src/rpc/rawtransaction_util.cpp [hunk 1]
```diff
@@ -221,6 +221,9 @@ UniValue SignTransaction(CMutableTransaction& mtx, const UniValue& prevTxsUnival
                     // Automatically also add the P2WSH wrapped version of the script (to deal with P2SH-P2WSH).
                     keystore->AddCScript(GetScriptForWitness(witnessScript));
                 }
+                if (rs.isNull() && ws.isNull()) {
+                    throw JSONRPCError(RPC_TYPE_ERROR, "Missing redeemScript/witnessScript");
```
Comment (promag) [inline src/rpc/rawtransaction_util.cpp]: How about:
```
    RPC_INVALID_PARAMETER           = -8,  //!< Invalid, missing or duplicate parameter
```

**Review by promag — COMMENTED** [review]
I think `RPCTypeCheckObj(...)` in L202 could be removed?

Concept ACK.

**Comment by meshcollider** [comment]
Looks good, agree with `RPC_INVALID_PARAMETER` though

**Comment by ajtowns** [comment]
> I think `RPCTypeCheckObj(...)` in L202 could be removed?

Could be, but I think it gives a cleaner error for bad params, eg `"redeemScript": 5` currently gives:

    Expected type string for redeemScript, got number

vs leaving the error handling up to `ParseHexV` which gives:

    redeemScript must be hexadecimal string (not '')

Updated to use `RPC_INVALID_PARAMETER`.

**Comment by meshcollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/16250/commits/01174596e69568c434198a86f54cb9ea6740e6c2

**Review by promag — COMMENTED** [review]
ACK 01174596e. Could also write test without `dict`/`del`:
```diff
         outval = value - decimal.Decimal("0.00001000")
         rawtx = node2.createrawtransaction([{"txid": txid, "vout": vout}], [{self.final: outval}])

-        prevtx_err = dict(prevtxs[0])
-        del prevtx_err["redeemScript"]
-
-        assert_raises_rpc_error(-8, "Missing redeemScript/witnessScript", node2.signrawtransactionwithkey, rawtx, self.priv[0:self.nsigs-1], [prevtx_err])
+        assert_raises_rpc_error(-8, "Missing redeemScript/witnessScript", node2.signrawtransactionwithkey, rawtx, self.priv[0:self.nsigs-1], [{k:v for k,v in prevtxs[0].items() if k != "redeemScript"}])

         rawtx2 = node2.signrawtransactionwithkey(rawtx, self.priv[0:self.nsigs - 1], prevtxs)
         rawtx3 = node2.signrawtransactionwithkey(rawtx2["hex"], [self.priv[-1]], prevtxs)
```
