### PR TITLE
qa: Sync with validationinterface queue in sync_mempools

### LINKED ISSUE #12171: [qa] address_types.py failed
travis log: https://travis-ci.org/bitcoin/bitcoin/jobs/327785286

```
2018-01-11 17:49:08.016000 TestFramework (INFO): Sending from node 1 (['-addresstype=p2sh-segwit']) with multisig using default
2018-01-11 17:49:10.096000 TestFramework (INFO): Sending from node 2 (['-addresstype=p2sh-segwit', '-changetype=bech32']) with multisig using default
2018-01-11 17:49:12.492000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/address_types.py", line 183, in run_test
    assert_equal(unconf_balances[to_node], to_send * 10 * (2 + n))
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(0E-8 == 714.73999460)

### LINKED ISSUE #12205: Intermittent address_types.py test failures
address_types.py test seems to fail intermittently on travis

It was mentioned in https://github.com/bitcoin/bitcoin/pull/11991#issuecomment-357922664 that this could be due to sync_mempools failing. A failure I saw looked like:

```
address_types.py failed, Duration: 14 s
stdout:
2018-01-12 23:14:39.513000 TestFramework (INFO): Initializing test directory /tmp/bitcoin_test_runner_20180112_231145/address_types_178
2018-01-12 23:14:48.747000 TestFramework (INFO): Sending from node 0 (['-addresstype=legacy']) without multisig using default
2018-01-12 23:14:51.012000 TestFramework (INFO): Sending from node 1 (['-addresstype=p2sh-segwit']) without multisig using default
2018-01-12 23:14:53.263000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 123, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/address_types.py", line 183, in run_test
    assert_equal(unconf_balances[to_node], to_send * 10 * (2 + n))
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(0E-8 == 1176.25722960)
2018-01-12 23:14:53.263000 TestFramework (INFO): Stopping nodes
2018-01-12 23:14:53.577000 TestFramework (WARNING): Not cleaning up dir /tmp/bitcoin_test_runner_20180112_231145/address_types_178
2018-01-12 23:14:53.577000 TestFramework (ERROR): Test failed. Test logging available at /tmp/bitcoin_test_runner_20180112_231145/address_types_178/test_framework.log
2018-01-12 23:14:53.578000 TestFramework (ERROR): Hint: Call /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/combine_logs.py '/tmp/bitcoin_test_runner_20180112_231145/address_types_178' to consolidate all logs
```
https://travis-ci.org/bitcoin/bitcoin/jobs/328318030

### PR DESCRIPTION
**Pull request by maflcko**
Commit e545dedf72bff2bd41c93c93eb576929fce37112 moved `TransactionAddedToMempool` to the background scheduler thread. Thus, adding a transaction to the mempool will no longer add it to the wallet immediately. Functional tests, that `sync_mempools` and then call into wallet rpcs will race against the scheduler thread.

Fix that race by flushing the scheduler queue.

Fixes #12205; Fixes #12171;
References #9584;

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Obviously all other function tests are affected as well. I will try to fix them in a later commit, but the above fix is rather nasty as it is almost always failing on travis.

**Comment by promag** [comment]
Concept ACK. Not sure the test should handle this way. IMO some sync_mempool(flush_scheduler=True) would be better?

**Comment by MarcoFalke** [comment]
Yeah. Maybe an alternative would be to always catch up with the queue?


```diff
--- a/src/wallet/wallet.cpp
+++ b/src/wallet/wallet.cpp
@@ -1279,23 +1279,7 @@ void CWallet::BlockUntilSyncedToCurrentChain() {
     AssertLockNotHeld(cs_main);
     AssertLockNotHeld(cs_wallet);
 
-    {
-        // Skip the queue-draining stuff if we know we're caught up with
-        // chainActive.Tip()...
-        // We could also take cs_wallet here, and call m_last_block_processed
-        // protected by cs_wallet instead of cs_main, but as long as we need
-        // cs_main here anyway, its easier to just call it cs_main-protected.
-        LOCK(cs_main);
-        const CBlockIndex* initialChainTip = chainActive.Tip();
-
-        if (m_last_block_processed->GetAncestor(initialChainTip->nHeight) == initialChainTip) {
-            return;
-        }
-    }
-
-    // ...otherwise put a callback in the validation interface queue and wait
-    // for the queue to drain enough to execute it (indicating we are caught up
-    // at least with the time we entered this function).
+    // Wait for the queue to catch up on everything that was there when we entered this function
     SyncWithValidationInterfaceQueue();
 }

**Comment by MeshCollider** [comment]
I think @promag was suggesting a different way for the tests to handle it, not to change the core code btw. Current approach seems fine to me at least for now, utACK https://github.com/bitcoin/bitcoin/pull/12206/commits/fadc3f6249a9eddaa3078e570a4465162032195e

**Comment by MarcoFalke** [comment]
I am not aware of a way to flush the scheduler from outside the code without modifying the code or mining a block. Though, I might be misssing something.

**Comment by promag** [comment]
I was suggesting adding a RPC to just do `SyncWithValidationInterfaceQueue` or whatever. 

Feels weird to replace assertions with poll.

**Comment by MarcoFalke** [comment]
Yes, I plan to do something like that after branch off of 0.16. At this point I'd feel bad to delay 0.16 by spawning unnecessary review-load on the queue.

**Comment by TheBlueMatt** [comment]
I agree with @promag here, and that fix should be just as/more simple/obvious than even this fix. Just add an RPC that calls SyncWithValidationInterfaceQueue() and call that at the end of sync_mempools(), at least then its much more obvious the fix is complete, and should require a lower review burden.

**Review by ryanofsky — COMMENTED** [review]
utACK fadc3f6249a9eddaa3078e570a4465162032195e. I agree with everybody else that this should definitely be followed up on, but this fix is small and simple, and the test is failing constantly on travis, so it seems odd to object to merging this as a workaround.

**Comment by promag** [comment]
utACK fadc3f6.

**Comment by MarcoFalke** [comment]
Introduced the new `syncwithvalidationinterfacequeue` rpc as requested by @TheBlueMatt and @promag

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -1628,6 +1644,7 @@ static const CRPCCommand commands[] =
     { "hidden",             "waitfornewblock",        &waitfornewblock,        {"timeout"} },
     { "hidden",             "waitforblock",           &waitforblock,           {"blockhash","timeout"} },
     { "hidden",             "waitforblockheight",     &waitforblockheight,     {"height","timeout"} },
+    { "hidden",             "syncwithvalidationinterfacequeue", &syncwithvalidationinterfacequeue, {} },
```
Comment (promag) [inline src/rpc/blockchain.cpp]: Sort, alignment... :trollface:

**Review by promag — COMMENTED** [review]
Sweet utACK fadc3f6.

**Review by ryanofsky — COMMENTED** [review]
utACK fa1e69e52bf8de08b1ce7a774416aa7a8d20068b. @TheBlueMatt was right, the new fix is more simple and obvious than the old one.

File: src/rpc/blockchain.cpp [hunk 2]
```diff
@@ -323,6 +324,21 @@ UniValue waitforblockheight(const JSONRPCRequest& request)
     return ret;
 }
 
+UniValue syncwithvalidationinterfacequeue(const JSONRPCRequest& request)
```
Comment (promag) [inline src/rpc/blockchain.cpp]: Not sure but `src/rpc/misc.cpp` is a better place?

File: test/functional/test_framework/util.py [hunk 3]
```diff
@@ -390,7 +390,7 @@ def sync_chain(rpc_connections, *, wait=1, timeout=60):
         timeout -= wait
     raise AssertionError("Chain sync failed: Best block hashes don't match")
 
-def sync_mempools(rpc_connections, *, wait=1, timeout=60):
+def sync_mempools(rpc_connections, *, wait=1, timeout=60, flush_scheduler=True):
```
Comment (promag) [inline test/functional/test_framework/util.py]: How about not making it optional? If there is such need in the future, add it then?

Comment (MarcoFalke) [reply test/functional/test_framework/util.py]: Right now it is overkilling, i.e. always flushing. But that is not necessary, as for non-wallet functional tests and also most wallet functional test it can be turned off. I will leave the "turning it off" for later.

File: src/rpc/blockchain.cpp (hunk 2 above)
Comment (MarcoFalke) [reply src/rpc/blockchain.cpp]: My understanding is that `blockchain.cpp` also contains mempool rpcs. And this one is about mempool, no?

File: test/functional/test_framework/util.py (hunk 3 above)
Comment (promag) [reply test/functional/test_framework/util.py]: Ok, so minimal diff for now.

File: src/rpc/blockchain.cpp (hunk 2 above)
Comment (promag) [reply src/rpc/blockchain.cpp]: Ok.

**Comment by laanwj** [comment]
utACK fa1e69e

**Comment by MarcoFalke** [comment]
That looks like an overkill. Currently `setup_network` is only called after the chain was set up and I don't think there are any plans to change this in the near future. Syncing the (empty) mempools just after a "fresh" chain was set up is probably just wasting time on travis.
