### PR TITLE
rpc: Put undocumented JSON failure mode behind a runtime flag

### LINKED ISSUE #24695: Put undocumented JSON failure mode behind a runtime flag
Following the merge of https://github.com/bitcoin/bitcoin/pull/23083, we'll throw a non-fatal error at runtime if the documentation for an RPC is incorrect. This behaviour has found numerous issues over a very short period (of the PR being opened). However, this is not something that we want in production / release builds, instead, we want the ability to have it enabled in the CI and when running tests. A runtime option could be added, which controls this behaviour (disabled by default).

#### Useful skills:

- C++
- Understanding of Bitcoin Core's initialization sequence
- Understanding of Bitcoin Core's RPC interface

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

### PR DESCRIPTION
**Pull request by suhailsaqan**
Fixes #24695 (Put undocumented JSON failure mode behind a runtime flag)

### CODE REVIEW

File: src/init.cpp [hunk 1]
```diff
@@ -570,6 +570,7 @@ void SetupServerArgs(ArgsManager& argsman)
...
     argsman.AddArg("-rpcauth=<userpw>", "Username and HMAC-SHA-256 hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is included in share/rpcauth. The client then connects normally using the rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This option can be specified multiple times", ArgsManager::ALLOW_ANY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
     argsman.AddArg("-rpcbind=<addr>[:port]", "Bind to given address to listen for JSON-RPC connections. Do not expose the RPC server to untrusted networks such as the public internet! This option is ignored unless -rpcallowip is also passed. Port is optional and overrides -rpcport. Use [host]:port notation for IPv6. This option can be specified multiple times (default: 127.0.0.1 and ::1 i.e., localhost)", ArgsManager::ALLOW_ANY | ArgsManager::NETWORK_ONLY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
+    argsman.AddArg("-rpcshowerror", "Whether or not to throw a non-fatal error at runtime if the documentation for an RPC is incorrect. Default is false.", ArgsManager::ALLOW_ANY, OptionsCategory::RPC);
```
Comment (luke-jr) [inline src/init.cpp:573]: `ArgsManager::DEBUG_ONLY`

Comment (luke-jr) [inline src/init.cpp:573]: Maybe `-rpcdoccheck` would be better?

File: src/wallet/rpc/wallet.cpp [hunk 2]
```diff
@@ -56,7 +56,7 @@ static RPCHelpMan getwalletinfo()
                         {
                             {RPCResult::Type::NUM, "duration", "elapsed seconds since scan start"},
                             {RPCResult::Type::NUM, "progress", "scanning progress percentage [0.0, 1.0]"},
-                        }, /*skip_type_check=*/true},
```
Comment (luke-jr) [inline src/wallet/rpc/wallet.cpp:59]: I think we still need this?

**Review by luke-jr — CHANGES_REQUESTED** [review]

File: src/wallet/rpc/wallet.cpp (hunk 2 above)
Comment (suhailsaqan) [reply src/wallet/rpc/wallet.cpp:59]: > I think we still need this?

Wouldn't it be invalid because I took out the `skip_type_check` in `src/rpc/util.h`?

Comment (luke-jr) [reply src/wallet/rpc/wallet.cpp:59]: Yeah, you'll have to not do that ;)

Comment (suhailsaqan) [reply src/wallet/rpc/wallet.cpp]: Gotchu, I think that works now?

File: src/init.cpp (hunk 1 above)
Comment (Osusushue) [reply src/init.cpp]: E

File: src/init.cpp [hunk 3]
```diff
@@ -570,6 +570,7 @@ void SetupServerArgs(ArgsManager& argsman)
...
     argsman.AddArg("-rpcauth=<userpw>", "Username and HMAC-SHA-256 hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is included in share/rpcauth. The client then connects normally using the rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This option can be specified multiple times", ArgsManager::ALLOW_ANY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
     argsman.AddArg("-rpcbind=<addr>[:port]", "Bind to given address to listen for JSON-RPC connections. Do not expose the RPC server to untrusted networks such as the public internet! This option is ignored unless -rpcallowip is also passed. Port is optional and overrides -rpcport. Use [host]:port notation for IPv6. This option can be specified multiple times (default: 127.0.0.1 and ::1 i.e., localhost)", ArgsManager::ALLOW_ANY | ArgsManager::NETWORK_ONLY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
+    argsman.AddArg("-rpcdoccheck", "Whether or not to throw a non-fatal error at runtime if the documentation for an RPC is incorrect. Default is false.", ArgsManager::DEBUG_ONLY, OptionsCategory::RPC);
```
Comment (luke-jr) [inline src/init.cpp:573]: Usually the description is written as a positive (what happens if you set it). Also, default should match the format of other boolean options.

Comment (Osusushue) [reply src/init.cpp:573]: E

Comment (suhailsaqan) [reply src/init.cpp]: > Usually the description is written as a positive (what happens if you set it). Also, default should match the format of other boolean options.

Fixed and squashed previous commits.

File: src/init.cpp [hunk 4]
```diff
@@ -570,6 +570,7 @@ void SetupServerArgs(ArgsManager& argsman)
...
     argsman.AddArg("-rpcauth=<userpw>", "Username and HMAC-SHA-256 hashed password for JSON-RPC connections. The field <userpw> comes in the format: <USERNAME>:<SALT>$<HASH>. A canonical python script is included in share/rpcauth. The client then connects normally using the rpcuser=<USERNAME>/rpcpassword=<PASSWORD> pair of arguments. This option can be specified multiple times", ArgsManager::ALLOW_ANY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
     argsman.AddArg("-rpcbind=<addr>[:port]", "Bind to given address to listen for JSON-RPC connections. Do not expose the RPC server to untrusted networks such as the public internet! This option is ignored unless -rpcallowip is also passed. Port is optional and overrides -rpcport. Use [host]:port notation for IPv6. This option can be specified multiple times (default: 127.0.0.1 and ::1 i.e., localhost)", ArgsManager::ALLOW_ANY | ArgsManager::NETWORK_ONLY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
+    argsman.AddArg("-rpcdoccheck", strprintf("Throw a non-fatal error at runtime if the documentation for an RPC is incorrect (default: %u)", DEFAULT_RPC_DOC_CHECK), ArgsManager::DEBUG_ONLY, OptionsCategory::RPC);
```
Comment (luke-jr) [inline src/init.cpp:573]: I think you still need `ALLOW_ANY`

File: src/rpc/util.h [hunk 5]
```diff
@@ -22,6 +22,8 @@
 #include <variant>
 #include <vector>
 
+static const bool DEFAULT_RPC_DOC_CHECK=false;
```
Comment (luke-jr) [inline src/rpc/util.h:25]:
```c++
static constexpr bool DEFAULT_RPC_DOC_CHECK{false};
```

**Review by luke-jr — CHANGES_REQUESTED** [review]

File: src/init.cpp [hunk 6]
```diff
@@ -570,7 +570,7 @@ void SetupServerArgs(ArgsManager& argsman)
...
     argsman.AddArg("-rpcbind=<addr>[:port]", "Bind to given address to listen for JSON-RPC connections. Do not expose the RPC server to untrusted networks such as the public internet! This option is ignored unless -rpcallowip is also passed. Port is optional and overrides -rpcport. Use [host]:port notation for IPv6. This option can be specified multiple times (default: 127.0.0.1 and ::1 i.e., localhost)", ArgsManager::ALLOW_ANY | ArgsManager::NETWORK_ONLY | ArgsManager::SENSITIVE, OptionsCategory::RPC);
-    argsman.AddArg("-rpcdoccheck", strprintf("Throw a non-fatal error at runtime if the documentation for an RPC is incorrect (default: %u)", DEFAULT_RPC_DOC_CHECK), ArgsManager::DEBUG_ONLY, OptionsCategory::RPC);
+    argsman.AddArg("-rpcdoccheck", strprintf("Throw a non-fatal error at runtime if the documentation for an RPC is incorrect (default: %u)", DEFAULT_RPC_DOC_CHECK), ArgsManager::ALLOW_ANY, OptionsCategory::RPC);
```
Comment (luke-jr) [inline src/init.cpp:573]: both, look at the other debug options

**Comment by MarcoFalke** [comment]
Please squash your commits according to https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits

**Review by luke-jr — APPROVED** [review]
utACK after squashing

**Review by w0xlt — COMMENTED** [review]
Approach ACK

**Comment by suhailsaqan** [comment]
It says I can't squash because "A merge commit cannot exist among those commits". Would anyone know how to fix that?

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin/bitcoin/pull/25165

**Comment by suhailsaqan** [comment]
When I do `git merge master` it says `Already up to date.`. Am I not following it correctly?

So the current situation I'm in is that the changes are committed on my master branch. So I did `git checkout master` and `git fetch -all` but then not sure if `git merge master` is the correct thing to do next?

**Review by vincenzopalazzo — COMMENTED** [review]
Concept ACK

File: src/rpc/util.cpp [hunk 7]
```diff
@@ -861,7 +862,7 @@ void RPCResult::ToSections(Sections& sections, const OuterType outer_type, const
 
 bool RPCResult::MatchesType(const UniValue& result) const
 {
-    if (m_skip_type_check) {
+    if (!gArgs.GetBoolArg("-rpcdoccheck", DEFAULT_RPC_DOC_CHECK) || m_skip_type_check) {
```
Comment (MarcoFalke) [inline src/rpc/util.cpp:865]: nit: It might be better to put this into `RPCHelpMan::HandleRequest`, so that iteration over the results can be skipped.

File: src/rpc/util.h [hunk 8]
```diff
@@ -22,6 +22,8 @@
 #include <variant>
 #include <vector>
 
+static constexpr bool DEFAULT_RPC_DOC_CHECK{false};
```
Comment (MarcoFalke) [inline src/rpc/util.h:25]: Now that this is off by default, it needs to be enabled in the tests.

See `def write_config`.

File: src/rpc/util.cpp (hunk 7 above)
Comment (suhailsaqan) [reply src/rpc/util.cpp]: Just pushed changes. I believe it works but not entirely sure.

**Comment by MarcoFalke** [comment]
I've reworked https://github.com/bitcoin/bitcoin/pull/25165 . Hopefully it should be clearer now?

**Review by luke-jr — APPROVED** [review]
utACK b953ea6cc691ba61bf08eb186e76e7e8b7ba8120

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/25161/commits/b953ea6cc691ba61bf08eb186e76e7e8b7ba8120
