### PR TITLE
bench: Fix WalletMigration benchmark

### LINKED ISSUE #32277: bench: WalletMigration benchmark broken
master @ cdc32994feadf3f15df3cfac5baae36b4b011462
```bash
export CC=clang
export CXX=clang++
cmake -B build -DBUILD_BENCH=ON
cmake --build build
./build/bin/bench_bitcoin -filter=WalletMigration
bench_bitcoin: wallet/wallet.cpp:1772: void wallet::CWallet::InitWalletFlags(uint64_t): Assertion `m_wallet_flags == 0' failed.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by pablomartin4btc**
The keys and scripts created for the Legacy Wallet needed to be persisted in order for the migration to work properly.

Fixes #32277.

### CODE REVIEW

File: src/wallet/walletdb.cpp [hunk 1]
```diff
@@ -569,6 +569,22 @@ bool HasLegacyRecords(CWallet& wallet, DatabaseBatch& batch)
     return false;
 }
 
+bool HasAnyRecordWithKeyPrefix(CWallet& wallet, const std::string& dbkey_prefix)
```
Comment (achow101) [inline src/wallet/walletdb.cpp:572]: I don't think this is really necessary, especially since it's test only.

Comment (pablomartin4btc) [reply src/wallet/walletdb.cpp:572]: Ok, I can move it to the bench file.

Comment (furszy) [reply src/wallet/walletdb.cpp:572]: Could just remove it.

File: src/bench/wallet_migration.cpp [hunk 2]
```diff
@@ -42,6 +42,11 @@ static void WalletMigration(benchmark::Bench& bench)
         const CScript& script = scripts_watch_only.emplace_back(GetScriptForDestination(dest));
         assert(legacy_spkm->LoadWatchOnly(script));
         assert(wallet->SetAddressBook(dest, strprintf("watch_%d", w), /*purpose=*/std::nullopt));
+        {
+            WalletBatch batch(wallet->GetDatabase());
```
Comment (furszy) [inline src/bench/wallet_migration.cpp:46]: Can create a single batch instance outside the loop and use it everywhere. The "database" on this test is a plain map in memory. No thread synchronization is needed, writes are done sequential.

File: src/bench/wallet_migration.cpp [hunk 3]
```diff
@@ -58,6 +63,11 @@ static void WalletMigration(benchmark::Bench& bench)
         mtx.vout.emplace_back(COIN, scripts_watch_only.at(j % NUM_WATCH_ONLY_ADDR));
         mtx.vin.resize(2);
         wallet->AddToWallet(MakeTransactionRef(mtx), TxStateInactive{}, /*update_wtx=*/nullptr, /*fFlushOnClose=*/false, /*rescanning_old_block=*/true);
+        {
+            WalletBatch batch(wallet->GetDatabase());
+            batch.WriteKey(pubkey, key.GetPrivKey(), CKeyMetadata());
```
Comment (furszy) [inline src/bench/wallet_migration.cpp:68]: The empty metadata field smells bad. Double check migration.

Comment (pablomartin4btc) [reply src/bench/wallet_migration.cpp:68]: I've checked that keys (500 txs on local addresses) and scripts (20 wo imported addresses) are being migrated correctly (the first at `ApplyMigrationData` in `for (auto& desc_spkm : data.desc_spkms) {` and the second at `DoMigration` in `for (const auto& [desc_str, creation_time] : data->watch_descs) {`).

**Comment by pablomartin4btc** [comment]
_<ins>Updates</ins>:_
- Addressed feedbacks from @achow101 and @furszy.

**Comment by furszy** [comment]
Can you comment on https://github.com/bitcoin/bitcoin/issues/32277#issuecomment-2807698798?

File: src/bench/wallet_migration.cpp (hunk 3 above)
Comment (achow101) [reply src/bench/wallet_migration.cpp]: I think empty metadata is fine, there isn't really much metadata to be had for imports and randomly generated keys. It's basically just the creation time.

File: src/bench/wallet_migration.cpp [hunk 4]
```diff
@@ -42,6 +43,7 @@ static void WalletMigration(benchmark::Bench& bench)
         const CScript& script = scripts_watch_only.emplace_back(GetScriptForDestination(dest));
         assert(legacy_spkm->LoadWatchOnly(script));
         assert(wallet->SetAddressBook(dest, strprintf("watch_%d", w), /*purpose=*/std::nullopt));
```
Comment (davidgumberg) [inline src/bench/wallet_migration.cpp:45]: For context on my comment in https://github.com/bitcoin/bitcoin/issues/32277#issuecomment-2807698798, `SetAddressBook()` includes a [write](https://github.com/bitcoin/bitcoin/blob/e66e30c9e5383a467789574e61114b57536193b9/src/wallet/wallet.cpp#L2496-L2500)  to the database,  and so does [`AddToWallet(tx)`](https://github.com/bitcoin/bitcoin/blob/e66e30c9e5383a467789574e61114b57536193b9/src/wallet/wallet.cpp#L1160)

This is the reason why some records were persisted, but none that were strictly "legacy" records as mentioned in https://github.com/bitcoin/bitcoin/issues/32277#issuecomment-2810346369.

(@furszy)

**Comment by davidgumberg** [comment]
Tested ACK 7912cd41258d59e4

Either of the two DB writes added here seems to fix the issue in my testing, but it's better to be consistent and write both. 

---

I am no longer confident the [change to `success`](https://github.com/bitcoin/bitcoin/pull/32149/commits/0f602c5693ef5d0c63b1e5b7dc0990dced3655d6#diff-1f2db0e4d5c12d109c7f0962333c245b49b696cb39ff432da048e9d6c08944d8L4537-R4543) introduced in #32149 makes sense: 

https://github.com/bitcoin/bitcoin/blob/e66e30c9e5383a467789574e61114b57536193b9/src/wallet/wallet.cpp#L4538-L4544

Now, any wallet which fails the `HasLegacyRecords()` check gets flagged as `success = true`, before it was only wallets with the blank flag set which got `success = true` for free. On second thought, should #32149 have explicitly handled the empty watchonly wallet case, rather than having to reason about the correctness/completeness of `HasLegacyRecords()`

---

This bug was an instance of a more general class of crash during migration: https://github.com/bitcoin/bitcoin/issues/32111. This would still be a bug if #32111 was fixed, but might not have resulted in a crash.

**Review by furszy — COMMENTED** [review]
utACK 7912cd41258d5

File: src/bench/wallet_migration.cpp (hunk 4 above)
Comment (galaxycores) [reply src/bench/wallet_migration.cpp:45]: AdToWallet(tx)

File: src/bench/wallet_migration.cpp [hunk 5]
```diff
@@ -42,6 +43,7 @@ static void WalletMigration(benchmark::Bench& bench)
...
+        batch.WriteWatchOnly(script, CKeyMetadata());
```
Comment (galaxycores) [inline src/bench/wallet_migration.cpp:46]: (WriteWachOnly;)
