### PR TITLE
rpc, rest: Improve block rpc error handling, check header before attempting to read block data.

### LINKED ISSUE #20978: RPC `getblock` resulted in 500 and ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)
Invoking HTTP RPC  `getblock` resulted in the following failure: 

```
status_code: 500 status: Internal Server Error response_body: {"result":null,"error":{"code":-1,"message":"Block not found on disk"}
```

The logs have shown:

```
2021-01-21T16:48:53Z Pre-allocating up to position 0x400000 in rev02417.dat
2021-01-21T16:48:53Z UpdateTip: new best=00000000000000000005656edcf6fb5cea1d2fe392841a9bdaa8b1fa821df661 height=667046 version=0x20004000 log2_work=92.608345 tx=608416058 date='2021-01-21T16:48:23Z' progress=1.000000 cache=95.6MiB(725599txo) warning='73 of last 100 blocks have unexpected version'
2021-01-21T16:59:14Z UpdateTip: new best=0000000000000000000383edc4ee51e5e55000c85ae844899e582aedc6d0cb2f height=667047 version=0x2000e000 log2_work=92.608362 tx=608418465 date='2021-01-21T16:58:42Z' progress=1.000000 cache=96.9MiB(735971txo) warning='73 of last 100 blocks have unexpected version'

2021-01-21T17:13:25Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)

2021-01-21T17:13:25Z UpdateTip: new best=0000000000000000000bc7c177f0ef9fa47492beb5c14250c6d412b12997a56b height=667048 version=0x20000000 log2_work=92.608379 tx=608421018 date='2021-01-21T17:13:24Z' progress=1.000000 cache=98.4MiB(747960txo) warning='72 of last 100 blocks have unexpected version'
2021-01-21T17:16:06Z UpdateTip: new best=000000000000000000034359728a89d359e6859f6908145594888c26f952dcb7 height=667049 version=0x20600000 log2_work=92.608396 tx=608423202 date='2021-01-21T17:15:51Z' progress=1.000000 cache=99.2MiB(754485txo) warning='73 of last 100 blocks have unexpected version'
```

**Expected behavior**

No error

**Actual behavior**

RPC 500 error returned and ReadBlockFromDisk ERROR logged.

**To reproduce**

Unknown.

**System information**

AWS K8S 4 CPUs/8Gi RAM, GP3 EBS 3000 IOPS/125Mips 

```
2021-01-21T15:30:54Z Bitcoin Core version v0.20.1 (release build)
2021-01-21T15:30:54Z Assuming ancestors of block 0000000000000000000f2adce67e49b0b6bdeb9de8b7c3d7e93b21e7fc1e819d have valid signatures.
2021-01-21T15:30:54Z Setting nMinimumChainWork=00000000000000000000000000000000000000000e1ab5ec9348e9f4b8eb8154
2021-01-21T15:30:54Z Using the 'shani(1way,2way)' SHA256 implementation
2021-01-21T15:30:54Z Using RdSeed as additional entropy source
2021-01-21T15:30:54Z Using RdRand as an additional entropy source
2021-01-21T15:30:54Z Default data directory /root/.bitcoin
2021-01-21T15:30:54Z Using data directory /home/bitcoin/.bitcoin
2021-01-21T15:30:54Z Config file: /home/bitcoin/.bitcoin/bitcoin.conf (not found, skipping)
2021-01-21T15:30:54Z Command-line arg: datadir="/home/bitcoin/.bitcoin"
2021-01-21T15:30:54Z Command-line arg: rpcallowip="100.64.0.0/10"
2021-01-21T15:30:54Z Command-line arg: rpcbind=****
2021-01-21T15:30:54Z Command-line arg: rpcpassword=****
2021-01-21T15:30:54Z Command-line arg: rpcport="18332"
2021-01-21T15:30:54Z Command-line arg: rpcuser=****
2021-01-21T15:30:54Z Command-line arg: rpcworkqueue="4096"
2021-01-21T15:30:54Z Command-line arg: server=""
2021-01-21T15:30:54Z Command-line arg: txindex="1"
2021-01-21T15:30:54Z Using at most 125 automatic connections (1048576 file descriptors available)
2021-01-21T15:30:54Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2021-01-21T15:30:54Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2021-01-21T15:30:54Z Script verification uses 7 additional threads
2021-01-21T15:30:54Z scheduler thread start
2021-01-21T15:30:54Z WARNING: the RPC server is not safe to expose to untrusted networks such as the public internet
2021-01-21T15:30:54Z HTTP: creating work queue of depth 4096
2021-01-21T15:30:54Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
2021-01-21T15:30:54Z HTTP: starting 4 worker threads
2021-01-21T15:30:54Z Using wallet directory /home/bitcoin/.bitcoin
2021-01-21T15:30:54Z init message: Verifying wallet(s)...
2021-01-21T15:30:54Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2021-01-21T15:30:54Z Using wallet /home/bitcoin/.bitcoin
2021-01-21T15:30:54Z BerkeleyEnvironment::Open: LogDir=/home/bitcoin/.bitcoin/database ErrorFile=/home/bitcoin/.bitcoin/db.log
2021-01-21T15:30:54Z init message: Loading banlist...
2021-01-21T15:30:54Z Using /16 prefix for IP bucketing
2021-01-21T15:30:54Z Cache configuration:
2021-01-21T15:30:54Z * Using 2.0 MiB for block index database
2021-01-21T15:30:54Z * Using 56.0 MiB for transaction index database
2021-01-21T15:30:54Z * Using 8.0 MiB for chain state database
2021-01-21T15:30:54Z * Using 384.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2021-01-21T15:30:54Z init message: Loading block index...
2021-01-21T15:30:54Z Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
2021-01-21T15:30:54Z Opened LevelDB successfully
2021-01-21T15:30:54Z Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000
2021-01-21T15:30:58Z LoadBlockIndexDB: last block file = 2417
2021-01-21T15:30:58Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=6, size=8006735, heights=667029...667034, time=2021-01-21...2021-01-21)
2021-01-21T15:30:58Z Checking all blk files are present...
2021-01-21T15:30:58Z Opening LevelDB in /home/bitcoin/.bitcoin/chainstate
2021-01-21T15:30:58Z Opened LevelDB successfully
2021-01-21T15:30:58Z Using obfuscation key for /home/bitcoin/.bitcoin/chainstate: 8d04dcac7c5beaa0
2021-01-21T15:30:58Z Loaded best chain: hashBestChain=000000000000000000029ce801aba0474f571370c0f12808bae6501cf9ca1cec height=667034 date=2021-01-21T15:13:02Z progress=0.999994
2021-01-21T15:30:58Z init message: Rewinding blocks...
2021-01-21T15:30:58Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) started
2021-01-21T15:30:58Z FlushStateToDisk: write coins cache to disk (0 coins, 0kB) completed (0.00s)
2021-01-21T15:30:58Z init message: Verifying blocks...
2021-01-21T15:30:58Z Verifying last 6 blocks at level 3
2021-01-21T15:30:58Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2021-01-21T15:31:03Z No coin database inconsistencies in last 6 blocks (11765 transactions)
2021-01-21T15:31:03Z  block index            9520ms
2021-01-21T15:31:03Z Opening LevelDB in /home/bitcoin/.bitcoin/indexes/txindex
2021-01-21T15:31:03Z Opened LevelDB successfully
2021-01-21T15:31:03Z Using obfuscation key for /home/bitcoin/.bitcoin/indexes/txindex: 0000000000000000
2021-01-21T15:31:03Z init message: Loading wallet...
2021-01-21T15:31:03Z txindex thread start
2021-01-21T15:31:03Z txindex is enabled at height 667034
2021-01-21T15:31:03Z txindex thread exit
2021-01-21T15:31:03Z BerkeleyEnvironment::Open: LogDir=/home/bitcoin/.bitcoin/database ErrorFile=/home/bitcoin/.bitcoin/db.log
2021-01-21T15:31:03Z [default wallet] Wallet File Version = 169900
2021-01-21T15:31:03Z [default wallet] Keys: 2001 plaintext, 0 encrypted, 2001 w/ metadata, 2001 total. Unknown wallet records: 0
2021-01-21T15:31:03Z [default wallet] Wallet completed loading in              35ms
2021-01-21T15:31:03Z [default wallet] setKeyPool.size() = 2000
2021-01-21T15:31:03Z [default wallet] mapWallet.size() = 0
2021-01-21T15:31:03Z [default wallet] m_address_book.size() = 0
2021-01-21T15:31:03Z block tree size = 667038
2021-01-21T15:31:03Z nBestHeight = 667034
2021-01-21T15:31:03Z torcontrol thread start
2021-01-21T15:31:03Z Bound to [::]:8333
2021-01-21T15:31:03Z Bound to 0.0.0.0:8333
2021-01-21T15:31:03Z init message: Loading P2P addresses...
```

### PR DESCRIPTION
**Pull request by mzumsande**
Fixes #20978

If a block was pruned, `getblock` already returns a specific error: "Block not available (pruned data)".
But if we haven't received the full block yet (e.g. in a race with block downloading after a new block was received headers-first, or during IBD) we just return an unspecific "Block not found on disk" error and log
`ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0) `
which suggest something went wrong even though this is a completely normal and expected situation.

This PR improves the error message and stops calling `ReadRawBlockFromDisk()`, when we already know from the header that the block is not available on disk.
Similarly, it prevents all other rpcs from calling blockstorage read functions unless we expect the data to be there, so that `LogError()` will only be thrown when there is an actual file system problem.

I'm not  completely sure if the cause is important enough to change the wording of the rpc error, that some scripts may rely on.
If reviewers prefer it, an alternative solution would be to keep returning the current "Block not found on disk" error, but return it immediately instead of calling `ReadRawBlockFromDisk`, which would at least prevent the log error and also be an improvement in my opinion.

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Concept ACK

File: src/rpc/blockchain.cpp [hunk 1]
```diff
@@ -606,6 +606,8 @@ static std::vector<uint8_t> GetRawBlockChecked(BlockManager& blockman, const CBl
         LOCK(cs_main);
         if (blockman.IsBlockPruned(blockindex)) {
             throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
+        } else if (!(blockindex.nStatus & BLOCK_HAVE_DATA)) {
+            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (not fully downloaded)");
         }
```
Comment (fjahr) [inline src/rpc/blockchain.cpp:611]: Here and in `rest.cpp`: Structuring it like this should save us the `IsBlockPruned()` call in the normal case (untested). `IsBlockPruned()` checks the same condition plus something extra so this should not change behavior.

```suggestion
        if (!(blockindex.nStatus & BLOCK_HAVE_DATA)) {
            if (blockman.IsBlockPruned(blockindex) {
                throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
            }
            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (not fully downloaded)");
        }
```

**Comment by fjahr** [comment]
Concept ACK

**Review by maflcko — COMMENTED** [review]
Thanks for picking this up.

Seems fine to fix it this way.

However, you forgot `GetBlockChecked` (and all the other functions that can fail in the same way)?

My preference to fix it would be to move the checks to the inside of the block manager. This way,

* module-external cs_main locking (and races) are avoided, because a prune call happening after the  `IsBlockPruned` check (and leaving the scope of cs_main) could be detected, if wanted, by doing the check again in the block manager
* error case enumeration and handling are done in a single place, as opposed to every call site
* It would be easier for call sites to differentiate between read failures caused by logic bugs (what this pull is trying to solve) and read failures caused by IO corruption.

However, this basically requires a full rewrite of the blockmanager read-interface, so I haven't completed it yet. (Happy to pick it up again, if you think it makes sense as well)

File: src/rpc/blockchain.cpp (hunk 1 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: done. Performance doesn't seem that important, but I also think it's a bit clearer that way.

**Comment by mzumsande** [comment]
> However, you forgot GetBlockChecked (and all the other functions that can fail in the same way)?

Updated to change all functions I could find. I was only looking at `getblock` before, not at other RPCs.

>My preference to fix it would be to move the checks to the inside of the block manager. 

> However, this basically requires a full rewrite of the blockmanager read-interface, so I haven't completed it yet. (Happy to pick it up again, if you think it makes sense as well)

Makes sense to me, so concept a c k to that! Depending on how large this PR is going to be and how long it's going to take to complete it, I could either close this simple PR, which changes return errors and is not a refactor, or it could be a pure refactor on top of it? Let me know what you prefer.

File: src/rpc/blockchain.cpp [hunk 2]
```diff
@@ -583,8 +583,11 @@ static CBlock GetBlockChecked(BlockManager& blockman, const CBlockIndex& blockin
     CBlock block;
     {
         LOCK(cs_main);
-        if (blockman.IsBlockPruned(blockindex)) {
-            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
+        if (!(blockindex.nStatus & BLOCK_HAVE_DATA)) {
+            if (blockman.IsBlockPruned(blockindex)) {
+                throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
+            }
+            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (not fully downloaded)");
```
Comment (tdb3) [inline src/rpc/blockchain.cpp:590]: nit:  The comment below should also be adjusted.  The case where the header is available but we don't have the block yet is covered by this new `JSONRPCError`.

        // Block not found on disk. This could be because we have the block
        // header in our index but not yet have the block or did not accept the
        // block. Or if the block was pruned right after we released the lock above.

File: src/rpc/blockchain.cpp [hunk 3]
```diff
@@ -604,8 +607,11 @@ static std::vector<uint8_t> GetRawBlockChecked(BlockManager& blockman, const CBl
     FlatFilePos pos{};
     {
         LOCK(cs_main);
-        if (blockman.IsBlockPruned(blockindex)) {
-            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
+        if (!(blockindex.nStatus & BLOCK_HAVE_DATA)) {
+            if (blockman.IsBlockPruned(blockindex)) {
+                throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
+            }
+            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (not fully downloaded)");
```
Comment (tdb3) [inline src/rpc/blockchain.cpp:614]: nit: Same for here

        // Block not found on disk. This could be because we have the block
        // header in our index but not yet have the block or did not accept the
        // block. Or if the block was pruned right after we released the lock above.

**Review by tdb3 — COMMENTED** [review]
Concept ACK
Thanks for picking this up.  Overall, I think adding clarity for the user is a net positive.

> I'm not completely sure if the cause is important enough to change the wording of the rpc error, that some scripts may rely on.

I agree, this may be a borderline case because `Block not found on disk` seems like it is correct albeit not as descriptive.  Since we're not changing RPC data structure or error codes (just the message), I'm not even sure if implementing `deprecatedrpc` is fully appropriate.

https://corecheck.dev/bitcoin/bitcoin/pulls/30410

Looks like we lost coverage for the original `Block not found on disk` error, so it would be good to add a commit with a test for that (or in a follow up).  Maybe something like the following (and possibly move `move_block_file()` into the framework to allow reuse).

```diff
diff --git a/test/functional/rpc_blockchain.py b/test/functional/rpc_blockchain.py
index 4807551c0c3..363255ba48f 100755
--- a/test/functional/rpc_blockchain.py
+++ b/test/functional/rpc_blockchain.py
@@ -638,6 +638,11 @@ class BlockchainTest(BitcoinTestFramework):
         node.submitheader(block["hex"])
         assert_raises_rpc_error(-1, "Block not available (not fully downloaded)", lambda: node.getblock(block["hash"]))
 
+        self.log.info("Test getblock when block is missing")
+        move_block_file('blk00000.dat', 'blk00000.dat.bak')
+        assert_raises_rpc_error(-1, "Block not found on disk", node.getblock, blockhash)
+        move_block_file('blk00000.dat.bak', 'blk00000.dat')
+
 
 if __name__ == '__main__':
     BlockchainTest().main()
diff --git a/test/functional/rpc_getblockstats.py b/test/functional/rpc_getblockstats.py
index bf261befcc8..c4b4de65e80 100755
--- a/test/functional/rpc_getblockstats.py
+++ b/test/functional/rpc_getblockstats.py
@@ -182,5 +182,10 @@ class GetblockstatsTest(BitcoinTestFramework):
         assert_equal(tip_stats["utxo_increase_actual"], 4)
         assert_equal(tip_stats["utxo_size_inc_actual"], 300)
 
+        self.log.info('Test when block is missing')
+        (self.nodes[0].blocks_path / 'blk00000.dat').rename(self.nodes[0].blocks_path / 'blk00000.dat.backup')
+        assert_raises_rpc_error(-1, 'Block not found on disk', self.nodes[0].getblockstats, hash_or_height=1)
+        (self.nodes[0].blocks_path / 'blk00000.dat.backup').rename(self.nodes[0].blocks_path / 'blk00000.dat')
+
 if __name__ == '__main__':
     GetblockstatsTest().main()
```

File: src/rpc/blockchain.cpp [hunk 4]
```diff
@@ -629,8 +635,11 @@ static CBlockUndo GetUndoChecked(BlockManager& blockman, const CBlockIndex& bloc
 
     {
         LOCK(cs_main);
-        if (blockman.IsBlockPruned(blockindex)) {
-            throw JSONRPCError(RPC_MISC_ERROR, "Undo data not available (pruned data)");
+        if (!(blockindex.nStatus & BLOCK_HAVE_DATA)) {
+            if (blockman.IsBlockPruned(blockindex)) {
+                throw JSONRPCError(RPC_MISC_ERROR, "Block not available (pruned data)");
```
Comment (andrewtoth) [inline src/rpc/blockchain.cpp:640]:
```suggestion
                throw JSONRPCError(RPC_MISC_ERROR, "Undo not available (pruned data)");
```

File: src/rpc/blockchain.cpp [hunk 5]
```diff
@@ -629,8 +635,11 @@ static CBlockUndo GetUndoChecked(BlockManager& blockman, const CBlockIndex& bloc
...
+            }
+            throw JSONRPCError(RPC_MISC_ERROR, "Block not available (not fully downloaded)");
```
Comment (andrewtoth) [inline src/rpc/blockchain.cpp:642]:
```suggestion
            throw JSONRPCError(RPC_MISC_ERROR, "Undo not available (not fully downloaded)");
```

Comment (andrewtoth) [inline src/rpc/blockchain.cpp:642]: It feels like the rule of the 3 is being hit here and this code could be DRY'd up? Maybe in a helper function that takes the string `"Block"` or `"Undo"` and does string formatting?

**Review by andrewtoth — APPROVED** [review]
Concept ACK

File: src/rpc/blockchain.cpp [hunk 6]
```diff
@@ -629,8 +635,11 @@ static CBlockUndo GetUndoChecked(BlockManager& blockman, const CBlockIndex& bloc
 
     {
         LOCK(cs_main);
-        if (blockman.IsBlockPruned(blockindex)) {
-            throw JSONRPCError(RPC_MISC_ERROR, "Undo data not available (pruned data)");
+        if (!(blockindex.nStatus & BLOCK_HAVE_DATA)) {
```
Comment (andrewtoth) [inline src/rpc/blockchain.cpp:638]:
```suggestion
        if (!(blockindex.nStatus & BLOCK_HAVE_UNDO)) {
```

**Comment by mzumsande** [comment]
> Ok, I am done, but I think it is easier to review this pull request.

OK - I'm working on addressing the feedback, plus adding more test coverage for the different types of errors. Will update soon!

**Review by BrandonOdiwuor — COMMENTED** [review]
Concept ACK

File: src/rpc/blockchain.cpp (hunk 2 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: done, thanks!

File: src/rpc/blockchain.cpp (hunk 3 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: done, thanks!

File: src/rpc/blockchain.cpp (hunk 5 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: I have now added a single function `CheckHeaderForData` that takes a bool for querying undo data.

Comment (mzumsande) [reply src/rpc/blockchain.cpp]: fixed (see below)

File: src/rpc/blockchain.cpp (hunk 4 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: fixed (see below)

File: src/rpc/blockchain.cpp (hunk 6 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: fixed

**Review by andrewtoth — APPROVED** [review]
utACK 02f6a42be3dfc57998304801c0d909bfa96745e4

**Comment by mzumsande** [comment]
[02f6a42 ](https://github.com/bitcoin/bitcoin/commit/02f6a42be3dfc57998304801c0d909bfa96745e4)to 4fb708c:
Rebased and fixed silent conflict with #30636.

**Comment by andrewtoth** [comment]
I'm unsure why CI is failing now...

**Comment by fanquake** [comment]
@andrewtoth the CI failure in the test-each-commit job is unrelated to the changes (missing zmq package, fixed in #30749).

**Comment by mzumsande** [comment]
> @andrewtoth the CI failure in the test-each-commit job is unrelated to the changes (missing zmq package, fixed in #30749).

Thanks, I also wasn't sure! I've just rebased again.

File: src/rpc/blockchain.cpp [hunk 7]
```diff
@@ -184,7 +184,7 @@ UniValue blockToJSON(BlockManager& blockman, const CBlock& block, const CBlockIn
         case TxVerbosity::SHOW_DETAILS_AND_PREVOUT:
             CBlockUndo blockUndo;
             const bool is_not_pruned{WITH_LOCK(::cs_main, return !blockman.IsBlockPruned(blockindex))};
-            const bool have_undo{is_not_pruned && blockman.UndoReadFromDisk(blockUndo, blockindex)};
+            const bool have_undo{is_not_pruned && WITH_LOCK(::cs_main, return blockindex.nStatus & BLOCK_HAVE_UNDO) && blockman.UndoReadFromDisk(blockUndo, blockindex)};
```
Comment (fjahr) [inline src/rpc/blockchain.cpp:187]: In 041b78ccede9974117dac5d8623fedec2f32471d:

nit: I think it would be cleaner and easier to read if you break this up.

```suggestion
            const bool have_undo{is_not_pruned && WITH_LOCK(::cs_main, return blockindex.nStatus & BLOCK_HAVE_UNDO)};
            if (have_undo) {
                blockman.UndoReadFromDisk(blockUndo, blockindex);
            }
```

(same in `rpc/rawtransaction.cpp`)

Comment (mzumsande) [reply src/rpc/blockchain.cpp:187]: I can break this up, but I think the suggestion doesn't work because we still need to feed the result into `have_undo` so that if `UndoReadFromDisk` fails for an unexpected reason, we don't attempt to access `blockUndo` below and segfault.

File: src/rpc/blockchain.cpp [hunk 8]
```diff
@@ -580,7 +580,7 @@ static RPCHelpMan getblockheader()
     };
 }
 
-static void CheckHeaderForData(BlockManager& blockman, const CBlockIndex& blockindex, bool check_for_undo)
```
[the remark this answers is not in the document]
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: done

File: src/rpc/blockchain.cpp [hunk 9]
```diff
@@ -580,20 +580,32 @@ static RPCHelpMan getblockheader()
     };
 }
 
+static void CheckHeaderForData(BlockManager& blockman, const CBlockIndex& blockindex, bool check_for_undo)
```
[the remark this answers is not in the document]
Comment (mzumsande) [reply src/rpc/blockchain.cpp]: renamed to `CheckBlockDataAvailability()`

**Comment by mzumsande** [comment]
[041b78c ](https://github.com/bitcoin/bitcoin/commit/041b78ccede9974117dac5d8623fedec2f32471d)to [92236f4](https://github.com/bitcoin/bitcoin/commit/92236f43ff92c931f3a099e03d7851b890bff263): addressed feedback by @fjahr

File: src/rpc/blockchain.cpp (hunk 7 above)
Comment (fjahr) [reply src/rpc/blockchain.cpp]: > I think the suggestion doesn't work because we still need to feed the result into have_undo so that if UndoReadFromDisk fails for an unexpected reason like disk errors, we don't attempt to access blockUndo below and segfault.

I see, I think in that scenario it would be best to throw an error right there instead of ignoring it silently and giving the user an incomplete response? I mean, we have all indication that we should have the undo data in that scenario and then we can not read it, it seems like an error that the user should know about.

> In rpc/rawtransaction.cpp, did you mean to introduce a variable like skip_details or something to break this up?

I think that would work, I don't remember if I had something explicit in mind when I wrote it. It's just an awfully long list of conditions already and summing parts of them up in a variable with a concise name would make it easier to parse. I have left two additional suggestions there for shortening it inline and I think there it's the same question if we really want to silently return a limited result if we fail to read from disk what we are supposed to have. I'll wait for you feedback on that part and my inline suggestions. If nothing else I think it would also help a lot to just add line breaks after every condition.

Comment (mzumsande) [reply src/rpc/blockchain.cpp]: I think it makes sense to throw an error in this situation. Although it's not necessarily due to disk corruption, it would also be possible that the block/undo data is pruning event right after the blockindex check (`cs_main` is released) and before the `UndoReadFromDisk` call.

We also have a functional test for just this situation that wouldn't work anymore ([here](https://github.com/bitcoin/bitcoin/blob/c66c68345efb0bb3d5613ebac703cde779fa0f01/test/functional/rpc_blockchain.py#L615-L628)) but that tests doesn't actually prune a block but deletes an undo file to simulate pruning. So we'd either have to just remove it or actually prune a block... I'll try this out in the next days.

**Review by fjahr — COMMENTED** [review]
@mzumsande Sorry, I had written the comment below already earlier but failed to submit it because of github being github. But it seems like it's in line with your response.

File: src/rpc/rawtransaction.cpp [hunk 10]
```diff
@@ -405,7 +405,7 @@ static RPCHelpMan getrawtransaction()
     CBlockUndo blockUndo;
     CBlock block;
 
-    if (tx->IsCoinBase() || !blockindex || WITH_LOCK(::cs_main, return chainman.m_blockman.IsBlockPruned(*blockindex)) ||
+    if (tx->IsCoinBase() || !blockindex || WITH_LOCK(::cs_main, return !(blockindex->nStatus & BLOCK_HAVE_UNDO) || !(blockindex->nStatus & BLOCK_HAVE_DATA)) ||
         !(chainman.m_blockman.UndoReadFromDisk(blockUndo, *blockindex) && chainman.m_blockman.ReadBlockFromDisk(block, *blockindex))) {
```
Comment (furszy) [inline src/rpc/rawtransaction.cpp:409]: q: if the `block` is only used to obtain the undo data, shouldn't this be a `!chainman.m_blockman.ReadBlockFromDisk(block, *blockindex))`? (negated)

Comment (mzumsande) [reply src/rpc/rawtransaction.cpp:409]: We need both block and undo data below if we don't skip with the non-detailed response here. So there is a parenthesis after the first negation, so the logic is `not(a and b)` which is the same as `not(a) or not(b).`

Comment (furszy) [reply src/rpc/rawtransaction.cpp:409]: ah, missed the extra parenthesis. Good.
Might be good to decouple it as proposed in https://github.com/bitcoin/bitcoin/pull/30410#discussion_r1752283015.

I wish there would be methods for "hasBlockData()" and "hasUndoData()" so we are not forced to use the internal `BlockStatus` enum everywhere.

**Review by furszy — COMMENTED** [review]
Code review ACK 92236f43ff92c931f3a099e03d7851b890bff263

File: src/rpc/rawtransaction.cpp [hunk 11]
```diff
@@ -405,7 +405,7 @@ static RPCHelpMan getrawtransaction()
     CBlockUndo blockUndo;
     CBlock block;
 
-    if (tx->IsCoinBase() || !blockindex || WITH_LOCK(::cs_main, return chainman.m_blockman.IsBlockPruned(*blockindex)) ||
+    if (tx->IsCoinBase() || !blockindex || WITH_LOCK(::cs_main, return !(blockindex->nStatus & BLOCK_HAVE_UNDO) || !(blockindex->nStatus & BLOCK_HAVE_DATA)) ||
```
[the remark this answers is not in the document]
Comment (mzumsande) [reply src/rpc/rawtransaction.cpp]: done, good idea!

**Comment by mzumsande** [comment]
[92236f4 ](https://github.com/bitcoin/bitcoin/commit/92236f43ff92c931f3a099e03d7851b890bff263)to [ccee8a2](https://github.com/bitcoin/bitcoin/commit/ccee8a274770a060fa917f24828f2e2f5c1875ee):

Changed the last commit such that now it throws an error if our block index indicates we should have block/undo data but we can't read it.
Also changed the functional test: Before, it would try to imitate a "pruning" situation by just deleting the undo file. This made little sense to me, because when we prune we prune both block and undo data together (and would have failed earlier due to missing block data). The situation with block data and no undo data can occur though, with blocks that haven't been connected. I've added a test for that.

File: src/rpc/blockchain.cpp [hunk 12]
```diff
@@ -597,20 +597,32 @@ static RPCHelpMan getblockheader()
     };
 }
 
+void CheckBlockDataAvailability(BlockManager& blockman, const CBlockIndex& blockindex, bool check_for_undo)
+{
+    AssertLockHeld(cs_main);
+    uint32_t flag = check_for_undo ? BLOCK_HAVE_UNDO : BLOCK_HAVE_DATA;
```
Comment (fjahr) [inline src/rpc/blockchain.cpp:605]: More or a question: when `check_for_undo` is true doe we actually want to check for both? Having undo and not data set here would seem to be something going weirdly wrong though I guess.

```suggestion
    uint32_t flag = check_for_undo ? BLOCK_HAVE_MASK : BLOCK_HAVE_DATA;
```

File: src/rpc/rawtransaction.cpp [hunk 13]
```diff
@@ -405,11 +405,16 @@ static RPCHelpMan getrawtransaction()
...
     CBlock block;
 
-    if (tx->IsCoinBase() || !blockindex || WITH_LOCK(::cs_main, return chainman.m_blockman.IsBlockPruned(*blockindex)) ||
-        !(chainman.m_blockman.UndoReadFromDisk(blockUndo, *blockindex) && chainman.m_blockman.ReadBlockFromDisk(block, *blockindex))) {
+    if (tx->IsCoinBase() || !blockindex || WITH_LOCK(::cs_main, return !(blockindex->nStatus & BLOCK_HAVE_MASK))) {
         TxToJSON(*tx, hash_block, result, chainman.ActiveChainstate());
         return result;
     }
+    if (!chainman.m_blockman.UndoReadFromDisk(blockUndo, *blockindex)) {
+        throw JSONRPCError(RPC_INTERNAL_ERROR, "Undo data expected but can't be read. This could be due to disk coruption or a conflict with a pruning event.");
```
Comment (fjahr) [inline src/rpc/rawtransaction.cpp:413]: typo: corruption

File: src/rpc/rawtransaction.cpp [hunk 14]
```diff
@@ -405,11 +405,16 @@ static RPCHelpMan getrawtransaction()
...
+    }
+    if (!chainman.m_blockman.ReadBlockFromDisk(block, *blockindex)) {
+        throw JSONRPCError(RPC_INTERNAL_ERROR, "Block data expected but can't be read. This could be due to disk coruption or a conflict with a pruning event.");
```
Comment (fjahr) [inline src/rpc/rawtransaction.cpp:416]: typo: corruption

File: src/rpc/blockchain.cpp [hunk 15]
```diff
@@ -201,8 +201,10 @@ UniValue blockToJSON(BlockManager& blockman, const CBlock& block, const CBlockIn
         case TxVerbosity::SHOW_DETAILS_AND_PREVOUT:
             CBlockUndo blockUndo;
             const bool is_not_pruned{WITH_LOCK(::cs_main, return !blockman.IsBlockPruned(blockindex))};
-            const bool have_undo{is_not_pruned && blockman.UndoReadFromDisk(blockUndo, blockindex)};
-
+            bool have_undo{is_not_pruned && WITH_LOCK(::cs_main, return blockindex.nStatus & BLOCK_HAVE_UNDO)};
+            if (have_undo && !blockman.UndoReadFromDisk(blockUndo, blockindex)) {
+                throw JSONRPCError(RPC_INTERNAL_ERROR, "Undo data expected but can't be read. This could be due to disk coruption or a conflict with a pruning event.");
```
Comment (fjahr) [inline src/rpc/blockchain.cpp:206]: typo: corruption

**Review by fjahr — COMMENTED** [review]
Code review ACK a5df908d981138f066f5f963a1813d453483814a

Feel free to ignore typo comments unless you retouch.

Also saw a typo in 8bfb0bd7bd5f8963fb1f58988f9bb36199dc98de commit message: "dowloaded"

File: src/rpc/blockchain.cpp (hunk 12 above)
Comment (mzumsande) [reply src/rpc/blockchain.cpp:605]: I agree that it shouldn't be possible to have undo data but no block data.
On the other hand, callers of this function may not even be interested in the block data, and I'm not sure if a RPC call is the right place to check for this inconsistency. At least it's checked in `CheckBlockIndex()` [here](https://github.com/bitcoin/bitcoin/blob/06a9f7789e359131abad2489a221888f711bdc3b/src/validation.cpp#L5326), so I think I'll leave this as is for now.

File: src/rpc/rawtransaction.cpp (hunk 13 above)
Comment (mzumsande) [reply src/rpc/rawtransaction.cpp]: fixed

**Comment by mzumsande** [comment]
[a5df908 ](https://github.com/bitcoin/bitcoin/commit/a5df908d981138f066f5f963a1813d453483814a)to [6a1aa51](https://github.com/bitcoin/bitcoin/commit/6a1aa510e31e8b77793341473aa5afc9d023a6e3): Fixed typos.

**Review by andrewtoth — APPROVED** [review]
re-ACK 6a1aa510e31e8b77793341473aa5afc9d023a6e3

**Comment by fjahr** [comment]
re-ACK 6a1aa510e31e8b77793341473aa5afc9d023a6e3

**Comment by achow101** [comment]
ACK 6a1aa510e31e8b77793341473aa5afc9d023a6e3

**Comment by Sjors** [comment]
It would be nice to have unique (new) RPC error codes for this, because e.g. with ForkMonitor I was parsing the string that comes with `RPC_MISC_ERROR`, which this PR slightly changes.

https://github.com/jonathanbier/forkmonitor/commit/2d0e9f48cbd95b5ce52416ef497d1691ea3e24f0
