### PR TITLE
feefrac: avoid integer overflow in temporary

### LINKED ISSUE #32294: feefrac_mul_div: Integer-overflow in FeeFrac::Div
https://issues.oss-fuzz.com/issues/411172125:

```
echo '//v////7/////f////////8=' | base64 --decode > /tmp/dat

UBSAN_OPTIONS="suppressions=$(pwd)/test/sanitizer_suppressions/ubsan:print_stacktrace=1:halt_on_error=1:report_error_type=1" FUZZ=feefrac_mul_div  ./bld-cmake/bin/fuzz /tmp/dat
```

```
src/util/feefrac.h:99:21: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'int64_t' (aka 'long')

### PR DESCRIPTION
**Pull request by sipa**
In `FeeFrac::Div(__int128 n, int32_t d, bool round_down)` in src/util/feefrac.h, the following line computes the result:

```c++
        return quot + (mod > 0) - (mod && round_down);
```

The function can only be called under conditions where the result is in range, and thus doesn't involve any integer overflow. However, the intermediary result computed by just `quot + (mod > 0)` may still overflow if it's going to be corrected by the `- (mod && round_down)` that follows.

Fix this by balancing the two correction steps with each other first:
```c++
        return quot + ((mod > 0) - (mod && round_down));
```

Fixes #32294.

### CODE REVIEW

**Review by 1440000bytes — COMMENTED** [review]
ACK https://github.com/bitcoin/bitcoin/pull/32300/commits/6dd574444598240d2622e06e402548312123e5ef

Code and motivation looks good. I couldn't find any instance of such changes to introduce bug.

File: src/util/feefrac.h [hunk 1]
```diff
@@ -96,7 +96,7 @@ struct FeeFrac
         int64_t quot = n / d;
         int32_t mod = n % d;
         // Correct result if the / operator above rounded in the wrong direction.
-        return quot + (mod > 0) - (mod && round_down);
+        return quot + ((mod > 0) - (mod && round_down));
```
Comment (l0rinc) [inline src/util/feefrac.h:99]: The new code:

```C++
quot + ((mod > 0) - (mod && round_down));
```
Compiles to
```ASM
test    eax, eax
setne   al
setg    bl
movzx   eax, al
and     eax, ecx
*sub     ebx, eax*
movsx   rbx, ebx
*add     rbx, rdx*
```
(`-` before `+`)

while the old one:
```C++
quot + (mod > 0) - (mod && round_down);
```
Compiles to
```ASM
test    eax, eax
setg    bl
*add     rbx, rcx*
test    eax, eax
setne   al
movzx   eax, al
and     rax, rdx
*sub     rbx, rax*
```
(`+` before `-`)

----

The original suggestion also had the subtraction first: https://github.com/bitcoin/bitcoin/pull/30535#discussion_r1698947273

**Review by l0rinc — APPROVED** [review]
ACK 6dd574444598240d2622e06e402548312123e5ef

If you think it's useful, we could hard code the behavior via a unit test based on the fuzz finding

File: src/util/feefrac.h (hunk 1 above)
Comment (l0rinc) [reply src/util/feefrac.h:99]: Given that this tricked most of us, would it make sense to cover it with unit tests which demonstrate the behavior difference before/after?

Comment (l0rinc) [reply src/util/feefrac.h:99]: The simplest way I could find is to call it directly (not sure what the fuzzer did, don't have access):
```C++
BOOST_AUTO_TEST_CASE(feefrac_div_round_down_overflow)
{
#ifdef __SIZEOF_INT128__
    constexpr auto divisor{2};
    constexpr auto expected_result{std::numeric_limits<int64_t>::max()};
    constexpr auto overflow_numerator{__int128{expected_result} * divisor + 1};
    BOOST_CHECK_EQUAL(FeeFrac::Div(overflow_numerator, divisor, /*round_down=*/true), expected_result);
#else
    BOOST_TEST_MESSAGE("Skipped");
#endif
}
```


Which fails before the change with:
> cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j$(nproc) && build/bin/test_bitcoin --run_test='feefrac_tests/feefrac_div_round_down_overflow'
> ...
> Running 1 test case...
> Trace/BPT trap: 5

Comment (l0rinc) [reply src/util/feefrac.h:99]:
```C++
BOOST_CHECK_EQUAL((FeeFrac{0x7ffffffdfffffffb, 0x7ffffffd}.EvaluateFeeDown(0x7fffffff)), 0x7fffffffffffffff);
```
This works for me in simple Debug mode (with extra parentheses, built without sanitizers, doesn't fail in Release mode).
Before the fix this also fails with:
> cmake -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j$(nproc) && time build/bin/test_bitcoin --run_test='feefrac_tests/feefrac_operators'
...
> Running 1 test case...
> zsh: trace trap

**Comment by l0rinc** [comment]
Tested ACK 5cb1241814b9c541c5e5e8daadbbea595f2960ae
