### PR TITLE
net: Return IPv6 scope id in `CNetAddr::ToStringIP()`

### LINKED ISSUE #21982: Regression: CNetAddr scoped id/zone indices functionality
It's not clear to me if dropping support for this functionality was intentional.

Chain of events:

- #21689 removed test coverage due to a misunderstanding due, I believe, to this functionality being generally supported by all platforms except macOS which does not and returns a different format
- #21756 removed support and caused this regression
- #21690 restores the test coverage that would have caught this regression

Currently, neither the test coverage before #21689 nor the coverage restored by #21690 pass since the merge of #21756.

### PR DESCRIPTION
**Pull request by laanwj**
If a scope id is provided, return it back in the string representation. Also bring back the test (now in platform independent fashion). Closes #21982. Includes #21961 (apart from the MacOS remark).

### CODE REVIEW

File: src/test/net_tests.cpp [hunk 1]
```diff
@@ -301,12 +301,18 @@ BOOST_AUTO_TEST_CASE(cnetaddr_basic)
     // IPv6, scoped/link-local. See https://tools.ietf.org/html/rfc4007
     // We support non-negative decimal integers (uint32_t) as zone id indices.
     // Test with a fairly-high value, e.g. 32, to avoid locally reserved ids.
```
Comment (jonatack) [inline src/test/net_tests.cpp:303]: nit, can drop this line as we are no longer concerned about collisions with locally reserved zone ids

**Review by jonatack — COMMENTED** [review]
ACK 90972a8962cfd9bf63f3b982f5a85fcdc41f253d according to https://datatracker.ietf.org/doc/html/rfc4007#section-11.2 and https://en.wikipedia.org/wiki/IPv6_address#zone_index numeric zone indices like these (% + uint32, default 0 that can be omitted) should be mandatory/universally supported

File: src/test/net_tests.cpp (hunk 1 above)
Comment (laanwj) [reply src/test/net_tests.cpp:303]: I wasn't sure whether this was a problem for parsing or for formatting, that's why I kept it. But makes sense, will remove it.

**Comment by jonatack** [comment]
ACK c7d461b014422f1aaa13ae978d730864616ab7bb

**Comment by practicalswift** [comment]
Code looks correct, so code review ACK c7d461b014422f1aaa13ae978d730864616ab7bb

As stated in https://github.com/bitcoin/bitcoin/issues/21682#issuecomment-819897122 I have a slightly preference towards not including scope id in `CNetAddr::ToStringIP()` out. That is how Rust's `std::net::Ipv6Addr` work. That said: if others feels strongly about including scope id then I'm fine with that too. The important thing for me is that IPv6 addresses are printed identically across platforms and that goal has been achieved :)

Also it is probably worth noting that the requirements for _parsing_ and _printing_ IPv6 addresses are not the same.

**Comment by practicalswift** [comment]
@laanwj 

Thanks for providing the Rust `SocketAddrV6` string representation example. I see your point regarding it being different animals, and I guess this entire discussion boils down to if the expectation is that `CNetAddr::ToStringIP()` should print the IPv6 _address_ or the IPv6 _socket address_:
* IPv6 address ([std::net::Ipv6Addr](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html)): _"IPv6 addresses are defined as 128-bit integers in IETF RFC 4291. They are usually represented as eight 16-bit segments."_
* IPv6 socket address ([std::net::SocketAddrV6](https://doc.rust-lang.org/std/net/struct.SocketAddrV6.html)): _"IPv6 socket addresses consist of an IPv6 address, a 16-bit port number, as well as fields containing the traffic class, the flow label, and a scope identifier (see IETF RFC 2553, Section 3.3 for more details)."_

Is that a fair summary? :)

**Comment by laanwj** [comment]
For better or worse our data representation has an intermediate nesting level that doesn't neatly fit into that division.
`CService` is the full "socket address" addres + port + scope_id, CNetAddr is address **+ scope_id**.

As this is our data representation I think the think representation should reflect this.

File: src/test/net_tests.cpp [hunk 2]
```diff
@@ -300,13 +300,18 @@ BOOST_AUTO_TEST_CASE(cnetaddr_basic)
...
+    // zone id, for example, given a link-local address of "fe80::1" and a zone
+    // id of "32", return the address as "fe80::1%32".
     const std::string link_local{"fe80::1"};
     const std::string scoped_addr{link_local + "%32"};
     BOOST_REQUIRE(LookupHost(scoped_addr, addr, false));
     BOOST_REQUIRE(addr.IsValid());
     BOOST_REQUIRE(addr.IsIPv6());
     BOOST_CHECK(!addr.IsBindAny());
+    const std::string addr_str{addr.ToString()};
+    BOOST_CHECK(addr_str == scoped_addr);
```
Comment (vasild) [inline src/test/net_tests.cpp:313]: `BOOST_CHECK_EQUAL()` would print both values in case of failure. The extra variable `addr_str` looks like just clutter to me.

```suggestion
    BOOST_CHECK_EQUAL(addr.ToString(), scoped_addr);
```

**Review by vasild — APPROVED** [review]
ACK c7d461b014422f1aaa13ae978d730864616ab7bb

If the zone was (mostly) printed before (by `getnameinfo()`), keep printing it.

**Review by Twan1409 — COMMENTED** [review]
Ok

**Review by Twan1409 — CHANGES_REQUESTED** [review]
Ok

File: src/test/net_tests.cpp (hunk 2 above)
Comment (laanwj) [reply src/test/net_tests.cpp:313]: FWIW, I've simply restored this code from git history. But sure I'm fine with updating it.

**Comment by laanwj** [comment]
Updated the test for @vasild's comment.

**Comment by practicalswift** [comment]
cr ACK 6c280adcd865ae3da4df53d630c9bf737283a56f

> > […] I guess this entire discussion boils down to if the expectation is that `CNetAddr::ToStringIP()` should print the IPv6 _address_ or the IPv6 _socket address_:
> > * IPv6 address (std::net::Ipv6Addr): "IPv6 addresses are defined as 128-bit integers in IETF RFC 4291. They are usually represented as eight 16-bit segments."
> > * IPv6 socket address (std::net::SocketAddrV6): "IPv6 socket addresses consist of an IPv6 address, a 16-bit port number, as well as fields containing the traffic class, the flow label, and a scope identifier (see IETF RFC 2553, Section 3.3 for more details)."
>
> For better or worse our data representation has an intermediate nesting level that doesn't neatly fit into that division.
CService is the full "socket address" [addres + scope_id] + port, CNetAddr is address **+ scope_id**.
> 
> As this is our data representation I think the string representation should reflect this.

OK, I can see that point and I'm fine with that :)

**Comment by jonatack** [comment]
Post-merge ACK 6c280adcd865ae3da4df53d630c9bf737283a56f

`addr.ToString()` was previously memoized because it was used twice, once for checking the behavior on most platforms and a second time for the different behavior exhibited by macOS. We now only need it once, so good idea to simplify it. 

git diff c7d461b 6c280ad 
```diff
diff --git a/src/test/net_tests.cpp b/src/test/net_tests.cpp
index c0d3c3196e..7a122bd8b0 100644
--- a/src/test/net_tests.cpp
+++ b/src/test/net_tests.cpp
@@ -309,8 +309,7 @@ BOOST_AUTO_TEST_CASE(cnetaddr_basic)
     BOOST_REQUIRE(addr.IsValid());
     BOOST_REQUIRE(addr.IsIPv6());
     BOOST_CHECK(!addr.IsBindAny());
-    const std::string addr_str{addr.ToString()};
-    BOOST_CHECK(addr_str == scoped_addr);
+    BOOST_CHECK_EQUAL(addr.ToString(), scoped_addr);
```
