### PR TITLE
test: Switch multiprocess to clang i686 build

### LINKED ISSUE #22889: Compiling fails on 32-bit systems
Since #20233 compiling with clang 10.0 fails:
```
bench/addrman.cpp:113:32: error: non-constant-expression cannot be narrowed from type 'unsigned long long' to 'size_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
    const size_t addrman_count{bench.epochs() * bench.epochIterations()};
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bench/addrman.cpp:113:32: note: insert an explicit cast to silence this issue
    const size_t addrman_count{bench.epochs() * bench.epochIterations()};
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                               static_cast<size_t>(                    )
1 error generated.
make[2]: *** [Makefile:12508: bench/bench_bitcoin-addrman.o] Error 1
```

### PR DESCRIPTION
**Pull request by maflcko**
Building for i686 with clang helps to catch bugs early for:
* The OSS-Fuzz i686 clang libFuzzer build
* The arm 32-bit native clang build

Fixes  #22889

### CODE REVIEW

File: ci/test/00_setup_env_i686_multiprocess.sh [hunk 1]
```diff
@@ -6,11 +6,12 @@
...
 export LC_ALL=C.UTF-8
 
-export CONTAINER_NAME=ci_native_multiprocess
+export HOST=i686-pc-linux-gnu
+export CONTAINER_NAME=ci_i686_multiprocess
 export DOCKER_NAME_TAG=ubuntu:20.04
-export PACKAGES="cmake python3 python3-pip llvm clang"
-export DEP_OPTS="DEBUG=1 MULTIPROCESS=1"
+export PACKAGES="cmake python3 python3-pip llvm clang g++-multilib"
+export DEP_OPTS="DEBUG=1 MULTIPROCESS=1 CC='clang -m32' CXX='clang++ -m32'"
```
Comment (hebasto) [inline ci/test/00_setup_env_i686_multiprocess.sh:13]: I believe this won't work due to #22184.

Comment (MarcoFalke) [reply ci/test/00_setup_env_i686_multiprocess.sh]: It should still compile successfully. Though, I removed it now to minimize the diff

Comment (hebasto) [reply ci/test/00_setup_env_i686_multiprocess.sh]: > It should still compile successfully.

Yes, it should. But with gcc, not clang.

**Comment by hebasto** [comment]
Great!

CI catches #22889.

**Comment by practicalswift** [comment]
Concept ACK

**Comment by laanwj** [comment]
Concept ACK

**Comment by MarcoFalke** [comment]
> Now add a fix?

Done

**Review by hebasto — APPROVED** [review]
ACK fa309ee61c09726a8780acaea94502712f817921
