### PR TITLE
Diagnose unsuitable outputs in lockunspent().

### LINKED ISSUE #2667: lockunspent returns true even for non-existent outputs
just use lockunspent with "txid":123 to reproduce

### PR DESCRIPTION
**Pull request by BitonicEelis**
Fixes #2667.

This is a simplified version of pull request #3574, which was abandoned by its author.

I added some tests as well.

### CODE REVIEW

File: src/wallet/rpcwallet.cpp [hunk 1]
```diff
@@ -2397,6 +2399,40 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
+            const auto it = pwallet->mapWallet.find(outpt.hash);
+            if (it == pwallet->mapWallet.end())
+                throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, unknown transaction");
+
+            const CWalletTx& trans = it->second;
+
+            if (outpt.n >= trans.tx->vout.size())
+                throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, vout index out of bounds");
+
+            if (pwallet->IsMine(trans.tx->vout[outpt.n]) == ISMINE_NO)
```
Comment (promag) [inline src/wallet/rpcwallet.cpp]: I think is must be either `ISMINE_SPENDABLE` or `ISMINE_WATCH_SOLVABLE`?

**Review by promag — COMMENTED** [review]
Read developer notes and update accordingly.

File: src/wallet/rpcwallet.cpp (hunk 1 above)
Comment (promag) [inline src/wallet/rpcwallet.cpp]: Do we really have to test `IsMine` and all? In the wallet it's just a `std::set<COutPoint>`, so IMO is enough to check:
- if the input is valid output
- if the lock state is compatible with the argument.

But if there is interest in doing these tests, then perform the cheapest first.

File: src/wallet/rpcwallet.cpp [hunk 2]
```diff
@@ -2397,6 +2399,40 @@ UniValue lockunspent(const JSONRPCRequest& request)
 
         COutPoint outpt(uint256S(txid), nOutput);
 
+        const bool isLocked = pwallet->IsLockedCoin(outpt.hash, outpt.n);
+
+        if (fUnlock)
```
Comment (BitonicEelis) [inline src/wallet/rpcwallet.cpp]: Thanks for the review! Are you absolutely sure that attempting to lock an already locked output should be an error?

Comment (promag) [inline src/wallet/rpcwallet.cpp]: IMO yes, it can indicate that it was locked by other client as such it is not yours to use?

Comment (BitonicEelis) [inline src/wallet/rpcwallet.cpp]: Ok, makes sense!

File: src/wallet/rpcwallet.cpp (hunk 1 above)
Comment (BitonicEelis) [inline src/wallet/rpcwallet.cpp]: I'll remove the check for now. It can always be added later.

**Comment by BitonicEelis** [comment]
Amended to:
- comply with variable naming policy
- reject attempts to lock already locked outputs
- remove MINE check

File: src/wallet/rpcwallet.cpp [hunk 3]
```diff
@@ -2397,6 +2399,38 @@ UniValue lockunspent(const JSONRPCRequest& request)
 
         COutPoint outpt(uint256S(txid), nOutput);
 
+        const bool is_locked = pwallet->IsLockedCoin(outpt.hash, outpt.n);
+
+        if (fUnlock && !is_locked)
```
Comment (promag) [inline src/wallet/rpcwallet.cpp]: Missing `{}` and `{` is one the same line. Same below. See [developer notes](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md).

Comment (BitonicEelis) [inline src/wallet/rpcwallet.cpp]: Will do! Thanks for caring about consistent style. :)

**Comment by BitonicEelis** [comment]
Amended to use curly brackets in accordance with developer notes.

**Comment by MeshCollider** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11087/commits/918b6db42b12d86a01bdb70a4fc50244aa2ce623

**Comment by laanwj** [comment]
utACK https://github.com/bitcoin/bitcoin/pull/11087/commits/918b6db42b12d86a01bdb70a4fc50244aa2ce623

File: test/functional/wallet.py [hunk 4]
```diff
@@ -93,11 +93,17 @@ def run_test(self):
         # Exercise locking of unspent outputs
         unspent_0 = self.nodes[2].listunspent()[0]
         unspent_0 = {"txid": unspent_0["txid"], "vout": unspent_0["vout"]}
+        assert_raises_jsonrpc(-8, "expected locked output", self.nodes[2].lockunspent, True, [unspent_0])
```
Comment (jnewbery) [inline test/functional/wallet.py]: Personally, I don't think the complete error message needs to be asserted, as long as the string is long enough to disambiguate. But also fine to change this to the complete string.

**Review by ryanofsky — COMMENTED** [review]
utACK 918b6db42b12d86a01bdb70a4fc50244aa2ce623

You could modernize the code a little more: adding a range for loop instead of an index loop, and using UniValue directly instead of adding adding new find_value calls. Also I'm not sure if it's useful to make locking an already locked output or unlocked an already unlocked one errors. But overall, this change seems like an improvement and looks good to merge.

File: src/wallet/rpcwallet.cpp [hunk 5]
```diff
@@ -2397,6 +2399,42 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
+        if (fUnlock && !is_locked) {
+            throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, expected locked output");
+        }
+
+        if (!fUnlock) {
+            if (is_locked) {
+                throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, output already locked");
+            }
+
+            if (pwallet->IsSpent(outpt.hash, outpt.n)) {
```
Comment (jnewbery) [inline src/wallet/rpcwallet.cpp]: Why are these three checks ("expected unspent", "unknown transaction" and "vout index out of bounds") only done when trying to lock? Isn't it equally invalid to try to unlock bad txouts? Can you place these three checks above the `const bool is_locked = pwallet->IsLockedCoin(outpt.hash, outpt.n);` line?

File: src/wallet/rpcwallet.cpp [hunk 6]
```diff
@@ -2397,6 +2399,42 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
+            const CWalletTx& trans = it->second;
+
+            if (outpt.n >= trans.tx->vout.size()) {
+                throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, vout index out of bounds");
+            }
+        }
+    }
+
+    // Atomically set (un)locked status for the outputs.
+    for (unsigned int idx = 0; idx < outputs.size(); idx++) {
```
Comment (jnewbery) [inline src/wallet/rpcwallet.cpp]: You could save reparsing the json by saving a vector of `COutPoint`s in the first pass.

**Review by jnewbery — COMMENTED** [review]
Looks good, and great test coverage. A couple of nits inline.

Maybe out of the scope of this PR, but this RPC returns `true` if called with `false` but no list of transactions. A user might expect that with that call all outputs have been locked, but in fact it's a no-op. I think that `if (request.params.size() == 1 && !fUnlock)` then we should return `false` or throw.

File: src/wallet/rpcwallet.cpp (hunk 6 above)
Comment (Eelis) [reply src/wallet/rpcwallet.cpp]: These loops don't do any json parsing, because the data is already in a UniValue. The `find_value` calls find the desired value in UniValue's internal std::vector of values.

File: src/wallet/rpcwallet.cpp (hunk 5 above)
Comment (Eelis) [reply src/wallet/rpcwallet.cpp]: The idea was that in all three of those cases (already spent output, unknown transaction, and vout index out of bounds), `IsLockedCoin` should already have returned false, so checking `!is_locked` should be enough.

File: src/wallet/rpcwallet.cpp (hunk 6 above)
Comment (jnewbery) [reply src/wallet/rpcwallet.cpp]: You're right. There's no reparsing the JSON, just rereading the string and reconstructing the COutPoint.

I think either way is fine. Whichever you prefer.

File: src/wallet/rpcwallet.cpp (hunk 5 above)
Comment (jnewbery) [reply src/wallet/rpcwallet.cpp]: I agree that the function will correctly return an error, but I think that it's better to return the more precise error if possible. `expected unspent output`, `unknown transaction` and `vout index out of bounds` are better to return than `expected locked output` (the last could infer that the outpoint exists but is unlocked).

Comment (Eelis) [reply src/wallet/rpcwallet.cpp]: Makes sense, I'll make the errors more precise.

**Comment by BitonicEelis** [comment]
Amended to:
- store COutPoints in vector instead of recomputing them
- include "invalid parameter:" error prefix in expectations in test
- make unlock errors more precise

@ryanofsky Unfortunately, range-for cannot be used to iterate over a UniValue because it does not provide begin()/end().

Thanks for the feedback!

File: src/wallet/rpcwallet.cpp [hunk 7]
```diff
@@ -2389,33 +2389,72 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
+
+    // Create and validate the COutPoints first.
+
+    std::vector<COutPoint> outputs;
+    outputs.reserve(output_params.size());
+
+    for (unsigned int idx = 0; idx < output_params.size(); idx++) {
+         const UniValue& param = output_params[idx];
+
+        if (!param.isObject()) {
```
Comment (jnewbery) [inline src/wallet/rpcwallet.cpp]: You can remove this check entirely. Type checking is done by the `UniValue.get_xxx()` functions, and returns almost an identical error to that given by this explicit check.

With the explicit check:

```
→ bitcoin-cli -rpcwallet=w1 lockunspent true [\"string\"]
error code: -8
error message:
Invalid parameter, expected
```

without:

```
→ bitcoin-cli -rpcwallet=w1 lockunspent true [\"string\"]
error code: -1
error message:
JSON value is not an object as expected
```
The implicit `get_xxx()` check is used extensively in other RPCs.

You can also combine the line below with above:

```
const UniValue& o = request.params[1].get_obj();
```

File: src/wallet/rpcwallet.cpp [hunk 8]
```diff
@@ -2389,33 +2389,72 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
             throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, expected object");
-        const UniValue& o = output.get_obj();
+        }
+
+        const UniValue& o = param.get_obj();
 
         RPCTypeCheckObj(o,
```
Comment (jnewbery) [inline src/wallet/rpcwallet.cpp]: In contrast to my comment above, it makes sense to keep these. `RPCTypeCheckObj` provides slightly more information (both the type expected and type received)

File: test/functional/wallet.py [hunk 9]
```diff
@@ -144,6 +150,10 @@ def run_test(self):
         assert_equal(self.nodes[2].getbalance(), 94)
         assert_equal(self.nodes[2].getbalance("from1"), 94-21)
 
+        # Verify that a spent output cannot be locked anymore
+        spent_0 = {"txid": node0utxos[0]["txid"], "vout": node0utxos[0]["vout"]}
+        assert_raises_jsonrpc(-8, "Invalid parameter, expected unspent output", self.nodes[2].lockunspent, False, [spent_0])
```
Comment (jnewbery) [inline test/functional/wallet.py]: This is the bug. `lockunspent()` should be called on `self.nodes[0]`, not `self.nodes[2]`

**Review by jnewbery — COMMENTED** [review]
Looks great! One bug in the test code and one nit in the RPC method.

File: test/functional/wallet.py [hunk 10]
```diff
@@ -101,11 +101,17 @@ def run_test(self):
...
         unspent_0 = {"txid": unspent_0["txid"], "vout": unspent_0["vout"]}
+        assert_raises_jsonrpc(-8, "Invalid parameter, expected locked output", self.nodes[2].lockunspent, True, [unspent_0])
         self.nodes[2].lockunspent(False, [unspent_0])
+        assert_raises_jsonrpc(-8, "Invalid parameter, output already locked", self.nodes[2].lockunspent, False, [unspent_0])
         assert_raises_jsonrpc(-4, "Insufficient funds", self.nodes[2].sendtoaddress, self.nodes[2].getnewaddress(), 20)
         assert_equal([unspent_0], self.nodes[2].listlockunspent())
         self.nodes[2].lockunspent(True, [unspent_0])
         assert_equal(len(self.nodes[2].listlockunspent()), 0)
+        assert_raises_jsonrpc(-8, "Invalid parameter, unknown transaction",
+          self.nodes[2].lockunspent, False, [{"txid": "0000000000000000000000000000000000", "vout": 0}])
```
Comment (jnewbery) [inline test/functional/wallet.py]: I personally don't like this indentation style. It looks like something between a new line and a new code block.

Would you mind aligning this continuation line with the opening parens:

```python
    assert_raises_jsonrpc(-8, "Invalid parameter, unknown transaction",
                          self.nodes[2].lockunspent, False, [{"txid": "0000000000000000000000000000000000", "vout": 0}])
```

same below

File: test/functional/wallet.py (hunk 9 above)
Comment (BitonicEelis) [reply test/functional/wallet.py]: Thanks! This one stumped me because for some reason when I ran the wallet tests locally, they didn't fail..

**Comment by BitonicEelis** [comment]
Amended to:

- remove isObject check
- indent continued function call lines to match opening parenthesis
- call lockunspent on correct node in test

File: test/functional/wallet.py (hunk 9 above)
Comment (jnewbery) [reply test/functional/wallet.py]: Yes! I saw the same thing. Very odd. h/t @sdaftuar for spotting the bug.

**Comment by jnewbery** [comment]
Tested ACK fe2c95bda22c21252709cc1088d7e61a8c8b1df8. Looks great. Thanks for being receptive to all my feedback!

File: test/functional/wallet.py [hunk 11]
```diff
@@ -144,6 +152,10 @@ def run_test(self):
         assert_equal(self.nodes[2].getbalance(), 94)
         assert_equal(self.nodes[2].getbalance("from1"), 94-21)
 
+        # Verify that a spent output cannot be locked anymore
+        spent_0 = {"txid": node0utxos[0]["txid"], "vout": node0utxos[0]["vout"]}
+        assert_raises_jsonrpc(-8, "Invalid parameter, expected unspent output", self.nodes[0].lockunspent, False, [spent_0])
```
Comment (MarcoFalke) [inline test/functional/wallet.py]: Needs rebase and replace with "assert_raises_rpc_error"

File: src/wallet/rpcwallet.cpp [hunk 12]
```diff
@@ -2389,33 +2389,66 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
             {
                 {"txid", UniValueType(UniValue::VSTR)},
                 {"vout", UniValueType(UniValue::VNUM)},
             });
 
-        std::string txid = find_value(o, "txid").get_str();
-        if (!IsHex(txid))
+        const std::string txid = find_value(o, "txid").get_str();
```
Comment (ryanofsky) [inline src/wallet/rpcwallet.cpp]: Could declare as `const std::string&` to avoid copying string.

**Review by ryanofsky — COMMENTED** [review]
utACK fe2c95bda22c21252709cc1088d7e61a8c8b1df8. No significant changes since last review. Left minor comments (feel free to ignore them), but this does need to be rebased.

**Comment by BitonicEelis** [comment]
Amended/rebased to:
- use `assert_raises_rpc_error`;
- use references to avoid copying a UniValue and std::string, as suggested by ryanofsky.

**Review by ryanofsky — COMMENTED** [review]
utACK 28f8b6657764c7746645a6e75dfb09ffc0597322. Only changes since last review are rebase & adding const refs.

File: src/wallet/rpcwallet.cpp [hunk 13]
```diff
@@ -2447,33 +2447,66 @@ UniValue lockunspent(const JSONRPCRequest& request)
...
+        if (!fUnlock && is_locked) {
+            throw JSONRPCError(RPC_INVALID_PARAMETER, "Invalid parameter, output already locked");
+        }
+
+        outputs.push_back(outpt);
+    }
+
+    // Atomically set (un)locked status for the outputs.
+    for (const COutPoint& outpt : outputs) {
+        if (fUnlock) pwallet->UnlockCoin(outpt);
```
Comment (sipa) [inline src/wallet/rpcwallet.cpp]: Coding style nit; if with else always needs braces/indentation (I know the original code you're rewriting wasn't following this convention, but in new code we try to).

**Review by sipa — COMMENTED** [review]
utACK 28f8b6657764c7746645a6e75dfb09ffc0597322
