### PR TITLE
index: Commit MuHash and best block together for coinstatsindex

### LINKED ISSUE #24076: coinstatsindex way more fragile than any other data w.r.t. power loss
**Two times since a fresh 22.0 installation I've had a power loss event (artifically produced to test system behavior), and each time I've started getting incorrect muhash values for block heights since approximately that moment**

"Approximately", as in I've not taken care to record the exact time of events because I've expecting nothing of interest from bitcoind in particular; "incorrect", as in compared to my another long-running nodes running with coinstatsindex without power outages, **and** to its own muhash for the current tip calculated without using the index, `gettxoutsetinfo muhash null false`.

**Expected behavior**

As usual when testing power outage behavior, I've expected pretty much anything **except** silently returning incorrect data. Most desirable would be checking several recent block muhashes on restart and auto-correcting the problem.
 
**To reproduce**

Unsure if it can be reproduced reliably, but 2/2 times are rather good indicator that it may not be uncommon 

**System information**

Ubuntu Linux 20.04, `~/.bitcoin` on /dev/md raid1 over two HDDs, ext4 fs with default mount options

Running bitcoind 22.0 prebuilt binaries from bitcoincore (amd64).

Here's debug.log from a typical restart (I see nothing interesting there, just in case if some configured or autodetected parameters are relevant):
```
 2022-01-14T17:10:34Z Bitcoin Core version v22.0.0 (release build)
2022-01-14T17:10:34Z Assuming ancestors of block 00000000000000000008a89e854d57e5667df88f1cdef6fde2fbca1de5b639ad have valid signatures.
2022-01-14T17:10:34Z Setting nMinimumChainWork=00000000000000000000000000000000000000001fa4663bbbe19f82de910280
2022-01-14T17:10:34Z Using the 'shani(1way,2way)' SHA256 implementation
2022-01-14T17:10:34Z Using RdSeed as additional entropy source
2022-01-14T17:10:34Z Using RdRand as an additional entropy source
2022-01-14T17:10:34Z Default data directory /home/bitnode/.bitcoin
2022-01-14T17:10:34Z Using data directory /srv/slow/dot-bitcoin
2022-01-14T17:10:34Z Config file: /etc/bitcoin/bitcoin.conf
2022-01-14T17:10:34Z Config file arg: blockfilterindex="1"
2022-01-14T17:10:34Z Config file arg: coinstatsindex="1"
2022-01-14T17:10:34Z Config file arg: dbcache="2000"
2022-01-14T17:10:34Z Config file arg: listen="1"
2022-01-14T17:10:34Z Config file arg: maxuploadtarget="450"
2022-01-14T17:10:34Z Config file arg: peerblockfilters="1"
2022-01-14T17:10:34Z Config file arg: server="1"
2022-01-14T17:10:34Z Config file arg: txindex="1"
2022-01-14T17:10:34Z Config file arg: upnp="0"
2022-01-14T17:10:34Z Config file arg: whitelist="download@127.0.0.1"
2022-01-14T17:10:34Z Config file arg: whitelist="download@192.168.1.0/24"
2022-01-14T17:10:34Z Config file arg: zmqpubrawblock="tcp://127.0.0.1:28332"
2022-01-14T17:10:34Z Config file arg: zmqpubrawtx="tcp://127.0.0.1:28333"
2022-01-14T17:10:34Z Command-line arg: conf="/etc/bitcoin/bitcoin.conf"
2022-01-14T17:10:34Z Command-line arg: daemonwait=""
2022-01-14T17:10:34Z Command-line arg: datadir="/srv/slow/dot-bitcoin/"
2022-01-14T17:10:34Z Command-line arg: pid="/run/bitcoind/bitcoind.pid"
2022-01-14T17:10:34Z Using at most 125 automatic connections (1024 file descriptors available)
2022-01-14T17:10:34Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2022-01-14T17:10:34Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2022-01-14T17:10:34Z Script verification uses 15 additional threads
2022-01-14T17:10:34Z scheduler thread start
2022-01-14T17:10:34Z HTTP: creating work queue of depth 16
2022-01-14T17:10:34Z Using random cookie authentication.
2022-01-14T17:10:34Z Generated RPC authentication cookie /srv/slow/dot-bitcoin/.cookie
2022-01-14T17:10:34Z HTTP: starting 4 worker threads
2022-01-14T17:10:34Z Using wallet directory /srv/slow/dot-bitcoin/wallets
2022-01-14T17:10:34Z init message: Verifying wallet(s)…
2022-01-14T17:10:34Z init message: Loading banlist…
2022-01-14T17:10:34Z SetNetworkActive: true
2022-01-14T17:10:34Z Using /16 prefix for IP bucketing
2022-01-14T17:10:34Z Cache configuration:
2022-01-14T17:10:34Z * Using 2.0 MiB for block index database
2022-01-14T17:10:34Z * Using 249.8 MiB for transaction index database
2022-01-14T17:10:34Z * Using 218.5 MiB for basic block filter index database
2022-01-14T17:10:34Z * Using 8.0 MiB for chain state database
2022-01-14T17:10:34Z * Using 1521.7 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2022-01-14T17:10:34Z init message: Loading block index…
2022-01-14T17:10:34Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2022-01-14T17:10:34Z Opening LevelDB in /srv/slow/dot-bitcoin/blocks/index
2022-01-14T17:10:34Z Opened LevelDB successfully
2022-01-14T17:10:34Z Using obfuscation key for /srv/slow/dot-bitcoin/blocks/index: 0000000000000000
2022-01-14T17:10:38Z LoadBlockIndexDB: last block file = 2883
2022-01-14T17:10:38Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=17, size=20113255, heights=718645...718661, time=2022-01-14...2022-01-14)
2022-01-14T17:10:38Z Checking all blk files are present...
2022-01-14T17:10:38Z Opening LevelDB in /srv/slow/dot-bitcoin/chainstate
2022-01-14T17:10:39Z Opened LevelDB successfully
2022-01-14T17:10:39Z Using obfuscation key for /srv/slow/dot-bitcoin/chainstate: d57f45de91bd35fa
2022-01-14T17:10:39Z Loaded best chain: hashBestChain=000000000000000000001cab1821f8b5ce71faccfde4d9ae11ab444c0dff979f height=718643 date=2022-01-14T14:19:04Z progress=0.999964
2022-01-14T17:10:39Z init message: Verifying blocks…
2022-01-14T17:10:39Z Verifying last 6 blocks at level 3
2022-01-14T17:10:39Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2022-01-14T17:12:34Z No coin database inconsistencies in last 6 blocks (9259 transactions)
2022-01-14T17:12:34Z  block index          120309ms
2022-01-14T17:12:34Z Opening LevelDB in /srv/slow/dot-bitcoin/indexes/txindex
2022-01-14T17:12:35Z Opened LevelDB successfully
2022-01-14T17:12:35Z Using obfuscation key for /srv/slow/dot-bitcoin/indexes/txindex: 0000000000000000
2022-01-14T17:12:35Z txindex thread start
2022-01-14T17:12:35Z txindex is enabled at height 718643
2022-01-14T17:12:35Z txindex thread exit
2022-01-14T17:12:35Z Opening LevelDB in /srv/slow/dot-bitcoin/indexes/blockfilter/basic/db
2022-01-14T17:12:35Z Opened LevelDB successfully
2022-01-14T17:12:35Z Using obfuscation key for /srv/slow/dot-bitcoin/indexes/blockfilter/basic/db: 0000000000000000
2022-01-14T17:12:35Z basic block filter index thread start
2022-01-14T17:12:35Z basic block filter index is enabled at height 718643
2022-01-14T17:12:35Z basic block filter index thread exit
2022-01-14T17:12:35Z Opening LevelDB in /srv/slow/dot-bitcoin/indexes/coinstats/db
2022-01-14T17:12:36Z Opened LevelDB successfully
2022-01-14T17:12:36Z Using obfuscation key for /srv/slow/dot-bitcoin/indexes/coinstats/db: 0000000000000000
2022-01-14T17:12:36Z coinstatsindex thread start
2022-01-14T17:12:36Z coinstatsindex is enabled at height 718643
2022-01-14T17:12:36Z coinstatsindex thread exit
2022-01-14T17:12:36Z block tree size = 718667
2022-01-14T17:12:36Z nBestHeight = 718643
2022-01-14T17:12:36Z loadblk thread start
....
```

### PR DESCRIPTION
**Pull request by mzumsande**
Fixes #24076

Coinstatsindex currently writes the MuHash (`DB_MUHASH`) to disk in `CoinStatsIndex::WriteBlock()` and `CoinStatsIndex::ReverseBlock()`, but the best synced block is written in `BaseIndex::Commit()`. These are called at different points in time, both during the ThreadSync phase, and also after the initial sync is finished and validation callbacks (`BlockConnected()` vs `ChainStateFlushed()`) perform the syncing.

As a result, the index DB is temporarily in an inconsistent state, and if bitcoind is terminated uncleanly (so that there is no time to call `Commit()` by receiving an interrupt or by flushing the chainstate) this leads to problems:
On the next startup, `Init()` will read the best block and a MuHash that corresponds to a different (higher) block. Indexing will  be picked up at the the best block processing some blocks again, but since MuHash is a rolling hash, it will process some utxos twice and the muhashes for all future blocks will be wrong, as was observed in #24076.

Fix this by always committing `DB_MUHASH` together with `DB_BEST_BLOCK`.

Note that the block data for the index is still written at different times, but this does not corrupt the index - at worst, these entries will be processed another time and overwritten after an unclean shutdown and restart.

### CODE REVIEW

**Comment by mzumsande** [comment]
FYI @fjahr

File: src/index/coinstatsindex.cpp [hunk 1]
```diff
@@ -481,5 +486,5 @@ bool CoinStatsIndex::ReverseBlock(const CBlock& block, const CBlockIndex* pindex
     Assert(m_total_unspendables_scripts == read_out.second.total_unspendables_scripts);
     Assert(m_total_unspendables_unclaimed_rewards == read_out.second.total_unspendables_unclaimed_rewards);
 
-    return m_db->Write(DB_MUHASH, m_muhash);
```
Comment (luke-jr) [inline src/index/coinstatsindex.cpp:484]: Seems like the only problem is this lone line?

**Review by luke-jr — CHANGES_REQUESTED** [review]

File: src/index/coinstatsindex.cpp [hunk 2]
```diff
@@ -228,10 +228,7 @@ bool CoinStatsIndex::WriteBlock(const CBlock& block, const CBlockIndex* pindex)
     m_muhash.Finalize(out);
     value.second.muhash = out;
 
-    CDBBatch batch(*m_db);
-    batch.Write(DBHeightKey(pindex->nHeight), value);
-    batch.Write(DB_MUHASH, m_muhash);
-    return m_db->WriteBatch(batch);
```
[the remark this answers is not in the document]
Comment (mzumsande) [reply src/index/coinstatsindex.cpp:234]: I think this is spot is problematic, and the reason for the behavior reported in #24076: 

If we persist `DB_MUHASH` here in each `BlockConnected()` callback, but not `DB_BEST_BLOCK` (which is persisted only in `ChainStateFlushed()` callbacks and will therefore at this point in time have a lower height), the db is temporarily in an inconsistent state.

So in case of an unclean shutdown (with no time to flush the chainstate to disk to get in sync again), on next startup the index will initialize with the older `DB_BEST_BLOCK` but a `DB_MUHASH` which contains data from newer blocks. The index then reprocesses the blocks after `DB_BEST_BLOCK`'s height a second time. 
But MuHash is a rolling hash, so it will incorporate data from these blocks twice, and the hash will be incorrect.

**Review by Sjors — COMMENTED** [review]
Concept ACK

It might be worth rebasing this on #24133 and if at all possible, add a test that triggers the error added there.

I think overriding `CommitInternal` makes sense given that we require `DB_MUHASH` and `DB_BEST_BLOCK` to be in sync (which we explicitly check as of #24133).

The alternative would be to drop `DB_MUHASH` altogether, but since MuHash can't (?) be initialized from a finalized hash, we would have to index both the denominator and numerator.

File: src/index/coinstatsindex.cpp (hunk 1 above)
Comment (Sjors) [reply src/index/coinstatsindex.cpp:484]: If I replace only that line with `true` the reorg test in `feature_coinstatsindex.py` still passes. But not sure if that helps with the original issue.

**Review by fjahr — COMMENTED** [review]
Code review ACK 010156c07f28e2c8dc30d4408942d1e1d88ab54d

While I can not reproduce the issue I agree that this is likely to fix #24076.

I think there could still be inconsistencies between the running muhash and the coinstats data since those are not batched anymore now but at least that would then lead to a failure in `Init()` at restart. This could be avoided by squashing all of that into `CommitInternal()` as well ([drafted here](https://github.com/fjahr/bitcoin/commit/a90394efb9b348b7d3615d61fbea612470b1c75c)) but I don't think this is necessary right now. As I have reviewed this I am now really not sure about the boundaries between `Commit()` and `WriteBlock()` anymore and will think about refactoring that while reviewing #24230 (maybe that's already solved there).

File: src/index/coinstatsindex.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ryanofsky) [reply src/index/coinstatsindex.cpp:234]: In commit "index: Commit DB_MUHASH and DB_BEST_BLOCK to disk together" (010156c07f28e2c8dc30d4408942d1e1d88ab54d)

> The `CommitInternal` override feels like a hacky refactor.

I think I agree with luke if the point is that the override-and-call-base class code in `CommitInternal` is a little hacky, but fjahr's right this just the way the base index class was designed, so the override seems like appropriate way to handle this now. #24230 does clean up all the overrides and will simplify this a bit.

File: src/index/coinstatsindex.cpp [hunk 3]
```diff
@@ -228,10 +228,7 @@ bool CoinStatsIndex::WriteBlock(const CBlock& block, const CBlockIndex* pindex)
     m_muhash.Finalize(out);
     value.second.muhash = out;
 
-    CDBBatch batch(*m_db);
```
Comment (ryanofsky) [inline src/index/coinstatsindex.cpp:231]: In commit "index: Commit DB_MUHASH and DB_BEST_BLOCK to disk together" (010156c07f28e2c8dc30d4408942d1e1d88ab54d)

I might add a code comment here like "Intentionally do not update DB_MUHASH here so it stays in sync with DB_BEST_BLOCK, and index is not corrupted if there is an unclean shutdown"

**Review by ryanofsky — APPROVED** [review]
Code review ACK 010156c07f28e2c8dc30d4408942d1e1d88ab54d

It would be good to add a unit test to coinstatsindex_tests that triggers the issue this is supposed to fix. I think the test would just need to make the index object, send a BlockConnected notification, and then destroy the index object without sending ChainStateFlushed notification. This would save a corrupted index that should result in errors next time it is loaded.


re: https://github.com/bitcoin/bitcoin/pull/24138#pullrequestreview-880885450

> I think there could still be inconsistencies between the running muhash and the coinstats data since those are not batched anymore now but at least that would then lead to a failure in `Init()` at restart.

I could be wrong but this seems fine to me since coinstats data is accessed by height and written before the muhash & best block. So if the coinstats data is ahead of the muhash. it is just ignored. In your suggested followup a90394efb9b348b7d3615d61fbea612470b1c75c, I think the `if (!m_db->Read(DBHeightKey(pindex->nHeight))` check would be good to add, but I think it should it should just trigger a fatal error if the key isn't found. I don't see how the recovery code added in that commit would work.

> #24230 (maybe that's already solved there).

My guess is #24230 doesn't affect this, since it's trying to leave index's internal behavior the same, and just change the way it receives block connected and disconnected notifications, without changing the way it handles them.

File: src/index/coinstatsindex.cpp (hunk 1 above)
Comment (Sjors) [reply src/index/coinstatsindex.cpp:484]: >  if the node gets shut down during the reorg,

I guess this is very non trivial to test, but maybe add a comment?

File: src/index/coinstatsindex.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (mzumsande) [reply src/index/coinstatsindex.cpp:234]: Just to make this clear: This is not a refactor, it changes behavior (the points in time when `DB_MUHASH` is written to disk).

My understanding is that the indexes work in general such that that all persisted data describing the current _progress_ of indexing (such as the best block) must be in sync with the persisted chainstate information (which is sometimes not flushed for several blocks received) - that is why `ChainStateFlushed()` callbacks are used. In case of an unclean shutdown, the chainstate will be constructed from this point on, so the indexes must as well.

In contrast to this is the actual indexed data for each block - I think we could in principle cache it and also write it to disk with each `ChainStateFlushed()` callback and not use `BlockConnected()` at all. 

But it is also possible to write it to disk in advance with each `BlockConnected()` callback, as it is done:
This is dependent on the assumption that we will not read (and possibly overwrite) the indexed data in case it is ahead of the flushed chainstate data (and the best block), and also that _before_ flushing the chainstate, we have called `BlockConnected()` for each block.

With this in mind, I don't see a better way of doing this other than overriding `CommitInternal`.

File: src/index/coinstatsindex.cpp (hunk 3 above)
Comment (mzumsande) [reply src/index/coinstatsindex.cpp:231]: Thanks, I added a comment here.

File: src/index/coinstatsindex.cpp (hunk 1 above)
Comment (mzumsande) [reply src/index/coinstatsindex.cpp:492]: I added a comment at the end of `CoinStatsIndex::WriteBlock` (as suggested by ryanofsky below). I think that duplicating this comment in `CoinStatsIndex::ReverseBlock` is not required, since this function doesn't write anything else to disk there wouldn't really be the expectation that for it to write `DB_MUHASH` here.

**Comment by mzumsande** [comment]
I pushed an update, rebasing (with #24133 merged) and addressing feedback (adding a comment).

> It would be good to add a unit test to coinstatsindex_tests that triggers the issue this is supposed to fix. I think the test would just need to make the index object, send a BlockConnected notification, and then destroy the index object without sending ChainStateFlushed notification. This would save a corrupted index that should result in errors next time it is loaded.

This would be great. I haven't done this with this push, because 
a) I couldn't make it work yet, I had some technical difficulties with the test framework when restarting the index a second time. I will look into it more unless
b) @fjahr who said [here](https://github.com/bitcoin/bitcoin/pull/24133#discussion_r810605240) that he is working on this has more success.

**Review by ryanofsky — APPROVED** [review]
Code review ACK eb6cc05da32c5bde122725a0bc907d3767a791cd.  Only changes since previous review are rebasing and adding comments.

@mzumsande I wrote a little test which passes with this bugfix, and fails with the fix reverted. Feel free to add it to this PR or use the code in any way: ~ded9fda2b6e154ac64b2fc755ddaa738b309b7e9~ d3c2ebbfdc3c61a04b645c6bb435424fa60f4a0b

**Comment by mzumsande** [comment]
> @mzumsande I wrote a little test which passes with this bugfix, and fails with the fix reverted. Feel free to add it to this PR or use the code in any way: ~[ded9fda](https://github.com/bitcoin/bitcoin/commit/ded9fda2b6e154ac64b2fc755ddaa738b309b7e9)~ [d3c2ebb](https://github.com/bitcoin/bitcoin/commit/d3c2ebbfdc3c61a04b645c6bb435424fa60f4a0b)

Thank you! The test looks great, I added your commit to this PR (and confirmed that it fails on master).

**Review by ryanofsky — APPROVED** [review]
Code review ACK 691d45fdc83ec14f87a400f548553168ac70263f. Only change since last review is adding test

**Review by fjahr — COMMENTED** [review]
ACK 691d45fdc83ec14f87a400f548553168ac70263f

Reviewed code and ensured that the newly added test fails when eb6cc05da32c5bde122725a0bc907d3767a791cd is reverted.

File: src/test/coinstatsindex_tests.cpp [hunk 4]
```diff
@@ -78,4 +85,44 @@ BOOST_FIXTURE_TEST_CASE(coinstatsindex_initial_sync, TestChain100Setup)
...
+        // sending a chainstate flushed notification. Prior to #24138, this
+        // would cause the index to be corrupted and fail to reload.
+        ValidationInterfaceTest::BlockConnected(index, new_block, new_block_index);
+        index.Stop();
+    }
+
+    {
+        CoinStatsIndex index{1 << 20};
+        // Make sure the index can be loaded.
+        BOOST_REQUIRE(index.Start(chainstate));
```
[the remark this answers is not in the document]
Comment (MarcoFalke) [reply src/test/coinstatsindex_tests.cpp:123]: Is there a huge cost to spinning up the second index? If not, I think both versions are fine.
