### PR TITLE
gui: Add GUIUtil::bringToFront

### LINKED ISSUE #13829: Unhide QT window doesn't work when hidden with ⌘ + H
Noticed this while reviewing #13529, but it's also in master @ 5ba77df. On macOS 10.13.6:

schermafbeelding 2018-08-01 om 16 22 09

schermafbeelding 2018-08-01 om 16 12 51

* `Show` in the action menu doesn't work if the app was hidden by `Command + H`, it does work when hidden through this menu
* send and receive don't unhide the window when opened for the action menu. It does navigate to the right tab. The other actions do work (sign, verify & debug window)

Clicking "Toon" (= macOS native show) does work, suggesting the GUI uses some non-native method of hiding.

### PR DESCRIPTION
**Pull request by promag**
The sequence `show -> raise -> activateWindow` is factored out to the new function `GUIUtil::bringToFront` where a macOS fix is added in order to fix #13829.

Also included:
 - simplification of `BitcoinGUI::showNormalIfMinimized`
 - simplified some connections to `BitcoinGUI::showNormalIfMinimized`
 - added missing connections to `BitcoinGUI::showNormalIfMinimized`.

### CODE REVIEW

**Comment by promag** [comment]
@jonasschnelli @Sjors @ken2812221 review/test much appreciated.

File: src/qt/bitcoingui.cpp [hunk 1]
```diff
@@ -274,15 +274,15 @@ void BitcoinGUI::createActions()
     // can be triggered from the tray menu, and need to show the GUI to be useful.
     connect(overviewAction, &QAction::triggered, this, static_cast<void (BitcoinGUI::*)()>(&BitcoinGUI::showNormalIfMinimized));
```
Comment (ken2812221) [inline src/qt/bitcoingui.cpp]: Any reason to keep this one?

Comment (promag) [reply src/qt/bitcoingui.cpp]: Thanks.

**Comment by laanwj** [comment]
I think it would make sense, for ease of review, to split off the fix to #13829 from pure refactoring.

**Comment by promag** [comment]
Which refactor?

Note that the issue is observed in more places than the one reported in #13829.

File: src/qt/guiutil.cpp [hunk 2]
```diff
@@ -357,6 +367,21 @@ bool isObscured(QWidget *w)
         && checkPoint(QPoint(w->width() / 2, w->height() / 2), w));
 }
 
+void bringToFront(QWidget *w)
+{
+#ifdef Q_OS_MAC
+    id app = objc_msgSend((id) objc_getClass("NSApplication"), sel_registerName("sharedApplication"));
+    objc_msgSend(app, sel_getUid("activateIgnoringOtherApps:"), YES);
```
Comment (Sjors) [inline src/qt/guiutil.cpp]: Apple [documentation](https://developer.apple.com/documentation/appkit/nsapplication/1428468-activateignoringotherapps?language=objc) suggests that this normally shouldn't be needed, which suggests there's a deeper problem somewhere.

**Review by Sjors — APPROVED** [review]
tACK eed869b on macOS, this indeed fixes #13829.

The change from `static_cast<void (BitcoinGUI::*)()>` to `[this]` is most eye pleasing :-)

I think @laanwj is referring to e.g. the new `bringToFront()` function which contains both existing and new code. I didn't find it too confusing though.

**Comment by fanquake** [comment]
Testing current master on macOS 10.13.6 https://github.com/bitcoin/bitcoin/commit/2070a545e2c4e8c2dff4c0fb40b8fd2f68fc2ca.
If `Command + H` or the menu item is used to hide the window:
- Clicking the task bar icon shows the window.
- Clicking `show/hide` does not work.
- Clicking `show` (bottom of the menu ) does work.
- If `Send` or `Receive` is clicked, the window changes to the correct tab, but the window is not shown.
- `Sign`, `Verify` & `Debug` all unhide and show the correct dialog.

Testing https://github.com/bitcoin/bitcoin/pull/14123/commits/eed869b834a0d19318733420ed32f2f0df94d6be.
If `Command + H` or the menu item is used to hide the window:
- Clicking the task bar icon shows the window.
- Clicking `show/hide` does work.
- Click `show` (bottom of the menu ) does work.
- If `Send` or `Receive` is clicked, the window changes to the correct tab, and unhides.
- `Sign`, `Verify` & `Debug` all unhide and show the correct dialog. (this has also fixed the annoying "attention" bounce behaviour that was present before.)
- When the window has been minimised (CMD + M, which doesn't actually work at the moment..), only the sign, verify and debug items work, and they only display the sub window, the main window remains minimised. This seems to be a regression, as the options work with current master.

File: src/qt/guiutil.cpp (hunk 2 above)
Comment (fanquake) [reply src/qt/guiutil.cpp]: I'd also like to know a bit more about this, and the new `<objc/objc-runtime.h>` #include.

**Comment by promag** [comment]
Thanks for the reviews! I'll fix it.

BTW, in macOS "show/hide" action could be removed since it's already there natively.

File: src/qt/bitcoingui.cpp [hunk 3]
```diff
@@ -349,7 +349,9 @@ void BitcoinGUI::createActions()
         connect(encryptWalletAction, &QAction::triggered, walletFrame, &WalletFrame::encryptWallet);
         connect(backupWalletAction, &QAction::triggered, walletFrame, &WalletFrame::backupWallet);
         connect(changePassphraseAction, &QAction::triggered, walletFrame, &WalletFrame::changePassphrase);
+        connect(signMessageAction, &QAction::triggered, [this]{ showNormalIfMinimized(); });
         connect(signMessageAction, &QAction::triggered, [this]{ gotoSignMessageTab(); });
+        connect(verifyMessageAction, &QAction::triggered, [this]{ showNormalIfMinimized(); });
         connect(verifyMessageAction, &QAction::triggered, [this]{ gotoVerifyMessageTab(); });
```
Comment (ken2812221) [inline src/qt/bitcoingui.cpp]: I think this is better 
```
connect(signMessageAction, &QAction::triggered, [this]{ showNormalIfMinimized(); gotoSignMessageTab(); });
connect(verifyMessageAction, &QAction::triggered, [this]{ showNormalIfMinimized(); gotoSignMessageTab(); });

File: src/qt/bitcoingui.cpp [hunk 4]
```diff
@@ -1142,24 +1141,11 @@ void BitcoinGUI::showNormalIfMinimized(bool fToggleHidden)
...
-    else if (GUIUtil::isObscured(this))
-    {
-        raise();
-        activateWindow();
-    }
-    else if(fToggleHidden)
+    if (!isHidden() && !isMinimized() && !GUIUtil::isObscured(this) && fToggleHidden) {
         hide();
+    } else {
+        GUIUtil::bringToFront(this);
```
Comment (ken2812221) [inline src/qt/bitcoingui.cpp]: If the window was minimized, it might need to call `showNormal`.

**Comment by promag** [comment]
Rebased and added a fixup that `s/show/showNormal` after @ken2812221 https://github.com/bitcoin/bitcoin/pull/14123#discussion_r214781272.

File: src/qt/bitcoingui.cpp (hunk 4 above)
Comment (promag) [reply src/qt/bitcoingui.cpp]: This should be fixed.

File: src/qt/bitcoingui.cpp (hunk 3 above)
Comment (promag) [reply src/qt/bitcoingui.cpp]: Keeping multiple connections for now.

File: src/qt/guiutil.cpp [hunk 5]
```diff
@@ -62,6 +62,16 @@
 #include <QFontDatabase>
 #endif
 
+#if defined(Q_OS_MAC)
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
+// based on: https://github.com/Mozketo/LaunchAtLoginController/blob/master/LaunchAtLoginController.m
```
[the remark this answers is not in the document]
Comment (promag) [reply src/qt/guiutil.cpp]: Sure, done.

File: src/qt/guiutil.cpp [hunk 6]
```diff
@@ -357,6 +366,21 @@ bool isObscured(QWidget *w)
...
+void bringToFront(QWidget *w)
+{
+#ifdef Q_OS_MAC
+    id app = objc_msgSend((id) objc_getClass("NSApplication"), sel_registerName("sharedApplication"));
+    objc_msgSend(app, sel_getUid("activateIgnoringOtherApps:"), YES);
+#endif
+
+    if (w) {
+        // activateWindow() (sometimes) helps with keyboard focus on Windows
+        w->activateWindow();
```
Comment (hebasto) [inline src/qt/guiutil.cpp]: According to [Qt docs](https://doc.qt.io/qt-5/qwidget.html#activateWindow)

> Note that the window must be visible, otherwise activateWindow() has no effect.

Therefore, the safer sequence may be:
```
w->showNormal();  // or w->show();
w->activateWindow();
w->raise();

File: src/qt/guiutil.cpp [hunk 7]
```diff
@@ -357,6 +366,21 @@ bool isObscured(QWidget *w)
...
+        w->showNormal();
```
Comment (hebasto) [inline src/qt/guiutil.cpp]: Always `showNormal()` will break cases when then main window is maximized.

**Comment by hebasto** [comment]
IMO `show()`/`showNormal()` should not be aggregated with `activateWindow()`->`raise()` sequence in a single function. Rationale: `show()` is reverse to `hide()`, but `showNormal()` restores the widget after it has been maximized or minimized.

**Comment by jonasschnelli** [comment]
@promag: can you comment or address @hebasto's comments; rebase or close?

**Comment by promag** [comment]
Rebased and addressed review comments.

**Comment by hebasto** [comment]
tACK 56c61a3 

macOS 10.13.6 (17G65) + Qt 5.11.2 - works as expected, i.e. #13829 fixed

**Comment by ken2812221** [comment]
Tested ACK 56c61a33dd7f1bca4e5005654dd776ffe69c4c3b

File: src/qt/guiutil.cpp (hunk 2 above)
Comment (promag) [reply src/qt/guiutil.cpp]: Sure.

Comment (promag) [reply src/qt/guiutil.cpp]: Added comment.

**Review by promag — COMMENTED** [review]
Rebased with #14597.

File: src/qt/bitcoingui.cpp (hunk 3 above)
Comment (gwillen) [reply src/qt/bitcoingui.cpp]: I assume the other actions are only done that way for historical reasons -- prior to Qt5/C++11 this was not possible, and we only switched to using lambdas instead of the older syntax in 0.17 I believe.

**Comment by hebasto** [comment]
@promag 
The e0d1883d0e98c265db09b6a48b9c124f45edf898 commit you picked has a bug: https://github.com/bitcoin/bitcoin/pull/14597#issuecomment-434257329
See: https://github.com/bitcoin/bitcoin/pull/14597#issuecomment-434836662

File: src/qt/guiutil.cpp (hunk 2 above)
Comment (hebasto) [reply src/qt/guiutil.cpp]: According to the `sel_getUid` [documentation](https://developer.apple.com/documentation/objectivec/1418625-sel_getuid?language=objc):
> The implementation of this method is identical to the implementation of `sel_registerName`.

On master(750415701):
- `sel_registerName` used 4 times
- `sel_getUid` not used at all

Could `sel_getUid` replace with `sel_registerName`?

File: src/qt/guiutil.cpp [hunk 8]
```diff
@@ -60,6 +60,15 @@
 #include <QFontDatabase>
 #endif
 
+#if defined(Q_OS_MAC)
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
+
+#include <objc/objc-runtime.h>
+#include <CoreFoundation/CoreFoundation.h>
```
Comment (hebasto) [inline src/qt/guiutil.cpp]: This header is redundant.

**Review by ken2812221 — APPROVED** [review]
ACK d3becb175270d715daaffb75a037433a126a95f4

**Comment by hebasto** [comment]
Tested d3becb175270d715daaffb75a037433a126a95f4:
- on Windows 10: bug #14222 fixed
- on macOS 10.13.6: bug #13829 fixed
There is a new bug on macOS: obscure main window with another app window, click Dock icon; main windows appears and hides. Investigating...
- on Linux Mint 19
@promag is it worth to combine a Linux-specific bugfix #14591 into this PR?

Also a tiny nit left: https://github.com/bitcoin/bitcoin/pull/14123#discussion_r230507680

**Comment by Sjors** [comment]
re-tACK 0a656f8 on macOS 10.14.1 QT 5.11.2 (I didn't check the commits inherited from #14597)

Also +1 on doing Linux in another PR, it's already quite difficult to get any macOS changes through review.

**Comment by hebasto** [comment]
re-tACK

Systems:
- Linux Mint 19 + Qt 5.9.5
- macOS 10.13.6 + Qt 5.11.2

Commits: 5796671e1dd8a2d0b1e750c2dce19a10af624095, 6fc21aca6d5e16c3ece104fec8e5b3df116893b4, 0a656f85a9c694f25b06c6464d6e986816eecd58
