### PR TITLE
Fix datadir handling

### LINKED ISSUE #15240: bitcoind wont start with datadir specified in conf file and no home dir
bitcoind won't start if datadir is specified in the conf file and the user running it has no home dir

tested with debian stretch and bitcoin 0.17.1

```
# sudo -u bitcoin bitcoind -daemon -conf=/usr/local/etc/bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid

************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directories: Permission denied: "/home/bitcoin"
bitcoin in AppInit()

bitcoind: chainparamsbase.cpp:29: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.
Aborted

# mkhomedir_helper bitcoin

# sudo -u bitcoin bitcoind -daemon -conf=/usr/local/etc/bitcoin/bitcoin.conf -pid=/run/bitcoind/bitcoind.pid
Bitcoin server starting
```

### LINKED ISSUE #15745: unexpected behavior when specify datadir in config file
## issue sumary 
I specificed `datadir` in conf file and run bitcoind with `-conf` option, but data is writing to default `~/.bitcoin` dir , not the dir I want  

## steps to reproduce
**bitcoind version 0.17.1**
```
root@MNG-BC ➜  .bitcoin bitcoind --version
Bitcoin Core Daemon version v0.17.1.0-gef70f9b52b851c7997a9f1a0834714e3eebc1fd8
```

### step1: configrations
**bitcoind conf file path `/root/.bitcoin/bitcoin.conf`**
datadir for testnet : **datadir=/mnt/data/bitcoin**
```
# [core]
# Specify the location of the configuration file. To use non-default location, create a default location config file containing this setting.
conf=/root/.bitcoin/bitcoin.conf

# [debug]
# Enable debug logging for all categories.
#debug=1
# Log IP Addresses in debug output.
#logips=1
# Run this node on the Bitcoin Test Network.
#testnet=1

# [rpc]
# Accept command line and JSON-RPC commands.
server=1
# Accept public REST requests.
rest=1
# RPC user
rpcuser=rpcuser
# RPC password
rpcpassword=rpcpass
# RPC allow ip (allow all)
rpcallowip=0.0.0.0/0
# RPC bind
#rpcbind=127.0.0.1
# get all transaction
txindex=1


# [Sections]
# Most options automatically apply to mainnet, testnet, and regtest networks.
# If you want to confine an option to just one network, you should add it in the relevant section.
# EXCEPTIONS: The options addnode, connect, port, bind, rpcport, rpcbind and wallet
# only apply to mainnet unless they appear in the appropriate section below.

# Options only for mainnet
[main]
# datadir
datadir=/mnt/data/bitcoin/mainnet
# Listen for incoming connections on non-default port.(default: 8333 or testnet: 18333)
port=8333
# RPC port(default:8332 or testnet:18332)
rpcport=8332

# Options only for testnet
[test]
# datadir
datadir=/mnt/data/bitcoin
# Listen for incoming connections on non-default port.(default: 8333 or testnet: 18333)
port=18333
# RPC port(default:8332 or testnet:18332)
rpcport=18332

# Options only for regtest
[regtest]
```

### step2 : run bitcoind
run bitcoind with below command  
```
bitcoind -conf=/root/.bitcoin/bitcoin.conf -testnet=1
```

### step3 : check the data
expected all the data write to /mnt/data/bitcoin/testnet3  
but actually block data is been wroted to /root/.bitcoin/   
```
drwx------  2 root root 4096 Apr  4 16:51 blocks
drwx------  3 root root 4096 Apr  4 16:51 testnet3
```

more info about the contents in /root/.bitcoin 
```
root@MNG-BC ➜  .bitcoin du --max-depth=1 -h
1.1G    ./testnet3
4.0K    ./blocks
1.1G    .
root@MNG-BC ➜  .bitcoin cd testnet3
root@MNG-BC ➜  testnet3 ls
blocks
root@MNG-BC ➜  testnet3 cd blocks
root@MNG-BC ➜  blocks ls
blk00000.dat  blk00001.dat  blk00002.dat  blk00003.dat  blk00004.dat  blk00005.dat  blk00006.dat  blk00007.dat  index  rev00000.dat  rev00001.dat  rev00002.dat  rev00003.dat  rev00004.dat  rev00005.dat  rev00006.dat  rev00007.dat
```

## question
Why datadir is not taken effect in conf? Is it a bug or my conf is wrong?  Should I specific `-datadir` option in the command line?

### PR DESCRIPTION
**Pull request by hebasto**
Fix #15240, see: https://github.com/bitcoin/bitcoin/issues/15240#issuecomment-487353760
Fix #15745
Fix broken `feature_config_args.py` tests (disabled by MarcoFalke@fabe28a0cdcfa13e0e595a0905e3642a960d3077). All test are enabled now.
This PR is alternative to #13621.

User's `$HOME` directory is not touched unnecessarily now.

~To make reviewing easier only `bitcoind` code is modified (neither `bitcoin-cli` nor `bitcoin-qt`).~

Refs:
- https://github.com/bitcoin/bitcoin/issues/15745#issuecomment-479852569 by **laanwj**
- #16220

### CODE REVIEW

File: src/util/system.cpp [hunk 1]
```diff
@@ -784,7 +789,8 @@ void ClearDatadirCache()
 
 fs::path GetConfigFile(const std::string& confPath)
 {
-    return AbsPathForConfigVal(fs::path(confPath), false);
+    fs::path path = fs::path(confPath);
+    return path.is_absolute() ? path : AbsPathForConfigVal(path, false);
```
Comment (promag) [inline src/util/system.cpp]: Is this necessary? Looks like `fs::absolute` already does this in `AbsPathForConfigVal`.

File: src/util/system.cpp [hunk 2]
```diff
@@ -773,6 +773,11 @@ const fs::path &GetDataDir(bool fNetSpecific)
     return path;
 }
 
+bool CheckDataDirOption()
+{
+    return gArgs.IsArgSet("-datadir") ? fs::is_directory(fs::system_complete(gArgs.GetArg("-datadir", ""))) : true;
```
Comment (promag) [inline src/util/system.cpp]: This doesn't check the default data dir.

File: src/util/system.cpp (hunk 1 above)
Comment (hebasto) [reply src/util/system.cpp]: Yes, it is needed to not touch default datadir unnecessarily, before all configs are read.

File: src/util/system.cpp (hunk 2 above)
Comment (hebasto) [reply src/util/system.cpp]: You are right. This behavior is international.

**Comment by hebasto** [comment]
@promag Thank you for your review.
To be clear, the premature address to the default datadir, until possible `-datadir` option is read from the config file(s), is the root of all issues fixed by this PR.

**Comment by promag** [comment]
On my system:
```
# create a file in the default data dir
touch "/Users/joao/Library/Application Support/Bitcoin"

# launch with default data dir
src/bitcoind


************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: File exists: "/Users/joao/Library/Application Support/Bitcoin"
bitcoin in AppInit()

Assertion failed: (globalChainBaseParams), function BaseParams, file chainparamsbase.cpp, line 30.
[1]    53221 abort      src/bitcoind
```

**Comment by hebasto** [comment]
@promag 
> On my system:
> 
> ```
> # create a file in the default data dir
> touch "/Users/joao/Library/Application Support/Bitcoin"
> 
> # launch with default data dir
> src/bitcoind
> 
> 
> ************************
> EXCEPTION: N5boost10filesystem16filesystem_errorE
> boost::filesystem::create_directory: File exists: "/Users/joao/Library/Application Support/Bitcoin"
> bitcoin in AppInit()
> 
> Assertion failed: (globalChainBaseParams), function BaseParams, file chainparamsbase.cpp, line 30.
> [1]    53221 abort      src/bitcoind
> ```

The same behavior is observed on master as well. This PR does not change it.

File: src/util/system.cpp (hunk 1 above)
Comment (ryanofsky) [reply src/util/system.cpp]: It seems like a better fix (simpler and more general) would be to add:

```c++
if (path.is_absolute()) return path;
```

as the first line of AbsPathForConfigVal.

**Review by ryanofsky — COMMENTED** [review]
This comment doesn't seem to be true: https://github.com/bitcoin/bitcoin/pull/15864#issue-272240173

> To make reviewing easier only bitcoind code is modified (neither bitcoin-cli nor bitcoin-qt).

Since GetConfigFile is called all three places. It would also seem worrying if this were true, since it would mean the different binaries wouldn't behave consistently.

**Comment by hebasto** [comment]
@ryanofsky 
Thank you for your review. Your comment has been addressed.
Also commits for `bitcoin-qt` and tools (`bitcoin-cli`, `bitcoin-wallet`) have been added.

Would you mind re-reviewing?

File: src/util/system.cpp (hunk 2 above)
Comment (ryanofsky) [reply src/util/system.cpp]: In commit "Add CheckDataDirOption() function" (a45f692366d7bb4814af83e3b645c9e5a5a734e6)

I don't think `IsArgSet` is the right function to call here. If somebody has a `datadir` option specified in the config file, but wants to unset it on the command line by passing `-nodatadir` or `-datadir=""`, it seems like this should be allowed. Would suggest:

```
std::string datadir = gArgs.GetArg("-datadir", "");
return datadir.empty() || fs::is_directory(fs::system_complete(datadir));
```

And a corresponding change in GetDataDir()

File: src/bitcoind.cpp [hunk 3]
```diff
@@ -95,8 +95,7 @@ static bool AppInit(int argc, char* argv[])
 
     try
     {
-        if (!fs::is_directory(GetDataDir(false)))
-        {
+        if (!CheckDataDirOption()) {
```
Comment (ryanofsky) [inline src/bitcoind.cpp]: In commit "Fix datadir handling in bitcoind" (160470f76f22edd1f9ef6448584381fc5626b9c4)

I can't figure out what this commit is doing. Is it fixing #15745 or #15864? Is the idea to prevent the datadir from being cached here? Can you write in the commit description what problem this is fixing and how it works?

**Review by ryanofsky — APPROVED** [review]
utACK c4ab7420ef5dc4e6925519f8571a936f38720862. It's not really clear to me which bugs are being fixed by these changes, and how exactly the fixes work, but the basic idea seems to be to avoid calling `GetDataDir()` various places early on startup when it isn't necessary, to avoid caching bad values.

The changes seem worth making as optimizations or for clarity regardless of the bugs. But it'd also make sense as followup to look into:

- Whether caching datadir is a useful optimization
- Whether it makes sense to interpret a non-absolute "-conf" argument relative to the datadir

Both of these seem questionable to begin with.

**Comment by hebasto** [comment]
@ryanofsky 
> It's not really clear to me which bugs are being fixed by these changes, and how exactly the fixes work, but the basic idea seems to be to avoid calling GetDataDir() various places early on startup when it isn't necessary, to avoid caching bad values.

The root of the reported bugs (#15240, #15745) is `GetDataDir()` tries to _create_ data directory. This step is premature when config file is not read yet.

File: src/util/system.cpp [hunk 4]
```diff
@@ -1226,6 +1226,9 @@ int64_t GetStartupTime()
 
 fs::path AbsPathForConfigVal(const fs::path& path, bool net_specific)
 {
+    if (path.is_absolute()) {
```
[the remark this answers is not in the document]
Comment (hebasto) [reply src/util/system.cpp]: Fixed.

File: src/util/system.cpp (hunk 2 above)
Comment (hebasto) [reply src/util/system.cpp]: > I don't think IsArgSet is the right function to call here. If somebody has a datadir option specified in the config file, but wants to unset it on the command line by passing -nodatadir or -datadir="", it seems like this should be allowed.

Good catch! Agree.

**Comment by promag** [comment]
I think we could replace the directory creation with an assertion (that datadir already exists) and create the directory right before the first call to `GetDataDir()`.

**Comment by hebasto** [comment]
@promag 
> I think we could replace the directory creation with an assertion (that datadir already exists) and create the directory right before the first call to `GetDataDir()` - probably on init.

Is it a bit out of the scope of this PR?

**Comment by hebasto** [comment]
@ryanofsky 
All your comments have been addressed.

File: src/util/system.cpp [hunk 5]
```diff
@@ -753,8 +753,9 @@ const fs::path &GetDataDir(bool fNetSpecific)
     if (!path.empty())
         return path;
 
-    if (gArgs.IsArgSet("-datadir")) {
-        path = fs::system_complete(gArgs.GetArg("-datadir", ""));
+    std::string datadir = gArgs.GetArg("-datadir", "");
```
Comment (ryanofsky) [inline src/util/system.cpp]: In commit "Add CheckDataDirOption() function" (5df1581b9ee6f13593b33fa9629ea9fbadcad732)

Ideally commit message might also mention that it changes the behavior of the GetDataDir function. The effect I think is to now allow `-nodatadir` or `-datadir=''` options on the command line to override any datadir specified in the config file and reset it to default. In theory this could even be mentioned in release notes, but it's probably too niche.

**Review by ryanofsky — APPROVED** [review]
utACK 9bddf12763e1bcc41c176f8b7f0b883efed49823. Changes since last review are adding commit descriptions, documenting new `CheckDataDirOption()` method, and handling `-nodatadir` and `-datadir=""` better.

This PR should be tagged as needing release notes if release notes aren't added before it is merged in a `doc/release-notes-15864.md` file. I think you could take the description from https://github.com/bitcoin/bitcoin/pull/15864#issuecomment-490952565 and basically turn it into a release note, describing the class of bugs that are fixed and not mentioning specific function names.

File: src/util/system.cpp (hunk 5 above)
Comment (hebasto) [reply src/util/system.cpp]: > The effect I think is to now allow `-nodatadir` or `-datadir=''` options on the command line to override any datadir specified in the config file and reset it to default.

Unfortunately, neither `-nodatadir` nor `-datadir=''` on the command line can unset datadir specified in the config file or reset it to default. See: #16097.

**Comment by hebasto** [comment]
@MarcoFalke would you mind reviewing this PR?

**Comment by hebasto** [comment]
Rebased after #16205 merged.

**Comment by MarcoFalke** [comment]
Concept ACK

**Review by ryanofsky — APPROVED** [review]
utACK 4f0de6214ae591bfb37ef745140f45fcc97aec33. No changes since last review except rebase and replacing fprintf with tfm::format.

**Comment by hebasto** [comment]
Rebased on top of #16300.

File: src/util/system.cpp [hunk 6]
```diff
@@ -1199,6 +1199,9 @@ int64_t GetStartupTime()
 
 fs::path AbsPathForConfigVal(const fs::path& path, bool net_specific)
 {
+    if (path.is_absolute()) {
+        return path;
+    }
```
Comment (MarcoFalke) [inline src/util/system.cpp]: Would be nice if each commit had a test that failed before compilation and passes after. That might simplify review, no?

Comment (hebasto) [reply src/util/system.cpp]: Do tests enabled in 5124b1cef24a9b30876ddedf922dfdb555bd4ace do this job?

File: src/util/system.cpp (hunk 5 above)
Comment (MarcoFalke) [reply src/util/system.cpp]: Then, why is this changed?

File: src/bitcoind.cpp (hunk 3 above)
Comment (hebasto) [reply src/bitcoind.cpp]: Please see https://github.com/bitcoin/bitcoin/pull/15864#issuecomment-490952565

File: src/util/system.cpp (hunk 5 above)
Comment (hebasto) [reply src/util/system.cpp]: The [initial idea](https://github.com/bitcoin/bitcoin/pull/15864#discussion_r281785729) was:
> I don't think `IsArgSet` is the right function to call here.

If we recall:
https://github.com/bitcoin/bitcoin/blob/8c69fae94410f54bad13be0f34d54370fddbf4b3/src/util/system.cpp#L470-L474

using `IsArgNegated` is (logically) inappropriate for `-datadir` option, IMO.

Also (but minor), the suggested code uses only one function call (`GetArg`) instead of two calls (`IsArgSet` and `GetArg`).

**Review by ryanofsky — APPROVED** [review]
utACK 5f55360ea36487131a14dbc0a2518ec3babc1580. No changes since last review other than rebase and comment tweak.

File: src/util/system.cpp (hunk 6 above)
Comment (MarcoFalke) [reply src/util/system.cpp]: Can they be enabled in this commit (the first commit)?

Comment (hebasto) [reply src/util/system.cpp]: Do you mean to combine the "Enable all tests in feature_config_args.py " commit (5124b1cef24a9b30876ddedf922dfdb555bd4ace) into the "Return absolute path early in AbsPathForConfigVal" commit (c21150fd6f598196fae93cf4bddc6e7625a43660)?

Master branch plus this combined commit will fail the test.
And the test will be passed on top of the 584621f9a81b6cc547c8f1365f1b358866e9a335 and b921f6ee951f0ad6d87eeeb372136a7314af0b0e commits.

Did I understand your intention correctly?

**Comment by hebasto** [comment]
Rebased.

**Comment by hebasto** [comment]
@laanwj Would you mind reviewing this PR?

**Review by ryanofsky — APPROVED** [review]
utACK fd7310f24422901e0d4cf82c93f04b2b1b458865. No changes since last review other than rebase after #16291

**Comment by MarcoFalke** [comment]
The 09a307183aca7b2f6e1a14caf4430a1fc546e704 commit would have to be in the test commit or before it, otherwise the test running with the gui might fail on the test commit?

**Comment by hebasto** [comment]
Rebased.

@MarcoFalke 
> The 09a3071 commit would have to be in the test commit or before it, otherwise the test running with the gui might fail on the test commit?

Commits have been rearranged. The test commit is the last one now.

File: src/util/system.cpp (hunk 5 above)
Comment (hebasto) [reply src/util/system.cpp]: @ryanofsky @MarcoFalke 
> The effect I think is to now allow `-nodatadir` or `-datadir=''` options on the command line to override any datadir specified in the config file and reset it to default.

Actually, `-datadir=''` (with empty string) or `-datadir` will reset it to default. So, going to close #16416 in favor of this PR.

**Comment by hebasto** [comment]
@MarcoFalke https://github.com/bitcoin/bitcoin/issues/15240#issuecomment-541334088

Label "Needs backport 0.18" ?
