### PR TITLE
validation: don't try to invalidate genesis block in CChainState::InvalidateBlock

### LINKED ISSUE #20914: Null pointer derefence in CBlockIndexWorkComparator::operator() reachable via RPC call invalidateblock
While fuzzing the RPC interface I stumbled upon a null pointer dereference in `CBlockIndexWorkComparator::operator()` which is reachable via the `invalidateblock` RPC call:

```
$ ./autogen.sh
$ CC=clang CXX=clang++ ./configure --with-sanitizers=address,undefined
$ make
$ src/bitcoind -regtest &
$ src/bitcoin-cli -regtest generatetodescriptor 1 'addr(bcrt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3xueyj)#juyq9d97'
2021-01-12T14:27:41Z CreateNewBlock(): block weight: 932 txs: 0 fees: 0 sigops 400
2021-01-12T14:27:41Z Pre-allocating up to position 0x100000 in rev00000.dat
2021-01-12T14:27:41Z Leaving InitialBlockDownload (latching to false)
2021-01-12T14:27:41Z UpdateTip: new best=60c56626f298548305381979897bc2ac4ced1c1f6b3b7b6ba7dfaa83c428eb92 height=1 version=0x20000000 log2_work=2.000000 tx=2 date='2021-01-12T14:27:41Z' progress=1.000000 cache=0.0MiB(1txo)
[
  "60c56626f298548305381979897bc2ac4ced1c1f6b3b7b6ba7dfaa83c428eb92"
]
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
2021-01-12T14:28:01Z UpdateTip: new best=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 height=0 version=0x00000001 log2_work=1.000000 tx=1 date='2011-02-02T23:16:42Z' progress=1.000000 cache=0.0MiB(1txo)
2021-01-12T14:28:01Z ERROR: UndoReadFromDisk: no undo data available
2021-01-12T14:28:01Z ERROR: DisconnectBlock(): failure reading undo data
2021-01-12T14:28:01Z ERROR: DisconnectTip(): DisconnectBlock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 failed
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
validation.cpp:87:30: runtime error: member access within null pointer of type 'const CBlockIndex'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior validation.cpp:87:30 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7489==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000044 (pc 0x559ffc210c43 bp 0x60d0000e7301 sp 0x7f83af6b6890 T16)
==7489==The signal is caused by a READ memory access.
==7489==Hint: address points to the zero page.
    #0 0x559ffc210c42 in base_uint<256u>::CompareTo(base_uint<256u> const&) const src/arith_uint256.cpp
    #1 0x559ffbc96c55 in operator>(base_uint<256u> const&, base_uint<256u> const&) src/./arith_uint256.h:219:85
    #2 0x559ffbc96c55 in CBlockIndexWorkComparator::operator()(CBlockIndex const*, CBlockIndex const*) const src/validation.cpp:87:24
    #3 0x559ffbcc3363 in CChainState::InvalidateBlock(BlockValidationState&, CChainParams const&, CBlockIndex*) src/validation.cpp:2954:22
    #4 0x559ffbcc50d3 in InvalidateBlock(BlockValidationState&, CChainParams const&, CBlockIndex*) src/validation.cpp:3061:33
    #5 0x559ffb9a6eb7 in invalidateblock()::$_22::operator()(RPCHelpMan const&, JSONRPCRequest const&) const src/rpc/blockchain.cpp:1603:5
…
[1]+  Exit 1                  src/bitcoind -regtest
```

Nothing high priority of course, but still worth fixing :)

### PR DESCRIPTION
**Pull request by theStack**
In the block invalidation method (`CChainState::InvalidateBlock`), the code for creating the candidate block map assumes that the passed block's previous block (`pindex->pprev`) is available and otherwise segfaults due to null-pointer deference in `CBlockIndexWorkComparator()` (see analysis by practicalswift in #20914), i.e. it doesn't work with the genesis block. Rather than analyzing all possible code paths and implications for this corner case, simply fail early if the genesis block is passed.

Fixes #20914.

### CODE REVIEW

**Review by luke-jr — APPROVED** [review]
utACK

File: src/validation.cpp [hunk 1]
```diff
@@ -2923,6 +2923,9 @@ bool PreciousBlock(BlockValidationState& state, const CChainParams& params, CBlo
 
 bool CChainState::InvalidateBlock(BlockValidationState& state, const CChainParams& chainparams, CBlockIndex *pindex)
 {
+    // Genesis block can't be invalidated
+    if (pindex->nHeight == 0) return false;
```
Comment (ViralTaco) [inline src/validation.cpp:2927]: This is actually not preventing UB, it's adding more.

**Review by ViralTaco — CHANGES_REQUESTED** [review]
Add `nullptr` check for `pindex` in `BlockValidationState&, CChainParams const&, CBlockIndex*)`

I'm sorry I can't commit I need to setup the environment

**Comment by theStack** [comment]
@ViralTaco: Agree that there should also be a null pointer check `pindex` before access. Solved this now by adding a simple `assert` (alternatively one could change the parameter to a reference).

**Comment by sipa** [comment]
ACK 787df19b09babf50dd8124b3ac990b29c33cfe93. Tested invalidation of generic on regtest.

Would be nice to add a functional test that attempts this, so that it gets detected if it were reintroduced.

**Comment by practicalswift** [comment]
Tested ACK 787df19b09babf50dd8124b3ac990b29c33cfe93

Before:

```
$ git checkout master
$ make distclean
$ ./autogen.sh
$ CC=clang CXX=clang++ ./configure --with-sanitizers=address,undefined
$ make
$ src/bitcoind -regtest &
$ src/bitcoin-cli -regtest generatetodescriptor 1 'addr(bcrt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3xueyj)#juyq9d97'
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
validation.cpp:89:30: runtime error: member access within null pointer of type 'const CBlockIndex'
==11604==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000044 (pc 0x56387ee23e87 bp 0x000000000008 sp 0x7f3a6e1b6570 T16)
==11604==The signal is caused by a READ memory access.
==11604==Hint: address points to the zero page.
```

After:

```
$ gh pr checkout 20921
$ make -C src/ bitcoind
$ src/bitcoind -regtest &
$ src/bitcoin-cli -regtest generatetodescriptor 1 'addr(bcrt1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3xueyj)#juyq9d97'
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
$ src/bitcoin-cli -regtest invalidateblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
$ jobs
[1]+  Running                 src/bitcoind -regtest &
```
