### PR TITLE
wallet: ignore chainStateFlushed notifications while attaching chain

### LINKED ISSUE #24487: Automatic wallet rescan skipped after abort
I ran bitcoin-qt with an old wallet, causing it to rescan, then stopped it with a SIGINT signal, resulting in the following log. Nothing unexpected, so far:
```
2022-03-05T16:01:03Z init message: Loading wallet…
2022-03-05T16:01:03Z BerkeleyEnvironment::Open: LogDir=…/.bitcoin/database ErrorFile=…/.bitcoin/db.log
2022-03-05T15:57:18Z [walletname.dat] Wallet File Version = 159900
2022-03-05T15:57:18Z [walletname.dat] Keys: 2397 plaintext, 0 encrypted, 2397 w/ metadata, 2397 total. Unknown wallet records: 0
2022-03-05T15:57:18Z [walletname.dat] Wallet completed loading in              65ms
2022-03-05T15:57:18Z init message: Rescanning…
2022-03-05T15:57:18Z [walletname.dat] Rescanning last 134072 blocks (from block 591711)...
2022-03-05T15:57:18Z [walletname.dat] Rescan started from block 000000000000000000075fcc1872da61f45bcfd0e0bb36b7c8cb45e7a328ad41...
2022-03-05T15:58:18Z [walletname.dat] Still rescanning. At block 593552. Progress=0.632716
2022-03-05T15:59:18Z [walletname.dat] Still rescanning. At block 595458. Progress=0.638084
2022-03-05T15:59:37Z [walletname.dat] Rescan interrupted by shutdown request at block 596080. Progress=0.639932
2022-03-05T15:59:37Z Error: Failed to rescan the wallet during initialization
2022-03-05T15:59:41Z GUI: initializeResult : Initialization result:  false
2022-03-05T15:59:41Z GUI: requestShutdown : Requesting shutdown
2022-03-05T15:59:41Z GUI: Running Shutdown in thread
2022-03-05T15:59:41Z Shutdown: In progress...
2022-03-05T15:59:41Z scheduler thread exit
2022-03-05T15:59:42Z Shutdown: done
2022-03-05T15:59:42Z GUI: Shutdown finished
2022-03-05T15:59:42Z GUI: ~InitExecutor : Stopping thread
2022-03-05T15:59:42Z GUI: ~InitExecutor : Stopped thread
```

However, the next time it was launched, the rescan didn't continue, nor did it start over. It seems to have been skipped?
```
2022-03-05T16:01:03Z init message: Loading wallet…
2022-03-05T16:01:03Z BerkeleyEnvironment::Open: LogDir=…/.bitcoin/database ErrorFile=…/.bitcoin/db.log
2022-03-05T16:01:03Z [walletname.dat] Wallet File Version = 159900
2022-03-05T16:01:03Z [walletname.dat] Keys: 2397 plaintext, 0 encrypted, 2397 w/ metadata, 2397 total. Unknown wallet records: 0
2022-03-05T16:01:03Z [walletname.dat] Wallet completed loading in              91ms
2022-03-05T16:01:03Z [walletname.dat] setKeyPool.size() = 2000
2022-03-05T16:01:03Z [walletname.dat] mapWallet.size() = 378
2022-03-05T16:01:03Z [walletname.dat] m_address_book.size() = 183
2022-03-05T16:01:03Z Loaded 2 addresses from "anchors.dat"
```

I didn't investigate deeply, but could it be that despite the failed rescan, the new tip block was stored in the wallet? if so, this would be confusing.

### PR DESCRIPTION
**Pull request by mzumsande**
Fixes #24487

When a rescan is performed during `CWallet::AttachChain()` (e.g. when loading an old wallet) but this is interrupted by a shutdown signal, the wallet will currently stop the rescan, receive a `chainStateFlushed` signal, set the saved best block to the tip and shut down. At next startup, the rescan is not continued or repeated because of this. But some blocks have never been scanned by the wallet, which could lead to an incorrect balance.

Fix this by ignoring `chainStateFlushed` notifications until the chain is attached. Since `CWallet::chainStateFlushed` is being manually called by `AttachChain()` anyway after finishing with the rescan, it is not a problem if intermediate notifications are ignored.

Manual rescans started / aborted by the `rescanblockchain` / `abortrescan` RPCs are not affected by this.

I didn't choose alternative ways of fixing this issue that would delay the validationinterface registration or change anything else about the handling of `blockConnected` signals for the reasons mentioned in [this existing comment](https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L2937-L2944).

### CODE REVIEW

**Comment by mzumsande** [comment]
This breaks `feature_pruning.py`, putting into draft until I have analyzed it.

File: src/wallet/wallet.cpp [hunk 1]
```diff
@@ -3007,6 +3015,7 @@ bool CWallet::AttachChain(const std::shared_ptr<CWallet>& walletInstance, interf
                 return false;
             }
         }
+        walletInstance->m_attaching_chain = false;
```
Comment (S3RK) [inline src/wallet/wallet.cpp:3018]: If you never started a rescan, than you would leave `m_attaching_chain` in true state forever

**Review by S3RK — COMMENTED** [review]
With current implementation we don't save the rescan progress and on the next load we will have to start from scratch. Is it possible to save the last processed blocked at shutdown?

File: src/wallet/wallet.cpp (hunk 1 above)
Comment (mzumsande) [reply src/wallet/wallet.cpp:3018]: Oh yes, thanks. Moved the spot where we set `m_attaching_chain` into the conditional.

**Comment by mzumsande** [comment]
> With current implementation we don't save the rescan progress and on the next load we will have to start from scratch. Is it possible to save the last processed blocked at shutdown?

Yes, that's true. I think it should be possible to call `chainStateFlushed` with a locator to the block that was last processed  - I'll look into that. Of course it would save some time only in the rather rare situation of a clean shutdown during rescan (the bug must have existed for years but wasn't reported until very recently), so I'm not sure how important a feature like this would actually be for users.

**Comment by laanwj** [comment]
Concept ACK

> so I'm not sure how important a feature like this would actually be for users.

Right, I'm concerned about unexpected behavior. I don't think optimality is important in this case.

**Comment by S3RK** [comment]
> Yes, that's true. I think it should be possible to call `chainStateFlushed` with a locator to the block that was last processed - I'll look into that. Of course it would save some time only in the rather rare situation of a clean shutdown during rescan (the bug must have existed for years but wasn't reported until very recently), so I'm not sure how important a feature like this would actually be for users.

The wallet already tracks last processed block, why can't we just write that form `chainStateFlushed` handler regardless of what locator was passed in. That way we don't need any bool flags I believe.

**Comment by mzumsande** [comment]
> The wallet already tracks last processed block, why can't we just write that form `chainStateFlushed` handler regardless of what locator was passed in. That way we don't need any bool flags I believe.

Not sure I understand this right - do you mean why locators are used in general instead of single block hashes? I think that's because we want to be flexible and not dependent on a specific block: There may be a reorg so a given block is no longer part of the chain when the wallet is loaded, or maybe the the wallet called the chainStateFlushed handler manually without the actual chainstate being flushed, and then an unclean shutdown happens so that the wallet would be ahead of the chain at next startup.

In any case, any block must be converted to a locator anyway to be stored in `BESTBLOCK_NOMERKLE` in order not to break the db format.

Also note that `AttachChain()` updates `m_last_block_processed` optimistically to the tip (before actually processing any missing blocks) and not incrementally. So if it gets interrupted early, `m_last_block_processed` is not correct.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 2052e3aa9aa666bdc86dac370f1dd8fb978d3497. This is a straightforward fix for the bug described in #24487 where a wallet could skip scanning blocks if is shut down in the middle of a sync and a chainStateFlushed notification was received during the sync. It would be nice to write a test for this but probably would be tricky to write.

S3RK raises a great point in https://github.com/bitcoin/bitcoin/pull/24984#pullrequestreview-952900468 that the wallet doesn't save the scan position during syncs, so if it is interrupted, parts of the scan could be repeated unnecessarily next time the wallet is loaded. This issue would be good to fix, and I created #25010 to track it, but I think it's basically a separate issue with a separate fix. This PR makes that issue more likely to happen, but in the cases it does this, current behavior of skipping unscanned blocks is worse than new behavior of rescanning already-scanned blocks, so in every case this PR should be a strict improvement over the status quo.

**Comment by achow101** [comment]
ACK 2052e3aa9aa666bdc86dac370f1dd8fb978d3497

**Comment by S3RK** [comment]
Agree that "this PR should be a strict improvement over the status quo".

The only thing that still slightly worries me is two `return false` statements between setting and unsetting the `m_attaching_chain` flag. In both cases rescan fails, so I guess the behaviour is still correct, but it looks fragile.

**Comment by mzumsande** [comment]
> It would be nice to write a test for this but probably would be tricky to write.

Yes, I'd like that too. the problem is how to deal with the racing condition, timing the shutdown to be during the sync and not after. I played around a bit with bpftrace / uprobes after an idea by @jnewbery (e.g. hook into a function such as `SyncTransaction()` and send a SIGINT when it is invoked the 20th time) and that is really cool and seems to work, but obviously still very experimental and not ready for the CI.

> The only thing that still slightly worries me is two `return false` statements between setting and unsetting the `m_attaching_chain` flag. In both cases rescan fails, so I guess the behaviour is still correct, but it looks fragile.

Yes, we currently rely on this to be the case. We aren't only concerned about accidental signals during the sync but also after it, caused by the interrupting signal: In case of a shutdown by SIGINT, [Shutdown()](https://github.com/bitcoin/bitcoin/blob/9446de160f37ccf9d639960f38bc1e4337b0c5f7/src/init.cpp#L200 ) in Init will  create a `chainStateFlushed` signal which is processed by the wallet. At this point in time, `m_attaching_chain` must still be true or the bug is not fixed.

**Review by w0xlt — APPROVED** [review]
Code Review ACK https://github.com/bitcoin/bitcoin/pull/24984/commits/2052e3aa9aa666bdc86dac370f1dd8fb978d3497

If I understand correctly, the problem is that at the end of `CWallet::AttachChain()`, `CWallet::chainStateFlushed(...)` is called passing the chain tip as parameter, even if abort or shutdown is requested during the wallet scan (`CWallet::ScanForWalletTransactions`).

I think this solution achieves the goal of preventing the wallet from being in an inconsistent state by forcing it to write the tip only after the scan completes.

Ideally there would be a functional test for this, but I don't see how to simulate this on regtest.
