### PR TITLE
Convert ArgsManager::GetDataDir to a read-only function

### LINKED ISSUE #20070: bitcoin-cli needlessly creates empty ~/.bitcoin/wallets directory
When `bitcoin-cli` is run, **it, not bitcoind** creates an empty `~/.bitcoin/wallets` direcctory with `~` bring home of currently running user. This is weird and leads to user confusion because it happens even in cases when `bitcoin-cli` connects to a `bitcoind` running under a different user or probably on other machine.

**Expected behavior**

`bitcoin-cli` never modifies filesystem, especially not things that the daemon should take care of.

**Actual behavior**

`bitcoin-cli creates empty directory`

**To reproduce**

0. make sure `~/.bitcoin` does **not** exist under user A
1. install `bitcoind` and run it under a user B
2. run `bitcoin-cli getblockchaininfo` under user A
3. `ls ~/.bitcoin` under user A

For quick setup, you can try to use [my project](https://deb.ln-ask.me) in a Debian VM or using provided Docker file. Just `apt install bitcoin-regtest bitcoin-cli`, it's already pre-configured to run under a different user, so then just running `sudo bitcoin-cli getblockchaininfo && sudo ls /root/.bitcoin` should reproduce the issue.

**System information**

0.20 official release downloaded from `https://bitcoin.org/bin/bitcoin-core-...`, verified GPG signature from Wladimir.

OS: Linux Debian Buster
CPU: Intel x86_64
Disk: NVMe SSD
FS: ext4

I don't think configuration is relevant since `bitcoin-cli` is **not** informed where to find it (via parameters or otherwise) and thus it can **not** access it. I also added `-rpcport` and `-rpccookiefile` parameters explicitly but I don't think it's relevant.

Loosely related to #16220, but not a duplicate.

### PR DESCRIPTION
**Pull request by willcl-ark**
Fixes #20070

Currently `ArgsManager::GetDataDir()` ensures it will always return a datadir by creating one if necessary. The function is shared between `bitcoind` `bitcoin-qt` and `bitcoin-cli` which results in the undesirable behaviour described in #20070.

This PR splits out the part of the function which creates directories and adds it as a standalone function, only called as part of `bitcoind` and `bitcoin-qt` init, but not `bitcoin-cli`.

`ReadConfigFiles`' behavior is changed to use the absolute path of the config file in error and warning messages instead of a relative path.

This was inadvertantly the form being tested [here](https://github.com/bitcoin/bitcoin/blob/73966f75f67fb797163f0a766292a79d4b2c1b70/test/functional/feature_config_args.py#L287), whilst we were _not_ testing that a relative path was returned by the message even though we passed a relative path in as argument.

### CODE REVIEW

File: src/util/system.cpp [hunk 1]
```diff
@@ -965,6 +967,19 @@ bool ArgsManager::ReadConfigStream(std::istream& stream, const std::string& file
     return true;
 }
 
+void ArgsManager::GetConfigFilePath(fs::path& conf_path, fs::path& conf_file)
+{
+    conf_path = GetPathArg("-conf", BITCOIN_CONF_FILENAME);
+    conf_file = GetConfigFile(conf_path);
+}
+
+void ArgsManager::GetOrCreateConfigFilePath()
```
Comment (stickies-v) [inline src/util/system.cpp:976]: It seems like this function is only used to call `ArgsManager::CreateDataDirIfNotExists(false)`. Unless I misunderstand, I think it makes more sense to just make `ArgsManager::CreateDataDirIfNotExists` public? It's less code and a more clear intent, imo.

<details>
<summary>git diff (overlaps a bit with my other comment)</summary>

```diff
diff --git a/src/bitcoind.cpp b/src/bitcoind.cpp
index 3d154961b..49a709628 100644
--- a/src/bitcoind.cpp
+++ b/src/bitcoind.cpp
@@ -153,7 +153,7 @@ static bool AppInit(NodeContext& node, int argc, char* argv[])
         if (!CheckDataDirOption()) {
             return InitError(Untranslated(strprintf("Specified data directory \"%s\" does not exist.\n", args.GetArg("-datadir", ""))));
         }
-        args.GetOrCreateConfigFilePath();
+        args.CreateDataDirIfNotExists(false);
         if (!args.ReadConfigFiles(error, true)) {
             return InitError(Untranslated(strprintf("Error reading configuration file: %s\n", error)));
         }
diff --git a/src/qt/bitcoin.cpp b/src/qt/bitcoin.cpp
index f69c4be2d..fa3d0ab92 100644
--- a/src/qt/bitcoin.cpp
+++ b/src/qt/bitcoin.cpp
@@ -596,7 +596,7 @@ int GuiMain(int argc, char* argv[])
     try {
         /// 6b. Parse bitcoin.conf
         /// - Do not call gArgs.GetDataDirNet() before this step finishes
-        gArgs.GetOrCreateConfigFilePath();
+        gArgs.CreateDataDirIfNotExists(false);
         if (!gArgs.ReadConfigFiles(error, true)) {
             InitError(strprintf(Untranslated("Error reading configuration file: %s\n"), error));
             QMessageBox::critical(nullptr, PACKAGE_NAME,
diff --git a/src/util/system.cpp b/src/util/system.cpp
index 11991f1ab..335630599 100644
--- a/src/util/system.cpp
+++ b/src/util/system.cpp
@@ -967,17 +967,9 @@ bool ArgsManager::ReadConfigStream(std::istream& stream, const std::string& file
     return true;
 }
 
-void ArgsManager::GetConfigFilePath(fs::path& conf_path, fs::path& conf_file)
+fs::path ArgsManager::GetConfigFilePath()
 {
-    conf_path = GetPathArg("-conf", BITCOIN_CONF_FILENAME);
-    conf_file = GetConfigFile(conf_path);
-}
-
-void ArgsManager::GetOrCreateConfigFilePath()
-{
-    fs::path conf_path, conf_file;
-    GetConfigFilePath(conf_path, conf_file);
-    CreateDataDirIfNotExists(false);
+    return GetConfigFile(GetPathArg("-conf", BITCOIN_CONF_FILENAME));
 }
 
 bool ArgsManager::ReadConfigFiles(std::string& error, bool ignore_invalid_keys)
@@ -988,9 +980,8 @@ bool ArgsManager::ReadConfigFiles(std::string& error, bool ignore_invalid_keys)
         m_config_sections.clear();
     }
 
-    fs::path conf_path, conf_file;
-    GetConfigFilePath(conf_path, conf_file);
-    std::ifstream stream{conf_file};
+    auto conf_path{GetConfigFilePath()};
+    std::ifstream stream{conf_path};
 
     // not ok to have a config file specified that cannot be opened
     if (IsArgSet("-conf") && !stream.good()) {
diff --git a/src/util/system.h b/src/util/system.h
index e3cb56d06..85b1f00d0 100644
--- a/src/util/system.h
+++ b/src/util/system.h
@@ -242,8 +242,7 @@ protected:
     void SelectConfigNetwork(const std::string& network);
 
     [[nodiscard]] bool ParseParameters(int argc, const char* const argv[], std::string& error);
-    void GetConfigFilePath(fs::path& conf_path, fs::path& conf_file);
-    void GetOrCreateConfigFilePath();
+    fs::path GetConfigFilePath();
     [[nodiscard]] bool ReadConfigFiles(std::string& error, bool ignore_invalid_keys = false);
 
     /**
@@ -477,6 +476,13 @@ protected:
      */
     void LogArgs() const;
 
+    /**
+     * Create data directory if it doesn't exist
+     *
+     * @param net_specific Create a network-identified data directory
+     */
+    void CreateDataDirIfNotExists(bool net_specific);
+
 private:
     /**
      * Get data directory path
@@ -486,13 +492,6 @@ private:
      */
     const fs::path& GetDataDir(bool net_specific) const;
 
-    /**
-     * Create data directory if it doesn't exist
-     *
-     * @param net_specific Create a network-identified data directory
-     */
-    void CreateDataDirIfNotExists(bool net_specific);
-
     // Helper function for LogArgs().
     void logArgsPrefix(
         const std::string& prefix,
```
</details>

**Review by stickies-v — COMMENTED** [review]
Concept ACK - having the cli generate multiple datadirs is not great. Suggested some simplifications, I hope I'm not missing some nuance there?

File: src/util/system.cpp (hunk 1 above)
Comment (pinheadmz) [inline src/util/system.cpp:976]: I'd suggest renaming this function too, it returns `void` so it's not really a "getter"

**Review by pinheadmz — COMMENTED** [review]
concept ACK

I reproduced the steps from the issue and confirmed that the patch prevents creating new `Bitcoin/wallets` directory when running `bitcoin-cli -getinfo` from a new user on the same machine running bitcoind

File: src/util/system.cpp [hunk 2]
```diff
@@ -432,20 +432,21 @@ const fs::path& ArgsManager::GetDataDir(bool net_specific) const
...
         path /= fs::PathFromString(BaseParams().DataDir());
-        if (!fs::exists(path)) {
-            fs::create_directories(path / "wallets");
-        }
     }
 
     return path;
 }
 
+void ArgsManager::CreateDataDirIfNotExists(bool net_specific)
```
[the remark this answers is not in the document]
Comment (stickies-v) [reply src/util/system.cpp:442]: > Actually this is just for the wallet?

It's not just for the wallet, it's simply shorthand for creating both `datadir/` as well as `datadir/wallets/` - `fs::create_directories` [creates](https://en.cppreference.com/w/cpp/filesystem/create_directory) all the non-existing dirs in path.

File: src/util/system.cpp (hunk 1 above)
Comment (willcl-ark) [reply src/util/system.cpp]: Thanks, I adapted these changes with @pinheadmz name change suggested below

File: src/util/system.cpp [hunk 3]
```diff
@@ -965,6 +967,19 @@ bool ArgsManager::ReadConfigStream(std::istream& stream, const std::string& file
     return true;
 }
 
+void ArgsManager::GetConfigFilePath(fs::path& conf_path, fs::path& conf_file)
```
[the remark this answers is not in the document]
Comment (willcl-ark) [reply src/util/system.cpp]: agreed

File: src/util/system.cpp (hunk 1 above)
Comment (willcl-ark) [reply src/util/system.cpp]: Now returns a file path

**Comment by willcl-ark** [comment]
Thanks @stickies-v & @pinheadmz , I addressed your comments in the new push.

File: src/util/system.cpp [hunk 4]
```diff
@@ -432,20 +432,21 @@ const fs::path& ArgsManager::GetDataDir(bool net_specific) const
...
-            fs::create_directories(path / "wallets");
-        }
     }
 
     return path;
 }
 
+void ArgsManager::EnsureDataDir(bool net_specific)
+{
+    fs::path path = GetDataDir(net_specific);
```
Comment (stickies-v) [inline src/util/system.cpp:444]: nit
```suggestion
    const auto path{GetDataDir(net_specific)};
```

File: src/util/system.cpp [hunk 5]
```diff
@@ -973,8 +980,8 @@ bool ArgsManager::ReadConfigFiles(std::string& error, bool ignore_invalid_keys)
         m_config_sections.clear();
     }
 
-    const fs::path conf_path = GetPathArg("-conf", BITCOIN_CONF_FILENAME);
-    std::ifstream stream{GetConfigFile(conf_path)};
+    auto conf_path{GetConfigFilePath()};
```
Comment (stickies-v) [inline src/util/system.cpp:983]: sorry, forgot to mark this as `const` in my diff
```suggestion
    const auto conf_path{GetConfigFilePath()};
```

File: src/bitcoind.cpp [hunk 6]
```diff
@@ -153,6 +153,7 @@ static bool AppInit(NodeContext& node, int argc, char* argv[])
         if (!CheckDataDirOption()) {
             return InitError(Untranslated(strprintf("Specified data directory \"%s\" does not exist.\n", args.GetArg("-datadir", ""))));
         }
+        args.EnsureDataDir(false);
```
Comment (stickies-v) [inline src/bitcoind.cpp:156]:
```suggestion
        args.EnsureDataDir(/*net_specific=*/false);
```

File: src/qt/bitcoin.cpp [hunk 7]
```diff
@@ -596,6 +596,7 @@ int GuiMain(int argc, char* argv[])
     try {
         /// 6b. Parse bitcoin.conf
         /// - Do not call gArgs.GetDataDirNet() before this step finishes
+        gArgs.EnsureDataDir(false);
```
Comment (stickies-v) [inline src/qt/bitcoin.cpp:599]:
```suggestion
        gArgs.EnsureDataDir(/*net_specific=*/false);
```

**Comment by hebasto** [comment]
Concept ACK.

File: src/util/system.cpp (hunk 5 above)
Comment (willcl-ark) [reply src/util/system.cpp]: sure, also agree

File: src/util/system.cpp [hunk 8]
```diff
@@ -432,20 +432,21 @@ const fs::path& ArgsManager::GetDataDir(bool net_specific) const
...
     }
 
     return path;
 }
 
+void ArgsManager::EnsureDataDir(bool net_specific)
+{
+    fs::path path = GetDataDir(net_specific);
+    if (!fs::exists(path)) {
+        fs::create_directories(path / "wallets");
```
Comment (hebasto) [inline src/util/system.cpp:446]: 1. Should we care about possible exceptions here?
2. What is the point to run this code when `net_specific == false`?

File: src/util/system.cpp [hunk 9]
```diff
@@ -432,20 +432,21 @@ const fs::path& ArgsManager::GetDataDir(bool net_specific) const
...
         path /= fs::PathFromString(BaseParams().DataDir());
-        if (!fs::exists(path)) {
-            fs::create_directories(path / "wallets");
-        }
     }
 
     return path;
 }
 
+void ArgsManager::EnsureDataDir(bool net_specific)
```
Comment (hebasto) [inline src/util/system.cpp:442]: Maybe introduce two functions: one for `net_specific == true` and the other for `net_specific == true`?

It will make code cleaner on the caller sites.

Comment (willcl-ark) [reply src/util/system.cpp:442]: Totally agree there could be two wrapper functions here if desired, `EnsureDataDir` and `EnsureNetDataDir` perhaps? It might just means more duplicated code in the end though?

File: src/util/system.cpp (hunk 4 above)
Comment (willcl-ark) [reply src/util/system.cpp]: Now addresses in 7b69b99f9

File: src/util/system.cpp (hunk 8 above)
Comment (hebasto) [reply src/util/system.cpp:446]: > 2\. When run with `net_specific = false`, this will return the general `DataDir`, e.g. `$HOME/.bitcoin` and with `true` will return the network-specific DataDir e.g. `$HOME/.bitcoin/regtest`

> 2\. When run with `net_specific = false`, this will return the general `DataDir`, e.g. `$HOME/.bitcoin` and with `true` will return the network-specific DataDir e.g. `$HOME/.bitcoin/regtest`

Sorry, if my question was unclear. My point is whether we are interested in the `wallet` directory when `net_specific = false`?

File: src/util/system.cpp (hunk 9 above)
Comment (stickies-v) [reply src/util/system.cpp:442]: I did some digging, and I think (would be nice to get more confirmation on this) we can scrap the `net_specific == false` version entirely, we don't seem to need it. `EnsureDataDir` is called 3 times: 2 times right before reading config files - but it looks like we don't actually need to ensure a datadir there. If datadir doesn't exist, by definition no config files can be read (and that's handled gracefully). The only time we need it is where `net_specific==true`.

Intuitively, this makes sense - it can never hurt to ensure that all the necessary datadirs (both base as well as the more specific net) exist. However, there actually is a pitfall, because `GetDataDir()` [does some caching](https://github.com/bitcoin/bitcoin/blob/8126551d54ffd290ed5767248be4b3d19243787b/src/util/system.cpp#L420-L422), we're [not allowed](https://github.com/bitcoin/bitcoin/blob/8126551d54ffd290ed5767248be4b3d19243787b/src/qt/bitcoin.cpp#L598) to call `GetDatDir(true)` before we've determined the network we're on (which requires us to first read the basedir and check if there's a config file there).

For that reason, I think calling it `EnsureDataDirNet` is probably better - and aligns with `GetDataDirNet` naming.

<details>
<summary>git diff (quick patch just to prototype)</summary>

```diff
diff --git a/src/bitcoind.cpp b/src/bitcoind.cpp
index 3a36ff700..07002cc8a 100644
--- a/src/bitcoind.cpp
+++ b/src/bitcoind.cpp
@@ -153,7 +153,6 @@ static bool AppInit(NodeContext& node, int argc, char* argv[])
         if (!CheckDataDirOption()) {
             return InitError(Untranslated(strprintf("Specified data directory \"%s\" does not exist.\n", args.GetArg("-datadir", ""))));
         }
-        args.EnsureDataDir(/*net_specific=*/false);
         if (!args.ReadConfigFiles(error, true)) {
             return InitError(Untranslated(strprintf("Error reading configuration file: %s\n", error)));
         }
diff --git a/src/qt/bitcoin.cpp b/src/qt/bitcoin.cpp
index 80e607f77..59f433749 100644
--- a/src/qt/bitcoin.cpp
+++ b/src/qt/bitcoin.cpp
@@ -596,7 +596,6 @@ int GuiMain(int argc, char* argv[])
     try {
         /// 6b. Parse bitcoin.conf
         /// - Do not call gArgs.GetDataDirNet() before this step finishes
-        gArgs.EnsureDataDir(/*net_specific=*/false);
         if (!gArgs.ReadConfigFiles(error, true)) {
             InitError(strprintf(Untranslated("Error reading configuration file: %s\n"), error));
             QMessageBox::critical(nullptr, PACKAGE_NAME,
diff --git a/src/util/system.cpp b/src/util/system.cpp
index 329100008..75fd91516 100644
--- a/src/util/system.cpp
+++ b/src/util/system.cpp
@@ -439,9 +439,9 @@ const fs::path& ArgsManager::GetDataDir(bool net_specific) const
     return path;
 }
 
-void ArgsManager::EnsureDataDir(bool net_specific)
+void ArgsManager::EnsureDataDirNet()
 {
-    fs::path path = GetDataDir(net_specific);
+    fs::path path = GetDataDir(true);
     if (!fs::exists(path)) {
         fs::create_directories(path / "wallets");
     }
@@ -492,7 +492,7 @@ bool ArgsManager::IsArgSet(const std::string& strArg) const
 
 bool ArgsManager::InitSettings(std::string& error)
 {
-    EnsureDataDir(/*net_specific=*/true);
+    EnsureDataDirNet();
     if (!GetSettingsPath()) {
         return true; // Do nothing if settings file disabled.
     }
diff --git a/src/util/system.h b/src/util/system.h
index 3bcbd5c8e..23c15228e 100644
--- a/src/util/system.h
+++ b/src/util/system.h
@@ -478,10 +478,8 @@ protected:
 
     /**
      * Create data directory if it doesn't exist
-     *
-     * @param net_specific Create a network-identified data directory
      */
-    void EnsureDataDir(bool net_specific);
+    void EnsureDataDirNet();
 
 private:
     /**
```
</details>

**Comment by fanquake** [comment]
Does/can this also close #16220?

**Comment by willcl-ark** [comment]
> Does/can this also close #16220?

I will check this out, specifically w.r.t this comment which I had not been considering:

> It would be, however the reason that wallets/ is not created when the .bitcoin directory already exists is backwards compatibility. If there is an existing datadir but no wallets directory it's assumed to be an old data directory, and creating wallets would effectively hide the existing wallets in the top level dir, possibly leading to people to suspect loss of funds.

**Comment by willcl-ark** [comment]
> I will check this out, specifically w.r.t this comment which I had not been considering:

I don't believe this fully closes the loop on #16220, but I am also not sure that we ever will close that fully whilst also providing backwards-compatibility...

There can exist currently two different working wallet configurations:

1. Legacy: wallets in subfolders in top-level, e.g. `~/.bitcoin/test-wallet/wallet.dat` or `~/.bitcoin/regtest/test-wallet/wallet.dat`
2. Current: wallets in wallets/ subfolder, e.g. `~/.bitcoin/wallets/test-wallet/wallet.dat` or `~/.bitcoin/regtest/wallets/test-wallet/wallet.dat`

The current init logic (preserved by this PR) is that we will check for the presence of `.bitcoin/` dir, and if it exists then use it as DataDir and take no further action. If it does not exist, then we will create it, **along with** a `wallets/` subdirectory. This allows old installs to continue without "disappearing wallets", as described by #16220.

Without implementing some brittle filesystem-checking code as laanwj described, I don't see this as really "fixable" (and probably that issue should be closed). One way of doing it could be to recursively check each subdir not called `wallets/` in the datadir for the presence of `*.dat` files, but I don't much like that idea.

----
sidenote: I notice in testing this that `loadwallet` RPC says that it can take a path to a `wallet.dat` file, to load the wallet, which I found not to work at all, whether or not the wallet was in a wallets/ subdir or not (and IIRC from another recent issue it is not supposed to work like this, so could do with helptext being updated):

https://github.com/bitcoin/bitcoin/blob/2c1fe27bf3c1e504864987cbe80f9c24897d3cb1/src/wallet/rpc/wallet.cpp#L203

<details>
<summary>Details</summary>

```fish
will@ubuntu in ~/src/bitcoin on  2022-02-cli-datadir [$⇕] via 🐍 v3.7.16
✗ /home/will/src/bitcoin/src/bitcoin-cli loadwallet ~/.bitcoin/test/wallet.dat
error code: -4
error message:
Wallet file verification failed. Invalid -wallet path '/home/will/.bitcoin/test/wallet.dat'. -wallet path should point to a directory where wallet.dat and database/log.?????????? files can be stored, a location where such a directory could be created, or (for backwards compatibility) the name of an existing data file in -walletdir ("/home/will/.bitcoin")

will@ubuntu in ~/src/bitcoin on  2022-02-cli-datadir [$⇕] via 🐍 v3.7.16

####
# Moved wallet from ~/.bitcoin/test/wallet.dat to ~/.bitcoin/wallet.dat
####

✗ /home/will/src/bitcoin/src/bitcoin-cli loadwallet ~/.bitcoin/wallet.dat
error code: -4
error message:
Wallet file verification failed. Invalid -wallet path '/home/will/.bitcoin/wallet.dat'. -wallet path should point to a directory where wallet.dat and database/log.?????????? files can be stored, a location where such a directory could be created, or (for backwards compatibility) the name of an existing data file in -walletdir ("/home/will/.bitcoin")
```

</details>

File: src/util/system.cpp (hunk 8 above)
Comment (willcl-ark) [reply src/util/system.cpp:446]: Now updated to `EnsureDataDirNet` which always creates the `wallets/` path if it's creating a new DataDir, but otherwise doesn't.

**Comment by willcl-ark** [comment]
I don't particularly want to feature-creep too much, but another adjacent issue is https://github.com/bitcoin/bitcoin/issues/19990

Which could potentially be addressed in this PR too if desired?

**Comment by ryanofsky** [comment]
I could be wrong, but the current version of this 41e9a810837b1c1eb497c2c22a6fa9873f379836 appears to change behavior by only creating the `<datadir>/<netdir>/wallets` directory, and no longer creating the `<datadir>/wallets` one level up if `<datadir>` did not exist.

This seems like a potentially bad thing, because if testnet or signet or regtest bitcoin is started mainnet bitcoin, mainnet wallets will go be created in `<datadir>` not `<datadir>/wallets` as intended. I think more ideally this PR would just refactor the code as desired without changing behavior.

**Comment by willcl-ark** [comment]
Thanks @ryanofsky that was unintentional and is now fixed. The only behaviour change is now in `bitcoin-cli`.

This does still leave us with the (undesirable) behaviour described in https://github.com/bitcoin/bitcoin/pull/27073#issuecomment-1429434184. It seems likely a likely flow that a user might download bitcoin core, create `bitcoin.conf` and then run the application, which results in *not* creating a `wallets/` subdir on mainnet (and technically other networks, but it's unlikely a new user would manually create those subdirectories). E.g. the following:

```fish
$ mkdir ~/.bitcoin
$ echo "all_my_settings" >> ~/.bitcoin/bitcoin.conf
$ bitcoind    # first run
$ find .bitcoin -type d
.bitcoin
.bitcoin/chainstate
.bitcoin/blocks
.bitcoin/blocks/index   # no wallets/ subdir created as datadir already existed

$ bitcoind -regtest
$ find .bitcoin -type d
.bitcoin
.bitcoin/chainstate
.bitcoin/regtest
.bitcoin/regtest/wallets    # created as regtest subdir did not already exist, even though datadir did
.bitcoin/regtest/chainstate
.bitcoin/regtest/blocks
.bitcoin/regtest/blocks/index
.bitcoin/blocks
.bitcoin/blocks/index
```

But I think this is something for a different PR to fix.

File: src/util/system.cpp [hunk 10]
```diff
@@ -973,8 +983,8 @@ bool ArgsManager::ReadConfigFiles(std::string& error, bool ignore_invalid_keys)
         m_config_sections.clear();
     }
 
-    const fs::path conf_path = GetPathArg("-conf", BITCOIN_CONF_FILENAME);
-    std::ifstream stream{GetConfigFile(conf_path)};
+    const auto conf_path{GetConfigFilePath()};
+    std::ifstream stream{conf_path};
```
Comment (hebasto) [inline src/util/system.cpp:987]: Why `GetConfigFile()` call dropped?

File: src/util/system.cpp [hunk 11]
```diff
@@ -965,6 +970,11 @@ bool ArgsManager::ReadConfigStream(std::istream& stream, const std::string& file
     return true;
 }
 
+fs::path ArgsManager::GetConfigFilePath()
+{
+    return GetConfigFile(GetPathArg("-conf", BITCOIN_CONF_FILENAME));
```
Comment (hebasto) [inline src/util/system.cpp:975]: The behavior has been slightly changed:

- on master:
```
$ ./src/qt/bitcoin-qt -regtest -conf=nothing
Error: Error reading configuration file: specified config file "nothing" could not be opened.

```

- this PR (6207b73e508d6cfc7583483d00261c66b0c348c3):
```
$ ./src/qt/bitcoin-qt -regtest -conf=nothing
Error: Error reading configuration file: specified config file "/home/hebasto/.bitcoin/nothing" could not be opened.

```

If it is intended, maybe document it?

Comment (willcl-ark) [reply src/util/system.cpp:975]: Right that's a good catch. We still _behave_ the same as previously, either fetching `conf` from an absolute path or completing the path with default datadir, but now because I simplified [reading the conf into a stream](https://github.com/bitcoin/bitcoin/pull/27073/commits/6207b73e508d6cfc7583483d00261c66b0c348c3#diff-19427b0dd1a791adc728c82e88f267751ba4f1c751e19262cac03cccd2822216L993), we return the full path we were trying in the error.

I agree that therefore there is a slight behaviour change, and personally I think this is more desirable than previously, where users were not told the absolute path the program was searching on for the config I would prefer to keep it this way, but not sure what documentation you would suggest adding in this case?

Comment (hebasto) [reply src/util/system.cpp:975]: > ... not sure what documentation you would suggest adding in this case?

The PR description? A commit message?

Comment (hebasto) [reply src/util/system.cpp:975]: I'm curious now, why functional tests did not catch this change?

Comment (willcl-ark) [reply src/util/system.cpp:975]: The reason is that we do not test relative `-conf=` arguments [here](https://github.com/bitcoin/bitcoin/blob/73966f75f67fb797163f0a766292a79d4b2c1b70/test/functional/feature_config_args.py#L287), even though we pass a realtive conf argument in.

This means that we are only testing the `os.path.join` sum of default `DataDir` and the relative arg.

**Review by ryanofsky — APPROVED** [review]
Light code review ACK 64b812e9a6df8fb4ec96b978a08dc9bde2ada2f0. I want to look a little more closely at this and test a little more to be sure it works as expected, but this seems like a very nice change. Avoids confusing side effect of functions like GetDataDirNet, AbsPathForConfigVal, and GetConfigFile creating directories in the background.

**Review by ryanofsky — APPROVED** [review]
Light code review ACK 64b812e9a6df8fb4ec96b978a08dc9bde2ada2f0. I want to look a little more closely at this and test a little more to be sure it works as expected, but this seems like a very nice change. Avoids confusing side effect of functions like GetDataDirNet, AbsPathForConfigVal, and GetConfigFile creating directories in the background.

**Comment by TheCharlatan** [comment]
Concept ACK

You can mark both `GetConfigFilePath` and `EnsureDataDir` as `const`.

**Comment by willcl-ark** [comment]
> Concept ACK
> 
> You can mark both `GetConfigFilePath` and `EnsureDataDir` as `const`.

Updated in 5626101

**Review by sedited — APPROVED** [review]
Code review ACK 0af17e161d751b15f90615800411f36e11b3fcde

**Review by hebasto — APPROVED** [review]
ACK 0af17e161d751b15f90615800411f36e11b3fcde, tested on Ubuntu 22.04.

> Fixes https://github.com/bitcoin/bitcoin/issues/20070

Confirming the `bitcoin-cli` does not create a data directory and its subdirectories.

I've noticed another behavior change which looks good for me:
- master:
```
$ ./src/bitcoind rubbish
Error: Command line contains unexpected token 'rubbish', see bitcoind -h for a list of options.

$ tree ~/.bitcoin
/home/hebasto/.bitcoin
└── wallets

1 directory, 0 files
```
- this PR (0af17e161d751b15f90615800411f36e11b3fcde):
```
$ ./src/bitcoind rubbish
Error: Command line contains unexpected token 'rubbish', see bitcoind -h for a list of options.

$ ls ~/.bitcoin
ls: cannot access '/home/hebasto/.bitcoin': No such file or directory
```

**Review by ryanofsky — APPROVED** [review]
Code review ACK 0af17e161d751b15f90615800411f36e11b3fcde. Nice change that makes initialization more straightforward and gets rid of strange behavior. Only change since last review is adding a comment. I left some small suggestions, but they are not important.

---

I think part of the PR description https://github.com/bitcoin/bitcoin/pull/27073#issue-1579684533 is inaccurate.

> As part of the refactoring it introduces a slight behaviour change to `GetConfigFilePath`, which now always returns the absolute path of the provided `-conf` argument, specifically when surfacing an error.

The `GetConfigFilePath()` function is a new function so it's behavior isn't changing. I think it would be more accurate to say "`ReadConfigFiles` behavior is changed to use the absolute path of the config file in error and warning messages instead of a relative path."

File: src/util/system.cpp (hunk 11 above)
Comment (willcl-ark) [reply src/util/system.cpp:975]: Closing as I think this is resolved

File: src/util/system.h [hunk 12]
```diff
@@ -475,6 +476,17 @@ class ArgsManager
      */
     void LogArgs() const;
 
+    /** If datadir does not exist, create it along with wallets/
```
[the remark this answers is not in the document]
Comment (willcl-ark) [reply src/util/system.h]: Updated in 56e370fbb9413260723c598048392219b1055ad0

**Review by hebasto — APPROVED** [review]
re-ACK 64c105442ce8c10900ea6fbecdbcfebe42f2d387, only comments have been adjusted as requsted since my previous [review](https://github.com/bitcoin/bitcoin/pull/27073#pullrequestreview-1307435890).

**Review by sedited — APPROVED** [review]
Re-ACK 64c105442ce8c10900ea6fbecdbcfebe42f2d387

**Comment by achow101** [comment]
ACK 64c105442ce8c10900ea6fbecdbcfebe42f2d387

**Review by ryanofsky — APPROVED** [review]
Code review ACK 64c105442ce8c10900ea6fbecdbcfebe42f2d387. Only comment changes since last review
